### ISSUE TITLE
Example code does not add worker nodes to cluster. kubectl get nodes shows no resources.

### ISSUE THREAD

**Issue by jknott-terraform** [terraform-aws-modules/terraform-aws-eks#1000]
# I have issues
After running the example code. kubectl get nodes shows no nodes added to the cluster. The configmap aws-auth is added with no problems. I deleted it and re-added it still no nodes.

NAMESPACE     NAME                                 DATA   AGE
kube-system   aws-auth                             3      8m21s
kube-system   coredns                              1      23m
kube-system   eks-certificates-controller          0      22m
kube-system   extension-apiserver-authentication   6      23m
kube-system   kube-proxy                           1      23m
kube-system   kube-proxy-config                    1      23m

## I'm submitting a...

* [X ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Run current example code with your own subnets and vpc id.
    data "aws_eks_cluster" "cluster" {
  name = module.my-cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.my-cluster.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "~> 1.9"
}

module "my-cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "my-cluster"
  cluster_version = "1.17"
  subnets         = ["subnet-0439457bd188a340f","subnet-08c03322bc056f489","subnet-06a93826b8f22c0d0"]
  vpc_id          = "vpc-03ed0604d97169a60"

  worker_groups = [
    {
      instance_type = "m4.large"
      key_name = "devopsclass"
      asg_min_size  = 3
      asg_desired_capacity = 3
      asg_max_size  = 5
    }
  ]
    }

## What's the expected behavior?
The nodes to be added to the cluster automatically.

## Environment details

The instances are tagged with the default tags from community module

* Affected module version:
* OS: Fedora
* Terraform version: 13.0

## Any other relevant info
Here are the logs from the nodes

Sep 03 18:05:36 ip-20-10-2-241.ec2.internal systemd[1]: Starting Kubernetes Kubelet...
Sep 03 18:05:36 ip-20-10-2-241.ec2.internal systemd[1]: Started Kubernetes Kubelet.
Sep 03 18:05:36 ip-20-10-2-241.ec2.internal kubelet[5189]: I0903 18:05:36.795873    5189 server.go:416] Version: v1.17.9-eks-4c6976
Sep 03 18:05:36 ip-20-10-2-241.ec2.internal kubelet[5189]: W0903 18:05:36.796192    5189 plugins.go:115] WARNING: aws built-in cloud provider is now deprecated. The AWS provider is deprecated and will be removed in a future release
Sep 03 18:05:36 ip-20-10-2-241.ec2.internal kubelet[5189]: I0903 18:05:36.796323    5189 aws.go:1241] Zone not specified in configuration file; querying AWS metadata service
Sep 03 18:05:36 ip-20-10-2-241.ec2.internal kubelet[5189]: I0903 18:05:36.798806    5189 aws.go:1281] Building AWS cloudprovider
Sep 03 18:07:37 ip-20-10-2-241.ec2.internal kubelet[5189]: F0903 18:07:37.093007    5189 server.go:273] failed to run Kubelet: could not init cloud provider "aws": error finding instance i-0f5ec363015f3e214: "error listing AWS instances: \"RequestError: send request failed\\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp 20.10.3.170:443: i/o timeout\""
Sep 03 18:07:37 ip-20-10-2-241.ec2.internal systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Sep 03 18:07:37 ip-20-10-2-241.ec2.internal systemd[1]: Unit kubelet.service entered failed state.
Sep 03 18:07:37 ip-20-10-2-241.ec2.internal systemd[1]: kubelet.service failed.
Sep 03 18:07:42 ip-20-10-2-241.ec2.internal systemd[1]: kubelet.service holdoff time over, scheduling restart.

**Comment by dpiddockcmp** [comment]
Looking at that log snippet the kubelet process is failing to reach the EC2 API service. This looks like a network level problem. Do the subnets you are using have internet access?

**Comment by jknott-terraform** [comment]
Thank you for your comment. I was using the community module and it locks down internet access by default. Thank you
