### ISSUE TITLE
worker_groups_launch_template with r6g instance family

### ISSUE THREAD

**Issue by abdennour** [terraform-aws-modules/terraform-aws-eks#1001]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Cannot create new autoscaling group. `Terraform apply` fails
## If this is a bug, how to reproduce? Please include a code sample if relevant.

- Having a cluster in `ap-southeast-1` AWS region.
- Updating the Terraform plan by updating the launch template with new group of instance type `r6g.large` 

```tf
  worker_groups_launch_template = [
    {
      name                 = "memory-optimized-group"
      instance_type        = "r6g.large"
      asg_desired_capacity = 2
      public_ip            = true
      asg_max_size = 3
      asg_min_size            = 2
      autoscaling_enabled = true
      root_volume_size = "30"
      root_volume_type = "gp2"
      ebs_optimized = false
      enable_monitoring = false
    }
```

- Run `terraform apply -auto-approve`

- Getting this error : 

```
  StatusMessage: "The requested configuration is currently not supported. Please check the documentation for supported configurations. Launching EC2 instance failed."
}

  on .terraform/modules/eks/terraform-aws-eks-12.0.0/workers_launch_template.tf line 3, in resource "aws_autoscaling_group" "workers_launch_template":
   3: resource "aws_autoscaling_group" "workers_launch_template" {
```

## What's the expected behavior?

I expected that this update will create a new autoscaling group and this autoscaling group 

## Are you able to fix this problem and submit a PR? Link here if you have already.
No 

## Environment details

* Affected module version: `12.0.0"`
* OS: `k8s 1.16`
* Terraform version: 

```
Terraform v0.12.28
+ provider.archive v1.3.0
+ provider.aws v2.70.0
+ provider.kubernetes v1.12.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.3.0
+ provider.template v2.1.2
```

## Any other relevant info

no

**Comment by daroga0002** [comment]
`r6g.large` instance is basing on Arm-based AWS Graviton2 processors, currently if you don`t specify custom AMI module is having filter:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1c8122704413fb3f54bff90b2692100def041caf/local.tf#L27-L30

and searching via:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1c8122704413fb3f54bff90b2692100def041caf/data.tf#L16-L41

currently this search returns something like 
```
ami = {
  "architecture" = "x86_64"
  "arn" = "arn:aws:ec2:us-east-1::image/ami-02a815c648e3ac746"
  "block_device_mappings" = [
    {
      "device_name" = "/dev/xvda"
      "ebs" = {
        "delete_on_termination" = "true"
        "encrypted" = "false"
        "iops" = "0"
        "snapshot_id" = "snap-02f8d592cc6106713"
        "volume_size" = "20"
        "volume_type" = "gp2"
      }
      "no_device" = ""
      "virtual_name" = ""
    },
  ]
  "creation_date" = "2020-09-04T10:44:47.000Z"
  "description" = "EKS Kubernetes Worker AMI with AmazonLinux2 image, (k8s: 1.17.9, docker:19.03.6ce-4.amzn2)"
  "filter" = [
    {
      "name" = "name"
      "values" = [
        "amazon-eks-node-1.17-*",
      ]
    },
  ]
  "hypervisor" = "xen"
  "id" = "ami-02a815c648e3ac746"
  "image_id" = "ami-02a815c648e3ac746"
  "image_location" = "amazon/amazon-eks-node-1.17-v20200904"
  "image_owner_alias" = "amazon"
  "image_type" = "machine"
  "most_recent" = true
  "name" = "amazon-eks-node-1.17-v20200904"
  "owner_id" = "602401143452"
  "owners" = [
    "602401143452",
  ]
  "product_codes" = []
  "public" = true
  "root_device_name" = "/dev/xvda"
  "root_device_type" = "ebs"
  "root_snapshot_id" = "snap-02f8d592cc6106713"
  "sriov_net_support" = "simple"
  "state" = "available"
  "state_reason" = {
    "code" = "UNSET"
    "message" = "UNSET"
  }
  "tags" = {}
  "virtualization_type" = "hvm"
}
```

which is dedicated for `x86_64` and not `arm64` architecture. In result your `r6g.large` instance cannot use this and module fail on EC2 API request.

To get this working you must specify `worker_ami_name_filter` in worker definition and put any of ARM supported AMI, for example:
`amazon-eks-arm64-node-1.17-*`

Also AWS EKS supported AMIs you can find them under https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html


I think that in general this can be also improved in module code to discover this automatically basing on  instance architecture, when I will find some time will take a look how this can be achieved.

**Comment by barryib** [comment]
Closing this since the answer sounds good. Feel free to re-open it doesn't help you.

**Comment by Type1J** [comment]
@barryib I think that this should be a 3rd filter. If the solution, as @daroga0002 presented is used, then all Linux nodes in the cluster will be required to be ARM64. In the case that it's desirable to have both x86_64 and ARM64 nodes in the same cluster, a third platform (`"linux-arm64"` maybe?) should be created. (The second platform is `"windows"`.)

Currently, the only solution to having both x86_64 and ARM64 nodes in a cluster is to specify the `ami_id` in the worker group, which requires a:
```teraform
data "aws_ami" "eks_worker_arm64" {
   filter {
     name   = "name"
     values = ["amazon-eks-arm64-node-1.17-*"]
   }

   most_recent = true

   owners = ["602401143452"] // The ID of the owner of the official AWS EKS AMIs.
} 
 ```
 This could be done in the module easily, and it already has been done for the `"windows"` platform.

**Comment by daroga0002** [comment]
I just shared a reason of issue, to solve this just extend your definition of wroker group:

```
worker_groups_launch_template = [
    {
      name                 = "memory-optimized-group"
      instance_type        = "r6g.large"
      ami_id = <<<<<<<<<<<<<<<< ami_id or even better can be data.aws_ami.eks_worker_arm64.id
      asg_desired_capacity = 2
      public_ip            = true
      asg_max_size = 3
      asg_min_size            = 2
      autoscaling_enabled = true
      root_volume_size = "30"
      root_volume_type = "gp2"
      ebs_optimized = false
      enable_monitoring = false
    }
]
    
    ```

**Comment by Type1J** [comment]
Yes, that was what I was saying that a user of the module needs to do, currently.

A default AMI selection is done for both Linux x86_64 and Windows x86_64 inside the module, which makes the module very easy to use.

I'm only proposing that a 3rd platform be added (`"linux_arm64"`), which would imply that the `data.aws_ami.eks_worker_arm64` would be inside the module, and used when `ami_id` is not specified.

**Comment by daroga0002** [comment]
I dont know how you can recognise intention of user and basing on what criteria decision should be made, but feel free to open a PR :)
