### ISSUE TITLE
source_dest_check not applied

### ISSUE THREAD

**Issue by lorand-plensys** [terraform-aws-modules/terraform-aws-eks#1008]
# I have issues

The source_dest_check (AWS: SrcDestCheck) on ec2 instance subnets are not applied to my setup, while I think this should be the default case. This is not externalized either. 

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

After a successful terraform apply, I have the eks up and running,  but when I check Source/Destination Check 
(https://docs.aws.amazon.com/vpc/latest/userguide/VPC_NAT_Instance.html#EIP_Disable_SrcDestCheck)
it is set to TRUE. 

## If this is a bug, how to reproduce? Please include a code sample if relevant.

I'm using the module with worker_groups_launch_template like this:
```
    {
      name                    = "spot-1"
      override_instance_types = ["m5.large", "m5a.large", "t3a.large", "m5ad.large"]
      spot_instance_pools     = 4
      asg_max_size            = 8
      asg_desired_capacity    = 3
      kubelet_extra_args      = "--node-labels=node.kubernetes.io/lifecycle=spot"
      public_ip               = true
      bootstrap_extra_args    = "--use-max-pods false"
      suspended_processes     = ["AZRebalance"]
    }
```
No, other worker group or template defined. 

## What's the expected behavior?

The source_dest_check should be FALSE. 

## Are you able to fix this problem and submit a PR? Link here if you have already.

No.

## Environment details

* Affected module version: 12.2.0
* OS: linux (manjaro)
* Terraform version: v0.13.1

**Comment by dpiddockcmp** [comment]
Source/Destination check is not configurable for auto scaling instances. It defaults to true. This is a limitation of the AWS API (ASG, Launch Template, Launch Configuration) and not something controllable by this module.

You might want to try doing something in the userdata script at start up. e.g.
```
aws ec2 modify-instance-attribute --instance-id i-1234567890abcdef0 --source-dest-check "{\"Value\": true}"
```

**Comment by lorand-plensys** [comment]
Thanks @dpiddockcmp , I was not aware of that.
