### ISSUE TITLE
health_check_type variable for worker groups

### ISSUE THREAD

**Issue by OzzieFZI** [terraform-aws-modules/terraform-aws-eks#1009]
## I'm submitting a query

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Not a bug

## What's the expected behavior?
Is there a variable to set the `health_check_type` for the worker group? It defaults to `EC2` while I would like to be able to set it to `ELB`. Or if there is any other way to do this while still using the module?

## Environment details

* Affected module version: 12.2.0
* OS: Ubuntu/Linux
* Terraform version: 0.13

Thanks in advance!

**Comment by barryib** [comment]
Nope, it doesn’t exist. But I'll happy to review your PR.

**Comment by svaranasi-traderev** [comment]
@barryib I have a PR.

**Comment by svaranasi-traderev** [comment]
I'm still waiting for someone to review my PR. Anyone?
