### ISSUE TITLE
module.eks.local_file.kubeconfig[0] will be created

### ISSUE THREAD

**Issue by wmcnamee-tunein** [terraform-aws-modules/terraform-aws-eks#1012]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?

It appears this always wants to be created. I'm not sure it's possible, but I'd like see `no changes` when nothing needs updating.

```
  # module.eks.local_file.kubeconfig[0] will be created
+ resource "local_file" "kubeconfig" {
```

## Environment details

* Affected module version: v12.2.0
* OS: ubuntu
* Terraform version: 0.13.2

**Comment by daroga0002** [comment]
does you are running this in some CI process where this file is removed after job run?

Usually this happens on some CI runs where checkout from git is done and file is not existing, then usually is worth to disable it via variable: `write_kubeconfig=false` if it is not required.

**Comment by ghostsquad** [comment]
ya, it's an ephemeral job, so `git clone` is literally done every time, and there's no state between runs. The kubeconfig file though is required if `manage_aws_auth=true` ?

**Comment by daroga0002** [comment]
nope, you can use following definition which is working on my code (omitted some code for clarity):
```
module eks_cluster {
  create_eks = var.eks_create
  # https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/12.2.0
  source          = "terraform-aws-modules/eks/aws"
  version         = "12.2.0"
  cluster_name    = "eks-${var.environment}"
................
  vpc_id          = module.vpc.vpc_id
  manage_aws_auth = true
  enable_irsa                          = true
  write_kubeconfig                     = false
...............
}

data aws_eks_cluster cluster {
  count = var.eks_create ? 1 : 0
  name  = module.eks_cluster.cluster_id
}

data aws_eks_cluster_auth cluster {
  count = var.eks_create ? 1 : 0
  name  = module.eks_cluster.cluster_id
}

provider kubernetes {
  host                   = element(concat(data.aws_eks_cluster.cluster[*].endpoint, list("")), 0)
  cluster_ca_certificate = base64decode(element(concat(data.aws_eks_cluster.cluster[*].certificate_authority.0.data, list("")), 0))
  token                  = element(concat(data.aws_eks_cluster_auth.cluster[*].token, list("")), 0)
  load_config_file       = false
  version                = "1.13.1"
}
```

**Comment by ghostsquad** [comment]
Score thanks!!

**Comment by barryib** [comment]
closing this, since it's the correct behavior. Please set `write_kubeconfig=false` if you don't need kubeconfig to be generated on your local disk.
