### ISSUE TITLE
Change in random_pet of worker_groups_launch_template causes corrupt Terraform state

### ISSUE THREAD

**Issue by pre** [terraform-aws-modules/terraform-aws-eks#1013]
# I have issues

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

I'm building on top of the [basic example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/basic/main.tf).

Changing `delete_on_termination` of a volume causes `random_pet` to generate a new value which causes Terraform to irrecoverably panic. Changing the value back to the original does not help - Terraform has already corrupted its state.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

I have replaced `worker_groups` with `worker_groups_launch_template` with the following:

```
  worker_groups_launch_template = [
    {
      name                          = "worker-group-1"
      instance_type                 = "t2.small"
      additional_userdata           = "echo foo bar lolcat"
      asg_desired_capacity          = 1
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_one.id]
    },
    {
      name                          = "storage-1"
      instance_type                 = "t2.medium"
      kubelet_extra_args            = "--node-labels=openebs.io/nodegroup=storage-node"
      additional_userdata           = "echo foo bar doge"
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_two.id]
      asg_desired_capacity          = 3
      asg_max_size                  = 3
      asg_min_size                  = 3
      additional_ebs_volumes = [
        {
          block_device_name     = "/dev/sdb"
          volume_size           = 98
          volume_type           = "gp2"
          encrypted             = false
          delete_on_termination = false
        }
      ]
    }
]
```

Everything works and applies correctly. No problem so far. 

Now, after the first `terraform apply`, if I change  `delete_on_termination = true` and execute `terraform apply` (second time), Terraform gets in trouble with the following output below. 

Changing the value back to `delete_on_termination = false` and calling `terraform apply` (third time) does not revert the issue. All subsequent `terraform apply` will fail with the same error. Only fix I have found is to set `worker_groups_launch_template = []` and recreate all the nodes and therefore reset the internal Terraform state. 

```
  [..]
  # module.eks.random_pet.workers_launch_template[1] must be replaced
+/- resource "random_pet" "workers_launch_template" {
      ~ id        = "sharing-unicorn" -> (known after apply)
      ~ keepers   = {
          - "lt_name" = "test-eks-terraform-storage-120200918074031349000000008-1"
        } -> (known after apply) # forces replacement
        length    = 2
        separator = "-"
    }

Plan: 1 to add, 1 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.eks.aws_launch_template.workers_launch_template[1]: Modifying... [id=lt-06c0a2cb3f70eec68]
module.eks.aws_launch_template.workers_launch_template[1]: Modifications complete after 1s [id=lt-06c0a2cb3f70eec68]

Error: Provider produced inconsistent final plan

When expanding the plan for module.eks.random_pet.workers_launch_template[1]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/random" changed the planned action from
CreateThenDelete to DeleteThenCreate.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

## What's the expected behavior?

Changing an immutable attribute or such would not cause `random_pet` to generate a new value.

## Environment details

* Affected module version: v12.2.0
* OS: MacOS 10.15.6
* Terraform version: 
```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
```

## Any other relevant info

Possibly add [lifecycle "ignore changes"](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) to random_pet ?

**Comment by dpiddockcmp** [comment]
Try using Terraform 0.13.3. There were fixes related to CreateThenDelete/DeleteThenCreate ordering and panics.

You can also try dropping the `random_pet` from your state file to try to recover from the mess:
`terraform state rm module.eks.random_pet.workers_launch_template[1]`

The `random_pet` is there to optionally force ASG recreation when a launch configuration/template value is changed, if you set `asg_recreate_on_change`. Its use is not recommended in production as it does horrid things to your cluster.

**Comment by pre** [comment]
Confirmed: Terraform v0.13.3 fixes this bug. 

Thanks for the tip of `asg_recreate_on_change` - sounds reasonable to disable that one in order to explicitly create a new ASG instead of implicitly recreating the existing one. I know of one case where worker nodes were accidentally deleted from the production cluster due to an innocent change in the autoscaling group's terraform. :)
