### ISSUE TITLE
Eks cluster module setting ASG target_group_arns to null

### ISSUE THREAD

**Issue by kkapoor1987** [terraform-aws-modules/terraform-aws-eks#1015]
# I have doubt related to lifecycle of ASG  

Currently, we have 

  lifecycle {
    create_before_destroy = true
    ignore_changes        = [desired_capacity]
  }
However, we see the issue where target_group_arns which are updated using tf autoscaling_attachment is being set back to null. 
Shouldn't module ignore it ? 

 ignore_changes        = [desired_capacity,target_group_arns ] if they are not passed for worker nodes?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_attachment

**Comment by muconsulting** [comment]
Hi, 

You can override _workers_group_defaults_ variable, and define target_group_arns  with your target groups you want to automatically attached to the worker pool [cf. ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf#L71) or if you want to attach it to a specific worker pool - simply define target_group_arns in the pool definition itself.

**Comment by barryib** [comment]
Please provide the `target_group_arns` to your workers groups to avoid that.

Closing this. Feel free to re-open it if needed.
