### ISSUE TITLE
template provider and template_file data source should be replaced with templatefile

### ISSUE THREAD

**Issue by mariadb-JeffBachtel** [terraform-aws-modules/terraform-aws-eks#1017]
# I have issues

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

The eks module requires the `template` provider as a dependency, but it is archived/deprecated, with the `templatefile` function replacing it (see https://registry.terraform.io/providers/hashicorp/template/latest/docs/data-sources/file)

## If this is a bug, how to reproduce? Please include a code sample if relevant.

`data "template_file"` is used in `data.tf`

## What's the expected behavior?

Using the more recent (as of 0.12) function instead

## Environment details

* Affected module version: `12.2.0`
* OS: Linux
* Terraform version: `0.13.3`

**Comment by barryib** [comment]
We can't use the templatefile function for now without breaking some use cases. See https://github.com/terraform-aws-modules/terraform-aws-eks/issues/882 for info.

Maybe https://github.com/hashicorp/terraform/pull/24978 could help to solve that. 👀

**Comment by mariadb-JeffBachtel** [comment]
lolsob, thanks :) Closing because there's not much you can do about this, apologies for missing previous work (I looked!)

**Comment by nick4fake** [comment]
@barryib unfortunately there are not other options as template provider is not going to support terraform 0.14.

https://github.com/hashicorp/terraform-provider-template/issues/85
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/761

**Comment by rekcah78** [comment]
Hi,
Still no solution ?

I have this issue with hashicorp/template :
Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.

**Comment by daroga0002** [comment]
> Hi,
> Still no solution ?

in v18 of this module we dont relly on that legacy provider so please update
