### ISSUE TITLE
`wait_for_cluster` not executed when cluster accessibility change

### ISSUE THREAD

**Issue by agaudreault-jive** [terraform-aws-modules/terraform-aws-eks#1018]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

I was changing the configuration of my cluster to use a private endpoint instead of a public one. Since I am running the terraform on my machine and not on the VPC, I have to use a "proxy" to be able to access my API server endpoint. 

When the cluster already exist and the endpoint becomes not accessible, the terraform will fail during the `apply` with a connection error on `module.eks.kubernetes_config_map.aws_auth[0]`. For some reason, the state of aws_auth was lost after that and terraform was trying to re-create the resource. I had to recover it with `terraform import module.eks.kubernetes_config_map.aws_auth[0] kube-system/aws-auth`.

## What's the expected behavior?

I think the `wait_for_cluster` resource should always be executed to check if the endpoint and health of the cluster is valid before trying to use the kubernetes provider. If not always, It should at least be tested when the accessibility of the cluster change (`cluster_endpoint_private_access`, `cluster_endpoint_private_access_cidrs`, `cluster_endpoint_public_access`, `cluster_endpoint_public_access_cidrs`).

## If this is a bug, how to reproduce? Please include a code sample if relevant.

1. Deploy cluster with public access.

2. Open a port forwarding so you can access the cluster with `ssh -M -fNL 8443:<existing_fqdn>:443 bastion` or similar.

3. Update cluster with private access.

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "v12.2.0"

  ...

  cluster_endpoint_public_access        = false
  cluster_endpoint_private_access       = true

  # Need to change $ENDPOINT to use the one we can access
  wait_for_cluster_cmd      = "for i in `seq 1 60`; do curl -k -s ${var.cluster_endpoint}/healthz >/dev/null && exit 0 || true; sleep 5; done; echo TIMEOUT && exit 1"
}

provider "kubernetes" {
  host             = var.cluster_endpoint
  token            = data.aws_eks_cluster_auth.cluster.token
  load_config_file = false
  insecure         = true
  version          = "~> 1.11"
}
```

4. Update cluster_endpoint 

```
cluster_endpoint = "https://localhost:8443"
```

5. Note that the `wait_for_cluster_cmd` is not executed again with or without the new endpoint.

## Are you able to fix this problem and submit a PR? Link here if you have already.

I think the [triggers](https://www.terraform.io/docs/provisioners/null_resource.html#triggers) could be used on the null_resource with a random value to always make sure the cluster is accessible and healthy or with the reference to the variable that might impact the cluster accessibility. 

## Environment details

* Affected module version: v12.2.0
* OS: MacOS
* Terraform version: 0.12.24

## Any other relevant info

It turns out you can deduce if the cluster endpoint is accessible or not during the `terraform plan`. If the plan detect that the `aws_auth` config map does not exist and needs to be created, that probably means your endpoint is not accessible and terraform was not able to contact the cluster to get the map.

**Comment by daroga0002** [comment]
I think that proposed `triggers` usage will always show a terraform plan changes and will always execute something during apply what in general is against whole idea and assumptions done by Terraform creators (it should apply changes only when there is real change in code)
