### ISSUE TITLE
Support for security groups for pods

### ISSUE THREAD

**Issue by stpierre** [terraform-aws-modules/terraform-aws-eks#1021]
# I have issues

## I'm submitting a...

* [ ] bug report
* [X] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

[Security groups for pods](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html) must be provisioned separately from this module.

TBH I'm not even sure how to do this with Terraform, which is why this is a feature request and not a PR. The main sticking point is step 3:

```
kubectl set env daemonset aws-node -n kube-system ENABLE_POD_ENI=true
```

I.e., you have to modify the environment for an already-running DaemonSet that is not managed by Terraform, but is created automatically by AWS.

**Comment by max-rocket-internet** [comment]
This is way out of the scope of this module. You can read about why in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/635 🙂

**Comment by stpierre** [comment]
Fair enough. Any thoughts about how this *could* be supported (i.e., in one of those smaller, composable modules discussed in #635)? Is `local_exec` (sadly) the way to go here?

**Comment by max-rocket-internet** [comment]
I don't think it's too complicated...

>  Is local_exec (sadly) the way to go here?

I don't think `local_exec` is ever the way to go 😅

I think most people are using Helm to manage resources inside the cluster, so looking at the AWS docs, this is how I would do it:

1. Do it in the [aws-vpc-cni chart](https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni)
2. Do it in TF, attach the policy to `module.cluster_iam_role_arn`
3. Do it in the [aws-vpc-cni chart](https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni)
4. In your application chart (or elsewhere)
5. In your application chart, add the `SecurityGroupPolicy` to the chart
6. This is just installing the chart

**Comment by stpierre** [comment]
Thanks!
