### ISSUE TITLE
Fallback support for spot instance

### ISSUE THREAD

**Issue by janavenkat** [terraform-aws-modules/terraform-aws-eks#1024]
# I have issues
Am trying to use spot instance but some-times instances doesn't startup because that spot instance not available in the region. Is there any option is available for fallback to on-demand instances when spot instance is not available?

# Tried Solution
Used mixed type spot instances

## I'm submitting a...

[ * ] bug report
[ * ] feature request

## What is the current behavior?
When the spot instance is not available in the region it doesn't fallback to on-demand instance 

## If this is a bug, how to reproduce? Please include a code sample if relevant.
It's kind a tricky, create spot instance with single instance type and then in aws will fill to launch the instance due to instance capacity 

## What's the expected behavior?
When spot instance is not available in the region it will be switched to on-demand instance

## Are you able to fix this problem and submit a PR? Link here if you have already.
No

## Environment details

* Affected module version: v12.2.0
* OS: Amazon AMI 
* Terraform version: 0.12.24

**Comment by max-rocket-internet** [comment]
You should use a selection of instance types to ensure the requests are always fulfilled. And you choose instances from here with low rate of termination: https://aws.amazon.com/ec2/spot/instance-advisor/

Apart from that, I don't really know of a way to say "use spot instances but fall back to on-demand", I think this functionality would probably have to be in the cluster-autoscaler but not sure.

**Comment by max-rocket-internet** [comment]
Also, FYI this issue has nothing to do with this module 🙂

**Comment by philomory** [comment]
@janavenkat, it _is_ possible to set up a fall back to on-demand instances, but it's down to the configuration of the cluster autoscaler, which is definitely out of scope for this module. You need to set up a [custom "expander" configuration](https://docs.giantswarm.io/guides/spot-instances-with-on-demand-fallback/), to start with. Then you usually want some other stuff to support it, like the [AWS Node Termination Handler](https://github.com/aws/aws-node-termination-handler) and the [K8S Spot Rescheduler](https://github.com/pusher/k8s-spot-rescheduler).

At least, that's what I've been able to figure out so far, myself; it's a fairly involved process and I've not personally finished trying it out.

In any case, yes, it's possible, but no, it's not really in scope for this Terraform module.

**Comment by janavenkat** [comment]
> @janavenkat, it _is_ possible to set up a fall back to on-demand instances, but it's down to the configuration of the cluster autoscaler, which is definitely out of scope for this module. You need to set up a [custom "expander" configuration](https://docs.giantswarm.io/guides/spot-instances-with-on-demand-fallback/), to start with. Then you usually want some other stuff to support it, like the [AWS Node Termination Handler](https://github.com/aws/aws-node-termination-handler) and the [K8S Spot Rescheduler](https://github.com/pusher/k8s-spot-rescheduler).
> 
> At least, that's what I've been able to figure out so far, myself; it's a fairly involved process and I've not personally finished trying it out.
> 
> In any case, yes, it's possible, but no, it's not really in scope for this Terraform module.

Yeah true indeed thanks for the information am using expander config in autoscaler with Node termination Handler. Thanks a lot for the explanation
