### ISSUE TITLE
Cut version for 0.13 support

### ISSUE THREAD

**Issue by sc250024** [terraform-aws-modules/terraform-aws-eks#1025]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [X] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## Request

This issue is simple: would it be possible to cut a release to have Terraform 0.13 support? @antonbabenko 's comment (https://github.com/terraform-aws-modules/terraform-aws-eks/issues/774#issuecomment-663362956) indicates not wanting to use Terraform 0.13 features, but I think we can at least do a minor release to make it so this is usable with Terraform 0.13?

**Comment by antonbabenko** [comment]
Hi @sc250024 !

My comment there was about using new features of Terraform such as validation for variables and usage of `depends_on` with modules.

Terraform 0.13.* is supported, but 0.13.0 is not supported because it had some important bug. You can still use this module with Terraform 0.13.1, 0.13.2, etc.

**Comment by sc250024** [comment]
> Hi @sc250024 !
> 
> My comment there was about using new features of Terraform such as validation for variables and usage of `depends_on` with modules.
> 
> Terraform 0.13.* is supported, but 0.13.0 is not supported because it had some important bug. You can still use this module with Terraform 0.13.1, 0.13.2, etc.

Yep. I was just wondering if the commit https://github.com/terraform-aws-modules/terraform-aws-eks/commit/bceb966dfd6f763ad8ea58764e8e84922848eca4 (and previous commits too) could be included in a potential `v12.3.0` release.

**Comment by barryib** [comment]
@sc250024 v13.0.0 is almost there https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1034
