### ISSUE TITLE
sonobuoy e2e tests are failing

### ISSUE THREAD

**Issue by pavdmyt** [terraform-aws-modules/terraform-aws-eks#1026]
# I have issues

Running [sonobuoy e2e tests](https://sonobuoy.io/docs/master/e2eplugin/) to check that created EKS cluster is properly set up is failing at the following test cases:

```
[sig-network] DNS | should provide DNS for pods for Hostname [LinuxOnly] [Conformance]
[sig-network] DNS | should provide DNS for pods for Subdomain [Conformance]
[sig-network] DNS │ should provide DNS for ExternalName services [Conformance]
[sig-network] Proxy version v1 | should proxy through a service and a pod  [Conformance]
[sig-cli] Kubectl client Update Demo | should scale a replication controller  [Conformance]
[sig-cli] Kubectl client Guestbook | application should create and stop a working application  [Conformance]
[sig-cli] Kubectl client Update Demo │ should create and stop a replication controller  [Conformance]
```

Detailed description for every test case can be found here: https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.yaml

If EKS cluster is created manually (via aws console) the abovementioned test cases are passing.

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## If this is a bug, how to reproduce? Please include a code sample if relevant.

I'm creating EKS cluster using this module as follows:

```
module "cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "v12.1.0"

  vpc_id  = local.vpc_id
  subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]

  cluster_name    = var.cluster_name
  cluster_version = "1.16"
  worker_groups   = var.worker_groups
  map_roles       = local.map_roles
  tags            = local.tags

  write_kubeconfig = false
}
```

Run failed tests using `--e2e-focus` to specify a specific test case:

```
# Example running test "should proxy through a service and a pod"
$ sonobuoy run --plugin=e2e --kube-conformance-image gcr.io/google-containers/conformance:v1.16.13 --e2e-focus="should proxy through a service and a pod"
```

Check test results:

```
$ sonobuoy status                                                                 
   PLUGIN     STATUS   RESULT   COUNT
      e2e   complete   failed       1

Sonobuoy has completed. Use `sonobuoy retrieve` to get results.
```

Get detailed test results:

```
results=$(sonobuoy retrieve)
tar -xzf $results
detailed-logs=$(find ./podlogs -type f -name e2e.txt)
cat $detailed-logs
```

## What's the expected behavior?

The expected behavior is that all conformance tests are passing successfully (EKS is a [certified k8s distribution](https://www.cncf.io/certification/software-conformance/)):

```
$ sonobuoy run --plugin=e2e --kube-conformance-image gcr.io/google-containers/conformance:v1.16.13
```

## Are you able to fix this problem and submit a PR? Link here if you have already.

Not yet. Still debugging particular cases.

## Environment details

* Affected module version: `v12.1.0`
* OS: `macOS Mojave 10.14.6 (18G6020)`
* Terraform version: `v0.12.24`

## Any other relevant info

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T19:10:21Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

$ sonobuoy version
Sonobuoy Version: v0.18.5
MinimumKubeVersion: 1.16.0
MaximumKubeVersion: 1.18.99
GitSHA: a79a43a99680f7274e6315dbf09fadc8fd81a6e0
API Version:  v1.16.13-eks-2ba888
```

**Comment by max-rocket-internet** [comment]
Not a huge amount of info in this issue but let us know if you work out why the tests are failing if they are solvable in this Terraform module 🙂

**Comment by pavdmyt** [comment]
I've reproduced the described issue using [v13.0.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v13.0.0) module and running _EKS v1.18_ (`GitVersion:"v1.18.8-eks-7c9bda"`). Below are details on the first five failing tests.

## test-01
Name: `should provide DNS for pods for Hostname`
Description: https://github.com/kubernetes/kubernetes/blob/release-1.18/test/conformance/testdata/conformance.yaml#L1427
Implementation: https://github.com/kubernetes/kubernetes/blob/release-1.18/test/e2e/network/dns.go#L244
Sonobuoy logs: https://github.com/pavdmyt/k8s-conformance/blob/master/eks/1.18/test-01/e2e.log

## test-02
Name: `should provide DNS for pods for Subdomain`
Description: https://github.com/kubernetes/kubernetes/blob/release-1.18/test/conformance/testdata/conformance.yaml#L1436
Implementation: https://github.com/kubernetes/kubernetes/blob/release-1.18/test/e2e/network/dns.go#L286
Sonobuoy logs: https://github.com/pavdmyt/k8s-conformance/blob/master/eks/1.18/test-02/e2e.log

## test-03
Name: `should provide DNS for ExternalName services`
Description: https://github.com/kubernetes/kubernetes/blob/release-1.18/test/conformance/testdata/conformance.yaml#L1419
Implementation: https://github.com/kubernetes/kubernetes/blob/release-1.18/test/e2e/network/dns.go#L329
Sonobuoy logs: https://github.com/pavdmyt/k8s-conformance/blob/master/eks/1.18/test-03/e2e.log

## test-04
Name: `should proxy through a service and a pod`
Description: https://github.com/kubernetes/kubernetes/blob/release-1.18/test/conformance/testdata/conformance.yaml#L1542
Implementation: https://github.com/kubernetes/kubernetes/blob/release-1.18/test/e2e/network/proxy.go#L87
Sonobuoy logs: https://github.com/pavdmyt/k8s-conformance/blob/master/eks/1.18/test-04/e2e.log

## test-05
name: `should scale a replication controller`
description: https://github.com/kubernetes/kubernetes/blob/release-1.18/test/conformance/testdata/conformance.yaml#L1403
implementation: https://github.com/kubernetes/kubernetes/blob/release-1.18/test/e2e/kubectl/kubectl.go#L293
sonobuoy logs: https://github.com/pavdmyt/k8s-conformance/blob/master/eks/1.18/test-05/e2e.log

**Comment by barryib** [comment]
@pavdmyt I don't really understand what you want to do. Are you testing this and sharing your results as info or you're waiting for something else ? Will you propose a PR to fix this ? Or even start a discussion to fix this ?

**Comment by pavdmyt** [comment]
@barryib I'm collecting details on this issue when possible and making some notes. Currently I cannot spend enough time to pinpoint the root cause of the issue. So, I'm returning to it from time to time. Meanwhile, it is possible that someone else who's facing the similar issue could find it and provide additional context.

Isn't GitHub a platform for sharing and collaboration?

**Comment by daroga0002** [comment]
I think you can try to update sonobuoy to newest version, I have run this over my EKS (v1.18) created with automation using this module in version 13.2.1  and all tests passed:

```
$ ./sonobuoy run --wait --kube-conformance-image-version=v1.18.9
INFO[0002] created object                                name=sonobuoy namespace= resource=namespaces
INFO[0002] created object                                name=sonobuoy-serviceaccount namespace=sonobuoy resource=serviceaccounts
INFO[0002] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterrolebindings
INFO[0002] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterroles
INFO[0002] created object                                name=sonobuoy-config-cm namespace=sonobuoy resource=configmaps
INFO[0003] created object                                name=sonobuoy-plugins-cm namespace=sonobuoy resource=configmaps
INFO[0003] created object                                name=sonobuoy namespace=sonobuoy resource=pods
INFO[0003] created object                                name=sonobuoy-aggregator namespace=sonobuoy resource=services
$./sonobuoy retrieve
202011161002_sonobuoy_0940a7b8-9647-49c3-a18c-9482d17e5678.tar.gz
$ ./sonobuoy results 202011161002_sonobuoy_0940a7b8-9647-49c3-a18c-9482d17e5678.tar.gz
Plugin: e2e
Status: passed
Total: 4993
Passed: 275
Failed: 0
Skipped: 4718

Plugin: systemd-logs
Status: passed
Total: 7
Passed: 7
Failed: 0
Skipped: 0
```

Particular mentioned test in issue:

```
$ ./sonobuoy run --wait --kube-conformance-image-version=v1.18.9 --e2e-focus="should proxy through a service and a pod" --plugin=e2e
INFO[0002] created object                                name=sonobuoy namespace= resource=namespaces
INFO[0002] created object                                name=sonobuoy-serviceaccount namespace=sonobuoy resource=serviceaccounts
INFO[0002] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterrolebindings
INFO[0002] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterroles
INFO[0002] created object                                name=sonobuoy-config-cm namespace=sonobuoy resource=configmaps
INFO[0003] created object                                name=sonobuoy-plugins-cm namespace=sonobuoy resource=configmaps
INFO[0003] created object                                name=sonobuoy namespace=sonobuoy resource=pods
INFO[0003] created object                                name=sonobuoy-aggregator namespace=sonobuoy resource=services
$ ./sonobuoy retrieve
202011161118_sonobuoy_05817509-e659-4c95-a4db-6a75dcae2501.tar.gz
$ ./sonobuoy results 202011161118_sonobuoy_05817509-e659-4c95-a4db-6a75dcae2501.tar.gz
Plugin: e2e
Status: passed
Total: 4993
Passed: 1
Failed: 0
Skipped: 4992
$
```


In general also sonobuoy is failing I would rather address issue to https://github.com/vmware-tanzu/sonobuoy as this module doesn't influence on kubernetes internal configuration which is checked by sonobuoy

**Comment by pavdmyt** [comment]
@daroga0002 Thanks for suggestion!

I was running with `sonobuoy v0.18.5`, will try `v0.19.0`. Also, another possible reason is that actual K8s version in EKS is `v1.18.8`, but for my recent tests the latest available tests image was `gcr.io/google-containers/conformance:v1.18.6`. I see you're already using `--kube-conformance-image-version=v1.18.9`, maybe it causes the difference.
