### ISSUE TITLE
Fix for AWS EKS “is not authorized to perform: iam:CreateServiceLinkedRole”

### ISSUE THREAD

**Issue by tonyxiao** [terraform-aws-modules/terraform-aws-eks#103]
## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

##

After deployingeks via this TF module in a brand new AWS account, the internet-facing k8s service I created could not create a load balancer. Turns out it's because this is a brand new AWS account and no ELB has been created in it before and the AWS user guide (as well as this module) assumes that `AWSServiceRoleForElasticLoadBalancing` already exists. 

https://stackoverflow.com/questions/51597410/aws-eks-is-not-authorized-to-perform-iamcreateservicelinkedrole

Recommend adding

```
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": "iam:CreateServiceLinkedRole",
                "Resource": "arn:aws:iam::*:role/aws-service-role/*"
            },
            {
                "Effect": "Allow",
                "Action": [
                    "ec2:DescribeAccountAttributes"
                ],
                "Resource": "*"
            }
        ]
    }
```
To the cluster role policy.

**Comment by max-rocket-internet** [comment]
Hi @tonyxiao, this is a known issue. Could you test the fix in the PR:
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/91
If it works, I think we will merge that.

**Comment by tonyxiao** [comment]
awesome, will test it again tomorrow

**Comment by max-rocket-internet** [comment]
All sorted @tonyxiao ?

**Comment by max-rocket-internet** [comment]
I'm gonna close this as I assume it's resolved. Just let us know if not 🙂
