### ISSUE TITLE
Unable to update the EKS cluster endpoint for an existing cluster

### ISSUE THREAD

**Issue by rushabh268** [terraform-aws-modules/terraform-aws-eks#1032]
## I'm submitting a...

* [X] bug report

## What is the current behavior?

So, I can create the EKS cluster as follows:

```
provider "kubernetes" {
  host = aws_eks_cluster.eks_test.endpoint
  load_config_file = false
}

resource "aws_eks_cluster" "eks_test" {
  name = "test-eks"
  version = var.k8s_version
  role_arn = var.arn

  vpc_config {
    subnet_ids = var.private_subnet_ids
    endpoint_private_access = true
  }
  enabled_cluster_log_types = var.eks_cw_logging

  depends_on = [
    aws_iam_role_policy_attachment.cluster-AmazonEKSClusterPolicy,
    aws_iam_role_policy_attachment.cluster-AmazonEKSServicePolicy,
  ]
}
```

After this cluster is created, the next script creates an aws-auth ConfigMap that allows the bastion host role to execute kubectl commands on the cluster

#### Note: I cannot set the endpoint_public_access = false when I create the cluster above because then I cannot add the aws-auth ConfigMap since it won't succeed as the terraform won't be run from within the VPC but from my Mac which is outside the VPC

Now, I want to be able to do something like:

```

resource "aws_eks_cluster" "eks_test" {
  name = "test-eks"
  id. = eks_test.this_cluster_id // This field is currently not there but maybe needed? 
  version = var.k8s_version
  role_arn = var.arn

  vpc_config {
    endpoint_public_access = true // This is what I want to update
  }
}
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

1. Create an EKS cluster without the endpoint_public_access flag in vpc_config
2. Try updating the same cluster with endpoint_public_access flag

## What's the expected behavior?

Ideally, I should be able to do this in a simple manner using Terraform because I can do it using this AWS CLI command 

```
aws eks update-cluster-config --name test-eks --resources-vpc-config endpointPublicAccess=false,endpointPrivateAccess=true

```

## Environment details

Kubernetes version: 1.17.9

* Affected module version:
hashicorp/aws: 3.8
hashiCorp/kubernetes: 1.13.2
* OS: MacOS
* Terraform version: 0.13.3

## Any other relevant info

I am trying to do everything using Terraform and update to an resource should be supported is my assumption - Maybe I don't know how to do it and if someone can show it - that'll be great!

**Comment by daroga0002** [comment]
I maybe not understand clearly your issue, but in general you must decide how you manage your cluster. If you want manage aws-auth via module with only private endpoint then module must be used from VPC where cluster is created, in other way you must make this public. 


To summarise you cannot achieve a way where from one side you making this cluster private (in VPC) and want to manage it from external network.

**Comment by barryib** [comment]
@rushabh268 are you using [this module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/12.2.0) to deploy your cluster ?

**Comment by rushabh268** [comment]
@daroga0002 Good point but here's the problem:

The EKS worker instances are part of the managed node group so we do not want any connectivity to them (no SSH etc.) and hence we cannot start with the endpoint as private because with the default ConfigMap, access to the EKS endpoint is only from the nodes and hence even if I create another instance in the same VPC (for ex. bastion) then that instance won't be able to access the EKS cluster API endpoint to update the ConfigMap because the default aws-auth won't allow that. 

Also, the issue with keeping the endpoint public is we don't want to expose the endpoint to 0.0.0.0/0 as that's a security issue. Also, we don't want to restrict the public endpoint to specific CIDRs since we want to allow communication to the EKS cluster API endpoint only via the bastion instance which is in the same VPC. And to allow the bastion instance to communicate with the EKS cluster API, we need to update the aws-auth ConfigMap.

So, it more like a chicken and egg problem. Does that help explain the problem I have?

@barryib No, I am not using the module but instead I am using [this](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster) resource

**Comment by barryib** [comment]
First of all, this repository is about [terraform-aws-eks module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/12.2.0) and not about the [terraform aws provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs). So I'm going to close your issue here.

To answer to your question, if you want to manage a private EKS cluster, you need to an access to the EKS private endpoint. This is possible from the network perspective if you're in the worker nodes vpc. But you need to have the right from IAM perspective to add/remove/update the EKS cluster and aws-auth configmap. See https://docs.aws.amazon.com/eks/latest/userguide/eks-networking.html and https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html for more details.

To bootstrap your cluster, you can write a Terraform script from scratch or use this community module (this is the quickest way).
