### ISSUE TITLE
Avoid inline policy for cluster_elb_sl_role_creation?

### ISSUE THREAD

**Issue by wlonkly** [terraform-aws-modules/terraform-aws-eks#1035]
## I'm submitting a...

* [X] bug report
* [X] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

The policy attached to the `cluster_elb_sl_role_creation` role ([here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/31ad394dbc61390dc46643b571249a2b670e9caa/cluster.tf#L161-L166) is an inline policy, which fails to apply in organizations that disable inline policies in an SCP, which is at least _somewhat_ common.

## What is the expected behavior? 

This policy should be a managed policy, like all the other policies this module creates.

## Are you able to fix this problem and submit a PR? Link here if you have already.

Able, yes -- but wanted to get your input before doing so.

## Environment details

* Affected module version: v12.2.0
* OS: Mac OS 10.14.6
* Terraform version: 0.13.4

**Comment by barryib** [comment]
Hello if there is a managed policy for that, I'll happy to review it.

**Comment by wlonkly** [comment]
Ah, sorry, I was imprecise -- a customer-managed policy (not AWS-managed), just not inline. PR incoming.
