### ISSUE TITLE
Unintended update when attaching an ELB to an ASG created by a worker launch template

### ISSUE THREAD

**Issue by jbdelpech** [terraform-aws-modules/terraform-aws-eks#1036]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
With aws provider >= 3.0.0, we got an issue when we use an aws_autoscaling_attachment to attach an ELB to an autoscaling group created by a worker launch template. Indeed, terraform wants to remove the load balancer reference from the asg.

E.g:
```
  # module.eks-cluster.aws_autoscaling_group.workers_launch_template[2] will be updated in-place
  ~ resource "aws_autoscaling_group" "workers_launch_template" {
        arn                       = "arn:aws:autoscaling:eu-west-1:****:autoScalingGroup:***:autoScalingGroupName/asg20200622150741236300000012"
       ...
        id                        = "asg20200622150741236300000012"
      ~ load_balancers            = [
          - "elb-name",
        ]

```

ASG (aws_autoscaling_group.workers_launch_template) is unintended updated to remove load-balancers. So it removes the asg load balancer attachment as well.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
* Create a new EKS cluster with a worker launch template
* Create an ELB
* Attach the ELB to the asg created by the worker launch template
```
resource "aws_autoscaling_attachment" "elb_asg_attachment" {
  autoscaling_group_name = module.eks-cluster.workers_asg_names[0]
  elb                    = aws_elb.my_elb.id
}
```

## What's the expected behavior?
As in AWS prodivder 2.x.x version : do not remove the elb from the asg.

## Are you able to fix this problem and submit a PR? Link here if you have already.
According to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_attachment, I guess that worker launch template lifecycle needs an update (ignore_changes = [load_balancers, target_group_arns]).
I made a local test with an update of "ignore_changes" lifecycle parameter, and it works as expected.

## Environment details

* Affected module version: 0.12.0 to 0.12.2
* OS:
* Terraform version: 0.12.24
* AWS provider version : 3.8.0

## Any other relevant info
I'll made a PR soon.

**Comment by barryib** [comment]
There is actually a PR to add a classic load balancer to the ASG https://github.com/terraform-aws-modules/terraform-aws-eks/pull/992.
