### ISSUE TITLE
Module doesn't work on eu-south-1

### ISSUE THREAD

**Issue by NaveLevi** [terraform-aws-modules/terraform-aws-eks#1037]
# I have issues using the module on eu-south-1 (Milan)

## I'm submitting a...

* [ ] bug report

## What is the current behavior?
When trying to use the module in eu-south-1, I get the following error:

"Error: Your query returned no results. Please change your search criteria and try again."
It works great with all other regions I've tried

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Use either example at:
terraform-aws-eks/examples/basic/
terraform-aws-eks/examples/managed_node_groups/
change region var value to eu-south-1, run 'terraform init; terraform apply' .

## What's the expected behavior?
I expect the module to create the resources in eu-south-1

## Are you able to fix this problem and submit a PR? Link here if you have already.
No

## Environment details

* Affected module version: v12.2.0
* OS: Ubuntu 20.04
* Terraform version:  v0.13.4

## Any other relevant info
This is a new region, terraform-provider-aws support as been added in May 
https://github.com/terraform-providers/terraform-provider-aws/issues/13063

This region has to be manually enabled on AWS, I've made sure it's enabled on my account and I'm able to create resources there using aws cli

**Comment by daroga0002** [comment]
what version of terraform you are using as I think this is related to that, not the module code

**Comment by NaveLevi** [comment]
> what version of terraform you are using as I think this is related to that, not the module code

v0.13.4, I've also tried with v0.12.29 and got the same results

**Comment by barryib** [comment]
What is your aws provider version ? It sounds like the issue you linked has been resolved in https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v2.60.0

**Comment by NaveLevi** [comment]
> What is your aws provider version ? It sounds like the issue you linked has been resolved in https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v2.60.0

"Using previously-installed hashicorp/aws v3.9.0"

**Comment by barryib** [comment]
It sounds like [Terraform](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/data.tf#L16-L25) can't find the optimized AMI for your region.

Can you please check if [these variables](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/variables.tf#L116-L138) are correctly setted for `eu-south-1` ?

**Comment by NaveLevi** [comment]
> It sounds like [Terraform](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/data.tf#L16-L25) can't find the optimized AMI for your region.
> 
> Can you please check if [these variables](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/variables.tf#L116-L138) are correctly setted for `eu-south-1` ? Specially `worker_ami_owner_id ` maybe the AMI owner is different for your region.

Yep, that's exactly it. 
The default ami owner id is not a good fit for eu-south-1, I've added:
worker_ami_owner_id = "590381155156" 
and it's working well.
Should I keep the issue open or close it? Do we want the module to identify that it's running on eu-south-1 and use worker_ami_owner_id = "590381155156" instead?

Thanks a lot!

**Comment by barryib** [comment]
Humm, we should find a way to ensure that the default filter always work without using "if/else" strategy. There are a lot of regions out there.

Does using the AWS alias (worker_ami_owner_id = "amazon") work for you ?

**Comment by NaveLevi** [comment]
> Humm, we should find a way to ensure that the default filter always work without using "if/else" strategy. There are a lot of regions out there.
> 
> Does using the AWS alias (`worker_ami_owner_id = "amazon"`) work for you ?
> 
> Or do we need to use the SSM data source to get the ami id https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html ?

`worker_ami_owner_id = "amazon"` works for me

**Comment by barryib** [comment]
Great. I just opened this PR https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1038 for this issue. Waiting for review.
