### ISSUE TITLE
Path varaiable is not set for resource "aws_iam_policy" "cluster_elb_sl_role_creation"

### ISSUE THREAD

**Issue by apothini** [terraform-aws-modules/terraform-aws-eks#1044]
# I have issues

we are trying to create a policy for a specified path
resource "aws_iam_policy" "cluster_elb_sl_role_creation" {
  count       = var.manage_cluster_iam_resources && var.create_eks ? 1 : 0
  name_prefix = "${var.cluster_name}-elb-sl-role-creation"
  description = "Permissions for EKS to create AWSServiceRoleForElasticLoadBalancing service-linked role"
  policy      = data.aws_iam_policy_document.cluster_elb_sl_role_creation[0].json
  path        = var.iam_path
}

## I'm submitting a...

* [x ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Failing on creation of policy due to IAM Path restriction

## What's the expected behavior?

Policy Not created

## Are you able to fix this problem and submit a PR? Link here if you have already.
addded iam_path variable
resource "aws_iam_policy" "cluster_elb_sl_role_creation" {
  count       = var.manage_cluster_iam_resources && var.create_eks ? 1 : 0
  name_prefix = "${var.cluster_name}-elb-sl-role-creation"
  description = "Permissions for EKS to create AWSServiceRoleForElasticLoadBalancing service-linked role"
  policy      = data.aws_iam_policy_document.cluster_elb_sl_role_creation[0].json
  **path        = var.iam_path**
}

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by barryib** [comment]
Can you please open a PR for this ?
