### ISSUE TITLE
Cannot destroy after eks provisioning fails if using enable_irsa=true

### ISSUE THREAD

**Issue by armsnyder** [terraform-aws-modules/terraform-aws-eks#1050]
# I have issues

EKS had a provisioning outage today, so after applying this module I ended with an EKS cluster with status=failed. I then did a `terraform destroy` and got this error message:

```
Error: "url" has to use HTTPS scheme (i.e. begin with https://)

  on .terraform/modules/eks/irsa.tf line 10, in resource "aws_iam_openid_connect_provider" "oidc_provider":
  10: resource "aws_iam_openid_connect_provider" "oidc_provider" {
```

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Destroying the module with `enable_irsa="true"`, where the EKS cluster status after apply is "failed", results in a Terraform error.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

`terraform apply` this Terraform config, and induce an EKS state of "failed" by for example using incorrect subnets.

```terraform
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "~> 13.0.0"
  cluster_version = "1.17"
  cluster_name    = "foo"
  subnets         = [] # redacted
  vpc_id          = "" # redacted
  enable_irsa     = true
}
```

`terraform destroy`

You should see this error during destroy:

```
Error: "url" has to use HTTPS scheme (i.e. begin with https://)

  on .terraform/modules/eks/irsa.tf line 10, in resource "aws_iam_openid_connect_provider" "oidc_provider":
  10: resource "aws_iam_openid_connect_provider" "oidc_provider" {
```

## What's the expected behavior?

Generally I want `terraform destroy` to always work. I would expect the `aws_iam_openid_connect_provider` resource to be conditional on the `aws_eks_cluster.this[*].identity[*].oidc.0.issuer` being empty, to handle cases where the EKS cluster was created but is in a failed state.

## Environment details

* Affected module version: 13.0.0
* OS: Mac Catalina
* Terraform version: 0.12.29

**Comment by barryib** [comment]
@armsnyder can you please open a PR for this ?

**Comment by armsnyder** [comment]
Can we reopen this issue please? We ran into this issue again, using v3.6.0 of the module.

**Comment by vrathore18** [comment]
Yes. please reopen this issue.

**Comment by narqo** [comment]
I have exactly this issue when trying to destroy the cluster, using `terraform-aws-modules/eks/aws` 13.2.1. Is there a known workaround for that?

**Comment by bryantbiggs** [comment]
unfortunately the module is quite a bit ahead of the versions listed here so I don't know what the benefit would be to re-open. if someone can confirm that the issue still persists on the latest version v17.6.0, then I'd be more than happy to re-open this
