### ISSUE TITLE
terraform-aws-eks import is failing

### ISSUE THREAD

**Issue by hashir91** [terraform-aws-modules/terraform-aws-eks#1054]
I am trying to use import "terraform-aws-eks" in my local project and I am seeing the following error when I build:

# github.com/terraform-aws-modules/terraform-aws-eks: module github.com/terraform-aws-modules/terraform-aws-eks@latest found (v13.0.0+incompatible), but does not contain package github.com/terraform-aws-modules/terraform-aws-eks

**Comment by barryib** [comment]
Without context, we can't help you. What do you mean by "import" ? Do you mean you want to use this module ? Did you try [examples](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples) and docs ? Did you `terraform init` ? What is your terraform and providers versions ?

**Comment by barryib** [comment]
Closing this. Feel free to re-open it you have more inputs.
