### ISSUE TITLE
release for v0.13.0 has requirement terraform != 0.13.0

### ISSUE THREAD

**Issue by aidan-melen** [terraform-aws-modules/terraform-aws-eks#1055]
This is probably just a bug in the docs but the release for v0.13.0 says in the [requirements section](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/v13.0.0#requirements) that the module explicitly does not support terraform != 0.13.0. What is wrong with 0.13.0 that breaks this module?

I have successfully launched a cluster with this module on terraform == v0.13.4

**Comment by barryib** [comment]
There are lot of issues with TF 0.13.0 https://github.com/terraform-aws-modules/terraform-aws-eks/pull/976.

So we don't support that specific version. Please use at least TF 0.13.4.

**Comment by aidan-melen** [comment]
Awesome, thanks for the clarification.
