### ISSUE TITLE
supports configurable Kubernetes service IP address range

### ISSUE THREAD

**Issue by yanivpaz** [terraform-aws-modules/terraform-aws-eks#1056]
## Feature request
support configurable Kubernetes service IP address range

## What is the current behavior?
[configurable Kubernetes service IP address range](https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-eks-supports-configurable-kubernetes-service-ip-address-range/)  is not supported 

## What is the expected behavior?
Support this feature ( for reference  CFN - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-cluster-kubernetesnetworkconfig.html ) 

## Are you able to fix this problem and submit a PR? Link here if you have already.
No

**Comment by barryib** [comment]
This feature is not available yet in the aws provider, but there is an ongoing issue/PR https://github.com/terraform-providers/terraform-provider-aws/issues/15505.

**Comment by etoews** [comment]
For visibility, the PR [Enhancement/eks adding service ipv4 range](https://github.com/hashicorp/terraform-provider-aws/pull/15518) has merge and been released in [v3.19.0](https://github.com/hashicorp/terraform-provider-aws/blob/v3.19.0/CHANGELOG.md) of the provider.
