### ISSUE TITLE
Create a resource group grouping cluster resources.

### ISSUE THREAD

**Issue by yrotilio** [terraform-aws-modules/terraform-aws-eks#1059]
## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

No Resource Group is created when a cluster EKS and its dependencies are created.

## What's the proposed behavior?

A Resource Group is created when needed. It groups the cluster EKS resources and their dependencies on the `kubernetes.io/cluster/<cluster_name>` tag , helping our friends from costing to measure how expensive each EKS cluster is.

**Comment by barryib** [comment]
Please use the `var. tags` to tag all your ressources . See docs for more details.

Closing this. Feel free to re-open if needed.
