### ISSUE TITLE
[Request] Support fixed names for resources

### ISSUE THREAD

**Issue by alexandrud** [terraform-aws-modules/terraform-aws-eks#1066]
## I'm submitting a

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

ASG and launch template names are suffixed with a random number because the module uses name_prefix. 

## What's the expected behavior?

Allow the user to choose between either name or name_prefix when creating the resources.

E.g.:
```
Current:
module.eks.aws_iam_instance_profile.workers_launch_template[0]: Creating... [id=my-launch-template-k8s20201026094407967700000010]

Desired:
module.eks.aws_iam_instance_profile.workers_launch_template[0]: Creating... [id=my-launch-template-k8s]
```

## Are you able to fix this problem and submit a PR? Link here if you have already.

I will try to make the change and submit a PR.

## Environment details

* Affected module version: 13.0.0
* OS: Debian Linux
* Terraform version: 0.13.5

**Comment by barryib** [comment]
Closing this as it duplicates https://github.com/terraform-aws-modules/terraform-aws-eks/issues/896.
