### ISSUE TITLE
LICENSE is not discovered

### ISSUE THREAD

**Issue by daroga0002** [terraform-aws-modules/terraform-aws-eks#1068]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

LICENSE file in github is not discovered properly.

![image](https://user-images.githubusercontent.com/20227477/97278579-3b7ab780-183a-11eb-91b2-c98d916ffb0f.png)

As this is Apache License 2.0 I suggest to update this by generic GitHub generated License file which will fix above badge and also add additional `feature` like summary of license:

![image](https://user-images.githubusercontent.com/20227477/97278855-8b597e80-183a-11eb-9bde-74171469acb1.png)

## If this is a bug, how to reproduce? Please include a code sample if relevant.

It is visible on master branch

## What's the expected behavior?

Badge should be showing 

![image](https://user-images.githubusercontent.com/20227477/97278942-a3c99900-183a-11eb-8d04-af2d5489dad3.png)

## Are you able to fix this problem and submit a PR? Link here if you have already.
yes, https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1069

## Environment details

* Affected module version: 13.0.0, 12.*
* OS: N/A
* Terraform version: N/A

**Comment by daroga0002** [comment]
Licenses and other metadata are managed by https://github.com/terraform-aws-modules/meta

**Comment by barryib** [comment]
@daroga0002 did you open the PR on https://github.com/terraform-aws-modules/meta ?

**Comment by daroga0002** [comment]
@barryib  sorry I was sick last week, I opened https://github.com/terraform-aws-modules/meta/pull/20

**Comment by barryib** [comment]
> @barryib  sorry I was sick last week, I opened https://github.com/terraform-aws-modules/meta/pull/20

Oups. In the meantime I opened a PR also ^^

**Comment by daroga0002** [comment]
I noticed after I pushed my, but no problem
