### ISSUE TITLE
not able to attach the IAM policy (worker_autoscaling) to cluster-autoscaler

### ISSUE THREAD

**Issue by vrathore18** [terraform-aws-modules/terraform-aws-eks#1070]
Hello, I am trying to add cluster autoscaling on my existing EKS. Currently, I am creating my EKS infra from terraform 

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "4.0.2"

  cluster_name = "${var.name}"
  subnets      = ["${module.vpc.private_subnets}"]
  vpc_id       = "${module.vpc.vpc_id}"
  cluster_version = "${var.cluster_version}"

  kubeconfig_aws_authenticator_additional_args = ["-r", "arn:aws:iam::${var.target_account_id}:role/terraform"]

  worker_groups = [
    {
      instance_type        = "${var.eks_instance_type}"
      asg_desired_capacity = "${var.eks_asg_desired_capacity}"
      asg_max_size         = "${var.eks_asg_max_size}"
      key_name             = "${var.key_name}"
    },
  ]

  # configure aws-iam-authenticator auth;
  #
  # by default only "admin" role from client's AWS account will have
  # access to the cluster (you'll need to assume that role in order 
  # interact with the cluster)
  map_accounts = ["${var.target_account_id}"]

  map_roles = [
    {
      role_arn = "${format("arn:aws:iam::%s:role/admin", var.target_account_id)}"
      username = "${format("%s-admin", var.name)}"
      group    = "system:masters"
    },
  ]

  map_accounts_count = "1"
  map_roles_count    = "1"

  # don't write local configs, as we do it anyway
  write_kubeconfig      = "false"
  write_aws_auth_config = "false"
}

resource "local_file" "kubeconfig" {
  content  = "${module.eks.kubeconfig}"
  filename = "./.kube_config.yaml"
}
```

I have read this documentation(It was not clear):
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/autoscaling.md

But I am confused on some part:

1. where and how I am going to use the newly created policy i.e worker_autoscaling
2. how cluster-autoscaler is having the access to expand and reduce my worker node? and where is the metric define for it?

**Comment by barryib** [comment]
You have to enable IRSA (IAM Role for Service Account). See https://aws.amazon.com/fr/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/ for more info.

You can enable IRSA during the EKS deployment by setting `enable_irsa = true`.

I don't know which version of Terraform you're using, but you should consider upgrading your terraform-aws-eks module to the latest version (13.0.0). Furthermore, it sounds like you're are using Terraform 0.11. If yes, please upgrade to at least TF 0.12 (even better TF 0.13). We don't do any kind of support for TF 0.11.

**Comment by barryib** [comment]
See also docs https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/autoscaling.md

**Comment by barryib** [comment]
Without feedback, I'm closing this PR. Feel free to re-open it if you need.
