### ISSUE TITLE
`Usage Example` breaks during cluster upgrades

### ISSUE THREAD

**Issue by dcherman** [terraform-aws-modules/terraform-aws-eks#1072]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Resources that use the Kubernetes provider from the example (including the aws-auth configmap in the module) will fail to be modified after a control plane upgrade with the following (or similar) error:

`Error: Failed to update Config Map: Unauthorized`

Right now, the recommended/example way to set use this module per the README is as follows:

```hcl
data "aws_eks_cluster" "cluster" {
  name = module.my-cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.my-cluster.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "~> 1.9"
}

module "my-cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "my-cluster"
  cluster_version = "1.17"
}
```

Note that the two data sources are dependent on outputs from the module.  During the first creation of the module, the dependency chain will look something like this:

![image](https://user-images.githubusercontent.com/976608/97468906-29714580-191c-11eb-947c-15fbc638d67a.png)

                           
After the first creation of the module, that output is well-known and does not change during a cluster upgrade, so it seems like Terraform will allow the data sources to be read/updated before the cluster upgrade happens.  That results in a graph that looks more like the following

![image](https://user-images.githubusercontent.com/976608/97469201-840aa180-191c-11eb-8664-924122bd2510.png)

The problem that seems to be twofold:

1.  When a cluster upgrade does occur, it looks like tokens generated against the old control plane are no longer valid.  I tested this by requesting and storing a token locally, then modifying a copy of the kubeconfig to use it explicitly.  With time still left before the expiration, I received `You must be logged in to the server (Unauthorized)` when trying to access the cluster after the control plane was upgraded.  I'm not sure if this is a bug with EKS/AWS.

2. Since a cluster upgrade takes an extraordinarily long time (30m+), the token that was fetched in the datasource would have expired since they seem to have a lifetime of ~15m.  That means that even in the absence of the problem described above, modifying the config map would *still* fail.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Create a kubernetes cluster following the example, then upgrade the control plane while modifying the aws-auth configmap to add a role.  Observe that the configmap modification fails with the following error:

`Error: Failed to update Config Map: Unauthorized`

## What's the expected behavior?

The ConfigMap should be updated.

## Environment details

* Affected module version: 12.1.0
* OS: OSX 
* Terraform version: 0.12.29

**Comment by dcherman** [comment]
My current workaround that I just implemented is the following, though it creates a dependency on the aws cli:

```hcl
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  load_config_file       = false

  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    command = "aws"
    args = ["eks", "get-token", "--cluster-name", "${module.eks.cluster_id}"]
  }
}
```

**Comment by dzirg44** [comment]
@dcherman I have the same issue and it seems that after update some autoscaling  node groups cannot connect to the cluster due to authorization  error (((. Also terraform is trying to create new aws_auth kubernetes resource. It happens always after update, i am going to increase `duration_seconds` for  cluster IAM roles but I am not sure , that the problem is here(

**Comment by dcherman** [comment]
@dzirg44 Are you using managed nodegroups?  If so, I've experienced similar problems.

**Comment by barryib** [comment]
Are you experiencing this with the latest version of this module or with `v12.2.0` ?

**Comment by dcherman** [comment]
@barryib In my case, `v12.1.0`, however in looking at the example I believe the latest version would have this issue as well.  I haven't upgraded yet since I think I had a problem w/ cycles last time I tried; haven't revisited that yet.

**Comment by barryib** [comment]
In v12.2.0 we improved dependences management for managed node group https://github.com/terraform-aws-modules/terraform-aws-eks/pull/867. I was wondering if this solves your issue.
