### ISSUE TITLE
Running terraform plan I get an error with module.eks.aws_iam_role_policy.cluster_elb_sl_role_creation[0]

### ISSUE THREAD

**Issue by ado120** [terraform-aws-modules/terraform-aws-eks#1078]
# I have issues

## I'm submitting a...

* [* ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Haven't ran terraform plan in awhile with an eks cluster that was spun up using the eks module. Now everytime I run a terraform plan I get this:

To work with module.eks.aws_iam_role_policy.cluster_elb_sl_role_creation[0]
its original provider configuration at provider["registry.terraform.io/-/aws"]
is required, but it has been removed. This occurs when a provider
configuration is removed while objects created by that provider still exist in
the state. Re-add the provider configuration to destroy
module.eks.aws_iam_role_policy.cluster_elb_sl_role_creation[0], after which
you can remove the provider configuration again.

## What's the expected behavior?
Terraform plan should work

Anyone have any ideas?

**Comment by antonLebiedyntsev** [comment]
same 
Error: Invalid index

  on ../modules/terraform-aws-eks/cluster.tf line 171, in resource "aws_iam_role_policy_attachment" "cluster_elb_sl_role_creation":
 171:   policy_arn = aws_iam_policy.cluster_elb_sl_role_creation[0].arn
    |----------------
    | aws_iam_policy.cluster_elb_sl_role_creation is empty tuple

The given key does not identify an element in this collection value.

**Comment by antonLebiedyntsev** [comment]
upgraded terraform version 0.13.5 vorked

**Comment by ado120** [comment]
> upgraded terraform version 0.13.5 worked

I upgraded my terraform to .13.5 and still not working :( Did you try anything else?

**Comment by emerson-h** [comment]
Running `terraform state replace-provider registry.terraform.io/-/aws registry.terraform.io/hashicorp/aws` should resolve this issue

**Comment by ado120** [comment]
@emerson-h Thank you Emerson! This seems to have fixed my issue. What went wrong here and why was this the fix?

**Comment by barryib** [comment]
Great. If it's ok, feel free to close this issue.

**Comment by ado120** [comment]
@barryib yes Barry it's fixed now, although I would like to understand a bit more on why this went wrong and why I had to replace the provider in state?

**Comment by barryib** [comment]
This has been introduce in TF 0.13. Providers now have an explicit source location. The provider `registry.terraform.io/-/aws` in TF 0.12 is now under `registry.terraform.io/hashicorp/aws` namespace in TF 0.13. See https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations for more info.

**Comment by ado120** [comment]
Thank you so much for all of your help @barryib. Closing out this issue
