### ISSUE TITLE
[bug] IRSA example login errors

### ISSUE THREAD

**Issue by Justin-DynamicD** [terraform-aws-modules/terraform-aws-eks#1083]
the example deployment outlined here:
https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/irsa

I could not get this example to function in my testing, running into IAM permissions issues.

While the role and permissions appear to get created properly, after modifying and apply the helm chart, the resulting auto-scaler service gets stuck in a crash loop stating access denied and declaring it did not have the nessisary permissions. to perform the action, failing imediately citing lack of sts:AssumeRoleWithWebIdentity permissions (verified this is set in the trust relationship of the default "cluster-autoscaler" role"

The only variations made was I updated the cluster to 1.18, and set the image version accordingly in the helm chart.

After struggling with this, I fell back on [AWS documentation](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html) and applied permissions directly to the EC2 roles generated by the module and the service started perfectly.

I feel like there is some step missing here Im unaware of, in order to use the endpoint?

My actual module call is below, tags remvoed:

```
module "eks" {
  source           = "terraform-aws-modules/eks/aws"
  cluster_name     = local.cluster_name
  cluster_version  = "1.18"
  subnets          = data.terraform_remote_state.network.outputs.private_subnets
  write_kubeconfig = false
  vpc_id           = data.terraform_remote_state.network.outputs.vpc_id
  enable_irsa      = true
  worker_groups = [
    {
      name                 = "default_workers"
      instance_type        = "t2.medium"
      asg_max_size         = 1
      platform             = "linux"
      kubelet_extra_args   = "--node-labels=spot=false"
      suspended_processes  = ["AZRebalance"]
      tags = [
        {
          "key"                 = "k8s.io/cluster-autoscaler/enabled"
          "propagate_at_launch" = "false"
          "value"               = "true"
        },
        {
          "key"                 = "k8s.io/cluster-autoscaler/${local.cluster_name}"
          "propagate_at_launch" = "false"
          "value"               = "true"
        }
      ]
    },
    {
      name                 = "win_workers"
      instance_type        = "t2.small"
      asg_desired_capacity = 1
      asg_max_size         = 2
      platform             = "windows"
    }
  ]

  worker_groups_launch_template = [
    {
      name                    = "nix_spot"
      override_instance_types = ["t3.medium", "t3.large"]
      spot_instance_pools     = 2
      asg_max_size            = 5
      platform                = "linux"
      kubelet_extra_args      = "--node-labels=kubernetes.io/lifecycle=spot"
      public_ip               = false
      autoscaling_enabled     = true
      protect_from_scale_in   = true
  ]
  map_accounts = []
  map_roles    = []
  map_users    = var.eks_users
}
```

**Comment by barryib** [comment]
@Justin-DynamicD which version of this module are you using ?

Are you using the terraform-aws-`modules/iam/aws//modules/iam-assumable-role-with-oidc` to define the IAM role with OIDC like in the [example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa/irsa.tf#L1-L9) ? If yes, can you please test it with the latest version of that module please.

```hcl
module "iam_assumable_role_admin" {
  source                        = "terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc"
  version                       = "~> v3.0"
  create_role                   = true
  role_name                     = "cluster-autoscaler"
  provider_url                  = replace(module.eks.cluster_oidc_issuer_url, "https://", "")
  role_policy_arns              = [aws_iam_policy.cluster_autoscaler.arn]
  oidc_fully_qualified_subjects = ["system:serviceaccount:${local.k8s_service_account_namespace}:${local.k8s_service_account_name}"]
}

```

**Comment by Justin-DynamicD** [comment]
I am, but I'm using it -as-is from the example page linked, meaning its at 2.14.0.  Ill retry off hours and let you know how it behaves, thanks for the tip!

**Comment by Justin-DynamicD** [comment]
no dice, sadly.  I did not completely destroy, just deleted the old deployment then tried hte helm chart again:

```
E1104 02:50:42.813416       1 aws_manager.go:265] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
        status code: 403, request id: 919c3b67-0021-4543-8545-020c36371246
F1104 02:50:42.813448       1 aws_cloud_provider.go:382] Failed to create AWS Manager: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
        status code: 403, request id: 919c3b67-0021-4543-8545-020c36371246
```

Im at a loss.  I guess Ill just fall back on applying the permissions to the worker role for now as I honeslty have no idea where to begin to troubleshoot this feature.

**Comment by barryib** [comment]
My point here https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1083#issuecomment-721360729 is to update the IAM role for oidc version constraint and terraform apply again to see if it create your assumable role correctly.

**Comment by Justin-DynamicD** [comment]
Sorry if I was not clear. Here's what I did to the environment:

1. updated the version constraint like you asked and ran a new terraform apply.
2. removed the old auto-scaler deployment (kubectl delete [...]).
3. updated settings.yaml and verified the arn matched what was displayed in IAM for said role.
4. deployed the autoscaler with helm as per the README.
4. pulled the resulting logs, noticed I was still getting the 403, and reverted back to using the "old" method outlined [here](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html) which doesn't use helm to deploy but also relies on the local EC2 role for it's permissions, which works perfectly.

My problem is I I honestly dont understand how IRSA works at all, so I dont even know where to look to verify the deployment is trying to hit the right endpoint, using right creds, etc.  I was hoping this template would get me a fast running example so I could see a "functioning" cluster, but I jsut seem to have hit a brick wall.

**Comment by Justin-DynamicD** [comment]
Slight update: from reading the docs it would appear that there should be an annotaed service account present, but I don't see one, nor do I see anything in terraform that would create one (though in the locals you seem to deifne something that doesn get called).  Is the helm plan supposed ot create that?

**Comment by barryib** [comment]
It sounds like your helm chart doesn't create correct annotation for your service account. Are you using defining helm values like this https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa/cluster-autoscaler-chart-values.yaml#L5-L7 ?

```yaml
rbac:
  create: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::<ACCOUNT ID>:role/cluster-autoscaler"
````

We updated the doc yesterday https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1063

**Comment by brannondorsey** [comment]
I'm experiencing this exact same issue. I've confirmed the annotation is applied to the service account as mentioned above, and that it points to the ARN identified in [this role](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa/irsa.tf#L5).

**Comment by Justin-DynamicD** [comment]
well I'm glad im not crazy/the only one not seeing this work?

I did modify the heml chart yaml.  As I am running eks 1.18, I updated the file to the following:

```
awsRegion: us-west-2

rbac:
  create: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::<redacted>:role/cluster-autoscaler"

autoDiscovery:
  clusterName: <my cluster name>
  enabled: true

image:
  repository: us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler
  tag: v1.18.3
```

**Comment by Justin-DynamicD** [comment]
should this line be updated?

[servicename](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/fc40053c0cf3097c243e61866e505b51abdf6bb4/examples/irsa/locals.tf#L4)

Not certain why it's set as "cluster-autoscaler-aws-cluster-autoscaler" whereas the aws role is simply "cluster-autoscaler". Again, I appologize if im blindly poking at  the wrong things, I'm really just trying to look for gaps.

**Comment by brannondorsey** [comment]
[This comment](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/801#issuecomment-696733518) tipped me off to the solution. It appears that [the latest](https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler-chart) cluster-autoscaler helm chart creates a service account named `cluster-autoscaler-aws-cluster-autoscaler-chart` instead of `cluster-autoscaler-aws-cluster-autoscaler` which the [irsa example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1e4a908a951bd1b819b2761736dabb8875d6d765/examples/irsa/locals.tf#L4) expects.

@Justin-DynamicD are you using the helm chart from the new https://kubernetes.github.io/autoscaler helm repo or [the deprecated](https://github.com/helm/charts/tree/master/stable/cluster-autoscaler) `stable/charts` repo one linked from the irsa example README? If it's the former (like me), that will updating the `locals.k8s_service_account_name` to  `cluster-autoscaler-aws-cluster-autoscaler-chart` should solve the issue.

Perhaps we should update the irsa example README to link to the new helm chart and update `locals.k8s_service_account_name` to match.

**Comment by brannondorsey** [comment]
Somewhat ironically, updating the `iam_assumable_role_admin` to version `~> v3.0` [instead of version 2.14.0](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa/irsa.tf#L3) as @barryib suggested in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1083#issuecomment-721360729 actually introduced a problem, as terraform removes the required role <> policy attachment for some reason.

<img width="879" alt="Screen Shot 2020-11-05 at 11 04 00 AM" src="https://user-images.githubusercontent.com/3193533/98272208-d53f1480-1f5e-11eb-804d-7e11b7ecf0ee.png">

By using 2.14.0 instead I got this working with the solution in my previous comment.

**Comment by Justin-DynamicD** [comment]
can confirm: v3 does remove a role as well:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.iam_assumable_role_admin.aws_iam_role_policy_attachment.custom[0] will be created
  + resource "aws_iam_role_policy_attachment" "custom" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::<redacted>:policy/cluster-autoscaler20201103041508874900000018"
      + role       = "cluster-autoscaler"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

I think you unlocked pandoras box for me. Seems like i should have either used the deprecated autoscaler or dug into helm deeper.

**Comment by Justin-DynamicD** [comment]
Confirming the issue was the newer auto-scaler excpets a different name.

**Comment by barryib** [comment]
To avoid this, shouldn't we set a service account name for the cluster autoscaler https://github.com/helm/charts/blob/master/stable/cluster-autoscaler/values.yaml#L121 ?

**Comment by barryib** [comment]
> Somewhat ironically, updating the `iam_assumable_role_admin` to version `~> v3.0` [instead of version 2.14.0](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa/irsa.tf#L3) as @barryib suggested in [#1083 (comment)](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1083#issuecomment-721360729) actually introduced a problem, as terraform removes the required role <> policy attachment for some reason.
> 
> <img alt="Screen Shot 2020-11-05 at 11 04 00 AM" width="879" src="https://user-images.githubusercontent.com/3193533/98272208-d53f1480-1f5e-11eb-804d-7e11b7ecf0ee.png">
> 
> By using 2.14.0 instead I got this working with the solution in my previous comment.

Thanks for sharing this. I'll take a look as soon as I have a moment.

**Comment by brannondorsey** [comment]
> To avoid this, shouldn't we set a service account name for the cluster autoscaler https://github.com/helm/charts/blob/master/stable/cluster-autoscaler/values.yaml#L121 ?

Yep, that works too. Although I think it actually makes more sense to update `local.k8s_service_account_name` in `locals.tf` instead given that the README now recommends using the new helm chart (hosted at https://kubernetes.github.io/autoscaler) instead of the deprecated one. 

I've opened a PR #1090 with these changes as well as a few other fixes in the IRSA README.

**Comment by barryib** [comment]
Great. Thanks for opening a PR for this. And yes, we should update the example to use the recommended helm chart.

With that said, in production environment, I think it better to be explicit for these kind of change instead of trying to always create something that should match the chart default. Defaults will change during upgrades and you'll noticed most of the time when it's too late.

This only engages me, but to me we should also [set explicitly the autoscaler service account name](https://github.com/helm/charts/blob/master/stable/cluster-autoscaler/values.yaml#L121) to always match with `local.k8s_service_account_name`.

What do you think ?

**Comment by brannondorsey** [comment]
> With that said, in production environment, I think it better to be explicit for these kind of change instead of trying to always create something that should match the chart default. Defaults will change during upgrades and you'll noticed most of the time when it's too late.

Yeah, that's a good point. If this relationship had been more specific to begin with, it might not have been such a mystery as to what was going wrong here to begin with. I've updated the PR to explicitly set the `rbac.serviceAccount.name` in `cluster-autoscaler-chart-values.yaml` and added a code comment about this relationship in this commit
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1090/commits/1e04a4a3498626fd059c7f3d27b0e04ae25f53b3.
