### ISSUE TITLE
Update existing labels and taints of existing worker groups

### ISSUE THREAD

**Issue by PeteMac88** [terraform-aws-modules/terraform-aws-eks#1085]
# I have issues

Hey there,
i have an issue to update existing nodes with node labels and taints. The labels and taints are added to a node when add new worker group to our cluster but not if I am editing the `kubelet_extra_args` values of existing worker groups. Is this not possible or is this a bug?

Here is the snippet of our terraform code:

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = var.cluster_name
  subnets         = module.vpc.private_subnets
  cluster_version = var.cluster_version
  vpc_id          = module.vpc.vpc_id
  worker_groups = [
    for wg in var.worker_groups : {
      name                          = wg.name
      instance_type                 = wg.instance_type
      asg_desired_capacity          = wg.desired_capacity
      asg_min_size                  = wg.min_capacity
      asg_max_size                  = wg.max_capacity
      additional_security_group_ids = [aws_security_group.security_groups[wg.security_group_prefix].id]
      kubelet_extra_args            = wg.kubelet_extra_args
      tags = [
        {
          key                 = "k8s.io/cluster-autoscaler/enabled"
          propagate_at_launch = "false"
          value               = "true"
        },
        {
          key                 = "k8s.io/cluster-autoscaler/${var.cluster_name}"
          propagate_at_launch = "false"
          value               = "true"
        }
      ]
    }
  ]
  write_kubeconfig = var.eks_write_kubeconfig
  map_users        = var.map_users
  enable_irsa      = true
}
```
Help appreciated. Best regards

Peter

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## Environment details

* Affected module version: latest
* OS:
* Terraform version: v0.13.4

## Any other relevant info

We are using terraform cloud to keep our cluster state in sync and at best i want to changes to variable values directly applied to our cluster.

**Comment by barryib** [comment]
`kubelet_extra_args` is used by the bootstrap script which is run by cloudinit when your node start. To apply that you have different options:
- Do it manually on each worker node (I don't if it doable in your case)
- Do blue/green update with this module
- Drain and delete worker node one by one and let the ASG or Cluster Autoscaller spawn a new node

See https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#how-do-i-safely-remove-old-worker-groups and https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#why-are-nodes-not-recreated-when-the-launch_configurationlaunch_template-is-recreated for more info.

**Comment by barryib** [comment]
Closing this. Feel free to re-open it the provided answer doesn't help you.
