### ISSUE TITLE
Override ASG Tag propagation 

### ISSUE THREAD

**Issue by huddy** [terraform-aws-modules/terraform-aws-eks#1091]
# I have issues
Firstly thanks very much for maintaining this module, we've received a ton of value from this code. 

Currently when passing a list of tags into the module they get applied to both The ASG and instances/workers due to `propagate_at_launch` defaulting to true. 

I have a particular tag that I want applied to all resources including the ASG but except the worker nodes. 

A similar PR/Issue has been raised here: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1076 but was rejected with a good suggestion on how to solve this, which I plan to raise a PR for. 

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?

Currently all tags passed in via `var.tags` are propagated to ASG and worker nodes. 

## What's the expected behavior?

Based on the discussion in #1076 it seems there's a desire to solve this by allowing launch templates in the variable `worker_groups_launch_template` to override `var.tags`.  This would happen for ASGs by using `local.asg_tags`, so that during processing we use `var.workers_group_defaults.tags`, thus overriding the `var.tag`.

## Are you able to fix this problem and submit a PR? Link here if you have already.

https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1092

## Environment details

* Affected module version: latest/master
* OS: N/A
* Terraform version: N/A

## Any other relevant info

It would really help although obviously not expected if this would be merged in and tagged fairly soon as this would allow us to ship some functionality we require and I know others are looking forward to this as well!

**Comment by barryib** [comment]
Closing this, since #1092 is now merged.

**Comment by barryib** [comment]
[v13.2.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v13.2.0) is now released.
