### ISSUE TITLE
How do I name the nodes when using node_groups?

### ISSUE THREAD

**Issue by mohitasher** [terraform-aws-modules/terraform-aws-eks#1110]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

How can I add a name to the EC2 instances created using node_groups? It appears empty. I tried adding 'Name' using additional_tags however the tags are added to node group and not the nodes.

Thanks

**Comment by barryib** [comment]
This is not yet supported by AWS. See https://github.com/aws/containers-roadmap/issues/608

But if you're using Launch Template with Managed Node Group, you can define your tags specs in your LT directly.

**Comment by mickeypash** [comment]
The docs [for the `node_groups` submodule have `additional_tags` mentioned](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/node_groups). I haven't tested this myself but would this work or would one still need to use a launch template?

**Comment by zhixiangjoy** [comment]
I meet the same problems .
