### ISSUE TITLE
[Question/Feature Request] Update Existing .kube/config Instead of Overwriting

### ISSUE THREAD

**Issue by alexandrud** [terraform-aws-modules/terraform-aws-eks#1120]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Currently you can output the context configuration by using "write_kubeconfig" and, eventually set a custom path by using "config_output_path".

I believe it would be useful to have an "update_kubeconfig" mode where you just append the new context. Maybe run "aws eks --region $region update-kubeconfig --name $clusterName" or something similar?

We have several environments that we manage with terragrunt and some of the code is actually for deploying helm charts. If the .kube/config file gets overwritten this can break functionality of the code. If it just gets updated we can control the context from the helm provider as needed.

## What's the expected behavior?

Feature request to be able to update the .kube/config file instead of overwriting it.

## Environment details

* Affected module version: 13.2.1
* OS: Debian 10.x
* Terraform version: 1.13.5

**Comment by alexandrud** [comment]
The workaround we're using now:
`resource "null_resource" "update_kubeconfig" {
  provisioner "local-exec" {
    command = "aws eks --region ${var.aws_region} update-kubeconfig --name ${module.eks.cluster_id}"
  }
}`

**Comment by schollii** [comment]
We use same workaround but 
1. it would be nice not to have to do that, so I upvote supporting kubeconfig merge mode as a feature request
2. I use an alias `--alias ${var.cluster_name}` otherwise the context name is a length cluster ARN!

**Comment by barryib** [comment]
We can't handle updates in this module. This can be very difficult to handle and is beyond EKS deployment. So I suggest to write your own kubeconfig by relying on the module `kubeconfig` [output](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/outputs.tf#L70).

I'm closing this issue, but feel free to re-open it if needed.

**Comment by schollii** [comment]
The `output` link does not point to anything relevant, @barryib can you please update what you were referring to.
