### ISSUE TITLE
terraform init: no provider "aws" plugin meet the constraint ">= 3.3.0, ~> 2, ~> 2.23" with eks module 13.1.0+

### ISSUE THREAD

**Issue by darrenfurr** [terraform-aws-modules/terraform-aws-eks#1121]
## I'm submitting a...

* [x ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Terraform version: 0.12.28
When attempting to run `tf init` I receive: `no provider "aws" plugin meet the constraint ">= 3.3.0, ~> 2, ~> 2.23"`

## If this is a bug, how to reproduce? Please include a code sample if relevant.
```
provider "aws" {
  region = var.region
}

terraform {
  required_version = ">= 0.12.9, != 0.13.0"
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "~> 1.11"
}

module "eks" {
  source                          = "terraform-aws-modules/eks/aws"
...
}

```

## What's the expected behavior?
terraform init runs successfully

## Environment details

* Affected module version: 13.1.0+ 
* OS: Amazon Linux 2
* Terraform version: 0.12.28

## Workaround:
If I revert to 13.0.0 the module & terraform init works successfully.

**Comment by waynewong-ascenda** [comment]
Same issue, any update? Since I need to use launch template in 13.1.0

**Comment by fabianobianchi** [comment]
The lastest hashicorp/aws version is 3.22 according to https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md 

I am unsure why the module is requiring version 3.3.0 https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v13.1.0/versions.tf

**Comment by fabianobianchi** [comment]
I was facing this issue but I realized that in my child terraform code I had a conflicting code 

```
provider "aws" {
  region  = var.aws_region_name
  version = "2.36.0"
}
``` 
I hope that it helps you to find the solution @waynewong-ascenda

**Comment by cheriL** [comment]
It's a provider conflict and I change my eks module's version to 13.0.0.

**Comment by darrenfurr** [comment]
still an issue?
