### ISSUE TITLE
create managed node group with custom ami

### ISSUE THREAD

**Issue by tnimni** [terraform-aws-modules/terraform-aws-eks#1125]
# I have issues

## I'm submitting a...

* [ ] bug report
* [] feature request
* [v] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

I want to create a managed node group with custom ami

As far as I understand I have to create my own LT and plug it into the module as a value in the map node_groups

Is it possible to make the module generate the LT?
If I have to create my own LT how can I set the version to latest?

**Comment by entropitor** [comment]
Were you able to do this? I have the problem that my nodes are not recognized as part of the node group, how did you solve this?
