### ISSUE TITLE
kubelet_extra_args is not functioning for labels

### ISSUE THREAD

**Issue by Imoustak** [terraform-aws-modules/terraform-aws-eks#1128]
# I have issues
With the option `kubelet_extra_args` of `worker_groups`. Using the option 
`kubelet_extra_args = "--node-labels=mylabel=yes"` doesnt result in labels being created on the nodes. 

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Node labels arent added in the nodes.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
cluster_version = "1.17"
Use the option in `worker_groups` config:
`kubelet_extra_args = "--node-labels=mylabel=yes"`  

## What's the expected behavior?
Label `mylabel=yes` to be added to the nodes.

## Environment details

* Affected module version: 13.0.0
* OS: linux
* Terraform version: 0.13.5

**Comment by Imoustak** [comment]
The workers were already created and then I added this.

**Comment by ArchiFleKs** [comment]
@Imoustak this only works when node is registered, not after, this will work for new nodes but not existing one

**Comment by clementrey-dev** [comment]
Hello,
I am experiencing a similar issue. All nodes created with "kubelet_extra_args" are not even registered to the cluster whereas the instances are well running.
EKS version 1.18 

- terraform version: 0.13.4
- OS: macOS
- module version: 13.2.0

Do you know what could be the reason of that ?

Best Regards

**Comment by sudermanjr** [comment]
In my recent experience with this module, it is fairly easy to break the kubelet with this flag if you're not very careful about how you set it.

The best way to diagnose is to ssh to the node that hasn't joined the cluster and get the kubelet logs with `journalctl -u kubelet`.  Also check that kubelet is running with `systemctl status kubelet`

Once I got the syntax of the flag correct, my nodes started joining the cluster again.

**Comment by anupash147** [comment]
This is happening because since k8 1.16 the way nodes are labelled have changed .. take a look https://github.com/kubernetes/sig-release/blob/master/releases/release-1.16/release-notes-draft.md#deprecations-and-removals. with AWS its now a freak show.

**Comment by barryib** [comment]
@adv4000 @Imoustak is the following https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1046 fix your issue ?
