### ISSUE TITLE
Support GP3 volume type

### ISSUE THREAD

**Issue by sgran** [terraform-aws-modules/terraform-aws-eks#1130]
# Support GP3 volume type

## I'm submitting a...

* [x] feature request

## What is the current behavior?

root_volume_type and a few other configuration parameters affect the sort of EBS volume selected for the root volume for worker nodes.  AWS introduced a new volume type, GP3.  This new volume type needs a new parameter on the EBS section of the launch configuration, 'throughput'.  This new parameter is only valid for GP3 configurations and has a default value of 125.

This will almost certainly have to block on the AWS provider getting support for the new volume type and changing the struct for the EBS volume.

**Comment by jayzalowitz** [comment]
While you wait for this to merge this will get you up to speed: 
workers_group_defaults = {
    root_volume_type          = "gp3"
}

**Comment by jayzalowitz** [comment]
I dont think throughput is an option yet, i may be wrong: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#block-devices

**Comment by jayzalowitz** [comment]
Yep: https://github.com/hashicorp/terraform-provider-aws/issues/16514

**Comment by sidprak** [comment]
Now that provider support has landed in the launch template resource, I tested this out and gp3 volumes seem to work out of the box with this module. As mentioned above, the `throughput` setting needs to be added which I've done in #1146.

**Comment by sidprak** [comment]
Doing some googling, looks like gp3 is not supported in launch configuration yet (maybe not going to be supported at all?) so the support in #1146 is only in launch templates.
