### ISSUE TITLE
Configurable timeouts on creating workers node group.

### ISSUE THREAD

**Issue by samcday** [terraform-aws-modules/terraform-aws-eks#1131]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Creating a new node group can take longer than an hour, which causes the `node_groups.aws_eks_node_group.workers` resource to timeout.

## What's the expected behavior?

Timeout behaviour for `node_groups.aws_eks_node_group.workers` should be configurable!

## Environment details

* Affected module version: v12.2.0
* OS: Linux
* Terraform version: 0.12.x

**Comment by ruckc** [comment]
This is a constant pain point with automating EKS clusters

**Comment by bryantbiggs** [comment]
should be fixed shortly

**Comment by antonbabenko** [comment]
Fixed in #1552 

Released in [v17.9.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/v17.9.0).
