### ISSUE TITLE
EKS Managed Cluster Addons

### ISSUE THREAD

**Issue by RichiCoder1** [terraform-aws-modules/terraform-aws-eks#1137]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the feature request?

Support for EKS Managed Cluster Addons. Would be great if this module not only managed the cluster addon, but did the auto-version and IAM magic it does for other EKS parts.

Depends on https://github.com/hashicorp/terraform-provider-aws/issues/16542

**Comment by NeckBeardPrince** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/16972

**Comment by barryib** [comment]
Closing in favor of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1385
