### ISSUE TITLE
Error when upgrading from 1.4 to 1.5 (and how we solved it)

### ISSUE THREAD

**Issue by abelgvidal** [terraform-aws-modules/terraform-aws-eks#114]
This is just to let you know an issue upgrading from 1.4 to 1.5. 

As HTTP provider was removed in 1.5, and if you applied this module with version 1.4 and then upgraded to 1.5, the HTTP dependency is still stored in tfstate file and it breaks when `terraform plan` with message 

```
 `Error: Error asking for user input: 1 error(s) occurred:

* module.eks.data.http.workstation_external_ip: configuration for module.eks.provider.http is not present; a provider configuration block is required for all operations'
```

The solution is adding the dependency to the local copy of module, running `terraform apply`( it cleans the dependency from the tsfile ) and then removing it. 

I understand this is more a terraform issue, but maybe is useful for someone upgrading.

## Environment details

* Affected module version: 1.5
* OS: any
* Terraform version: 0.11.7

**Comment by max-rocket-internet** [comment]
Understood.

The solution is to just delete that resource from the state: `terraform state rm module.eks.data.http.workstation_external_ip`

**Comment by abelgvidal** [comment]
Thank you!

**Comment by elatt** [comment]
I found this ticket useful, may be worth noting in a `Release Notes` section or something for folks upgrading.

**Comment by brandoconnor** [comment]
Yea with a note in CHANGELOG.md, I think we can close this out as having done the due diligence. Super simple PR if either of you have the cycles.

**Comment by abelgvidal** [comment]
A PR with the note https://github.com/terraform-aws-modules/terraform-aws-eks/pull/139 @brandoconnor  👋

**Comment by max-rocket-internet** [comment]
Cool. Gonna close this then 🙂
