### ISSUE TITLE
module returns "query returned no results" when using a non existent cluster_version

### ISSUE THREAD

**Issue by mahpatil** [terraform-aws-modules/terraform-aws-eks#1141]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Get "Error: Your query returned no results. Please change your search criteria and try again." if the cluster_version specified is incorrect.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
```
module "eks-cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = var.cluster_name
  cluster_version = var.cluster_version //set this to "1.19" currently AWS latest v 1.18
  subnets         = var.subnets
  vpc_id          = var.vpc_id

  worker_groups = [
    {
      instance_type         = var.instance_type
      asg_max_size          = var.asg_max_size
      asg_desired_capacity  = var.asg_desired_capacity
      additional_userdata   = var.additional_userdata
    }
  ]
  tags = var.tags
}
```

## What's the expected behavior?
I would expect it to fail with a bit more friendly message but I get below error, it is confusing and doesn't lead to specific field.
Error: Your query returned no results. Please change your search criteria and try again.

Error: Your query returned no results. Please change your search criteria and try again.

## Environment details

* Affected module version: 13.2.1+
* OS: macOS
* Terraform version: 0.14

**Comment by btsuhako** [comment]
this module is searching for `amazon-eks-node-1.19-v*` in the AMI registry -> https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v13.2.1/local.tf#L18

right now it looks like AWS hasn't published that AMI yet. 1.18 available, but 1.19 isn't:
![image](https://user-images.githubusercontent.com/2069065/101959660-f7156200-3bc2-11eb-9c7c-03092b3e75f7.png)
![image](https://user-images.githubusercontent.com/2069065/101959671-fc72ac80-3bc2-11eb-8c85-3b58e11e09bc.png)

**Comment by dbirks** [comment]
In case anyone else tries updating to 1.19 now that it's available:

![Screenshot from 2021-02-16 21-22-38](https://user-images.githubusercontent.com/7545665/108147687-54cf9a00-709d-11eb-8470-07a16b1f4cae.png)

I ran into the same `query returned no results` error, until I manually set the Windows ami to 1.18 (even though I'm not using any Windows nodes):
```
worker_ami_name_filter_windows = "Windows_Server-2019-English-Core-EKS_Optimized-1.18-*"
```

It looks like AWS just hasn't released a Windows 1.19 ami yet.

**Comment by sanarena** [comment]
Ah, Terraform should have a better error handling for this.
After doing a change in a large TF code base, i got hit by this error and Terraform was not announcing where is the issue coming from.

@dbirks solution solved my issue.

**Comment by obeleh** [comment]
How would I go about if I use `node_groups` in stead of workers?

**Comment by barryib** [comment]
I just opened https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1371 to address this. Will you please review it and test it ?
