### ISSUE TITLE
Feature request to support kubernetes_network_config 

### ISSUE THREAD

**Issue by lee-vincent** [terraform-aws-modules/terraform-aws-eks#1144]
## I'm submitting a...

[*] feature request

## What is the current behavior?
Unable to specify the CIDR block that Kubernetes will provision service IP addresses from

## What's the expected behavior?
To be able to set service_ipv4_cidr in the eks module per this documentation:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#kubernetes_network_config

## Environment details
aws provider version = "3.21.0"

**Comment by iserko** [comment]
already a PR for it #1139
