### ISSUE TITLE
enable_irsa=true creates OIDC provider with audience pointing to global sts endpoint (sts.amazonaws.com)

### ISSUE THREAD

**Issue by toytown** [terraform-aws-modules/terraform-aws-eks#1145]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

EKE- 1.18, Fargate

when enable_irsa = true an OIDC provider is created correctly and the audience is set to "sts.amazonaws.com". However, in most corporate network one is encouraged to use local endpoint "sts.eu-central-1.amazonaws.com". In most of the corporate network I have experienced the  "sts.amazonaws.com" is blocked which creates issues for role assumption by containers.

## What's the expected behavior?

Either based on region setting of the EKS cluster or through explicit setting of sts endpoint it would be nice to have to be able to configure OIDC audience (sts endpoint) explicitly with some property like

oidc_audience = sts.xxxx.com (if irsa is set tot true)
 

## Environment details

* Affected module version:
* OS: Linux
* Terraform version: 0.13.4

**Comment by damacus** [comment]
The local endpoints are usually handled by the VPC module, and I think it should probably stick that way to keep the complexity of this module to a minimum. 

The fix for this is probably documentation on how to easily create the endpoint with the VPC module in an example.

**Comment by bodgit** [comment]
I think @toytown is simply asking for a new variable to allow setting the audience, (the `client_id_list` argument on the `aws_iam_openid_connect_provider` resource) which is currently hardcoded to `local.sts_principal`.

I am probably going to want this also as I have to use VPC endpoints in order to reach the STS API without using a proxy.

**Comment by cabrinha** [comment]
Deploying to CN accounts, in regions like `cn-north-1` cause an error with IAM Roles for Service Accounts.

"Incorrect Token Audience" will be seen because the `client_id_list` gets configured with `sts.amazonaws.com.cn` and not `sts.amazonaws.com`.

**Comment by daroga0002** [comment]
does this is not working in this use case: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1e2c32430f458409771938c16a3dc437cd657d02/local.tf#L47


or this is related to OIDM role module used in examples?

**Comment by cabrinha** [comment]
> does this is not working in this use case:
> 
> https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1e2c32430f458409771938c16a3dc437cd657d02/local.tf#L47
> 
> or this is related to OIDM role module used in examples?

The code you've pasted here works as expected, but cluster-autoscaler, velero, etc -- almost any service that uses IAM Roles for Service Accounts needs to use `sts.amazonaws.com` and not `sts.amazonaws.com.cn`.

**Comment by daroga0002** [comment]
ok, but in that case I believe change is applicable to module https://github.com/terraform-aws-modules/terraform-aws-iam/tree/v4.1.0/modules/iam-assumable-role-with-oidc which is used in example:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9022013844a61193a2f8764311fb679747807f5c/examples/irsa/irsa.tf#L1-L9

**Comment by cabrinha** [comment]
> ok, but in that case I believe change is applicable to module https://github.com/terraform-aws-modules/terraform-aws-iam/tree/v4.1.0/modules/iam-assumable-role-with-oidc which is used in example:
> 
> https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9022013844a61193a2f8764311fb679747807f5c/examples/irsa/irsa.tf#L1-L9

I don't understand where `sts.amazonaws.com` comes into play here... The EKS module creates the OpenID Connect Identity Provider, and thats where the Audience aka Client ID is specified...

**Comment by cabrinha** [comment]
AWS docs instruct using `sts.amazonaws.com` when creating an OIDC provider: https://docs.amazonaws.cn/en_us/eks/latest/userguide/enable-iam-roles-for-service-accounts.html

```
To create an IAM OIDC identity provider for your cluster with the Amazon Web Services Management Console

    Open the Amazon EKS console at https://console.amazonaws.cn/eks/home#/clusters

.

Select the name of your cluster and then select the Configuration tab.

In the Details section, note the value of the OpenID Connect provider URL.

Open the IAM console at https://console.amazonaws.cn/iam/

.

In the navigation panel, choose Identity Providers. If a Provider is listed that matches the URL for your cluster, then you already have a provider for your cluster. If a provider isn't listed that matches the URL for your cluster, then you must create one.

To create a provider, choose Add Provider.

For Provider Type, choose OpenID Connect.

For Provider URL, paste the OIDC issuer URL for your cluster, and then choose Get thumbprint.

For Audience, enter sts.amazonaws.com and choose Add provider.
```

**Comment by daroga0002** [comment]
just to confirm (as I dont have any experience with cn region), https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/irsa.tf#L12 should be pointing always to `sts.amazonaws.com` ?

**Comment by cabrinha** [comment]
> just to confirm (as I dont have any experience with cn region), https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/irsa.tf#L12 should be pointing always to `sts.amazonaws.com` ?

When using IAM Roles for Service Accounts, this is the only thing that works for me. I don't see any harm in having both `sts.amazonaws.com` and `sts.amazonaws.com.cn` in there though, which is what I'm currently doing.

**Comment by cabrinha** [comment]
@daroga0002 could you take another look or weigh in on the PR?
