### ISSUE TITLE
Terraform plan fails while refreshing state of kube-system/aws-auth with 'Error: configmaps "aws-auth" is forbidden'

### ISSUE THREAD

**Issue by dresnick-sf** [terraform-aws-modules/terraform-aws-eks#1148]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Running `terraform plan` fails with this error:

```
module.eks.module.eks.kubernetes_config_map.aws_auth[0]: Refreshing state... [id=kube-system/aws-auth]

Error: configmaps "aws-auth" is forbidden: User "system:serviceaccount:default:default" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
```

The user running terraform has correct permissions, it is running using the same role used when the cluster was initially created.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

The change I've made in the use of this module is to create my own cluster security group.
```
  cluster_create_security_group = false
  cluster_security_group_id     = local.cluster_security_group_id
```
Without that change I am able to successfully run `terraform plan`, including refreshing the state of `module.eks.module.eks.kubernetes_config_map.aws_auth[0] [id=kube-system/aws-auth]`

The last time I successfully ran `terraform plan` was with terraform-aws-eks version 12.2.0 and terraform 0.13.0. Reverting from 13.2.1 to that version doesn't change the error message I get.

I gave `system:serviceaccount:default:default` cluster admin permission, though this did not change the results.

## What's the expected behavior?

Plan will succeed.

## Are you able to fix this problem and submit a PR? Link here if you have already.

The only workaround I've found is to recreate the cluster. The problem occurs for 3 existing clusters, 1 of which has been replaced.

## Environment details

* Affected module version: 13.2.1
* OS: EKS Kubernetes Worker AMI with AmazonLinux2 image, (k8s: 1.16.13, docker:19.03.6ce-4.amzn2)
* Terraform version: 0.14.2

**Comment by dresnick-sf** [comment]
This was was probably because I used the wrong state files for the clusters.

**Comment by harsh4870** [comment]
@dresnick-sf  i am facing same error if you can please share you example files for reference can not re-apply the terraform configuration.

**Comment by Nirosan** [comment]
@harsh4870 similar error occurred to me, it was due to the kubernetes provider part missing.

```
data "aws_eks_cluster" "cluster" {
  name = module.eks-cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks-cluster.cluster_id
}
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  token                  = data.aws_eks_cluster_auth.cluster.token
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
}
```

**Comment by gimpiron** [comment]
@Nirosan 
cc: @harsh4870 

I still get this error, i have the provider well configured-  i know that because my module does work on new clusters, 
at some point, about 3 months after creation, I start getting this weird errors.

Does anybody know how can it be? How this provider works well on new creation and some time after that but fails later on?

**Comment by lqychange** [comment]
I'm facing the similar issue, working when provisioned the EKS cluster initially, but getting below error couple of month later when try to update resources with the same Terraform Workspace on TFE:

`Error: configmaps "aws-auth" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-system"`

My Kubernete Provider configuration is:

`provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}`

**Comment by daroga0002** [comment]
In general looks that you are not able to connect to EKS API because your user/role doesnt have permissions in EKS itself (this is part controlled by aws-auth configmap). 

User which has full permissions in EKS even without entry in mentioned config map is EKS creator. Does you created cluster on same role/user as now you are trying to access?

**Comment by PaulWBrassard** [comment]
I am getting the same issue as @msnelling (terraform apply on no version change works) with the only difference that I'm going from 1.19 to 1.20.
```
│ Error: configmaps "aws-auth" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
│ 
│   with module.cluster.kubernetes_config_map.aws_auth[0],
│   on .terraform/modules/cluster/aws/eks/control_plane/auth.tf line 45, in resource "kubernetes_config_map" "aws_auth":
│   45: resource "kubernetes_config_map" "aws_auth" {
│ 
╵
```
I was thinking that maybe it was an issue with auth token retreival from [aws_eks_cluster_auth datasource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/eks_cluster_auth), so I switch to using a local config and I still get the same error.

To try to rule out auth issues, I attempted to change the same config map in a different way. Interestingly, terraform plan works there:
```
Terraform will perform the following actions:

  # module.cluster.kubernetes_config_map.aws_auth[0] will be updated in-place
  ~ resource "kubernetes_config_map" "aws_auth" {
      ~ data        = {
          ~ "mapRoles" = <<-EOT
                - "groups":
                  - "system:bootstrappers"
                  - "system:nodes"
                  "rolearn": "<redacted-arn>"
                  "username": "system:node:{{EC2PrivateDNSName}}"
                - "groups":
                  - "system:bootstrappers"
                  - "system:nodes"
                  "rolearn": "<redacted-arn>"
                  "username": "system:node:{{EC2PrivateDNSName}}"
                - "groups":
                  - "system:bootstrappers"
                  - "system:nodes"
                  "rolearn": "<redacted-arn>"
                  "username": "system:node:{{EC2PrivateDNSName}}"
              + - "groups":
              +   - "system:masters"
              +   "rolearn": "<redacted-arn>"
              +   "username": "admin"
            EOT
            # (1 unchanged element hidden)
        }
        id          = "kube-system/aws-auth"
        # (1 unchanged attribute hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Now I'm thinking this just may be an AWS provider bug. I am currently using `registry.terraform.io/hashicorp/aws` version     3.63.0.
I'll try updating the provider to see if it resolves the issue.
