### ISSUE TITLE
Desired Capacity not tracking changes

### ISSUE THREAD

**Issue by monfardineL** [terraform-aws-modules/terraform-aws-eks#1149]
# I have issues
I've first tried upgrading from 3 to 4 desired nodes, but got no changes tracked. Upgrading minimum capacity (from 3 to 4 also) would give a error, since desired can't be lower as minimum cap.

## I'm submitting a...

* [X ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Changing desired_capacity on a node_group block won't be tracked by Terraform.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Increase desired_capacity on a node_group from 3 -> 4. (Some screenshots attached)

## What's the expected behavior?

Upgrade desired capacity from 3 to 4.

## Are you able to fix this problem and submit a PR? Link here if you have already.
No.
## Environment details

* Affected module version: v13.2.0/v13.2.1. Will downgrade to test next.
* OS: EKS Cluster v1.17 with AmazonLinux2 image.
* Terraform version: v0.13.5

## Any other relevant info
![2020-12-17 15_53_18-eks tf - aws - Visual Studio Code](https://user-images.githubusercontent.com/9057896/102531608-566ee880-4081-11eb-8fa5-263c738ec447.png)
![2020-12-17 15_53_33-plan production (#216115) · Jobs · gitops _ infra _ aws · GitLab](https://user-images.githubusercontent.com/9057896/102531610-57077f00-4081-11eb-941e-6b01b2ea0bda.png)
![2020-12-17 15_59_13-apply (#216116) · Jobs · gitops _ infra _ aws · GitLab](https://user-images.githubusercontent.com/9057896/102531612-57a01580-4081-11eb-9a93-49bc722a57c2.png)

**Comment by ecktom** [comment]
See eg. https://github.com/terraform-aws-modules/terraform-aws-eks/issues/835

**Comment by monfardineL** [comment]
Didn't make sense at first, but now I understood the "problem". Closing the issue. Thanks.
