### ISSUE TITLE
Tags on Fargate profiles aren't created properly

### ISSUE THREAD

**Issue by Lena-nfb** [terraform-aws-modules/terraform-aws-eks#1156]
# I have issues
with tags on fargate profiles

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

when create an EKS cluster on fargate tags aren't created properly on fargate profiles. When `tags` object exists on fargate profile as in the [example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/fargate/main.tf#L103) then the tags aren't merged with the [tags](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/fargate/main.tf#L103) from the cluster but swallowed. 

## If this is a bug, how to reproduce? Please include a code sample if relevant.
If you `terraform plan` the fargate [example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/fargate/main.tf#L78) it should output

```
 # module.eks.module.fargate.aws_eks_fargate_profile.this["example"] will be created
  + resource "aws_eks_fargate_profile" "this" {
      + arn                    = (known after apply)
      + cluster_name           = (known after apply)
      + fargate_profile_name   = (known after apply)
      + id                     = (known after apply)
      + pod_execution_role_arn = (known after apply)
      + status                 = (known after apply)
      + subnet_ids             = (known after apply)
      + tags                   = {
          + "Owner" = "test"
        }

      + selector {
          + namespace = "default"
        }
    }
``` 

## What's the expected behavior?
It should output

```
  # module.eks.module.fargate.aws_eks_fargate_profile.this["example"] will be created
  + resource "aws_eks_fargate_profile" "this" {
      + arn                    = (known after apply)
      + cluster_name           = (known after apply)
      + fargate_profile_name   = (known after apply)
      + id                     = (known after apply)
      + pod_execution_role_arn = (known after apply)
      + status                 = (known after apply)
      + subnet_ids             = (known after apply)
      + tags                   = {
          + "Environment" = "test"
          + "GithubOrg"   = "terraform-aws-modules"
          + "GithubRepo"  = "terraform-aws-eks"
          + "Owner"       = "test"
        }

      + selector {
          + namespace = "default"
        }
    }
```

## Are you able to fix this problem and submit a PR? Link here if you have already.

[PR-1159](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1159)

**Comment by barryib** [comment]
closing since #1159 is now merged.
