### ISSUE TITLE
Bug introduced in PR #115

### ISSUE THREAD

**Issue by mr-joshua** [terraform-aws-modules/terraform-aws-eks#116]
# I have issues

Bug introduced in #115 
## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Line 29:
```
  image_id                    = "${lookup(var.worker_groups[count.index], "ami_id", lookup(local.workers_group_defaults, "ami_id", data.aws_ami.eks_worker.id))}"
```

The logic as written will ALWAYS set the image_id to "".

## If this is a bug, how to reproduce? Please include a code sample if relevvant.

Do not specify an ami_id and this error will occur.

## What's the expected behavior?

If no ami_id is provided then it should default to the data object ami_id.

Line 29 should be:

  image_id                    = "${lookup(var.worker_groups[count.index], "ami_id", data.aws_ami.eks_worker.id)}"

## Are you able to fix this problem and submit a PR? Link here if you have already.

Added to PR #112 

## Environment details

* Affected module version: master
* OS: N/A
* Terraform version: 0.11.7

**Comment by max-rocket-internet** [comment]
@erks

**Comment by max-rocket-internet** [comment]
Do mean https://github.com/terraform-aws-modules/terraform-aws-eks/pull/115 ?

**Comment by mr-joshua** [comment]
Reviewed and agree with you that the solution you propose is the best way to address.  Thanks.

**Comment by erks** [comment]
thanks, @mr-joshua. And, my apologies, as I had only tested the case where the default is overridden.

**Comment by max-rocket-internet** [comment]
🙌

**Comment by max-rocket-internet** [comment]
All good, no worries, quickly and easily fixed. It wasn't in a release anyway.

**Comment by brandoconnor** [comment]
Thanks for hopping on this with the quickness!
