### ISSUE TITLE
"list" function was deprecated in Terraform v0.12

### ISSUE THREAD

**Issue by TjeuKayim** [terraform-aws-modules/terraform-aws-eks#1164]
This module doesn't work with Terraform v0.15.0-dev build from source (commit c0e37a7ea1928918a9efc02290ecd241d396d3a6)

```
Error: Error in function call

  on .terraform/modules/eks/outputs.tf line 3, in output "cluster_id":
   3:   value       = element(concat(aws_eks_cluster.this.*.id, list("")), 0)

Call to function "list" failed: the "list" function was deprecated in
Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to
write a literal list.
```

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/65777d0a37791dd1200d478e3bacc4c9a75f24c8/outputs.tf#L3

**Comment by jtgorny** [comment]
Too bad this comment wasn't found before the stable release yesterday. Looks like lots of people, myself included are having the same issue. Hopefully the solution gets merged in quick. #1165

**Comment by antonbabenko** [comment]
Terraform 0.15 is supported in version [v15.0.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/v15.0.0) that has been just released.

For the previous version of Terraform please use this module version `~> 14.0`.

Let us know if there are any issues with this release.
