### ISSUE TITLE
How can I use the node_groups in a for loop so that to create node_groups from a list eg: var node_group_types =  ["ng1", "ng2", "ng3"]

### ISSUE THREAD

**Issue by anoopl** [terraform-aws-modules/terraform-aws-eks#1168]
How can I use the node_groups in a for loop so that to create node_groups from a list eg: var node_group_types =  ["ng1", "ng2", "ng3"]

## support request 

I tried using for_each and for_each with dynamic as following:

node_groups = [
    {
      for_each = toset(var.node_group_types)
      name                          = each.value
      instance_type                 = var.instance_type
      additional_userdata           = "echo foo bar"
      additional_security_group_ids = [aws_security_group.node.id]
      asg_desired_capacity          = var.node_desired_size
      asg_max_size                  = var.node_maximum_size
      asg_min_size                  = var.node_minimum_size
      disk_size                     = var.disk_size
    },

  ]
}

Got error:
20:       name                          = each.value

A reference to "each.value" has been used in a context in which it
unavailable, such as when the configuration no longer contains the value in
its "for_each" expression. Remove this reference to each.value in your
configuration to work around this error.

Then tried:

    dynamic "node_group_type" {
      for_each = var.node_group_types
       content {
        {
      name                          = node_group_type
      instance_type                 = var.instance_type
      additional_userdata           = "echo foo bar"
      additional_security_group_ids = ["aws_security_group.${node_group_tye}.id"]
      asg_desired_capacity          = var.node_desired_size
      asg_max_size                  = var.node_maximum_size
      asg_min_size                  = var.node_minimum_size
      disk_size                     = var.disk_size

    },
    }
  }

But could not get it working due to syntax errors. Can you please support on this?

* Affected module version:
* OS:
* Terraform version:
v0.13.5

**Comment by mwalsher** [comment]
We are successfully using `for`, e.g.:

```
  node_groups = [
    for private_subnet_az, private_subnet_id in var.private_subnet_az_id_map : {
      name = "spot-${private_subnet_az}"
      subnets = [private_subnet_id]
    }
  ]
```

**Comment by anoopl** [comment]
@mwalsher, Thanks for the suggestion. I will try this
