### ISSUE TITLE
Issues with examples

### ISSUE THREAD

**Issue by imyousuf** [terraform-aws-modules/terraform-aws-eks#1171]
# I have issues

## I'm submitting a bug related to the IRSA example and documentation.

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

* Currently if I follow the example the auto-scaler fails to fetch auth credentials -

```bash
E0102 14:33:38.386535       1 aws_manager.go:262] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.us-east-1.amazonaws.com/id/9CF055927D35417AAD227E0AE5B5F10B
	status code: 400, request id: e611b681-b83e-4063-8c4b-f74a0f177643
F0102 14:33:38.386553       1 aws_cloud_provider.go:376] Failed to create AWS Manager: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.us-east-1.amazonaws.com/id/9CF055927D35417AAD227E0AE5B5F10B
	status code: 400, request id: e611b681-b83e-4063-8c4b-f74a0f177643
```
* Link to `public Helm chart` is broken
* Spot instances does not work with launch template (_does work with launch configuration_)
* When launch template is updated it does create a new version but does not change `Default` version; so the older template will stay in effect
* `spot_max_price` is not used and confused me
* `k8s-spot-termination-handler` is no longer maintained as AWS has their own

## If this is a bug, how to reproduce? Please include a code sample if relevant.

* Use the [TF Code](https://github.com/imyousuf/webhook-broker/commit/32bd6be2800829bf1a6c22365fa126be9cd0b4e6#diff-a5af2bdb3137b0b4cc8411dee3048b937805e466db1391eb2f757a95cc06d0b8) without `enable_irsa` prop set to `true` in `eks` module
* Also link to `public Helm chart` is broken since the project renamed the [directory](https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler).
* Test the current spot instance example to reproduce it with the versions specified below
* Use launch template and then change some config (e.g. instance type) and re-apply; then observe the default version from AWS Console
* AWS now maintains its own [spot termination handler](https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler).

## What's the expected behavior?

Example should include the `enable_irsa` prop so that others dont go finding why its not working.

## Are you able to fix this problem and submit a PR? Link here if you have already.

Currently do not have the time or know everything else to test hence just reporting the issue.

## Environment details

* Affected module version: **13.2.1**
* OS: Ubuntu 20.04.1 LTS
* Terraform version: 
```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.22.0
+ provider registry.terraform.io/hashicorp/helm v2.0.1
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

## Any other relevant info

I have figured out the workaround to these issues as I have worked on this branch -
https://github.com/imyousuf/webhook-broker/tree/terraform

**Comment by seanturner026** [comment]
Having the same issue.
