### ISSUE TITLE
WARNING: Kubernetes configuration file is world-readable. This is insecure

### ISSUE THREAD

**Issue by satazor** [terraform-aws-modules/terraform-aws-eks#1172]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

The kubeconfig file has 0644 permissions.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

The default behavior already outputs a `kubeconfig` file, so there's no need to reproduce.

## What's the expected behavior?

The `kubeconfig` perms should be 0600.

## Are you able to fix this problem and submit a PR? Link here if you have already.

Yes.

PR: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1173

## Environment details

* Affected module version: 13.2.1
* OS: All
* Terraform version: 0.13

**Comment by hypervtechnics** [comment]
I think that this is a bit exagggerated. The kubeconfig does not contain sensitive information besides the cluster name or the server certificate. This information is not really critical imo.

**Comment by barryib** [comment]
Closing since, the default is now `600`. You can also set your own permission by using `var.kubeconfig_file_permission`
