### ISSUE TITLE
Using helm provider in the irsa example

### ISSUE THREAD

**Issue by fernando-villalba** [terraform-aws-modules/terraform-aws-eks#1178]
Why is the Helm provider not used in the [irsa example](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/irsa) to do the "manual" helm step like this?

```
provider "helm" {
  kubernetes {
    host                   = module.eks.cluster_endpoint
    token                  = data.aws_eks_cluster_auth.cluster.token
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  }
}
```

It just feels to me as it would be a better automation practice to use the helm provider here and it would also remove the extra steps. 

I am mostly very curious why this decision was made and if there is any advantage of having the extra step.

**Comment by trallnag** [comment]
I just follow this doc <https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/README.md>
