### ISSUE TITLE
Remove modules/node_groups/random.tf completely - it only causes issues

### ISSUE THREAD

**Issue by pre** [terraform-aws-modules/terraform-aws-eks#1188]
# I have issues

The `random_pet` resource is a nice helper for starting up a new environment quickly. 

However, in a live cluster it will only cause maintenance pain with bad side-effects. 

See https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1109#issuecomment-763450622

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

The `random_pet` for node_groups is only used for dynamic node_group name. 

However, the mere existence of modules/node_groups/random.tf causes a side-effect. The random_pet will create an unrelated resource `module.eks.module.node_groups.random_pet.node_groups["test-workers"]` which is bound to the node groups. 

As a result, changing any attribute in the Launch Template bound to a Managed Node Group will cause the whole Node Group being recreated. The correct behaviour would be to update the Launch Template in-place and then update Managed Node Group to use the new Launch Template version (which can be a separate action).

## If this is a bug, how to reproduce? Please include a code sample if relevant.

See issue https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1109 for details.

## What's the expected behavior?

Updating a Launch Template must not recreate a Managed Node Group.

Only the Launch Template version should be bound to a Managed Node Group and the Managed Node Group must be updated in-place (not recreated).

## Environment details

* Affected module version: v13.2.1
* OS: Mac OS
* Terraform version: 0.13.x - 0.14.4.

## Any other relevant info

See issue https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1109 for details.

**Comment by tjsampson** [comment]
Yes, we are running into some issues as well with this piece of the code. I have submitted a ticket here: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1194

**Comment by treksler** [comment]
i am also having issues. my use case is to specify 3 subnets for the eks cluster, but only use 1 subnet for some node groups.

**Comment by fractos** [comment]
Yep, just hit this with changing the instance type for a managed node group. Wondering what to do about it.

**Comment by barryib** [comment]
I just opened this https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1188. Can you please review and test it.
