### ISSUE TITLE
Add support for userdata in managed NodeGroups

### ISSUE THREAD

**Issue by psoares** [terraform-aws-modules/terraform-aws-eks#1192]
# I have issues
Currently, using node_groups, I see no way of injecting custom userdata by default without resorting to a custom launch template. The feature seems available in worker_groups_defaults though, through several hooks: pre_userdata, post_userdata, userdata_template_file...

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
There is no attribute in node_groups_default for setting default userdata.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
```hcl
module "eks" {
  source                                             = "terraform-aws-modules/eks/aws"
  version                                            = "13.2.1"
  // [...]
  node_groups_defaults = {
    additional_tags = local.owner_tags
    // no parameter to set userdata (pre, post or completely new)
  }
  workers_group_defaults = {
    post_userdata = templatefile("${path.module}/post_userdata.sh.tmpl", {})
  }
  node_groups = {
    example = {
      name             = "example"
      desired_capacity = 1
      max_capacity     = 5
      min_capacity     = 1

      instance_type = "t3a.xlarge"
      
    }
  }
}```


## What's the expected behavior?
node_groups_defaults should have a placeholder for using custom userdata, just like worker_group_defaults.

## Are you able to fix this problem and submit a PR? Link here if you have already.
I may be. I have to look into it.
## Environment details

* Affected module version: 13.2.1
* OS: Windows 10
* Terraform version: 0.14.4

## Any other relevant info

**Comment by psoares** [comment]
Seems like it isn't and won't be supported by the upstream aws module. See https://github.com/aws/containers-roadmap/issues/596.
They say they won't implement since this can be solved with launch templates (which is what I wanted to avoid in the first place).

**Comment by michelesr** [comment]
Other managed services like RDS have things like parameter groups to allow tweaking the configuration, so why can't we have a similar feature in EKS?

In my opinion the fact that you have to use a Custom AMI to be able to override the kubelet arguments is not flexible. It's nice to be able to managed nodegroup updates to the latest recommended AMI version from AWS, but if you use Custom AMI, how do you achieve that exactly?

Is there a way to disable the default merging of userdata from AWS without having to set `ImageId` explicitly in the Launch Template?

**Comment by barryib** [comment]
Closing since is has been implemented in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1138
