### ISSUE TITLE
"root_volume_size" has no effect on self-managed Windows node groups

### ISSUE THREAD

**Issue by yafanasiev** [terraform-aws-modules/terraform-aws-eks#1195]
# I have issues

Root EBS volume of self-managed Windows node groups does not change when setting "root_volume_size".

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

When adding a "root_volume_size" to node group configuration, a new EBS volume is attached to EC2 instance alongside with root volume.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```
{
      name                          = "windows-nodes"
      platform                      = "windows"
      asg_max_size                  = "4"
      asg_desired_capacity          = "4"
      asg_min_size                  = "2"
      subnets                       = REDACTED
      additional_security_group_ids = [REDACTED]
      key_name                      = "REDACTED"
      instance_type                 = "t3a.large"
      cpu_credits                   = "unlimited"
      protect_from_scale_in         = true
      kubelet_extra_args            = "--register-with-taints=\"os=windows:NoSchedule\""
      root_volume_size              = "150"
}
```

## What's the expected behavior?

Modifying this parameter should change the root volume size instead.

## Environment details

* Affected module version: 12.0.0
* OS: MacOS Big Sur
* Terraform version: v0.14.4

## Any other relevant info

The EBS volume is mounted under `/dev/xvda`, like in Linux EKS AMI's, instead of `/dev/sda1` like it should. Changing configuration to

```
      ...
      root_volume_size              = "150"
      root_block_device_name        = "/dev/sda1"
```

fixes the issue. I believe the problem is in https://github.com/terraform-aws-modules/terraform-aws-eks/blob/65777d0a37791dd1200d478e3bacc4c9a75f24c8/workers_launch_template.tf#L368
This always gets a `root_block_device_name` from Linux AMI, as specified in https://github.com/terraform-aws-modules/terraform-aws-eks/blob/65777d0a37791dd1200d478e3bacc4c9a75f24c8/local.tf#L74

**Comment by barryib** [comment]
@yafanasiev is #1401 solves your issue ?
