### ISSUE TITLE
create_elb_service_linked_role value type issue 

### ISSUE THREAD

**Issue by email2liyang** [terraform-aws-modules/terraform-aws-eks#120]
# I have issues about var create_elb_service_linked_role

* [ x ] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

in the doc, it says it's type of String 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0180644770878a28bc9511b7a0ce285c0e7454db/variables.tf#L25-L28 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0180644770878a28bc9511b7a0ce285c0e7454db/README.md#L105
but in code it's used in count, see from https://github.com/terraform-aws-modules/terraform-aws-eks/blob/405e170f90a6b0ac0ef9b1e63e622996bf28dabe/cluster.tf#L62-L65

## If this is a bug, how to reproduce? Please include a code sample if relevvant.

if you put create_elb_service_linked_role in module eks, it will generate error

sample code below

```
module "eks" {
  source                         = "terraform-aws-modules/eks/aws"
  version                        = "1.6.0"
  cluster_name                   = "${var.cluster_name}"
  subnets                        = ["${module.vpc.public_subnets}"]
  tags                           = "${local.tags}"
  vpc_id                         = "${module.vpc.vpc_id}"
  worker_groups                  = "${local.worker_groups}"
  worker_group_count             = "2"
  worker_security_group_id       = "${aws_security_group.stage-online-worker.id}"
  cluster_security_group_id      = "${aws_security_group.stage-online-master.id}"
  create_elb_service_linked_role = true
}
```

## What's the expected behavior?

it should not generate error 

## Environment details

* Affected module version: 1.6.0
* OS: mac os 10.13.2
* Terraform version:v0.11.7

**Comment by max-rocket-internet** [comment]
What is the actual error you are seeing?

**Comment by email2liyang** [comment]
when I add create_elb_service_linked_role in moduel eks, it gives error below
```
Error: Error applying plan:

2 error(s) occurred:

* module.eks.aws_iam_service_linked_role.elasticloadbalancing: 1 error(s) occurred:

* aws_iam_service_linked_role.elasticloadbalancing: Error creating service-linked role with name elasticloadbalancing.amazonaws.com: InvalidInput: Service role name AWSServiceRoleForElasticLoadBalancing has been taken in this account, please try a different suffix.
	status code: 400, request id: ffd0ca58-b1cf-11e8-b4b1-0d912c26e6a0
* module.eks.null_resource.update_config_map_aws_auth: Error running command 'kubectl apply -f ./config-map-aws-auth_stage-online.yaml --kubeconfig ./kubeconfig_stage-online': exit status 1. Output: Please enter Username: W0906 20:35:19.869596    1840 factory_object_mapping.go:423] Failed to download OpenAPI (EOF), falling back to swagger
Please enter Username: error: EOF

```

**Comment by email2liyang** [comment]
what's the actual use about his var? what I want is after I create EKS cluster, I should be able to specify a service with cluserIP in aws it should create ELB and expose service to out side of the world

**Comment by email2liyang** [comment]
if I remove var from module eks, create_elb_service_linked_role I could create eks cluster successfully

**Comment by max-rocket-internet** [comment]
The error is: `Error creating service-linked role with name elasticloadbalancing.amazonaws.com: InvalidInput: Service role name AWSServiceRoleForElasticLoadBalancing has been taken in this account`

So have you already created the service linked role in this account? It can only be created once per account.

**Comment by email2liyang** [comment]
@max-rocket-internet , yes, I checked my account, that's the case and it's already in use for an exist eks cluster. 

what value should we set for create_elb_service_linked_role? true or false or 1 as it's used in count in the module? 

what happen if I do not set the value in the module ?

Thanks

**Comment by email2liyang** [comment]
@max-rocket-internet , I check it again, all good now, I will close this issue

thanks

**Comment by max-rocket-internet** [comment]
Did it start working? Or did you create the resource outside of the module? I'm curious because I'm not 100% sure if creating the resource inside the module is the right way to go now!

**Comment by email2liyang** [comment]
as long as I can see it works
