### ISSUE TITLE
Example: Add the SPOT support for Managed Node Groups (#1129)

### ISSUE THREAD

**Issue by jseiser** [terraform-aws-modules/terraform-aws-eks#1206]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ X] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

There is no example for managed node groups, using Spot instances

## What's the expected behavior?
I would love an example.

**Comment by barryib** [comment]
The actual example for managed node group use SPOT instances.

**Comment by jseiser** [comment]
@barryib 

Sorry, somehow missed it.

I assume by that example you can't have a mixed on demand/spot instance deployment like you can using the asg style deployments?

I also don't see an option for applying additional policies to the worker nodes.
