### ISSUE TITLE
When using NodeGroups, we should be able to choose the ASG name prefix

### ISSUE THREAD

**Issue by psoares** [terraform-aws-modules/terraform-aws-eks#1215]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
When nodeGroups are used, their names are set by the key in the nodegroups map. However, the underlying ASGs have names that are generated through a name prefix. That name prefix seems to be set in workers_launch_template.tf:
```
resource "aws_autoscaling_group" "workers_launch_template" {
  // [...]
  name_prefix = join(
      "-",
      compact(
       [
          coalescelist(aws_eks_cluster.this[*].name, [""])[0],
          lookup(var.worker_groups_launch_template[count.index], "name", count.index),
          lookup(var.worker_groups_launch_template[count.index], "asg_recreate_on_change", local.workers_group_defaults["asg_recreate_on_change"]) ? random_pet.workers_launch_template[count.index].id : ""
        ]
      )
    )
  // [...]
```

I would like to be able to prioritize node autoscaling based on the name of the ASGs, which this auto-generated name makes difficult/impossible. See *Prioritizing a node group or Auto Scaling group* in  https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html.

## What's the expected behavior?
The autoscaling group should have a name start starts with/contains the name of the corresponding node group.

## Are you able to fix this problem and submit a PR? Link here if you have already.
Yes. I will try to submit a PR.

## Environment details

* Affected module version: All
* OS:
* Terraform version: All

**Comment by perryp** [comment]
Having similar problems. 
Did you find a solution to assign a name to an ASG?

**Comment by psoares** [comment]
Not yet. I'm currently migrating to Kubernetes 1.19. I'll come back to this
when I'm done.

**Comment by 1ambda** [comment]
Does managed node group support using predefined (existing) auto scaling group?

**Comment by shiron-babi** [comment]
@perryp - Any chance we can push this feature forward ?

**Comment by 1ambda** [comment]
@shiron-babi Hi, managed node groups created on EKS 1.21 have name prefix such as “eks-{nodegroupname}-{uuid}. You might use this new feature for named ASGs.
