### ISSUE TITLE
terraform eks launch config validation error

### ISSUE THREAD

**Issue by sarankals** [terraform-aws-modules/terraform-aws-eks#1216]
# I have issues

Error: Error creating launch configuration: ValidationError: gp3 is invalid. Valid volume types are standard, io1, gp2, st1 and sc1.
        status code: 400, request id: c7afb7e0-07ef-45ac-866c-09574784fbef

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

error

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Error: Error creating launch configuration: ValidationError: gp3 is invalid. Valid volume types are standard, io1, gp2, st1 and sc1.
        status code: 400, request id: 809cb07e-ea04-4420-b378-84085b4adbb9

Error: Error running command 'for i in `seq 1 60`; do if `command -v wget > /dev/null`; then wget --no-check-certificate -O - -q $ENDPOINT/healthz >/dev/null && exit 0 || true; else curl -k -s $ENDPOINT/healthz >/dev/null && exit 0 || true;fi; sleep 5; done; echo TIMEOUT && exit 1': exec: "/bin/sh": file does not exist. Output:

## What's the expected behavior?

error unable to run terraform apply

## Environment details

* Affected module version:
* OS:win10
* Terraform version:
* Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.25.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.1
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

**Comment by david-wirelab** [comment]
@sarankals you could set `root_volume_type` to `"gp2"` under `worker_groups`.
Like so:

```terraform
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "14.0.0"
.
<redacted>
.
  worker_groups = [
    {
      instance_type        = "t2.medium"
      root_volume_type     = "gp2"
    }
  ]
}
```

**Comment by sarankals** [comment]
[](url)
![Capture](https://user-images.githubusercontent.com/27405864/106616805-f7fbbc00-6593-11eb-9470-42da0fd9d305.JPG)

**Comment by sarankals** [comment]
hi david 
thanks for the update getting above error to move forward

**Comment by david-wirelab** [comment]
It seems you are trying to run this module on Windows? That one above is a bash script (Linux) so I doubt it will run on Windows unless you can install bash on it somehow.

**Comment by sarankals** [comment]
hi david , 
im running Git bash window

**Comment by david-wirelab** [comment]
Sorry I am not familiar with Windows so can't really help further. :(

**Comment by sarankals** [comment]
thanks david appreciated

**Comment by aidan-melen** [comment]
Also getting the error:

```Error: Error creating launch configuration: ValidationError: gp3 is invalid. Valid volume types are standard, io1, gp2, st1 and sc1.```

I was planning on overriding the `root_volume_type` with `gp2` until I guess the launch configuration can support the volume type.

**Comment by franko22** [comment]
It was very helpful!

**Comment by kgibcc** [comment]
Is there a work around here to run module on Windows?  Using git bash produces same error.

**Comment by barryib** [comment]
We now use gp2 as default.
