### ISSUE TITLE
node_groups configurable lifecycle ignore_changes

### ISSUE THREAD

**Issue by marekaf** [terraform-aws-modules/terraform-aws-eks#1222]
# configuration lifecycle ignore_changes in node_groups module
Hello 👋 

I'd love to configure [lifecycle ignore_changes](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/node_groups/node_groups.tf#L61
) with a variable being passed to the module 
```
  lifecycle {
    create_before_destroy = true
    ignore_changes        = [scaling_config.0.desired_size]
  }
```
or at least ignore `min_size` along with desired_size.

We have an external autoscaling that changes min_size based on schedule. This is causing a terraform drift that we'd like to get rid of.

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

I'm happy to submit a PR for this. I just need to know what is the preferred implementation.

**Comment by sidewinder12s** [comment]
You cannot use variables in lifecycle blocks unless that's changed with TF 0.15.

**Comment by marekaf** [comment]
then let's simply ignore `min_size` together with diesired_size

**Comment by abatilo** [comment]
Does this imply that if we're going to use `cluster-autoscaler` that we should just NOT use the nested `node_group` module?

**Comment by jaimehrubiks** [comment]
I don't see an easy solution here, as for many, the min_size is required to let the autoscaler remove all nodes when we need, and deploy when not. And also a way to scale-from zero which is currently not well supported in managed node groups.


@abatilo, no, the original cluster-autoscaler does not change min-size, you can use it fine.

**Comment by sandeepyy** [comment]
Even  i am facing this issue, 

Error: error creating EKS Node Group (sd-saas-prd:sd-saas-api-node-prd): ResourceInUseException: NodeGroup already exists with name sd-saas-api-node-prd and cluster name sd-saas-prd
│ {
│   RespMetadata: {
│     StatusCode: 409,
│   },
│   ClusterName: "sd-saas-prd",
│   Message_: "NodeGroup already exists with name sd-saas-api-node-prd and cluster name sd-saas-prd",
│   NodegroupName: "sd-saas-api-node-prd"
│ }
│

**Comment by bryantbiggs** [comment]
@sandeepyy this is already in the module https://github.com/terraform-aws-modules/terraform-aws-eks/blob/dc8a6eecddc2c6957ba309a939ee46f39b946461/modules/eks-managed-node-group/main.tf#L343

**Comment by bryantbiggs** [comment]
https://github.com/bryantbiggs/eks-desired-size-hack
