### ISSUE TITLE
The asg_desired_capacity is not updating

### ISSUE THREAD

**Issue by fabiofilz** [terraform-aws-modules/terraform-aws-eks#1223]
When changing the asg_desired_capacity it updates neither the Auto Scaling Groups nor the terraform.tfstate in the bucket.

  worker_groups_launch_template  = [
    {
      name                    = "core"
      spot_price              = "0.4"
      override_instance_types = ["m5.2xlarge","m5a.2xlarge"]
      asg_max_size            = 14
      asg_min_size            = 1
      asg_desired_capacity    = 9
      ami_id                  = "ami-0965e2bf3eeaXXXX"
      key_name                = "CloudFormation-eu-central-1"
      enable_monitoring       = true
      iam_role_id             = "DefaultD2EksWorkersRole"
      autoscaling_enabled     = true
      kubelet_extra_args      = "--node-labels=node.kubernetes.io/lifecycle=spot,purpose=core,ami_id=ami-0965e2bf3eeaXXXX"
      suspended_processes     = ["AZRebalance"]
    }

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by Raghav2211** [comment]
@fabiofilz Maybe this can help https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#why-does-changing-the-worker-groups-desired-count-not-do-anything
