### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by cbaenziger** [terraform-aws-modules/terraform-aws-eks#1227]
# I have issues
 I see the [README](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/4fc609bd22459fce7863872ac032d9e89d75009f/README.md#license) states this code is licensed under the MIT license and the [LICENSE](https://github.com/terraform-aws-modules/terraform-aws-eks/commit/d75e493e27399c0ba39a370a62eeb2adf24bf18c) was changed to Apache version 2 11 months ago.
 
Which license is this code released under?

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

**Comment by barryib** [comment]
cc @antonbabenko

**Comment by antonbabenko** [comment]
We stick to use Apache license everywhere in other repositories. README and [LICENSE file](https://github.com/terraform-aws-modules/terraform-aws-route53/blob/master/LICENSE) has to be updated.
