### ISSUE TITLE
could not open kubeconfig - so such file or directory

### ISSUE THREAD

**Issue by ElSamhaa** [terraform-aws-modules/terraform-aws-eks#1231]
# I have issues

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
`kubeconfig` not recreated if deleted.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
- delete `kubeconfig` after being first created
- reference the file in another peer script
- rerun `terraform apply`

## What's the expected behavior?
The file should be recreated.

## Environment details

* Affected module version: v14.0.0
* OS: Fedora 33
* Terraform version: v0.14.6

## Any other relevant info
It used to be rewritten if deleted before.

EKS code:
```terraform
module "eks" {
  source             = "terraform-aws-modules/eks/aws"

  cluster_name       = "temp-eks"
  cluster_version    = "1.18"
  subnets            = module.vpc.private_subnets
  vpc_id             = module.vpc.vpc_id
  config_output_path = ".terraform/"

  worker_groups = [
    {
      instance_type = "t3.large"
      asg_max_size  = 3
    }
  ]
  # not using the default "gp3" as it was not available in the region used to develop this script
  workers_group_defaults = {
    root_volume_type = "gp2"
  }
}
```

helm code:
```terraform
provider "helm" {
  kubernetes {
    config_path = module.eks.kubeconfig_filename
  }
}
```

output:
```
module.eks.aws_autoscaling_group.workers[0]: Refreshing state... [id=temp-eks-020210203131836867700000002]

Error: could not open kubeconfig ".terraform/kubeconfig_temp-eks": stat .terraform/kubeconfig_temp-eks: no such file or directory


Releasing state lock. This may take a few moments...
```

**Comment by vrathore18** [comment]
I am facing the same issue.

**Comment by iTaybb** [comment]
Looks like it's not an issue with `terraform-aws-eks` but with `terraform-provider-kubernetes`. Please see this issue: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1142
