### ISSUE TITLE
How to handle taints

### ISSUE THREAD

**Issue by pgvirtuoso** [terraform-aws-modules/terraform-aws-eks#1232]
How can I add some taints using this terraform?

**Comment by kkapoor1987** [comment]
Check this example
You have to pass `kubelet_extra_args` via LT
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/31ad394dbc61390dc46643b571249a2b670e9caa/examples/spot_instances/main.tf

**Comment by pgvirtuoso** [comment]
Thank you
