### ISSUE TITLE
How to keep a node_group with size = 0

### ISSUE THREAD

**Issue by marcellodesales** [terraform-aws-modules/terraform-aws-eks#1233]
# I have issues

* We don't want to delete a node_group
* We just want to set the size to 0 to clean resources

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

```console
Error: expected scaling_config.0.desired_size to be at least (1), got 0

  on .terraform/modules/eks/modules/node_groups/node_groups.tf line 11, in resource "aws_eks_node_group" "workers":
  11:     desired_size = each.value["desired_capacity"]

Error: expected scaling_config.0.desired_size to be at least (1), got 0

  on .terraform/modules/eks/modules/node_groups/node_groups.tf line 11, in resource "aws_eks_node_group" "workers":
  11:     desired_size = each.value["desired_capacity"]
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

* Setting the `desired_capacity to 0`

## What's the expected behavior?

* I can have a node_group of size 0

## Are you able to fix this problem and submit a PR? Link here if you have already.

No

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by cippaciong** [comment]
@marcellodesales if you are using managed node groups, this is an EKS feature that has not be released yet but they are working on it. See https://github.com/aws/containers-roadmap/issues/724

**Comment by adelwin** [comment]
Hi, 
can we relook at this pls?
I understand the AWS API feature for min_size = 0 and desired_size = 0 has just been released (about 2-3 days ago).
So that should be inline with this.
We can create cluster nodegroup with 0 size in eksctl in ui and also in aws-cli. terraform should be the same.

one of the use-case is to "initially" create a 0-sized nodegroup, then customize the CNI, so we dont have to end-up scaling the nodegroups 2 times, (to 0 and back) to essentially restart the nodes.

**Comment by daroga0002** [comment]
I have checked and current release of module is able to create such node groups
![image](https://user-images.githubusercontent.com/20227477/132357617-585ec48e-c638-4e92-aa17-ccd77b598a1b.png)

```
  # module.eks_cluster.module.node_groups.aws_eks_node_group.workers["node2"] will be created
  + resource "aws_eks_node_group" "workers" {
      + ami_type               = "AL2_x86_64"
      + arn                    = (known after apply)
      + capacity_type          = "ON_DEMAND"
      + cluster_name           = "eks"
      + disk_size              = 50
      + id                     = (known after apply)
      + instance_types         = [
          + "m5.xlarge",
        ]
      + node_group_name        = (known after apply)
      + node_group_name_prefix = "eksnode2"
      + node_role_arn          = "arn:aws:iam::*******:role/eks20210825103410662700000003"
      + release_version        = (known after apply)
      + resources              = (known after apply)
      + status                 = (known after apply)
      + subnet_ids             = [
          + "subnet-07a78a7e8184e3702",
        ]
      + tags                   = {
          + "Name" = "eks"
        }
      + tags_all               = {
          + "Name"    = "eks"
        }
      + version                = (known after apply)

      + scaling_config {
          + desired_size = 0
          + max_size     = 10
          + min_size     = 0
        }

      + timeouts {}

      + update_config {
          + max_unavailable            = (known after apply)
          + max_unavailable_percentage = (known after apply)
        }
    }
```
