### ISSUE TITLE
Upgrade cluster version is not supported

### ISSUE THREAD

**Issue by mkamel93** [terraform-aws-modules/terraform-aws-eks#1246]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I have provisioned an EKS cluster with Kubernetes version 1.18 successfully then I tried to update the Kubernetes version to 1.19 but when I am trying to run 
```terraform plan``` 
I got the following error: **Error: Your query returned no results. Please change your search criteria and try again.**

## What's the expected behavior?
It should update the cluster kubernetes version same as updating it from the GUI

## Environment details

* Affected module version: v14.0.0
* OS: Linux, Mac
* Terraform version: v0.14.3

**Comment by jochen-st** [comment]
same with

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.27.0
+ provider registry.terraform.io/hashicorp/helm v1.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

**Comment by italolelis** [comment]
This is related to #1141. As proposed by @dbirks, a workaround would be to set 

`worker_ami_name_filter_windows = "Windows_Server-2019-English-Core-EKS_Optimized-1.18-*"` 

even if you don't have any windows servers, at least until AWS releases the windows version to 1.19.

It worked fine for me. Thanks to @dbirks.

**Comment by aholbreich** [comment]
@italolelis work aour don't works for me. I'm using node_groups

**Comment by barryib** [comment]
I just opened https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1371 to address this. Will you please review it and test it ?
