### ISSUE TITLE
autoscaling_enabled on worker asg does not respect workers_group_defaults

### ISSUE THREAD

**Issue by zknill** [terraform-aws-modules/terraform-aws-eks#125]
# I have issues

## I'm submitting a...

* [x ] bug report

## What is the current behaviour?

Setting `autoscaling_enabled` using the format described in `workers_group_defaults_defaults` does not set the correct `cluster-autoscaler` tags on the asg instances
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/4762908d9bb8079ffebb26da7d806bbc2d5828ff/local.tf#L30

Instantiate the module with:
```hcl
module "eks" {
  // trimmed ...

  workers_group_defaults = {
    autoscaling_enabled = "true"
  }
}
```
And the worker ASG launch config is set up with tags that propagate to workers that include:
```
k8s.io/cluster-autoscaler/disabled: true
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Set on of:
* Autoscaling enabled in the worker group defaults
```hcl
  workers_group_defaults = {
    autoscaling_enabled = "true"
  }
```
* Autoscaling enabled to `true` on the worker_groups variables
```hcl
  worker_groups = "${
    list(
      map("autoscaling_enabled", "true") # anything other than the value `1` here will fail.
    )
  }"
```

## What's the expected behavior?
Setting either of the following in the module definition:
```hcl
  workers_group_defaults = {
    autoscaling_enabled = "true"
  }
```
```hcl
  worker_groups = "${
    list(
      map("autoscaling_enabled", "true")
    )
  }"
```
should produce the asg propagate tags: `k8s.io/cluster-autoscaler/enabled: true`

## Are you able to fix this problem and submit a PR? Link here if you have already.

Yes

## Environment details

* Affected module version: `1.6.0`
* OS: `Linux`
* Terraform version: `v0.11.6`

**Comment by max-rocket-internet** [comment]
I see, correct! Thanks for the issue.

We need some lookup of the default here as a fallback:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L14

**Comment by max-rocket-internet** [comment]
Fixed here: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/130
Can you confirm @zknill ?

**Comment by zknill** [comment]
@max-rocket-internet tested. It works; thanks!

**Comment by max-rocket-internet** [comment]
Great 🎉
