### ISSUE TITLE
Possible to have SSM on nodes created with Managed Node Groups?

### ISSUE THREAD

**Issue by ado120** [terraform-aws-modules/terraform-aws-eks#1254]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Currently, I do not see any flag that allows for SSM instance profiles to be attached to the nodes in a Managed Node Group at the time of creation.. Am I missing something here?

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by Nightbr** [comment]
Maybe related to #1263

Could be great to deploy the DaemonSet in this package with a simple parameters `enable_ssm_worker`.

**Comment by lgg42** [comment]
> Maybe related to #1263
> 
> Could be great to deploy the DaemonSet in this package with a simple parameters `enable_ssm_worker`.
> 
> OK after seeing #224, seems ok to manage this outside the module but my feeling is we could have a parameter to simply enable SSM on worker nodes (disabled by default) because SSM becomes a core features of AWS platform to access securely to EC2 instances.
> 
> At least, could be great to add an example in docs to install SSM manager via `pre_userdata` and `iam_role_id`.

in your locals:
```
  ssm_userdata = <<-EOT
  #!/bin/bash

  set -o errexit
  set -o pipefail
  set -o nounset

  yum install -y amazon-ssm-agent
  systemctl enable amazon-ssm-agent
  systemctl start amazon-ssm-agent
  EOT
  pre_userdata = var.enable_ssm ? chomp("${local.ssm_userdata}\n${var.pre_userdata}") : var.pre_userdata
```

then in the eks module:
```
  node_groups_defaults = {
    ami_type               = var.default_nodes_ami_type
    disk_size              = var.default_nodes_disk_space
    additional_tags        = var.default_nodes_tags
    create_launch_template = var.create_launch_template
    pre_userdata           = var.create_launch_template ? local.pre_userdata : ""
  }
  node_groups = var.node_groups
```

**Comment by barryib** [comment]
This should be possible. Use `pre_userdata` in your LT. Closing this, since we won't install SSM in this module. Everything is already provided to executed custom scripts in nodes userdata.

**Comment by ikarlashov** [comment]
Good snippet from @gg42 

Just be aware that you also need to add sufficient IAM permissions for you cluster. For that you need to specify var.workers_additional_policies. Also be aware, that you need to specify the whole ARN in a list format.
