### ISSUE TITLE
Key Pair Addition

### ISSUE THREAD

**Issue by farrukh90** [terraform-aws-modules/terraform-aws-eks#1261]
# I have issues
I have an issue with worker nodes. Is there anyway we can attach a key pair so  I can troubleshoot ec2 instances that are created with ASG? 

## I'm submitting a...

* [ ] bug report
* [*] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Current modules does not allow key pairs to be attached to ec2 ASGs 

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Build K8s from this module and you wont be able to attach key pair

## What's the expected behavior?
I should be able to attach a key pair

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by jochen-st** [comment]
I am not sure what your configuration is, but key pairs can be used with self managed worker groups (launch configuration or launch template).

See the following excerpt:
~~~
  worker_groups_launch_template = [
    {
      name                          = "WG1"
      instance_type                 = "t3a.large"
      asg_desired_capacity          = 2
      key_name                      = "YOUR_KEY_HERE"
      cpu_credits                   = "standard"
    }
  ]
~~~

Unfortunately the options for worker_groups_launch_template are not all present in the documentation. See workers_group_defaults_defaults in local.tf for valid keys: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a26c9fd0c9c880d5b99c438ad620e91dda957e10/local.tf#L28

**Comment by huguesalary** [comment]
Key pairs can also be used with "managed node groups".

All you need to do is 

1- create a key_pair:
```
resource "aws_key_pair" "eks_nodes" {
  key_name   = "eks-nodes"
  public_key = "AN SSH PUBLIC KEY"
}
```

2- create a `launch_template` that will use the key_pair you just created:
```
resource "aws_launch_template" "eks_node_with_keypair" {

  # instance_type is a required field so we need a default value.
  # t3.medium is the default value when creating a node group in the AWS Console, use that.
  instance_type = "t3.medium"

  key_name = aws_key_pair.eks_nodes.key_name
}
```

3- Use your template in your module:
```
module "my_cluster" {
  source                          = "terraform-aws-modules/eks/aws"
  version                         = "13.2.1"

  cluster_name                    = "my-cluster"
  cluster_version                 = "1.18"

node_groups = {
    main = {
      desired_capacity = 3
      max_capacity     = 10
      min_capacity     = 3
      launch_template_id = aws_launch_template.eks_node_with_keypair.id
      launch_template_version = aws_launch_template.eks_node_with_keypair.latest_version
    }
  }

}
```

**Comment by barryib** [comment]
Closing this. Since it sounds fixed.
