### ISSUE TITLE
`Unauthorized` when using an assumed role in AWS provider

### ISSUE THREAD

**Issue by ahamez** [terraform-aws-modules/terraform-aws-eks#1264]
## Description

First, thanks for the awesome work 👍!

Using the [tutorial on hashicorp.com](https://learn.hashicorp.com/tutorials/terraform/eks) as a starting point, I wanted to try to deploy an EKS using an assumed role in the `aws` provider:
```HCL
provider "aws" {
  region = "eu-west-3"
  assume_role {
    role_arn = "arn:aws:iam::BBBBBBBBBBBB:role/terraform-deployer.role"
  }
}
```
(full code below)

I thus have a user account in AWS account `A` who can assume the role `terraform-deployer.role` in the account `B` (I tested this part manually, I can switch roles in the AWS console for instance).

`terraform apply` called with an account in `A` works well until the very end where it fails with:
```
module.eks.kubernetes_config_map.aws_auth[0]: Creating...

Error: Unauthorized
```

I must add that it works without the `assume_role` when deploying with an account in `B`, so it's related to the multi-account setup. 
Also, to avoid any problem related to AWS permissions, the role in account `B` has the policy `AdministratorAccess` attached and trusts the whole account `A`.

➡️ I'm not 100% sure that it's a bug, maybe I'm missing something in the configuration. However, I can't find anything in the documentation that pertains to this specific use-case and everything I could find on the net was related to a single account setup.

## Versions

 - Terraform:
     + Terraform v0.14.7
 - Provider(s):
    + provider registry.terraform.io/hashicorp/aws v3.31.0
    + provider registry.terraform.io/hashicorp/kubernetes v2.0.2
    + provider registry.terraform.io/hashicorp/local v2.1.0
    + provider registry.terraform.io/hashicorp/null v3.1.0
    + provider registry.terraform.io/hashicorp/random v3.1.0
    + provider registry.terraform.io/hashicorp/template v2.2.0
 - Module:
    + terraform-aws-modules/eks/aws: 14.0.0

## Reproduction

- Two AWS accounts `A` and `B`
- A role in AWS account `B` with `AdministratorAccess` policy with trust the whole account `A`.

`terraform apply` with the following code:

### Code Snippet to Reproduce
```HCL
# ---------------------------------------------------------------------------------------------------
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.20.0"
    }

    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.0.1"
    }
  }

  required_version = "~> 0.14"
}

# ---------------------------------------------------------------------------------------------------
provider "aws" {
  region = "eu-west-3"
  assume_role {
    role_arn = "arn:aws:iam::BBBBBBBBBBBB:role/terraform-deployer.role"
  }
}

data "aws_availability_zones" "available" {}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.77.0"

  name            = "foo-vpc"
  cidr            = "10.0.0.0/16"
  azs             = data.aws_availability_zones.available.names
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]

  tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
  }

  public_subnet_tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
    "kubernetes.io/role/elb"                      = "1"
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
    "kubernetes.io/role/internal-elb"             = "1"
  }
}

# ---------------------------------------------------------------------------------------------------
locals {
  cluster_name = "foo"
}

# ---------------------------------------------------------------------------------------------------
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = local.cluster_name
  cluster_version = "1.19"
  subnets         = module.vpc.private_subnets

  vpc_id = module.vpc.vpc_id

  worker_groups = []
}

# ---------------------------------------------------------------------------------------------------
data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    command     = "aws"
    args = [
      "eks",
      "get-token",
      "--cluster-name",
      data.aws_eks_cluster.cluster.name
    ]
  }
}

```

## Expected behavior
It should end without an error, or at least with a clear error message (what's `Unauthorized`?).

## Actual behavior
The deployment fails with `Unauthorized`.

### Terminal Output Screenshot(s)
Here's an extract showing that everything's fine until the last moment at the creation of `module.eks.kubernetes_config_map.aws_auth[0]:`
```
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

[...]

Plan: 41 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.eks.aws_iam_policy.cluster_elb_sl_role_creation[0]: Creating...
module.eks.aws_iam_role.cluster[0]: Creating...
module.vpc.aws_vpc.this[0]: Creating...
module.eks.aws_iam_policy.cluster_elb_sl_role_creation[0]: Creation complete after 1s [id=arn:aws:iam::BBBBBB:policy/foo-elb-sl-role-creation20210307195902119800000001]
module.vpc.aws_vpc.this[0]: Creation complete after 2s [id=vpc-00984b74b58474aed]
module.vpc.aws_route_table.private[1]: Creating...
module.vpc.aws_internet_gateway.this[0]: Creating...

[...]

module.eks.null_resource.wait_for_cluster[0]: Creation complete after 2m32s [id=6734423463304295711]
data.aws_eks_cluster.cluster: Reading...
data.aws_eks_cluster.cluster: Read complete after 0s [id=foo]
module.eks.kubernetes_config_map.aws_auth[0]: Creating...

Error: Unauthorized
```

**Comment by ahamez** [comment]
Sorry closing this, wrong repository 😅 It should have been in https://github.com/hashicorp/terraform-provider-kubernetes

**Comment by asafhm** [comment]
@ahamez Couldn't find your issue on https://github.com/hashicorp/terraform-provider-kubernetes, would love to know if and how you solved it 👍

**Comment by ahamez** [comment]
@asafhm I don't recall the details, but I can share some parts of my TF files for which authentication now works without a flaw, it might help you.

Here's how the authentication is performed in the `eks` module (certainly the most important part, note the `"--role"` in `kubeconfig_aws_authenticator_command_args`):
```terraform
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "17.0.3"

  # snip

  kubeconfig_aws_authenticator_command = "aws"
  kubeconfig_aws_authenticator_command_args = [
    "eks",
    "get-token",
    "--cluster-name",
    local.full_cluster_name,
    "--role",
    local.role
  ]
}
```
And here's the authentication with the `kubernetes` provider:
```terraform
data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}
```
