### ISSUE TITLE
Unreliable ENI destroy

### ISSUE THREAD

**Issue by TjeuKayim** [terraform-aws-modules/terraform-aws-eks#1267]
## Description

I'm using Terraform to deploy an AWS EKS-cluster, an AWS Application Load Balancer, and several Helm releases, several Kubernetes resources, S3 buckets, Route53 records, and more. Everything is created in one `terraform apply` run and cleaned up in one `terraform destroy` run. However, after I refactored the Terraform declarations and upgraded Terraform modules and providers recently, I'm experiencing an issue.

The EKS cluster has two worker nodes most of the time, each EC2 instance has three associated elastic network interfaces (ENIs). When destroying, zero to two of these ENIs remain behind (always ones with a private IP), dangling with status available. This prevents Terraform from destroying the security group attached to those ENIs, so after 10 minutes the operation fails with the error `DependencyViolation for Security Group`. If I manually delete the ENI in the AWS Console and try `terraform destroy` again, the security group is destroyed successfully.

This issue is very similar to <https://github.com/terraform-aws-modules/terraform-aws-eks/issues/285> and I tried all the suggestions there, but it didn't help.

## Versions

 - Terraform: v0.15-0-dev   e9c7f37b8, v0.14.5, v0.14.0-beta2, v0.14.0-beta1, v0.14.0-alpha20201007, v0.14.0-alpha20200923, v0.14.0-alpha20200910, v0.14.0-dev a176aaa4d, v0.13.5, v0.13.2 (all versions I tried were affected)

 - Provider(s):

```
+ provider registry.terraform.io/hashicorp/aws v3.26.0
+ provider registry.terraform.io/hashicorp/helm v2.0.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

 - Module: github.com/TjeuKayim/terraform-aws-eks commit 00177596b75d184e47b03be0b6de069a7a06b4fd (from my own pull request)

## Reproduction

I'm not using workspaces.

I can reproduce the error about 80% when running `terraform apply` and `terraform destroy` on certain Git commits. That source code is not public, but I could try to develop a minimal reproduction if that's needed.

### Code Snippet to Reproduce

TODO

## Expected behavior

This Terraform module manages EKS workers and has to clean up all AWS resources on destroy.

## Actual behavior

Running `terraform destroy` leaves behind dangling ENIs in AWS in approximately 80% of the runs, resulting in errors.

### Terminal Output Screenshot(s)

Screenshot comparing a successful run (left) and failing run (right), while they both used the exact same Terraform set-up.
![image](https://user-images.githubusercontent.com/15987676/110452334-5fda8080-80c5-11eb-8f73-9d40dfe4607f.png)

See this Gist for full console logs https://gist.github.com/TjeuKayim/2b4632236f91f53f9c92a8c7c3486a78, I've also added the trace logs (`TF_LOG_PATH`). I suspect that the order of operations matters, but I'm not sure what to look for in the logs.

## Additional context

For this project, I upgraded the Terraform version multiple times and many issues were resolved, thanks for the active development in the Terraform ecosystem!

I have also contributed an improvement myself in [terraform-provider-kubernetes (merged)](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1143). For some of tests deployments, I used dev overrides to use a self-built provider, but turning that on or of didn't do anything related to this issue.

**Comment by TjeuKayim** [comment]
This issue is still present after upgrading several software components, including Terraform v0.15.0, Kubernetes v1.19, Terraform AWS provider 3.37, and aws-load-balancer-controller 1.1.5.

New insights: As my infrastructure as code evolved, I noticed that this issue went away at some point. After some experiments, I tracked down two changes that made the Terraform destroy operation succeed again.

1. Change the EC2 instance type in EKS worker groups configuration from `t2.small` to `t3a.medium`
2. Set `alb.ingress.kubernetes.io/scheme` from `internal` to `internet-facing` (and set `ip-address-type: dualstack`)

With one of these changes (or both) applied, I no longer experience dangling ENIs as described in this GitHub issue.

**Comment by GrigorievNick** [comment]
I think I meet this a few times with the latest module version 18.3.
but not every time.

**Comment by AmitKatyal-Sophos** [comment]
Any update on this issue?

**Comment by atamgp** [comment]
I see this sometimes also, need to remove the ENI's from the SG's in order for `tf destroy` to continue
