### ISSUE TITLE
Cannot use encryted EBS PVC given the examples provided

### ISSUE THREAD

**Issue by alexmnyc** [terraform-aws-modules/terraform-aws-eks#1273]
# I have issues
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/launch_templates_with_managed_node_groups/disk_encryption_policy.tf#L33

when creating this policy, i get this output

```
Error: Error creating IAM policy k8s-service-eks-node-pvc-ubmHGfaW: MalformedPolicyDocument: Policy document should not specify a principal.
	status code: 400, request id: b79cc8a5-8f70-486d-adb0-XXX

```

statement is

```
Statement = [
                  + {
                      + Action    = [
                          + "kms:ReEncrypt*",
                          + "kms:GenerateDataKey*",
                          + "kms:Encrypt",
                          + "kms:DescribeKey",
                          + "kms:Decrypt",
                        ]
                      + Effect    = "Allow"
                      + Principal = {
                          + AWS = [
                              + "arn:aws:iam::XXX:role/namespace/team/eks-services-team",
                              + "arn:aws:iam::XXX:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling_eks-ubmHGfaW",
                            ]
                        }
                      + Resource  = "arn:aws:kms:us-east-1:XXX:key/ec16e7b0-bafe-4504-a153-0a006b1d9bXX"
                      + Sid       = "AllowServiceLinkedRoleCMK"
                    },
                  + {
                      + Action    = "kms:CreateGrant"
                      + Condition = {
                          + Bool = {
                              + kms:GrantIsForAWSResource = [
                                  + "true",
                                ]
                            }
                        }
                      + Effect    = "Allow"
                      + Principal = {
                          + AWS = [
                              + "arn:aws:iam::XXX:role/namespace/team/services-team-u",
                              + "arn:aws:iam::XXX:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling_eks-team-ubmHGfaW",
                            ]
                        }
                      + Resource  = "arn:aws:kms:us-east-1:XXX:key/ec16e7b0-bafe-4504-a153-0a006b1d9bXX"
                      + Sid       = "AllowAttachmentOfPersistentResources"
                    },
                ]
```

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

fails to create policy

## If this is a bug, how to reproduce? Please include a code sample if relevant.

create a policy resource and attach existing example ebs_decryption policy document from https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/launch_templates_with_managed_node_groups/disk_encryption_policy.tf#L10

resource "aws_iam_policy" "eks_node_ebs_pvc_kms" {
  description = "${local.project_name} ${module.eks.cluster_id} EKS cluster KMS for PVCs for k8s StorageClasses policy"
  name        = "k8s-service-${local.project_name}-eks-node-ebs-kms-pvc-${module.eks.cluster_id}-u"
  path        = local.iam_path
  policy      = data.aws_iam_policy_document.ebs_decryption.json 
}

## What's the expected behavior?

a policy is created

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by mbevc1** [comment]
Also note about encryption examples, IAM policy Sid cannot have spaces.

**Comment by robgeiner** [comment]
Hey guys, the example is a bit unclear.  The issue you are hitting is that these are KEY policies, i.e. set on your key.  I stumbled on that initially also.    
```
resource "aws_kms_key" "ebs_encryption" {
  description                = "KMS Key for ebs volumes"
  enable_key_rotation = true
  policy                         = data.aws_iam_policy_document.ebs_decryption.json
} 
```
Hope that helps
