### ISSUE TITLE
Ability to use security groups for private access rules

### ISSUE THREAD

**Issue by marc-slingshot** [terraform-aws-modules/terraform-aws-eks#1275]
## Is your request related to a new offering from AWS?

No

## Is your request related to a problem? Please describe.

Unable to use security groups for private access rules.

## Describe the solution you'd like.

Add configuration option to use security groups for private access rules.

## Describe alternatives you've considered.

Use CIDR rules.

## Additional context

We are trying to setup a private access only EKS cluster.  We have a VPN setup inside of the AWS profile and it has a security group associated with it.  We would like to be able to use that security group ID to access the cluster provisioned by terraform.

Added a PR here - https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1274

**Comment by schollii** [comment]
Do you mean that you would like to use kubectl from an ec2 inside that vpc? (or otherwise make requests to api server eg from a lambda in vpc)

**Comment by marc-slingshot** [comment]
> Do you mean that you would like to use kubectl from an ec2 inside that vpc? (or otherwise make requests to api server eg from a lambda in vpc)

Yes more or less, kubernetes API access via a private-only VPC EKS cluster.

**Comment by schollii** [comment]
Have you tried adding the CIDR block of the VPC? There is a parameter for it (actually I opened a PR a couple weeks ago towards clarifying its use), that has worked for me. 

Although, that's not quite as tight as a separate SG (since any instance in the VPC would be allowed ACCESS, even a bastion host; whereas for sg approach, an attacker would have to find a way to add SG to the instance they have compromised).

**Comment by marc-slingshot** [comment]
yes I am currently implementing it with CIDR rules (see above issue description in the alternatives section), but would prefer to use a SG.

**Comment by manpreetsnehra** [comment]
I don't think that's such a bit problem. The cluster_security_group_id is in outputs you can technically just use aws_security_group_rule https://tf-registry.herokuapp.com/providers/hashicorp/aws/latest/docs/resources/security_group_rule to get your desired result.
