### ISSUE TITLE
How to deploy a new worker group to the existing cluster using this module?

### ISSUE THREAD

**Issue by alexmnyc** [terraform-aws-modules/terraform-aws-eks#1276]
How to deploy a new worker group to the existing cluster using this module?

**Comment by dfitz82** [comment]
I added a new map to "worker_groups_launch_template", but running into an issue.
The state file looks good but terraform wants to recreate the entire cluster along with the new worker group. It's as if the state file is being ignored.

**Comment by alexmnyc** [comment]
Same here

**Comment by dfitz82** [comment]
I removed all of the changes and ran a plan, but still the Terraform wants to try and create everything again.  From iam roles to asg's and the cluster itself.  I am worried this is something I have done to cause it to happen.

**Comment by brunorochadasilva** [comment]
> How to deploy a new worker group to the existing cluster using this module?

Hey @alexmnyc, which module version are you using?
Are you just trying append a new worker group to `worker_groups_launch_template` or are you changing (removind then add) in the existing map?

**Comment by alexmnyc** [comment]
@brunorochadasilva using the latest from 
```
module "eks_cluster" {
  source                        = "terraform-aws-modules/eks/aws"
```
