### ISSUE TITLE
Changing `instance_type` does not apply on AWS

### ISSUE THREAD

**Issue by mwhiter** [terraform-aws-modules/terraform-aws-eks#1281]
## Description

Previously, our EKS cluster was configured with `t2.micro` instances. However, I wanted to bump up the instances to `t2.small`. The plan said that this change would be applied, and it successfully applied, but I still see the instance type in AWS is `t2.small`.

## Versions

 - Terraform: v0.14.0

 - Provider(s): AWS Provider - no idea

 - Module: provider registry.terraform.io/hashicorp/aws v3.25.0
 - Module: provider registry.terraform.io/hashicorp/kubernetes v1.13.3

## Reproduction

1. Initialize Kubernetes cluster with `instance_type` = `t2.micro`
2. Change cluster to `instance_type` = `t2.small`
3. Execute plan and apply
3. Check cluster in Amazon EKS. Observe nodes are still `t2.micro`
![image](https://user-images.githubusercontent.com/4925402/112080940-37d52d80-8b59-11eb-8a58-b72460da87bc.png)

### Code Snippet to Reproduce

```
module "eks" {

// other data omitted...

  workers_group_defaults = {
    root_volume_type = "gp2"
  }

worker_groups = [
    {
      name                          = "worker-group-1"
      instance_type                 = "t2.small"
      asg_desired_capacity          = 4
      asg_max_size                  = 5
      asg_min_size                  = 1
      additional_security_group_ids = [aws_security_group.all_worker_mgmt.id]
    },
  ]
}
```

## Expected behavior
The AWS nodes would update to `t2.small`

## Actual behavior
The nodes are still `t2.micro`

![image](https://user-images.githubusercontent.com/4925402/112080940-37d52d80-8b59-11eb-8a58-b72460da87bc.png)

### Terminal Output Screenshot(s)

![image](https://user-images.githubusercontent.com/4925402/112081175-9bf7f180-8b59-11eb-9c11-93ca0c4ed928.png)

![image](https://user-images.githubusercontent.com/4925402/112081121-8a164e80-8b59-11eb-9317-4d782f7dc16e.png)

![image](https://user-images.githubusercontent.com/4925402/112081152-926e8980-8b59-11eb-9b8a-c39d09d497d9.png)

## Additional context
Want to bump up the instance type to increase the number of pods available.

**Comment by james-callahan** [comment]
Your launch configurations have been updated; it's up to you to restart your nodes.
e.g. you might go to "Instance refresh"

**Comment by mwhiter** [comment]
Thanks @james-callahan. I didn't know I had to do that. Will try the instance refresh on the AWS console, and update back if I have any issues, or close the ticket if it works as expected.

**Comment by mwhiter** [comment]
Closed! Thanks a lot for the help. I can now see the cluster instances are `t2.small`

**Comment by elonmusk408** [comment]
Hi
I have a query.
If I downgrade the eks cluster   instance type r5.4xlarge to r5.2xlarge via terraform. 
1.all running pods will be moved to New instance type without any lost(data/pods).?
2.any other config need to modify 
3.first i will enable the prefix_delegation in current cluster then I will downgrade the instance type , wil it leads to any loss of pods.

**Comment by daroga0002** [comment]
> 1.all running pods will be moved to New instance type without any lost(data/pods).?

if they application is  ephemeral then no issue as you dont require move data, if they use persistent storage then if this is following standard practices then persistent volume will be reattached to new pod 

> 2.any other config need to modify
be aware that best practice will be to do in two steps to avoid downtime. Create new node group in one apply and then remove legacy in second apply

> 3.first i will enable the prefix_delegation in current cluster then I will downgrade the instance type , wil it leads to any loss of pods.

pods should be recreted
