### ISSUE TITLE
Add possibility to disable `node_groups completely

### ISSUE THREAD

**Issue by Zyava** [terraform-aws-modules/terraform-aws-eks#1290]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Currently `node_groups` submodule always creates a managed node group called "default" and it is not possible to disable this behaviour. However, managed group has a lot of missing features which is possible to enable/configure via `worker_groups_launch_template`:
- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1192
- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1206
- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1214
- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1215
- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1233

It should be possible to disable `node_groups completely.

## What's the expected behavior?
`node_groups` can be disabled completely and `worker_groups_launch_template` used instead.

## Are you able to fix this problem and submit a PR? Link here if you have already.
PR: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1291

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by barryib** [comment]
I don't really understand your need. Where that "default" node group comming from ?

**Comment by Zyava** [comment]
@barryib did you even check my PR? If yes, you couldn't miss [the only functional change](https://github.com/Zyava/terraform-aws-eks/commit/025822a5f636201dd34be3e927e827b65ef94f9c#diff-f18568a32bfa70d11a736400eff74d8c51858b9fcbb8af637c14d94c3562a431R3) I made...

**Comment by barryib** [comment]
> @barryib did you even check my PR? If yes, you couldn't miss [the only functional change](https://github.com/Zyava/terraform-aws-eks/commit/025822a5f636201dd34be3e927e827b65ef94f9c#diff-f18568a32bfa70d11a736400eff74d8c51858b9fcbb8af637c14d94c3562a431R3) I made...

I saw that, but to me we on create resources if `var.node_groups` is not empty and `var.create_eks` is `true` https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/node_groups/locals.tf#L3.

**Comment by Zyava** [comment]
You are now referring to the line which was added on 19th of April while my issue and PR was created on 31st of March and ask questions which I can't answer. I didn't follow the module source code changes after I created my PR, sorry.

I don't know why my PR was ignored for 2 months and now you ask these questions.
If this issue and PR are obsolete now - feel free to close it.

**Comment by barryib** [comment]
> You are now referring to the line which was added on 19th of April while my issue and PR was created on 31st of March and ask questions which I can't answer. I didn't follow the module source code changes after I created my PR, sorry.

@Zyava that line exist since January 2020. See the submodule init PR https://github.com/terraform-aws-modules/terraform-aws-eks/pull/650

My question was simple: What is your needs and where that "default" you were mentioning coming from ?

> I don't know why my PR was ignored for 2 months and now you ask these questions.

This is community module, I'm not working alone on this. So probably someone may answer your question.

FIW, I was not available for personal matters. I work on this on personal time during long nights... So feel free to sponsor terraform-aws-modules to get the SLA you need.

I'm closing this, since we won't get anything good from our discussions.

Regards.
