### ISSUE TITLE
How to inject a launch template version for worker_groups_launch_template

### ISSUE THREAD

**Issue by alexmnyc** [terraform-aws-modules/terraform-aws-eks#1293]
Our IAM policy prohibits creation launch templates with $Default and $Latest versions. It seems that the default behavior is to use "$Latest"

Using worker_groups_launch_template, is there any way to overcome this requirement and make the module auto-generate launch template version on each run?

**Comment by barryib** [comment]
Closing because it's now implemented in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1370
