### ISSUE TITLE
Deprecated "registry.terraform.io/hashicorp/template"

### ISSUE THREAD

**Issue by tiwarisuraj9** [terraform-aws-modules/terraform-aws-eks#1294]
## Description

Terraform eks 14 module is using deprecated "template provider", which doesn't support mac m1.  Ref. https://github.com/hashicorp/terraform-provider-template
Error while running `terraform init`
```
Incompatible provider version

Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a
package available for your current platform, darwin_arm64.
```
## Versions

 - Terraform: v0.14.10

 - Provider(s): terraform-aws-modules/eks/aws

 - Module: 14.0

## Reproduction

Run terraform module terraform-aws-modules/eks/aws with version 14 on Mac M1.

### Code Snippet to Reproduce

![image](https://user-images.githubusercontent.com/36725056/114138180-7596cc00-9937-11eb-9d54-beaebc8fe971.png)

**Comment by khdevel** [comment]
There is still the problem with v0.15.0 on **darwin_arm64**

```text
Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a
package available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider
may have different platforms supported.
```

Could you write us when this out-of-date module will be replaced?
