### ISSUE TITLE
Updating asg_desired_capacity of the worker_group_spot_template does not yield updates to existing ASG's, terraform plan does not see any changes

### ISSUE THREAD

**Issue by alexmnyc** [terraform-aws-modules/terraform-aws-eks#1295]
using the latest module

worker_group_spot_template =  [
    {
      name                      = join("-", [var.cluster_name, var.worker_group_name_suffix, "spot"])

      override_instance_types = local.worker_instance_types
      asg_min_size            = var.asg_min_size
      asg_max_size            = var.asg_max_size
      asg_desired_capacity    = var.asg_desired_size // HERE
  },
]

**Comment by gijs3it** [comment]
It is by design, Auto-scaler in many clusters takes care of the Desired instances.
File: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/node_groups/node_groups.tf
Relevant part: 
```
lifecycle {
    create_before_destroy = true
    ignore_changes        = [scaling_config.0.desired_size]
}
```

**Comment by bryantbiggs** [comment]
https://github.com/bryantbiggs/eks-desired-size-hack
