### ISSUE TITLE
Support of instance storage

### ISSUE THREAD

**Issue by funes79** [terraform-aws-modules/terraform-aws-eks#1298]
## Is your request related to a new offering from AWS?

There are EC2 types coming with instance storage - instance store:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html

EC2 types such as `r5dn` or `c6gd` offers instance storage - NVMe SSD ephemeral volumes. As far as I understand this terraform eks module supports only EBS volumes. 

## Describe the solution you'd like.

Would it be possible to mount these instance storage volumes in the node groups and make those volumes available to Kubernetes? If it is already possible, how? And what is then the path inside the OS?

**Comment by dignajar** [comment]
@funes79  I'm looking the same, have you figured it out to use the ephemeral disk from the instances ? I want to use `m5d` and `g4dn` instance types and use the SSD disk that came with the instance.
