### ISSUE TITLE
WeightedCapacity is not supported in launch_template

### ISSUE THREAD

**Issue by jasonyihk** [terraform-aws-modules/terraform-aws-eks#1302]
At the moment, only instance_type is supported, as spotted in workers_launch_template.tf

 content {
      instance_type = override.value
 }

should add WeightedCapacity:

override_instance_types                     = [{"instance_type"= "t3.xlarge", "weighted_capacity"="1"}]

 content {
      instance_type = override.value.instance_type
     weighted_capacity = override.value.weighted_capacity
 }

**Comment by Xyaren** [comment]
This is still a thing...

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.0.0 :tada:
