### ISSUE TITLE
Does not work with Terraform 0.15

### ISSUE THREAD

**Issue by lispyclouds** [terraform-aws-modules/terraform-aws-eks#1303]
## Description

Terraform 0.15 removed the `list` function as part of the release and its usage in the [outputs.tf](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/outputs.tf#L11) breaks it with the new Terraform. Should be using tolist() as per the new release

## Versions

 - Terraform: 0.15

 - Module: 14.0.0

**Comment by raunyoliveira-hotmart** [comment]
There is a branch with the terraform 0.15 syntax: [https://github.com/terraform-aws-modules/terraform-aws-eks/tree/tf015-syntax](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/tf015-syntax)

Maybe @antonbabenko have more information about this?

Thanks!

**Comment by TjeuKayim** [comment]
Anton Babenko and I worked on #1164 to fix this issue, the pull request is open for a few months now.

**Comment by antonbabenko** [comment]
It was my debug in this EKS module :)

Terraform 0.15 is supported in version [v15.0.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/v15.0.0) that has been just released.

For the previous version of Terraform please use this module version `~> 14.0`.

Let us know if there are any issues with this release.

**Comment by alexfeig** [comment]
Hi @antonbabenko - thanks for all your work on this! When do you think there will be an official module release for this version?

**Comment by antonbabenko** [comment]
@alexfeig I think if we don't have it tomorrow, I will have to look into the release process for this module deeper (unfortunately, I am not aware of the right procedure yet).
