### ISSUE TITLE
Upgrade Guide

### ISSUE THREAD

**Issue by kaykhancheckpoint** [terraform-aws-modules/terraform-aws-eks#1305]
## Is your request related to a problem? Please describe.
I have a kubernertes cluster using `cluster_version = "1.18"`, i want to upgrade my cluster version to `1.19` but i don't know the steps i should take.

## Describe the solution you'd like.
An upgrade guide, readme guide would be sufficient

**Comment by ismailyenigul** [comment]
Hi @kaykhancheckpoint 
maybe this helps you #1333 
Let me know if you have any question.
