### ISSUE TITLE
Control plane security group consideration

### ISSUE THREAD

**Issue by sechunOH** [terraform-aws-modules/terraform-aws-eks#1313]
## Is your request related to a new offering from AWS?

Hello, I'm confused with different behaviors of tools. Maybe it is because I'm new to EKS, also terraform. 

With Amazon EKS security group considerations, (https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html)
it is recommended that control plane security groups have rules with below.

ingress: TCP/443/src: all node security groups
egress: TCP/1025-65535/dst: all node security groups

When I create eks clusters with eksctl, control plane security groups have above recommended rules. (of course, it creates another security group additionally for traffic between managed node group and self-managed nodes.)

I'm using eks module with version ~> 15.0.
It is coded like below.
```
resource "aws_security_group_rule" "cluster_egress_internet" {
  count             = var.cluster_create_security_group && var.create_eks ? 1 : 0
  description       = "Allow cluster egress access to the Internet."
  protocol          = "-1"
  security_group_id = local.cluster_security_group_id
  cidr_blocks       = ["0.0.0.0/0"]
  from_port         = 0
  to_port           = 0
  type              = "egress"
```

I don't know why eks module does not adopt AWS recommended security groups rules.
Should I set "cluster_create_security_group=false" and specify "cluster_security_group_id" argument for applying this recommended rules?

## Is your request related to a problem? Please describe.

not a problem.

**Comment by shiron-babi** [comment]
hey @sechunOH,

I encountered the same issue. 
Did you manage to solve it ? If so, can you share how?

Thanks

**Comment by sechunOH** [comment]
Hi, @shiron-babi 
I'm not using terraform eks module now.
I was confused that there were two different control plane SG when I created eks cluster with eks module.
I did not undertstand that behavior, so created eks module myself.

As a result, I don't create security group for control plane. I think it is created automatically when creating "aws_eks_cluster" resource.
```
resource "aws_security_group" "eks_nodes" {
  name        = "eks_nodes_sg"
  description = "Security group for all nodes in the cluster"
  vpc_id      = var.vpc_id

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    "kubernetes.io/cluster/${var.cluster_name}" = "owned"
  }
}

resource "aws_security_group_rule" "nodes" {
  description              = "Allow nodes to communicate with each other"
  from_port                = 0
  protocol                 = "-1"
  security_group_id        = aws_security_group.eks_nodes.id
  source_security_group_id = aws_security_group.eks_nodes.id
  to_port                  = 65535
  type                     = "ingress"
}
resource "aws_security_group_rule" "nodes_inbound" {
  description              = "Allow worker Kubelets and pods to receive communication from the cluster control plane"
  from_port                = 1025
  protocol                 = "tcp"
  security_group_id        = aws_security_group.eks_nodes.id
  source_security_group_id = data.aws_eks_cluster.cluster.vpc_config[0].cluster_security_group_id
  to_port                  = 65535
  type                     = "ingress"
}

data "aws_eks_cluster" "cluster" {
  name = aws_eks_cluster.this.id

  depends_on = [null_resource.wait_for_cluster]
}
```
You can refer to eks terraform module for using "null_resource.wait_for_cluster".

This answer is maybe not a 100% solution, but I hope this will be helpful for you.

**Comment by daroga0002** [comment]
I think https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1542 is answering on your concerns. Let me know if not
