### ISSUE TITLE
Allow to specify update_default_version in Launch Templates

### ISSUE THREAD

**Issue by drmaciej** [terraform-aws-modules/terraform-aws-eks#1315]
## Is your request related to a new offering from AWS?

Not a very new feature; available in terraform: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#update_default_version

## Is your request related to a problem? Please describe.

When I eyeball the launch template in AWS Console, I have to remember to select the latest version from the dropdown. If I don't, I look at a wrong version and focus on incorrect values, which leads me to troubleshooting an issue which may not be there.

## Describe the solution you'd like.

There should be a variable that allows module users to specify the value of update_default_version. To maintain backwards compatibility, it could default to `null`; `null` is what's currently set in the state file.

## Describe alternatives you've considered.

None.

**Comment by barryib** [comment]
Closing because it's now implemented in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1370
