### ISSUE TITLE
How to SSH into worker group node

### ISSUE THREAD

**Issue by kaykhancheckpoint** [terraform-aws-modules/terraform-aws-eks#1316]
I would like to SSH into the worker group nodes.

I have set `public_ip` to true and i have set the correct `key_name` that corresponds to an aws key pair.

But when i try to connect i get a connection time out error.

> 
> sudo ssh -i geeiq-prod-key<redacted>.amazonaws.com
> ssh: connect to host <redacted>.amazonaws.com port 22: Connection timed out

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = local.k8s_name
  cluster_version = "1.19"
  subnets         = data.terraform_remote_state.networking.outputs.private_subnets
  enable_irsa     = true

  tags = {
    Terraform   = "true"
    Environment = local.workspace
    GithubRepo  = "terraform-aws-eks"
    GithubOrg   = "terraform-aws-modules"
  }

  vpc_id = data.terraform_remote_state.networking.outputs.vpc_id

  workers_group_defaults = {
    root_volume_type = "gp2"
  }

  worker_groups = [
    {
      name                          = "worker-nodes"
      instance_type                 = "t2.small"
      additional_userdata           = ""
      asg_min_size                  = 1
      asg_desired_capacity          = 1
      asg_max_size                  = 5
      additional_security_group_ids = [data.terraform_remote_state.networking.outputs.eks_worker_nodes_sg_id]
      kubelet_extra_args            = "--node-labels=geeiq/node-type=worker"
      public_ip                     = true
      key_name                      = "geeiq-prod-key"
      tags = [
        {
          "key"                 = "k8s.io/cluster-autoscaler/enabled"
          "propagate_at_launch" = "false"
          "value"               = "true"
        },
        {
          "key"                 = "k8s.io/cluster-autoscaler/${local.k8s_name}"
          "propagate_at_launch" = "false"
          "value"               = "true"
        }
      ]
    },

  ]

  worker_additional_security_group_ids = [data.terraform_remote_state.networking.outputs.allow_access_from_checkpoint_sg_id]


}

data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}
```

**Comment by vertrost** [comment]
Did you open port 22 in Security groups for workernodes?

**Comment by kaykhancheckpoint** [comment]
@vertrost Yes

**Comment by inge4pres** [comment]
Hi @kaykhancheckpoint 
you got it right, private subnets do not have public connectivity by default in VPCs, so you cannot SSH into them from outside the VPC.
If you add public subnets, then you can forward the SSH connection from the instance in the public subnet to the instance in the private subnet, using its private IP (this is the suggested architecture).
e.g. if you have a public subnet instance with IP 1.2.3.4 and a private subnet instance with IP 10.2.3.4 you can do
```
$ ssh-agent
$ ssh -i geeiq-prod-key -A ec2-user@1.2.3.4
$ ip-1.2.3.4 # ssh 10.2.3.4
```
This is the same concept applied to bastion hosts.

Another workaround is to set `public_ip=true` in the worker group / launch templates definition: depending on your network config you might be able to route to the private instances by assigning them a public IP, though I'd not recommend this way.

**Comment by barryib** [comment]
Closing this. Since it's not related to terraform-aws-eks.
