### ISSUE TITLE
Warning: Deprecated Resource  The null_data_source was historically used to construct intermediate values to re-use elsewhere in configuration, the same can now be achieved using locals

### ISSUE THREAD

**Issue by Snehil03** [terraform-aws-modules/terraform-aws-eks#1323]
# I have issues
While executing terraform on my code base I am getting below warning coming from eks module
 
```
Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals

```
## I'm submitting a...

* [ ] bug report
I don't use node_groups in particular we use workers_group in our project but after the upgrade of eks 1.16 , I am getting warning mentioned above, 
on deper investigation understood that these is coming from eks module as part of node_groups.tf file,

## What is the current behavior?
gives warning mentioned as part of description

## If this is a bug, how to reproduce? Please include a code sample if relevant.
create a terraform modules eks and customized with workernodes rather then node_groups
https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/12.1.0

## What's the expected behavior?
I should not get warning mentioned as not using node_group

## Environment details

* Affected module version: terraform-aws-modules/terraform-aws-eks : 12.1.0 
* OS: 
* Terraform version: 0.13.2

## Any other relevant info
no

**Comment by barryib** [comment]
Closing this. We don't use `null_data_source` since https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v12.2.0 released in 15 Jul 2020. Please upgrade, we are now in v16.0.0.
