### ISSUE TITLE
Scale managed node groups to 0

### ISSUE THREAD

**Issue by michalschott** [terraform-aws-modules/terraform-aws-eks#1324]
I wanted to setup cluster-autoscaler to downscale my managed node groups to 0.

I have defined my node group as follows:
```
node_groups = {
  "spot_az1" = {
    max_capacity  = 70
    min_capacity  = 0
    capacity_type = "SPOT"
    k8s_labels = {
      "lifecycle" = "spot"
    }
    instance_types = [
      "m5.large",
      "m5.xlarge",
      "m5.2xlarge",
    ]
  }
...
```

Also tried `min_capacity = "0"` (string not number) but keep getting
```
Error: expected scaling_config.0.min_size to be at least (1), got 0

  on .terraform/modules/eks/modules/node_groups/node_groups.tf line 13, in resource "aws_eks_node_group" "workers":
  13:     min_size     = each.value["min_capacity"]
```

Is this on purpose or is there a limitation somewhere for managed node groups which I'm not aware of?

Best,
Michal

**Comment by codexetreme** [comment]
Hello, not sure if you found the answer to this, but managed nodes internally run an AWS ASG so its possible to scale them to 0, but EKS for some reason does not allow it, there is an open PR on the AWS GitHub repositories to implement this, but it's so far open, you can find more information here 

https://github.com/aws/containers-roadmap/issues/724

however this link - https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-scale-a-node-group-to-0 

says that you can do it via an autoscaler and some special annotations on the EC2 VMs (although, please note that I am not sure if this cluster autoscaler is working on an EKS cluster or a custom k8s cluster setup on EC2 instances)

Hope this helps :)

**Comment by michalschott** [comment]
So it looks like this is just not supported in managed node groups. This is exactly the answer I was looking for, thanks.

**Comment by codexetreme** [comment]
I am glad that helped :), so I think this PR can be closed, probably the maintainers have to do that though. not sure
