### ISSUE TITLE
add tags to underlying resource aws_iam_policy

### ISSUE THREAD

**Issue by vadivkanag** [terraform-aws-modules/terraform-aws-eks#1328]
## Is your request related to a problem? - Yes
Could you please add tags to these resource as well, its failing in our compliance check.

## Describe the solution you'd like.
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/cluster.tf#L167
```shell
resource "aws_iam_policy" "cluster_elb_sl_role_creation" {
 .....
 tags = var.tags
}
```
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers_launch_template.tf#L557
```shell
resource "aws_iam_instance_profile" "workers_launch_template" {
 ......
 tags = var.tags
}
```

**Comment by barryib** [comment]
Closing. This has been added with https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1321
