### ISSUE TITLE
Terraform init throws error  : Error: Failed to download module

### ISSUE THREAD

**Issue by Snehil03** [terraform-aws-modules/terraform-aws-eks#1330]
# I have issues
Terraform init does not run successfully on Bitbucket pipelines during initial first run

## I'm submitting a...

* [ I am facing issue with respect to running terraform init in Bitbucket Pipelines, wheras these code works on local machine ] bug report

I saw these bug reported multiple times and solution provided 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/versions.tf 
but even after the changes suggested not able to run it via CI server 

error :
```
+ terraform init
Initializing modules...
- aws-services in ../../modules/aws-services
- cluster in ../../modules/cluster
Downloading terraform-aws-modules/eks/aws 12.2.0 for cluster.eks...
Downloading terraform-aws-modules/vpc/aws 3.0.0 for cluster.vpc...
- elasticsearch in ../../modules/elasticsearch
- ingress in ../../modules/ingress
- ingress.letsencrypt_issuers in ../../modules/k8s_manifest
- ingress.wildcard-domain-certificate in ../../modules/wildcard-certificate
- ingress.wildcard-domain-certificate.k8s_manifest_domain_wildcard in ../../modules/k8s_manifest
- ingress.wildcard-subdomain-certificate in ../../modules/wildcard-certificate
- ingress.wildcard-subdomain-certificate.k8s_manifest_domain_wildcard in ../../modules/k8s_manifest
- k8s_cluster_config in ../../modules/k8s_cluster_config
- k8s_cluster_config.k8s_pod_network_policies in ../../modules/k8s_manifest
- k8s_cluster_config.k8s_pod_security_policy in ../../modules/k8s_manifest
- kubed in ../../modules/kubed
- monitoring in ../../modules/monitoring
Error: Failed to download module
Could not download module "eks" (../../modules/cluster/eks.tf:1) source code
from
"git::https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v12.2.0":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v12.2.0': git
must be available and on the PATH.
Error: Failed to download module
Could not download module "vpc" (../../modules/cluster/vpc.tf:1) source code
from
"git::https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v3.0.0":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v3.0.0': git
must be available and on the PATH.
Error: Failed to download module
Could not download module "eks" (../../modules/cluster/eks.tf:1) source code
from
"git::https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v12.2.0":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v12.2.0': git
must be available and on the PATH.
```

local configurations 

terraform version 
Terraform v0.13.2
+ provider registry.terraform.io/carlpett/sops v0.6.2
+ provider registry.terraform.io/hashicorp/aws v3.37.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/helm v2.1.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

## What is the current behavior?
terraform init ends with error 

## If this is a bug, how to reproduce? Please include a code sample if relevant.
take a sample code and try to use bitbucket pipelines first time to do terraform init, it does not work .

## What's the expected behavior?
it should initialize all the terraform modules

## Are you able to fix this problem and submit a PR? Link here if you have already.
No

## Environment details
Test 

* Affected module version: eks
* OS: Linux 
* Terraform version: 0.13.2

**Comment by codexetreme** [comment]
According to your log

```
Could not download module "eks" (../../modules/cluster/eks.tf:1) source code
from
"git::https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v12.2.0":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v12.2.0': git
must be available and on the PATH.
```
it says git must be on the path, I am just shooting in the dark here, but could you verify that git is infact on path?
