### ISSUE TITLE
`kubelet_extra_args` failed with docker config pushed in `pre_userdata`

### ISSUE THREAD

**Issue by llavaud** [terraform-aws-modules/terraform-aws-eks#1337]
## Description

Setting a docker config on managed nodes using the `pre_userdata` parameter fail the `kubelet_extra_args`.
If another command is executed in `pre_userdata` this works correctly, so it seems related to the creation of the `config.json` file in the `/var/lib/kubelet` folder that must trigger something. 

## Versions

 - Terraform: 0.15.1

 - Provider(s):
registry.terraform.io/hashicorp/aws v3.38.0
registry.terraform.io/hashicorp/cloudinit v2.2.0
registry.terraform.io/hashicorp/kubernetes v2.1.0
registry.terraform.io/hashicorp/local v2.1.0
registry.terraform.io/hashicorp/null v3.1.0
registry.terraform.io/hashicorp/random v3.1.0
registry.terraform.io/hashicorp/template v2.2.0

 - Module: v15.2.0

## Reproduction
define a `pre_userdata` and a `kubelet_extra_args` module inputs.

### Code Snippet to Reproduce
```
create_launch_template = true

pre_userdata = <<EOT
mkdir -p /var/lib/kubelet
cat <<EOF >/var/lib/kubelet/config.json
{
  "auths": {
    "myregistry.example.com": {
      "auth": "xxx"
    }
  }
}
EOT

kubelet_extra_args = "--system-reserved-cgroup=/system-reserved --system-reserved=cpu=200m,memory=500Mi --kube-reserved-cgroup=/kube-reserved --kube-reserved=cpu=200m,memory=500Mi"
```

## Expected behavior
`/etc/eks/bootstrap.sh` must be updated like the following:
```
KUBELET_EXTRA_ARGS="${KUBELET_EXTRA_ARGS:-}"
KUBELET_EXTRA_ARGS+=" --system-reserved-cgroup=/system-reserved --system-reserved=cpu=200m,memory=500Mi --kube-reserved-cgroup=/kube-reserved --kube-reserved=cpu=200m,memory=500Mi"
```

## Actual behavior
`/etc/eks/bootstrap.sh` is not updated:
```
KUBELET_EXTRA_ARGS="${KUBELET_EXTRA_ARGS:-}"
```

**Comment by ArchiFleKs** [comment]
@llavaud are you using custom AMI or official AMI ?

**Comment by ArchiFleKs** [comment]
@llavaud Maybe it is just a typo but you have EOF and EOT so your example would not work

**Comment by llavaud** [comment]
> @llavaud Maybe it is just a typo but you have EOF and EOT so your example would not work

Ho my bad, you totaly right, I forgot the EOF when I pasted the code from my custom launchtemplate.
Shame on me !
