### ISSUE TITLE
kubernetes provider not working when adding cluster_encryption_config to module configuration

### ISSUE THREAD

**Issue by jslusher** [terraform-aws-modules/terraform-aws-eks#1338]
## Description
I'm getting an error about permissions to the `aws-auth` configmap when I try to add a `cluster_encryption_config` block to the eks module that created my running EKS cluster. It's referencing the local Github Actions runner, which was the error I was getting before I added a kubernetes `provider` block, and so I suspect there's something about adding it that causes it to ignore that block.

## Reproduction
Create a cluster without setting a `cluster_encryption_config` block and then add the block to the module.

### Code Snippet to Reproduce
```
resource "aws_kms_key" "my-eks-cluster" {
  description = "my-eks-cluster"
}

data "aws_eks_cluster" "my-eks-cluster" {
  name = module.my-eks-cluster.cluster_id
}

data "aws_eks_cluster_auth" "my-eks-cluster" {
  name = module.my-eks-cluster.cluster_id
}

provider "kubernetes" {
  host = data.aws_eks_cluster.my-eks-cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.my-eks-cluster.certificate_authority.0.data)
  token = data.aws_eks_cluster_auth.my-eks-cluster.token
}

module "my-eks-cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "my-eks-cluster"
  cluster_version = "1.19"
  cluster_endpoint_public_access = false
  cluster_endpoint_private_access = true
  cluster_create_endpoint_private_access_sg_rule = true

  #cluster_encryption_config = [
    #{
      #provider_key_arn = aws_kms_key.my-eks-cluster.arn
      #resources        = ["secrets"]
    #}
  #]

  cluster_endpoint_private_access_cidrs = [
    var.vpn-subnet,
    var.vpc-ipv4-subnet
  ]

  subnets         = [
    var.control-plane-eks-subnet-a-id,
    var.control-plane-eks-subnet-b-id,
    var.control-plane-eks-subnet-c-id,
  ]

  map_roles = [
    {
      rolearn = aws_iam_role.mng-eks-west.arn
      username = "system:node:{{EC2PrivateDNSName}}"
      groups = [
        "system:bootstrappers",
        "system:nodes"
      ]
    }
  ]

  vpc_id          = var.main-vpc-id
}
```
## Expected behavior
I would expect to be able to add the kms encryption config to the existing cluster or at least get a message that I can't for some reason.

## Actual behavior
```
Error: configmaps "aws-auth" is forbidden: User "system:serviceaccount:actions-runner-system:default" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
```

I also tried using this provider block option: 

```
provider "kubernetes" {
  host                   = data.aws_eks_cluster.default.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.default.certificate_authority[0].data)
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    args        = ["token", "--cluster-id", module.vpc.cluster_name]
    command     = "aws-iam-authenticator"
  }
}
```

The problem is that it doesn't seem to recognize that there's a `provider` block at all.

**Comment by mlopez-eb** [comment]
Perhaps a similar issue, but when I add both those blocks, I get the following error:

`Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp [::1]:80: connect: connection refused`

I also attempted to only comment out the `cluster_encryption_config` block, and it successfully planned out the changes. Not sure if the issues have to do with each other but they seem similar to me in a sense.

**Comment by fydrah** [comment]
I have the same issue, I think this could be related to the usage of [provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#encryption_config) block for aws_eks_cluster resource (see: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1d848b56bf7c43ce708bd7cdee45589f816e05f0/cluster.tf#L38)
Maybe this "provider" block (required by eks_cluster resource) overrides the kubernetes provider block defined in the same plan? I don't know how and why, but it's the only link between the encryption config block and the kubernetes provider block..

**Comment by philicious** [comment]
I think this error is new and not the same as #911 . those usually happened because of incomplete configuration of the kubernetes provider.

however, I see the exact same error as @mlopez-eb , when trying to enable encryption, on clusters that exist for almost a year and have been managed and updated thru TF dozen times flawlessly
