### ISSUE TITLE
Fix: Comcast's kuberhealthy hosting changed and repository pointers need to be updated

### ISSUE THREAD

**Issue by xenoglaux88** [terraform-aws-modules/terraform-aws-eks#1352]
## Description
5/12/2021 Comcast migrated the helm chart hosting for kuberhealthy from `comcast.github.io` -> `kuberhealthy.github.io`. As a result, `./eks-jx.health.jx-health/main.tf` repository url needs to be updated to `https://kuberhealthy.github.io/kuberhealthy/helm-repos`. Furthermore, this has a dependency on a fix being added to kuberhealthy as well since their index.yaml didn't get updated when they did the migration. So once the repo link is fixed, the following error will occur until the Dependency issue below is resolved.

```
Error: failed to download "https://comcast.github.io/kuberhealthy/helm-repos/archives/kuberhealthy-64.tgz" at version "64" (hint: running `helm repo update` may help)

  on .terraform/modules/eks-jx.health.jx-health/main.tf line 1, in resource "helm_release" "kuberhealthy":
   1: resource "helm_release" "kuberhealthy" {
```

Dependency on Issue: [Kuberhealthy Issue](https://github.com/kuberhealthy/kuberhealthy/issues/938) as the helm deploy will try to download the charts from a url that doesn't exist.

## Versions
 - Terraform: 14.11
 - Provider(s): AWS (probably all)
 - Module: eks-jx.health.jx-health

## Reproduction

`terraform apply`

## Expected behavior

Successful deployment

## Actual behavior

Error that the https://comcast.github.io/kuberhealthy/helm-repos doesn't exist.
### Terminal Output Screenshot(s)

I can post later, but not in a place to reproduce as I fixed locally, and can only show the secondary error currently. Will update later of needed.

**Comment by xenoglaux88** [comment]
Did this get fixed, I tried a clean pull today of the modules and it seemed to be fixed already. Not sure what ticket that was done in though.

**Comment by daroga0002** [comment]
I dont know how this is related to this terraform module as seems be some 3rd party issue.

**Comment by xenoglaux88** [comment]
Well one of the terraform modules that deployed kuberhealthy was pointing to the wrong url. I fixed it manually locally. Looks like someone got it thought
