### ISSUE TITLE
metadata options block not supported in node_groups

### ISSUE THREAD

**Issue by primeroz** [terraform-aws-modules/terraform-aws-eks#1353]
## Is your request related to a problem? Please describe.
The `metadata options` block is only supported in the `workers` but not in the `node_groups` https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1301

my understanding is that we could use this options to block access to metadata endpoint from workloads and force the use of IRSA as explained [here](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node)

Is this on purpose ? 

I use node_groups to get managed_groups and i would rather not have to switch to un-managed worker groups. 

## Describe the solution you'd like.
Support `metadata options` on the node_group

## Describe alternatives you've considered.
Calico policy - they work.

## Additional context
I am willing to do a PR but first wanted to check if there is any reason why this was not implemnted in the same PR as the worker_groups one

**Comment by jmorgan415** [comment]
> We forgot that MNG now support LT. So please open a PR. I'll happy to review it.

I've created a branch locally for this and will submit a PR since this is a pressing issue or us and I haven't seen a PR form the author.

**Comment by antonbabenko** [comment]
Fixed in #1485

Please use module [v17.18.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/v17.18.0).
