### ISSUE TITLE
Always create fargate role

### ISSUE THREAD

**Issue by james-callahan** [terraform-aws-modules/terraform-aws-eks#1356]
## Is your request related to a new offering from AWS?

No

## Is your request related to a problem? Please describe.

When manually managing aws_auth configmap, you need a manual process to be able to add the fargate role.
However, when you do not specify any fargate profiles, the role is not created: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/781f673295dd69d24c85d10b47cb03507f394402/modules/fargate/locals.tf#L2
This means that the fargate role gets recreated if you have an intermediate state of no active profiles; and hence (because of using `name_prefix` rather than a specific `name`) needing to update your manually managed aws_auth configmap.

## Describe the solution you'd like.

Remove the `&& length(var.fargate_profiles) > 0` from the condition of when to create the fargate IAM role

## Describe alternatives you've considered.

An additional variable to the fargate submodule `always_create_role` -> this seems like needless complexity, though if its less objectionable then that would be fine.

**Comment by daroga0002** [comment]
If I understand correctly, I don't think that creating a fargate role always will be a good idea. Many organizations are not using this feature and don't want to enable it. 

aws_auth management can be disabled using input parameter `manage_aws_auth`:
![image](https://user-images.githubusercontent.com/20227477/118991393-fe1b7a00-b983-11eb-8d16-fecf63952a61.png)

**Comment by james-callahan** [comment]
> aws_auth management can be disabled using input parameter `manage_aws_auth`

Yes.... I mentioned that in the issue. This seems like a non-sequitur?

**Comment by daroga0002** [comment]
Ok, seems I not understood your issue. 

So if we will go with proposed way to remove `&& length(var.fargate_profiles) > 0`  then only two resources will be created:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/781f673295dd69d24c85d10b47cb03507f394402/modules/fargate/fargate.tf


without `aws_eks_fargate_profile` what I think will cause that it doesnt make sense (correct me if I am wrong as I dont have experience with Fargate on EKS)

**Comment by james-callahan** [comment]
>  then only two resources will be created:

yes, the `aws_iam_role` and `aws_iam_role_policy_attachment`.



> without `aws_eks_fargate_profile` what I think will cause that it doesnt make sense (correct me if I am wrong as I dont have experience with Fargate on EKS)

0-to-many `aws_eks_fargate_profile` may be created/managed. The non-existence of any profiles shouldn't mean the `aws_iam_role` isn't created.

**Comment by daroga0002** [comment]
> 0-to-many `aws_eks_fargate_profile` may be created/managed. The non-existence of any profiles shouldn't mean the `aws_iam_role` isn't created.

But fargate  profile as per AWS is required to schedule a pod:
```
Before you can schedule pods on Fargate in your cluster, you must define at least one Fargate profile that specifies which pods should use Fargate when they are launched.
```

so I still not understand what is sense to create role and attachment without profile.  Maybe you can more briefly iterate what is you use case (where you creating fargate profiles)?

**Comment by james-callahan** [comment]
> Maybe you can more briefly iterate what is you use case (where you creating fargate profiles)?

1. create EKS cluster by applying terraform module (setting `manage_aws_auth = false`) with e.g. one fargate profile "foo"
2. manually manage aws_auth via e.g. a gitops workflow; this involves using `terraform state show module.eks.module.fargate.aws_iam_role.eks_fargate_pod` and committing it to a different repo
3. for some reason (e.g. changing workloads), disable the fargate profile "foo" (by applying this module). 
4. add a new fargate profile "bar" => be confused why you're getting permission errors

Step 3 **currently** destroys the fargate role as there are 0 profiles defined. Only for a role to be created again in step 4; but because the role using `name_prefix`, it does not match the contents of aws_auth.

**Comment by daroga0002** [comment]
ok, so it seems be specific only to your `hybrid` workflow.

Question does steps 3,4 can be in reverted order? Then it should be working you without issue.

**Comment by james-callahan** [comment]
> Question does steps 3,4 can be in reverted order? Then it should be working you without issue.

no; they may occur months apart at the will of various teams sharing the EKS cluster.

**Comment by barryib** [comment]
@james-callahan @daroga0002 thanks for this clarification.

@james-callahan If you open a PR, we'll be happy to review it.

**Comment by james-callahan** [comment]
#1429 updated.

**Comment by daroga0002** [comment]
more details in [PR](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1429), but such `hybrid` custom workloads should be covered by user specific code implementation (current module implementation is fully providing and supporting outputs which can be used in custom code)
