### ISSUE TITLE
Unauthorized error when executing kubectl

### ISSUE THREAD

**Issue by lpossamai** [terraform-aws-modules/terraform-aws-eks#1358]
## Description

After creating the cluster from another IAM user, I can no longer execute `kubectl`. Gives me the following error:

`error: You must be logged in to the server (Unauthorized)`

The command `update-kubeconfig` returns a successful message.
`aws eks --region ap-southeast-2 update-kubeconfig --name test-cluster`

## Versions

 - Terraform:
0.14.9
 - Provider(s):
aws v3.40.0
 - Module:
terraform-aws-modules/eks/aws (latest version)

## Code

Terraform code:

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = local.cluster_name
  cluster_version = "1.19"
  subnets         = module.vpc.private_subnets

  vpc_id = module.vpc.vpc_id

  workers_group_defaults = {
    root_volume_type = "gp2"
  }

  worker_groups = [
    {
      name                          = "worker-group-1"
      instance_type                 = "t2.small"
      additional_userdata           = "echo foo bar"
      asg_desired_capacity          = 2
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_one.id]
    },
    {
      name                          = "worker-group-2"
      instance_type                 = "t2.medium"
      additional_userdata           = "echo foo bar"
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_two.id]
      asg_desired_capacity          = 1
    },
  ]
}

data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}
```

**Comment by barryib** [comment]
Please refer to the EKS documentation for authentication with kubectl.

**Comment by mkochco** [comment]
@lpossamai - I hope you resolved your issue.  Here's hopefully a more helpful response.  There are `map_roles` and `map_users` fields/vars on the eks module.  IIUC I believe you can use those to allow  users/roles other than the creator to use kubectl.

e.g.
```
map_roles = [
  {
    rolearn  = "arn:aws:iam::############:role/whateverroleyouwanttogiveaccess"
    username = "Admins"
    groups   = ["system:masters"]
  },
]
```
