### ISSUE TITLE
Network interfaces are missing tags

### ISSUE THREAD

**Issue by alexmnyc** [terraform-aws-modules/terraform-aws-eks#1361]
Please add a network interface tag specificiton to inherit parent tags here 

```
tag_specifications {
         resource_type = "network-interface"
         tags =  var.tags merge with defaults
        }
```

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/32f70afe602cc96e89f31e3562bf237d80482a4b/workers_launch_template.tf#L255

**Comment by barryib** [comment]
Thanks for opening this issue. @alexmnyc Can you please open a PR to address this ?

**Comment by alexmnyc** [comment]
Sure thing

**Comment by alexmnyc** [comment]
Done https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1362

**Comment by alexmnyc** [comment]
bump

**Comment by alexmnyc** [comment]
PR is here https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1362

**Comment by nikitacr7** [comment]
Hello @barryib , @antonbabenko 
Do you have any plans to implement it? It looks like it's already implemented in https://github.com/hashicorp/terraform-provider-aws/pull/20409

**Comment by antonbabenko** [comment]
Yes, it is now possible to add, please make a pull request for this feature. See similar PR #1397.

**Comment by nikitacr7** [comment]
Hello @antonbabenko 

Please review the PR: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1563
