### ISSUE TITLE
Instance Refresh not triggering on launch_template changes

### ISSUE THREAD

**Issue by Patricol** [terraform-aws-modules/terraform-aws-eks#1365]
## Description

With the new instance refresh functionality, changes to the launch template will not trigger a refresh, because the `autoscaling_group`'s `launch_template` block does not actually change if its `version = $Latest`, as is the case by [default](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/acbf51c33342ce2b1d6b05f55ee9e149e7c26621/local.tf#L78).

This is unexpected based on the comment [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/acbf51c33342ce2b1d6b05f55ee9e149e7c26621/local.tf#L102): `A refresh will always be triggered by a change in any of launch_configuration, launch_template, or mixed_instances_policy.`

I tested by changing `ami_id` multiple times; which never triggered an instance refresh.

All of the terraform resources appear to be created correctly; and I'm on the newest AWS provider (`3.40.0`).

I think this was just a misunderstanding of the intended behavior of `aws_autoscaling_group`'s `instance_refresh` block.

I suppose this module could handle bumping an explicitly set `launch_template` `version`.

## Versions

 - Terraform: `v0.14.11`

 - Provider(s):
```
+ provider registry.terraform.io/hashicorp/aws v3.40.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.3.0
```
 - Module: `16.0.0`

## Reproduction
Skipping most repro descriptions because the module does correctly setup all the resources; they just don't behave as documented.

**Comment by barryib** [comment]
@Patricol Thanks for opening this. @bashims can you please have a look ?

**Comment by barryib** [comment]
@Patricol did you tried the [instace refresh's example](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/instance_refresh) ? Is that example works for you ? Can you please share your configuration ?

**Comment by bashims** [comment]
@barryib absolutely.

@Patricol  can you try changing/adding a tag to the example ASG config. That should trigger the refresh.

In the meantime I will take a closer look to see what's going on.

**Comment by bashims** [comment]
@Patricol as a work around please add the following to your `worker_groups_launch_template`:
```
      instance_refresh_triggers            = ["tag"]
      tags = [
        {
          key                 = "test_trigger_refresh"
          value               = "true"
          propagate_at_launch = true
        },
     ]
```

**Comment by bashims** [comment]
@barryib I'm working on a fix now. We need to bump/change the launch_template version to trigger the instance_refresh. Triggering from `tags` works fine however.

**Comment by Patricol** [comment]
@bashims That does work for me.

I'll try the example code soon.

**Comment by stevehipwell** [comment]
@bashims is there a reason why the node termination handler policy is added to the worker node role in the example?

**Comment by barryib** [comment]
> @bashims is there a reason why the node termination handler policy is added to the worker node role in the example?

Nope. It should be attached to the node termination handler through IRSA.

**Comment by stevehipwell** [comment]
@barryib that's what I thought. Would you like me to also add the the spot instance termination and rebalance suggestion events to the example queue from the [aws-node-termination-handler repo docs](https://github.com/aws/aws-node-termination-handler#4-create-amazon-eventbridge-rules) ?

**Comment by barryib** [comment]
> @barryib that's what I thought. Would you like me to also add the the spot instance termination and rebalance suggestion events to the example queue from the [aws-node-termination-handler repo docs](https://github.com/aws/aws-node-termination-handler#4-create-amazon-eventbridge-rules) ?

Yes you can if it's simple. Please add a link to the NTH docs also. People must follow that docs. The example is there for help only and not to address every NTH use cases.

**Comment by stevehipwell** [comment]
@barryib https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1373.

**Comment by barryib** [comment]
> @barryib #1373.

Thanks. Merged.

**Comment by bashims** [comment]
> @bashims is there a reason why the node termination handler policy is added to the worker node role in the example?

I believe it is uses IRSA so it there is no need for attaching it to the worker node role. This was probably a leftover i.e. before I switched to IRSA.
