### ISSUE TITLE
Error: Cycle issue with the version v16.0.0

### ISSUE THREAD

**Issue by ae250060** [terraform-aws-modules/terraform-aws-eks#1368]
## Description

With the release of v16.0.0, we have exprienced the following issue with terraform apply:

Error: Cycle: module.my-eks-cluster.aws_iam_instance_profile.workers[0], module.my-eks-cluster.aws_launch_configuration.workers[0], module.my-eks-cluster.random_pet.workers[0] (destroy), module.my-eks-cluster.aws_launch_configuration.workers[0] (destroy deposed 53a4ae45), module.my-eks-cluster.null_resource.wait_for_cluster[0] (destroy), module.my-eks-cluster.aws_autoscaling_group.workers[0]

## ⚠️ Note

And we have alredy done the following before submiting the issue.

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions
v16.0.0
 - Terraform:
0.13.7
 - Provider(s):
aws        =  v3.40.0
local      = v2.1.0
random = v3.1.0
      
This actually start to happen with the v16.0.0 release.

**Comment by daroga0002** [comment]
can you paste whole plan as seems there is some replacement on workers

**Comment by ae250060** [comment]
Hello @daroga0002,

Thanks for your fast reply please find below the plan attached.

Cheers
[plan.txt](https://github.com/terraform-aws-modules/terraform-aws-eks/files/6509863/plan.txt)

**Comment by daroga0002** [comment]
reason of change is:

```
  # module.xxx-yyy-eks-test.aws_launch_configuration.workers[0] must be replaced
  ..........
     ~ image_id                         = "ami-00a182929447c6963" -> "ami-07edd1ff4d841185c" # forces replacement
  ..........
```

does you passing manually a AMI for workers or fetching dynamically from somewhere?

**Comment by ae250060** [comment]
That actually comes from the terraform-aws-eks module it self precisely from here:

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf

and this part in the code:

`
  image_id = lookup(
      
      
            var.worker_groups[count.index],
      
      
            "ami_id",
      
      
            lookup(var.worker_groups[count.index], "platform", local.workers_group_defaults["platform"]) == "windows" ? local.default_ami_id_windows : local.default_ami_id_linux,
      
      
          )`

So it's an expected behaviour.

**Comment by barryib** [comment]
In v16.0.0 we droped random_pets for LC/LT and local-exec for waiting for cluster. Those destroy are probably causing cycle. Can you please backup your state and then remove random_pets and null_resource and retry an apply ?

```shell
terraform state rm module.my-eks-cluster.random_pet.workers
terraform state rm cluster.null_resource.wait_for_cluster
```

**Comment by ae250060** [comment]
@barryib that works fine thanks, is there a way to avoid this before actulally going to the v16.1.0 version? any adaptions we should carry on while on version v15.2.0 to avoid having to modify the state manually? Just our of curiosity !

**Comment by daroga0002** [comment]
> @barryib that works fine thanks, is there a way to avoid this before actulally going to the v16.1.0 version? any adaptions we should carry on while on version v15.2.0 to avoid having to modify the state manually? Just our of curiosity !

I think the good answer here is just to observe `BREAKING CHANGES` mark in changelog before upgrade

**Comment by ae250060** [comment]
got it @daroga0002 thank you all for the great help will the issue.
