### ISSUE TITLE
Error in TF plan after EKS 1.20 upgrade

### ISSUE THREAD

**Issue by Ghazgkull** [terraform-aws-modules/terraform-aws-eks#1376]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

After upgrading an EKS cluster to 1.20, attempts to run `terraform plan` result in an error from this module:
```
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│
│   on .terraform/modules/eks/data.tf line 27, in data "aws_ami" "eks_worker_windows":
│   27: data "aws_ami" "eks_worker_windows" {
│
```

## Versions

 - Terraform:
 $ terraform -version
Terraform v0.15.0
on darwin_amd64
 - Provider(s):
$ terraform providers -version
Terraform v0.15.0
on darwin_amd64
 - Module:
v16.0.1 (also failed the same way on v15.1.0)

## Reproduction

Using the same Terraform configuration of this module that has been working successfully for years, we're seeing an error from this module after upgrading our clusters to Kubernetes 1.20 on EKS.

It looks like something changed on the AWS side which is causing a lookup of a windows AMI to fail? Note that we're using the default AWS EKS AMI, not windows.

### Code Snippet to Reproduce

I could share my config, but I think this is going to be a general problem that's not related to configuration... since it's an internal data lookup in the module.

**Comment by barryib** [comment]
This has been fixed in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1371. Will release it in few hours.

**Comment by darkn3rd** [comment]
I am having this issue with Linux.   What version can I use that doesn't have this issue?
