### ISSUE TITLE
Setting priority on worker groups for auto scaling

### ISSUE THREAD

**Issue by AlecZebrick** [terraform-aws-modules/terraform-aws-eks#1379]
It's possible I'm missing something reading over the docs, but I'd like a way to set priorities among the worker groups. I'm currently using this in a kubeflow eks deployment in which I use expensive p3 gpu-enabled spot instances for ML. I am trying to set it up in a way where this gpu worker group is a lower priority on auto scaling than my on-demand instances for general purpose computing. 

Something akin to the priorities section here:

piVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    10:
      - .*-non-existing-entry.*
    20:
      - eksctl-ai-us-west-2-nodegroup-p3od-NodeGroup-NKHMN74TFOPF
    60:
      - eksctl-ai-us-west-2-nodegroup-p3spot-NodeGroup-1EC86FRMZ7V6N

Is this already a feature?

**Comment by daroga0002** [comment]
how this is related to this terraform module?

**Comment by AlecZebrick** [comment]
Ah sorry if the syntax there was confusing. I am indeed referring to this module and am currently launching my cluster with the following worker group config:

    ```
worker_groups = [
    {
      name                = "Worker-Spot"
      spot_price          = "2.00"
      instance_type       =  ["m5.large", "c5.large"]
      ami_id              = data.aws_ami.eks_worker_ami.id
      asg_max_size        = 15
      asg_min_size        = 5
      asg_desired_capacity= 7

      kubelet_extra_args  = "--node-labels=node.kubernetes.io/lifecycle=spot"
      suspended_processes = ["AZRebalance"]
      tags = [
        {
          "key"                 = "k8s.io/cluster-autoscaler/enabled"
          "propagate_at_launch" = "false"
          "value"               = "true"
        },
        {
          "key"                 = "k8s.io/cluster-autoscaler/kubeflow"
          "propagate_at_launch" = "false"
          "value"               = "owned"
        }
      ]
    },
    {
      name                = "GPU-Spot"
      spot_price          = "3.00"
      instance_type       = "p3.2xlarge"
      ami_id              = data.aws_ami.eks_worker_ami.id
      asg_desired_capacity          = 0
      asg_min_size                  = 0
      asg_max_size                  = 10
      kubelet_extra_args  = "--node-labels=node.kubernetes.io/lifecycle=spot"
      suspended_processes = ["AZRebalance"]
      tags = [
        {
          "key"                 = "k8s.io/cluster-autoscaler/enabled"
          "propagate_at_launch" = "false"
          "value"               = "true"
        },
        {
          "key"                 = "k8s.io/cluster-autoscaler/kubeflow"
          "propagate_at_launch" = "false"
          "value"               = "owned"
        }
      ]
    }
  ]

    node_groups = [
         {
      name                    = "Managed-spot"
      spot_price          = "2.20"
      capacity_type           = "SPOT"
      instance_types          = ["m5.large", "c5.large"]
      min_capacity = 5
      desired_capacity    = 7
      max_capacity = 10
      },

    ]

```
I would love to have a way to pass priorities for auto-scaling to have more control of scaling events. This feature would especially be useful for people using these expensive GPU instances for ML so that we can set a scale down to zero in the event no one is running training jobs, and prevent the usage of the gpu instances in scale up events that are not gpu dependent (ENI capacity etc). Just a feature suggestion. I'm currently achieving this task using an auto-scaler I found on git with a termination handler daemon set, but this would be amazing to have as an input option here in this module. If you're still lost with what I'm saying then I'm sorry.. I'm very new to terraform.

**Comment by AlecZebrick** [comment]
```

    
worker_groups = [
    {
      name                = "Worker-Spot"
      spot_price          = "2.00"
      instance_type       =  ["m5.large", "c5.large"]
      ami_id              = data.aws_ami.eks_worker_ami.id
      asg_max_size        = 15
      asg_min_size        = 5
      asg_desired_capacity= 7

      kubelet_extra_args  = "--node-labels=node.kubernetes.io/lifecycle=spot"
      suspended_processes = ["AZRebalance"]
      tags = [
        {
          "key"                 = "k8s.io/cluster-autoscaler/enabled"
          "propagate_at_launch" = "false"
          "value"               = "true"
        },
        {
          "key"                 = "k8s.io/cluster-autoscaler/kubeflow"
          "propagate_at_launch" = "false"
          "value"               = "owned"
        }
      ]
    },
    {
      name                = "GPU-Spot"
      spot_price          = "3.00"
      instance_type       = "p3.2xlarge"
      ami_id              = data.aws_ami.eks_worker_ami.id
      asg_desired_capacity          = 0
      asg_min_size                  = 0
      asg_max_size                  = 10
      kubelet_extra_args  = "--node-labels=node.kubernetes.io/lifecycle=spot"
      suspended_processes = ["AZRebalance"]
      tags = [
        {
          "key"                 = "k8s.io/cluster-autoscaler/enabled"
          "propagate_at_launch" = "false"
          "value"               = "true"
        },
        {
          "key"                 = "k8s.io/cluster-autoscaler/kubeflow"
          "propagate_at_launch" = "false"
          "value"               = "owned"
        }
      ]
    }
  ]

    node_groups = [
         {
      name                    = "Managed-spot"
      spot_price          = "2.20"
      capacity_type           = "SPOT"
      instance_types          = ["m5.large", "c5.large"]
      min_capacity = 5
      desired_capacity    = 7
      max_capacity = 10
      },

    ]

```

**Comment by daroga0002** [comment]
so currently there is no direct configuration or service which is adjusting autoscaling group sizes, in EKS approach AWS suggest this exactly same as on other deployments via cluster autoscaler:
https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html

I know AWS is trying to get more and more integration between EKS <> AWS layer so yesterday they releases next add ons:
https://aws.amazon.com/about-aws/whats-new/2021/05/eks-add-ons-now-support-coredns-kube-proxy/

but I think you needs can be achieved only via cluster autoscaler.

**Comment by stevehipwell** [comment]
It looks like you're missing ASG tags to help the autoscaler out.

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup

**Comment by daroga0002** [comment]
@AlecZebrick autoscaler is not a part of module, this is separated project and there is no plan to include this natively it into this module. As @stevehipwell  suggested you probably are missing some tags. 

Closing this issue as it is rather related to more about autoscaler config than module itself
