### ISSUE TITLE
15-Minute Timeout Using aws_eks_cluster

### ISSUE THREAD

**Issue by RGPosadas** [terraform-aws-modules/terraform-aws-eks#138]
# I have issues

## I'm submitting a...

* [x] bug report
* [x] feature request

## What is the current behavior?
`aws_eks_cluster` is timing out at 15 minutes (the 'bug'). There exists [timeout configs](https://www.terraform.io/docs/providers/aws/r/eks_cluster.html), but the module does not expose it to the users (the 'feature request'). 

```
TestFirst 2018-09-19T16:19:14-04:00 command.go:100: Error: Error applying plan:
TestFirst 2018-09-19T16:19:14-04:00 command.go:100: 
TestFirst 2018-09-19T16:19:14-04:00 command.go:100: 1 error(s) occurred:
TestFirst 2018-09-19T16:19:14-04:00 command.go:100: 
TestFirst 2018-09-19T16:19:14-04:00 command.go:100: * module.test_cluster.module.eks.aws_eks_cluster.this: 1 error(s) occurred:
TestFirst 2018-09-19T16:19:14-04:00 command.go:100: 
TestFirst 2018-09-19T16:19:14-04:00 command.go:100: * aws_eks_cluster.this: timeout while waiting for state to become 'ACTIVE' (last state: 'CREATING', timeout: 15m0s)
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.
1. Try to manage an EKS cluster using this module
2. If it takes longer than 15 mins, then you simply timeout.

## What's the expected behavior?
To have successfully managed an EKS cluster.

## Environment details
* Affected module version: v1.4.0
* OS: CentOS 7
* Terraform version: v0.11.8

**Comment by max-rocket-internet** [comment]
OK I see!

Feel free to make a PR to set the timeout higher.

**Comment by brandoconnor** [comment]
An example of what we'd be looking for @RGPosadas :
https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/alb_w_logs.tf#L20-L24

**Comment by max-rocket-internet** [comment]
Boom. DONE!
