### ISSUE TITLE
Error tls: crypto/x509: system root pool is not available on Windows

### ISSUE THREAD

**Issue by ivialex-mcd** [terraform-aws-modules/terraform-aws-eks#1384]
## Description

After the merge of this pull request [1339](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1339), when executing the terraform apply command to create the eks cluster and the managed nodes groups, it gives the following error as shown in the image below.

![image](https://user-images.githubusercontent.com/82114943/119190632-004d0980-ba54-11eb-9391-46140775b784.png)

## Versions

 - Terraform:

> $ terraform -version
> Terraform v0.15.0
> on windows_amd64

 - Provider(s):

> provider registry.terraform.io/hashicorp/aws v3.40.0
> provider registry.terraform.io/hashicorp/cloudinit v2.2.0
> provider registry.terraform.io/hashicorp/kubernetes v1.13.3
> provider registry.terraform.io/hashicorp/local v2.1.0
> provider registry.terraform.io/hashicorp/null v3.1.0
> provider registry.terraform.io/hashicorp/random v3.1.0
> provider registry.terraform.io/hashicorp/template v2.2.0
> provider registry.terraform.io/terraform-aws-modules/http v2.4.0

 - Module:

> terraform-aws-eks

## Reproduction
I'm trying to deploy EKS and Nodes Groups using the example **launch_templates_with_managed_node_groups** as a model.
And I'm using Git Bash to run the terraform commands.

### Code Snippet to Reproduce
Example **launch_templates_with_managed_node_groups**

## Expected behavior
Work on both Windows and Linux platforms.

## Actual behavior
After I runned the commando terraform apply -auto-approve show this error below:

│ Error: Error tls: crypto/x509: system root pool is not available on Windows
│
│   on .terraform\modules\eks\cluster.tf line 68, in data "http" "wait_for_cluster":
│   68: data "http" "wait_for_cluster" {

### Terminal Output Screenshot(s)
![image](https://user-images.githubusercontent.com/82114943/119190632-004d0980-ba54-11eb-9391-46140775b784.png)

## Additional context
N/A

**Comment by barryib** [comment]
Thanks @ivialex-mcd for reporting this issue. I'll try to fix this during the weekend.

**Comment by nareshkhatiwada** [comment]
I got same issue 

Error: Error tls: crypto/x509: system root pool is not available on Windows

  on .terraform\modules\eks\cluster.tf line 68, in data "http" "wait_for_cluster":
  68: data "http" "wait_for_cluster" {

**Comment by barryib** [comment]
I just publish https://github.com/terraform-aws-modules/terraform-provider-http/releases/tag/v2.4.1 to try to fix the provider issue on Windows.

@ivialex-mcd  @nareshkhatiwada can you please test it with `terraform-aws-modules/terraform-provider-http` v2.4.1 ?

```hcl
terraform {
  required_providers {
    http = {
      source = "terraform-aws-modules/http"
      version = "2.4.1"
    }
  }
}
```

**Comment by ivialex-mcd** [comment]
> I just published https://github.com/terraform-aws-modules/terraform-provider-http/releases/tag/v2.4.1 to try to fix the provider issue on Windows.
> 
> @ivialex-mcd @nareshkhatiwada @rkinganduril can you please test it with `terraform-aws-modules/terraform-provider-http` v2.4.1 ?
> 
> ```terraform
> terraform {
>   required_providers {
>     http = {
>       source = "terraform-aws-modules/http"
>       version = "2.4.1"
>     }
>   }
> }
> ```

Hi @barryib ,

It works for me. But it generated another problem as shown below.

This error had happened with version 15.2.0 of the EKS module. And even upgrading to version 16.1.0 did not solve it. Do you already have any other tickets for this problem?

│ Error: error creating EKS Node Group (eks-cluster-mcd-rfm-dev/eks-cluster-mcd-rfm-dev-node_group_gp-enjoyed-ferret): InvalidRequestException: Cannot specify instance types in launch template and API request
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "1afe9bdf-b681-468e-ba43-f5ed6c761c34"
│   },
│   ClusterName: "eks-cluster-mcd-rfm-dev",
│   Message_: "Cannot specify instance types in launch template and API request",
│   NodegroupName: "eks-cluster-mcd-rfm-dev-node_group_gp-enjoyed-ferret"
│ }
│
│   on .terraform\modules\eks\modules\node_groups\node_groups.tf line 1, in resource "aws_eks_node_group" "workers":
│    1: resource "aws_eks_node_group" "workers" {
│

**Comment by barryib** [comment]
Thanks for your feedback. Indeed this is not related to the wait_for_cluster datasource. Please, we can continue to discuss on https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1386
