### ISSUE TITLE
node_role_arn must not be empty

### ISSUE THREAD

**Issue by sharath23v** [terraform-aws-modules/terraform-aws-eks#1392]
## Description

I am trying to use a pre-defined role for cluster and workers. With below setting cluster works fine but not the node-groups. It says iam_role_arn is mandatory but document doesn't have any such inputs. 

## Versions
Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

### Code Snippet to Reproduce

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "16.1.0"

  cluster_name    = "${var.cluster_name}"
  cluster_version = "1.18"
  subnets         = module.vpc.private_subnets

  vpc_id = module.vpc.vpc_id

  node_groups_defaults = {
    ami_type  = "AL2_x86_64"
    disk_size = 50
    #iam_role_arn = "arn:aws:iam::xyz:role/NodeRole"
  }

  node_groups = {
    app = {
      node_group_name = "application"
      #source_security_group_ids = ""
      desired_capacity = 1
      max_capacity     = 3
      min_capacity     = 1
      instance_types = ["t3.large"]
      k8s_labels = {
        tier = "frontend"
      }
      key_name = ""
      additional_tags = {
        ExtraTag = "example"
      }
    }
  }
  worker_create_cluster_primary_security_group_rules = true

  write_kubeconfig   = true
  config_output_path = "./"

  cluster_enabled_log_types = ["api","audit","authenticator","controllerManager","scheduler"]
  cluster_iam_role_name = "eks-cluster-service"
  manage_cluster_iam_resources = "false"
  manage_worker_iam_resources = "false"
  #workers_role_name = "NodeRole"
  tags = {
    Environment = "staging"
  }

}

```

## Expected behavior
It works if i uncomment the iam_role_arn in nodegroupdefaults. There is no mention of this anywhere in document. 

### Terminal Output Screenshot(s)
![image](https://user-images.githubusercontent.com/49023089/119517492-47f5cd00-bd95-11eb-9b67-797faaeafa72.png)

## Additional context
I am not sure if i am not doing it right or the document needs to be updated. Please guide me on this.

**Comment by barryib** [comment]
IAM role ARNs are not mandatory because by default the role create them. In your case, you explicitly said that you want to managed IAM role by yourself ( `manage_cluster_iam_resources = "false"` and `manage_worker_iam_resources = "false"`) so you have to provide them.

**Comment by RoiNsec** [comment]
I have the same issue, I want to manage the IAM nodes role manually.
There is solution for this?

**Comment by daroga0002** [comment]
> I have the same issue, I want to manage the IAM nodes role manually.
> There is solution for this?

Please check inputs to module.

There is `manage_cluster_iam_resources` which allow control creating cluster policies outside module and `manage_cluster_iam_resources` for workers

**Comment by sharath23v** [comment]
`module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "16.1.0"

  cluster_name    = "${var.cluster_name}"
  cluster_version = "1.19"
  subnets         = module.vpc.private_subnets

  vpc_id = module.vpc.vpc_id

  node_groups_defaults = {
    ami_type  = "AL2_x86_64"
    disk_size = 50
    iam_role_arn = "arn:aws:iam::123456789123:role/eksNodeRole"
  }

  node_groups = {
    app = {
      node_group_name = "app"
      desired_capacity = 1
      max_capacity     = 1
      min_capacity     = 1
      instance_types = ["t3.large"]
      k8s_labels = {
        tier = "backend"
      }
      key_name = ""
      additional_tags = {
        Name = "app"
      }
    }

  }
  worker_create_cluster_primary_security_group_rules = true

  write_kubeconfig   = true
  config_output_path = "./"

  cluster_enabled_log_types = ["api","audit","authenticator","controllerManager","scheduler"]
  cluster_iam_role_name = "eks-cluster-service"
  manage_cluster_iam_resources = "false"
  manage_worker_iam_resources = "false"
  tags = {
    Environment = "staging"
  }
}
`

This is how i got it working. manage_cluster_iam_resources  & manage_worker_iam_resources  were set to false and added this iam_role_arn in nodegroup defaults to input my custom worker role.

**Comment by RoiSec** [comment]
I fixed this by using data object and referenced him to the iam_role_node in node group defaults.

`iam_role_arn=data.aws_iam_role.node_role.arn`

`data "aws_iam_role" "node_role" {
  name = "eks-node-group-role"
  depends_on = [
    aws_iam_role.eks-node-group-role
  ]
}`
