### ISSUE TITLE
Master branch commit fdd44c - broken launch configurations for multiple worker node configurations

### ISSUE THREAD

**Issue by mmcaya** [terraform-aws-modules/terraform-aws-eks#140]
# I have issues
@max-rocket-internet 
Quick heads-up
This change broke worker launch configurations for multiple worker group configurations:
https://github.com/terraform-aws-modules/terraform-aws-eks/blame/master/workers.tf#L31

```
* module.eks.aws_launch_configuration.workers[1]: Resource 'aws_iam_instance_profile.workers' not found for variable 'aws_iam_instance_profile.workers.id'
* module.eks.aws_launch_configuration.workers[0]: Resource 'aws_iam_instance_profile.workers' not found for variable 'aws_iam_instance_profile.workers.id'
```

Previous code had it properly select via the count index
```
-  iam_instance_profile        = "${aws_iam_instance_profile.workers.id}"
+  iam_instance_profile        = "${element(aws_iam_instance_profile.workers.*.id, count.index)}"
```

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## If this is a bug, how to reproduce? Please include a code sample if relevvant.
Sample multi worker group config
```
worker_groups = [
  {
    "name"                 = "green"
    "instance_type"        = "m4.large"
    "asg_desired_capacity" = "0"
    "asg_max_size"         = "0"
    "asg_min_size"         = "0"
  },
  {
    "name"                 = "blue"
    "instance_type"        = "m4.large"
    "asg_desired_capacity" = "2"
    "asg_max_size"         = "2"
    "asg_min_size"         = "2"
  },
]

worker_group_count = "2"
```
## Are you able to fix this problem and submit a PR? Link here if you have already.
Can submit PR by end of day 9/25 if a fix doesn't make it in 

## Environment details

* Affected module version: master
* OS:
* Terraform version:

**Comment by max-rocket-internet** [comment]
Thanks! Can you confirm this fixes it? https://github.com/terraform-aws-modules/terraform-aws-eks/pull/141

**Comment by mmcaya** [comment]
👍 look good from my local testing,

```
------------------------------------------------------------------------
No changes. Infrastructure is up-to-date.
```

**Comment by max-rocket-internet** [comment]
Thanks! My mistake.
