### ISSUE TITLE
Windows platform will always fail, because "windows" != "linux"

### ISSUE THREAD

**Issue by brettcave** [terraform-aws-modules/terraform-aws-eks#1410]
## Description

If a worker group platform is set to "windows", the eks apply will never pass. This is due how the AMI is resolved in local.

## Versions
 - Terraform: 0.13.x
 - Provider(s):
   provider registry.terraform.io/hashicorp/aws v3.42.0
 - Module:
  terraform-aws-eks, v0.16.1  onwards, 0.17

## Reproduction
Run this module with `var.workers_group_defaults.platform` set to `"windows"`. Plan will succeed. Apply will fail:

```
Error: Cannot fetch root device name for blank AMI ID.
      on .terraform/modules/eks/workers.tf line 1
    198: resource "aws_launch_configuration" "workers" {
```

Workspaces: fails with or without.

## Expected behavior
terraform apply passes, creating a windows worker node group.

## Additional context
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1371 introduced the bug, affecting 0.16.1 and 0.17 and beyond.

The fix will be committed shortly.
```
---   worker_has_windows_ami = length([for x in concat(var.worker_groups, var.worker_groups_launch_template) : x if lookup(x, "platform", "linux") == "windows"]) > 0

+++ worker_has_windows_ami = length([for x in concat(var.worker_groups, var.worker_groups_launch_template) : x if lookup(x, "platform", "windows") == "windows"]) > 0
```

**Comment by brettcave** [comment]
Is there anything else that is needed to apply this to other minor versions? Some upstream modules that reference this one have minor version pinning (e.g. `~> 16.0`), what would be needed to apply this to a v16 patch?

**Comment by brettcave** [comment]
> 
> 
> Is there anything else that is needed to apply this to other minor versions? Some upstream modules that reference this one have minor version pinning (e.g. `~> 16.0`), what would be needed to apply this to a v16 patch?

@barryib is a v16 patch release possible? (otherwise we'll need to get other module vendors to bump their version - e.g. https://github.com/spotinst/terraform-spotinst-ocean-eks/blob/master/eks.tf#L3

**Comment by barryib** [comment]
[v17.0.3](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v17.0.3) is released
