### ISSUE TITLE
Make tags on security groups consistent

### ISSUE THREAD

**Issue by IvanDechovsky** [terraform-aws-modules/terraform-aws-eks#1416]
## Is your request related to a new offering from AWS?
No
## Is your request related to a problem? Please describe.
Tags for cluster and worker security groups mismatch. 

Cluster SG only has 
```
  tags = merge(
    var.tags,
    {
      "Name" = "${var.cluster_name}-eks_cluster_sg"
    },
  )
```
while workers SG has:
```
  tags = merge(
    var.tags,
    {
      "Name"                                      = "${var.cluster_name}-eks_worker_sg"
      "kubernetes.io/cluster/${var.cluster_name}" = "owned"
    },
  )
```
## Describe the solution you'd like.
Could you please add the extra `"kubernetes.io/cluster/${var.cluster_name}"` tag to the cluster security group so we can consistently query all security groups created by the module for a specific cluster in a given account.

**Comment by barryib** [comment]
Thanks @IvanDechovsky. Right ! Feel free to open a PR. I'll happy to review it.

**Comment by IvanDechovsky** [comment]
Done! [PR 1418](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1418)

**Comment by daroga0002** [comment]
basing on [docs](https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html) and issue #1441 this should be closed.
