### ISSUE TITLE
Ability to protect from accidental destruction

### ISSUE THREAD

**Issue by psibi** [terraform-aws-modules/terraform-aws-eks#1426]
## Is your request related to a new offering from AWS?

No

## Is your request related to a problem? Please describe.

I have seen ocassionally that changing some input parameters to this module, leads to the creation of new ASGs where it replaces the existing ASG with a new one. I have seen various cases, where accidentally the cluster was temporarily brought down because of this.

## Describe the solution you'd like.

Use the lifecyle `prevent_destroy` feature from terraform to solve this. More details about this here: https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#prevent_destroy

Basically, have an optional input parameter like this:

```
enable_cluster_protection
```

with it's default value being the current behaviour, so that it doesn't affect existing users.

Having this argument will enable `prevent_destroy = true` for the `aws_eks_cluster`, `aws_autoscaling_group` and `aws_eks_node_group` resources.

The modify/destruction of such resources will involve manual steps:
- Change back the `enable_cluster_protection` so that  `prevent_destory` becomes false.
- Then do the `terraform apply/destroy` to apply or destroy those resources.

## Describe alternatives you've considered.

Alternative is to examine the terraform plan carefully before applying. But again this might not work for all the cases and there are some cases where we don't want things to get automatically replaced.

We also have some use cases where we automatically apply the plan as part of CI if the change is within a certain blast radius.

## Additional context

I have created this issue to create initial discussion around it. If others think it's a good idea, I can volunteer to implement the relevant changes.

**Comment by daroga0002** [comment]
I think issue with this approach is that if I remember correctly you cannot have variables inside lifecycle blocks.

Does you tested such code example?

**Comment by psibi** [comment]
After looking into it, there is no easy way to integrate this as part of the module because of current limitations in terraform.  https://github.com/hashicorp/terraform/issues/22544

There is an ugly workaround in the thread there: https://github.com/hashicorp/terraform/issues/22544#issuecomment-582974372
But this would just make the code more complicated.

I have just ahead and implemented `prevent_destroy = true` in our fork and I'm just planning to sync with this upstream regularly. I will close this issue as there is no easy way to implement this. Thanks @daroga0002 for the feedback!
