### ISSUE TITLE
Error adding kms Key to module eks [kubernetes version = "2.2.0" and kubectl version = "1.11.1"]

### ISSUE THREAD

**Issue by umersaleem443** [terraform-aws-modules/terraform-aws-eks#1427]
## Description:

when I tried to add the resource "aws_kms_key" to the *.tf file and after this i added cluster_encription_config in module eks. it is giving me the error. like " Error: Get "http://localhost/api/v1/namespaces/default/configmaps/config-map": dial tcp [::1]:80: connect: connection refused"

## Resource Added: 

```
resource "aws_kms_key" "eks" {
  description = "EKS Secret Encryption Key"
}

module "eks" {
  source          = "../.."
  cluster_name    = local.cluster_name
  cluster_version = "1.20"
  subnets         = module.vpc.private_subnets

  cluster_encryption_config = [
    {
      provider_key_arn = aws_kms_key.eks.arn
      resources        = ["secrets"]
    }
  ]

......
......
```

## Versions:
kubernetes version = "2.2.0"
kubectl version = "1.11.1" 
Terraform version = v0.15.0

## Command Attempted:
```
Terraform apply  
```
## Error:
```
Error: Get "http://localhost/api/v1/namespaces/default/configmaps/config-map": dial tcp [::1]:80: connect: connection refused"
```
## Expected Behavior:

Should generate the kms key and attach to the eks module

**Comment by barryib** [comment]
Your kubernetes provider is miss configured. Please see the readme for it should be configured.

**Comment by Ghazgkull** [comment]
I work with @umersaleem443. For context, we've been using the EKS module successfully since version 5.0.0. Our kubernetes provider is configured and is working fine with:
```
provider "kubernetes" {
  host                   = data.aws_eks_cluster.eks-cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks-cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.eks-cluster.token
}
```

What we're observing is that when we add this `cluster_encryption_config` to our existing EKS module configuration, the Kubernetes provider suddenly starts failing as described.

**Comment by daroga0002** [comment]
you should have in provider:
`load_config_file=false`


as per docs:

```load_config_file - (Optional) By default the local config (~/.kube/config) is loaded when you use this provider. This option at false disables this behaviour which is desired when statically specifying the configuration or relying on in-cluster config. Can be sourced from KUBE_LOAD_CONFIG_FILE```

this is suggested by output:
```
Error: Get "http://localhost/api/v1/namespaces/default/configmaps/config-map": dial tcp [::1]:80: connect: connection refused"
```

where you trying to connect to cluster endpoint  running on localhost:80

**Comment by umersaleem443** [comment]
@daroga0002  As you can see my kubernetes version is 2.2.0, and it is clearly mentioned in the document "The ```load_config_file``` attribute has been removed." from the version 2.0.0. ```https://github.com/hashicorp/terraform-provider-kubernetes/blob/b5770d4b51a1e1314c0f64b9f2c92cac9be7021a/website/docs/guides/v2-upgrade-guide.markdown#changes-to-kubernetes-credentials-supplied-in-the-provider-block``` 
So I think this is not going to work in my case.

**Comment by daroga0002** [comment]
Yup, you are right, but it still seems be issue with Kubernetes provider setup as you trying to connect to localhost. I propose you to enable debug on terraform by setting env variable `TF_LOG=trace` and then collect output from this try (it will produce a lot of output, but we need only snippet from node group creation). The best execute it with `terraform apply -parallelism=1` it will take a lot of time as there will be just one thread but output will be very clear as logs will be ordered.

More info about debug:
https://www.terraform.io/docs/internals/debugging.html

**Comment by alzabo** [comment]
I experienced similar errors when attempting to add encryption config to an existing cluster via Terraform, using this module.

As a workaround, I was able to encrypt the existing cluster in the AWS console, and then Terraform ran OK with the KMS config, (noop).

I didn't dig in fully, but I suspect that adding encryption config triggers re-creation of the cluster, which probably isn't what you want to happen

**Comment by Ghazgkull** [comment]
I just sat with Umer and walked through this again, after we updated to the latest version of all involved components and updated our config. We're still seeing the same issue, but critically we noticed that it's not happening during `terraform apply` as initially reported. But it's actually during the `terraform plan` that it fails, while attempting to refresh state.

Here's our current configuration of the Kubernetes and Kubectl providers:
```
provider "kubernetes" {
  host                   = data.aws_eks_cluster.eks-cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks-cluster.certificate_authority.0.data)
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    args        = ["eks", "get-token", "--cluster-name", local.cluster_name]
    command     = "aws"
  }
}

provider "kubectl" {
  host                   = data.aws_eks_cluster.eks-cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks-cluster.certificate_authority.0.data)
  load_config_file       = false
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    args        = ["eks", "get-token", "--cluster-name", local.cluster_name]
    command     = "aws"
  }
}
```

Here are the versions we're using now:
```
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.3.2"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "1.11.1"
    }
```

With a Terraform version of:
```
  required_version = ">= 1.0.0"
```

Here's an example of a resource which is failing to refresh. This is a resource that is deployed and works fine until we add the KMS encryption config:
```

resource "kubernetes_namespace" "addons" {
  metadata {
    name = "addons"
  }
  depends_on = [module.eks]
}

```

**Comment by pedroslopez** [comment]
I've been having this same issue enabling encryption on an existing cluster, using latest versions of this module and the kubernetes provider.

```terraform
data "aws_eks_cluster" "cluster" {
  name = module.cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.cluster.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}
```

```terraform
resource "aws_kms_key" "eks" {
  description = "EKS Secret Encryption Key"
}

module "eks" {
  source           = "terraform-aws-modules/eks/aws"
  version          = "17.1.0"
  cluster_name     = var.cluster_name
  cluster_version  = "1.20"
  enable_irsa      = true
  write_kubeconfig = false

  vpc_id  = var.vpc_id
  subnets = var.subnet_ids

  cluster_encryption_config = [
    {
      provider_key_arn = aws_kms_key.eks.arn
      resources        = ["secrets"]
    }
  ]

  worker_groups = [ ... ]

  map_users = var.map_users
}
```

As soon as the `cluster_encryption_config` is added to the cluster, plans start failing with `Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused`

**Comment by threesquared** [comment]
I am having the same issue just trying to move the `aws_kms_key` resource that is passed to the `provider_key_arn` in the `cluster_encryption_config`.
