### ISSUE TITLE
Terraform do not notice a change to asg_desired_capacity

### ISSUE THREAD

**Issue by vorozhko** [terraform-aws-modules/terraform-aws-eks#143]
# I have an issue
I have two nodes groups in EKS cluster. Any change to asg_desired_capacity get unnoticed by Terraform.

## I'm submitting a...
* [x ] bug report

## What is the current behavior?
Terraform do NOT notice changes to asg_desired_capacity field.

## If this is a bug, how to reproduce? Please include a code sample if relevvant.
Increase or decrease values of asg_desired_capacity.
Example of node groups:
```
worker_groups = "${list(
    map("instance_type","t2.medium",
      "additional_userdata","echo foo bar",
      "key_name","eks-nodes",
      "asg_min_size", "1",
      "asg_desired_capacity", "2",
      "asg_max_size", "3",
      "subnets", "${join(",", data.terraform_remote_state.net_config.k8s-private-subnet-ids)}"
    ),
    map("instance_type","t2.large",
      "additional_userdata","echo foo bar",
      "key_name","eks-nodes",
      "asg_min_size", "1",
      "asg_desired_capacity", "2",
      "asg_max_size", "3",
      "subnets", "${join(",", data.terraform_remote_state.net_config.k8s-private-subnet-ids)}"
    )
    
  )}
```

## What's the expected behavior?
Terraform update ASG.

## Environment details

* Affected module version: 1.6.0
* OS: MacOS
* Terraform version: v0.11.7

I notice that in worker.tf file desired_capacity changes are ignored. What the purpose of it?
```
lifecycle {
    ignore_changes = ["desired_capacity"]
  }
```

Thanks!

**Comment by vorozhko** [comment]
I have found why it's done like that here https://github.com/terraform-aws-modules/terraform-aws-eks/issues/38
Closing issue.

**Comment by adecchi-2inno** [comment]
@vorozhko 
Thank you to show the link to the issue, did you find a workaround to change the desired capacity when the cluster is already deployed ?
