### ISSUE TITLE
Cannot create a second cluster: Service role name AWSServiceRoleForElasticLoadBalancing has been taken in this account, please try a different suffix.

### ISSUE THREAD

**Issue by bkmeneguello** [terraform-aws-modules/terraform-aws-eks#144]
# I have issues

## I'm submitting a...

* [x] bug report

## What is the current behavior?

I can't create a second cluster because it throws this error: "Service role name AWSServiceRoleForElasticLoadBalancing has been taken in this account, please try a different suffix"

## If this is a bug, how to reproduce? Please include a code sample if relevant.

try to create a second cluster with the same configs but a different name.

## What's the expected behavior?

It should be able to create as many clusters I wish

## Environment details

* Affected module version: v1.4.0
* OS: Linux Mint 19 Tara
* Terraform version: v0.11.8

## Any other relevant info

The error happens with this resource: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/3b546a9c1bc9fab24b3bd0ca5ec30b5defed5e50/cluster.tf#L62-L65

**Comment by max-rocket-internet** [comment]
Another issue related to the `aws_iam_service_linked_role`. We also have this older issue: 
 https://github.com/terraform-aws-modules/terraform-aws-eks/issues/132

**Comment by okgolove** [comment]
Same situation. Want to have multiple clusters in one AWS account.

**Comment by max-rocket-internet** [comment]
So I think to resolve this error you need to delete any ELBs created by the first cluster, then delete the service linked role: `terraform destroy -target=module.xxx.aws_iam_service_linked_role.elasticloadbalancing`

Then allow the clusters to create new ELBs and they should just create their own service linked roles.

Can you guys test that?

**Comment by okgolove** [comment]
I just have set create_elb_service_linked_role = false and it works fine

**Comment by max-rocket-internet** [comment]
PR is now merged so I'll close this issue.
