### ISSUE TITLE
Multiple SG with tag "kubernetes.io/cluster/${var.cluster_name}" = "owned"

### ISSUE THREAD

**Issue by marcelobartsch** [terraform-aws-modules/terraform-aws-eks#1441]
When creating a the workers security group, this causes an issue that prevent services with LoadBalancer type to be created as expected.

As there will be two security groups tagged as owned by the cluster

Error updating load balancer with new hosts ..... Multiple tagged security groups found for instance i-fffffffffffffa; ensure only the k8s security group is tagged; the tagged groups were sg-aaaaaaaaaaa(dev-eks-0120210430090701491500000003) sg-bbbbbbbbbb(eks-cluster-sg-dev-eks-265811359)

Source

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9022013844a61193a2f8764311fb679747807f5c/workers.tf#L369

**Comment by daroga0002** [comment]
@marcelobartsch does this tagging is created by module?
