### ISSUE TITLE
Upgrading from module version 4.0.2 to latest 17.1.0 (strategy)

### ISSUE THREAD

**Issue by nodesocket** [terraform-aws-modules/terraform-aws-eks#1448]
Hello, I am attempting _(key word is attempting)_ to upgrade from the very old and legacy version of Terraform `v0.11.3` to latest `v1.0.0.`. Along with that upgrade, I am also upgrading from version `4.0.2` of this EKS module to `17.1.0`.

I've gone ahead and fixed all the Terraform syntax changes and bumped first to Terraform version `v0.13.7` as recommended by the Terraform output. However, now when running `plan` I am seeing the following logged many times:

```
Error: Provider configuration not present

To work with
module.k8s-court-stage.data.aws_iam_policy_document.cluster_assume_role_policy
its original provider configuration at provider["registry.terraform.io/-/aws"]
is required, but it has been removed. This occurs when a provider
configuration is removed while objects created by that provider still exist in
the state. Re-add the provider configuration to destroy
module.k8s-reynen-court-stage.data.aws_iam_policy_document.cluster_assume_role_policy,
after which you can remove the provider configuration again.
```

Is it even possible to do this upgrade while keeping the existing EKS clusters and EC2 worker group instances intact? If not, what's the process to recover from these errors and continue with upgrading?

**Comment by nodesocket** [comment]
@daroga0002 thanks for the reply. Indeed this is going to be a bit of a nightmare, but needs to be done. I ran:

```
terraform 0.13upgrade
```

And it only created a single new file `versions.tf` with:

```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
    random = {
      source = "hashicorp/random"
    }
  }
  required_version = ">= 0.13"
}
```

I am still getting the `provider configuration not present` errors when running `terraform plan`. I think the issue now is the sate in the s3 bucket, not the local configuration.

Any other ideas how to proceed?

**Comment by nodesocket** [comment]
@daroga0002 I am ok biting the bullet and having to create new EKS clusters using the new version `17.1.0 `. However, at this point I can't even do that. How can I remove the old EKS clusters?

Should I remove the EKS resources from the state using?

```terraform
terraform state rm
```

Is there a single command that will do this for me? I have the following in the legacy Terraform code:

```terraform
module "k8s" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "foobar-${var.environment}"
  cluster_version = "1.19"
  version         = "~> 4.0.2"
  
  ...
}
```

**Comment by daroga0002** [comment]
> Is there a single command that will do this for me? I have the following in the legacy Terraform code:

try:
`terraform state rm module.k8s`

regarding path, when you bumped version of module what plan is showing?

**Comment by nodesocket** [comment]
I also just ran into this upgrading from `0.14.11`. My feedback would be NOT a command line flag I have to provide to ignore changes outside of Terraform but a new attribute that behaves like `lifecycle { ignore_changes = [] }`.

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.fusionauth.aws_db_instance.rds has been changed
  ~ resource "aws_db_instance" "rds" {
        id                                    = "fusionauth"
      ~ latest_restorable_time                = "2021-07-06T16:42:02Z" -> "2021-07-06T16:57:02Z"
        name                                  = "fusionauth"
        tags                                  = {
            "Env"  = "stage"
            "Name" = "fusionauth"
        }
        # (52 unchanged attributes hidden)
    }
  # module.postgres.aws_db_instance.rds has been changed
  ~ resource "aws_db_instance" "rds" {
        id                                    = "postgres"
      ~ latest_restorable_time                = "2021-07-06T16:39:08Z" -> "2021-07-06T16:59:09Z"
        name                                  = "simplyagree"
        tags                                  = {
            "Env"  = "stage"
            "Name" = "postgres"
        }
        # (52 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions
to undo or respond to these changes.
```

**Comment by nodesocket** [comment]
@daroga0002 doing:

```terraform
terraform state rm module.k8s
```

Worked like a charm, and was able to actually get everything upgraded to Terraform version `1.0.1`. Thanks for the help.
