### ISSUE TITLE
Error running kubectl command: AccessDenied

### ISSUE THREAD

**Issue by RGPosadas** [terraform-aws-modules/terraform-aws-eks#145]
## I'm submitting a...

* [x] bug report

## What is the current behavior?
The EKS module works properly when run locally. But when it is run on a Jenkins build, this error pops up:

```
module.test_eks_module.module.eks.null_resource.update_config_map_aws_auth: Error running command 'kubectl apply -f ./config-map-aws-auth_clusterName.yaml --kubeconfig ./kubeconfig_clusterName': exit status 1. Output: could not get token: AccessDenied: Access denied

TestEKS 2018-09-28T20:47:32Z command.go:100: 	status code: 403, request id: 95b55acf-c35f-11e8-a8cf-ffb857db2354

TestEKS 2018-09-28T20:47:32Z command.go:100: Unable to connect to the server: getting token: exec: exit status 1

```

IAM roles are properly set as [documented here.](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/eks_test_fixture)

## What's the expected behavior?
To run the kubectl command.

## Environment details

* Affected module version:
* OS: CentOS 7
* Terraform version: 1.10.7
* EKS Module version: 1.6.0
* aws-iam-authenticator version: 1.10.3
* kubectl version: 1.10.8

**Comment by max-rocket-internet** [comment]
Hi @RGPosadas,
There's really many things that could cause this. Your environment variables, your IAM access, your installed version etc.

If I was you, I would start by running `aws-iam-authenticator` manually. e.g `aws-iam-authenticator token -i your-cluster-name`. This command must work.

**Comment by jensendw** [comment]
@RGPosadas In my case we were assuming a role for terraform changes and when the EKS cluster is provisioned only that role and not your user will have admin access.  If that is the case you can add the following to your module parameters 

```
  kubeconfig_aws_authenticator_additional_args = ["-r", "ARN of the role youre assuming"]
```

**Comment by max-rocket-internet** [comment]
Will close this now. Feel free to open it again if it's still an issue for you.
