### ISSUE TITLE
Module resources not inheriting `default_tags` from AWS provider.

### ISSUE THREAD

**Issue by citrix-ericgo** [terraform-aws-modules/terraform-aws-eks#1455]
## Description

Setting `default_tags` in a provider block does not percolate down to resources created by the module.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions
```
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.45.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
 - Module: terraform-aws-eks?
```

## Reproduction

Set a locals with a base_tags variable:
```
locals {
  base_tags = {
    environment = "foo"
    owner       = "bar@baz.qux"
  }
}
```
Apply default_tags to the aws provider:
```
terraform {
  required_version = "~> 0.14"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.45.0"
    }
  }
  backend "s3" {
    encrypt = true
  }
}
```
`terraform apply`

Observe no tags applied to the resources (such as AWS EC2 Autoscaling groups

### Code Snippet to Reproduce
```module "eks" {
  source                      = "terraform-aws-modules/eks/aws"
  cluster_name                = "widget-${var.environment}"
  cluster_version             = "1.18"
  subnets                     = var.private_subnets
  vpc_id                      = var.vpc_id
  cluster_enabled_log_types   = local.cluster_enabled_log_types
  manage_aws_auth             = true
  write_kubeconfig            = true
  kubeconfig_output_path      = "./"
  workers_additional_policies = ["arn:aws:iam::123456789012:policy/foobar"]
  map_users                   = var.user_permissions
  tags                        = local.base_tags

  worker_groups = [
    {
      name                 = "worker-group-1"
      instance_type        = var.instance_type
      asg_desired_capacity = 1
      asg_max_size         = 4
      asg_min_size         = 1
      disk_size            = 80
    },
    {
      name                 = "worker-group-2"
      instance_type        = var.instance_type
      asg_desired_capacity = 1
      asg_max_size         = 4
      asg_min_size         = 1
      disk_size            = 80
    },
  ]
}
```

## Expected behavior
Tags applied to resources created by the module

## Actual behavior
No tags applied to resources created by the module

## Additional context
Its also worth noting that `default_tags` in the provider also conflict with setting `tags` in the module itself. I get a complaint about de-duplicating tags. This would not be a big deal if I did not need to create other AWS resources outside of this module.

**Comment by citrix-ericgo** [comment]
I recognize that this is a known issue with the default tagging as documented (https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider) but the issue I have is that I cannot do both. I can't set it in `tags` in the module and `default_tags` for resources not managed by said module.

**Comment by gavinclarkeuk** [comment]
Seeing the same issue - I'm guessing it is related to the fix for https://github.com/terraform-aws-modules/terraform-aws-eks/issues/860

My understanding is that out of the box EKS's ASGs don't propagate tags correctly, so the fix for the above applies a specific workaround directly to the ASG. The workaround isn't looking at the default tags, just the tags passed to the module. Presumably needs to do some combination of the two - perhaps by using `tags_all` from some appropriate parent object?

**Comment by aidan-mundy** [comment]
This seems solvable via the use of launch templates. I would like avoid manually managing my launch template, but the module should be able to pull in tags and add them to the launch template. It may require some more advanced configuration because launch templates can specify which tags are applied to different resources used by the instance.
