### ISSUE TITLE
Enable EBS encryption on the volume for Nodegroup

### ISSUE THREAD

**Issue by raghavvidya** [terraform-aws-modules/terraform-aws-eks#1457]
## Description

We tried to use the Nodegroup submodule to create EKS node groups, but we could not find out to enable encryption on the root volume. Can you please guide us ?

## Versions
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.46.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

### Code Snippet to Reproduce

```
  node_groups_defaults = {
    key_name       = var.key_name
    pre_userdata   = data.template_file.pre_userdata.rendered
    root_encrypted = true
    eni_delete     = true
    public_ip      = false
  }
  node_groups = var.node_groups
```

## Actual behavior

On the console, the Nodegroup instances still show EBS volume is not encrypted.

**Comment by alzabo** [comment]
This isn't currently supported, but there's a PR pending review, etc. here: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1428

**Comment by daroga0002** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1428  was merged
