### ISSUE TITLE
Simplify the code shown in kubernetes provider in root readme.md

### ISSUE THREAD

**Issue by schollii** [terraform-aws-modules/terraform-aws-eks#1458]
## Is your request related to a new offering from AWS?

No 

## Is your request related to a problem? Please describe.

Not really

## Describe the solution you'd like.

The docs in main readme.md should use `var.create_eks` instead of the obfuscated `element(concat(..., [""]), 0)` construct. 

## Describe alternatives you've considered.

```
provider "kubernetes" {
  host                   = var.create_eks ? data.aws_eks_cluster.cluster[0].endpoint : ""
  cluster_ca_certificate = var.create_eks ? base64decode(data.aws_eks_cluster.cluster[0].certificate_authority.0.data) : ""
  token                  = var.create_eks ? data.aws_eks_cluster_auth.cluster[0].token : ""
}
```

**Comment by daroga0002** [comment]
it is simplified now:
![image](https://user-images.githubusercontent.com/20227477/133795118-0bd73302-2b7e-4c9f-807f-707e6d80b09b.png)
