### ISSUE TITLE
Switching spot_allocation_strategy cause terraform apply failed

### ISSUE THREAD

**Issue by cwyl02** [terraform-aws-modules/terraform-aws-eks#1460]
## Description

We are trying to switch the spot allocation strategy from the default `lowest-price` to `capacity-optimized`. When I made the change, I also made sure to remove the `spot_instance_pools` argument. However, in the terraform diff, looks like the spot_instance_pools arg is not removed, but rather changed to value from  `workers_group_defaults_defaults` in https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf
The outcome is that the tf apply error out saying 

`Error: Error updating Auto Scaling Group: ValidationError: SpotInstancePools option is only available with the lowest-price allocation strategy.`

tf diff:

> 

    Terraform will perform the following actions:
    
     module.abc.module.eks.aws_autoscaling_group.workers_launch_template[0] will be updated in-place
      ~ resource "aws_autoscaling_group" "workers_launch_template" {
            arn                       = "arn:aws:autoscaling:region:1234:autoScalingGroup:blah:autoScalingGroupName/some-eks-cluster-spot-generic-2cpu-8g-120200804173932713600000004"
            .. skipped rows with no diff
    
          ~ mixed_instances_policy {
              ~ instances_distribution {
                    on_demand_allocation_strategy            = "prioritized"
                    on_demand_base_capacity                  = 0
                    on_demand_percentage_above_base_capacity = 0
                  ~ spot_allocation_strategy                 = "lowest-price" -> "capacity-optimized"
                  ~ spot_instance_pools                      = 6 -> 10
                }
      .. skipped rows with no diff
        }

## Versions
 - Terraform:
0.12.28
 - Provider(s):
13.2.1, 14.0.0 
 - Module:

## Reproduction

Use the "before" code snippet to create this worker group
Then modify to "after" code snippet to modify this worker group

### Code Snippet to Reproduce
before:

> 

        worker_groups_launch_template = [
            {
              name                    = "spot-generic-2cpu-8g-1"
              override_instance_types = ["m4.large", "m5a.large", "m5.large"]
              spot_instance_pools = 6
              asg_max_size            = 8
              asg_min_size            = 5
              asg_desired_capacity    = 5
              kubelet_extra_args      = "--node-labels=node.kubernetes.io/lifecycle=spot"
              public_ip               = false
              additional_userdata     = "yum install ec2-instance-connect -y"
              additional_security_group_ids = [aws_security_group.worker-nodes-sg.id]
              enabled_metrics = ["GroupDesiredCapacity", "GroupInServiceInstances", "GroupPendingInstances", "GroupTerminatingInstances", "GroupStandbyInstances", "GroupTotalInstances"]
              tags = []
            }, 
           ....

after:

> 
        worker_groups_launch_template = [
          {
            name                    = "spot-generic-2cpu-8g-1"
            override_instance_types = ["m4.large", "m5a.large", "m5.large"]
            spot_allocation_strategy = "capacity-optimized"
            asg_max_size            = 8
            asg_min_size            = 5
            asg_desired_capacity    = 5
            kubelet_extra_args      = "--node-labels=node.kubernetes.io/lifecycle=spot"
            public_ip               = false
            additional_userdata     = "yum install ec2-instance-connect -y"
            additional_security_group_ids = [aws_security_group.worker-nodes-sg.id]
            enabled_metrics = ["GroupDesiredCapacity", "GroupInServiceInstances", "GroupPendingInstances", "GroupTerminatingInstances", "GroupStandbyInstances", "GroupTotalInstances"]
            tags = []
          }, 
         ....

## Expected behavior
Should change the strategy and remove the spot_instance_pools arg.

## Actual behavior
spot_instance_pools arg is not removed, but default value is picked up

### Terminal Output Screenshot(s)
`Error: Error updating Auto Scaling Group: ValidationError: SpotInstancePools option is only available with the lowest-price allocation strategy.
        status code: 400, request id: ...`

**Comment by thuandt** [comment]
@cwyl02 Have you try with `spot_instance_pools = null`?

**Comment by cthiebault** [comment]
@thuandt I have the same problem and setting `spot_instance_pools = null` does not fix it :-(

**Comment by cageyv** [comment]
@cwyl02 @cthiebault try `spot_instance_pools = 0`
