### ISSUE TITLE
Implicit node_group object creation is flawed

### ISSUE THREAD

**Issue by apeschel** [terraform-aws-modules/terraform-aws-eks#1462]
## Description

The node_group object used in this module has the "optional" type attribute "name" that significantly changes the behavior of this module if it's set.

This module manages to do this by avoiding declaring an explicit object definition for node_group, and instead dynamically constructing the node_group object, as seen here:

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v17.1.0/modules/node_groups/locals.tf

This is a huge flaw, because terraform doesn't normally support objects with optional type attributes, and there is no practical way to conditionally set the "name" attribute without running into type errors.

We have several existing clusters that need to have the name field set, but we don't want to set it for new clusters. Unfortunately, there's no way to use common code to do this with the current node_group object. The terraform type system just explodes.

This module should explicitly define the node_group object, which would help with the type issues around the "name" attribute.

If this module wants to use an optional attribute, there is an experimental terraform feature for using optional attributes. While it would mean using an experimental module, it would have the massive benefit of not completely breaking the terraform type system, and would allow for users to come up with ways to optionally set the name attribute.

https://www.terraform.io/docs/language/expressions/type-constraints.html#experimental-optional-object-type-attributes

**Comment by jaimehrubiks** [comment]
Just for clarification, can you explain how you reproduce this bug? Maybe that can help someone finding a solution. Does this happen when you mix node gruops with and without name field on the same cluster?

**Comment by apeschel** [comment]
@jaimehrubiks 

Here's an example of what I'm trying to do:

```
locals {
  node_group_base = {
    desired_capacity  = 6
    max_capacity      = 9
    min_capacity      = 6
    instance_types    = ["r5.xlarge"]
    subnets           = [element(module.vpc.private_subnets, 0)]
    disk_size         = 20
  }
  node_group_name_hack = {
    name              = var.cluster_node_groups_name
  }
  node_groups_expanded = var.cluster_node_groups_name != null ? merge(local.node_group_base, local.node_group_name_hack) : local.node_group_base
}

module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "17.1.0"
  cluster_name    = var.cluster_name
  subnets         = module.vpc.private_subnets
  tags            = var.custom_tags

  vpc_id = module.vpc.vpc_id

  node_groups = {
    pool = local.node_groups_expanded
  }
}
```

I've tried several different methods of conditionals, but not had any success in getting the optional name attribute to play nicely with the Terraform type system and conditionals. Terraform conditionals explode if the schemas for the returned objects differ, which is the case for the node_group object with its optional name attribute.

**Comment by apeschel** [comment]
Here's a link to a relevant Terraform issue covering this problem: https://github.com/hashicorp/terraform/issues/22405

**Comment by apeschel** [comment]
For a comparison, if the "name" attribute wasn't optional and there was an explicit object declaration for node_group, the Terraform code could just look like this:

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "17.1.0"
  cluster_name    = var.cluster_name
  subnets         = module.vpc.private_subnets
  tags            = var.custom_tags

  vpc_id = module.vpc.vpc_id

  node_groups = {
    pool = {
      name              = var.cluster_node_groups_name
      desired_capacity  = 6
      max_capacity      = 9
      min_capacity      = 6
      instance_types    = ["r5.xlarge"]
      subnets           = [element(module.vpc.private_subnets, 0)]
      disk_size         = 20
    }
  }
}
```

The would require the "name" attribute to have a default value, and for the module to switch behavior on whether the "name" attribute had the default value or not, rather than whether the "name" attribute existed or not.

**Comment by apeschel** [comment]
To clarify a bit more, normally with terraform you can explicitly omit an attribute by setting it to to `null`. However, the method of building the node_group object used by this module completely breaks that ability.

As an example, this *does not work*, it is currently impossible to have the name attribute included in the node_group object and also get the generated name_prefix behavior:

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "17.1.0"

  node_groups = {
    pool = {
      name              = null
    }
  }
}

**Comment by apeschel** [comment]
For reference on the normal Terraform workflow of setting an attribute to null to omit it:

https://www.terraform.io/docs/language/expressions/types.html#types

>null: a value that represents absence or omission. **If you set an argument of a resource or module to null, Terraform behaves as though you had completely omitted it** — it will use the argument's default value if it has one, or raise an error if the argument is mandatory. null is most useful in conditional expressions, so you can dynamically omit an argument if a condition isn't met.

**Comment by apeschel** [comment]
To clearly point out the problem code, these lines break things:

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v17.1.0/modules/node_groups/locals.tf#L30-L38

**Comment by apeschel** [comment]
This only affects v17.0.0 and later.

**Comment by apeschel** [comment]
Despite this being a bug for a really long time, this only really comes up with v17+, due to the requirement to set the name on existing clusters, but to omit it on new clusters.

**Comment by apeschel** [comment]
I've opened a PR with a fix: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1464

**Comment by apeschel** [comment]
This node_groups_names construct is a consequence of not explicitly
declaring the node_group object.

lookup will *always* return the default condition if an attribute exists,
but Terraform will set an attribute to null when it is supposed to be
omitted -- the attribute will exist, but shouldn't be used.

With the decision to implicitly define the node_group object, we have to
first check if an attribute exists, and then check if the attribute is null
if it does exist. We cannot take a shortcut by chaining the lookups in the
default condition, since the default condition will not be reached if the
attribute exists and is null.

It would be ideal to rework this module to explicitly declare
the node_group object, as that would simplify the logic.

**Comment by daroga0002** [comment]
as mentioned in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1464 seems this issue is not relevant in terraform 1.0.6
