### ISSUE TITLE
Ability to have exclusive tags for just the eks cluster resouces

### ISSUE THREAD

**Issue by mmerrill3** [terraform-aws-modules/terraform-aws-eks#1470]
## Describe the solution you'd like.
As a terraform user, I'd like to give my eks cluster resource a set of tags that are exclusive to just the cluster resource

## Describe alternatives you've considered.
I have forked this project and I created a new variable in variables.tf, specific for the cluster tags

## Additional context
Tags as placed on all the resources, which is verbose, and chews into limits of tagging in AWS.  I'd like to the ability to put tags only on the EKS cluster itself.

**Comment by mmerrill3** [comment]
Hi @antonbabenko , let me know if this is something that can be looked at for a future release.  Basically, I have a use case where I just need to be able to tag the EKS clusters with very specific tags, and the other resources that are created along the EKS cluster do not need that tag.

**Comment by antonbabenko** [comment]
Hi @mmerrill3 !

@barryib is the lead maintainer of this module and he will reply when time permits.

PS: I guess it is a summer break for many of us who maintain terraform-aws-modules, so don't expect an immediate response.

**Comment by antonbabenko** [comment]
Fixed in #1569

Released in [v17.9.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/v17.9.0).
