### ISSUE TITLE
Cannot select IMDSv2 for EC2 worker nodes.

### ISSUE THREAD

**Issue by gio-salvador** [terraform-aws-modules/terraform-aws-eks#1471]
## Description

As per the AWS Foundational Security Best Practices v1.0.0;
EC2.8: EC2 Instances should use Instance Metadata Service Version 2 (IMDSv2)
Severity: High

[EC2.8] This control checks whether your Amazon Elastic Compute Cloud (Amazon EC2) instance metadata version is configured with Instance Metadata Service Version 2 (IMDSv2). The control passes if HttpTokens is set to required for IMDSv2. The control fails if HttpTokens is set to optional.

## Expected behaviour
EC2 Worker nodes should have IMDSv2 enabled by default.

## Actual behaviour
IMDS is not version 2 on worker nodes currently deployed with this module, and there is no argument option to select version 2.

## Additional context
More information about the Metadata options in the Terraform aws_instance resource documentation:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#metadata-options

**Comment by nielsvbrecht** [comment]
You need to use launch templates with the eks module, then you ar able to set the metadata_http_tokens to "required"
