### ISSUE TITLE
Wrong security group in example launch-template for managed node groups?

### ISSUE THREAD

**Issue by siku4** [terraform-aws-modules/terraform-aws-eks#1478]
## Description

The launch template example for __managed node groups__ references to the security group for EKS worker groups (__self-managed nodes__). In our case this prevents Pods from communicating with the K8s API server. The Kubelets on the other hand seem to be able to communicate with the API server: Pods are scheduled and started correctly.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9022013844a61193a2f8764311fb679747807f5c/examples/launch_templates_with_managed_node_groups/launchtemplate.tf#L49

Imho the clusters primary security group must be referenced here. In our case this change solved the connectivity problems within the cluster.

## Reproduction
Use the example launch template for managed nodes groups from this repo, start a Pod and try to access the K8s API Server (by default 172.20.0.1). We noticed it when deploying our basic cluster components, such as cert-manager, which has to access a ConfigMap via API server.

## Expected behavior
The cluster primary security group (in the AWS console it can be found under `Configuration -> Networking -> Cluster security group`) is referenced here:

` security_groups             = [module.eks.cluster_primary_security_group_id] `

## Additional context
I have reinsured myself and created a managed node group via AWS console. The cluster security group mentioned above is, as expected, always attached to the EC2 instances.
 
There is also an additional hint when choosing "Use Launch Template" in the creation wizard for a new node group:

> If you specify custom security groups in the launch template, Amazon EKS will not add the cluster security group, and you must ensure the ingress and egress rules of your security groups enable communication with your cluster’s endpoint.

Further hints under `Configuration -> Networking -> Cluster Security group`:

> The Cluster Security Group is a unified security group that is used to control communications between the Kubernetes control plane and compute resources on the cluster. The cluster security group is applied by default to the Kubernetes control plane managed by Amazon EKS __as well as any managed compute resources created through the Amazon EKS API__.

> __Worker node__ security groups are security groups applied to __unmanaged worker nodes__ that control communications from worker nodes to the Kubernetes control plane.

**Comment by siku4** [comment]
**Update**: I don't want to rule out that there was a problem with the AWS CNI plugin and the node rolling update (triggered by the security group change in the launch template) solved the problem because the aws-node pods were restarted. We could **not** reproduce the error again. 

But the main question remains: Which SG should be used here?

**Comment by daroga0002** [comment]
you have described input/outputs in [docs](https://github.com/terraform-aws-modules/terraform-aws-eks)

for input is will be:
```
If provided, all workers will be attached to this security group. If not given, a security group will be created with necessary ingress/egress to work with the EKS cluster.
```

for output it will be:
```
Security group ID attached to the EKS workers.
```
