### ISSUE TITLE
Configmap (aws_auth) trying to make a POST request to localhost?

### ISSUE THREAD

**Issue by nodesocket** [terraform-aws-modules/terraform-aws-eks#1481]
## Description

Attempting to create a brand new EKS cluster using the latest module version `17.1.0` and creating the configmap `aws_auth` is failing trying to connect to `Post "http://localhost/api/v1/namespaces/kube-system/configmaps"`.  Why is it trying to connect to something locally at `localhost`? Previously it would write the configmap to a file locally on disk in the same directory and then I would manually just `kubectl apply -f config-map-aws-auth_acme-stage.yaml`. Did something change with this behavior?

```
module.stage.kubernetes_config_map.aws_auth[0]: Creating...
╷
│ Error: Post "http://localhost/api/v1/namespaces/kube-system/configmaps": dial tcp [::1]:80: connect: connection refused
│
│   with module.stage.kubernetes_config_map.aws_auth[0],
│   on .terraform/modules/stage/aws_auth.tf line 63, in resource "kubernetes_config_map" "aws_auth":
│   63: resource "kubernetes_config_map" "aws_auth" {
│
╵
```

## Versions
 - Terraform: 1.0.1
 - Provider(s): AWS 3.48.0
 - Module: 17.1.0

### Code Snippet to Reproduce

```
module "stage" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "acme-stage"
  cluster_version = "1.20"
  version         = "17.1.0"

  subnets = data.aws_subnet_ids.usw2.ids

  vpc_id = data.aws_vpc.usw2.id

  manage_cluster_iam_resources    = false
  cluster_iam_role_name           = "eks"
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false
  cluster_log_retention_in_days   = 7

  cluster_enabled_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler",
  ]

  cluster_encryption_config = [
    {
      provider_key_arn = data.aws_kms_key.eks-secrets.arn
      resources        = ["secrets"]
    }
  ]

  node_groups = {
    general = {
      desired_capacity    = 3
      max_capacity        = 3
      min_capacity        = 3
      instance_types      = ["m5.xlarge"]
      disk_size           = 250
      public_ip           = false
      capacity_type       = "ON_DEMAND"
      ami_release_version = "v20210628"

      k8s_labels = {
        Env = var.environment
      }

      tags = {
        Env          = var.environment
        AutoSnapshot = "true"
      }
    }
  }
}

```

**Comment by nodesocket** [comment]
I flipped `manage_aws_auth = false` which made everything work, but now I don't have a `config-map-aws-auth_acme-stage.yaml` file locally. Is there no way to replicate the old behavior where it writes the auth configmap to local disk? Maybe I am missing something.

**Comment by arcreative** [comment]
This auth management has me tearing my hair out.  It was very very difficult to get one cluster running, but we're running two in the same terraform config and it's been absolutely awful. Would love if there were a reliable way to use this as it seems to do what we need it to when it works, but it's taken hours to days to get it to stop being finicky.  

Also having an issue with the module not wanting to use a `kubernetes` provider that has an alias on it, but each provider is paired to a single cluster as far as I can tell.  Can consider that a different issue, however.

**Comment by RobinNil** [comment]
@nodesocket we were having the same issues, for us moving from aws provider from 3.37.0 to 3.53.0 resolved it.

Maybe, the project can consider requiring higher version of aws provider.
