### ISSUE TITLE
"launch_template_id" and "launch_template_version" inside "worker_groups_launch_template" block

### ISSUE THREAD

**Issue by sujeetkp** [terraform-aws-modules/terraform-aws-eks#1486]
Is it possible to pass " launch_template_id" and "launch_template_version" inside "worker_groups_launch_template" block or is it allowed only inside a Node Group ?

Even if I pass the Launch Template details, it is still taking some default values (E.g.: Instnce type as m4.large) for the EC2 instance worker nodes.

terraform -v
Terraform v1.0.0
on windows_amd64

```
aws = {
      source = "hashicorp/aws"
      version = "3.50.0"
}
```

```
module "eks" {

    source  = "terraform-aws-modules/eks/aws"
    version = "17.1.0"
       
    cluster_name    = local.eks_cluster_name
    cluster_version = var.eks_cluster_version

    vpc_id          = module.vpc.vpc_id
    subnets         = module.vpc.private_subnets

    worker_groups_launch_template = [

        {
            name                 = "worker-group-1"
            asg_desired_capacity = var.eks_worker_nodes   
            asg_min_size         = var.eks_worker_nodes     
            asg_max_size         = var.eks_worker_nodes 

            launch_template_id = aws_launch_template.eks_launch_template.id
            launch_template_version = aws_launch_template.eks_launch_template.latest_version
        }
    ]


    cluster_endpoint_private_access = true

    write_kubeconfig  = true
    kubeconfig_output_path = "./kubeconfig/"

    tags = local.tags

}
```

If it is not supported, is there any way to define an additional ebs volume ?

**Comment by daroga0002** [comment]
Please take a look into https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/launch_templates/main.tf this is showing how to customize worker groups

**Comment by daroga0002** [comment]
regarding 

>it is still taking some default values (E.g.: Instnce type as m4.large) for the EC2 instance worker nodes

this is because you don`t specify a `instance_type` in worker_groups_launch_template so assumes some defaults from this map https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c2bd137152945317124c4cded258f12662d267f4/local.tf#L51-L132
