### ISSUE TITLE
Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth

### ISSUE THREAD

**Issue by vmasule** [terraform-aws-modules/terraform-aws-eks#1487]
Below issue is happening quite frequently and it blocks deleting terraform resources created earlier, I have updated to terraform 2.0.0 version but still it is happening. I have referenced all the similar issues created in this forum but none clearly state what is really wrong and how behind the scene this issue occur.

How can I bypass this issue and at least delete the existing cluster by running terraform destroy command? I am thinking of not using this module as it seems quit unstable.

````
ERRO[0056] Module /Users/bhaidas.masule/git/appsian-cloud/aws-infrastructure-setup/development/us-west-2/dev/eks has finished with an error: 1 error occurred:
	* exit status 1
  prefix=[/Users/bhaidas.masule/git/appsian-cloud/aws-infrastructure-setup/development/us-west-2/dev/eks] 
INFO[0056] ╷
│ Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp [::1]:80: connect: connection refused
│ 
│   with module.eks.kubernetes_config_map.aws_auth[0],
│   on .terraform/modules/eks/aws_auth.tf line 63, in resource "kubernetes_config_map" "aws_auth":
│   63: resource "kubernetes_config_map" "aws_auth" {
````

**Comment by y0zg** [comment]
Can you please specify what is `2.0.0` version you mentioned. 
AWS EKS module latest version is https://github.com/terraform-aws-modules/terraform-aws-eks/tree/v17.1.0

**Comment by vmasule** [comment]
@y0zg Thanks for reverting back, I mentioned that about version in K8s provider section in `required_providers`
````
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.0"
    }
````

But I observer after adding `config_path` in k8s provider section like below, it's not giving me that error anymore, it was tested only once so I don't whether that is correct fix

````
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  token                  = data.aws_eks_cluster_auth.cluster.token
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  config_path = "~/.kube/config-dev"
}
````

If issue was because of that missing config_path then I would close this ticket.
