### ISSUE TITLE
Terraform getting timeout on wait_for_cluster and breaking provisioning of EKS

### ISSUE THREAD

**Issue by chaitanyakommoju** [terraform-aws-modules/terraform-aws-eks#1492]
## Description

I'm trying to create an AWS EKS private cluster using Terraform with the private subnet in VPC in AWS region `us-west-2,`  
I set the `endpoint_private_access=true` and` endpoint_public_access=false` after this I ran the terraform apply, for provisioning cluster and it fails and throws the error which is in `Code Snippet` section.
I have followed the steps by deleting the `.terraform` folder and its contents and re-initiated the modules and applied the `terraform plan` and `terraform apply`, but still it throws the error.

But when I set the public and private API endpoint to true, everything works without any issues.
I have applied the `terraform apply` second time but still I seeing the same `data "http" "wait_for_cluster"` error

I have waited for 35min to provisioned for coredns, aws-node and kube-proxy, but those are still not provisioned, attached screenshot for your reference

## Versions

 - Terraform:v.1.02
 - Provider(s):
provider registry.terraform.io/hashicorp/aws v3.47.0
provider registry.terraform.io/hashicorp/cloudinit v2.2.0
provider registry.terraform.io/hashicorp/http v2.1.0
provider registry.terraform.io/hashicorp/kubernetes v2.3.2
provider registry.terraform.io/hashicorp/local v2.1.0
provider registry.terraform.io/hashicorp/random v3.1.0
provider registry.terraform.io/terraform-aws-modules/http v2.4.1

 - Module: eks

### Code Snippet to Reproduce
Error: Error making request: Get "ENDPOINT URL": dial tcp <IP Address>:443: connectex: A   connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
    
    with module.app_eks.data.http.wait_for_cluster[0],
    on .terraform\modules\private_eks\data.tf line 89, in data "http" "wait_for_cluster":
    89: data "http" "wait_for_cluster" {

## Expected behavior
The cluster needs to be provisioned

## Actual behavior
the cluster does not get provisioned but kubeconfig is acquired

### Terminal Output Screenshot(s)
![EKS_Issue](https://user-images.githubusercontent.com/57356958/126357590-ffa36770-0055-482f-b879-308d989bf47e.jpg)

**Comment by giautm** [comment]
I got the same issue when disable public access via `cluster_endpoint_public_access  = false`.

```
│ Error: Error making request: Get "https://xxxx.gr7.ap-southeast-1.eks.amazonaws.com/healthz": dial tcp 10.10.11.253:443: connect: connection timed out
│ 
│   with module.eks.data.http.wait_for_cluster[0],
│   on .terraform/modules/eks/data.tf line 89, in data "http" "wait_for_cluster":
```

**Comment by giautm** [comment]
I think we can disable this check by set `manage_aws_auth = false` (no public `kubectrl` will allowed)

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9022013844a61193a2f8764311fb679747807f5c/data.tf#L89-L91

**Comment by chaitanyakommoju** [comment]
> I got the same issue when disable public access via `cluster_endpoint_public_access = false`.
> 
> ```
> │ Error: Error making request: Get "https://xxxx.gr7.ap-southeast-1.eks.amazonaws.com/healthz": dial tcp 10.10.11.253:443: connect: connection timed out
> │ 
> │   with module.eks.data.http.wait_for_cluster[0],
> │   on .terraform/modules/eks/data.tf line 89, in data "http" "wait_for_cluster":
> ```

yeah, I'm still seeing this issue and I don't know if someone from Terraform eks module team is looking into it or not
@barryib  can you please help to resolve this issue

**Comment by chaitanyakommoju** [comment]
> false
@giautm 
does it work for you?

**Comment by giautm** [comment]
TL/DR: Use terraform on bastion computer. (Or setup Github Actions Runner on that computer)

I found some thing during explore this module. You should have a bastion computer (EC2 instance) that on the same network of GKE if you want to use private access only.

If you create eks with `cluster_endpoint_public_access = true` first, then update it to `cluster_endpoint_public_access = false`. You will lose the access to k8s from local. It lead to the error:

```
Error: Get "https://xxxxx.gr7.ap-southeast-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 10.10.200.240:443: connect: connection timed out
```

**Comment by chaitanyakommoju** [comment]
> TL/DR: Use terraform on bastion computer. (Or setup Github Actions Runner on that computer)
> 
> I found some thing during explore this module. You should have a bastion computer (EC2 instance) that on the same network of EKS if you want to use private access only.
> 
> If you create eks with `cluster_endpoint_public_access = true` first, then update it to `cluster_endpoint_public_access = false`. You will lose the access to k8s from local. It lead to the error:
> 
> ```
> Error: Get "https://xxxxx.gr7.ap-southeast-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 10.10.200.240:443: connect: connection timed out
> ```
> 
> PS: setting `manage_aws_auth = false` is not necessary when you use bastion computer.

I'm setting up the VPC, bastion host and eks in a single  ``terraform apply`, because of this I'm cannot have bastion hosts connected to the VPC which I'm going to create along with eks, is there any other way to sort out this issue, I don't know if contributors and eks module teams have tested this type of scenario or not. 

Looking for some help

**Comment by sujeetkp** [comment]
I am getting the same error as well, but it is intermittent. Sometimes its success and sometimes it fails.
Not sure what is wrong.

**Comment by sujeetkp** [comment]
@barryib : Could you please check this if you have some time ?

**Comment by chaitanyakommoju** [comment]
> @barryib : Could you please check this if you have some time ?

@barryib can you please look into this issue, help to resolve it by setting up the eks cluster to private using terraform EKS module

**Comment by giautm** [comment]
I think they mention it in FaQ:

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#how-can-i-work-with-the-cluster-if-i-disable-the-public-endpoint

**Comment by networkhorse** [comment]
I faced this issue with the following spec:

```
module "eks" {
  depends_on = [
    module.vpc
  ]

  source           = "terraform-aws-modules/eks/aws"
  cluster_name     = var.cluster_name
  cluster_version  = var.cluster_version

  vpc_id           = module.vpc.vpc_id
  subnets          = module.vpc.private_subnets

  node_groups      = []

  manage_aws_auth  = true
  write_kubeconfig = false
}
```

Changing to:
```
module "eks" {
  depends_on = [
    module.vpc
  ]

  source           = "terraform-aws-modules/eks/aws"
  cluster_name     = var.cluster_name
  cluster_version  = var.cluster_version

  vpc_id           = module.vpc.vpc_id
  subnets          = module.vpc.private_subnets

  node_groups      = []

  manage_aws_auth  = true
  write_kubeconfig = false

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true
  wait_for_cluster_timeout        = 600
}
```

Seems to have completely alleviated the issue on my test with 4 runs of apply/destroy.

**Comment by daroga0002** [comment]
> Seems to have completely alleviated the issue on my test with 4 runs of apply/destroy.

This is working as for some time AWS allowing to create dual cluster endpoints. Explanation of their setting is here:
![image](https://user-images.githubusercontent.com/20227477/131877476-7f9fe96b-b85e-4dcb-93a5-2160f8585f9b.png)




In API and this module `Public and private` is just achievable by setting:
```
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true
```

**Comment by networkhorse** [comment]
@daroga0002 it is unclear why you have closed this issue given that the default configuration for this module is causing problems. You should be able to provision this without it breaking regardless of whether you configure Public, Public and Private, or just Private. At present, it seems that minimally "Public" alone will break the module.

I vote the issue be re-opened.

**Comment by daroga0002** [comment]
options `Public` and `Public and private` will be working without any special requirements. Option `Private` has requirements which are described here:
https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html

so as arleady mentioned in this thread this is not issue with module but with the way how user trying to apply it. If you making private only cluster endpoint then you must have access to it to manage `aws-auth` map, if you dont have correct routing/security groups/NACL between computer where you executing terraform and with your cluster endpoint there is nothing we can help. 

If you want to create cluster with `private cluster endpoint` then you cannot manage  `aws-auth` Config map which require direct access to EKS cluster endpoint. To achieve that you must set input `manage_aws_auth  = false` (this will cause you will need to manage configmap outside of this module.

**Comment by daroga0002** [comment]
Default is `Public` but in that case your worker nodes (kubelet) are also using Public endpoint so you must ensure you got a correct routing to external world from VPC where you deploying EKS.

**Comment by networkhorse** [comment]
In my case I was seeing everything available but Terraform disagreed seemingly randomly.

**Comment by daroga0002** [comment]
> In my case I was seeing everything available but Terraform disagreed seemingly randomly.

You mean your case in regards of workstation where you was applying plan or from worker nodes?


PS
I reopened issue

**Comment by networkhorse** [comment]
> You mean your case in regards of workstation where you was applying plan or from worker nodes?

With this config:

```
module "eks" {
  depends_on = [
    module.vpc
  ]

  source           = "terraform-aws-modules/eks/aws"
  cluster_name     = var.cluster_name
  cluster_version  = var.cluster_version

  vpc_id           = module.vpc.vpc_id
  subnets          = module.vpc.private_subnets

  node_groups      = []

  manage_aws_auth  = true
  write_kubeconfig = false
}
```

I was seeing intermittent failures, despite the cluster showing as available via AWS Console and the hostname being reachable for management.

I will try to reproduce it if you'd like me to, but since then I have been using the workaround of public + private. It's entirely possible it was only a one-day occurrence due to some temporary issue.

**Comment by daroga0002** [comment]
ok, but with private cluster endpoint and input `manage_aws_auth  = true`  your workstation where you executing terraform must have correct routing, security groups and DNS to reach a EKS API endpoint

**Comment by networkhorse** [comment]
> ok, but with private cluster endpoint and input `manage_aws_auth = true` your workstation where you executing terraform must have correct routing, security groups and DNS to reach a EKS API endpoint

I'm always having the public and private enabled, so my device just talks to the cluster using the public connection information. I don't actually utilise the private element of this at all beyond having it enabled to fix the bug. My ideal scenario would be public-only.

**Comment by daroga0002** [comment]
ok, so can you verify does in that config you are able to reach EKS API endpoint from `module.vpc.private_subnets` via `curl` ?
