### ISSUE TITLE
Exclude policy getting attached to worker nodes.

### ISSUE THREAD

**Issue by roy-tonal** [terraform-aws-modules/terraform-aws-eks#1493]
## Description

While deploying EKS cluster with node groups or self managed node group a policy gets attached to node `AmazonEC2ContainerRegistryReadOnly` As I'm using the flag `manage_worker_iam_resources` set to `true`. 

I have a requirement where I need to add `AmazonEC2ContainerRegistryPowerUser` to the node, but since the same policy is getting added with Read and PowerUser, sometimes the node is not able to write to ECR because of policy `AmazonEC2ContainerRegistryReadOnly`.

So is there any way where I can just exclude the policy `AmazonEC2ContainerRegistryReadOnly` so that it does not gets attached to the worker nodes?

I know if i set `manage_worker_iam_resources`to false then i can add an instance role with required policies. But just asking if there is any other way to do it?

## Versions

 - Terraform: v0.13.6

 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v3.36.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
 

 - Module: eks

## Reproduction
Just use any example code to deploy EKS cluster.

### Code Snippet to Reproduce
```# module.environment.module.eks.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly[0] will be created
  + resource "aws_iam_role_policy_attachment" "workers_AmazonEC2ContainerRegistryReadOnly" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      + role       = "devops20210604133744310700000009"
    } -->
```
This gets added as a default.

## Additional context
Wanted help to see if we can exclude adding the above policy (`AmazonEC2ContainerRegistryReadOnly`) to worker nodes.

**Comment by daroga0002** [comment]
AWS policy evaluation is described here https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html 

And in general if there is nothing explicitly denied in your policies then `AmazonEC2ContainerRegistryReadOnly` and `AmazonEC2ContainerRegistryPowerUser` during evaluation will give you all permissions from `AmazonEC2ContainerRegistryPowerUser` (as power user policy contains already read only privileges)

`AmazonEC2ContainerRegistryReadOnly`:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:DescribeRepositories",
                "ecr:ListImages",
                "ecr:DescribeImages",
                "ecr:BatchGetImage",
                "ecr:GetLifecyclePolicy",
                "ecr:GetLifecyclePolicyPreview",
                "ecr:ListTagsForResource",
                "ecr:DescribeImageScanFindings"
            ],
            "Resource": "*"
        }
    ]
}
```

`AmazonEC2ContainerRegistryPowerUser`:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:DescribeRepositories",
                "ecr:ListImages",
                "ecr:DescribeImages",
                "ecr:BatchGetImage",
                "ecr:GetLifecyclePolicy",
                "ecr:GetLifecyclePolicyPreview",
                "ecr:ListTagsForResource",
                "ecr:DescribeImageScanFindings",
                "ecr:InitiateLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:CompleteLayerUpload",
                "ecr:PutImage"
            ],
            "Resource": "*"
        }
    ]
}
```


Your problem is probably somewhere else and doesnt seems be related to module
