### ISSUE TITLE
Improve iam and security group naming convention 

### ISSUE THREAD

**Issue by simonmacklin** [terraform-aws-modules/terraform-aws-eks#150]
## I'm submitting a...

* [ ] bug report
- [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

At the moment security groups and IAM roles are not immediately clear  on what infrastructure they belong too.  As a example if I name the cluster 'test' the cluster iam role is named something like 

test201810021044448743111111112

I can understand the prefix is to prevent collisions but in my opinion it would be better to prefix it with something like eks-${var.cluster_name}-role- which would up up with something like 

eks-test-role-201810021044448743111111112

## Are you able to fix this problem and submit a PR? Link here if you have already.

I have not submitted a PR yet until I can get an idea of everyones opinion but will be more then happy too.

Kind Regards

Simon

**Comment by max-rocket-internet** [comment]
I agree.

I also created a similar issue here: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/88

I don't think the "prevent collisions" idea holds up, as what are the chances of you having a role of `eks-cluster-name` elsewhere?

**Comment by simonmacklin** [comment]
Hi Max 

I agree totally.  I am more than happy to submit a pull request without any prefixing.

Many thanks

**Comment by max-rocket-internet** [comment]
> I am more than happy to submit a pull request without any prefixing

Awesome 👍

**Comment by dpiddockcmp** [comment]
Please note that changing the IAM role names will cause all existing clusters to be recreated. I agree that the naming sucks but it's now technical debt.

A change of this magnitude should wait for a major version number change and have some form of migration path for existing clusters. Something similar to #137 for the EKS cluster resource.

> I don't think the "prevent collisions" idea holds up, as what are the chances of you having a role of `eks-cluster-name` elsewhere?

Justification for the use of `name_prefix` was given here: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/88#issuecomment-412424297

Currently you can use the same terraform config in multiple regions as IAM is global.

**Comment by max-rocket-internet** [comment]
> Please note that changing the IAM role names will cause all existing clusters to be recreated.

Yeah this is really annoying. You can't change the EKS cluster role without recreating it.

> Currently you can use the same terraform config in multiple regions as IAM is global.

This is true. The IAM role names will be unique but the cluster names could be identical.

Any more opinions on this? Personally, I could go either way.

**Comment by simonmacklin** [comment]
I could put in a variable, something like 'use_new_naming_convention' and if this is set to true create the roles and security groups with a new format.  This will allow new users to have the new naming and not break any existing clusters.  

This will be pretty easy to do, but may cause some confusion.  

Simon

**Comment by max-rocket-internet** [comment]
> I could put in a variable, something like `use_new_naming_convention` and if this is set to true create the roles and security groups with a new format. This will allow new users to have the new naming and not break any existing clusters.

Yeah would work but then we would need the IAM resources duplicated, once for old and once for new. Kinda messy.

I'm on the fence on this one 🤔

**Comment by simonmacklin** [comment]
A quick way to maybe implement this could be something like this?

```
resource "aws_iam_role" "role" {
  name_prefix = "${var.use_new_naming_convention == 1 ? "eks-${aws_eks_cluster.this.name}-role-" : "${aws_eks_cluster.this.name}" }"
}
```

**Comment by max-rocket-internet** [comment]
> A quick way to maybe implement this could be something like this?

This is slightly better but will still result in names like `xxxxx20180919094539278700000002`. But yes, just having the hyphen and keyword there would be better I guess.

**Comment by max-rocket-internet** [comment]
Please refer to https://github.com/terraform-aws-modules/terraform-aws-eks/issues/88
