### ISSUE TITLE
Terraform Module for EKS doesn't work for Apple M1

### ISSUE THREAD

**Issue by SarangKanabargi** [terraform-aws-modules/terraform-aws-eks#1511]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform: >= 0.14.1

 - Provider(s): AWS 

 - Module: terraform-aws-modules/eks/aws

## Reproduction

 
 terraform init

### Code Snippet to Reproduce

```
terraform {
  required_version = ">= 0.14.1"
}

locals{
    vpc_id = "vpc-1234ab"
    region = "eu-west-1"
    cluster_name = "dev-eks-cluster"
    subnets = ["subnet-1234", "subnet-1235", "subnet-1236"]
    cluster_enabled_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    asg_desired_capacity = 1
    asg_max_size = 3
    asg_min_size = 1
    instance_type = "m4.large"
    spot_price = "0.20"
}

provider "aws" {
  region  = local.region
}

module "eks-cluster" {
  source       = "terraform-aws-modules/eks/aws"
  version = "v7.0.1"
  cluster_name = local.cluster_name
  subnets = local.subnets
  vpc_id  = local.vpc_id
  worker_groups = [
    {
      spot_price = local.spot_price
      asg_desired_capacity = local.asg_desired_capacity
      asg_max_size = local.asg_max_size
      asg_min_size = local.asg_min_size
      instance_type = local.instance_type
      name = "worker-group"
      additional_userdata = "Worker group configurations"
      tags = [{
          key                 = "worker-group-tag"
          value               = "worker-group-1"
          propagate_at_launch = true
      }]
    }
  ]
  map_users = [
      {
        userarn = "arn:aws:iam::AWS_ACCOUNT:user/AWS_USERNAME"
        username = "AWS_USERNAME"
        groups = ["system:masters"]
      },
    ]
  cluster_enabled_log_types = local.cluster_enabled_log_types
  tags = {
    environment = "dev-env"
  }
}
```

## Expected behavior

Init should import the required module for apple m1 chip

## Actual behavior

terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/null versions matching ">= 2.1.0"...
- Finding hashicorp/template versions matching ">= 2.1.0"...
- Finding hashicorp/random versions matching ">= 2.1.0"...
- Finding hashicorp/local versions matching ">= 1.2.0"...
- Finding hashicorp/aws versions matching ">= 2.31.0"...
- Using hashicorp/null v3.1.0 from the shared cache directory
- Using hashicorp/random v3.1.0 from the shared cache directory
- Using hashicorp/local v2.1.0 from the shared cache directory
- Using hashicorp/aws v3.52.0 from the shared cache directory
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package
│ available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are
│ available for all platforms. Other versions of this provider may have different
│ platforms supported.
╵

### Terminal Output Screenshot(s)

Refer above

## Additional context

Apple M1 chip with 16GB RAM

**Comment by tnimni** [comment]
work around can be found here
https://github.com/hashicorp/terraform/issues/27257#issuecomment-825102330
that's not a module issue but a problem with terraform

**Comment by SarangKanabargi** [comment]
Thank you.
