### ISSUE TITLE
Cannot set Instance Type in Launch Template for Node Groups

### ISSUE THREAD

**Issue by fitchtech** [terraform-aws-modules/terraform-aws-eks#1514]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9022013844a61193a2f8764311fb679747807f5c/modules/node_groups/launch_template.tf#L42

If you try to update a node group to a launch template with instance type defined you get the following error message: "You must continue to not specify an instance type within the launch template"

This feature should be removed as it's not supported by AWS

**Comment by jaimehrubiks** [comment]
If I'm not wrong, it is supported. You just need to choose if you want to set it on the LT or not on the first creation. you cannot change it later. 

In my case I set that variable to true because then I can roll update the nodes by changing the instance type
