### ISSUE TITLE
Plan change to node_group that requires replacement destroy/create and using name arg apply fails

### ISSUE THREAD

**Issue by fitchtech** [terraform-aws-modules/terraform-aws-eks#1516]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9022013844a61193a2f8764311fb679747807f5c/modules/node_groups/node_groups.tf#L84

    nodeGroup1 = {
      name                              = "nodeGroup1"
      max_capacity                  = var.asg_max_capacity
      min_capacity                   = var.asg_min_capacity
      desired_capacity              = var.asg_desired_capacity
      launch_template_id         = aws_launch_template.eks_default.id
      launch_template_version = aws_launch_template.eks_default.default_version
      subnets                             = local.eks_node_group_subnets
    }

For example, you cannot add subnets to an existing node group. When I need to have more subnets added to the list the node group needs to be destroyed before being created. Cause it tries to create before destroy, it fails. The reason being is a node group with the same name already exists. The only way to get around this is manually delete the node group then Terraform apply. 

Therefore their needs to be a variable to override the default create before destroy. 

The only other option is to use name_prefix however I do not want clusters with random names. As we use nodeSelector with the nodegroup name in our deployments.

**Comment by daroga0002** [comment]
this is known AWS node groups limitation that you have just limited edit options to existing node group.
