### ISSUE TITLE
Cannot use cluster_version 1.20 with the eks module

### ISSUE THREAD

**Issue by jordanandres1** [terraform-aws-modules/terraform-aws-eks#1521]
## Description

Cannot use cluster_version 1.20 with the eks module

## Versions

 - Terraform: 1.0.4

 - Provider(s): 
    - registry.terraform.io/hashicorp/aws v3.53.0
    - registry.terraform.io/hashicorp/cloudinit v2.2.0
    - registry.terraform.io/hashicorp/kubernetes v1.13.4
    - registry.terraform.io/hashicorp/local v2.1.0
    - registry.terraform.io/terraform-aws-modules/http v2.4.1

 - Module: 17.1.0

## Reproduction

- Creating a cluster with a cluster_version "1.20" returns an error that it is not able to find an ami image for those versions

## Expected behavior

The cluster should be created normally

## Actual behavior

Error: Your query returned no results. Please change your search criteria and try again.
with module.eks_cluster.data.aws_ami.eks_worker[0],
on .terraform/modules/eks_cluster/data.tf line 20, in data "aws_ami" "eks_worker":
20: data "aws_ami" "eks_worker"

## Additional context

As a temporal fix forcing the ami name filter with `worker_ami_name_filter = "amazon-eks-node-${var.cluster_version}*"` instead of the default one `"amazon-eks-node-${var.cluster_version}-v*"` seems to work

**Comment by stanvit** [comment]
We had the same issue because our `cluster_version` was set to integer, like `cluster_version = 1.20`. When it's converted to string in the search filter, the zero is dropped and it becomes just `"v1.2"`. 

Changing the line to `cluster_version  = "1.20"` resolved the problem.

**Comment by jordanandres1** [comment]
It worked, thanks for your help
