### ISSUE TITLE
Passing multiple instances types not working

### ISSUE THREAD

**Issue by contactekansh** [terraform-aws-modules/terraform-aws-eks#1522]
## Description

When passing multiple instances types keeping the capacity type to SPOT, It's create the fleet request with only the single instance type. 

`  node_groups = {
    example = {
      desired_capacity = 2
      max_capacity     = 10
      min_capacity     = 1
      instance_types = ["t3.large","t3.xlarge"]
      capacity_type  = "SPOT"
      k8s_labels = {
        Environment = "test"
        GithubRepo  = "terraform-aws-eks"
        GithubOrg   = "terraform-aws-modules"
      }
      additional_tags = {
        ExtraTag = "example"
      }
      taints = [
        {
          key    = "spot"
          value  = "true"
          effect = "NO_SCHEDULE"
        }
      ]
    }`

## Versions

 - Terraform: v1.0.4

**Comment by daroga0002** [comment]
I have tested this on newest release of module and your configuration working as expected:
![image](https://user-images.githubusercontent.com/20227477/131984463-18ca53b7-4107-4065-b9c4-aeda505330d3.png)


config:
```
node_groups ={
  example = { 
    desired_capacity = 2 
    max_capacity = 10 
    min_capacity = 1 
    instance_types = ["t3.large","t3.xlarge"] 
    capacity_type = "SPOT" 
    k8s_labels = { 
      Environment = "test" 
      GithubRepo = "terraform-aws-eks" 
      GithubOrg = "terraform-aws-modules" 
    } 
    additional_tags = { ExtraTag = "example" } 
    taints = [ { key = "spot" 
    value = "true" 
    effect = "NO_SCHEDULE" 
    } ] 
  }
}
```

Silently created EKS ASG also looks good:
![image](https://user-images.githubusercontent.com/20227477/131984892-036eb113-c3f3-4dc9-a9c6-40beb250a624.png)

ASG is created with options:
![image](https://user-images.githubusercontent.com/20227477/131985594-fecc2e1b-a0ed-40e1-a600-f11597269309.png)


none of them we are able to influence as they are created by AWS backend api (we use EKS Nodegroup api which is silently creating underlying ASG)


I am closing as this is correct behaviour which we cannot influence as this is just how `Node groups` are working. If you require a more control in that area then you must switch into worker groups. Differences are described here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#what-is-the-difference-between-node_groups-and-worker_groups
