### ISSUE TITLE
support for client.authentication.k8s.io/v1beta1

### ISSUE THREAD

**Issue by vsamidurai** [terraform-aws-modules/terraform-aws-eks#1526]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
support for client.authentication.k8s.io/v1beta1 kubeconfig,  when we create a new EKS cluster.  client.authentication.k8s.io/v1beta1 API available for a while. should be able to generate kubeconfig with v1beta1 api.

**Comment by daroga0002** [comment]
not stale

**Comment by daroga0002** [comment]
#1550 was merged

**Comment by vsamidurai** [comment]
> #1550 was merged

Thank you @daroga0002
