### ISSUE TITLE
Public + Private subnets VPC scenario

### ISSUE THREAD

**Issue by julianxhokaxhiu** [terraform-aws-modules/terraform-aws-eks#1531]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
Yes. I've not found any documentation ( of if it's a supported scenario by this module ) related to creating an EKS cluster using a Private + Public VPC subnet scenario. See https://aws.amazon.com/blogs/containers/de-mystifying-cluster-networking-for-amazon-eks-worker-nodes/

Not sure if I am missing something, but in case feel free to let me know. Any help towards this is appreciated.

## Describe the solution you'd like.
```terraform
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  private_subnets = [...]
  private_subnet_tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
    "kubernetes.io/role/internal-elb" = "1"
  }

  public_subnets = [...]
  public_subnet_tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
    "kubernetes.io/role/elb" = "1"
  }
  
  # ...
}

module "eks" {
  source = "terraform-aws-modules/eks/aws"

  # AWS vpc
  subnets = concat(module.vpc.private_subnets, module.vpc.public_subnets)

  # K8s cluster
  cluster_endpoint_public_access  = true
  cluster_endpoint_private_access = true
  
  # ...
}
```
Something like this would be great. I tested this and even though terraform is able to apply all the changes the end result is that I'm not able to connect to the cluster.

Also, how does the module knows where to spawn worker nodes? And is it possible to tell how many per subnet type? ( like 3 for private, 10 for public for eg. )

## Describe alternatives you've considered.
N/A

## Additional context
N/A

**Comment by jamiegwatkin** [comment]
I had trouble with this too, if you take a look at the node group example it uses a combation of private and public subnets -  https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/managed_node_groups/main.tf#L32

We went with this configuration, instances are on the private subnet but we're able to use public facing load balancers.

```
module "this" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "17.1.0"
  cluster_name    = local.cluster_name
  cluster_version = "1.20"
  subnets         = module.vpc.private_subnets
  vpc_id          = module.vpc.vpc_id
  map_accounts    = var.map_accounts
  map_users       = var.map_users
  map_roles       = var.map_roles

  node_groups = {
    general-purpose = {
      desired_capacity = 3
      max_capacity     = 3
      min_capacity     = 3
      instance_types   = [var.instance_type] # See https://aws.amazon.com/ec2/instance-types/.
      capacity_type    = "ON_DEMAND"
    }
  }
}

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = local.cluster_name
  cidr = var.vpc_cidr

  azs             = var.vpc_azs
  private_subnets = var.vpc_private_subnets
  public_subnets  = var.vpc_public_subnets

  enable_nat_gateway = true
  enable_vpn_gateway = true

  # Enable DNS hostnames and DNS support required for VPC Peering
  enable_dns_hostnames = true
  enable_dns_support   = true

  # Don't assign public IPv4 addresses on EC2 instance launch.
  #map_public_ip_on_launch = false

  public_subnet_tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
    "kubernetes.io/role/elb"                      = "1"
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
    "kubernetes.io/role/internal-elb"             = "1"
  }

  tags = {
    name        = var.project_name
    environment = var.environment
  }
}
```
