### ISSUE TITLE
Unable to upgrade to version from 15.1.0 to 15.2.0. Tries to delete and recreate the Cluster 

### ISSUE THREAD

**Issue by jainshantanu** [terraform-aws-modules/terraform-aws-eks#1534]
## Description

I am trying to upgrade the module version from 15.1.0 to 15.2.0. When I try to do that I get the following error:

Error: Get "http://localhost/apis/storage.k8s.io/v1/storageclasses/gp2-encrypted": dial tcp [::1]:80: connect: connection refused.

I have used the providers as following:

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
}

I have the same issue on a newly created cluster everything is fine and then I'm changing the module tag and get this error, the weird thing is that if I put everything back just like in the state everything work as expected.

Does anyone face a similar issue? Please let me know your views.

## Versions

 - Terraform: 0.14.4

 - Provider(s): 2.1

 - Module: 15.2.0

## Reproduction

 yes
 yes
 Upgraded the module version from 15.1.0 to 15.2.0

### Code Snippet to Reproduce
module "eks" {
  # module details
  source     = "terraform-aws-modules/eks/aws"
  #version    = "~> 13.2.1"
  version    = "15.2.0"
  create_eks = true # default
  # required inputs
  cluster_name = var.cluster_name
  subnets      = [for s in data.aws_subnet.private_subnets : s.id]
  vpc_id       = data.aws_vpc.vpc.id
  # optional inputs
  cluster_version                       = var.cluster_version
  cluster_endpoint_public_access        = true # default 
  cluster_endpoint_public_access_cidrs  = var.whitelisted_cidrs_for_eks_cluster
  cluster_endpoint_private_access       = true # default false - opend because public is restricted
  cluster_endpoint_private_access_cidrs = ["0.0.0.0/0"]
  cluster_create_timeout                = "60s"
  cluster_iam_role_name                 = aws_iam_role.eks_cluster_role.name
  enable_irsa                           = var.enable_irsa
  manage_aws_auth                       = var.manage_aws_auth
  map_roles                             = var.map_roles
  workers_role_name                     = "aws_eks_worker_role"
  kubeconfig_name                       = var.cluster_name
  cluster_create_security_group         = false
  cluster_security_group_id             = aws_security_group.eks_security_group.id
  cluster_enabled_log_types             = ["api", "audit", "authenticator", "controllerManager", "scheduler"]

  manage_cluster_iam_resources = true # default 
  manage_worker_iam_resources  = true # default
  node_groups = {
    managed_nodes = {
      desired_capacity = var.node_capacity_desired
      max_capacity     = var.node_capacity_max
      min_capacity     = var.node_capacity_min
      disk_size        = var.node_disk_size
      instance_types    = var.node_type
      k8s_labels = {
        Environment = var.environment
      }
      additional_tags = local.default_tags
    }
  }
  tags = merge(
    local.default_tags,
    {
      cluster = var.cluster_name
    }
  )
  providers = {
    aws = aws.eksdeploy
  }
}

**Comment by jainshantanu** [comment]
@barryib @max-rocket-internet can you please help me here! Thanks in advance :)

**Comment by daroga0002** [comment]
you got some issue with kubernetes provider configuration as this trying to reach kubernetes API on your localhost:
```
"http://localhost/apis/storage.k8s.io/v1/storageclasses/gp2-encrypted"
```


doesnt looks to related to moodule itself, does you manage somoe resources using kubernetes provider?
