### ISSUE TITLE
Cluster endpoint is not reachable after updating to 17.1.0

### ISSUE THREAD

**Issue by leelanakka** [terraform-aws-modules/terraform-aws-eks#1536]
## Description

We have updated the module version to 17.1.0 when we are trying to use a custom IAM role to access our cluster, we are getting the following error.

Error: Get "http://localhost/apis/storage.k8s.io/v1/storageclasses/gp2-encrypted": dial tcp [::1]:80: connect: connection refused

## Versions

 - Terraform: 0.14.7

 - Provider(s): 2.1

 - Module: 17.1.0

## Reproduction

Do the following

> manage_cluster_iam_resources = true # default  -> change it to false

Uncomment -> #cluster_iam_role_name  = aws_iam_role.eks_cluster_role.name

### Code Snippet to Reproduce

`module "eks" {
  # module details
  source     = "terraform-aws-modules/eks/aws"
  #version    = "~> 13.2.1"
  version    = "17.1.0"
  create_eks = true # default
  # required inputs
  cluster_name = var.cluster_name
  subnets      = [for s in data.aws_subnet.private_subnets : s.id]
  vpc_id       = data.aws_vpc.vpc.id
  # optional inputs
  cluster_version                       = var.cluster_version
  cluster_endpoint_public_access        = true # default 
  cluster_endpoint_public_access_cidrs  = var.whitelisted_cidrs_for_eks_cluster
  cluster_endpoint_private_access       = true # default false - opend because public is restricted
  cluster_endpoint_private_access_cidrs = ["0.0.0.0/0"]
  #wait_for_cluster_cmd                  = "for i in seq 1 60; do wget --no-check-certificate -O - -q $ENDPOINT/healthz \u003e/dev/null \u0026\u0026 exit 0 || true; sleep 5; done; echo TIMEOUT \u0026\u0026 exit 1"
  cluster_create_timeout                = "60s"
  #cluster_iam_role_name                 = aws_iam_role.eks_cluster_role.name
  enable_irsa                           = var.enable_irsa
  manage_aws_auth                       = var.manage_aws_auth
  map_roles                             = var.map_roles
  workers_role_name                     = "aws_eks_worker_role"
  kubeconfig_name                       = var.cluster_name
  cluster_create_security_group         = false
  cluster_security_group_id             = aws_security_group.eks_security_group.id
  cluster_enabled_log_types             = ["api", "audit", "authenticator", "controllerManager", "scheduler"]

  manage_cluster_iam_resources = true # default 
  manage_worker_iam_resources  = true # default
  ```
node_groups = {
    managed_nodes = {
      desired_capacity = var.node_capacity_desired
      max_capacity     = var.node_capacity_max
      min_capacity     = var.node_capacity_min
      disk_size        = var.node_disk_size
      instance_types    = var.node_type
      k8s_labels = {
        Environment = var.environment
      }
      additional_tags = local.default_tags
    }
  }
  tags = merge(
    local.default_tags,
    {
      cluster = var.cluster_name
    }
  )
  providers = {
    aws = aws.eksdeploy
  }
}

data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}
resource "kubernetes_storage_class" "gp2_encrypted" {
  metadata {
    name = "gp2-encrypted"
    annotations = {      "storageclass.kubernetes.io/is-default-class" = "true"
    }
  }
  storage_provisioner = "kubernetes.io/aws-ebs"
  reclaim_policy      = "Delete"
  parameters = {
    type      = "gp2"
    fsType    = "ext4"
    encrypted = "true"
    kmsKeyId  = aws_kms_key.volumes_key.arn
  }
  volume_binding_mode    = "WaitForFirstConsumer"
  allow_volume_expansion = false
}
````

### Terminal Output Screenshot(s)

![unnamed](https://user-images.githubusercontent.com/44019459/130040680-b7f6a7a3-19c8-4666-91b2-994eebd7b667.png)

## Additional context

@zimbatm @max-rocket-internet @barryib

**Comment by daroga0002** [comment]
please check https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1280 as seems be wrongly configured kubernetes provider

**Comment by sagikazarmark** [comment]
I'm not 100% sure which part is wrong in the configuration. The workaround mentioned in #1280 seems to be the same as posted in this issue (albeit the provider config is missing) and that's what I use as well. #1487 seems to be irrelevant.

I believe the problem is what @dak1n1 described [here](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1280#issuecomment-810533105), namely there is a circular dependency between the module and its output (that is used for configuring the kubernetes provider).

I believe the `manage_aws_auth` option is conceptually broken (which is why the module requires a kubernetes provider in the first place). Turning it off solves the problem. It would probably make sense to extract that functionality to a separate module, but it's also trivial to replicate.

**Comment by dmitry-mightydevops** [comment]
I got exactly same behavior.
