### ISSUE TITLE
Do not install the CNI network plugin by default or be able to choose to delete it before the worker nodes start

### ISSUE THREAD

**Issue by dignajar** [terraform-aws-modules/terraform-aws-eks#1540]
# I have issues

## I'm submitting a...
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!

## What is the current behavior?
The daemonset `aws-node` is installed by default.

## What's the expected behavior?
I would like to have the possibility to not deploy the daemonset `aws-node` or remove it at the end of the creation of the control plane, before the workers nodes start.

## Any other relevant info
I'm looking for the best way to remove the CNI plugin from a fresh EKS installation and install others such as Calico or Weave before the worker nodes start running.

**Comment by daroga0002** [comment]
aws-node daemonset is incoming by default and there is no way to change it. This module doesn't touch this area so if you need it then probably should handle by some custom local-exec or etc.

**Comment by daroga0002** [comment]
closing issue as this is something what we cannot solve and is AWS default behaviour
