### ISSUE TITLE
Error on migrating to TF `1.0.0` with module version `16.1.0`

### ISSUE THREAD

**Issue by ns0092** [terraform-aws-modules/terraform-aws-eks#1544]
## Description

We recently migrated to Terraform version `1.0.0` and we are currently on module version `16.1.0` for EKS version `1.20`. 
We are seeing this error on Terraform apply:

```
Error: Cycle: module.AcwpEKSCluster.module.node_groups.aws_eks_node_group.workers["workers"] (destroy deposed 7d0434e0), module.AcwpEKSCluster.module.node_groups.var.cluster_name (expand), module.AcwpEKSCluster.module.node_groups.local.node_groups_names (expand), module.AcwpEKSCluster.module.node_groups.var.ng_depends_on (expand), module.AcwpEKSCluster.module.node_groups.aws_eks_node_group.workers["workers"], module.AcwpEKSCluster.data.http.wait_for_cluster[0], module.AcwpEKSCluster.module.node_groups.random_pet.node_groups["workers"] (destroy), module.AcwpEKSCluster.null_resource.wait_for_cluster[0] (destroy), module.AcwpEKSCluster.aws_eks_cluster.this[0]
```

Nothing useful on DEBUG logs. 

## Versions

 - Terraform:
1.0.0
 - Provider(s):
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.53.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
 
 - Module:
 `16.1.0` 

## Reproduction
terraform init and terraform apply

<img width="2555" alt="Screen Shot 2021-08-23 at 9 24 36 PM" src="https://user-images.githubusercontent.com/48308423/130555569-4ed93dfa-9973-4628-9034-c099e1410883.png">

**Comment by ns0092** [comment]
Same error with module `17.1.0` and Terraform `1.0.5`

**Comment by bryantbiggs** [comment]
this looks like you have a cyclical dependency in your configuration and not related to this module
