### ISSUE TITLE
mixed_instances_policy for managed node groups

### ISSUE THREAD

**Issue by v1nc3nt27** [terraform-aws-modules/terraform-aws-eks#1547]
If I understand correctly, currently it is only possible to specify mixed_instances_policy for self-managed worker groups. For managed node groups, it is only possible to set all instances to either ON_DEMAND or SPOT. As mixed_instances_policy is an option for managed node groups in AWS, it would be a nice feature to add.

**Comment by daroga0002** [comment]
nope, AWS Node groups have own api which on backend is using a AWS autoscaling, but you cannot influence it. 

Any changes directly to autoscaling is just a unsupported by AWS hack


There was some similar discussion under https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1525

**Comment by v1nc3nt27** [comment]
Ah, that's too bad. At this point, I don't want to switch to worker groups so I'll probably manually edit the ASG, I guess. Well, thanks a lot for clarifying it!
