### ISSUE TITLE
add option to set Fargate Role name when module will create the Role

### ISSUE THREAD

**Issue by emanuelflp** [terraform-aws-modules/terraform-aws-eks#1551]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
When creating a fargate profile, we cant define the fargate profile name, since is even just 1 by cluster. In the same way that we can define a name for Cluster and Node Roles, same needs to be applied to Fargate Role.

## Describe the solution you'd like.
Use the parameter `fargate_pod_execution_role_name` as name if defined and Fargate Role needs to be created.

## Example:
```
resource "aws_iam_role" "eks_fargate_pod" {
  count                = local.create_eks && var.create_fargate_pod_execution_role ? 1 : 0
  name_prefix          = var.fargate_pod_execution_role_name != "" ? null : format("%s-fargate", substr(var.cluster_name, 0, 24))
  name                 = var.fargate_pod_execution_role_name != "" ? var.fargate_pod_execution_role_name : null```

**Comment by ibrahiem96** [comment]
Hey @emanuelflp 

If you looked at the inputs on the README.md you will see that they have a variable for setting the pod execution role name: https://github.com/terraform-aws-modules/terraform-aws-eks#input_fargate_pod_execution_role_name

I am sure they didn't include it in the example because they wanted to keep it as simple and straightforward as possible

Cheers

Ibrahiem

**Comment by daroga0002** [comment]
as @ibrahiem96  mentioned there is few fargate parameters to customize:
![image](https://user-images.githubusercontent.com/20227477/131506777-a10eba81-b953-4787-9438-dbb6cf429d30.png)

doesn't they fit your scenario?

**Comment by emanuelflp** [comment]
Hello everyone. 
So, the paramater `fargate_pod_execution_role_name` is used only when already exists the role. In this way, the module will not create the Fargate Role and will use the existent Role.

I can't define the Role name if module will create the Role, because it is fixed as `name_prefix`. So is this that I want. Define the Pod Execution Role Name that will be created by module.

**Comment by daroga0002** [comment]
Why you cannot create `fargate_pod_execution_role_name` externally and pass into module?

I am little lost here, so please clarify as I am not using fargate pods in EKS
