### ISSUE TITLE
CloudWatch alarms embeded in the module

### ISSUE THREAD

**Issue by todortanevski** [terraform-aws-modules/terraform-aws-eks#1553]
## Is your request related to a new offering from AWS?

No.

## Is your request related to a problem? Please describe.

No.

## Describe the solution you'd like.

CloudWatch Alarms are not included in this module. They can be added at least for ASG level alerting.
Can we / should we modify this module / create a pull request to add this?
We are thinking configurable alarms through argument that is set by default to false: if enabled one needs to provide an alerting e-mail/sns topic.

## Describe alternatives you've considered.

Creating alarms at the terraform file where we call this module.

**Comment by antonbabenko** [comment]
Hi @todortanevski !

I don't think we need to bring this functionality into this module but you should rather use another module like [terraform-aws-cloudwatch](https://github.com/terraform-aws-modules/terraform-aws-cloudwatch/#metric-alarm) to manage metric alarms.

Cloudwatch module can utilize outputs from the EKS module.
