### ISSUE TITLE
Add example for enabled_metrics in MNG with LT

### ISSUE THREAD

**Issue by rangarb885** [terraform-aws-modules/terraform-aws-eks#1559]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
I didn't find an example on how to enabled_metrics ("Auto Scaling group metrics collection") while using Managed Node Group with Launch Template.

## Describe the solution you'd like.
Looking for an update on terraform-aws-eks/examples/launch_templates_with_managed_node_groups/ to include enabled_metrics for ASG

## Describe alternatives you've considered.
Manual enable it on console

## Additional context
None

**Comment by daroga0002** [comment]
Autoscaling group is created silently by [Nodegroup API](https://docs.aws.amazon.com/eks/latest/APIReference/API_Nodegroup.html). In result you cannot officially influence ASG as this is unsupported way. If you want to customize ASGs then you most go with `worker_groups` scenario described [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#what-is-the-difference-between-node_groups-and-worker_groups)
