### ISSUE TITLE
Remove depends_on for terraform >= 0.13

### ISSUE THREAD

**Issue by mavogel** [terraform-aws-modules/terraform-aws-eks#1574]
## Description

I'm about to use the module and found a comment `will be removed in terraform 0.13` -> [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/fargate.tf#L18). After checking the versions, I saw the module is on `terraform 0.13` -> [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/versions.tf#L2)

So can those `depends_on` be removed? (I did not test it, yet, but wanted to point out). I could file a PR then. 

And I found [more](https://github.com/terraform-aws-modules/terraform-aws-eks/search?q=Will+be+removed) occurrences of the `Will be removed...`

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform: `1.0.0`

 - Provider(s):

 - Module: `v17.15.0`

**Comment by antonbabenko** [comment]
Hi @mavogel !

Good catch! I thought about this earlier today, too, but I was thinking about it from the simplification and standardization (across the rest of terraform-aws-modules) point of view.

If there are no objections from anyone, I will self-assign myself to this issue and schedule it for the next week.

**Comment by antonbabenko** [comment]
Breaking change to do:
Remove variables from `variables.tf` - `eks_depends_on` and `ng_depends_on`.

**Comment by daroga0002** [comment]
I have opened some draft PR for this, I will need to test it deeply but it should solve this issue

**Comment by antonbabenko** [comment]
This issue has been resolved in version 17.24.0 :tada:
