### ISSUE TITLE
Node Group modifying each time terraform apply runs due to version change on LT

### ISSUE THREAD

**Issue by rangarb885** [terraform-aws-modules/terraform-aws-eks#1597]
## Description

In EKS 1.21, I have MNG with LT pattern. I have a custom AMI on LT. Even though there is no change on AMI or User-data , each time when terraform plan run it shows diff on default and latest version on LT which cause MNG to be recreated. This cause unwanted interruption to the EKS workloads.

## Versions

 - Terraform: 0.15.3

 - Provider(s): 

 - Module: 
```
hashicorp/kubernetes v2.2.0
hashicorp/aws v3.59.0
hashicorp/template v2.2.0
terraform-aws-modules/http v2.4.1
hashicorp/local v2.1.0
hashicorp/helm v2.2.0
hashicorp/cloudinit v2.2.0
hashicorp/archive v2.2.0
```

terraform-aws-eks module version : `v17.1.0`
   

## Reproduction

Are you using workspaces? : No
Have you cleared the local cache (see Notice section above)?  : Yes
List steps in order that led up to the issue you encountered : 
 - Create a EKS Cluster
 - Use MNG with LT 
 - In LT, use a Custom AMI (build out of amazon eks AMI). 
 - Use the default User-data to bootstrap.

### Code Snippet to Reproduce

*EKS*
```
module "eks" {
  ....
  node_groups = {
    cs_ng = {
      desired_capacity               =  4
      max_capacity                    =  4
      min_capacity                     = 10
      launch_template_id          = aws_launch_template.default.id
      launch_template_version = aws_launch_template.default.default_version
      instance_types                  = []
      k8s_labels = {
        Environment = var.environment
        Region      = var.region
        NodeGroup   = "workers"
      }
      additional_tags = {
        "Name"                                = "${var.eks.cluster_name}-node"
        "k8s.io/cluster-autoscaler/enabled"   = "true"
        "k8s.io/cluster-autoscaler/${var.eks.cluster_name}" = "owned"
      }
    }
  }
}
```

*Launch_Template*
```
data "aws_ami" "ami" {
  owners      = ["self"]
  most_recent = true

  filter {
    name   = "name"
    values = ["eks-ami-${var.eks.cluster_version}*"]
  }
}

resource "aws_launch_template" "default" {
  name_prefix            = "${var.eks.cluster_name}-"
  description            = "Default Launch-Template"
  update_default_version = true

  block_device_mappings {
    device_name = "/dev/xvda"

    ebs {
      volume_size         = 800
      volume_type        = "gp2"
      delete_on_termination = true
      encrypted           = true
      kms_key_id          = aws_kms_key.worker_ebs_kms.arn
    }
  }

  instance_type = var.eks.instance_type

  monitoring {
    enabled = true
  }

  network_interfaces {
    associate_public_ip_address = false
    delete_on_termination        = true
    security_groups           = [module.eks.cluster_primary_security_group_id]
  }

  image_id = data.aws_ami.ami.id

  user_data = base64encode(
    data.template_file.launch_template_userdata.rendered,
  )

  # Supplying custom tags to EKS instances is another use-case for LaunchTemplates
  tag_specifications {
    resource_type = "instance"

    tags = {
      "kubernetes.io/cluster/${var.eks.cluster_name}"   = "owned"
      "k8s.io/cluster-autoscaler/enabled"      = "true"
      "k8s.io/cluster-autoscaler/${var.eks.cluster_name}" = "owned"
      "Name"                                         = "${var.eks.cluster_name}-worker"
    }
  }

  tags = {
    cluster_name = "${var.eks.cluster_name}"
  }

  lifecycle {
    create_before_destroy = true
    ignore_changes = [
      tags,
    ]
  }
}
```

## Expected behavior
No change should happen to the latest_version and default_version of aws_launch_template as there is no change on them.

## Actual behavior
aws_launch_template gets updated with newer version and updates latest & default version, which leads to aws_eks_node_group to be replaced.

### Terminal Output Screenshot(s)
```
   # aws_launch_template.default will be updated in-place
   ~ resource "aws_launch_template" "default" {
       ~ default_version         = 14 -> (known after apply)
         id                      = "lt-020f35c0e3018fc32"
       ~ latest_version          = 14 -> (known after apply)
         name                    = "eks-vpc-test-20210901030504281300000001"
         # (15 unchanged attributes hidden)
     }


   ~ resource "aws_eks_node_group" "workers" {
         id                     = "eks-vpc-test:fiaa-vpc-test-cs_ng20210922163717878400000002"
         tags                   = {
             "Name"                                    = "eks-vpc-test-node"
             "k8s.io/cluster-autoscaler/enabled"       = "true"
             "k8s.io/cluster-autoscaler/fiaa-vpc-test" = "owned"
             "nike-environment"                        = "sbx"
         }
         # (16 unchanged attributes hidden)
       ~ launch_template {
             id      = "lt-020f35c0e3018fc32"
             name    = "eks-vpc-test-20210901030504281300000001"
           ~ version = "14" -> (known after apply)
         }
         # (2 unchanged blocks hidden)
     }

```

## Additional context
If i try to add default_version and latest_version to lifecycle/ignore_changes, it does not recoganize the change on AMI when it happens & forces me to run the terraform plan and apply twices. (1st time for changing AMI, 2nd time for apply the change)

**Comment by rangarb885** [comment]
Here for the above issue, I was follow the example : https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/launch_templates_with_managed_node_groups

**Comment by daroga0002** [comment]
upstream bug https://github.com/hashicorp/terraform-provider-aws/issues/19411

**Comment by daroga0002** [comment]
to ignore LT version changes just set update_default_version to `false` in inputs to node group (as per https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/node_groups)

**Comment by jweigand** [comment]
> to ignore LT version changes just set update_default_version to `false` in inputs to node group (as per https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/node_groups)

@daroga0002 I tried doing this, doesn't seem to work, still tries to change from a specific version number to "$Latest":

`  ~ resource "aws_eks_node_group" "workers" {
        id                     = "nodegroupid"
        tags                   = {
            "Name" = "nodegroup1"
        }
        # (16 unchanged attributes hidden)

      ~ launch_template {
            id      = "lt-id"
            name    = "nodegroup"
          ~ version = "3" -> "$Latest"`

**Comment by jamiegwatkin** [comment]
Like @jweigand I also had the same result.

**Comment by jaimehrubiks** [comment]
The code is different for when using an external launch template, as seen here https://github.com/jaimehrubiks/terraform-aws-eks/blob/master/modules/node_groups/node_groups.tf there are two dynamic blocks referring to launch_template. In your case, it is the one above. 

Not sure why your launch template is triggering a change when there is no change on it. That looks more like an upstream bug on a certain version of the provider? not sure.

**Comment by celestialorb** [comment]
I'm facing this issue as well, no matter what I set the EKS module still attempts to change the launch template version to `$Latest`.

**Comment by zhelding** [comment]
Hi folks. I'm investigating this issue as part of my work on upstream bug hashicorp/terraform-provider-aws#19411. However, I am not able to replicate the perpetual diff in `aws_launch_template` using the config provided above.

#### Versions

Output of `terraform -version`:

```
Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.59.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v2.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

On `v17.1.0` of `terraform-aws-modules/terraform-aws-eks`, using `examples/launch_templates_with_managed_node_groups`.

#### Config

The config I used is mostly identical to that of `examples/launch_templates_with_managed_node_groups`. The main changes are switching from local values to input variables, as well as the addition of k8s tags to match the original partial config provided for this issue.

[Full config gist](https://gist.github.com/zhelding/e9ef5dcd6bfe5bc881a67255441cf9f4)

#### Results

```bash
$ terraform apply
...
Plan: 46 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
...
Apply complete! Resources: 46 added, 0 changed, 0 destroyed.

$ terraform apply
...
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Same results on continued `terraform apply` attempts.

@rangarb885, @jamiegwatkin, or @Lincon-Freitas: are any of you able to either compare your failing configs with mine, or otherwise provide a full failing config so I can replicate on my end?

Thanks!

**Comment by rangarb885** [comment]
Hi Zoe,
Can you try the below:
1. On the LT add a new tag via CLI or Console.
2. Run the Terraform plan & apply. What i observed was that the LT version
gets changed as it removes the tag which is created via CLI.

Thanks!
