### ISSUE TITLE
Running I/O intensive applications (Storage optimized instances)

### ISSUE THREAD

**Issue by Smana** [terraform-aws-modules/terraform-aws-eks#1605]
## Is your request related to a new offering from AWS?
No this is related to available instance types that we'd like to use for storage intensive workloads

## Is your request related to a problem? Please describe.
Not really. Just trying to find out the best option to make use of the local disks of `i3en` instances

## Describe the solution you'd like.
Being able to add local nvme disks and make them available to EKS

## Describe alternatives you've considered.
None

## Additional context
In order to be able to get the best performances for i/o intensive workloads we'd like to make use of `i3en` instances.
We're currently using managed nodes and when I use this instance type I get the following partitionning:

node group configuration

```hcl
    high_io = {
      ami_type  = "AL2_x86_64"
      disk_size = 200
      desired_capacity = 1
      max_capacity     = 3
      min_capacity     = 1
      capacity_type    = "ON_DEMAND"
      ng_per_az        = false

      instance_types = ["i3en.xlarge"]
    }
```

```console
lsblk
NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
nvme1n1       259:0    0  2.3T  0 disk
nvme0n1       259:1    0  200G  0 disk
├─nvme0n1p1   259:2    0  200G  0 part /
└─nvme0n1p128 259:3    0    1M  0 part
```

```console
vme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     vol04868f6bf58624452 Amazon Elastic Block Store               1           0.00   B / 214.75  GB    512   B +  0 B   1.0
/dev/nvme1n1     AWSB29D9697EA2CE2289 Amazon EC2 NVMe Instance Storage         1           2.50  TB /   2.50  TB    512   B +  0 B   0
```

Here we can see that the root partition takes 200G from the nvme storage for the root partition.

Generally speaking what would be the best approach please ?

**Comment by daroga0002** [comment]
could you elaborate a question and how this is related to terraform module?

**Comment by antonbabenko** [comment]
@Smana Please ask K8S/EKS related questions in a better place (e.g. https://slack.k8s.io/ has lots of people who should be able to help).

I am going to close this issue here since it is not related to the behavior of this Terraform module.

**Comment by Smana** [comment]
I finally managed to get things work with the following configuration

```hcl
      pre_userdata   = <<-EOT
cat <<EOF > /etc/udev/rules.d/90-kubernetes-discovery.rules
# Discover Instance Storage disks so kubernetes local provisioner can pick them up from /dev/disk/kubernetes
KERNEL=="nvme[0-9]*n[0-9]*", ENV{DEVTYPE}=="disk", ATTRS{model}=="Amazon EC2 NVMe Instance Storage", ATTRS{serial}=="?*", SYMLINK+="disk/kubernetes/nvme-$attr{model}_$attr{serial}", OPTIONS="string_escape=replace"
EOF
udevadm control --reload && udevadm trigger
EOT
```

Based on https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/getting-started.md#option-5-eks-experimental
