### ISSUE TITLE
Missing Security Group Rule

### ISSUE THREAD

**Issue by jdziat** [terraform-aws-modules/terraform-aws-eks#1606]
## Description

Ran into an issue over the last few days where a security group rule was removed and caused intermittent connectivity issues depending on where the pods existed. Just wondering why this didn't trigger anything when running terraform. I don't see any audit trails at the moment of the group/rule being deleted or modified. This is more of a general question than an ongoing bug. If it happens again or if i can reproduce it I'll capture and document what i can.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:

 - Provider(s):

 - Module:

## Reproduction
Unable to reproduce and all our other clusters seem to be working appropriately

### Code Snippet to Reproduce
N/A

## Expected behavior
On security rule change/deletion/modification should trigger terraform to add/change the group

## Actual behavior
Completes without incident and makes it appear as it's in a healthy state

**Comment by daroga0002** [comment]
please provide details to this issue

**Comment by jdziat** [comment]
Wait, the issue is that one of our clusters that takes advantage of spot instances are joining different security groups not just the primary one that's configured.
