### ISSUE TITLE
Create multi worker_groups by loop

### ISSUE THREAD

**Issue by PLeS207** [terraform-aws-modules/terraform-aws-eks#1609]
Hello guys please help, How can I create multi worker_groups, if I want for example 100 worker_groups , tried to use for and for each and local variables,  but it doesn't work
```
worker_groups = [
    {
      name                          = "worker-group-1"
      instance_type                 = "t3.small"
      additional_userdata           = "echo foo bar"
      asg_desired_capacity          = 2
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_one.id]
    },
.
.
.
.

    {
      name                          = "worker-group-N"
      instance_type                 = "t3.medium"
      additional_userdata           = "echo foo bar"
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_two.id]
      asg_desired_capacity          = 1
    },
  ]
```

tried work with local variables like 
```
locals {
worker_groups =     [{
      name                          = "worker-group-2"
      instance_type                 = "t3.small"
      asg_desired_capacity          = 2

  },
  {
      name                          = "worker-group-3"
      instance_type                 = "t3.medium"
      asg_desired_capacity          = 1
    }
  ]
}
```
And then put it in worker_groups
```
worker_groups = [
    {
      name                          = "worker-group-1"
      instance_type                 = "t3.small"
      additional_userdata           = "echo foo bar"
      asg_desired_capacity          = 2
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_one.id]
    },

    local.worker_groups

]
```
but it doesn't work too

**Comment by daroga0002** [comment]
you must generate input values in correct format. This is rather generic terraform programming than something strictly related to module.

I can advise you look into some example of such generation code patterns (for example we doing some generation here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1d1a73e138683373eea90525884c9abf0d57bbbb/aws_auth.tf#L39-L61).


I am closing this issue as it is not related to this module

**Comment by daroga0002** [comment]
> And then put it in worker_groups
> 
> ```
> worker_groups = [
>     {
>       name                          = "worker-group-1"
>       instance_type                 = "t3.small"
>       additional_userdata           = "echo foo bar"
>       asg_desired_capacity          = 2
>       additional_security_group_ids = [aws_security_group.worker_group_mgmt_one.id]
>     },
> 
>     local.worker_groups
> 
> ]
> ```
> 
> but it doesn't work too

because you are trying to add element which is new list (instead of map). SO you must either concat two lists or add map (instead list into list)
