### ISSUE TITLE
Set custom timeouts for create and delete in fargate_profiles input

### ISSUE THREAD

**Issue by IvanDechovsky** [terraform-aws-modules/terraform-aws-eks#1610]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
When creating/destroying fargate profiles we often hit the 10 minute default timeout limit causing the terraform apply to fail. 

## Describe the solution you'd like.
The `aws_eks_fargate_profile` resource has the ability to define a different [timeout](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_fargate_profile#timeouts) for `create | delete`. We would like to be able to set those via the `fargate_profiles` input in the module

**Comment by daroga0002** [comment]
we should address this issue in same way as in node groups: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/253f927465ccac36bcadefcfb1fd0e39b6244d73/modules/node_groups/main.tf#L81-L85

to make a consistent user experience.

**Comment by daroga0002** [comment]
@IvanDechovsky do you will be able to submit PR for this?

**Comment by IvanDechovsky** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1614

**Comment by IvanDechovsky** [comment]
@daroga0002 PR updated. Slightly different approach where the same timeouts are applied across all profiles. Tested as well. Thanks for the feedback.

**Comment by daroga0002** [comment]
#1614 was merged so closing this issue, it will be in next release
