### ISSUE TITLE
KMS key policy and encrypted node groups - circular dependency

### ISSUE THREAD

**Issue by mj3c** [terraform-aws-modules/terraform-aws-eks#1619]
## Is your request related to a problem? Please describe.
I am trying to create a custom KMS key (CMK) and use that for both encrypting the EKS secrets, as well as the node EBS blocks. In order to do this, the AWSServiceRoleForAutoScaling service-linked role needs to have permissions to use the key. However, this role does not exist until you create your first ASG. Now what happens is a circular dependency between the key policy and the service-linked role which will be created when the EKS module creates the node groups (and therefore ASGs). Something like this:

```terraform
data "aws_caller_identity" "current" {}

data "aws_iam_policy_document" "kms_main" {
  statement {
    sid    = "Allow service-linked role use of the CMK"
    effect = "Allow"
    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"]
    }
    # ...
  }
  # ...
}

resource "aws_kms_key" "main" {
  key_usage                = "ENCRYPT_DECRYPT"
  customer_master_key_spec = "SYMMETRIC_DEFAULT"
  policy                   = data.aws_iam_policy_document.kms_main.json
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "17.20.0"

  # ...
  cluster_encryption_config = [
    {
      provider_key_arn = aws_kms_key.main.arn
      resources        = ["secrets"]
    }
  ]

  node_groups_defaults = {
    # ...
    disk_kms_key_id = aws_kms_key.main.arn
    # ...
  }
}
```

It is apparent that the EKS module depends on the key ARN, but the key resource also depends on `AWSServiceRoleForAutoScaling` service-linked role to exist, else I get `MalformedPolicyDocument: Invalid principal in policy`.

If I create/manage this service-linked role through Terraform, then I cannot easily apply all this multiple times (for example in different regions), as it will complain about the role already existing. Also, I tried creating the service-linked role with the `custom_suffix` argument set, but the node groups / ASGs are still created using the default role which doesn't have the suffix. I found the `service_linked_role_arn` argument in this module, but that is only for **worker** groups, not **node** groups.

Am I missing something here, or will I have to manage the service-linked role through Terraform as well?

**Comment by daroga0002** [comment]
this require some deeper investigation, maybe somebody from community will be able to deep dive into it.

**Comment by mj3c** [comment]
To add some more information - this is probably because of the differences between how node groups and worker groups are created. Node groups resource is `aws_eks_node_group` which does not have any arguments related to specifying a custom service-linked role. Worker groups are created with `aws_autoscaling_group`, which _does_ have an argument for specifying the role, it's `service_linked_role_arn`.

For this reason it seems that it is impossible to create a custom KMS key and use it for EKS managed node groups in one single `terraform apply`, on a new AWS account which doesn't have the service-linked role already created.

**Comment by nmofonseca** [comment]
Hello @mj3c ,

I am facing exactly the same issue, have you ever found a solution for the problem?

I haven't tried to run apply again after their first execution, does it work the 2nd time?

**Comment by nmofonseca** [comment]
Since this is still a problem, can we ask for this  issue to be reopened?

**Comment by mj3c** [comment]
Hi @nmofonseca . I don't think I have resolved it, it doesn't seem possible to work around with terraform only. If I remember correctly, I opted for creating the service-linked role manually in the AWS console, removing it from terraform code, and then running terraform apply.

**Comment by nmofonseca** [comment]
@mj3c , thanks for coming back at me, I tried to create the role manually using aws cli, like this: 

```bash
aws iam create-service-linked-role --aws-service-name autoscaling.amazonaws.com --custom-suffix myenv and changed the 
```

Then I changed the policy to use that role on the ebs policy:

```tf
data "aws_iam_policy_document" "ebs" {
  # Copy of default KMS policy that lets you manage it
  statement {
    sid       = "Enable IAM User Permissions"
    actions   = ["kms:*"]
    resources = ["*"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
    }
  }

  # Required for EKS
  statement {
    sid = "Allow service-linked role use of the CMK"
    actions = [
      "kms:Encrypt",
      "kms:Decrypt",
      "kms:ReEncrypt*",
      "kms:GenerateDataKey*",
      "kms:DescribeKey"
    ]
    resources = ["*"]

    principals {
      type = "AWS"
      identifiers = [
        "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling_myenv", # required for the ASG to manage encrypted volumes for nodes
        module.eks.cluster_iam_role_arn,                                                                                                            # required for the cluster / persistentvolume-controller to create encrypted PVCs
      ]
    }
  }

  statement {
    sid       = "Allow attachment of persistent resources"
    actions   = ["kms:CreateGrant"]
    resources = ["*"]

    principals {
      type = "AWS"
      identifiers = [
        "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling_myenv", # required for the ASG to manage encrypted volumes for nodes
        module.eks.cluster_iam_role_arn,                                                                                                            # required for the cluster / persistentvolume-controller to create encrypted PVCs
      ]
    }

    condition {
      test     = "Bool"
      variable = "kms:GrantIsForAWSResource"
      values   = ["true"]
    }
  }
}
```

Which made the code move from the ebs key and created it, however when I looked at IAM I had both roles:

AWSServiceRoleForAutoScaling_npinfra and AWSServiceRoleForAutoScaling so it seems the module still tries to create the role, do you mean removed the code from a fork of the module or something else?

However, the apply now moves forward, the eks managed node group is failing, I was seeing a bunch of ec2 instances that were spun up but terminated and it took like 21 minutes until it failed:

```bash
Error: error waiting for EKS Node Group (wtw-mdp-npinfra-eks-cluster:eks-mycluster-nodes-20220302095107997600000008) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 2 errors occurred:

[2022-03-02T10:14:50.512Z] │ 	* eks-eks-mycluster-nodes-20220302095107997600000008-78bfa505-2f87-0b52-0ebc-d234bc416cf8: AsgInstanceLaunchFailures: Instance became unhealthy while waiting for instance to be in InService state. Termination Reason: Client.InternalError: Client error on launch

[2022-03-02T10:14:50.512Z] │ 	* i-007e452f1ac93f121, i-00f092689e4ceb6c9, i-01585c3d6882737ba, i-0270db681d2768120, i-02f0dbf02610ce368, i-05d816fa9b69bcbc0, i-0696c927eacd02903, i-06dac83a15ebc51bd, i-07285a2af85dba771, i-07d2b456d17d5a61b, i-091e2519263f85285, i-0d0e6eb7b6de95a31, i-0d8ecb4c9c7df3cb8, i-0f023298f2e513a47, i-0f55b41b692938ef7: NodeCreationFailure: Instances failed to join the kubernetes cluster
```

Which sounds similar to another github issues [#1910](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1910)

Maybe I will need to raise my own issue.

**Comment by mj3c** [comment]
@nmofonseca You created your custom service-linked role (by specifying the suffix), but if you are using EKS-managed nodes (called "node groups" in terraform), there is no way to make them use your own custom role, they always use the role called `AWSServiceRoleForAutoScaling`. At least that was my experience some months back.

If you want to use your own role `AWSServiceRoleForAutoScaling_myenc`, you can do that by using custom node groups (called "worker groups" in terraform), because the worker group resource has an attribute where you can set your custom role.

It's a bit confusing because of the terminology but that's as best as I can explain the conclusions I reached. You can check my previous comments again, maybe it helps.

**Comment by nmofonseca** [comment]
@mj3c  and does it work if I create the role AWSServiceRoleForAutoScaling manually, or using terraform before ruing the eks modules and kms code?

I will give it a try anyway :)

Thanks for taking your time and replying to me, much appreciated

**Comment by nmofonseca** [comment]
@mj3c , yep if I create without the custom suffix the role first then everything seems to be working, thanks for pointing me in the right direction

**Comment by nmofonseca** [comment]
@mj3c  and for everyone benefit I managed to create the role using terraform, just make sure It is created before the cluster and key.

Code snippet:

```tf
resource "aws_iam_service_linked_role" "autoscalingrole" {
  aws_service_name = "autoscaling.amazonaws.com"

  tags = merge(
    local.tags,
    {
      Name = "npinfra-eks-autoscaling-role"
    }
  )
}
```

This will create the service-linked role.

Cheers.

**Comment by bryantbiggs** [comment]
Just to be clear, this is not a module related issue and an issue due to the way AWS handles this role. If you have never created an ASG in your account, this default role will not exist - it only comes into existence if either:
1. You create it
2. You deploy an ASG which creates it

The problem then becomes an issue because some accounts may have the role, others do not, and its a mess. You can create this role in Terraform but if it already exists in an account, you'll have to skip it or import it. 

The problem is further compounded by the EKS managed node group service because that service's API does not expose the ability to specify which service linked role to use.

**Comment by nmofonseca** [comment]
> 

Hello @bryantbiggs ,  once again thank you so much for clarifying and explaining and most of all taking time to do it.

I totally understand this is not related with the module itself and I should have made it clear on my previous comment.

For my use case, I will make it part of the account bootstrap to make sure it's there, but yes the strategy for ensuring the role is there is nothing the creators and maintainers of this module can do, I just wanted to share what I did for the next person that faces the issue like me.

I also understand is not really a solution more an workaround but hopefully will avoid others wasting a couple of hours 👍

**Comment by bryantbiggs** [comment]
no worries at all - when I see lots of activity on closed issues I try to put a summary since it means others are encountering the same issue and are coming back to these issues looking for potential solutions
