### ISSUE TITLE
Docs on subnets are misleading and not following recommended practice

### ISSUE THREAD

**Issue by jaredready** [terraform-aws-modules/terraform-aws-eks#1620]
## Description

The `subnets` variable is described as `A list of subnets to place the EKS cluster and workers within.`. This is not really correct. The EKS cluster (control plane) runs in an AWS-managed VPC and account. The subnets provided to the EKS Cluster API are the subnets where the service places ENIs for cross-VPC communication between nodes and the control plane.

It is also recommended that these ENIs be placed in small subnets dedicated to this purpose. Emphasis mine.

> Make sure that the subnets that you specify during cluster creation have enough available IP addresses for the Amazon EKS created network interfaces. We recommend creating small (/28), dedicated subnets for Amazon EKS created network interfaces, and only specifying these subnets as part of cluster creation. **Other resources, such as nodes and load balancers, should be launched in separate subnets from the subnets specified during cluster creation.**

https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html

This behavior seems to be supported by specifying different subnets in `var.subnets` and `worker_groups[].subnets` but the docs on these inputs are not clear.

I suggest updating the documentation on the `subnets` variable, making a note about to support using separate subnets for the EKS ENIs and worker nodes, and/or adding an extra optional variable (maybe `eni_subnets`?).

**Comment by daroga0002** [comment]
Duplicates https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1312
