### ISSUE TITLE
Steps to use Windows workers in the FAQ are not working

### ISSUE THREAD

**Issue by fsalum** [terraform-aws-modules/terraform-aws-eks#1624]
Hi folks,

I'm following https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#how-can-i-use-windows-workers, my windows worker node gets created (I see it on the EC2 instances) but it never joins the EKS cluster.

I followed the steps from the FAQ:
1. Create my EKS cluster with linux workers only
2. Followed AWS steps to enable windows support
3. Update my terraform file to include the windows worker group
4. Applied the changes
5. Windows instance shows up on EC2 but doesn't join the EKS cluster

Am I missing something ?

Thanks,
Felipe

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.0.0 :tada:
