### ISSUE TITLE
Allow spot_options for launch templates

### ISSUE THREAD

**Issue by davidweizheng** [terraform-aws-modules/terraform-aws-eks#1626]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
Yes. It is currently not possible to set `spot_options` for launch templates.

## Describe the solution you'd like.

Allow `spot_options` for launch templates. For example:

```
resource "aws_autoscaling_group" "workers_launch_template" {
  ...
  instance_market_options {
    market_type = "spot"
    spot_options {
      block_duration_minutes = 60
    }
  }
}
```

Currently, only `market_type` is supported under `instance_market_options`.

## Describe alternatives you've considered.
N/A

## Additional context

N/A

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.0.0 :tada:
