### ISSUE TITLE
missing conditional for datasource

### ISSUE THREAD

**Issue by daroga0002** [terraform-aws-modules/terraform-aws-eks#1632]
## Description

https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1580 introduces bug which occurs when `var.create_eks` is setup for false. This is because https://github.com/terraform-aws-modules/terraform-aws-eks/blob/f198efd2c4ed695c8018ee343701454069806790/modules/node_groups/locals.tf#L1-L3 always require a input (which in case of `create_eks` is optional).

In node group we are doing this by `if` https://github.com/terraform-aws-modules/terraform-aws-eks/blob/f198efd2c4ed695c8018ee343701454069806790/modules/node_groups/locals.tf#L43 so this is respected there.

We need add to data source something like:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/f198efd2c4ed695c8018ee343701454069806790/modules/fargate/main.tf#L13

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions
any versions of tf and aws provider

## Reproduction
run `examples/complete`

## Expected behavior
It should not throw error

## Actual behavior
```
$ terraform plan
╷
│ Error: "name" length must be between 1-100 characters: ""
│ 
│   with module.disabled_node_groups.data.aws_eks_cluster.default,
│   on ../../modules/node_groups/locals.tf line 2, in data "aws_eks_cluster" "default":
│    2:   name = var.cluster_name
│ 
╵
╷
│ Error: "name" doesn't comply with restrictions ("^[0-9A-Za-z][A-Za-z0-9\\-_]+$"): ""
│ 
│   with module.disabled_node_groups.data.aws_eks_cluster.default,
│   on ../../modules/node_groups/locals.tf line 2, in data "aws_eks_cluster" "default":
│    2:   name = var.cluster_name
│ 
╵
╷
│ Error: "name" length must be between 1-100 characters: ""
│ 
│   with module.disabled_eks.module.node_groups.data.aws_eks_cluster.default,
│   on ../../modules/node_groups/locals.tf line 2, in data "aws_eks_cluster" "default":
│    2:   name = var.cluster_name
│ 
╵
╷
│ Error: "name" doesn't comply with restrictions ("^[0-9A-Za-z][A-Za-z0-9\\-_]+$"): ""
│ 
│   with module.disabled_eks.module.node_groups.data.aws_eks_cluster.default,
│   on ../../modules/node_groups/locals.tf line 2, in data "aws_eks_cluster" "default":
│    2:   name = var.cluster_name
│ 
```

**Comment by stevehipwell** [comment]
@daroga0002 I assume that this issue is only impacting where `var.create_eks == false` and not what was reported yesterday?

I saw this behaviour yesterday and assumed that it wasn't an issue as it was previously working, but one reviewing again today I can see the issue. Off the top of my head a fix would be to set `cluster_name = var.create_eks ? coalescelist(aws_eks_cluster.this[*].name, [""])[0] : var.cluster_name`.

Furthermore should the module be able to create MNGs if `var.create_eks == false`?
