### ISSUE TITLE
Document how to do Kubernetes version upgrades

### ISSUE THREAD

**Issue by shrinandj** [terraform-aws-modules/terraform-aws-eks#164]
# I have issues
Finding out how I could perform a cluster upgrade when a new K8S version is supported by EKS.

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I tried to modify my existing terraform template and changed `cluster_version`. But doing a `terraform apply` after that did not change anything in the cluster.

Could you document the way these upgrades can be performed? If it's too complicated, please write the shorter version here. I can volunteer to write a more detailed version and add it in the docs.

**Comment by max-rocket-internet** [comment]
> Finding out how I could perform a cluster upgrade when a new K8S version is supported by EKS.

Currently you can't. AWS say you have to remove the cluster and create a new one 💣

**Comment by shrinandj** [comment]
Whaaa....??? 

Neways, thanks for the update! I'll close this issue and keep an eye on the official documentation.
