### ISSUE TITLE
Eks cluster upgrade including node groups

### ISSUE THREAD

**Issue by OldWarrior3000** [terraform-aws-modules/terraform-aws-eks#1641]
Hi, 

Maybe I was looking in the wrong place but I couldn't find any documentation around it in the repository.

I created a cluster with the terraform module (1.20) now I would like to upgrade the cluster including it's node groups via `terraform apply`.

When changing the cluster version it correctly propagates the upgrade but the node groups (I am using aws node groups not worker groups) stayed the same. Is there a safe way doing it via terraform? Also some of my node groups contains state, which complicates the migration to a new node group. 

Thanks in advance!

**Comment by vidbaz** [comment]
I have the same issue, so basically we need to update worker nodes "manually", it would be awesome that this information is somewhere in the documentation.

https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1608#issuecomment-940871348

**Comment by bryantbiggs** [comment]
> I have the same issue, so basically we need to update worker nodes "manually", it would be awesome that this information is somewhere in the documentation.
> 
> [#1608 (comment)](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1608#issuecomment-940871348)

This is related to general Kubernetes/EKS knowledge and not related to the module so I don't think it makes sense to go on the module documentation
