### ISSUE TITLE
Unable to add SG's to worker nodes

### ISSUE THREAD

**Issue by janibashamd** [terraform-aws-modules/terraform-aws-eks#1648]
## Description

I am trying to create all resources from scratch like VPC, subnets, SG's, EKS, etc. I tried below code which is not working to detect SG from provided VPC. Instead for some reason SG's is being looked in default VPC but not user provided VPC.

## ⚠️ Note
Steps performed -
1. Created Network components like new VPC, SN's, SG's, etc
2. Tried to create EKS using aws-eks module to use existing SG for worker nodes.

## Versions

 - Terraform: 0.13
 
 - Provider(s):

 - Module:
```terraform
terraform {
  required_version = "~> 0.13"
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = ">2.3.0"
    }
    template = {
      source  = "hashicorp/template"
      version = ">2.1.2"
    }
    null = {
      source  = "hashicorp/null"
      version = ">2.1.2"
    }
    bigip = {
      source = "F5Networks/bigip"
      version = "1.8.0"
    }

  }
}
```
## Reproduction

 No
 Yes

### Code Snippet to Reproduce

module "my-cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "automation-eks-cluster"
  vpc_id       = aws_vpc.Main.id
  cluster_version = "1.21"
#  cluster_create_security_group = false
#  cluster_security_group_id = "aws_security_group.sg1.id"
  worker_create_security_group = false
  worker_security_group_id = "aws_security_group.sg2.id"
  worker_additional_security_group_ids = ["aws_security_group.sg1.id"]
  subnets      = [aws_subnet.publicsubnet1.id, aws_subnet.publicsubnet2.id, aws_subnet.publicsubnet3.id]
  worker_groups = [
    {
      instance_type = "m4.large"
      asg_max_size  = 1
    }
  ]
}

## Expected behavior
Workers should be created with provided SG's

## Actual behavior
Provided SG is searched in default VPC

### Terminal Output Screenshot(s)

Error: Error creating launch configuration: ValidationError: The security group 'aws_security_group.sg1.id' does not exist in default VPC 'vpc-87666654'
	status code: 400, request id: <>

**Comment by antonbabenko** [comment]
You should not write the value as a string.

Instead of `["aws_security_group.sg1.id"]` you should write `[aws_security_group.sg1.id]`. Look into the format you specified in `subnets`.

**Comment by antonbabenko** [comment]
There is no better way to get IP addresses other than using data sources as you described.
