### ISSUE TITLE
Create EBS Storage Class 

### ISSUE THREAD

**Issue by simonmacklin** [terraform-aws-modules/terraform-aws-eks#165]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
At the moment after bringing up a new cluster I have to apply the EBS storage class manually.  I can imagine everyone using this module will require EBS storage at some point and it would be great if we can get this module to create it for us with a local exec and template.

## Are you able to fix this problem and submit a PR? Link here if you have already.

Yes is everyone is in agreement I will write the code and submit a PR.

**Comment by max-rocket-internet** [comment]
Hey @simonmacklin,
We have already discussed this type of change a few times, here's the reference:
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/99

Personally, I think AWS should include this resource by default, just like they do for `clusterrolebinding`

**Comment by simonmacklin** [comment]
Thanks @max-rocket-internet 

After reading #99 I totally get the why it is not in the module. 

Thanks again

**Comment by max-rocket-internet** [comment]
All good, glad you understand.

BTW, kops creates it by default:
https://github.com/kubernetes/kops/pull/1304/files

So I think there is good grounds to just ask AWS to do it also. I've asked in their Slack. I think it's already been requested also 🤞

**Comment by simonmacklin** [comment]
Nice one!
