### ISSUE TITLE
wait_for_cluster times out after updating from 13.X to 17.22.0 w. private access enabled and public access disabled

### ISSUE THREAD

**Issue by tech4242** [terraform-aws-modules/terraform-aws-eks#1657]
## Description

The problem is that after upgrading EKS module from 13.X to 17.22.0 (big upgrade, I know) my bastion host setup does not work anymore. 

```
module "eks" {
  cluster_endpoint_private_access = true
  cluster_create_endpoint_private_access_sg_rule = true
  cluster_endpoint_private_access_cidrs = [aws_subnet.xx_sg_subnet.cidr_block]
  cluster_endpoint_public_access  = false
}
```
where `aws_subnet.xx_sg_subnet.cidr_block` is the CIDR block of the bastion host.

and the k8s provider is:
```
provider "kubernetes" {
  token                  = data.aws_eks_cluster_auth.xx-eks.token
  config_path            = "~/.kube/config"
  insecure               = true
}
```
While I was still running 13.X, wait_for_cluster (I assume) was a more tightly integrated resource of the eks module (AFAIK) and after upgrade to 17.22.0.

`terraform plan` output is: `module.eks.data.http.wait_for_cluster[0]`throws a `connect: operation timed out`

This is an expected error if networking is not setup properly but how I run the setup (or used to) is that my kubeconfig maps to localhost and I have an ssh tunnel to my bastion host. the k8s provider with the setup above (`config_path` (because my kubeconfig points cluster to localhost) and `insecure`) would patch/proxy the wait_for_cluster request properly 

but the new version in `data.tf`:

```
data "http" "wait_for_cluster" {
  count = var.create_eks && var.manage_aws_auth ? 1 : 0

  url            = format("%s/healthz", aws_eks_cluster.this[0].endpoint)
  ca_certificate = base64decode(local.cluster_auth_base64)
  timeout        = var.wait_for_cluster_timeout

  depends_on = [
    aws_eks_cluster.this,
    aws_security_group_rule.cluster_private_access_sg_source,
    aws_security_group_rule.cluster_private_access_cidrs_source,
  ]
}
```

*My theory:* `wait_for_cluster` does a normal HTTP request without the kubernetes provider `config_path` setting, so the connection times out on `terraform plan` as the cluster cannot be reached. 

Tried commenting out the ca_certificate etc. but this request just does not follow the old path.

## Versions

```
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.14.0
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

## Expected behavior
Be able to use terraform even if `cluster_endpoint_public_access  = false` due to `config_path` setting in kubernetes provider. 

I am aware that these 2 providers are separate entities but my question is this: 

**What is the new/actual/preferred way of only being able to access the cluster through a bastion host?**

## Actual behavior
Cannot use terraform anymore as long as `cluster_endpoint_public_access  = false` because the data http wait_for_cluster request times out. 

If I change `cluster_endpoint_public_access  = true` (e.g. via AWS console)  I can run everything even if I use

```
provider "kubernetes" {
  token                  = data.aws_eks_cluster_auth.xx-eks.token
  config_path            = "~/.kube/config"
  insecure               = true
}
```

instead of 

```
provider "kubernetes" {
  host                   = data.aws_eks_cluster.xx-eks.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.xx-eks.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.xx-eks.token
}
```

which makes sense since if `cluster_endpoint_public_access  = true` I can use any IP to connect to the k8s API - even my localhost SSH tunnelling setup so there the data http request from above does not timeout anymore.

At least it's deterministic. 

I am also happy to change my kubernetes provider method to something else as long as I can keep my k8s access private only.

**Comment by tech4242** [comment]
> > _My theory:_ `wait_for_cluster` does a normal HTTP request without the kubernetes provider `config_path` setting, so the connection times out on `terraform plan` as the cluster cannot be reached.
> 
> http data source is just doing normal http request to K8s API it had replaced curl/wget to make this more platform agnostic as this data source giving a repeatable and predicted behaviour over each platform

I understand but the problem is now that setups like this:

```
provider "kubernetes" {
  token                  = data.aws_eks_cluster_auth.xx-eks.token
  config_path            = "~/.kube/config"
  insecure               = true
}
```

where I can SSH tunnel traffic to my bastion host via my kubeconfig to connect to EKS does not work anymore.

**So my question is: how do you connect to private-access only EKS clusters with Terraform?**

**Comment by daroga0002** [comment]
> So my question is: how do you connect to private-access only EKS clusters with Terraform?

you must run terraform from subnet under which there is access to EKS endpoint (remember also to open a security group to EKS endpoint).

**Comment by tech4242** [comment]
> > So my question is: how do you connect to private-access only EKS clusters with Terraform?
> 
> you must run terraform from subnet under which there is access to EKS endpoint (remember also to open a security group to EKS endpoint).

you do see the chicken/egg problem right? I want to terraform my bastion host but I actually need to manually create a bastion host and run terraform there.

I tried https://github.com/sshuttle/sshuttle in order to route my traffic through the bastion host and I can make requests from the bastion host's IP but I still cannot reach the `https://` AWS URL.

```
module.eks.module.node_groups.aws_launch_template.workers["second"]: Refreshing state... [id=x]
╷
│ Error: Error making request: Get "https://xxx.amazonaws.com/healthz": dial tcp xxx:443: connect: operation timed out
│
│   with module.eks.data.http.wait_for_cluster[0],
│   on .terraform/modules/eks/data.tf line 92, in data "http" "wait_for_cluster":
│   92: data "http" "wait_for_cluster" {
│
╵
```

can you think of another networking setup? I really don't want to have all of my tfstate etc. on the bastion host itself and there should be some "standard" way of doing this - bastion hosts are pretty common I thought.

**Comment by daroga0002** [comment]
> I really don't want to have all of my tfstate etc. on the bastion host itself

You should use remote state (for example s3) and locking mechanism (for example dynamodb table).

This is very specific use case which is not common. Most of the flows for private only clusters are that users have arleady some `runner` which is running in their private agent under CI/CD process (like Jenkins or etc.)

If you need special customization you can fork module or use some 13.X  version

**Comment by jaimehrubiks** [comment]
I agree with @daroga0002 , this is just a regular HTTP request, so it makes sense as it is very standard.

The regular use case is to use terraform from the bastion host (and use some backend like s3 to store the state).

I can try to think of some workaround like:

a) Use your "/etc/hosts" file to trick your OS into replacing the EKS endpoint to localhost
b) Use a VPN from your bastion to your laptop
c) Fork the module
...
