### ISSUE TITLE
Better way to reserve system resource is needed

### ISSUE THREAD

**Issue by JaslynnWangTR** [terraform-aws-modules/terraform-aws-eks#1659]
## Is your request related to a problem? Please describe.

- I need a way to reserve system resource without restarting kubelet.
Currently I am using the parameter to reserver (something similar to the below code), however, it looks like this method is going to be deprecated. So I am trying to find a new way. The alternative method I found is to change /etc/kubernetes/kubelet/kubelet-config.json and restart kubelet. But I need a way to reserve resource without restarting kubelet. Can we have a better way to reserve resource?
Thank you

#!/bin/bash
set -o xtrace
/etc/eks/bootstrap.sh
--apiserver-endpoint '${master_endpoint}'
--b64-cluster-ca '${certificate_authority_b64}'
'${cluster_name}'
--kubelet-extra-args "--read-only-port=10255 --node-labels=cluster=${cluster_name} --kube-reserved memory=0.5Gi,ephemeral-storage=2Gi --system-reserved memory=0.3Gi,ephemeral-storage=1Gi --eviction-hard memory.available<200Mi,nodefs.available<10%"

I copied this code from https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1153

## Describe the solution you'd like.

- reserve system resource without restarting kubelet

**Comment by ashishjullia** [comment]
@daroga0002  is it possible to replicate the same functionality with [node_group_defaults](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/99d289988df56cd8469a2e17f2bfb220dc87b701/examples/complete/main.tf#L64)

I'm trying to achieve something like [this](https://github.com/awslabs/amazon-eks-ami/issues/318#issuecomment-546534337).
