### ISSUE TITLE
Automatize enabling windows nodes support

### ISSUE THREAD

**Issue by schwichti** [terraform-aws-modules/terraform-aws-eks#1663]
## Is your request related to a new offering from AWS?
no

## Is your request related to a problem? Please describe.
As stated in the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#how-can-i-use-windows-workers) I need to "apply some configs manually" to "enable Windows support for your EKS cluster".
The FAQ also suggests not to use eksctl but the Powershell scripts provided by AWS. Is there a reason not to use eksctl?
I would like to automate these manual steps.

## Describe the solution you'd like.
This is my solution approach:
```hcl
resource "null_resource" "prepare_windows" {
  provisioner "local-exec" {
    command = "eksctl utils install-vpc-controllers --cluster ${var.infrastructurename}-eks --approve"
    interpreter = ["PowerShell", "-Command"]
  }
  depends_on = [module.eks]
}
```

But how can I delay the creation of windows worker nodes until vpc controllers have been installed?

## Describe alternatives you've considered.
Do everything manually like it's 1798.

**Comment by schwichti** [comment]
Just discovered this Helm chart that might solve the issue: https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/kubernetes-addons/windows-vpc-controllers

Will check later.

**Comment by schwichti** [comment]
> Will check later.

No, I won't. Windows VPC controllers are not needed anymore. Check https://github.com/aws-samples/aws-eks-accelerator-for-terraform/pull/85#issue-1065524718 and https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support

**Comment by bryantbiggs** [comment]
Unfortunately, I don't know how much of this can be supported so I'm going to close this issue for now. PRs are always welcome for review
