### ISSUE TITLE
Managed Node Group:  Cant Set on_demand_base_capacity   

### ISSUE THREAD

**Issue by jseiser** [terraform-aws-modules/terraform-aws-eks#1670]
When configuring Managed node groups, we should be able to control:

on_demand_base_capacity
spot_allocation_strategy
on_demand_percentage_above_base_capacity

Ive attempted to set this in 

## Describe the solution you'd like.
I would like to be able to define

on_demand_base_capacity
spot_allocation_strategy
on_demand_percentage_above_base_capacity

**Comment by daroga0002** [comment]
> Ive attempted to set this in

how you were setting this?

**Comment by daroga0002** [comment]
Please also provide more details about your issue as we cannot accept such drop in without any details

**Comment by jseiser** [comment]
@daroga0002 


Sorry, was copy/pasting and must have dropped it.


```
workers_group_defaults_defaults = {
    on_demand_base_capacity                  = "50" 
    on_demand_percentage_above_base_capacity = "0" 
    spot_allocation_strategy                 = "capacity-optimized"
}

  node_groups_defaults = {
    ami_type               = "AL2_x86_64"
    disk_size              = var.node_group_default_disk_size
    disk_encrypted         = true
    pre_userdata           = templatefile("${path.module}/templates/userdata.tpl", {})
    update_default_version = true
    root_volume_type       = "gp3"
  }
  node_groups = {
    private1 = {
      subnets          = [tolist(data.aws_subnet_ids.private.ids)[0]]
      desired_capacity = lower(var.platform_env) == "prod" ? 3 : 2
      max_capacity     = lower(var.platform_env) == "prod" ? 6 : 3
      min_capacity     = lower(var.platform_env) == "prod" ? 3 : 1

      instance_types = lower(var.platform_env) == "prod" ? var.prod_instance_types : var.dev_instance_types
      capacity_type  = "SPOT"

      additional_tags = {
        Name    = format("%s-%s-%s", var.layer, var.vpc_id_tag, var.platform_env)
      }

      update_config = {
        max_unavailable_percentage = 50
      }
    }
}
```

This just resulted in a managed node group, with pure spot instances.  I could go into the UI and adjust the base capacity etc, but it was not picked up from the TF.

**Comment by daroga0002** [comment]
please look into https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#why-does-changing-the-node-or-worker-groups-desired-count-not-do-anything


as we ignore min and desired capacity after creating node groups

**Comment by jseiser** [comment]
@daroga0002 

I guess im not seeing the relationship here?  Im not asking about node counts, im talking about mixing on-demand and spot instances, at a certain capacity percentage when using managed nodes.

**Comment by daroga0002** [comment]
> I guess im not seeing the relationship here? Im not asking about node counts, im talking about mixing on-demand and spot instances, at a certain capacity percentage when using managed nodes.

then you must create two node groups, one for spot and second for ondemand, pure node groups doesnt support mixed on-demand and spot instances.

**Comment by nickvanwegen** [comment]
@daroga0002 

I think I am facing the same problem. Let me try to explain. 

So in the main module if you use un-managed nodes you have a option to set `spot_allocation_strategy`

I have the following configuration for node_groups and it does not change the value. 

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "17.23.0"
  cluster_version = var.cluster_version
  cluster_name    = var.cluster_name
  vpc_id          = var.vpc_id
  subnets         = var.subnets

  enable_irsa = true

  workers_group_defaults = {
    spot_allocation_strategy = "lowest-price"
    protect_from_scale_in    = true
    max_instance_lifetime    = 120
  }


  node_groups_defaults = {
    name_prefix              = "xcp"
    create_launch_template   = true
    set_instance_types_on_lt = false
    disk_encrypted           = true
    disk_kms_key_id          = ""
    disk_size                = 25
    ami_type                 = "AL2_x86_64"
    capacity_type            = "SPOT"

    update_config = {
      max_unavailable_percentage = 25
    }

    bootstrap_env = {
      CONTAINER_RUNTIME = "containerd"
    }

  }

  node_groups = var.node_groups

}
```

```
  node_groups = [
    {
      name             = "main-1"
      instance_types   = ["m5.large", "m5a.large"]
      desired_capacity = 1
      max_capacity     = 10
      min_capacity     = 1
      subnets          = ["subnet-1"]
    },
    {
      name             = "main-2"
      instance_types   = ["m5.large", "m5a.large"]
      desired_capacity = 1
      max_capacity     = 10
      min_capacity     = 1
      subnets          = ["subnet-2"]
    },
    {
      name             = "main-3"
      instance_types   = ["m5.large", "m5a.large"]
      desired_capacity = 1
      max_capacity     = 10
      min_capacity     = 1
      subnets          = ["subnet-3"]
    }
  ]

```

![image](https://user-images.githubusercontent.com/47427309/141101662-ce2f9fa3-8656-46e7-8035-269a7473ef0c.png)

Same is true for other configuration for spot instances with managed nodes. 
For example some settings i would like to put but i cannot

protect_from_scale_in
spot_allocation_strategy

And a lot of other mixes instance LT configuration options. 

Am i doing something wrong within the config or is it just not available at this moment to use these options?

**Comment by daroga0002** [comment]
you are using `node_groups` and they dont support `spot_allocation_strategy`.

If you want to use it then you must use workers, example of config:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/56e93d77de58f311f1d1d7051f40bf77e7b03524/examples/launch_templates/main.tf#L24-L74

**Comment by nickvanwegen** [comment]
@daroga0002 

I know workers support them. 
Are you going to support this in the future?

See screenshot below is my above configuration manually adjusted for spot_allocation_strategy = lowest-price

![image](https://user-images.githubusercontent.com/47427309/141107277-39bd47e4-66fb-4005-bb23-06b041be918f.png)

**Comment by daroga0002** [comment]
looks it is missing in terraform resource https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group

so you can open a issue on https://github.com/hashicorp/terraform-provider-aws and when it will be added then we will be able to extend module

**Comment by jseiser** [comment]
Yes, thanks @nickvanwegen  !

I was trying to communicate that it appears like it is supported by AWS, just that I can not get it to work via the module.

Thanks everyone.
