### ISSUE TITLE
AZ Rebalance gets suspendend by default in v17.22.0

### ISSUE THREAD

**Issue by Arisfx** [terraform-aws-modules/terraform-aws-eks#1687]
## Description

Our tf code is adding on the worker autoscaling groups the `AZRebalance` as a **suspending** process. 

I had to go to `.terraform/modules/eks/locals.tf` and from there locate the default values of `workers_group` and change `suspended_processes` from `["AZRebalance"]` to `null`. 
But we use a pipeline to apply the terraform code and manually edit the .terraform folder is not an option.

Can you please advise?

**Comment by daroga0002** [comment]
you can change this via input workers_group_defaults (applicable to all workers):

```
workers_group_defaults = {
   suspended_processes = null
}
```
or by defining to particular worker group:
 ```
  worker_groups = [
    {
      name                          = "worker-group-1"
      instance_type                 = "t3.small"
      additional_userdata           = "echo foo bar"
      asg_desired_capacity          = 2
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_one.id]
    },
    {
      name                          = "worker-group-2"
      instance_type                 = "t3.medium"
      additional_userdata           = "echo foo bar"
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_two.id]
      asg_desired_capacity          = 1
      suspended_processes = null
    },
  ]
```

**Comment by Arisfx** [comment]
Thank you Dawid.
