### ISSUE TITLE
Bug: using write_kubeconfig="false" and manage_aws_auth="true" causes "no such file"

### ISSUE THREAD

**Issue by philwinder** [terraform-aws-modules/terraform-aws-eks#169]
If you set  write_kubeconfig="false" and manage_aws_auth="true", then the aws_auth file will try to `kubectl apply` the auth configmap. See [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/aws_auth.tf#L11).

But if the kubeconfig file isn't written, then it can't find the kubeconfig.

The easiest fix is to always write the file, but I would like to not create the kubeconfig file for other reasons.

**Comment by max-rocket-internet** [comment]
Understood. Happy to accept a PR for this also.

**Comment by max-rocket-internet** [comment]
@philwinder can you test this PR? https://github.com/terraform-aws-modules/terraform-aws-eks/pull/228

**Comment by max-rocket-internet** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/228
