### ISSUE TITLE
AWS EKS error creating EKS Cluster (complete-Tq06LkVT)  module.eks.aws_eks_cluster.this[0]

### ISSUE THREAD

**Issue by favourjuwe** [terraform-aws-modules/terraform-aws-eks#1693]
Hello team, I am working with this repo :

https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/complete

to create an AWS EKS cluster.

After running 

Terraform init
Terraform plan
Terraform apply

r current setup : windows 10 OS
Terraform version : Terraform v1.0.0 on windows_amd64

I am getting this error

error creating EKS Cluster (complete-Tq06LkVT)  module.eks.aws_eks_cluster.this[0]

│   on ..\..\main.tf line 11, in resource "aws_eks_cluster" "this":
│   11: resource "aws_eks_cluster" "this" {
│

**Comment by daroga0002** [comment]
Windows is not always native platform for terraform so I will recommend you to update terraform to latest version and then try

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.0.0 :tada:
