### ISSUE TITLE
Mixed ondemand and spot instances with managed nodegroups

### ISSUE THREAD

**Issue by e-tip** [terraform-aws-modules/terraform-aws-eks#1696]
## Is your request related to a problem? Please describe.
As far as i've understand, mixed OnDemand and spot ASG can be created only using worker_nodes and not using node_groups
Unfortunately all my groups are managed due to a company policy that wants to have as many externally managed things. 
And in this case i can't manage to have a node_group with 3 ondemand based instance and the rest of 100% spot instances

## Describe the solution you'd like.
a property like worker_groups_launch_template only for node_groups

**Comment by daroga0002** [comment]
if you want mix spot and ondemand group in single managed node group without launch template then it is not supported by AWS itself. 

If you mean something different then the best show me screen from AWS UI how you configuring this.

**Comment by e-tip** [comment]
I'm getting this by modifying the created underlying ASG in this wa
![Schermata 2021-11-19 alle 15 17 39](https://user-images.githubusercontent.com/1098494/142637259-959dff2f-94fd-4b2b-abb7-159930e0d625.png)
y

**Comment by daroga0002** [comment]
this is assumed as hack on managed groups as AWS EKS Nodegroup API doesnt support it
