### ISSUE TITLE
worker_groups_launch_template only one node connecting when "Private"

### ISSUE THREAD

**Issue by ArunaLakmal** [terraform-aws-modules/terraform-aws-eks#1697]
## Is your request related to a problem? Please describe.

I have created a `worker_groups_launch_template` type worker group with private IP address assignment. When I created this worker group with more instance only one instance is connecting to the cluster. But If I make it public, all nodes are connecting to the cluster. I know this is something I can check with aws and I'd like to know any similar issues or limitations in this scenario. 

Here is my `worker_groups_launch_template` configuration

```
{
    name                 = "infra"
    instance_type        = "t2.medium"
    asg_max_size         = 4
    asg_desired_capacity = 4
    asg_min_size         = 4
    public_ip            = false
    kubelet_extra_args   = "--node-labels=dumb.label.io/role=infra --register-with-taints=infrastructure=true:NoSchedule"
  }
```

with above configurations 4 nodes are provisioning but only one is in the cluster, if I make `public_ip  = true` all nodes are connecting to the cluster. This is kinda weird and I'd like to see your valuable ideas on this. 

*Note:* If I try to access  the nodes  via  SSM or instance connect it is also not succeeded, I feel something related to the networking layer.

**Comment by daroga0002** [comment]
please paste here full module config, terraform plan and other info as without this we cannot help

**Comment by ArunaLakmal** [comment]
Here is the entire eks cluster module for the cluster

```
locals {
    subnet_ids = concat(var.public_subnets, var.private_subnets)
}

data "aws_eks_cluster" "cluster" {
  name = module.colyseus-eks-cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.colyseus-eks-cluster.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "~> 1.9"
}

module "colyseus-eks-cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = var.cluster_name
  cluster_version = var.kubernetes_version
  subnets         = local.subnet_ids
  vpc_id          = var.vpc_id

  worker_groups = var.worker_groups
  worker_groups_launch_template = var.custom_worker_groups
  
  map_roles    = var.map_roles
  map_users    = var.map_users
  map_accounts = var.map_accounts
}
```

I'm using terragrunt and here is the terraform vars file. 

```
worker_groups = [
  {
    instance_type        = "t2.medium"
    asg_max_size         = 10
    asg_desired_capacity = 2
    asg_min_size         = 2
  },
  {
    instance_type        = "t2.medium"
    asg_max_size         = 10
    asg_desired_capacity = 2
    asg_min_size         = 2
  },
]

custom_worker_groups = [
  {
    name                 = "infra"
    instance_type        = "t2.medium"
    asg_max_size         = 2
    asg_desired_capacity = 2
    asg_min_size         = 2
    public_ip            = true
    kubelet_extra_args   = "--node-labels=dumb.domain.io/role=infra --register-with-taints=infrastructure=true:NoSchedule"
  },
]


```

This is really strange and I'm still finding a solution for this. Only a single worker group is connecting to the cluster no matter how many nodes provisioned.
