### ISSUE TITLE
Feature request: option to not create the aws_auth files

### ISSUE THREAD

**Issue by philwinder** [terraform-aws-modules/terraform-aws-eks#170]
Can I suggest adding the ability to not create the aws_auth files, like you do for the kubeconfig file?

The reason why I would like this is because I use the same module on multiple different clusters. I don't want to store all those aws-auth files because the logic is contained within the code. Since I don't want to store them, I don't have them in git. So each time I re-apply, terraform thinks it needs to recreate then again, even though the actual aws_auth configmap hasn't changed.

(The same applies to the kubeconfig file too, I don't want to create that either)

In the past I have achieved this by piping the manifest into kubectl like this: `printf ${data.manifest.rendered} | kubectl apply...`

But note that this still relies on a kubeconfig file to exist (see #169).

**Comment by max-rocket-internet** [comment]
Sure! Sounds reasonable. PRs welcome 🙂

**Comment by max-rocket-internet** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/228
