### ISSUE TITLE
IRSA audience for aws-cn should be "sts.amazonaws.com"

### ISSUE THREAD

**Issue by sak-kishore** [terraform-aws-modules/terraform-aws-eks#1704]
**What happened?**

The cluster autoscaler pods deployed in cn-northwest-1 region using helm - https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa/irsa.tf kept crash looping. Investigating the pod logs, I found the following:

`│ E1124 11:33:38.307357       1 aws_manager.go:265] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials                                                                │
│ caused by: InvalidIdentityToken: Incorrect token audience                                                                                                                                                                 │
│     status code: 400, request id: b4faca20-b8fa-4b19-896c-64f70094d013  `

Upon checking the token audience in my OIDC provider, it was set by the module to `sts.amazonaws.com.cn `

_Output snippet:_ 

`{
    "Url": "oidc.eks.cn-northwest-1.amazonaws.com.cn/id/88E5C8D5DAFCCF674D4617208E9234E6",
    "ClientIDList": [
        "sts.amazonaws.com.cn",
    ],
    "ThumbprintList": [
        "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
    ],
    "CreateDate": "2021-11-25T12:25:03.385000+00:00",
    "Tags": [`

whereas it should be` sts.amazonaws.com` as per below references

https://aws.amazon.com/premiumsupport/knowledge-center/eks-troubleshoot-oidc-and-irsa/
https://github.com/weaveworks/eksctl/pull/1912

**Testing:**

I made the above changes by declaring the input variable in the main EKS module while enabling irsa and the pod crash loop was fixed

```
enable_irsa     = true
openid_connect_audiences = ["sts.amazonaws.com"]
```

**Comment by daroga0002** [comment]
does this is issue or you were able to solve this?

**Comment by sak-kishore** [comment]
I was able to solve it by updating the audience as above but by default when you deploy cluster autoscaler in the china region, you will face this issue. So the module needs to be updated to incorporate the right audience. In my view, we could keep the existing one `sts.amazonaws.com.cn` and inject the right one `sts.amazonaws.com` as well.

**Comment by daroga0002** [comment]
currently module allow customising and adding additional audiences, we don`t want to always inject `sts.amazonaws.com` as this is not always required. Issue is also strictly related to China users which have dedicated AWS docs which are describing those differences.

I am closing this issue as this is rather just a common configuration option used by China users
