### ISSUE TITLE
http.wait_for_cluster changes every time because of headers

### ISSUE THREAD

**Issue by lucasreed** [terraform-aws-modules/terraform-aws-eks#1708]
## Description
This was previously mentioned in #1578 but since that issue is closed (and also deals with two separate problems) I'm opening this new issue to track.

Basically the `Date` header will always return something different which is not desirable when dealing with terraform planfiles for deployment. I have opened a PR to the http provider that this module uses: https://github.com/terraform-aws-modules/terraform-provider-http/pull/10

Which would open up the option to add ignored response headers. If we can get some movement on that PR, that functionality could be adopted here to ignore the `Date` header.

## Versions

 - Terraform: 0.13.7

 - Provider(s): N/A

 - Module: v17.20.0 but any version newer than this will still have the problem

## Reproduction

- Run terraform plan
  - There will be a diff for the http.wait_for_cluster data object
- Run terraform plan again
  - There will be a new diff with a new value for the Date header in the same data object.

### Code Snippet to Reproduce

N/A
## Expected behavior

No diff should show if no resources are actually changing

## Actual behavior

No resources change, but this changing data object makes it impossible to run `terraform plan` into a plan file output and run a `terraform apply` using that planfile

### Terminal Output Screenshot(s)

(Stolen from the Issue that was closed that I mentioned at the top)
```
data "http" "wait_for_cluster"  {
        ...
      ~ response_headers = {
          ~ "Date"                              = "Tue, 14 Sep 2021 04:03:03 GMT" -> "Tue, 14 Sep 2021 04:03:11 GMT"
            ..
        }
    }
```

**Comment by daroga0002** [comment]
I propose you update a terraform to newest version as there was a change how refresh and real apply is done.

**Comment by lucasreed** [comment]
> I propose you update a terraform to newest version as there was a change how refresh and real apply is done.

Oh that's great, thank you!
