### ISSUE TITLE
Managed Node Group with LT - Insufficient InstanceType in specific AZ error

### ISSUE THREAD

**Issue by rangarb885** [terraform-aws-modules/terraform-aws-eks#1709]
## Description
_Disclaimer_ : This is not a bug. 

I want to understand what needs to be configured on NodeGroup and its corresponding Launch Template to handle the situation where an AZ does not have sufficient Instances to provision for the specific InstanceType.

## Versions

 - Terraform: v0.15

 - Provider(s):  v17.1.0

 - Module: 
 ```
hashicorp/kubernetes v2.2.0
hashicorp/aws v3.59.0
hashicorp/template v2.2.0
terraform-aws-modules/http v2.4.1
hashicorp/local v2.1.0
hashicorp/helm v2.2.0
hashicorp/cloudinit v2.2.0
hashicorp/archive v2.2.0
```

## Reproduction

Steps to reproduce the behaviour:

1. Create a EKS cluster with Managed NodeGroup (which manages ASG). MNG uses a Custom Launch Template. 
2. Cluster is configured with 4 subnets.
3. LT has a single InstanceType (say m5.2xlarge)
4. When the AMI is updated and new version of LT is released, MNG take cares of updating the cluster nodes with the help of ASG. 
5. During this process, due to some AWS AZ limitations during that time, one of the AZ has no available instance type of m5.2xlarge and leading to below error on AutoScalingGroup. This error causes longer time for MNG to update the cluster as ASG tries to balance the nodes across the AZs multiple times.
```
At 2021-12-01T19:44:33Z instances were launched to balance instances in zones us-west-2a us-west-2d with other zones resulting in more than desired number of instances in the group. 
At 2021-12-01T19:44:53Z availability zones us-west-2a us-west-2d had 3 1 instances respectively. 
An instance was launched to aid in balancing the group's zones.
``` 

Is there a way to handle this by setting ASG (managed by MNG) to ignore node balancing across AZs. 
As per my workload we don't care on which AZ the node are created but just want to make sure they are created on specific set of Subnets (private).

## Expected behaviour
ASG managed by MNG to ignore the need for balancing of nodes across AZ

## Actual behaviour
Though min nodes required on MNG is created, ASG keeps on trying to balance the node across AZs until it successful.

**Comment by daroga0002** [comment]
This is not supported in Managed groups, instead of that you can user worker groups which have this enabled by default

**Comment by rangarb885** [comment]
Thanks @daroga0002 . I am trying to use multiple `instance_types` to mitigate it. 
But do we know why instance_types  listed under `node_groups` gets sorted when it gets applied?  

I have 2 instance_types specified as `["m5.2xlarge, "m5.xlarge"]`. But when it gets applied on the node_group , `m5.xlarge` comes first and instance are provisioned with that.

**Comment by bryantbiggs** [comment]
@rangarb885 see https://github.com/hashicorp/terraform-provider-aws/pull/21404
