### ISSUE TITLE
Ability to specify tags for worker security groups

### ISSUE THREAD

**Issue by mikesir87** [terraform-aws-modules/terraform-aws-eks#1711]
## Is your request related to a problem? Please describe.
When using [Karpenter](https://karpenter.sh), it scans and automatically selects a security group that has the `kubernetes.io/cluster/<cluster-name>` tag to apply to the launch template it creates. But, since EKS automatically creates another security group with the same tag (and any automatically created by load balancers), there's a good chance that it doesn't select the right one. This obviously causes nodes to launch with the incorrect role and can't connect to the cluster, talk to each other, etc.

## Describe the solution you'd like.
I'd like the ability to specify tags specifically for the worker security group. But, I know that's not something this module has generally supported (one-off tags). And it doesn't make sense to specify it in the higher-level `tags` variable, as I don't need to add something to every security group.

## Describe alternatives you've considered.
We've thought about simply managing our own security group and replicating all of the security group rules. But, it would be nice if we didn't need to maintain that ourselves.

## Additional context
I'm happy to submit a PR based on any sort of direction/input on how you'd like to solve this.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.0.0 :tada:
