### ISSUE TITLE
InvalidParameterException: nodeGroupName can't be longer than 63 characters!

### ISSUE THREAD

**Issue by adrdimitrov** [terraform-aws-modules/terraform-aws-eks#1713]
## Description

Hello team,

We have a pretty lame issue here. In short our ClusterName is really long. 
The detailed description:
We are trying to upgrade our EKS module. Current version is 13.2.1. We are trying to upgrade it to the latest, but since our eks cluster name is a long one we are getting the following error trying to upgrade:

Error: error creating EKS Node Group (k8s-******************-sandbox:k8s-******************-sandbox-NODEGROUP20211207130759507400000005): InvalidParameterException: nodeGroupName can't be longer than 63 characters!
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "b24890f3-4db2-4c09-a964-7ab9b0db6521"
  },
  Message_: "nodeGroupName can't be longer than 63 characters!"
}

  on .terraform/modules/eks/modules/node_groups/main.tf line 1, in resource "aws_eks_node_group" "workers":
   1: resource "aws_eks_node_group" "workers" {

As can be seen from the error the Node groups are getting the clustername, node group name and adding a lot of random number(i think this is a date) in the following format ClusterName-nodeGroupName20211207130759507400000005

How can I fix/workaround this. If possible how can I remove the numbers behind the name?

## Versions

 - Terraform:
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.68.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction

 
 
1.  changing the eks module version from 13.2.1 to 17.24.0 exact row:
`source                                         = "git::https://github.com/terraform-aws-modules/terraform-aws-eks.git?ref=v17.24.0"`
2. apply changes

## Expected behavior
 
To be upgraded with the old NodeGroup names without adding stuff behind

## Actual behavior

Upgrading the nodegroups name and adding 28 symbols

### Terminal Output Screenshot(s)

`Error: error creating EKS Node Group (k8s-******************-sandbox:k8s-******************-sandbox-NODEGROUP20211207130759507400000005): InvalidParameterException: nodeGroupName can't be longer than 63 characters!
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "b24890f3-4db2-4c09-a964-7ab9b0db6521"
  },
  Message_: "nodeGroupName can't be longer than 63 characters!"
}

  on .terraform/modules/eks/modules/node_groups/main.tf line 1, in resource "aws_eks_node_group" "workers":
   1: resource "aws_eks_node_group" "workers" {`

**Comment by daroga0002** [comment]
you can workaround this by adding `name_prefix` to override node group name

**Comment by bryantbiggs** [comment]
closing due to solution provided above

**Comment by kevincantu** [comment]
FWIW I've seen this error while using name_prefix.  🤷‍♀️

**Comment by youwalther65** [comment]
Same for me, regardless what I specify in module "eks_managed_node_group" name is always used as a prefix and my node group name gets too long!
