### ISSUE TITLE
node_groups/launch_template.tf needs to be more flexible on the device_name within block_device_mappings section

### ISSUE THREAD

**Issue by kongdewen** [terraform-aws-modules/terraform-aws-eks#1714]
## Description
First, thank you so much to enable custom AMI image in the node_groups launch templates. But it also can cause a problem when custom AMI image root volume name isn't `/dev/xvda` as hardcoded in https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/node_groups/launch_template.tf#L41. it will cause consumers can't setup correct root devices block_device_mappings when we launch the EC2 instance. 

## Reproduction
To reproduce the issue, we can launch an custom AMI image with root device name differ than `/dev/xvda`

## Expected behavior
we should be able to setup the ami root device name based on the AMI image itself

## Actual behavior
the root device name is fixed to `/dev/xvda`

**Comment by bryantbiggs** [comment]
closed with #1680
