### ISSUE TITLE
Security Groups differ from aws recommendation

### ISSUE THREAD

**Issue by ryanli-me** [terraform-aws-modules/terraform-aws-eks#172]
# I have issues
Security Groups differ from aws recommendation
## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Currently, cluster sg opens outbound 0.0.0.0/0 for all port. 
Similarly, worker node sg opens inbound port from 0-65535 from worker node sg.

## What's the expected behavior?

Aws recommends cluster sg only opens inbound 1025-65535 port to worker node sg. 
Aws recommends worker sg only opens inbound 443 and 1025-65535 ports to worker node sg.
Here's the reference. https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html

## Are you able to fix this problem and submit a PR? Link here if you have already.
I could fix this and submit a PR.
## Environment details

* Affected module version:
* OS: 
* Terraform version:

**Comment by max-rocket-internet** [comment]
Hey @ryanli-me 

> Currently, cluster sg opens outbound 0.0.0.0/0 for all port.

Yes, this is for the EKS service itself. What else would you have here? Or even for the nodes, what else would you have here?

> Similarly, worker node sg opens inbound port from 0-65535 from worker node sg.

This is to itself. What else would you have here? Here's the AWS CFN: https://github.com/awslabs/amazon-eks-ami/blob/master/amazon-eks-nodegroup.yaml#L207-L216

> Aws recommends cluster sg only opens inbound 1025-65535 port to worker node sg.

Yes, from EKS service to nodes: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L85-L94

> Aws recommends worker sg only opens inbound 443

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L96-L105

**Comment by max-rocket-internet** [comment]
Maybe make a PR to make it clearer what you mean?

**Comment by wilkko** [comment]
Add additional_cluster_security_group_ids or similar so that EKS control plain outbound access can be limited to worker nodes? Or can EKS control plane/cluster be attached to a single security group?

**Comment by max-rocket-internet** [comment]
@wikko I am not 100% sure what you mean but I don't think it's related to this issue?

> EKS control plain outbound access can be limited to worker nodes

This is not desirable because your `kubectl` from your workstation needs to access the cluster endpoint also. As does anything else that needs access to k8s API, such as deployment tools (travis, CI etc), developers and any users who use `kubectl`.

Hope that helps 😎

**Comment by wilkko** [comment]
I was talking about control plane outbound access e.g. minimum and recommended outbound access for control plane is mentioned here:
https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html

How are those outbound rules relevant to kubectl?

**Comment by max-rocket-internet** [comment]
Ahh, yes, you are correct. My mistake, I was conflating the EKS cluster endpoint and the control plane. They are separate.

Again, feel free to make a PR for these changes.

**Comment by wilkko** [comment]
It's actually a mystery how I can connect to EKS  with kubectl when the cluster SG seems to limits inbound access to worker nodes (as recommended).

**Comment by max-rocket-internet** [comment]
Because the cluster endpoint that `kubectl` connects to is like any other AWS API, i.e. always publicly accessible

**Comment by max-rocket-internet** [comment]
I'm gonna close this now. Feel free to reopen if it's still an issue.
