### ISSUE TITLE
feat(docs): deployment decision tree

### ISSUE THREAD

**Issue by m00lecule** [terraform-aws-modules/terraform-aws-eks#1722]
Hello, I would like to request an additional documentation.

During my first deep dive with eks and IaC I was struggling to find out the most optimal way to meet my needs.

My considerations were:
- terraform vs eksctl
- managed vs self-managed nodes support
- custom AMI support

I have found sufficient strategy after few days of studying this module code and AWS documentation.

### I was wondering If we could enhance module documentation with deployment **decision tree**. I strongly believe that this pattern is occrruing often for newcomers and I would like to save their time.

**Comment by bryantbiggs** [comment]
hello @m00lecule  - while I agree that there are numerous decisions out there when it comes to the Kubernetes space in general, I don't think this is valuable for the module. A quick google search on any of these and you will see numerous articles and blog posts so I think its best to leave these types of opinions out of the documentation
