### ISSUE TITLE
set max pods in launch config

### ISSUE THREAD

**Issue by shaunc** [terraform-aws-modules/terraform-aws-eks#1730]
## Is your request related to a problem? Please describe.

I am trying to use the [helm chart for the aws cni](https://registry.terraform.io/modules/DNXLabs/eks-vpc-cni/aws/latest) to set `ENABLE_PREFIX_DELEGATION`, which changes the max pods per node.

## Describe the solution you'd like.

I would like a configuration to set the pods per node in a launch configuration template.

## Describe alternatives you've considered.

Somehow patch the launch configuration template afterwards?

**Comment by bryantbiggs** [comment]
closed with #1680

**Comment by shaunc** [comment]
Great -- thanks!
