### ISSUE TITLE
Unable to use conditional expression for launch template

### ISSUE THREAD

**Issue by abhishiekgowtham** [terraform-aws-modules/terraform-aws-eks#1731]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.
I'm unable to set multiple `worker_groups_launch_template` based on a conditional input variable. Something like 

`worker_groups_launch_template = var.utilize_spot_instances ? local.free_tier_workers_group : local.paid_tier_workers_group`

I've tried setting the `local.free_tier_workers_group` some objects to null or empty and it doesn't work and throws the following error: 

```
│ Error: Inconsistent conditional result types
│
│  257:   worker_groups_launch_template = var.utilize_spot_instances ? local.free_tier_workers_group : local.paid_tier_workers_group
│     ├────────────────
│     │ local.free_tier_workers_group is tuple with 4 elements
│     │ local.paid_tier_workers_group is tuple with 4 elements
│     │ var.utilize_spot_instances is a bool, known only after apply
│
│ The true and false result expressions must have consistent types. The given
│ expressions are tuple and tuple, respectively.

```
## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform: `0.13.7`

 - Provider(s): `terraform-aws-eks`

 - Module: `terraform-aws-modules/eks/aws - 16.2.0`

## Reproduction

- Use conditional expression for selecting/using `worker_groups_launch_template `
- Both variables can be of same length or set some objects to null

### Code Snippet to Reproduce

`worker_groups_launch_template = var.utilize_spot_instances ? local.free_tier_workers_group : local.paid_tier_workers_group`

## Expected behavior

- It should accept whatever worker launch templates is provided without checking in depth
- Is there a workaround for the issue?

## Actual behavior

- Keep getting `Inconsistent conditional result types` error

**Comment by bryantbiggs** [comment]
@abhishiekgowtham - closing this for now with the latest release of v18.x. Please let me know if your issue still persists after updating to the latest version
