### ISSUE TITLE
Precreated resources: IAM, VPC erroring

### ISSUE THREAD

**Issue by jauyzed** [terraform-aws-modules/terraform-aws-eks#1732]
## Is your request related to a new offering from AWS?
No, 

## Is your request related to a problem? Please describe.
This TF is great for creating all EKS related resources but in a place where IAM and VPC resources/services are strictly managed by someone for example a security team- this TF module may not work out of the box; might requires some modifications

## Describe the solution you'd like.
If VPC, IAM roles and profiles required to a EKS cluster provisioning is managed by a different team for example VPC, subnets, IAM roles, instance profiles, launch profiles, security groups, are pre-created- what modifications need to be done without breaking the modules?   

## Describe alternatives you've considered.
I tried to modify some of code but there are some dependencies on custom created resources(IAM, VPC etc) and removing or modifying them is actually breaking the main module. If there is a way to pass/reuse the precreated resources described above via variables.tf/locals.tf, that will be nice to have.

**Comment by bryantbiggs** [comment]
VPC resources are not involved in this module, those must exist prior to deploying the module. The module allows you to utilize the IAM resources it creates or provide your own

**Comment by jauyzed** [comment]
I'm trying to provision the an EKS cluster without creating IAM resources(using the complete example)

Passing these variables in the module EKS:

```
manage_cluster_iam_resources = false
manage_worker_iam_resources  = false
cluster_iam_role_name  = "existing-svc-role-eks-cluster"
workers_role_name       = "existing-svc-role-eks-worker"
```

```
$ terraform plan

[ERROR] vertex "data.aws_iam_role.custom_cluster_iam_role (expand)" error: error reading IAM Role (): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, GetRoleInput.RoleName.
╷
│ Error: error reading IAM Role (): InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, GetRoleInput.RoleName.
│
│
│   with data.aws_iam_role.custom_cluster_iam_role[0],
│   on data.tf line 66, in data "aws_iam_role" "custom_cluster_iam_role":
│   66: data "aws_iam_role" "custom_cluster_iam_role" {

```
