### ISSUE TITLE
Requesting to add few more example combinations

### ISSUE THREAD

**Issue by jauyzed** [terraform-aws-modules/terraform-aws-eks#1735]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
This is more of a usage example request than a feature request in this module. I've been reading and trying this module for few days now. I was using the existing examples as a reference point to create resources but running into errors. In a org where all IAM resources are already provisioned, this module may not work for the use case I'm testing. I'm requesting to add working example if EKS IAM roles, VPC, Subnets, SG's are provisioned. I was able to provision EKS cluster but running into issues while creating node_groups, self managed nodes with launch_templates and custom AMI.  I have set all variables that refer manage_IAM resources to false

Specific error: 
`Error: node_role_arn must not be empty, got
│
│   with module.eks.module.node_groups.aws_eks_node_group.workers["example"],
│   on ../../modules/node_groups/main.tf line 8, in resource "aws_eks_node_group" "workers":
│    8:   node_role_arn = each.value["iam_role_arn"]`

Initially I ran into this but setting instance_profile role somewhere in the child module condensed to the error above. 

`Error: Error getting instance profiles: InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, GetInstanceProfileInput.InstanceProfileName.
│
│
│   with module.eks.data.aws_iam_instance_profile.custom_worker_group_iam_instance_profile[0],
│   on ../../data.tf line 72, in data "aws_iam_instance_profile" "custom_worker_group_iam_instance_profile":
│   72: data "aws_iam_instance_profile" "custom_worker_group_iam_instance_profile" {`
│

`│ Error: Error getting instance profiles: InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, GetInstanceProfileInput.InstanceProfileName.
│
│
│   with module.eks.data.aws_iam_instance_profile.custom_worker_group_launch_template_iam_instance_profile[0],
│   on ../../data.tf line 82, in data "aws_iam_instance_profile" "custom_worker_group_launch_template_iam_instance_profile":
│   82: data "aws_iam_instance_profile" "custom_worker_group_launch_template_iam_instance_profile" {
│`

`│ Error: node_role_arn must not be empty, got
│
│   with module.eks.module.node_groups.aws_eks_node_group.workers["example"],
│   on ../../modules/node_groups/main.tf line 8, in resource "aws_eks_node_group" "workers":
│    8:   node_role_arn = each.value["iam_role_arn" `

## Describe the solution you'd like.
Not looking for resolution for the above described errors but few more example combinations would be great

## Describe alternatives you've considered.
Tried the examples in the module

**Comment by bryantbiggs** [comment]
@jauyzed - Closing this for now with the latest release of v18.x. Please let me know if your issue still persists after updating to the latest version and we can revisit
