### ISSUE TITLE
The disk_size does not changed.

### ISSUE THREAD

**Issue by shoji-kai** [terraform-aws-modules/terraform-aws-eks#1739]
## Description

The disk_size does not changed.

## Versions

 - Terraform: v1.1.2

 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

 - Module: 18.0.0

### Code Snippet to Reproduce

```
  eks_managed_node_group_defaults = {
    ami_type  = "AL2_x86_64"
    disk_size = 50
    instance_types = ["t3a.small", "t3.small", "t2.small"]
  }
```

## Expected behavior

Volume size is 50 GB.

## Actual behavior

Volums size is 20 GB. (default volume size)

### Terminal Output Screenshot(s)

```
% k get no ip-172-17-0-28.us-east-2.compute.internal -o=jsonpath='{.status.capacity}' | jq -r
{
  "attachable-volumes-aws-ebs": "25",
  "cpu": "2",
  "ephemeral-storage": "20959212Ki",
  "hugepages-1Gi": "0",
  "hugepages-2Mi": "0",
  "memory": "1994628Ki",
  "pods": "8"
}
```

**Comment by bryantbiggs** [comment]
@shoji-kai is this using a custom launch template or using the launch template provided by AWS EKS? `disk_size` is only valid when using the AWS EKS launch template, otherwise you should specify within the `block_device_mappings` - https://github.com/terraform-aws-modules/terraform-aws-eks/blob/d71ef01c37f777d28cbf6c6e8dbc161de073d6b1/modules/eks-managed-node-group/main.tf#L284

**Comment by shoji-kai** [comment]
@bryantbiggs 
Thank you for your reploy.
I'm using EKS managed nodegroup. 
So, I think that the launch template provided by AWS EKS is used.

**Comment by shoji-kai** [comment]
I have tested v17.24.0, and this version is works correctly.
So, I think this issue occurs only version v18.0.0.

**Comment by martijnvdp** [comment]
got the same thing looks like this statement in node_groups.tf is causing it always to set the launch template name to the key
`  launch_template_name            = try(each.value.launch_template_name, each.key)`

so if you add launch_template = "" to your node group it will work :-)
`  eks_managed_node_groups = {
    default = {

      disk_size            = local.eks1.node_root_disk_size
      launch_template_name = ""`

**Comment by bryantbiggs** [comment]
ah, I see now what you all are doing. let me add a bit of documentation for this

basically we made the decision to always create a launch template for EKS managed node groups because this solves a number of issues (tags, its always tags) and theres no penalty (or so we thought) for creating a template. however, because we are creating a template that looks like its forcing users to specify some of the EKS managed node group settings through the launch template rather than directly - as is the case with disk size

**Comment by bryantbiggs** [comment]
updates added - see https://github.com/terraform-aws-modules/terraform-aws-eks/blob/7babe877758ae0287975627a0135aa8b40c29e93/examples/eks_managed_node_group/main.tf#L72-L75 for complete example that has been validated

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.0.6 :tada:

**Comment by shoji-kai** [comment]
@martijnvdp 
Thank you very much! :)

**Comment by dignajar** [comment]
I have the same issue even with the version v18.0.6.

I'm trying to migrate from v17.x to v18.x and before I had this configuration and works fine, also setting up the disk type to gp3.

```
    create_launch_template: true
    disk_size: 32
    disk_type: "gp3"
```

I tried the following, but doesn't work, do I need to create my own launch template to change the disk size and disk type ?
```
    create_launch_template: true
    launch_template_name: ""
    disk_size: 32
    disk_type: "gp3"
```

**Comment by raylaijh** [comment]
experiencing the same as @dignajar as well. Currently using 18.2.0, user-data stanza doesn't take effect too. Works fine originally on v17.x

**Comment by baowei** [comment]
module comment “  disk_size            = local.use_custom_launch_template ? null : var.disk_size # if using LT, set disk size on LT or else it will error here”
but ,how to config for launch_template? thanks @antonbabenko

**Comment by baowei** [comment]
@dignajar @raylaijh 
According to the module file: [eks-managed-node-group/main.tf](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/eks-managed-node-group/main.tf)
```
1, "disk_size = local.use_custom_launch_template? Null: var.disk_size # if using LT, set disk size on LT or else it will error here"
2, "resource "aws_launch_template" "this" {
```

Refer to the configuration below

```
  eks_managed_node_groups = {
    nodeGroup-1A = {
      subnet_ids              = [element(jsondecode(data.vault_generic_secret.eks_vpc.data["private_subnet_ids"]), 0)]
      pre_bootstrap_user_data = <<-EOT
      echo "$(jq '."log-opts"."max-size" = "100m"' /etc/docker/daemon.json)" > /etc/docker/daemon.json
      EOT
      # ebs_optimized           = true
      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 200
            volume_type           = "gp3"
            iops                  = 3000
            throughput            = 125
            encrypted             = true
            delete_on_termination = true
          }
        }
      }
    }
   }
```

**Comment by mikstew** [comment]
Sorry to revive a long dead issue, but was there a way to get the configurable `disk_size` as well as the tag propagation? If I use the `create_launch_template = false` I lose tags and if I don't use it, the `disk_size` variable is ignored.
