### ISSUE TITLE
worker nodes ip's limit due to ENI limit

### ISSUE THREAD

**Issue by sagivle** [terraform-aws-modules/terraform-aws-eks#174]
# I have issues

there is a limit on the max ip's per ENI (30)
currently the workers has only one network interface (ENI)
how do we add more ENI to the workers?

## I'm submitting a...

* [x ] bug report
* [ ] feature request
* [x ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

30 ip's limit per worker

## Environment details

* Affected module version:
* OS:
* Terraform version:
0.11.8

**Comment by max-rocket-internet** [comment]
You just change the instance type in your worker group map.

**Comment by sagivle** [comment]
we are using m5.4xlarge it has 30 ip's per ENI
we have reached that limit so we need to add more ENI
how do i do that with EKS terraform module?
