### ISSUE TITLE
Managed node group bootstrap.sh not run with custom ami

### ISSUE THREAD

**Issue by jallen-frb** [terraform-aws-modules/terraform-aws-eks#1740]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:
Terraform v0.13.4
 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
 - Module:
18.0.0

## Reproduction

Converted to 18.0.0 from 17.24.0
I am following the instructions in the readme to use custom AMI that is EKS optimized. Whenever I apply my changes the bootstrap script does not seem to run and join the node to the cluster. I get the following terraform error:
```
Error: error waiting for EKS Node Group (<example>) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:
	* <instance-id>: NodeCreationFailure: Instances failed to join the kubernetes cluster
```

If I SSH/SSM into the node and look at the cloud-init log this is what I see:
```
Cloud-init v. 21.4-0ubuntu1~20.04.1 running 'modules:config' at Thu, 06 Jan 2022 07:31:29 +0000. Up 28.96 seconds.
Pre-Bootstrap Script Init
Aliasing EKS k8s snap commands
Added:
  - kubelet-eks.kubelet as kubelet
Added:
  - kubectl-eks.kubectl as kubectl
Stopping k8s daemons until configured
Stopped.
Cluster "kubernetes" set.
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Exited with error on line 483
Cloud-init v. 21.4-0ubuntu1~20.04.1 running 'modules:final' at Thu, 06 Jan 2022 07:31:34 +0000. Up 33.42 seconds.
2022-01-06 07:31:38,605 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2022-01-06 07:31:38,611 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
```

### Code Snippet to Reproduce
AMI Source:
```
data "aws_ami" "eks_ubuntu" {
  most_recent = true
  owners = ["099720109477"] # Canonical (Ubuntu)

  filter {
    name   = "name"
    values = ["ubuntu-eks/k8s_1.21/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"]
  }

  filter {
        name = "virtualization-type"
        values = ["hvm"]
  }
}
```
Node group:
```
  eks_managed_node_groups = {
    project1 = {
      name_prefix      = "project1"
      description      = "project1 managed node group launch template"

      # Auto scaling group capacity
      desired_capacity = 1
      max_capacity     = 1
      min_capacity     = 1

      # Instance image and bootstrap options
      ami_id                     = data.aws_ami.eks_ubuntu.id
      platform                   = "linux"
      enable_bootstrap_user_data = true
      bootstrap_extra_args       = ""
      instance_types             = ["c5n.large"]

      pre_bootstrap_user_data = <<-EOT
        echo "Pre-Bootstrap Script Init"
      EOT

      post_bootstrap_user_data = <<-EOT
        echo "Post-Bootstrap Script Init"
      EOT

      iam_role_additional_policies = [
        "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy",
        "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
        "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
      ]

      # Node group taints
      taints = [
        {
          key = "dedicated"
          value = "project1"
          effect = "NO_SCHEDULE"
        }
      ]

      tags = {
        launch_template = "project1"
      }
    }
```

## Expected behavior
The eks bootstrap script is run through the module

## Actual behavior
The boostrap script is not run, I believe

**Comment by stevehipwell** [comment]
@jallen-frb I haven't been able to go through all of the code changes introduced in `v18.0.0` but if the behaviour is consistent with `v17` then you either need to have the standard EKS bootstrap script in your AMI and set `eks_optimized = true` or you need to provide the whole user_data script.

**Comment by bryantbiggs** [comment]
just at first glance, a things you might check:
1. v18.x takes a minimalist approach in terms of security access - port 8080 is not open by default on the security groups created so if the ubuntu flavor of EKS AMI uses this port, you will need to add a rule to allow traffic on 8080 between the nodes and the control plane
2. With the use of the Ubuntu EKS AMI, does this flavor of AMI provided a bootstrap script at /etc/eks/bootstrap.sh? If so, you will need to opt into providing a bootstrap script by setting https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L132 or provide your own bootstrap script/userdata
3. I see you have a `NO_SCHEDULE` taint - are there other nodes in the cluster that will allow the utility pods to be provisioned (CoreDNS, etc.)? if this is the only node group in the cluster, the utility pods that are required won't be able to provision and lead to a failure to join

**Comment by jallen-frb** [comment]
> @jallen-frb I haven't been able to go through all of the code changes introduced in `v18.0.0` but if the behaviour is consistent with `v17` then you either need to have the standard EKS bootstrap script in your AMI and set `eks_optimized = true` or you need to provide the whole user_data script.

@stevehipwell 18 gets rid of `eks_optimized = true` and replaces it with:
```
      enable_bootstrap_user_data = true
      bootstrap_extra_args       = ""

      pre_bootstrap_user_data = <<-EOT
        echo "Pre-Bootstrap Script Init"
      EOT

      post_bootstrap_user_data = <<-EOT
        echo "Post-Bootstrap Script Init"
      EOT
```
I am following the instructions as per 5. from the new readme: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/README.md#node-group-configuration
<img width="926" alt="Screen Shot 2022-01-06 at 9 25 37 AM" src="https://user-images.githubusercontent.com/85565361/148397951-99611e51-b97b-4a0f-8de9-b145df1d3921.png">

**Comment by jallen-frb** [comment]
> just at first glance, a things you might check:
> 
> 1. v18.x takes a minimalist approach in terms of security access - port 8080 is not open by default on the security groups created so if the ubuntu flavor of EKS AMI uses this port, you will need to add a rule to allow traffic on 8080 between the nodes and the control plane
> 2. With the use of the Ubuntu EKS AMI, does this flavor of AMI provided a bootstrap script at /etc/eks/bootstrap.sh? If so, you will need to opt into providing a bootstrap script by setting https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L132 or provide your own bootstrap script/userdata
> 3. I see you have a `NO_SCHEDULE` taint - are there other nodes in the cluster that will allow the utility pods to be provisioned (CoreDNS, etc.)? if this is the only node group in the cluster, the utility pods that are required won't be able to provision and lead to a failure to join

@bryantbiggs

1. I will look into the sq and port stuff
2. My AMI (ubuntu 20.04 eks optimized image direct from Canonical) has the bootstrap script correctly at /etc/eks/bootstrap.sh
3. I am using this in main part of the module:
```
  # Cluster addons
  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }
```

**Comment by stevehipwell** [comment]
> @stevehipwell 18 gets rid of eks_optimized = true and replaces it with:

I just looked at the README and it was still present so sorry for that.

**Comment by jallen-frb** [comment]
> > @stevehipwell 18 gets rid of eks_optimized = true and replaces it with:
> 
> I just looked at the README and it was still present so sorry for that.

@stevehipwell I do not see it there for version 18.0.0. Where are you seeing that?

**Comment by stevehipwell** [comment]
@jallen-frb I miss read `ebs_optimized` as `eks_optimized`, apologies again. I still haven't fully worked through the changes made in v18.

**Comment by jallen-frb** [comment]
I just confirmed the bootstrap script is not running correctly. If I go on to the system and manually run the bootstrap script it connects to the cluster.

If I grab this output from the cloud-init logs and run it as root user it connects fine:
```
      ami_id                     = data.aws_ami.eks_ubuntu.id
      platform                   = "linux"
      enable_bootstrap_user_data = true
      bootstrap_extra_args       = ""

      pre_bootstrap_user_data = <<-EOT
        echo "Pre-Bootstrap Script Init"
        export cluster_name=${module.eks.cluster_id}
        echo $cluster_name
        export endpoint=${module.eks.cluster_endpoint}
        echo $endpoint
        export cluster_auth_base64=${module.eks.cluster_certificate_authority_data}
        echo $cluster_auth_base64
        echo "/etc/eks/bootstrap.sh --b64-cluster-ca $cluster_auth_base64 --apiserver-endpoint $endpoint $cluster_name"
      EOT
```

BUT if I try to run the script in there I still get the cannot connect to localhost:8080. Are the variables not getting passed correctly? I feel like I am crazy.
```
      ami_id                     = data.aws_ami.eks_ubuntu.id
      platform                   = "linux"
      enable_bootstrap_user_data = true
      bootstrap_extra_args       = ""

      pre_bootstrap_user_data = <<-EOT
        echo "Pre-Bootstrap Script Init"
        export cluster_name=${module.eks.cluster_id}
        echo $cluster_name
        export endpoint=${module.eks.cluster_endpoint}
        echo $endpoint
        export cluster_auth_base64=${module.eks.cluster_certificate_authority_data}
        echo $cluster_auth_base64
        echo "/etc/eks/bootstrap.sh --b64-cluster-ca $cluster_auth_base64 --apiserver-endpoint $endpoint $cluster_name"
        /etc/eks/bootstrap.sh --b64-cluster-ca $cluster_auth_base64 --apiserver-endpoint $endpoint $cluster_name
      EOT
```

**Comment by bryantbiggs** [comment]
you can view the rendered user data to see if the variables are populated correctly by going to a launched instance in the console and viewing the user data for it

**Comment by jallen-frb** [comment]
Yes the variables are populated correctly. I am starting to think it has to do with the bootstrap script or its permissions now.

**Comment by jallen-frb** [comment]
I just find it odd that version 17.24.0 was running the same AMI and everything worked using pre_userdata:
```
    project1 = {
      name_prefix      = "project1"

      instance_types = ["c5n.large"]

      desired_capacity = 1
      max_capacity     = 1
      min_capacity     = 1

      create_launch_template = true
      ami_id                 = data.aws_ami.eks_ubuntu.id
      ami_is_eks_optimized   = true
      capacity_type          = "ON_DEMAND"

      # bootstrap_env = {
      # }

      taints = [
        {
          key = "dedicated"
          value = "project1"
          effect = "NO_SCHEDULE"
        }
      ]

      additional_tags = {
        launch_template = "project1"
      }

      pre_userdata = <<-EOT
        #!/bin/sh
        # enable htcp congestion control algo
        modprobe tcp_htcp
        # allow testing with buffers up to 128MB
        sysctl -w net.core.rmem_max=134217728
        sysctl -w net.core.wmem_max=134217728
        # increase Linux autotuning TCP buffer limit to 64MB
        sysctl -w net.ipv4.tcp_rmem="4096 87380 67108864"
        sysctl -w net.ipv4.tcp_wmem="4096 65536 67108864"
        # increase the length of the processor input queue
        sysctl -w net.core.netdev_max_backlog=250000
        # recommended default congestion control is htcp
        sysctl -w net.ipv4.tcp_congestion_control=htcp
        # recommended for hosts with jumbo frames enabled
        sysctl -w net.ipv4.tcp_mtu_probing=1
      EOT
    }
```

**Comment by jallen-frb** [comment]
I figured it out. Ubuntu pushed a new AMI yesterday that had some changes that breaks the bootstrap. Not sure how quite yet, but I can confirm it is their EKS 1.21 optimized image that was pushed on January 5, 2021.

**Comment by jallen-frb** [comment]
https://bugs.launchpad.net/cloud-images/+bug/1956620
