### ISSUE TITLE
Improved CHANGELOG for v18.0.0

### ISSUE THREAD

**Issue by stevehipwell** [terraform-aws-modules/terraform-aws-eks#1741]
## Is your request related to a new offering from AWS?

No

## Is your request related to a problem? Please describe.

The CHANGELOG for `v18.0.0` doesn't seem to cover all of the changes introduced in the new version and the commit comments are misleading.

## Describe the solution you'd like.

I think this information is available in the PR (https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1680) and [UPGRADE-18.0.md](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/UPGRADE-18.0.md). I'd like the release notes to reference the upgrade document and it be made clear that the main commit/PR contains far more than just replacing count with for. Ideally the release would directly contain the list of changes from the PR so there is no need to visit the PR directly.

## Describe alternatives you've considered.

N/A

## Additional context

N/A

**Comment by stevehipwell** [comment]
FYI @antonbabenko. PS great work on upgrading the module, I have a lot of reading to do to get back up to speed with the new design.

**Comment by antonbabenko** [comment]
You are right, there is still some improvement to be done to polish the release flow.

In particular, I have to do an extra step and remember to put the information which will be in release notes in the merge commit description.

Talking about v18.0.0 release, I have just edited the release notes and included more information - https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v18.0.0

Thank you for opening this issue and your contributions!

**Comment by stevehipwell** [comment]
@antonbabenko if you want to use the CHANGELOG.md as a source of truth I can open a PR to automate the population of the release description with the information from there? That way the release logic just needs a checkpoint step to say that the CHANGELOG needs to be populated and expanded before a release is cut.

**Comment by antonbabenko** [comment]
We use semantic-release projects for this already. The challenge here is on the human side - I need to remember to put the correct information in the correct place at the correct time.

I think we are good with this now. Just need more practicing :)
