### ISSUE TITLE
additional outputs to facilitate managing aws-auth configmap

### ISSUE THREAD

**Issue by joncolby** [terraform-aws-modules/terraform-aws-eks#1742]
## Describe the solution you'd like.

With module 18.0.x ,  the `aws_auth_configmap_yaml` is output as a string.   However this makes it difficult for users who wish to manage the configmap using the kubernetes provider `kubernetes_config_map_v1`.   Workarounds are needed in order to extract the data part, combine with custom role mappings, and re-encode to pass to the `kubernetes_config_map_v1` resource.

I think it would be useful to provide the raw lists of the various roles, which will allow easier creation of the mapRoles using object-type data structures.

for example:

```hcl
output "eks_managed_role_arns" {
  value = [for group in module.eks_managed_node_group : group.iam_role_arn]
}
```
I could gladly submit a PR fairly quickly if there is agreement that this would be useful.

## Why not use `kubectl` solution as in examples?

We like many users run terraform from pipelines.   requiring the `kubectl` utility and the kubeconfig is not always possible or desirable.  Furthermore, some users may prefer to not rely on external commands for whatever reason.

## This feature request refers to this output

```hcl
output "aws_auth_configmap_yaml" {
  description = "Formatted yaml output for base aws-auth configmap containing roles used in cluster node groups/fargate profiles"
  value = templatefile("${path.module}/templates/aws_auth_cm.tpl",
    {
      eks_managed_role_arns        = [for group in module.eks_managed_node_group : group.iam_role_arn]
      self_managed_role_arns       = [for group in module.self_managed_node_group : group.iam_role_arn if group.platform != "windows"]
      win32_self_managed_role_arns = [for group in module.self_managed_node_group : group.iam_role_arn if group.platform == "windows"]
      fargate_profile_arns         = [for group in module.fargate_profile : group.fargate_profile_arn]
    }
  )   
```

**Comment by bryantbiggs** [comment]
I think this is already possible given the outputs `fargate_profiles`, `eks_managed_node_groups`, and `self_managed_node_groups`, no? users can create their own list or map comprehensions with these outputs to generate any necessary maps/lists as desired

**Comment by joncolby** [comment]
@bryantbiggs  -   you are right!   i didnt catch that the node groups are output as objects and we can pick the roles from them.

closing this request.   

excellent work on this refactor.  module is much cleaner now.

**Comment by canidam** [comment]
@joncolby mind sharing how you handle `aws-auth` configmap now? It is created automatically by EKS, then handling it with terraform is impossible without importing it first.

**Comment by bryantbiggs** [comment]
@canidam check out the aws_auth_configmap_yaml output - this should cover all IAM roles created by this module and you can add/append to it if you have additional/external roles

**Comment by canidam** [comment]
@bryantbiggs how can I append to it without using `kubectl` ? Is it possible to append an existing config map with Terraform? That's exactly what I need

**Comment by bryantbiggs** [comment]
Just simple terraform string formatting

**Comment by canidam** [comment]
@bryantbiggs but when I try to add `resource "kubernetes_config_map_v1" "aws-auth" { .. }` I get an error that it already exists. So how can I manage it with Terraform?

**Comment by bryantbiggs** [comment]
This is an exercise left up to users. When using the EKS managed node groups, that service automatically creates the aws-auth configmap which can cause conflicts. You can check out the examples for one way of how this was handled (via kubectl patch)

**Comment by canidam** [comment]
@bryantbiggs that's exactly what I asked @joncolby :) I'm trying not to use kubectl patch, as it feels more error-prone and brings kubectl as dependency. Can you provide with an idea how to do that? Since this is a new change there are no resources for that

**Comment by bryantbiggs** [comment]
This is one of the major points of v18 - keeping this module focused on provisioning AWS infrastructure resources and leaving cluster configuration out of the module (other than what is exposed/provided via the EKS managed node group service). You mentioned importing and appending and I was merely just pointing out that a bare bones, formatted configmap is provided by the module to hopefully aid users in this transition from managed by the module to externally managed (however users see fit)

**Comment by canidam** [comment]
I understand the intention of this change, but as I see it it's a little complicated as EKS (the service) couples this. When creating EKS, this is created for you, and makes it impossible for managing this in one-shot.
In the previous version, I had everything configured and after the module finish successfully the cluster was ready for use.

Now I'm looking to achieve this outcome. Running the module, then running import, then running the module again to manage aws-auth is cumbersome. Do you have any idea / suggestion to make this smooth as it was previously?

Thanks!

**Comment by bryantbiggs** [comment]
Have you not looked at the examples?!

**Comment by canidam** [comment]
I looked - the only one available is using `kubectl patch` .. am I missing something?

**Comment by bryantbiggs** [comment]
> Do you have any idea / suggestion to make this smooth as it was previously?

thats my suggestion - `kubectl patch` since thats what that API call is designed for. If you want it natively in Terraform, I suggest you go voice your +1 here https://github.com/hashicorp/terraform-provider-kubernetes/issues/723

**Comment by vkruoso** [comment]
I would suggest a doc improvement to make this more clear to the user their options, as this will mostly make the upgrade  painful to figure out how to do this. The `kubectl` solution works, but it adds the external dependency that most do not want to manage (running on terraform runners on the cloud / or controlling its installation and version), so it would be great to have extra example with other approaches to manage that configmap.

**Comment by bryantbiggs** [comment]
> I would suggest a doc improvement to make this more clear to the user their options, as this will mostly make the upgrade  painful to figure out how to do this. The `kubectl` solution works, but it adds the external dependency that most do not want to manage (running on terraform runners on the cloud / or controlling its installation and version), so it would be great to have extra example with other approaches to manage that configmap.

And PRs are welcomed
