### ISSUE TITLE
Support creating IPv6 EKS clusters 

### ISSUE THREAD

**Issue by stevehipwell** [terraform-aws-modules/terraform-aws-eks#1746]
## Is your request related to a new offering from AWS?

Yes. I doubt it's in the provider as the CLI arguments aren't even documented yet. But we should have an issue to track this.

## Is your request related to a problem? Please describe.

I'd like to be able to create IPv6 enabled clusters as described in the [AWS news announcement](https://aws.amazon.com/blogs/aws/amazon-elastic-kubernetes-service-adds-ipv6-networking/).

## Describe the solution you'd like.

I'd like this option supported as soon as the provider exposes it.

## Describe alternatives you've considered.

N/A

## Additional context

N/A

**Comment by bryantbiggs** [comment]
upstream issue for tracking https://github.com/hashicorp/terraform-provider-aws/issues/22407

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.1.0 :tada:
