### ISSUE TITLE
Cannot create Ingress resources after upgrading to 18 release

### ISSUE THREAD

**Issue by ITD27M01** [terraform-aws-modules/terraform-aws-eks#1748]
## Description

After upgrading to the 18 release the fresh cluster shows error during Ingress resource creation:

```
Error from server (InternalError): error when creating "keycloak": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-ingress-nginx-controller-admission.kube-system.svc:443/networking/v1/ingresses?timeout=10s": dial tcp 10.1.103.106:8443: i/o timeout
```

## Versions

 - Terraform: v1.1.2

 - Provider(s): aws v3.70.0

 - Module: 18.0.2

## Reproduction

Create new cluster, install ingress-nginx, try to create Ingress resource

### Code Snippet to Reproduce

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"

  version = "18.0.2"

  cluster_version = var.cluster_version
  cluster_name    = var.cluster_name
  vpc_id          = var.vpc_id
  subnet_ids      = var.subnets

  enable_irsa = true

  cluster_endpoint_private_access = var.cluster_endpoint_private_access
  cluster_endpoint_public_access  = var.cluster_endpoint_public_access

  eks_managed_node_group_defaults = var.node_groups_defaults
  eks_managed_node_groups         = var.node_groups

  tags         = var.tags
  cluster_tags = var.cluster_tags
}
```

## Actual behavior

Prior version 17 works well. But in 18 something happens with security groups.

**Comment by bryantbiggs** [comment]
hi @ITD27M01 - yes, with v18.x the security groups are very minimal in terms of rule access. based on your snippet, looks like you will need to add an egress rule for 8443

**Comment by ITD27M01** [comment]
@bryantbiggs Thanks for your reply.

As I see now, pods cannot communicate to each other on different nodes. Could you point me out which SG I need to fix to allow such communication?

**Comment by bryantbiggs** [comment]
if its node to node, you can add additional rules via `node_security_group_additional_rules`, and there is a similar variable for the cluster `cluster_security_group_additional_rules` if its control plan access thats desired (ref https://github.com/terraform-aws-modules/terraform-aws-eks/blob/3c6686379de9489d4c044cd13a63e2329e2ae4e1/examples/eks_managed_node_group/main.tf#L47) 

Check out https://github.com/terraform-aws-modules/terraform-aws-eks#security-groups if you haven't already

**Comment by ITD27M01** [comment]
@bryantbiggs Thanks,

For a complete understanding could you explain which SG is responsible for pod to pod communication between nodes, is it "cluster security group" ?

**Comment by bryantbiggs** [comment]
It is `node_security_group_xxx` defined here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/3c6686379de9489d4c044cd13a63e2329e2ae4e1/node_groups.tf#L10



This security group is attached to each node group created to allow node-to-node comms. In the image below, it is the box titled "Cluster node security group":

![security_groups](https://raw.githubusercontent.com/terraform-aws-modules/terraform-aws-eks/master/.github/images/security_groups.svg)

**Comment by ITD27M01** [comment]
@bryantbiggs I see, thank you.

I want to allow ingress and egress communication for node_security_group with itself. Is there any way to do the trick? Or I have to specify each used nodes subnet cidr in such rules?

**Comment by bryantbiggs** [comment]
you should be able to do something similar to what is provided for CoreDNS https://github.com/terraform-aws-modules/terraform-aws-eks/blob/3c6686379de9489d4c044cd13a63e2329e2ae4e1/node_groups.tf#L46

so you can add a rule block like:
```hcl
	ingress_self_nginx = {
      description = "Node to node Nginx"
      protocol    = "tcp"
      from_port   = 8443
      to_port     = 8443
      type        = "ingress"
      self        = true
    }
    egress_self_nginx = {
      description = "Node to node Nginx"
      protocol    = "tcp"
      from_port   = 8443
      to_port     = 8443
      type        = "egress"
      self        = true
    }
```

**Comment by ITD27M01** [comment]
I've defined appropriate rules in both `cluster_security_group_additional_rules` and `node_security_group_additional_rules` because calling webhook requires API to pods communications.

@bryantbiggs Thank you for explanations.

**Comment by alekc** [comment]
I feel like this should really be explained in much more detail on the Upgrade to v18 guide, and possibly add an example of a configuration which would allow inter pods communication like it was usually happening with EKS. 
I've literally spent last 6 hours trying to hunt down a bug in argocd not realizing that there is an issue linked to interpod communication due to security groups :(

**Comment by ITD27M01** [comment]
I've tested and cluster autoscaler works well without sg modification.

**Comment by clayrisser** [comment]
Loosen the security group rules to allow the cluster to communicate with the nodes.

```hcl
    ingress_cluster_all = {
      description                   = "Cluster to node all ports/protocols"
      protocol                      = "-1"
      from_port                     = 0
      to_port                       = 0
      type                          = "ingress"
      source_cluster_security_group = true
    }
```

Below is a loose (but still secure from the outside) configuration of security groups that enables full communication between my cluster and nodes, and that allows full access to the internet.

```hcl
  cluster_security_group_additional_rules = {
    egress_nodes_ephemeral_ports_tcp = {
      description                = "To node 1025-65535"
      protocol                   = "tcp"
      from_port                  = 1025
      to_port                    = 65535
      type                       = "egress"
      source_node_security_group = true
    }
  }
  node_security_group_additional_rules = {
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    ingress_cluster_all = {
      description                   = "Cluster to node all ports/protocols"
      protocol                      = "-1"
      from_port                     = 0
      to_port                       = 0
      type                          = "ingress"
      source_cluster_security_group = true
    }
    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
  }
```

**Comment by loukandr** [comment]
I was receiving this error when deploying the application:

Error from server (InternalError): error when creating "application.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.kube-system.svc:443/networking/v1/ingresses?timeout=10s": dial tcp 10.0.1.217:8443: i/o timeout_

This is how I was able to fix it. The eks module needed the following additional security group rule settings:
```
node_security_group_additional_rules = {
    ingress_admission_webhook_controller = {
      description                   = "AWS NLB Admission Webhook Controller"
      protocol                      = "tcp"
      from_port                     = 8443
      to_port                       = 8443
      type                          = "ingress"
      source_cluster_security_group = true
    }
  }
```

**Comment by jwestfio** [comment]
@clayrisser Nice call on the `ingress_cluster_all` additional rules.  Documentation should surely include this, as without it, validating/mutating webhooks do not function on EKS.

**Comment by benbonnet** [comment]
once using any of the `node_security_group_additional_rules` or `node_security_group_additional_rules` described in the docs; terraform complains about the following :

```
Warning: Argument is deprecated
with module.vpc.aws_vpc.this
on .terraform/modules/vpc/main.tf line 28, in resource "aws_vpc" "this":
  enable_classiclink_dns_support   = var.enable_classiclink_dns_support
With the retirement of EC2-Classic the enable_classiclink_dns_support attribute has been deprecated and will be removed in a future version.
``` 
and

```
Warning: Argument is deprecated
with module.vpc.aws_vpc.this
on .terraform/modules/vpc/main.tf line 27, in resource "aws_vpc" "this":
  enable_classiclink               = var.enable_classiclink
With the retirement of EC2-Classic the enable_classiclink attribute has been deprecated and will be removed in a future version.
```

Wondering if, some month later, the described config is still releevenant.

Thanks alot for any feedbacks
