### ISSUE TITLE
Release 18: IMDSv2 is required by default in launch template

### ISSUE THREAD

**Issue by psact** [terraform-aws-modules/terraform-aws-eks#1749]
## Is your request related to a new offering from AWS?

No
## Is your request related to a problem? Please describe.

By default the launch template created for managed node groups sets the following defaults:
``` {
  "http_endpoint": "enabled",
  "http_put_response_hop_limit": 2,
  "http_tokens": "required"
}
```
This is a change in behavior from the 17.x release, and things like `kube2iam` are broken with this as the default.
https://github.com/jtblin/kube2iam/pull/325

## Describe the solution you'd like.

Change the default to the more permissive `"http_tokens": "optional"` or mention this in the upgrade guide.

**Comment by bryantbiggs** [comment]
apologies for the confusion - it is mentioned but because its a nested attribute, its somewhat hidden under `metadata_options` as a new added variable.

this change was introduced as requested by the community for more strict security default requirements https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1579 but users still have the ability to relax those restrictions

**Comment by psact** [comment]
Sounds good, for anyone arriving via a search, this snippet should re-enable IMDSv1 for your cluster:
```
eks_managed_node_group_defaults = {
  metadata_options = {
    http_tokens = "optional",
  }
}
```

**Comment by james-callahan** [comment]
> Sounds good, for anyone arriving via a search, this snippet should re-enable IMDSv1 for your cluster:
> 
> ```
> eks_managed_node_group_defaults = {
>   metadata_options = {
>     http_tokens = "optional",
>   }
> }
> ```

FYI this works if you've already applied the node group, but if you haven't you will get this error:
```
Error: InvalidParameterValue: A value of ‘’ is not valid for http-endpoint. Valid values are ‘enabled’ or ‘disabled’.
│ 	status code: 400
```

The full fix is to add the whole:
```
    metadata_options = {
      http_endpoint               = "enabled"
      http_tokens                 = "optional"
      http_put_response_hop_limit = 2
    }
```
