### ISSUE TITLE
set  associate_public_ip_address = false and nodes can not register to the cluster master

### ISSUE THREAD

**Issue by vw1234** [terraform-aws-modules/terraform-aws-eks#175]
# I have issues

## I'm submitting a...

* [X ] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
in the resource aws_launch_configuration, I removed the associate_public_ip_address = true line and rerun the steps, then  
``` 
kubectl  --kubeconfig=kubeconfig get nodes
No resources found.
```
added the line back and went through all the steps,  then 
```
kubectl  --kubeconfig=kubeconfig get nodes --watch
NAME                                       STATUS   ROLES    AGE   VERSION
ip-10-10-5-79.us-west-2.compute.internal   Ready    <none>   42s   v1.10.3
```
## If this is a bug, how to reproduce? Please include a code sample if relevvant.

```
resource "aws_launch_configuration" "k8ht" {
  associate_public_ip_address = true
  iam_instance_profile        = "${aws_iam_instance_profile.k8ht-node.name}"
  image_id                    = "${data.aws_ami.eks-worker.id}"
  instance_type               = "${var.ec2-type}"
  name_prefix                 = "terraform-eks-k8ht"
  security_groups             = ["${aws_security_group.k8ht-node.id}"]
  user_data_base64            = "${base64encode(local.k8ht-node-userdata)}"

  lifecycle {
    create_before_destroy = true
  }
}
```

## What's the expected behavior?

This line is the only difference in the package. it should not matter 

## Environment details

* Affected module version:
* OS:  macOS 10.13.6
* Terraform version:

Terraform v0.11.8
   provider.aws v1.37.0
   provider.http v1.0.1

**Comment by max-rocket-internet** [comment]
Hey @vw1234 
I'm not sure you are using this TF module? That code you show is not from this module. So I assume you are following something like what is [here](https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html)?

Anyway, to answer your question:

The EKS service endpoint is something like `https://XXXXXXXXX.yl4.us-east-1.eks.amazonaws.com`. If your cluster worker nodes cannot reach this endpoint then they cannot join or participate in the cluster. If you set `associate_public_ip_address` to false and your instances are in the public subnet, then they will not be able to reach the internet and will not be able to join the cluster as they cannot reach the cluster endpoint.

Make sense?

**Comment by kaduev13** [comment]
@max-rocket-internet faced the same problem, your answer is really helpful 👍 The only question is – is it possible to access the master node (`https://XXXXXXXXX.yl4.us-east-1.eks.amazonaws.com` is a master node address, right?) using VPC network (without reaching the internet)? It sounds a little bit odd that the master node is located outside of VPC, IMHO.

**Comment by max-rocket-internet** [comment]
> It sounds a little bit odd that the master node is located outside of VPC

Perhaps but you have to realise that the "master node" is the EKS service, i.e. an service from AWS. All the AWS services are public.

But to answer your question, no it's not possible yet. It will be when AWS add a VPC endpoint for the EKS service. This exists for other services for this very problem. Some info here: 
 https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html

🙂

**Comment by dpiddockcmp** [comment]
EKS is a bit muddier than that.

They spin up three EC2 instances and a load balancer in their account. There are two ENI created in your VPC with the master security group attached. It's almost like the nodes should be able to communicate via those interfaces but the VPC DNS magic is missing. Or is it only the initial node registration that happens via the public service?

Like how RDS creates an ENI in your VPC. Then the VPC has DNS entries added for the RDS endpoint that resolve to the ENI. External services resolve the endpoint to a public IP, if the RDS is public.

**Comment by max-rocket-internet** [comment]
The EKS service needs to contact the kubelet on each worker. That's what the EKS VPC ENIs are for.

> Like how RDS creates an ENI in your VPC. Then the VPC has DNS entries added for the RDS endpoint that resolve to the ENI

Correct but a classic RDS instance does not require connectivity externally to function. Remember `kubectl` is also calling the EKS master endpoint, therefore it would be quite strange to not have it public.

**Comment by max-rocket-internet** [comment]
I'm gonna close this but feel free to reopen if you still have an issue.
