### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by im2nguyen** [terraform-aws-modules/terraform-aws-eks#1750]
## Description

Hello! I'm experiencing an issue when upgrading from `17.x` to `18.0.4`.

When I apply the [configuration](https://github.com/hashicorp/learn-terraform-provision-eks-cluster/tree/update-eks-module-18.0.4) ([`eks-cluster.tf`](https://github.com/hashicorp/learn-terraform-provision-eks-cluster/blob/update-eks-module-18.0.4/eks-cluster.tf)), Terraform returns with the following error.

```
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.eks.module.self_managed_node_group["worker-group-2"].aws_autoscaling_group.this[0] to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags: length changed from 5 to 6.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.eks.module.self_managed_node_group["worker-group-1"].aws_autoscaling_group.this[0] to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags: length changed from 5 to 6.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

Is there something I'm doing wrong? Can you point me in the right way? Thank you!

Tangentially, it was difficult to figure out what object the `self_managed_node_groups` attribute expects without navigating through all the examples. Is it possible to add an example to the [Inputs](https://github.com/terraform-aws-modules/terraform-aws-eks#input_self_managed_node_groups) section of the readme?

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform: v1.1.2

 - Provider(s):
 
    ``` 
    Terraform v1.1.2
    on darwin_amd64
    + provider registry.terraform.io/hashicorp/aws v3.71.0
    + provider registry.terraform.io/hashicorp/cloudinit v2.2.0
    + provider registry.terraform.io/hashicorp/kubernetes v2.7.1
    + provider registry.terraform.io/hashicorp/local v2.1.0
    + provider registry.terraform.io/hashicorp/null v3.1.0
    + provider registry.terraform.io/hashicorp/random v3.1.0
    + provider registry.terraform.io/hashicorp/tls v3.1.0
    ```
    

 - Module: 18.0.2

## Reproduction

No workspaces. Cleared local cache.

### Code Snippet to Reproduce

- [Complete configuration](https://github.com/hashicorp/learn-terraform-provision-eks-cluster/tree/update-eks-module-18.0.4)
- EKS module configuration ([`eks-cluster.tf`](https://github.com/hashicorp/learn-terraform-provision-eks-cluster/blob/update-eks-module-18.0.4/eks-cluster.tf))

## Expected behavior

Terraform applies successfully.

## Actual behavior

Terraform returns error.

```
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.eks.module.self_managed_node_group["worker-group-2"].aws_autoscaling_group.this[0] to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags: length changed from 5 to 6.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.eks.module.self_managed_node_group["worker-group-1"].aws_autoscaling_group.this[0] to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags: length changed from 5 to 6.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

**Comment by bryantbiggs** [comment]
1. Do you have a repro of your configuration 
2. The inputs for self managed node groups (as well as EKS managed node groups and fargate profiles) are fully documented - you can check either:
- The sub-module and its variables https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/self-managed-node-group/variables.tf
- The sub-module instantiation within the root module https://github.com/terraform-aws-modules/terraform-aws-eks/blob/b2e901c4e1ca5438959b98e9480ebe3801cd1917/node_groups.tf#L281

**Comment by im2nguyen** [comment]
Hi @bryantbiggs, yep. I listed the configuration in the original issue.

- [Complete configuration](https://github.com/hashicorp/learn-terraform-provision-eks-cluster/tree/update-eks-module-18.0.4)
- EKS module configuration ([`eks-cluster.tf`](https://github.com/hashicorp/learn-terraform-provision-eks-cluster/blob/update-eks-module-18.0.4/eks-cluster.tf))

**Comment by bryantbiggs** [comment]
my apologies @im2nguyen - I overlooked that on the first pass

It looks like you are suffering from https://github.com/hashicorp/terraform/issues/4149 - to get around this, your referenced security groups will need to be created before they can be referenced

**Comment by im2nguyen** [comment]
Hrm... I wonder why the implicit dependencies doesn't work here 🤔

**Comment by bryantbiggs** [comment]
closing this for now @im2nguyen since its a Terraform core issue
