### ISSUE TITLE
Some tags are not persisted in state although applied to resources

### ISSUE THREAD

**Issue by canidam** [terraform-aws-modules/terraform-aws-eks#1756]
## Description

I'm using few tags when creating EKS resources. All of them applied, but when running apply again I see 13 changes, with modification to the `tags` attribute - adding a single tag out of the configured 3.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

**_Done. Issue still persist. I tried to destroy and re-create the cluster few times. Same issue._**

## Versions
 - Terraform:
 ```
Terraform v1.1.3 on darwin_amd64
```
 - Provider(s):
```
+ provider registry.terraform.io/hashicorp/aws v3.71.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

```
 - Module: `terraform-aws-modules/eks/aws @ 18.0.5`

## Reproduction

Define tags as follows
```
locals {
  tags = {
    Managed-by                      = "Terraform"
    Environment                     = "my-env"
    Cloudwatch_to_s3_lambda_enabled = "true"
  }
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.0.5"

  cluster_name                         = var.cluster_name
  cluster_version                      = var.cluster_version
..
..

  tags = local.tags
}
```

Run apply, let terraform create the resources.
Once its done, run apply again. Notice the planned changes. All of them are the same, adding the tag to multiple resources.

```
..
      ~ tags                   = {
          + "Cloudwatch_to_s3_lambda_enabled" = "true"
            # (3 unchanged elements hidden)
        }

Plan: 0 to add, 13 to change, 0 to destroy.
```

I checked multiple resources, the tag is actually applied. Terraform state just isn't aware of it.

Not using workspaces.

I've tried to clear the cache, reinstall modules, recreate EKS cluster.

### Code Snippet to Reproduce

See above. Rest of the code is similar to the examples.

## Expected behavior

Tag be applied and kept in state. Further plan/apply executions shouldn't present this change.

## Actual behavior

Tag is applied, but every plan/apply presents this as a change.

## Additional context

This worked properly with eks module `v17.20`

**Comment by canidam** [comment]
Changing the tag to `CloudwatchToS3LambdaEnabled     = "true"` seems to solve the issue.

**Comment by bryantbiggs** [comment]
unfortunately without a full reproduction, this doesn't tell us anything. please see the examples section as these examples have tags and work as intended
