### ISSUE TITLE
auto-scaling mertics option

### ISSUE THREAD

**Issue by Staggerlee011** [terraform-aws-modules/terraform-aws-eks#1761]
Hi, 

when deploying a eks auto scaling group, i dont see an option to enable the auto scaling group metrics. and once created going to ec2 > auto scaling group > monitoring it will always show metrics as not enabled. 

Is it possible to add?

**Comment by bryantbiggs** [comment]
Are you referring to EKS managed node groups or self managed node groups?

**Comment by Staggerlee011** [comment]
Hi sorry, for the managed node groups.

**Comment by bryantbiggs** [comment]
EKS managed or self managed?

**Comment by Staggerlee011** [comment]
Thanks bryan.
