### ISSUE TITLE
user-data with eks-managed-nodes seems off after upgrade to v18.x

### ISSUE THREAD

**Issue by nickvanwegen** [terraform-aws-modules/terraform-aws-eks#1763]
## Description

After updated to module version 18.x I cant get user-data to work properly with eks-managed-nodes. 

In module version 17.x I used eks-managed-nodes with build in module features for user-data. for example(see code below). 
With this config managed nodes worked fine. But now since module v18.x when I try to use the new configuration. (see below)
I either get the error that the mime templating is not correct. Or the node just ignore the whole user-data config i give to them via the module. 

Also in the v18.x module. I see that in the launch-template the userdata seems to get mixed up.
In the EKS default userdata its adds the taints and extra labels for managed nodes. But then when i look in the LT created by the module userdata those are gone. 
Aswell as in the LT created by the module is no mime templating. (see outputs below) 

Another notice is that the ASG created by eks-managed-node-group points to the eks defaul created LT and not the one created by the module. 

Am I doing something wrong or is this a bug? 

## Versions

 - Terraform: v1.1.3

 - Provider(s):
 provider registry.terraform.io/hashicorp/aws v3.65.0

 - Module: 18.0.5

### Code Snippet to Reproduce

module V17.x config
````terraform
    bootstrap_env = {
      CONTAINER_RUNTIME = "containerd"
      USE_MAX_PODS      = false
    }

kubelet_extra_args = ["--max-pods=24"]`

terraform
    taints = [
      {
        key    = "node.cilium.io/agent-not-ready"
        value  = "true"
        effect = "NO_SCHEDULE"
      }
    ]

create_launch_template                 = true

````

module v18.x config
```
create_launch_template                 = true
    #bootstrap configuration
    enable_bootstrap_user_data = true
    bootstrap_extra_args       = "--kubelet-extra-args '--max-pods=24'"

    pre_bootstrap_user_data = <<-EOT
        export CONTAINER_RUNTIME="containerd"
        export USE_MAX_PODS=false
    EOT

    taints = [
      {
        key    = "node.cilium.io/agent-not-ready"
        value  = "true"
        effect = "NO_SCHEDULE"
      }
    ]

```

EKS default LT userdata
```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: text/x-shellscript; charset="us-ascii"
#!/bin/bash
set -ex
B64_CLUSTER_CA=hidden
API_SERVER_URL=hidden
K8S_CLUSTER_DNS_IP=172.20.0.10
/etc/eks/bootstrap.sh clustername --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup-image=ami-02b3f04ab50ffd9f1,eks.amazonaws.com/capacityType=SPOT,eks.amazonaws.com/nodegroup=default-2-2022011108144902890000001e --register-with-taints=node.cilium.io/agent-not-ready=true:NoSchedule' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL --dns-cluster-ip $K8S_CLUSTER_DNS_IP

--//--
```
Module created LT userdata
```
#!/bin/bash
set -e
export CONTAINER_RUNTIME="containerd"
export USE_MAX_PODS=false
B64_CLUSTER_CA=hidden
API_SERVER_URL=hidden
/etc/eks/bootstrap.sh clustername --kubelet-extra-args '--max-pods=24' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL

```

## Expected behavior

After i updated my config to v18.x i expected to have the same nodes as i would have on 17.x
## Actual behavior

User-data configuration seems off
### Terminal Output Screenshot(s)

n/a
## Additional context

n/a

**Comment by nickvanwegen** [comment]
terraform apply output with above configuration

`to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:* : Ec2LaunchTemplateInvalidConfiguration: User data was not in the MIME multipart format
`

LT created by module 

```
#!/bin/bash
set -e
export CONTAINER_RUNTIME="containerd"
export USE_MAX_PODS=false
B64_CLUSTER_CA=hidden
API_SERVER_URL=hidden
/etc/eks/bootstrap.sh cluster --kubelet-extra-args '--max-pods=24' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL


```

**Comment by bryantbiggs** [comment]
I think the configuration you want should be:

```hcl
    bootstrap_extra_args       = "--kubelet-extra-args '--max-pods=24'"

    pre_bootstrap_user_data = <<-EOT
        export CONTAINER_RUNTIME="containerd"
        export USE_MAX_PODS=false
    EOT

    taints = [
      {
        key    = "node.cilium.io/agent-not-ready"
        value  = "true"
        effect = "NO_SCHEDULE"
      }
    ]

```

**Comment by nickvanwegen** [comment]
Hi @bryantbiggs If i dont use `enable_bootstrap_user_data = true` the `bootstrap_extra_args` are not picked up. 

So far i have found that if i give in my configuration an ami_id so 
`ami_id                                 = "ami-02b3f04ab50ffd9f1"` 
then it works. 

The only thing then is that the taints block does not work anymore. so with managed nodes i have to taint with kubelet-extra-args

**Comment by bryantbiggs** [comment]
please read https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/_user_data if you haven't already

**Comment by nickvanwegen** [comment]
I have read this i see that if you use a custom AMI you can set the option but now i am here and i am using ami_id = but the id i give is the EKS optimized AMI. With this it works. 

Now i use your suggested configuration and i log into the node that gets deployed and look  at the user-data i see that the user data looks like the following. 
```
content-Type: multipart/mixed; boundary="//"
MIME-Version: 1.0

--//
Content-Transfer-Encoding: 7bit
Content-Type: text/x-shellscript
Mime-Version: 1.0

export CONTAINER_RUNTIME="containerd"
export USE_MAX_PODS=false

--//--
```
so these nodes never join my cluster

**Comment by bryantbiggs** [comment]
I can't help you unless you post a full code sample of the module configuration. The examples provided in the project are meant for both demonstration and testing/validation and they do work. So you can provide a full reproduction or look at the examples to figure it out on your own
