### ISSUE TITLE
Concatinating cluster_security_group_id  and security_group_ids forces cluster replacement when importing an existing cluster

### ISSUE THREAD

**Issue by tsoe77** [terraform-aws-modules/terraform-aws-eks#1764]
## Description

Module will force to replace entire cluster when we import an existing cluster with pre-created additional security-groups.

## Versions

- Terraform:
- Provider(s):

```txt
Terraform v1.1.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.71.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

Your version of Terraform is out of date! The latest version
is 1.1.3. You can update by downloading from https://www.terraform.io/downloads.html
```

- Module:

```txt
source  = "terraform-aws-modules/eks/aws"
version = "18.0.5"
```

## Reproduction

I am not using Terraform workspace. Following is my Terraform snippet.

```json
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.0.5"

  cluster_name                    = "my-existing-cluster"
  cluster_version                 = "1.21"
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  create_cloudwatch_log_group = false
  create_cluster_security_group = false
  create_node_security_group = false
  create_iam_role = false

  vpc_id     = "vpc-123abc"
  subnet_ids = ["subnet-123abc", "subnet-456def", "subnet-789ghi"]
  cluster_security_group_id = "sg-123abc"
  cluster_additional_security_group_ids = ["sg-456def"]
  node_security_group_id = "sg-123abc"
  iam_role_arn = "arn:aws:iam::1234567890:role/my-cluster-role"
}
```

1) Import an existing cluster

`terraform import 'module.eks.aws_eks_cluster.this[0]' my-cluster`

1) Terraform plan

```txt
  # module.eks.aws_eks_cluster.this[0] must be replaced
  ...

      ~ vpc_config {
          ~ cluster_security_group_id = "sg-123abc" -> (known after apply)
          ~ security_group_ids        = [ # forces replacement
              + "sg-123abc",
                # (1 unchanged element hidden)
            ]
          ~ vpc_id                    = "vpc-123abc" -> (known after apply)
            # (4 unchanged attributes hidden)
        }
        # (1 unchanged block hidden)
    }

Plan: 1 to add, 0 to change, 2 to destroy.
```

## Expected behavior

I expect it to apply changes to the minor differences such as tags, etc. only. 

## Actual behavior

Module tried to merge cluster_security_group_id to the additional security_group_ids. I wasn't expecting it to happen since cluster_security_group_id is an attribute itself in `aws_eks_cluster` `vpc_config`.

```txt
          ~ cluster_security_group_id = "sg-123abc" -> (known after apply)
          ~ security_group_ids        = [ # forces replacement
              + "sg-123abc",
                # (1 unchanged element hidden)
            ]
```

## Additional context

The issue seems to be caused by line 16 of module's `main.tf` in my opinion.

```txt
    security_group_ids      = distinct(concat(var.cluster_additional_security_group_ids, [local.cluster_security_group_id]))
```

I tried updating it to this and I get an expected result.

```txt
    security_group_ids = var.cluster_additional_security_group_ids
```

**Comment by bryantbiggs** [comment]
needs re-production configs

**Comment by tsoe77** [comment]
Thanks for looking into it @bryantbiggs. After looking into it a bit deeper, I discovered I had an extra SG which actually not needed in the original cluster. The module provides the correct way of deploying a new cluster. It's fine after cleaning it up and re-ran it.

**Comment by glaracuente** [comment]
I think this is a real issue and should be opened back up. I could be wrong. 

But no matter whether you use this module, or the pure `aws_eks_cluster` resource to import an existing cluster, the "cluster_security_group_id" is never part of the list of "security_group_ids" upon an import.

So by this module explicitly adding the value of the "cluster_security_group_id" to this list, it's not compatible with importing an existing cluster. I can even imagine that this could not be used to create a cluster and then make any terraform plan/apply to it without causes a recreation.

**Comment by glaracuente** [comment]
nevermind, just some confusion with the naming, that makes sense after reading this:

This module by default creates a cluster security group ("additional" security group when viewed from the console) in addition to the default security group created by the AWS EKS service. This "additional" security group allows users to customize inbound and outbound rules via the module as they see fit

which was found here: https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest
