### ISSUE TITLE
Terraform attempts to create new cluster without destroying previous one on a replace operation

### ISSUE THREAD

**Issue by erhudy** [terraform-aws-modules/terraform-aws-eks#1767]
## Description

I am consistently encountering an issue where I make a change to a cluster setup in some way that requires Terraform to replace and recreate it. This is fine, but Terraform doesn't actually destroy the old cluster. It just attempts to create a new one with the same name and fails.

## Versions

```
Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.71.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

Module: terraform-aws-eks 18.0.5

## Reproduction

1. Create an EKS cluster
2. Change something that will trigger a cluster replacement (in my case, I changed the name of some IAM stuff).
3. Apply and watch as Terraform attempts to create a new cluster over top of the old one

I am not using workspaces and I have cleared the local cache repeatedly.

## Expected behavior
I would expect Terraform to destroy the old cluster and associated resources before creating a replacement.

## Actual behavior
Terraform tries to create a new cluster without removing the old one.

### Terminal Output Screenshot(s)

```
# module.eks.aws_eks_cluster.this[0] must be replaced
+/- resource "aws_eks_cluster" "this" {
      ~ arn                       = "arn:aws:eks:us-east-1:XXXXXXXXXXXX:cluster/erhudy-eks-baselinetest" -> (known after apply)


Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

 

  Enter a value: yes

 

module.eks.aws_iam_openid_connect_provider.oidc_provider[0]: Destroying... [id=arn:aws:iam::XXXXXXXXXXXX:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/XXXXXXXX]
aws_iam_instance_profile.eks_managed_node_instance_profile: Creating...
module.eks.aws_iam_openid_connect_provider.oidc_provider[0]: Destruction complete after 1s
aws_security_group.private_access_cidrs_sg: Creating...
aws_iam_instance_profile.eks_managed_node_instance_profile: Creation complete after 1s [id=XXXXXXXXXXXX]
aws_iam_instance_profile.eks_managed_node_instance_profile (deposed object 2b9a4de0): Destroying... [id=XXXXXXXXXXXX]
aws_iam_instance_profile.eks_managed_node_instance_profile: Destruction complete after 0s
aws_security_group.private_access_cidrs_sg: Creation complete after 1s [id=XXXXXXXXXXXX]
module.eks.aws_eks_cluster.this[0]: Creating...
╷
│ Error: error creating EKS Cluster (erhudy-eks-baselinetest): ResourceInUseException: Cluster already exists with name: erhudy-eks-baselinetest
│ {
│   RespMetadata: {
│     StatusCode: 409,
│     RequestID: "bbf4c452-4fdd-4344-81c9-a12bec214a48"
│   },
│   ClusterName: "erhudy-eks-baselinetest",
│   Message_: "Cluster already exists with name: erhudy-eks-baselinetest"
│ }
│
│   with module.eks.aws_eks_cluster.this[0],
│   on .terraform/modules/eks/main.tf line 7, in resource "aws_eks_cluster" "this":
│    7: resource "aws_eks_cluster" "this" {
│
```

**Comment by matt-land** [comment]
I also saw this behavior with 18.0.5. Workaround (not great) is to tear down the cluster manually first for certain kinds of config changes.

**Comment by bryantbiggs** [comment]
You could also use a random provider in the cluster name and set the variables on the keepers section so that the cluster is recreated when the cluster re-creation variables are changed

**Comment by bryantbiggs** [comment]
This actually would be a good feature request for the upstream AWS provider to add a `name_prefix` that's commonly used for scenarios like this

**Comment by martijnvdp** [comment]
i usually destroy the cluster first by adding `create = false` and after that i deploy a new cluster

**Comment by bryantbiggs** [comment]
closing since this is outside the scope of the module
