### ISSUE TITLE
Use create_launch_template without Detailed CloudWatch monitoring

### ISSUE THREAD

**Issue by v1nc3nt27** [terraform-aws-modules/terraform-aws-eks#1769]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
I'm using module version 17.24.0 and I'm currently in the process of changing the container runtime of all nodes to `containderd`. I just noticed the `bootstrap_env` parameter, which would be a nice way to get rid of the explicit launch templates we currently use. However, when creating a launch template with that parameter, by default the extended cloudwatch metrics are gathered. As we don't need this, I was trying to find a way to influence this parameter. However, without any luck so far. Is it even possible to influence it or do we have to keep using explicit launch template definitions? Setting `create_launch_template` to true is a necessary parameter to use `bootstrap_env` I have noticed. Thanks!

**Comment by daroga0002** [comment]
in your node group definition add:
```
..............
  self_managed_node_groups = {
    default_node_group = {
       enable_monitoring = false 
    }
..............
```

to change only one node group, or to make it globally as default:

```
  eks_managed_node_group_defaults = {
    enable_monitoring = false 
  }
```

**Comment by v1nc3nt27** [comment]
Thanks a lot, I have totally missed this parameter.
