### ISSUE TITLE
Pods unable to access any network outside the node

### ISSUE THREAD

**Issue by sumagoudb** [terraform-aws-modules/terraform-aws-eks#1779]
## Description

Newbie here! Sorry if this question is wrong.

I created a self managed node group with the following code in a private subnet with NAT. I see the pods are unable to access internet. can you help me if I missed any additional configuration or is this a bug?

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.0.6"

  cluster_name                    = local.name
  cluster_version                 = local.cluster_version
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }

  cluster_encryption_config = [{
    provider_key_arn = aws_kms_key.eks.arn
    resources        = ["secrets"]
  }]

  vpc_id     = var.vpc_id
  subnet_ids = var.private_subnets

  enable_irsa = true

  self_managed_node_group_defaults = {
    disk_size = 20
    instance_types = ["t3.medium"]
  }

  self_managed_node_groups = {
    default_node_group = {}
  }
}

```

## Versions
 - Terraform: v1.1.3
 - Provider(s):
    - hashicorp/aws v3.72.0
    - hashicorp/cloudinit v2.2.0
    - hashicorp/null v3.1.0
    - hashicorp/tls v3.1.0
 - Module: 18.0.6

## Reproduction

Are you using workspaces? --> no
Have you cleared the local cache (see Notice section above)? --> yes
List steps in order that led up to the issue you encountered --> 

```
terraform init
terraform plan
terraform apply

```
get the kubeconfig updated.
run a pod with below command and try apt update
        `kubectl run ubuntu --image=ubuntu -it --rm --restart=Never -- /bin/bash`
         `apt update`

**Comment by bryantbiggs** [comment]
Please see https://github.com/terraform-aws-modules/terraform-aws-eks#security-groups - by default, the security groups created provide only the bare minimum of network connectivity. Most likely you will need to add rules to the groups created or add your own security group

**Comment by sumagoudb** [comment]
Node is able to pull the public image but the pod spun up is unable to do the `apt update`, I suspect something with the cluster setup itself. I will definitely try your suggestion to add additional security group.

**Comment by bryantbiggs** [comment]
most likely because [443/https egress to 0.0.0.0/0](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9c6c36c5c8d6071055b2ee190ab7c1685daf6ff0/node_groups.tf#L120) is provided by default, you'll probably have to add 80/http egress to 0.0.0.0/0 to do an apt update

**Comment by sumagoudb** [comment]
Thank you, it worked :)

**Comment by tal-testim** [comment]
Hi @sumagoudb may i ask what is the changes you did and where?

**Comment by mdminhazulhaque** [comment]
Adding the following block from [examples/complete/main.tf](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/complete/main.tf#L81-L99) resolved the issue.

```
  node_security_group_additional_rules = {
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
  }
```
