### ISSUE TITLE
Add support for instance_metadata_tags in the metadata_options (aws provider v3.72.0) 

### ISSUE THREAD

**Issue by romogo17** [terraform-aws-modules/terraform-aws-eks#1780]
## Is your request related to a problem? Please describe.
On Jan 13, 2022, a new version of the terraform aws provider was released ([v3.72.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.72.0))

This release add support for `instance_metadata_tags` to the `metadata_options`
> resource/aws_launch_template: Add the instance_metadata_tags argument to the metadata_options configuration block ([#22463](https://github.com/hashicorp/terraform-provider-aws/issues/22463))

The default for `instance_metadata_tags` [is "disabled"](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#instance_metadata_tags)

After updating the provider, I got the following diff in one of my managed node groups, stating `instance_metadata_tags` was going to be setup as `disabled`
```
  ~ resource "aws_launch_template" "this" {
      ~ default_version                      = 1 -> (known after apply)
        id                                   = "lt-0000022222222"
      ~ latest_version                       = 1 -> (known after apply)
        name                                 = "XXXXYYYYYZZZZZZ"
        # (16 unchanged attributes hidden)

      ~ metadata_options {
          + instance_metadata_tags      = "disabled"
            # (4 unchanged attributes hidden)
        }

        # (4 unchanged blocks hidden)
    }
```

This option is not available in the `eks-managed-node-group` module.
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/cf985c23471b39d5bf2b7219b338c22e7cdae711/modules/eks-managed-node-group/main.tf#L177-L185

## Describe the solution you've considered
- Add `instance_metadata_tags` to the  `metadata_options` in the `eks-managed-node-group` module.
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/cf985c23471b39d5bf2b7219b338c22e7cdae711/modules/eks-managed-node-group/main.tf#L177-L185

- Also, add a default for it in the `metadata_options` variable
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/cf985c23471b39d5bf2b7219b338c22e7cdae711/modules/eks-managed-node-group/variables.tf#L213-L221

- Although, if I'm not wrong this would also require bumping up the provider version to `>= v3.72.0`
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/cf985c23471b39d5bf2b7219b338c22e7cdae711/versions.tf#L4-L8

## Describe alternatives you've considered.

- Add a version constraint to the aws provider so that `v3.72.0` is not picked

```tf
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.64, < 3.72.0"
    }
  }
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.2.0 :tada:

**Comment by romogo17** [comment]
Wow, that was fast! 🚀
Thank you very much, @bryantbiggs & @antonbabenko !

**Comment by antonbabenko** [comment]
35 seconds to be precise :)

**Comment by SeTeM** [comment]
@antonbabenko 
Module v18 has a lot of breaking changes that prevent me from upgrading the module, but the issue appears even in v17 with aws provider v3.72.0. Do you plan to backport the fix to v17?

**Comment by antonbabenko** [comment]
We have no plans to backport this to v17.

There is a detailed [upgrade guide](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/UPGRADE-18.0.md) explaining all the changes in v18. If you have questions, you can search for existing issues or ask a question.

**Comment by ivankovnatsky** [comment]
> @antonbabenko Module v18 has a lot of breaking changes that prevent me from upgrading the module, but the issue appears even in v17 with aws provider v3.72.0. Do you plan to backport the fix to v17?

You can use a separate module for self/eks/fargate modules under `https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/`. and point to 18.x.x tag.

I myself will be upgrading node groups than eks module.

**Comment by SeTeM** [comment]
@ivankovnatsky, thanks for the idea, I'll take it into account
