### ISSUE TITLE
Updating node groups tags trigger a replacement of the node group

### ISSUE THREAD

**Issue by gionn** [terraform-aws-modules/terraform-aws-eks#1793]
## Description

 Changes to aws_eks_node_group tags trigger replacement of all the nodes in the group.

## Versions
 - Terraform: 1.0.11
+ provider registry.terraform.io/hashicorp/aws v3.64.2
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.1.1
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/rancher/rancher2 v1.16.0
 - Module: 18.0.6

## Reproduction

Change `var.tags` between two run of `terraform apply`

### Code Snippet to Reproduce

```
module "my-cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.0.6"

  prefix_separator = ""
  cluster_name     = var.cluster_name
  cluster_version  = var.kubernetes_version
  cluster_encryption_config = [
    {
      provider_key_arn = local.kms_key_id
      resources        = ["secrets"]
    }
  ]
  cluster_enabled_log_types = var.cluster_logging != [] ? var.cluster_logging : null
  subnet_ids                = module.vpc.public_subnets
  vpc_id                    = module.vpc.vpc_id
  tags                      = var.tags
  eks_managed_node_groups = {
    default = {
      desired_size   = var.desired_capacity
      max_size       = var.max_capacity
      min_size       = var.min_capacity
      instance_types = [var.instance_type]
    }
  }
}
```

## Expected behavior

Changes to tags should be immediate and not retrigger a node group replacement (slow)

## Actual behavior

The entire node group is replaced (20 minutes on average)

### Terminal Output Screenshot(s)

```
 # module.my-cluster.module.eks_managed_node_group["default"].aws_eks_node_group.this[0] will be updated in-place
  ~ resource "aws_eks_node_group" "this" {
        id                     = "opsexp-1171:default-2022011908463674530000000e"
      ~ tags                   = {
          - "scope" = "integration-pipeline" -> null
            # (1 unchanged element hidden)
        }
      ~ tags_all               = {
          - "scope" = "integration-pipeline" -> null
            # (1 unchanged element hidden)
        }
        # (15 unchanged attributes hidden)
      ~ launch_template {
            id      = "lt-0b830e3b561c40ffb"
            name    = "default-2022011908463573740000000b"
          ~ version = "2" -> (known after apply)
        }
```

```
module.my-cluster.module.eks_managed_node_group["default"].aws_eks_node_group.this[0]: Still modifying... [id=opsexp-1171:default-2022011908463674530000000e, 27m20s elapsed]
module.my-cluster.module.eks_managed_node_group["default"].aws_eks_node_group.this[0]: Modifications complete after 27m28s [id=opsexp-1171:default-2022011908463674530000000e]
```

**Comment by bryantbiggs** [comment]
this reproduction is inadequate as provided

**Comment by bryantbiggs** [comment]
see https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1826
