### ISSUE TITLE
module.eks.aws_auth_configmap_yaml output is missing rolearn when using existing node role/profile

### ISSUE THREAD

**Issue by youwalther65** [terraform-aws-modules/terraform-aws-eks#1794]
## Description
When creating node groups in EKS module using  MNG with create_iam_role = false/iam_role_arn    = aws_iam_role.eks-worker.arn and self-MNG with create_iam_instance_profile = false/iam_role_arn    = aws_iam_role.eks-worker.arn then module.eks.aws_auth_configmap_yaml output contains empty "rolearn:" line and so merging with other roles fails

## Versions

 - Terraform:
v1.0.11
 - Provider(s):
provider registry.terraform.io/hashicorp/aws v3.72.0
 - Module:
eks 18.2.0

### Code Snippet to Reproduce
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"
...
  eks_managed_node_groups = {    
...
      create_iam_role = false
      iam_role_arn    = aws_iam_role.eks-worker.arn
...
  self_managed_node_groups = {
...
      create_iam_instance_profile = false
      iam_instance_profile_arn = aws_iam_instance_profile.eks-worker-profile.arn
...
}

output "aws_auth_configmap_yaml" {
  description = "Formatted yaml output for base aws-auth configmap containing roles used in cluster node groups/fargate profiles"
  value       = module.eks.aws_auth_configmap_yaml
}

## Expected behavior
Outputs:

aws_auth_configmap_yaml = <<EOT
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    **- rolearn: arn:aws:iam::<redacted>:role/tf-ipv6-demo-eks-node-group-role**
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

aws-auth ConfigMap in cluster itself is correct and contains one worker node role entry (both self-MNG and MNG uses same role/profile) like:
$ k get cm -n kube-system aws-auth -o yaml
apiVersion: v1
data:
  mapRoles: |-
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<redacted>:role/tf-ipv6-demo-eks-node-group-role
      username: system:node:{{EC2PrivateDNSName}}

## Actual behavior
Outputs:

aws_auth_configmap_yaml = <<EOT
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    **- rolearn:**
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    **- rolearn:**
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

**Comment by bryantbiggs** [comment]
module outputs are of those resources created by the module; resources that exist outside of the module will not be contained within the output. there are a few edge cases where this may not be true but that is generally true
