### ISSUE TITLE
Attribute-Based Instance Type Selection for node groups

### ISSUE THREAD

**Issue by youwalther65** [terraform-aws-modules/terraform-aws-eks#1800]
## Is your request related to a new offering from AWS?
Yes, see:
https://aws.amazon.com/blogs/aws/new-attribute-based-instance-type-selection-for-ec2-auto-scaling-and-ec2-fleet/
https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-asg-instance-type-requirements.html

The feature is not yet implemented in the Terraform AWS provider, see corresponding issue:
https://github.com/hashicorp/terraform-provider-aws/issues/21566

This would be a great feature for node groups using SPOT or ON DEMAND with instance diversification. It would simplify node group configuration and make it future proof by just provision the needed resources (for example vCPU and memory) and let the corresponding AWS API pickup suitable instance types even new ones as  they become available.

**Comment by bryantbiggs** [comment]
bad bot

**Comment by risinger** [comment]
Would a maintainer please reopen and stop the bot from marking this stale?

**Comment by sacksi28** [comment]
@bryantbiggs I believe https://github.com/hashicorp/terraform-provider-aws/issues/21566 doesn't cover the `aws_eks_node_group` resource unless I have missed something. :-) 

May be we look at using [ec2_instance_types data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ec2_instance_types#filter) to implement instance selector similar to how eksctl does [here](https://eksctl.io/usage/instance-selector/#instance-selector)

Any thoughts?

**Comment by bryantbiggs** [comment]
Correct - getting it into the EKS managed node group is a whole different ball of yarn. First we need the EKS service to support it in managed node groups, then the AWS provider will need to update (possibly, depending on implementation/API). We could try passing a launch template with the attribute based instance selection and see what happens - haven't tried that myself 🤷🏽

**Comment by ruecarlo** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/21566 is now closed so work on this can progress.

**Comment by davidweizheng** [comment]
This feature would be very useful. Can someone look into it?

**Comment by bryantbiggs** [comment]
v19 needs to be released to increase the provider version to at least v4.x first

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.0.0 :tada:
