### ISSUE TITLE
var.create_iam_role is true when it's false

### ISSUE THREAD

**Issue by zicodes** [terraform-aws-modules/terraform-aws-eks#1811]
## Versions
v18.2.3
 - Terraform:
Terraform v1.1.4
 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v3.73.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

 - Module:
 /modules/eks/modules/eks-managed-node-group

## Reproduction

Hello,

I am setting ```create_iam_role``` to ```false``` and receiving below (please note it says ```var.create_iam_role is true``` when it shouldn't be.

Is it possible that the module is ignoring `create_iam_role = false` ?

Additionally, I am not using CNI. Is there an error with it being applied?

I can get a terraform plan to execute successfully If I make these edits:
1.
 modules/eks-managed-node-group/main.tf line 433
change:
```
  for_each = var.create && var.create_iam_role ? toset(compact(distinct(concat([
```
to
```
  for_each = var.create && false ? toset(compact(distinct(concat([
```
2.
 modules/eks-managed-node-group/main.tf line 436
change:
```
    var.iam_role_attach_cni_policy ? local.cni_policy : "",
```
to:
```
    var.iam_role_attach_cni_policy ? false : "",
```
3.  modules/eks-managed-node-group/main.tf line 268

change:
```
  node_role_arn = var.create_iam_role ? aws_iam_role.this[0].arn : var.iam_role_arn
```
to  (hardcoded arn), having `var.iam_role_arn` didn't work:

```
  node_role_arn = "arn:aws:iam::123456789:role/aws-service-role/eks-nodegroup.amazonaws.com/AWSServiceRoleForAmazonEKSNodegroup"

```

```
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/eks/modules/eks-managed-node-group/main.tf line 433, in resource "aws_iam_role_policy_attachment" "this":
│  433:   for_each = var.create && var.create_iam_role ? toset(compact(distinct(concat([
│  434:     "${local.iam_role_policy_prefix}/AmazonEKSWorkerNodePolicy",
│  435:     "${local.iam_role_policy_prefix}/AmazonEC2ContainerRegistryReadOnly",
│  436:     var.iam_role_attach_cni_policy ? local.cni_policy : "",
│  437:   ], var.iam_role_additional_policies)))) : toset([])
│     ├────────────────
│     │ local.cni_policy is a string, known only after apply
│     │ local.iam_role_policy_prefix is a string, known only after apply
│     │ var.create is true
│     │ var.create_iam_role is true
│     │ var.iam_role_additional_policies is empty list of string
│     │ var.iam_role_attach_cni_policy is true
│ 
│ The "for_each" value depends on resource attributes that cannot be
│ determined until apply, so Terraform cannot predict how many instances will
│ be created. To work around this, use the -target argument to first apply
│ only the resources that the for_each depends on.
```

### Code Snippet to Reproduce
```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "18.2.3"

  for_each         = var.eks_instances
  cluster_name     = "xxx"
  cluster_version  = "1.21" 

  vpc_id          =  "xxx"
  subnet_ids       = []

  create_cluster_security_group         = false
  cluster_security_group_id             = "xxx"
  cluster_endpoint_private_access       = true
  cluster_endpoint_public_access        = false
  cluster_endpoint_public_access_cidrs	= ["127.0.0.127/32"]
  create_node_security_group          = false
  node_security_group_id              = "xxx"


  create_iam_role = false
  iam_role_arn    = aws_iam_role.eks_cluster.arn
  iam_role_additional_policies = []
  iam_role_use_name_prefix = false
  
  depends_on                      = [
    aws_security_group.eks-cluster-sec-group,
    aws_security_group.eks-external-sec-group,
    aws_key_pair.eks_keypair,
    aws_iam_role.eks_cluster,
    aws_iam_role.eks_nodes
  ]

  # EKS Managed Node Group(s)
  eks_managed_node_group_defaults = {
    ami_type               = "AL2_x86_64"
    disk_size              = 30
    instance_types         = ["t3.medium"]
    vpc_security_group_ids =  [ "xxx" ]
  }

  eks_managed_node_groups = {
    blue = {}
    green = {
      min_size     = 2
      max_size     = 2
      desired_size = 2

      instance_types = ["t3.medium"]
      capacity_type  = "ON_DEMAND"
      labels = {
        Xxx = "xxx"
      }

      taints = {
        dedicated = {
          key    = "dedicated"
          value  = "gpuGroup"
          effect = "NO_SCHEDULE"
        }
      }

      update_config = {
        max_unavailable_percentage = 50 # or set `max_unavailable`
      }
    }
  }
}
```

## Expected behavior
Since my own IAM role is used, the module shouldn't be making any IAM role attachments.
## Actual behavior
create_iam_role shows as true when it's set to false
possibly var.iam_role_arn is also problematic

Thank you

**Comment by zicodes** [comment]
Additionally, I tried older versions of 18.x and they exhibit the same behaviour.

as if `create_iam_role` and then after custom edits to module `iam_role_arn` not taking proper effect

**Comment by bryantbiggs** [comment]
I believe the issue you are facing is actually the use of `depends_on` in your module instantiation (https://github.com/hashicorp/terraform/issues/30340#issuecomment-1010202582). 

this is clearly identified in the docs https://github.com/terraform-aws-modules/terraform-aws-eks#%E2%84%B9%EF%B8%8F-error-invalid-for_each-argument-

**Comment by zicodes** [comment]
@bryantbiggs 

Okay so using v18.2.3 the solution for me seems to be moving:
`create_iam_role = false
  iam_role_arn    = aws_iam_role.eks_cluster.arn`

from the main config body into `eks_managed_node_group_defaults`, like this:

`  # EKS Managed Node Group(s)
  eks_managed_node_group_defaults = {
    create_iam_role = false
    iam_role_arn    = aws_iam_role.eks_cluster.arn
    ami_type               = "AL2_x86_64"
    disk_size              = 30
    instance_types         = ["t3.medium"]
    vpc_security_group_ids =  [ "xxx" ]
  }
`
This so far yielded a plan output. 

So far now I assume `create_iam_role` exists for both cluster & node group. Which makes sense now as older v17 modules used to have separate var assignments for both.

**Comment by practical-gitops** [comment]
removing depends_on solved this issue.

**Comment by cduv** [comment]
removing depends_on inside eks module call solved this issue.
