### ISSUE TITLE
How to slow down node group migration when applying a change

### ISSUE THREAD

**Issue by hetile-ssense** [terraform-aws-modules/terraform-aws-eks#1813]
## Description

We have a few clusters deployed with the module, both QA and PROD.

From time to time, we make some changes on the instance type used by the cluster which, obviously, triggers a node group re-creation and a full migration of all the deployment on newly created node group and the old one is destroyed.

While this isn't an issue in QA since pod dies constantly and we're using spot instances so devs are used to it, for production, it is way to violent as all the pod get evicted at once and while it being transferred to the new node group, there isn't enough spawned deployment to handle to load and boom, website goes down for a split second as everything stabilize. We have different nodegroup defined and they all get handled at the same time too. We could split the changes per node group but it still create a massive migration within these groups.

We are looking for a way to have this move happen slowly so that enough pods are available before all the eviction happens.

It seems that terraform just blindly delete/recreate while kube just try its best to stay alive as quickly as possible.

Sorry if this isn't the correct way to get input, I don't think that's a bug since it's probably the expected behavior from terraform so I'm looking for pointers or if there's already a built-in mecanism feel free to refer me and close this :) (yes, I did search a bunch but couldn't find much except options to affect the ASG itself but terraform seems to be a little more direct.

## Versions

 - Terraform: 1.1.4

 - Provider(s):

 - Module:

## Reproduction

- Deploy a cluster
- Have some workload on it
- Change instance type

## Expected behavior

We would like a slow migration from old nodegroup to new nodegroup

## Actual behavior

Everything is evicted too quickly which create a downtime

## Additional context
Probably not a bug

**Comment by bryantbiggs** [comment]
I think your safest route would be to add a new node group(s) when you want to make an instance type change, taint the nodes in the old node group - once the old nodes no longer have pods running on them then you can remove that node group

I suspect theres an OSS operator of sorts out there that does this - I don't know of a way of natively doing it in the module here. The closest example I could point you to would be https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/irsa_autoscale_refresh

**Comment by philicious** [comment]
@hetile-ssense if you use Managed-Node-Groups, EKS will take partial responsibility of gracefully cordoning and draining workloads to the new nodes.
however as you described, this can lead to short downtimes if all replicas of a deployment are evicted in parallel. you can mitigate this with adding Pod Disruption Budgets to your deployments, ensuring that some are always up

**Comment by daroga0002** [comment]
evitction of pods is controlled by deployments definition, so you must setup this on Kubernetes objects level.

**Comment by bryantbiggs** [comment]
closing for now since its outside the purview of this module

**Comment by rl-abdulkarim** [comment]
> https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/irsa_autoscale_refresh

The link is dead. Facing a similar issue where the old node group gets terminated sooner than I expect it to.

Is the deletion time of old node group configurable? 
I understand that it's not recommended but still, if one wants, can they configure the old nodegroup to stay alive for 'x' minutes and then terminate?
