### ISSUE TITLE
provide output for workers IAM role ARN

### ISSUE THREAD

**Issue by draeath** [terraform-aws-modules/terraform-aws-eks#1815]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
I am attempting to create S3 buckets, managing permissions with S3 policies. The principles accepted in this include IAM role ARNs. Cluster workers have their own role created, NOT the (already exposed) cluster role, so `cluster_iam_role_arn` is not useful for this sort of thing.

## Describe the solution you'd like.
Similar to the existing `module.eks.cluster_iam_role_arn` output, something like `module.eks.workers_iam_role_arn` would do the job.

## Describe alternatives you've considered.
I have tried a variety of ways to access this data, but have failed (likely due to my being a terraform newbie). I'm sure there's another way to get at this, but I think it's sufficiently useful that it should be an eks module output as this would be useful broadly in managing cluster node's access to other AWS resources without manually creating / managing the worker IAM role itself.

## Additional context
Both of the following terraform states have the value I am interested in:

-  `module.eks.aws_iam_role.workers[0]` (`arn` variable)
-  `module.eks.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy[0]` (`role` variable)

**Comment by bryantbiggs** [comment]
The output is not that straight forward because the node groups use `for_each` so the result is 0-n ARNs (depending on how many node groups are created). However, you can see how you can extract the IAM role ARNs here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/outputs.tf#L168-L171

**Comment by draeath** [comment]
@bryantbiggs thanks, that looks like what I need.

What's interesting though, is I only have *one* of these ARNs in my state even though I am creating 9 node groups. Nosing around on the AWS side, they all have the same role.

**Comment by draeath** [comment]
Eh actually I don't understand how to make use of this, or that `eks_managed_node_group` module call is something v18 added.

```tf
output "worker_iam_role_arns" {
  description = "IAM role ARNs of the EKS nodes."
  value       = [for group in module.eks_managed_node_group : group.iam_role_arn]
}
```

throws:
```
│ Error: Reference to undeclared module
│ 
│   on outputs.tf line 48, in output "worker_iam_role_arns":
│   48:   value       = [for group in module.eks_managed_node_group : group.iam_role_arn]
│ 
│ No module call named "eks_managed_node_group" is declared in the root module.
```

**Comment by auyer** [comment]
I also noticed this difference in behaviour.
In 17.x all nodes used the "cluster_iam_role_arn". 
In 18.x, it creates one policy for each node group.

This made me change the way I added roles to my cluster. 

What I did:

before: 
```hcl
resource "aws_iam_role_policy_attachment" "my-role-policy" {
  policy_arn = my-policy.arn
  role       = module.eks.cluster_iam_role_name
}

module "eks" {...}
```

After:
```hcl
module "eks" {
...
eks_managed_node_group_defaults = {
    iam_role_additional_policies = [my-policy.arn]
  }
}
```

Hope it helps!

**Comment by bryantbiggs** [comment]
the correct output for what was posted above would be:

```hcl
output "worker_iam_role_arns" {
  description = "IAM role ARNs of the EKS nodes."
  value       = [for group in module.eks.eks_managed_node_groups : group.iam_role_arn]
}
```

closing out issue for now
