### ISSUE TITLE
Do there is a way to prevent create default storage class in EKS with this module?

### ISSUE THREAD

**Issue by GrigorievNick** [terraform-aws-modules/terraform-aws-eks#1821]
## Description

So there is a way to prevent creating a default storage class in EKS with this module?
Or maybe someone knows, work around how to change or delete default SG with terraforming.

**Comment by philicious** [comment]
@GrigorievNick afaik no. there always is a default StorageClass when you create an EKS

however you could use the tf kubernetes provider to provision a new default SC. I personally like to manage all cluster-internal components with helm / helmfile tho, which gives you more flexibility than the kubernetes provider of tf

**Comment by GrigorievNick** [comment]
But there is no way to change already existed storage class. And I need not only create new storage class, but also change annotations on old one.

**Comment by philicious** [comment]
@GrigorievNick it depends on the tooling: i.e. with helm you do have the possibility to map/import existing resources onto a helm release and continue managing it then. including updating annotations

**Comment by GrigorievNick** [comment]
You mean pure helm? Not terraform helm_provider?

вт, 1 февр. 2022 г., 21:53 philicious ***@***.***>:

**Comment by philicious** [comment]
yes, pure helm. the helm provider doesnt provide the full feature-set as helm itself. in the end you might be able to first import to helm natively, then connect it to tf with helm provider.

**Comment by bryantbiggs** [comment]
closing for now since this is outside the purview of the module

**Comment by gnuletik** [comment]
I was able to remove the default storage class with https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/annotations.

```tf
resource "kubernetes_annotations" "default-storageclass" {
  api_version = "storage.k8s.io/v1"
  kind        = "StorageClass"
  force       = "true"

  metadata {
    name = "gp2"
  }
  annotations = {
    "storageclass.kubernetes.io/is-default-class" = "false"
  }
}
```

**Comment by gfrid** [comment]
> I was able to remove the default storage class with https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/annotations.
> 
> ```terraform
> resource "kubernetes_annotations" "default-storageclass" {
>   api_version = "storage.k8s.io/v1"
>   kind        = "StorageClass"
>   force       = "true"
> 
>   metadata {
>     name = "gp2"
>   }
>   annotations = {
>     "storageclass.kubernetes.io/is-default-class" = "false"
>   }
> }
> ```

thanks, i have been looking for that!!!
