### ISSUE TITLE
Additional EKS OIDC root CA thumbprint

### ISSUE THREAD

**Issue by c6-fviana** [terraform-aws-modules/terraform-aws-eks#1832]
In the 17.x I was using a custom internal thumbprint for OIDC.
On new clusters provisioned by 18.x I had some problems to assume role by webIdentity due thumbprint check errors

It's possible to have a way to include new custom thumbprint?

**Comment by bryantbiggs** [comment]
No, I don't believe this is possible

**Comment by bryantbiggs** [comment]
closing since this is outside the purview of the module
