### ISSUE TITLE
in a pickle

### ISSUE THREAD

**Issue by naseemkullah** [terraform-aws-modules/terraform-aws-eks#1834]
looking to upgrade from 12.2.0 to latest 18.2.7 without downtime

Could someone please refer me to an upgrade path? 😬

**Comment by ivankovnatsky** [comment]
@naseemkullah please just follow this issue. and close yours, the summary does not indicate any real context.

**Comment by naseemkullah** [comment]
Hi @ivankovnatsky i noticed an issue with regards to upgrading to 18.

Are there any docs to upgrade from 12 to 13, 13 to 14, 14 to 15 and so on? Or should the upgrade from 12 to 28 be attempted directly?

Closing issue now. It would appreciate any info with regards to that.

**Comment by ivankovnatsky** [comment]
@naseemkullah 

tdlr: v18 is a breaking change meaning that you won't be able to upgrade keeping your current resources, and the actions like state manipulation and other shenanigans would be needed. 

take a look around at https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/UPGRADE-18.0.md and the thread down the issue: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1744

sorry, though i posted the url, but i did not.

**Comment by naseemkullah** [comment]
I see I see

Do you have any info about going from 12 to something below 18? Actually the interesting release is 16 in my case to get rid of `template_file` use which is not supported on ARM

**Comment by naseemkullah** [comment]
Thanks @ivankovnatsky

**Comment by kaykhancheckpoint** [comment]
Curious if you ever managed to do an upgrade?

**Comment by ivankovnatsky** [comment]
We did an upgrade only for this module: https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/self-managed-node-group.
