### ISSUE TITLE
Race-Condition with certain EKS Addons

### ISSUE THREAD

**Issue by philicious** [terraform-aws-modules/terraform-aws-eks#1838]
## Description

If you choose to deploy an EKS addon that is of kind `Deployment` (e.g. coredns), it can lead to a race-condition where the node-group is not yet created and the Addon is waiting indefinitely to be deployed, ultimately leading to a TF timeout.

With kind `DaemonSet` Addons like-kube-proxy, this doesnt happen.

## Versions
 - Module: 18.2.1

## Reproduction
```
  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
      addon_version     = var.addon_coredns_version
    }
  }
```

```
|Error: unexpected EKS Add-On (tst-eks:coredns) state returned during creation: timeout while waiting for state to become 'ACTIVE' (last state: 'DEGRADED', timeout: 20m0s)
│ [WARNING] Running terraform apply again will remove the kubernetes add-on and attempt to create it again effectively purging previous add-on configuration
│
│ with module.eks.module.eks.aws_eks_addon.this["coredns"],
│ on .terraform/modules/eks.eks/main.tf line 221, in resource "aws_eks_addon" "this":
│ 221: resource "aws_eks_addon" "this" {
```
## Additional context

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L221-L238 doesnt have a dependency on the node-group creation, which can lead to this race-condition

**Comment by bryantbiggs** [comment]
duplicate #1801
