### ISSUE TITLE
Change Fargate Security Group / Load Balancer Health Check

### ISSUE THREAD

**Issue by francardoso93** [terraform-aws-modules/terraform-aws-eks#1839]
## Description

LoadBalancer security group is added to `node_security_group_id` inbound (all ports) when it is created. BUT Node SG isn't the same group that Fargate is in (Even though I really wish it was). That makes health check fail and pod inacessibilidade through it.

So I wonder if it is possible to do one of these:
- Change Fargate security group from `cluster_primary_security_group_id` to `node_security_group_id` (Which seems like the best option)
- Change behavior of LoadBalancers to add inbound ports to `cluster_primary_security_group_id`  instead of  `node_security_group_id`. (Not so good security wise but would fix this).

## Versions
 - Terraform:
Terraform v1.0.11
 - Module: 
 terraform-aws-modules/eks/aws 18.2.3

**Comment by bryantbiggs** [comment]
hi @francardoso93 - we don't have control over what security group the Fargate profiles use at this point in time (as far as I am aware). also, this module does not have any resources regarding load balancers so I don't think thats applicable here

**Comment by francardoso93** [comment]
Ok @bryantbiggs thanks anyway! 
I feel that this would be a nice feature though.

**Comment by bryantbiggs** [comment]
I'm sorry - I don't know what feature you are referring to. The AWS API does not expose the ability to specify what security group is assigned to the Fargate profile https://awscli.amazonaws.com/v2/documentation/api/latest/reference/eks/create-fargate-profile.html

AWS has to support the configuration first, then the AWS Terraform provider has to support it before we can support it here

**Comment by bryantbiggs** [comment]
closing for now
