### ISSUE TITLE
VPC-CNI addon with managed IRSA

### ISSUE THREAD

**Issue by jacobball11** [terraform-aws-modules/terraform-aws-eks#1841]
## Is your request related to a new offering from AWS?
No. This request is based on the [Configuring the Amazon VPC CNI plugin to use IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html) article.

## Is your request related to a problem? Please describe.
The problem is a chicken before the egg problem. The VPC-CNI addon recommends that we create a user role that gets attached directly to the CNI pods. This role (as described in the article linked above) requires a trust policy that is linked to the OIDC ID which we don't have access to until the module is applied (and thus the cluster exists). The terraform EKS module only allows us to pass in a role ARN for the plugin so it is impossible to create a new cluster from scratch with this addon and its appropriate iam role.

## Describe the solution you'd like.

- Add a new optionally created `aws_iam_role` specifically for the VPC-CNI addon 
- Add the necessary policies to the vpc-cni-addon role as described in the article above
- Add input variables for creating the role, naming the role, additional policies to the role, additional tags, etc... (just like it is done for the cluster iam role)
- Update the addon resource block to conditionally use the new role or to use a provided role for `service_account_role_arn`

## Describe alternatives you've considered.
Additional documentation around the addons would be really helpful if nothing else.
The addon iam role can be created just fine _after_ the cluster already exists, but that means I have to deploy changes twice (or more) to accomplish something that can be done all at once.

## Additional context
The ultimate goal here is to have the ability to create (and destroy) multiple eks clusters in different regions created just as they can be created using eksctl from a terminal. Currently I have to create this eks addon and its corresponding iam role separately because I can't insert an OIDC ID that doesn't exist yet into an iam role policy.

**Comment by jacobball11** [comment]
@bryantbiggs If it helps, here is my current (temporary) solution to this problem.

```
data "aws_iam_policy" "cni" {
  name = "AmazonEKS_CNI_Policy"
}

locals {
  eks-oidc-issuer-id = trimprefix(module.eks-cluster.cluster_oidc_issuer_url, "https://")
}

data "aws_iam_policy_document" "vpc-cni-assume-role-policy" {
  statement {
    effect = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    principals {
      type        = "Federated"
      identifiers = [module.eks-cluster.oidc_provider_arn]
    }

    condition {
      test = "StringEquals"
      variable = "${local.eks-oidc-issuer-id}:sub"

      values = [
        "system:serviceaccount:kube-system:aws-node"
      ]
    }

    condition {
      test = "StringEquals"
      variable = "${local.eks-oidc-issuer-id}:aud"

      values = [
        "sts.amazonaws.com"
      ]
    }
  }
}

resource "aws_iam_role" "vpc-cni" {
  name               = "${var.cluster-name}-${var.region}-CNI-Role"
  managed_policy_arns = [data.aws_iam_policy.cni.arn]
  assume_role_policy = data.aws_iam_policy_document.vpc-cni-assume-role-policy.json
}

resource "aws_eks_addon" "vpc-cni" {
  cluster_name             = module.eks-cluster.cluster_id
  addon_name               = "vpc-cni"
  resolve_conflicts        = "OVERWRITE"
  service_account_role_arn = aws_iam_role.vpc-cni.arn
}
```

Notes: 
- The module name in this case is `eks-cluster`
- The input variables used are `cluster-name` and `region` where `cluster-name` could be pulled directly from the output of the module but I wanted to give the user a bit more control here.
- This will create the IAM role and policy/assume role policy just as it is created with `eksctl` (as far as I know anyways)

**Comment by bryantbiggs** [comment]
thanks @jacobball11 - I think I have an idea of what needs to be implemented, just need to find a bit of time and we should have something for this

**Comment by bryantbiggs** [comment]
@jacobball11 FYI - you can see an example here of this new integration https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1882
