### ISSUE TITLE
Unable to apply labels to the EKS managed node group worker node when used bootstrap_extra_args in v18 eks module

### ISSUE THREAD

**Issue by Abhilash2008** [terraform-aws-modules/terraform-aws-eks#1842]
## Description

I'm working on migration from v17 to v18 and spin up worker nodes with containerd runtime. I'm using bootstrap_extra_args to apply lifecycle label to worker nodes. But for some reason it is not working. 

node group code:

eks_managed_node_group_defaults = {
    key_name                                 = var.key_name
    pre_bootstrap_user_data       = file("${path.module}/templates/pre-worker-userdata.yaml")
    create_security_group            = false
    iam_role_additional_policies  = [
      "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
      "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
      "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
      ]
    vpc_security_group_ids         = concat(var.worker_additional_security_group_ids, [data.aws_security_group.worker_channel_common_security_group.id,  aws_security_group.channels-sg.id, aws_security_group.workers.id])
  }

eks_managed_node_groups         = var.node_groups

pre-worker-userdata.yaml code:

---Some proxy configs goes here----
cat <<-EOF > /etc/profile.d/bootstrap.sh
export CONTAINER_RUNTIME="containerd"
EOF
sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh

Value of variable node_groups:

node_groups:
  
  on_demand_0_:
    desired_size: 1
    instance_types: ["m5.large"]
    bootstrap_extra_args: "--container-runtime containerd --kubelet-extra-args '--node-labels=lifecycle=OnDemand'"
    max_size: 9
    min_size: 1
    subnet_ids: ["XXXXXXX"]
    cluster_version: "1.21"

## Versions
 - Terraform: 1.0.8

 - Provider(s):
 Terraform v1.0.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.74.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4
+ provider registry.terraform.io/hashicorp/tls v3.1.0
 - Module: 18.1.0

## Expected behavior
Node to be launched with containerd as runtime and labeled with "lifecycle=OnDemand" 

## Actual behavior
Label is not applied to the node

**Comment by bryantbiggs** [comment]
hi @Abhilash2008  - I think you want to check out this https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/eks_managed_node_group#container-runtime--user-data

Let me know if this solves your issue or not

**Comment by Abhilash2008** [comment]
@bryantbiggs I'm afraid, no. In my use-case, I cannot put both the export statements (one for CONTAINER_RUNTIME and another for KUBELET_EXTRA_ARGS) together in a single block. I want containerd as runtime for all my nodes but lifecycle label to differ as I have both OnDemand and Spot instances. That's why I separated them as seen in the code above.

**Comment by bryantbiggs** [comment]
I'm sorry, I don't follow

**Comment by Abhilash2008** [comment]
In the doc you referred, both the exports(shown below) are configured in a single script which in turn is passed as an input to pre_bootstrap_user_data. In my use case, they are separated. I want to set container_runtime flag in the input which I pass to 'pre_bootstrap_user_data' and pass kubelet arguments as an input to 'bootstrap_extra_args. Can I not do it this way?

export CONTAINER_RUNTIME="containerd"
export KUBELET_EXTRA_ARGS="--node-labels=lifecycle=OnDemand"

**Comment by bryantbiggs** [comment]
unless you are using a custom AMI, managed node groups set the `--kubelet-extra-args` flag and we do not have direct access to it. this is why we use the workaround that I linked. 

it sounds like you want one node group of on-demand and one using spot - I haven't checked what managed node groups spit out when using a mixed node group

**Comment by Abhilash2008** [comment]
I just tried spinning up a new node with below config. It failed to pick both containerd runtime and also the labels. Instead docker has been chosen (as it is the default) as runtime for the node.

on_demand_1_:
    desired_size: 1
    instance_types: ["m5.large"]
    pre_bootstrap_user_data: " #!/bin/bash
                                set -ex
                                cat <<-EOF > /etc/profile.d/bootstrap.sh
                                export CONTAINER_RUNTIME=containerd
                                export KUBELET_EXTRA_ARGS=--node-labels=lifecycle=OnDemand
                                EOF
                                sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh
                                "
    max_size: 9
    min_size: 1
    subnet_ids: ["XXXXXXXX"]
    version: "1.21"

**Comment by Abhilash2008** [comment]
I tried with below code too passing it as input to pre_bootstrap_user_data. Doesn't work. It failed to apply the label to worker nodes. 

cat <<-EOF > /etc/profile.d/bootstrap.sh
export CONTAINER_RUNTIME="containerd"
export KUBELET_EXTRA_ARGS="--node-labels=lifecycle=OnDemand"
EOF
# Source extra environment variables in bootstrap script
sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh

**Comment by bryantbiggs** [comment]
@Abhilash2008 I would file your ticket upstream and see what the EKS team says - https://github.com/awslabs/amazon-eks-ami/issues/844

The work around that I referenced is exactly that, a work around because the EKS managed node group service doesn't allow us direct access to the bootstrap.sh invocation where these flags are set. The examples I pointed you to do work, they do come up with the containerd runtime

**Comment by Abhilash2008** [comment]
@bryantbiggs Thanks for the answer and taking it to upstream. Much appreciated. 

The workaround you have referenced absolutely makes sense to me. In fact, it is what I used in my code. Only then I see worker nodes have come up with containerd runtime. The only concern which I have is it is not applying the label to my worker nodes due to which I could not deploy one of the add-ons(cluster-autoscaler) onto the nodes. This add-on is using nodeSelector in its deployment.yaml to ensure it is deployed only on OnDemand type instances but not spot instances for persistence reasons. 

As a workaround, I've applied the label manually to my worker node using 'kubectl label nodes' and tried deploying the add-on which went fine this time. Now I want this labelling to be happened as part of my automation. Hope it is clear.

**Comment by bryantbiggs** [comment]
but if you have one node group of on-demand, the EKS managed node group will automatically label that with OnDemand, and likewise a separate node group for spot, EKS managed node group will automatically label that with Spot - correct? I'm not following why you need to control the labels yourself

**Comment by jvahldick** [comment]
Hey guys
I'm having a similar issue as @Abhilash2008 is mentioned. I manage to add the containerd as default runtime container, however, when trying to add node labels through labels or --node-labels using KUBELET_EXTRA_ARGS they seem to be ignored for some reason.

I tried lots of different ways that I don't remember all attempts. The outcome is usually the same, which is the node not joining the cluster or not having the labels added.

**Comment by bryantbiggs** [comment]
Guys - you're not listening. Do this - create a simple EKS managed node group using just the default configurations. Go look at the user data for the node that is provisioned and look at the various flags used in the bootstrap.sh script - those were set by the EKS managed node group service, not this module

When using the EKS managed node group service, *UNLESS* you provide an `ami_id` (signalling to the service that its a custom AMI), the EKS managed node group service is going to managed the bootstrap.sh script invocation. This is what you are wanting access to and what we do NOT have access to - that is the reason for the workaround posted. How to get it to work for lables, I don't know - feel free to investigate. However, this module shouldn't be concerned with this issue because its an issue with the EKS managed node group service. Therefore, please raise an issue either through AWS support or with one of the EKS github repositories asking how they can support access to the bootstrap.sh script for more configuration/customization

**Comment by jvahldick** [comment]
Hey @bryantbiggs 
Just for sake of clarification, I have seem your message before I posted and I have tried with the ami_id as well.

Basically using the id returned by the following command:
```
data "aws_ssm_parameter" "eks_ami" {
  name = "/aws/service/eks/optimized-ami/${var.cluster_version}/amazon-linux-2/recommended/image_id"
}
```

Anyways, I'll keep trying and if I figure something out I reach you again.

**Comment by bryantbiggs** [comment]
please check out the examples, there are so many use cases demonstrated there https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L198-L312

**Comment by jvahldick** [comment]
Thanks for the light @bryantbiggs 

I managed to get it working. The issue was that I was adding this label `kubernetes.io/cluster/${var.cluster_name}=owned`, and this was the cause of my headache.

@Abhilash2008 please make sure you remove this label as well.

It worked for me with the custom AMI and the standard one as well.

**Comment by Abhilash2008** [comment]
@jvahldick I'm using EKS Optimized AMI not the custom ones. Also, I'm not adding any labels other than --node-labels=lifecycle=OnDemand. 

This is what I had in my v17 code kubelet_extra_args="--node-labels=lifecycle=OnDemand". Wanted to implement this in v18 so tried the options boot_extra_args and also the workaround referenced by bryant but none of them are working. May I know what code has worked for you.

**Comment by bryantbiggs** [comment]
Wait, can't you set the label through the `label` variable?

**Comment by jvahldick** [comment]
@bryantbiggs In one of my tests that was not applied, but that's not this lib problem as you mentioned. Just to give some context, I'm not using this lib. I just used as a part of one of my test scenarios.

I'll try this weekend to create a couple of scenarios to see the outputs to give something more concrete here.

@Abhilash2008 once I create a couple of scenarios I share it with you.

**Comment by jvahldick** [comment]
@Abhilash2008 

you can find the examples in the link below
https://github.com/jvahldick/demo-terraform-eks

I am creating one node using custom AMI + launch template and one with the standard AMI

**Comment by Abhilash2008** [comment]
I managed to add labels to worker nodes using 'labels' input in the submodule eks_managed_node_groups. In v17, I've used kubelet_extra_args="--node-labels=lifecycle=OnDemand" to apply the same. So, it looks like 'labels' is kind of replacement for kubelet_extra_args in this case.  The issue is fixed. Thank you very much @bryantbiggs for the fix. Thanks @jvahldick for sharing examples.

labels= { 
lifecycle = "OnDemand" 
}

**Comment by kaykhancheckpoint** [comment]
So im also confused by this because i wanted to set a custom label for my node which i use to assign resources via NodeSelector.

I assumed the below would work because there is an example doing the exact same - https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/complete/main.tf#L114

```
bootstrap_extra_args = "--kubelet-extra-args '--node-labels=geeiq/node-type=worker'"
```

however after deploying my cluster this label was not present.

@bryantbiggs  Is the example incorrect and we should be using `eks_managed_node_groups.worker_group.labels = {}` instead?

**Comment by bryantbiggs** [comment]
it is correct because that is for a self managed node group - this does not work the same on EKS managed node groups which abstract access to the boostrap.sh script
