### ISSUE TITLE
disk_size ignored on eks_managed_node_groups

### ISSUE THREAD

**Issue by nmofonseca** [terraform-aws-modules/terraform-aws-eks#1845]
## Description

Creating a fresh new EKS cluster in a new AWS account we can't seem to change the size of the volume of EKS managed node group EC2 instances, it always creates with the default value of 20 Gib.

## Versions
 - Terraform:
Terraform v1.1.4
 - Provider(s):
hashicorp/cloudinit v2.2.0.
hashicorp/aws v3.74.0...
hashicorp/kubernetes v2.7.1...
hashicorp/helm v2.4.1...
hashicorp/tls v3.1.0...
 - Module:
registry.terraform.io/terraform-aws-modules/eks/aws 18.3.0 for eks.

## Reproduction
Use the examples provided for eks_managed_node_groups to copy and paste and adapt for my case

From complete example: [complete_main](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/complete/main.tf)

### Code Snippet to Reproduce
My snippet of code for eks managed node groups:

```
  #EKS managed node group defaults and config
  eks_managed_node_group_defaults = {
    ami_type       = "AL2_x86_64"
    key_name       = "ec2usrkey"
    disk_size      = var.eks_node_storage
    instance_types = var.kubernetes_worker_instance_types
  }

  eks_managed_node_groups = {
    eks-preprod-nodes = {
      min_size     = 2
      max_size     = 10
      desired_size = 2
      capacity_type  = "ON_DEMAND"
      labels = local.tags

      update_config = {
        max_unavailable_percentage = 50 # or set `max_unavailable`
      }

      tags = local.tags
    }
  }

```

## Expected behavior
Create EKS and EKS managed nodes with Volume with the size specified in configuration.

## Actual behavior
All the EC2 node are created with Volume of 20 GiB.

### Terminal Output Screenshot(s)
I am happy to provide a screenshot but not sure what is required.

## Additional context
I read somewhere that I could set create_launch_template=false, but it fails on the oidc with saying launch template couldn't be found, so it never creates the eks node group, but my understanding that with that option set to false it won't create a custom template and EKS will create it's own but seems to have a racing condition.

Error:
```
module.eks.aws_eks_cluster.this[0]: Creation complete after 13m35s [id=test-eks-cluster]
module.eks.data.tls_certificate.this[0]: Reading...
data.aws_eks_cluster.cluster: Reading...
data.aws_eks_cluster_auth.cluster: Reading...
data.aws_eks_cluster_auth.cluster: Read complete after 0s [id=test-eks-cluster]
module.eks.module.eks_managed_node_group["eks-nodes"].aws_eks_node_group.this[0]: Creating...
module.eks.data.tls_certificate.this[0]: Read complete after 1s [id=2022-02-04 12:36:14.542695416 +0000 UTC]
module.eks.aws_iam_openid_connect_provider.oidc_provider[0]: Creating...
data.aws_eks_cluster.cluster: Read complete after 1s [id=test-eks-cluster]
module.eks.aws_iam_openid_connect_provider.oidc_provider[0]: Creation complete after 0s [id=arn:aws:iam::862914874889:oidc-provider/oidc.eks.eu-west-2.amazonaws.com/id/CEAD64ECDD11294AF849D109B8DDDA1C]
╷
│ Error: error creating EKS Node Group (test-eks-cluster:eks-nodes-2022020412361450260000000b): InvalidParameterException: Launch template could not be found : The specified launch template, with template name eks-nodes, does not exist.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "99fd46e9-76f5-4fa3-98be-1397653768d5"
│   },
│   Message_: "Launch template could not be found : The specified launch template, with template name eks-nodes, does not exist."
│ }

```

Thank in advance.

**Comment by bryantbiggs** [comment]
please see https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L96-L100

**Comment by nmofonseca** [comment]
@bryantbiggs  first of all thank you so much for replying me and so quickly.

I should have mentioned that I wanted to find a way to specify the size using the custom launch template the module creates by default

```hcl
      create_launch_template = false
      launch_template_name   = ""
```

But now I understand that will trigger the module to create EKS using EKS own launch templates which loses a bunch of things I have set like the ssh key, tags and the additional security group.

Regardless of that I did found the answer to my question on the complete eks managed group down on the file you sent me L250-263

```hcl
      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 75
            volume_type           = "gp3"
            iops                  = 3000
            throughput            = 150
            encrypted             = true
            kms_key_id            = aws_kms_key.ebs.arn
            delete_on_termination = true
          }
        }
      }

```
I really don't know what happened but the example I was reading before opening the issue didn't looked the same as it looks now because I clearly didn't read that before.

Now onto my next point which is adding an existing IAM role to be able to manage the cluster via kubectl, I will give a look at the example again but if you know where I can check one I will truly appreciate

**Comment by nmofonseca** [comment]
I have found both things I was looking after on the complete examples so I am closing the issue.

Thank you so much for the work the maintainers do and for this great module :) and again a bit thank you to @bryantbiggs  that helped me figure out where my issue was.

**Comment by bryantbiggs** [comment]
for which node group? you have two listed

**Comment by cthiebault** [comment]
I'm not sure if I understand: I thought I had defined only `test` node group :-/

I thought that `eks_managed_node_groups.default_node_group` was only there to override default EKS managed group config...

In fact, do I need to define this `eks_managed_node_groups.default_node_group`?

**Comment by nmofonseca** [comment]
@cthiebault  My reading of this is  that eks_managed_node_groups.default_node_group is just considered a default node group but is a separate node group for test.

Test node group won't get what you configured, on my case I ended up like this:



```tf
 #EKS managed node group defaults and config
  eks_managed_node_group_defaults = {
    ami_type       = "AL2_x86_64"
    key_name       = "mykey"
    instance_types = var.kubernetes_worker_instance_types
  }

  eks_managed_node_groups = {
    eks-nodes = {
      min_size      = var.eks_min_nodes
      max_size      = var.eks_max_nodes
      desired_size  = var.eks_desired_nodes
      capacity_type = "ON_DEMAND"
      labels        = local.tags

      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = var.eks_node_storage
            volume_type           = "gp3"
            iops                  = 3000
            throughput            = 150
            encrypted             = true
            kms_key_id            = aws_kms_key.ebskey.arn
            delete_on_termination = true
          }
        }
      }


      update_config = {
        max_unavailable_percentage = 50 # or set `max_unavailable`
      }

      tags = local.tags
    }
  }

  tags = local.tags
}
```

This will create nodes with the root volume of the size I specify on var.eks_node_storage.

**Comment by cthiebault** [comment]
Thanks for your help @nmofonseca!

I used a setup like yours and I still get 2 volumes attached to my test node :-(
- `/dev/xvda`: 50GB gp3 encrypted
- `/dev/xvdb`: 20GB gp2 not encrypted

```terraform
  eks_managed_node_group_defaults = {
    ami_type              = "BOTTLEROCKET_x86_64"
    platform              = "bottlerocket"
    instance_types        = [ "t3.medium" ]
    disk_size             = 50
    block_device_mappings = {
      xvda = {
        device_name = "/dev/xvda"
        ebs         = {
          volume_size           = 50
          volume_type           = "gp3"
          iops                  = 3000
          throughput            = 150
          encrypted             = true
          delete_on_termination = true
        }
      }
    }
  }

  eks_managed_node_groups = {
    test = {
      labels       = { env = "test" }
      min_size     = 1
      max_size     = 2
      desired_size = 1
    }
  }
```

**Comment by Mgonand** [comment]
I'm in the same page than you @cthiebault .
I think you should use:
```
 create_launch_template = false
 launch_template_name  = ""
```
like this:
```terraform
  eks_managed_node_group_defaults = {
    ami_type              = "BOTTLEROCKET_x86_64"
    platform              = "bottlerocket"
    instance_types        = [ "t3.medium" ]
    disk_size             = 50
    block_device_mappings = {
      xvda = {
        device_name = "/dev/xvda"
        ebs         = {
          volume_size           = 50
          volume_type           = "gp3"
          iops                  = 3000
          throughput            = 150
          encrypted             = true
          delete_on_termination = true
        }
      }
    }
  }

  eks_managed_node_groups = {
    test = {
      create_launch_template = false
      launch_template_name  = ""
      labels       = { env = "test" }
      min_size     = 1
      max_size     = 2
      desired_size = 1
    }
  }
```

with that kind of configuration I get the right disk size but I get a misconfiguration with the security groups of the nodes, just the cluster security group is assigned to the instances instead of the node security group, so be aware of that. I'm still looking for a cleaner option.

**Comment by chiting** [comment]
> Thanks for your help @nmofonseca!
> 
> I used a setup like yours and I still get 2 volumes attached to my test node :-(
> 
>     * `/dev/xvda`: 50GB gp3 encrypted
> 
>     * `/dev/xvdb`: 20GB gp2 not encrypted
> 
> 
> ```terraform
>   eks_managed_node_group_defaults = {
>     ami_type              = "BOTTLEROCKET_x86_64"
>     platform              = "bottlerocket"
>     instance_types        = [ "t3.medium" ]
>     disk_size             = 50
>     block_device_mappings = {
>       xvda = {
>         device_name = "/dev/xvda"
>         ebs         = {
>           volume_size           = 50
>           volume_type           = "gp3"
>           iops                  = 3000
>           throughput            = 150
>           encrypted             = true
>           delete_on_termination = true
>         }
>       }
>     }
>   }
> 
>   eks_managed_node_groups = {
>     test = {
>       labels       = { env = "test" }
>       min_size     = 1
>       max_size     = 2
>       desired_size = 1
>     }
>   }
> ```

Hello @cthiebault, you get 2 volumes because you are using the bottlerocket AMI and it comes with 2 volumes: https://github.com/bottlerocket-os/bottlerocket#default-volumes

**Comment by cthiebault** [comment]
Thanks for the info about bottlerocket @chiting! I didn't pay attention to bottlerocket AMI before switching to it :-/

**Comment by cthiebault** [comment]
To conclude, here is my configuration where I keep the default disk size, but I use encrypted `gp3` volume.

I now get 2 GP3 encrypted volumes of 2 & 20 GB...

Thanks again for the pointer @chiting :-)

```terraform
  eks_managed_node_group_defaults = {
    ami_type              = "BOTTLEROCKET_x86_64"
    platform              = "bottlerocket"
    instance_types        = [ "t3.medium" ]

    # Force gp3 & encryption (https://github.com/bottlerocket-os/bottlerocket#default-volumes)
    block_device_mappings = {
      xvda = {
        device_name = "/dev/xvda"
        ebs         = {
          volume_size           = 2
          volume_type           = "gp3"
          iops                  = 3000
          throughput            = 150
          encrypted             = true
          delete_on_termination = true
        }
      }
      xvdb = {
        device_name = "/dev/xvdb"
        ebs         = {
          volume_size           = 20
          volume_type           = "gp3"
          iops                  = 3000
          throughput            = 150
          encrypted             = true
          delete_on_termination = true
        }
      }
    }
  }

  eks_managed_node_groups = {
    test = {
      labels       = { env = "test" }
      min_size     = 1
      max_size     = 2
      desired_size = 1
    }
  }
```
