### ISSUE TITLE
Remove spot-termination event rule code, because of it doesn't work properly.

### ISSUE THREAD

**Issue by sepiro2000** [terraform-aws-modules/terraform-aws-eks#1850]
## Description

`aws.ec2` event source doesn't have an ARN of ASG, so https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa_autoscale_refresh/charts.tf#L273 code doesn't work properly. As mentioned in https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-instance-termination-notices.html `aws.ec2` event source has an ARN of ec2.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:

 - Provider(s):

 - Module:

## Additional context
I think remove spot-termination event rule code, because of it doesn't work properly.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.5.1 :tada:
