### ISSUE TITLE
nodes and pods on different subnets. pods are always snated with the node's primary interface.

### ISSUE THREAD

**Issue by shaibs3** [terraform-aws-modules/terraform-aws-eks#1853]
## Description

i am working with the eks module on version 18.2.3.
i have 1 self managed node group that runs on private subnets.
i have created eni config crds and annotated the worker nodes so that the pods running on those nodes 
will be assigned ip addresses from public subnets (based on az).
after digging into the routing tables and iptables roles, i can tell that pods running on the secondary eni ( belonging to the public subnet) will always route via the correct eni ( which is expected).
however the iptables roles make outgoing packets from those pods to do snat with the node's primary interface's ip.
that is unexpected since it makes pods belonging to a public subnet route via a private subnet.
i would expect that snat will be performed based on the interface that the packet is being transmitted.
anyway i would need your advise on that.
thanks!

**Comment by bryantbiggs** [comment]
I think you want to consult the EKS docs since this is outside the scope of this module
