### ISSUE TITLE
Fargate Instances unable to access public internet services.

### ISSUE THREAD

**Issue by DameonSmith** [terraform-aws-modules/terraform-aws-eks#1857]
## Description

I recently updated the module from `17.23.0` to `18.4.0`, and have been unable to get fargate instances to access any resources outside of the VPC. The primary security group seems to have an egress to the internet, and I tried adding my own security group rules to open it up as much as  I could for testing. However every request to the internet, fails on fargate nodes. If I launch the same container on eks managed nodes in the same cluster I can make requests to the internet without issue.

## Versions
18.4.0
 - Terraform:
1.1.3
 - Provider(s):
aws ~> 3.0

## Reproduction
Launching fargate instances in a new cluster.
Using work spaces

Launched new cluster
Setup Fargate worker node profiles
Launched pods onto those nodes.

## Expected behavior
Fargate woker nodes being able to access resources on the public internet.

## Actual behavior
Any request made to external domains or IPs fail.

**Comment by DameonSmith** [comment]
I've got 3 public subnets and 3 private that the cluster can use, the fargate and worker nodes are all in the private subnets, and I have a natgateway in the public subnets. I can reach the internet from inside the private subnets for everything but fargate. 

I tried launching an instance in the same sg that fargate should be launching into and did a reachability analysis on it and it seems to be able to reach the igw. So I'm kind of at a loss for why fargate is having an issue.

**Comment by bryantbiggs** [comment]
Fargate profiles inherit the cluster security group which is more restrictive in v18 - you'll want to add a security group to the Fargate pods to provide more egress access https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html

**Comment by DameonSmith** [comment]
I figured it out at like midnight yesterday. I actually had internet access, but no DNS traffic allowed to coredns. I had to add rules to the sg where coredns (deployed on EC2) lived, allowing ingress and egress to `cluster primary sg` where fargate was launching.

I thought I had added the appropriate sg rules with terraform originally, but they were mangled due to a terraform not being able to parse the port range data I gave it. Caused me a lot of confusion.

**Comment by FernandoMiguel** [comment]
> inherit the cluster security group

@bryantbiggs the cluster or the node sg?

**Comment by bryantbiggs** [comment]
cluster

**Comment by KevinSnyderCodes** [comment]
For completeness, here is an example of how to achieve this:

```tf
module "eks" {
  source  = "terraform-aws-modules/eks/aws"

  # ...
}

resource "aws_security_group_rule" "node_ingress_cluster_primary_security_group_all" {
  security_group_id = module.eks.node_security_group_id

  type = "ingress"

  protocol  = "-1"
  from_port = 0
  to_port   = 0

  source_security_group_id = module.eks.cluster_primary_security_group_id

  description = "Cluster primary security group to node all ports/protocols"
}
```

Change the ports and protocols to your liking.

The reason you must create the `aws_security_group_rule` outside the EKS module is because using the module's `var.node_security_group_additional_rules` causes a circular reference -- `module.eks.cluster_primary_security_group_id` as an input to `module.eks` -- which throws an error.

**Comment by FernandoMiguel** [comment]
@bryantbiggs sorry I may have missed some context of you @ me here/now.
Can you please clarify?

**Comment by bryantbiggs** [comment]
@FernandoMiguel  see https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#fargate-gs-check-compatibility

**Comment by FernandoMiguel** [comment]
@bryantbiggs we got our fargate nodes working fine. Have had for months now (minus clingy issues with coredns).

**Comment by bryantbiggs** [comment]
> @bryantbiggs we got our fargate nodes working fine. Have had for months now (minus clingy issues with coredns).

ok great. Just clarifying the statements above for others that come here - modifying node security groups do not affect Fargate profiles

**Comment by FernandoMiguel** [comment]
> > @bryantbiggs we got our fargate nodes working fine. Have had for months now (minus clingy issues with coredns).
> 
> ok great. Just clarifying the statements above for others that come here - modifying node security groups do not affect Fargate profiles

Well aware, thanks.
Didn't make any sense to me/us when we first started, but we learned.
Still think it makes no sense to use control plane SGs for worker nodes but aws....
