### ISSUE TITLE
Resource "null_resource" "wait_for_cluster" taking forever to create hence breaking the apply process

### ISSUE THREAD

**Issue by thedusansky** [terraform-aws-modules/terraform-aws-eks#1858]
Dear team, 

I am trying to create an EKS cluster with the private-only access. 
  
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false

However, during the apply process, the resource "null_resource" "wait_for_cluster" is looping the 'still creating' status until it's timed out after 1 hour. I believe this is the same scenario as - https://stackoverflow.com/questions/65263317/unable-to-create-eks-cluster-when-deploying-to-private-subnets
This resource has local-exec provisioner which is running the commands locally and trying to access the cluster EP:

resource "null_resource" "wait_for_cluster" {
  count = var.create_eks && var.manage_aws_auth ? 1 : 0

  depends_on = [
    aws_eks_cluster.this[0],
    aws_security_group_rule.cluster_private_access,
  ]

  provisioner "local-exec" {
    command     = var.wait_for_cluster_cmd
    interpreter = var.wait_for_cluster_interpreter
    environment = {
      ENDPOINT = aws_eks_cluster.this[0].endpoint
    }
  }
}

variable "wait_for_cluster_cmd" {
  description = "Custom local-exec command to execute for determining if the eks cluster is healthy. Cluster endpoint will be available as an environment variable called ENDPOINT"
  type        = string
  default     = "for i in `seq 1 60`; do if `command -v wget > /dev/null`; then wget --no-check-certificate -O - -q $ENDPOINT/healthz >/dev/null && exit 0 || true; else curl -k -s $ENDPOINT/healthz >/dev/null && exit 0 || true;fi; sleep 5; done; echo TIMEOUT && exit 1"
}

variable "wait_for_cluster_interpreter" {
  description = "Custom local-exec command line interpreter for the command to determining if the eks cluster is healthy."
  type        = list(string)
  default     = ["/bin/sh", "-c"]
}

The thing is I'm running a terraform code on GitLab pipeline (in an environment that is not in the same VPC as the cluster), could it be that it's getting stuck because it can't access the cluster from the outside then? 
Is there a way to create a cluster with private only EP and subnets from the GitLab environment like in my case? 

Thank you! 

## Versions
 - Terraform: 0.13.7
 - Provider(s): aws: 2.64.0
 - Module: https://github.com/terraform-aws-modules/terraform-aws-eks

## Expected behavior
Apply complete successfully

## Actual behavior
Apply process broken, loop creation of null resource 

### Terminal Output Screenshot(s)
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [47m10s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [47m20s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [47m30s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [47m40s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [47m50s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [48m0s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [48m10s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [48m20s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [48m30s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [48m40s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [48m50s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [49m0s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [49m10s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [49m20s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [49m30s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [49m40s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [49m50s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [50m0s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [50m10s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [50m20s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [50m30s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [50m40s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [50m50s elapsed]
module.eks[0].null_resource.wait_for_cluster[0]: Still creating... [51m0s elapsed]
WARNING: Timed out waiting for the build to finish
ERROR: Job failed: execution took longer than 1h0m0s seconds

**Comment by bryantbiggs** [comment]
This is outside the scope of this module - however, yes you can create a cluster with only private endpoint enabled, you just need to remove any resources that are trying to use that endpoint from a non-private location (I.e. - local exec will not work unless the entity running the plan/apply has private network access connectivity)
