### ISSUE TITLE
Confusing security group assignment for self managed nodes

### ISSUE THREAD

**Issue by IvanDechovsky** [terraform-aws-modules/terraform-aws-eks#1859]
## Description
When configuring a custom security group for self managed nodes, you have two variables in the root module:
```
create_node_security_group       = false
node_security_group_id           = aws_security_group.self_managed_nodes.id
```
With this set, I would expect that security group to be attached to the nodes. However, if i follow the variable in the module, I see it gets assigned to the local in `node-groups.tf`
```
node_security_group_id = local.create_node_sg ? aws_security_group.node[0].id : var.node_security_group_id
```
but that local is not used anywhere. More specifically, I would expect that it is passed in [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/43822aff06ffa7ab38f281422a3c5663e4e0b061/node_groups.tf#L408) in `vpc_security_group_ids`.

Currently, to make it work I need to set the two root variables like above and  also
```
  self_managed_node_group_defaults = {
    vpc_security_group_ids                   = [aws_security_group.self_managed_nodes.id]
    ....
    }
```

Is this intended? I think, it would be nice if I didn't also have to set it in the `defaults` of the node groups.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.5.1 :tada:
