### ISSUE TITLE
v18 cluster with private AND public access enabled is not reachable from a bastion host

### ISSUE THREAD

**Issue by schealex** [terraform-aws-modules/terraform-aws-eks#1863]
## Description

I'm using a eks cluster based upon [examples/eks_managed_node_group](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/README.md) and have not changed the security at all. I'm having 

```tf
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true
```

and the cluster was able to be created and is able to be updated from my local machine using the cluster endpoint.
In our CI pipeline which runs on a gitlab runner within the SAME VPC and private subnet i am not able to reach that endpoint. I than tried to curl the address from our bastion host (also on the same vpc) and the address is not able to be reached.

Please help as this is currently blocking a deployment.

PS: the nodes and pods don't seem to have a problem reaching the API

## Versions

 - Terraform: v0.14.11
 - Provider(s):
+ provider registry.terraform.io/gavinbunney/kubectl v1.13.1
+ provider registry.terraform.io/hashicorp/aws v3.72.0      
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0 
+ provider registry.terraform.io/hashicorp/external v2.2.0  
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/mumoshu/helmfile v0.14.1
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Expected behavior

Be able to reach the cluster from inside the same VPC

## Actual behavior

Not able to reach the cluster from inside the same VPC

**Comment by schealex** [comment]
after some more digging i found that you can supply `cluster_additional_security_group_ids` which leads to the module allowing access via 443 for all the groups. Does that mean you have to supply the vpc's sg to this by default?

**Comment by schealex** [comment]
ok i can acutally confirm that passing in the relevant sgs into that param does fix it. This is new in v18 as my v17 cluster did not need this to work the same way.
Now i'm facing the problem that if i add them in terraform it forces a cluster replacement. Is there a way to tell terraform to use the changes i made in aws directly?

**Comment by bryantbiggs** [comment]
please see the [upgrade guide](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/UPGRADE-18.0.md) and documentation on security group improvements https://github.com/terraform-aws-modules/terraform-aws-eks#security-groups
