### ISSUE TITLE
Creation of cluster and coredns addon timesout after 20 mins

### ISSUE THREAD

**Issue by kaykhancheckpoint** [terraform-aws-modules/terraform-aws-eks#1868]
## Description

When creating eks cluster and the addons, creation of coredns causes time out after 20 mins. apparently this should have been fixed in the latest version?

https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1801#issuecomment-1031894770

## Versions

 - Terraform:  `v1.1.5`

 - Provider(s):
```
+ provider registry.terraform.io/hashicorp/aws v4.0.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

 - Module: latest

## Reproduction

```
terraform init
terraform apply
```

### Code Snippet to Reproduce
```
locals {
  workspace       = terraform.workspace
  name            = "${var.org_name}-${terraform.workspace}-k8s"
  cluster_version = "1.21"
  region          = var.region

  tags = {
    Example    = local.name
    GithubRepo = "terraform-aws-eks"
    GithubOrg  = "terraform-aws-modules"
  }
}


module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"

  cluster_name                    = local.name
  cluster_version                 = local.cluster_version
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }



  vpc_id     = data.terraform_remote_state.networking.outputs.vpc_id
  subnet_ids = concat(data.terraform_remote_state.networking.outputs.public_subnets, data.terraform_remote_state.networking.outputs.private_subnets)

  # Extend cluster security group rules
  cluster_security_group_additional_rules = {
    egress_nodes_ephemeral_ports_tcp = {
      description                = "To node 1025-65535"
      protocol                   = "tcp"
      from_port                  = 1025
      to_port                    = 65535
      type                       = "egress"
      source_node_security_group = true
    }
  }

  # Extend node-to-node security group rules
  node_security_group_additional_rules = {
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
  }

  eks_managed_node_group_defaults = {
    ami_type  = "AL2_x86_64"
    disk_size = 50
  }

  eks_managed_node_groups = {
    worker_group = {
      name           = "worker-group"
      min_size       = 2
      max_size       = 10
      desired_size   = 2
      instance_types = ["m5.large"]
      capacity_type  = "ON_DEMAND"

      bootstrap_extra_args = "--kubelet-extra-args '--node-labels=geeiq/node-type=worker'"

      update_config = {
        max_unavailable_percentage = 50
      }

      labels = {
        Environment = "test"
        GithubRepo  = "terraform-aws-eks"
        GithubOrg   = "terraform-aws-modules"
      }

      taints = [
        {
          key    = "dedicated"
          value  = "gpuGroup"
          effect = "NO_SCHEDULE"
        }
      ]

      tags = {
        ExtraTag = "example"
      }
    }
  }
}
```

## Expected behavior

Expect cluster and addons (coredns) to be successfully created

## Actual behavior

apply  fails with timeout, coredns not created and shows Degraded on aws dashboard

### Terminal Output Screenshot(s)
![image](https://user-images.githubusercontent.com/65535942/153635444-273fb8a5-af06-43f6-9ec6-550484d8f26f.png)

## Additional context

1. I tried to create the cluseter including addons from scratch
2. I tried to create the cluster first without addons and then add the addons to the module eks and apply. 

- in both situations i ran into the same problem.

**Comment by bryantbiggs** [comment]
you have one node group shown above and it has taints on that node group - it looks like you are blocking the coredns pods (all pods really) from deploying due to this taint

**Comment by kaykhancheckpoint** [comment]
Ah i see i don't need that taint right? it seems like i left it there from the example with spot instances....

**Comment by bryantbiggs** [comment]
well if you have a taint, you need to add a toleration for pods to run on those nodes. if you had other node groups that didn't have a taint, you would be fine. however, since this is the only node group you have and it has a taint - its preventing the core service pods from coming up (coredns, vpc cni, etc.). Just remove the taint block and you should be fine

**Comment by noqureshi** [comment]
I am having a same issue with the Fargate Profile. I am not using taint but still getting the same error. 

![image](https://user-images.githubusercontent.com/87381210/178149364-5c80fc2d-322b-46a0-bf19-77d9dff87ea3.png)

`
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"

  cluster_name    = var.CLUSTER_NAME
  cluster_version = "1.22"

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  cluster_enabled_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]

  cluster_addons = {
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }

  cluster_encryption_config = [{
    provider_key_arn = aws_kms_key.eks.arn
    resources        = ["secrets"]
  }]

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  # Fargate Profile(s)
  fargate_profiles = {
    coredns-fargate-profile = {
      name = "coredns"
      selectors = [
        {
          namespace = "kube-system"
        },
        {
          namespace = "default"
        },
        {
          namespace = var.ARGOCD_NAME_SPACE
        },
      ]
      pod_execution_role_arn = aws_iam_role.pod-execution-role.arn
      service_account_name   = local.k8s_service_account_name
      subnets                = module.vpc.private_subnets
    }
  }
}

resource "aws_eks_addon" "coredns" {
  addon_name        = "coredns"
  addon_version     = "v1.8.7-eksbuild.1"
  cluster_name      = var.CLUSTER_NAME
  resolve_conflicts = "OVERWRITE"
  depends_on        = [module.eks]
}
`

**Comment by bryantbiggs** [comment]
Fargate only clusters require an update to CoreDNS which is not available via the AWS API currently - you can see an example here https://github.com/clowdhaus/eks-reference-architecture/tree/main/serverless/us-east-1

**Comment by booleanbetrayal** [comment]
Just ran into this as well in a Fargate-only cluster. Failed after 20m timeout, but succeeds quickly on re-run. Is there a Terraform-friendly way of working around this issue at this point?

**Comment by Dean-MMT** [comment]
I've run into the same issue in a fargate-only cluster (not related to any taints). Would be interested to see if anyone has a work-around other than re-running terraform apply.
