### ISSUE TITLE
V18 nodes are not registering to the cluster

### ISSUE THREAD

**Issue by andrewhadji-michael** [terraform-aws-modules/terraform-aws-eks#1872]
Hi.

I have been battling with this problem all week now. First with the v17 of this module and now with v18.

I have copy and pasted the example code from here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/self_managed_node_group/main.tf modified it only slightly.

I have two issues:

This part of the example I get a message "complete is not expected here"

    # Complete
    complete = {
      name            = "complete-self-mng"
      use_name_prefix = false

So I changed it too:

  # Complete
  eks_managed_node_groups = {
    spot = {
      name            = "complete-eks-mng"
      use_name_prefix = true

and the code runs.

However there is something wrong as I end up with two autoscaling groups one called complete-eks-mng and one called tags.

However neither of these nodes finish provisionging to the cluster:

module.eks.module.eks_managed_node_group["spot"].aws_eks_node_group.this[0]: Still creating... [23m0s elapsed]
╷
│ Error: error waiting for EKS Node Group (andrew-test:complete-eks-mng-2022021214372681580000001c) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:
│ 	* i-084c5f36bba9e50e7: NodeCreationFailure: Instances failed to join the kubernetes cluster
│ 
│ 
│ 
│   with module.eks.module.eks_managed_node_group["spot"].aws_eks_node_group.this[0],
│   on .terraform/modules/eks/modules/eks-managed-node-group/main.tf line 269, in resource "aws_eks_node_group" "this":
│  269: resource "aws_eks_node_group" "this" {
│ 
╵
╷
│ Error: error waiting for EKS Node Group (andrew-test:tags-2022021214372681250000001a) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:
│ 	* i-0a8c1482d8281915f: NodeCreationFailure: Instances failed to join the kubernetes cluster
│ 
│ 
│ 
│   with module.eks.module.eks_managed_node_group["tags"].aws_eks_node_group.this[0],
│   on .terraform/modules/eks/modules/eks-managed-node-group/main.tf line 269, in resource "aws_eks_node_group" "this":
│  269: resource "aws_eks_node_group" "this" {

My code can be found here:

https://github.com/andrewhadji-michael/tf-eks

I do not know why I cannot get the nodes to register with the cluster.

**Comment by andrewhadji-michael** [comment]
OK, so I took the example here: https://raw.githubusercontent.com/terraform-aws-modules/terraform-aws-eks/v18.6.0/examples/eks_managed_node_group/main.tf made the smallest modifications too it to get it to run and I still have the same issues the node groups do not finsh provisioning. 

Out of the box the example code does not work I am afraid. I had the same issue with v17 of this module as well.

You can see my code here: https://github.com/andrewhadji-michael/tf-eks

file: managed-node-groups-copied-as-is.tf

**Comment by andrewhadji-michael** [comment]
Tell me something that really confuses me. Do we need vpc endpoints in the private subnets?

The nacls are open inbound and outbound 0.0.0.0/0, we have  nat gateways in the public subnets and the route tables all have entries in the private subnet but still the nodes are not provisioning.

**Comment by bryantbiggs** [comment]
its very difficult to follow what you are doing or trying to do. I can tell you though, the examples provided in this repository do work

**Comment by andrewhadji-michael** [comment]
> OK, so I took the example here: https://raw.githubusercontent.com/terraform-aws-modules/terraform-aws-eks/v18.6.0/examples/eks_managed_node_group/main.tf made the smallest modifications too it to get it to run and I still have the same issues the node groups do not finsh provisioning.
> 
> Out of the box the example code does not work I am afraid. I had the same issue with v17 of this module as well.
> 
> You can see my code here: https://github.com/andrewhadji-michael/tf-eks
> 
> file: managed-node-groups-copied-as-is.tf

Please run this and you will e they dont.

**Comment by bryantbiggs** [comment]
> > OK, so I took the example here: [`v18.6.0`/examples/eks_managed_node_group/main.tf (raw)](https://raw.githubusercontent.com/terraform-aws-modules/terraform-aws-eks/v18.6.0/examples/eks_managed_node_group/main.tf) made the smallest modifications too it to get it to run and I still have the same issues the node groups do not finsh provisioning.
> > Out of the box the example code does not work I am afraid. I had the same issue with v17 of this module as well.
> > You can see my code here: [andrewhadji-michael/tf-eks](https://github.com/andrewhadji-michael/tf-eks)
> > file: managed-node-groups-copied-as-is.tf
> 
> Please run this and you will see they dont.
> 
> (All the nodes groups just failed to provision)
> 
> I am running out of ideas now, becuase honesly if you look ay my code it is a 99% copy paste.

Your code won't work - its completely invalid. You have the same resource/module names in two different files in the same directory - Terraform won't even do a plan due to conflicts

**Comment by andrewhadji-michael** [comment]
> > > OK, so I took the example here: [`v18.6.0`/examples/eks_managed_node_group/main.tf (raw)](https://raw.githubusercontent.com/terraform-aws-modules/terraform-aws-eks/v18.6.0/examples/eks_managed_node_group/main.tf) made the smallest modifications too it to get it to run and I still have the same issues the node groups do not finsh provisioning.
> > > Out of the box the example code does not work I am afraid. I had the same issue with v17 of this module as well.
> > > You can see my code here: [andrewhadji-michael/tf-eks](https://github.com/andrewhadji-michael/tf-eks)
> > > file: managed-node-groups-copied-as-is.tf
> > 
> > 
> > Please run this and you will see they dont.
> > (All the nodes groups just failed to provision)
> > I am running out of ideas now, becuase honesly if you look ay my code it is a 99% copy paste.
> 
> Your code won't work - its completely invalid. You have the same resource/module names in two different files in the same directory - Terraform won't even do a plan due to conflicts

Use the file called: managed-node-groups-copied-as-is.tf

**Comment by bryantbiggs** [comment]
but what are you trying to achieve here?

**Comment by andrewhadji-michael** [comment]
> but what are you trying to achieve here?

I want to proved I can deploy a working cluster

**Comment by bryantbiggs** [comment]
you should start with the bare minimum and understand what it is exactly that you are deploying:

```hcl
provider "aws" {
  region = local.region
}

locals {
  name            = "example"
  cluster_version = "1.21"
  region          = "us-east-2"

  tags = {
    Example    = local.name
  }
}

################################################################################
# EKS Module
################################################################################

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.6.0"

  cluster_name                    = local.name
  cluster_version                 = local.cluster_version

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  eks_managed_node_groups = {
    default = {}
  }

  tags = local.tags
}

################################################################################
# Supporting Resources
################################################################################

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 3.0"

  name = local.name
  cidr = "10.0.0.0/16"

  azs             = ["${local.region}a", "${local.region}b", "${local.region}c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]

  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true

  public_subnet_tags = {
    "kubernetes.io/cluster/${local.name}" = "shared"
    "kubernetes.io/role/elb"              = 1
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.name}" = "shared"
    "kubernetes.io/role/internal-elb"     = 1
  }

  tags = local.tags
}
```

**Comment by andrewhadji-michael** [comment]
OK so given the simplified code you kindly gave me, I can report that as of now the node group is still in the process of creating:

module.eks.module.eks_managed_node_group["default"].aws_eks_node_group.this[0]: Still creating... [10m20s elapsed]

I expect it will time out eventually.

At this point I am wondering if the company aws account I am working in has some sort of security policies on it that is restricting these activities as this is crazy.

I am going to try your example code against my own personal account just to verify its behaviour.

Thanks

**Comment by andrewhadji-michael** [comment]
OK, in my own personal account the tf script finished succesfully.

How do I generate the kubeconfig to access the cluster?

I will be back on this again tomorrow as I now need to make this work for a node group comprised of spot instances so expect more questions tomorrow! :)

But thanks for your help.

It seems there is some oddity about the company aws account I have been trying to use. ¯\_(ツ)_/¯

**Comment by andrewhadji-michael** [comment]
OK, very good news. I just tried it again this time in the eu-west-2 region in my company account and it worked!

I dont have a kubeconfig yet so I can see if the node is actually registered but TF completed with no issues!

So tomorrow I just have to add the rest of the bits to the module.

Thanks for your help so far. I am sure I will have lots of questions.

**Comment by andrewhadji-michael** [comment]
Thanks your your help. I understand this s not technical support! :)

I think I have managed to figure out how to get access to that output variable like so:

module.eks.eks_managed_node_groups.spot_pool.iam_role_arn

One suggestion I would make is you guys should add a new example called basic.tf or simple.tf like what you provided me yesterday as that woul help alot of people get off the ground quickly. The current examples are very dense.

**Comment by bryantbiggs** [comment]
The current examples fulfill two primary functions currently:
1) Provide a means of testing/validating changes to the module
2) Provide users a reference of the different configuration possibilities

What we do NOT provide is:
- How to Terraform
- How to EKS

**Comment by bryantbiggs** [comment]
closing issue for now with resolution steps above

**Comment by andrewhadji-michael** [comment]
Thanks again. You helped me out more than you realise!
