### ISSUE TITLE
Looking for IAM policy for creating EKS clusters

### ISSUE THREAD

**Issue by darnone** [terraform-aws-modules/terraform-aws-eks#1873]
## Description

The "docs" folder in ht repo is missing. There is a reference to a iam policy document for EKS that is not found at this link: https://discuss.hashicorp.com/t/eks-cluster-not-destroyed-completely-getting-error-unauthorized/18569

the page comes up 403 and the docs folder is missing entirely.

Short of that, I have been been searching for a minimum policy for eks cluster creation. Is it possible for anyone to post something here?

**Comment by bryantbiggs** [comment]
The policy is highly dependent on what configuration you are trying to provision. My recommendation would be to use a tool like https://github.com/iann0036/iamlive that will generate the policy based on the API calls used when creating your cluster
