### ISSUE TITLE
Deployment of EKS managed node group gives deprecation warning from self-managed-node-group

### ISSUE THREAD

**Issue by ekakela** [terraform-aws-modules/terraform-aws-eks#1874]
## Description

I am using the latest version of module with   ```
eks_managed_node_groups = {
    primary = {
      min_size     = 2
      max_size     = 4
      desired_size = 2

      instance_types = ["t3.large"]
      capacity_type  = "ON_DEMAND"
      labels = {
        customer_name = var.customer_name
      }
    }
  }
}
```

But terraform apply complains always on the apply that 

```

│ Warning: Argument is deprecated
│
│   with module.EKS-Cluster.module.eks.module.self_managed_node_group.aws_autoscaling_group.this,
│   on .terraform/modules/EKS-Cluster.eks/modules/self-managed-node-group/main.tf line 392, in resource "aws_autoscaling_group" "this":
│  392:   tags = concat(
│  393:     [
│  394:       {
│  395:         key                 = "Name"
│  396:         value               = var.name
│  397:         propagate_at_launch = true
│  398:       },
│  399:       {
│  400:         key                 = "kubernetes.io/cluster/${var.cluster_name}"
│  401:         value               = "owned"
│  402:         propagate_at_launch = true
│  403:       },
│  404:       {
│  405:         key                 = "k8s.io/cluster/${var.cluster_name}"
│  406:         value               = "owned"
│  407:         propagate_at_launch = true
│  408:       },
│  409:     ],
│  410:     var.propagate_tags,
│  411:     [for k, v in var.tags :
│  412:       {
│  413:         key                 = k
│  414:         value               = v
│  415:         propagate_at_launch = true
│  416:       }
│  417:     ]
│  418:   )
│
│ Use tag instead
```


## Versions
 - Terraform: Terraform v1.1.5
 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v4.0.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.8.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

 - Module: Latest

## Reproduction
Deploy EKS cluster with eks_managed_node_group


## Expected behavior
Should not give warnings on self_managed_node group when using eks_managed_node_Group

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.6.1 :tada:
