### ISSUE TITLE
Deploying managed node group with default user_data template fails - Ec2LaunchTemplateInvalidConfiguration: User data was not in the MIME multipart format.

### ISSUE THREAD

**Issue by idan-gur** [terraform-aws-modules/terraform-aws-eks#1875]
## Description

While trying to deploy a completely [private EKS cluster](https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html),
when adding the `enable_bootstrap_user_data = true` option to add the necessary flags to the bootstrap.sh script the apply fails.

## Versions

 - Terraform: 1.1.5

 - Provider(s): AWS 3.71.0

 - Module: 18.x

## Reproduction

- Create a managed node group EKS (platform linux) 
- Add the `enable_bootstrap_user_data = true` flag
- Run plan

### Code Snippet to Reproduce
```
eks_managed_node_groups = {
	  main_node_group = {
		    name = "***"
		    
		    enable_monitoring      = false
		    create_launch_template = true
		    ebs_optimized          = true
		    desired_capacity       = 1
		    max_capacity           = 1
		    min_capacity           = 1
		    
		    vpc_security_group_ids  = []
		    
		    disk_size       = 100
		    
		    instance_types = ["r5.xlarge"]
		    ami_type       = "AL2_x86_64" # "BOTTLEROCKET_ARM_64" "AL2_ARM_64"
		    public_ip      = false
		    
		    # Bootstrap data
		    enable_bootstrap_user_data = true
	}
}
```

## Expected behavior
Apply ran successfully

## Actual behavior
```
╷
│ Error: error waiting for EKS Node Group (***) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:
│ 	* : Ec2LaunchTemplateInvalidConfiguration: User data was not in the MIME multipart format.
│ 
│ 
│ 
│   with module.eks.module.eks.module.eks_managed_node_group["***"].aws_eks_node_group.this[0],
│   on .terraform/modules/eks.eks/modules/eks-managed-node-group/main.tf line 269, in resource "aws_eks_node_group" "this":
│  269: resource "aws_eks_node_group" "this" {
│ 
╵
```

## Additional context
I think this is due to the _user_data module not using cloudinit_config when the `enable_bootstrap_user_data` is set.

**Comment by bryantbiggs** [comment]
the MIME multipart is only required when using EKS managed node groups and NOT supplying a custom AMI (i.e. - no value provided for `ami_id`)

**Comment by idan-gur** [comment]
@bryantbiggs 
Well I don't have an `ami_id` here, I just supplied the `ami_type` which as I understand is not the same as supplying a custom AMI, please correct me if I'm wrong

**Comment by bryantbiggs** [comment]
ah my apologies, I mis-read `ami_type` and thought `ami_id` - the `enable_bootstrap_user_data` doesn't do anything in this case and isn't required in your config. why do you suggest the issue is with the MIME multipart user data (or user data at all)?

**Comment by idan-gur** [comment]
Well I have managed to deploy this exact configuration and managed node group and it works great without the `enable_bootstrap_user_data`, But here I must configure the EKS nodes with the `bootstrap.sh` script to use the CA and Endpoint flags for it to work in a private (no egress only VPCe) environment. 

> For Linux and Windows nodes, you must include bootstrap arguments when launching self-managed nodes. This text 
> bypasses the Amazon EKS introspection and doesn't require access to the Amazon EKS API from within the VPC. Replace <api-server-endpoint> and <certificate-authority> with the values from your Amazon EKS cluster.
> 
>     For Linux nodes:
> 
> 	--apiserver-endpoint <api-server-endpoint> --b64-cluster-ca <certificate-authority>
> 
> For additional arguments, see the [bootstrap script](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh)
> 
> on GitHub.
> 
> For Windows nodes:
> 
>     -APIServerEndpoint <api-server-endpoint> -Base64ClusterCA <certificate-authority>
> 
>     For additional arguments, see [Amazon EKS optimized Windows AMI](https://docs.aws.amazon.com/eks/latest/userguide/eks-custom-ami-windows.html).

**Comment by idan-gur** [comment]
Oh shit, please don't tell me it's only needed for self-managed nodes why have I missed that in the docs, I wanna cry 🤠

**Comment by bryantbiggs** [comment]
> Oh shit, please don't tell me it's only needed for self-managed nodes why have I missed that in the docs, I wanna cry cowboy_hat_face

yessir! the EKS managed node group service will set this for you (unless you provide an `ami_id`, then you need to enable the `enable_bootstrap_user_data` for this reason)
