### ISSUE TITLE
AWS provider v4.0.0 deprecated the use of `tags` in favor of the `tag` block in aws_autoscaling_group

### ISSUE THREAD

**Issue by romogo17** [terraform-aws-modules/terraform-aws-eks#1876]
On [v4.0.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.0.0) of the AWS Provider, `tags` was deprecated in favor of the `tag` configuration block in `aws_autoscaling_group`.
> resource/aws_autoscaling_group: The tags argument has been deprecated. All configurations using tags should be updated to use the tag argument instead (https://github.com/hashicorp/terraform-provider-aws/issues/22663)

This makes plans run against this version of the provider show this warning 
```
╷
│ Warning: Argument is deprecated
│ 
│   on .terraform/modules/self-managed-node-group/main.tf line 392, in resource "aws_autoscaling_group" "this":
│  392:   tags = concat(
│  393:     [
│  394:       {
│  395:         key                 = "Name"
│  396:         value               = var.name
│  397:         propagate_at_launch = true
│  398:       },
│  399:       {
│  400:         key                 = "kubernetes.io/cluster/${var.cluster_name}"
│  401:         value               = "owned"
│  402:         propagate_at_launch = true
│  403:       },
│  404:       {
│  405:         key                 = "k8s.io/cluster/${var.cluster_name}"
│  406:         value               = "owned"
│  407:         propagate_at_launch = true
│  408:       },
│  409:     ],
│  410:     var.propagate_tags,
│  411:     [for k, v in var.tags :
│  412:       {
│  413:         key                 = k
│  414:         value               = v
│  415:         propagate_at_launch = true
│  416:       }
│  417:     ]
│  418:   )
│ 
│ Use tag instead
╵
```

## Describe the solution you've considered
Convert this into a dynamic block and bumping the required provider version. 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9c9ac81e3a3a91d52b5341d005de80a05a2fa0e8/modules/self-managed-node-group/main.tf#L392-L418

**Comment by bryantbiggs** [comment]
duplicate #1874
