### ISSUE TITLE
kube-system services (e.g. coredns) running on 'out-of-box' nodes (create_launch_template = false) only accepts connections from the same security group

### ISSUE THREAD

**Issue by shupcode** [terraform-aws-modules/terraform-aws-eks#1877]
## Description

EKS-Managed-Node-Group config issue:

Not a bug? but I encountered an issue where if kube-system services are deployed on nodes that are created out of the box (create_launch_template=false), they only accept inbound connections from the same security group.

For e.g., my coredns service deployed on 'out-of-box' nodes will NOT accept traffic from nodes that are created with (create_launch_template=true, using extended security group rules as per the example) unless those nodes are associated with the same security group as the out-of-box node that the coredns pods are running on.

This caused my pods on the non 'out-of-box' nodes not being able to call the kubernetes DNS resolution service that is being served on the 'out-of-box' nodes.

### Fix

I had to make sure that my coredns service is deployed with (create_launch_template=false) so that it respects and follows the extended security group rules in the module config that my other nodes follow.

Alternatively, if I chose to keep my kube-system services deployed on out-of-box nodes, I will have to make sure that my other non out-of-box nodes are associated with the out-of-box security group created by AWS.

**Comment by bryantbiggs** [comment]
I don't know that we can do anything here - we've made the module default to creating custom launch templates for various reasons (theres not real downside to not go the custom launch template route, you gain a lot of standard functionality like tags and security groups, etc.). if you mix and match custom with default, I guess thats up to the user to ensure functional parity - we have no control over the EKS managed node group service and what it does
