### ISSUE TITLE
`block_device_mappings` set in  `self_managed_node_group_defaults` kept ignored

### ISSUE THREAD

**Issue by DanMaxic** [terraform-aws-modules/terraform-aws-eks#1878]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/e1a71e8ebe3be450953edf972b78476bcfdb2c10/modules/eks-managed-node-group/main.tf#L76

code\version ref: 
source          = "terraform-aws-modules/eks/aws"
version = "18.6.0"
-------------------
when defining block_device_mappings, it getting ignored dew a filter defined in that row:
```
for_each = flatten([lookup(block_device_mappings.value, "ebs", [])])
```

```
block_device_mappings = {
      xvda = {
        device_name = "/dev/xvda"
        ebs = {
          volume_size           = var.disk_size
          volume_type           = "gp3"
          iops                  = 3000
          throughput            = 150
          encrypted             = true
          delete_on_termination = true
        }
      }
    }
```
bypassing this bug: just specify to each nodegroup its block_device_mappings

**Comment by bryantbiggs** [comment]
I'm not following, what is the issue you are facing?

**Comment by DanMaxic** [comment]
the issue is, that when I defining `block_device_mapping` in the `self_managed_node_group_defaults`, the values are getting ignored, 
meaning the `block_device_mapping` got skipped when the module generates the aws_launch_template, instead it generates default gp2 volume with defualt values.
from tracing the code, it seems that this row, filters out block device map that not called "ebs"...
