### ISSUE TITLE
Need ability to depends_on for nodes in the cluster. Otherwise, during destroy, the node groups all get deleted while still needed

### ISSUE THREAD

**Issue by MatthewFagan** [terraform-aws-modules/terraform-aws-eks#1883]
Hi. We are using cert-manager with terraform-aws-eks module and aws_autoscaling_node_groups. We have the cert-manager depends_on [terraform-aws-eks.cluster_id]. That works fine during deploy. But during destroy, the worker nodes get destroyed before cert-manager, and then cert-manager cannot destroy because if needs to start a pod as part of its destroy process. So we need an output from this module that can be put in a "depends_on" clause to prevent the node groups getting deleted before other modules that depend on them.

**Comment by daroga0002** [comment]
take from those (depending on your deployment type):

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9a99689cc13147f4afc426b34ba009875a28614e/outputs.tf#L147-L163
