### ISSUE TITLE
Kubeconfig file for the cluster

### ISSUE THREAD

**Issue by jauyzed** [terraform-aws-modules/terraform-aws-eks#1887]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
A kubeconfig was being generated previously with a template existing in the templates folder but the feature was removed? 

## Describe the solution you'd like.
A kubeconfig file generated for the cluster post creation

**Comment by bryantbiggs** [comment]
you can generate the config using `aws eks update-kubeconfig --region <region-code> --name <cluster-name>` - see https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html
