### ISSUE TITLE
module version output

### ISSUE THREAD

**Issue by FernandoMiguel** [terraform-aws-modules/terraform-aws-eks#1888]
would it be possible to have the module have an output with the release?
you folks release so often that I never know what is the version we have.

I'm currently pinning like
```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"
```
but if there was an output available, i could put that as an output of our root module, and we would document version jumps.

**Comment by bryantbiggs** [comment]
unfortunately this is not easy to do - we use a bit of automation to handle our releases that are based on conventional commits and semver. have you tried looking into using the generated lockfile? if you git control your lockfile you can have a CI check that does something like `terraform init -upgrade=true` and then you can check for any git diff (i.e. - version changes are detected)

**Comment by FernandoMiguel** [comment]
For now I coded an ugly file data source that looks at the changelog.md and fetches the first set of '###'
It's ugly but it works (unless you change the layout or make typos).

But it would be great if your automation would also fill in / replace a field within outputs.tf with the release tag.
Not only just for this module, but all similar ones. 
One can dream.

**Comment by bryantbiggs** [comment]
Why wouldn't the lock file work for this? 

https://www.terraform.io/language/files/dependency-lock

**Comment by FernandoMiguel** [comment]
> Why wouldn't the lock file work for this? 
> 
> https://www.terraform.io/language/files/dependency-lock

We have a mix of Windows, Linux and mac... As far as I know, there's no way to codify which platforms to download the hashes, so it's left to us individually to run an extra lock command.

**Comment by daroga0002** [comment]
you can just pin it:

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.7.2"
......
```

**Comment by bryantbiggs** [comment]
closing for now since we won't be supporting this request
