### ISSUE TITLE
EBS volumes not in correct AZ

### ISSUE THREAD

**Issue by andrewhadji-michael** [terraform-aws-modules/terraform-aws-eks#1895]
Hi.

Hopefully someone cann help me out. Not sure if I have missed something form my configuration or not.

Apologise for asking here if it is not the right forum.

My eks config looks like this:

module "eks" {

  source  = "terraform-aws-modules/eks/aws"
  version = "18.7.2"

  cluster_name    = var.cluster_name
  cluster_version = var.cluster_version

  vpc_id                          = module.vpc.vpc_id
  subnet_ids                      = module.vpc.private_subnets
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  cluster_enabled_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]

  eks_managed_node_groups = {
    spot_pool = {
      name            = var.cluster_name
      use_name_prefix = true
      subnet_ids      = module.vpc.private_subnets

      instance_types = ["m5.xlarge", "m5.2xlarge", "m5.4xlarge", "m5.8xlarge"]
      capacity_type  = "SPOT"
      ebs_optimized  = true
      disk_size      = 100
      min_size       = 1
      max_size       = 250
      desired_size   = 1
    }
  }

  tags = {
    Name = var.cluster_name
  }
}

I am deploying a solr helm chart as well. What I am finding is that 33/40 pods seem to be ok but some of them are comlaining about this issue: node(s) had volume node affinity conflict

From my googling it seems that some of the ebs voumes might be in the wrong az.

Anyone have any ideas how I sort this out?

Have I missed something from my configuration?

**Comment by daroga0002** [comment]
This is not related to EKS module, but rather cloud provider in Kubernetes. You must setup affinity in your deployments and additionally have available nodes in those AZs.

As you using SPOT instances nodes are created in random AZs without balance (as in one AZ there can be no available resources) so I am advising you to limit particulal node group to single AZ.

**Comment by andrewhadji-michael** [comment]
OK, thank you very much. I think I know what I have to do now.

My plan is to add affinity that says if key tag 'a' then 'eu-west-2a' etc etc...
