### ISSUE TITLE
fargate only cluster , "Additional security groups" does not work properly

### ISSUE THREAD

**Issue by FernandoMiguel** [terraform-aws-modules/terraform-aws-eks#1900]
## Description

This module creates an additional SG for the cluster, besides the one EKS api creates.
But when using Fargate only cluster, seems the additional SG is not attached to fargate nodes.
The module also doesn't provide a direct way to add rules to the cluster SG.

## Versions
```
$ terraform  -v
Terraform v1.1.6
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.13.1
+ provider registry.terraform.io/hashicorp/aws v4.2.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.8.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

## Reproduction

tf init
tf apply

### Code Snippet to Reproduce
[
](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9a99689cc13147f4afc426b34ba009875a28614e/main.tf#L122)

## Expected behavior
For both these two SGs attach to the fargate nodes
![image](https://user-images.githubusercontent.com/168366/155376848-2d189c77-69da-4e82-88d5-c6e4a8efadc2.png)

## Actual behavior
Only the "Cluster security group" one does, and that one only has a rule for `self` all traffic.

**Comment by bryantbiggs** [comment]
This is a limitation of AWS - the alternative that AWS provides is security groups for pods https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html (the module nor Terraform AWS provider have the ability to change/specify security groups attached to the profiles)
