### ISSUE TITLE
Policy arn:aws:iam::***:policy/AmazonEKS_CNI_IPv6_Policy does not exist or is not attachable.

### ISSUE THREAD

**Issue by rmalenko** [terraform-aws-modules/terraform-aws-eks#1906]
Policy arn:aws:iam::***:policy/AmazonEKS_CNI_IPv6_Policy does not exist or is not attachable.

[gist](https://gist.github.com/rmalenko/16eeb30dd24ea0576140ac50af0fb6f6)

**Comment by bryantbiggs** [comment]
This is a bit of a chicken and the egg problem that I don't have a good solution for yet. However, this should get you unstuck
1. Set [`create_cni_ipv6_iam_policy = true`](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/e1a71e8ebe3be450953edf972b78476bcfdb2c10/variables.tf#L182) - this will create the policy that its complaining about missing
2. Once everything comes up, you can remove that line and go back to relying on the VPC CNI IRSA for the permissions (note: you will want to set `iam_role_attach_cni_policy = false` as well. This removes those permissions from the nodes)

Why this is a chicken vs the egg problem: when a fresh cluster is deployed, there are core services running on the nodes that are trying to perform actions. The VPC CNI is one of them - so if the permissions are not there upon cluster/node group creation, the plugin will fail to attach IPs/ENIs and the deployment fails. So we have to give the nodes the permissions to start, then we can remove those right after.

**Comment by rmalenko** [comment]
Thank you a lot!
