### ISSUE TITLE
add datasource for aws eks describe-addon-versions

### ISSUE THREAD

**Issue by awoimbee** [terraform-aws-modules/terraform-aws-eks#1908]
Relates to: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1385#issuecomment-990100231

## Is your request related to a problem? Please describe.
I manage kubernetes clusters, some deployments like `kube-proxy` are (strangely) not managed by EKS by default. 
Like, come on ! I got informed of the issue by AlertManager !

Turns out Terraform has [`aws_eks_addon`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon), but I need to give this resource `addon_version`, which I don't want to do, I just want the addon version to match the kubernetes version.

## Describe the solution you'd like.
A datasource called something like `aws_describe_addon_versions` so I don't have to call the aws cli (`aws eks describe-addon-versions --addon-name kube-proxy --query 'addons[*].addonVersions[0].addonVersion'`).
And / or I would like the ability to set `addon_version = "latest"` in `aws_eks_addon`.

## Describe alternatives you've considered.
Call the aws cli (`aws eks describe-addon-versions --addon-name kube-proxy --query 'addons[*].addonVersions[0].addonVersion'`)

EDIT: I'm so sorry, I didn't see I was on `terraform-aws-modules/terraform-aws-eks` and not `hashicorp/terraform-provider-aws`, I guess this issue is still relevant to this project, but feel free to close.

**Comment by bryantbiggs** [comment]
Requires upstream provider support https://github.com/hashicorp/terraform-provider-aws/issues/20725

**Comment by bryantbiggs** [comment]
This is a breaking change due to requiring the v4.x of the AWS provider and is scheduled for the v19.x release https://github.com/terraform-aws-modules/terraform-aws-eks/compare/master...bryantbiggs:refactor/incorporate-autoscaling-module?expand=1

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.0.0 :tada:
