### ISSUE TITLE
Node Group IAM  node group role not in OUTPUT of the terraform-aws-eks module.

### ISSUE THREAD

**Issue by leftyb** [terraform-aws-modules/terraform-aws-eks#1909]
## Description
Hi all,
I need to reference the ARN of the created role from the  "eks-managed-node-group"  module, but is not outputted from the EKS module. 

I can see that it is outputted from the "eks-managed-node-group" module,  as 

```
output "iam_role_arn" {
  description = "The Amazon Resource Name (ARN) specifying the IAM role"
  value       = try(aws_iam_role.this[0].arn, "")
}

```  

But this then is not outputted from the main EKS module, so can not be used from my main file that is including the EKS module like so:

`module "restcomm-eks" {
  source                         = "../../../../modules/eks"
   ...
}
`
## Expected behavior

To be able to reference the created node-group role ARN similar to the output of the EKS module "cluster_iam_role_arn".
Something like "node_group_iam_role_arn".

Thank you.

**Comment by bryantbiggs** [comment]
The output is there, you just have to unpack it from the output map. Here is an example where we pull all the roles out for use in the configmap output the module generates https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/outputs.tf#L169-L179

**Comment by leftyb** [comment]
This is what I do, 
But I am thinking that having it similarly outputted same as the cluster ARN is better to use.

Thanks anyway.

**Comment by bryantbiggs** [comment]
But unfortunately we cannot do that - because there is the possibility of crating multiple node groups/fargate profiles, we can't have a singular output of one IAM role

**Comment by leftyb** [comment]
OK I see,
thanks.
