### ISSUE TITLE
Odd behavior with lookups on defaults

### ISSUE THREAD

**Issue by jasonmcintosh** [terraform-aws-modules/terraform-aws-eks#191]
# I have issues setting max/min sizes.  

Min/Max sizes on  module.eks.aws_autoscaling_group.workers seem to be permanently set to 0.

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
```
 max_size              = "${lookup(var.worker_groups[count.index], "asg_max_size", local.workers_group_defaults["asg_max_size"])}"
  min_size              = "${lookup(var.worker_groups[count.index], "asg_min_size", local.workers_group_defaults["asg_min_size"])}"
```
IF I modify the code and change it to:
```
  max_size              = "${lookup(var.worker_groups[count.index], "asg_max_size", 10)}"
  min_size              = "${lookup(var.worker_groups[count.index], "asg_min_size", 2)}"
```
I see worker groups created with a max/min size.  I can ALSO do:
```
  max_size              = "${lookup(var.worker_groups[count.index], "asg_max_size", local.asg_max_size)}"
  min_size              = "${lookup(var.worker_groups[count.index], "asg_min_size", local.asg_min_size)}"
```  

## If this is a bug, how to reproduce? Please include a code sample if relevant.
module "eks" {
  source                = "terraform-aws-modules/eks/aws"
  cluster_name          = "demo"
  subnets               = ["${data.aws_subnet_ids.private.ids}"]
  vpc_id                = "${data.aws_vpc.selected.id}"
  config_output_path = "${format("%s/", pathexpand("~/.kube"))}"
  manage_aws_auth = true
  worker_group_count = "1"
  worker_groups = [
    {
      name = "base"
      instance_type = "m5.xlarge"
      asg_max_size = 10
      asg_min_size = 2
      asg_desired_capacity = 4
      ami_id = "${data.aws_ami.eks-worker.id}"
    }
  ]
}

## What's the expected behavior?
min/max sizes should be set to something other than 0.  Current method using a lookup with a default using a map element doesn't work.

## Are you able to fix this problem and submit a PR? Link here if you have already.
Not currently

## Environment details

* Affected module version:  Current 1.7.0
* OS: Mac OS X 
* Terraform version: v0.11.10

## Any other relevant info
https://github.com/hashicorp/terraform/issues/18878

Seems to be a bug in lookups that hopefully will be fixed in v12.

**Comment by max-rocket-internet** [comment]
I've never seen this issue before but there have been many changes to the lookup arrangement for the worker groups so I'm gonna close this now. Feel free to reopen if it's still an issue.
