### ISSUE TITLE
How do I set the EKS gp2 storageclass option allowVolumeExpansion to true

### ISSUE THREAD

**Issue by terms5** [terraform-aws-modules/terraform-aws-eks#1914]
Trying to find documentation on how to spin up my EKS cluster with the storage class option 'allowVolumeExpansion' to true.
I don't see it in any of the examples and when I use this module it defaults to false.

After spinning up the cluster the piece I am talking about is this:
`kubectl get storageclass

NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   
gp2 (default)   kubernetes.io/aws-ebs   Delete              WaitForFirstConsumer          false`

**Comment by daroga0002** [comment]
This is not related to module as storageclass is EKS object and is out of control from terraform and AWS itself. 

Probably as some workaround you can use kubectl patch command and local-provisioner after creating cluster

**Comment by n1vgabay** [comment]
Hi, there is any solution to this issue?

**Comment by daroga0002** [comment]
> Hi, there is any solution to this issue?


you must patch this via kubectl (or any other method) or add second storageclass. But as mentioned this is out of scope of this module
