### ISSUE TITLE
`eks_managed_node_group` example: Nodes in NotReady state due to CNI issues

### ISSUE THREAD

**Issue by saidmasoud** [terraform-aws-modules/terraform-aws-eks#1918]
## Description

When creating a cluster using the code in `/examples/eks_managed_node_group/`, the nodes fail to enter a `Ready` state. Inspecting individual nodes in the cluster suggest an issue to initialize the CNI plugin (see below)

## Versions

 - Terraform: 0.13.7

 - Provider(s):
```sh
~ cat .terraform/plugins/selections.json
{
  "registry.terraform.io/hashicorp/aws": {
    "hash": "h1:OePPETAA8BIGTCgGQ54F3oAZnOFH5lxyDdP0cyLXdU4=",
    "version": "4.3.0"
  },
  "registry.terraform.io/hashicorp/cloudinit": {
    "hash": "h1:siiI0wK6/jUDdA5P8ifTO0yc9YmXHml4hz5K9I9N+MA=",
    "version": "2.2.0"
  },
  "registry.terraform.io/hashicorp/null": {
    "hash": "h1:xhbHC6in3nQryvTQBWKxebi3inG5OCgHgc4fRxL0ymc=",
    "version": "3.1.0"
  },
  "registry.terraform.io/hashicorp/tls": {
    "hash": "h1:XTU9f6sGMZHOT8r/+LWCz2BZOPH127FBTPjMMEAAu1U=",
    "version": "3.1.0"
  }
}%
```

 - Module: 18.7.2

## Reproduction

1. Copy the files at https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/eks_managed_node_group into a modules directory
2. Change `source = ../..` to `source = "terraform-aws-modules/eks/aws"`
3. Add `name` and `region` variables to `variables.tf`, update `local.name` and `local.region` to reference vars
4. Initialize a local terraform workspace in another directory
5. Create `module` definition, pointing to module directory and adding `name` and `region` attributes
6. Run `terraform init|plan|apply`

## Expected behavior

All resources are successfully provisioned by `terraform`, and cluster is ready for use.

## Actual behavior

Most resources are successfully provisioned, but nodes end up and remain in a `NotReady` state. 

### Terminal Output Screenshot(s)

This error is repeated multiple times after running `terraform apply`:

```sh
Error: error waiting for EKS Node Group (cluster:complete-eks-mng-2022030219354854220000000f) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:
	* i-01a0b9fd76fdc4dad: NodeCreationFailure: Unhealthy nodes in the kubernetes cluster



  on .terraform/modules/eks.eks/modules/eks-managed-node-group/main.tf line 269, in resource "aws_eks_node_group" "this":
 269: resource "aws_eks_node_group" "this" {
```

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/23317181/156447568-8347d4ca-b3c8-40c5-bc2b-d00fd0c6736e.png">

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/23317181/156447638-4ebb3e2a-77ea-4129-993d-d6d9cb4f3750.png">

**Comment by bryantbiggs** [comment]
There were recent changes for this example, please try the latest as it was just validated again today and works as expected

**Comment by saidmasoud** [comment]
I destroyed and tried to re-create with version 18.8.1 and got the same result. If it helps, this was done on a fresh AWS account.

**Comment by bryantbiggs** [comment]
I've spun up the EKS managed node group example at least 4 times today without issue so I'm not sure whats different on your end

**Comment by pcwiltsey** [comment]
I had a similar issue that ended up being a security group I had disabled, thinking I would add it back later.
