### ISSUE TITLE
Managing creation of kubeconfig through local_file and passing to kubernetes provider

### ISSUE THREAD

**Issue by poojaac** [terraform-aws-modules/terraform-aws-eks#1922]
## Description

We are upgrading the EKS module from 17.x to 18.x and we have cleaned the statefile as suggested. As we need to create other kuberetes resources, we are creating the kubernetes provider and refering to the kubeconfig file created using local_file. But the terraform plan is failing to find the kubeconfig file.

## Versions

 - Terraform: 1.0.0 

### Code Snippet to Reproduce
resource "local_file" "kubeconfig" {
  content              = local.kubeconfig
  filename             = "${path.module}/kubeconfig_${local.eks_cluster_name}"
  file_permission      = "0600"
  directory_permission = "0755"
}

provider "kubernetes" {
  host                           = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                         = data.aws_eks_cluster_auth.cluster.token
  config_path               = local_file.kubeconfig.filename
}

## Expected behavior
The kubernetes provider should be able to find the kubeconfig file

## Actual behavior
'config_path' refers to an invalid path: "./kubeconfig_infra-9ebEuuXn": stat ./kubeconfig_infra-9ebEuuXn: no such file or directory

### Terminal Output Screenshot(s)
![image](https://user-images.githubusercontent.com/52164525/157068063-95050808-6020-4c7e-be3a-a7afaeb10e59.png)

## Additional context
Please suggest how to handle creation of kubeconfig file and how it can be passed to kubernetes provider since managing kubeconfig has been removed from module version 18.x

**Comment by bryantbiggs** [comment]
this is already documented within the examples provided https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa_autoscale_refresh/charts.tf#L2-L5

**Comment by poojaac** [comment]
@bryantbiggs We tried this but the other components which are trying to connect to the kubernetes is giving the error
Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/k8s-config": dial tcp 127.0.0.1:80: connect: connection refused

**Comment by kadamd-acc** [comment]
Hi @poojaac ,

Did you find any solution for the above issue, as we are also facing the same  error "dial tcp 127.0.0.1:80: connect: connection refused" 

we have created the data template file for kubeconfig and passed that to kubernets provider configpath 

Below are the config file template- 

data "template_file" "kubeconfig" {
#count = (var.user_os == "linux" && var.k8s_cluster_type == "eks") ? 1 : 0
  template = <<-EOF
    apiVersion: v1
    kind: Config
    current-context: terraform
    clusters:
    - name: ${data.aws_eks_cluster.selected[0].name}
      cluster:
        certificate-authority-data: ${data.aws_eks_cluster.selected[0].certificate_authority.0.data}
        server: ${data.aws_eks_cluster.selected[0].endpoint}
    contexts:
    - name: terraform
      context:
        cluster: ${data.aws_eks_cluster.selected[0].name}
        user:
    users:
    - name: terraform
      user:
        token: ${data.aws_eks_cluster_auth.selected[0].token}
  EOF
}

please suggest if you have fixed this issue.

**Comment by poojaac** [comment]
@kadamd-acc No we are still facing the same issue. Using the latest 18.x module and have configured the kubernetes provider block as mentioned in the examples section 

`provider "kubernetes" {

  host                   = module.eks_cluster.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks_cluster.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    command     = "aws"
    # This requires the awscli to be installed locally where Terraform is executed
    args = ["eks", "get-token", "--cluster-name", module.eks_cluster.cluster_id]
  }
}`

But still getting Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused when creating the aws-auth configmap.
