### ISSUE TITLE
Output IAM role arns created by nodegroup submodules (iam_role_arn)

### ISSUE THREAD

**Issue by tculp** [terraform-aws-modules/terraform-aws-eks#1923]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
Updating or overwriting the aws-auth configmap is difficult without having easy access to which roles are used/created for the nodegroups.

## Describe the solution you'd like.
An output by the eks parent module that provides a list of all nodegroup roles.

## Describe alternatives you've considered.
- Using a data source to pull role names
- Manually copy role arns
- Create node groups separately using the submodule directly (not preferred)

## Additional context
This could also help satisfy #1744 and #1901

**Comment by bryantbiggs** [comment]
you can see how to do this here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/outputs.tf#L169-L179
or feel free to use the already formatted configmap and add in any additional roles/groups/etc. before consuming downstream
