### ISSUE TITLE
Desired Size for both Self managed and EKS managed not working after the EKS deployment

### ISSUE THREAD

**Issue by sourabhsharma487** [terraform-aws-modules/terraform-aws-eks#1924]
**Scenario:** I needed to provision a couple of EKS clusters using both EKS managed and Self managed node groups. I tried provisioning it with this code using the 18.8.1 version and I am able to deploy it for both node groups.

**Problem statement:**  This code is not accepting "desired_size" changes in terms of adding/removing the nodes after the EKS cluster deployment is done based on the need. 

**Versions:**
Terraform-aws-eks: 18.8.1
Terraform 1.1.6
OS: Windows 10 Enterprise

EKS: 1.21

`

terraform-aws-eks/main.tf

module "eks" {
  source                               = "terraform-aws-modules/eks/aws"

  version                              = "18.8.1"
  vpc_id                               = var.vpc_id
  subnet_ids                           = var.public_subnets
  cluster_endpoint_private_access      = var.cluster_endpoint_private_access
  cluster_endpoint_public_access       = var.cluster_endpoint_public_access
  cluster_name                         = var.cluster_name
  cluster_version                      = local.cluster_version
  tags                                 = local.tags

  eks_managed_node_group_defaults = {
    ami_type               = "AL2_x86_64"
    disk_size              = 20
    instance_types         = ["m6i.large", "m5.large", "m5n.large", "m5zn.large"]
    vpc_security_group_ids = [aws_security_group.all_worker_mgmt.id]
  }

  eks_managed_node_groups = {
    # blue = {}
    green = {
      min_size     = 1
      max_size     = 5
      desired_size = 4
      instance_types = ["t3.large"]
      capacity_type  = "SPOT"
      labels = {
        Environment = "eks-terraform"
      }
      taints = {
        dedicated = {
          key    = "dedicated"
          value  = "gpuGroup"
          effect = "NO_SCHEDULE"
        }
      }
      tags = {
        Maintainer = "Sourabh Sharma"
      }
    }
  }
}
`

**Comment by bryantbiggs** [comment]
Desired size is ignored due to the nature of Kubernetes and predominant use of autoscaling (i.e. - cluster autoscaler, Karpenter, etc.). Therefore changing `desired_size` after provisioning will not influence the number of nodes. If you need to force more nodes into the pool, you can raise the `min_size` as a work around

**Comment by gordonmurray** [comment]
> Desired size is ignored due to the nature of Kubernetes and predominant use of autoscaling (i.e. - cluster autoscaler, Karpenter, etc.).

This makes sense. However the desired size as well as min/max can be changed in the EKS UI in the AWS Console. I would assume if the AWS UI can do it, it could also be possible for the Terraform module to do it also.

![Screenshot from 2022-08-11 17-09-45](https://user-images.githubusercontent.com/56556/184179661-c1dbbf6a-7642-4e4e-9c74-10a2402dc5d4.png)

**Comment by bryantbiggs** [comment]
https://github.com/bryantbiggs/eks-desired-size-hack
