### ISSUE TITLE
dial tcp 127.0.0.1:80: connect: connection refused error while upgrade the module from 17.x to 18.x

### ISSUE THREAD

**Issue by poojaac** [terraform-aws-modules/terraform-aws-eks#1929]
## Description

We are upgrading the EKS module from 17.x to 18.x and we have self managed nodes. We have cleaned up the statefile by removing  the **module.eks_cluster.local_file.kubeconfig** and **module.eks_cluster.kubernetes_config_map.aws_auth** references since18.x version doesn't manage the kubeconfig and aws_auth.

As we are creating the kubernetes resources like secrets, configmaps in the same state as we are creating the cluster, we have configured the kubernetes provider block. But kuberenetes provider is not able to talk to the cluster and the terraform plan is failing with the error **Error: Get "http://localhost/api/v1/namespaces/kube-system/secrets/git-credentials": dial tcp 127.0.0.1:80: connect: connection refused**
We did not face such issue when we used the 17.x version of eks module

## Versions

 - Terraform: 1.0.0

 - Provider(s): 
```terraform
   kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">=2.1.0"
    }
```

 - Module: 
 ```terraform
module "eks_cluster" {
   source  = "terraform-aws-modules/eks/aws"
   version = "18.2.4"
   ...
}
```

### Code Snippet to Reproduce
```terraform
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}

data "aws_eks_cluster" "cluster" {
  name = module.eks_cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks_cluster.cluster_id
}

resource "kubernetes_secret" "git_credentials" {
  metadata {
    name      = "git-credentials"
    namespace = local.k8s_kube_system_namespace
  }
  data = {
    username = "git"
    password = data.aws_ssm_parameter.flux_token.value
  }
  type = "kubernetes.io/basic-auth"
}
```

## Expected behavior
Terraform plan should be able to successfully list the resources to the added/modified/destroyed

## Actual behavior
Tearraform plan is failing with the error
**Error: Get "http://localhost/api/v1/namespaces/kube-system/secrets/git-credentials": dial tcp 127.0.0.1:80: connect: connection refused**

### Terminal Output Screenshot(s)
![image](https://user-images.githubusercontent.com/52164525/157436087-880664f7-974b-43dc-865a-989ca782c850.png)

## Additional context
When we are setting the TF_LOG to DEBUG, we are able to see the detailed logs from the aws provider, where as the kubernetes provider is not showing any detailed logs.

**Comment by bryantbiggs** [comment]
unfortunately this is outside the scope of the module. due to the [number of issues](https://github.com/terraform-aws-modules/terraform-aws-eks/issues?q=is%3Aissue+sort%3Aupdated-desc+aws-auth+is%3Aclosed) and wide ranging configurations, the management of aws-auth/kubeconfig was removed from the module
