### ISSUE TITLE
How to customize worker_groups

### ISSUE THREAD

**Issue by syst0m** [terraform-aws-modules/terraform-aws-eks#193]
# I have issues
with trying to modify the example worker_group config.

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [/] support request
* [ ] kudos, thank you, warm fuzzy

Starting from your example config, I am trying to define a single autoscaling group, which uses just 1 instance type, has a minimum of 2 workers and a maximum of 5 workers.

In the example _worker_groups_ the list has two maps, which are identical, except the 2nd one has
the _additional_security_group_ids_ element:

```
...
  worker_groups = [
    {
      instance_type       = "t2.small"
      additional_userdata = ""
      subnets             = "${join(",", module.vpc.private_subnets)}"
    },
    {
      instance_type                 = "t2.small"
      additional_userdata           = ""
      subnets                       = "${join(",", module.vpc.private_subnets)}"
      additional_security_group_ids = "${aws_security_group.worker_group_mgmt_one.id},${aws_security_group.worker_group_mgmt_two.id}"
    },
...
```

Why are there two maps, and why does only the 2nd one have the _additional_security_group_ids_ set? Which map is actually used to provision the workers?

Also, where and how is the number of workers set in the example?
Is it here:
`  worker_group_count                   = "2"
`
In the commented out example for multiple worker groups of differing configurations, you are using 
_asg_max_size_ and _asg_min_size_ to set the limits of the asg group. I don't see anything similar being done in the example group.

What's the proper way to define the config for only one asg group?

Finally, I see that for autoscaling to take place, some additional config needs to be set,
as described here:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/autoscaling.md

If that's the case, is there a point in defining the _asg_max_size_ and _asg_min_size_ without setting _autoscaling_enabled_ to _true_? 
Would the number of workers ever change without it?

## Environment details

* Affected module version: 1.7.0
* OS: 10.14.1
* Terraform version: 0.11.10

## Any other relevant info
Thanks in advance!

**Comment by max-rocket-internet** [comment]
Hi @syst0m !

>  I am trying to define a single autoscaling group, which uses just 1 instance type, has a minimum of 2 workers and a maximum of 5 workers.

> What's the proper way to define the config for only one asg group?

Here:

```hcl
  worker_groups = [
    {
      instance_type       = "m4.xlarge"
      asg_max_size        = 5
      asg_min_size        = 2
  ]
```

> Why are there two maps, and why does only the 2nd one have the additional_security_group_ids set? 

It's an example to show how one might configure 2 worker groups with different settings.

> Which map is actually used to provision the workers?

Both are used. This will create 2 worker groups. i.e 2x ASGs.

> Also, where and how is the number of workers set in the example?

Do you mean the number of instances in the ASG? Or the number of worker groups? `worker_group_count` is the number of worker groups.

> In the commented out example for multiple worker groups of differing configurations, you are using asg_max_size and asg_min_size to set the limits of the asg group. I don't see anything similar being done in the example group.

Correct. The defaults are used in this case. Search for `workers_group_defaults` in the README and this is explained.

> If that's the case, is there a point in defining the asg_max_size and asg_min_size without setting autoscaling_enabled to true? Would the number of workers ever change without it?

The min and max values are the limits. The cluster-autoscaler will adjust the `asg_desired_capacity` number but always within the limits. Without the cluster-autoscaler, the `asg_desired_capacity` will never change and you will always have the same number of instances in your ASG.

Hope that helps!

**Comment by syst0m** [comment]
Hi @max-rocket-internet 

Thanks for the detailed explanation. 👍 

I'm gonna try that out. :)

**Comment by wilkko** [comment]
If an auto scaling launch configuration is created with above configuration and worker node instances launched based on it, changing auto scaling launch configurations afterwards does not seem to have an effect on the running instances. E.g. if an instance gets a new security group, one has to manually tear down old worker nodes and let auto scaling group launch new instances. 

Am I just missing the autoscaling_enabled=true property?

**Comment by max-rocket-internet** [comment]
> one has to manually tear down old worker nodes and let auto scaling group launch new instances.

This is normal and is how ASGs and LCs work.

> Am I just missing the autoscaling_enabled=true property?

This just adds a tag to the ASG that is read by the k8s `cluster-autoscaler` (if running). Nothing more. If you want autoscaling, you need to install the `cluster-autoscaler` chart: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/autoscaling.md

**Comment by syst0m** [comment]
I tried configuring the worker_groups, with the example you provided, @max-rocket-internet .

Now I get:

`Error: Error applying plan:

2 error(s) occurred:

* module.eks.aws_iam_instance_profile.workers[1]: index 1 out of range for list var.worker_groups (max 1) in:

${lookup(var.worker_groups[count.index], "iam_role_id",  lookup(local.workers_group_defaults, "iam_role_id"))}
* module.eks.data.template_file.userdata[1]: index 1 out of range for list var.worker_groups (max 1) in:

${lookup(var.worker_groups[count.index], "pre_userdata", local.workers_group_defaults["pre_userdata"])}`

**Comment by syst0m** [comment]
I tried modifying the `asg_desired_capacity` value, and then re-running `terraform apply`.
The ASG provisioned by terraform doesn't get modified.
For example, if during initial provisoning `asg_desired_capacity = 2`, then I set it to 0, or, let's say 5, and re-run `terraform apply`, the ASG deployed remains unchanged.

**Comment by max-rocket-internet** [comment]
Correct. This is intentional:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L23

Due to the fact that most people are using the cluster-autoscaler to change this value and don't want terraform to change it. So it's set on creation but then ignored.

**Comment by syst0m** [comment]
Ok, many thanks for taking the time to provide explanations and feedback.
It is much appreciated!
