### ISSUE TITLE
Unable to modify instance size of existing node group in EKS

### ISSUE THREAD

**Issue by shikha372** [terraform-aws-modules/terraform-aws-eks#1931]
## Description

while trying to modify the instance size for worker nodes that are part of a node group in EKS , faced 409 error as module instead of updating configuration in existing node group, trying to create another with same name.

## Versions

 - Terraform: v0.14.9

 - Provider(s): v2.8.0

 - Module: terraform-aws-eks 

## Reproduction
Try changing the existing instance size in input vars and run upgrade

## Expected behavior
in-place modification to change instance type in EKS node group

## Actual behavior
Unable to update instance type for worker nodes in existing nodegroup added to EKS 

### Terminal Output Screenshot(s)
Error: error creating EKS Node Group (xyz:application): ResourceInUseException: NodeGroup already exists with name application and cluster name env1-dev-eks
{
 RespMetadata: {
StatusCode: 409,
     RequestID: "2b5a3065-849c-40ea-a2f6-49ab265e4ffc"
   },
 ClusterName: "xyz",
Message_: "NodeGroup already exists with name application and cluster name xyz",
NodegroupName: "application"
}

**Comment by bryantbiggs** [comment]
closing due to lack of information

**Comment by shikha372** [comment]
@bryantbiggs what else information is needed ..let me know? 
we are trying below :
-> setup eks cluster on AWS with node group assigned a specific machine type eg. (m5.xlarge) and for other configuration like AMI we used launch template
-> now, we need to update this instance type of node group from current m5.xlarge to r5.xlarge
-> while we are trying to update it using terraform apply with module (terraform-aws-eks) it is giving 409 error as mentioned above in the case
-> is this feature supported to update the instance type in existing node group without first destroying it?

**Comment by bryantbiggs** [comment]
the configuration you are using. just looking above, I don't know how old your EKS module version is but v2.8.0 is quite dated and the module relies on at least v3.72 https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/versions.tf#L7

**Comment by shikha372** [comment]
provider looks like below:-

terraform {
required_providers {
aws = "3.67.0"
#kubernetes = "1.13.3"
elasticsearch = {
source = "phillbaker/elasticsearch"
version = ">= 1.6.3"
}
}
experiments = [module_variable_optional_attrs]
}

would just like to confirm is this feature supported in later versions from v3.72 ??

**Comment by bryantbiggs** [comment]
I am not going to respond further and kindly refer back to:
> This section really needs to be filled in __Code Snippet to Reproduce__ in the issue ticket

**Comment by kintarowins** [comment]
I'm getting this error as well, is there a solution? For me, I'm just changing the instance type `instance_types = ["t3.xlarge"]`
