### ISSUE TITLE
Support EC2 Fleets (manage On-Demand, RI, Spot Instances with a single ASG)

### ISSUE THREAD

**Issue by geota** [terraform-aws-modules/terraform-aws-eks#194]
# I have issues

## I'm submitting a...

* [ ] bug report
* [X] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
This module only provisions vanilla ASGs.

## What's the expected behavior?
Support EC2 Fleets with Spot + ASG support.
Amazon just shipped support for managing RI, Spot, and On-Demand in a single ASG. I would like to leverage these ASGs inside of my EKS worker groups.

## Are you able to fix this problem and submit a PR? Link here if you have already.
Happy to submit a PR, but want to get general alignment that this would be merged/accepted.
## Environment details

* Affected module version:
* OS:
* Terraform version:

## Any other relevant info
https://github.com/kubernetes/autoscaler/issues/838
https://github.com/terraform-providers/terraform-provider-aws/issues/6478
https://aws.amazon.com/about-aws/whats-new/2018/11/scale-instances-across-purchase-options-in-a-single-ASG/

**Comment by max-rocket-internet** [comment]
I would love this also 🎉

**Comment by skang0601** [comment]
So I took a crack at converting it but there seems to be some bugs in the aws provider that is currently blocking it, mainly this: https://github.com/terraform-providers/terraform-provider-aws/issues/4570

**Comment by max-rocket-internet** [comment]
Launch templates have been added so this is now possible 🎉
