### ISSUE TITLE
Node group get launch_template_name from node_group_defaults

### ISSUE THREAD

**Issue by bjzhang1101** [terraform-aws-modules/terraform-aws-eks#1945]
## Is your request related to a new offering from AWS?

No
## Is your request related to a problem? Please describe.

We found that `launch_template_name` in node group can not inherit the value from `eks_managed_node_group_defaults` like other launch_template related fields like `create_launch_template` or `launch_template_version`: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v18.10.2/node_groups.tf#L276. Instead, it uses the `key` of the node groups map. Is this intentional? 

In our cace, we have multiple node groups per cluster using the same template, this means we need to add the same field for each node groups every time.

## Describe the solution you'd like.
Make `launch_template_name` to inherit value from `eks_managed_node_group_defaults`.

## Describe alternatives you've considered.
Define `launch_template_name` in every node groups.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.11.0 :tada:

**Comment by bjzhang1101** [comment]
Thanks! @antonbabenko
