### ISSUE TITLE
coredns workload shows up before the add on is installed

### ISSUE THREAD

**Issue by FernandoMiguel** [terraform-aws-modules/terraform-aws-eks#1947]
## Description

I'm seeing this weird issue where the coredns workload shows up in the cluster, even before the coredns addon is installed (or even installed at all) in the cluster.
which then leads to a failure for it to get healthy when the addon is installed given the status is of `ReplicaSet "coredns-66cb55d4f4" has timed out progressing.`

![image](https://user-images.githubusercontent.com/168366/159055195-f101ef6c-a38c-470a-bc4f-cd4117405998.png)
![image](https://user-images.githubusercontent.com/168366/159055238-3d5b4536-e1e9-4dd0-a4fe-252fe9458333.png)

## Versions
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.13.1
+ provider registry.terraform.io/hashicorp/aws v4.5.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.8.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/tls v3.1.0

 - Module:
  "Source": "registry.terraform.io/terraform-aws-modules/eks/aws",
  "Version": "18.10.2",

## Reproduction

no

clean install

### Code Snippet to Reproduce
```
################################################################################
# EKS Addons
################################################################################

variable "cluster_addons" {
  description = "Map of cluster addon configurations to enable before the workers are created. Addon name can be the map keys or set with `name`"
  type        = any
  nullable    = false
  default = {
    kube-proxy = {
      resolve_conflicts = "OVERWRITE"
      addon_version     = "v1.21.2-eksbuild.2"
    }
    vpc-cni = {
      enable_pod_eni    = true
      resolve_conflicts = "OVERWRITE"
      addon_version     = "v1.10.2-eksbuild.1"
    }
    # coredns = {
    #   resolve_conflicts = "OVERWRITE"
    #   addon_version     = "v1.8.4-eksbuild.1"
    # }
  }
}
```
## Expected behavior
for a workload only show up when an addon is installed

## Actual behavior
a workload shows in well before the addon is added to the cluster

## Additional context
fargate only cluster

**Comment by bryantbiggs** [comment]
CoreDNS is installed by default by AWS - so I'm inclined to close the issue here and have you open a ticket with AWS (unless I am missing something obvious)

**Comment by FernandoMiguel** [comment]
> CoreDNS is installed by default by AWS - so I'm inclined to close the issue here and have you open a ticket with AWS (unless I am missing something obvious)

although I agree with you, it is still and addon that by default the module doesn't provide
```################################################################################
# EKS Addons
################################################################################

variable "cluster_addons" {
  description = "Map of cluster addon configurations to enable for the cluster. Addon name can be the map keys or set with `name`"
  type        = any
  default     = {}
}
```
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/6aefb829c5fddea809f29f10676673e926c39c55/variables.tf#L358-L366
so why would it show up there?

@bryantbiggs  if this is an issue with aws itself, more than happy to open a ticket with them.

**Comment by bryantbiggs** [comment]
correct - thats what I'm saying. the module does not specify any default addons, in fact it does nothing with addons unless users opt in via the `cluster_addons` variable. so this issue is on the AWS side

**Comment by maati55** [comment]
@FernandoMiguel Did you find anything about this? I am having the same issue

**Comment by FernandoMiguel** [comment]
> @FernandoMiguel Did you find anything about this? I am having the same issue

@maati55 i read there a fix for some of these timeouts last weeks.
i havent had the chance to deploy a new fargate cluster to test.
but let me know if you find anything

**Comment by FernandoMiguel** [comment]
@maati55 not fixed
`module.eks.module.eks.aws_eks_addon.this["coredns"]: Still creating... [20m0s elapsed]`

**Comment by bryantbiggs** [comment]
> @FernandoMiguel I have tested a couple of things but nothing works. Looks like with fargate only cluster it doesn't work at all, not sure if anyone managed to run with argate only cluster. Not an ideal, but I end up adding an eks managed node group for kube-system, and fargate for other namesapces.

Have you read https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#fargate-gs-coredns

**Comment by maati55** [comment]
@bryantbiggs Yes, I saw that and based on that I have created a **coredns** profile, but still have the same issue. It failed on initial run after 20mins with DEGRADED error, then if removed the coredns add-ons from cluster and re-run the terraform again, it will add the add-ons and terraform complete successfully.

```
coredns = {
  name = "coredns"
  selectors = [
    {
      namespace = "kube-system"
      labels = {
        k8s-app = "kube-dns"
      }
    },
  ]

  timeouts = {
    create = "10m"
    delete = "10m"
  }

  subnet_ids = [for s in data.aws_subnet.private : s.id]
}
```

**Comment by bryantbiggs** [comment]
the module creates the profile, I'm referring to the patch process:

```
kubectl patch deployment coredns \
    -n kube-system \
    --type json \
    -p='[{"op": "remove", "path": "/spec/template/metadata/annotations/eks.amazonaws.com~1compute-type"}]'
```

**Comment by maati55** [comment]
> if you can, running a small instance to get past the manual patching for Fargate is the route I would suggest. This is what we do for the Fargate example https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/fargate_profile/main.tf#L48-L50
> 
Yes, that's what I actually did - Thanks

**Comment by FernandoMiguel** [comment]
for now, we've worked around this by having `local-exec` patching and redeploying coredns, and only then adding the addon...
weirdly enough it all works even without the addon.
I'll push this back to the service team

**Comment by FernandoMiguel** [comment]
@maati55 https://github.com/aws/containers-roadmap/issues/1687

**Comment by JordyWTC** [comment]
> for now, we've worked around this by having `local-exec` patching and redeploying coredns, and only then adding the addon... weirdly enough it all works even without the addon. I'll push this back to the service team

I solved this also by doing a local-exec in a tf file:

`data "template_file" "kubeconfig" {
  template = <<EOF
apiVersion: v1
kind: Config
current-context: terraform
clusters:
- name: ${module.eks.cluster_id}
  cluster:
    certificate-authority-data: ${data.aws_eks_cluster.cluster.certificate_authority.0.data}
    server: ${data.aws_eks_cluster.cluster.endpoint}
contexts:
- name: terraform
  context:
    cluster: ${module.eks.cluster_id}
    user: terraform
users:
- name: terraform
  user:
    token: ${data.aws_eks_cluster_auth.cluster.token}
EOF
}

resource "null_resource" "coredns_patch" {
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<EOF
kubectl --kubeconfig=<(echo '${data.template_file.kubeconfig.rendered}') \
  delete deployment coredns \
  --namespace kube-system \
EOF
  }
}`
