### ISSUE TITLE
Error: error creating KMS Key: MalformedPolicyDocumentException

### ISSUE THREAD

**Issue by evenme** [terraform-aws-modules/terraform-aws-eks#1950]
## Description

Trying to create a new cluster since upgrading from v17-v18 didn't work. I actually have 3 issues I'm trying to solve, the first is this KMS key creation problem which fails to create the key with this error:

```
Error: error creating KMS Key: MalformedPolicyDocumentException: The new key policy will not allow you to update the key policy in the future.
with aws_kms_key.ebs
on main-eks.tf line 277, in resource "aws_kms_key" "ebs":
resource "aws_kms_key" "ebs" {
```

## Versions
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.13.1
+ provider registry.terraform.io/hashicorp/aws v3.75.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/tfe v0.25.3
+ provider registry.terraform.io/hashicorp/tls v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.24.1
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
 - Module: v18

## Reproduction

Steps to reproduce the behavior: run plan and apply on this terraform code:

```

resource "aws_kms_key" "eks" {
  description             = "EKS Secret Encryption Key"
  deletion_window_in_days = 7
  enable_key_rotation     = true
  tags                    = var.tags
}

resource "aws_kms_key" "ebs" {
  description             = "Customer managed key to encrypt EKS managed node group volumes"
  deletion_window_in_days = 7
  policy                  = data.aws_iam_policy_document.ebs.json
}

# This policy is required for the KMS key used for EKS root volumes, so the cluster is allowed to enc/dec/attach encrypted EBS volumes
data "aws_iam_policy_document" "ebs" {
  # Copy of default KMS policy that lets you manage it
  statement {
    sid       = "Enable IAM User Permissions"
    actions   = ["kms:*"]
    resources = ["*"]

    principals {
      type = "AWS"
      identifiers = [
        "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root",
        "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/vault-role"
      ]
    }
  }

  # Required for EKS
  statement {
    sid = "Allow service-linked role use of the CMK"
    actions = [
      "kms:Encrypt",
      "kms:Decrypt",
      "kms:ReEncrypt*",
      "kms:GenerateDataKey*",
      "kms:DescribeKey"
    ]
    resources = ["*"]

    principals {
      type = "AWS"
      identifiers = [
        "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling", # required for the ASG to manage encrypted volumes for nodes
        module.eks.cluster_iam_role_arn,                                                                                                            # required for the cluster / persistentvolume-controller to create encrypted PVCs
      ]
    }
  }

  statement {
    sid       = "Allow attachment of persistent resources"
    actions   = ["kms:CreateGrant"]
    resources = ["*"]

    principals {
      type = "AWS"
      identifiers = [
        "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling", # required for the ASG to manage encrypted volumes for nodes
        module.eks.cluster_iam_role_arn,                                                                                                            # required for the cluster / persistentvolume-controller to create encrypted PVCs
      ]
    }

    condition {
      test     = "Bool"
      variable = "kms:GrantIsForAWSResource"
      values   = ["true"]
    }
  }
}
``` 

## Expected behavior
Create the KMS key

## Actual behavior
Error: error creating KMS Key: MalformedPolicyDocumentException: The new key policy will not allow you to update the key policy in the future.
with aws_kms_key.ebs
on main-eks.tf line 277, in resource "aws_kms_key" "ebs":
resource "aws_kms_key" "ebs" {

## Additional context
The code is also not fully creating the cluster either (extracted from examples, with just one managed node group), the instances from managed node groups are being created but not joining the cluster/showing as nodes. Other parts fail too because if times out on waiting to become active. This new v18 became so complex (with almost 300 lines to create a cluster using a module that before was done with under 50 lines), if we didn't want to use the addons feature we would not move to v18 at all.

**Comment by bryantbiggs** [comment]
This isn't related to the module - https://aws.amazon.com/premiumsupport/knowledge-center/update-key-policy-future/
