### ISSUE TITLE
Unable to set docker bridge network in userdata script

### ISSUE THREAD

**Issue by sriram0721** [terraform-aws-modules/terraform-aws-eks#1954]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:

 - Provider(s):

 - Module:

**Comment by sriram0721** [comment]
Terraform Version:- 1.0.0
Module Version:- 18.11.0

We are trying to enable docker bridge network on the eks to utilize DIND capabilities . Unfortunately the args are not setting up whenever we make apply terraform changes

code snippet
`module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = local.cluster_name
  cluster_version = var.cluster_version

  tags = var.tags
  vpc_id = module.vpc.vpc_id
  subnet_ids  = module.vpc.private_subnets
  eks_managed_node_group_defaults = {
    instance_types         = "m4.large"
  }
   eks_managed_node_groups = {
    jenkins_eks_worker = {
      desired_size = 3
      instance_types = ["m4.large"]
      pre_bootstrap_user_data = <<-EOT
      echo "foo"
      export FOO=bar
      EOT
      bootstrap_extra_args = "---enable-docker-bridge true --kubelet-extra-args '--max-pods=15'"
      
      
    }
  }
}`

**Comment by bryantbiggs** [comment]
the EKS managed node group user data removes direct access to a lot of the upstream EKS user data capabilities. You can reference https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9528619acacff3441f5361ae6367fe9074ffde10/examples/eks_managed_node_group/main.tf#L197-L208 to figure out a suitable work around

**Comment by sriram0721** [comment]
does it work with default docker runtime. i see that the above code you have shared uses containerd as its run time

**Comment by sriram0721** [comment]
but even after providing like this, i dont see it being set on the node level . Any thoughts/suggestions @bryantbiggs 

 ```
  eks_managed_node_groups = {
    jenkins_eks_worker = {
      desired_size = 3
      instance_types = ["m4.large"]
      extend_config= {
      pre_bootstrap_user_data = <<-EOT
       #!/bin/bash 
       set -ex 
       cat <<-EOF > /etc/profile.d/bootstrap.sh 
       export ENABLE_DOCKER_BRIDGE=true 
       export KUBELET_EXTRA_ARGS="--enable-docker-bridge true" 
       EOF 
       # Source extra environment variables in bootstrap script 
       sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh 
       EOT 
      }
```

**Comment by bryantbiggs** [comment]
unfortunately, this is outside the scope of the module
