### ISSUE TITLE
General Query EKS Managed vs Self Managed Node Groups

### ISSUE THREAD

**Issue by dempti** [terraform-aws-modules/terraform-aws-eks#1956]
This is a questin rather than a bug.

I want to learn about the difference between using Self Manged and EKS Managed node groups.
I did go through the documentation of AWS itself but did not find much useful information.

What are the pros and cons of using EKS Managed and Self Managed Node groups and their use cases?

**Comment by elagree** [comment]
Hello @dempti,

Self managed nodes will require from your/your team more action than the EKS managed nodes.

By example if you want to upgrade a Self-Managed node you will have to create a new node group and migrate your pods into this new node group.
With an EKS managed node Group (without custom AMI) you can do it easily thanks to eksctl or UI and AWS will do the rolling for you.

Basically with Managed node group you will have less responsibility. Check this [picture](https://aws.github.io/aws-eks-best-practices/reliability/docs/images/SRM-Fargate.jpeg)

You can find information [here](https://docs.aws.amazon.com/eks/latest/userguide/eks-compute.html).

**Comment by bryantbiggs** [comment]
this is more of a broader EKS question - please refer to the EKS documentation
