### ISSUE TITLE
Terraform not recognising cluster already created

### ISSUE THREAD

**Issue by z-mani** [terraform-aws-modules/terraform-aws-eks#1969]
## Description

Due to the changes in Terraform v18.0, we have upgraded our stack to fit these updates. We are running into an error however that says "error creating EKS Cluster (envoy-dev-cluster): ResourceInUseException: Cluster already exists with name" and we are unsure how to fix it. The cluster is created using Terraform in a GitLab CI pipeline with v12. Then we added changes that include removing the old map roles method that was removed and inputing it a different way. When these changes are pushed to GitLab and it is run, Terraform tries creating the Cluster instead of updating it. We are doing this in our dev account, currently we have customers in a prod account that was created with Terraform v12. We ideally don't want to take down the Cluster to enforce these new changes hence trying to solve these module issues by updating not recreating.

## Versions

 - Terraform: v1.1.7

 - Provider(s): v1.1.7

 - Module: eks/aws = "18.11.0"

## Reproduction

- Running Terraform v12 in GitLab CI that brings up cluster.
- Adding changes to Terraform locally that are needed for v18.
- Pushing those changes to GitLab and running the pipeline.

## Expected behavior
We expect Terraform to recognise the current cluster in AWS that was brought up using v12. 

## Actual behavior
Throws error saying "error creating EKS Cluster (envoy-dev-cluster): ResourceInUseException: Cluster already exists with name"

### Terminal Output Screenshot(s)
![Screen Shot 2022-03-28 at 1](https://user-images.githubusercontent.com/102492637/160308797-a7752b32-e231-4080-8a55-3bac027176cb.png)

**Comment by bryantbiggs** [comment]
from the little bit of information provided, it looks like you possibly tried to re-create the cluster which is causing the existing cluster error. I would start with:
1. https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/UPGRADE-18.0.md
2. https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1744

**Comment by bryantbiggs** [comment]
closing out for now - please see above

**Comment by fsadykov** [comment]
Facing the same issue 

terraform v1.0.9 
provider v4.1.0
Module EKS: 17.18.0

**Comment by crohling** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/UPGRADE-18.0.md moved to https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-18.0.md for anyone else reading through this after-the-fact.

**Comment by adiii717** [comment]
same here today, until I have to destroy and recreate
this is really annoying, how one can do this in production?
this module `18.x` is really buggy
