### ISSUE TITLE
Cannot Detach policy on cluster destroy

### ISSUE THREAD

**Issue by marky-mark** [terraform-aws-modules/terraform-aws-eks#197]
# I have issues

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Cannot 

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Create a cluster with policies and destroy...get the following error

```
* module.eks.module.eks.aws_iam_role.workers (destroy): 1 error(s) occurred:
* aws_iam_role.workers: DeleteConflict: Cannot delete entity, must detach all policies first.
```

## What's the expected behavior?

Destroy the cluster and detach policies

## Are you able to fix this problem and submit a PR? Link here if you have already.

https://github.com/terraform-aws-modules/terraform-aws-eks/pull/196

## Environment details

* Affected module version: 1.7.0
* OS: Mac
* Terraform version: 0.11.10

**Comment by max-rocket-internet** [comment]
Resolved in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/196
