### ISSUE TITLE
Ability to customize userdata template args

### ISSUE THREAD

**Issue by alex88** [terraform-aws-modules/terraform-aws-eks#1975]
## Is your request related to a problem? Please describe.
After migrating to v18 it seems that the old `userdata_template_extra_args` variable doesn't have a replacement, so I can't provide extra variables to the userdata custom template

## Describe the solution you'd like.
Be able to merge custom variables in the template, like I was doing in v17, e.g.:

```
      userdata_template_extra_args = {
        enable_admin_container   = false
        enable_control_container = true
      }
```

and in my template

```

# The admin host container provides SSH access and runs with "superpowers".
# It is disabled by default, but can be disabled explicitly.
[settings.host-containers.admin]
enabled = ${enable_admin_container}

# The control host container provides out-of-band access via SSM.
# It is enabled by default, and can be disabled if you do not expect to use SSM.
# This could leave you with no way to access the API and change settings on an existing node!
[settings.host-containers.control]
enabled = ${enable_control_container}
```

## Describe alternatives you've considered.
Hardcoding the variables in the template

## Additional context
I'm not an expert in terraform, but I haven't found a replacement of such feature.

**Comment by bryantbiggs** [comment]
Please see:
- https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/_user_data
- https://github.com/terraform-aws-modules/terraform-aws-eks/blob/6d7245621f97bb8e38642a9e40ddce3a32ff9efb/examples/eks_managed_node_group/main.tf#L139-L143

**Comment by alex88** [comment]
Oh ok so just use bootstrap_extra_args and maintain the template myself, thanks!
