### ISSUE TITLE
Node security group and route table accessibility

### ISSUE THREAD

**Issue by ivandir** [terraform-aws-modules/terraform-aws-eks#1976]
## Is your request related to a new offering from AWS?
No - This is an existing feature of the module that is obstructed from direct access

## Is your request related to a problem? Please describe.
I'm creating a new k8s cluster in a secondary VPC and would like to peer it with the primary VPC. There's no direct access via the EKS module to update the security groups of the nodes.

## Describe the solution you'd like.
Allow access to security groups assigned to node instances by eks module or allow for a direct security group assignment to nodes via LT, not indirect like remote_access or other group rules. Remote access is useless for this because it assigns a port 22 ssh rule to the new SG not the SG itself to the Node instance via LT.

## Describe alternatives you've considered.
Manually making the updates via AWS console and executing `terraform apply -refresh-only` to ignore but this is not ideal

## Additional context
I'm using the VPC module (See https://github.com/terraform-aws-modules/terraform-aws-vpc) provided by you to create the VPC but I don't see any way there either to update the route tables of NAT gateway or public/private subnets. In a VPC peering connection you need to update both route tables and security groups to allow for bi-directional comms.

I understand for the route table this is out of the context since it's in a different module but I wanted to give the overall context of the use case.

eks=18.15.0
vpc=3.13.0

**Comment by bryantbiggs** [comment]
I'm not quite following what you are trying to achieve - do you have an example configuration? Have you read through https://github.com/terraform-aws-modules/terraform-aws-eks#security-groups - the security groups are quite extensible and configurable

**Comment by ivandir** [comment]
@bryantbiggs thanks for responding so fast. I've read the security-groups section and the issue is that I can't attach a custom security group to the nodes. 

For example let's say this is my security group that allows another VPC to communicate with the nodes:

```
resource "aws_security_group" "vpc_peering" {
  name_prefix = "${local.name}-vpc-peering"
  description = "Allow VPC peer access"
  vpc_id      = module.vpc.vpc_id

  ingress {
    description = "VPC peering"
    from_port   = 0
    to_port     = 65535
    protocol    = "tcp"
    cidr_blocks = ["172.34.0.0/16"]
  }

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
  }

  tags = local.tags
}
```
When I add it to vpc_security_group_ids

```
  eks_managed_node_group_defaults = {
    ami_type       = "AL2_x86_64"
    disk_size      = 20
    instance_types = ["t3.micro", "t3.small"]
    vpc_security_group_ids = [aws_security_group.vpc_peering.id]
  }
```
I expect it to be listed as a security group in the node_group instances but it's not and I can't modify the default groups because they're hidden. Is this an artifact of the EKS managed node groups because it does show up in the self managed node group.

**Comment by ivandir** [comment]
I see, so then this would have to be set to true.

```
  eks_managed_node_groups = {
    green = {
      **create_launch_template = true**
      ...
    }
  }
```

**Comment by bryantbiggs** [comment]
it is `true` by default, users have to disable by setting it to false like https://github.com/terraform-aws-modules/terraform-aws-eks/blob/6d7245621f97bb8e38642a9e40ddce3a32ff9efb/examples/eks_managed_node_group/main.tf#L109-L113

**Comment by ivandir** [comment]
Thanks @bryantbiggs that resolved the issue. I'll close this ticket.
