### ISSUE TITLE
The instance_metadata_tags value doesn't propagate to EKS launch template copy on managed node groups

### ISSUE THREAD

**Issue by alin-grecu** [terraform-aws-modules/terraform-aws-eks#1977]
## Description

Any value set to `instance_metadata_tags` inside `metadata_option` for `eks_managed_node_groups` is not propagated onto the [EKS managed copy of the provided launch template](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#:~:text=The%20Amazon%20EKS%20API%20creates%20this%20launch%20template%20either%20by%20copying%20one%20you%20provide%20or%20by%20creating%20one%20automatically%20with%20default%20values%20in%20your%20account).
It doesn't matter if you specifically set `enabled` or `disabled` to `instance_metadata_tags` both lend the value `Don't include in launch template` for `Allow tags in metadata` field on the EKS managed LT copy.

## Configuration

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.8.1"

  cluster_name                    = var.short_env
  cluster_version                 = var.cluster_version
  cluster_endpoint_private_access = var.control_plane_private_access
  cluster_endpoint_public_access  = var.control_plane_public_access
  enable_irsa                     = var.enable_irsa
  vpc_id                          = data.aws_vpc.selected.id
  subnet_ids                      = data.aws_subnets.private.ids
  cluster_security_group_id       = aws_security_group.control_plane.id
  create_cluster_security_group   = false
  create_node_security_group      = false

  eks_managed_node_groups = {
    workers = {
      name                       = "${var.short_env}-workers"
      enable_bootstrap_user_data = true
      pre_bootstrap_user_data    = data.aws_s3_object.initscript.body
      subnet_ids                 = data.aws_subnets.private.ids
      ami_id                     = data.aws_ami.ubuntu_eks.image_id
      key_name                   = var.key_pair
      min_size                   = var.workers["min_size"]
      max_size                   = var.workers["max_size"]
      desired_size               = var.workers["desired_size"]
      instance_types             = var.workers["instance_types"]
      vpc_security_group_ids     = [aws_security_group.workers.id]
      create_iam_role            = false
      iam_role_arn               = aws_iam_role.eksworkers.arn
      create_security_group      = false
      metadata_options = {
        http_endpoint               = "enabled"
        http_tokens                 = "optional"
        instance_metadata_tags      = "enabled"
        http_put_response_hop_limit = "3"
      }
      tags = {
        Role = "eksworker"
      }
    }
  }
  tags = local.common_tags
}
```

## Versions

- Module version [18.8.1]:

- Terraform version: v0.15.3
- Provider version(s):
```
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.8.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

## Reproduction Code [Required]

1. At first I started the above configuration without `metadata_options`
2. I added `metadata_options` with the values from above.
3. Everything propagated correctly to the EKS copy of provided launch template (`http_endpoint`, `http_tokens`, `http_put_response_hop_limit`) but not the `instance_metadata_tags` value.

## Expected behavior

I was expecting `instance_metadata_tags` value to be propagated onto the launch template copy EKS creates and uses with it's managed ASG and subsequently to the EC2 instances it creates.

## Actual behavior

`Allow tags in metadata` field on the copied launch template is always set to `Don't include in launch template`.

**Comment by alin-grecu** [comment]
This feels like it's more on AWS side in the way the handle the launch template copy. I'm curious if anyone manages to replicate.

**Comment by bryantbiggs** [comment]
I suspect this down to the EKS service - please reach out to your AWS support to confirm

**Comment by alin-grecu** [comment]
I don't have the option of contacting AWS technical support because of my current support plan.

**Comment by MadsRC** [comment]
Just pitching in to confirm that I'm facing the exact same issue. `instance_metadata_tags` is not being propagated to the launch template for managed node groups.

**Comment by alin-grecu** [comment]
@MadsRC do you have the option of contacting AWS support to validate this is an issue on their side?

**Comment by MadsRC** [comment]
I do, in theory - I'm trying to reach their support team and will get back once I know more.

**Comment by MadsRC** [comment]
I finally managed to get reach AWS support (Case ID 9935829441 in case anyone from AWS is following along...) and am currently awaiting their response.

I'll also have to correct my previous statement about it not working with a launch template and an EC2 instance created manually. I can't replicate it, unfortunately :(

However, after some testing I've noticed that the managed node group that is created is listed as using the launch template I specified, but the autoscaling group that is seemingly created by EKS to manage these nodes lists a launch template created by "arn:aws:sts::XXXXXXXXXXXX:assumed-role/AWSServiceRoleForAmazonEKSNodegroup/EKS" - which doesn't have the setting to allow metadata in tags...

I'm thinking that's the reason the settings from the launch template we created wasn't propagated to the EC2 instances. Makes sense, since the autoscaling group is seemingly configured to use a completely different launch template...

Exactly why the autoscaling group is configured as such, I don't know... But hoping AWS will get back to me with an answer.

**Comment by bryantbiggs** [comment]
EKS managed node groups will merge information from the launch template users provide with its own launch template - you will see 2 launch templates for each node group typically, where the one used on the ASG is created by the EKS managed node group service

**Comment by MadsRC** [comment]
> EKS managed node groups will merge information from the launch template users provide with its own launch template - you will see 2 launch templates for each node group typically, where the one used on the ASG is created by the EKS managed node group service

I was thinking it was something like this, but I couldn't find any mention of it in the AWS EKS documentation. Only exception was a mention of the fact that if one used unsupported settings in the launch template, a default one would be used instead. Looking at the unsupported settings, I don't see any of the settings I use listed.

If AWS merges the provided launch template and the default one into the one used by the ASG, then I guess that explains why I was seeing 2  launch templates - but it doesn't really explain why my setting from the launch template isn't carried over (unless the default value takes precedent, but that would be... silly...)

Let's see what AWS Support has to say about it. Will report back when I hear something.

**Comment by MadsRC** [comment]
I got an answer from AWS and they confirmed that it is working as intended.

As mentioned [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions) AWS EC2 instance tag keys only support `a-z`, `A-Z` and `0-1` if you enable instance tags in instance metadata. When using EKS Managed Node Groups, EKS will create a `kubernetes.io/cluster/cluster-name=owned` tag.

EKS, being graceful and all, handles this transparently and simply just ignores the fact that you specifically asked it to set tags in instance metadata. There is absolutely no need to supply the user with a warning or flash message.

There is currently a feature request for the EC2 service at AWS to allow `/` in for tags in the instance metadata service, but AWS is unable to provide any ETA.

Should this module perhaps not allow setting this, or include a warning until AWS fixes this? I'd be happy to write a PR in my spare time if needed.

**Comment by alin-grecu** [comment]
Thanks for helping get a resolution on this @MadsRC! I don't agree with AWS on them being "graceful" especially when they don't explicitly document this 😄  but I understand their reasoning. Hopefully they'll support `/` soon.
