### ISSUE TITLE
Required Kubernetes Configuration to Join Worker Nodes 

### ISSUE THREAD

**Issue by syst0m** [terraform-aws-modules/terraform-aws-eks#198]
# I have issues
understanding how to customize the module config to allow for the worker nodes to automatically get detected by the k8s master.
## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [√] support request
* [ ] kudos, thank you, warm fuzzy

`terraform apply` output produces a `config_map_aws_auth` k8s ConfigMap.
After configuring kubectl to access the cluster, I can see that all my nodes are ready:
`✗ kubectl get nodes
NAME                                       STATUS   ROLES    AGE   VERSION
ip-10-0-2-166.eu-west-1.compute.internal   Ready    <none>   19m   v1.10.3
ip-10-0-2-17.eu-west-1.compute.internal    Ready    <none>   19m   v1.10.3`

However, my understanding was that I needed to write the `config_map_aws_auth` manually to the cluster with kubectl, as I haven't set `manage_aws_auth` explicitly to `true`.
According to the kubectl output I provided, it looks the workers have nevertheless managed to join the cluster.

I also found reference to this procedure in the official terrafrom eks-getting-started guide:
https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html

There don't seem to be any ConfgiMaps avaialable in the cluster:
`✗ kubectl get configmaps
No resources found.`

## Environment details

* Affected module version: 1.7.0
* OS: macOS Mojave 10.14.1
* Terraform version: 0.11.10

## Any other relevant info

Thanks in advance!

**Comment by syst0m** [comment]
Right, I see it in the `kube-system` namespace.
Tested scheduling some pods, that seems to work.
So, then, basically `manage_aws_auth` is enabled by default, and will write the ConfigMap necessary to allow the workers to join the cluster automatically?

**Comment by max-rocket-internet** [comment]
Yep: https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html

**Comment by syst0m** [comment]
Cool, thanks for the info!
