### ISSUE TITLE
Cluster security group created forcibly even with all check in place

### ISSUE THREAD

**Issue by nikhilkenifullstack** [terraform-aws-modules/terraform-aws-eks#1982]
Hello Team \ Maintainers,

We are using this module in an Org, where security group creation is restricted.
Hence we need to provide the ones - which are approved by security team, and created in advance.

I have checked my code multiple times, and i can confirm that the module creates the security group, even after all the defensive checks in place.

My code.. I have checked multiple times, these are all the inputs needed to prevent the SG creation, but it happens regardless :(

module "cluster" {
    source  = "terraform-aws-modules/eks/aws"
    version = "18.17.0"
     (We need a cluster which is compliant as per Org policies)
    cluster_endpoint_private_access = true
    cluster_endpoint_public_access  = false
   create_cluster_security_group = false
    create_node_security_group = false
    cluster_security_group_id = data.aws_security_group.default.id
  cluster_additional_security_group_ids = [data.aws_security_group.default.id]
  vpc_id = <Some vpc id>
 subnet_ids = <List of our private subnet id'>
....
....

}

**Comment by bryantbiggs** [comment]
The cluster primary security group is created automatically by the EKS service itself and is outside the control of this module
