### ISSUE TITLE
Multiple security groups are created with the kubernetes.io/cluster tag

### ISSUE THREAD

**Issue by blakepettersson** [terraform-aws-modules/terraform-aws-eks#1986]
## Description

The issue is exactly the same as #1810, but for EKS managed node groups, with the same workaround (and presumably the same fix)

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- `18.10.1`

- Terraform version:

```
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v3.72.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/oboukili/argocd v2.2.8
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

Your version of Terraform is out of date! The latest version is 1.1.7. You can update by downloading from https://www.terraform.io/downloads.html
```

## Reproduction Code [Required]

Steps to reproduce the behaviour:

    Create a cluster with this module, using default values and containing at least one eks_managed_node_group

Possible workaround:

    Disable creation of either the node_group or shared node group security groups through module variables and create a separate security group outside this module.

**Comment by bryantbiggs** [comment]
hi @blakepettersson - the EKS managed node group sub-module security group does not have these tags currently

**Comment by blakepettersson** [comment]
@bryantbiggs so it seems :facepalm:. The issue in the case of EKS managed node groups seems to be that EKS autogenerates a security group that already has the `kubernetes.io/cluster/${var.cluster_name}` set, which conflicts with the tag which is set by `aws_security_group.node`. I'll setup a proper repro for this.

**Comment by leiarenee** [comment]
```
Events:
  Type     Reason                  Age                  From                Message
  ----     ------                  ----                 ----                -------
  Normal   EnsuringLoadBalancer    97s (x6 over 4m16s)  service-controller  Ensuring load balancer
  Warning  SyncLoadBalancerFailed  96s (x6 over 4m14s)  service-controller  Error syncing load balancer: failed to ensure load balancer: Multiple tagged security groups found for instance i-07d843b5953ca7412; ensure only the k8s security group is tagged; the tagged groups were sg-0bc8599e71f8a54a9(my-testing-k8s-node-20220419213507462100000009) sg-0b189fb8969ff5bd4(eks-cluster-sg-my-testing-k8s-987542792)
```

**Comment by gohmc** [comment]
> @bryantbiggs so it seems 🤦. The issue in the case of EKS managed node groups seems to be that EKS autogenerates a security group that already has the `kubernetes.io/cluster/${var.cluster_name}` set, which conflicts with the tag which is set by `aws_security_group.node`. I'll setup a proper repro for this.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/dc8a6eecddc2c6957ba309a939ee46f39b946461/node_groups.tf#L160

**Comment by kaykhancheckpoint** [comment]
I'm also experiencing an issue with this after installing the aws-load-balancer-controller. I get the following error from there. 

```
{"level":"error","ts":1651137191.6512694,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Reconciler error","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","name":"k8s-echoserv-echoserv-aaf854977c","namespace":"echoserver","error":"expect exactly one securityGroup tagged with kubernetes.io/cluster/geeiq-test-k8s for eni eni-0605625aa92fe670e, got: [sg-0cc7f9db258d4e3f8 sg-0e95a58276d2c4ae5]"}
```

After checking the console. i can see i have 2 sgs with the same tag ` "kubernetes.io/cluster/<cluster_name>" = "owned" `.

Im also using eks managed node groups.

**Comment by diginc** [comment]
@kaykhancheckpoint check the last couple posts for the workaround from leiarenee

**Comment by leiarenee** [comment]
This workaround worked for me. (https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1810)

Module 'eks'

```terraform
  node_security_group_tags = {
    "kubernetes.io/cluster/${local.name}" = null
  }
```

**Comment by kaykhancheckpoint** [comment]
@diginc @leiarenee yup, thank you

**Comment by rcmurphy** [comment]
This workaround did not work for us.

**Comment by bryantbiggs** [comment]
@rcmurphy / @mr-kelly can you try:
```hcl
  cluster_tags = {
    "kubernetes.io/cluster/${local.name}" = null
  }
```

Where `${local.name}` is the name of your cluster

**Comment by rcmurphy** [comment]
I can confirm we've tried that. It did not work.

**Comment by bryantbiggs** [comment]
> ~I can confirm we've tried that. It did not work.~

apologies - does that mean that it does work for your case or not?

**Comment by rcmurphy** [comment]
It means my ops engineer told me he did it and then realized that you would actually posted a slightly different command, So we never actually tried it. We are used to different work around though (In this case we need to set a kernel parameter, so are using a start up container that’s privileged to do it instead.)

**Comment by mr-kelly** [comment]
> @rcmurphy / @mr-kelly can you try:
> 
> ```terraform
>   cluster_tags = {
>     "kubernetes.io/cluster/${local.name}" = null
>   }
> ```
> 
> Where `${local.name}` is the name of your cluster

In my Karpenter Example, this doesn't work.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/520852/171971337-98d99028-a329-4c61-a7f7-4f618d8b01ad.png">

And these stop create security group doesn't work so:

```tf
  create_node_security_group = false
  create_cluster_security_group = false

```

I am still trying....

**Comment by mr-kelly** [comment]
In this offical doc:
https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html

AWS says :

<img width="730" alt="image" src="https://user-images.githubusercontent.com/520852/171972213-1d6ffa9b-bbfd-4947-bc40-d65a2a66cc4c.png">

And in my `karpenter` example,   
`kubernetes.io/cluster/cluster-name=owned` appears twice.

**Comment by Furragen** [comment]
If I understand you correctly @bryantbiggs , EKS automatically tags the clusters primary security group with `"kubernetes.io/cluster/$clustername" = owned`.
And that would mean you basically have to use `attach_cluster_primary_security_group = true`, because the clusters primary security group will always have the problematic tag, since you state that
```
cluster_tags = {
    "kubernetes.io/cluster/${local.name}" = null
  }
```
does not work.

An alternative would be to set `create_security_group = false`in the node group, which seems like the equivalent of setting `attach_cluster_primary_security_group = true`.

Do I understand this correctly?

**Comment by bryantbiggs** [comment]
> If I understand you correctly @bryantbiggs , EKS automatically tags the clusters primary security group with `"kubernetes.io/cluster/$clustername" = owned`. And that would mean you basically have to use `attach_cluster_primary_security_group = true`, because the clusters primary security group will always have the problematic tag, since you state that
> 
> ```
> cluster_tags = {
>     "kubernetes.io/cluster/${local.name}" = null
>   }
> ```
> 
> does not work.
> 
> An alternative would be to set `create_security_group = false`in the node group, which seems like the equivalent of setting `attach_cluster_primary_security_group = true`.
> 
> Do I understand this correctly?

No - the security group and tag in question only come into play when they are attached to nodes. So you can have 40+ security groups in your account with this tag without issue, but as soon as you attach more than one of those security groups to node(s) in your cluster, then its a conflict

**Comment by Furragen** [comment]
That is very interesting.
My clusters were built without `attach_cluster_primary_security_group = true`.
Yet the aws-lb-controller complains as soon as I add the tag to any second security group.

**Comment by ashishjullia** [comment]
Hi, @kaykhancheckpoint how did you actually deploy and enabled the "load balancer controller"?

**Comment by tareks** [comment]
Running into what appears to be a similar issue, I _think_ I've been able to work around it by using `  create_cluster_primary_security_group_tags = false`. 

The problem appears to be that there are more than 1 security group that are tagged with `"kubernetes.io/cluster/${var.cluster_name}" = "owned"`. Setting that variable to `false` seems to at least stop Karpenter nodes from picking up the additional security group which stops things like the aws-lb-controller from complaining about ENIs with multiple security groups.

This may be a clue when running an apply:
```
module.eks.aws_ec2_tag.cluster_primary_security_group["karpenter.sh/discovery"] will be destroyed
```

Note that existing Karpenter instances need to be replaced for this tag change to take effect.

**Comment by robertlagrant** [comment]
I think this issue has probably been closed prematurely; I just hit it as well with this template.

**Comment by pingme0** [comment]
The issue still exists with module terraform-aws-modules/eks/aws:v18.26.6.
The proposed workaround resolved my problem.

**Comment by uwburn** [comment]
+1

Stepped over this as well with 18.26.6, using `attach_cluster_primary_security_group = true`.

Results was the inability to have the ELB working, having two security groups with `"kubernetes.io/cluster/<cluster_name>" = "owned"`.

Using `create_cluster_primary_security_group_tags = false`, but honestly atm i'm not able to say if this is a proper setup or just a workaround.
