### ISSUE TITLE
Integrate aws-ebs-csi-driver plugin into the deployment (/terraform-aws-eks)

### ISSUE THREAD

**Issue by gfrid** [terraform-aws-modules/terraform-aws-eks#1989]
Request related to a new offering from AWS: https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html. CSI add-on is now available to public over EKS managed add-ons.
Till some time ago 'ebs-csi' functionality available as 'unmanaged plugin' in other terraform modules, AWS now offers ebs-csi driver as EKS managed add-on, the unmanaged deployment conflicts with RBAC if in later step you want to manage it as 'EKS managed add-on'

-------------------------------------------
EXAMPLE of unmnaged:
  source = "DrFaust92/ebs-csi-driver/kubernetes"
  version = "2.13.0"

once aws-ebs-csi-driver is installed as unmanaged and you try to transfer it to managed you get a conflict error, the only way is to 'OVERWRITE'. 

error: Conflict with "HashiCorp" using rbac.authorization.k8s.io/v1: .rules

-------------------------------------------
  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }

Please add new cluster_addons

**Comment by bryantbiggs** [comment]
this is an upstream issue on the EKS service side - there isn't any change that we can make within the module to fix this

**Comment by kaykhancheckpoint** [comment]
I just wanted to check whether this was available now?

My cluster addons looks like this 

```
 cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts        = "OVERWRITE"
      service_account_role_arn = module.vpc_cni_irsa.iam_role_arn
    }
    aws-ebs-csi-driver = {
      resolve_conflicts = "OVERWRITE"
    }
  }
 ```
 
 And i can see in the aws dashboard that the aws-ebs-csi-driver is active. 
 
 However im having some issues when attempting to create a pvc from a storage class

**Comment by bryantbiggs** [comment]
yes the managed addon is available by EKS now - https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html

**Comment by kaykhancheckpoint** [comment]
okay, thanks for clarifying!

**Comment by kaykhancheckpoint** [comment]
@bryantbiggs Follow up question when integrating aws-ebs-csi-driver using this module. I seem to have a permissions issue when trying to setup a pvc. It's constantly in a state of `Pending` and suggests there isent the correct permissions

>   Warning  ProvisioningFailed    115s  ebs.csi.aws.com_ebs-csi-controller-bb878b5db-tgw4t_39cd0e10-7a75-46d0-9821-6766be0b0fee  failed to provision volume with StorageClass "elasticsearch": rpc error: code = Internal desc = Could not create volume "pvc-afc5056b-abd3-4fce-bed6-b5b309943ff6": could not create volume in EC2: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: Q8Sb1SzHYNEOEh1k_k-awG7IRswCqE5XdGgqgxUa0draxmo6pFtu8zq8C8VXIjxhJfKjzLY6Aqc_jqB4TVm-K3TsmKZocpnCx8H39XvnkJ_MK3hM_ATkAxvN0Lxkhf9WdvLWIC4KEeKaeQ_rSl5IlMgh7hPH_wB4RxisIlWd7K1DlMscEMGUDg1ut0XoUG_JC66Sb_6zyDNKBL6O1rkfEmGBvkMq-g7UcQZ0_KyfPOSjklDruHBEQVIZ15pXo5O9qy4kSteRHrB6XzBRRJEigQhRzfScyXSuhMJ9XP8OTNDeBzRvKAY2bow-_IEQZb0oGwH1YVEsNAF3n7ZeGlE3qGcPRzHy6KIor57Hj9qRGymYV8H3rFqOrzv6uQnHRA2q47Fp0vwTRuPdhqZVU-5fP2UjgD_aRE7de0I1K5D6ZtopOqk8ptKqTP507cAPhxRhnUmWjl9Ep4sToOkiniZz00aNkp69hmhmMxv17w1VUFHaD-jV3GjvvAfQ2_nv5JnYKggQ-BV-m70wPhMrqzyBEDZs8fNkGp4NgsvEi3eIKwQqxDzkDbkL997RMgE39corjNegG9Ks2IVFQlknE_EJtGb1CR9gvUS84C9mJvvBS-WBoV6UKtkj5rcv-imIm5CAW0zWZ89JuZtt4sgzxQ

Can you see what i might have missed?

```
  cluster_addons = {
    ...
    aws-ebs-csi-driver = {
      resolve_conflicts        = "OVERWRITE"
      service_account_role_arn = module.ebs_csi_irsa.iam_role_arn
    }

  }
  
  module "ebs_csi_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 4.12"

  role_name             = "${local.cluster_name}-ebs-csi"
  attach_ebs_csi_policy = true

  oidc_providers = {
    ex = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:aws-ebs-csi-driver"]
    }
  }

  tags = local.tags
}
 ```
 
My best guess is that the above module is not enough, I cannot see the serviceaccount that corresponds to the role `aws-ebs-csi-driver` in my k8s cluster.
 
 ```
 {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::700849607999:oidc-provider/oidc.eks.eu-west-2.amazonaws.com/id/B02660CC7E55090032325E1CD715816B"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.eu-west-2.amazonaws.com/id/B02660CC7E55090032325E1CD715816B:aud": "sts.amazonaws.com",
                    "oidc.eks.eu-west-2.amazonaws.com/id/B02660CC7E55090032325E1CD715816B:sub": "system:serviceaccount:kube-system:aws-ebs-csi-driver"
                }
            }
        }
    ]
}
```

 **kubectl get serviceaccounts -n kube-system | grep "ebs*"**
```
ebs-csi-controller-sa                       1         3d22h
ebs-csi-node-sa   
```

**I just want to confirm that am i right in thinking i still need to  create this serviceaccount. `aws-ebs-csi-driver` and attach the role to it? Or should that have been taken care of already by the setup of the cluster?**

```
resource "kubernetes_service_account" "ebs_csi_driver" {
  metadata {
    name      = local.service_account_name
    namespace = local.service_account_namespace
    annotations = {
      "eks.amazonaws.com/role-arn" = module.ebs_csi_irsa.iam_role_arn
    }
  }
}
```

**Comment by kaykhancheckpoint** [comment]
Oh i just spotted what might be issue, https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html

The service account should be named  `ebs-csi-controller-sa`
https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/examples/iam-role-for-service-accounts-eks/main.tf#L84-L98

**Comment by gfrid** [comment]
can you post here the complete working code please
