### ISSUE TITLE
update to v18 error: "name_prefix" cannot be less than 3 characters

### ISSUE THREAD

**Issue by geoffcline** [terraform-aws-modules/terraform-aws-eks#1990]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
- v18.19.0

- Terraform version:

Terraform v1.1.7
- Provider version(s):
- provider registry.terraform.io/hashicorp/aws v4.8.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.9.0
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/tls v3.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]

```
terraform {
  required_providers {
    local = {
      source = "hashicorp/local"
    }
  }
}

variable "cluster_name" {
  description = "The name of the cluster"
  type        = string
  default = "april-tf2"
}

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = var.cluster_name
  cidr = "10.0.42.0/23"
  secondary_cidr_blocks = ["100.64.0.0/16"]

  azs             = ["us-east-2a", "us-east-2b"]
  private_subnets = ["10.0.42.0/28","10.0.42.16/28", "100.64.0.0/16"]
  public_subnets = ["10.0.43.0/28","10.0.43.48/28"]

  enable_nat_gateway     = true
  single_nat_gateway     = true
  one_nat_gateway_per_az = false

  private_subnet_tags = {
    "kubernetes.io/cluster/${var.cluster_name}" = "owned"
  }
}

module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"

  cluster_version = "1.21"
  cluster_name    = var.cluster_name
  vpc_id          = module.vpc.vpc_id
  subnet_ids         = module.vpc.private_subnets
  enable_irsa     = true

  # Only need one node to get Karpenter up and running
  self_managed_node_groups = [
    {
      instance_type = "t3a.medium"
      asg_max_size  = 1
    }
  ]

  tags = {
    "karpenter.sh/discovery" = var.cluster_name
  }
}
```

1. apply with eks module version <18. 
2. change to eks module version ~> 18.
3. updated based on https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-18.0.md
4. clear state, init, then plan 

## Expected behavior

The plan to successfully generate. 

## Actual behavior

The plan fails to generate. 

```
│ Error: "name_prefix" cannot be less than 3 characters
│
│   with module.eks.module.self_managed_node_group["0"].aws_launch_template.this[0],
│   on .terraform/modules/eks/modules/self-managed-node-group/main.tf line 55, in resource "aws_launch_template" "this":
│   55:   name_prefix = var.launch_template_use_name_prefix ? "${local.launch_template_name_int}-" : null
```

### Terminal Output Screenshot(s)

<img width="967" alt="Screen Shot 2022-04-05 at 3 10 26 PM" src="https://user-images.githubusercontent.com/5782953/161840667-479e6614-b47c-4218-8c98-c81c7704b5b9.png">

**Comment by geoffcline** [comment]
relevant error

```
│ Error: **"name_prefix" cannot be less than 3 characters**
│
│   with module.eks.module.self_managed_node_group["0"].aws_launch_template.this[0],
│   on .terraform/modules/eks/modules/self-managed-node-group/main.tf line 55, in resource "aws_launch_template" "this":
│   55:   **name_prefix** = var.launch_template_use_name_prefix ? "${local.launch_template_name_int}-" : **null**
```

this seems contradictory to me, if `var.launch_template_use_name_prefix` is false, then `null` is used, and isn't that <3 chars?

**Comment by bryantbiggs** [comment]
this:
```hcl
self_managed_node_groups = [
    {
      instance_type = "t3a.medium"
      asg_max_size  = 1
    }
  ]
```

should be changed to something like this: 
```hcl
self_managed_node_groups = {
    karpenter = {
      instance_type = "t3a.medium"
      asg_max_size  = 1
    }
  }
```

**Comment by bryantbiggs** [comment]
also, if you're looking to get started with Karpenter using the modules provided here https://github.com/clowdhaus/eks-reference-architecture/tree/main/karpenter

just FYI

**Comment by geoffcline** [comment]
thank you!
