### ISSUE TITLE
Unnecessary extra volume attachment

### ISSUE THREAD

**Issue by anbotero** [terraform-aws-modules/terraform-aws-eks#1993]
## Description

Perhaps not really an _issue_ itself but a misunderstanding, but [from what](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html) I understood, as long as in the `block_device_mappings` I referenced the same device name, I could override the settings of the root volume from an AMI. I just tried doing that for the volume of a Node Group I created, and it does replace the root volume with my new settings (**gp3**), yet the generated instance also now has another **gp2** volume attached and pointing to `/dev/xvdb`.

I don't understand where it's coming from, and I don't want it. 

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: `v18.19.0`

- Terraform version: `v1.1.7`

- Provider version(s): `4.8.0`

## Reproduction Code [Required]

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18"

  cluster_name                    = "myclustername"
  cluster_version                 = "myclusterversion"
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  cluster_addons = {
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts        = "OVERWRITE"
    }
  }

  vpc_id = data.terraform_remote_state.vpc.outputs.vpc_id
  subnet_ids = [
    data.terraform_remote_state.vpc.outputs.private_subnets[0],
    data.terraform_remote_state.vpc.outputs.private_subnets[1]
  ]

  eks_managed_node_group_defaults = {
    ami_type                     = "BOTTLEROCKET_x86_64"
    iam_role_attach_cni_policy   = true
    iam_role_additional_policies = ["arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"]
  }

  eks_managed_node_groups = {
    saas = {
      min_size     = 1
      max_size     = 1
      desired_size = 1

      capacity_type  = "SPOT"
      instance_types = ["t3a.small", "t3.small", "t2.small"]

      block_device_mappings = {
        root = {
          # Device name changes depending on the instance type
          # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html
          device_name = "/dev/xvda"
          ebs = {
            delete_on_termination = true
            throughput            = 150
            volume_size           = 20
            volume_type           = "gp3"
          }
        }
      }
    }
  }
}
```

- Clear workspace.
- `terraform init` before starting
- `terraform plan -out=tfplan`
- `terraform apply tfplan`

## Expected behavior

Instances from Node Groups should only have a **single** gp3 volume attached to `/dev/xvda`.

## Actual behavior

Instances from Node Groups get **a second** gp2 volume attached to `/dev/xvdb` aside from the root gp3 volume attached to `/dev/xvda` .

### Terminal Output Screenshot(s)

From inside the instance, with Session Manager:
```
bash-5.1# lsblk
NAME     MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
loop0      7:0    0  280K  1 loop /x86_64-bottlerocket-linux-gnu/sys-root/usr/share/licenses
loop1      7:1    0 11.6M  1 loop /local/var/lib/kernel-devel/.overlay/lower
                                  /var/lib/kernel-devel/.overlay/lower
xvda     202:0    0   20G  0 disk
|-xvda1  202:1    0    4M  0 part
|-xvda2  202:2    0    5M  0 part
|-xvda3  202:3    0   40M  0 part /boot
|-xvda4  202:4    0  920M  0 part
|-xvda5  202:5    0   10M  0 part
|-xvda6  202:6    0   25M  0 part
|-xvda7  202:7    0    5M  0 part
|-xvda8  202:8    0   40M  0 part
|-xvda9  202:9    0  920M  0 part
|-xvda10 202:10   0   10M  0 part
|-xvda11 202:11   0   25M  0 part
`-xvda12 202:12   0   42M  0 part /local/var/lib/bottlerocket
                                  /var/lib/bottlerocket
xvdb     202:16   0   20G  0 disk
`-xvdb1  202:17   0   20G  0 part /var
                                  /opt
                                  /mnt
                                  /local
```

**Comment by bryantbiggs** [comment]
hi @anbotero - yes, bottlerocket creates 2 volumes. you can see more here https://github.com/bottlerocket-os/bottlerocket/issues/1203

**Comment by anbotero** [comment]
> hi @anbotero - yes, bottlerocket creates 2 volumes. you can see more here [bottlerocket-os/bottlerocket#1203](https://github.com/bottlerocket-os/bottlerocket/issues/1203)

Excellent. Thanks a lot for the clarification, and apologies for the Issue. 😅

**Comment by bryantbiggs** [comment]
no worries!
