### ISSUE TITLE
aws_auth configmap as output in main module

### ISSUE THREAD

**Issue by nickvanwegen** [terraform-aws-modules/terraform-aws-eks#2002]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

I have upgraded to the new module version to migrate to the new managed aws_auth configmap. 

Tho I need to use a depends_on block for some of my resources on this configmap. 
I use AWS-loadbalancer-controler and i need the configmap to exist when I destroy my environment (I run it in ci/cd for e2e testing)
if the configmap is deleted before the LB-controller wants to delete its resources it created it fails to do so. 

Now with the new managed aws_auth function the configmap is deleted before the LB controller.

## Describe the solution you'd like.

get the configmap resources as output of the main module so you can use the output as a depends_on resource.

**Comment by bryantbiggs** [comment]
The `depends_on` doesn't use outputs, however, I think you will find that with the use of data sources elsewhere in this module that you won't be able to depend on anything used in this module

**Comment by nickvanwegen** [comment]
Hmm maybe I am not using the right words my bad for that. 

An example of what I had in the v18 version before the managed aws_auth function was this. 

```
  depends_on = [

    module.eks.aws_auth_configmap_yaml,
  ]
```

And that worked. That is why my question was pointed towards outputs. But maybe I am not understanding something here?

**Comment by bryantbiggs** [comment]
> Hmm maybe I am not using the right words my bad for that.
> 
> An example of what I had in the v18 version before the managed aws_auth function was this.
> 
> ```
>   depends_on = [
> 
>     module.eks.aws_auth_configmap_yaml,
>   ]
> ```
> 
> And that worked. That is why my question was pointed towards outputs. But maybe I am not understanding something here?

1. If you don't use that depends on block, does it still work? 
2. I've never seen it work like this but if it does, then what you are actually depending on is:
```hcl
	depends_on = [
		module.eks_managed_node_group,
		module.self_managed_node_group,
		module.fargate_profile,
	]
```

**Comment by nickvanwegen** [comment]
1. It will work without the depens_on block but then the configmap will be deleted before the LB-controller deletes its services which will result in a failed destroy. 
2. That makes sense yes but what I am looking for is a way to let there be a depends_on the creating of the aws_auth configmap. 

So i also tested to put the depends_on the self_managed_node_group and try a delete and this does not do the trick. 
One of the first things TF does when running the destroy command is empty the aws_auth configmap.

**Comment by bryantbiggs** [comment]
the output `aws_auth_configmap_yaml` is just text - its simply a [template](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/templates/aws_auth_cm.tpl) that is [rendered](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/cd8731ec5a659fa7e3f31555bc558e4fd3dedc5d/outputs.tf#L186). It was put in place to help with the transition from v17.x where the management of the configmap was removed - so no, Terraform was not destroying the configmap prior to v18.20

**Comment by nickvanwegen** [comment]
No thats correct but having the output on the upstream module makes it so that i can tune the way Tf handles the destroy and creation of this resource. 

In the v17 verions there was a similar output which could be used. in the v18 prior to v18.20 as-well 
I guess i could still use the output but its marked as deprecated so i dont know how long this will be around :D

Anyway thats the only reason for my request of the output i myself see no other way on depending on the creating of the configmap. Other then doing it myself which for what ill need to keep the configmap output if possible

**Comment by bryantbiggs** [comment]
Like I said, you aren't depending on the configmap but instead depending on:
```hcl
	depends_on = [
		module.eks_managed_node_group,
		module.self_managed_node_group,
		module.fargate_profile,
	]
```

`aws_auth_configmap_yaml` is being removed in v19.x

**Comment by atamgp** [comment]
@nickvanwegen  I understand your issue.
Currently the output `aws_auth_configmap_yaml` is indeed just a template and not the real `kubernetes_config_map.aws_auth` resource in the module. You would need a dependency on that.

The resource it self also has no dependencies which means that upon module deletion, this is deleted instantly.
This mean, that any k8s resource you add to the module needs to be cleaned up before the module deletion is triggered.

I suspect that the earlier `config_map_aws_auth` output was indeed the resource exposed making this work.
Now, you will need to depend on the whole module (which is inefficient).
