### ISSUE TITLE
Security group tags created by EKS could be overridden

### ISSUE THREAD

**Issue by pcheung-sfdc** [terraform-aws-modules/terraform-aws-eks#2006]
## Description

Starting with 18.14.0, this introduced a [resource](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/7369f8a19e3966b1edafa9cead972fbad6b56f80/main.tf#L62) to override tags of the cluster primary SG. This could be used to override a tag used by EKS to delete the SG when destroying the cluster, leaving the SG lingering and unmanaged, which can prevent destroying the VPC it's in.

- [ X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 18.14.0 and above

- Terraform version: v1.1.7

- Provider version(s): ~v4.0

## Reproduction Code [Required]

Pass in a "Name" tag to the module like for example:
```  
module "eks" {
...
  tags = {
    Name = "foo"
  }
}
```

## Expected behavior

The cluster primary SG is automatically generated when creating an EKS cluster is also automatically removed when destroying the cluster.

## Actual behavior

The cluster primary SG is not being destroyed if its tags are overridden.

**Comment by bryantbiggs** [comment]
you should be able to re-override using `cluster_tags`

**Comment by pcheung-sfdc** [comment]
Any good reason not to set the cluster_tags? 
If not, I can create a PR to specify the `cluster_tags`

**Comment by bryantbiggs** [comment]
No - we try to provide an "additional" tag for select resources where users might want to provide tags specific to that resource. `var.tags` is generic across all resources and `var.cluster_tags` is applied to just the cluster (i.e. - control plane)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.20.2 :tada:
