### ISSUE TITLE
Multiple Regions: Support `provider=`

### ISSUE THREAD

**Issue by darrenfurr** [terraform-aws-modules/terraform-aws-eks#2016]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform]
  - Yes ✅:  multiple providers: https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations

## Is your request related to a problem? Please describe.
- Not really. I would like to spin up 2 EKS clusters, 1 in 1 region & the other in another region.

## Describe the solution you'd like.
```
module "eks" {
  provider = aws.secondary
  source                          = "terraform-aws-modules/eks/aws"
```

## Describe alternatives you've considered.
- I copied the module into another folder & run TF from that folder on an EC2 in that region

**Comment by bryantbiggs** [comment]
This is already possible today using:

```hcl
# will use default AWS provider
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  ...
}

module "eks_oregon" {
  source  = "terraform-aws-modules/eks/aws"
  
  providers = {
    aws = aws.uswest2
  }
}

module "eks_virginia" {
  source  = "terraform-aws-modules/eks/aws"
  
  providers = {
    aws = aws.useast1
  }
}
```

**Comment by darrenfurr** [comment]
Nice! I looked in the docs & didn't see this option! Thank you
