### ISSUE TITLE
Multiple Providers (Self Managed Node Groups): Fails to create ASG Launch Templates

### ISSUE THREAD

**Issue by darrenfurr** [terraform-aws-modules/terraform-aws-eks#2019]
- [ X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions
- Module version [Required]:
`18.20.2`
- Terraform version:
`1.1.3`
- Provider version(s):
`aws 4.20.0` 

## Reproduction Code [Required]
Attempting to add a second EKS cluster in alternate region.
I have two modules that are identical with a few exceptions (see below)...

Snippet:
```
module "eks" {
  source                          = "terraform-aws-modules/eks/aws"
  providers = {
    aws = aws.primary
  }

  create                          = true
  cluster_name                    = "${local.prefix}-eks"
  cluster_version                 = "1.21"
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true
  subnet_ids                      = data.aws_subnets.private.ids
  vpc_id                          = data.aws_vpc.selected.id
  enable_irsa                     = true
  tags                            = local.tags
  create_iam_role                 = false
  iam_role_arn                    = data.aws_iam_role.eks_admin.arn
  iam_role_name                   = data.aws_iam_role.eks_admin.name

`...other configs removed for brevity`

self_managed_node_groups = {
    general = {
      name                     = "general"
      instance_type            = var.eksInstanceTypeMap["general"]
      desired_size             = 1
      min_size                 = 1
      max_size                 = var.eksMaxAsgMap["general"]
      key_name                 = ""
      tags                     = local.worker_tags
      post_bootstrap_user_data = file("./scripts/init.sh")
      enable_monitoring        = false
      create_security_group    = false
    }
  }
}
```

The other module is identical, just called `eks_secondary`: providers is set for aws.secondary, subnet_ids, vpc_ids, & vpc_security_group_ids...

Are you using workspaces?
- No

Have you cleared the local cache (see Notice section above)? 
- Yes

List steps in order that led up to the issue you encountered 
- The first EKS module creates/updates successfully.

## Expected behavior
- Launch Templates create/update successfully for both EKS clusters

## Actual behavior
- The second EKS module creates the Control Plane, but the Launch Templates fail to create/update.
`Auto Scaling Group: ValidationError: You must use a valid fully-formed launch template`

### Terminal Output Screenshot(s)
```
2022-04-14T17:51:51.6247053Z Error: Error updating Auto Scaling Group: ValidationError: You must use a valid fully-formed launch template. The requested configuration is currently not supported. Please check the documentation for supported configurations.
2022-04-14T17:51:51.6248373Z 	status code: 400, request id: 69832f67-d45e-40ca-a94a-80770ab7f79d
2022-04-14T17:51:51.6248658Z 
2022-04-14T17:51:51.6249214Z   with module.eks_secondary.module.self_managed_node_group["general"].aws_autoscaling_group.this[0],
2022-04-14T17:51:51.6250213Z   on .terraform/modules/eks_secondary/modules/self-managed-node-group/main.tf line 265, in resource "aws_autoscaling_group" "this":
2022-04-14T17:51:51.6250959Z  265: resource "aws_autoscaling_group" "this" {
```

## Additional context
The Launch Templates do create successfully, just not the AutoScaling Groups

**Comment by bryantbiggs** [comment]
I would not recommend to control multiple regions in one state unless its dictated by the service (i.e. - CloudFront, Global Accelrator, etc. that have to be deployed through us-east-1). These are not issues  related to the module but related to the use of multiple regions in one state file (i.e. - all data sources and supporting resources will need their alias equivalent, data sources do not inherit their region from where they are used)

**Comment by darrenfurr** [comment]
@bryantbiggs - thank you for your response, but why support providers in your module at all then?

If I want to spin up a truly multi-region infra (like other AWS services: rds, docdb, elasticache, etc) with primary & secondary region then 1 TF state should be acceptable.

Shouldn’t this be a Feature Request & not just a closed question?

**Comment by bryantbiggs** [comment]
There isn't any additional support required by the module to do what you are trying to do. This module can be stamped out into multiple regions from the same statefile/root. However, in general I would not recommend that because if any region goes down or experiences network connectivity issues, then you just wiped out your ability to make changes (Terraform will fail to read the impacted region and fail to plan/apply). More importantly, its clear you are not familiar with how this is done. Please take the time to investigate further on your own if this is the route you wish to proceed with, however, there are no changes required with this module to achieve this

**Comment by darrenfurr** [comment]
@bryantbiggs - I am very familiar with Terraform, state files, & how it operates with the AWS APIs. 

I understand your recommendation, but also understand how global clusters (RDS, docdb, elasticache) work with replication. And per Terraforms own [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_global_cluster#new-documentdb-global-cluster), they use providers to establish the read replicas in another region.
I was attempting to implement the same pattern with this EKS module. 

You state, `"This module can be stamped out into multiple regions from the same statefile/root".`
However, clearly it does not -- because I'm running into the error above & am unable to create an AutoScaling Group.

IF you do not want to support it - that is fine. 
I would prefer that you just state that **clearly in the docs for this module** vs me wasting my time & your time.

**Comment by bryantbiggs** [comment]
again, there is nothing preventing this module from supporting aliased providers. 

if I had to guess, you are not syncing your data sources to your alias and therefore they are unable to find the appropriate resources in the other region which is not a module issue but a user issue:
```
subnet_ids                      = data.aws_subnets.private.ids
vpc_id                          = data.aws_vpc.selected.id
```

**Comment by darrenfurr** [comment]
Follow-up on this -- the issue was **not the module**, but the launch template. I was attempting to create an ASG with m6a or c6a nodes, but they do not support ebs optimized in us-east-2.

Not a great error from the AWS APIs
