### ISSUE TITLE
kubeconfig file not being written

### ISSUE THREAD

**Issue by aimanparvaiz** [terraform-aws-modules/terraform-aws-eks#202]
# I have issues

## I'm submitting a...

* [* ] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I am seeing the kubeconfig file content as output but it's not being written to disk. I have AWS_PROFILE set and I am assuming a role mentioned in the .envrc file. Everything works as expected except the kubeconfig file being written to disk. By default write_kubeconfig is true and I am not changing that or the path, also if I copy the kubeconfig content from terraform output and put it in a file I am able to use kubectl.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
module "eks" {
  source = "repo link"
  cluster_name = "core-dev-eks"
  vpc_id = "vpc_id"
  subnets = "subnets"
  worker_group_count = 1
  worker_groups = "${local.worker_groups}"
  tags = {
    Terraform = "true"
    Environment = "dev"
  }

}
  worker_groups = [
    {
      instance_type = "t2.xlarge"
      asg_max = 4
      autoscaling_enabled = true
      asg_desired_capacity = 3
      autoscaling_enabled = true
      subnets = "private_subnets"
    }
  ]
}
Post successfully apply I dont see kubeconfig file in the `./` path.
## What's the expected behavior?
See kubeconfig file in the current dir

## Environment details

* Affected module version: 1.8.0
* OS: macOS 10.14.1
* Terraform version: v0.11.10

**Comment by stijndehaes** [comment]
If you retry terraform apply a second time is the file written the second time?

**Comment by max-rocket-internet** [comment]
OK cool so mystery solved, right?
