### ISSUE TITLE
Adding IAM policy to IAM role of EKS

### ISSUE THREAD

**Issue by victoryeo** [terraform-aws-modules/terraform-aws-eks#2020]
I use module "eks" in terraform script. It has node_groups. But i am not able to add IAM policy to IAM role of the EKS cluster. I want to add AWS EBS CSI policy to the IAM role of the EKS cluster.

## Is your request related to a new offering from AWS?
No

Is this functionality available in the [AWS provider for Terraform]
Yes

(https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.

  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
Yes, i want to add IAM policy to an IAM role.

## Describe the solution you'd like.
Adding IAM policy to IAM role

## Describe alternatives you've considered.
The alternative is , i manually go to AWS management console and IAM console, click on the IAM role, then manually add the IAM policy to it.

**Comment by bryantbiggs** [comment]
You can see how to achieve this with our examples https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L357-L362

However, I would recommend you use our EBS CSI IRSA role which gets attached to the EBS CSI driver addon instead https://github.com/terraform-aws-modules/terraform-aws-iam/blob/5b792f24f420f28684ea3c26c075b5d44fdcac1d/examples/iam-role-for-service-accounts-eks/main.tf#L84-L98
