### ISSUE TITLE
how to use existing AWS SG & IAM role for node group?

### ISSUE THREAD

**Issue by Epic55** [terraform-aws-modules/terraform-aws-eks#2021]
## Description
Hi, i used the code from EKS module examples. I wrote a code to use existing security group & iam role for a node group, but terraform creates a new SG & IAM role. How to correctly write such code? I tried to write code in 3 blocks of code: in self_managed_node_group_defaults{}, in self_managed_node_groups {}, above it. Nothing helped.
With Cluster SG & IAM role everything is all right.

## Versions
- Module version [Required]: 18.20.2
- Terraform version: v1.1.8
- Provider version(s): aws v4.9.0

## Reproduction Code [Required]
```
...
    create_node_security_group = false
    node_security_group_id = "..."
    node_security_group_name = "..."
    create_iam_role = false
    iam_role_name = "eks-node-role"
    iam_role_arn = "arn:aws:iam::...:role/eks-node-role"
    ...
self_managed_node_group_defaults = {
    create_node_security_group = false
    node_security_group_id = "..."
    node_security_group_name = "..."
    create_iam_role = false
    iam_role_name = "eks-node-role"
    iam_role_arn = "arn:aws:iam::...:role/eks-node-role"
    ...
  }
self_managed_node_groups = {
    create_node_security_group = false
    node_security_group_id = "..."
    node_security_group_name = "..."
    create_iam_role = false
    iam_role_name = "eks-node-role"
    iam_role_arn = "arn:aws:iam::...:role/eks-node-role"
    ....
  }
```
## Steps to reproduce the behavior:
add the code above to eks module code to deploy eks with terraform eks module

## Expected behavior
terraform uses existing security group and iam role for node group

## Actual behavior
terraform tries to create a new security group and new iam role for node group

**Comment by iaacautomation** [comment]
Those variables are not part of "node_group" blocks but the default module block

**Comment by bryantbiggs** [comment]
Hi @iaacautomation - we need a complete reproduction

**Comment by Epic55** [comment]
my code:
```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.20.2"
  cluster_name    = "my-cluster"
  cluster_version = "1.21"
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false
  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }
  vpc_id     = var.vpc_id
  subnet_ids = var.private_subnets

  create_cluster_security_group = false
  cluster_security_group_id = var.security_group

  create_node_security_group = false
  node_security_group_id = var.security_group

  create_iam_role = false
  iam_role_name = "eks-cluster-role"
  iam_role_arn = "arn:aws:iam::...:role/eks-cluster-role"
  enable_irsa = false

  self_managed_node_group_defaults = {
    instance_type                          = "t2.small"
    update_launch_template_default_version = true
  }
  self_managed_node_groups = {
    mygroup1 = {
      name         = "test-1"
      max_size     = 2
      desired_size = 1
      use_mixed_instances_policy = true
      mixed_instances_policy = {
        instances_distribution = {
          on_demand_base_capacity                  = 0
          on_demand_percentage_above_base_capacity = 10
          spot_allocation_strategy                 = "capacity-optimized"
        }
        override = [
          {
            instance_type     = "t2.small"
            weighted_capacity = "1"
          },
          {
            instance_type     = "t2.small"
            weighted_capacity = "2"
          },
        ]
      }
    }
  }
  manage_aws_auth_configmap = true
  aws_auth_users = [
    {
      userarn  = "arn:aws:iam::....:user/....m"
      username = "..."
      groups   = ["system:masters"]
    }
  ]
  aws_auth_accounts = [
    "..."
  ]
}
```

**Comment by Epic55** [comment]
I figured out that if in main code block i remove:
`create_node_security_group = false`
terraform will create 25 objects, including this:
```
module.eks.module.eks.module.self_managed_node_group["mygroup1"].aws_security_group.this[0]
module.eks.module.eks.aws_security_group.node[0]
```
If i set parameter above, Terraform will create 14 objects. So this parameter works. 
It means these 2 parameters:
```
node_security_group_id = ""
node_security_group_name = ""
```
dont work.
Terraform tries to create this:
module.eks.module.eks.aws_security_group.node[0]

**Comment by bryantbiggs** [comment]
so it looks like you are missing the configs for `self_managed_node_group_defaults` or `self_managed_node_groups`. You should add:

- `create_iam_instance_profile = false` # since you are using self managed node groups
- `iam_instance_profile_arn = xxx`
- `create_security_group = false`
- `vpc_security_group_ids=[xxx]`

**Comment by Epic55** [comment]
Thanks, it helped, but now i have this error:
`Error: unexpected EKS Add-On (my-cluster:coredns) state returned during creation: timeout while waiting for state to become 'ACTIVE' (last state: 'DEGRADED', timeout: 20m0s)`

**Comment by Epic55** [comment]
Any suggestions why do i have errors above?

**Comment by Epic55** [comment]
@bendyna-vitalii 
```
  create_iam_role = false
  iam_role_name = "eks-cluster-role"
  iam_role_arn = "arn:aws:iam::111222333444:role/eks-cluster-role"
  
  eks_managed_node_group_defaults = {
    create_iam_role = false
    iam_role_name = "eks-node-role"
    iam_role_arn = "arn:aws:iam::111222333444:role/eks-node-role"
```

**Comment by Epic55** [comment]
`Post "http://localhost/api/v1/namespaces/kube-system/configmaps": dial tcp [::1]:80: connect: connection refused`
I solved this issue, i didn't use k8s provider, this was my error.

`Error: unexpected EKS Add-On (my-cluster:coredns) state returned during creation: timeout while waiting for state to become 'ACTIVE' (last state: 'DEGRADED', timeout: 20m0s)`
I still have this issue with self managed group. With EKS managed group i don't have such issue.
EKS managed group works fine, so i m closing topic.
