### ISSUE TITLE
Multiple Instance type not adding in the eks module for asg

### ISSUE THREAD

**Issue by sushilalert** [terraform-aws-modules/terraform-aws-eks#2025]
## Description

Trying to add multiple instance types through eks module so that it can select other instance types if one is not available. But it is giving the error:

instance_types       = !each.value["set_instance_types_on_lt"] ? each.value["instance_types"] : null

inappropriate-value-for-attribute-name-string-required

**Comment by bryantbiggs** [comment]
please complete the issue template as its written in order for us to be able to help you resolve any questions/issues
