### ISSUE TITLE
[Question] self managed node groups volume size

### ISSUE THREAD

**Issue by aliartiza75** [terraform-aws-modules/terraform-aws-eks#2027]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

There are two ways in the **self manage node groups** main.tf file, which can be used to specify the size of the volume for a node group.

1. [**Method 1**: disk_size](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/681e00aafea093be72ec06ada3825a23a181b1c5/examples/self_managed_node_group/main.tf#L219)

2. [**Method 2**: block_device_mappings](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/681e00aafea093be72ec06ada3825a23a181b1c5/examples/self_managed_node_group/main.tf#L230)

After looking at the [node_groups.tf](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf) and [self_managed_node_group](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/self-managed-node-group/main.tf) module file. I am assuming that it is not being used anywhere.

Secondly, in method 1 I don't have options to change volume specifications i.e encryption, volume type, etc.

I have 2 questions:

1. What is the purpose of **disk_size**?
2. if we can create a volume using the **block_device_mappings** param then is it necessary to keep disk_size in the example because it is causing confusion?

## Describe the solution you'd like.

I think only 1 method should be used to specify the size of the volume because only disk_size doesn't provide much flexibility.

## Describe alternatives you've considered.

NIL

## Additional context

NIL

**Comment by aliartiza75** [comment]
@bryantbiggs sure. Another suggestion:

It would be good to add [this](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2023#issuecomment-1101621165) in the examples provided.

**Comment by bryantbiggs** [comment]
The use of `disk_size` in examples was updated in #2034
