### ISSUE TITLE
kube-system always in a pending state

### ISSUE THREAD

**Issue by vovkanaz** [terraform-aws-modules/terraform-aws-eks#203]
# I have issues
kubectl get all --all-namespaces
NAMESPACE     NAME                            READY     STATUS    RESTARTS   AGE
kube-system   pod/kube-dns-64b69465b4-5wr8b   0/3       Pending   0          8m

## I'm submitting a...

* [x] bug report

## What is the current behavior?
After creating an EKS cluster with a help of this module, cluster always  stay in a pending state

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Setup new cluster, with existing VPC and 2 subnets inside of it

## What's the expected behavior?
Cluster in a READY state

## Are you able to fix this problem and submit a PR? Link here if you have already.
Try to use this documentation, and all works like a charm
https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html#eks-master-cluster-iam-role

## Environment details
AWS EKS Kubernetes 1.10

* Affected module version: latest
* OS: Centos 7.5
* Terraform version:
Terraform v0.11.10
+ provider.aws v1.50.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.random v1.3.1
+ provider.template v1.0.0

**Comment by vovkanaz** [comment]
Yes, this example works. We used this example for our needs and try to implement existing vpc with 2 subnets inside, and got pending state... So we'll try to understand what's going on with our existing VPC, thank you!

**Comment by vovkanaz** [comment]
module "eks" {
  source                               = "../.."
  cluster_name                         = "${local.cluster_name}"
  subnets                              = ["${var.private_subnets}"]
  tags                                 = "${local.tags}"
  vpc_id                               = "${var.vpc_id}"
  worker_groups                        = "${local.worker_groups}"
  worker_group_count                   = "2"
  worker_additional_security_group_ids = ["${aws_security_group.all_worker_mgmt.id}"]
  #map_roles                            = "${var.map_roles}"
  #map_users                            = "${var.map_users}"
  #map_accounts                         = "${var.map_accounts}"
}

variable "vpc_id" {
  default = "vpc_id"
  }

variable "private_subnets" {
    type    = "list"
    default = ["subnet-id2", "subnet-id1"]
}

NAMESPACE     NAME                            READY     STATUS    RESTARTS   AGE
kube-system   pod/kube-dns-64b69465b4-l2jwm   0/3       Pending   0          2m

describe

Volumes:
  kube-dns-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-dns
    Optional:  true
  kube-dns-token-4lksf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-dns-token-4lksf
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  39s (x26 over 6m)  default-scheduler  no nodes available to schedule pods

**Comment by marcelloromani** [comment]
@vovkanaz I've seen this behaviour and in our cause it boiled down to the aws auth config map not being deployed due to a timeout, therefore the nodes didn't join the cluster, and all PODs remained in pending state for lack of worker nodes.

If you `describe` the POD and look at the start up log of the worker nodes you should be able to figure out what's wrong.

I hope this will be of help to you.

**Comment by max-rocket-internet** [comment]
OK closing as requested. For the future, you should `describe` the resource to see details about its state. This will tell you why a pod is `Pending` 🙂

**Comment by NeoTech** [comment]
I have kube-system pending pods WITH the nodes accessing the cluster, so they show up as nodes when issuing kubectl get nodes. The pods are running when you describe them and you can login into them but the readyness probe doesn't seem to pick them up.

**Comment by ricktbaker** [comment]
@NeoTech I am having this exact problem.   Did you ever figure out a solution?   Pods are running, but they are showing as pending
