### ISSUE TITLE
min_size & desired_size

### ISSUE THREAD

**Issue by dmitry-mightydevops** [terraform-aws-modules/terraform-aws-eks#2030]
## Description

```
eks_managed_node_groups = {
  ops-v1 = {
    min_size       = 1
    max_size       = 5
    desired_size   = 1
    ...
    instance_types = ["m5.large"]
  }
```

the group is created. I change the desired_size 1 -> 2, run apply and nothing. It doesn't detect the change because of the following code for the [node group](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/5815d17cd2330286250ea4f81fcad3ac9bf19776/modules/eks-managed-node-group/main.tf#L340)

```
lifecycle {
    create_before_destroy = true
    ignore_changes = [
      scaling_config[0].desired_size,
    ]
  }
```

I then try to do

```
eks_managed_node_groups = {
  ops-v1 = {
    min_size       = 2
    max_size       = 5
    desired_size   = 2
    ...
    instance_types = ["m5.large"]
  }
```

and apply fails with the following error:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.eks_cluster.module.eks_cluster.module.eks_managed_node_group["ops-v1"].aws_eks_node_group.this[0] will be updated in-place
  ~ resource "aws_eks_node_group" "this" {
        id              = "project-prod-eks:prod-ops-v1"
        tags            = {
            "Name"                                = "prod-ops-v1"
            "created"                             = "4/18/2022"
            "environment"                         = "prod"
            "updated"                             = "4/18/2022"

        }
        # (15 unchanged attributes hidden)


      ~ scaling_config {
          ~ min_size     = 1 -> 2
            # (2 unchanged attributes hidden)
        }


        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions in workspace "prod"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.eks_cluster.module.eks_cluster.module.eks_managed_node_group["ops-v1"].aws_eks_node_group.this[0]: Modifying... [id=project-prod-eks:prod-ops-v1]
╷
│ Error: error updating EKS Node Group (project-prod-eks:prod-ops-v1) config: InvalidParameterException: Minimum capacity 2 can't be greater than desired size 1
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "21006d45-9a28-40ec-8d06-0205d6abc95d"
│   },
│   ClusterName: "project-prod-eks",
│   Message_: "Minimum capacity 2 can't be greater than desired size 1",
│   NodegroupName: "prod-ops-v1"
│ }
│ 
│   with module.eks_cluster.module.eks_cluster.module.eks_managed_node_group["ops-v1"].aws_eks_node_group.this[0],
│   on .terraform/modules/eks_cluster.eks_cluster/modules/eks-managed-node-group/main.tf line 272, in resource "aws_eks_node_group" "this":
│  272: resource "aws_eks_node_group" "this" {
│ 
╵
make: *** [Makefile:38: apply] Error 1

```

So the only way to overcome it is
- modify ASG manually in GUI or via AWS cli
- create a new "node-group" with different basic settings.

Is this considered a bug?

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 

- Terraform version: 1.1.8
- Provider version(s): 18.20.2

**Comment by bryantbiggs** [comment]
hi @dmitry-mightydevops - this is not a bug and is the desired effect. Autoscaling of nodes via cluster autoscaler or Karpenter is the preferred method by many, and unfortunately Terraform does not allow for parameterizing `ignore_changes` at this time so this is the default effect

**Comment by dmitry-mightydevops** [comment]
Sounds good - thanks @bryantbiggs that's what I thought.

**Comment by NickLarsenNZ** [comment]
I'm getting this too (on a cluster I scaled up manually via the console).

@bryantbiggs I think this should be reopened.

Perhaps the `minimum`, `maximum`, and `desired` values should change in the order depending on which is currently greater or less than others (to avoid breaking the constraint).

**Comment by dejwsz** [comment]
Regarding the comment: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2030#issuecomment-1105094751 I suspect it will be possible to handle this properly after this is done: https://github.com/hashicorp/terraform/issues/27360, https://github.com/hashicorp/terraform/issues/3116

**Comment by bryantbiggs** [comment]
https://github.com/bryantbiggs/eks-desired-size-hack
