### ISSUE TITLE
terraform destroy fails

### ISSUE THREAD

**Issue by syst0m** [terraform-aws-modules/terraform-aws-eks#204]
# I have issues
with running `terraform destroy` to completion without errors.
## I'm submitting a...

* [/] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
`terraform destroy` completes with errors.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
`terraform destroy -auto-approve
data.template_file.map_accounts: Refreshing state...
data.template_file.map_roles: Refreshing state...
data.template_file.map_users: Refreshing state...
data.aws_availability_zones.available: Refreshing state...
data.aws_region.current: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_iam_policy_document.workers_assume_role_policy: Refreshing state...
data.aws_ami.eks_worker: Refreshing state...
data.aws_iam_policy_document.cluster_assume_role_policy: Refreshing state...

Error: Error applying plan:

4 error(s) occurred:

* local.cluster_name: local.cluster_name: Resource 'random_string.suffix' does not have attribute 'result' for variable 'random_string.suffix.result'
* module.eks.output.config_map_aws_auth: Resource 'data.template_file.config_map_aws_auth' does not have attribute 'rendered' for variable 'data.template_file.config_map_aws_auth.rendered'
* module.eks.output.cluster_endpoint: Resource 'aws_eks_cluster.this' does not have attribute 'endpoint' for variable 'aws_eks_cluster.this.endpoint'
* module.eks.output.kubeconfig: Resource 'data.template_file.kubeconfig' does not have attribute 'rendered' for variable 'data.template_file.kubeconfig.rendered'`

## Environment details

* Affected module version: 1.7.0
* OS: 10.14.1
* Terraform version: 0.11.10

**Comment by mmcaya** [comment]
If you are blocked, this is a known issue with terraform and described here: https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0111-november-30-2017
and you can use `TF_WARN_OUTPUT_ERRORS=1` to get passed it with `0.11.*` terraform runtimes.

There are some other known workarounds using the 
`value       = "${element(concat(RESOURCE.*.NAME, list("")), 0)}"` pattern, but that may not work for all the above types when using `0.11.*`

Some of this can possibly be revisited when `0.12` is officially released, as its stated they plan to remove that env variable support.

**Comment by max-rocket-internet** [comment]
> Some of this can possibly be revisited when 0.12 is officially released

Says everyone about every Terraform issue nowadays 🤣

**Comment by syst0m** [comment]
Ok, thanks for the tip.
Much appreciated!
