### ISSUE TITLE
Remove politics from repo

### ISSUE THREAD

**Issue by tkaesserfm** [terraform-aws-modules/terraform-aws-eks#2043]
Git is about engineering. Not about politics. Please remove political parameters ([khuylo](https://en.wikipedia.org/wiki/Putin_khuylo)). Doesn't help anyone

**Comment by reegnz** [comment]
@bryantbiggs why was this issue closed without any explanation? I think the request is completely valid (keep politics out of code).

**Comment by bryantbiggs** [comment]
There is no explanation necessary. Users have their opinions, so do the maintainers
