### ISSUE TITLE
data aws_eks_cluster throws "error reading EKS Cluster (xxx): couldn't find resource" error

### ISSUE THREAD

**Issue by charlielj88** [terraform-aws-modules/terraform-aws-eks#2045]
## Description

When defined the data aws_eks_cluster with a valid eks name, terraform throws the error "error reading EKS Cluster (xxx): couldn't find resource"

## Versions

- Module version [Required]: NA

- Terraform version: v1.1.9

- Provider version(s): aws: v4.11.0, kubenetes: v2.10.0

## Reproduction Code [Required]

Defined the following blocks in the providers.tf,
```
data "aws_eks_cluster" "cluster_ap_1" {
  name = module.sophon-eks-ap-1.cluster_id
}

data "aws_eks_cluster_auth" "cluster_auth_ap_1" {
  name = module.sophon-eks-ap-1.cluster_id
}

provider "kubernetes" {
  alias = "ap-northeast-1"
  host                   = data.aws_eks_cluster.cluster_ap_1.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster_ap_1.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster_auth_ap_1.token
}
```
however, when executing the "terraform apply", it throws the error,
```
╷
│ Error: error reading EKS Cluster (sophon-eks-ap-1): couldn't find resource
│ 
│   with data.aws_eks_cluster.cluster_ap_1,
│   on providers.tf line 23, in data "aws_eks_cluster" "cluster_ap_1":
│   23: data "aws_eks_cluster" "cluster_ap_1" {
```

## Expected behavior

No error should be thrown

## Actual behavior
An unexpected error as above

## Additional context
Also would like to clarify how "aws_eks_cluster" datasource retrieves the eks instance by merely using the eks name, since there is possibility that are multiple eks instances with same name across different regions.

**Comment by bryantbiggs** [comment]
this question is not relevant to this module https://www.terraform.io/language/data-sources
