### ISSUE TITLE
The node security group is not added to instances created by the EKS managed launch template

### ISSUE THREAD

**Issue by marcusschiesser** [terraform-aws-modules/terraform-aws-eks#2049]
## Description

Creating a cluster with EKS managed node groups and EKS managed launch template (`create_launch_template = false` and `     launch_template_name   = ""`), The [node security group](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/20af82846b4a1f23f3787a8c455f39c0b6164d80/node_groups.tf#L148) is created, but not added to instances created by the EKS managed launch template. 

The instances only have the [`cluster_primary_security_group_id`](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/dc8a6eecddc2c6957ba309a939ee46f39b946461#output_cluster_primary_security_group_id) assigned.

Therefore [node_security_group_additional_rules](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/dc8a6eecddc2c6957ba309a939ee46f39b946461#input_node_security_group_additional_rules) and generally rules of the node security group are not added to the instances.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 18.20.2

- Terraform version: v1.1.8
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v4.10.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.10.0
+ provider registry.terraform.io/hashicorp/tls v3.3.0
```

## Reproduction Code [Required]

```
 eks_managed_node_groups = {
    workers = {
      create_launch_template = false
      launch_template_name   = ""
      disk_size              = 50
```

## Expected behavior

The [node security group](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/20af82846b4a1f23f3787a8c455f39c0b6164d80/node_groups.tf#L148) is added to instances created by the EKS managed launch template. 

## Actual behavior

The [node security group](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/20af82846b4a1f23f3787a8c455f39c0b6164d80/node_groups.tf#L148) is not added to instances created by the EKS managed launch template.

**Comment by marcusschiesser** [comment]
Is there a workaround? For example, how can I change the EKS managed launch template to add the node security group?

**Comment by bryantbiggs** [comment]
if you more control over resources then you'll have to use the custom launch template - this is why its the default setting instead of using the default EKS managed node group security group

**Comment by marcusschiesser** [comment]
@bryantbiggs Makes sense. The reason I ended up wanting to use the EKS managed launch template was that I wanted to increase the disk size.
So what would be the right approach for this ticket? Something like the following two?

1. Document that setting `create_launch_template = false` you're entering the danger zone and security groups are not working as expected
2. Make `disk_size` work with the custom launch template

**Comment by bryantbiggs** [comment]
I believe this is already well documented
- https://github.com/terraform-aws-modules/terraform-aws-eks/blob/d969e94bbea89ed616713bdab849f042ceda87ac/examples/eks_managed_node_group/main.tf#L129-L135

- https://github.com/terraform-aws-modules/terraform-aws-eks/blob/d969e94bbea89ed616713bdab849f042ceda87ac/examples/eks_managed_node_group/main.tf#L284-L297

**Comment by goetzc** [comment]
> I believe this is already well documented

Code examples are mostly not what is considered as the traditional documentation. Would be very handy to have it.

**Comment by bryantbiggs** [comment]
> > I believe this is already well documented
> 
> Code examples are mostly not what is considered as the traditional documentation. Would be very handy to have it.

Why would code examples not fall under documentation?

**Comment by bryantbiggs** [comment]
Closing this out for now since there is no further action to be taken
