### ISSUE TITLE
How to configure & encrypt root EBS volume?

### ISSUE THREAD

**Issue by hasakura12** [terraform-aws-modules/terraform-aws-eks#2056]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

For self-managed node group, there used to be a variable called `root_encrypted` and `root_kms_key_id` inside launch config default map.

Now launch config is replaced with launch template, I can find only `block_device_mappings`: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/self_managed_node_group/main.tf#L229

Is this `block_device_mappings` for custom EBS volume? I'm assuming so because in the example, non-complete node groups don't specify this block device mapping: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/self_managed_node_group/main.tf#L107-L163

If this `block_device_mappings` is not for root EBS volume, how can I configure encryption of the root EBS volume? Or has AWS changed it so that root EBS volume is encrypted by default?

_

**Comment by bryantbiggs** [comment]
Correct - you should use `block_device_mappings` to enable this

**Comment by hasakura12** [comment]
You mean even for root EBS volume?

**Comment by bryantbiggs** [comment]
you can look up the root device volume for the instance you are using to get these details - see more here https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/RootDeviceStorage.html

**Comment by hasakura12** [comment]
I see. I have integrated the latest AWS EKS module codes and ran `terraform plan`, and EKS cluster needs to be replaced (create replacement and destroy). 

Are there non-disruptive way to integrate new version of EKS module without deleting? Replacing will cause serious downtime where I need to manually install bunch of stuff to EKS cluster again (CA, Istio, and apps).


Here is the terraform plan output:
```tf
 # module.eks.module.eks_cluster.aws_eks_cluster.this[0] must be replaced
+/- resource "aws_eks_cluster" "this" {
      ~ arn                       = "arn:aws:eks:us-east-1:xxxx:cluster/xxx" -> (known after apply)
      ~ certificate_authority     = [
          - {
              - data = "xxxx"
            },
        ] -> (known after apply)
      ~ created_at                = "2021-01-04 19:43:03.467 +0000 UTC" -> (known after apply)
        enabled_cluster_log_types = [
            "api",
            "audit",
            "authenticator",
            "controllerManager",
            "scheduler",
        ]
      ~ endpoint                  = "https://xxxx.gr7.us-east-1.eks.amazonaws.com" -> (known after apply)
      ~ id                        = "xxxx" -> (known after apply)
      ~ identity                  = [
          - {
              - oidc = [
                  - {
                      - issuer = "https://oidc.eks.us-east-1.amazonaws.com/id/xxxx"
                    },
                ]
            },
        ] -> (known after apply)
        name                      = "xxxx"
      ~ platform_version          = "eks.7" -> (known after apply)
      ~ role_arn                  = "arn:aws:iam::xxxx:role/xxxx202101041851yyyy -> (known after apply) # forces replacement
      ~ status                    = "ACTIVE" -> (known after apply)
        tags                      = {
            "Application"                                               = "xxxx"
            "Environment"                                               = "prod"
            "k8s.io/cluster-autoscaler/xxxx" = "true"
            "kubernetes.io/cluster/xxxx"     = "shared"
        }
        tags_all                  = {
            "Application"                                               = "xxxx"
            "Environment"                                               = "prod"
            "k8s.io/cluster-autoscaler/xxxx" = "true"
            "kubernetes.io/cluster/xxxx"     = "shared"
        }
        version                   = "1.19"

        encryption_config {
            resources = [
                "secrets",
            ]

            provider {
                key_arn = "arn:aws:kms:us-east-1:xxxx:key/xxxx"
            }
        }

      ~ kubernetes_network_config {
          ~ ip_family         = "ipv4" -> (known after apply)
          ~ service_ipv4_cidr = "172.20.0.0/16" -> (known after apply)
        }

      ~ timeouts {
          - create = "30m" -> null
          - delete = "15m" -> null
        }

      ~ vpc_config {
          ~ cluster_security_group_id = "sg-xxxx" -> (known after apply)
            endpoint_private_access   = false
            endpoint_public_access    = true
            public_access_cidrs       = [
                "0.0.0.0/0",
            ]
          ~ security_group_ids        = [
              - "sg-xxxx",
            ] -> (known after apply) # forces replacement
            subnet_ids                = [
                "subnet-xxxx",
                "subnet-xxxx",
                "subnet-xxxx",
                "subnet-xxxx",
            ]
          ~ vpc_id                    = "vpc-xxxx" -> (known after apply)
        }
    }
```

Since two days ago, older version of EKS module stop working (data for fetching AMI no longer returns AMI, hence can't do terraform apply).

**Comment by bryantbiggs** [comment]
I don't follow - what exactly is your question? 

Here is where Terraform is telling you whats forcing the replacement so you should focus there
```
 ~ security_group_ids = [
       - "sg-xxxx",
   ] -> (known after apply) # forces replacement
```

**Comment by bryantbiggs** [comment]
Closing for now - please feel free to provide additional details if your question was not answered or open a new issue if you are facing a different issue

**Comment by jrkalf-cambrian** [comment]
hi @bryantbiggs,
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/RootDeviceStorage.html

Sorry to re-open an archived thread. I can't seem to get this to work. I've opened up a testing eks and tried to get an **eks managed node** group up and running having the root volume encrypted as well.

As following:
```
  eks_managed_node_groups = {
    thor = {
      min_size     = 2
      max_size     = 3
      desired_size = 2 

      instance_types = ["t3.micro"]
      capacity_type  = "SPOT"
      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 20
            volume_type           = "gp3"
            encrypted             = true
            kms_key_id            = aws_kms_key.qa_eks.arn
            delete_on_termination = false
          }
        }
      }
    }
  }
```
Computer says NO.

So what am I doing wrong in here, or is the functionality simply not there right now and would it be a feature request,  or something I'd have to code and merge-request myself?
The EKS documentation in the README.md is very sparse when it comes to the block_device_mappings.
Perhaps you can send a sample to learn from?

**Comment by deybhayden** [comment]
Hey there, I was running into this issue as well, but discovered a difference in my config helped actually respect the `block_device_mappings`. I have one node group where the block device mappings aren't respected:

```terraform
    bottlerocket_encrypted = {
      create_launch_template = false
      launch_template_name   = ""

      ami_type = "BOTTLEROCKET_x86_64"
      platform = "bottlerocket"

      block_device_mappings = {
        xvdb = {
          device_name = "/dev/xvdb"
          ebs = {
            volume_size           = 50
            volume_type           = "gp3"
            iops                  = 150
            encrypted             = true
            kms_key_id            = aws_kms_key.eks.arn
            delete_on_termination = true
          }
        }
      }

      desired_size = var.bottlerocket_nodes_desired
      min_size     = var.bottlerocket_nodes_min
      max_size     = var.bottlerocket_nodes_max
    }
```

And I added a new node group that is having its mappings respected:

```
    br_encrypted_v2 = {
      ami_type = "BOTTLEROCKET_x86_64"
      platform = "bottlerocket"

      block_device_mappings = {
        xvdb = {
          device_name = "/dev/xvdb"
          ebs = {
            volume_size           = 50
            volume_type           = "gp3"
            iops                  = 150
            encrypted             = true
            kms_key_id            = aws_kms_key.eks.arn
            delete_on_termination = true
          }
        }
      }

      desired_size = var.bottlerocket_nodes_desired
      min_size     = var.bottlerocket_nodes_min
      max_size     = var.bottlerocket_nodes_max
    }
```

I think the mapping was ignored due to the fact that I wasn't creating my own launch template, but letting EKS do it for me.
