### ISSUE TITLE
RBAC permission for Fargate based cluster

### ISSUE THREAD

**Issue by raghavgupta0** [terraform-aws-modules/terraform-aws-eks#2058]
Hi,

I am trying to create EKS cluster with Fargate based profile, but after cluster creation I am getting below error -
"This may be due to the current user or role not having Kubernetes RBAC permissions to describe cluster resources or not having an entry in the cluster’s auth config map."

Also I can't find the auth config map for fargate profile example.
[main.txt](https://github.com/terraform-aws-modules/terraform-aws-eks/files/8631483/main.txt)

**Comment by bryantbiggs** [comment]
1. The error is because the identity you are logged into the console as is not in the aws-auth configmap (or it has insufficient permissions)
2. The EKS service automatically injects the Fargate profile identities into the aws-auth configmap
