### ISSUE TITLE
eks_managed_node_groups: bootstrap_extra_args: "User data was not in the MIME multipart format"

### ISSUE THREAD

**Issue by qingvincentyin** [terraform-aws-modules/terraform-aws-eks#2059]
## Description

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

See:

- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1875

I don't think the underlying problem was resolved and might have gotten worse in `terraform-aws-modules` `v18.20.5` (or probably more likely because of `hashicorp/aws` provider `4.x.x`). I can reproduce the error in a very simple 1-step procedure below.

## Versions

Module version:

- https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v18.20.5

```console
$ tf version
Terraform v1.1.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.13.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/tls v3.3.0


$ tf providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/aws] ~> 4.11
└── module.eks
    ├── provider[registry.terraform.io/hashicorp/tls] >= 3.0.0
    ├── provider[registry.terraform.io/hashicorp/kubernetes] >= 2.10.0
    ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
    ├── module.eks_managed_node_group
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
    │   └── module.user_data
    │       └── provider[registry.terraform.io/hashicorp/cloudinit] >= 2.0.0
    ├── module.fargate_profile
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
    └── module.self_managed_node_group
        ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
        └── module.user_data
            └── provider[registry.terraform.io/hashicorp/cloudinit] >= 2.0.0
```

## Reproduction Code

Here's the complete minimal code to reproduce the problem.

```hcl
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "18.20.5"
  cluster_name    = "my-cluster1"
  cluster_version = "1.21"
  vpc_id          = "vpc-8333e1fb"
  subnet_ids      = ["subnet-74210e0d", "subnet-a9e9a0e2"]

  eks_managed_node_groups = {
    my-node-group = {
      min_size     = 1
      max_size     = 1
      desired_size = 1

      enable_bootstrap_user_data = true
      bootstrap_extra_args       = "--aws-api-retry-attempts 4"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

terraform {
  required_version = "~> 1.1"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.11"
    }
  }
}
```

```console
$ terraform apply
...
Plan: 28 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Enter a value: yes

...
╷
│ Error: error waiting for EKS Node Group (my-cluster1:my-node-group-2022050700211250350000000d) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:
│ 	* : Ec2LaunchTemplateInvalidConfiguration: User data was not in the MIME multipart format.
│
│   with module.eks.module.eks_managed_node_group["my-node-group"].aws_eks_node_group.this[0],
│   on .terraform/modules/eks/modules/eks-managed-node-group/main.tf line 272, in resource "aws_eks_node_group" "this":
│  272: resource "aws_eks_node_group" "this" {
```

## Additional context

Your comment here said to remove the `enable_bootstrap_user_data` param:

- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1875#issuecomment-1039175430

Maybe you were talking about something else, but that won't solve my problem. The flag `enable_bootstrap_user_data` is needed because of this `%{ if ... ~}` statement:

- https://github.com/terraform-aws-modules/terraform-aws-eks/blob/d969e94bbea89ed616713bdab849f042ceda87ac/templates/linux_user_data.tpl#L9-L12

**Comment by dsuievalov** [comment]
Get into the same issue and fixed by disabling `enable_bootstrap_user_data` and defining `pre_bootstrap_user_data` param from the example - https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L220. Hope that help.

**Comment by bryantbiggs** [comment]
> Get into the same issue and fixed by disabling `enable_bootstrap_user_data` and defining `pre_bootstrap_user_data` param from the example - [https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L220](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf?rgh-link-date=2022-05-07T11%3A52%3A16Z#L220). Hope that help.

^ This is correct.

EKS managed node groups merge provide their own launch template that is merged with a custom launch template when provided (this module defaults to creating a custom launch template since it offers more functionality that is commonly used such as tagging instances launched). In that merging process, the EKS managed node group service injects the bootstrap.sh script invocation in the user data at the END - UNLESS there is a custom AMI provided (an `ami_id` is set). So when using an EKS managed node group, you do not enable `enable_bootstrap_user_data` unless you are providing an AMI as this will inject the bootstrap.sh script that is no longer provided by the EKS managed node group service.

**Comment by qingvincentyin** [comment]
Wonderful! Thank you both!

I didn't know which docs to read. I was reading the top-level READMEs at

- https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest
- https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/eks-managed-node-group

and its variable description for [bootstrap_extra_args](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/eks-managed-node-group#input_bootstrap_extra_args) which doesn't explain much and in fact quite misleading.

Now that I know where to look, your docs that explain this whole solution is here:

-  https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/user_data.md#eks-managed-node-group

**I wish the variable descriptions for [bootstrap_extra_args](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/eks-managed-node-group#input_bootstrap_extra_args) and [pre_bootstrap_user_data](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/eks-managed-node-group#input_pre_bootstrap_user_data) had contained a link to the above `user_data` docs.**

Also, I found your answer to a very similar discussion

- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1770#issuecomment-1011381159

So, with all the new knowledge and sample code, I got it working. My new, working code is below. I've taken the liberty to set an extra env var `DOCKER_CONFIG_JSON` which is what I'm really going after for my real work.

```hcl
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "18.20.5"
  cluster_name    = "my-cluster1"
  cluster_version = "1.21"
  vpc_id          = "vpc-8333e1fb"
  subnet_ids      = ["subnet-74210e0d", "subnet-a9e9a0e2"]

  eks_managed_node_groups = {
    my-node-group = {
      min_size     = 1
      max_size     = 1
      desired_size = 1

      # https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/user_data.md#eks-managed-node-group
      enable_bootstrap_user_data = false
      pre_bootstrap_user_data    = <<-EOT
      #!/bin/bash
      set -ex
      cat <<-EOF > /etc/profile.d/bootstrap.sh
      export API_RETRY_ATTEMPTS=4
      export DOCKER_CONFIG_JSON='{"bridge":"none","log-driver":"json-file","log-opts":{"max-size":"1024m","max-file":"2"},"live-restore":true,"max-concurrent-downloads":10,"default-ulimits":{"memlock":{"Hard":-1,"Name":"memlock","Soft":-1}}}'
      EOF
      # Source extra environment variables in bootstrap script
      sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh
      EOT
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

terraform {
  required_version = "~> 1.1"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.11"
    }
  }
}
```

We can close this issue.

**Comment by bogdando** [comment]
> Get into the same issue and fixed by disabling `enable_bootstrap_user_data` and defining `pre_bootstrap_user_data` param from the example - https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L220. Hope that help.

When ``enable_bootstrap_user_data`` unset, I believe the expectation is no ``pre_/post_ bootstrap_user_data`` should be used, because it wasn't enabled. This looks like another issue, I'm trying to address both in the linked PR
