### ISSUE TITLE
'cluster_security_group_additional_rules' - source to be CIDR/Subnet or 0.0.0.0/0

### ISSUE THREAD

**Issue by gfrid** [terraform-aws-modules/terraform-aws-eks#2064]
Subject: RE:[AWS CASE 10013369591] Unable to connect to the server: dial xxx.xxx.xxx.xxx tcp i/o time out
According to various deployment scenarios 443 port should be added to EKS Cluster security group

To fix the issue you can perform any of the below:
- Add an inbound rule in your cluster security group (sg-xxxxx) to allow HTTPS traffic from the below two security groups which are attached to your instance:
sg-xxxx
sg-xxxx

- Add an inbound rule in your cluster security group (sg-xxxxxx) to allow HTTPS traffic from the sub-net cidr of the ec2 instance (x.x.x.x/x).

- Add an inbound rule in your cluster security group (sg-xxxxxx) to allow HTTPS traffic from the ec2 instance IP address (x.x.x.x)

EKS TF code does not incorporate such scenario because the _source_cluster_security_group_  is false or true

cluster_security_group_additional_rules = {
    eks_api_kubectl_ing = {
      description                = "Cluster PUBLIC API 443 ingress port for kubectl from other VPC"
      protocol                   = "tcp"
      from_port                  = 443
      to_port                    = 443
      type                       = "ingress"
      source_cluster_security_group = false
    }
  }

**Comment by bryantbiggs** [comment]
I'm not sure I understand what is provided in the issue - but I'll leave this for reference which should clarify what is provided https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/network_connectivity.md

**Comment by bryantbiggs** [comment]
yes

**Comment by gfrid** [comment]
> yes

thanks
