### ISSUE TITLE
[Open Dialogue] - Feedback

### ISSUE THREAD

**Issue by bryantbiggs** [terraform-aws-modules/terraform-aws-eks#2066]
Please share your feedback in regards to the module - good, bad, or indifferent. 
- How can it be improved?
- What are your pain points?

Note: a revised, more detailed upgrade guidance for v17.x to v18.x is coming https://github.com/clowdhaus/eks-v17-v18-migrate

**Comment by mehemken** [comment]
v18 is much nicer! Thanks for getting rid of the auth map error. That is a major win.

**Comment by gilbrown123** [comment]
we are using  module version v17 and v18 .
as you mentioned the upgrade path is not clear :) ... 
v18 is great - but we do have some problems with the EKS provider and cluster auth - it seems like when using exec we are having trouble to assume a role in another account (not like in the aws provider). 

please continue with your great work on this module !

**Comment by jallen-frb** [comment]
I have a question, how does aws-auth work with multiple clusters? is it possible to use multiple provider blocks?

**Comment by bryantbiggs** [comment]
> I have a question, how does aws-auth work with multiple clusters? is it possible to use multiple provider blocks?

@jallen-frb there is a 1:1 relationship between the EKS module definition and an EKS cluster created. Working with multiple clusters, the management of aws-auth would have to be external to the module

**Comment by kaykhancheckpoint** [comment]
v18 has a lot less bugs which is good. Some of the examples (eks_managed_node_group) which are used as documentation are a little over complicated atleast for what i needed, consider breaking the examples down.

Consider enabling discussions / q&a so people who use this module to setup their k8s cluster can get help on related kubernetes configuration issues.

https://docs.github.com/en/discussions/quickstart
https://resources.github.com/devops/process/planning/discussions/

**Comment by bryanasdev000** [comment]
I just wanted to thank everyone for their efforts, this module has saved me more times than I can count :P

**Comment by chuongnguyen5397** [comment]
This module is amazing. But the upgrade from v17 to v18 is very complicated. It changed a lot of resources name in the module like `aws_iam_role.cluster` to `aws_iam_role.this` or security group of workers to node. 
I think you should have a detail upgrade guide for people

**Comment by bryantbiggs** [comment]
Closing out issue for now but all are still welcomed to voice any feedback here - this issue will remained pinned but by closing it, it won't show up in active issues seeking resolution. Thanks all for your support!

**Comment by philicious** [comment]
Only seeing this issue now and wanted to shout out a BIG THANK YOU to all contributors and especially to @bryantbiggs and @antonbabenko for your efforts on this and other modules !

Quick feedback on the module: 
the overhauled v18 is muuuch better structured as the historically grown v17 and overall awesome to use with alot of features and flexibility.
Not really anything that I would say is missing or bad.

As an idea: Maybe add back the possibility to provision "extended" cluster-SG rules. v17 had them and with v18 only the bare minimum is provisioned which is not enough for many users.
