### ISSUE TITLE
Cluster Name

### ISSUE THREAD

**Issue by nariman-maad** [terraform-aws-modules/terraform-aws-eks#2068]
Hi.
When cluster name is not set , I receive the error from aws 
Error: "name" length must be between 1-100 characters: ""

Bu "Required Inputs not list this var"
https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest?tab=inputs#required-inputs

**Comment by bryantbiggs** [comment]
Terraform treats any variable that does not have a default value as required. This is not reflected in this module where a default value is provided to make disabling resource creation easier. A cluster name is required
