### ISSUE TITLE
Politcal references violates this project's own Code of Conduct

### ISSUE THREAD

**Issue by raackley** [terraform-aws-modules/terraform-aws-eks#2071]
This [PR](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2070) simply closed with a dismissive response of "we are not reviewing this at this time".

This isn't a valid response. This _needs_ to be reviewed because it solves an important Code of Conduct violation.

I understand that people have strong opinions about politics, but the solution is simple. Keep it out of the code. Individual political opinions (even code maintainers) are not valid here.

**Comment by bryantbiggs** [comment]
This is not up for discussion - cc @antonbabenko
