### ISSUE TITLE
Add taints functionality in self managed Node Grup

### ISSUE THREAD

**Issue by nariman-maad** [terraform-aws-modules/terraform-aws-eks#2074]
Hi.
Is it possible to add taint functionality to self managed Node Group ?

**Comment by bryantbiggs** [comment]
Taints and labels are a feature of the EKS managed node group service. If you wish to replicate that functionality while using self-managed node groups, you could look at using the [`kubectl` Teraform provider](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs) to provide that functionality

**Comment by nariman-maad** [comment]
Thanks for reply 

      bootstrap_extra_args = "--kubelet-extra-args '--node-labels=node.kubernetes.io/lifecycle=spot --node-labels=key=value --register-with-taints=key=value:NoSchedule'"

**Comment by nkirpa** [comment]
`bootstrap_extra_args = "-KubeletExtraArgs '--node-labels=key=value --register-with-taints=key=value=windows:NoSchedule'"`

That works for me!
