### ISSUE TITLE
Creating a separate EKS-managed node group modifies aws-auth configmap.

### ISSUE THREAD

**Issue by jrouly** [terraform-aws-modules/terraform-aws-eks#2075]
## Description

This isn't a bug report necessarily, more of a "weird behavior" report.

1. Set `manage_aws_auth_configmap = true` (as in [this example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L80)) and run `terraform apply`. Terraform will manage the `aws-auth` configmap created by EKS. Great.
2. Create a separate EKS-managed node group (as in [this example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/complete/main.tf#L238-L253)) and run `terraform apply` a second time. EKS will create the node group and will also modify the `aws-auth` configmap in order to add the node group as a system bootstrapper.
3. Re-run `terraform apply` (a third time). The diff in `aws-auth` will be picked up and the new node group will be _removed_ as a bootstrapper. Subsequent `terraform apply` runs will find no diff.

At this point, nodes in the new group are no longer able to join the cluster because they lack permission.

### Module

```
source  = "terraform-aws-modules/eks/aws"
version = "18.20.5"
```

### Terraform
```
Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.13.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.5.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/random v3.1.3
+ provider registry.terraform.io/hashicorp/tls v3.3.0
```

**Comment by bryantbiggs** [comment]
Yes - if you create a node group separate from the root module you will need to feed that back in to ensure the configmap entry is maintained https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/complete/main.tf#L197-L199

The EKS managed node group service automatically adds this (first entry you saw). But when managing the aws-auth configmap with the module, all external identities need to be fed into the configmap. If the node groups are created as part of the root module, their entities are known and will be maintained in the configmap

**Comment by jrouly** [comment]
@bryantbiggs As far as I can tell, that example results in a circular dependency: `module.eks` depends on `module.eks_managed_node_group`, which in turn depends on `module.eks`.

**Comment by bryantbiggs** [comment]
Using node groups from the root module, or external of the root module works either way. Here is an example that has both internal and external node groups that works https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/complete/main.tf#L238-L275

**Comment by jrouly** [comment]
OK, thanks @bryantbiggs. I can play around with that. I missed `aws_auth_node_iam_role_arns_non_windows` in the documentation initially, thank you.
