### ISSUE TITLE
docs - need minimal example 

### ISSUE THREAD

**Issue by darkn3rd** [terraform-aws-modules/terraform-aws-eks#2078]
## Is your request related to a problem? Please describe.

The current examples are too complex and compound too many options in a single example.  I have difficulty getting off the ground quickly as a new user.

## Describe the solution you'd like.

 Could we get a minimal example to get off the ground?

## Describe alternatives you've considered.

The alternative is to not use this module and use something like `eksctl`.

**Comment by tanvp112** [comment]
This [example](https://karpenter.sh/v0.10.0/getting-started/getting-started-with-terraform/) from karpenter is really good for starter.

**Comment by bryantbiggs** [comment]
Hi @tanvp112 - apologies for the  confusion. Our examples originally started as a way to show users the different ways they could configure the modules and the breadth of functionality, which then morphed into trying to cover all functionality as a means of testing and validation. However, this leaves examples looking rather complex and not like what  you would find in an environment (gosh I hope not 😅 ).

I will try to put something together to show MVPs but any feedback or guidance on what would be helpful is much appreciated

**Comment by bryantbiggs** [comment]
FYI - I started this awhile back for similar type questions but I probably need to spend some more time on completing the examples laid out https://github.com/clowdhaus/eks-reference-architecture
