### ISSUE TITLE
default_tags bug Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by barantomasz83** [terraform-aws-modules/terraform-aws-eks#2079]
## Description
Hi,
I am migrating my stack from version 17 to 18. Currently I am using 'default_tags' for provider to set tags for each resource, like below, and it works fine:
provider "aws" {
  alias  = "ireland"
  region = "eu-west-1"
  default_tags {
    tags = merge(local.AWS_DEFAULT_RESOURCES_TAGS, var.AWS_RESOURCES_TAGS)
  }
}

In version 18 I get: "│ Error: Provider produced inconsistent final plan" for each defined tag

When I tried to set the same tags directly in eks module and overwrite default one I got  :Error: "tags" are identical to those in the "default_tags" configuration block of the provider"

I found solution by overwriting default tags and adding one extra directly in eks module but I think it should be repaired in future versions.

![image](https://user-images.githubusercontent.com/67588485/169007384-03415697-95d7-4ad1-84dc-0c08f61ab415.png)

## Versions
- Module version [Required]: "18.21.0"

- Terraform version: v1.1.9

- Provider version(s): 4.14.0

## Reproduction Code [Required]
provider "aws" {
  alias  = "ireland"
  region = "eu-west-1"
  default_tags {
    tags = merge(local.AWS_DEFAULT_RESOURCES_TAGS, var.AWS_RESOURCES_TAGS)
  }
}
locals {
  AWS_DEFAULT_RESOURCES_TAGS = {
    TERRAFORM                     = "true"
    EKS_CLUSTER_NAME              = module.eks_cluster_first.eks_cluster_name
  }
}

1. set default_tags for aws provider
2. create eks cluster with self managed NG

## Actual behavior

│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.eks_cluster_first.module.eks.module.self_managed_node_group["mixed"].aws_security_group.this[0] to include new values learned so far during apply, provider                                                                                                                                                                               provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "TERRAFORM" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Terminal Output Screenshot(s)

![image](https://user-images.githubusercontent.com/67588485/169001941-1ea3bde1-c1c8-41e0-8b3c-fd04f3676781.png)

**Comment by bryantbiggs** [comment]
This is a well known issue with the AWS provider and not related to the module https://github.com/hashicorp/terraform-provider-aws/issues/19583
