### ISSUE TITLE
Cluster Autoscaler can't scale worker nodes ASGs to zero

### ISSUE THREAD

**Issue by Chili-Man** [terraform-aws-modules/terraform-aws-eks#208]
# I have issues

I would like to enable the cluster autoscaler to support scaling down ASGs to zero nodes. According to the cluster autoscaler documentation, https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-scale-a-node-group-to-0, we need to add the following tag to the ASG: 

```
{
    "PropagateAtLaunch": true,
    "Value": "bar",
    "Key": "k8s.io/cluster-autoscaler/node-template/label/foo"
}
```

However, I wasn't able to find a good way of passing that extra tag to only one specific worker_group. I'd like to be able to specify a different value and key for each worker group.

## I'm submitting a...

* [ ] bug report
* [X] feature request
* [X] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Current behavior does not allow passing extra tags to the ASGs that get created for each specific worker group. 

## What's the expected behavior?

Ideally, we'd be able to do something like this 

```hcl
 worker_group_count = 3

  worker_groups = [
    {
      name                 = "default"
      instance_type        = "r5.4xlarge"
      asg_desired_capacity = "8"
      asg_max_size         = "12"
      asg_min_size         = "8"
    },
    {
      name                 = "transparencyapi-green"
      instance_type        = "r5.4xlarge"
      asg_desired_capacity = "3"
      asg_max_size         = "3"
      asg_min_size         = "0"
      asg_extra_tags       = {
        key = "k8s.io/cluster-autoscaler/node-template/label/transparencyapi"
        value = "green"
        propagate_at_launch = "true"
      }

      kubelet_extra_args   = "--register-with-taints='deployment=green:NoSchedule' --node-labels='transparencyapi=green'"
    },
    {
      name                 = "transparencyapi-blue"
      instance_type        = "r5.4xlarge"
      asg_desired_capacity = "3"
      asg_max_size         = "3"
      asg_min_size         = "0"
      asg_extra_tags       = {
      key = "k8s.io/cluster-autoscaler/node-template/label/transparencyapi"
      value = "blue"
      propagate_at_launch = "true"
      }
      kubelet_extra_args   = "--register-with-taints='deployment=blue:NoSchedule' --node-labels='transparencyapi=blue'"
    },
  ]
```

## Are you able to fix this problem and submit a PR? Link here if you have already.

I'd be more then happy to submit a PR for this if I can get some guidance. I'm having trouble figuring out the best way to enable this. 

## Environment details

* Affected module version: master
* OS: Ubuntu 18.10
* Terraform version: 0.11.0

**Comment by max-rocket-internet** [comment]
Hey @Chili-Man you are correct! And we have another issue already for this here: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/89

Feel free to add your voice to that issue or better yet, make a PR 😎
