### ISSUE TITLE
SpringBoot Containers are failing after the upgrade from 17.23.0 to 18.21.0

### ISSUE THREAD

**Issue by amd87hh** [terraform-aws-modules/terraform-aws-eks#2080]
## Description

Hi. I am trying to upgrade the EKS Module from 17.23.0 to 18.21.0, which works, but causes the following issue:
Spring Boot Containers, which are deployed into EKS Managed NG can't fetch metadata , and containers are failing:

`Unable to retrieve the requested metadata (/latest/meta-data/instance-id). Unauthorized 401 ...
There is no EC2 meta data available, because the application is not running in the EC2 environment.`

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 17.23.0 -> 18.21.0
- Terraform version: v1.1.9 on darwin_arm64
- Provider version(s):aws v4.11.0; cloudinit v2.2.0; kubernetes v2.10.0; tls v3.3.0

## 17.23.0 Code (working)
```
locals {
  test_cluster_name    = "eks-test"
  test_cluster_version = "1.21"
}


provider "kubernetes" {
  host                   = data.aws_eks_cluster.eks-test.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks-test.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.eks-test.token
}


module "eks-test" {
  source  = "terraform-aws-modules/eks/aws"
  version = "17.23.0"

  cluster_name    = local.test_cluster_name
  cluster_version = local.test_cluster_version

  subnets = module.vpc.private_subnets
  vpc_id  = module.vpc.vpc_id

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  node_groups = {
    test = {
      desired_capacity = 1
      max_capacity     = 2
      min_capacity     = 1
      disk_size        = 100
      instance_types   = ["t2.medium"]
    }
  }
}


data "aws_eks_cluster" "eks-test" {
  name = module.eks-test.cluster_id
}

data "aws_eks_cluster_auth" "eks-test" {
  name = module.eks-test.cluster_id
}
```
## 18.21.0 Code (failing)
```
locals {
  test_cluster_name    = "eks-test"
  test_cluster_version = "1.21"
}

provider "kubernetes" {
  alias                  = "eks-test"
  host                   = module.eks-test.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks-test.cluster_certificate_authority_data)
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    command     = "aws"
    args = ["eks", "get-token", "--cluster-name", module.eks-test.cluster_id]
  }
}

module "eks-test" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.21.0"

  cluster_name                    = local.test_cluster_name
  cluster_version                 = local.test_cluster_version
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets
  
  cluster_enabled_log_types   = []
  create_cloudwatch_log_group = false
  enable_irsa                 = false

  eks_managed_node_groups = {
    test = {
      desired_size      = 1
      max_size          = 2
      min_size          = 1
      disk_size         = 100
      enable_monitoring = false
      instance_types    = ["t2.medium"]

    }
  }
  manage_aws_auth_configmap = true
}


data "aws_eks_cluster" "eks-test" {
  name = module.eks-test.cluster_id
}

data "aws_eks_cluster_auth" "eks-test" {
  name = module.eks-test.cluster_id
}

```

## Steps to reproduce the behavior

The problem is that the erroneous behavior can only be observed using the Spring Boot container. So I need to provide the container, which I can't.

## Expected behavior

I'm excpecting that Sping Boot Containers, which are running in the old version of the EKS module, can run in the new one. 

## Actual behavior

They fail -> CrashLoopBackOff

### Terminal Output Screenshot(s)

[pod.log](https://pastebin.com/1SRZ6z8r)

## Additional context

For me the problem seems to be an authorization issue. I have already tried to investigate, how the lib 'spring-cloud-aws-autoconfigure' provide the credentials. But I did not understand the chain completly (terraform -> eks -> spring).

I know that the information I provide is not enough to reproduce the behavior, but I hope maybe someone has an idea.

Thanks, 

Alexej

**Comment by bryantbiggs** [comment]
Your issue is most likely related to [IMDS settings](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf#L2-L5). You should look up what spring boot requires since this is outside the scope of the module

**Comment by amd87hh** [comment]
Hi. Thanks for the hint. Is there a way to change the metadata_options.http_tokens to "optional", when using the EKS module in order to use IMDSV1?
