### ISSUE TITLE
submodules should also have the prefix_separator variable

### ISSUE THREAD

**Issue by srjakes** [terraform-aws-modules/terraform-aws-eks#2082]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.

During the upgrade from v17 to v18 the prefix_separator allows for moving resources around with `terraform state mv` to avoid destroy/create or replace actions.
But, the self-managed-node-group doesn't use prefix_separator and instead hard-codes a '-' and this means that even after moving the aws_launch_template it still needs to be replaced because there is no way to set the same name_prefix.

## Describe the solution you'd like.

Add the prefix_separator variable to the sub modules and use it instead of hard-coding a '-'

## Describe alternatives you've considered.

Allow the module to recreate resources.

**Comment by bryantbiggs** [comment]
Thank you for the issue - however, we are not looking to implement this in the node groups. The changes were made to the control plane, however we will not be carrying those forward to the node groups since those are easily replaced
