### ISSUE TITLE
node group update fails when VPC CNI addon is enabled

### ISSUE THREAD

**Issue by szkbury** [terraform-aws-modules/terraform-aws-eks#2086]
## Description

I've found some bug in EKS blueprint when VPC_CNI addon is turned on. Editing a node group (for example adding a new one) fails with the timeout because the role assigned to the nodes has policy attachment removed and 

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
4.0.4
- Terraform version:
Terraform v1.1.8
- Provider version(s):
Terraform v1.1.8
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.14.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.5.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]

The code is taken from 
https://aws-ia.github.io/terraform-aws-eks-blueprints/getting-started/
and as this tutorial says
terraform-aws-eks-blueprints/examples/eks-cluster-with-new-vpc example is taken as a start
then **getting started** tutorial is executed but skipping **cleanup** section - the EKS is working

execute steps from https://aws-ia.github.io/terraform-aws-eks-blueprints/getting-started/ but skip cleanup section
add the following
```
mg_test = {
          node_group_name = "managed-test"
          instance_types  = ["m5.large"]
          min_size        = "1"
          subnet_ids      = module.aws_vpc.private_subnets
        }
```
in that part:
```
  # EKS MANAGED NODE GROUPS
  managed_node_groups = {
```
execute terraform apply

## Expected behavior

node upgraded without any issues

## Actual behavior

the very first step terraform does is to remove policy attachment from IRSA role:

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.eks_blueprints_kubernetes_addons.module.aws_cloudwatch_metrics[0].module.helm_addon.module.irsa[0].aws_iam_role_policy_attachment.irsa[0]: Destroying... [id=aws001-preprod-dev-eks-cloudwatch-agent-irsa-2022051909043063440000000e]
module.eks_blueprints_kubernetes_addons.module.aws_vpc_cni[0].module.irsa_addon[0].aws_iam_role_policy_attachment.irsa[0]: Destroying... [id=aws001-preprod-dev-eks-aws-node-irsa-2022051909043068410000000f]
module.eks_blueprints_kubernetes_addons.module.aws_vpc_cni[0].module.irsa_addon[0].aws_iam_role_policy_attachment.irsa[0]: Destruction complete after 1s
```
( Note that the removed policy is arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy )
then terraform tries to create a new node group

`module.eks_blueprints.module.aws_eks_managed_node_groups["mg_ski"].aws_iam_role.managed_ng: Creating...`

but it times out after 20 minutes

```
│ Error: error waiting for EKS Node Group (aws001-preprod-dev-eks:managed-ski-20220519091022118900000005) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:
│ 	* i-06576ff0ac5971553, i-0849e995e20cbf19b: NodeCreationFailure: Instances failed to join the kubernetes cluster
```

Node group gets "Create failed" status and nodes have "Not ready" status
Instances are up and running but:
aws-node pod is restarting with

`{"level":"info","ts":"2022-05-19T09:25:57.154Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}`

and ipamd.log shows

```
tail -n 3 /var/log/aws-routed-eni/ipamd.log
{"level":"error","ts":"2022-05-19T09:26:17.788Z","caller":"ipamd/ipamd.go:456","msg":"Failed to call ec2:DescribeNetworkInterfaces for [eni-0721b5e0b27ea7275]: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 0e88218f-037c-4838-a347-ee4fa254f495"}
{"level":"error","ts":"2022-05-19T09:26:17.903Z","caller":"ipamd/ipamd.go:456","msg":"Failed to call ec2:DescribeNetworkInterfaces for [eni-0721b5e0b27ea7275]: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: b8133cd9-a889-4e5c-b191-5d970f0dc7cf"}
{"level":"error","ts":"2022-05-19T09:26:18.013Z","caller":"aws-k8s-agent/main.go:27","msg":"Initialization failure: ipamd init: failed to retrieve attached ENIs info"}
```

I confirmed that all above happens due to arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy removal from IRSA role used by aws-node pods

## Additional context

This issue doesn't exist when VPC_CNI addon is turned off (aws-node pods don't use IRSA role then)
`enable_amazon_eks_vpc_cni    = false`

**Comment by bryantbiggs** [comment]
@szkbury please open this issue on the https://github.com/aws-ia/terraform-aws-eks-blueprints/ project, thank you!
