### ISSUE TITLE
Managed node groups' launch template "$Latest" version producing an infinite always-changing plan

### ISSUE THREAD

**Issue by tal-asulin** [terraform-aws-modules/terraform-aws-eks#2087]
## Description

When using managed node group and setting the launch template version to "$Latest", Terraform will always show a difference in the plan and apply changes. 

The issue was first introduced in older version - v17.1.0 and got fixed on v17.1.3 but the same issue happened again [#1446 ](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1446) in newer versions (18.21.0).

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 18.21.0

- Terraform & providers version:
Terraform v1.2.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.15.1
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/tls v3.4.0

## Reproduction Code [Required]

Produced using the module' example:

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "18.21.0"
  cluster_version = "1.21"
  cluster_name    = "test_cluster"
  vpc_id          = "<VPC_ID>"
  subnet_ids      = ["<SUBNET_ID_1>","<SUBNET_ID_2>]

  eks_managed_node_group_defaults = {
    disk_size               = 50
    instance_types          = ["m6i.large", "m5.large", "m5n.large", "m5zn.large"]
    launch_template_version = "$Latest"
    tags                    = {"default_tag" = "test_tag"}
  }

  eks_managed_node_groups = {
    green = {
      min_size     = 1
      max_size     = 10
      desired_size = 1

      instance_types = ["t3.large"]
      capacity_type  = "SPOT"
    }
  }
}
```
1. Apply the plan for the first time
2. Apply the plan again (without making any changes).

## Expected behavior

No changes to the launch template version and the plan itself. 

## Actual behavior

Launch template version will constantly change from static number to $Latest even if no change was done to the plan.

### Terminal Output Screenshot(s)

<img width="1278" alt="Screen Shot 2022-05-25 at 21 26 05" src="https://user-images.githubusercontent.com/24853126/170339486-3b6a1804-2ef6-474f-9bd3-fa0c478e7364.png">

**Comment by tal-asulin** [comment]
Removing this line will truly make this behaviour disappear, but isn't it a valid value to set? for example, changing launch template metadata will bump the launch template version and will be resulted with the desired change in Terraform plan.

**Comment by bryantbiggs** [comment]
It is, but see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#version

**Comment by tal-asulin** [comment]
Understood. Thanks @bryantbiggs for the quick response.
