### ISSUE TITLE
Unable to find configuration for "aws_autoscaling_policy".

### ISSUE THREAD

**Issue by ashishjullia** [terraform-aws-modules/terraform-aws-eks#2089]
While trying to create a "managed node group" and defining the same in eks module definition, it results in successfully creating the "auto scaling group" but the problem how should I define the policy based on which it will get autoscaled without this, this functionality is irrelevant.

**Comment by dan-petty** [comment]
I ran into this recently as well.

https://aws.amazon.com/blogs/aws/introducing-karpenter-an-open-source-high-performance-kubernetes-cluster-autoscaler/
