### ISSUE TITLE
Launch template name needs to be explicitly set to empty string to use managed node group's launch template

### ISSUE THREAD

**Issue by andrewbelu** [terraform-aws-modules/terraform-aws-eks#2091]
## Description

See the following line in node_groups.tf
`launch_template_name            = try(each.value.launch_template_name, var.eks_managed_node_group_defaults.launch_template_name, each.key)`

It uses the key in the eks_managed_node_groups map to determine the name of the launch template. Is this intended behaviour? This somewhat goes against it's default value in the [eks_managed_node_group module](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/eks-managed-node-group/variables.tf):
```
variable "launch_template_name" {
  description = "Launch template name - either to be created (`var.create_launch_template` = `true`) or existing (`var.create_launch_template` = `false`)"
  type        = string
  default     = ""
}
```

- Module version [Required]:
Master

- Terraform version:
1.1.9

**Comment by bryantbiggs** [comment]
Correct. Its quite complex actually, and maybe there is a better way, but you can see more here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/eks-managed-node-group/main.tf#L33

We default to custom launch templates because they provide a lot of missing functionality not offered by the default launch template (i.e. - tags, security groups, etc.)

**Comment by andrewbelu** [comment]
Perhaps another boolean, something like use_custom_launch_template? If set, then it will explicitly use the managed node group's LT, otherwise it can use the custom one. Controlling this functionality by name seems a little bit confusing to me from an outside perspective.

**Comment by lucasff** [comment]
Is it because of this that my launch templates are failing to be created? I'm using the latest for everything and trying to spin up a fresh new cluster.
