### ISSUE TITLE
Add documentation on how to upgrade the eks version

### ISSUE THREAD

**Issue by thetillhoff** [terraform-aws-modules/terraform-aws-eks#2095]
It would be great it the docs would contain a section on how to upgrade the EKS version of an existing cluster.
F.e. if it's necessary to upgrade the version via the UI first and then set the version in terraform as well, or if it's sufficient to set the version in terraform and that the module will automatically do the upgrade - and not rebuild the cluster from scratch.

**Comment by bryantbiggs** [comment]
https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

You can simply change the cluster version in the module definition - by default, the control plane will update first followed by the data plane (nodes)

**Comment by thetillhoff** [comment]
Thank you for the fast information!
