### ISSUE TITLE
karpenter example of 18.23.0 cannot create LoadBalancer, conflict with the Official AWS EKS tagging

### ISSUE THREAD

**Issue by mr-kelly** [terraform-aws-modules/terraform-aws-eks#2099]
I am using the `karpenter` example to create a AWS EKS.
Version 18.23.0

Then I am going to install the KubeSphere.
https://kubesphere.com.cn/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks/

At the step I edit my service yaml from `NodePort` to `Load Balancer`, error occur when I `kubectl describe svc` to:

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/520852/171884003-32581fd8-6ec5-4b76-84ae-a456caa3a77e.png">

`Load Balancer` cannot create!

I think the security group make this error happend.  A AWS EKS auto created security groups has the tag `kubernetes.io/cluster/CLUSTER_NAME: owned` which may be conflict with AWS EKS Terraform Module.

But what should I do for that?

**Comment by mr-kelly** [comment]
> I am using the `karpenter` example to create a AWS EKS. Version 18.23.0
> 
> Then I am going to install the KubeSphere. https://kubesphere.com.cn/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks/
> 
> At the step I edit my service yaml from `NodePort` to `Load Balancer`, error occur when I `kubectl describe svc` to:
> 
> <img alt="image" width="1285" src="https://user-images.githubusercontent.com/520852/171884003-32581fd8-6ec5-4b76-84ae-a456caa3a77e.png">
> 
> `Load Balancer` cannot create!
> 
> I think the security group make this error happend. A AWS EKS auto created security groups has the tag `kubernetes.io/cluster/CLUSTER_NAME: owned` which may be conflict with AWS EKS Terraform Module.
> 
> But what should I do for that?

Maybe Related: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1986

**Comment by mr-kelly** [comment]
> correct, this is a duplicate of #1986
> 
> you can use the workaround shown [here](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1986#issuecomment-1112635625) for now

Thank you very much.

**Comment by mr-kelly** [comment]
> correct, this is a duplicate of #1986
> 
> you can use the workaround shown [here](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1986#issuecomment-1112635625) for now

Bad.  @bryantbiggs 

When I add scriptin Module 'eks':
```tf
node_security_group_tags = {
  "kubernetes.io/cluster/${local.name}" = null
}
```

I still cannot create the load balancer.... with Karpenter example.


<img width="782" alt="image" src="https://user-images.githubusercontent.com/520852/171901823-12673652-b9e6-40d1-9e21-801628c59f67.png">


Should I change some example script?

**Comment by jmorgan415** [comment]
> > correct, this is a duplicate of #1986
> > you can use the workaround shown [here](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1986#issuecomment-1112635625) for now
> 
> Bad. @bryantbiggs
> 
> When I add scriptin Module 'eks':
> 
> ```terraform
> node_security_group_tags = {
>   "kubernetes.io/cluster/${local.name}" = null
> }
> ```
> 
> I still cannot create the load balancer.... with Karpenter example.
> 
> <img alt="image" width="734" src="https://user-images.githubusercontent.com/520852/171902576-30d963f3-75f8-4c6a-95ce-f8ecb48e7df1.png">
> 
> `ensure the k8s security group is tagged`....
> 
> Should I change some example script?

Bumping this.  Facing the same issue.  This is not "closed".
