### ISSUE TITLE
Assumption Missing: Install Kubectl

### ISSUE THREAD

**Issue by Jeeppler** [terraform-aws-modules/terraform-aws-eks#21]
# I have issues

## I'm submitting a

* [ ] bug report

## What is the current behavior

There is no mention of the requirement to have `kubectl` installed before running the script. The module will fail while applying the plan.

```
Error: Error applying plan:

1 error(s) occurred:

* module.eks.null_resource.configure_kubectl: Error running command 'kubectl apply -f .//config-map-aws-auth.yaml --kubeconfig .//kubeconfig': exit status 127. Output: /bin/sh: 1: kubectl: not found
```

## What's the expected behavior

Have the a note and a link to the install instructions in the Assumption section of the README.md.

**Comment by brandoconnor** [comment]
Did you miss the documentation or does it need to be more clear? https://github.com/terraform-aws-modules/terraform-aws-eks#dependencies

**Comment by Jeeppler** [comment]
@brandoconnor Yes, I clearly missed it. Maybe you should put this in the Assumption section, because this is where you assume all the other "dependencies" or "requirements".

**Comment by brandoconnor** [comment]
That seems reasonable. I'll put those sections closer together and link depenedencies to the assumptions.

**Comment by Jeeppler** [comment]
Yes, please.

**Comment by brandoconnor** [comment]
This is now moved into the assumptions section. Shipping in 1.1.0. Thanks for the suggestion!
