### ISSUE TITLE
travis builds are failing due to not getting latest terraform release

### ISSUE THREAD

**Issue by max-rocket-internet** [terraform-aws-modules/terraform-aws-eks#210]
[This line](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/.travis.yml#L26):

```
- export LATEST_TERRAFORM_VERSION=$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | grep tag_name | cut -d '"' -f 4 | cut -c2-)
```

Because:

```
$ curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest
{
  "message": "API rate limit exceeded for 62.96.154.15. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

Anyone know a better way?

**Comment by RothAndrew** [comment]
I'm not sold on the idea that always getting the latest version of Terraform is the right way to go. Seems more stable to pick a version that you officially support and increment the version as new releases come out after testing that the sh*t doesn't hit the fan.

**Comment by RothAndrew** [comment]
But also, https://releases.hashicorp.com/terraform/

**Comment by RothAndrew** [comment]
https://github.com/hashicorp/terraform/issues/9803#issuecomment-257903082

> Hey @ColinHebert
> 
> Thank you for opening an issue. You might not recognize my name, since I'm not involved in the day-to-day workings of Terraform. One of my responsibilities is to manage the HashiCorp releases service, and Paul asked me to take a look at this issue.
> 
> In short, we intentionally do not provide a pointer to the "latest" version of any of our software downloads. This was a very intentional and very deliberate choice, and I'd would like to explain the reasoning. As part of the [Tao of HashiCorp](https://www.hashicorp.com/blog/tao-of-hashicorp.html), we believe in Versioning through Codification and Automation through Codification. These two concepts are key in building a successful and sustainable platform. It is _highly discouraged_ that you "ride the latest version" of any software package, not just HashiCorp. It is important to note that this is not a reflection of the quality of the software or release; it is a property of a well-built system. At any point in time, you should be able to reproduce a build. Using a remote URL whose target changes voids the possibility of having a reproducible build. We do not advocate downloading the latest version of Terraform (or any HashiCorp software), and encourage users to pick a version and then coordinate an upgrade effectively.
> 
> In case you are unaware, the HashiCorp Releases Service features a [full JSON API](https://www.hashicorp.com/blog/hashicorp-and-fastly.html#json-api) which provides machine-parsable version information. Here is a quick `jq` that would let you download the latest version of Terraform, but you should be strongly advised that we do not recommend this.
> 
> ```shell
> echo "https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')_darwin_amd64.zip"
> ```
> 
> Right now, that will return "0.7.8".
