### ISSUE TITLE
missing a README with the required AWS IAM permissions for creating the cluster

### ISSUE THREAD

**Issue by evoosa** [terraform-aws-modules/terraform-aws-eks#2102]

**Comment by bryantbiggs** [comment]
Permissions required are highly dependent on the cluster configuration. Permission guidance is not something we can reliably offer - instead, uses are urged to use tools such as https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html or https://github.com/iann0036/iamlive to help create a policy scoped to their use case
