### ISSUE TITLE
Output labels and taints for eks-managed-node-groups

### ISSUE THREAD

**Issue by tculp** [terraform-aws-modules/terraform-aws-eks#2104]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider

## Is your request related to a problem? Please describe.
I'm working on making an out-of-module solution for EKS-managed node group cluster-autoscaler labels and taints. Currently, the labels and taints of the aws_eks_node_group object are not output by the eks-managed-node-group module.

## Describe the solution you'd like.
Add node_group_labels and node_group_taints outputs to the module, so that they can be consumed in other resources.

## Describe alternatives you've considered.
Using a variable data source to get the aws_eks_node_group details from the node_group_arn output. However, this is significantly more cumbersome.

## Additional context
Related to the answer to https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1558 and others

**Comment by bryantbiggs** [comment]
if taints and labels are inputs, don't you have access to these already?

**Comment by tculp** [comment]
They are available manually,
```
"${var.name_prefix}-scaling" = {
      min_size     = 0
      max_size     = 10
      desired_size = 0

      instance_types = ["m5.8xlarge"]
      labels         = {
        scaling = "true"
      }
      taints         = [
        {
          key    = "scaling"
          value  = "true"
          effect = "NO_SCHEDULE"
        }
      ]
      tags = {
        NodeGroup = "${var.name_prefix}-scaling"
      }
    }
  }
  ```
  but I can't do something like
  ```
  {
    for name, group in module.eks.eks_managed_node_groups : name =>
      {
        for label_name, label_value in data.aws_eks_node_group.nodegroups[name].labels : "k8s.io/cluster-autoscaler/node-template/label/${label_name}" => label_value
      }
  }
  ```

I suppose I could instead build a map as a local like
```
group_labels_taints = {
  group_name = {
    labels = {

    }
    taints = [{

    }]
  }
}
```
and use that for both, but that feels like ti spreads out the complexity weirdly.

**Comment by tculp** [comment]
On a similar note, it would be useful for the node_group_name to be output by the module, in case `use_name_prefix = false` was not supplied
