### ISSUE TITLE
Question: removal of cluster_endpoint_private_access_cidrs

### ISSUE THREAD

**Issue by gwaz151** [terraform-aws-modules/terraform-aws-eks#2106]
Noticed in 18.x of the module that the cluster_endpoint_private_access_cidrs input was removed.  This is something that we are using, due to a remote connection to our clusters, and I’m wondering why it was removed and how others are supporting this in 18.x with the removal.  

Thank you!

**Comment by bryantbiggs** [comment]
You can replicate that functionality https://github.com/terraform-aws-modules/terraform-aws-eks/blob/e90c877a741ab3cc4215376a70f7bcc360b6a3d2/main.tf#L103

By adding additional rules to the `cluster_security_group_additional_rules` variable

**Comment by gwaz151** [comment]
Great, thank you!  I see that is available directly in the module as well as in EKS Blueprints so I believe that will get us what we need.
