### ISSUE TITLE
Changes to hashicorp/terraform-provider-aws (in v4.17.0) break public subnets

### ISSUE THREAD

**Issue by MatthewFagan** [terraform-aws-modules/terraform-aws-eks#2107]
In v4.17.0 (latest) of hashicorp/terraform-provider-aws, they changed the meaning of the associate_public_ip_address field. The result is that the launch configuration created by terraform-aws-eks now has the wrong value for public subnets. The change in question: https://github.com/hashicorp/terraform-provider-aws/issues/13137

I also posted an issue on their github. I think you probably need to coordinate with them to make sure you agree on what the value means.

**Comment by bryantbiggs** [comment]
I don't believe this applies to this module - we don't utilize launch configurations

**Comment by bryantbiggs** [comment]
> A launch configuration is created for each worker_group. You either do it directly or indirectly. Either way, it is broken when using your module

I beg to disagree - I think you are using the older v17 version of the module. In v18 we do not utilize launch configuration and only use launch templates
