### ISSUE TITLE
How to pass/reserve required memory for "kubelet" to avoid OOM issues?

### ISSUE THREAD

**Issue by ashishjullia** [terraform-aws-modules/terraform-aws-eks#2108]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: I'm unable to find the "exact version number" for this functionality.

## Is your request related to a problem? Please describe.

I'm trying to replicate something like [this](https://github.com/awslabs/amazon-eks-ami/issues/318#issuecomment-546534337).

## Describe the solution you'd like.

In a scenario, where there can be times when load is high on the "nodes" I was to reserve minimum memory for "kubelet", to avoid situations like "Node Not Ready".
## Describe alternatives you've considered.

As of now, I'm unable to figure out any alternatives to this.

**Comment by bryantbiggs** [comment]
https://github.com/awslabs/amazon-eks-ami/issues/873

**Comment by ashishjullia** [comment]
@bryantbiggs I actually did read the "issue mentioned above by you" but didn't understand how to use something like that in my eks cluster.

**Comment by bryantbiggs** [comment]
its not natively supported hence the issue. You could probably hack together a solution in userdata if you feel up to it

**Comment by bryantbiggs** [comment]
closing since this is outside scope of the module
