### ISSUE TITLE
broken manage_aws_auth_configmap usage

### ISSUE THREAD

**Issue by stantruera** [terraform-aws-modules/terraform-aws-eks#2110]
## Description

I'm getting the following error:
```
│ Error: expected length of name_prefix to be in the range (1 - 38), got manage_aws_auth_configmap-eks-node-group-
│
│   with module.eks.module.eks_managed_node_group["manage_aws_auth_configmap"].aws_iam_role.this[0],
│   on .terraform/modules/eks/modules/eks-managed-node-group/main.tf line 435, in resource "aws_iam_role" "this":
│  435:   name_prefix = var.iam_role_use_name_prefix ? "${local.iam_role_name}-" : null
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: **18.23.0**

- Terraform version: **v1.0.11**
- Provider version(s):
registry.terraform.io/hashicorp/aws v4.13.0
registry.terraform.io/hashicorp/cloudinit v2.2.0
registry.terraform.io/hashicorp/kubernetes v2.11.0
registry.terraform.io/hashicorp/random v3.3.1
registry.terraform.io/hashicorp/tls v3.4.0

## Reproduction Code [Required]
```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.23.0"
  tags = var.tags
  cluster_name = "aws-dev-us-west-2-dev1"

  create_cloudwatch_log_group = false

  eks_managed_node_groups = {
    awesome-group = {
      min_size     = 1
      max_size     = 10
      desired_size = 1

      instance_types = ["t3.large"]
    }

    manage_aws_auth_configmap = true

  }

  vpc_id     = module.vpc.vpc_id
  subnet_ids = [module.vpc.public_subnets[0], module.vpc.public_subnets[1]]
}

```

## Steps to reproduce the behavior:

Just run the configuration code above

When `manage_aws_auth_configmap` is not present in the configuration everything works well, no errors.
Tho when I use `manage_aws_auth_configmap = false` or `manage_aws_auth_configmap = true` in the configuration it triggers the same error above

**Comment by stantruera** [comment]
omg, please ignore this

**Comment by nickmelis** [comment]
Having the same issue when upgrading the module version from 15.1.0 to 18.26.4. What was the issue here?

**Comment by yagrxu** [comment]
> Having the same issue when upgrading the module version from 15.1.0 to 18.26.4. What was the issue here?
@nickmelis 
In my case, indents was wrong.
