### ISSUE TITLE
Unable to import an eks cluster without force recreation

### ISSUE THREAD

**Issue by liad5h** [terraform-aws-modules/terraform-aws-eks#2120]
## Description

I am trying to import a cluster that was created with eksctl to terraform.
The import works fine, but when I run `terraform plan` I see that the `aws_eks_cluster` has to be replaced due to:
```hcl
    ~ vpc_config {
          ~ cluster_security_group_id = "sg-y" -> (known after apply)
          - security_group_ids        = [
              - "sg-x",
            ] -> null # forces replacement
          ~ vpc_id                    = "vpc-id" -> (known after apply)
            # (4 unchanged attributes hidden)
        }

```

This happens because both `var.cluster_additional_security_group_ids` & `local.cluster_security_group_id` are used here - https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9a99689cc13147f4afc426b34ba009875a28614e/main.tf#L16

## Versions
- Module version [Required]: 18.7.2

- Terraform version:

```
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.75.2
```

## Reproduction Code [Required]

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.7.2"
  create = true
  cluster_name                     = var.cluster_name
  cluster_version                  = var.cluster_version
  cluster_endpoint_private_access  = false
  cluster_endpoint_public_access   = true
  vpc_id                           = var.vpc_id
  subnet_ids                       = var.subnet_ids
  create_cluster_security_group = false
  cluster_security_group_id = "sg-y"
  cluster_additional_security_group_ids = var.cluster_additional_security_group_ids
  iam_role_name = var.iam_role_name
}
```

1. `terraform init`
2. `terraform import 'module.eks.aws_eks_cluster.this[0]' my-cluster`
3. `terraform plan`

## Expected behavior
`aws_eks_cluster` resource should not be recreated 

If I try to import the cluster to an `aws_eks_cluster` resource with the following code, I do not get the same issue:
```hcl
data "aws_iam_role" "this" {
  name = var.role_name
}
resource "aws_eks_cluster" "this" {
  name     = var.cluster_name
  role_arn = data.aws_iam_role.this.arn
  vpc_config {
    endpoint_public_access = true
    public_access_cidrs = ["0.0.0.0/0"]
    subnet_ids = var.subnet_ids
    security_group_ids = var.cluster_additional_security_group_ids
  }
}
```

1. `terraform init`
2. `terraform import 'aws_eks_cluster.this[0]' my-cluster`
3. `terraform plan`

## Actual behavior
`aws_eks_cluster` resource is going to be recreated

**Comment by bryantbiggs** [comment]
you need to match your code with your existing cluster - this looks like you need to align your code regarding what existing security groups you have on the cluster

**Comment by liad5h** [comment]
@bryantbiggs my code is aligned.
I wouldn’t have opened this issue if it wasn’t.

thanks for the great help.

**Comment by bryantbiggs** [comment]
If it was aligned you wouldn't see a diff, so I beg to differ

Have you tried setting `create_cluster_security_group = false` ? I have no idea what eksctl has created for you so its nearly impossible to provide guidance which is why I say your code needs to align with what exists

**Comment by bryantbiggs** [comment]
@liad5h were you able to resolve your import?
