### ISSUE TITLE
Cannot apply after renaming self-managed node group launch template

### ISSUE THREAD

**Issue by pavelpp** [terraform-aws-modules/terraform-aws-eks#2122]
## Description

After specifying a custom launch template name I'm unable to apply, because I'm getting the error:

```
Error: Error updating Auto Scaling Group: ValidationError: You must use a valid fully-formed launch template. The image id '[ami-0c0a87338135e509f]' does not exist
        status code: 400, request id: 85660ff5-b81b-44bd-81c4-668bc4a71b7f

  on .terraform/modules/eks-cluster.eks-cluster/modules/self-managed-node-group/main.tf line 260, in resource "aws_autoscaling_group" "this":
 260: resource "aws_autoscaling_group" "this" {
```

I have no idea what this ami is.

## Versions

- Module version [Required]: 18.9.0

- Terraform version: Terraform v0.13.1
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v3.72.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.4.0
```

## Reproduction Code [Required]

1. rename an existing self-managed node group launch template to 

```
launch_template_name            = "eks-node-group-launch-template"
launch_template_use_name_prefix = false
```
2. try to apply

**Comment by pavelpp** [comment]
For now I did the update manually, by removing the launch template from terraform state, applying the template with `target`, which created a new template with the correct name, then manually changing the ASG launch template via the AWS management console, but I'm wondering if this is a limitation of the AWS, because you can't rename the existing launch template

**Comment by bryantbiggs** [comment]
I don't believe you can rename launch templates - you must create new. closing this out for now
