### ISSUE TITLE
worker role path has to be removed from the config map

### ISSUE THREAD

**Issue by pschrammel** [terraform-aws-modules/terraform-aws-eks#2124]
## Description

I have to create my worker roles with specific naming schema (including a path). But the nodes won't join if the worker arn in the configMap has the path included. See https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html#access-denied-managed-node-groups

## Versions

- Module version [Required]: 18.24.1

- Terraform version: 0.14.11

- Provider version(s): 
- Using hashicorp/tls v3.4.0 from the shared cache directory
- Using hashicorp/null v3.1.1 from the shared cache directory
- Using hashicorp/kubernetes v2.11.0 from the shared cache directory
- Using hashicorp/template v2.2.0 from the shared cache directory
- Using hashicorp/aws v4.19.0 from the shared cache directory

## Reproduction Code [Required]

create a worker role with a path arn:aws:iam::xxxxxx:role/development/ccs-office/office-ir-eks-worker
the node-group creation will fail (though everything will come up and will be running). removing "development/ccs-office/" onlye in the configMap is already enough to let the nodes join.

## Expected behavior

joining nodes

## Actual behavior

node group created but creatinf is failing as nodes don't join in time

**Comment by pschrammel** [comment]
another way to solve it (instead of the user fiddling around with this problem .... like I did) would be to just remove the path from the role when the configmap resource is created. as far as I can say everything else works with the path.

**Comment by AvihaiSam** [comment]
you should fix this with regex on ARN. just remove the path.
that way - a user **can** create a role with a path and not suffer from this issue.

```hcl
join("/", values(regex("(?P<prefix>arn:aws:iam::[0-9]+:role)/.+/(?P<role>[^/]*)", aws_iam_role.this.arn)))
