### ISSUE TITLE
Not able to tag autoscaling group created by EKS Managed Node Group

### ISSUE THREAD

**Issue by sparsh-anurag** [terraform-aws-modules/terraform-aws-eks#2128]
HI, I am trying to use this code in order to tag asg group, it is working when all the resources are already created. but when I am trying to run it from scratch I am getting this error

│ Error: Invalid for_each argument
│ 
│   on modules/eks/main.tf line 144, in resource "aws_autoscaling_group_tag" "example":
│  144:   for_each = toset(
│  145:     [for asg in flatten(
│  146:       [for resources in aws_eks_node_group.worker-nodes.resources : resources.autoscaling_groups]
│  147:     ) : asg.name]
│  148:   )
│     ├────────────────
│     │ aws_eks_node_group.worker-nodes.resources is a list of object, known only after apply
│ 
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target
│ argument to first apply only the resources that the for_each depends on.

**The code block which I am using**

 resource "aws_autoscaling_group_tag" "example" {
  for_each = toset(
    [for asg in flatten(
      [for resources in aws_eks_node_group.worker-nodes.resources : resources.autoscaling_groups]
    ) : asg.name]
  )

  autoscaling_group_name = each.value

  tag {
    key   = "Name"
    value = "Worker"
    propagate_at_launch = true
  }
   depends_on = [
    aws_eks_node_group.worker-nodes,
    aws_eks_cluster.eks,

  ]
}

**Comment by prateekn** [comment]
You can try the method mentioned in the [example section](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/312e4a4d59cb10a762a4045e9944f3f837126933/examples/eks_managed_node_group/main.tf#L677-L711)

**Comment by prateekn** [comment]
You can try the method mentioned in the [example section](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/312e4a4d59cb10a762a4045e9944f3f837126933/examples/eks_managed_node_group/main.tf#L674-L712) ! !

**Comment by bryantbiggs** [comment]
Thank you for linking @prateekn - @sparsh-anurag please see the link provided for how to achieve this
