### ISSUE TITLE
dependency should be to kms 1.0.1 - not 1.0.0  

### ISSUE THREAD

**Issue by trieder83** [terraform-aws-modules/terraform-aws-eks#2130]
## Description
many eks driver have a version constraint of <4.0.0 for aws provider. but kms 1.0.0 has one with >= 4.0.0.
This is incompatible. Seems this is fixed in kms 1.0.1. So the dependency should be changed to 1.0.1
(issue introduces in 18.25.0 and exists in 18.26.0)

$ tf init
Initializing modules...
Downloading git::https://github.com/DNXLabs/terraform-aws-eks-cluster-autoscaler.git for cluster_autoscaler...
- cluster_autoscaler in .terraform\modules\cluster_autoscaler
Downloading git::https://github.com/DNXLabs/terraform-aws-eks-efs-csi-driver.git for efs_csi_driver...
- efs_csi_driver in .terraform\modules\efs_csi_driver
Downloading registry.terraform.io/DNXLabs/eks-external-dns/aws 0.1.4 for eks-external-dns...
- eks-external-dns in .terraform\modules\eks-external-dns
Downloading registry.terraform.io/DNXLabs/eks-lb-controller/aws 0.6.0 for eks-lb-controller...
- eks-lb-controller in .terraform\modules\eks-lb-controller
Downloading registry.terraform.io/terraform-aws-modules/eks/aws 18.25.0 for eks_dev...
- eks_dev in .terraform\modules\eks_dev
- eks_dev.eks_managed_node_group in .terraform\modules\eks_dev\modules\eks-managed-node-group
- eks_dev.eks_managed_node_group.user_data in .terraform\modules\eks_dev\modules\_user_data
- eks_dev.fargate_profile in .terraform\modules\eks_dev\modules\fargate-profile
Downloading registry.terraform.io/terraform-aws-modules/kms/aws 1.0.0 for eks_dev.kms...
- eks_dev.kms in .terraform\modules\eks_dev.kms
- eks_dev.self_managed_node_group in .terraform\modules\eks_dev\modules\self-managed-node-group
- eks_dev.self_managed_node_group.user_data in .terraform\modules\eks_dev\modules\_user_data

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding hashicorp/aws versions matching "~> 3.0, >= 3.13.0, >= 3.72.0, >= 4.0.0, < 4.0.0"...
- Finding hashicorp/kubernetes versions matching ">= 1.10.0, >= 2.10.0, 2.10.0, < 3.0.0"...
- Finding gavinbunney/kubectl versions matching ">= 1.9.4, >= 1.14.0"...
- Finding hashicorp/tls versions matching ">= 3.0.0, 3.4.0"...
- Finding hashicorp/helm versions matching ">= 1.0.0, < 3.0.0"...
- Finding hashicorp/cloudinit versions matching ">= 2.0.0"...
- Installing hashicorp/tls v3.4.0...
- Installed hashicorp/tls v3.4.0 (signed by HashiCorp)
- Installing hashicorp/helm v2.6.0...
- Installed hashicorp/helm v2.6.0 (signed by HashiCorp)
- Installing hashicorp/cloudinit v2.2.0...
- Installed hashicorp/cloudinit v2.2.0 (signed by HashiCorp)
- Installing hashicorp/kubernetes v2.10.0...
- Installed hashicorp/kubernetes v2.10.0 (signed by HashiCorp)
- Installing gavinbunney/kubectl v1.14.0...
- Installed gavinbunney/kubectl v1.14.0 (self-signed, key ID AD64217B5ADD572F)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider
│ hashicorp/aws: no available releases match the given constraints ~> 3.0, >=
│ 3.13.0, >= 3.72.0, >= 4.0.0, < 4.0.0

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.26.1 :tada:
