### ISSUE TITLE
Fix: Allow setting metadata endpoint options so users can configure or disable

### ISSUE THREAD

**Issue by scotthesterberg** [terraform-aws-modules/terraform-aws-eks#2132]
Can we get this fix back-ported to this repo: https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/657 ? It would be useful for the same reasons it was implemented for the AWS EKS Blueprints repo.

Allow setting metadata endpoint options so users can configure or disable.

**Motivation**

Allow users to configure the metadata endpoint options to suit their workloads, or even disable if not supported in their region

**Comment by scotthesterberg** [comment]
I do not believe it is. There is currently no way to fully disable setting the metadata_options. I have attempted setting `metadata_options = null` and Terraform still attempts to set the metadata. In some AWS deployments this is not currently supported. This is way the `enable_metadata_options` flag was implemented in the referenced PR.

**Comment by bryantbiggs** [comment]
after investigating, it looks like our conditional check against `null` is incorrect. PR coming soon

**Comment by scotthesterberg** [comment]
Awesome, thank you so much!

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.26.2 :tada:

**Comment by bryantbiggs** [comment]
@scotthesterberg this should be resolved now by setting `metadata_options = {}` , let me know if you run into any issues

**Comment by scotthesterberg** [comment]
@bryantbiggs Thanks I really appreciate it!
