### ISSUE TITLE
Dynamically multiple namespace creation

### ISSUE THREAD

**Issue by raghavgupta0** [terraform-aws-modules/terraform-aws-eks#2134]
Hi Team,
I am trying to create multiple Namespace creations using the list(string) variable. but getting below error because of list string variable 
"   on .terraform/modules/eks_demo.eks/modules/fargate-profile/main.tf line 72, in resource "aws_eks_fargate_profile" "this":
  72:       namespace = selector.value.namespace
 Inappropriate value for attribute "namespace": string required."
-----------------------------------------------------------------------------------
I have tried the below code for the same and it will create the multiple namespaces 
 
variable "fargate_profile_multiple_namespaces" {
  type        = list(string)
  description = "List of Namespaces on EKS which will be created with Fargate profile"
  default     = ["test-1", "test-2"]
}

 resource "aws_eks_fargate_profile" "multiple_namespaces" {
  count                  = length(var.fargate_profile_multiple_namespaces)
  cluster_name           = module.eks.cluster_id 
  fargate_profile_name   = "fp-${var.fargate_profile_multiple_namespaces[count.index]}"
  pod_execution_role_arn = aws_iam_role.fargate_pod_execution_role.arn
  subnet_ids             = local.private_subnet_ids

  selector {
    namespace = var.fargate_profile_verticals_namespaces[count.index]
  }
}

So is it possible with this module ? If yes, please let me know the approach.

Thanks

**Comment by bryantbiggs** [comment]
1. Yes it is possible, see https://github.com/terraform-aws-modules/terraform-aws-eks/blob/f34670cf0bc84c42df14f64422ffda7298006fb8/examples/fargate_profile/main.tf#L67
2. Please fill out the issue template as provided in the future please
