### ISSUE TITLE
Internal Classic Load Balancers when deploying k8s application as service=LoadBalancer

### ISSUE THREAD

**Issue by ashishjullia** [terraform-aws-modules/terraform-aws-eks#2139]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality
  - Not sure whether it is available or not

## Is your request related to a problem? Please describe.

While trying to deploy a k8s application, I'm providing "service type == LoadBalancer" and by default, it creates an internet-facing load balancer.

## Describe the solution you'd like.

I want to create and internal load balancer as per [this](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-create-internal-load-balancer.html)
Also, what is the correct way to create a "Network Load Balancer" when deploying a k8s application with this module?

## Describe alternatives you've considered.

I think one solution can be to use Network Load Balancer but unsure about this as well.

## Additional context

@bryantbiggs @antonbabenko

**Comment by bryantbiggs** [comment]
This is outside the scope of this module - please see the configurations for your selected ingress on how to configure

**Comment by ashishjullia** [comment]
@bryantbiggs I was able to add the following addons with the following TF code:

> cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }

But unable to add the `AWS Load Balancer Controller add-on`, if you could help me with the same it is highly appreciated.

**Comment by bryantbiggs** [comment]
It's not a supported EKS addon

**Comment by ashishjullia** [comment]
@bryantbiggs 
Oh, but on the [main page](https://github.com/terraform-aws-modules/terraform-aws-eks) it shows the following are supported and as per [this page](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html) AWS also specifies the same policy as it is specified on [this](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json).

The only thing I want to achieve is that I have a service which I want to deploy with "LoadBalancer" service type but by default it is being created using "ELB or Classic Load Balancer" and I want to achieve the same via "Network Load Balancer" for the whenever I hit a google search I am being directed to these links.

Also, I'm currently using [this](https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-role-for-service-accounts-eks) via which I've currently deployed the "cluster autoscaler" and this is the solution you advised me before, see [here](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1483#issuecomment-1142644928).

And on [this](https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-role-for-service-accounts-eks) is mentioned that required policies for "Load Balancer Controller" are supported (and the same set of policies are required by aws as I've pointed above). The only thing I'm unsure about is how to leverage these in contrast with the "AWS Load Balancer Controller".

![image](https://user-images.githubusercontent.com/11252951/177225447-2b4bd8eb-e737-409e-b0ea-763899528774.png)

**Comment by ashishjullia** [comment]
Adding to the above.

Is it possible to achieve the same by just setting `true` for [this](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/50ee5bb88a257c178000749c5947bde9a7d67048/modules/iam-role-for-service-accounts-eks/variables.tf#L213).

And deploying "load balancer controller" via helm chart?

**Comment by ashishjullia** [comment]
@bryantbiggs I used the following block but the service account `aws-load-balancer-controller` is not getting created.
```
module "load_balancer_controller_irsa_role" {
  source = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"

  role_name                              = "load-balancer-controller"
  attach_load_balancer_controller_policy = true

  oidc_providers = {
    ex = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:aws-load-balancer-controller"]
    }
  }
}
```

**Comment by bryantbiggs** [comment]
@ashishjullia that module only creates IRSA roles - we do not host any modules in this organization that deploy software/applications onto EKS. Please go back and re-read the documentation

**Comment by ashishjullia** [comment]
Cool thanks.
