### ISSUE TITLE
How to change ami_name_filter

### ISSUE THREAD

**Issue by asamueltx** [terraform-aws-modules/terraform-aws-eks#2145]
Hello,
This is in reference to module 17.7.0 that is what we use. My organization has a patched eks-node ami released every month called golden-ami-amazon-eks-node-1.22-2022* and I see in the local.tf line 29   `worker_ami_name_filter = var.worker_ami_name_filter != "" ? var.worker_ami_name_filter : "amazon-eks-node-${var.cluster_version}-v*"`

Is there a way I can call the eks module with a different eks ami name? because the filter amazon-eks-node-${var.cluster_version}-v* does not work.

**Comment by bryantbiggs** [comment]
you would use the `ami_id` variable for this

**Comment by bryantbiggs** [comment]
ah - I missed that detail. Unfortunately, we no longer support v17.x and the recommendation would be to upgrade to v18.x to use the `ami_id`

**Comment by bryantbiggs** [comment]
Please see the examples provided - its been available in all versions of v18.x

**Comment by bryantbiggs** [comment]
closing out with information provided above
