### ISSUE TITLE
hardcoded dash in name-prefix forces replacement of node groups when upgrading to 18x

### ISSUE THREAD

**Issue by zhujik** [terraform-aws-modules/terraform-aws-eks#2153]
## Description

Due to https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/eks-managed-node-group/main.tf#L49 and https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/self-managed-node-group/main.tf#L55, when upgrading from v1.17.x to v1.18.x, if the name of the nodegroup did not have that trailing dash before, the nodegroup will always be forcefully replaced. We should be able to circumvent this by specifing name_prefix ourselves, it would be enough to just remove that hard-coded dash altogether.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.74.3
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.10.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.3
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/jfrog/artifactory v2.6.21
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]

* create a v1.17.x nodegroup (unmanaged or managed) with no trailing dash as name.
* upgrade to v1.18.x

## Expected behavior

There should be away to avoid nodegroup replacement

## Actual behavior

* no matter your configuration, the nodegroup is replaced.

**Comment by bryantbiggs** [comment]
This change was intentional and made during a breaking change. Users can remove the current node group from Terraform control (i.e. - `terraform state rm ...`) and provision a new node group, cordon and drain the old node group and then remove once the last pod has migrated. This process should gracefully migrate pods from the old node group to the new without disruption

**Comment by zhujik** [comment]
@bryantbiggs  please elaborate. This does not work that simply, due to iam roles chaning and security groups being shuffled around and replaced, as soon as I due that, I end up with nodes in the old (self-managed) nodegroup that are in the NotReady state and all pods on them are unreachable.

**Comment by luizhenmariano** [comment]
+1
