### ISSUE TITLE
Recommended way to set ENABLE_PREFIX_DELEGATION

### ISSUE THREAD

**Issue by soostdijck** [terraform-aws-modules/terraform-aws-eks#2155]
## Description

The amount of pods per node is limited by the vpc cni addon, but there is a feature to increase the limit to something useful by setting "ENABLE_PREFIX_DELEGATION" and "WARM_PREFIX_TARGET" in the EKS cluster.

What is the recommended way to do this? I see other EKS modules that simply fire up a `kubectl` and set the settings, but that isn't very elegant (plus local-exec won't work using TFcloud).

## info

More info can be found in this [blog article
](https://aws.amazon.com/blogs/containers/amazon-vpc-cni-increases-pods-per-node-limits/)

**Comment by bryantbiggs** [comment]
Unfortunately, that is the current method for enabling this functionality. You can refer to the example I provided [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/ipv4-prefix-delegation) that demonstrates how to achieve this in Terraform

**Comment by bryantbiggs** [comment]
closing for now since its outside the scope of this module

**Comment by mohag** [comment]
> ## Description
> The amount of pods per node is limited by the vpc cni addon, but there is a feature to increase the limit to something useful by setting "ENABLE_PREFIX_DELEGATION" and "WARM_PREFIX_TARGET" in the EKS cluster.
> 
> What is the recommended way to do this? I see other EKS modules that simply fire up a `kubectl` and set the settings, but that isn't very elegant (plus local-exec won't work using TFcloud).

There seems to be [a 3rd-party provider](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs) that [makes it nicer](https://github.com/broadwing/terraform-eks/blob/db84a0afe2dcee31b8a37274c5d3c23270972d7b/provision_networking.tf)...

(A 3rd-party provider is not ideal though)
