### ISSUE TITLE
initialization fails for terraform-aws-kms module - v18.26.3

### ISSUE THREAD

**Issue by kumarpmd** [terraform-aws-modules/terraform-aws-eks#2156]
## Is your request related to a problem? Please describe.
terraform-aws-eks v18.26.3 initialization fails to download terraform-aws-modules/kms/aws from public internet.  Our corporate network blocks direct github.com.  
terraform-aws-eks v18.25.0 introduced an option to create_kms_key.  In our case, kms keys are created ahead of the cluster creation. create_kms_key is set to false, but the module is still getting initialized and fails during download.

```
Error: Failed to download module
Could not download module "kms"
(.terraform/modules/eks_cluster/terraform-aws-eks-18.26.3/main.tf:90) source
code from
"git::https://github.com/terraform-aws-modules/terraform-aws-kms?ref=v1.0.1":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-kms?ref=v1.0.1':
/usr/bin/git exited with 128: Cloning into
'.terraform/modules/eks_cluster.kms'...
fatal: repository
'https://github.com/terraform-aws-modules/terraform-aws-kms/' not found
```

## Describe the solution you'd like.
Can kms module be referenced locally in 'terraform-aws-eks/modules' similar to the node-groups and user_data
or conditionally initialize terraform-aws-kms module, if an option?

## Describe alternatives you've considered.
We could download the terraform-aws-kms and setup '.terraform/modules/eks-cluster.kms'

## Additional context
We are using v18.23.0, and are blocked from upgrading to the latest version of terraform-aws-eks.

**Comment by kumarpmd** [comment]
Thanks @bryantbiggs for looking through our case..
We were able to download and pre-initialize the kms module for terraform-aws-eks.

**Comment by bryantbiggs** [comment]
@kumarpmd I'm glad to here, cheers!
