### ISSUE TITLE
not able to increase disk size of node group using "disk_size" option - v18.26.1

### ISSUE THREAD

**Issue by prasoon-pxc** [terraform-aws-modules/terraform-aws-eks#2157]
## Is your request related to a problem? Please describe.

Trying to increase disk size of eks managed node groups but disk size is not increasing from by default 20G.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 
 18.26.1

- Terraform version:
0.13
- Provider version(s):
aws --> 4.12.1
kubernetes --> 2.11.0

## Reproduction Code [Required]

-- specify **disk_size** for managed_node_groups 
```
  eks_managed_node_groups = {
    nodegroup = {
      min_size     = var.managed_node_groups["min_size"]
      max_size     = var.managed_node_groups["max_size"]
      desired_size = var.managed_node_groups["desired_size"]
      taints       = var.managed_node_groups["taints"]
      disk_size = 100

    }



eks_managed_node_group_defaults = {
    instance_types = ["m5.xlarge"]
    disk_size      = 100
    subnet_ids     = module.vpc.private_subnets
    description    = "EKS managed node groups"
    labels = {
      "group-name" = "my group"
    }
}
```

## Expected behavior
disk size of instances in node groups should be changed as specify i.e. 100G

## Actual behavior

Disk Size is by default 20G.

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L131-L136

if you want to change the disk size you can add a block device mapping like [this](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L285-L298) (not all attributes required however)

**Comment by prasoon-pxc** [comment]
@bryantbiggs --> Ok will check with this approach.thanks

**Comment by prasoon-pxc** [comment]
@bryantbiggs --> Thanks It's works

**Comment by dkowsley** [comment]
@bryantbiggs what is the purpose of `disk_size`, then? What function does it perform?

**Comment by bryantbiggs** [comment]
`disk_size` is only valid when using the EKS managed node group default template, while this module defaults to a custom launch template to support tags, custom security groups, etc.
