### ISSUE TITLE
[Feedback] A variable has been introduced (without notice?) that requires political consideration by users

### ISSUE THREAD

**Issue by krishnan-mani** [terraform-aws-modules/terraform-aws-eks#2159]
## Description

variable introduced and defaulted to `true`, see [location](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/67e0f752b9910c0124afb5409cdf4b32fd0087a0/variables.tf#L525)

At the very least, this opts the user into a political view which they may not have considered. On the other hand, conscious choice by the user requires them to make a decision that involves a political opinion, which, imho, is in no way related to the technical usage of the module

```terraform
variable "putin_khuylo" {
  description = "Do you agree that Putin doesn't respect Ukrainian sovereignty and territorial integrity? More info: https://en.wikipedia.org/wiki/Putin_khuylo!"
  type        = bool
  default     = true
}
```

Perhaps, this is a violation of the code of conduct adopted by the project.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by bryantbiggs** [comment]
Thank you but this is not something that is open for discussion

**Comment by jvelasquez** [comment]
Hey @bryantbiggs @antonbabenko,

I have been a user of this module for a long time. Referencing this in the code base is inappropriate and undermines other serious issues happening around the world? It stops many people to actually use it as it violates political neutrality.

Can we consider deleting all reference to this variable from the code base (it is also NSFW, please lookup what does it mean)?
