### ISSUE TITLE
pass the load_balancers variable to autoscaling group of self_managed_node_group module

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [terraform-aws-modules/terraform-aws-eks#2160]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? - Yes ✅: 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#load_balancers

## Is your request related to a problem? Please describe.

Our team is going to update the module version from v17 to v18. But we ran into a problem, we can't specify the 'load_balancers' variable for 'aws_autoscaling_group' in the 'self-managed-node-group' module.

For instance,
v17, workers_launch_template.tf file
```
resource "aws_autoscaling_group" "workers_launch_template" {
  count = var.create_eks ? local.worker_group_launch_template_count : 0
...
  load_balancers = lookup(
    var.worker_groups_launch_template[count.index],
    "load_balancers",
    local.workers_group_defaults["load_balancers"]
  )
...
}

```

## Describe the solution you'd like.
I would like to pass the load_balancers parameter for the autoscaling group through the self_managed_node_group configuration.

## Additional context
If you need more information or there's a better way of solving my issue, please let me know.

**Comment by YevheniiPokhvalii** [comment]
Any updates on this?
