### ISSUE TITLE
Attempting to modify the cluster post-creation leads to an IAM error

### ISSUE THREAD

**Issue by ajpauwels** [terraform-aws-modules/terraform-aws-eks#2162]
## Description

I have recently deployed an EKS cluster with both public and private endpoint access. This succeeded without issue. The problem arises when trying to make a subsequent update to the cluster that makes an UpdateClusterConfig API call to AWS. Specifically, I set `public_endpoint_access = false`, re-ran apply, and hit this:

```
│ Error: error updating EKS Cluster (lefranc-0) VPC config: InvalidRequestException: Role with arn: arn:aws:iam::140327370353:role/lefranc-0-cluster-20220716170511649200000001, could not be assumed because it does not exist or the trusted entity is not correct
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "035daf3b-50ff-4407-9dce-a9dc939186c1"
│   },
│   ClusterName: "lefranc-0",
│   Message_: "Role with arn: arn:aws:iam::140327370353:role/lefranc-0-cluster-20220716170511649200000001, could not be assumed because it does not exist or the trusted entity is not correct"
│ }
│ 
│   with module.eks[0].aws_eks_cluster.this[0],
│   on .terraform/modules/eks/main.tf line 14, in resource "aws_eks_cluster" "this":
│   14: resource "aws_eks_cluster" "this" {
│ 
```

Full EKS module definition:
https://github.com/pauwels-labs/terraform-infra/blob/16a5305f9f76a92b6fb5c2d0ab4e458230395931/eks/eks.tf#L43

Feel free to clone this branch and run plan/apply using the included tfvars file. You'll need to update the account ID and role name to assume for the cluster account and the keys account (can be the same).

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

I have found this related issue which was closed as unable to reproduce, but I'm not convinced the reviewer attempted to update the cluster rather than just create it:
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2057

## Versions

- Module version [Required]: 18.26.3

- Terraform version:
```
(engineering-dev/default) terraform-infra $ terraform version
Terraform v1.2.5
on linux_amd64
```

## Reproduction Code [Required]

1. New workspace is created using `terraform workspace new deployments-prod-engineering-deployments-prod`
2. I use a base user in my IAM account which is then authorized to assume roles in other accounts; in this module, the tfvars file allows you to specify which account ID and role name to use for the account in which the cluster will be created, and the account in which keys for cluster envelope encryption are created. You can feel free to use the same account ID and role for both, but you'll need to make sure the user/role you're logged in as on your CLI can assume that role in that account. I'm not sure if this will affect the outcome.
3. I run `terraform apply -var-file deployments-prod-engineering-deployments-prod.tfvars` to initially create the cluster which does not create any problems
4. I change the `public_endpoint_access` variable to `false`
5. I rerun `terraform apply -var-file deployments-prod-engineering-deployments-prod.tfvars`
6. Hit the IAM error above

## Expected behavior

The UpdateClusterConfig API call made by Terraform succeeds without an IAM error and disables public endpoint access.

## Actual behavior

The error copied above is returned.

## Additional context

Attempting to perform `aws eks update-cluster-config --name lefranc-0 --resources-vpc-config endpointPublicAccess=false,endpointPrivateAccess=true --profile admin-engineering-deployments-prod-mfa --region eu-west-1` leads to the exact same error.

**Comment by ajpauwels** [comment]
I can also confirm that trying to change it via the UI doesn't work. I'm at a bit of a loss here, I assume the issue is that somehow the rule I'm assuming to try and do this isn't allowed to assume the created cluster role, but I thought that:
1. The trusted entity assuming the cluster role is not me, but the EKS service
2. I added my assumed role as allowed to assume the cluster role in the cluster role's trust relationship, still doesn't work

**Comment by supergrilo** [comment]
Any problem here! 

```
▶ cat eks.tf 
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.26"

  cluster_name    = "ir-k8s-dev"
  cluster_version = "1.22"

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false

  vpc_id     = "vpc-f247c196"
  subnet_ids = ["subnet-b311a1c5", "subnet-0012a276", "subnet-1c4e8444", "subnet-71ec0216", "subnet-01488259", "subnet-36ef0151"]

  eks_managed_node_group_defaults = {
    disk_size      = 100
    instance_types = ["m6i.large", "m5.large", "m5n.large", "m5zn.large"]
  }

  eks_managed_node_groups = {
    green = {
      min_size     = 1
      max_size     = 10
      desired_size = 1

      instance_types = ["t3.large"]
      capacity_type  = "SPOT"
    }
  }

  tags = {
    environment = "dev"
    terraform   = "true"
  }
}
```

```
│ Error: error creating EKS Cluster (ir-k8s-dev): InvalidParameterException: Role with arn: arn:aws:iam::646770040222:role/ir-k8s-dev-cluster-20220726161828400200000007, could not be assumed because it does not exist or the trusted entity is not correct
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "5e82efd0-40d9-4fcc-a343-36d27d482608"
│   },
│   ClusterName: "ir-k8s-dev",
│   Message_: "Role with arn: arn:aws:iam::646770040222:role/ir-k8s-dev-cluster-20220726161828400200000007, could not be assumed because it does not exist or the trusted entity is not correct"
│ }
│ 
│   with module.eks.aws_eks_cluster.this[0],
│   on .terraform/modules/eks/main.tf line 14, in resource "aws_eks_cluster" "this":
│   14: resource "aws_eks_cluster" "this" {
│ 
```

**Comment by bryantbiggs** [comment]
most likely the issue relates to the IAM entity who created the cluster (this entity is added automatically as a `system:masters` role) and any additional cluster auth when additional roles have not been added

**Comment by ajpauwels** [comment]
Does internal cluster auth interact/aws-auth configmap interact at all with a call to change public/private endpoint availability?

**Comment by supergrilo** [comment]
I  solved this on my environment. Basically are iam permissions. 
If you use iam.* will work as well 
I will try to test each role, one by one to set a restrictive permissions

**Comment by chaospuppy** [comment]
@bryantbiggs can you clarify what your suspicions are?  I'm running into this same issue with `18.26.6`, although the issue is persisting despite setting `cluster_endpoint_public_access` to `true` as a last resort.

**Comment by bryantbiggs** [comment]
you'll have to provide configs and steps to repro

**Comment by chaospuppy** [comment]
Our module terraform looks like this (vars substituted with representative values):
```
module "eks" {

  source  = "terraform-aws-modules/eks/aws"
  version = "18.26.6"

  # Metadata
  cluster_name    = "test-cluster"
  cluster_version = "1.21"

  # CloudWatch
  create_cloudwatch_log_group = false

  # API access
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false # setting to true didn't help

  # IAM
  create_iam_role               = true
  iam_role_permissions_boundary = "our-permissions-boundary-arn"
  # KMS Encryption
  create_kms_key                  = false
  cluster_encryption_config       = [{
      provider_key_arn = "our-key-arn"
      resources = ["secrets"]
  }]
  kms_key_deletion_window_in_days = 7
  enable_kms_key_rotation         = false

  # Addons
  cluster_addons = {
    # Available addons (as of June 30 2022):
    # adot
    # kube-proxy
    # vpc-cni
    # coredns
    # aws-ebs-csi-driver
    aws-ebs-csi-driver = {
      resolve_conflicts = "OVERWRITE"
      tags              = var.cluster_tags
    }
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {
      resolve_conflicts = "OVERWRITE"
    }
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }

  # Networking
  vpc_id                      = "our-vpc-id"
  subnet_ids                  = ["subnet1", "subnet2"]
  cluster_security_group_name = "test-cluster-eks-security-group"

  # Defaults for Managed Node Groups - applies to all node groups unless overridden in the node group configuration
  eks_managed_node_group_defaults = {
    create_iam_role = true
    disk_size       = "200"
    ami_type        = "AL2_x86_64"
    ami_id = "stock-eks-worker-node-ami"
  }

  # Managed Node Groups
  eks_managed_node_groups = var.eks_cluster_managed_node_groups

  # OIDC
  openid_connect_audiences = var.eks_cluster_openid_connect_audiences
}
```

We are uniquely constrained by a permissions boundary we have to attach to each role we create, which admittedly makes this more nuanced for us.  What I'm trying to get an understand of is what is happening at this stage of cluster creation  that could result in this error.  It seems like a self-explanatory error until you realize, as the others in this issue and in #2057 did, that the EKS role *does* exist and *does* have `eks.amazonaws.com` as a principal that can assume it:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "EKSClusterAssumeRole",
            "Effect": "Allow",
            "Principal": {
                "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

**Comment by ajpauwels** [comment]
@supergrilo can you elaborate on what you did to fix? I gave AdministratorAccess to the cluster IAM role but that did not resolve.

@bryantbiggs I will try adding new roles to the aws-auth configmap and see if that changes things.

**Comment by alejandro-gallardo-ntt** [comment]
Hi,

I have ran into the same issue and I could reproduce the error only in clusters with secrets encryption enabled. Adding root user to the key policy (like the module does by default when creating the kms) would solve the problem. 

[Default key policy - AWS Key Management Service](https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html)

But granting Describekey permission to the eks role of the cluster in the kms key was a better solution for me as it follows the least privilege principle.

https://docs.aws.amazon.com/eks/latest/userguide/enable-kms.html

You could modify the policy or create a kms grant like this:

```
resource "aws_kms_grant" "a" {
  name              = "my-role-grant"
  key_id             =  my-kms-key-id
  grantee_principal = module.eks.cluster_iam_role_arn
  operations        = ["DescribeKey"]

}
```

I hope it helps.

Regards.

**Comment by chaospuppy** [comment]
For us, it was a case of
```
"iam:DeleteServiceLinkedRole",
"iam:CreateServiceLinkedRole"
```
missing from the permission boundary we were placing on the EKS cluster role.  Based on the variety of solutions that people have had, it seems as though `InvalidRequestException` and `InvalidParameterException` during EKS Cluster creation stem from a wide range of IAM policy related issues.

**Comment by edalford11** [comment]
The issue for me was that my cluster was created in 2018. I had upgraded this module to the latest 18.26 version but it looks like the `AmazonEKSServicePolicy` is no longer being added to the cluster role in this new version. As stated in the note here https://docs.aws.amazon.com/eks/latest/userguide/service_IAM_role.html, clusters created on or after April 16, 2020 do not need that policy added to the cluster role any more. Since my cluster was created before then, I added

```
iam_role_additional_policies = [
  "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"
]
```

The error no longer comes up anymore.

**Comment by ajpauwels** [comment]
Thank you all for the additional potential fixes.

@alejandro-gallardo-ntt I've been suspecting it might be an issue with the IAM keys, as my keys are in a separate account from the cluster. Will be testing with keys in same account to verify if the issue is with IAM access to the other account.

I encourage others encountering an identical error to post their fixes in this thread. As @chaospuppy said, it seems like this error will cover a wide range of IAM issues stemming from a wide range of potential AWS setups. Having encountered little to no discussion of this error after a lot of googling, this issue may help lead people down the right path for their particular environment. I'll try to compile them as a final doc, @bryantbiggs would you be interested in a docs PR for IAM-related errors?
