### ISSUE TITLE
support specifying tags only for the managed node group

### ISSUE THREAD

**Issue by mmerickel** [terraform-aws-modules/terraform-aws-eks#2166]
In the similar vein as https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2084 it would be nice if the managed node groups could specify tags that only impacted the `aws_eks_node_group` resource. Currently the `tags` option in `eks_managed_node_group_defaults`, etc applies to all resources (launch template, security groups, iam roles, node groups) and there is not an option to impact only the node groups. Presumably a `node_group_tags` option would suffice.

**Comment by bryantbiggs** [comment]
What is the use case for this?

**Comment by mmerickel** [comment]
Well when adding extra tags like node-termination-handler/managed=true there’s just no sense in them appearing anywhere except in the node group. Ideally only the ASG but AWS doesn’t expose a simple api for that - would be even better if the node group resource returned the arn of the new ASG and we could just tag that.

**Comment by bryantbiggs** [comment]
This is how that can be solved today until native support is provided https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L673-L712

**Comment by mmerickel** [comment]
Thanks @bryantbiggs. A couple notes for anyone else:
- AWS automatically adds the autoscaler tags to managed node groups so the example code is not necessary.
- the NTH is not necessary according to https://github.com/aws/aws-node-termination-handler/issues/186#issuecomment-654301771 for managed node groups, so actually gets rid of my two main needs here.
