### ISSUE TITLE
kms_key_enable_default_policy does not default to true

### ISSUE THREAD

**Issue by nocode99** [terraform-aws-modules/terraform-aws-eks#2169]
## Description

`var.kms_key_enable_default_policy` in the description and README says it defaults to `true` but it is set to `false`. It's an easy PR fix but wasn't sure which way is the intended desire. Should it be false and fix the documentation or fix the default value?

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by bryantbiggs** [comment]
ah, this is a copy+paste error from the KMS module variable. In this case, the description should be updated to `false`

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.27.0 :tada:
