### ISSUE TITLE
Plan fails when `create_kms_key=true` and `create=false`

### ISSUE THREAD

**Issue by npapapietro** [terraform-aws-modules/terraform-aws-eks#2172]
## Description

When running `terraform plan` with the `create=false` and `create_kms_key=true` an error `Error: Null value found in list` is returned.  I believe this is because the `iam_role` for the cluster is hidden behind the `create` flag as well and null is passed to the kms module here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/640a99485eff31dfb5c671177c04d42023772260/main.tf#L105

## Versions

- Module version [Required]: v18.26.5

## Reproduction Code [Required]

```terraform
module "cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.26.5"

  create          = false
  create_kms_key  = true
  // ...
}
```

## Expected behavior

KMS creation is either dependent on `create` or updated on creation.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.26.6 :tada:
