### ISSUE TITLE
Facing "data.tls_certificate.this[0].certificates is empty list of object" in terraform plan command

### ISSUE THREAD

**Issue by codal-jayesh** [terraform-aws-modules/terraform-aws-eks#2173]
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/eks/main.tf line 211, in resource "aws_iam_openid_connect_provider" "oidc_provider":
│  211:   thumbprint_list = concat([data.tls_certificate.this[0].certificates[0].sha1_fingerprint], var.custom_oidc_thumbprints)
│     ├────────────────
│     │ data.tls_certificate.this[0].certificates is empty list of object
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.

Above error is coming again and again. Previous day it was working but today it is continuously throwing above error.

Please reply if anyone has faced above error or knowing solution.

Thanks,
Jayesh

**Comment by schmidp** [comment]
I am facing the same issue.

**Comment by stimmerman** [comment]
Same for me, a solution has been posted here: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2170#issuecomment-1191922960

**Comment by FernandoMiguel** [comment]
temp fix https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2170#issuecomment-1191922960

**Comment by codal-jayesh** [comment]
Thank you all of you guys, 

Now it has been resolved from #2170.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.26.6 :tada:
