### ISSUE TITLE
Unable to apply after upgrade from 18.26.1 to 18.26.6

### ISSUE THREAD

**Issue by rekcah78** [terraform-aws-modules/terraform-aws-eks#2178]
## Description

I get this error after upgrading module from 18.26.1 to 18.26.6, i think is due to the change in 18.26.1

│   on .terraform/modules/k8s/modules/self-managed-node-group/main.tf line 366, in resource "aws_autoscaling_group" "this":
│  366:               for_each = length(lookup(override.value, "launch_template_specification", {})) > 0 ? override.value.launch_template_specification : []
│ 
│ Invalid value for "default" parameter: the default value must have the same type as the map elements.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:

terraform -version 
Terraform v1.2.5
on darwin_arm64
- Provider version(s):

+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.23.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.4.0

## Additional context

I have 3 self_managed_node_groups

**Comment by pen-pal** [comment]
@rekcah78 can you share your terraform file as well
