### ISSUE TITLE
Ability to pass parameters to kubelet's config file

### ISSUE THREAD

**Issue by vchepkov** [terraform-aws-modules/terraform-aws-eks#2180]
Currently we supply custom max-pod values via `--kubelet-extra-args` 
kubelet reports that flag has been deprecated and config file should be used instead

```
Flag --max-pods has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
```

It would be useful for the module to provide ability to supply kubelet's config parameters

**Comment by bryantbiggs** [comment]
Because of the various different ways in which settings are passed to the bootstrap script, we only provide the minimum information necessary to join nodes to the cluster while letting users to provide additional functionality as needed through user data. This avoids having to keep up to date on things like this deprecation notice as well as the myriad of different ways these settings are passed to the kubelet

**Comment by vchepkov** [comment]
@bryantbiggs, what would you recommend to do for this case? 
using sed command  in `pre_bootstrap_user_data` to edit /var/lib/kubelet/kubeconfig  directly ?
Please advise. Thank you

**Comment by bryantbiggs** [comment]
I don't know what your setup/configuration is, but the solution would most likely be implemented via user data in some shape or form. You can check our examples for references https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L221-L231

**Comment by vchepkov** [comment]
Right, so the choices are either hack bootstrap.sh, so it will populate /var/lib/kubelet/kubeconfig or hack /var/lib/kubelet/kubeconfig  directly before script runs. From what I understand, that is the file that deprecation warning refers to

**Comment by bryantbiggs** [comment]
I think you are looking for https://github.com/awslabs/amazon-eks-ami/issues/873

**Comment by bryantbiggs** [comment]
if you come up with a better solution, please do share. The example I linked to was provided by a user of the module - it helps to share these solutions for others that might be running into similar situations

**Comment by bryantbiggs** [comment]
closing for now with the information provided above
