### ISSUE TITLE
How should I do to deploy one ASG per AZ so that cluster-autoscaler can work when using EBS?

### ISSUE THREAD

**Issue by luarx** [terraform-aws-modules/terraform-aws-eks#2186]
## Is your request related to a problem? Please describe.
I need to deploy one ASG per Availability Zone so that the cluster-autoscaler can work correctly when using EBS

## Describe the solution you'd like.
Be able to define one ASG per Availability Zone

Is there any documentation that explains how to do it? I haven't found them

Thanks in advance!

(Related issue but without a solution https://github.com/terraform-aws-modules/terraform-aws-eks/issues/637)

**Comment by bryantbiggs** [comment]
you can restrict what subnets are used in the  node groups which will restrict them to an AZ. So 3 node group definitions, each specifying a different subnet ID would achieve this

**Comment by luarx** [comment]
Awesome! Thanks a lot for the solution and for the quick response, you have all my respect 🙏
