### ISSUE TITLE
Two security groups for nodes one without rules

### ISSUE THREAD

**Issue by Aurrix** [terraform-aws-modules/terraform-aws-eks#2187]
## Description

Multiple security groups are created for EKS cluster with the given configuration. One of the groups is missing firewall rules that are supplied with configuration.

In the cluster networking tab I can see the following security groups:
<img width="166" alt="image" src="https://user-images.githubusercontent.com/31369395/182945679-70d2d268-ceb1-4419-a433-2df558102be9.png">

This is a list of security groups for the account:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/31369395/182945920-b82c5113-47ca-4679-bb00-738dbbdb6c36.png">

The one that is selected on the screenshot is created by EKS module and for some reason and does not have any rules attached to it. While others do.

Also, outputting security groups for cluster and nodes return the same ids as from the first screenshots (that are visible within the cluster). Though I see that the description is identical to the one provided by default in the module ( on line 367) for eks-managed-node-group.

## Versions

- Module version: 18.26.6
- Terraform version: v1.2.5
- Provider version(s): ~>4.24

## Reproduction Code

```
module "eks" {
  source       = "terraform-aws-modules/eks/aws"
  version      = "18.26.6"
  cluster_name = var.cluster_name

  vpc_id                    = data.terraform_remote_state.vpc.outputs.vpc_id
  subnet_ids                = data.terraform_remote_state.vpc.outputs.private_subnets
  cluster_enabled_log_types = []
  enable_irsa               = true

  # EKS Managed Node Group(s)
  eks_managed_node_group_defaults = {
    disk_size      = 10
    instance_types = ["t3.medium"]
  }

  eks_managed_node_groups = {
    default = {
      min_size     = 1
      max_size     = 2
      desired_size = 2

      instance_types = ["t3.medium"]
      capacity_type  = "ON_DEMAND"
    }
  }

  #   Extend cluster security group rules
  cluster_security_group_additional_rules = {
    ingress_self_all = {
      description = "Cluster to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    egress_all = {
      description      = "Cluster all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
  }

  node_security_group_additional_rules = {
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
  }
}
```

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/network_connectivity.md#security-groups

**Comment by Aurrix** [comment]
@bryantbiggs I see that one of the points in the readme that you have shared basically says that there will be an empty group per node:
```
Each node group (EKS Managed Node Group and Self Managed Node Group) by default creates its own security group. By default, this security group does not contain any additional security group rules. It is merely an "empty container" that offers users the ability to opt into any addition inbound our outbound rules as necessary
```
The problem that I have is that this security group blocks traffic for istio sidecar injection. Also, there is no easy way of referring to it from the module outputs to add rules manually. Could you advise on any workarounds?

**Comment by bryantbiggs** [comment]
you can disable its creation

**Comment by Aurrix** [comment]
@bryantbiggs don't you think that it is rather a bug? I would expect the only rules that I have specified to be created and applied. Though, new security groups are created the default EKS node group still affects the accessibility.

**Comment by Aurrix** [comment]
It seems like the group is actually created by configuration within eks_managed_node_groups object.

An example can be found [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L318)

So disabling or configuring solves my issue. I do believe though this should be added to the root readme.
