### ISSUE TITLE
aws_autoscaling_attachment overwritten by rerunning module

### ISSUE THREAD

**Issue by jpke** [terraform-aws-modules/terraform-aws-eks#219]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

If another terraform module managing ingress ALBs and ASG attachments is run after this module creates a cluster, then rerunning this module removes the ASG attachments created by the other module.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

- Create a cluster with `terraform-aws-eks
- Create an ALB and a target group
- Run the following code with variables matching resources created

```
data "aws_lb_target_group" "target_group" {
  name = "<target_group_name>"
}

data "aws_autoscaling_groups" "asg_name" {
  filter {
    name   = "key"
    values = ["Name"]
  }

  filter {
    name   = "value"
    values = ["<asg_name>"]
  }
}

resource "aws_autoscaling_attachment" "k8s-private-web" {
  autoscaling_group_name = "${element(data.aws_autoscaling_groups.asg_name.names, 0)}"
  alb_target_group_arn   = "${data.aws_lb_target_group.target_group.arn}"
}

```

- Rerun the terraform-aws-eks module. It will delete the ASG target group attachments

## What's the expected behavior?

Rerunning terraform-aws-eks will not try to make any changes.

## Are you able to fix this problem and submit a PR? Link here if you have already.

https://github.com/terraform-aws-modules/terraform-aws-eks/pull/218

## Environment details

* Affected module version: v1.4.0
* OS: OSX 10.14
* Terraform version: v0.11.10

**Comment by max-rocket-internet** [comment]
Doesn't this work?

```hcl
module "eu01_stg" {
  source                               = "git@github.com:terraform-aws-modules/terraform-aws-eks.git?ref=v1.7.0"
  cluster_name                         = "xxx-xxx"

  worker_groups = [
    {
      instance_type       = "m4.xlarge"
      asg_max_size        = 40
      target_group_arns = ["${data.aws_lb_target_group.target_group.arn}"]
    },
  ]
}
```

**Comment by jpke** [comment]
Thanks for the feedback!

We were able to provision our albs prior to running the module and then sending target_group_arns into it. We had to remove our aws_autoscaling_attachments in our alb module, and let this eks module handle attaching asgs to target groups.

Really liking working with this module!
