### ISSUE TITLE
The instance_metadata_http_tokens value doesn't propagate to EKS launch template copy on managed node groups

### ISSUE THREAD

**Issue by ferozeab** [terraform-aws-modules/terraform-aws-eks#2192]
Any value set to http_tokens inside metadata_option for managed_node_groups is not propagated onto the EKS managed copy of the provided launch template.
It doesn't matter if you specifically set optional or required to http_tokens, it is set to "Optional" by default. 

           #EKS managed node group
             managed_node_groups = {
	     mg_t2 = {
            node_group_name = "t2-managed-ondemand"
            instance_types  = ["t2.large"]
            subnet_ids      = var.private_subnets
	   
	   metadata_options = {
	  
               http_endpoint = "enabled"
               http_put_response_hop_limit = "2"
               http_tokens = "required"
      }
	  
    }

Terraform_version = "Terraform v1.0.1"

**Comment by bryantbiggs** [comment]
duplicate - please follow/use the issue template that is provided https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1977
