### ISSUE TITLE
Empty value on self_managed_node_groups_autoscaling_group_names when default node group not created

### ISSUE THREAD

**Issue by marpada** [terraform-aws-modules/terraform-aws-eks#2193]
## Description

When creating several self-managed node groups, but NOT the default node group, the output self_managed_node_groups_autoscaling_group_names contains an empty value.

```
self_managed_node_groups_autoscaling_group_names = [
  "bottlerocket-self-mng-2022080805253047320000002e",
  "complete-self-mng",
  "",
  "efa-20220808052530474100000030",
  "mixed-20220808052530475200000031",
]
```

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version :`18.26.6`

- Terraform version: `Terraform v1.2.6`
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v4.25.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1
+ provider registry.terraform.io/hashicorp/tls v3.4.0
```

## Reproduction Code [Required]

Use [self-managed group example](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/self_managed_node_group), but disable the creation of the default node group:

```
  self_managed_node_groups = {
    default_node_group = { create = false }
    ....
    }
```

## Expected behavior

output.self_managed_node_groups_autoscaling_group_names should only contain valid values

```
self_managed_node_groups_autoscaling_group_names = [
  "bottlerocket-self-mng-2022080805253047320000002e",
  "complete-self-mng",
  "efa-20220808052530474100000030",
  "mixed-20220808052530475200000031",
]
```

## Actual behavior

output.self_managed_node_groups_autoscaling_group_names includes an empty value.

```
self_managed_node_groups_autoscaling_group_names = [
  "bottlerocket-self-mng-2022080805253047320000002e",
  "complete-self-mng",
  "",
  "efa-20220808052530474100000030",
  "mixed-20220808052530475200000031",
]
```

## Additional context

This issue prevents from using output.self_managed_node_groups_autoscaling_group_names for creating other resources based on autoscaling names. Sometimes the generated list can be filtered out but this not always works, for instance if needed to use it in a count or for_each parameter as Terraform cannot determine the content during the plan.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.27.1 :tada:
