### ISSUE TITLE
ResourceInUseException: Cannot Delete Fargate Profile

### ISSUE THREAD

**Issue by raghavgupta0** [terraform-aws-modules/terraform-aws-eks#2194]
Hi , 
I am getting the below error for "cn-northwest-1", for other regions it's working fine.

Error: error deleting EKS Fargate Profile (fgeks-eks-cluster:gatekeeper): ResourceInUseException: Cannot Delete Fargate Profile gatekeeper because cluster fgeks-reference-cluster currently has an update in progress

Terraform v1.1.4
hashicorp/kubernetes v2.12.1
hashicorp/aws v4.25.0
Kubernetes 1.21

I am getting this error for all present/created Fargate profiles.

**Comment by bryantbiggs** [comment]
this is not a module issue, the issue is in your error message posted ` because cluster fgeks-reference-cluster currently has an update in progress`
