### ISSUE TITLE
managed_node_group submodule suspending processes

### ISSUE THREAD

**Issue by cmsmith7** [terraform-aws-modules/terraform-aws-eks#2195]
## Is your request related to a new offering from AWS?
No

Is this functionality available in the [AWS provider for Terraform]
Yes ✅: hashicorp/aws 4.11.0 .. terraform 1.1.2

## Is your request related to a problem? Please describe.
We currently deploy our EKS cluster using terraform but without the use of the EKS module (as it wasn't available at the time of cluster deployments).  We have migrated to use the eks-managed-node-groups submodule from our own self managed deployed node groups and currently deploy one managed spot and one managed ondemand node group to each cluster via the submodule.  We have experienced issues with spot node group and specifically AZRebalance on our spot node group.  I can see in the self_managed_node group module you have the ability to specify suspended_processes and also if you are using the core EKS module to deploy your cluster and node groups via workers_group_defaults but It doesn't appear that you are able to specify suspended_processes specifically in the managed_node_group submodule itself.  I apologise if I have missed something in the docs.  I have had cases open with AWS and even though we provide 8+ similar instance types into the module we find that AZ's fail to procure spot instances very regularly and the cluster constantly tries to rebalance so would be great to have the ability to suspend_processes.

## Describe the solution you'd like.
A method to provide a way to suspend processes in the managed_node_group submodule.

## Describe alternatives you've considered.
I would like to know for certain it is not possible via the module before moving on to alternate solutions.  Or if the functionality is not there for a reason.

## Additional context
n/a

**Comment by bryantbiggs** [comment]
This would be down to the EKS managed node group service since it creates/manages the underlying autoscaling group. We only have the ability to control what the:
1. EKS managed node group service supports
2. AWS Terraform provider supports
