### ISSUE TITLE
Ability to disable addons in eks module or resource

### ISSUE THREAD

**Issue by dpa456** [terraform-aws-modules/terraform-aws-eks#2196]
## Is your request related to a problem? Please describe.

kube-proxy is installed by default in the eks module, but I want to self hosted for custom kube-proxy
Therefore, I would like to have an option not to install it.

> Although it provides a method using kubectl, it does not able to self-host in terraform.
[Updating the kube-proxy self-managed add-on](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)

## Describe the solution you'd like.

I would like to have an option not to install by default addons.

## Describe alternatives you've considered.

> 1. module "eks"

```
module "eks" {
  cluster_addons_kube_proxy_enable = false
  cluster_addons_coredns_enable = true
}
```

> 2. resource "aws_eks_addon"

```
resource "aws_eks_addon" "kube_proxy" {
  enable = false
}

resource "aws_eks_addon" "coredns" {
  enable = true
  ...
}
```

## Additional context

I checked that addons is installed by default through eks module, so please let me know if there is any difference
I would appreciate it if you could share the relevant context.

**Comment by bryantbiggs** [comment]
These are not installed by default by the module - they are installed by the EKS service.
