### ISSUE TITLE
cluster_encryption_policy_use_name_prefix is a bool, documentation error

### ISSUE THREAD

**Issue by maclarensg** [terraform-aws-modules/terraform-aws-eks#2198]
## Description
https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest?tab=inputs

On the documentation the variable `cluster_encryption_policy_use_name_prefix` states it is a string but it is a boolean instead

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.28.0 :tada:
