### ISSUE TITLE
Provide an output for the eks-managed-node-group launch template name

### ISSUE THREAD

**Issue by romogo17** [terraform-aws-modules/terraform-aws-eks#2199]
## Background
Currently, within the `eks-managed-node-group` submodule, there are output variables for getting the launch template `id`, `arn` and `latest_version` — but not the launch template `name`

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c0f14fbdeffaee36e865e90328e633b73c4e2e10/modules/eks-managed-node-group/outputs.tf#L5-L19

When we use a prefix for the launch template name, a portion of the resulting name will not be known beforehand, which makes extracting the final name a bit difficult. 

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c0f14fbdeffaee36e865e90328e633b73c4e2e10/modules/eks-managed-node-group/main.tf#L45-L49

## Describe the solution you'd like.
Adding another output for the launch template name

```hcl
output "launch_template_name" {
  description = "The name of the launch template"
  value       = try(aws_launch_template.this[0].name, "")
}
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.28.0 :tada:
