### ISSUE TITLE
Unable to pass into user-data Env variables placeholders 

### ISSUE THREAD

**Issue by md2k** [terraform-aws-modules/terraform-aws-eks#220]
# I have issues
We want to use Env Vars we collect during cloud-init to pass them as parts of the extra args to populate some labels for kubelet.
For example we set: 
```
worker_groups = [
    {
      name                 = "master-pool-a"
      asg_desired_capacity = 2
      asg_max_size         = 5
      asg_min_size         = 2
      key_name             = "xxxxxxxxxx"
      instance_type        = "t2.medium"
      pre_userdata         = "ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)"
      kubelet_extra_args   = "--node-labels=node-role.kubernetes.io/master=true,k8s.amazonaws.com/eniConfig=$ZONE --register-with-taints=node-role.kubernetes.io/master=true:NoSchedule"
    },
]
```

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
While `pre_userdata` set correctly and env variables populated properly, Extra args use single quote escaping what preventing us from use variables inside parameters

## What's the expected behavior?
Expected behaviour, when user-data executed, it do evaluation of extra args with desired values of specified variables

This is very easy to fix , by simple change from single quote escape to double quotes. Is there any particular reason to use single quotes? 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/templates/userdata.sh.tpl#L7

**Comment by md2k** [comment]
anyone from maintainers?

**Comment by max-rocket-internet** [comment]
> Is there any particular reason to use single quotes?

Not that I know of!

**Comment by max-rocket-internet** [comment]
Feel free to make and test a PR to remove the quotes.
