### ISSUE TITLE
strange IAM/lambda while creating the cluster

### ISSUE THREAD

**Issue by vinisfreitas-sinerlog** [terraform-aws-modules/terraform-aws-eks#2200]
## Description

looking at the eks cluster authentication logs, while creating it, I can see some weird things, like a strange role arn, for example:

`level=info msg="mapping IAM role" groups="[]" role="arn:aws:iam::782030699418:role/AWSWesleyClusterManagerLambda-Add-AddonManagerRole-AAAABBBBCCCC" username="eks:addon-manager"`

`level=info msg="mapping IAM role" groups="[]" role="arn:aws:iam::782030699418:role/AWSWesleyClusterManagerLambda-NodeManagerRole-DDDDEEEEFFFF" username="eks:node-manager"`

`level=info msg="mapping IAM role" groups="[]" role="arn:aws:iam::782030699418:role/AWSWesleyClusterManagerLambda-FargateManagerRole-GGGGHHHHJJJJ" username="eks:fargate-manager"`

I searched a bit in the repo, but nothing about this, any ideas what it could be this?

**Comment by bryantbiggs** [comment]
let me see what I can find out and get back to you @vinisfreitas-sinerlog
