### ISSUE TITLE
Complete example and AWS Load Balancer Controller security groups

### ISSUE THREAD

**Issue by pmcenery-bl** [terraform-aws-modules/terraform-aws-eks#2202]
The complete example does not include any security groups that allow the control plane to communicate with the nodes. It would appear that a number of people have had this problem when upgrading to v18, and one solution can be seen [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2462#issuecomment-1031624085). Maybe a more generic rule that would be less likely to cripple the cluster would be something such as this which allows the control plane to talk to any node and port on the nodes:

```terraform
node_security_group_additional_rules = {
    ingress_control_plane_all = {
      description                   = "Control plane to all ports/protocols"
      protocol                      = "-1"
      from_port                     = 0
      to_port                       = 0
      type                          = "ingress"
      source_cluster_security_group = true
    }
    [...]
}
```

Pleaase can the example be updated to reflect this requirement.

**Comment by bryantbiggs** [comment]
The examples demonstrate the various ways that the module can be configured and it does provide example usage of various security group rule additions. The module has taken a stance of least access to start from a more secure posture and users are allowed to extend that access to suit their workloads.
