### ISSUE TITLE
EKS Access after deploy cluster

### ISSUE THREAD

**Issue by mauriciovillagran25** [terraform-aws-modules/terraform-aws-eks#2206]
## Description

I can't EKS cluster after the last version of the module. In the AWS console appear this warning:

"Your current user or role does not have access to Kubernetes objects on this EKS cluster
This may be due to the current user or role not having Kubernetes RBAC permissions to describe cluster resources or not having an entry in the cluster’s auth config map."

Do I need to modify anything in my code?

**Comment by tutunak** [comment]
Check the example in the README. You need to configure aws-auth

```
  # aws-auth configmap
  manage_aws_auth_configmap = true

  aws_auth_roles = [
    {
      rolearn  = "arn:aws:iam::66666666666:role/role1"
      username = "role1"
      groups   = ["system:masters"]
    },
  ]

  aws_auth_users = [
    {
      userarn  = "arn:aws:iam::66666666666:user/user1"
      username = "user1"
      groups   = ["system:masters"]
    },
    {
      userarn  = "arn:aws:iam::66666666666:user/user2"
      username = "user2"
      groups   = ["system:masters"]
    },
  ]
```

**Comment by bryantbiggs** [comment]
what @tutunak is correct - the identity that created the cluster is automatically added to the cluster at time of creation as a `systems:master` role in the cluster (you won't see this in the aws-auth configmap). If this is not the same identity you log into the console with, you will see the error described. Simply add your role/user to the configmap under the appropriate group(s).
