### ISSUE TITLE
Add EBS CSI policy

### ISSUE THREAD

**Issue by intention-attention** [terraform-aws-modules/terraform-aws-eks#2207]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider

## Is your request related to a problem? Please describe.
Unable to apply deployments with persistence volumes

## Describe the solution you'd like.
Attach AmazonEBSCSIDriverPolicy to resource "aws_iam_role_policy_attachment" "this" on eks-managed-node-group module

## Additional context
I was having issues deploying helm charts into an EKS cluster due to this. Adding the policy sorted this out for me

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-role-for-service-accounts-eks

**Comment by intention-attention** [comment]
@bryantbiggs thanks for your answer. The underlying idea was to attach that specific policy to the role (name formed with <cluster_name>-eks-node-group-<timestamp> and with AWS Service: ec2 as trusted entity) that is automatically added.
More specifically when aws-ebs-csi-driver cluster addon is added to cluster_addons .

**Comment by bryantbiggs** [comment]
Yes, you can create the role as per the link and pass it in to the EBS CSI driver addon

**Comment by tutunak** [comment]
@bryantbiggs, I recently had the same problem. EKS cluster created by this module already had a pg2 storage class. And without this policy, it won't work. In the module, some AWS policies already presented ->[attached policies]( https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0957d674456373a47ab22d09073b4ef7af584fd3/modules/eks-managed-node-group/main.tf#L449)

`
# Policies attached ref https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group
resource "aws_iam_role_policy_attachment" "this" {
  for_each = var.create && var.create_iam_role ? toset(compact(distinct(concat([
    "${local.iam_role_policy_prefix}/AmazonEKSWorkerNodePolicy",
    "${local.iam_role_policy_prefix}/AmazonEC2ContainerRegistryReadOnly",
    var.iam_role_attach_cni_policy ? local.cni_policy : "",
  ], var.iam_role_additional_policies)))) : toset([])

  policy_arn = each.value
  role       = aws_iam_role.this[0].name
}`

looks like this policy also can be added

**Comment by intention-attention** [comment]
@tutunak thanks to bring extra details.
@bryantbiggs I could create a role but it would need the other existing policies. The assumed role overrides in the instance could cover that as referred by @tutunak 
If it is possible to add another element in the list with "${local.iam_role_policy_prefix}/AmazonEBSCSIDriverPolicy" it would even better than what we already have available.
Thanks for your work.

**Comment by zirpu** [comment]
I added the EBSCSIDriverPolicy via
```
      iam_role_additional_policies = [
        "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
      ]
```
that works.

**Comment by bryantbiggs** [comment]
you can certainly attach the AWS managed policy to all of the nodes as @zirpu has pointed out above, but what I am referring to is only providing the permissions to the addon itself. Here is an example where the the IRSA is passed to the VPC CNI addon and a similar approach can be used for the EBS CSI driver https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L61

**Comment by tutunak** [comment]
Yes, it will work. But the default configured EKS, that created by this module, won't work in the part of PV creation without this policy. Unfortunately, it is not obvious.

**Comment by bryantbiggs** [comment]
this module does not provision anything related to the EBS CSI driver

**Comment by tutunak** [comment]
Yes, doesn't provide. But AWS adds gp2 storage class by default. 
`kubectl get storageclass`
```
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  34m
```

Nothing additional was configured by me. I'm using EKS based on Kubernetes 1.23

**Comment by bryantbiggs** [comment]
got it.

so back to what I said before - users can attach the managed policy to the node, or the IRSA role to the addon. Either way, there isn't any change required here at the module level

**Comment by a0s** [comment]
@bryantbiggs Could you please share example if attaching role to the addon? Would it be something like a 
```
clusterAddons: {
  "aws-ebs-csi-driver": {
    resolve_conflicts: "OVERWRITE",
    addon_version: "v1.10.0-eksbuild.1",
    serviceAccountRoleArn: ".... irsa bla bla " 
  }
}

**Comment by gohmc** [comment]
Like this:

```
cluster_addons = {
  aws-ebs-csi-driver = {
    resolve_conflicts = "OVERWRITE"
    addon_version = "xxxxx"
    service_account_role_arn = module.<name>.iam_role_arn
  }
}
```

**Comment by a0s** [comment]
Hm, `terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks` requires existing eks cluster in `oidc_providers` block.
But `terraform-aws-modules/eks/aws` requires existing role (from irsa module) in `cluster_addons` block.. Is it chicken and egg problem or am i missed something??

**Comment by bryantbiggs** [comment]
It resolves just fine with this module - I don't have much experience with the CDK

See docs here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/irsa_integration.md
