### ISSUE TITLE
Duplicate Security Group Rule Error

### ISSUE THREAD

**Issue by davidlcan** [terraform-aws-modules/terraform-aws-eks#2210]
## Description

We want to add logic to allow egress access to github through ssh, so we use `data "github_ip_ranges" "ip_ranges" {}` to get the allowed ip ranges (https://api.github.com/meta) dynamically. Then we use below code to add egress rules for the allowed ip ranges.
```
egress_github_ssh = {
      description = "Egress to GitHub repos through SSH"
      type        = "egress"
      from_port   = 22
      to_port     = 22
      protocol    = "tcp"
      # https://api.github.com/meta
      cidr_blocks = data.github_ip_ranges.ip_ranges.git_ipv4
}
```

But whenever the value returned changes, terraform apply always return below error:
```
│ Error: [WARN] A duplicate Security Group rule was found on (sg-08c3a111662c4da4a). This may be
--
  | │ a side effect of a now-fixed Terraform issue causing two security groups with
  | │ identical attributes but different source_security_group_ids to overwrite each
  | │ other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
  | │ information and instructions for recovery. Error: InvalidPermission.Duplicate: the specified rule "peer: 192.30.252.0/22, TCP, from port: 22, to port: 22, ALLOW" already exists
  | │ 	status code: 400, request id: 7b8c0250-0f6c-48c3-8459-35529c2da589
  | │
  | │   with module.eks.module.eks.aws_security_group_rule.node["egress_github_ssh"],
  | │   on ../../../../modules/eks/vendor/github.com/terraform-aws-modules/terraform-aws-eks/node_groups.tf line 166, in resource "aws_security_group_rule" "node":
  | │  166: resource "aws_security_group_rule" "node" {
```

This looks quite similar as https://github.com/terraform-aws-modules/terraform-aws-eks/issues/984. I suspect that it can be fixed similarly. My current workaround is to delete `egress_github_ssh` and then apply. After it's deleted, add it back and apply again, which is inconvenient. It will be nice if it can be fixed.

Thanks for your help.

- [*] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 18.6.0

- Terraform version: v0.14.11

- Provider version(s): aws provider 3.72.0

## Reproduction Code [Required]

Steps to reproduce the behavior: As I mentioned above in the description, if we set the dynamic ip ranges of github to `node_security_group_additional_rules` and when the ip ranges change, we see this issue happen during terraform apply.

## Expected behavior

We expect that it can correctly replace the changed ip ranges without error.

## Actual behavior

It reports duplicate Security Group rule was found. Maybe as mentioned in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/984, it is performing a create then destroy of the security group rule. This won't work as the rules must be firstly deleted and then created.

**Comment by bryantbiggs** [comment]
Usually you want to avoid computed/unknown values as keys but not sure how else to get around this uniqueness, but I think you want to do something like the following:

```hcl
locals {
  github = { for cidr in data.github_ip_ranges.this.git_ipv4 :
    cidr => {
      description = "Egress to GitHub repos through SSH"
      type        = "egress"
      from_port   = 22
      to_port     = 22
      protocol    = "tcp"
      cidr_blocks = cidr
    }
  }
}
```

**Comment by davidlcan** [comment]
Hi @bryantbiggs , thanks for your response. Yeah, your suggestion can be used as a workaround. This issue can be closed. Thanks again for your help.
