### ISSUE TITLE
`disk_size` not respected when directly calling MNG submodule & using custom LT

### ISSUE THREAD

**Issue by kencieszykowski** [terraform-aws-modules/terraform-aws-eks#2212]
## Description

When calling the Managed Nodegroup Submodule here directly, the `disk_size` var is not respected when using a custom launch template.  The nodes are all created with the default 20Gi of space, with no effect when changing the `disk_size` var in the module call.

- [ x ] ✋ I have searched the open/closed issues and my issue is not listed:  There was a closed ticket that was effectively what I'm calling out here; but it was closed as the user didn't populate any details or fill out this template.  Everything else I found using `disk_size` is using the parent module. 

## Versions

- Module version: 18.28.0

- Terraform version: 1.0.3

## Reproduction Code

```
module "eks_managed_node_group" {
  source = "terraform-aws-modules/eks/aws//modules/eks-managed-node-group"

  name            = "cluster-name-nodegroup"
  cluster_name    = "cluster-name"
  cluster_version = "1.21"

  vpc_id     = "vpc-xxx"

  // The following variables are necessary if you decide to use the module outside of the parent EKS module context.
  // Without it, the security groups of the nodes are empty and thus won't join the cluster.
  cluster_primary_security_group_id = "sg-xxx"
  cluster_security_group_id = "sg-xxx"
  
  // Creation flags
  create_iam_role = "false"
  create_security_group = "false"
  
  // Added variables from the example on Module
  iam_role_arn = "arn:aws:iam::000:role/eks-worker"
  launch_template_name = "sample-nodegroup-name"
  subnet_ids = ["subnet-xxx","subnet-xxx","subnet-xxx"]
  vpc_security_group_ids = ["xxx"]
  key_name = "xxx"
  disk_size = 400
  
  min_size     = 3
  max_size     = 3
  desired_size = 3

  instance_types = ["c5a.4xlarge"]
  capacity_type  = "ON_DEMAND"

  tags = {
    Terraform   = "true"
  }
}
```

Initial build succeeds; but `disk_size` is not respected.

## Expected behavior

I would expect that the disk size on the nodes launched from this LT and into the node group would have a disk size of 400Gi.

## Actual behavior

These nodes are getting the default 20Gi disk size; with no means to increase it (other than in the console).

## Additional context

Taking a look at the custom LT Terraform, it seems like the `disk_size` isn't getting mapped correctly when calling the module directly.  It seems tied into `ebs_mappings` from a parent module.

When using a default LT, it does seem like there is mapping for this var, but that looks like the only place.

**Comment by bryantbiggs** [comment]
`disk_size` is only applicable when using the default EKS managed node group launch template. This module defaults to a custom launch template for a number of reasons, so you'll need to adjust EBS volume settings using https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L285-L298

**Comment by kencieszykowski** [comment]
> `disk_size` is only applicable when using the default EKS managed node group launch template. This module defaults to a custom launch template for a number of reasons, so you'll need to adjust EBS volume settings using https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L285-L298

Hah-- just found that was happening after I posted this.  Appreciate the words to back it up!

**Comment by aaronborden-rivian** [comment]
👋  I just ran into this as well. Would you consider a) updating the docs so it's clear `disk_size` only applies to the default manged node group launch template, which isn't used by default or b) using [coalesce](https://www.terraform.io/language/functions/coalesce) within the custom launch template so that absent a device mapping with `volume_size`, `disk_size` would be applied:

```
resource "aws_launch_template" "this" {
  count = var.create && var.create_launch_template ? 1 : 0
  # ...
 
  dynamic "block_device_mappings" {
    for_each = var.block_device_mappings
    content {
      # ...
      dynamic "ebs" {
        for_each = flatten([lookup(block_device_mappings.value, "ebs", [])])
        content {
          # ...
          volume_size           = coalesce(lookup(ebs.value, "volume_size", null), try(var.disk_size, null))
        }
      }
    }
  }

**Comment by rgarrigue** [comment]
The suggestion b) makes a lot of sense. I could have properly read the doc of course, but `disk_size` seemed so obviously what I needed that I didn't paid attention to the result until my cluster started dying in its tiny 20gb default disk size.

And even with the link above, it tooks some time to get the block_device_mappings right to match the current settings, except for an increased disk size
