### ISSUE TITLE
Question about default node security group

### ISSUE THREAD

**Issue by a-suenami** [terraform-aws-modules/terraform-aws-eks#2213]
Thank you for providing us with a great module. I have only one question regarding this module.

I have the following comment about the cluster node security group.
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf#L9-L13

And the referenced page describes as below:

Rule type | Protocol | Ports | Source | Destination
-- | -- | -- | -- | --
Inbound | All | All | Self |  
Outbound | All | All |   | 0.0.0.0/0 (IPv4) or ::/0 (IPv6)

It seems that all communication between self is allowed, but in fact, communication other than DNS is not allowed by default.
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf#L86-L117

This was causing me to not be able to connect to the Pod, on which my application was running, and my requests were timing out.

I solved the problem by adding the following configuration

```hcl
node_security_group_additional_rules = {
  node_to_node_all_ingress = {
    self = true
    description = "Node to node all traffic"

    protocol = "all"
    from_port = 0
    to_port = 0
    type = "ingress" }
  }
  node_to_node_all_egress = {
    self = true
    description = "Node to node all traffic"

    protocol = "all"
    from_port = 0
    to_port = 0
    type = "egress"
  }
}
```

Is this a specification?
I'm hoping it is default and not additional.

**Comment by bryantbiggs** [comment]
please see the provided documentation https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/network_connectivity.md#network-connectivity

**Comment by a-suenami** [comment]
@bryantbiggs 
Thank you for sharing the document. I hadn't checked it thoroughly. :bow:
