### ISSUE TITLE
Complete example file insufficiently documented

### ISSUE THREAD

**Issue by schollii** [terraform-aws-modules/terraform-aws-eks#2215]
## Description

Currently the example `examples/complete/main.tf` shows a lot of features and it is hard to tell whether some of them are examples of possibilities vs best practice. Eg kms + encryption of secrets is a best practice, whereas I presume that the node security groups are the opposite (they open pathways that should only be available in exceptional circumstances). 

I would like to submit a PR with comment placeholders where clarifications are needed, then we could use the PR discussion to help me figure out what to write. Does that work? 

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 18.29

## Reproduction Code [Required]

Look at examples/complete/main.tf

## Expected behavior

Many lines in that file should have a comment explaining purpose 

## Actual behavior

No comments explaining why certain configuration elements are used, and the description of associated inputs is insufficient to figure it out.

**Comment by bryantbiggs** [comment]
As we have stated [here](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples#examples), the examples are not representative of "best practices" and its still up to users to know how they should configure the module to suit their workload and requirements. We will have some changes coming soon around this but the tl;dr is:
- Reference https://github.com/clowdhaus/eks-reference-architecture
- Reference https://github.com/aws-ia/terraform-aws-eks-blueprints

**Comment by schollii** [comment]
Keeping this open until I can see the "changes coming soon" mentioned by @bryantbiggs

**Comment by bryantbiggs** [comment]
It is coming in v19 https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2250/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R25
