### ISSUE TITLE
module overrides load_balancers configuration for self managed node group ASGs

### ISSUE THREAD

**Issue by arpanadhikari** [terraform-aws-modules/terraform-aws-eks#2217]
## Description

Since the new module version v18.x doesn't support attaching classic load balancers to ASGs. We have to separately attach load balancers using the `aws_autoscaling_attachment` terraform resource.

However, for terraform-aws-eks managed ASGs, every time we run a `terraform apply`, the module removes this association leading to the load balancers being removed from ASGs, causing an outage.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note
This is relevant for self managed node group ASGs.

## Versions

- Module version [Required]:

- Terraform version:
<1.1.3
- Provider version(s):
v18.18.x

## Reproduction Code [Required]
Create a new alb_attachment.tf
```hcl
resource "aws_autoscaling_attachment" "test" {
  count                                  = length(module.eks.self_managed_node_groups_autoscaling_group_names)
  autoscaling_group_name                 = module.eks.self_managed_node_groups_autoscaling_group_names[count.index]
  elb                                    = "elb-arn"
}
```

- Add the above  configuration to your eks module usage.
- Run terraform apply.
- Run terraform plan.
- Notice the module try to remove the previously created ELB->ASG association.
- 

Using Workspaces

Cache cleared.

See steps above for reproducing this issue.

## Expected behavior

Module should ignore changes to ELB associations with ASG since it's no longer managing this part of the configuration.

## Actual behavior

Module overrides externally added config for ELB-> ASG association.

**Comment by arpanadhikari** [comment]
Created a PR to resolve this issue.
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2218

**Comment by bryantbiggs** [comment]
I will post the question I left on the PR here as well - I'm curious, do you not utilize the AWS load balancer controller for ingress?

**Comment by arpanadhikari** [comment]
> I will post the question I left on the PR here as well - I'm curious, do you not utilize the AWS load balancer controller for ingress?

We do. But some of the clusters do not have load balancer controllers so we have to attach long-lived load balancers deployed separately using terraform.

**Comment by bryantbiggs** [comment]
see comment here https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2218#issuecomment-1238650527
