### ISSUE TITLE
Self Managed Node group auth config map inlcude path and doesnt joining cluster

### ISSUE THREAD

**Issue by apothini** [terraform-aws-modules/terraform-aws-eks#2221]
## Description

Self Managed Node group auth config map inlcude path and doesnt joining cluster.
aws auth config doesnt read the right role for worker nodes - this includes path of the role thorugh the module
 "rolearn": "arn:aws:iam::880459142958:role/delegatedadmin/developer/app-eks-wg-role"
      "username": "system:node:{{EC2PrivateDNSName}}"
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::880459142958:role/delegatedadmin/developer/data-eks-wg-role"
      "username": "system:node:{{EC2PrivateDNSName}}"
And aws documentation shows 
The role ARN can't include a path such as role/my-team/developers/my-role. The format of the ARN must be arn:aws:iam::111122223333:role/my-role. In this example, my-team/developers/ needs to be removed.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by bryantbiggs** [comment]
paths in the IAM role are not supported in the configmap - this is outside the purview of the module
