### ISSUE TITLE
EKS clusters created with this module fail to work with ALB Ingress Controller 

### ISSUE THREAD

**Issue by trolleksii** [terraform-aws-modules/terraform-aws-eks#2223]
## Description

EKS clusters created with this module have issues running ALB Ingress Controller due to the presence of the tag ` "kubernetes.io/cluster/${var.cluster_name}" = "owned"` on the node_security_group. The ingress controller keeps spamming following error: 

```JSON
{
  "level": "error",
  "ts": 1662575681.565169,
  "logger": "controller-runtime.manager.controller.targetGroupBinding",
  "msg": "Reconciler error",
  "reconciler group": "elbv2.k8s.aws",
  "reconciler kind": "TargetGroupBinding",
  "name": "k8s-argocd-argocdse-ace231793c",
  "namespace": "argocd",
  "error": "expect exactly one securityGroup tagged with kubernetes.io/cluster/int-cluster for eni eni-085f19bc4667e3c34, got: [sg-065d86cd7ae244685 sg-0667d0816d900666c] (clusterName: int-cluster)"
}
```

As it appears after the installation procedure this tag is present in two SGs:
1. SG named `eks-cluster-sg-MY_CLUSTER-UNIQUE_ID` which is created automatically and must have this tag according to [AWS Docs](https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html)
2. SG for node groups [created by this module](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9e184dddf4daabdd4f62bf938b03894009aa4de4/node_groups.tf#L148)

When I manually remove the tag from the Node Group SG the ingress controller is able to reconcile and build the model.

I did a quick research and didn't find a requirement from AWS to have this tag on the Node Group SG.

Of course I could create a security group outside of the module with rules copy-pasted from the module code but that doesn't make much sense given that this functionality is already implemented and there's to reason to have that tag on that particular security group.

I'd like to ask to remove this tag from the module and I prepared a [PR](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2224) to do so.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 18.29.0

- Terraform version:
1.2.8
- Provider version(s):
v4.27.0

## Reproduction Code [Required]

Code from [examples/eks_managed_node_group](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/eks_managed_node_group) was used to validate the issue.

ALB Ingress controller v2.4 installed with helm following the [official installation guide](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/)

1. Create a cluster with the example code (variable `create_node_security_group` is true by default)
2. Deploy the ALB Ingress Controller
3. Deploy any workload with an Ingress resource

## Expected behavior

ALB Ingress Controller should successfully reconcile and targets should appear in the ALB Target Group.

## Actual behavior

Ingress controller keeps spamming error about duplicate tag, target group remains empty. If the tag is removed manually the problem disappears.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.29.1 :tada:
