### ISSUE TITLE
List of values for "eks_managed_node_groups"

### ISSUE THREAD

**Issue by thedusansky** [terraform-aws-modules/terraform-aws-eks#2232]
Dear team, 

Maybe this is not the best place to ask, but cannot find another way - 
I'm having issues finding the list of values for _eks_managed_node_groups_ (values to be assigned to the node group). 
Could you please point me to the part of the code where I can find the full list of values for the managed node group? 
Many thanks.

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/eks-managed-node-group/variables.tf

**Comment by thedusansky** [comment]
> 

Thanks Bryant,
I appreciate it!
