### ISSUE TITLE
Timeout waiting on cluster to become active

### ISSUE THREAD

**Issue by sfloyd-tn** [terraform-aws-modules/terraform-aws-eks#2233]
## Description

I am using an almost exact copy of the managed_nodes example found here: https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/eks_managed_node_group

When I run apply it takes roughly an hour and then will time out with the following error:
```
module.eks.aws_eks_cluster.this[0]: Still creating... [57m26s elapsed]
╷
│ Error: error waiting for EKS Cluster (xxxxxx-eks) to create: timeout while waiting for state to become 'ACTIVE' (last state: 'CREATING', timeout: 30m0s)
│
│   with module.eks.aws_eks_cluster.this[0],
│   on .terraform/modules/eks/main.tf line 14, in resource "aws_eks_cluster" "this":
│   14: resource "aws_eks_cluster" "this" {
```
When I check in the AWS console I can see the cluster and also see that it is already `active`. If I then try and run apply again I get the following error:
```
aws_security_group.remote_access: Modifications complete after 2s [id=sg-0xxxxx3]
╷
│ Error: error creating EKS Cluster (xxxxxx-eks): ResourceInUseException: Cluster already exists with name: xxxxxx-eks
│ {
│   RespMetadata: {
│     StatusCode: 409,
│     RequestID: "27740053-7d00-40e6-8f0c-8f26482cec70"
│   },
│   ClusterName: "xxxxxx-eks",
│   Message_: "Cluster already exists with name: xxxxxx-eks"
│ }
│
│   with module.eks.aws_eks_cluster.this[0],
│   on .terraform/modules/eks/main.tf line 14, in resource "aws_eks_cluster" "this":
│   14: resource "aws_eks_cluster" "this" {
```

- [ x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
`registry.terraform.io/terraform-aws-modules/eks/aws 18.29.0 for eks`

- Terraform version:
```
$ terraform -version
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.0.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.13.1
+ provider registry.terraform.io/hashicorp/tls v4.0.2
```

## Reproduction Code [Required]

The code I used is here...exactly but with my own vars subbed in where needed:
https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/eks_managed_node_group

## Expected behavior

Should be able to run the code from end to end without failing.

## Actual behavior

Apply times out waiting for eks cluster to become `active` while it already is `active` as seen in the AWS console.

**Comment by bryantbiggs** [comment]
> The code I used is here...exactly but with my own vars subbed in where needed:
[master/examples/eks_managed_node_group](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/eks_managed_node_group?rgh-link-date=2022-09-16T14%3A51%3A54Z)

this doesn't show a reproduction - there are other factors that largely influence EKS cluster issues, such as networking settings and account permissions/SCPs

All I can say currently is that the examples provision successfully as they are currently written
