### ISSUE TITLE
pre_bootstrap_user_data not be executed

### ISSUE THREAD

**Issue by wufengzlw** [terraform-aws-modules/terraform-aws-eks#2234]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:
```
$ tf -version
Terraform v1.1.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.31.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

## Reproduction Code [Required]

```
    ng_4_spot = {
      desired_capacity = var.desired_spot_nodes
      max_capacity     = var.max_spot_nodes
      min_capacity     = var.min_spot_nodes

      launch_template_id      = aws_launch_template.default.id
      launch_template_version = aws_launch_template.default.default_version

      subnets        = [element(var.private_subnets, 2)]
      instance_types = ["r5a.large", "r5.large", "r5b.large", "r5n.large"]
      capacity_type  = "SPOT"
      k8s_labels = {
        Environment = var.environment
        NodeGroup   = "ng_4_spot"
      }
      enable_bootstrap_user_data = true
      pre_bootstrap_user_data = <<-EOT
        #!/bin/bash
        set -ex
        cat <<-EOF > /etc/profile.d/bootstrap.sh
        export KUBELET_EXTRA_ARGS="--kube-reserved=[memory=1000Mi]"
        EOF
        # Source extra environment variables in bootstrap script
        sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh
        sed -i 's/KUBELET_EXTRA_ARGS=$2/KUBELET_EXTRA_ARGS="$2 $KUBELET_EXTRA_ARGS"/' /etc/eks/bootstrap.sh
        EOT
    }
```

## Expected behavior

this is what I added to node_group config
```
+      enable_bootstrap_user_data = true
+      pre_bootstrap_user_data = <<-EOT
+        #!/bin/bash
+        set -ex
+        cat <<-EOF > /etc/profile.d/bootstrap.sh
+        export KUBELET_EXTRA_ARGS="--kube-reserved=[memory=1000Mi]"
+        EOF
+        # Source extra environment variables in bootstrap script
+        sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh
+        sed -i 's/KUBELET_EXTRA_ARGS=$2/KUBELET_EXTRA_ARGS="$2 $KUBELET_EXTRA_ARGS"/' /etc/eks/bootstrap.sh
+        EOT
```

I'd expect this can setup kubelet config before bootstrap to increase reserved memory size

## Actual behavior
1. when I applied this change, TF "No change"
2. I tried to taint node_group  `module.eks.module.node_groups.aws_eks_node_group.workers["ng_4_spot"]` and applied, NG got recreatd but the pre_bootstrap_user_data was not executed, on the new EKS node, `/etc/profile.d/bootstrap.sh` not exist

**Comment by bryantbiggs** [comment]
If you provide your own launch template then you provide the user data within that launch template

**Comment by wufengzlw** [comment]
@bryantbiggs thanks for you quick reply, I'll try that

**Comment by bryantbiggs** [comment]
closing for now
