### ISSUE TITLE
eks_managed_node_group not accepting desired size when called from the eks module

### ISSUE THREAD

**Issue by khumps** [terraform-aws-modules/terraform-aws-eks#2236]
## My code:

```
module "eks" {
source = "LOCAL_PATH_TO_EKS_MODULE_CLONE_V_18.29.0"
...
  eks_managed_node_groups = {
    prod = {
     ...
      min_size                         = 1
      max_size                         = 5
      desired_size                     = 2
  }
}
```

## What I expect:
A node group spun up with `min_size: 1` `max_size:5` and `desired_size: 2`

## What I get: 
A node group with `min_size` and `max_size` correct, but `desired_size: 1`

What I have done:
I configured this based on the complete example: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v18.29.0/examples/complete/main.tf#L142-L144

I looked in the terraform state and sure enough the state reflects the incorrect size:
```
# module.eks.module.eks_managed_node_group["prod"].aws_eks_node_group.this[0]:
resource "aws_eks_node_group" "this" {
...
    scaling_config {
        desired_size = 1
        max_size     = 5
        min_size     = 1
    }
...
}
```

Extra info:
Provider version: `v18.29.0`
Kuberetes version: `1.21`
Terraform version: `1.1`

**Comment by bryantbiggs** [comment]
Most likely you configured a desired size of 1 and then changed to 2 and the module does not support this. The module is designed to be used with some sort of node/data plane auto scaling so the `ignored_size` is ignored after initial launch

**Comment by khumps** [comment]
> Most likely you configured a desired size of 1 and then changed to 2 and the module does not support this. The module is designed to be used with some sort of node/data plane auto scaling so the `ignored_size` is ignored after initial launch

That is exactly what I did! The documentation doesn't suggest that as the behavior. It may be worth updating [the readme](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/eks-managed-node-group/README.md?plain=1#L110) to make that more clear

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md

**Comment by bryantbiggs** [comment]
https://github.com/bryantbiggs/eks-desired-size-hack
