### ISSUE TITLE
Patch for v17.20.0 

### ISSUE THREAD

**Issue by schwichti** [terraform-aws-modules/terraform-aws-eks#2238]
Hi, 
I am using an older version, i.e. 17.20.0 of this module. Currently, updating the module would take to long and I need a short-term patch to restrict the security group rule workers_ingress_self which "Allow node to communicate with each other.": see https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v17.20.0/workers.tf#L399

What is the purpose of the rule?
Why is it so permissive?

**Comment by schwichti** [comment]
Are these the security group rules that are currently used in the latest release https://github.com/terraform-aws-modules/terraform-aws-eks/blob/58285f37d1dfaacbf99055ed87f1be19cc39f5ad/node_groups.tf#L61 ? 
Is it possible to manually recreating such a security group and pass it to the module in version 17.20.0 via the variable `worker_security_group_id` ?

**Comment by bryantbiggs** [comment]
We won't be releasing any additional changes for v17.x which was deprecated almost a year ago now

**Comment by schwichti** [comment]
I want to patch it myself, but I would need guidance. The rule currently allows all protocols on all ports. I do not know how to restrict traffic without breaking anything.
