### ISSUE TITLE
Add ssm agent support

### ISSUE THREAD

**Issue by runningman84** [terraform-aws-modules/terraform-aws-eks#224]
## I'm submitting a...

* [x] feature request

## What is the current behavior?

You cannot access any worker node via ssh.

## What's the expected behavior?

It would be cool to access the worker nodes via the SSM session manager. This would help to debug any issues with the worker nodes.

## Are you able to fix this problem and submit a PR? Link here if you have already.

It is quite easy to implement:

role:
```
resource "aws_iam_role_policy_attachment" "node-AmazonEC2RoleforSSM" {
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
  role       = "${aws_iam_role.node.name}"
}
```

userdata:
```
yum install -y amazon-ssm-agent
systemctl start amazon-ssm-agent
systemctl enable amazon-ssm-agent
```

**Comment by brandoconnor** [comment]
PR discussed and closed. Hopefully you're managing to make this work through the flexibility we provide in the userdata variables.
