### ISSUE TITLE
Error on apply the EKS module

### ISSUE THREAD

**Issue by mauriciovillagran25** [terraform-aws-modules/terraform-aws-eks#2240]
I´ve an error when applying the module.

Error: Cycle: module.internal_ingress_eks_sg.aws_security_group.this_name_prefix, module.internal_ingress_eks_sg.var.create_timeout (expand), module.internal_ingress_eks_sg.var.delete_timeout (expand), module.internal_ingress_eks_sg.var.tags (expand), module.internal_ingress_eks_sg.var.name (expand), module.internal_ingress_eks_sg.var.vpc_id (expand), module.internal_ingress_eks_sg.var.use_name_prefix (expand), module.internal_ingress_eks_sg.var.create_sg (expand), module.internal_ingress_eks_sg.var.putin_khuylo (expand), module.internal_ingress_eks_sg.var.create (expand), module.internal_ingress_eks_sg.local.create (expand), module.internal_ingress_eks_sg.var.description (expand), module.internal_ingress_eks_sg.var.revoke_rules_on_delete (expand), module.internal_ingress_eks_sg.aws_security_group.this, module.eks_cluster.output.cluster_endpoint (expand), module.eks_cluster.output.eks_managed_node_groups_autoscaling_group_names (expand), module.eks_cluster.output.self_managed_node_groups (expand), module.eks_cluster.output.oidc_provider (expand), module.eks_cluster.aws_eks_addon.this, module.eks_cluster.output.cluster_addons (expand), module.eks_cluster.output.cluster_certificate_authority_data (expand), module.eks_cluster.aws_ec2_tag.cluster_primary_security_group, module.eks_cluster.kubernetes_config_map.aws_auth, module.eks_cluster.kubernetes_config_map_v1_data.aws_auth, module.eks_cluster.local.fargate_profile_pod_execution_role_arns (expand), module.eks_cluster.local.node_iam_role_arns_non_windows (expand), module.eks_cluster.local.aws_auth_configmap_data (expand), module.eks_cluster.output.cluster_primary_security_group_id (expand), module.eks_cluster.local.node_iam_role_arns_windows (expand), module.eks_cluster (close), module.eks_cluster.output.cluster_id (expand), module.eks_cluster.output.eks_managed_node_groups (expand), module.eks_cluster.output.cluster_status (expand), module.eks_cluster.output.fargate_profiles (expand), module.eks_cluster.output.cluster_arn (expand), module.eks_cluster.module.fargate_profile.output.fargate_profile_pod_execution_role_arn (expand), module.eks_cluster.module.fargate_profile.output.fargate_profile_id (expand), module.eks_cluster.module.fargate_profile (close), module.eks_cluster.module.fargate_profile.output.fargate_profile_status (expand), module.eks_cluster.module.self_managed_node_group.output.autoscaling_group_id (expand), module.eks_cluster.module.self_managed_node_group.output.autoscaling_group_availability_zones (expand), module.eks_cluster.module.self_managed_node_group.aws_autoscaling_schedule.this, module.eks_cluster.module.self_managed_node_group.output.autoscaling_group_schedule_arns (expand), module.eks_cluster.module.self_managed_node_group.output.autoscaling_group_health_check_grace_period (expand), module.eks_cluster.module.self_managed_node_group.output.autoscaling_group_health_check_type (expand), module.eks_cluster.module.self_managed_node_group.output.autoscaling_group_arn (expand), module.eks_cluster.module.self_managed_node_group.output.launch_template_arn (expand), module.eks_cluster.module.self_managed_node_group.output.user_data (expand), module.eks_cluster.module.self_managed_node_group.module.user_data.var.cluster_name (expand), module.eks_cluster.module.self_managed_node_group.module.user_data.local.int_linux_default_user_data (expand), module.eks_cluster.module.self_managed_node_group.module.user_data.var.cluster_auth_base64 (expand), module.eks_cluster.module.self_managed_node_group.module.user_data (close), module.eks_cluster.module.self_managed_node_group.var.cluster_name (expand), module.eks_cluster.module.self_managed_node_group.local.launch_template_version (expand), module.eks_cluster.module.self_managed_node_group.output.launch_template_id (expand), module.eks_cluster.module.self_managed_node_group.var.cluster_auth_base64 (expand), module.eks_cluster.module.self_managed_node_group.output.launch_template_latest_version (expand), module.eks_cluster.module.self_managed_node_group.output.autoscaling_group_max_size (expand), module.eks_cluster.module.self_managed_node_group.var.cluster_version (expand), module.eks_cluster.module.self_managed_node_group.data.aws_ami.eks_default, module.eks_cluster.module.self_managed_node_group.local.security_group_ids (expand), module.eks_cluster.module.self_managed_node_group.output.image_id (expand), module.eks_cluster.module.self_managed_node_group.output.launch_template_name (expand), module.eks_cluster.module.self_managed_node_group.var.cluster_primary_security_group_id (expand), module.eks_cluster.module.self_managed_node_group (close), module.eks_cluster.module.self_managed_node_group.output.autoscaling_group_name (expand), module.eks_cluster.module.self_managed_node_group.output.autoscaling_group_desired_capacity (expand), module.eks_cluster.module.self_managed_node_group.output.autoscaling_group_default_cooldown (expand), module.eks_cluster.module.self_managed_node_group.output.autoscaling_group_min_size (expand), module.eks_cluster.module.eks_managed_node_group.output.node_group_arn (expand), module.eks_cluster.module.eks_managed_node_group.output.launch_template_id (expand), module.eks_cluster.module.eks_managed_node_group.output.launch_template_name (expand), module.eks_cluster.module.eks_managed_node_group.output.node_group_status (expand), module.eks_cluster.module.eks_managed_node_group.output.node_group_taints (expand), module.eks_cluster.module.eks_managed_node_group.output.node_group_labels (expand), module.eks_cluster.module.eks_managed_node_group.module.user_data (close), module.eks_cluster.module.eks_managed_node_group.output.launch_template_arn (expand), module.eks_cluster.module.eks_managed_node_group.output.launch_template_latest_version (expand), module.eks_cluster.module.eks_managed_node_group (close), module.eks_cluster.module.eks_managed_node_group.output.node_group_autoscaling_group_names (expand), module.eks_cluster.module.eks_managed_node_group.output.node_group_id (expand), module.eks_cluster.module.eks_managed_node_group.var.cluster_version (expand), module.eks_cluster.module.eks_managed_node_group.local.launch_template_version (expand), module.eks_cluster.module.eks_managed_node_group.var.cluster_primary_security_group_id (expand), module.eks_cluster.module.eks_managed_node_group.local.security_group_ids (expand), module.eks_cluster.module.eks_managed_node_group.module.user_data.var.cluster_name (expand), module.eks_cluster.module.eks_managed_node_group.module.user_data.local.int_linux_default_user_data (expand), module.eks_cluster.module.eks_managed_node_group.var.cluster_auth_base64 (expand), module.eks_cluster.module.eks_managed_node_group.module.user_data.var.cluster_auth_base64 (expand), module.eks_cluster.module.eks_managed_node_group.var.cluster_endpoint (expand), module.eks_cluster.module.eks_managed_node_group.module.user_data.var.cluster_endpoint (expand), module.eks_cluster.module.eks_managed_node_group.module.user_data.local.platform (expand), module.eks_cluster.module.eks_managed_node_group.module.user_data.output.user_data (expand), module.eks_cluster.module.eks_managed_node_group.aws_launch_template.this, module.eks_cluster.module.eks_managed_node_group.local.launch_template_name (expand), module.eks_cluster.module.eks_managed_node_group.var.cluster_name (expand), module.eks_cluster.module.eks_managed_node_group.aws_eks_node_group.this, module.eks_cluster.module.eks_managed_node_group.output.node_group_resources (expand), module.eks_cluster.module.fargate_profile.var.cluster_name (expand), module.eks_cluster.module.fargate_profile.aws_eks_fargate_profile.this, module.eks_cluster.module.fargate_profile.output.fargate_profile_arn (expand), module.eks_cluster.output.aws_auth_configmap_yaml (expand), module.eks_cluster.output.cluster_oidc_issuer_url (expand), module.eks_cluster.output.cluster_version (expand), module.eks_cluster.aws_eks_identity_provider_config.this, module.eks_cluster.output.cluster_identity_providers (expand), module.eks_cluster.output.cluster_platform_version (expand), module.eks_cluster.data.tls_certificate.this, module.eks_cluster.aws_iam_openid_connect_provider.oidc_provider, module.eks_cluster.output.oidc_provider_arn (expand), module.internal_ingress_eks_sg (expand), module.internal_ingress_eks_sg.output.security_group_id (expand), module.eks_cluster.var.node_security_group_additional_rules (expand), module.eks_cluster.aws_security_group_rule.node, module.eks_cluster.aws_eks_cluster.this, module.eks_cluster.module.self_managed_node_group.var.cluster_endpoint (expand), module.eks_cluster.module.self_managed_node_group.module.user_data.var.cluster_endpoint (expand), module.eks_cluster.module.self_managed_node_group.module.user_data.local.platform (expand), module.eks_cluster.module.self_managed_node_group.module.user_data.output.user_data (expand), module.eks_cluster.module.self_managed_node_group.aws_launch_template.this, module.eks_cluster.module.self_managed_node_group.local.launch_template_name (expand), module.eks_cluster.module.self_managed_node_group.aws_autoscaling_group.this, module.eks_cluster.module.self_managed_node_group.output.autoscaling_group_vpc_zone_identifier (expand), module.eks_cluster.output.self_managed_node_groups_autoscaling_group_names (expand)

**Comment by bryantbiggs** [comment]
please use the templates provided to provide the necessary information
