### ISSUE TITLE
[Question] Updating EKS optimized AMI version

### ISSUE THREAD

**Issue by repl-mike-roest** [terraform-aws-modules/terraform-aws-eks#2244]
## Description
We're currently using the module to spin up EKS clusters using a single managed node group per cluster.  When I load my clusters up in the console I'm seeing
![image](https://user-images.githubusercontent.com/32706821/192591913-6a8476a4-c4ec-4eab-a89a-c7f0a3ebcf19.png)
I would kind of expect re-running the terraform for my cluster would cause the AMI to be updated. However that doesn't appear to be the case.  In some ways I guess it makes sense as there is no resource to change.

I have just ami_type defined for my node group to 
```
eks_managed_node_groups = {
    "${local.resource_prefix}-system" = {
      ami_type                = "AL2_ARM_64"
      min_size                = var.ha ? length(var.cluster_subnet_ids) : 1
      max_size                = var.cluster_instance_max
      desired_size            = var.ha ? length(var.cluster_subnet_ids) : 1
      pre_bootstrap_user_data = <<-EOT
        #!/bin/bash
        set -exu -o pipefail
        cat <<-EOF > /etc/profile.d/bootstrap.sh
        export CONTAINER_RUNTIME="containerd"
        EOF
        # Source extra environment variables in bootstrap script
        sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh
        EOT
      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 50
            volume_type           = "gp3"
            delete_on_termination = true
          }
        }
      }
    }
```

Is there any suggested method to ensure that the ami stays up to date?  Something like putting a timestamp into the pre_bootstrap_user_data may work?  As that would force a new launch template version and I suppose at that point the EKS system would use the latest AMI.  It would however have the downside of always rotating the instances even if not required.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: "18.28.0"

**Comment by repl-mike-roest** [comment]
I've attempted my thought of putting something into the pre_bootstrap_user_data to force a launch template update this did not work however.  It did cause a full rotation of all the underlying nodes due to the change in the launch template but did not update the AMI

**Comment by bryantbiggs** [comment]
the EKS managed node group API should be noticing the diff with the new version and prompt the update. if its not, it might be a provider bug or something within EKS where the new version prompt is shown in the console but if you query the node group with the CLI it may not show the latest AMI ID. 

if you want to force the upgrade behavior, you can set the version for the latest AMI ID via [`release_version`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#release_version)

**Comment by repl-mike-roest** [comment]
Hey @bryantbiggs thanks I think I'm going to look at putting a small lambda in place that can query the SSM param for the latest ami version and if it doesn't match the currently running node group machines then force the update with update-nogdegroup-version. I was originally going to do it as a CronJob on the cluster but realized that's not really going to work since if I want to monitor for the update to be successful the cronjob pod would block the update (or get killed)
