### ISSUE TITLE
Custom AMI: Pre-bootstrap user_data is inserted into launch templates of node groups when enable_bootstrap_user_data is disabled

### ISSUE THREAD

**Issue by bogdando** [terraform-aws-modules/terraform-aws-eks#2246]
## Description

There is also a misconfiguration in ``templates/linux_user_data.tpl`` which always inserts ``pre_bootstrap_user_data``, even if ``enable_bootstrap_user_data: false``. The latter setting should control insertion of ``pre_bootstrap_user_data`` just like it already does for ``post_bootstrap_user_data``.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: v18.29.1

- Terraform version:

Terraform v1.2.5
on linux_amd64

- Provider version(s):

+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.32.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1
## Reproduction Code [Required]

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.32"
    }
  }
  required_version = ">= 0.13.1"
}

provider "aws" {
  region  = "eu-west-1"
}

data "aws_caller_identity" "current" {}

locals {
  name            = "test-1"
  cluster_version = "1.23"
  region          = "eu-west-1"
  azs             = ["eu-west-1c"]
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.12.0"

  name = local.name
  cidr = "10.20.0.0/16"

  azs             = local.azs
  private_subnets = ["10.20.36.0/22"]

  enable_nat_gateway     = false
}

resource "tls_private_key" "this" {
  algorithm = "RSA"
}

resource "aws_key_pair" "this" {
  key_name_prefix = local.name
  public_key      = tls_private_key.this.public_key_openssh
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.29.1"

  cluster_name                    = local.name
  cluster_version                 = local.cluster_version
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false

  cluster_endpoint_public_access_cidrs = []

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  eks_managed_node_group_defaults = {
    ami_type = "AL2_x86_64"
    platform = "linux"
    disk_size = 10
    instance_types = ["t3a.large"]
    subnet_ids = [module.vpc.private_subnets]
    enable_bootstrap_user_data = false
    pre_bootstrap_user_data = <<-EOT
      export CONTAINER_RUNTIME="containerd"
      export USE_MAX_PODS=false
      EOT
    bootstrap_extra_args = "--container-runtime containerd --kubelet-extra-args '--max-pods=20 --instance-type t3a.large'"
    post_bootstrap_user_data = <<-EOT
      echo "All done"
      EOT
  }

  eks_managed_node_groups = {
    default_node_group = {
    }
  }
}
```

## Expected behavior

When ``enable_bootstrap_user_data : false``, user data in launch template should not contain ``pre_bootstrap_user_data``, nor ``post_bootstrap_user_data``

## Actual behavior

When ``enable_bootstrap_user_data : false``, user data will contain ``pre_bootstrap_user_data``, but it will not contain ``post_bootstrap_user_data``

### Terminal Output Screenshot(s)

```
...
  # module.eks.module.eks_managed_node_group["default_node_group"].aws_eks_node_group.this[0] will be created
  + resource "aws_eks_node_group" "this" {
      + ami_type               = "AL2_x86_64"
      + arn                    = (known after apply)
      + capacity_type          = (known after apply)
      + cluster_name           = "test-1"
      + disk_size              = (known after apply)
      + id                     = (known after apply)
      + instance_types         = [
          + "t3a.large",
        ]
      + node_group_name        = (known after apply)
      + node_group_name_prefix = "default_node_group-"
      + node_role_arn          = (known after apply)
      + release_version        = (known after apply)
      + resources              = (known after apply)
      + status                 = (known after apply)
      + subnet_ids             = (known after apply)
      + tags                   = {
          + "Name" = "default_node_group"
        }
      + tags_all               = {
          + "Name" = "default_node_group"
        }
      + version                = "1.23"

      + launch_template {
          + id      = (known after apply)
          + name    = (known after apply)
          + version = (known after apply)
        }

      + scaling_config {
          + desired_size = 1
          + max_size     = 3
          + min_size     = 1
        }

      + timeouts {}

      + update_config {
          + max_unavailable            = (known after apply)
          + max_unavailable_percentage = (known after apply)
        }
    }
...
  # module.eks.module.eks_managed_node_group["default_node_group"].aws_launch_template.this[0] will be created
  + resource "aws_launch_template" "this" {
      + arn                    = (known after apply)
      + default_version        = (known after apply)
      + description            = "Custom launch template for default_node_group EKS managed node group"
      + id                     = (known after apply)
      + latest_version         = (known after apply)
      + name                   = (known after apply)
      + name_prefix            = "default_node_group-"
      + tags_all               = (known after apply)
      + update_default_version = true
      + user_data              = "Q29udGVudC1UeXBlOiBtdWx0aXBhcnQvbWl4ZWQ7IGJvdW5kYXJ5PSIvLyIKTUlNRS1WZXJzaW9uOiAxLjANCg0KLS0vLw0KQ29udGVudC1UcmFuc2Zlci1FbmNvZGluZzogN2JpdA0KQ29udGVudC1UeXBlOiB0ZXh0L3gtc2hlbGxzY3JpcHQNCk1pbWUtVmVyc2lvbjogMS4wDQoNCmV4cG9ydCBDT05UQUlORVJfUlVOVElNRT0iY29udGFpbmVyZCIKZXhwb3J0IFVTRV9NQVhfUE9EUz1mYWxzZQoNCi0tLy8tLQ0K"
      + vpc_security_group_ids = (known after apply)

      + metadata_options {
          + http_endpoint               = "enabled"
          + http_protocol_ipv6          = "disabled"
          + http_put_response_hop_limit = 2
          + http_tokens                 = "required"
          + instance_metadata_tags      = "disabled"
        }

      + monitoring {
          + enabled = true
        }

      + tag_specifications {
          + resource_type = "instance"
          + tags          = {
              + "Name" = "default_node_group"
            }
        }
      + tag_specifications {
          + resource_type = "network-interface"
          + tags          = {
              + "Name" = "default_node_group"
            }
        }
      + tag_specifications {
          + resource_type = "volume"
          + tags          = {
              + "Name" = "default_node_group"
            }
        }
    }
...
```

## Additional context

See:
```
  # module.eks.module.eks_managed_node_group["default_node_group"].aws_launch_template.this[0] will be created
  + resource "aws_launch_template" "this" {
      + user_data              = "Q29udGVudC1UeXBlOiBtdWx0aXBhcnQvbWl4ZWQ7IGJvdW5kYXJ5PSIvLyIKTUlNRS1WZXJzaW9uOiAxLjANCg0KLS0vLw0KQ29udGVudC1UcmFuc2Zlci1FbmNvZGluZzogN2JpdA0KQ29udGVudC1UeXBlOiB0ZXh0L3gtc2hlbGxzY3JpcHQNCk1pbWUtVmVyc2lvbjogMS4wDQoNCmV4cG9ydCBDT05UQUlORVJfUlVOVElNRT0iY29udGFpbmVyZCIKZXhwb3J0IFVTRV9NQVhfUE9EUz1mYWxzZQoNCi0tLy8tLQ0K"
``` 
So the generated user_data
```
Content-Type: multipart/mixed; boundary="//"
MIME-Version: 1.0

--//
Content-Transfer-Encoding: 7bit
Content-Type: text/x-shellscript
Mime-Version: 1.0

export CONTAINER_RUNTIME="containerd"
export USE_MAX_PODS=false

--//--
```
was unexpected since user data injection had been disabled (``enable_bootstrap_user_data = false``)

**Comment by bryantbiggs** [comment]
again, please take a look at the documentation

- `enable_bootstrap_user_data` is only valid for EKS managed node groups when a custom AMI ID is provided or on self-managed node groups. This controls whether the module will provide the bootstrap user data since EKS managed node groups will NOT when a custom AMI ID is provided and since self-managed node groups by default provide nothing.
-  `bootstrap_extra_args` and `post_bootstrap_user_data` are only valid when using a custom AMI ID for EKS managed node groups or when using a self-managed node group
- MIME multi-part format is ONLY valid on EKS managed node groups when NOT using a custom AMI ID which is what this module provides

I still do not see any issues with the current user data implementation and only see issues with your understanding of the various configurations and how to utilize them

**Comment by bogdando** [comment]
@bryantbiggs I can clearly see a problem here. Do you have alternative communication channels, like community meetings, slack channels, to discuss it?

**Comment by bogdando** [comment]
Could we for a moment ignore self-managed nodes, and MIME format (there is another issue for the latter).
When see that we got from your comment above:

> ``enable_bootstrap_user_data`` is only valid for EKS managed node groups when a custom AMI ID is provided. This controls whether the module will provide the bootstrap user data since EKS managed node groups will NOT when a custom AMI ID is provided

Now the issue description confirms that things work differently, and there is a reproducer for that:
> **Expected behavior**
> When enable_bootstrap_user_data : false, user data in launch template should not contain pre_bootstrap_user_data, nor post_bootstrap_user_data
> **Actual behavior**
> When enable_bootstrap_user_data : false, user data will contain pre_bootstrap_user_data, but it will not contain post_bootstrap_user_data
```
eks_managed_node_group_defaults = {               # IS a managed NG
    ami_type = "AL2_x86_64"                                 # HAS custom AMI
    enable_bootstrap_user_data = false                 # user data IS disabled
    pre_bootstrap_user_data = <<-EOT                  # this still got injected into Launch template (it should NOT)
    ...
    bootstrap_extra_args = "--container-runtime containerd --kubelet-extra-args '--max-pods=20 --instance-type t3a.large'"
    post_bootstrap_user_data = <<-EOT                 # this is NOT injected into Launch template, as expected
    ...
}
```
Can you see the problem now?

**Comment by bryantbiggs** [comment]
First, lets please refrain from creating additional issues and PRs and work in a central thread - this issue.

For your configuration provided above, this is incorrect
> ami_type = "AL2_x86_64"                                 # HAS custom AMI

That is the AMI type which is specific to EKS managed node groups to differentiate between Amazon Linux 2, Bottlerocket, ARM, and x86/64 combinations. If you want to set a custom AMI, you provide an ID via the `ami_id` field which now indicates to the service that its a custom AMI

I am really trying hard to help you here but the repeated challenges are becoming exhausting. Please, post the desired outcome you are trying to achieve and the code you are using to achieve it. As I have stated before, the only issues I have seen so far via your issues/PRs are that of a lack of understanding of the various configurations (which is not unreasonable, its a quite complex module with a LOT of options and configurations exposed via variables).
