### ISSUE TITLE
Support Warm pool in EKS managed nodegroup

### ISSUE THREAD

**Issue by sinycn** [terraform-aws-modules/terraform-aws-eks#2248]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

 YES   warm pool related doc https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#auto-scaling-group-with-warm-pool

## Is your request related to a problem? Please describe.

in my use case  a large docker image about 27G is used for CI purpose when autoscaling  i need to wait 30mins  before docker image ready   so i want to use warm pool to cache docker image in advance and reduce waiting time for ci users
i notice that warm pool is supported in self managed node group but not enable in managed node group

## Describe the solution you'd like.

add an input variable to enable warm pool settting  in EKS managed nodegroup

**Comment by bryantbiggs** [comment]
Closing here since this is not supported by EKS managed node groups today https://github.com/aws/containers-roadmap/issues/1387

**Comment by iptizer** [comment]
Don't forget to upvote the feature request in the linked issue!!
