### ISSUE TITLE
Add an attribute to specify the Availability Zones for EKS Managed Groups nodes  

### ISSUE THREAD

**Issue by ryuzakyl** [terraform-aws-modules/terraform-aws-eks#2252]
**NOTE:** Unsure if what I'm asking is a feature request, but couldn't find a solution by looking at the documentation.

## Is your request related to a problem? Please describe.
Is there a way to specify a single Availability Zone for the nodes in `eks_managed_node_groups`?

I've been able specify `ami_type`, `platform`, `min_size`, `min_size`, and many more, but I'd like to have my nodes created in a single Availability Zone. If this is already possible, I'd appreciate some pointers to some resources.

## Describe the solution you'd like.

I would imagine something similar to this:

```console
...
  eks_managed_node_groups = {
    bottlerocket = {
      ami_type     = "BOTTLEROCKET_x86_64"
      platform     = "bottlerocket"
      min_size     = 5
      max_size     = 10
      desired_size = 5
      availability_zones = ["us-west-2a"]    <----------------------
    }
  }
... 
```

## Describe alternatives you've considered.
`eksctl` apparently has this feature. It would be something along the lines of:

```console
$ eksctl create cluster --name=cluster --zones=us-west-2a,us-west-2b --node-zones=us-west-2a
```
but this is not an option for me, since I want it to be in Terraform as part of my IaC codebase.

## Additional context
N/A.

**Comment by bryantbiggs** [comment]
you can achieve this by specifying the appropriate subnet ID for the AZ you want to use https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L239
