### ISSUE TITLE
I want to create a EKS cluster with AMI prepared by AWS and install additional packages on the node group instances

### ISSUE THREAD

**Issue by janiszewskimichal** [terraform-aws-modules/terraform-aws-eks#2254]
Hi,

I want to create an EKS cluster, which:

1. node group is using the AWS EKS AMI  
2. SSH access to the node group EC2 instances is unblocked. Currently, a separate security group is created with appropriate SSH access but it's not attached to the instances 
3. `pre_bootstrap_user_data` parameter is executed to install additional packages to the node group EC2 instances. 

Unfortunately, I cannot achieve this, not sure if it is feasible at all. Maybe someone can point out what I am doing wrong?

There is no issue during terraform run.

## Versions
```
Terraform v1.2.2
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.33.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.7.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.13.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/tls v4.0.3
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```
## Reproduction Code [Required]

```
provider "aws" {
  region = "us-west-2"
}

locals {
  name            = "my_cluster"
  cluster_version = "1.23"
  region          = "us-west-2"

  vpc_id     = "<my_vpc>"
  subnet_ids = ["<subnet-1>", "<subnet-2>", "<subnet-3>"]

  tags = {
    Environment    = "dev"
  }
}

resource "aws_security_group" "remote_access" {
  name_prefix = "${local.name}-remote-access"
  description = "Allow remote SSH access"
  vpc_id      = local.vpc_id

  ingress {
    description = "SSH access"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8","172.0.0.0/8"]
  }

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

  tags = local.tags
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"

  cluster_name    = local.name
  cluster_version = local.cluster_version

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni    = {
      resolve_conflicts = "OVERWRITE"
    }
  }

  vpc_id     = local.vpc_id
  subnet_ids = local.subnet_ids
  cluster_enabled_log_types = ["audit", "api", "authenticator", "controllerManager", "scheduler"]

  # EKS Managed Node Group(s)
  eks_managed_node_group_defaults = {
    disk_size      = 100
    instance_types = ["t3.medium"]
  }

  eks_managed_node_groups = {

    worker1 = {
      instance_types = ["t3.medium"]
      capacity_type  = "ON_DEMAND"
      min_size       = 2
      max_size       = 4
      desired_size   = 2
      name           = "worker1"

      # Installation of additional packages
      pre_bootstrap_user_data = <<-EOT
      yum -y install osquery
      EOT
      
      create_launch_template = false
      launch_template_name   = ""

      vpc_security_group_ids = [aws_security_group.remote_access.id]

      remote_access = {
        ec2_ssh_key               = "Instant-Environments-test2"
        source_security_group_ids = [aws_security_group.remote_access.id]
      }
    }
  }

  tags = local.tags
}
```

Update the following variables with parameters that suit your VPC
```
vpc_id     = "<my_vpc>"
subnet_ids = ["<subnet-1>", "<subnet-2>", "<subnet-3>"]
```
execute :
```
terraform init
terraform apply
```
## Expected behavior

- the EKS cluster is created (AWS default EKS AMI is used),  
nodes groups instances have:
- additional packages installed - in my case it's osquery
- Security Group that allows SSH access is attached

## Actual behavior

- the EKS cluster is created (AWS default EKS AMI is used),  
nodes groups instances have:
- DON'T HAVE additional packages installed - in my case it's osquery
- Security Group that allows SSH access IS NOT attached

**Comment by bryantbiggs** [comment]
If you want to provide user data then you need to use a custom launch template (which is the default for this module for this reason plus a number of other reasons). 

I would suggest using the custom launch template which will allow you to provide user data and open up SSH access on the security group created by this module (another reason to use custom launch template). Within the launch template spec you can provide `key_name` which is the name of an existing PEM key for SSH access. 

Lastly, I would recommend not using SSH which avoids a lot of what you are trying to do here (key pair, SSH security group rules) and instead use session manager by simply attaching the SSM access policy to the node group https://github.com/terraform-aws-modules/terraform-aws-eks/blob/7f901840c430c0b631cc4066a87779b915a07524/examples/complete/main.tf#L104
