### ISSUE TITLE
Incorporate "Tags for the ASG to support cluster-autoscaler scale up from 0" example into managed node groups

### ISSUE THREAD

**Issue by flowinh2o** [terraform-aws-modules/terraform-aws-eks#2255]
## Support for managed node groups to scale from 0 via tagging the associate node groups

It would be nice to incorporate the tagging of autoscaling groups that is already in the included example https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L674.  I don't think the changes are going to happen on the AWS side since the ticket has been open for almost 2 years now.  https://github.com/aws/containers-roadmap/issues/724

Looks like the work is pretty much done here so why not just add another variable to enable tagging propagation?

Thank you.

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1558#issuecomment-1030640207

**Comment by bryantbiggs** [comment]
closing since there isn't a viable solution to incorporate this into the module - see linked comment above where this was attempted
