### ISSUE TITLE
EKS Managed Node Group - Multiple network interfaces in different subnets

### ISSUE THREAD

**Issue by jbreed** [terraform-aws-modules/terraform-aws-eks#2256]
## Description

Is this a capability within the module? Reading the EKS Managed Node Group module it appears subnet_id is commented out stating to do this at the node group level. By doing this I don't get multiple ENI's in different subnets. If I hard-set network_interfaces it creates them, but they all end up on the same subnet as I am unable to specify where to attach this. 

Background: Looking at using Multus CNI in which eth0 will be used for control traffic and then two additional interfaces that multus can use for other networks.

I currently have three different node groups. Only one node group do I need particular interfaces added. With auto-scaling potentially with hundreds of nodes, this isn't something I would want to re-configure manually (assuming that is even an option).

## Versions

- Module version [Required]:

- Terraform version:
v1.2.9
- Provider version(s):
hashicorp/aws v4.33.0
hashicorp/cloudinit v2.2.0
hashicorp/helm v2.7.0
hashicorp/kubernetes v2.13.1
hashicorp/tls v4.0.3

**Comment by bryantbiggs** [comment]
I'm not sure which interfaces you are referring to - do you have a pseudo example config of what you are trying to achieve?

**Comment by jbreed** [comment]
@bryantbiggs 

I’ll try and get something somewhat moved over to put here later today.

I was reading last night that auto scaling groups don’t support adding new interfaces in different subnets so others have used lambda with hooks to add interfaces when they are pending. This isn’t ideal, but may be the only option.

The doc references multiple subnets per separate interfaces not supported for launch templates, which seems odd to me.

**Comment by jbreed** [comment]
@bryantbiggs Here is a close version to what I was testing with. You can see the commented out interfaces, which when using that they create; however, all reside on the same subnet so I looked at other options.

Multus reference: https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-multus-cni/

Auto scaling reference: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-auto-scaling-multiple-network-interfaces/

It appears I may need to create a lambda function to do this; however, would be awesome to handle this here in this terraform template. If lambda is needed, then maybe I can get Terraform to deploy the components needed for doing this.

I tried adding control plane subnet ID's here and listing all subnets under the particular node group; however, didn't seem to do what I was working towards. There is essentially 3 node groups and only 1 of those node groups I was wanting to connect multiple interfaces on for Multus. 

`
terraform {

  required_version = ">=0.12.0"

}

provider "aws" {

  region = var.region

}

data "aws_eks_cluster" "cluster" {

  name = module.eks.cluster_id

}

data "aws_eks_cluster_auth" "cluster_auth" {

  name = module.eks.cluster_id

}

provider "kubernetes" {

  host                   = module.eks.cluster_endpoint

  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

  token                  = data.aws_eks_cluster_auth.cluster_auth.token

}

module "eks" {
  source                                = "terraform-aws-modules/eks/aws"
  version                               = "18.30.0"
  cluster_endpoint_private_access       = true
  cluster_endpoint_public_access        = false
  cluster_name                          = var.cluster_name
  subnet_ids                            = var.cluster_subnets
  control_plane_subnet_ids              = [var.cluster_subnets[0],var.cluster_subnets[1]]
  vpc_id                                = var.cluster_vpcid
  create_cluster_security_group         = false
  cluster_security_group_id             = var.cluster_sg_id
  create_node_security_group            = false
  cluster_additional_security_group_ids = var.additional_sg_id
  create_iam_role                       = false
  iam_role_arn                          = var.cluster_role
  enable_irsa                           = false
  cluster_enabled_log_types             = ["api", "audit", "authenticator", "controllerManager", "scheduler"]

  cluster_addons = {
    coredns = {}
    kube-proxy = {}
    vpc-cni = {}
  }

  eks_managed_node_group_defaults = {
    capacity_type                   = var.node_type
    cluster_version                 = ""
    cluster_primary_security_group_id = module.eks.cluster_primary_security_group_id
    cluster_security_group_id       = module.eks.node_security_group_id
    enable_bootstrap_user_data      = true

    pre_bootstrap_user_data = <<-EOT
    echo "Updating packages..."
    yum update -y
    EOT

    create_iam_role                 = false
    iam_role_arn                    = var.node_role
    create_security_group           = false
    vpc_security_group_ids          = distinct(concat([module.eks.cluster_primary_security_group_id, module.eks.node_security_group_id], var.vpc_sg))
    ami_id                          = var.node_ami
    instance_types                  = ["t3.2xlarge"]
    create_launch_template          = true
    min_size                        = 0
    max_size                        = 100
    desired_size                    = 1
    tags                            = {"Terraform": "true"}
  }

  eks_managed_node_groups = {
    one = {
      name                        = "control"
      labels                      = {"role": "control"}
      subnet_ids                  = [var.cluster_subnets[1]]
    }

    two = {
      name                        = "user"
      labels                      = {"role": "user"}
      subnet_ids                  = [var.cluster_subnets[0], var.multus_subnet_1, var.multus_subnet_2]
      # network_interfaces = [
      #     {
      #       device_index = 0
      #       description = "Default interface"
      #       associate_public_ip_address = false
      #       subnet_id = var.cluster_subnets[0]
      #     },
      #     {
      #       device_index = 1
      #       description = "Default interface 2"
      #       associate_public_ip_address = false
      #       subnet_id = var.cluster_subnets[0]
      #     },
      #     {
      #       device_index = 2
      #       description = "Multus-Net1 network interface"
      #       associate_public_ip_address = false
      #       subnet_id = var.multus_subnet_1
      #     },
      #     {
      #       device_index = 3
      #       description = "Multus-Net2 network interface"
      #       associate_public_ip_address = false
      #       subnet_id = var.multus_subnet_2
      #     }
      # ]
    }

    three = {
      name                        = "proxy"
      labels                      = {"role": "proxy"}
      subnet_ids                  = [var.cluster_subnets[0]]
    }
  }

  manage_aws_auth_configmap = true
  aws_auth_roles = var.auth_roles

  tags = {
    Terraform = "true"
  }
}
`

**Comment by jbreed** [comment]
Ideally, it would be cleaner if Flannel worked cleanly with EKS and the ability for Multus to add secondary interfaces that leverage VXLan over the infrastructure; however, it appears you have to do some hacky stuff just to get Flannel even functional at all for EKS.

I looked into using Weave w/ multus, but ran into issues in which the overlay interface created is named the same and fails. 

With this needing to be portable between environments, maybe Multus can be used with bridge interfaces and pinning pods to run on the same physical node. The issue then comes to properly autoscaling.

**Comment by bryantbiggs** [comment]
Ah ok, so it is instance ENIs. Yes, with EKS managed node groups, the EKS managed node group controls the subnet IDs (see [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/ad6b2e2ab77d35d86028d69fea886f7148db7bb8/modules/eks-managed-node-group/main.tf#L278)) and therefore the launch template cannot specify subnet IDs or you will get an error message like this

```
Error: error creating EKS Node Group (ex-eks-managed-node-group:custom_ami-2022100417330923390000001a): InvalidParameterException: You must not specify a subnet in your launch template. All subnets must be specified in the API.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "4d6ade05-cbb1-4634-88cc-7a0d2c929e32"
│   },
│   Message_: "You must not specify a subnet in your launch template. All subnets must be specified in the API."
│ }
```

If you want to still set things up this way, you can instead utilize the self-managed nodes which do support the ENI configurations as you have demonstrated https://github.com/terraform-aws-modules/terraform-aws-eks/blob/7f901840c430c0b631cc4066a87779b915a07524/examples/self_managed_node_group/main.tf#L191-L199
