### ISSUE TITLE
unable to find the argument input variables

### ISSUE THREAD

**Issue by daggubav** [terraform-aws-modules/terraform-aws-eks#2257]
## Description
unable to use the [worker_sg_ingress_from_port, cluster_create_endpoint_private_access_sg_rule and cluster_endpoint_private_access_cidrs]  variable with upgrading the module to 18.0.0. please let us know if there is any equivalent / alternative variable to use.

## Versions

- Module version [Required]: 18.0.0

- Terraform version:
0.14.11
- Provider version(s):
0.13.1
## Reproduction Code [Required]

use input variable [worker_sg_ingress_from_port, cluster_create_endpoint_private_access_sg_rule and cluster_endpoint_private_access_cidrs]  that will generate an error not supporting with 18.0.0

## Expected behavior

expected to should support [worker_sg_ingress_from_port, cluster_create_endpoint_private_access_sg_rule and cluster_endpoint_private_access_cidrs]

## Actual behavior

should support [worker_sg_ingress_from_port, cluster_create_endpoint_private_access_sg_rule and cluster_endpoint_private_access_cidrs]

### Terminal Output Screenshot(s)

Error: Unsupported argument
  on main.tf line 28, in module "eks":
  28:   worker_sg_ingress_from_port           = "443"
An argument named "worker_sg_ingress_from_port" is not expected here.
Error: Unsupported argument
  on main.tf line 25, in module "eks":
  25:   cluster_create_endpoint_private_access_sg_rule = "true"
An argument named "cluster_create_endpoint_private_access_sg_rule" is not
expected here.
Error: Unsupported argument
  on main.tf line 26, in module "eks":
  26:   cluster_endpoint_private_access_cidrs = ["10.0.0.0/8"]
An argument named "cluster_endpoint_private_access_cidrs" is not expected
here.

**Comment by bryantbiggs** [comment]
please see the upgrade guide https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-18.0.md
