### ISSUE TITLE
Allow spot price percentage when using spot instance capacity on EKS worker groups launch templates

### ISSUE THREAD

**Issue by mdiianni** [terraform-aws-modules/terraform-aws-eks#2259]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
I moved EKS worker groups to SPOT instance capacity with multiple instances families but only to realise I wasn't saving any money 💸 or benefiting from lower prices as the default price is equal to On-Demand 🤦🏼‍♂️ . Now I am struggling to find a way to benefit from SPOT instances pricing using Terraform. 

## Describe the solution you'd like.
When using `worker_groups_launch_template` with `capacity_type = "spot"` and multiple instance families (`override_instance_types`), I would like to provide a `spot_price_saving_percentage` so I can tell Terraform to automatically place a SPOT request automatically no matter what instance family I have on the list `override_instance_types`. The goal will be then to instruct Terraform to place an (spot) Instance request either equal to current On-Demand price (current default) or a percentage below using `spot_price_saving_percentage`.

## Describe alternatives you've considered.
Based on the above, 
* if you set `spot_price_saving_percentage = 0` (Default) that means you will be using spot instances at on-demand price
* if you set `spot_price_saving_percentage = 100` that means you will be using spot instances at current spot rate, which also means your request chances to be fulfilled are reduced and based on AZ spot availability.
* if you set `spot_price_saving_percentage = 10`, that means you will be using spot instances at 10% below the on-demand price but still above the spot price.
* this will also work when using multiple instances as the percentage will apply to any.
* the only challenge here is relying on Terraform to fetch the current spot prices for the given instance family eg. `c5.xlarge` currently at $0.194/h on-demand, $0.0843/h spot, and apply the percentage configured, eg. `spot_price_saving_percentage = 20` --> then request will be submitted for a `c5.xlarge` instance will be equal to: `(on-demand-price - spot-price) * 20/100 + spot-price` -->  `(0.194 - 0.0843) * 0.2 + 0.0843` --> `c5.xlarge = "0.10624/h"` --> which is 54% cheaper than on-demand, but higher to current spot price ($0.0843/h = 43% compared to on-demand)
* the same will apply if you provide a list of instance families, e.g `override_instance_types = ["c5.xlarge", "m5.4xlarge", "t3.medium"]`, depending on the instance that is picked up by the request the price will be calculated based on the percentage and the request placed as normal.
* potentially instead of calling it `spot_price_saving_percentage` it could be called `spot_price_margin_percentage` as it is effectively providing a price between current spot and on-demand price. 
* and that will fix what you can see on the screenshot below:

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/2330249/194506922-88871bb2-5aec-4b72-bf46-dc52701da051.png">

## Additional context
* Not sure if this solution could be backed integrating with an AWS spot instance data feed: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-data-feeds.html and https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_datafeed_subscription

**Comment by bryantbiggs** [comment]
do you have an example configuration of what you are trying to achieve?

**Comment by mdiianni** [comment]
Assuming some EKS cluster configuration like:

```
module "default-eks-cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = var.cluster_name
  cluster_version = var.kubernetes_version
  subnets         = local.subnet_ids
  vpc_id          = var.vpc_id

  worker_groups_launch_template = var.custom_worker_groups
  
  map_roles    = var.map_roles
  map_users    = var.map_users
  map_accounts = var.map_accounts
}
```
And a worker group launch template variable like:
```
custom_worker_groups = [
  {
    name                 = "infra"
    instance_type        = ["c5.xlarge", "m5.4xlarge", "t3.medium"]
    asg_max_size         = 5
    asg_desired_capacity = 2
    asg_min_size         = 2
    kubelet_extra_args   = "--node-labels=nodepool=tceu-infra,node.kubernetes.io/lifecycle=`curl -s http://169.254.169.254/latest/meta-data/instance-life-cycle`"
  }
```
Having the new feature I will expect to add an additional param to the variable like:
```
custom_worker_groups = [
  {
    name                 = "infra"
    instance_type        = ["c5.xlarge", "m5.4xlarge", "t3.medium"]
    asg_max_size         = 5
    asg_desired_capacity = 2
    asg_min_size         = 2
    kubelet_extra_args   = "--node-labels=nodepool=tceu-infra,node.kubernetes.io/lifecycle=`curl -s http://169.254.169.254/latest/meta-data/instance-life-cycle`"
    spot_price_saving_percentage = 20
  }
```
That will instruct Terraform to attempt placing a spot instance request using either of the instances on the list, as it happens now, but instead of providing the on-demand price it will be either the spot_price including the margin selected. Hope that makes sense.

**Comment by bryantbiggs** [comment]
This looks like v17.x syntax - do you have an example using the latest configuration

**Comment by mdiianni** [comment]
I found this https://aws.amazon.com/blogs/aws/new-attribute-based-instance-type-selection-for-ec2-auto-scaling-and-ec2-fleet/ which could be a way to solve the problem for EKS worker nodes of that effectively places a spot request at lowest market price or either at a percentage above spot price

**Comment by bryantbiggs** [comment]
This sounds like custom logic that would need to be implemented at the provider level. We only have access to what is provided through the current resource schemas https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#mixed_instances_policy

**Comment by mdiianni** [comment]
thanks @bryantbiggs, actually also came the mixed instances policy which also points to autoscaling_group resources and found the following;
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#on_demand_max_price_percentage_over_lowest_price

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#spot_max_price_percentage_over_lowest_price

Is there a way to access to those properties from the EKS module itself?

**Comment by bryantbiggs** [comment]
please see the module documentation and examples

**Comment by mdiianni** [comment]
Thanks @bryantbiggs
