### ISSUE TITLE
I've opened a PR to add a clear notification to the README regarding this issue https://github.com/bryantbiggs/terraform-aws-eks/tree/fix/remote-access-sgs#%E2%84%B9%EF%B8%8F-error-invalid-for_each-argument-

### ISSUE THREAD

**Issue by josepedropinto2022** [terraform-aws-modules/terraform-aws-eks#2265]
I've opened a PR to add a clear notification to the README regarding this issue 
https://github.com/bryantbiggs/terraform-aws-eks/tree/fix/remote-access-sgs#%E2%84%B9%EF%B8%8F-error-invalid-for_each-argument-

_Originally posted by @bryantbiggs in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1753#issuecomment-1010253743_

**Comment by josepedropinto2022** [comment]
hi the issue page does exit (404) https://github.com/bryantbiggs/terraform-aws-eks/tree/fix/remote-access-sgs#%E2%84%B9%EF%B8%8F-error-invalid-for_each-argument- thanks

**Comment by bryantbiggs** [comment]
please see documentation - specifically the FAQ
