### ISSUE TITLE
Update version for EKS addons

### ISSUE THREAD

**Issue by dusanu87** [terraform-aws-modules/terraform-aws-eks#2266]
## Description

We are not able to change version for any of EKS addons. Terraform is not recognizing any changes in version parameter value. We can only see change in Terraform if we are trying to add or remove some addon. 
Is there a way to upgrade EKS addon version via Terraform?
Cluster version: 1.22

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 18.29.0

- Terraform version: v1.2.6
- Provider version(s):
aws v4.24.0
kubernetes v2.11.0

## Reproduction Code [Required]

cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
      version           = "v1.8.7-eksbuild.1"
    }
    
  }

## Steps to reproduce the behavior:
Change or remove version parameter value. Run terraform plan.

## Expected behavior

Version parameter value should be set to changed value or to null(in case of removing it completely).

## Actual behavior

Changing or removing version parameter value is not resulting in any changes in Terraform plan. There is a change in Terraform plan only if we are adding or removing some addon, changing version parameter does not result any change.

## Additional context

We encountered this behaviour during EKS upgrade process. We upgrade cluster version to 1.23 and changed versions for addons (coredns, kube-proxy and vpc-cni). Cluster was successfully upgraded to version 1.23 but addons were not upgraded.

**Comment by bryantbiggs** [comment]
the argument is `addon_version` not `version` https://github.com/terraform-aws-modules/terraform-aws-eks/blob/7f901840c430c0b631cc4066a87779b915a07524/main.tf#L348
