### ISSUE TITLE
var.schedule - Different aws_autoscaling_schedule parameter name leads to error

### ISSUE THREAD

**Issue by brunobritodev** [terraform-aws-modules/terraform-aws-eks#2268]
## Description

When using the module there is a parameter `schedules`. Which is a `aws_autoscaling_schedule` under the hood. But there is a parameter that has a different name from `resource aws_autoscaling_schedule`. So it can leads us to make mistakes.

[Code](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/self-managed-node-group/main.tf#L437)
```
resource "aws_autoscaling_schedule" "this" {
  // ... 
  desired_capacity = lookup(each.value, "desired_size", null) <-- desired_capacity -> desired_size
  //...
}
```

I got struggled by hours looking official docs because apparently I didn't set the `desired_capacity`. So I checked many times before I got this mistype

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

My suggestion is add support for `desired_capacity` and also keep `desired_size` for backward compatibility.

## Versions

- Module version [Required]: 18.30.1

**Comment by bryantbiggs** [comment]
this is intentional in this module to ensure the same convention is used across resources. 

EKS Managed Node Groups
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/8dc5ad447884883ded23e3fed149ea87337dfafd/node_groups.tf#L248-L250

Self Managed Node Groups
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/8dc5ad447884883ded23e3fed149ea87337dfafd/node_groups.tf#L357-L359

Event the autoscaling schedule 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/8dc5ad447884883ded23e3fed149ea87337dfafd/modules/self-managed-node-group/main.tf#L435-L437

**Comment by brunobritodev** [comment]
I see. But both `aws_autoscaling_group` and `aws_autoscaling_schedule` has `desired_capacity` instead **desired_size**. When you check the AWS console, the name is Desired Capacity
![image](https://user-images.githubusercontent.com/7241156/195599493-7fc8ddd9-6e2a-4b69-b377-bf4931e06580.png)

Don't you think this kind of rename could lead people to misleading? Why not just leave the var's name untouched?

I'm insist on this because when we check the module and see `aws_autoscaling_schedule` is not obvious that could have rename on some vars. To understand the details of resource we go to [official docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group) and this module docs don't mention or warn us about these changes. 

Afterall desired_size and desired_capacity is not too different, so untrained eyes just don't notice.

**Comment by bryantbiggs** [comment]
> To understand the details of resource we go to [official docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group) and this module docs don't mention or warn us about these changes

Users are encouraged to go to the docs for the *module since there is no guarantee of 1:1 with the underlying resources depending on what solution is being provided

**Comment by bryantbiggs** [comment]
closing with explanation provided above
