### ISSUE TITLE
local.workers_group_defaults_defaults: local.workers_group_defaults_defaults: At column 3, line 1: join: argument 1 should be type list, got type string in: ${join(",", var.subnets)}

### ISSUE THREAD

**Issue by florenm** [terraform-aws-modules/terraform-aws-eks#227]
# I have issues
* local.workers_group_defaults_defaults: local.workers_group_defaults_defaults: At column 3, line 1: join: argument 1 should be type list, got type string in: ${join(",", var.subnets)}
## I'm submitting a...
* [x ] support request

## What is the current behavior?
I am running terraform plan, I placed everything with doubkle quotes, still getting this error, tried with one subnet, 2 ... same

## If this is a bug, how to reproduce? Please include a code sample if relevant.

er>terraform plan
var.cluster_name
  Name of the EKS cluster. Also used as a prefix in names of related resources.
  Enter a value: ekscluster
var.subnets
  A list of subnets to place the EKS cluster and workers within.
  Enter a value: "subnet-0356f45a283def95a", "subnet-004c1a9974beaf542"
var.vpc_id
  VPC where the cluster and workers will be deployed.
  Enter a value: "vpc-0756ae61be27b74cb"
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.
  Default: us-east-1
  Enter a value: "us-east-1"
Error: Error asking for user input: 1 error(s) occurred:

* local.workers_group_defaults_defaults: local.workers_group_defaults_defaults:
At column 3, line 1: join: argument 1 should be type list, got type string in:

${join(",", var.subnets)}

## Are you able to fix this problem and submit a PR? Link here if you have already.
no
## Environment details
Windows, terraform 
* Affected module version:latest?
* OS:Windows
* Terraform version:
Terraform v0.11.11
+ provider.aws v1.54.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0

**Comment by hobbsh** [comment]
What does your terraform code look like? You should be specifying the subnets var as a list, not a string, i.e.:

```
module "eks" {
  source                = "terraform-aws-modules/eks/aws"
  subnets               = ["subnet-1", "subnet-2"]
```

See the example here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_test_fixture/main.tf#L132

**Comment by max-rocket-internet** [comment]
Closing this old issue. Feel free to open a new one when running against latest release 🙂
