### ISSUE TITLE
Provider default_tags are missing for `eks_managed_node_group/aws_launch_template`

### ISSUE THREAD

**Issue by nantiferov** [terraform-aws-modules/terraform-aws-eks#2275]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 18.30.0

- Terraform version: v1.2.9
- Provider version(s): v4.32.0

## Reproduction Code [Required]

```hcl
provider "aws" {
  default_tags { tags = { foo="bar" } }
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.30.0"
....
  eks_managed_node_groups = {
  ...
  }
}

```

Try to use default_tags with aws_eks_node_groups like in example and worker nodes will miss default_tags from provider.

## Expected behavior

Tags from provider default_tags will be assigned to all created resources.

## Actual behavior

`eks_managed_node_group/aws_launch_template` is missing them and currently we have to hot fix it by defining the same tag with

```hcl
  eks_managed_node_group_defaults = {
   launch_template_tags = { foo="bar" }
}
```

### Terminal Output Screenshot(s)

None

## Additional context

Similar to https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2214

**Comment by bryantbiggs** [comment]
we will not be providing any additional support for workarounds regarding provider tags in this module. Provider tags are meant to work at the provider level and the module should not be concerned with their usage. We offer a variable that is similar in nature, `var.tags`, but we are not able to support ensuring that the provider tags functionality works as it was intended. Please file an issue with the upstream provider (or better yet, raise your concern on one of the many open issues regarding the provider tags https://github.com/hashicorp/terraform-provider-aws/issues?q=is%3Aissue+is%3Aopen+default+tags+sort%3Areactions-%2B1-desc).

Attempting to provide minimal support for workarounds has already proven problematic https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2264 and will be reverted in v19

**Comment by nantiferov** [comment]
It is fixed in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2276 and I don't see any issues with this.

Defining this in tags is causing never-ending diff due to aws provider issue.

**Comment by bryantbiggs** [comment]
> Defining this in tags is causing never-ending diff due to aws provider issue.

Correct, its the provider's issue to correct. We tried to fix this in one other location and now users are raising errors due to conflicts https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2264

We simply cannot bake this in, its not how provider tags were meant to be used nor are we able to fix the implementation here in a module

**Comment by nantiferov** [comment]
Ok, thank you, I will close PR then.

P.S. I believe we will have to live with this for years since HashiCorp don't care much of issues like this.

**Comment by nantiferov** [comment]
> Also, have you tried merging the provider tags with var.tags?

I tried and this creates mess with never-ending diff on aws_eks_node_group due to the same tag set both from provider default_tags and these tags. They should be added only to aws_launch_template, like in PR I created.
