### ISSUE TITLE
Terraform exited with code 1.

### ISSUE THREAD

**Issue by premsgr6** [terraform-aws-modules/terraform-aws-eks#2277]
module.eks.aws_cloudwatch_log_group.this[0]: Creating...
╷
│ Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists:  The CloudWatch Log Group '/aws/eks/eks-dev/cluster' already exists.
│ 
│   with module.eks.aws_cloudwatch_log_group.this[0],
│   on .terraform/modules/eks/main.tf line 80, in resource "aws_cloudwatch_log_group" "this":
│   80: resource "aws_cloudwatch_log_group" "this" {
│ 
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.

tried to delete the log group still same issue

**Comment by bryantbiggs** [comment]
closing due to lack of information - please use templates provided
