### ISSUE TITLE
Question: EKS Managed Node groups upgrade

### ISSUE THREAD

**Issue by rohanagrawal-amex** [terraform-aws-modules/terraform-aws-eks#2278]
## Description

I mean to ask this as a question: For upgrading the Kubernetes versions for eks, if we use the eks_managed_node_groups option, will it automatically upgrade the nodes after the cluster version is upgraded or we will need to explicitly upgrade the nodes. 

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 17.24.0

**Comment by bryantbiggs** [comment]
using this module without specifying a custom AMI, it will pull the correct AMI for the new cluster version and perform the upgrade. However, spin up a test cluster using your configuration and double-check for your configuration. All responses are highly dependent on the configuration
