### ISSUE TITLE
Terraform plan failing during execution

### ISSUE THREAD

**Issue by freshcot** [terraform-aws-modules/terraform-aws-eks#2279]
My terraform plan is failing with this error:

```
Error: Your query returned no results. Please change your search criteria and try again.

  on .terraform/modules/eks/data.tf line 27, in data "aws_ami" "eks_worker_windows":
  27: data "aws_ami" "eks_worker_windows" {
```

I found a similar [issue](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1327) that was closed

### Versions

1. terraform: 0.14.11
2. aws provider: 3.36.0
3. eks module: 13.2.1

My region is us-east-1. Also I asked aws support and they said that they don't see any internal issues with AMI fetching

**Comment by freshcot** [comment]
This issue was in the EKS cluster version, I was using 1.19 so there is no windows images for it, need to use 1.10 and higher

**Comment by identw** [comment]
need to use 1.20 and higher
