### ISSUE TITLE
Namespace is not created for fargate profile, hence fargate profile is not created

### ISSUE THREAD

**Issue by ZillaG** [terraform-aws-modules/terraform-aws-eks#2284]
## Description

I used this module to create my EKS cluster, and it was created. However, I specified a fargate profile in a yet non-existent namespace (since there is no cluster), and the namespace was not automatically created, and hence the fargate profile and their corresponding fargate nodes were not created.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
18.0
- Terraform version:
1.2.8
- Provider version(s):

```
$ terraform providers -version
Terraform v1.2.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.34.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.14.0
+ provider registry.terraform.io/hashicorp/tls v4.0.3
```

## Reproduction Code [Required]

```
module "k8s_cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"

  cluster_name    = "eks-sandbox"
  cluster_version = "1.23"
  ....
  fargate_profiles = {
    default = {
      name = "default"
      selectors = [
        {
          namespace = "default"
        }
      ]
    },
    kube_system = {
      name = "fp-k8s"
      selectors = [
        {
          namespace = "kube-system"
        }
      ]
    },
    my_system = {
      name = "fp-my-system"
      selectors = [
        {
          namespace = "my-system"
        }
      ]
    }
  }
}
```

Not using workspaces

Yes, have cleared local cache

- Create a terraform script using the `terraform-aws-modules/eks/aws` module, with definitions for `fargate_profiles`
- Run `terraform plan -out out.o`
- Run `terraform apply out.o`

## Expected behavior

I expected the `my-system` namespace to automatically get created with fargate nodes in it
```
$ kubectl get ns
NAME              STATUS   AGE
default           Active   15d
kube-node-lease   Active   15d
kube-public       Active   15d
kube-system       Active   15d
my-system         Active   15d <----- I expected this
```

## Actual behavior

The `my-system` namespace was never created, and hence the fargate nodes in it were never created.
```
$ kubectl get ns
NAME              STATUS   AGE
default           Active   15d
kube-node-lease   Active   15d
kube-public       Active   15d
kube-system       Active   15d
```

## Additional context

Note I previously used a YAML file to create an EKS cluster and did
```
$ eksctl create cluster -f my-cluster.yaml
```
and the YAML file had similar fargate profile specifications, and the `my-system` namespace and their corresponding fargate nodes were created, so I expected the same behavior using this module.

**Comment by bryantbiggs** [comment]
Fargate profiles do not create namespaces, they provide compute for pods deployed into the namespaces specified in their selectors

> Namespace – You must specify a namespace for a selector. The selector only matches pods that are created in this namespace. However, you can create multiple selectors to target multiple namespaces.
