### ISSUE TITLE
Unable to create bottlerocket profile even when I mention it in the eks_managed_groups_defaults

### ISSUE THREAD

**Issue by govardha** [terraform-aws-modules/terraform-aws-eks#2288]
## Description

I am trying to create a bottle rocket based EKS Managed Node group, my cluster is created, the node groups are created, but it always ends up with Amazon Linux, rather than Bottlerocket.  

I did notice one weird thing though if in the eks_managed_node_group_defaults map I don't include the platform and ami_id, the bottlerocket based nodes are created.  But the issue is, although AWS has issued a newer version of the bottlerocket OS terraform never recognizes a new version is out and doesn't upgrade the OS hence I tried to introduce ami_id.  

If your request is for a new feature, please use the `Feature request` template.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
18.30.2
- Terraform version:

Terraform v1.3.3
- Provider version(s):
AWS 4.37.0

## Reproduction Code [Required]

```
data "aws_ami" "eks_default_bottlerocket" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["bottlerocket-aws-k8s-${local.cluster_version}-x86_64-*"]
  }
}

module "eks_cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"
  ##version = "18.30.0"

  cluster_name                    = "${var.cluster_prefix}-${var.cluster_inst}-eks-${local.region}"
  cluster_version                 = var.eks_version
  cluster_endpoint_private_access = false
  cluster_endpoint_public_access  = true
  enable_irsa                     = true
  vpc_id                          = var.eks_vpc_id
  subnet_ids                      = data.aws_subnets.this_eks_subnets.ids

  
  eks_managed_node_group_defaults = {
    ami_type = "BOTTLEROCKET_x86_64"
    platform = "bottlerocket"
    ami_id                                = data.aws_ami.eks_default_bottlerocket.image_id
    attach_cluster_primary_security_group = true
    create_security_group                 = false
    iam_role_attach_cni_policy            = true


    ## We do the additional policies so that SSM starts working and is reporting crap into CloudWatch
    iam_role_additional_policies = [
      "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
      "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
    ]
  }

  eks_managed_node_groups = {
    first_ng = {
      create_launch_template = false
      launch_template_name   = ""
      name                   = local.node_group
      instance_types         = var.instance_types
      min_size               = var.min_size
      max_size               = var.max_size
      desired_size           = var.desired_size
      ami_type               = var.ami_type
      platform               = "bottlerocket"
      ami_id                 = data.aws_ami.eks_default_bottlerocket.image_id
    }

    bottlerocket_default = {
      # By default, the module creates a launch template to ensure tags are propagated to instances, etc.,
      # so we need to disable it to use the default template provided by the AWS EKS managed node group service
      create_launch_template = false
      launch_template_name   = ""
      ami_type               = "BOTTLEROCKET_x86_64"
      platform               = "bottlerocket"
      ami_id                 = data.aws_ami.eks_default_bottlerocket.image_id
      instance_types         = var.instance_types
      min_size               = var.min_size
      max_size               = var.max_size
      desired_size           = var.desired_size
    }
  }
}
```

terraform init
terraform plan
terraform apply

I am using workspaces

I have cleared local cache.

## Expected behavior
I expect a bottlerocket OS based EKS managed node group created in my EKS cluster.

## Actual behavior
Amazon Linux based EKS managed node group is created.

**Comment by bryantbiggs** [comment]
You don't need to specify the AMI ID - this will pin to whichever AMI you are providing. You only need to set
```hcl
    ami_type = "BOTTLEROCKET_x86_64"
    platform = "bottlerocket"
```

**Comment by govardha** [comment]
Hi Bryan,

Thanks for your response, I do have those parameters, when I query the SSM parameters for bottlerocket, I get a newer AMI than what my existing cluster is running, but terraform never sees the latest recommended ami is different hence says nothing has changed in the environment.

Hence I am trying to set the `ami_id ` to get the module to see there is a difference and then allow me to upgrade.  

Is there a different way to go about this?

Thank you!

**Comment by bryantbiggs** [comment]
that is down to the managed node group service and when they update the service to use the newer AMI
