### ISSUE TITLE
Cannot use default launch_template

### ISSUE THREAD

**Issue by azizea** [terraform-aws-modules/terraform-aws-eks#2296]
## Description

https://github.com/terraform-aws-modules/terraform-aws-eks/commit/e16b3c4cbd5f139d54467965f690e79f8e68b76b#r89912554

While trying to create a default launch template using scenario 1 with Terraform v1.1.9

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module versions 18.24.0 , 18.30.3 :

- Terraform version:
1.3.4
- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v3.75.2
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.15.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.24.0"

  cluster_name    = local.cluster_name
  cluster_version = var.kubernetes_version

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  cluster_endpoint_private_access                = var.cluster_private_endpoint
  cluster_endpoint_public_access                 = !var.cluster_private_endpoint
  cluster_enabled_log_types                      = ["api", "audit", "authenticator"]

  eks_managed_node_groups = {
    node_group = {
      name                 = var.cluster_node_groups_name
      version              = var.kubernetes_version
      force_update_version = true
      desired_size         = 6
      max_size             = 9
      min_size             = 6
      instance_types = ["r5.xlarge"]
      subnets        = [element(module.vpc.private_subnets, 0)]
      disk_size      = 20
      create_launch_template          = false
      launch_template_name            = ""
      launch_template_description     = ""
      enable_monitoring               = true
      cluster_log_retention_in_days   = 7
    }
    worker_additional_security_group_ids = [aws_security_group.all_worker_mgmt.id]
    map_roles                            = local.map_roles
    map_users                            = var.map_users
    map_accounts                         = local.map_accounts
  }

  depends_on = [module.vpc_peering]

}
```

* Using workspaces

* Cleared cache

`terraform apply`

## Expected behavior

EKS managed default launch template created 

## Actual behavior

> ╷
> │ Error: Invalid template interpolation value
> │ 
> │   on .terraform/modules/aws_platform.eks/modules/eks-managed-node-group/main.tf line 40, in locals:
> │   40:   launch_template_name_int = coalesce(var.launch_template_name, "${var.name}-eks-node-group")
> │     ├────────────────
> │     │ var.name is null
> │ 
> │ The expression result is null. Cannot include a null value in a string template.
> ╵
> ╷
> │ Error: Invalid template interpolation value
> │ 
> │   on .terraform/modules/aws_platform.eks/modules/eks-managed-node-group/main.tf line 358, in locals:
> │  358:   security_group_name   = coalesce(var.security_group_name, "${var.name}-eks-node-group")
> │     ├────────────────
> │     │ var.name is null
> │ 
> │ The expression result is null. Cannot include a null value in a string template.
> ╵
> ╷
> │ Error: Invalid template interpolation value
> │ 
> │   on .terraform/modules/aws_platform.eks/modules/eks-managed-node-group/main.tf line 410, in locals:
> │  410:   iam_role_name = coalesce(var.iam_role_name, "${var.name}-eks-node-group")
> │     ├────────────────
> │     │ var.name is null
> │ 
> │ The expression result is null. Cannot include a null value in a string template.
> ╵
> Releasing state lock. This may take a few moments...

**Comment by bryantbiggs** [comment]
I don't think there is an error in the module, I think the error is in your config; namely `var.cluster_node_groups_name` must be null in your config. This works in our examples which is why I believe the error is in your configuration https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1bc86e19aa0a8776e578d4f58b852bffa28e2aac/examples/eks_managed_node_group/main.tf#L133-L134

**Comment by azizea** [comment]
Hello, 

thank you so much for your response, i fixed the above issue per your recommendation. 

Now i got EKS managed node group, and have `**enable_monitoring = true**`

```
  # EKS Managed node group, with default launch_templates
  eks_managed_node_groups = {
    default = {
      # EKS Managed node templates
      cluster_log_retention_in_days = 7
      create_launch_template        = false
      enable_monitoring             = true
      force_update_version          = true
      launch_template_description   = ""
      launch_template_name          = ""

      # Instance configurations
      desired_size                  = 6
      disk_size                     = 20
      instance_types                = ["r5.xlarge"]
      max_size                      = 9
      min_size                      = 6
      subnets                       = [element(module.vpc.private_subnets, 0)]
      version                       = var.kubernetes_version
    }
```

however after cluster is built and i still see that node instances have not enabled enhanced monitoring.

could you help with this? i see same variable in your example. but somehow it's not enabling monitoring

![image](https://user-images.githubusercontent.com/33434200/202576463-0300de65-95fb-4493-b4e2-e72762d36ef9.png)

Thank you!

**Comment by bryantbiggs** [comment]
that feature is only supported if using the custom launch template https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1bc86e19aa0a8776e578d4f58b852bffa28e2aac/modules/eks-managed-node-group/main.tf#L201

**Comment by azizea** [comment]
Thank you so much 

> that feature is only supported if using the custom launch template
> 
> https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1bc86e19aa0a8776e578d4f58b852bffa28e2aac/modules/eks-managed-node-group/main.tf#L201

Thank you so much, was able to create aws_launch_template resource and referenced this resource in eks managed node group!

I appreciate your help!
