### ISSUE TITLE
Feature Request: Key Pair for Worker Nodes

### ISSUE THREAD

**Issue by Jeeppler** [terraform-aws-modules/terraform-aws-eks#23]
## I'm submitting a

* [ ] feature request

## What is the current behavior

I want to access the worker nodes via SSH using a Key Pair (Private-Public Key). However there is no option which allows me to specify a key pair to be installed on the worker nodes.

## What's the expected behavior

Provide an option to specify a key pair (local or already in AWS) and installed it on the worker nodes. It should be possible to set the key name via variable. For inspiration have a look at Terraform-DC/OS module: https://github.com/dcos/terraform-dcos/tree/master/aws#configure-aws-ssh-keys

**Comment by Jeeppler** [comment]
The `key_name` parameter for the `worker_group_defaults` does not seem to work:

~~~
  workers_group_defaults = {
      ...
      key_name = "my-key"  # The key name that should be used for the instances in the 
      ...
    }
~~~

The EC2 instances do not show a key pair in their configuration. On the other hand I did not import the key in the local environment, the key however was registered in AWS. Do I miss something?

**Comment by Jeeppler** [comment]
Pull request #17 added the `key_name` parameter to the `worker_group_defaults`.

**Comment by brandoconnor** [comment]
Closing this out as I shop 1.1.0 now. Thanks again!

**Comment by macropin** [comment]
Is this documented anywhere?

**Comment by max-rocket-internet** [comment]
@macropin 

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf#L28

**Comment by chrissound** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a47f4642215734ce249ad0f9bb559bafe2f03c8e/local.tf#L32
