### ISSUE TITLE
Data source for current AWS partition breaks modules

### ISSUE THREAD

**Issue by apeschel** [terraform-aws-modules/terraform-aws-eks#2301]
## Description

No matter what I do, I can't seem to get this module to work. I keep running into this issue:

https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1753

The issue was improperly closed by an automated bot without ever receiving any real triage by a maintainer.

While I appreciate that the root cause of the issue is likely due to an upstream issue with the AKS provider, that doesn't help me at all with being able to actually use this module.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
18.30.3
- Terraform version:
1.3.4
- Provider version(s):

## Reproduction Code [Required]

Refer to https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1753

**Comment by bryantbiggs** [comment]
please provide a reproduction configuration - I suspect you have a `depends_on` on your module which is not recommended for modules

**Comment by apeschel** [comment]
@bryantbiggs Apologies on the late response - your suspicion was correct on this. Thank you for your help.

**Comment by bryantbiggs** [comment]
no worries!
