### ISSUE TITLE
use public subnet in eks cluster

### ISSUE THREAD

**Issue by raghavgupta0** [terraform-aws-modules/terraform-aws-eks#2302]
Hi,

I am trying to create a cluster with farget profile, using the "subnet_ids" option I can define private subnets only, can you please help me with how I can use a public subnet as well?

I can see resource "`aws_eks_cluster`" has a "vpc_config" option where we can define both public & private subnets.

EKS version : 1.22
Module version : latest

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1bc86e19aa0a8776e578d4f58b852bffa28e2aac/examples/fargate_profile/main.tf#L79
