### ISSUE TITLE
github-actions bot sends emails for old, merged pull requests

### ISSUE THREAD

**Issue by graywolf-at-work** [terraform-aws-modules/terraform-aws-eks#2304]
## Is your request related to a new offering from AWS?

No.

## Is your request related to a problem? Please describe.

When I make a pull request to this project and it is merged, I'm happy that I've helped a little bit and promptly forget about it. And then github-actions bot reminds be about the pull requests after more then two years with very useful message `I'm going to lock this pull request because it has been closed for 30 days`.

https://github.com/terraform-aws-modules/terraform-aws-eks/pull/880#issuecomment-1319467309
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/864#issuecomment-1319467498

## Describe the solution you'd like.

Please consider not sending the very useful email.

## Describe alternatives you've considered.

Ignoring notifications for this whole repository, but I would like to avoid that.

## Additional context

Can't think of anything.

**Comment by bryantbiggs** [comment]
you can configure which events you want to receive notifications for in the GItHub UI
