### ISSUE TITLE
aws_cloudwatch_event_rule limits cluster name to 35 characters

### ISSUE THREAD

**Issue by FernandoMiguel** [terraform-aws-modules/terraform-aws-eks#2311]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
In https://github.com/terraform-aws-modules/terraform-aws-eks/blob/efbe952/modules/karpenter/main.tf#L261
`aws_cloudwatch_event_rule` name limits cluster name to 35 characters, due to prefixing "Karpenter" and "InstanceStateChange".
Given our clusters have an usually longer name plus append a Random Pet name, this makes it very hard to work with this length limitation

## Describe the solution you'd like.
for the use of a different variable for the Queue and the SQS Rule.
Also for the option of using `name_prefix`

## Describe alternatives you've considered.
limiting cluster name to 35 characters until this is addressed

## Additional context
The next limit to be hit is `aws_sqs_queue` name of 80 characters, which is prefixed by `Karpenter-`, making the total limit for the cluster name of 70 characters.

**Comment by nitrocode** [comment]
This may be resolved with the per kubernetes addon helm_config option of overriding the `service_account`  as seen in this PR https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1193

See example for the aws lb controller

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/aws-load-balancer-controller#irsa-is-too-long

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.0.0 :tada:
