### ISSUE TITLE
Support taints for self managed node group

### ISSUE THREAD

**Issue by weixianearmap** [terraform-aws-modules/terraform-aws-eks#2313]
## Is your request related to a problem? Please describe.

Currently, I see we are able to add taints for managed node group, but we are not able to add taints for self managed node group when we create the node group. And we even can't use eksctl to add taints later due to the design/limitation of eksctl.

## Describe the solution you'd like.

`terraform-aws-eks` should support taints for self managed node group as well.

## Describe alternatives you've considered.

We have to use eksctl to create self managed node group which supports taints. However, it's better for us to use this terraform module only instead of using both this module and eksctl.

or use 
```
kubelet_extra_args = "--register-with-taints=os=windows:NoSchedule"
```

**Comment by andyc-valstro** [comment]
PRs welcome for this?

**Comment by bryantbiggs** [comment]
Taints are supported by the EKS managed node group created here because the EKS managed node groups support taints - we can pass taints to the EKS API and they are created. With self-managed node groups, there is no AWS or EKS API, so how would this be accomplished?

**Comment by andyc-valstro** [comment]
not prettily :) 

but with some super annoying terraform object -> string conversion and your `user_data` modules' `bootstrap_extra_args` var.

```
  bootstrap_extra_args = "-KubeletExtraArgs ' --register-with-taints=os=windows:NoSchedule'"
```

we'd have to merge taints string into user-specified extra args.

**Comment by andycmaj** [comment]
not prettily :) 

but with some super annoying terraform object -> string conversion and your `user_data` modules' `bootstrap_extra_args` var.

```
  bootstrap_extra_args = "-KubeletExtraArgs ' --register-with-taints=os=windows:NoSchedule'"
```

we'd have to merge taints string into user-specified extra args.

**Comment by weixianearmap** [comment]
I found another way to solve it with [runtimeClasses.yml](https://kubernetes.io/docs/concepts/windows/user-guide/#simplifying-with-runtimeclass)

**Comment by bryantbiggs** [comment]
> I found another way to solve it with [runtimeClasses.yml](https://kubernetes.io/docs/concepts/windows/user-guide/#simplifying-with-runtimeclass)

closing out
