### ISSUE TITLE
Using target_group_arns parameter conflicts with aws_autoscaling_attachment usage in subsequent modules

### ISSUE THREAD

**Issue by SinisterMinister** [terraform-aws-modules/terraform-aws-eks#2315]
## Description

Using `target_group_arns` causes issues with using `aws_autoscaling_attachment` with external modules. We use an addon module approach where we have modules that build upon the deployments of other modules. We have a module that attaches another load balancer to our cluster, but if we run the parent module, it breaks the child module's attachment. This is due to the design of the provider, which recommends:

> Terraform currently provides both a standalone [`aws_autoscaling_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_attachment) resource (describing an ASG attached to an ELB or ALB), and an [`aws_autoscaling_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group) with `load_balancers` and `target_group_arns` defined in-line. These two methods are not mutually-exclusive. If `aws_autoscaling_attachment` resources are used, either alone or with inline `load_balancers` or `target_group_arns`, the `aws_autoscaling_group` resource must be configured to ignore changes to the `load_balancers` and `target_group_arns` arguments within a [lifecycle configuration block](https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html).

The module should favor using `aws_autoscaling_attachment` resources that it manages instead of the built-in resource parameters to eliminate this conflict. This would allow for more flexibility with using the module in more complex setups.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
18.30.3
- Terraform version:
v1.3.2
- Provider version(s):
v4.40.0

## Reproduction Code [Required]

```terraform
# Deploy cluster with target group arns defined
module "cluster" {
  ...
  self_managed_node_groups = {
    group = {
      ...
      target_group_arns = [local.target_group_arn_0]
    }
  }
}

# Attach target group to cluster directly. This will cause the module and this resource to fight
resource "aws_autoscaling_attachment" "asg_lb" {
  autoscaling_group_name = module.cluster.self_managed_node_groups_autoscaling_group_names[0]
  lb_target_group_arn    = local.target_group_arn_1
}
```

Use `target_group_arns` with node groups while also attaching to a target group directly.

## Expected behavior

Both target groups are attached and don't interfere with the other

## Actual behavior

Target group attachments cleared to only ones defined in module.

**Comment by SinisterMinister** [comment]
It does appear that you can work around this by electing to use `aws_autoscaling_attachment` directly and never using `target_group_arns` field in the modules but I feel like a better dev experience can be had by allowing for both to work in conjunction.

**Comment by bryantbiggs** [comment]
This form of managing ALBs and target group bindings is generally not used with EKS/Kubernetes. This module follows more of the Kubernetes "norms" where things like the desired size value is ignored since nearly all clusters use a form of autoscaling. Likewise, the vast majority of clusters utilize an ingress controller such as the ALB controller for managing ALBs and/or the target group bindings. Therefore, we won't be looking to make any additional changes to deviate from this convention at this time

**Comment by SinisterMinister** [comment]
> Likewise, the vast majority of clusters utilize an ingress controller such as the ALB controller for managing ALBs and/or the target group bindings. Therefore, we won't be looking to make any additional changes to deviate from this convention at this time

That's a very closed-minded approach and antithetical to reusable module design and doesn't allow for extensibility and assumes that our use-case is invalid.

Are you saying that anyone who deviates from whatever approach you've deemed as not "generally" used isn't viable or supported? How do you expect users to innovate using this module then or who have edge-case issues with your approach, such as us?

**Comment by SinisterMinister** [comment]
@bryantbiggs Does this mean that this module won't support alternative routing solutions from ALBs? e.g. Traefik, nginx, Kong, or others? That's essentially what this ticket is about as we do not use ALBs for our edge and have multiple ingress classes to wire up. Is this module not meant to be extended upon?

**Comment by bryantbiggs** [comment]
> Does this mean that this module won't support alternative routing solutions from ALBs? e.g. Traefik, nginx, Kong, or others? That's essentially what this ticket is about as we do not use ALBs for our edge and have multiple ingress classes to wire up. Is this module not meant to be extended upon?

That is not what I stated - I stated that the controllers are generally responsible for managing the target groups and routing of paths to services/pods/nodes, not Terraform. 

> Is this module not meant to be extended upon?

I don't follow. This module can be extended as you have stated above by the use of `aws_autoscaling_attachment`
