### ISSUE TITLE
Price-capacity-optimized allocation strategy

### ISSUE THREAD

**Issue by tanvp112** [terraform-aws-modules/terraform-aws-eks#2316]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? 
  - Yes ✅: please list the AWS provider version which introduced this functionality

[price-capacity-optimized](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#spot_allocation_strategy) is supported.

## Is your request related to a problem? Please describe.

As per described by AWS [here](https://aws.amazon.com/blogs/compute/introducing-price-capacity-optimized-allocation-strategy-for-ec2-spot-instances/)

## Describe the solution you'd like.

Ability to set this spot allocation strategy for managed node group.

## Describe alternatives you've considered.

Self-managed node group.

## Additional context

NA

**Comment by bryantbiggs** [comment]
This is managed by Karpenter today

**Comment by tanvp112** [comment]
Thanks Bryan for confirming. For others who came here for the feature to be available for mng, please cast your vote [here](https://github.com/aws/containers-roadmap/issues/1903).
