### ISSUE TITLE
provider hashicorp/aws version issue

### ISSUE THREAD

**Issue by raghavgupta0** [terraform-aws-modules/terraform-aws-eks#2317]
Hi Team,
Today I am getting the below error related to the provider version, so please let me know what changes are required 
till yesterday it was working fine with same version.
error 
│ Could not retrieve the list of available versions for provider hashicorp/aws: no available releases match the given constraints >= 2.42.0, >= 2.54.0, >= 2.70.0, >= 3.7.1, >= 3.72.0, <
│ 4.0.0, >= 4.45.0

module version: latest
EKS : 1.24
terraform "~> 1.0"
hashicorp/aws ">= 3.72"
hashicorp/kubernetes  ">= 2.10"
gavinbunney/kubectl  ">= 1.7.0"
tls   "<4.0.0"

**Comment by bryantbiggs** [comment]
Please provide a reproduction
