### ISSUE TITLE
unable to "opt in to using a template provided by the module"

### ISSUE THREAD

**Issue by yokhahn** [terraform-aws-modules/terraform-aws-eks#2329]
"Key": "cluster.eks",
      "Source": "registry.terraform.io/terraform-aws-modules/eks/aws",
      "Version": "18.29.0",

The documentation at https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/user_data.md#self-managed-node-group
indicates that one should be able to "opt in to using a template provided by the module"  for self-managed node groups by setting:
enable_bootstrap_user_data = true # to opt in to using the module supplied bootstrap user data template

however it appears that this is never passed along to the module "self_managed_node_group" {
in node_groups.tf

I expect adding a line like:
enable_bootstrap_user_data = try(each.value.enable_bootstrap_user_data, var.self_managed_node_group_defaults.enable_bootstrap_user_data, false)

to the module call would fix things.. but I don't have a good place to test before submitting a pull request.
So I thought I'd drop this issue.

**Comment by bryantbiggs** [comment]
please fill in the template provided - we cannot assist without a proper reproduction 

also - do note that we are now onto version 19
