### ISSUE TITLE
Feature request: ability to attach EBS volumes to worker nodes

### ISSUE THREAD

**Issue by maxenglander** [terraform-aws-modules/terraform-aws-eks#233]
# Feature request: ability to attach EBS volumes to worker nodes

I would like to be able to attach EBS volumes to worker nodes. Currently it is not possible to do so.

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

It is not possible to attach EBS volumes to worker nodes.

## What's the desired behavior?

I would like to be able to include either an array of EBS volumes details for this module to attach or create-and-attach to the worker nodes.

## Are you able to fix this problem and submit a PR? Link here if you have already.

I plan on submitting a PR.

**Comment by max-rocket-internet** [comment]
Hi Max!
Sounds good. Will check the PR when it's opened.
Kind regards,
Max

**Comment by max-rocket-internet** [comment]
As discussed in other issues/PRs, this can be achieved by creating your own LC outside the module and specifying it for the worker group 🙂
