### ISSUE TITLE
use_default_tags removed from 19.0.x

### ISSUE THREAD

**Issue by verwilst** [terraform-aws-modules/terraform-aws-eks#2330]
## Description
v18.x had the use_default_tags parameter, which seems to be removed in v19. 
Is there any reasoning behind this? Maybe another way to get default AWS provider tags to be added?

**Comment by bryantbiggs** [comment]
please see https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md#removed
