### ISSUE TITLE
module.eks.cluster_id is not working

### ISSUE THREAD

**Issue by raghavgupta0** [terraform-aws-modules/terraform-aws-eks#2331]
In v18.31.2 I used "module.eks.cluster_id" to fetch the cluster name and used that value accordingly.
but in the latest version v19.0.* I am getting error for the same 

data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

  with module.eks_fargate.data.aws_eks_cluster.cluster,
 on ../provider.tf line 2, in data "aws_eks_cluster" "cluster":
  2:   name = module.eks.cluster_id
the argument "name" is required, but no definition was found.

**Comment by sabhika** [comment]
We are facing the same issue as well.

╷
│ Error: Missing required argument
│ 
│   with data.aws_eks_cluster.cluster,
│   on main.tf line 55, in data "aws_eks_cluster" "cluster":
│   55:     name = module.eks.cluster_id
│ 
│ The argument "name" is required, but no definition was found.

**Comment by bryantbiggs** [comment]
Please see the upgrade guide - the error message is telling you quite clearly what the issue is https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md
