### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by DutchEllie** [terraform-aws-modules/terraform-aws-eks#2332]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/7124d7603a81ad07bbcc7a932ba0f41989365471/node_groups.tf#L171

`local.node_secuirty_group_recommended_rules`

I don't think that secuirty should be spelled like this. This could cause some issues

**Comment by DutchEllie** [comment]
I see that the variable it is referencing is technically also spelled wrong? Is this intentional?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.1.0 :tada:
