### ISSUE TITLE
self_managed_node_groups:  Error: Conflicting configuration arguments

### ISSUE THREAD

**Issue by tfcoder1** [terraform-aws-modules/terraform-aws-eks#2336]
I have created a self_managed_node_groups with instance_requirements specs as per the config below, however it resulted in error: **"instance_requirements": conflicts with instance_type**

- ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
19.0.4

## Reproduction Code
``
module "self_managed_node_groups" {
  source = "../../modules/eks-cluster/modules/self-managed-node-group"

  name                            = "c4-r16"
  launch_template_name            = "c4-r16"
  launch_template_use_name_prefix = true
  cluster_name                    = module.eks.cluster_name
  cluster_version                 = module.eks.cluster_version
  cluster_endpoint                = module.eks.cluster_endpoint
  cluster_auth_base64             = module.eks.cluster_certificate_authority_data
  subnet_ids                      = [module.vpc.private_subnet_ids]
  vpc_security_group_ids = [module.eks.cluster_primary_security_group_id,
  module.eks.cluster_security_group_id]

  min_size     = 1
  max_size     = 10
  desired_size = 1

  instance_requirements = {
    cpu_manufacturers                                = ["AMD", "INTEL"]
    excluded_instance_types                          = ["T"]
    on_demand_max_price_percentage_over_lowest_price = 50
    vcpu_count = {
      max = 4
      min = 4
    }
    memory_mib = {
      max = 16000
      min = 16000
    }
  }

  ebs_optimized = true
  block_device_mappings = {
    xvda = {
      device_name = "/dev/xvda"
      ebs = {
        volume_size           = 400
        volume_type           = "gp3"
        delete_on_termination = true
      }
    }
  }
  tags = {
    "k8s.io/cluster-autoscaler/node-template/label/target-node" = "on-demand"
  }

}

## Expected behavior

self managed node group is created

## Actual behavior

Error: Conflicting configuration arguments
│ 
│   with module.self_managed_node_groups.aws_launch_template.this[0],
│   on ../../modules/eks-cluster/modules/self-managed-node-group/main.tf line 47, in resource "aws_launch_template" "this":
│   47: resource "aws_launch_template" "this" {
│ 
│ "instance_requirements": conflicts with instance_type
╵
╷
│ Error: Conflicting configuration arguments
│ 
│   with module.self_managed_node_groups.aws_launch_template.this[0],
│   on ../../modules/eks-cluster/modules/self-managed-node-group/main.tf line 270, in resource "aws_launch_template" "this":
│  270:   instance_type = var.instance_type
│ 
│ "instance_type": conflicts with instance_requirements

**Comment by bryantbiggs** [comment]
this is per the AWS API - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#instance_requirements

**Comment by tfcoder1** [comment]
Thanks, yes it worked after commenting instance_type. How about making it as an optional in the module?
