### ISSUE TITLE
Kubernetes cluster unreachable: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by raghavgupta0** [terraform-aws-modules/terraform-aws-eks#2338]
Hi,

I am trying to install EKS cluster with Fargate profile but getting an invalid apiversion error, I have changes apiversion to v1beta1 than I am getting below error,

 Error: The configmap "aws-auth" does not exist

   with module.eks_fargate.module.eks.kubernetes_config_map_v1_data.aws_auth[0],
   on .terraform/modules/eks_fargate.eks/main.tf line 518, in resource "kubernetes_config_map_v1_data" "aws_auth":
  518: resource "kubernetes_config_map_v1_data" "aws_auth" {

EKS version 1.24
module latest
helm : api_version = "client.authentication.k8s.io/v1beta1
kubernetes: api_version = "client.authentication.k8s.io/v1beta1"

**Comment by bryantbiggs** [comment]
hi - please provide the information requested in the issue template so we can help triage
