### ISSUE TITLE
EKS Managed node group do not use disk_size attribute

### ISSUE THREAD

**Issue by napestershine** [terraform-aws-modules/terraform-aws-eks#2340]
Hi

I am trying to create a EKS cluster with managed node groups. Here is repo:
https://github.com/napestershine/eks-lt

When I specify `disk_size`, it doesn't make any changes to disk_size as its on this line of code:
https://github.com/napestershine/eks-lt/blob/main/eks.tf#L42

on AWS console it still shows using disk size 20 GB.

How can I fix it?

Thanks

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/ca03fd9ec16f8e6d8440d23adb72cb7c7ba33c56/modules/eks-managed-node-group/variables.tf#L336
