### ISSUE TITLE
Shared IAM role for node_groups.

### ISSUE THREAD

**Issue by ipleten** [terraform-aws-modules/terraform-aws-eks#2341]
We have a couple eks_mamanged_node_group's and we would like to share the same IAM roles as we want to have them static due to access to/from another account.
Currently it's seems trying to create IAM role per each node_group. And even more if we set create_iam_role=false and iam_role_arn='arn:xxx:xxx' we need to manage all permissions manually.

So after upgrading from v14 to v19 we need to import and manage IAM role and policies on our own.

Is there any way to do this using  module?

**Comment by bryantbiggs** [comment]
The shared IAM role would need the permissions applied - the module does not attach permissions to a role it did not create as this would cause a conflict
