### ISSUE TITLE
v19 needs better examples for MNG

### ISSUE THREAD

**Issue by FernandoMiguel** [terraform-aws-modules/terraform-aws-eks#2343]
I feel I'm pretty experienced with this module and its submodules, like MNG.
but doing the upgrade from 18 to 19, I am struggling to get the SGs working.

Can the examples be updated to include a few more configurations?

**Comment by bryantbiggs** [comment]
> Can the examples be updated to include a few more configurations?

What configurations? What are you struggling with

**Comment by FernandoMiguel** [comment]
closing for now... during the v19 upgrade we missed a tag so the MNG wasnt picking up the right SG.
once we readded the tag, the correct SG was picked.
sorry for the noise
