### ISSUE TITLE
Add EKS Addon Configurations

### ISSUE THREAD

**Issue by seanturner026** [terraform-aws-modules/terraform-aws-eks#2344]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: [v4.47.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.47.0)

## Is your request related to a problem? Please describe.
AWS recently added the capability to add configurations to EKS Addons

## Describe the solution you'd like.
A modification to the interface that allows for a json configuration to be passed to EKS Addons

## Describe alternatives you've considered.
n/a

## Additional context
- This PR merges the capability into the AWS Provider: https://github.com/hashicorp/terraform-provider-aws/pull/28295
- blog post: https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/

**Comment by bryantbiggs** [comment]
already working on it 😉

**Comment by seanturner026** [comment]
I thought this might be the case :D

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.1.0 :tada:
