### ISSUE TITLE
Make default KMS alias optional or configurable

### ISSUE THREAD

**Issue by kodakmoment** [terraform-aws-modules/terraform-aws-eks#2346]
## Is your request related to a problem? Please describe.
We are running into an AlreadyExistsException for the KMS alias in our labbing environment. This is because we have made some mistakes and are not able to remove the KMS keys that was previously created by this module. We are waiting for AWS support to have the KMS keys removed.

## Describe the solution you'd like.
It would be nice if the module was able to have the default kms alias optional or configurable in some way

**Comment by FernandoMiguel** [comment]
it takes 7 to 30 days for a KMS key to be deleted.
if you apply, destroy , apply, it will use the exact same name for the alias, and will fail.
ideally you use a `name_prefix` to avoid clashing

**Comment by FernandoMiguel** [comment]
sadky this module opts for a static key name
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L132-L136
a PR could improve that.

**Comment by FernandoMiguel** [comment]
the downstream module supports both
https://github.com/terraform-aws-modules/terraform-aws-kms/blob/master/main.tf#L362
