### ISSUE TITLE
configuration_values example is incorrect

### ISSUE THREAD

**Issue by mmerickel** [terraform-aws-modules/terraform-aws-eks#2348]
The new `configuration_values` is broken, the values must be strings and not bool/number.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/f0abb25ba265cc952fc2573884166c657385be85/examples/eks_managed_node_group/main.tf#L64-L74

**Comment by bryantbiggs** [comment]
Thanks - just discovered this as well this morning https://github.com/clowdhaus/eks-reference-architecture/blob/main/ipv4-prefix-delegation/eks.tf

I'll get it corrected

**Comment by bryantbiggs** [comment]
or feel free to open a PR if you are inclined

**Comment by marvin-w** [comment]
Oh didn't even look for issues, just fixed it straight away. Thanks for linking :).

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.2.0 :tada:
