### ISSUE TITLE
`launch_template_tags`: allow specifying resource tags

### ISSUE THREAD

**Issue by pat-s** [terraform-aws-modules/terraform-aws-eks#2351]
## Is your request related to a problem? Please describe.
`launch_template_tags` let's you add additional tags to launch templates which are then applied to new instances.

However, AFAICS there is no option to control the so called "resource tags" for the newly created tags. These decide e.g. whether these new tags are also applied to spot instances.

![image](https://user-images.githubusercontent.com/8430564/208289443-b3f157d4-0bec-48d1-924b-435514e1675a.png)

![image](https://user-images.githubusercontent.com/8430564/208289470-fda1444f-1cca-4e73-a947-dd799a094eea.png)

## Describe the solution you'd like.
Allow defining resource tags for custom `launch_template_tags`.

## Additional context

aws-eks v18.31.2

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.2.0 :tada:
