### ISSUE TITLE
Some region not support launch template elastic gpu tagging.

### ISSUE THREAD

**Issue by cw-juyeonyu** [terraform-aws-modules/terraform-aws-eks#2356]
## Description

When upgrading terraform eks module to "19.3.1", an error occurred with the message "Tagging an elastic gpu on create is not yet supported in this region".

## Versions

- Module version [Required]: 19.3.1

- Terraform version: 1.3.6

- Provider version(s):
  - aws: 4.40.0

### Terminal Output Screenshot(s)

│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "8066ceb6-8791-4875-a9d3-7325de60d41a"
│   },
│   Message_: "Tagging an elastic gpu on create is not yet supported in this region."
│ }

## Additional context

AWS Region: ap-northeast-2

I think the [code of the line](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/046c688be2c2440fafc8cef48db9f3bc8915058d/modules/eks-managed-node-group/main.tf#L273) is related

**Comment by jurgen-weber-deltatre** [comment]
Yeah, this is related; https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2355

**Comment by gamunu** [comment]
This is the change that appears to have added the GPU tagging. The only way to get around this is to downgrade the module version.

https://github.com/terraform-aws-modules/terraform-aws-eks/compare/v19.1.1...v19.2.0

**Comment by cw-juyeonyu** [comment]
> This is the change that appears to have added the GPU tagging. The only way to get around this is to downgrade the module version.
> 
> [v19.1.1...v19.2.0](https://github.com/terraform-aws-modules/terraform-aws-eks/compare/v19.1.1...v19.2.0)

I don't use elastic gpu.
Should I wait until AWS supports it?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.4.0 :tada:
