### ISSUE TITLE
Review release management lifecycle

### ISSUE THREAD

**Issue by nmargaritis** [terraform-aws-modules/terraform-aws-eks#2358]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
It is a suggestion related to what took place (release wise) primarily after version v19. (it has also happened in the past)

It is not usual to do 5 releases on a library like that in that short period of time. It might indicate a problem with the flow that is being used to release or the steps taken prior to a release being promoted to make sure that the release is ready.

![Screenshot 2022-12-19 at 11 13 12](https://user-images.githubusercontent.com/7851375/208392719-b0d0770b-45cc-41ea-9e17-411c814238b1.png)

## Describe the solution you'd like.
Maybe it is good idea to introduce beta builds which community will use to give feedback. This way you can take a little bit more time to debug and review if the release is stable enough to be promoted. It will also minimize releases with major flaws being available to be used as well as minimize the number of new releases you promote, so maintenance from other parties using the module would be easier. 

## Describe alternatives you've considered.
/

## Additional context
This is a suggestion.

**Comment by bryantbiggs** [comment]
1. What is a "build"
2. What would the process for making something "beta" look like
3. Why are a number of releases in a short span "unusual" or "indicative of a problem"?

**Comment by bryantbiggs** [comment]
closing for now - please feel free to respond here if you have any additional details
