### ISSUE TITLE
Error launching new instance after release 19.2.0

### ISSUE THREAD

**Issue by pavlospt** [terraform-aws-modules/terraform-aws-eks#2361]
## Description

When release 19.2.0 was created `tag_specifications` were introduced, which are being applied to a bigger set of tags. This is causing our launch templates not being able to schedule a new instance, because we do not deploy any Elastic GPUs.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
19.3.1

- Terraform version:
1.3.4
- Provider version(s):
1.3.4

**Comment by darrenfurr** [comment]
Same issue here. All our EC2 nodes were destroyed & all pods are now stuck Pending.
I reverted the module to 19.1.0 & the nodes came back up.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.4.0 :tada:

**Comment by pavlospt** [comment]
@bryantbiggs as mentioned in the PR spot request should be removed from the default list as well!
