### ISSUE TITLE
internal  load balncer is still picking public subnet in EKS cluster.

### ISSUE THREAD

**Issue by nandeeshb09** [terraform-aws-modules/terraform-aws-eks#237]
Hi All,

Please help on this ,I have EKS cluster with public and private subnets.
I want worker nodes should be in private subnets and have created.

But internal load balancer is picking up public subnet still ,even though if we have tagged.
I have created tag in private subnet with below tag,but still internal load balancer is picking up public subnet.
Key | Value
kubernetes.io/role/internal-elb | 1

please guide on this...Im stuck at this work from last one week...Pleaseeee..

**Comment by stevehouel** [comment]
Did you tag to your private subnets ?

With that:
kubernetes.io/role/internal-elb = 1

Look at Step 4 on:
https://docs.aws.amazon.com/eks/latest/userguide/create-public-private-vpc.html

**Comment by max-rocket-internet** [comment]
Closing after no update in a long time. Feel free to reopen 🙂
