### ISSUE TITLE
Way to hide autoscaling group desired_size ("Objects have changed outside of Terraform") 

### ISSUE THREAD

**Issue by janavenkat** [terraform-aws-modules/terraform-aws-eks#2372]
## Description

Am currently updating terraform version from 0.13 to 1.2.9, everything works with plan expect with autoscaling group.
Seems from terraform version 0.15x there was a change in `ignore_changes` in lifecycle and terraform prepared a better design from terraform v 1.2.x.

It should not report the change `desired_size`  in output still I get the `desired_size` changes in the output

- [ x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version: 1.2.9

- Provider version(s): 
EKS: 18.29.0
AWS provider: 3.75.2

## Reproduction Code [Required]
Using the same code 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/5ae6abcaf49c67d1f71bfd9840a70300655cd25d/examples/self_managed_node_group/main.tf#L39

1. Create eks cluster with self managed node group with minimum of 2 node groups using eks module with terraform version v0.13.5
2. Deploy cluster autoscaler.
3. Update terraform to v 1.2.9
4. Run the plan, there will be output "Objects have changed outside of Terraform" and change in the `desired_size`

## Expected behavior

No changes. Infrastructure is up-to-date.

## Actual behavior

```tf

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:

  # module.eks-test-com.module.self_managed_node_group["spot-high"].aws_autoscaling_group.this[0] has changed
  ~ resource "aws_autoscaling_group" "this" {
      ~ desired_capacity          = 0 -> 1
        id                        = "eks-test-com-spot-high"
        name                      = "eks-test-com-spot-high"
        # (22 unchanged attributes hidden)

        # (9 unchanged blocks hidden)
    }
  # module.eks-test-com.module.self_managed_node_group["spot-low"].aws_autoscaling_group.this[0] has changed
  ~ resource "aws_autoscaling_group" "this" {
      ~ desired_capacity          = 6 -> 7
        id                        = "eks-test-com-spot-low"
        name                      = "eks-test-com-spot-low"
        # (22 unchanged attributes hidden)

        # (9 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.


No changes. Infrastructure is up-to-date.
```

Imagine if you have a lot of node groups in the config and it's produces some noise 

## Additional context

Already in autoscaling resource `desired_size` is ignored but it's with in the module

Useful links:
https://github.com/hashicorp/terraform/issues/28803
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1578
https://discuss.hashicorp.com/t/unless-you-have-made-equivalent-changes-to-your-configuration-or-ignored-the-relevant-attributes-using-ignore-changes/41950/6

**Comment by bryantbiggs** [comment]
This is not related to the module but to Terraform core, as you have already pointed out. You can either apply the changes as they are and any future changes should be ignored, or you can align your code to match the current state and apply and again any future changes will be ignored

**Comment by janavenkat** [comment]
> This is not related to the module but to Terraform core, as you have already pointed out. You can either apply the changes as they are and any future changes should be ignored, or you can align your code to match the current state and apply and again any future changes will be ignored

@bryantbiggs thank you for the response.

Am bit confused with the terraform changes, So after applying the plan and in my next run there should not be any changes right?

**Comment by bryantbiggs** [comment]
correct - its intended to set the value on creation but here it looks like its treating the changes from migrating across Terraform versions as a new "creation" - https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes

Once you apply the changes, it should forget about any future changes to `desired_capacity`

**Comment by bryantbiggs** [comment]
closing with the guidance provided above
