### ISSUE TITLE
Module upgrade to 19.x is detaching the additional IAM policies

### ISSUE THREAD

**Issue by tal-asulin** [terraform-aws-modules/terraform-aws-eks#2374]
## Description

Upgrading the module version from 18.x to 19.x requires a second apply for appending the additional IAM policies of the EKS and the relevant node groups.
We see that during the first apply, in the plan execution manifest, the IAM policies will be detached and later on re-attached as it is described in the documentation [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md).
In practice, we see that Terraform is detaching the IAM policies but not attaching them again. When we do a second apply, those policies are truly being attached as they should.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 18.21.0 -> 19.4.2

- Terraform version:
.# terraform version
  Terraform v1.3.2
  on darwin_amd64
  + provider registry.terraform.io/hashicorp/aws v4.48.0
  + provider registry.terraform.io/hashicorp/cloudinit v2.2.0
  + provider registry.terraform.io/hashicorp/kubernetes v2.16.1
  + provider registry.terraform.io/hashicorp/tls v4.0.4

.# terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/aws]
└── module.eks
    ├── provider[registry.terraform.io/hashicorp/aws] >= 4.47.0
    ├── provider[registry.terraform.io/hashicorp/tls] >= 3.0.0
    ├── provider[registry.terraform.io/hashicorp/kubernetes] >= 2.10.0
    ├── module.fargate_profile
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 4.47.0
    ├── module.kms
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
    ├── module.self_managed_node_group
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 4.47.0
    │   └── module.user_data
    │       └── provider[registry.terraform.io/hashicorp/cloudinit] >= 2.0.0
    └── module.eks_managed_node_group
        ├── provider[registry.terraform.io/hashicorp/aws] >= 4.47.0
        └── module.user_data
            └── provider[registry.terraform.io/hashicorp/cloudinit] >= 2.0.0

## Reproduction Code [Required]
Configuration for EKS module version 18.31.0:
```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "18.21.0"
  cluster_version = "1.21"
  cluster_name    = "test_cluster"
  vpc_id          = "<VPC>"
  subnet_ids      = [<SUBNETS_LIST>]

    eks_managed_node_group_defaults = {
      disk_size               = 50
      instance_types          = ["m6i.large", "m5.large", "m5n.large", "m5zn.large"]
      launch_template_version = "$Latest"
      tags                    = {"default_tag" = "test_tag"}

      iam_role_name = "test_cluster_iam_role"
      iam_role_additional_policies = [
        "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
        "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
        "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      ]
      create_security_group = false
    }

    eks_managed_node_groups = {
      green = {
        min_size     = 1
        max_size     = 2
        desired_size = 1

        instance_types = ["t3.large"]
        capacity_type  = "SPOT"
      }
    }
}

```

Configuration for upgrading the EKS module to 19.4.2:
```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "19.4.2"
  cluster_version = "1.21"
  cluster_name    = "test_cluster"
  vpc_id          = "vpc-0f626fd24e7511ba6"
  subnet_ids      = ["subnet-0c49f64a4a376aeb9", "subnet-03d7914c74d4e7855", "subnet-03132781cdd5438a1"]

    eks_managed_node_group_defaults = {
      disk_size               = 50
      instance_types          = ["t3.large"]
      launch_template_version = "$Latest"
      tags                    = {"default_tag" = "test_tag"}

      iam_role_name = "test_cluster_iam_role"
      iam_role_additional_policies = {
        AmazonSSMManagedInstanceCore       = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
        AmazonEKSWorkerNodePolicy          = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
        AmazonEC2ContainerRegistryReadOnly = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      }
    }

    eks_managed_node_groups = {
      green = {
        min_size     = 1
        max_size     = 2
        desired_size = 1

        instance_types = ["t3.large"]
        capacity_type  = "SPOT"
      }
    }
}
```

- Provision a new cluster using module version - 18.31.0
- Make the needed changed to `iam_role_additional_policies`
- Update the EKS module version to 19.4.2
- Run `terraform init`
- Run `terraform apply`
- On the next apply, you will still see changes needed to be done to the attached IAM policies.  

## Expected behavior

Zero changes after the seconf plan of the module upgrade. 

## Actual behavior

After the first apply, policies got detached and missing.
In the second apply, they are being attached again.

### Terminal Output Screenshot(s)
Output from the second apply:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # module.eks.aws_iam_role_policy_attachment.this["AmazonEKSClusterPolicy"] will be created
  + resource "aws_iam_role_policy_attachment" "this" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
      + role       = "test_cluster-cluster-20230101092344908100000004"
    }

  # module.eks.aws_iam_role_policy_attachment.this["AmazonEKSVPCResourceController"] will be created
  + resource "aws_iam_role_policy_attachment" "this" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
      + role       = "test_cluster-cluster-20230101092344908100000004"
    }

  # module.eks.module.eks_managed_node_group["green"].aws_eks_node_group.this[0] will be updated in-place
  ~ resource "aws_eks_node_group" "this" {
        id                     = "test_cluster:green-2023010109320725150000000d"
        tags                   = {
            "Name"        = "green"
            "default_tag" = "test_tag"
        }
        # (16 unchanged attributes hidden)

      ~ launch_template {
            id      = "lt-06254e929aa67afe2"
            name    = "green-2023010109320623740000000b"
          ~ version = "1" -> "$Latest"
        }

        # (3 unchanged blocks hidden)
    }

  # module.eks.module.eks_managed_node_group["green"].aws_iam_role_policy_attachment.additional["AmazonSSMManagedInstanceCore"] will be created
  + resource "aws_iam_role_policy_attachment" "additional" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
      + role       = "test_cluster_iam_role-20230101092344098100000003"
    }

Plan: 3 to add, 1 to change, 0 to destroy.
```

**Comment by bryantbiggs** [comment]
do you have a `depends_on` on your EKS module definition?

**Comment by bryantbiggs** [comment]
yep - remove the `depends_on`; you don't need it and its actually causing the issues you are seeing

https://github.com/hashicorp/terraform/issues/26383#issuecomment-699149145

**Comment by rudimk** [comment]
I see. Very interesting. I can now see why this would be an issue. Removing the dependency is a bit of an issue since we do need the EKS module to run after the VPC and the security groups are up. But at any rate, we were planning to break out the VPC-related TF and the EKS portion into separate TF states, so that ought to clean this up. 

Curiously - in the OP's description, they're not using `depends_on`.

**Comment by rudimk** [comment]
@bryantbiggs btw thanks for the assist! We have a way forward now, which is always a relief :)

**Comment by rudimk** [comment]
Gotcha - I actually realised later myself that we could depend on implicit dependency mapping by just referencing the list of subnets, which is something we're doing atm. Going to tweak our code and test this up - thanks so much!

**Comment by tal-asulin** [comment]
In the example provided above, we are not using `depends_on`. In addition, we were also simulated it with hardcoded IDs for the VPC and subnets list. am I missing something here?

**Comment by bryantbiggs** [comment]
Did you read the upgrade guide https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md#terraform-state-moves

**Comment by bryantbiggs** [comment]
closing with guidance provided above
