### ISSUE TITLE
"wait_for_cluster" is showing up changes

### ISSUE THREAD

**Issue by sahotay** [terraform-aws-modules/terraform-aws-eks#2375]
## Description

I recently upgraded the version from 15.2.0 to 16.2.0 and later to 17.2.0, the cluster works fine but it is showing an annoying change every time.

![image](https://user-images.githubusercontent.com/12233395/210254318-bfec79ed-e084-4abe-bb5d-e6cb7d8a03bb.png)

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists
- [x] Already performed following steps 

## Versions

- Module version [Required]: v17.24.0

- Terraform version: v0.13.6

**Comment by FernandoMiguel** [comment]
those versions are very old.
the latest one is v19.
also, your terraform version is a few years old. the latest is 1.3.6.
can you reproduce the issue with a recent version?

**Comment by sahotay** [comment]
updating to the latest version of this module is recreating this cluster which will make it pretty critical at this point

**Comment by bryantbiggs** [comment]
unfortunately, at that version its extremely hard to say and I don't know how else to help other than to upgrade to the latest version
