### ISSUE TITLE
make manage_aws_auth_configmap=false also ignore metadata

### ISSUE THREAD

**Issue by mattparkes** [terraform-aws-modules/terraform-aws-eks#2379]
## Is your request related to a problem? Please describe.
We have a slightly unique situation in that we provision some of our cluster with this module, but then manage the contents of the `aws-auth` ConfigMap with GitOps and ArgoCD. 

We've achieved 99% of what we want with `create_aws_auth_configmap=true` (so we can bootstrap our cluster with a minimum viable auth config) and `manage_aws_auth_configmap=false` (so that ArgoCD handles the contents of the repo from then on).

The _only_ issue we have is that ArgoCD automatically adds a label to every resource it updates and because lifecycle_ignore is only set on `data`, we always have this change pending:

```
Terraform will perform the following actions:

  # module.eks-cluster.kubernetes_config_map.aws_auth[0] will be updated in-place
  ~ resource "kubernetes_config_map" "aws_auth" {
        id          = "kube-system/aws-auth"
        # (3 unchanged attributes hidden)

      ~ metadata {
          ~ labels           = {
              - "argocd.argoproj.io/instance" = "foo-bar-aws-auth" -> null
            }
            name             = "aws-auth"
            # (5 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

## Describe the solution you'd like.
I'd like to change the `ignore_changes` on `kubernetes_config_map.aws_auth` from `[data]` to `[data, metadata.labels, metadata.annotations]` _(actually needs to be `[data, metadata[0].labels, metadata[0].annotations]` for ...reasons)_.

This would allow people to add  whatever metadata or annotations they want to this resource.

## Describe alternatives you've considered.
We could make another input called something like `aws_auth_labels=[]`, but this seems less desirable than my proposed solution and clutters the inputs with stuff that will likely never get used, as you'd also probably have to do `aws_auth_annotations=[]` whilst you're there to cover all bases.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.5.0 :tada:
