### ISSUE TITLE
kms_key_id invalid ARN: arn: invalid prefix

### ISSUE THREAD

**Issue by yanncarlier** [terraform-aws-modules/terraform-aws-eks#2381]
## Description

Using terraform v 1.1.9 and/or terraform v 1.3.6

examples/self_managed_node_group
only changing the config:  region  = "ap-northeast-2"

After terraform init
running terraform plan in this example dir:

I'm getting this error

│ Error: "block_device_mappings.0.ebs.0.kms_key_id" (4a16e7ff-1436-4604-a3a9-cc8771da4641) is an invalid ARN: arn: invalid prefix
│ 
│   with module.eks.module.self_managed_node_group["complete"].aws_launch_template.this[0],
│   on ../../modules/self-managed-node-group/main.tf line 47, in resource "aws_launch_template" "this":
│   47: resource "aws_launch_template" "this" {
│ 

## Versions

- Module version [Required]:
V19.4.2

**Comment by bryantbiggs** [comment]
we will need a reproduction to test/troubleshoot

**Comment by aiamur** [comment]
use kms_key_arn instead of kms_key_id. It solved this issue for me.

**Comment by yanncarlier** [comment]
> 

This also solved for me, @aiamur Thanks

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.8.0 :tada:
