### ISSUE TITLE
Additional node security group rule for metrics-server

### ISSUE THREAD

**Issue by AndreiBanaruTakeda** [terraform-aws-modules/terraform-aws-eks#2389]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No

## Is your request related to a problem? Please describe.
No

## Describe the solution you'd like.
So far we used two additional SG rules for our nodes to enable metrics-server communication:
```
node_security_group_additional_rules = {
    metrics-server_ingress = {
      description                   = "communication between control plane and the metrics-server endpoint"
      protocol                      = "tcp"
      from_port                     = "4443"
      to_port                       = "4443"
      type                          = "ingress"
      source_cluster_security_group = true
    },
    metrics-server_pod_ingress = {
      description = "communication between the metrics-server pod and the kubelet running on each worker node"
      protocol    = "tcp"
      from_port   = "10250"
      to_port     = "10250"
      type        = "ingress"
      self        = true
    }
}
```

Looks like the first one was included implicitly with https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2353 so we commented it out in our module's IaC.

As per metrics-server documentation the second one is also needed - https://github.com/kubernetes-sigs/metrics-server#requirements

I am more than happy to open a PR for this.

## Describe alternatives you've considered.
I can continue to have the SG rule added with our IaC.

## Additional context
N/A

**Comment by bryantbiggs** [comment]
I believe we already cover the 2nd rule, but please feel free to open a PR for the first rule to be added to the recommended security group rules

**Comment by AndreiBanaruTakeda** [comment]
You cover just the first one - https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf#L119

**Comment by bryantbiggs** [comment]
ah, overlooked that one. We cover the first one in https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0e3cb9a0afcea87e1da0c87ecc969ffb963619ea/node_groups.tf#L110-L117 so by all accounts, there shouldn't be any changes required, no?

**Comment by AndreiBanaruTakeda** [comment]
Agreed, looks like you added that in release 19.0, excellent. I will go ahead and remove it from our own module.
