### ISSUE TITLE
Unable to use cni-metric-helper with default configuration

### ISSUE THREAD

**Issue by csantanapr** [terraform-aws-modules/terraform-aws-eks#2394]
## Description

I'm unable to use the [cni-metric-helper](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cmd/cni-metrics-helper/README.md] 

The default config for security group ingress rule doesn't allow port 61678 from cluster to node

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Reproduction Code [Required]

Install eks cluster with default config
Install cni-metric-helper following instructions https://github.com/terraform-aws-modules/terraform-aws-eks/

In my case the cni-metric-helper was not able to communicate and printed the following logs
```
Failed to grab CNI endpoint: the server is currently unable to handle the request (get pods aws-node-ktpbn:61678)"}
Failed to grab CNI endpoint: the server is currently unable to handle the request (get pods aws-node-4tjv5:61678)"}
```

## Expected behavior

To be able to get metrics from vpc-cni ip address allocations

## Actual behavior

I can't get metrics

## Additional context

Issue to add more docs about this requirement https://github.com/aws/amazon-vpc-cni-k8s/issues/2208

I was able to fix the problem by adding a security group ingress rule to allow inbound to nodes from cluster for port tcp 61678

I think the code to update to fix is located here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf#L74-L106

**Comment by bryantbiggs** [comment]
please see comment here https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2395#discussion_r1069400312

At this time, we will not be adding this to the recommended security group rules
