### ISSUE TITLE
kube-proxy doesn't exist in the latest AWS worker node AMI

### ISSUE THREAD

**Issue by smalltown** [terraform-aws-modules/terraform-aws-eks#24]
# I have issues

## I'm submitting a

* [ ] bug report

## What is the current behavior
kube-proxy doesn't exist in the latest AWS worker node AMI, but the userdata teamplate try to restart it, that will encounter error as below

```
Failed to restart kube-proxy.service: Unit not found.
```

## What's the expected behavior
Remove the kube-proxy from restart step

**Comment by brandoconnor** [comment]
Merged with #26. Thanks for putting this together!
