### ISSUE TITLE
Terraform is trying to force_replacement the Managed Node Group while doing EKS version upgrade

### ISSUE THREAD

**Issue by shivakumar5** [terraform-aws-modules/terraform-aws-eks#2400]
## Description

When upgrading from 1.21 to 1.22 we want to make sure that the upgrades on the node group happen in a rolling fashion. 
But what we noticed is any changes to the aws_eks_node_group resource is destroying existing nodegroup and recreating a new node group. so that there is a downtime and new nodes are not provisioned in a rolling fashion.

How to upgrade EKS managed nodegroup without recreating it ?

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: N/A

- Terraform version: 1.2.6

- Provider version(s): v4

## Reproduction Code [Required]

* Update EKS Nodegroup Version to 1.22 in terraform code

## Expected behavior

Terraform should allow to do rolling update without recreating nodegroups

## Actual behavior

Terraform creating new nodegroup and deleting old nodegroup 

### Terminal Output Screenshot(s)

```hcl
# aws_eks_node_group.eks_managed_node_groups["dogfood"] must be replaced
+/- resource "aws_eks_node_group" "eks_managed_node_groups" {
      ~ arn                    = "arn:aws:eks:us-east-1::nodegroup/gp-dev-na-0-dogfood-1-21-202301090[61]()33908710000000d/6ac2ca94-dfb9-3d87-e1b4-33433dc8fff7" -> (known after apply)
      ~ capacity_type          = "ON_DEMAND" -> (known after apply)
      ~ disk_size              = 20 -> (known after apply)
      ~ id                     = "gp-dev-na-0:gp-dev-na-0-dogfood-1-21-2023010906133908710000000d" -> (known after apply)
      ~ node_group_name        = "gp-dev-na-0-dogfood-1-21-2023010906133908710000000d" -> (known after apply)
      ~ node_group_name_prefix = "gp-dev-na-0-dogfood-1-21-" -> "gp-dev-na-0-dogfood-1-22-" # forces replacement
      ~ release_version        = "1.11.1-104f8e0f" -> (known after apply)
      ~ resources              = [
          - {
              - autoscaling_groups              = [
                  - {
                      - name = "eks-gp-dev-na-0-dogfood-1-21-2023010906133908710000000d-6ac2ca94-dfb9-3d87-e1b4-33433dc8fff7"
                    },
                ]
              - remote_access_security_group_id = ""
            },
        ] -> (known after apply)
      ~ status                 = "ACTIVE" -> (known after apply)
        tags                   = {
            "tenant" = "dogfood"
        }
      ~ version                = "1.21" -> "1.22"
        # (8 unchanged attributes hidden)

      ~ update_config {
          ~ max_unavailable            = 1 -> (known after apply)
          ~ max_unavailable_percentage = 0 -> (known after apply)
        }

        # (2 unchanged blocks hidden)
    }
```

**Comment by bryantbiggs** [comment]
this is because you have tied the Kubernetes version into the name of the node group
`~ node_group_name_prefix = "gp-dev-na-0-dogfood-1-21-" -> "gp-dev-na-0-dogfood-1-22-" # forces replacement`

I would recommend that you avoid this unless you are doing blue/green upgrades of node groups

**Comment by shivakumar5** [comment]
Thank you so much @bryantbiggs , that helped me a lot!
Silly me, Removed version from name fixed the issue :)
