### ISSUE TITLE
Addons version not updated with EKS upgrade

### ISSUE THREAD

**Issue by rr-krupesh-savaliya** [terraform-aws-modules/terraform-aws-eks#2401]
## Description

The Addon version is not showing to update with the latest EKS version if the addon was already created previously.
Also, the `most_recent=true` flag not working as well. It always returns the default version.

## Versions

- Module version: `18.30.3`

- Terraform version: `1.3.5`

- Provider version(s): 
- aws: `4.49.0`

1. Add add-ons at EKS version `1.22` or `1.23`
2. Upgrade the EKS cluster with the next upgrade `1.23` or `1.24`
3. During or after the upgrade it's not showing the change related to the latest add-ons versions

## Expected behavior

- It must be updated add-ons version to the latest with the cluster upgrade

## Actual behavior

- It's not updating add-ons with cluster upgrades also, the `most_recent=true` flag does not return the latest version of the addon.

**Comment by bryantbiggs** [comment]
this behavior is only available within v19 of the module

**Comment by rr-krupesh-savaliya** [comment]
can we patch this change to 18.X?

**Comment by bryantbiggs** [comment]
no - the data source didn't come available until v4 of the provider which means going from the v3 AWS provider to v4 is a breaking change
