### ISSUE TITLE
Option to prevent KMS key deletion using lifecycle prevent_destroy = true

### ISSUE THREAD

**Issue by atheiman** [terraform-aws-modules/terraform-aws-eks#2402]
## Is your request related to a problem? Please describe.
Need to be able to prevent scheduling KMS key deletion. Our AWS account has a Service Control Policy which denies scheduling KMS key deletion for security and compliance safety reasons - this action can only be done by a security admin, not by our role which creates / deletes EKS clusters.

## Describe the solution you'd like.
- Add a new input `disable_kms_key_deletion` which will add [`lifecycle.prevent_destroy = true`](https://developer.hashicorp.com/terraform/tutorials/state/resource-lifecycle#prevent-resource-deletion) to any KMS key created by the module.

## Describe alternatives you've considered.
- When specifying `kms_key_deletion_window_in_days = 0`, `lifecycle.prevent_destroy = true` is added to any KMS key created by the module.

**Comment by bryantbiggs** [comment]
> Add a new input disable_kms_key_deletion which will add [lifecycle.prevent_destroy = true](https://developer.hashicorp.com/terraform/tutorials/state/resource-lifecycle#prevent-resource-deletion) to any KMS key created by the module.

Terraform does not support variables within lifecycle blocks so this won't be something that can be supported. Instead, users can bring their own keys, instead of using the one created by the module, if they so choose
