### ISSUE TITLE
Can't add gp2 volume type to eks_managed_node_groups

### ISSUE THREAD

**Issue by inemyrovsk** [terraform-aws-modules/terraform-aws-eks#2403]
I am using 19.5.1 version of eks module and I  am not able to add gp2 volume to nodes here is the configuration of terragrunt which I use:

```
eks_managed_node_groups = {
    test = {
      min_size     = **
      max_size     = **
      desired_size = **

      use_custom_launch_template = true
      launch_template_name   = "test"
      instance_types = ["***"]
      capacity_type  = "SPOT"
      iam_role_additional_policies = {
          additional = "***"
        }

      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 50
            volume_type           = "gp2"
            iops                  = 0
            throughput            = 125
            encrypted             = false
            delete_on_termination = true
          }
        }
      }

      labels = {
        purpose = "test-env-apps"
        environment = "test"
      }

    }
```

I have tried different divice_name but every fails with error:
InvalidRequestException: throughput cannot be specified with the volumeType of device /dev/xvda

Also, removing throughput doesn't work, it says:
   throughput parameter is not valid

How can I assign gp2 volumes to eks_managed_node_groups ?

**Comment by lordz-ei** [comment]
Worked for me with the following
`eks_managed_node_groups = {
    k8stest = {
      min_size     = 1
      max_size     = 2
      desired_size = 2

      use_custom_launch_template = true
      launch_template_name   = "k8stest-lt"
      capacity_type  = "ON_DEMAND"
      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 30
            volume_type           = "gp2"
            encrypted             = true
            delete_on_termination = true
          }
        }
      }
    }
  }`

Though it set's disk size to 20 GB no matter what.
