### ISSUE TITLE
AWS Module Performs Lookup on allowed null variable "iam_role_additional_policies"

### ISSUE THREAD

**Issue by cpumanaz** [terraform-aws-modules/terraform-aws-eks#2405]
There is no requirement for a value on the AWS module, or the `self-managed-node-group` This line expects to process a variable. This results in the following error.

```
│ Error: Invalid value for input variable
│ 
│   on .terraform/modules/eks.eks/node_groups.tf line 336, in module "eks_managed_node_group":
│  336:   iam_role_additional_policies = lookup(each.value, "iam_role_additional_policies", lookup(var.eks_managed_node_group_defaults, "iam_role_additional_policies", {}))
```

`modules/eks-managed-node-group/variables.tf:461,1-40: map of string required.`

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0e3cb9a0afcea87e1da0c87ecc969ffb963619ea/node_groups.tf#L336

@bryantbiggs When you developed this change, did you test it against this type of input where `iam_role_additional_policies` is undefined?

```
  eks_managed_node_group_defaults = {
  }
```

**Comment by bryantbiggs** [comment]
yes, I did - see the examples
