### ISSUE TITLE
Cannot remove 0.0.0.0/0 from public_access_cidrs

### ISSUE THREAD

**Issue by daugustus** [terraform-aws-modules/terraform-aws-eks#2410]
## Description

To restrict access to the EKS API, we have added our VPN endpoints to the public_access_cidrs. But when we apply the code, the resource still has the 0.0.0.0/0 entry, in addition to our VPN endpoints. If we delete the 0.0.0.0/0 entry manually, Terraform wants to add it back.  Our CIDRs are not touched.

- [X ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.50.0
+ provider registry.terraform.io/hashicorp/null v3.2.1

## Reproduction Code [Required]

resource "aws_eks_cluster" "eks_cluster" {
  name     = var.eks_name
  role_arn = var.eks_role
  version  = var.eks_version

  enabled_cluster_log_types = var.log_types

  vpc_config {
    security_group_ids = [module.eks_cluster_sg.security_group_id]
    subnet_ids = "redacted subnet ids"
    public_access_cidrs     = ['redacted Cidr 1', 'redacted Cidr 2']
    endpoint_private_access = true
    endpoint_public_access = true
  }
}

no workspaces

local cache cleared

normal maintenance

## Expected behavior
The Cidrs I specify should REPLACE the existing Cidrs

## Actual behavior

After applying code,  only the cirds I specify should exist but 0.0.0.0/0 is still listed

**Comment by bryantbiggs** [comment]
this is not a restriction implemented by the module, we did try to remove this when v19 was released but its not supported by upstream at this time - https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2320
