### ISSUE TITLE
Error: Invalid for_each argument for  eks_managed_node_group (create_iam_role = false)

### ISSUE THREAD

**Issue by VivienMoretto87** [terraform-aws-modules/terraform-aws-eks#2411]
## Description

When I try to create a new node_group eks with eks_managed_node_group (outside of the eks module ), when I apply the code : Terraform send me the following error : 

╷
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/airflow_k8s.eks_managed_node_group/modules/eks-managed-node-group/main.tf line 434, in resource "aws_iam_role_policy_attachment" "this":
│  434:   for_each = { for k, v in toset(compact([
│  435:     "${local.iam_role_policy_prefix}/AmazonEKSWorkerNodePolicy",
│  436:     "${local.iam_role_policy_prefix}/AmazonEC2ContainerRegistryReadOnly",
│  437:     var.iam_role_attach_cni_policy ? local.cni_policy : "",
│  438:   ])) : k => v if var.create && var.create_iam_role }
│     ├────────────────
│     │ local.cni_policy is a string, known only after apply
│     │ local.iam_role_policy_prefix is a string, known only after apply
│     │ var.create is true
│     │ var.create_iam_role is false
│     │ var.iam_role_attach_cni_policy is true
│ 
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform
│ cannot determine the full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place
│ apply-time results only in the map values.
│ 
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends
│ on, and then apply a second time to fully converge.
  

## Versions

- Module version : 19.5.1

- Terraform version: v1.3.7

- Provider version(s):
 registry.terraform.io/hashicorp/aws  : 4.50.0
## Reproduction Code [Required]

module "eks_managed_node_group" {
  source = "terraform-aws-modules/eks/aws//modules/eks-managed-node-group"
  version = "19.5.1"

  name            = "eks-ng_example"
  cluster_name    = "cluster_name"
  cluster_version = "1.24"

  subnet_ids = data.terraform_remote_state.network.outputs.private_subnets_ids
  
  cluster_primary_security_group_id = data.terraform_remote_state.k8s.outputs.cluster_primary_security_group_id
  vpc_security_group_ids = [data.terraform_remote_state.k8s.outputs.vpc_security_group_ids]
 
  create_iam_role = false
  iam_role_arn = aws_iam_role.k8s_instance_role.arn
  create_launch_template = false
  launch_template_name = "lchtpl-eks_airflow"
  launch_template_version = "1"
  ami_type = "AL2_x86_64"
 
  instance_types = ["t3.large","t3a.large"]

 }

terraform init
terraform apply

╷
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/airflow_k8s.eks_managed_node_group/modules/eks-managed-node-group/main.tf line 434, in resource "aws_iam_role_policy_attachment" "this":
│  434:   for_each = { for k, v in toset(compact([
│  435:     "${local.iam_role_policy_prefix}/AmazonEKSWorkerNodePolicy",
│  436:     "${local.iam_role_policy_prefix}/AmazonEC2ContainerRegistryReadOnly",
│  437:     var.iam_role_attach_cni_policy ? local.cni_policy : "",
│  438:   ])) : k => v if var.create && var.create_iam_role }
│     ├────────────────
│     │ local.cni_policy is a string, known only after apply
│     │ local.iam_role_policy_prefix is a string, known only after apply
│     │ var.create is true
│     │ var.create_iam_role is false
│     │ var.iam_role_attach_cni_policy is true
│ 
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform
│ cannot determine the full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place
│ apply-time results only in the map values.
│ 
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends
│ on, and then apply a second time to fully converge.

**Comment by bryantbiggs** [comment]
your reproduction does not match your statement - I suspect you are using a `depends_on` across modules. This should be removed and the issue will subside

**Comment by VivienMoretto87** [comment]
It works with the version 18.31.2 (eks-managed-node-group).
This part of the code have changed when the version 19.x.x arrived.

**Comment by bryantbiggs** [comment]
Closing until you can provide a proper reproduction to help troubleshoot
