### ISSUE TITLE
Error adding cluster_addon to existing cluster

### ISSUE THREAD

**Issue by joshuaganger** [terraform-aws-modules/terraform-aws-eks#2412]
I have an existing 1.24 cluster created by version 19.4.0 of this module and updated to 19.5.1 via Terraform 1.3.7.  I've attempted to add the cert-manager addon by adding the following code to the cluster_addons{} block:
```
cert-manager = {
      resolve_conflicts = "OVERWRITE"
      most_recent = true
      service_account_role_arn = module.cert_manager_irsa.iam_role_arn # in iam.tf
}
```

On terraform plan I receive the following error:

```
│ Error: error reading EKS Add-On version info (cert-manager, 1.24): Empty result
│ 
│   with module.eks.data.aws_eks_addon_version.this["cert-manager"],
│   on .terraform/modules/eks/main.tf line 406, in data "aws_eks_addon_version" "this":
│  406: data "aws_eks_addon_version" "this" {
│ 
╵
```

The empty result seems like it would be correct in the case that the addon has yet to be added to the cluster.  Should it be possible to add an addon to an existing cluster?  Or is it intentional that these are only to be created at the time of cluster creation?

**Comment by bryantbiggs** [comment]
cert-manager is not a supported addon by EKS

**Comment by joshuaganger** [comment]
Well that would explain it.  I was misled by it's presence in the IRSA module.  Thanks,

**Comment by bryantbiggs** [comment]
The IRSA module provides the role and permissions for a number of common tools/services/addons deployed onto EKS - its is not indicative of what is supported natively by EKS as an addon. In fact, most of what is in the IRSA module is reliant on users to provide the service, typically through a Helm chart deployment
