### ISSUE TITLE
Invalid input for iam_role_additional_policies 

### ISSUE THREAD

**Issue by PEGA-NarasimhaRao-Meda** [terraform-aws-modules/terraform-aws-eks#2418]
## Description

Cluster creation failed with latest terraform version and aws provider. It failed with below error.

│ Error: Invalid value for input variable
│ 
│   on .terraform/modules/cluster/node_groups.tf line 336, in module "eks_managed_node_group":
│  336:   iam_role_additional_policies = lookup(each.value, "iam_role_additional_policies", lookup(var.eks_managed_node_group_defaults, "iam_role_additional_policies", {}))
│ 
│ The given value is not suitable for
│ module.cluster.module.eks_managed_node_group["default"].var.iam_role_additional_policies
│ declared at
│ .terraform/modules/cluster/modules/eks-managed-node-group/variables.tf:461,1-40:
│ map of string required.

"I validated the script in variables.tf (https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/eks-managed-node-group/variables.tf#L463), there I could see type as map."

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 19.5.1

- Terraform version: Terraform v1.3.7

- Provider version(s): hashicorp/aws v4.51.0

## Reproduction Code [Required]

Create new script(eks module) for eks managed node group (https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf). Run with latest terraform, module and provider versions.

## Expected behavior

It should be able to create a cluster

## Actual behavior

Provision got failed with input mismatch error

### Terminal Output Screenshot(s)

<img width="1482" alt="Screenshot 2023-01-24 at 10 29 53 PM" src="https://user-images.githubusercontent.com/109585795/214469810-8dbdd068-05bd-4d86-96c3-6c079274121d.png">

**Comment by bryantbiggs** [comment]
we will need to see a reproduction in order to help troubleshoot

**Comment by PEGA-NarasimhaRao-Meda** [comment]
Hello @bryantbiggs 
  
  module "cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "${var.name}"
  cluster_version = "${var.cluster_version}"
  subnet_ids        = "${module.vpc.public_subnets}"

  tags = "${local.tags}"

  vpc_id                 = "${module.vpc.vpc_id}"
  eks_managed_node_groups          = {
    default = var.eks_managed_node_groups_default
  }

  cluster_timeouts = {
    create = "60m"
    delete = "60m"
  }
  enable_irsa = "true"

  eks_managed_node_group_defaults = {
    root_volume_type = "gp2"
    ami_id = data.aws_ami.eks_managed_worker.image_id
  }

  node_security_group_additional_rules = {
    ingress_allow_access_from_control_plane = {
      type = "ingress"
      protocol = "tcp"
      from_port = 9443
      to_port = 9443
      source_cluster_security_group = true
    }
  }

  cluster_addons = {
    aws-ebs-csi-driver = {
      resolve_conflicts = "OVERWRITE"
    }
  }
}

**Comment by PEGA-NarasimhaRao-Meda** [comment]
@bryantbiggs 
Any update on this?

**Comment by PEGA-NarasimhaRao-Meda** [comment]
@bryantbiggs 
FYI: I am able to create cluster with 18.x module version.

**Comment by bryantbiggs** [comment]
I don't know what you are doing from looking at your config - there isn't any node group specified 

I would suggest you go back and look at the examples or even here https://github.com/clowdhaus/eks-reference-architecture/tree/main/eks-managed-node-group for references on how to setup a cluster with the module

**Comment by PEGA-NarasimhaRao-Meda** [comment]
@bryantbiggs 
  I am using below config only. 
  https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v19.5.1/examples/complete/main.tf
  
  Specified eks_managed_node_groups.
   (eks_managed_node_groups = {
default = var.eks_managed_node_groups_default
})

**Comment by bryantbiggs** [comment]
> (eks_managed_node_groups = {
default = var.eks_managed_node_groups_default
})

Is not valid HCL syntax nor does it show what is trying to be created

See https://github.com/bryantbiggs/how-to-create-reproduction

**Comment by PEGA-NarasimhaRao-Meda** [comment]
Hello @bryantbiggs 
My bad. Issue is with my config only. iam_role_additional_policies is specified as list in config instead of map. 
Closing this issue.
Thanks.
