### ISSUE TITLE
Individual Security Group for EKS Node Groups Alternative?

### ISSUE THREAD

**Issue by leba-gd** [terraform-aws-modules/terraform-aws-eks#2424]
Hi Team,

with the update to v19 you removed the possibilty to add security groups to specific (eks-managed) node groups. Apparently, I'm one of the few people who were using the feature in v18 so this is indeed a breaking change for me. 

The docu states that I am supposed to add the SG to the node group by other means. And that's where my question arises from: I currently don't see any possibility to programatically attach the SG to the respective nodes besides using the cli or by manually browsing to the AWS website and doing it there. Is that the intended way to do it now or did I miss something in the terraform files which would allow me to do that? I have the security group set up and manually attaching it to the nodes does apply my ingress rules as expected - I'm just missing the programmatical way to do that with the terraform eks module.

Do you happen to have any insights which could help me out in this regard?

**Comment by bryantbiggs** [comment]
You would create your respective security groups that you wish to use and attach, and then pass them into the nodegroup(s) via [vpc_security_group_ids](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/26c2dffa91f28a891feaa90d417ff428f5342e4e/examples/complete/main.tf#L163)

**Comment by leba-gd** [comment]
That does the trick, thank you very much!

Closing this as solved.
