### ISSUE TITLE
Node Group IAM Role Policy attachment order problem

### ISSUE THREAD

**Issue by 4gsim** [terraform-aws-modules/terraform-aws-eks#2425]
## Description

Sometimes the EKS cluster is not created because the required IAM role policy attachments for the node groups do not exist. This does not happen every time. I am guessing the node group creation should wait for these attachments.

## Versions

- Module version [Required]:

- Terraform version:
1.2.3
- Provider version(s):
18.24.0

## Reproduction Code [Required]

Deploy an EKS cluster with terraform apply.

## Expected behavior

ESK cluster to be deployed

## Actual behavior

Deployment fails with missing IAM role policy attachments.

### Terminal Output Screenshot(s)

module.cluster.module.eks.module.eks_managed_node_group["spots"].aws_security_group.this[0]: Creation complete after 2s [id=sg-017f2dc6013eb3bcd]
module.cluster.module.ebs_csi_driver.kubernetes_service_account.node: Creation complete after 1s [id=kube-system/ebs-csi-node]
module.cluster.module.ebs_csi_driver.kubernetes_cluster_role_binding.node: Creating...
module.cluster.module.ebs_csi_driver.kubernetes_daemonset.node: Creating...
module.cluster.module.ebs_csi_driver.kubernetes_cluster_role_binding.node: Creation complete after 0s [id=ebs-csi-node-getter-binding]
module.cluster.module.ebs_csi_driver.module.ebs_controller_role.aws_iam_role.this[0]: Creation complete after 2s [id=ebs-csi-driver-controller2023012705115584540000000b]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_iam_role.this[0]: Creation complete after 2s [id=ondemands-eks-node-group-20230127051155843900000009]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"]: Creating...
module.cluster.module.ebs_csi_driver.kubernetes_service_account.csi_driver: Creating...
module.cluster.module.ebs_csi_driver.module.ebs_controller_role.aws_iam_role_policy_attachment.custom[0]: Creating...
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"]: Creating...
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"]: Creating...
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"]: Creating...
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Creating...
module.cluster.module.eks.module.eks_managed_node_group["spots"].aws_iam_role.this[0]: Creation complete after 2s [id=spots-eks-node-group-2023012705115584530000000a]
module.cluster.module.eks.module.eks_managed_node_group["spots"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"]: Creating...
module.cluster.module.eks.module.eks_managed_node_group["spots"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"]: Creating...
module.cluster.module.ebs_csi_driver.kubernetes_daemonset.node: Creation complete after 0s [id=kube-system/ebs-csi-node]
module.cluster.module.eks.module.eks_managed_node_group["spots"].aws_eks_node_group.this[0]: Creating...
module.cluster.module.ebs_csi_driver.kubernetes_service_account.csi_driver: Creation complete after 0s [id=kube-system/ebs-csi-controller]
module.cluster.module.eks.module.eks_managed_node_group["spots"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"]: Creating...
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"]: Creation complete after 1s [id=ondemands-eks-node-group-20230127051155843900000009-20230127051158243400000010]
module.cluster.module.eks.module.eks_managed_node_group["spots"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"]: Creation complete after 1s [id=spots-eks-node-group-2023012705115584530000000a-20230127051158247700000011]
module.cluster.module.eks.module.eks_managed_node_group["spots"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"]: Creating...
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"]: Creation complete after 1s [id=ondemands-eks-node-group-20230127051155843900000009-20230127051158251700000012]
module.cluster.module.ebs_csi_driver.kubernetes_cluster_role_binding.attacher: Creating...
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"]: Creation complete after 1s [id=ondemands-eks-node-group-20230127051155843900000009-20230127051158255800000016]
module.cluster.module.ebs_csi_driver.kubernetes_cluster_role_binding.provisioner: Creating...
module.cluster.module.eks.module.eks_managed_node_group["spots"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"]: Creation complete after 1s [id=spots-eks-node-group-2023012705115584530000000a-20230127051158253900000013]
module.cluster.module.ebs_csi_driver.module.ebs_controller_role.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=ebs-csi-driver-controller2023012705115584540000000b-20230127051158254500000014]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"]: Creation complete after 1s [id=ondemands-eks-node-group-20230127051155843900000009-20230127051158255300000015]
module.cluster.module.ebs_csi_driver.kubernetes_cluster_role_binding.resizer[0]: Creating...
module.cluster.module.ebs_csi_driver.kubernetes_cluster_role_binding.attacher: Creation complete after 0s [id=ebs-csi-attacher-binding]
module.cluster.module.ebs_csi_driver.kubernetes_cluster_role_binding.provisioner: Creation complete after 0s [id=ebs-csi-provisioner-binding]
module.cluster.module.ebs_csi_driver.kubernetes_cluster_role_binding.resizer[0]: Creation complete after 0s [id=ebs-csi-resizer-binding]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Creating...
module.cluster.module.eks.module.eks_managed_node_group["spots"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"]: Creation complete after 1s [id=spots-eks-node-group-2023012705115584530000000a-20230127051158851900000017]
module.cluster.module.eks.module.eks_managed_node_group["spots"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"]: Creation complete after 0s [id=spots-eks-node-group-2023012705115584530000000a-20230127051159035500000018]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [10s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [10s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [20s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [20s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [30s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [30s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [40s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [40s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [50s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [50s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [1m0s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [1m0s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [1m10s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [1m10s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [1m20s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [1m20s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [1m30s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [1m30s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [1m40s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [1m40s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [1m50s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [1m50s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [2m0s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [2m0s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [2m10s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Still creating... [2m10s elapsed]
module.cluster.module.ebs_csi_driver.kubernetes_deployment.ebs_csi_controller: Creation complete after 2m16s [id=kube-system/ebs-csi-controller]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Still creating... [2m20s elapsed]
module.cluster.module.eks.module.eks_managed_node_group["ondemands"].aws_eks_node_group.this[0]: Creation complete after 2m29s [id=test-cluster:ondemands-2023012705115783740000000c]

│ Warning: Redundant ignore_changes element
│ 
│   on .terraform/modules/cluster.eks/main.tf line 305, in resource "aws_eks_addon" "this":
│  305: resource "aws_eks_addon" "this" {
│ 
│ Adding an attribute name to ignore_changes tells Terraform to ignore future
│ changes to the argument in configuration after the object has been created,
│ retaining the value originally configured.
│ 
│ The attribute modified_at is decided by the provider alone and therefore
│ there can be no configured value to compare with. Including this attribute
│ in ignore_changes has no effect. Remove the attribute from ignore_changes
│ to quiet this warning.

│ Error: error creating EKS Node Group (test-cluster:spots-2023012705115789640000000e): InvalidParameterException: The provided role doesn't have the Amazon EKS Managed Policies associated with it. Please ensure the following policies [arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy, arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly] are attached

**Comment by bryantbiggs** [comment]
1. Its virtually impossible to tell whats happening without a reproduction
2. It looks like you are using version v18.x - the project is now on v19.x which handles permissions differently
