### ISSUE TITLE
Terraform apply fails with error GET https://**.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 10.x.x.147:443: i/o timeout

### ISSUE THREAD

**Issue by rajkumar501** [terraform-aws-modules/terraform-aws-eks#2426]
## Description
Terraform apply fails with error GET https://**.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 10.x.x.147:443: i/o timeout

** Vefified
If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 8.0.0

- Terraform version: 0.13.7

- Provider version(s):  "~> 1.10"

## Reproduction Code [Required]

Versions:  k8 V1.21 , Module V8.0.0
Cluster.tf :
```
data "aws_eks_cluster" "cluster" {
  name = module.eks-cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks-cluster.cluster_id
}

provider "kubernetes" {
  host                              = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate            = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                             = data.aws_eks_cluster_auth.cluster.token
  load_config_file                  = false
  version                           = "~> 1.10"
}

module "eks-cluster" {
  source                            = "terraform-aws-modules/eks/aws"
  version                           = "8.0.0"
  cluster_name                      = var.eks_cluster_name
  cluster_version                   = var.eks_cluster_version
  subnets                           = var.subnet_id
  vpc_id                            = var.vpc_id
  cluster_enabled_log_types         = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
  manage_worker_autoscaling_policy  = true
  attach_worker_autoscaling_policy  = true
  tags                              = local.required_tags
  manage_aws_auth=true
  cluster_endpoint_private_access   = var.private_only_cluster == true ? true : false
  cluster_endpoint_public_access    = var.private_only_cluster == true ? false : false
  map_roles = [
    {
      rolearn = var.sso_role
      username = "admin"
      groups    = ["system:masters"]
    },
  ]

  map_users = [
    {
      userarn = var.jenkins_arn
      username = "svc-admin"
      groups    = ["system:masters"]
    },
    {
      userarn = var.admin_arn
      username = "application-admin"
      groups    = ["system:masters"]
    },
  ]

  worker_groups_launch_template = [
    {
      instance_type                = var.instance_sku
      asg_desired_capacity         = "3"
      asg_min_size                 = "1"
      asg_max_size                 = "6"
      ami_type                     = "AL2_x86_64"
      key_name                     = var.ssh_key
      tags = [
        {
          "key"                 = "k8s.io/cluster-autoscaler/enabled"
          "propagate_at_launch" = true
          "value"               = "true"
        },
        {
          "key"                 = "k8s.io/cluster-autoscaler/${var.eks_cluster_name}"
          "propagate_at_launch" = true
          "value"               = "owned"
        }
      ]
    }
  ]
}


```

 yes
 yes

* Enable EKS cluster private accessEndpoint
* Run terraform plan/apply after Private Endpoint successfully enabled
* Terraform creates the cluster fine with public endpoint  and works as expected but after updating the following block to enable private endpoint
```  cluster_endpoint_private_access   = var.private_only_cluster == true ? true : false
           cluster_endpoint_public_access    = var.private_only_cluster == true ? false : false
```

## Expected behavior

* Plan and apply stages are executed without any issues

## Actual behavior

Plan/apply fails with following behavior:

* Terraform apply fails :
```
Error: Get "https://*.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 10.x.x.147:443: i/o timeout


Operation failed: failed running terraform plan (exit 1)
```

## Additional context
##Verified ``aws-auth`` exists in cluster
##Works as expected with v7.0.1 module

**Comment by bryantbiggs** [comment]
I'm not sure how much help I can provide - the module is currently on v19.x and it looks like you are quite a bit behind at v8.x

**Comment by rajkumar501** [comment]
@bryantbiggs  ,  yeah unfortunately we are still in use of v8.0.0 so kindly suggest if an upgrade is the only possible way will go ahead with it and will check it out , Thanks
