### ISSUE TITLE
key_arn gives error when external kms key used for cluster encryption config

### ISSUE THREAD

**Issue by ib-ak** [terraform-aws-modules/terraform-aws-eks#2429]
## Description

```
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/eks/main.tf line 67, in resource "aws_eks_cluster" "this":
│   67:         key_arn = var.create_kms_key ? module.kms.key_arn : encryption_config.value.provider_key_arn
│     ├────────────────
│     │ module.kms.key_arn is null
│     │ var.create_kms_key is false
│ 
│ Inappropriate value for attribute "key_arn": string required.

```

```
$ tf version
Terraform v1.3.7
on darwin_amd64
```
If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: "19.6.0"

- Terraform version: 1.3.7

- Provider version(s):
aws v4.52.0 

## Reproduction Code [Required]
Same as complete example with external kms

 no
 yes
 updated the module from 18 to 19
cluster_encryption_config = removed brackets. resources and key was present from beginning. create_kms_key was set to false

## Expected behavior

no error

## Actual behavior

│ Inappropriate value for attribute "key_arn": string required.

### Terminal Output Screenshot(s)

attached above

**Comment by ib-ak** [comment]
should nt both conditional results should be string ?

**Comment by bryantbiggs** [comment]
> should nt both conditional results be strings ?
No clue, can't see what your code is or what you are trying to do

**Comment by ib-ak** [comment]
> > should nt both conditional results be strings ?
> 
> No clue, can't see what your code is or what you are trying to do



i am setting same values as complete example.

```
create_kms_key                             = false
cluster_encryption_config = {
    provider_key_arn = module.kms.key_arn
    resources        = ["secrets"]
  }
```

**Comment by bryantbiggs** [comment]
https://github.com/bryantbiggs/how-to-create-reproduction

**Comment by ib-ak** [comment]
https://github.com/bryantbiggs/how-to-create-reproduction/compare/main...ib-ak:how-to-create-reproduction:main?diff=split

**Comment by ib-ak** [comment]
my state file got messde up. Thats why the issue. Thanks for looking into it. We can close the issue.
