### ISSUE TITLE
Feature request: support for supplying custom launch configuration 

### ISSUE THREAD

**Issue by maxenglander** [terraform-aws-modules/terraform-aws-eks#244]
# I have issues

I would like to be able to do custom things to the worker launch configuration, like attach EBS volumes. In response to a discussion with @max-rocket-internet on [my current PR](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/236) for adding EBS volumes (see #233), I am opening a new ticket as a proposal for an alternate approach: supplying a user-defined launch configuration template in `worker_groups`.

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Currently, this module takes responsibility for creating a new launch configuration for the worker ASG. This is great, but certain things do not fit into the current model for defining worker groups, e.g. adding EBS volumes. There is [an open PR](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/236) which adds support for EBS volumes to this modules launch configuration, but it is rather inelegant and causes a fair amount of duplication.

## Are you able to fix this problem and submit a PR? Link here if you have already.

I plan to submit a PR which will make it possible for users to supply a custom launch configuration template in the `worker_groups` config block.

**Comment by max-rocket-internet** [comment]
Awesome idea, Max! I'm surprised this hasn't come up earlier to be honest.

**Comment by maxenglander** [comment]
Well wish I could take credit :)

**Comment by maxenglander** [comment]
My team decided to address our issue (need to attach EBS volumes to worker nodes) by setting `worker_group_count` to zero, and managing the ASG and LC config outside of this module. We looked at supplying a custom launch configuration parameter, but doing so would have required us to also manage IAM roles and profiles, and security groups. We don't need this issue anymore, so closing out.

**Comment by max-rocket-internet** [comment]
OK fair enough.
