### ISSUE TITLE
EKS managed node group ignores `disk_size` input

### ISSUE THREAD

**Issue by azend** [terraform-aws-modules/terraform-aws-eks#2441]
## Description

While using the example for defining an EKS managed node group, my team noticed that the option for `disk_input` does not effect change within resources of the EKS module. Upon further inspection, it's clear that `disk_size` is not used at all. 

Example: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/ece82472a62d7674b10261701bc1ec697988638f/examples/eks_managed_node_group/main.tf#L102

The only line using `disk_size` inside the `eks_managed_node_group` module is https://github.com/terraform-aws-modules/terraform-aws-eks/blob/094ed1d5e461552a0a76bc019c36690fe0fc2dd5/modules/eks-managed-node-group/main.tf#L332 which doesn't specify a disk size unless you specify that you're using a custom launch template. The example provided sets `use_custom_launch_template` to false so the example itself would fail to set disk size choosing to ignore it instead.

Current resolution: 
Use `volume_size` as part of the `block_device_mappings` to control disk size.
```hcl
  # EKS Managed Node Group(s)
  eks_managed_node_group_defaults = {
    block_device_mappings = {
      xvda = {
        device_name = "/dev/xvda"
        ebs = {
          volume_size           = 50 # default is 20
        }
      }
    }
  }
  ```

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: v19.6.0

- Terraform version:
```
Terraform v1.3.5
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html
```
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v4.40.0
```

## Reproduction Code [Required]

Use the provided example

Plan the provided example

## Expected behavior

Disk size on the managed node groups should be effected with the change set by `disk_size`.

## Actual behavior

No change to resources and defaults prevail.

**Comment by pagey101** [comment]
I have also noticed this (version 19.5.1)

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/4b7fe4637a048a52422ee04d6146136f48900695/examples/eks_managed_node_group/main.tf#L97-L109

**Comment by bryantbiggs** [comment]
Apologies - wrong link
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/4b7fe4637a048a52422ee04d6146136f48900695/modules/eks-managed-node-group/README.md?plain=1#L22-L31

`disk_size` and `remote_access` are only available  when using the EKS managed node group default template. This module defaults to creating a custom launch template to give users control over the security groups used, tags, etc.

**Comment by cheddarwhizzy** [comment]
Seems as though if we want to set a custom disk_size and ami_id, setting `use_custom_launch_template = false` will only allow disk_size. If `use_custom_launch_template = true`, I can set ami_id but not disk_size..
