### ISSUE TITLE
Don't depracate aws_auth_configmap_yaml please 

### ISSUE THREAD

**Issue by omerlh** [terraform-aws-modules/terraform-aws-eks#2442]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

No

## Is your request related to a problem? Please describe.

Today we manage aws auth confimap using this module, and it's a bit messy - the cluster is not accessible from the internet, making CI/CD for terraform a bit of a challenge. We are considering to move the auth map to be managed via gitops, so using `aws_auth_configmap_yaml` allows us to export it as file and commit it somewhere. 

What is the reason for deprecating it? 

## Describe the solution you'd like.

Use terraform to create a file and commit it to git with the config file data. We can wrap it with config map structure, just need to actual mapping. Due to this [problem](https://discuss.hashicorp.com/t/accessing-nested-output-object-from-a-module/49543), and the fact I'm using CDKTF, it's pretty hard to do it manually be extracting the role from the node group.

## Describe alternatives you've considered.

Replicating the code in this module and building the map ourselves.

**Comment by bryantbiggs** [comment]
when https://github.com/aws/containers-roadmap/issues/185#issuecomment-1234850299 is in place, it will be removed since its no longer used/required
