### ISSUE TITLE
Support instances with different architecture (x86_64 and AArch64 [Graviton]) in the same Auto Scaling Group

### ISSUE THREAD

**Issue by nemoforum** [terraform-aws-modules/terraform-aws-eks#2444]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: 3.30.0 https://github.com/hashicorp/terraform-provider-aws/blob/release/3.x/CHANGELOG.md#3300-february-26-2021
  https://github.com/hashicorp/terraform-provider-aws/pull/16325

## Is your request related to a problem? Please describe.
No

## Describe the solution you'd like.
An ability to specify instances with different architecture (x86_64 and AArch64 [Graviton]) in the same ASG (mixed instance policy, self-managed ASG).
The module should check the architectures of specified instances and create a launch template with an appropriate AMI per architecture.

## Describe alternatives you've considered.
-

## Additional context
https://aws.amazon.com/blogs/compute/supporting-aws-graviton2-and-x86-instance-types-in-the-same-auto-scaling-group/
The usage of Fleets with mixed instance architecture allows to save costs.

**Comment by bryantbiggs** [comment]
this is supported today

**Comment by nemoforum** [comment]
@bryantbiggs , excuse me, where is it supported?
What I can see, is that only one launch template is being created https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/self-managed-node-group/main.tf#L47 and only one AMI is being specified https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/self-managed-node-group/main.tf#L4 .
While ASG with mixed arch instances requires multiple launch templates (1 per arch) with different AMIs. For example, for AArch64 it looks like this:
`data "aws_ami" "eks_default" {
  filter {
    name   = "name"
    values = ["amazon-eks-arm64-node-${var.cluster_version}-v*"]
  }

  most_recent = true
  owners      = ["amazon"]
}`

**Comment by bryantbiggs** [comment]
it is supported because we do support mixed-instances policy https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a8e0de0b3f3a3e27232b35e9ed8814549273bced/modules/self-managed-node-group/main.tf#L467

> Moreover, the module will not work with Graviton ASG at all without specifying AArch64 (arm64) AMI manually.

What is manual vs what is not? You have to provide configuration - I don't see how that could be "automated" or inferred in some way
