### ISSUE TITLE
Launch Template for Node Groups Cause Connectivity Issues

### ISSUE THREAD

**Issue by hilafish** [terraform-aws-modules/terraform-aws-eks#2447]
- Not sure if I'm the one who supposed to label it as a question or not, couldn't find how to do it if it's on me, sorry.
- [X] ✋ I have searched the open/closed issues and my issue is not listed.
- Not even sure it's ok to ask here, as Terraform gets executed ok, but I don't know how else to troubleshoot this, so hopefully you could help.

## Versions
- Module version [Required]: "~> 18.0"
- Terraform version: v1.3.5

Provider version(s):
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.41.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/http v3.2.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/taiidani/jenkins v0.10.0

## Issue Description:

I have EKS that I've installed Jenkins on it.
With the code that works (no launch template), Jenkins job runs ok.
With the code that doesn't work (launch template creation - I need to run a script on the nodes, for now I've put just an echo in the script to eliminate the issue is with the script's content), the Jenkins job fails on a pip install phase-
```
Installing pip dependencies: ...working... Cannot contact jenkins-agent-cpu-j149c: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@5a343fa7:JNLP4-connect connection from 10.207.84.202/10.207.84.202:35866": Remote call on JNLP4-connect connection from 10.207.84.202/10.207.84.202:35866 failed. The channel is closing down or has closed down
Agent jenkins-agent-cpu-j149c was deleted; cancelling node body
Could not connect to jenkins-agent-cpu-j149c to send interrupt signal to process
```

## Reproduction Code [Required]

Not working-

```
eks_managed_node_group_defaults = {

    enable_bootstrap_user_data = true
    post_bootstrap_user_data = <<-EOT
      MIME-Version: 1.0
      Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

      --==MYBOUNDARY==
      Content-Type: text/x-shellscript; charset="us-ascii"

      #!/bin/bash
      echo "nothing to do"  ## as you can see it’s just a dummy to test functionality 

      --==MYBOUNDARY==--    
    EOT  
    …..
    …..
}


  eks_managed_node_groups = {
    ci-master = {  …. }
    ci-worker = { …. }
}
```
--------

Working-
```
  eks_managed_node_groups = {
    ci-master = {  
      ….
      create_launch_template = false
      launch_template_name   = ""   
   }
    ci-worker = {
      ….
      create_launch_template = false
      launch_template_name   = ""   
   }
}
```
--------

set up the cluster with the non working code- a.k.a:
* set `enable_bootstrap_user_data = true` 
* set up a script on `post_bootstrap_user_data` or `pre_bootstrap_user_data` (I tried them both, both result with the same issue).
* don't set at all `create_launch_template = false` and `launch_template_name   = ""`
* run the jenkins job. you can't without deploying it, so.. let me know if you need me to check anything else in comparison of working and non working code implementation - I've put below the security settings of the node, if there's anything else to compare, let me know. 

## Expected behavior

The Jenkins job should work ok.

## Actual behavior

Jenkins job fails with the error-
```
Installing pip dependencies: ...working... Cannot contact jenkins-agent-cpu-j149c: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@5a343fa7:JNLP4-connect connection from 10.207.84.202/10.207.84.202:35866": Remote call on JNLP4-connect connection from 10.207.84.202/10.207.84.202:35866 failed. The channel is closing down or has closed down
Agent jenkins-agent-cpu-j149c was deleted; cancelling node body
Could not connect to jenkins-agent-cpu-j149c to send interrupt signal to process
```

## Additional context

attaching screenshots of the security settings of the nodes of the node pool

working-
![image 2 - working](https://user-images.githubusercontent.com/46403828/216827745-29d7f136-923b-4d5a-90b1-4f8f359a75c1.png)

not working-
![image 1 - not working](https://user-images.githubusercontent.com/46403828/216827710-af672d45-5937-4011-8c32-8217aaabf266.png)

I've compared the two, if any - the not working one has more rules to allow connectivity, so it should work.

1. I tried to follow the code but I can't see a reason why the security settings would defer once we use a launch template.
2. The root question - Why would the job fail on the connectivity error above while all I did is to create a launch template for the node groups?

Thanks,
Hila

**Comment by bryantbiggs** [comment]
when you use the default launch template created by the EKS managed node group, EKS uses the cluster primary security group on nodes which allows all egress to the public IPv4 internet, and allows all ingress across the security group itself

when you use a custom launch template, you will need to add in the rules your services require since the security group created and attached by this module does not automatically permit ingress across the security group itself by default

**Comment by hilafish** [comment]
Where in the code does it attach the shared node group SG?

and do I really need it if all communications are done via the cluster SG, like in the working example?

**Comment by bryantbiggs** [comment]
> Where in the code does it attach the shared node group SG to each node in the nodegroup? (as seen in the non-working code example).

The code here does not - that is just the default behavior of EKS managed node groups. This is also the default for EKS Fargate profiles; users do not even have the option to control what security group is used on EKS Fargate profiles through the API

**Comment by hilafish** [comment]
OK. It's still not clear to me how the SG attachments are changing when using the launch template option or not, but.. it does seem more something on the AWS layers and not this module.
Anyway, thank you, closing this issue.
