### ISSUE TITLE
Getting error during while upgrading terraform-aws-eks version to 19.5.0.Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused 

### ISSUE THREAD

**Issue by KetkiRayter** [terraform-aws-modules/terraform-aws-eks#2449]
## Description

We are trying to upgrade our terraform-aws-eks version from 8.1.0 to the latest (19.5.0 ). 
While we are working with this upgrade, we are getting an error:
Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused

  with module.eks.kubernetes_config_map.aws_auth[0],
  on .terraform/modules/eks/main.tf line 510, in resource "kubernetes_config_map" "aws_auth":
 510: resource "kubernetes_config_map" "aws_auth" {

2023-02-06T15:49:40.039Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"

This is my provider configuration for kubernetes in main.tf 
provider "kubernetes" {
 host                   = data.aws_eks_cluster.cluster.endpoint
 cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
 token                  = data.aws_eks_cluster_auth.cluster.token
}

data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}

Below are the other providers and their versions.

## Versions
terraform {
  required_version = ">= 1.0"
  backend "s3" {}
  required_providers {
    aws = {
      version = ">= 4.47"
      }
    local = {
      version = ">= 1.4"
      }
    tls = {
      source  = "hashicorp/tls"
      version = ">= 3.0"
    }
    null = { 
      version = ">= 2.1"
      }
    template = {
      version = ">= 2.1"
      }
    random = {
      version = ">= 2.1"
      }
    kubernetes = {
    source  = "hashicorp/kubernetes"
    version = ">= 2.10"
    }
  }
}

We are executing this with the help of jenkins.

**Comment by hariskmohd** [comment]
I think the problem is with the kubernetes provider. Try using exec plugin instead of token.

provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
  }
}

This works for me.

**Comment by bryantbiggs** [comment]
`module.eks.cluster_id` should be looked at - most likely you want `module.eks.cluster_name` unless you are creating a local cluster on Outposts

**Comment by KetkiRayter** [comment]
@hariskmohd Tried using exec plugin as you suggested, but unfortunately still getting the same error. First, could see an error with using client.authentication.k8s.io/v1alpha1 ( please find the screenshot of the error attached)
![image](https://user-images.githubusercontent.com/124601084/217279272-4c1c803b-9503-4696-b7f6-c64886306258.png)

I tried updating it to "client.authentication.k8s.io/v1beta1", still no luck.
![image](https://user-images.githubusercontent.com/124601084/217280037-cf393120-6e8d-4a22-94b2-501ebefab1a1.png)

**Comment by vikaskoppineedi** [comment]
I am getting the same error, when trying to aws-auth configmap.

**Comment by chriskinsman** [comment]
Seeing a similar issue right now.  It is trying to hit localhost instead of the remote resource for some reason

**Comment by nantiferov** [comment]
I had something similar and fixed that by removing configmap from state and recreating it on next apply.
As I remember, nothing bad happened)

**Comment by chriskinsman** [comment]
Got past by using a path to kubeconfig for the kubernetes provider but it wan't to recreate the cluster now without deleting the old cluster so something has been lost.  Will try your option @nantiferov

**Comment by chriskinsman** [comment]
@nantiferov That worked.  Thanks for the idea...

**Comment by artsirgenx** [comment]
same issue
