### ISSUE TITLE
lifecycle management to ignore tags

### ISSUE THREAD

**Issue by ninjadude333** [terraform-aws-modules/terraform-aws-eks#2452]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is available in the AWS provider

## Is your request related to a problem? Please describe.

I have a organization policy that wont allow me to delete tags. I'm usually using lifecycle manager ignore tags to solve this.
is it possible to do that when using the eks module ?
this is the error i'm getting:
```
│ Error: updating tags for IAM Role (ZTDEMO-cluster-cluster-20230207075603138000000007): error untagging resource (ZTDEMO-cluster-cluster-20230207075603138000000007): AccessDenied: User: arn:aws:iam::4444444411:user/xxxx is not authorized to perform: iam:UntagRole on resource: role ZTDEMO-cluster-cluster-20230207075603138000000007 with an explicit deny in a service control policy
│       status code: 403, request id: 9d726c65-e5cf-47cc-a67b-c072f60218c0
│
│   with module.eks.aws_iam_role.this[0],
│   on .terraform/modules/eks/main.tf line 255, in resource "aws_iam_role" "this":
│  255: resource "aws_iam_role" "this" {
```

## Describe the solution you'd like.

A way to add a lifecycle stanza
```
  lifecycle {
    ignore_changes = [tags]
  }
```

## Describe alternatives you've considered.

not using the module :)

**Comment by bryantbiggs** [comment]
this is not possible because lifecycle blocks do not support variables and nearly all users do not want tags to be ignored

**Comment by ninjadude333** [comment]
ok, 10x, any thinkable workaround ?

**Comment by bryantbiggs** [comment]
re-think your SCPs?

**Comment by ninjadude333** [comment]
not in my hands :)

**Comment by bryantbiggs** [comment]
nor mine 😬
