### ISSUE TITLE
nodegroup needs access to kms_key

### ISSUE THREAD

**Issue by cdenneen** [terraform-aws-modules/terraform-aws-eks#2454]
```
module "eks" {
  create_kms_key = true
  eks_managed_node_group = {
    default = {}
  }
}
```
The nodeGroup iam does not have access to the kms key generated.
If you try to apply:

```
module "eks" {
  kms_key_users = module.eks.eks_managed_node_group["default"].iam_role_arn
# or 
  kms_key_users = module.eks.eks_managed_node_group["default"].node_group_arn
}
```
you end up with a cycle dependency.

I tried to pull the nodegroup arn into a "locals" variable but still didn't work.

Right now trying to access the node via SSM breaks because the InstanceProfile can't access the key.

Only other solution I can think of is to create the kms_key outside of the eks module but I am trying to avoid that if possible.

**Comment by cdenneen** [comment]
Ok so trying to do via kms module yielded the same result of cycle: ` Error: Cycle: module.eks.module.eks_managed_node_group.output.node_group_arn (expand),`

```
module "kms" {
  source  = "terraform-aws-modules/kms/aws"
  version = "1.1.0"

  aliases               = ["eks/${local.name}"]
  description           = "${local.name} cluster encryption key"
  enable_default_policy = true
  key_owners            = [
    "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/eksAdmin"
  ]
  key_users             = [
    module.eks.cluster_iam_role_arn,
    # module.eks.eks_managed_node_groups["default"].iam_role_arn # <-- causes cycle
  ]

  tags = local.tags
}
```

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-kms/issues/14#issuecomment-1422498771

**Comment by cdenneen** [comment]
@bryantbiggs this issue has to do with the KMS key created either by eks module or KMS module needs to allow the use of SSM. Currently if you try to connect to node via ssm it complains about not able to access the key.

**Comment by bryantbiggs** [comment]
I disagree - the KMS key created by the module is only used by the EKS cluster for secret encryption, this has no affect on SSM

Your issue is with the key you are creating and passing to the nodegroups/EC2 instances and most likely the permissions provided in that key policy which is outside the scope of this module

**Comment by cdenneen** [comment]
Managed Node Groups are a sub module of this module. Creating a MNG with block device mapping that sets encrypted disks means the instance role needs to decrypt the key? In this case the NodeGroup ARN needs to be added to the kms key_users. 

So there needs to be a way to create a NodeGroup or MNG that can create encrypted blockdevices and allow access to that key from the node groups instance profile role.

**Comment by bryantbiggs** [comment]
yes, and there are various ways to approach this that users are doing this today using this module
