### ISSUE TITLE
Add Karpenter mapRoles

### ISSUE THREAD

**Issue by phuongnt28** [terraform-aws-modules/terraform-aws-eks#2456]
Currently, Karpenter module is available. However, the "**maproles**" in **aws-auth confimap** for Karpenter does not available similar to "**Fargate**" yet. Could you add this feature?

**Comment by bryantbiggs** [comment]
The Karpenter sub-module is not present in the main module - so this is not possible

**Comment by phuongnt28** [comment]
> The Karpenter sub-module is not present in the main module - so this is not possible

Thanks for your response. I think Karpenter is really cool for replacing the auto scaler, hope you will release it in the main module soon.

**Comment by bryantbiggs** [comment]
I don't know that there are any plans to push it into the main module. I think it makes more sense as a sub-module that users can elect to use if they so choose
