### ISSUE TITLE
Workers on 1.10 even when EKS is provisioned as 1.11

### ISSUE THREAD

**Issue by zytek** [terraform-aws-modules/terraform-aws-eks#246]
# I have issues

## I'm submitting a...

* [x] bug report

## What is the current behavior?

Created new cluster, specifying `cluster_version = "1.11"` with two worker groups (using new Launch Templates support).

Provisioned node reports version 1.10.11

This is a problem with ami filter probably.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Create new cluster version `1.11` with at least one worker groups launch template, example:
```
worker_groups_launch_templates = [
    {
      name                   = "r-xlarge-spot"
      instance_type          = "r4.xlarge"
      override_instance_type = "r3.xlarge"

      asg_desired_capacity                     = 1
      asg_max_size                             = 1
      asg_min_size                             = 1
      autoscaling_enabled                      = true
      key_name                                 = "dev"
      on_demand_percentage_above_base_capacity = "0"
      public_ip                                = true
      root_volume_size                         = 50
      spot_instance_pools                      = 1
      spot_instance_pools                      = 2
      subnets                                  = "${join(",", local.subnets)}"
    },
```

## What's the expected behavior?

Node version is in sync with cluster version.

## Are you able to fix this problem and submit a PR? Link here if you have already.

If we identify the issue then probably yes.

## Environment details

* Affected module version: latest
* OS: MacOS
* Terraform version:

```
Terraform v0.11.11
+ provider.aws v1.54.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

## Any other relevant info

Launch Template reports AMI: amazon-eks-node-1.10-v20190109 (ami-0de10c614955da932)

```
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
➜  ~ kubectl get nodes
NAME                                         STATUS    ROLES     AGE       VERSION
ip-10-10-72-147.eu-west-1.compute.internal   Ready     <none>    22h       v1.10.11
```

**Comment by zytek** [comment]
Probably related #214 - as it mentions ami filter issue.
One workaround is to delete default ami and require users to explicitly set it.

**Comment by max-rocket-internet** [comment]
No update and lots of changes in this module since. So I will close be feel free to reopen after testing on latest version of module.
