### ISSUE TITLE
Allow disk_size irrespective of use_custom_launch_template

### ISSUE THREAD

**Issue by brsolomon-deloitte** [terraform-aws-modules/terraform-aws-eks#2464]
As a user of the this module, I want to be able to pass `disk_size` without having to pass `use_custom_launch_template = false`. I don't want to have to resort to `block_device_mappings` just so that I can alter `volume_size` within. There is a reason why `use_custom_launch_template = true` is useful in the first place, and I don't want to disable that behavior just so I can manipulate `disk_size`.

The `eks-managed-node-group` submodule should allow `disk_size` to be used unconditionally - 20 GiB is simply too small for most clusters. At the very least, please provide a more prominent and complete example of using `block_device_mappings`.

**Comment by bryantbiggs** [comment]
and how would that work? `disk_size` is only available on EKS managed node groups when using the default launch template - thats just the AWS API

**Comment by brsolomon-deloitte** [comment]
I would expect that this module would take the user-supplied `disk_size` parameter and template that out as needed to its custom launch template.

**Comment by bryantbiggs** [comment]
I mean, that sounds nice in theory, but not sure how we would even begin to approach something like that in a static configuration language
