### ISSUE TITLE
Ability to set a custom policy name AND separate custom role name for karpenter IRSA

### ISSUE THREAD

**Issue by patrickleet** [terraform-aws-modules/terraform-aws-eks#2465]
## Is your request related to a new offering from AWS?

No

## Is your request related to a problem? Please describe.

I need to be able to set the policy name separately to the role name. You can currently provide a name that is used for the role AND the policy via `irsa_name`, but you can not set a separate name for each. Due to my organization requirements I need to be able to name each of them separately.

## Describe the solution you'd like.

#2480 

## Describe alternatives you've considered.

It's a minor change, and makes sense in this module. I don't want to use a different solution.

**Comment by gwilsonco** [comment]
This would be a useful feature given our org policies.

**Comment by curtisnn** [comment]
Our org requires this type of solution. Would be helpful for us.

**Comment by sabarnath** [comment]
Yes, we too have a strong policy to enforce that every role/policy name should be prefixed with the given value.
So current default naming have violating the policy and automatically get deleted. Kindly approve it.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.10.0 :tada:
