### ISSUE TITLE
Support for "early" cluster_addons (vpc-cni with ENABLE_PREFIX_DELEGATION)

### ISSUE THREAD

**Issue by gw0** [terraform-aws-modules/terraform-aws-eks#2467]
## Is your request related to a new offering from AWS?

Yes

## Is your request related to a problem? Please describe.

As described on [EKS Cluster w/ Prefix Delegation](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/ipv4-prefix-delegation) (https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2155), the `vpc-cni` is a special cluster addon that needs to be configured **before** any EC2 instances (node groups) are created. If you naively apply it [like this but without `vpc_cni_irsa`](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L67-L72), initial nodes have a different configuration than later ones.

The [recommended workaround](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/ipv4-prefix-delegation/main.tf#L82) is to configure the `aws_eks_addon` `vpc-cni` separately without the [the `depends_on` directive](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L397-L401).

## Describe the solution you'd like.

To generalize it seems there are "early" and "normal" `cluster_addons`, some need to be applied before node groups are created other ones after. It would therefore be a trivial change to improve the Terraform module UX by changing the following `depends_on` directive:

- https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L397-L401

By introducing `local.early_cluster_addons = ["vpc-cni"]` and using:
```
  depends_on = contains(local.early_cluster_addons, each.key) ? [] : [
    module.fargate_profile,
    module.eks_managed_node_group,
    module.self_managed_node_group,
  ]
```

Or by introducing an `apply_early` option for `cluster_addons` and using:
```
  depends_on = each.value.apply_early ? [] : [
    module.fargate_profile,
    module.eks_managed_node_group,
    module.self_managed_node_group,
  ]
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.9.0 :tada:
