### ISSUE TITLE
Using bootstrap_extra_args with bottlerocket in managed node group results in creating 2 launch templates and failed creation of managed node group

### ISSUE THREAD

**Issue by Kummerkasten** [terraform-aws-modules/terraform-aws-eks#2472]
## Description

Hi! I am trying to add some bootstrap_extra_args for one of my managed node groups running on bottlerocket. I have read https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/user_data.md and checked the examples folder. I think I configured everything according to the docs but the managed node group can not be created.

- [/] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
version = "18.31.2"
- Terraform version:
v1.3.4
- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v4.54.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.17.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4

## Reproduction Code [Required]

  ```
eks_managed_node_group_defaults = {
    timeouts = {
      create = "10m"
      delete = "20m"
    }
    instance_types = [t3a.medium]
    subnet_ids     = var.vpc_private_subnets
    ami_type = "BOTTLEROCKET_x86_64"
    ami_release_version = "1.12.0-6ef1139f"
    platform = "bottlerocket"

    enable_monitoring = true
    ebs_optimized     = true

    # We are using the IRSA created below for permissions
    # However, we have to deploy with the policy attached FIRST (when creating a fresh cluster)
    # and then turn this off after the cluster/node group is created. Without this initial policy,
    # the VPC CNI fails to assign IPs and nodes cannot join the cluster
    # See https://github.com/aws/containers-roadmap/issues/1666 for more context
    iam_role_attach_cni_policy = true

    iam_role_additional_policies = [
      "arn:aws:iam::aws:policy/AmazonS3FullAccess",
      "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser",
      "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole",
      "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
    ]


    block_device_mappings = {
      xvda = {
        device_name = "/dev/xvda"
        ebs = {
          delete_on_termination = true
          encrypted             = true
          kms_key_id            = aws_kms_key.eks_ebs.arn
          volume_size           = "150"
          volume_type           = "gp3"
        }
      }
    }

    metadata_options = {
      http_endpoint               = "enabled"
      http_tokens                 = "optional"
      http_put_response_hop_limit = 2
    }

    force_update_version = true

    update_config = {
      max_unavailable = 1
    }
  }

  eks_managed_node_groups = {

    default_node_group = {
      name                  = "default"
      use_name_prefix       = true
      create_security_group = false
      max_size              = "1"
      min_size              = "1"

      # By default, the module creates a launch template to ensure tags are propagated to instances, etc.,
      # so we need to disable it to use the default template provided by the AWS EKS managed node group service
      create_launch_template = false
      launch_template_name   = ""

      labels = {
        dedicated = "default"
      }
    }

    gitlab_runner_node_group = {
      name                  =  gitlab-runner
      use_name_prefix       = true
      create_security_group = false
      instance_types        = [t3a.medium]
      max_size              = "1"
      min_size               = "1"
      desired_size         = "1"
         
      bootstrap_extra_args = <<-EOT
      [settings.kubernetes]
      image-gc-high-threshold-percent = 75
      image-gc-low-threshold-percent = 50
      [settings.container-registry.credentials]
      registry = "docker.io"
      auth = "super-secret-string"
      EOT

      labels = {
        dedicated = "gitlab-runner"
      }

      taints = {
        dedicated = {
          key    = "dedicated"
          value  = "gitlab-runner"
          effect = "NO_SCHEDULE"
        }
      }
    }
  }
```

Add bootstrap_extra_args to gitlab-runner managed node group
Run terraform init, plan and apply

## Expected behavior

Expectation:
The module creates a launch template with the merged bootstrap_extra_args for my managed gitlab-runner node group and spins up nodes from this launch template which then join the eks cluster.

What actually happened:
The module creates two launch templates. One named after the node group which only contains the values defined in bootstrap_extra_args which then is used by the managed node group and results in a failed creation state for that managed node group. Another launch template is created with the name "eks-xxxxx" which contains the merged user_data containing both the default user_data and the bootstrap_extra_args which is then attached to the auto-scaling group of the gitlab-runner managed node group. 

### Terminal Output Screenshot(s)
![two_lt](https://user-images.githubusercontent.com/117807980/218689584-ab5cac71-5026-407a-b676-3edc087349c3.png)

![Screenshot from 2023-02-14 10-04-17](https://user-images.githubusercontent.com/117807980/218689308-de73b2cf-7d21-4858-9508-098ff04fc8b2.png)

**Comment by mprzygrodzki** [comment]
I see similar behaviour with launch tempaltes, specifying following i.e.

```
    create_launch_template = true
    launch_template_name   = "my-app-mng-lt"
    launch_template_use_name_prefix = false
``` 

will create 2 LT - the one where I've specified "my-app-mng-lt" is created  but not used as default one for mng node group, and the one attached starts with "eks-... "

**Comment by Kummerkasten** [comment]
After digging in a bit deeper I have to say shame on me it has nothing to do with the module. I was able to resolve this by fixing the settings in bootstrap_extra_args to match what is in the bottlerocket documentation and discovering another specific issue with the "image-gc-...." settings I use.

Old config:
`   bootstrap_extra_args = <<-EOT
    [settings.kubernetes]
    image-gc-high-threshold-percent = 75
    image-gc-low-threshold-percent = 50
    [settings.container-registry.credentials]
    registry = "docker.io"
    auth = "super-secret-string"
    EOT `
    
New config:
`    bootstrap_extra_args = <<-EOT
    [settings.kubernetes]
    image-gc-high-threshold-percent = "80"
    image-gc-low-threshold-percent = "70"
    [[settings.container-registry.credentials]]
    registry = "docker.io"
    auth = "super-secret-string"
    EOT   `    
    
I missed the second pair of square brakets for "settings.container-registry.credentials.
And the "image-gc-...." settings have to be strings. There is an open issue for bottlerocket-os here: https://github.com/bottlerocket-os/bottlerocket/issues/2883
