### ISSUE TITLE
dial tcp 127.0.0.1:80: connect: connection refused when trying to update tags

### ISSUE THREAD

**Issue by fpapalardo** [terraform-aws-modules/terraform-aws-eks#2485]
## Description

When trying to update our common_tags for the `tags` variable we are getting the following error

```
Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with module.eks-saas-green.module.eks.kubernetes_config_map_v1_data.aws_auth[0],
│   on .terraform/modules/eks-saas.eks/main.tf line 527, in resource "kubernetes_config_map_v1_data" "aws_auth":
│  527: resource "kubernetes_config_map_v1_data" "aws_auth" {
│ 
╵
```

Any other change so far works as expected and this resource gets refreshed successfully 
`module.eks-saas-green.module.eks.kubernetes_config_map_v1_data.aws_auth[0]: Refreshing state... [id=kube-system/aws-auth]`

but when updating the tags issue raises back

This is how our provider has been set and working fine
```
data "aws_eks_cluster" "this" {
  name  = module.eks.cluster_name

  depends_on = [
    module.eks.cluster_name
  ]
}

data "aws_eks_cluster_auth" "this" {
  name  = module.eks.cluster_name

  depends_on = [
    module.eks.cluster_name
  ]
}

provider "kubernetes" {
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority[0].data)
  host                   = data.aws_eks_cluster.this.endpoint
  token                  = data.aws_eks_cluster_auth.this.token
}
```

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 19.5.1

- Terraform version: 1.2.9
- Provider version(s):
- Using hashicorp/aws v4.47.0
- Using hashicorp/kubernetes v2.18.0

## Reproduction Code [Required]

We just add a new tag value to our common tags that is later use in variable tags:
```
common_tags = {
    # example1
    "Finance.Class"                  = var.tag_class
    "Finance.CostCenter"             = var.tag_costcenter

    # addition
    "Ownership.Team"                 = var.tag_team
  }
```

Our pipeline runs on atlantis so there is no locals run involved or local cache

## Expected behavior

Successfully run plan

## Actual behavior

`Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused`

**Comment by bryantbiggs** [comment]
remove the `depends_on` usage

**Comment by fpapalardo** [comment]
This actually fix the issue
