### ISSUE TITLE
CloudWatch Logs Log Group already exists

### ISSUE THREAD

**Issue by cdenneen** [terraform-aws-modules/terraform-aws-eks#2486]
## Description

I've created a cluster and destroyed it. When creating again the Log Group complains that it already exists. Therefore the destroy isn't deleting it.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 19.7.0

- Terraform version:

Terraform v1.3.9
- Provider version(s):

+ provider registry.terraform.io/fluxcd/flux v0.23.0
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/gitlabhq/gitlab v15.8.0
+ provider registry.terraform.io/hashicorp/aws v4.54.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.18.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4- Provider version(s):

## Reproduction Code [Required]

Create cluster
Destroy cluster
Create cluster with same name

## Expected behavior

Cluster and all resources created successfully.

## Actual behavior

Terraform exists due to log group already exists with that name.

### Terminal Output Screenshot(s)

```
╷
│ Error: creating CloudWatch Logs Log Group (/aws/eks/mgmt-test123/cluster): ResourceAlreadyExistsException: The specified log group already exists
│
│   with module.eks.aws_cloudwatch_log_group.this[0],
│   on .terraform/modules/eks/main.tf line 105, in resource "aws_cloudwatch_log_group" "this":
│  105: resource "aws_cloudwatch_log_group" "this" {
│
```

## Additional context

#2277

**Comment by bryantbiggs** [comment]
this has already been addressed in previous issues

**Comment by cdenneen** [comment]
Reference?

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L294-L318
