### ISSUE TITLE
Allow usage of dedicated autoscaling_group_tags per node group in self_managed_node_groups

### ISSUE THREAD

**Issue by youwalther65** [terraform-aws-modules/terraform-aws-eks#2490]
## Is your request related to a new offering from AWS?
yes, see aws_autoscaling_group_resource [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group) for example AWS provider 4.55.0

## Is your request related to a problem? Please describe.
I want to add additional ASG tags to allow Cluster Autoscaler to scale form zero to only specific ASG which require this like:
```yaml
      autoscaling_group_tags = {
        "k8s.io/cluster-autoscaler/node-template/label/system-component" : "enabled",
        "k8s.io/cluster-autoscaler/node-template/taint/system-component" : "enabled:NoSchedule",
      }
```
See Cluster Autoscaler documentation on this topic [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup)

Currently module only allow to set common tags for all ASG in self_managed_node_group_defaults

## Describe the solution you'd like.
Add an attribute autoscaling_group_tags on a particular  self-managed node group so that those tags will be added in addition to the tags from self_managed_node_group_defaults

```yaml
# self-managed node groups
  self_managed_node_group_defaults = {
    instance_type                          = "m6i.xlarge"
    update_launch_template_default_version = true
    iam_role_additional_policies = {
      AmazonSSMManagedInstanceCore = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
    }
    # enable discovery of autoscaling groups by cluster-autoscaler
    autoscaling_group_tags = {
      "k8s.io/cluster-autoscaler/enabled" : true,
      "k8s.io/cluster-autoscaler/${local.name}" : "owned",
      "auto-delete" : "no"
    }
  }

  self_managed_node_groups = {
    smng-ond = {
      #name = "${local.name}-smng-ond"
      name = "smng-ond"

      min_size     = 1
      max_size     = 3
      desired_size = 3

      # https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
      bootstrap_extra_args = "--kubelet-extra-args '--node-labels=system-component=enabled --register-with-taints=system-component=enabled:NoSchedule'"

      # required for scaling from zero according to:
      # https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md
      autoscaling_group_tags = {
        "k8s.io/cluster-autoscaler/node-template/label/system-component" : "enabled",
        "k8s.io/cluster-autoscaler/node-template/taint/system-component" : "enabled:NoSchedule",
      }
    }
```

**Comment by bryantbiggs** [comment]
this has been attempted but no solution exists today - https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1558#issuecomment-1030640207

**Comment by youwalther65** [comment]
After evaluating I can confirm that this feature is already implemented and working for self-managed node group.
