### ISSUE TITLE
Need "allocation_strategy" for provisioning spot instances

### ISSUE THREAD

**Issue by pikilisaikiran** [terraform-aws-modules/terraform-aws-eks#2493]
As per the Terraform documentation, it is possible to use some of the attributes like allocation_strategy for spot instances
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_fleet_request
But, I couldn't find them here.
Is it possible to have them from the eks modules?

**Comment by waiyanmin95** [comment]
@pikilisaikiran you can reference it from here 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c7565e265e23cbc622041fc153193f490cfe948f/examples/self_managed_node_group/main.tf#L114-L142

**Comment by bryantbiggs** [comment]
thanks @waiyanmin95 - closing out for now

**Comment by kaykhan** [comment]
looks like `spot_allocation_strategy` is not available for managed node groups can anyone confirm that. 

Assuming that is the case because `mixed_instances_policy` is not available for managed node groups.
