### ISSUE TITLE
Disable kms key creation

### ISSUE THREAD

**Issue by saintmalik** [terraform-aws-modules/terraform-aws-eks#2496]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 19.10.0

- Terraform version:
0.12.0
- Provider version(s):

## Reproduction Code [Required]

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "19.10.0"
  cluster_name    = "pre-prod-bookum-cluster"
  cluster_version = "1.25"
  subnet_ids      = module.vpc.private_subnets
  #   cluster_iam_role_name         = "eks-serverless-cluster-iam-role"
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true
  create_kms_key = false
.....
```

terraform apply --auto-approve

## Expected behavior

create an eks cluster without creating kms or activating the secrets encryption

## Actual behavior

Unsupported attribute

### Terminal Output Screenshot(s)

![Screenshot 2023-03-01 at 5 25 33 PM](https://user-images.githubusercontent.com/37118134/222200994-cec5b970-6162-4753-8014-e9899e0bc6a7.jpg)

**Comment by hjeffries94** [comment]
Hey @saintmalik, I've had this issue previously and resolved it by setting:
```
create_kms_key                  = false
cluster_encryption_config = {}
```

Hopefully that solves your issue!

**Comment by saintmalik** [comment]
> Hey @saintmalik, I've had this issue previously and resolved it by setting:
> 
> ```
> create_kms_key                  = false
> cluster_encryption_config = {}
> ```
> 
> Hopefully that solves your issue!

i just tried, this, didnt work, started getting new errors different from the initial error

**Comment by hjeffries94** [comment]
@saintmalik care to share your new errors?

**Comment by saintmalik** [comment]
my helm_release config, started having errors, here
![Screenshot 2023-03-03 at 2 43 29 AM](https://user-images.githubusercontent.com/37118134/222610667-a69dc0a0-67fc-4381-9317-a04ecb783e7e.jpg)

**Comment by hjeffries94** [comment]
@saintmalik so it looks like it did fix your errors as your plan is able to get further than before (hence why you're now seeing Helm errors and not EKS module errors).

I'd suggest looking at the following and making the required changes, either by altering your kube_config file or using this:
```
export KUBE_CONFIG_PATH=<PATH_TO_KUBE_CONFIG_FILE>
```

Here's a good reference: https://stackoverflow.com/questions/61903086/error-no-configuration-has-been-provided-try-setting-kubernetes-master-environ

I've previously had these errors as well and exporting my kube_config_path fixed them for me. Hope this helps!

**Comment by saintmalik** [comment]
Thanks, this worked, thanks for helping through, i do appreciate, but fixing this issue raised another error too, this time, eks related

![Screenshot 2023-03-03 at 4 08 47 PM](https://user-images.githubusercontent.com/37118134/222756139-619290cc-554e-49ed-8b55-20b177430683.jpg)

**Comment by saintmalik** [comment]
all fixed, thanks, closing this
