### ISSUE TITLE
Utilise Multiple IAM Role ARN's when Provisioning Karpenter Module

### ISSUE THREAD

**Issue by hjeffries94** [terraform-aws-modules/terraform-aws-eks#2497]
As of right now, it appears that we can only use a single IAM role for Karpenter, which isn't ideal if you have multiple EKS managed node groups:
```
eks_managed_node_groups = {
    initial = {

iam_role_arn    = module.eks.eks_managed_node_groups["initial"].iam_role_arn
```
As a workaround, I've basically had to duplicate every resource using for_each:
```
for_each = toset(values(module.eks-cluster.eks_managed_node_groups)[*].iam_role_arn)
iam_role_arn = each.key
```
This isn't an ideal solution and would be significantly better if we can use a list of strings instead of just a string, or some other solution.

If there is already a method of doing this more cleanly, then please let me know, but I haven't been able to identify anything concrete in the last 24 hours.

Thank you!

**Comment by bryantbiggs** [comment]
does Karpenter support multiple roles? How would Karpenter utilize multiple roles?
