### ISSUE TITLE
Not Clear on EC2PrivateDNSName

### ISSUE THREAD

**Issue by ravigude** [terraform-aws-modules/terraform-aws-eks#25]
# I have issues

* [ * ] support request

Should I be exporting my bastion's Ec2 private DNS NAME before I do terraform apply ? 
I used bastion host to provision the EKS cluster
I am not clear on EC2PrivateDNSName variable

**Comment by brandoconnor** [comment]
Hi @ravigude 👋 

Hmmm, I'm not exactly sure what you're trying to do here with regard to the EC2PrivateDNSName. Let me share what I see as a more common way to run Terraform.

If you're just getting started, running terraform directly from your workstation is a perfectly good practice. When you're collaborating with a team, doing deployments often, or in production and needing some more quality assurance, at that point you should consider running terraform apply commands from a dedicated CI/CD worker.

I don't recommend using bastion hosts to run terraform. Bastions should serve exactly one purpose: provide controlled ssh access to hosts within a VPC. That's their only job. Nothing more, nothing less. I've seen the situation of an ever bloating management host that acts as a bastion as well... it doesn't turn out pretty. Segmenting your infrastructure by role is a good practice that will help keep your cloud architecture clean.

I'm going to close this issue for now but if you're still unclear on the common use case and how it relates to the module here, I can go into more detail. In short, it's not recommended to use a bastion for anything but ssh access to instances. Run terraform from your workstation if you're just getting started. This all means you won't need to worry about the `EC2PrivateDNSName` variable at all. I hope that helps 👍
