### ISSUE TITLE
Set instance_type in AWS Launch Template instead of Managed Node Group

### ISSUE THREAD

**Issue by sidewinder12s** [terraform-aws-modules/terraform-aws-eks#2503]
## Is your request related to a problem? Please describe.

You cannot modify instance types on managed node groups if you are not using a provided AWS Launch Template. It appears we just need to move the instance_type spec from the MNG to the launch template. 

## Describe the solution you'd like.

Set the instance_types through Launch template instead of on the managed_node_group config.

## Describe alternatives you've considered.

The alternative is to require users to create new MNGs and manually migrate their workloads when they must change them.

## Additional context

It appears the main drawback of this is that you cannot specify multiple instance types when setting instance_type through the launch template. That may be undesirable for some users, though I don't think it's generally recommended to have multiple instance sizes in MNGs (or self-managed-node-groups) since then the Autoscaler will not know what size instance it is going to launch.

https://github.com/aws/containers-roadmap/issues/746
https://github.com/aws/containers-roadmap/issues/585

**Comment by sidewinder12s** [comment]
Before I look at implementing this, does anyone have major objections to changing the instance specification behavior? 

@bryantbiggs Was there a reason you left the instance_type variable commented out in this module?

https://github.com/terraform-aws-modules/terraform-aws-eks/commit/ee9f0c646a45ca9baa6174a036d1e09bcccb87b1#diff-4402c3de90b812296b76c12945524bfde8723038f31d2db203eb2b9294f72df8R45

**Comment by bryantbiggs** [comment]
This is not a change that we'll support here
