### ISSUE TITLE
Relationship between eks version and aws-eks-module

### ISSUE THREAD

**Issue by liuyanbiao** [terraform-aws-modules/terraform-aws-eks#2505]
Hi

We already updated our eks version to 1.23 but we never update our aws eks module which is still on v13.2.1.

Is there any guide how to update this module from v13.2.1 ?
And there is only one v14.0.0?

Bill

**Comment by bryantbiggs** [comment]
No, that is a quite old version and I don't think any material was provided at the time to upgrade from 13 to 14
