### ISSUE TITLE
Examples should set up proper NATs when there are multiple AZs and subnets

### ISSUE THREAD

**Issue by lordgordon** [terraform-aws-modules/terraform-aws-eks#2507]
## Problem

The examples using the `vpc` module are creating a single NAT when multiple AZs and subnets are available:

```terraform

locals {
  // ...

  vpc_cidr = "10.0.0.0/16"
  azs      = slice(data.aws_availability_zones.available.names, 0, 3)
  
  // ... 
}

// ...

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  
  // ...
  
  azs             = local.azs
  private_subnets = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 4, k)]
  public_subnets  = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 8, k + 48)]
  intra_subnets   = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 8, k + 52)]

  enable_nat_gateway   = true
  single_nat_gateway   = true

  // ...
}
```

This configuration leads to a suboptimal NAT allocation. AWS usually sends out this email to inform you and fix the problem:

> We have observed that your Amazon VPC resources are using a shared NAT Gateway across multiple Availability Zones (AZ). To ensure high availability and minimize inter-AZ data transfer costs, we recommend utilizing separate NAT Gateways in each AZ and routing traffic locally within the same AZ.

> Each NAT Gateway operates within a designated AZ and is built with redundancy in that zone only. As a result, if the NAT Gateway or AZ experiences failure, resources utilizing that NAT Gateway in other AZ(s) also get impacted. Additionally, routing traffic from one AZ to a NAT Gateway in a different AZ incurs additional inter-AZ data transfer charges. We recommend choosing a maintenance window for architecture changes in your Amazon VPC.

## Solution

Since those examples are used as a baseline for new EKS clusters, and this networking configuration is easy to miss, I propose to improve the examples to ensure they have the proper configuration.

I'll gladly contribute with a PR if there is an agreement.

**Comment by lordgordon** [comment]
Further reference: https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/3.12.0#nat-gateway-scenarios

**Comment by bryantbiggs** [comment]
the examples here are not intended to show recommended guidance on how your VPC should be setup - a VPC is required, along with access to the internet, in order for the examples to deploy successfully. Therefore, the supporting resource are merely just that - the minimum required resources to support the example

**Comment by lordgordon** [comment]
> the examples here are not intended to show recommended guidance on how your VPC should be setup - a VPC is required, along with access to the internet, in order for the examples to deploy successfully. Therefore, the supporting resource are merely just that - the minimum required resources to support the example

I understand your point, and I agree. Unfortunately, it happens most of the time that the setup is copied and pasted without deep knowledge of every aspect, especially when the whole networking is "obscured" by another module.

Anyway, in case someone else stumbles on this thread, here is the proper setup when dealing with multiple AZs and subnets:

```terraform
enable_nat_gateway     = true
single_nat_gateway     = false
one_nat_gateway_per_az = true
enable_dns_hostnames   = true
```
