### ISSUE TITLE
Pods are eating all the IPs after the cluster is provisioned

### ISSUE THREAD

**Issue by trustycoder83** [terraform-aws-modules/terraform-aws-eks#2511]
## Is your request related to a new offering from AWS?
  - Yes ✅: [VPC CNI custom network](https://github.com/aws/amazon-vpc-cni-k8s#aws_vpc_k8s_cni_custom_network_cfg)

## Is your request related to a problem? Please describe
After the EKS provision is completed, each pod that I create will consume an IP address from the available subnets, and I end up with no available IP addresses.

## Describe the solution you'd like.
I'm looking for a solution where I can provide a custom network config for the VPC CNI, in order to not hit this issue.

## Describe alternatives you've considered.
Any other alternative solution might work for me, except the one where I need to increase the subnet size because is not possible in my environment.

**Comment by bryantbiggs** [comment]
here is an example using this module to enable custom networking https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/vpc-cni-custom-networking/main.tf
