### ISSUE TITLE
Make `remote_access` nullable in `eks-managed-node-group` module

### ISSUE THREAD

**Issue by wjf3121** [terraform-aws-modules/terraform-aws-eks#2515]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
Yes: I'm trying to conditionally set remote_access block based on a boolean flag. I was expecting something like this to work:
```
remote_access = var.enable_remote_access ? {
  ece_ssh_key = var.ssh_key
  source_security_group_ids = [var.sg_id]
} : null
```

In reality it gives me the following error: 
```
│ Error: Invalid function argument
│
│   on .terraform/modules/account_service.eks/modules/eks-managed-node-group/main.tf line 310, in resource "aws_eks_node_group" "this":
│  310:     for_each = length(var.remote_access) > 0 ? [var.remote_access] : []
│     ├────────────────
│     │ while calling length(value)
│     │ var.remote_access is null
│
│ Invalid value for "value" parameter: argument must not be null.

```
This is caused by [the length call](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c7565e265e23cbc622041fc153193f490cfe948f/modules/eks-managed-node-group/main.tf#L347). It would be nice if `remote_access` variable can be nullable and we can check if the variable is null before the `length` call so that we can conditionally set the value.

## Describe the solution you'd like.
Make `remote_access` nullable so that it can be conditionally enabled.

**Comment by bryantbiggs** [comment]
1. I don't recommend re-wrapping modules in this manner; it leads to weird things like this
2. You can achieve the same outcome using a map comprehension (for_each over a map and put your conditional within the map)

**Comment by wjf3121** [comment]
Hi @bryantbiggs , thanks for the response and suggestion, really appreciate it.

Do you mind elaborate a bit on 2? How can I achieve the same thing through map comprehension?

**Comment by bryantbiggs** [comment]
we have several instances of this throughout the codebase https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c7565e265e23cbc622041fc153193f490cfe948f/main.tf#L97-L99
