### ISSUE TITLE
how to get node group's role attributes

### ISSUE THREAD

**Issue by Mapel88** [terraform-aws-modules/terraform-aws-eks#2516]
## Is your request related to a problem? Please describe.
The eks module creates node group and node group role with the relevant permissions.
After creating, I need to attach additional policies to the node group role, but not sure how to get its name or arn as it's not listed in output attributes.

## Describe the solution you'd like.
Add node group role attribute to outputs list or allow attaching additional policies to this role.

## Describe alternatives you've considered.
I tried using 
```
data "aws_iam_role" "example" {
  name = "an_example_role_name"
}
```
but it requires explicit name while the role name is created with a timestamp so I can't get it with data resource.

Is there any other way I'm not familiar with to get the created node group role?

Thanks

**Comment by bryantbiggs** [comment]
you can attach additional policies like this https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c7565e265e23cbc622041fc153193f490cfe948f/examples/eks_managed_node_group/main.tf#L262-L265

**Comment by Mapel88** [comment]
Thank you very much! 
This is exactly what I was looking for.
Worked like a charm :)

**Comment by Mapel88** [comment]
sorry for re-opening this issue, but I still need the node group role's arn for the "aws_auth_roles".
I searched the complete example and used rolearn: module.eks_managed_node_group.iam_role_arn as indicated in the example:
```
aws_auth_roles = [
    {
      rolearn: module.eks_managed_node_group.iam_role_arn,
      username : "system:node:{{EC2PrivateDNSName}}",
      groups : [
        "system:bootstrappers",
        "system:nodes"
      ]
    }
  ]
```

But getting this error:
```
╷
│ Error: Reference to undeclared module
│
│   on eks.tf line 123, in module "eks-cluster":
│  123:       rolearn: module.eks_managed_node_group.iam_role_arn,
│
│ No module call named "eks_managed_node_group" is declared in the root module.
╵

```

How am I supposed to declare this module if it's used internally by the eks module?
What am I missing?
Sorry if this is a dumb question.. pretty new at this :)

Thanks!

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c7565e265e23cbc622041fc153193f490cfe948f/outputs.tf#L217

**Comment by bryantbiggs** [comment]
FYI - this module manages the configmap. Instead of listing "how to get this attribute" - perhaps lets start with what overall solution you are trying to achieve

**Comment by Mapel88** [comment]
Thank you for time and patience, very much appreciated.
I am using eks module to manage config map.
I used the example from the complete main file.

> https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c7565e265e23cbc622041fc153193f490cfe948f/examples/complete/main.tf#L249-L257

I used the exact code from this example, but I guess I misunderstood how to get the node group role's arn from the module?
This is my code. Am I suppose to declare or source anything else to be able to get "module.eks_managed_node_groups.iam_role_arn" like in the example?

```
module "eks-cluster" {
    source                        = "terraform-aws-modules/eks/aws"
    version                       = "19.10"
	
	# eks configuration
	.
	.
	.

    eks_managed_node_groups = {
        ng = {
			# ng configuration
			.
			.
			.
            # attach additional policies to node group role
            iam_role_additional_policies = {
              efs_policy = aws_iam_policy.eks_efs_csi_policy.arn
            }
        }
    }
	
	manage_aws_auth_configmap = true
	aws_auth_roles = [
		{
		  rolearn: module.eks_managed_node_groups.iam_role_arn,
		  username : "system:node:{{EC2PrivateDNSName}}",
		  groups : [
			"system:bootstrappers",
			"system:nodes"
		  ]
		}
	]
}

```
As I stated, I'm pretty new at this so I only know the basics - modules exports all kind of attributes they created, and I can use them in other resources, so when I didn't see it in the "outputs" section of the eks module documentation I assumed this is something needs to be exported.
Also there is only "feature, bug and security vulnerability" categories and no "question" category, so didn't realize I can just post a question, assumed it needs to be in specific structure to be accepted.
I will take your note into consideration for next issues :)

Thank you very much for your assistance.

**Comment by Mapel88** [comment]
> https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c7565e265e23cbc622041fc153193f490cfe948f/outputs.tf#L217

I just noticed your previous comment and it led me in the right direction.
What I needed is this:  **module.eks-cluster.aws_auth_configmap_yaml** instead of this **module.eks_managed_node_groups.iam_role_arn**
```
  aws_auth_roles = [
    {
      rolearn: module.eks-cluster.aws_auth_configmap_yaml,
      username : "system:node:{{EC2PrivateDNSName}}",
      groups : [
        "system:bootstrappers",
        "system:nodes"
      ]
    }
  ]
```

Thank you very much again for you help and hope this thread will help others :)

**Comment by bryantbiggs** [comment]
closing for now since this seems to be solved for you
