### ISSUE TITLE
eks managed node group not autoscaling

### ISSUE THREAD

**Issue by sebastianmontero** [terraform-aws-modules/terraform-aws-eks#2518]
Version: 19.10.0

I created a eks cluster with a eks managed node group with the following configuration:

```
 eks_managed_node_groups = {
    main = {
      min_size     = 1
      max_size     = 7
      desired_size = 1

      instance_types             = ["t3.xlarge"]
      disk_size                  = 100
      use_custom_launch_template = false
    }
  }
```
The cluster, node group and autoscaling group seem to have been created correctly, but when I deploy pods to the cluster that request more resources than the single node can provide I would expect the node group scale to 2 nodes to accommodate the new nodes, but it does NOT. 
What could be causing this? I'm I missing some configuration? 

I noticed that the autoscaling group has no scaling policies. Is this the issue? How can I add a scaling policy via terraform?

Thanks,

**Comment by bryantbiggs** [comment]
You need to provide a scaling mechanism - typically this is either [cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) or [karpenter](https://karpenter.sh/)
