### ISSUE TITLE
module.eks.eks_managed_node_groups.core.node_group_status returns wrong parameter

### ISSUE THREAD

**Issue by dfroberg** [terraform-aws-modules/terraform-aws-eks#2519]
## Description

When looking up the node_group status the node group ARN is returned instead.

If your request is for a new feature, please use the `Feature request` template.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
19.10
- Terraform version:
Terraform v1.3.9
- Provider version(s):

+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/grafana/grafana v1.35.0
+ provider registry.terraform.io/hashicorp/aws v4.56.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.18.1
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
+ provider registry.terraform.io/viktorradnai/bcrypt v0.1.2
## Reproduction Code [Required]

```hcl
tags = merge(local.tags, {
    "core_status"    = module.eks.eks_managed_node_groups.core.node_group_status == "ACTIVE" ? "ready" : "not-ready"
  })
```

## Expected behavior

A string return with node group status i.e., ACTIVE

## Actual behavior

The node group ARN is returned.

## Additional context

The error is caused by the module output pointing to the wrong parameter in
[modules/eks_managed_node_group/modules/eks-managed-node-group/outputs.tf#L38-L39](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c7565e265e23cbc622041fc153193f490cfe948f/modules/eks-managed-node-group/outputs.tf#L49)

```hcl
output "node_group_status" {
  description = "Status of the EKS Node Group"
  value       = try(aws_eks_node_group.this[0].arn, null)
}
```

Should instead be;

```hcl
output "node_group_status" {
  description = "Status of the EKS Node Group"
  value       = try(aws_eks_node_group.this[0].status, null)
}
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.10.1 :tada:
