### ISSUE TITLE
Your query returned no results. Please change your search criteria and try again

### ISSUE THREAD

**Issue by mkondapalli** [terraform-aws-modules/terraform-aws-eks#2521]
## Description

Terraform plan was working till yesterday and now it fails with the error in the data source. I assume there is some change in the AMI's naming in the AWS side but how to fix this is the question

If your request is for a new feature, please use the `Feature request` template.

- [ yes ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

module "eks" {
  source                               = "terraform-aws-modules/eks/aws"
  cluster_name                         = var.cluster_name
  cluster_version                      = var.eks_version
  subnets                              = var.subnets
  tags                                 = var.tags
  version                              = "12.0.0"

- Terraform version:  v0.13.7

- Provider version(s):hashicorp/aws v3.76.1

## Reproduction Code [Required]

terraform plan 

## Expected behavior

Plan should work as it was till yesterday

## Actual behavior

It fails with  Error: Your query returned no results. Please change your search criteria and try again.
22:12:33  

### Terminal Output Screenshot(s)

Error: Your query returned no results. Please change your search criteria and try again.

  on .terraform/modules/eks.eks/data.tf line 27, in data "aws_ami" "eks_worker_windows":
   27: data "aws_ami" "eks_worker_windows" {

**Comment by mkondapalli** [comment]
worker_ami_name_filter_windows = "Windows_Server-2019-English-Core-EKS_Optimized-1.21-2022.12.13"
  worker_ami_owner_id_windows    = "957547624766"

Adding this fixed the issue. AWS owner change and also we are using 1.20 looks like AWS is not supporting 1.20 AMI's anymore. We are not using windows and this is work around fix for us

**Comment by mkondapalli** [comment]
> Adding the owner ID should be enough. Also please note that this ID may vary between different regions. **957547624766** is valid for us-east-1, but for us-west-2 you should use **137057727718**

Since this is pulling based on the kubernetes version and we are running 1.20 and AMIs for 1.20 do not exist has to changee the name filter

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.0.0/local.tf#L28

**Comment by bryantbiggs** [comment]
EKS no longer supports 1.20 - I would recommend updating your cluster to at least 1.22 which is the minimum supported Kubernetes version by EKS currently

**Comment by mkondapalli** [comment]
> EKS no longer supports 1.20 - I would recommend updating your cluster to at least 1.22 which is the minimum supported Kubernetes version by EKS currently

Yeah we are planning to upgrade
