### ISSUE TITLE
Leave out key administrators when using default KMS key policy

### ISSUE THREAD

**Issue by hauke-d** [terraform-aws-modules/terraform-aws-eks#2526]
## Is your request related to a problem? Please describe.
When using `kms_key_enable_default_policy = true`, the generated KMS key has a policy granting `kms:*` to all identities in the account. However, it will also always add the `KeyAdministration` policy for the identity performing the plan/apply, even if the `kms_key_administrators` variable is empty, as it uses a datasource to [always append the current identity](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/df1b62548c1d8c7117f4ab45c5b494de64b34cb8/main.tf#L134). As the `KeyAdministration` permissions are redundant for any identity inside the account in this case, we would like not to add them at all, because we have different identities running TF.

## Describe the solution you'd like.
I see two possible solutions: 
1) Add a variable `kms_key_administrators_add_current` to turn off the automatic addition of the current identity to the `key_administrators` variable of the KMS module. 
2) Do not add the current identity at all in case `kms_key_enable_default_policy` is enabled as it would be redundant (Breaking change!)

## Describe alternatives you've considered.
Alternatives would require changes to the KMS module

I'd be happy to submit a PR if this is considered useful.

**Comment by bryantbiggs** [comment]
could you provide a reproduction and then also the desired output

**Comment by RobinFrcd** [comment]
For example, just follow https://developer.hashicorp.com/terraform/tutorials/kubernetes/eks and then add `kms_key_enable_default_policy = true` you'll see this diff:

```
  # module.eks.module.kms.aws_kms_key.this[0] will be updated in-place
  ~ resource "aws_kms_key" "this" {
        id                                 = "***"
      ~ policy                             = jsonencode(
          ~ {
              ~ Statement = [
                  + {
                      + Action    = "kms:*"
                      + Effect    = "Allow"
                      + Principal = {
                          + AWS = "arn:aws:iam::***:root"
                        }
                      + Resource  = "*"
                      + Sid       = "Default"
                    },
```

**Comment by RobinFrcd** [comment]
Nice boit :+1:
