### ISSUE TITLE
Support for new - AMI Type AL2023

### ISSUE THREAD

**Issue by d-teller** [terraform-aws-modules/terraform-aws-eks#2527]
1st of all, thank you for this Module and all the effort put into this.

## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
AWS Released a new AMI - [AL2023](https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-linux-2023/)

The EKS Module doesnt support it yet, as its constrained to use only the following.
According to AWS it is supported - [here](https://docs.aws.amazon.com/linux/al2023/ug/using-with-ecs-eks.html)

`expected ami_type to be one of [AL2_x86_64 AL2_x86_64_GPU AL2_ARM_64 CUSTOM BOTTLEROCKET_ARM_64 BOTTLEROCKET_x86_64 BOTTLEROCKET_ARM_64_NVIDIA BOTTLEROCKET_x86_64_NVIDIA WINDOWS_CORE_2019_x86_64 WINDOWS_FULL_2019_x86_64 WINDOWS_CORE_2022_x86_64 WINDOWS_FULL_2022_x86_64], got AL2023
`
## Describe the solution you'd like.
Add support for AL2023

**Comment by bryantbiggs** [comment]
This will need to wait for:
1. AWS to release an EKS AL2023 AMI 
2. EKS managed nodegroups add support for the relevant AMI type
3. Terraform AWS provider updated to allow use of the new AMI type(s)
4. Then we can support this here

Closing for now - you can follow its progress here https://github.com/awslabs/amazon-eks-ami/pull/1212
