### ISSUE TITLE
No No method of specifying a credit specification for burstable performance worker instances

### ISSUE THREAD

**Issue by bmacauley-reward** [terraform-aws-modules/terraform-aws-eks#253]
# I have issues

## I'm submitting a...

 feature request

## What is the current behavior?

No method of specifying a credit specification for burstable performance worker instances
eg t2.medium ...defaults to standard, would like to set it to unlimited

## What's the expected behavior?
Configuration parameter for credit specification...

aws_launch_template ...rather than aws_launch_configuration?
https://www.terraform.io/docs/providers/aws/r/launch_template.html

## Environment details

* Affected module version: v2.1.0
* OS: MacOS
* Terraform version: 0.11.11

**Comment by max-rocket-internet** [comment]
Cool. Feel free to make a PR 🙂

**Comment by a-shink** [comment]
I started coding, have result and will send Merge request ASAP.

For T3 instances this parameter is "unlimited" by default. As result peoples can have additional charges even in Free tier or "surprises" like 68$ price per instance instead 3.6$ expected. Check detailed explanation at https://advancedweb.hu/2019/03/05/t3_unlimited/
The module still don't configure this param so better do it. I think better default is have "limited" mode.

This parameter can be configured for Launch Templates only, don't work for Launch Configuration even via AWS API.

**Comment by a-shink** [comment]
I just did it #426
