### ISSUE TITLE
Karpenter module - support optional IAM policy ARNs to attach to IRSA role

### ISSUE THREAD

**Issue by Constantin07** [terraform-aws-modules/terraform-aws-eks#2535]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
There is no simple way to grant Karpenter IRSA IAM permissions to a CMK KMS key used for EBS encryption.

## Describe the solution you'd like.
An optional variable to pass a list of ARNs of IAM policies to attach to the IRSA role used by Karpenter controller.

## Describe alternatives you've considered.
Amend the CMK KMS use policy and add permissions on KMS resource side but this is not ideal as it creates circular dependency. In my case CMK KMS key is created as a `core` shared resource together with use policy which I just want to reference in Karpenter's IRSA role.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.11.0 :tada:
