### ISSUE TITLE
`node_security_group_id` vs `vpc_security_group_ids` for EKS Managed Node Groups?

### ISSUE THREAD

**Issue by ChrisJBurns** [terraform-aws-modules/terraform-aws-eks#2536]
## Description

We are upgrading our cluster from `17.24.0` to `18.31.2` and there are a couple of changes to say the least. I'm pretty much following the upgrade guide where renames are concerned, but I have noticed that it says in the upgrade guide that what was once `worker_additional_security_group_ids` is now `vpc_security_group_ids`. But what is `node_security_group_id` for if `vpc_security_group_ids` also exists?

Secondly, we had the following for version `17.24.0`:
```hcl
  cluster_create_security_group = false
  cluster_security_group_id     = aws_security_group.eks_cluster.id
  worker_create_security_group  = false
  worker_security_group_id      = aws_security_group.eks_cluster.id
```

With `aws_security_group.eks_cluster.id` referencing a SG that had the following rules:
```hcl
# EKS ENI & Managed NodeGroup security group
resource "aws_security_group" "eks_tooling" {
  name        = "eks-eni-and-managed-nodegroup-${var.eks_cluster_name}"
  description = "Applied to EKS ENIs and Managed NodeGroups"
  vpc_id      = var.vpc_id

  tags = {
    Name        = "eks-eni-and-managed-nodegroup-${var.eks_cluster_name}"
    Environment = var.environment_name
    Capability  = "Security Group"
    Cluster     = var.eks_cluster_name
  }
}

# Allow all ingress TCP traffic to self. Worker<->Master nodes allow all traffic
resource "aws_security_group_rule" "eks_ingress_tcp_traffic_tooling" {
  description       = "All TCP traffic. Worker and Master communication"
  security_group_id = aws_security_group.eks_cluster.id
  type              = "ingress"
  from_port         = 0
  to_port           = 65535
  protocol          = "tcp"
  self              = true
}

# Allow all ingress UDP traffic to self. Worker<->Master nodes allow all traffic
resource "aws_security_group_rule" "eks_ingress_udp_traffic_tooling" {
  description       = "All UDP traffic. Worker and Master communication"
  security_group_id = aws_security_group.eks_cluster.id
  type              = "ingress"
  from_port         = 0
  to_port           = 65535
  protocol          = "udp"
  self              = true
}
```

Is it true that these SecurityGroups and rules are already added by the provider now? I ask because the SG and SG rules above were written over 2 years ago, so it's entirely possible the provider does this kind of stuff now.

**Comment by reedjosh** [comment]
I'd like to know more about this too. Going through this same upgrade atm.

So far not much luck getting the security groups lined up, but learning quickly.

I'll try to ping back if I find anything out myself.

**Comment by reedjosh** [comment]
`node_security_group_id` is the primary security group id, and `vpc_security_group_ids` is any additional security groups.

I believe the distinction is primarily required because of the underlying logic in it.

If the module is told not to create the security group, then it checks that the secuirty group id has been provided.


In a normal programming language one might just check that there was at least one security group in the list of security groups, but it's probably easier to have two separate fields in terraform.

Maybe there are other reasons to separate the two as well.

**Comment by reedjosh** [comment]
I am curious if you got to try going straight to v19. I'm upgrading ours atm and have done like 5 v17->v19 transitions successfully so far. It has not been easy though.

I'd even be up for a slack or zoom sometime now that I feel pretty confident about it.

Cheers!

**Comment by bryantbiggs** [comment]
in general, there are two distinct security groups because there are two logical constructs at play - the control plane, and the data plane. Therefore there are access requirements for the control plane, and access requirements for the data plane. For the majority of the workloads, users will only be modifying access in the node security group. You can see more details and reasoning behind the design here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/network_connectivity.md

**Comment by ChrisJBurns** [comment]
So I've come back to this and given it another try but this time the upgrade straight from `17.x` to `19.x`. It seems that the Security Groups that are attached to the worker nodes is the one that was mentioned above: `aws_security_group.eks_cluster.id`. Whereas on the cluster before the upgrade, the security group that seems to be attached to the worker nodes is the default security group with description: "EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads.".

I'm not entirely sure where I need to change in order to get it to work. 

Pre upgrade:
```hcl
  cluster_create_security_group = false
  cluster_security_group_id     = aws_security_group.eks_tooling.id
  worker_create_security_group  = false
  worker_security_group_id      = aws_security_group.eks_tooling.id
```

After upgrade:
```hcl
  create_cluster_security_group = false
  cluster_security_group_id     = aws_security_group.eks_tooling.id
  create_node_security_group  = false
  node_security_group_id      = aws_security_group.eks_tooling.id
```

Now as expected, the Security Group that is being attached to the nodes is indeed ` aws_security_group.eks_tooling.id`. Which somewhat seems expected, the only thing that I don't understand is how in `17.x` when we provided `worker_security_group_id      = aws_security_group.eks_tooling.id`, it still attached the EKS created Security Group to the EC2 instances (worker nodes).

**Comment by ChrisJBurns** [comment]
Update:

I managed to solve the above by just adding the following:

```hcl
  eks_managed_node_group_defaults = {
    attach_cluster_primary_security_group = true
    ...
    ...
  }. 
```

I need to sort out the Security Group Rules in future anyways but this has allowed me to progress with a potential upgrade.

I can close now as I know the answer to the question I asked when I raised this ticket!

Thanks for your help both @reedjosh  @bryantbiggs
