### ISSUE TITLE
While provising ipv6 along with karpenter, Policy attachement fail with error stating policy does not exists with name "NoSuchEntity: Policy arn:aws:iam::aws:policy/AmazonEKS_CNI_IPv6_Policy"

### ISSUE THREAD

**Issue by yjagdale** [terraform-aws-modules/terraform-aws-eks#2543]
## Description

when we try to install karpenter with ipv6 support, Installation fails with error ```NoSuchEntity: Policy arn:aws:iam::aws:policy/AmazonEKS_CNI_IPv6_Policy```
the reason is AmazonEKS_CNI_IPv6_Policy not aws managed policy as per doc [aws_doc](https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html)

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:
Terraform v1.4.2
- Provider version(s):
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.60.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.19.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4

## Reproduction Code [Required]

Run terraform provising using below values
```
module "karpenter" {
  source                       = "terraform-aws-modules/eks/aws//modules/karpenter"
  version                      = "~> 19.11.0"
  cluster_ip_family            = "ipv6"
  cluster_name                 = module.eks.cluster_name
  irsa_oidc_provider_arn       = module.eks.oidc_provider_arn
  create_irsa                  = false
  iam_role_additional_policies = local.additional_policies
  tags                         = var.tags
}
```

## Expected behavior
Policy should be taken from account specific scope. we have flag in eks module to create this policy

## Actual behavior
its trying to add ipv6 as managed policy and endup in error policy not found.

### Terminal Output Screenshot(s)
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/17045535/228903915-e336e1dc-4683-4682-9456-9965713205fe.png">

**Comment by bryantbiggs** [comment]
Did you opt in to creating the policy with this module first? https://github.com/terraform-aws-modules/terraform-aws-eks/blob/2cf6a5bc14fd48b8e02c9755648b862d41e00333/examples/eks_managed_node_group/main.tf#L55

**Comment by yjagdale** [comment]
@bryantbiggs - Any thoughts?
