### ISSUE TITLE
Managed node group launch template creation incorrect behavior

### ISSUE THREAD

**Issue by pkashlikov-exos** [terraform-aws-modules/terraform-aws-eks#2545]
## Description

As per Managed Node Group Module documentation create_launch_template input have following behavior: "Determines whether to create a launch template or not. If set to false, EKS will use its own default launch template" and default value is "true". Based on this I'm assuming that if I don't set it to false, module will create launch template and use it to launch nodes, but we observe different behavior. 

If your request is for a new feature, please use the `Feature request` template.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 19.9.0

- Terraform version:
Terraform v1.2.9
- Provider version(s):

+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.51.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.14.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4

## Reproduction Code [Required]

`module "eks_cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 19.9"

  cluster_name                           = local.eks_cluster_name
  cluster_version                        = "1.24"
  cluster_enabled_log_types              = ["audit", "api", "authenticator", "scheduler", "controllerManager"]
  vpc_id                                 = local.vpc_id
  kms_key_description                    = "Default cluster key of ${local.name}"
  kms_key_administrators                 = local.administrators_arn_list
  cloudwatch_log_group_retention_in_days = local.cloudwatch_log_group_retention_in_days
  control_plane_subnet_ids               = [aws_subnet.us_east_1a_private.id, aws_subnet.us_east_1b_private.id]
  subnet_ids                             = [aws_subnet.us_east_1a_private.id, aws_subnet.us_east_1b_private.id, aws_subnet.us_east_1a_public.id, aws_subnet.us_east_1b_public.id]
  cluster_endpoint_private_access        = true
  manage_aws_auth_configmap              = true

  cluster_addons = {
    coredns = {
      most_recent = true
    }
    kube-proxy = {
      most_recent = true
    }
    vpc-cni = {
      most_recent = true
    }
    aws-ebs-csi-driver = {
      most_recent              = true
      service_account_role_arn = "${module.csi_ebs_service_account.service_role_arn}"
    }
  }
  aws_auth_roles = [
    {
      rolearn  = "arn:aws:iam::xxxxxxxxxx:role/AWSReservedSSO_AdministratorAccess_9791cf4055bbd307"
      username = "Admin"
      groups   = ["system:masters"]
    },
  ]
  eks_managed_node_groups = {
    initial = {
      instance_types                         = ["m6a.2xlarge"]
      force_update_version                   = true
      update_launch_template_default_version = false
      min_size                               = 2
      max_size                               = 10
      desired_size                           = 3
      subnet_ids                             = [aws_subnet.us_east_1a_private.id, aws_subnet.us_east_1b_private.id]
      iam_role_additional_policies = {
        AmazonSSMManagedInstanceCore = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
      }

      block_device_mappings = {
        ebs = {
          volume_type = "gp3"
        }
      }
    }
  }`

Launch eks cluster with managed node group and check in AWS console which launch template is actually being used. There is another launch template being created by EKS itself and used for node creation.

## Expected behavior

One launch template is created and being used to launch nodes.

## Actual behavior

Launch template is created by Terraform apply and another one is created by assumed-role/AWSServiceRoleForAmazonEKSNodegroup/EKS and being actually used to launch nodes.

**Comment by bryantbiggs** [comment]
Please see the EKS managed nodegroup documentation. When a custom launch template is used (which this module creates by default), its merged with a launch template created by EKS. Therefore, you will see two launch templates, the one provided by the module, and the one provided by EKS, but the one created by EKS is the LT used on the nodegroup since it has the merged results
