### ISSUE TITLE
Does module version 18.31.2 support EKS 1.25

### ISSUE THREAD

**Issue by steveckt39** [terraform-aws-modules/terraform-aws-eks#2548]
This is more of a question than an issue.  Going through the examples (../terraform-aws-eks)/examples/) that were updated just days ago, it referenced EKS 1.24.  I don't see any mention about EKS 1.25.

Does module version 18.31.2 support EKS 1.25?  knowing that some of the newer feature of 1.25 may not be manipulated using 18.31.2, can the module 18.31.2 otherwise provision a working EKS 1.25 cluster?

**Comment by bryantbiggs** [comment]
Yes - there are no changes required in this module to support specific Kubernetes versions
