### ISSUE TITLE
create_iam_role = false for managed_node_groups creates the role

### ISSUE THREAD

**Issue by reedjosh** [terraform-aws-modules/terraform-aws-eks#2553]
## Description

`create_iam_role = false` for managed_node_groups still creates an IAM role

- [ ✅ ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version:
`19.12.0` coming from `17.something` or other.

- Terraform version:
`1.3.9`

## Reproduction Code [Required]

``` terraform
}
 ...
  eks_managed_node_groups = {
    default = {

      ...

      craete_iam_role = false
      iam_role_arn = "arn:aws:iam::<redacted>"
      iam_role_name = "<a redacted name>"
      iam_role_use_name_prefix = false
      
      ...

    },
...
}
```

Not using workspaces.

It doesn't really matter the order. Just cannot get the managed node group to respect the `iam_role_*` options.

## Expected behavior

Iam role for managed node groups are as specified and not created by the EKS module if missing.

Iam role for managed node groups matches the ARN and name of an existing node group. If a matching node group is not found the operations fail.

## Actual behavior

The settings appear to be completely ignored and a new node role is created for each node group.

**Comment by bryantbiggs** [comment]
there seems to be a key piece of information that has been removed from the issue template that is vital to being able to provide feedback/support - here is a copy of said information that was removed 
![image](https://user-images.githubusercontent.com/10913471/231593219-1078b3c2-fa36-4874-b10a-0c11e10b98dc.png)

**Comment by reedjosh** [comment]
I'm not actually sure which part you are referring to?

I mean I removed what I though were instructions?

Gimme a sec and I'll grab and refill.

**Comment by reedjosh** [comment]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):


## Reproduction Code [Required]



Steps to reproduce the behavior:





## Expected behavior



## Actual behavior



### Terminal Output Screenshot(s)



## Additional context

**Comment by reedjosh** [comment]
I'll do one bit at a time. We're def intercommunicating somewhere.

**Comment by bryantbiggs** [comment]
I don't know if what you provided is a direct copy+paste but what I can say is that this will not do what you might have intended due to the mis-spelling `craete_iam_role = false`

**Comment by reedjosh** [comment]
> I don't know if what you provided is a direct copy+paste but what I can say is that this will not do what you might have intended due to the mis-spelling craete_iam_role = false

Ha, I was just filling out one section at a time, but I think that was possibly the issue?

**Comment by reedjosh** [comment]
Although, does TF allow variables that aren't present on the module?

**Comment by reedjosh** [comment]
Let's just close this. I was just trying to preserve the old IAM role, but I've since built it out so I can upgrade without doing so.
