### ISSUE TITLE
List of string  variable added to environment variable  is not interpreted correctly

### ISSUE THREAD

**Issue by forasoft** [terraform-aws-modules/terraform-aws-eks#2554]
## Description

After add  list of string variable  to environment variables and terraform plan variable is not interpreted as list of string 

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions
- Terraform version: 1.4.4 

- Provider version(s):
+ provider registry.terraform.io/cloudposse/utils v1.7.1
+ provider registry.terraform.io/hashicorp/aws v4.47.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4

## Reproduction Code [Required]

module "eks" {
  source             = "terraform-aws-modules/eks/aws"

  cluster_name       = var.cluster_name
  cluster_version    = var.cluster_version
  

  vpc_id                         = module.vpc.vpc_id
  subnet_ids                     = module.vpc.private_subnets
  cluster_endpoint_public_access = true

  enable_irsa     = true 
  

  eks_managed_node_group_defaults = {
    ami_type = "AL2_x86_64"

  }
 
  eks_managed_node_groups = {
    services = {
      name = var.service_node_group_name

      instance_types = var.service_node_group_instance_types
      capacity_type  = var.capacity_type
      labels       = var.service_node_group_labels
      min_size     = var.service_node_group_min_size
      max_size     = var.service_node_group_max_size
      desired_size = var.service_node_group_desired_size
    }

    media = {
      name = var.media_node_group_name

      instance_types = var.media_node_group_instance_types
      capacity_type  = var.capacity_type
      labels       = var.media_node_group_labels
      min_size     = var.media_node_group_min_size
      max_size     = var.media_node_group_max_size
      desired_size = var.media_node_group_desired_size
    }
  }

}

variable "service_node_group_instance_types" {

  default = ["t2.medium"]
  
}

1)export TF_VAR_service_node_group_instance_types=[\"t3.medium\"]   
2)Run terraform init && terraform plan 

## Expected behavior

terraform plan pass with no errors 

## Actual behavior

Receive an error : 
Error: Invalid value for input variable

   on .terraform/modules/eks/node_groups.tf line 298, in module "eks_managed_node_group":
  298:   instance_types       = try(each.value.instance_types, var.eks_managed_node_group_defaults.instance_types, null)
 
 The given value is not suitable for module.eks.module.eks_managed_node_group["services"].var.instance_types declared at
 .terraform/modules/eks/modules/eks-managed-node-group/variables.tf:353,1-26: list of string required.
 
 
 ### Terminal Output Screenshot(s)
 
 
![image](https://user-images.githubusercontent.com/2485683/230643233-78609d14-fea9-47f8-8165-1886564770a2.png)

**Comment by bryantbiggs** [comment]
closing since this appears to be down to how the Terraform code is provisioned and not the actual module
