### ISSUE TITLE
Karpenter module does not create managed node group

### ISSUE THREAD

**Issue by pwdavison** [terraform-aws-modules/terraform-aws-eks#2556]
## Description

The karpenter module contains the following variable:

variable "create" {
  description = "Determines whether to create EKS managed node group or not"
  type        = bool
  default     = true
}

Within the implementation of this module, it does not appear this flag creates a managed node group. 

- [ X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 19.12.0

- Terraform version:
v1.3.2
- Provider version(s):

+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.62.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.19.0

## Reproduction Code [Required]

Call karpenter module with required inputs such as:

module "karpenter" {
  source = "terraform-aws-modules/eks/aws//modules/karpenter"

  cluster_name = module.eks.cluster_name

  irsa_oidc_provider_arn          = module.eks.oidc_provider_arn
  irsa_namespace_service_accounts = ["karpenter:karpenter"]

  tags = {
    Environment = "dev"
    Terraform   = "true"
  }
}

## Expected behavior

A new managed node group should be created based on the create variable description:

variable "create" {
  description = "Determines whether to create EKS managed node group or not"
  type        = bool
  default     = true
}

## Actual behavior

Managed node group is not created. A managed node group resource or the calling of the managed node group module is not contained within the karpenter module.

**Comment by bryantbiggs** [comment]
thanks for the issue - however, this is working as intended. you need compute in order to run applications/addons on your cluster, including karpenter - but from there on, Karpenter can manage additional compute requirements. I would suggest looking at the Karpenter example we provided which demonstrates running Karpenter on EKS Fargate, while Karpenter EC2 based compute for your cluster workloads

**Comment by pwdavison** [comment]
Hi Bryant, thanks for your reply. My confusion stems from the description of the `create` variable, "Determines whether to create EKS managed node group or not".

When I read the docs for this module initially, my assumption was that by default, a managed node group would be created for karpenter to run on. Is this not the intention of the `create` variable?

**Comment by bryantbiggs** [comment]
which `create` variable exactly? By default, this module will only create a managed node group if a definition is provided for a least one nodegroup

**Comment by pwdavison** [comment]
Referring to this one

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/273c48a631c0ab45ffac1d1a77c7752e8541b1f2/modules/karpenter/variables.tf#L1

Looking at the [main.tf](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/273c48a631c0ab45ffac1d1a77c7752e8541b1f2/modules/karpenter/main.tf) of the module, it seems that this toggles creation of iam roles, instance profiles, and sqs queue but not a managed node group resource.

**Comment by bryantbiggs** [comment]
correct, but you need to provide a definition, even the bare minimum to tell terraform you want to create something

```hcl
  # omitted ...
  eks_managed_node_groups = {
    minimum = {}
  }
  # omitted ...
 ```
