### ISSUE TITLE
Dependency Cycle Error on example code eks_managed_node_group

### ISSUE THREAD

**Issue by Roxyrob** [terraform-aws-modules/terraform-aws-eks#2557]
## Description

There is a dependency cycle error in this example code [eks_managed_node_group](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/eks_managed_node_group)

**module.vpc_cni_irsa** depends on **module.eks**
<pre>
module "vpc_cni_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 5.0"
  ...

  oidc_providers = {
    main = {
      <b>provider_arn               = module.eks.oidc_provider_arn</b>
      ...
}
</pre>

and **module.eks** depends on **module.vpc_cni_irsa**
<pre>
module "eks" {
  ...
  cluster_addons = {
    ...
    vpc-cni = {
      most_recent              = true
      before_compute           = true
      <b>service_account_role_arn = module.vpc_cni_irsa.iam_role_arn</b>
 ...
}
</pre>

## Versions
- Module version [Required]: v19.12.0

- Terraform version:

- Provider version(s):

## Reproduction Code [Required]
The issue can be catched reading the code but I suppose you can get error running
terraform apply

## Expected behavior

Apply with no cycle errors or documentation warn about 2 step execution

## Actual behavior

Sample code Code has a Cycle error

**Comment by bryantbiggs** [comment]
There is no error - please only report errors along with reproduction code

**Comment by Roxyrob** [comment]
Hi @bryantbiggs my bad,
I tried to convert example code to creates more eks clusters using a map of cluster like this:
<pre>
eks_instances = {
  clus1 = {
    create = true
    cluster_version = ...
    ...
  }
}
</pre>

and using for_each on code like below. So the cross-reference between **module.eks** and **module.vpc_cni_irsa** become a CYCLE ERROR:

<pre>
<b>module "eks"</b> {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 19.12"

  for_each = {
    for k, v in var.eks_instances:
      k => v
    if (lookup(v, "create", false))
  }
  ...
  cluster_addons = merge(
    {
      vpc-cni = {
        ...
        service_account_role_arn = module.vpc_cni_irsa<b>[each.key]</b>.iam_role_arn
    },
    lookup(each.value, "cluster_addons", {})
  )
...


<b>module "vpc_cni_irsa"</b> {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 5.0"

  for_each = {
    for k, v in var.eks_instances:
      k => v
    if (lookup(v, "create", false))
  }

  ...
      provider_arn               = module.eks<b>[each.key]</b>.oidc_provider_arn
  ...
}
</pre>

I'll really appreciate if you know why with for_each cycle become evident and how you managed to hide the module cross-reference (cycle) in the original code.

**Comment by bryantbiggs** [comment]
creating multiple clusters with a `for_each` loop works well today https://github.com/clowdhaus/terraform-aws-eks-report/blob/f537a89c07e68a66c3be0a4aa2950449e0cc02cb/examples/complete/main.tf#L56-L72

**Comment by Roxyrob** [comment]
That is another and different example without mutual dependencies (module.eks with service_account_role_arn = vpc_cni_irsa iam_role_arn and module.vpc_cni_irsa with policy containing eks cluster oidc_provider_arn).
