### ISSUE TITLE
Cluster API cannot access the spark-operator webhook service endpoint on port 8080

### ISSUE THREAD

**Issue by alita1991** [terraform-aws-modules/terraform-aws-eks#2561]
## Description

I utilized the Terraform module 'terraform-aws-eks' to provision an EKS cluster with version 1.23. However, I encountered a timeout issue when the API server attempted to access the spark-operator webhook service endpoint. What I found is that the ports between the cluster API and the nodes were not open within the cluster, which is not expected when you are inside the cluster.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: v19.12.0

## Reproduction Code [Required]

- examples/eks_managed_node_group/main.tf

1. Provision an EKS cluster using node groups.
2. Check the security groups and see if the Cluster API can access the service endpoints (1 to 65535)

## Expected behavior

Cluster API must be able to access the service endpoints

## Actual behavior

Cluster API is not able to access the service endpoints

### API server logs

681315700000,I0412 16:08:20.134289      10 dialer.go:37] [6f5dcf0368464344: 10.195.65.23:8080] Dialing...
1681315710000,E0412 16:08:30.125227      10 writers.go:117] apiserver was unable to write a JSON response: http: Handler timeout

**Comment by bryantbiggs** [comment]
port 8080 is not enabled by default, you would need to add a rule to enable that access https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/network_connectivity.md#security-groups

**Comment by alita1991** [comment]
Hi @bryantbiggs,

Is there a security reason for now allowing Cluster API to access that specific port?

**Comment by bryantbiggs** [comment]
did you read the linked docs?

**Comment by alita1991** [comment]
Hi,

I read the document, is pretty clear, however from a k8s user point of view, the expectation was to have the required access when you are inside the cluster, and when I say inside, I refer to K8s components. 

You can close the ticket, the documentation will help me to have a starting point.

Thanks

**Comment by bryantbiggs** [comment]
for a stronger security posture, and because its easier to open up access as opposed to remove access, the module defaults to starting with the bare minimum access required for the cluster to come up successfully. Any additional ports used by applications deployed onto the clusters should be added by users since this will vary by application and by use case.
