### ISSUE TITLE
Current eks-managed-node-group example doesn't allow traffic between nodes.

### ISSUE THREAD

**Issue by apeschel** [terraform-aws-modules/terraform-aws-eks#2562]
## Description

https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/eks_managed_node_group

The v18 version of this example had a rule to allow node-to-node traffic, but it was removed in the changes to v19. This means the v19 example doesn't actually do anything useful, since the pods can't communicate with pods on other nodes. There's no warning in there about needing to add rules to allow traffic between pods.

I think there's two possible ways to fix this:

1. Add this block back to the example

```
    # Extend node-to-node security group rules
    node_security_group_additional_rules = {
      ingress_self_all = {
        description = "Node to node all ports/protocols"
        protocol    = "-1"
        from_port   = 0
        to_port     = 0
        type        = "ingress"
        self        = true
      }
      egress_all = {
        description      = "Node all egress"
        protocol         = "-1"
        from_port        = 0
        to_port          = 0
        type             = "egress"
        cidr_blocks      = ["0.0.0.0/0"]
        ipv6_cidr_blocks = ["::/0"]
      }
    }
```

2. Add these rules to the default `node_security_group_recommended_rules`.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: Docs on head of master

## Expected behavior

Pods can communicate when building a cluster using the example.

## Actual behavior

Pods cannot communicate with pods on other nodes.

**Comment by bryantbiggs** [comment]
This was documented here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md

**Comment by bryantbiggs** [comment]
What should be updated? I can't document things that are not known - I don't know what all different applications and their network connectivity requirements users will be deploying on to their clusters. The module is designed to facility "core" traffic, and its up to users to extend based on their application and workload requirements

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/network_connectivity.md#security-groups

We can support adding rules - we cannot support removing rules or restricting access. Previous versions of this module allowed all traffic to flow cross security group which is not something that some institutions will allow. Again, there isn't anything disabled by default - think of a standard security group. When you create a security group, but default you get - nothing. No ingress, no egress. Why - because AWS does not know what your networking requirements are and its better to start from a restricted perspective and add access as needed.

**Comment by bryantbiggs** [comment]
self is the rule type - meaning, the security group itself. So `Self: TCP & UDP/53` is signifying [these rules](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0f9d9fac93caf239386f47b0f117706ea78c2bec/node_groups.tf#L110-L125) - those rules are required for cluster DNS (coreDNS) to function correctly

The `Self: TCP/1025-65535 [Opt]` is again representing [this rule](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0f9d9fac93caf239386f47b0f117706ea78c2bec/node_groups.tf#L129-L136) that is optional; enabled if `node_security_group_recommended_rules` is `true`
