### ISSUE TITLE
Karpenter IAM role - missing permissions to create the service-linked role for EC2 spot instances

### ISSUE THREAD

**Issue by Constantin07** [terraform-aws-modules/terraform-aws-eks#2565]
## Is your request related to a problem? Please describe.

When spinning up new EC2 spot instances in a fresh new AWS account the service linked role `AWSServiceRoleForEC2Spot` is missing and Karpenter fails with this error:

`ERROR	controller.provisioner launching machine, creating cloud provider instance, creating instance, with fleet error(s), AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.`

## Describe the solution you'd like.

Grant in IAM policies for Karpenter permissions to create the service linked role `AWSServiceRoleForEC2Spot` if it doesn't exist.

## Describe alternatives you've considered.

Current workarount is to create it manually:
```bash
AWS_PROFILE=<profile> aws iam create-service-linked-role --aws-service-name spot.amazonaws.com
{
    "Role": {
        "Path": "/aws-service-role/spot.amazonaws.com/",
        "RoleName": "AWSServiceRoleForEC2Spot",
        "RoleId": "********************",
        "Arn": "arn:aws:iam::***************:role/aws-service-role/spot.amazonaws.com/AWSServiceRoleForEC2Spot",
        "CreateDate": "2023-04-13T14:38:56+00:00",
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": [
                        "sts:AssumeRole"
                    ],
                    "Effect": "Allow",
                    "Principal": {
                        "Service": [
                            "spot.amazonaws.com"
                        ]
                    }
                }
            ]
        }
    }
}
```

**Comment by bryantbiggs** [comment]
Please see the [getting started guide](https://karpenter.sh/v0.27.2/getting-started/getting-started-with-karpenter/#3-create-a-cluster) - this role should exist in your account and is outside the scope of the module

```sh
aws iam create-service-linked-role --aws-service-name spot.amazonaws.com || true
# If the role has already been successfully created, you will see:
# An error occurred (InvalidInput) when calling the CreateServiceLinkedRole operation: Service role name AWSServiceRoleForEC2Spot has been taken in this account, please try a different suffix.
```
