### ISSUE TITLE
EKS Cluster Load Balancer Slowness

### ISSUE THREAD

**Issue by infa-pavakuma** [terraform-aws-modules/terraform-aws-eks#2567]
## Description

EKS Slowness:
All, I have an EKS cluster running and I am using nginx Ingress controller with Classic LB. However while accessing the LB, it is too dead slow ( Not all the requests, but only a couple of requests ). I have the LB in public subnet and my EC2 Instances are in private subnet. And my public subnets also have the elb tag as well. Is there anything that I am missing?

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:
https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/self_managed_node_group

## Reproduction Code [Required]

[](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/self_managed_node_group)

**Comment by bryantbiggs** [comment]
this is not related to the module - I would open an issue with the nginx ingress controller project
