### ISSUE TITLE
Upgrading from v17 forces recreation of EKS node resources

### ISSUE THREAD

**Issue by pettinz** [terraform-aws-modules/terraform-aws-eks#2568]
## Description

Upgrading the module from v17 to v19, the following resources are planned to be replaced
- `resource "aws_autoscaling_group" "this"`
- `resource "aws_launch_template" "this"`
- `resource "aws_iam_instance_profile" "this"`

The resources listed above are created by the internal modules, in our particular case the self-managed-node-group module. A big deal in a heavy production environment.

The present issue is caused by a hardcoded hyphen placed at the end of the name prefix of the listed resources (e.g. [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/fd62c24b07359082985b8c7422361afdeec4254c/modules/self-managed-node-group/main.tf#L321)). 

## Versions

- Module version [Required]: 19.12.0

- Terraform version:
```
❯ terraform version
Terraform v1.3.9
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.4.5. You can update by downloading from https://www.terraform.io/downloads.html
```
- Provider version(s):
```
❯ terraform providers -version
Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.58.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.17.0
```

## Reproduction of the issue

The issue can be reproduced upgrading from v17 if the name prefix of the ASG, Launch Templates or Instance Profiles resources do not end with a hyphen.

### Produced plan

```
  # module.eks.module.self_managed_node_group["node-group-01-a"].aws_autoscaling_group.this[0] must be replaced
+/- resource "aws_autoscaling_group" "this" {
      ~ name_prefix   = "node-group-01-a" -> "node-group-01-a-" # forces replacement
        # ...
    }

  # module.eks.module.self_managed_node_group["node-group-01-a"].aws_launch_template.this[0] must be replaced
+/- resource "aws_launch_template" "this" {
      ~ name_prefix   = "node-group-01-a" -> "node-group-01-a-" # forces replacement
        # ...
    }

  # module.eks.module.self_managed_node_group["node-group-01-a"].aws_iam_instance_profile.this[0] must be replaced
+/- resource "aws_iam_instance_profile" "this" {
      ~ name_prefix = "eks-instance-profile" -> "eks-instance-profile-" # forces replacement
        # ...
    }
```

### Expected plan

```
  # module.eks.module.self_managed_node_group["node-group-01-a"].aws_autoscaling_group.this[0] will be updated in-place
~ resource "aws_autoscaling_group" "this" {
        # ...
    }

  # module.eks.module.self_managed_node_group["node-group-01-a"].aws_launch_template.this[0] will be updated in-place
~ resource "aws_launch_template" "this" {
        # ...
    }

  # module.eks.module.self_managed_node_group["node-group-01-a"].aws_iam_instance_profile.this[0] will be updated in-place
~ resource "aws_iam_instance_profile" "this" {
        # ...
    }
```

## Possible fix

A possible solution to this issue is to add to the internal modules an optional variable `prefix_separator`, already present in the main module with the same meaning. This variable defaults to the hyphen, so if not explicitly set it does not involve any change.
I proposed this solution in a [PR](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2566#issue-1666690361) for the self-managed-node-group module.

**Comment by bryantbiggs** [comment]
as mentioned in the linked PR - thank you but we are not looking to add this into the module
