### ISSUE TITLE
Support worker launch template delete_on_termination for network interfaces

### ISSUE THREAD

**Issue by duanshiqiang** [terraform-aws-modules/terraform-aws-eks#257]
# I have issues

## I'm submitting a

* [x] feature request

## What is the current behavior?

delete_on_termination for worker launch template's network interfaces is not able to specify.

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by skang0601** [comment]
This a fairly simple addition, I’ll open up a PR for this.

**Comment by duanshiqiang** [comment]
> This is a fairly simple addition, I’ll open up a PR for this.

Thanks!

**Comment by skang0601** [comment]
Sorry haven't had time to look at this until recently. I've been trying to figure out the default behavior on these network interfaces but it's been inconsistent from my testing and the AWS docs doesn't reveal much from my digging. I'll do some more testing over the weekend.

**Comment by duanshiqiang** [comment]
I also can't find relevant info from AWS documentation. But in our AWS account, those interfaces will be left there even after the node is terminated.

**Comment by max-rocket-internet** [comment]
This was added.
