### ISSUE TITLE
Change made to default of cluster_endpoint_private_access & cluster_endpoint_public_access without mention in the changelog

### ISSUE THREAD

**Issue by JHunsGlobal** [terraform-aws-modules/terraform-aws-eks#2574]
## Description

Either I've missed where this change is mention, but it is a breaking change when going from v18.x to v19.x
The default of cluster_endpoint_private_access changed from false to true and the default for cluster_endpoint_public_access from true to false.

This obviously now causes our api endpoint to timeout. Easy to fix, but very annoying that there was no mention of it in the ChangeLog.

Thought I'd raise it as an issue incase anyone faces an api timeout when upgrading from v18 to v19.

**Comment by bryantbiggs** [comment]
It is documented https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md
