### ISSUE TITLE
coredns times out

### ISSUE THREAD

**Issue by funes79** [terraform-aws-modules/terraform-aws-eks#2578]
## Description
- [x ] ✋ I have searched the open/closed issues and my issue is not listed. I have found issues where others had similar problems, but the next terraform apply run was ok. In my case it always hangs, the first time when the EKS is created and also the next terraform apply.

```
module.eks.aws_eks_addon.this["coredns"]: Still creating... [4m50s elapsed]
module.eks.aws_eks_addon.this["coredns"]: Still creating... [5m0s elapsed]
...
module.eks.aws_eks_addon.this["coredns"]: Still creating... [20m0s elapsed]

Error: unexpected EKS Add-On (eks_skadi:coredns) state returned during creation: timeout while waiting for state to become 'ACTIVE' (last state: 'CREATING', timeout: 20m0s)
Warning:  Running terraform apply again will remove the kubernetes add-on and attempt to create it again effectively purging previous add-on configuration
```

Cluster version 1.25.
Module version 19.12.0.

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "19.12.0" 
  ...
  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
      addon_version     = "v1.9.3-eksbuild.2"
    }
  ...
```

## Versions

- Module version: 19.12.0

- Terraform version: 1.0.9

- Provider version(s):
terraform-aws-modules/eks/aws 19.12.0
terraform-aws-modules/kms/aws 1.1.0
terraform-aws-modules/iam/aws 5.17.0

Create a cluster with corends addon. Run terraform apply, the first time it hangs 20minutes and times out. Then next time the plan wants to replace and recreate the coredns, and hangs again.

## Expected behavior

It should create coredns addon within couple of minutes.

**Comment by bryantbiggs** [comment]
did you check the logs for why its waiting to be scheduled? (note - its not a module issue but it will tell you where to look)

**Comment by funes79** [comment]
No I havent. Can you be more specific how to debug?

**Comment by bryantbiggs** [comment]
https://jamesdefabia.github.io/docs/user-guide/kubectl/kubectl_logs/

**Comment by funes79** [comment]
Yes, it was a security group blocking ecr endpoint access. Problem solved, thanks.
