### ISSUE TITLE
Question: Where are mixed instances policy variables set in the .tf code (17.24.0)

### ISSUE THREAD

**Issue by timlaroche** [terraform-aws-modules/terraform-aws-eks#2583]
## Description

Quick question; where is the terraform logic that default sets these mixed-instance variables? https://github.com/terraform-aws-modules/terraform-aws-eks/blob/e90c877a741ab3cc4215376a70f7bcc360b6a3d2/locals.tf#L104

I need a bit more help to see exactly where `if mixed_instance and launchtemplates: set these variables`

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 17.24.0

- Terraform version: n/a

- Provider version(s): n/a

**Comment by bryantbiggs** [comment]
v17.x is no longer supported - I recommend updating to v19.x
