### ISSUE TITLE
EKS managed group example times out during CoreDNS addon creation

### ISSUE THREAD

**Issue by vishwa-trulioo** [terraform-aws-modules/terraform-aws-eks#2585]
## Description

I am attempting to create an EKS cluster with an EKS managed node group. I used the example [eks_managed_node_group](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/eks_managed_node_group) provided with this module.
The expected configuration of the cluster is as follows,
- EKS cluster with majority of the default settings set automatically by the module.
- Enable addons: `coredns`, `kube-proxy`, `vpc-cni`
- EKS-managed node group with 2 nodes

Few things to note modifications, (I don't think this will cause the any errors)
1. Create the cluster in an existing VPC. (The VPC doesn't have any K8S specific labels applied)
2. Referenced a KMS key created outside of the module and passed into the module.
3. I didn't enable IPv6 addresses for the Nodes, pods.

Also, I can confirm,
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: `19.13.1`
- Terraform version: `1.4.5`
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v4.64.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.20.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```
## Reproduction Code [Required]
```
provider "aws" {
  region = "us-west-2"
}

terraform {
  required_version = ">= 1.3.6"
  required_providers {
    aws = ">= 4.64.0"
    kubernetes = ">=2.20"
  }
}

provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
  }
}

module "eks" {
  source = "terraform-aws-modules/eks/aws"
  version = "~> 19.13"

  cluster_version                 = null # 1.25
  cluster_name                    = "my-cluster"


  vpc_id     = "vpc-XXXXXXX"
  subnet_ids = ["subnet-xxxxxx", "subnet-yyyyy", "subnet-zzzzzzz"]
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  manage_aws_auth_configmap = true

  enable_irsa = true

  create_kms_key = false
  cluster_encryption_config = {
    resources        = ["secrets"]
    provider_key_arn = aws_kms_key.eks.arn
  }

  cluster_addons = {
    coredns = {
      most_recent = true
    }
    kube-proxy = {
      most_recent = true
    }
    vpc-cni = {
      most_recent              = true
      before_compute           = true
      service_account_role_arn = module.vpc_cni_irsa.iam_role_arn
      configuration_values = jsonencode({
        env = {
          ENABLE_PREFIX_DELEGATION = "true"
          WARM_PREFIX_TARGET       = "1"
        }
      })
    }
  }

  eks_managed_node_group_defaults = {
    ami_type       = "AL2_x86_64"
    instance_types = ["t3.medium"]
    iam_role_attach_cni_policy = true
  }

  eks_managed_node_groups = {
    default_node_group = {
      name = "my-cluster-managed"
      use_name_prefix = false
      use_custom_launch_template = false
      subnet_ids = ["subnet-xxxxxx", "subnet-yyyyy", "subnet-zzzzzzz"]
      instance_types = ["t3.medium"]
      disk_size = 30

      min_size     = 1
      desired_size = 2
      max_size     = 3
      tags = {
        Name = "my-cluster-managed"
      }
    }
  }

  tags = {
    Name = "my-cluster"
  }
}

resource "aws_kms_key" "eks" {
  description             = "EKS Secret Encryption Key"
  deletion_window_in_days = 7
  enable_key_rotation     = true

  tags = {
    Name = "my-cluster"
  }
}

module "vpc_cni_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 5.0"

  role_name_prefix      = "VPC-CNI-IRSA"
  attach_vpc_cni_policy = true
  vpc_cni_enable_ipv6   = true

  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:aws-node"]
    }
  }
}
```

1. I just run the regular terraform commands, that's all,
```
terraform init
terraform plan
terraform apply -auto-approve
```
2. I re-ran the terraform apply to see if the kubernetes addons gets recreated. It is still times out and produces the same error.

## Expected behavior

Assuming this is a really simple setup, I expected it to create the cluster and the node groups without any error and produce a stable healthy EK cluster.

## Actual behavior

Here is my observations,
1. The terraform apply command eventually times out and fails trying to configure the `coredns`. Here is the last few lines before the error
```
module.eks.aws_eks_addon.this["coredns"]: Still creating... [19m30s elapsed]
module.eks.aws_eks_addon.this["coredns"]: Still creating... [19m40s elapsed]
module.eks.aws_eks_addon.this["coredns"]: Still creating... [19m50s elapsed]
module.eks.aws_eks_addon.this["coredns"]: Still creating... [20m0s elapsed]
╷
│ Error: unexpected EKS Add-On (my-cluster:coredns) state returned during creation: timeout while waiting for state to become 'ACTIVE' (last state: 'CREATING', timeout: 20m0s)
│ [WARNING] Running terraform apply again will remove the kubernetes add-on and attempt to create it again effectively purging previous add-on configuration
│ 
│   with module.eks.aws_eks_addon.this["coredns"],
│   on .terraform/modules/eks/main.tf line 382, in resource "aws_eks_addon" "this":
│  382: resource "aws_eks_addon" "this" {
```
2. In the AWS console the `CoreDNS` and `VPC CNI` plugins are marked `Degraded`.
4. In the AWS console, I can see the node group, but I can see any nodes listed. But I do see 2 EC2 instances in the EC2 service page.
5. Additionally, I see this message on the cluster page, probably it is something to do with the [aws-auth ConfigMap](https://docs.aws.amazon.com/eks/latest/userguide/security_iam_troubleshoot.html#security-iam-troubleshoot-cannot-view-nodes-or-workloads)
> Your current IAM principal doesn’t have access to Kubernetes objects on this cluster.

### Terminal Output Screenshot(s)
Outputs, added to 'Actual behavior section'.

## Additional context
1. It would be good to add code snippet in an example on how to manage the IAM Authenticator ConfigMap added to an example on how to add/trust roles or user to a EKS cluster using this module.
2. The AWS console offer disabling the encryption for secrets. How do accomplish that from this module?
3. If there is s certain procedure to follow for these scenarios, (e.g. first add code for creating cluster -> then add code for node group -> Then enable addons -> etc.) I would like that stated in the readme.

**Comment by BarnumD** [comment]
This was occuring for me because I didn't enable ipv6 on the nodes, and yet `vpc_cni_enable_ipv6 ` was still set to `true` in the `vpc_cni_irsa`.  So look for other areas that are still using ipv6.

**Comment by bryantbiggs** [comment]
this usually happens if something is mis-configured which does not allow the CoreDNS pods come up correctly. It looks you have some mis-configurations (either the cluster should be IPv6 or the VPC CNI should have the IPv4 policy)
