### ISSUE TITLE
When adding the VPC-CNI plugin the module is creating a security group to allow all the traffic between control plane and dataplane

### ISSUE THREAD

**Issue by alinalex1392** [terraform-aws-modules/terraform-aws-eks#2588]
## Description

I am configuring the EKS module to add the VPC CNI plugin, after creating the cluster I could see that I have a security group that allows the connection to all ports and protocols between the data plane and control plane, is this the normal behavior?
The security group is attached to the ENI interfaces. I have created 4 ENI interfaces, one for each availability zone.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

  version = "19.10.0"

- Terraform version:
 
Terraform v1.4.2
on linux_amd64

- Provider version(s):

+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.57.1
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.18.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4

## Reproduction Code [Required]

Configure the VPC CNI addon plugin using the EKS module with 4 subnets attached to 4 ENIs that span across all the availability zones.

## Expected behavior

I was not expecting to have the sg attached to both the control plane and data plane to allow all the traffic.

**Comment by bryantbiggs** [comment]
Please provide a reproduction to troubleshoot
