### ISSUE TITLE
Verify AWS EKS module in Terraform Module Registry

### ISSUE THREAD

**Issue by Jeeppler** [terraform-aws-modules/terraform-aws-eks#259]
# I have issues

## I'm submitting a...

* [x] feature request

## What is the current behavior?

Currently this AWS EKS module is not a verified module, therefore the module is harder to find in the Terraform module registry.

## What's the expected behavior?

The provision count of this module is above 40_000, has active maintainers and a community around it. It would be nice to verify this module in the Terraform module registry. This way it is easier to distinguish this well maintained module from the many other EKS modules in the Terraform registry. In addition, it is just easier to find.

## Any other relevant information?

Another module which reached a verified status is the [VPC module](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/). The VPC module is an important building block and can be used with this AWS EKS module. It should be possible to contact the VPC module maintainer and ask about the module verification process.

**Comment by max-rocket-internet** [comment]
Sounds great but I have no idea about any of this 😃

I think @antonbabenko will know though?

**Comment by antonbabenko** [comment]
I would approve this one, for sure.

Though, I am not aware of the verification process nowadays.

**Comment by Jeeppler** [comment]
@antonbabenko Thanks for your support.

Is the verification process done by HashiCorp employees or by community members? If the verification process is done by HashiCorp employees do you know whom to ask?

**Comment by antonbabenko** [comment]
It is done by HashiCorp employees, but I don't know who to ask.

**Comment by Jeeppler** [comment]
I created an issue in the Terraform repository asking for a [How to guide to verify registry modules](https://github.com/hashicorp/terraform/issues/20173). Let's see what the responses will be.

**Comment by brant4test** [comment]
Great! Looking forward to it.

**Comment by brandoconnor** [comment]
Thanks for submitting this. To tell the full story, I tried to get this module and my ALB module verified early on and received a response (3 months later) with some uncertainty and redirection process-wise. My attempts to follow up didn't get anything further. Out of the blue, the verified badge showed up on the ALB module... totally unclear to me how, when, or why 🤷‍♀️ . I somewhat expect the same thing will happen here.

Let's keep this closed for the moment to declutter the issues a bit as there's really no further action to take on our end. Feel free to chime back in with any updates.
