### ISSUE TITLE
How to run workers and pods on Secondary CIDR of VPC

### ISSUE THREAD

**Issue by iahmad-khan** [terraform-aws-modules/terraform-aws-eks#2591]
We are running out of IP addresses for EKS workers and pods, and CNI custom networking seems complex.

Here in the blog post, option-2, they propose we can add another CIDER to VPC and use it for EKS workers and Pods without CNI usage. 

https://aws.amazon.com/blogs/containers/optimize-ip-addresses-usage-by-pods-in-your-amazon-eks-cluster/

How can we do the AWS EKS-related changes using this module?

**Comment by bryantbiggs** [comment]
see https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/vpc-cni-custom-networking

**Comment by iahmad-khan** [comment]
@bryantbiggs thanks, that is the option-1 in the post, i am aiming for option-2

**Comment by bryantbiggs** [comment]
its the same but you need to ensure the control plane subnets are different than the subnets used by the nodes/pods. You can set the control plane subnet via `control_plane_subnet_ids`

**Comment by iahmad-khan** [comment]
@bryantbiggs is there some example that doesn't use ani CNI-related config, also currently we are using the module version 13.1.0, it is possible to do it if we currently stay on that version

**Comment by iahmad-khan** [comment]
Yes, I can leave the existing subnets as it is, but I want to create a new cider that can be used by workers and pods without having to do any CNI related stuff

**Comment by iahmad-khan** [comment]
@bryantbiggs Currently we are on version 13.2.1 , that looks very old and doesnt seem to have support for custom cider stuff, what should be the upgrade path if we need to upgrade to latest? upgrading directly from 13.2.1 to latest is possible?
