### ISSUE TITLE
VPC CNI custom networking - add support for ENIConfig CRD

### ISSUE THREAD

**Issue by Constantin07** [terraform-aws-modules/terraform-aws-eks#2593]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
Create `ENIConfig` CRD as an option when specified so that worker nodes can use secondary CIDR block IP range for pods.
Mode details: https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html

## Describe the solution you'd like.
Add support in this TF module to create `ENIConfig` CRDs after control plane is provisioned but before the manage node group is deployed so that I don't have to manually recycle worker nodes.

## Describe alternatives you've considered.
Using at the moment:
1. Spin up EKS control plane & managed node group.
2. Run a separate Terraform plan to create CNI custom networking `ENIConfig` CRDs. (inconvenient), snippet as an example:
```terraform

data "aws_availability_zones" "available" {}

data "aws_eks_cluster" "this" {
  name = local.eks_cluster_name
}

# Subnets for EKS Pods
data "aws_subnets" "ekspods" {
  for_each = toset(local.azs)

  filter {
    name   = "vpc-id"
    values = [data.aws_eks_cluster.this.vpc_config[0].vpc_id]
  }

  filter {
    name   = "tag:Name"
    values = ["*eks-pods*"]
  }

  filter {
    name   = "availability-zone"
    values = [each.value]
  }
}

# Security group used by EKS worker nodes (primary ENI).
# Assign it for secondary ENI too as it has all required permissions.
data "aws_security_group" "node" {
  filter {
    name   = "vpc-id"
    values = [data.aws_eks_cluster.this.vpc_config[0].vpc_id]
  }

  filter {
    name   = "tag:Name"
    values = ["${var.project}-${var.environment}-${var.component}-node*"]
  }
}

locals {
  eks_cluster_name = some_value_here
  azs              = slice(data.aws_availability_zones.available.names, 0, 3)
}

################################################################################
# VPC-CNI Custom Networking ENIConfig
################################################################################

resource "kubernetes_manifest" "eni_config" {
  for_each = { for key, value in data.aws_subnets.ekspods : key => value.ids[0] }

  manifest = {
    apiVersion = "crd.k8s.amazonaws.com/v1alpha1"
    kind       = "ENIConfig"

    metadata = {
      name = each.key
    }

    spec = {
      securityGroups = [
        data.aws_security_group.node.id,
      ]
      subnet = each.value
    }
  }
}

# The default AWS provider in the default region
provider "aws" {
  region = var.region
}

data "aws_eks_cluster_auth" "this" {
  name = local.eks_cluster_name
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.this.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.this.token
}

terraform {
  required_version = ">= 1.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.54"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.18"
    }
  }
}

```
4. Refresh (terminate) worker nodes to pick up new config

## Additional context
AWS VPC CNI custom networking - https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html

**Comment by bryantbiggs** [comment]
please see the example here which demonstrates how to use this module to create a cluster with custom networking enabled https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/vpc-cni-custom-networking

We have no plans at this time to add kubernetes resources to this module (outside of the aws-auth configmap which is currently a requirement)
