### ISSUE TITLE
AWS EKS Terraform : provider.stdio: received EOF, stopping recv loop: err=“rpc error: code = Unavailable desc = error reading from server: EOF 

### ISSUE THREAD

**Issue by yogisdm** [terraform-aws-modules/terraform-aws-eks#2595]
## Description
I am trying to create EKS cluster with the available eks terraform module - https://github.com/terraform-aws-modules/terraform-aws-eks. The eks cluster is getting created successfully, but when it is executing the mapUsers section, where I have updated one IAM user to be added to kubeconfig file, there it is getting failed.

- [ ] ✋ I have searched the open/closed issues - https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2009 like this one and similar issues. But still I am getting "aws-auth" does not exist issue.

## Versions

- Module version [Required]:
     -- 19.13.1 -  https://github.com/terraform-aws-modules/terraform-aws-eks
- Terraform version:
        v1.4.5
- Provider version(s):
       -- AWS : v4.64.0
       -- Kubernetes : v2.20.0
       

## Reproduction Code [Required]
```
provider "aws" {
  region     = "us-east-1"
}

//data "aws_eks_cluster" "default" {
//  name = module.eks_cluster_creation.cluster_id
//}

data "aws_eks_cluster_auth" "default" {
  name = module.eks_cluster_creation.cluster_name
}

provider "kubernetes" {
  host                   = module.eks_cluster_creation.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks_cluster_creation.cluster_certificate_authority_data)
  token = data.aws_eks_cluster_auth.default.token
}

terraform {
  backend "s3" {
    bucket = "statefile"
    key    = "tf/eks.tf"
    region = "us-east-1"
  }
}

locals {
  name   = "Sandbox-Cluster-Test"
  region = "us-east-1"
  azs      = slice(data.aws_availability_zones.myaz.names, 0, 3)
  tags = {
    Example    = local.name
    GithubRepo = "terraform-aws-eks"
    GithubOrg  = "terraform-aws-modules"
  }
}

data "aws_vpc" "myvpc"{
filter {
 name = "tag:Name"
 values = ["VPC-DevOps"]
}
}
data "aws_availability_zones" "myaz" {
  state = "available"
}

resource "aws_subnet" "public-subnets" {
  count = 3
  vpc_id            = data.aws_vpc.myvpc.id
  cidr_block = var.public-subnet-cidr1[count.index]
   tags = {
    Name = "Public-k8s-subnet"
  }
    availability_zone = "${data.aws_availability_zones.myaz.names[count.index]}"
  map_public_ip_on_launch = true
}

data "aws_route_table" "publicrt" {
   vpc_id            = data.aws_vpc.myvpc.id
  filter {
   name = "tag:Name"
   values = ["public-route-table"]
  }
}

resource "aws_route_table_association" "public-route-1" {
  count = "${length(var.public-subnet-cidr1)}"
  subnet_id = "${element(aws_subnet.public-subnets.*.id, count.index)}"
  route_table_id = data.aws_route_table.publicrt.id
}

module "eks_nodegroup_role" {
source = "./eks-role"
}

module "eks_cluster_creation" {
  source = "terraform-aws-modules/eks/aws"
  version = "19.13.1"
  cluster_name                   = local.name
  
  iam_role_arn = module.eks_nodegroup_role.eks_role
  cluster_endpoint_public_access = true
  cluster_endpoint_private_access = false
  subnet_ids        =  flatten([aws_subnet.public-subnets[*].id])
  vpc_id    = data.aws_vpc.myvpc.id
  manage_aws_auth_configmap = true
    aws_auth_users = [
    {
      userarn  = "arn:aws:iam::xxxxxxxxx:user/usertest"
      username = "usertest"
      groups   = ["system:masters"]
    }
  ]
  
    aws_auth_accounts = [
    "xxxxxxxxx"
  ]
  
  depends_on = [module.eks_nodegroup_role]
}

resource "null_resource" "kubectl" {
    provisioner "local-exec" {
        command = "aws eks --region us-east-1 update-kubeconfig --name ${local.name}"
    }
	depends_on = [module.eks_cluster_creation]
}
```

===============================================================
EKS-Role Module
===============================================================
```
resource "aws_iam_role" "eks-iam-role" {
 name = "sandboxcluster-eks-iam-role"

 path = "/"

 assume_role_policy = <<EOF
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Principal": {
    "Service": "eks.amazonaws.com"
   },
   "Action": "sts:AssumeRole"
  }
 ]
}
EOF
}

resource "aws_iam_role_policy_attachment" "AmazonEKSClusterPolicy" {
 policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
 role    = aws_iam_role.eks-iam-role.name
}
resource "aws_iam_role_policy_attachment" "AmazonEC2ContainerRegistryReadOnly-EKS" {
 policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
 role    = aws_iam_role.eks-iam-role.name
}

resource "aws_iam_role" "workernodes" {
  name = "eks-node-group-example"
 
  assume_role_policy = jsonencode({
   Statement = [{
    Action = "sts:AssumeRole"
    Effect = "Allow"
    Principal = {
     Service = "ec2.amazonaws.com"
    }
   }]
   Version = "2012-10-17"
  })
 }
 
 resource "aws_iam_role_policy_attachment" "AmazonEKSWorkerNodePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
  role    = aws_iam_role.workernodes.name
 }
 
 resource "aws_iam_role_policy_attachment" "AmazonEKS_CNI_Policy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  role    = aws_iam_role.workernodes.name
 }
 
 resource "aws_iam_role_policy_attachment" "EC2InstanceProfileForImageBuilderECRContainerBuilds" {
  policy_arn = "arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds"
  role    = aws_iam_role.workernodes.name
 }
 
 resource "aws_iam_role_policy_attachment" "AmazonEC2ContainerRegistryReadOnly" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
  role    = aws_iam_role.workernodes.name
 }
```

- Deploying EKS cluster with manage_aws_auth_configmap = true using the eks-terraform module.
- 

## Expected behavior

Along with EKS cluster creation, the iam users should be added to the aws-config file.

## Actual behavior

Getting the error "aws-auth" does not exist after the terraform apply command

### Terminal Output Screenshot(s)

[DEBUG] [aws-sdk-go]
 [31m╷ [0m [0m
 [31m│ [0m  [0m [1m [31mError:  [0m [0m [1mThe configmap "aws-auth" does not exist [0m
 [31m│ [0m  [0m
 [31m│ [0m  [0m [0m  with module.eks_cluster_creation.kubernetes_config_map_v1_data.aws_auth[0],
 [31m│ [0m  [0m  on .terraform/modules/eks_cluster_creation/[main.tf](http://main.tf/) line 553, in resource "kubernetes_config_map_v1_data" "aws_auth":
 [31m│ [0m  [0m 553: resource "kubernetes_config_map_v1_data" "aws_auth"  [4m{ [0m [0m
 [31m│ [0m  [0m
 [31m╵ [0m [0m
2023-04-28T12:07:03.961Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-04-28T12:07:03.961Z [DEBUG] provider: plugin process exited: path=.terraform/providers/[registry.terraform.io/hashicorp/kubernetes/2.20.0/linux_amd64/terraform-provider-kubernetes_v2.20.0_x5](http://registry.terraform.io/hashicorp/kubernetes/2.20.0/linux_amd64/terraform-provider-kubernetes_v2.20.0_x5) pid=15195
2023-04-28T12:07:03.966Z [DEBUG] provider: plugin exited

================================================================================
**Apart from the aws-auth does not exist, I also see the below error:
[DEBUG] provider.stdio: received EOF, stopping recv loop: err=“rpc error: code = Unavailable desc = error reading from server: EOF”.**
**Could anyone please help here whether it is issue with way mapUser parameter is defined or something else?**

**Comment by bryantbiggs** [comment]
unfortunately there are a number of errors in your code which I suspect are leading to the issues you are experiencing. I would suggest looking at the examples we have provided and working backwards from there.
