### ISSUE TITLE
Output EKS cluster ID using id attribute

### ISSUE THREAD

**Issue by nicosingh** [terraform-aws-modules/terraform-aws-eks#2599]
Hey everyone! Just an innocent question 🤔 My apologies in advance if it is a duplicate!

I'm seeing that version 19 of the module changes the source of `cluster_id` output ([release notes](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v19.0.0)), which used to be like:

```terraform
output "cluster_id" {
  description = "The name/id of the EKS cluster. Will block on cluster creation until the cluster is really ready"
  value       = try(aws_eks_cluster.this[0].id, "")
}
```
([reference](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v18.20.2/outputs.tf#L20-L23))

From version 19 onwards has been updated to:

```terraform
output "cluster_id" {
  description = "The ID of the EKS cluster. Note: currently a value is returned only for local EKS clusters created on Outposts"
  value       = try(aws_eks_cluster.this[0].cluster_id, null)
}
```
([reference](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v19.0.0/outputs.tf#L20-L23))

The question: is there any reason to **not output** the new attribute `id` returned by the `aws_eks_cluster` resource? I see that the module from v19 onwards only outputs `cluster_id` (which is fine, understanding their new purpose for Outposts) and also `name` (which is an input argument, by the way, and doesn't seem necessary to be returned back). This means to have something like:

```terraform
output "cluster_id" {
  description = "The ID of the EKS cluster. Note: currently a value is returned only for local EKS clusters created on Outposts"
  value       = try(aws_eks_cluster.this[0].cluster_id, "")
}

# adding new output
output "id" {
  description = "Name of the cluster"
  value       = try(aws_eks_cluster.this[0].id, "")
}

# this is given as input, do we really need it?
output "cluster_name" {
  description = "The name of the EKS cluster"
  value       = try(aws_eks_cluster.this[0].name, "")
}
```

The purpose of that new output is to bring back the functionality of blocking the usage of the cluster ID variable to the creation of the EKS cluster. If we use the variables `cluster_id` or `cluster_name` for that purpose (as we used to in versions <19) it won't work in all scenarios because `cluster_id` only works on Outposts and `cluster_name` doesn't wait the EKS cluster to be created.

Please let me know your thoughts! I'd love to create a new PR if necessary.

**Comment by bryantbiggs** [comment]
what is the underlying problem you are trying to solve?

**Comment by nicosingh** [comment]
@bryantbiggs to block the usage of the EKS module to the creation of the cluster, for instance to be used later with `kubernetes` and `helm` providers.

I know we can do a workaround in our own Terraform projects to block the variable for cluster creation anyway, like:

```terraform
# create EKS cluster
module "cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "19.13.1"

  cluster_name = var.cluster_name
# . . .
}
data "aws_eks_cluster" "cluster" {
  name       = var.cluster_name
  depends_on = [module.cluster]
}
output "id" {
  value = data.aws_eks_cluster.cluster.id
}
```

But it just feels far simpler to use the attributes of the `aws_eks_cluster` that are already there (like using their `id` attribute).

**Comment by bryantbiggs** [comment]
we show an example with those providers - it works without issue using the current outputs https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/karpenter

**Comment by nicosingh** [comment]
Oh! I see 🤔 You use `module.eks.cluster_endpoint` and `module.eks.cluster_certificate_authority_data` to block the providers for Cluster creation, instead of `cluster_id` only.

That makes the trick, then 😀 Please feel free to close the issue. I truly appreciate your help!.
