### ISSUE TITLE
Eks version update

### ISSUE THREAD

**Issue by s9r-5** [terraform-aws-modules/terraform-aws-eks#2607]
I using this module with v18.21.0 , do I need to update this version to update my eks cluster version because I am getting this error : Unsupported Kubernetes minor version update from 1.22 to 1.25.

**Comment by bryantbiggs** [comment]
Kubernetes, and EKS, only allow one minor version incremental upgrades. So if your control plane is currently on 1.22 then you can only go up to 1.23 with an in-place upgrade, then 1.24, then 1.25, etc.

**Comment by s9r-5** [comment]
Thanks , I will try to update eks version one by one.
