### ISSUE TITLE
map_roles not being updated if the cluster has been initially created without map_roles

### ISSUE THREAD

**Issue by trobert2** [terraform-aws-modules/terraform-aws-eks#261]
# I have issues

## I'm submitting a...

* [x] bug report

## What is the current behavior?
When the module has created a cluster and we want to add new mappings to the `aws-auth` config map, for example `map_roles`, the new roles are not added after a new `terraform apply`

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Create a cluster:
```
module "test-cluster" {
  source       = "terraform-aws-modules/eks/aws"
  cluster_name = "test"
  subnets      = ["${module.eks-network-stack.subnet_ids}"]
  vpc_id       = "${module.eks-network-stack.vpc_id}"

  worker_groups = [
    {
      instance_type = "m4.large"
      asg_max_size  = 5
    }
  ]

  tags = {
    Environment = "test"
  }
}
```
Update the configuration like so and try to apply it:
```
module "test-cluster" {
  source       = "terraform-aws-modules/eks/aws"
  cluster_name = "test"
  subnets      = ["${module.eks-network-stack.subnet_ids}"]
  vpc_id       = "${module.eks-network-stack.vpc_id}"

  map_roles    = [
    {
      role_arn = "arn:aws:iam::000000000:role/EKSAdmin"
      username = "adminuser:{{SessionName}}"
      group    = "system:masters"
    }
  ]

  worker_groups = [
    {
      instance_type = "m4.large"
      asg_max_size  = 5
    }
  ]

  tags = {
    Environment = "test"
  }
}
```

## What's the expected behavior?
The new `map_roles` values would appear in the config map on the EKS cluster.

## Are you able to fix this problem and submit a PR? Link here if you have already.
Not familiar with the module at this time, sorry.
## Environment details

* Affected module version: 2.1.0
* OS: alpine, macOS
* Terraform version: 0.11.11

**Comment by max-rocket-internet** [comment]
It's because you are missing the `map_roles_count` variable 🙂

**Comment by trobert2** [comment]
@max-rocket-internet thank you, this fixed my issue.
Any chance to improve the docs to say that one is related to the other?
How about error out when one is mentioned without the other?

**Comment by max-rocket-internet** [comment]
Well it is in the readme and it is very common in Terraform due to the `value of count cannot be computed` error.

In saying that, I have also fallen for this mistake more than once also.

> How about error out when one is mentioned without the other?

Sure, how do you do that?

**Comment by trobert2** [comment]
@max-rocket-internet I am pretty new to terraform, but wasn't there a `length` function?
I am sure I have seen this somewhere `count = "${length(var.names)}"` https://www.terraform.io/docs/configuration/interpolation.html#length-list-

**Comment by antonbabenko** [comment]
@trobert2 You are right, there is `length` function in Terraform, but it does not work with all types of values (to put it this way). This is the reason for `map_roles_count` variable.

**Comment by max-rocket-internet** [comment]
> I am pretty new to terraform, but wasn't there a length function?

Welcome to Terraform. This is just one of the many super annoying language limitations 😃
