### ISSUE TITLE
Unable create new Cluster with version 19.13.1 (latest)

### ISSUE THREAD

**Issue by quyennguyenvan** [terraform-aws-modules/terraform-aws-eks#2612]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

terraform -v
Terraform v1.3.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.66.1
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.20.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4

Your version of Terraform is out of date! The latest version
is 1.4.6. You can update by downloading from https://www.terraform.io/downloads.html

<on-windows-11>

## Reproduction Code [Required]

1. have using workspace 
2. Have cleared the local cached

3. step of produce

terraform init
terraform plan

Code Snippet to Reproduce

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "19.13.1"
  cluster_name    = var.cluster_name
  cluster_version = var.cluster_version

  enable_irsa = true

  create_iam_role = true
  iam_role_name   = "${var.cluster_name}-ClusterRole"

  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {
      most_recent = true
    }
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }
  cluster_enabled_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler",
  ]

  vpc_id                               = var.vpc_id
  subnet_ids                           = var.private_subnet_ids
  control_plane_subnet_ids             = var.control_plane_subnet_ids
  cluster_endpoint_public_access       = true
  cluster_endpoint_public_access_cidrs = var.cluster_endpoint_public_access_cidrs

  cluster_security_group_name = "${var.cluster_name}-eks-cluster-sg"

  eks_managed_node_group_defaults = {
    create_iam_role = true
    ami_type        = "AL2_x86_64"
    disk_size       = 100
    instance_types  = var.eks_managed_node_group_defaults_instance_types
  }

  eks_managed_node_groups = {
    blue = {}
    green = {
      min_size     = 1
      max_size     = var.max_size
      desired_size = 1

      instance_types = var.instance_types
      capacity_type  = "ON_DEMAND"

      taints = {
        dedicated = {
          key    = "dedicated"
          value  = "gpuGroup"
          effect = "NO_SCHEDULE"
        }
      }
      update_config = {
        max_unavailable_percentage = 50 # or set `max_unavailable`
      }
    }
  }
  # aws-auth configmap
  manage_aws_auth_configmap = var.manage_aws_auth_configmap
  aws_auth_users            = var.aws_auth_users
  aws_auth_accounts         = var.aws_auth_accounts


  tags = var.default_tags

}
```

## Expected behavior

The terraform plan should be successful

## Actual behavior

│ Error: Invalid for_each argument
│
│   on .terraform\modules\eks.eks\modules\eks-managed-node-group\main.tf line 434, in resource "aws_iam_role_policy_attachment" "this":
│  434:   for_each = { for k, v in toset(compact([
│  435:     "${local.iam_role_policy_prefix}/AmazonEKSWorkerNodePolicy",
│  436:     "${local.iam_role_policy_prefix}/AmazonEC2ContainerRegistryReadOnly",
│  437:     var.iam_role_attach_cni_policy ? local.cni_policy : "",
│  438:   ])) : k => v if var.create && var.create_iam_role }
│     ├────────────────
│     │ local.cni_policy is a string, known only after apply
│     │ local.iam_role_policy_prefix is a string, known only after apply
│     │ var.create_iam_role is true
│     │ var.iam_role_attach_cni_policy is true
│
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this
│ resource.
│
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.

**Comment by bryantbiggs** [comment]
I am not able to reproduce that with the config provided

**Comment by quyennguyenvan** [comment]
hi @bryantbiggs , there is my config
```
 eks_config = {
        cluster_name                                   = "doosan-app-dev-env"
        cluster_version                                = "1.24"
        max_size                                       = 10
        eks_managed_node_group_defaults_instance_types = ["t2.medium"]
        instance_type                                  = "t2.medium"
        instance_types                                 = ["t2.medium"]
        manage_aws_auth_configmap                      = true
        aws_auth_users = [
          {
            userarn  = "arn:aws:iam::629526135429:user/joe-dev"
            username = "joe-dev"
            groups   = ["system:masters"]
          },
        ]
        aws_auth_accounts                    = ["629526135429", ]
        cluster_endpoint_public_access_cidrs = ["0.0.0.0/0"]
      }
```

**Comment by bryantbiggs** [comment]
still not able to reproduce

**Comment by quyennguyenvan** [comment]
@bryantbiggs  that my repo https://github.com/quyennguyenvan/k8s_provision
please check it

**Comment by bryantbiggs** [comment]
Remove all of these https://github.com/quyennguyenvan/k8s_provision/blob/401ba1aef733ebc7f1e0dd48c108c7bb77775ea4/main.tf#L71-L73

That is the issue - see why reproductions are important 😬

**Comment by quyennguyenvan** [comment]
hi @bryantbiggs  why can no depends_on the vpc module done before create the EKS cluster ?

**Comment by bryantbiggs** [comment]
1. You don't need it
2. Hashicorp states this is not recommended and will cause issues when used across modules like this (like the one you are reporting) https://github.com/hashicorp/terraform/issues/30340

**Comment by quyennguyenvan** [comment]
oh, thank you so much @bryantbiggs , 
i will close this issue, thank for your support
