### ISSUE TITLE
No addon for Load Balancer Controller

### ISSUE THREAD

**Issue by xgp** [terraform-aws-modules/terraform-aws-eks#2616]
## Description

The documentation in the README indicates that there is a cluster addon available for the AWS Load Balancer Controller, however, there is no indication of a name to use, no example of how to use it, and I can't find a name when running `aws eks describe-addon-versions |grep addonName`:
```
            "addonName": "factorhouse_kpow",
            "addonName": "datree_engine-pro",
            "addonName": "kube-proxy",
            "addonName": "aws-guardduty-agent",
            "addonName": "adot",
            "addonName": "vpc-cni",
            "addonName": "dynatrace_dynatrace-operator",
            "addonName": "upbound_universal-crossplane",
            "addonName": "coredns",
            "addonName": "tetrate-io_istio-distro",
            "addonName": "aws-ebs-csi-driver",
            "addonName": "teleport_teleport",
            "addonName": "kubecost_kubecost",
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by SrDayne** [comment]
If you are mentioning this README than you can't install any addons with this module. This module only creates IAM roles/policies. 
https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-role-for-service-accounts-eks

You need to create your own module to install LB Controller. I use Helm provider, for example.
