### ISSUE TITLE
"does not have attribute 'endpoint'" blocking "terraform destroy"

### ISSUE THREAD

**Issue by brant4test** [terraform-aws-modules/terraform-aws-eks#262]
# I have issues

## I'm submitting a...

* [] bug report

## What is the current behavior?

$ terraform destroy
```
...
Error: Error applying plan:
3 error(s) occurred:
* module.eks.output.config_map_aws_auth: Resource 'data.template_file.config_map_aws_auth' does not have attribute 'rendered' for variable 'data.template_file.config_map_aws_auth.rendered'
* module.eks.output.kubeconfig: Resource 'data.template_file.kubeconfig' does not have attribute 'rendered' for variable 'data.template_file.kubeconfig.rendered'
* module.eks.output.cluster_endpoint: Resource 'aws_eks_cluster.this' does not have attribute 'endpoint' for variable 'aws_eks_cluster.this.endpoint'
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.
1. Set cluster_name a bit longger, say 
locals {
  cluster_name = "************************-eks-${random_string.suffix.result}"
}
you would get an error while running 
$ terraform apply
```
Error: Error applying plan:
3 error(s) occurred:
* module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy: Resource 'aws_iam_role.cluster' not found for variable 'aws_iam_role.cluster.name'
* module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy: Resource 'aws_iam_role.cluster' not found for variable 'aws_iam_role.cluster.name'
* module.eks.aws_iam_role.cluster: "name_prefix" cannot be longer than 32 characters, name is limited to 64
```
2. Then you move on to run 
$ terraform destroy
You would get that error.

## What's the expected behavior?
terraform destroy without any errors

## Environment details

* Affected module version:
Terraform-aws-eks v2.1.0

* OS: $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

* Terraform version:
Terraform v0.11.11

## Any other relevant info
"remove s3 contents along with dynamodb Items" is not a good way to fix it. Any suggestions? Thanks!

**Comment by cwiggs** [comment]
I was having a similar issue but was only get 1 error to begin with; that error was:

```
module.eks.output.config_map_aws_auth: Resource 'data.template_file.config_map_aws_auth' does not have attribute 'rendered' for variable 'data.template_file.config_map_aws_auth.rendered'
```

So as @skang0601 suggested I looked at my state, odd thing is, it seems to be empty:
```
$ terraform state pull
{
    "version": 3,
    "terraform_version": "0.11.11",
    "serial": 9,
    "lineage": "57e93692-87c5-b94e-1f98-d79f4e2e6232",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        },
        {
            "path": [
                "root",
                "eks"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        }
    ]
}
```

Ran `terraform destroy` again, thinking it would say everything was already gone, and it doesn't. instead I get more errors:

```
* module.eks.output.config_map_aws_auth: Resource 'data.template_file.config_map_aws_auth' does not have attribute 'rendered' for variable 'data.template_file.config_map_aws_auth.rendered'
* module.eks.output.cluster_id: Resource 'aws_eks_cluster.this' does not have attribute 'id' for variable 'aws_eks_cluster.this.id'
* module.eks.output.cluster_version: Resource 'aws_eks_cluster.this' does not have attribute 'version' for variable 'aws_eks_cluster.this.version'
* module.eks.output.cluster_endpoint: Resource 'aws_eks_cluster.this' does not have attribute 'endpoint' for variable 'aws_eks_cluster.this.endpoint'
* module.eks.output.kubeconfig: Resource 'data.template_file.kubeconfig' does not have attribute 'rendered' for variable 'data.template_file.kubeconfig.rendered'
* module.eks.output.cluster_certificate_authority_data: Resource 'aws_eks_cluster.this' does not have attribute 'certificate_authority.0.data' for variable 'aws_eks_cluster.this.certificate_authority.0.data'
```

What is even more weird is when I run a `terraform plan -destroy` it says "No changes. Infrastructure is up-to-date."

So at the end of the day it seems like everything **is** destroyed, but terraform is in a state where planning thinks it is destroyed, but destroy doesn't, weird.

**Comment by max-rocket-internet** [comment]
Is this a problem with this module? Or a general TF issue?

**Comment by cwiggs** [comment]
@max-rocket-internet that is a good question.  I was thinking of trying to re-create some of the module in a normal TF project (not a module) for testing.  Then I could remove pieces of the code one at a time to see what resource causes the issue.  If someone has some extra time go ahead and give it a try...or hopefully TF 0.12 will come out soon and fix a lot of issues :)

**Comment by brant4test** [comment]
First time destroying a EKS stack built based on terraform-aws-eks v2.2.1, got 
```
Error: Error applying plan:

2 error(s) occurred:

* module.eks.output.config_map_aws_auth: Resource 'data.template_file.config_map_aws_auth' does not have attribute 'rendered' for variable 'da
* local.worker_groups_launch_template: local.worker_groups_launch_template: Resource 'aws_security_group.worker_group_mgmt_two' does not have orker_group_mgmt_two.id'
```

**Comment by pst** [comment]
I'm seeing this problem too. I'm referencing the clusters' output in module input variables. This works fine when creating and destroying. However when executing destroy again I see the 

```

**Comment by pst** [comment]
For what it's worth, the `aws_eks_cluster` data source suffers from the same issue.

**Comment by max-rocket-internet** [comment]
Closing this old issue. Feel free to open a new one when running against latest release 🙂
