### ISSUE TITLE
ingress_nodes_ephemeral should also allow low ports

### ISSUE THREAD

**Issue by brsolomon-deloitte** [terraform-aws-modules/terraform-aws-eks#2621]
## Description

At https://github.com/terraform-aws-modules/terraform-aws-eks/blob/fcb4256fa17b3e0bde8bbd69dfd191414977f30c/node_groups.tf#LL128C6-L128C6,

please consider changing the `from_port` of `ingress_nodes_ephemeral` from its current value of 1025 to 0. The reason for this is that, without allowing the privileged ports, many applications that communicate using PodIP will break.

For instance, `ingress-nginx` controller will contact "upstream" apps at their `PodIP`.

If I have an Pod that uses a `containerPort` of 80 (pretty normal for that to be the case, even if the `Service` uses a non-privileged port), then `ingress-nginx` will time out trying to talk to this application, and it requires re-configuration on the application side to make it listen on a port at 1025 or higher.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by bryantbiggs** [comment]
This is left to users to add - this level of access is not allowed in a number of organizations

**Comment by brsolomon-deloitte** [comment]
For any other users wanting this functionality, it can be accomplished as follows:

```
  node_security_group_additional_rules = {
    ingress_nodes_privileged = {
      description = "Node to node ingress on privileged ports"
      protocol    = "tcp"
      from_port   = 0
      to_port     = 1024
      type        = "ingress"
      self        = true
    }
  }
```
