### ISSUE TITLE
Changing number of nodes in an ASG breaks communcation between AWS NLB and k8s

### ISSUE THREAD

**Issue by chicken231** [terraform-aws-modules/terraform-aws-eks#263]
# I have issues

After changing the number of nodes in an AWS NSG with this module, traffic no longer gets passed through the AWS NLB to k8s.
After the ASG node count is updated, I have to delete the `LoadBalancer` service and re-create it. Surely I'm missing something simple.

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?

Changing *only* the number of nodes in an autoscaling group breaks communication between AWS NLB and k8s `LoadBalancer` service.

If I have:

```
asg_desired_capacity           = 3
asg_max_size                   = 3
asg_min_size                   = 3
```

And I change it to:

```
asg_desired_capacity           = 2
asg_max_size                   = 2
asg_min_size                   = 2
```

```
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.eks.aws_autoscaling_group.workers[1]
      max_size: "3" => "2"
      min_size: "3" => "2"


Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------
```

Then any connection through a NLB associated with a pod running on this worker group times out.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Service annotations for the `LoadBalancer`:

```
service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "*"
service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

Terraform (mostly taken from EKS Test Fixture):

```

# https://www.terraform.io/docs/configuration/providers.html
terraform { required_version = "~> 0.11" }
provider "aws" { version = "~> 1.54.0" region  = "${var.region}" }
provider "random" { version = "~> 1.3" }
provider "local" { version = "~> 1.1" }
provider "null" { version = "~> 1.0  " }
provider "template" { version = "~> 1.0" }

data "aws_availability_zones" "available" {}

locals {
  cluster_name = "${lookup(local.tags, "Project")}-${lookup(local.tags, "Environment")}-${random_string.suffix.result}"

  # be very careful changing these values as it'll destroy active nodes
  # if you change just the name of a worker group
  worker_groups = [
    {
      name                           = "wg_frontends"
      instance_type                  = "t2.small"
      subnets                        = "${join(",", module.vpc.private_subnets)}"
      asg_desired_capacity           = 2
      asg_max_size                   = 2
      asg_min_size                   = 2
      autoscaling_enabled            = false
    }
  ]
  tags = {
    Terraform   = "true"
    Project     = "asdf"
    Environment = "asdf"
    Workspace   = "${terraform.workspace}"
  }
}

resource "random_string" "suffix" {
  length  = 8
  special = false
}

resource "aws_security_group" "worker_group_mgmt_one" {
  name_prefix = "worker_group_mgmt_one"
  description = "SG to be applied to all *nix machines"
  vpc_id      = "${module.vpc.vpc_id}"

  ingress {
    from_port = 22
    to_port   = 22
    protocol  = "tcp"

    cidr_blocks = [
      "10.0.0.0/8",
    ]
  }
}

resource "aws_security_group" "worker_group_mgmt_two" {
  name_prefix = "worker_group_mgmt_two"
  vpc_id      = "${module.vpc.vpc_id}"

  ingress {
    from_port = 22
    to_port   = 22
    protocol  = "tcp"

    cidr_blocks = [
      "192.168.0.0/16",
    ]
  }
}

resource "aws_security_group" "all_worker_mgmt" {
  name_prefix = "all_worker_management"
  vpc_id      = "${module.vpc.vpc_id}"

  ingress {
    from_port = 22
    to_port   = 22
    protocol  = "tcp"

    cidr_blocks = [
      "10.0.0.0/8",
      "172.16.0.0/12",
      "192.168.0.0/16",
    ]
  }
}

# https://github.com/terraform-aws-modules/terraform-aws-vpc
module "vpc" {
  source                 = "terraform-aws-modules/vpc/aws"
  version                = "~> 1.53.0"
  name                   = "${lookup(local.tags, "Project")}-${lookup(local.tags, "Environment")}"
  cidr                   = "10.0.0.0/16"
  azs                    = ["${data.aws_availability_zones.available.names[0]}", "${data.aws_availability_zones.available.names[1]}", "${data.aws_availability_zones.available.names[2]}"]
  private_subnets        = ["10.0.0.0/23", "10.0.2.0/23", "10.0.4.0/23"]
  public_subnets         = ["10.0.6.0/23", "10.0.8.0/23", "10.0.10.0/23"]
  # be careful mixing these NAT options
  enable_nat_gateway     = true
  single_nat_gateway     = true
  one_nat_gateway_per_az = false
  # reuse_nat_ips          = false                      # Skip creation of EIPs for the NAT Gateways
  # external_nat_ip_ids    = ["${aws_eip.nat.*.id}"]   # IPs specified here as input to the module
  tags                   = "${merge(local.tags, map("kubernetes.io/cluster/${local.cluster_name}", "shared"))}"
}

# https://github.com/terraform-aws-modules/terraform-aws-
module "eks" {
  source                               = "terraform-aws-modules/eks/aws"
  version                              = "~> 2.1.0"
  cluster_name                         = "${local.cluster_name}"
  subnets                              = ["${module.vpc.private_subnets}"]
  tags                                 = "${local.tags}"
  vpc_id                               = "${module.vpc.vpc_id}"
  worker_groups                        = "${local.worker_groups}"
  # worker_groups_launch_template        = "${local.worker_groups_launch_template}"
  # change this based on the worker groups in the list near the top of this file
  worker_group_count                   = "1"
  # worker_group_launch_template_count   = "0"
  worker_additional_security_group_ids = ["${aws_security_group.all_worker_mgmt.id}"]
  map_roles                            = "${var.map_roles}"
  map_roles_count                      = "${var.map_roles_count}"
  map_users                            = "${var.map_users}"
  map_users_count                      = "${var.map_users_count}"
  map_accounts                         = "${var.map_accounts}"
  map_accounts_count                   = "${var.map_accounts_count}"
}
````

## What's the expected behavior?

Scaling nodes in an ASG shouldn't stop traffic from flowing through the Load Balancer to k8s services.

## Environment details

* Affected module version: `2.1.0`
* OS: `Ubuntu 18.04`
* Terraform version:

```
Terraform v0.11.11
+ provider.aws v1.54.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.random v1.3.1
+ provider.template v1.0.0
```

**Comment by unthought** [comment]
@chicken231 Probably unrelated to the problem you're experiencing, but FWIW I recall that I had to set these on the VPC:
```
  # IMPORTANT
  # https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html
  enable_dns_support   = true
  enable_dns_hostnames = true
```

without this the nodes didn't even join the cluster.

Some other thoughts:
* did you check what the NLB is pointing to in the AWS Console when you see this problem?
* can you paste the execution of the change to the SG
* does it really only kill a single node of the original 3, or does it throw out all of them and recreate 2?

**Comment by chicken231** [comment]
@unthought Thanks for responding.

I did read that doc and remember the requirement, but I don't have issues with nodes joining the cluster. The [VPC Module](https://github.com/terraform-aws-modules/terraform-aws-vpc) has `enable_dns_hostnames = false` and `enable_dns_support = true` by default and I didn't change them.

I did notice in the AWS Dashboard that when I added/removed a node to/from the worker group, then every single node which is enumerated in the Network Load Balancer's target group would go `unhealthy` and not recover.

---

I was able to reproduce the original issue with 100% success many times. But I've made some changes and can no longer reproduce the original issue!

I should [not have set this annotation](https://kubernetes.io/docs/concepts/services-networking/service/#network-load-balancer-support-on-aws-alpha) for the `LoadBalancer` object: `service.beta.kubernetes.io/aws-load-balancer-type: "nlb"` because, for an `nlb`...

> Warning: This is an alpha feature and not recommended for production clusters yet.

Well that settles it. The default and proven AWS Load Balancer is the `classic` type, not `network`. I deleted the NLB and created classic the LB's again without the `nlb` annotation.

Other points of reference for my issue:

+   [https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L95](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L95)
+   [https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L95](https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html)
