### ISSUE TITLE
how to install karpanter, or come up with module that installs karpanter?

### ISSUE THREAD

**Issue by uttambaral98** [terraform-aws-modules/terraform-aws-eks#2633]
I would love to know how to install karpenter with this, (https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/karpenter)

If I need to install separately I would love to know on how to do that, and it would be much appreciated if the module would come with karpenter installed.

**Comment by bryantbiggs** [comment]
See the example we have provided

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/f741db1b2c7c4ef0409d7c2e4f588bbc639cbaf2/examples/karpenter/main.tf#L170-L179
