### ISSUE TITLE
v18 to v19 upgrade deletes policy attachments

### ISSUE THREAD

**Issue by alejandro-gallardo-ntt** [terraform-aws-modules/terraform-aws-eks#2636]
## Description

When upgrading from v18 to v19, AmazonEKSClusterPolicy and AmazonEKSVPCResourceController policy attachments are deleted from AWS and a second terraform apply is required:

First apply:

```
# module.eks.aws_iam_role_policy_attachment.this["AmazonEKSClusterPolicy"] will be created
  + resource "aws_iam_role_policy_attachment" "this" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
      + role       = "my-cluster-name-cluster-20230531091859300100000009"
    }

  # module.eks.aws_iam_role_policy_attachment.this["AmazonEKSVPCResourceController"] will be created
  + resource "aws_iam_role_policy_attachment" "this" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
      + role       = "my-cluster-name-cluster-20230531091859300100000009"
    }

  # module.eks.aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"] will be destroyed
  # (because key ["arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"] is not in for_each map)
  - resource "aws_iam_role_policy_attachment" "this" {
      - id         = "my-cluster-name-cluster-20230531091859300100000009-20230531091900894800000012" -> null
      - policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy" -> null
      - role       = "my-cluster-name-cluster-20230531091859300100000009" -> null
    }

  # module.eks.aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"] will be destroyed
  # (because key ["arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"] is not in for_each map)
  - resource "aws_iam_role_policy_attachment" "this" {
      - id         = "my-cluster-name-cluster-20230531091859300100000009-20230531091900905600000014" -> null
      - policy_arn = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController" -> null
      - role       = "my-cluster-name-cluster-20230531091859300100000009" -> null
    }
```

(Verified in AWS that policies are not attached to the role anymore)

Second apply:

```
Terraform will perform the following actions:

  # module.eks.aws_iam_role_policy_attachment.this["AmazonEKSClusterPolicy"] will be created
  + resource "aws_iam_role_policy_attachment" "this" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
      + role       = "my-cluster-name-cluster-20230531091859300100000009"
    }

  # module.eks.aws_iam_role_policy_attachment.this["AmazonEKSVPCResourceController"] will be created
  + resource "aws_iam_role_policy_attachment" "this" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
      + role       = "my-cluster-name-cluster-20230531091859300100000009"
    }
```
(Verified in AWS that policies are attached to the role again)

To workaround this, I execute the following terraform state moves before applying the v19 version. Maybe this should be added to the Upgrade Guide:

```
terraform state mv  'module.eks.aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"]' 'module.eks.aws_iam_role_policy_attachment.this["AmazonEKSClusterPolicy"]'

terraform state mv 'module.eks.aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"]' 'module.eks.aws_iam_role_policy_attachment.this["AmazonEKSVPCResourceController"]'
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v19.15.1

- Terraform version: Terraform v1.3.5

- Provider version(s): 
```
+ provider registry.terraform.io/hashicorp/aws v4.57.1
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.17.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

## Reproduction Code [Required]

1. Deploy an EKS cluster in v18.26.1
2. Follow the upgrade guide https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md
3. Run terraform apply a second time

## Expected behavior

Terraform apply should not delete resources in a way a second apply is needed.

## Actual behavior

Terraform apply deletes resources and a second apply is needed.

**Comment by bryantbiggs** [comment]
this is documented in the v19.0 upgrade guide https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md#terraform-state-moves

**Comment by alejandro-gallardo-ntt** [comment]
> this is documented in the v19.0 upgrade guide https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md#terraform-state-moves

State mv steps in the v19.0 upgrade guide are optional and for the additional policy attachments, but the document says nothing about the default ones created in the module [(AmazonEKSClusterPolicy and AmazonEKSVPCResourceController)](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/b6fa04f65bdcb26869215fb840f5ee088a096bc8/main.tf#L323-L332)
If you don´t run state moves for these two policies, they are deleted from AWS and never created again if you don´t run a second terraform apply. 
   
Same for the additional policy attachments, it´s not optional but mandatory to run state moves, otherwise they will be deleted and not recreated.

**Comment by gluckzhang** [comment]
I ran into the same issue recently. We thought terraform just would like to recreate these role attachments as there is a new `aws_iam_role_policy_attachment` to be created, and the old one is to be destroyed. My guess is terraform tries to create the new `aws_iam_role_policy_attachment` first, and because there exists the same role already, it does not do anything. Later on, the existing role is removed and it leads to this issue.

Would be nice to update the guide since the Terraform state move commands are NOT optional from this perspective.
