### ISSUE TITLE
Un-deprecate the aws_auth_configmap_yaml output

### ISSUE THREAD

**Issue by tculp** [terraform-aws-modules/terraform-aws-eks#2640]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
The manage_aws_auth_configmap and create_aws_auth_configmap variables are useful additions to the module and simplify the creation of the aws-auth configmap in many cases.

However, there are other cases where it might not be sufficient, such as if a new nodegroup needs to be added in another stack and added to the aws-auth configmap.

Additionally, the requirement to provision the kubernetes provider in the same stack as creating the cluster can cause issues and goes directly against official terraform advice.

https://developer.hashicorp.com/terraform/language/providers/configuration#provider-configuration-1
```
You can use [expressions](https://developer.hashicorp.com/terraform/language/expressions) in the values of these configuration arguments, but can only reference values that are known before the configuration is applied. This means you can safely reference input variables, but not attributes exported by resources (with an exception for resource arguments that are specified directly in the configuration).
```

## Describe the solution you'd like.
I would like the aws_auth_configmap_yaml to be un-deprecated, so that I may feel confident in using it.

## Describe alternatives you've considered.
Use a personal module to build the aws-auth configmap yaml from scratch.

## Additional context
Since the manage_aws_auth_configmap parameter has been created, there has been a plethora of issues created about configuring the provider.

**Comment by bryantbiggs** [comment]
as this functionality moves to the EKS API, there won't be a need for the configmap and therefore it will stay marked as deprecated until its removed in a breaking change

Ref: https://github.com/aws/containers-roadmap/issues/185

**Comment by tculp** [comment]
Excellent, that would definitely be the preferred solution. Thanks for the link!
