### ISSUE TITLE
The module output cluster_name returns a value even if the EKS cluster hasn't been created

### ISSUE THREAD

**Issue by mw-tlhakhan** [terraform-aws-modules/terraform-aws-eks#2641]
## Description

The module output `cluster_name` returns the `cluster_name` even if the cluster hasn't been created yet.  This causes Terraform plan to fail when using the output value of `cluster_name` in a subsequent modules or resources.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions
Module version [Required]: v19.15.2
Terraform version: 
```
Terraform v1.3.7
```

Provider version(s):
```
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.1.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.21.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

## Reproduction Code [Required]

```hcl
terraform {
  backend "local" {
    path = "local.tfstate"
  }
}

variable "vpc_id" {
  type = string
}

variable "private_subnet_ids" {
  type = list(string)
}

resource "aws_kms_key" "my_key" {
  description = "EKS Cluster Secret Encryption Key"
}

module "my_eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "v19.15.2"

  create                    = true
  manage_aws_auth_configmap = false

  cluster_name    = "test-cluster-1"
  iam_role_name   = "test-cluster-1"
  cluster_version = "1.25"

  vpc_id     = var.vpc_id
  subnet_ids = var.private_subnet_ids

  cluster_endpoint_private_access = false
  cluster_endpoint_public_access  = true
  cluster_service_ipv4_cidr       = "10.255.0.0/16"

  enable_irsa = true

  cluster_enabled_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]

  cluster_encryption_config = {
    provider_key_arn = aws_kms_key.my_key.arn
    resources        = ["secrets"]
  }
}

data "aws_eks_cluster" "my_eks" {
  name = module.my_eks.cluster_name
}
```

1. Create the `terraform.tfvars` with the populated variables.
2. Run `terraform init` and `terraform plan`

## Expected behavior

The plan should be successful,  I expect the data resource to be known after apply.

```
  # data.aws_eks_cluster.my_eks will be read during apply
  # (config refers to values not yet known)
 <= data "aws_eks_cluster" "my_eks" {
      + arn                       = (known after apply)
      + certificate_authority     = (known after apply)
      + cluster_id                = (known after apply)
      + created_at                = (known after apply)
      + enabled_cluster_log_types = (known after apply)
      + endpoint                  = (known after apply)
      + id                        = (known after apply)
      + identity                  = (known after apply)
      + kubernetes_network_config = (known after apply)
      + name                      = (known after apply)
      + outpost_config            = (known after apply)
      + platform_version          = (known after apply)
      + role_arn                  = (known after apply)
      + status                    = (known after apply)
      + tags                      = (known after apply)
      + version                   = (known after apply)
      + vpc_config                = (known after apply)
    }
```

## Actual behavior

```
terraform plan
module.my_eks.data.aws_partition.current: Reading...
module.my_eks.module.kms.data.aws_partition.current: Reading...
module.my_eks.module.kms.data.aws_caller_identity.current: Reading...
module.my_eks.data.aws_caller_identity.current: Reading...
module.my_eks.module.kms.data.aws_partition.current: Read complete after 0s [id=aws]
module.my_eks.data.aws_partition.current: Read complete after 0s [id=aws]
module.my_eks.data.aws_iam_policy_document.assume_role_policy[0]: Reading...
module.my_eks.data.aws_iam_policy_document.assume_role_policy[0]: Read complete after 0s
module.my_eks.data.aws_caller_identity.current: Read complete after 0s
module.my_eks.module.kms.data.aws_caller_identity.current: Read complete after 0s
module.my_eks.data.aws_iam_session_context.current: Reading...
module.my_eks.data.aws_iam_session_context.current: Read complete after 0s
data.aws_eks_cluster.my_eks: Reading...
╷
│ Error: reading EKS Cluster (test-cluster-1): couldn't find resource
│
│   with data.aws_eks_cluster.my_eks,
│   on main.tf line 47, in data "aws_eks_cluster" "my_eks":
│   47: data "aws_eks_cluster" "my_eks" {
│
╵
```

## Additional context

When I make the following change in the `outputs.tf` file, I see it working as expected.

The [`name` is an argument reference](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#name), where as [`id` is an attribute reference](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#id) for the `aws_eks_cluster` resource.  The resource immediately returns the values of _argument_ reference, whereas the return of _attribute_ reference is known only after apply.

```hcl
diff --git a/outputs.tf b/outputs.tf
index ea02a3a..52c6a96 100644
--- a/outputs.tf
+++ b/outputs.tf
@@ -24,7 +24,7 @@ output "cluster_id" {

 output "cluster_name" {
   description = "The name of the EKS cluster"
-  value       = try(aws_eks_cluster.this[0].name, "")
+  value       = try(aws_eks_cluster.this[0].id, "")
 }

 output "cluster_oidc_issuer_url" {
```

The `aws_eks_cluster` resource documentation mentions the following:  [id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#id) - Name of the cluster.

Making the above change to the `outputs.tf` will resolve the issue, and support the use of `cluster_name` output value as input for dependent resources or modules.  The value of `name` and `id` from `aws_eks_cluster` resource is the same, however the behavior is different.  This fix would help with module usability and composability.

Presently as a workaround, I am using output value of `cluster_arn`, passing it to a data `aws_arn`, then getting the resource attribute and doing a `trimprefix(data.aws_arn.eks_cluster.resource, "cluster/")` to get the cluster name.  This is because `cluster_arn` is an _attribute_ reference of the `aws_eks_cluster` resource and would be known after apply, the plan works as intended.

**Comment by bryantbiggs** [comment]
you should not need to use both this module and the `aws_eks_cluster` data source in the same statefile

**Comment by bryantbiggs** [comment]
> semantically different

There isn't anything semantically different, these are all handled directly from the `aws_eks_cluster` resource in the same way

If you can share a full reproduction, perhaps we can better help you in terms of what you are trying to achieve

**Comment by bryantbiggs** [comment]
ok, well unfortunately I cannot help you without better understanding what you are trying to do. Yes, I know how Terraform works - no, I do not know what you are trying to solve for

**Comment by bryantbiggs** [comment]
Nope - see examples here and across the internet, it's used a lot
