### ISSUE TITLE
Move aws-auth handling to a submodule

### ISSUE THREAD

**Issue by blongman-snapdocs** [terraform-aws-modules/terraform-aws-eks#2646]
## Is your request related to a new offering from AWS?
No.  It's about code organization.

## Is your request related to a problem? Please describe.
I would like to make my main eks template be non-reliant on the kubernetes provider.  I'd like to move that functionality to another template that uses my main eks template as a data source.

## Describe the solution you'd like.
Move the section that manages aws-auth (https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L464-L569) of the module to a submodule - and call that submodule as needed.  This provides a transition method and backwards compatibility for those who are not ready to migrate aws-auth handling to other tooling.

## Describe alternatives you've considered.
When initially transitioning from module 17 to 18, I copied the code creating the aws-auth configmap out of the module and into the template.  I reversed course later when I realized that the functionality changed later in the 18 series.  This is an ok solution, but the maintenance burden is higher.

I've also considered copying that code into a submodule myself, but any maintenance of that code would likely end when I leave the company.

## Additional context
I'm currently on module 19.15.2.

I currently have a template that creates 12 clusters (one per tfvars file) and have found that race conditions stemming from the use of the kubernetes provider in the template that creates the cluster can be challenging after new code has been added to that template.  I've migrated a lot of code out of that template, but I still use the aws-auth functionality.  I'd prefer to see this happen upstream rather than putting that code in the template itself or maintaining a submodule that will become unmaintained when I leave the company.

**Comment by bryantbiggs** [comment]
in terms of a sub-module, we can't do that due to the order of operations and lifecycle. However, the configmap will be going away and so will the Kubernetes provider (leaving just the AWS provider) - ref https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2640#issuecomment-1573870767

**Comment by bryantbiggs** [comment]
closing for now with guidance provided above
