### ISSUE TITLE
Self Managed Nodegroup ami_type support

### ISSUE THREAD

**Issue by bkrugery** [terraform-aws-modules/terraform-aws-eks#2647]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? 
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
Currently managed node groups have the ability to specify ami_type so it'll pick the appropriate one (as viewed in the module's variables.tf file)  The self-managed does not have this, we can just specify an ami-id only, which is bad if we want to do anything outside of the default ami's.

## Describe the solution you'd like.
The ability to use the same ami types that are available to the managed node groups.

## Describe alternatives you've considered.
hard coding the ami (not a fan)
re-writing parts of my own modules to do the same thing.

**Comment by bryantbiggs** [comment]
The AMI type is a function of the EKS managed nodegroups and is not available for self-managed. Howeve, you can use the AMI data source to query the respective AMI based on the name pattern and Kubernetes version https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a2fb28e63e923b1c46ae1f611c237cf1d47e96b4/examples/self_managed_node_group/main.tf#L283C1-L301
