### ISSUE TITLE
changing the desired_size in self manged node group is not doing anything

### ISSUE THREAD

**Issue by premsgr6** [terraform-aws-modules/terraform-aws-eks#2655]
Hi, I am using the eks module of terraform to deploy the eks cluster which is deployed properly, I am using self manged node group.
After deployment I planned to increase the number of nodes in cluster and to do that I updated my terraform code and updated desired_size in self_managed_node_groups from 4 to 5 but  after running the terraform plan it is showing No changes. Your infrastructure matches the configuration. below is the config for self_managed_node_groups:
self_managed_node_groups = {
    eks-cluster-node-pool = {
      name                       = "eks-cluster"
      min_size                   = 3
      max_size                   = 10
      desired_size               = 5
      ami_id                     = "ami-07e01fxxxxxx"
      use_mixed_instances_policy = true
      # instance_type              = "t3a.2xlarge"

      mixed_instances_policy = {
        instances_distribution = {
          on_demand_base_capacity                  = 100
          on_demand_percentage_above_base_capacity = 10
          spot_allocation_strategy                 = "capacity-optimized"
        }

        override = [
          {
            instance_type     = "t3a.2xlarge"
            weighted_capacity = "1"
          },
        ]

      }
    }
  }

**Comment by bryantbiggs** [comment]
See https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#why-are-there-no-changes-when-a-node-groups-desired_size-is-modified

And here is one work around https://github.com/bryantbiggs/eks-desired-size-hack
