### ISSUE TITLE
terraform-aws-modules/eks/aws latest version not available in registry.terraform.io

### ISSUE THREAD

**Issue by pac78275** [terraform-aws-modules/terraform-aws-eks#2659]
When attempting to use the module [`terraform-aws-modules/eks/aws` in the Terraform public registry](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest), the latest version (19.15.3) kicks back a 404 error. You have to pin the version to 19.15.2 or earlier to be able to use this module at all. Specifying no version or the latest will result in a 404 error. Was the latest release pulled from the Terraform public registry for same reason? This needs to be resolved. Thanks.

**Comment by bryantbiggs** [comment]
If a version is pulled from the registry, the registry would not show it as available. However, no, we have not recalled any versions from the registry and today I have deployed several clusters using the v19.15.3 version

Closing since this doesn't require an module changes
