### ISSUE TITLE
Add a switch to scope node groups to a single subnet

### ISSUE THREAD

**Issue by shengjiangfeng** [terraform-aws-modules/terraform-aws-eks#2668]
>   I want to seperate subnet in nodegroups , but 

`
  eks_managed_node_groups = merge([

    for subnet_id in local.subnet_ids : {
      for node_group_name, node_group_config in var.eks_managed_node_groups :
      format("%s-%s", node_group_name, subnet_id) => {
        instance_types = node_group_config.instance_types
        labels         = node_group_config.labels
        subnet_ids     = [subnet_id]
      }
    }
  ]...)`
  Does'nt work for me. Terraform tell me  "merge" failed: arguments must be maps or objects, got "tuple".

**Comment by bryantbiggs** [comment]
please fill out the requested details in the issue template provided so that we can help triage and troubleshoot

**Comment by shengjiangfeng** [comment]
> please fill out the requested details in the issue template provided so that we can help triage and troubleshoot

Thanks for reply , i have filled out the issue. Terraform merge function cannot  work in eks_managed_node_groups , because it is a map.
