### ISSUE TITLE
Add a switch to scope node groups to a single subnet

### ISSUE THREAD

**Issue by shengjiangfeng** [terraform-aws-modules/terraform-aws-eks#2669]
Currently node groups are created with all the subnets that are passed in via subnet_ids. This causes issues when using Cluster Autoscaler and running stateful workloads backed by EBS volumes, as the EBS volumes are AZ locked. Having node group scoped to a single subnet is also recommended by AWS when working with stateful workloads.

The module currently does check to see if each value in the eks_managed_node_groups has a subnet_id field but it's somewhat difficult to generate the correct data structure downstream of the module.

The required data structure for creating 3 node groups that only have a single subnet associated.

`managed_node_groups =
{
t3medium-a = {
instance_types = [
"t3.medium",
"t3a.medium",
]
labels = {
instance_family = "t3x.medium"
type = "spot"
}
subnet_ids = [
"a",
]
}
t3medium-b = {
instance_types = [
"t3.medium",
"t3a.medium",
]
labels = {
instance_family = "t3x.medium"
type = "spot"
}
subnet_ids = [
"b",
]
}
t3medium-c = {
instance_types = [
"t3.medium",
"t3a.medium",
]
labels = {
instance_family = "t3x.medium"
type = "spot"
}
subnet_ids = [
"c",
]
}
}

I want to seperate subnet in nodegroups , but the solution below does'nt work for me. Terraform tell me "merge" failed: arguments must be maps or objects, got "tuple".

eks_managed_node_groups = merge([
for subnet_id in local.subnet_ids : {
for node_group_name, node_group_config in var.eks_managed_node_groups :
format("%s-%s", node_group_name, subnet_id) => {
instance_types = node_group_config.instance_types
labels = node_group_config.labels
subnet_ids = [subnet_id]
}
}
]...).
Terraform merge function cannot work in eks_managed_node_groups , because it is a map.

**Comment by bryantbiggs** [comment]
its very hard to tell what your configuration is doing since its not formatted - but you should be able to pass in a single subnet ID for `subnet_ids` in the nodegroup to restrict the nodegroup to that one subnet

**Comment by shengjiangfeng** [comment]
I just want to generate the configuration dynamically.
