### ISSUE TITLE
User not authorized to perform kms:DescribeKey operation

### ISSUE THREAD

**Issue by james-downing** [terraform-aws-modules/terraform-aws-eks#2678]
## Description

Despite providing sufficient permissions to the KMS key policy the cluster is not being created due to insufficient KMS permissions. I'm perplexed by this as it should be very straightforward and all permissions look correct.

## Versions

- Module version [Required]:
`19.15.3`

- Terraform version:
`v1.2.5`
- Provider version(s):
aws: `v5.5.0`

## Reproduction Code

I've tried letting the eks module generate the key and providing the following variables:
```
  kms_key_enable_default_policy = true
  kms_key_administrators         = ["arn:aws:iam::redacted:user/redacted@redacted.com"]
  kms_key_owners                     = ["arn:aws:iam::redacted:user/redacted@redacted.com"]
  kms_key_service_users          = ["arn:aws:iam::redacted:user/redacted@redacted.com"]
  kms_key_users                        = ["arn:aws:iam::redacted:user/redacted@redacted.com"]
```
and also using an external key as shown in the `/examples/complete` example:
```
  create_kms_key = false
  cluster_encryption_config = {
    resources        = ["secrets"]
    provider_key_arn = module.kms.key_arn
  }
...
module "kms" {
  source  = "terraform-aws-modules/kms/aws"
  version = "~> 1.5"

  aliases               = ["eks/${local.name}"]
  description           = "${local.name} cluster encryption key"
  enable_default_policy = true
  key_owners            = [data.aws_caller_identity.current.arn]

}
```

`terraform apply`

## Expected behavior

Cluster is created successfully.

## Actual behavior

Upon EKS cluster creation:

```
│ Error: creating EKS Cluster (my-cluster): InvalidRequestException: User not authorized to perform kms:DescribeKey operation
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "2bc816b4-0a5b-4c0c-bb4d-a43b24d72a40"
│   },
│   Message_: "User not authorized to perform kms:DescribeKey operation"
│ }
│
│   with module.eks.aws_eks_cluster.this[0],
│   on .terraform/modules/eks/main.tf line 25, in resource "aws_eks_cluster" "this":
│   25: resource "aws_eks_cluster" "this" {
│
╵
```

Despite within the KMS key policy I can clearly see:
```
{
            "Sid": "KeyOwner",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::redacted:user/redacted@redacted.com"
            },
            "Action": "kms:*",
            "Resource": "*"
        }
```
## Additional context

I've checked the generated KMS key policy, it's providing the correct permissions to the correct user. I'm also running the Terraform via the same users credentials.

I've checked the AWS [troubleshooting key access](https://docs.aws.amazon.com/kms/latest/developerguide/policy-evaluation.html) guide and none of these should apply to me. Very much at a loss to what could be causing this, no explicit denies, SCP's, endpoint policies etc.

**Comment by jp928** [comment]
same bere.

**Comment by deanmax** [comment]
same issue here. We were not seeing this issue on v.18.28.0

**Comment by shawnjohnson** [comment]
Same here. I was using Terraform Cloud with a specific AWS IAM role, and my local CLI interactions were with a different SSO role. I added both roles to the aws-auth and as key admins - resolved.

**Comment by bryantbiggs** [comment]
sounds like this is just mis-configuration so I am going to close it out for now
