### ISSUE TITLE
node security group should be output

### ISSUE THREAD

**Issue by kbzg4** [terraform-aws-modules/terraform-aws-eks#2679]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Describe the solution you'd like.
output "node_security_group_id" {
  description = "node security group"
  value       = try(aws_eks_cluster.this[0].vpc_config[0].node_security_group_id, null)
}

## Describe alternatives you've considered.
using a data source to fetch this by name with a depends on is wasteful.

## Additional context
use case: rds is created in another tf repo, but the SG needs to be updated with a rule to allow inbound traffic from the nodes, should be able to call by reference and not fetch it with a data source

**Comment by bryantbiggs** [comment]
that is the cluster's primary security group, not the node security group. That is already an output https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0a17f655fb7da00640627ed9255f1d96e42fcfd7/outputs.tf#L50
