### ISSUE TITLE
[Karpenter] Allow passing multiple roles to `iam:PassRole`

### ISSUE THREAD

**Issue by Jeinhaus** [terraform-aws-modules/terraform-aws-eks#2683]
## Is your request related to a new offering from AWS?
  - No

## Is your request related to a problem? Please describe.

This is basically the same issue as https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2560.
Since [karpenter 0.29 now supports Windows nodes](https://github.com/aws/karpenter/releases/tag/v0.29.0), we want to use different instance profiles, because Windows nodes need the extra permission `eks:kube-proxy-windows` for Windows networking to work.
This is just one use case for using different `AWSNodeTemplates`.

Just like @caleb-devops said in [this comment](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2560#issuecomment-1506113449), I think this module should support as many features of Karpenter as possible.

## Describe the solution you'd like.

Please add a variable to the Karpenter module to support passing additional roles that nodes can assume.
It might look like this

```hcl
 statement {
    actions   = ["iam:PassRole"]
    resources = concat([var.create_iam_role ? aws_iam_role.this[0].arn : var.iam_role_arn], var.additional_iam_role_arns)
  }
```

**Comment by bryantbiggs** [comment]
Windows containers do not require an additional role https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support

`eks:kube-proxy-windows` is an RBAC group inside the cluster which the node IAM role would need to have via the aws-auth configmap. 

As far as I can tell, there are no changes required to the Karpenter sub-module in order to run Windows containers

**Comment by Jeinhaus** [comment]
But wouldn't it make sense to only add Windows nodes to this RBAC group instead of all nodes?

**Comment by bryantbiggs** [comment]
> But wouldn't it make sense to only add Windows nodes to this RBAC group instead of all nodes?

No

> Also, the use case mentioned https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2560#issuecomment-1505750739 (dependencies that don't support IRSA and need an instance role) is valid, don't you think?

There are a ton of various use cases and configurations. However, this module is already massively complex with a plethora of variables. Its quite easy to think `"But, just one more - it adds flexibility..."`, but it actually increases the complexity of the module. Unless there is something that is widely requested by a number of users (i.e. - 15-20+), I don't see the need to keep conflating the module for all of these edge cases when there are workarounds
