### ISSUE TITLE
An argument named "tags" is not expected here

### ISSUE THREAD

**Issue by emvardanian** [terraform-aws-modules/terraform-aws-eks#2686]
I decided to create a new cluster in the EKS service using the following documentation: https://docs.gitlab.com/ee/user/infrastructure/clusters/connect/new_eks_cluster.html

 I got an error in the "**validate**" step:

 _Error: Unsupported argument
 on .terraform/modules/eks/modules/self-managed-node-group/main.tf line 391, in resource "aws_autoscaling_group" "this":_

  _391: tags = concat(_

_An argument named "tags" is not expected here._

I will be grateful for any advice
<img width="1083" alt="error" src="https://github.com/terraform-aws-modules/terraform-aws-eks/assets/109952562/0019774d-b384-434f-ac6c-90c8ad5c80ae">

**Comment by petercort** [comment]
That guide is using v18.1.0 of the eks module. Appears to me that in that version, tags were a map value, and in the current version they're a dynamic block. 

I would start by updating the module version to the latest v19.15.3
