### ISSUE TITLE
Passing the kubeconfig filename to another module

### ISSUE THREAD

**Issue by syst0m** [terraform-aws-modules/terraform-aws-eks#269]
# I have issues
with passing the value of the generated kubeconfig filename to the prometheus-operator helm provider.
## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
```
terraform console
>"${module.eks.kubeconfig.filename}"
Couldn't find output "kubeconfig.filename" for module var: module.eks.kubeconfig.filename
```

I was hoping to create a new output that would contain the value of the kubeconfig filename,
then pass that output as a variable to the prometheus-operator provider config.
How could I achieve this?

**Comment by syst0m** [comment]
I managed to do this by cloning your module locally, then adding a new output:
```
output "kubeconfig_filename" {
  description = "Filename of the generated kubeconfig"
  value       = "${module.eks.kubeconfig_filename}"
}
```
However, I would like to avoid this approach, because I would like to downstream your changes.
Any ideas how to go about this?

**Comment by frimik** [comment]
@max-rocket-internet this seems done in #272 and can be closed?

**Comment by max-rocket-internet** [comment]
Sure thing.
