### ISSUE TITLE
Problem with deleting aws_security_group.node while destroy

### ISSUE THREAD

**Issue by nicraMarcin** [terraform-aws-modules/terraform-aws-eks#2691]
version `source = "tfr:///terraform-aws-modules/eks/aws//?version=19.15.2"`

HI,
I have problem with destroy eks, it stucks while destroying security group
```shell
aws_security_group_rule.node["ingress_cluster_443"]: Destruction complete after 4s
aws_security_group_rule.node["ingress_self_coredns_tcp"]: Destruction complete after 4s
aws_security_group.cluster[0]: Destroying... [id=sg-0156cbfd7fcd9db09]
aws_security_group.node[0]: Destroying... [id=sg-0eeff565f5609bf90]
aws_security_group.cluster[0]: Destruction complete after 1s
aws_security_group.node[0]: Still destroying... [id=sg-0eeff565f5609bf90, 10s elapsed]
aws_security_group.node[0]: Still destroying... [id=sg-0eeff565f5609bf90, 20s elapsed]
aws_security_group.node[0]: Still destroying... [id=sg-0eeff565f5609bf90, 30s elapsed]
aws_security_group.node[0]: Still destroying... [id=sg-0eeff565f5609bf90, 40s elapsed]
aws_security_group.node[0]: Still destroying... [id=sg-0eeff565f5609bf90, 50s elapsed]
...
```
This is because, to this security group a network interface is bound. after manual deleting eni- aws-K8S- it keep going further.

**Comment by nicraMarcin** [comment]
@bryantbiggs Why you closed this issue? The eni interface is created by module and should be deleted by module.
I create clean eks and after is up and running I'm deleting it, and problem with stuck interface esists.

Interface has description `

Elastic network interface | aws-K8S-i-0013bb5a69faf8ff9

`
and was created during "apply" process.

**Comment by bryantbiggs** [comment]
no, the module does not create the ENI that you are describing. You are either dealing with the VPC CNI where it has not had time to clean up the resource it creates (it creates ENIs for container networking), or a load balancer. Both of those are resources that are deployed *onto the cluster but are not relevant to the module. Again, you need to ensure the resources deployed onto the cluster are cleaned up first, before trying to destroy the cluster

**Comment by nicraMarcin** [comment]
Thank you for clarification. I'll check when this interface is created and why is not deleted. It was confusing, because it description was `aws-K8S-i` and these interfaces are created during setting up eks.

**Comment by nicraMarcin** [comment]
@bryantbiggs please   ##help.
I set new and clean EKS cluster from module. After it was up and running I was adding and deleting my resources. All went well and all was deleted. 
This interface was created during EKS creation and wan't deleted after instance was terminated.
[interfaces](https://ibb.co/J5kCf04)
[instances](https://ibb.co/0yvVMyS)
As you can see instance was terminated but interface still exists. 
Is this AWS problem? Where to request it?
