### ISSUE TITLE
updating  terraform eks module version from 6.3.0 to 8.2.0 

### ISSUE THREAD

**Issue by guttikondajitendra** [terraform-aws-modules/terraform-aws-eks#2692]
I am updating terraform eks module version from 6.3.0 to 8.2.0 in my project. since this is very new to me do i need do the node (instnace) refresh since we are using  asg instance refresh every time?  when i am upgrade eks modules moving forward !. Right now the only change i see in my project 

1)  **module.eks.kubernetes_config_map.aws_auth[0] will be created
  + resource "kubernetes_config_map" "aws_auth" {**
  
  2) module.eks.null_resource.update_config_map_aws_auth[0] will be destroyed
  - resource "null_resource" "update_config_map_aws_auth" {
  3) module.eks.null_resource.wait_for_cluster[0] will be created
  + resource "null_resource" "wait_for_cluster" {
      + id = (known after apply)
    }

**Comment by bryantbiggs** [comment]
I'm sorry but thats quite an old version thats not been supported for some time - however, instance refresh changes are usually safe, they just control the manner in which nodes are replaced in the autoscaling group
