### ISSUE TITLE
Security group "workers_ingress_cluster" is very limiting

### ISSUE THREAD

**Issue by ilyasotkov** [terraform-aws-modules/terraform-aws-eks#27]
Currently, in `workers.tf`, we have this security group:

```tf
resource "aws_security_group_rule" "workers_ingress_cluster" {
  description              = "Allow workers Kubelets and pods to receive communication from the cluster control plane."
  protocol                 = "tcp"
  security_group_id        = "${aws_security_group.workers.id}"
  source_security_group_id = "${local.cluster_security_group_id}"
  from_port                = 1025
  to_port                  = 65535
  type                     = "ingress"
  count                    = "${var.worker_security_group_id == "" ? 1 : 0}"
}
```

Basically, this setting makes it impossible for Kubernetes services to access pods that have have containerPort set to anything below 1025, which is a huge issue since so many of them use the 80 port (e.g. nginx). So, `from_port` should be set to 0, not 1025.

I realize this is copied from CloudFormation in the official EKS guide, so I'll also submit an issue there.

**Comment by brandoconnor** [comment]
This is in discussion on #28 . Hopefully, you're good with what I've proposed there. Thanks for the contribution!

**Comment by brandoconnor** [comment]
Shipping this change to a release now. Thanks again!
