### ISSUE TITLE
EKS OIDC Provider Issues

### ISSUE THREAD

**Issue by Bruce-Lu674** [terraform-aws-modules/terraform-aws-eks#2700]
Hi, team 
I am using terraform to create an EKS cluster in China, and I am having the following problems with it:

The OIDC Provider created and bound by Terraform has the following:
Audience :
sts.amazonaws.com.cn

In China, the STS endpoint is actually sts.amazonaws.com, which does not require the .cn suffix.

If the suffix is added, the IAM Role permission cannot be obtained through IRSA, and the following error will be reported:
{"level": "error", "ts":1690425075.104501, "logger": "controller.ingress", "msg": "Reconciler error", "name": "alb-ingress", "namespace":" alb-ingress", "error": "WebIdentityErr: failed to retrieve credentials\ncaused by: InvalidIdentityToken: Incorrect token audience\n\tstatus code: 400, request id: xx-xx-xx-xx-xxx"}

(This error message is thrown by Amazon Load Balancer Controller when I create the Ingress resource)

When I configured the Audience to be sts.amazonaws.com, I was able to get rid of the error.

Could you please help to check about this issues ?

Any help would be greatly appricated ~

**Comment by bryantbiggs** [comment]
can you paste your configuration

**Comment by Bruce-Lu674** [comment]
@bryantbiggs Hi, you can try to use the tearraform to create the EKS Cluster in cn-north-1 region.

provider "aws" {
  region = var.region
}

data "aws_availability_zones" "available" {}

locals {
  cluster_name = "education-eks-${random_string.suffix.result}"
}

resource "random_string" "suffix" {
  length  = 8
  special = false
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "5.0.0"

  name = "education-vpc"

  cidr = "10.0.0.0/16"
  azs  = slice(data.aws_availability_zones.available.names, 0, 3)

  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]

  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true

  public_subnet_tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
    "kubernetes.io/role/elb"                      = 1
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
    "kubernetes.io/role/internal-elb"             = 1
  }
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "19.15.3"

  cluster_name    = local.cluster_name
  cluster_version = "1.27"
  create_iam_role  = false
  iam_role_arn = "arn:aws-cn:iam::112233445566:role/eksClusterRole"
  vpc_id                         = module.vpc.vpc_id
  subnet_ids                     = module.vpc.private_subnets
  cluster_endpoint_public_access = true

  eks_managed_node_group_defaults = {
    ami_type = "AL2_x86_64"

  }

  eks_managed_node_groups = {
    one = {
      name = "node-group-1"

      instance_types = ["t3.small"]

      min_size     = 1
      max_size     = 3
      desired_size = 2
    }

    two = {
      name = "node-group-2"

      instance_types = ["t3.small"]

      min_size     = 1
      max_size     = 2
      desired_size = 1
    }
  }
}

It will create the EKS cluster successfully.
Then use the helm install the aws loadbalancer controller in the cluster, and create the Ingress resource can reproduce the error.

**Comment by bryantbiggs** [comment]
1. I don't see the full config to reproduce the error
2. Have you considered setting https://github.com/terraform-aws-modules/terraform-aws-eks/blob/de14031c970fc23412ebbfae719cefe259c2ad32/variables.tf#L421 - this was added by another user from the Beijing region

**Comment by Bruce-Lu674** [comment]
@bryantbiggs Hi, thanks for your reply.
Just use the terraform to create a normal EKS cluster in BJS region (no special configuration) , when the creation is complete, we can check the OIDC Provider from IAM console.

Check in the OIDC Provider detail, you can see the Audiences is sts.amazonaws.com.cn , i think that should be sts.amazonaws.com

and follow the EKS document install the controller : https://docs.amazonaws.cn/en_us/eks/latest/userguide/aws-load-balancer-controller.html

Then create a ALB class ingress resources can reproduce the error.

**Comment by bryantbiggs** [comment]
right, and have you tried setting `cluster_iam_role_dns_suffix = "amazonaws.com"` as mentioned above?

**Comment by Bruce-Lu674** [comment]
@bryantbiggs  I will try to set it , and i find the same [issues](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2271)

**Comment by Bruce-Lu674** [comment]
Add cluster_iam_role_dns_suffix = "amazonaws.com" works fine, thanks
