### ISSUE TITLE
vpc_cni eks addon - lack customization for amazon-k8s-cni-init container

### ISSUE THREAD

**Issue by andreb92** [terraform-aws-modules/terraform-aws-eks#2703]
## Is your request related to a problem? Please describe.
When installing vpc-cni addon using terraform eks module I would like to customize cni-init container env vars and activate parameters like DISABLE_TCP_EARLY_DEMUX  to enable security group for pods at cluster startup without manual intervention via kubectl

## Describe the solution you'd like.
Have the possibility to customize init container env vars

## Describe alternatives you've considered.
Installing vpc-cni addon via helm to reach expected results

**Comment by bryantbiggs** [comment]
if this is supported by the VPC CNI addon custom configuration then this module supports it. Otherwise, its out of scope for this module
