### ISSUE TITLE
Leave out key administrators when using default KMS key policy

### ISSUE THREAD

**Issue by marekaf** [terraform-aws-modules/terraform-aws-eks#2705]
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2526

this is still an issue

I'm happy to implement a fix

**Comment by bryantbiggs** [comment]
I still need more details on what the current issue is, and what the proposed change(s) are.

**Comment by marekaf** [comment]
Hi.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/df1b62548c1d8c7117f4ab45c5b494de64b34cb8/main.tf#L134

the module enforces the current IAM identity (be it a role for automation like github_actions or some user doing the apply from their local machine, etc.) to be appended to KMS key policy. 

The problematic part is appending this 
```
[data.aws_iam_session_context.current.issuer_arn]
```

If you have e.g. github actions doing all the plans and applies but then some user does `terraform plan` from their local machine, or you even use terraform cloud on the side as well, you are getting terraform drifts all the time as it's injecting the current identity in the kms policy with each change. Like this:

```
 # module.eks.module.kms.aws_kms_key.this[0] will be updated in-place
  ~ resource "aws_kms_key" "this" {
        id                                 = "2e6dbc35-084f-abcdfeavv"
      ~ policy                             = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = {
                          ~ AWS = "arn:aws:iam::1234567890:role/github_actions" -> "arn:aws:iam:: 1234567890:user/myuser"
                        }
                        # (4 unchanged attributes hidden)
                    },
```

The `var.kms_key_enable_default_policy` allows this:
```
                    {
                        Action    = "kms:*"
                        Effect    = "Allow"
                        Principal = {
                            AWS = "arn:aws:iam:: 1234567890:root"
                        }
                        Resource  = "*"
                        Sid       = "Default"
                    },
```
i.e. root == all of the entities in your AWS account to be an admin of the key == making the kms_key_administrators redundant

what would make more sense is something like:
```
  key_administrators        = coalescelist(var.kms_key_administrators, var.kms_key_administrator_current_issuer ? [data.aws_iam_session_context.current.issuer_arn] : [])
```
having `var.kms_key_administrator_current_issuer` set `true` by default

or somehow use the information about using the default policy being in use and skip injecting the administrator
```
  key_administrators        = coalescelist(var.kms_key_administrators, var.kms_key_enable_default_policy ? []: [data.aws_iam_session_context.current.issuer_arn] )
```

**Comment by bryantbiggs** [comment]
this is intentional - it ensures that folks do not create keys that they suddenly cannot manage and have to open AWS support tickets. If you wish to control the behavior, specify a static admin via `kms_key_administrators` 

In short - someone (an IAM identity) has to be a key administrator to ensure it does not reach a state where it cannot be managed

**Comment by marekaf** [comment]
I do understand that part.
But specifying `kms_key_enable_default_policy = true` along with not using `kms_key_administrators` or setting it to `[]` is not behaving as I'd expect. Looks pretty much like a bug to me. 

Why would it be an issue to implement the logic that I mentioned earlier (i.e. using default policy == allowing everybody and not having an explicit administrator)?

**Comment by bryantbiggs** [comment]
> Looks pretty much like a bug to me

What makes that a bug? Why is having redundant permissions a bug as opposed to, like I stated above, a safe measure to ensure that you avoid losing access to fully manage the key

**Comment by marekaf** [comment]
> What makes that a bug? Why is having redundant permissions a bug as opposed to, like I stated above, a safe measure to ensure that you avoid losing access to fully manage the key

Having the default policy enabled makes this redundant in 100% cases. In cases like mine (using more IAM entities to do terraform plans/applies) this causes only troubles and diffs. 
i.e. serves no purpose and only causes issues.

How else would you describe a bug? 

> a safe measure to ensure that you avoid losing access to fully manage the key

You cannot lose access to the KMS key if it whitelists the entire AWS account. 

The logic to solve this is very simple. I don't see any negative outcomes of implementing this.

**Comment by phyzical** [comment]
Hey, 

We just finished up migrating off of blueprints and started hitting this too,

```
# module.eks.module.aws_eks.module.kms.aws_kms_key.this[0] will be updated in-place
  ~ resource "aws_kms_key" "this" {
      ~ policy                             = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = {
                          ~ AWS = "arn:aws:sts::12345:assumed-role/eks-ci/aws-go-sdk-1693200237560607000" -> "arn:aws:sts::12345:assumed-role/eks-ci/aws-go-sdk-1693200534345203512"
                        }
                        # (4 unchanged attributes hidden)
                    },
```

Providing a role we trust avoids the drift.

But i would still argue its a "bug" in the sense that it creates redundant noise.

Though you could argue this is a "Warning".

Just my 2 cents.

**Comment by kylelikesboatstuff** [comment]
Very interested in seeing a follow up. I have the same problem.
