### ISSUE TITLE
How to add kubelet arguments or configuration to AL2 node group

### ISSUE THREAD

**Issue by bennesp** [terraform-aws-modules/terraform-aws-eks#2709]
This is more a question than anything else, but could become a feature request, so apologize if this is the wrong place to ask this.

I am currently using `ami_type = "AL2_x86_64"` and I don't want to use Bottlerocket.

Is there an opinionated way of adding kubelet arguments or configure the `KubeletConfiguration` according to this module?

I am currently using `pre_bootstrap_user_data` like the following but it seems a bit hack-ish to me

```terraform
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "19.15.3"

  # ...
  
  eks_managed_node_groups = {

    "on_demand" = {
      ami_type = "AL2_x86_64"

      # ...

      pre_bootstrap_user_data = <<-EOT
        #!/bin/bash
        EXTRA_CONF='{"imageGCLowThresholdPercent": 50, "imageGCHighThresholdPercent": 70}'
        jq --argjson extra_conf "$EXTRA_CONF" '. + $extra_conf' \
          /etc/kubernetes/kubelet/kubelet-config.json > /tmp/kubelet-config.json
        mv /tmp/kubelet-config.json /etc/kubernetes/kubelet/kubelet-config.json
      EOT

      # ...

    }
  }
}
```

An idea could be to let users of the module that want AL2 to use `bootstrap_extra_args`

**Comment by bennesp** [comment]
This is still valid to me

**Comment by bryantbiggs** [comment]
unfortunately, this solutions or others like it are the only way to do this https://github.com/awslabs/amazon-eks-ami/issues/844 until better support is provided by EKS to pass through custom values

Closing since there isn't anything we can do here in the module

**Comment by bennesp** [comment]
Thank you for taking the time to answer and to explain.

Just to let future viewers (and the future me) understand the status as of now, this comment https://github.com/awslabs/amazon-eks-ami/pull/875#issuecomment-1146018089 sums up well what I guess is the current status:
- The AL2 AMI script `bootstrap.sh` is becoming messy
- The support to new features to `bootstrap.sh`, like adding user kubernetes configuration, was discussed and rejected because the script [would become too complex](https://github.com/awslabs/amazon-eks-ami/pull/875#issuecomment-1625740913)
  - See add kubernetes configuration with env variables https://github.com/awslabs/amazon-eks-ami/pull/855
  - See add kubernetes configuration with json https://github.com/awslabs/amazon-eks-ami/pull/875 is not  
- People want to re-write `bootstrap.sh` entirely as a binary with the same interface of Bottlerocket
- Potentially [using the drop-in configuration directory](https://github.com/awslabs/amazon-eks-ami/pull/875#issuecomment-1729490973) of kubernetes 1.28
