### ISSUE TITLE
Maintainer on holiday for 3 weeks

### ISSUE THREAD

**Issue by max-rocket-internet** [terraform-aws-modules/terraform-aws-eks#271]
After tomorrow, I will be on holiday for 3 weeks 🏖 @brandoconnor is working on GCP related stuff these days so is no longer actively working on this repo.

Perhaps one of @skang0601 @Jeeppler @dpiddockcmp @erks @laverya would like to help out with maintenance?

CC @antonbabenko

**Comment by antonbabenko** [comment]
I am here, back from FOSDEM and CfgMgmtCamp. I will watch this repo and try to help if there is anything.

Thanks for heads up!

**Comment by antonbabenko** [comment]
Closing this issue, which is actually an _update from the maintainer_ :) Everyone is welcome to participate in PRs and issues, as usual.

**Comment by brandoconnor** [comment]
Thanks, guys!

**Comment by skang0601** [comment]
Happy to help if you need additional hands.

**Comment by laverya** [comment]
Same here!
