### ISSUE TITLE
Require possible way to paas Corefile for CoreDNS Addon | lamduck configuration

### ISSUE THREAD

**Issue by ArunSisodiya** [terraform-aws-modules/terraform-aws-eks#2710]
## How to pass CoreDNS corefile to EKS terraform addon

In the recent past, while upgrading the Kubernetes cluster to a newer version, we found the issue with CoreDNS.
CoreDNS addon is not gracefully shutting down which is causing downtime to DNS requests.

To avoid this downtime, after doing some research I found this option for CoreDNS:
https://aws.github.io/aws-eks-best-practices/scalability/docs/cluster-services/#coredns-lameduck-duration

This is about increasing `lameduck` duration to 30s.

```tf
  cluster_addons = {
    coredns = {
      most_recent   = true
      addon_version = data.aws_eks_addon_version.coredns.version
      configuration_values = jsonencode({
       <Need to find the right way of passing corefile here>
      })
    }
```

## Versions

- Module version ~> 19.0]:

- Terraform version:
Terraform v1.4.5
- Provider version(s):
aws  = "~> 4.0"

**Comment by bryantbiggs** [comment]
you can pass the corefile via the configuration values - this is already supported today

**Comment by ArunSisodiya** [comment]
@bryantbiggs - Can you please provide an example of how to pass the file content?
Since the core file is a multiline file and passing it to JSON causes problems.

I have created the ticket to see an example. There are no examples available.
