### ISSUE TITLE
Upgrade EKS Cluster & Node Group simultaneously from 1.22 to 1.27

### ISSUE THREAD

**Issue by vesubramanian** [terraform-aws-modules/terraform-aws-eks#2711]
## Description

I am using the Terraform Module (versions below) to provision EKS cluster and Node Groups. Cluster was at 1.22 version. Now, I need to upgrade it to 1.27 version. I wanted to upgrade both Cluster & Node Groups from 1.22 to 1.27 in a single run. Is this possible? If yes, please provide the steps. If not, please provide the reasons.

## Versions

- Module version [Required]:
   >= 17.0.0, < 18.0.0

- Terraform version:
1.1.7

- Provider version(s):
   Terraform - >=0.13.0
   AWS - >=2.57
   Kubernetes - <3.0.0

## Reproduction Code [Required]

Assigned version to 1.23 from 1.22 initially, since the UI also seems to allow only this (not sure why). Although Cluster got upgraded, the Node Group did not.

## Expected behavior

Cluster & Node Groups should have got upgraded

## Actual behavior

Only Cluster got upgraded, but Node Group did not.

**Comment by RobertFr0st** [comment]
I ran into this issue last month.  The long of the short is that EKS only supports updating 1 major version at a time, and additionally requires that if say your cluster is v1.23 your node group must also be v1.23.  The approach I ended up adopting to go 1.21 -> 1.27 was to first delete the associated node groups, and then incrementally update the major version / apply changes.  And once I was fully updated then I updated the node groups to use amis associated with the latest release of eks.  Additionally you're probably already aware but there are some changes surrounding updating CoreDNS that need to be made as well documented over here: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

**Comment by bryantbiggs** [comment]
Its actually Kubernetes that requires the control plane components are upgraded in serial, one minor version at a time https://kubernetes.io/releases/version-skew-policy/#supported-component-upgrade-order

If you wish to skip versions, the only route is to utilize a blue/green cluster upgrade. This consists of creating a second EKS cluster on the desired (1.27) version alongside your existing (1.22) cluster. Once the new (1.27) cluster is up and running you can start migrating your workloads over to it from the existing (1.22) cluster. Once the last pod has migrated, you can remove the old (1.22) cluster.
