### ISSUE TITLE
The version of eks supported by the terraform-eks module

### ISSUE THREAD

**Issue by thomas-yangy** [terraform-aws-modules/terraform-aws-eks#2713]
I want to know the correspondence between terrafrom-aws-eks and eks version？ 
 I can't find the relevant documentation description, so I would like to ask if there is such documentation

**Comment by cpepper96** [comment]
You can set the EKS (Kubernetes) version with the [cluster_version](https://github.com/terraform-aws-modules/terraform-aws-eks#input_cluster_version) variable. [EKS currently supports Kubernetes](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html) 1.23, 1.24. 1.25, 1.26, 1.27 so I'd expect the latest version of this module supports those as well.

**Comment by bryantbiggs** [comment]
It is a direct pass through to the API and therefor follows the API behavior https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html#cfn-eks-cluster-version
