### ISSUE TITLE
Remove putin_khuylo var

### ISSUE THREAD

**Issue by RobertFr0st** [terraform-aws-modules/terraform-aws-eks#2714]
It appears there was a change made to the code base to add this putin_khuylo variable in order to make a political statement.  I would recommend removing it as it does not add any additional functionality to the code base and the conditional logic here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/666603b6e531140d5d8fbd777cd90a7fbb8247dd/main.tf#L13 seems to me to be a likely source of future confusion to users as it is not immediately obvious based on the name of the variable that it would govern the create or not create logic as well.  Additionally it seems to me the desired political statement has been made on the README.md which is probably the most appropriate place as it does not potentially interfere with the intended functionality of the code.
  Thanks!

**Comment by bryantbiggs** [comment]
thank you, but we currently do not plan on making any further changes on this subject
