### ISSUE TITLE
cannot execute eks-managed-node-group module when using sub modules

### ISSUE THREAD

**Issue by aksh-sood** [terraform-aws-modules/terraform-aws-eks#2717]
## Description

I am trying to create eks-managed-nodes by calling the eks-managed node modules inside the node submodule main.tf file. This node module gets called in the module eks main.tf file.  The eks-managed-node module call inside nodes module main.tf has a for_each loop in it to create multiple node groups for the same cluster . The node_groups are supplied from root vars.tf with variable type map(map(dynamic)) with each sub map containing configuration for a single node group hence generating multiple node_groups

i am creating the node role in iam module and setting the create_iam_role to false .  The entire eks module is called in the root main.tf file. 

below is the folder structure.

```

├── main.tf
├── modules
│   ├── eks
│   │   ├── main.tf(where node module is called)
│   │   ├── modules
│   │   │   ├── cluster
│   │   │   │   ├── main.tf
│   │   │   │   ├── output.tf
│   │   │   │   └── vars.tf
│   │   │   ├── iam
│   │   │   │   ├── main.tf
│   │   │   │   ├── outputs.tf
│   │   │   │   └── vars.tf
│   │   │   ├── nodes
│   │   │   │   ├── main.tf (where eks-managed-node module is set)
│   │   │   │   └── vars.tf
│   │   ├── outputs.tf
│   │   └── vars.tf
├── outputs.tf
├── providers.tf
```

I am getting the following error on plan and apply
![Screenshot from 2023-08-10 18-49-34](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/53402073/2697935d-14fe-4206-99a5-0fe35cc2d4fb)

If i am making the same call from root main.tf module which changing any code inside the node module then the execution works perfectly .

## Versions

- Module version [Required]:

- Terraform version:
1.5.2
- Provider version(s):
aws: 5.10.0
kubernetes: 2.22.0

## Reproduction Code [Required]

No
yes

1. Destruction if a node group in eks module lead to destruction of addons too hence created cluster myself and used the eks-managed-nodes module for node creation .
2. Created an eks cluster in cluster module without nay nodes.
3. Used nodes module for creation of nodes . 
4. calling nodes module in following path.(./modules/eks/main.tf) alog with cluster module.

## Expected behavior

clean run with terraform plan or apply

## Additional context

there are multiple node groups to be created so for_each is being used in the eks-managed-node module call with iam role being passed as a variable and create_iam set to false.

How do i get the node call working from inside ./modules/eks/main.tf

**Comment by FernandoMiguel** [comment]
if you have a `depends_on`, you will need to remove it
