### ISSUE TITLE
Can't get node to join cluster - support request

### ISSUE THREAD

**Issue by bodegus** [terraform-aws-modules/terraform-aws-eks#273]
# I have issues
I can't get the nodes to join the cluster

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [X ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I can't get the node to join the cluster.
kubectl get nodes --watch --kubeconfig kubeconfigXXX
No nodes appear

kubectl get svc --watch --kubeconfig kubeconfig
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.100.0.1   <none>        443/TCP   1h

## If this is a bug, how to reproduce? Please include a code sample if relevant.
module "eks_cluster" {
  source       = "../module/eks"
  cluster_name = "${var.cluster_name}"
  subnets      = ["${module.eks_vpc.subnet1_id}", "${module.eks_vpc.subnet2_id}", "${module.eks_vpc.subnet3_id}"]
  vpc_id       = "${module.eks_vpc.vpc_id}"
  manage_aws_auth = true
  write_kubeconfig = true
  config_output_path = "./"
  worker_groups = [
    {
      instance_type = "m4.large"
      asg_max_size  = 5
    }
  ]

  tags = {
    environment = "test"
  }
}

## What's the expected behavior?
Nodes return in kubectl

## Environment details

* Affected module version: [v2.1.0] - 2019-01-15]  
* OS: ubuntu 18.04
* Terraform version: 11.11

## Any other relevant info
I have everything working via the eks getting started guide cloud formation templates, I compared the deployments and don't see a diff between VPC, cluster, node, IAM.

**Comment by max-rocket-internet** [comment]
Are the subnets `"${module.eks_vpc.subnet1_id}", "${module.eks_vpc.subnet2_id}", "${module.eks_vpc.subnet3_id}"` public? Or have routes to a NAT gateways? Can you post the TF code of the VPC module?

EKS nodes need to access the internet in order to reach the AWS EKS API endpoint.

**Comment by bodegus** [comment]
I tried to do a 1:1 mapping of the cloud formation template flavor for eks.

resource "aws_vpc" "main" {
  cidr_block       = "192.168.0.0/16"
  enable_dns_support  =    true
  enable_dns_hostnames = true
  tags = {
    Name = "${var.vpc_name}"
  }
}

resource "aws_subnet" "az1" {
  vpc_id     = "${aws_vpc.main.id}"
  cidr_block = "192.168.64.0/18"
  availability_zone = "${var.region}a"
  tags = {
    Name = "${var.vpc_name}-az1"
  }
}

resource "aws_subnet" "az2" {
  vpc_id     = "${aws_vpc.main.id}"
  cidr_block = "192.168.128.0/18"
  availability_zone = "${var.region}b"
  tags = {
    Name = "${var.vpc_name}-az2"
  }
}

resource "aws_subnet" "az3" {
  vpc_id     = "${aws_vpc.main.id}"
  cidr_block = "192.168.192.0/18"
  availability_zone = "${var.region}c"
  tags = {
    Name = "${var.vpc_name}-az3"
  }
}

resource "aws_security_group" "eks_sg" {
  name        = "${var.vpc_name} allow"
  description = "Allow all inbound traffic"
  vpc_id      = "${aws_vpc.main.id}"

  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port       = 0
    to_port         = 0
    protocol        = "-1"
    cidr_blocks     = ["0.0.0.0/0"]
  }
}

resource "aws_internet_gateway" "gw" {
  vpc_id = "${aws_vpc.main.id}"

  tags = {
    Name = "${var.vpc_name}-internet-gateway"
  }
}

resource "aws_route_table" "r" {
  vpc_id = "${aws_vpc.main.id}"
  tags = {
    Name = "${var.vpc_name} Public Subnets"
    Network = "Public"
  }

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.gw.id}"
  }
}

resource "aws_route_table_association" "a" {
  subnet_id      = "${aws_subnet.az1.id}"
  route_table_id = "${aws_route_table.r.id}"
}

resource "aws_route_table_association" "b" {
  subnet_id      = "${aws_subnet.az2.id}"
  route_table_id = "${aws_route_table.r.id}"
}

resource "aws_route_table_association" "c" {
  subnet_id      = "${aws_subnet.az3.id}"
  route_table_id = "${aws_route_table.r.id}"
}

output "vpc_id" {
  description = "The ID of the VPC"
  value       = "${aws_vpc.main.id}"
}

output "subnet1_id" {
  description = "The ID of the az1 subnet"
  value       = "${aws_subnet.az1.id}"
}

output "subnet2_id" {
  description = "The ID of the az2 subnet"
  value       = "${aws_subnet.az2.id}"
}

output "subnet3_id" {
  description = "The ID of the az3 subnet"
  value       = "${aws_subnet.az3.id}"
}

**Comment by bodegus** [comment]
Update - the node joined the cluster after added the ssh key pair and public IP...
