### ISSUE TITLE
Error: failed to download module

### ISSUE THREAD

**Issue by nrinaldi-fetch** [terraform-aws-modules/terraform-aws-eks#2730]
## Description

Unable to download these modules. 

```
Error: Failed to download module

Could not download module "eks" (eks.tf:74) source code from
"git::https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v19.16.0":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v19.16.0':
git must be available and on the PATH.


Error: Failed to download module

Could not download module "external_dns_irsa_role" (eks.tf:218) source code
from
"git::https://github.com/terraform-aws-modules/terraform-aws-iam?ref=v5.29.1":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-iam?ref=v5.29.1': git
must be available and on the PATH.
```

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:
v1.5.6
- Provider version(s):

- Git version:
2.420

## Additional context

I am running on an Apple M1 Max Chip. OS is Ventura 13.5.1

**Comment by bryantbiggs** [comment]
I'm not seeing any issues with pulling down module definitions with `terraform init`
