### ISSUE TITLE
Thumbprint list should only include CA fingerprint

### ISSUE THREAD

**Issue by gabegorelick** [terraform-aws-modules/terraform-aws-eks#2732]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.

https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2307 updated the OIDC provider `thumbprint_list` to include all  certificate fingerprints. This was valid at the time, since that's what the Terraform docs recommended. However, the docs have since been updated to recommend against this (https://github.com/hashicorp/terraform-provider-aws/issues/32847). 

Here's what's in the [latest docs](https://registry.terraform.io/providers/hashicorp/aws/5.15.0/docs/resources/eks_cluster):

> thumbprint_list = [data.tls_certificate.example.certificates[0].sha1_fingerprint]

Additionally, including all fingerprints can cause issues since AWS only allows a maximum of 5 to be specified (https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2632). So if you want to provide extra fingerprints, there may not be room.

I also think that official AWS tooling (Console, eksctl) only populates the CA fingerprint. Here's eksctl, for example:
https://github.com/eksctl-io/eksctl/blob/fb50ae558a9f9c3259fc42bda7cc3957a1d824d5/pkg/iam/oidc/api.go#L113

## Describe the solution you'd like.

Go back to the behavior before #2307 and only include the CA fingerprint in `thumbprint_list`.

## Describe alternatives you've considered.

Do nothing and live with the fact that this module behaves differently from what AWS and Terraform recommend.

**Comment by bryantbiggs** [comment]
if you'd like to open a PR, I'll merge it
