### ISSUE TITLE
Terraform conditional blocks terraform plan/apply

### ISSUE THREAD

**Issue by Roxyrob** [terraform-aws-modules/terraform-aws-eks#2734]
## Description

Conditional eks cluster creation points out "Terraform Kubernetes Provider" limits and lack of flessibility, blocking code execution. Some Workarounds can be used to remove the block (like terraform state rm '...' or terraform destroy) but normal terraform flexible code management with conditionals is not possible with this module.

Related Issue:
  [Fail to upgrade to version 18 from 17 #2728](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2728)

References:
  [Conditional kubernetes_manifest resource](https://discuss.hashicorp.com/t/conditional-kubernetes-manifest-resource/57940)
  [Conditional kubernetes provider resources #2276](https://github.com/hashicorp/terraform-provider-kubernetes/issues/2276)
  [Unknown values should not block successful planning #30937](https://github.com/hashicorp/terraform/issues/30937)

## Versions

- Module version [Required]: v19.16.0
- Terraform version: v1.5.2
- Provider version(s): 5.7.0

## Reproduction Code

<pre>
provider "kubernetes" {
  alias = "clus1"
  host  = module.eks_clus1[0].cluster_endpoint
  cluster_ca_certificate = try(base64decode(module.eks_clus1[0].cluster_certificate_authority_data), null)

  exec {
    api_version   = "client.authentication.k8s.io/v1beta1"
    command       = "aws"
    args          = ["eks", "get-token", "--cluster-name", local.name]
  }
}

module "eks_clus1" {
  source  = "terraform-aws-modules/eks/aws"
  version = "..."

  <b>count</b> = var.eks_clus1_create ? 1 : 0

  providers = {
    aws = aws....
    kubernetes = kubernetes.clus1
  }
  ...
}

   set variable "<b>eks_clus1_create</b> = <b>true</b>"
<b>terraform plan</b>
<b>terraform apply</b>

   set variable "<b>eks_clus1_create</b> = <b>false</b>"
<b>terraform plan</b>       (1)
<b>terraform apply</b>     (2)
<b>terraform plan</b>       (3)
</pre>

## Expected behavior

No errors in (1), (2) and (3) and no changes in (3)

## Actual behavior

Executing (1), (2) and (3) returns error like:

<pre>
│ Error: Get "http://localhost/api/v1/namespaces/kube-system/<b>configmaps/aws-auth</b>": dial tcp [::1]:80: connect: connection refused
│
│ with module.eks_clus1[0].kubernetes_config_map_v1_data.aws_auth[0],
│ on .terraform/modules/eks_clus1/main.tf <b>line 554</b>, in resource "<b>kubernetes_config_map_v1_data</b>" "<b>aws_auth</b>":
│ 554: resource "<b>kubernetes_config_map_v1_data</b>" "<b>aws_auth</b>" {
</pre>

## Additional context

This is a known issue/behavior of <b>Terraform Kubernetes Provider</b>, not an issue of this module but this module uses this providere and so inherit inflexibility introduced by the provider issue/behavior.

As a replacement  of Terraform Kubernetes Provider can you evaulate usage of kubernetes providers that use "non-Server Side" check during terraform plan like "<b>kubectl_manifest</b>" or that correctly interpret parameters <b>unkown values</b> ?

**Comment by bryantbiggs** [comment]
Apologies but I am not following what the exact issue is here - could you try to clarify?

**Comment by Roxyrob** [comment]
@bryantbiggs. The use of "Terraform Kubernetes Provider" has critical drawbacks. Try to run sample code using count.

The behavior is not 100% Terraform compliance as you cannot enable|disable cluster creation with conditional expressions.

Think about situations in which you need 3 cluster in production environment, 1 cluster in devel evnvironment, 0 cluster in sandboxing environment, using the same terraform codebase (DRY common code) and flags/tfvars to manage these dimensions and without make manual correction removing tf state resources or destroy entire environments or introduce any other useless workaround to avoid incomplete compliance with conditional expressions for resources management.

You can find more info on links in previous comment and on other links like this: [Avoid the Terraform kubernetes_manifest resource](https://medium.com/@danieljimgarcia/dont-use-the-terraform-kubernetes-manifest-resource-6c7ff4fe629a).

**Comment by bryantbiggs** [comment]
If you have a more concrete issue, we can investigate further. Dow now, I'm not seeing any reported issue

**Comment by Roxyrob** [comment]
Workaround for others facing this same issue.

To **destroy only the eks cluster** (made by this excellent module) **without terraform destroy all**: 

<pre>
  set <b>var.eks_clus1_create</b> to <b>false</b>
terraform state rm 'module.eks_clus1[0].kubernetes_config_map_v1_data.aws_auth[0]'
terraform apply
</pre>

**Comment by Roxyrob** [comment]
@bryantbiggs
I apologize as manage_aws_auth_configmap is false by defualt, so the correct "Reproduction Code" is:

## Reproduction Code

<pre>
provider "kubernetes" {
  alias = "clus1"
  host  = module.eks_clus1[0].cluster_endpoint
  cluster_ca_certificate = try(base64decode(module.eks_clus1[0].cluster_certificate_authority_data), null)

  exec {
    api_version   = "client.authentication.k8s.io/v1beta1"
    command       = "aws"
    args          = ["eks", "get-token", "--cluster-name", local.name]
  }
}

module "eks_clus1" {
  source  = "terraform-aws-modules/eks/aws"
  version = "..."

  <b>count</b> = var.eks_clus1_create ? 1 : 0

  providers = {
    aws = aws....
    kubernetes = kubernetes.clus1
  }
  <b>manage_aws_auth_configmap = true</b>
  ...
}


   set variable "<b>eks_clus1_create</b> = <b>true</b>"
<b>terraform plan</b>
<b>terraform apply</b>

   set variable "<b>eks_clus1_create</b> = <b>false</b>"
<b>terraform plan</b>       (1)
<b>terraform apply</b>      (2)
<b>terraform plan</b>       (3)
</pre>

**Comment by Roxyrob** [comment]
It is correct to assert that this module doesn't really requires to manage aws-auth to work fine and aws-auth can be managed differently (e.g. GitOps) ?

If it is true , is probably better to document and warning about module dependency from "terraform kubernetes provider" if used to manage aws-auth configmap  (`manage_aws_auth_configmap`, `create_aws_auth_configmap`, `aws_auth_configmap_data`).

This will avoid some inflexibility like that above.
