### ISSUE TITLE
Supply different launch template tags for instance and volume using tag_specifications

### ISSUE THREAD

**Issue by gdasson** [terraform-aws-modules/terraform-aws-eks#2739]
## Is your request related to a problem? Please describe.
We have a requirement to apply certain enterprise related tags to the ec2 instances and ebs volumes that are created as part of the eks managed node groups. We want the module to create launch templates so we have set:
`create_launch_template  = true`. 

We are using the [tag_specifications](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/eks-managed-node-group/variables.tf#L277-L281) variable to supply ["instance" , "volume" ] to let the module know that we want to add certain tags to these resources. The option to supply tags for these resources is this map variable named launch_template_tags described [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/eks-managed-node-group/variables.tf#L271-L275). The way the modules are written today, the same tags will be applied to both the volume and to the instance which is not required in our use case! We want different tags to be added to volumes than to the instances. 

## Describe the solution you'd like.
Would prefer an option to supply different tags for each resource type.

## Describe alternatives you've considered.
Add tags to the resources after they are created, either manually or through cli commands via a terraform null_resource. Both are ugly and fragile options.

## Additional context
I'll most probably submit a PR to fix this. Raising this issue for awareness and to receive suggestions, if any.

**Comment by bryantbiggs** [comment]
thank you - however, we do not have any plans to split up these tags any further
