### ISSUE TITLE
Auto scaling instance refresh fails with validation errors

### ISSUE THREAD

**Issue by alexoughton** [terraform-aws-modules/terraform-aws-eks#2740]
Hello,

A change in the AWS provider requires that "scale_in_protected_instances" be added to the "preferences" block of the instance_refresh. Please see this upstream issue:

https://github.com/hashicorp/terraform-provider-aws/issues/33377

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version 19.16.0

- Terraform version: 1.3.4

- Provider version(s):
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.16.1
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.11.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]

Any code using a self_managed node group.

Any change which would trigger an instance refresh. The use of a specific "dynamic" in the module does not seem to permit the end-user to apply this value ourselves.

## Expected behavior

The terraform will apply and the instances will refresh.

## Actual behavior

```
╷
│ Error: starting Auto Scaling Group (qa-shared-linux-cluster-qa-shared-linux-cluster-additionalnode) instance refresh: ValidationError: 2 validation errors detected: Value '' at 'preferences.scaleInProtectedInstances' failed to satisfy constraint: Member must satisfy enum value set: [Ignore, Wait, Refresh]; Value '' at 'preferences.standbyInstances' failed to satisfy constraint: Member must satisfy enum value set: [Terminate, Ignore, Wait]
│ 	status code: 400, request id: dea79dce-77a5-40ff-a561-469c83389021
│
│   with module.smp-eks.module.eks_blueprints.module.aws_eks.module.self_managed_node_group["additionalnode"].aws_autoscaling_group.this[0],
│   on .terraform/modules/smp-eks.eks_blueprints.aws_eks/modules/self-managed-node-group/main.tf line 412, in resource "aws_autoscaling_group" "this":
│  412: resource "aws_autoscaling_group" "this" {
```

**Comment by bryantbiggs** [comment]
this is due to the upstream bug https://github.com/hashicorp/terraform-provider-aws/issues/33377

**Comment by bryantbiggs** [comment]
this should be resolved now with https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.16.2
