### ISSUE TITLE
Tags are not attached to EC2 / Vols etc when using use_custom_launch_template = false

### ISSUE THREAD

**Issue by oc-stephen-bennett** [terraform-aws-modules/terraform-aws-eks#2741]
When adding a managed node group with `use_custom_launch_template = false`, no custom tags are added to the ec2 nodes or volumes.

**Comment by bryantbiggs** [comment]
that is correct - that is one of the reasons for the custom launch template. this is outside of the module's control and down to the EKS API. I would suggest not using the default managed nodegroup launch template

**Comment by oc-stephen-bennett** [comment]
Is there a way to expand the root disk volume with the custom? i dont see a way to do it from examples / variable options

**Comment by bryantbiggs** [comment]
yes https://github.com/terraform-aws-modules/terraform-aws-eks/blob/918aa7cc40cbc072836410747834de64d84f514d/examples/eks_managed_node_group/main.tf#L233-L246
