### ISSUE TITLE
new karpenter policy attachment fails

### ISSUE THREAD

**Issue by OSingh** [terraform-aws-modules/terraform-aws-eks#2742]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:
Terraform v1.5.6
on windows_386
- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v5.16.2
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/hashicorp/vault v3.20.0

## Reproduction Code [Required]

module "karpenter" {
  depends_on = [ module.eks_managed_node_group ]
  source = "terraform-aws-modules/eks/aws//modules/karpenter"

  cluster_name = module.eks.cluster_name

  irsa_oidc_provider_arn          = module.eks.oidc_provider_arn
  irsa_namespace_service_accounts = ["karpenter:karpenter"]

  create_iam_role = false
  iam_role_arn    = module.eks.eks_managed_node_groups["initial"].iam_role_arn
}

## Actual behavior

Error: Invalid for_each argument
│
│   on .terraform\modules\eks_cluster.karpenter\modules\karpenter\main.tf line 345, in resource "aws_iam_role_policy_attachment" "this":
│  345:   for_each = { for k, v in toset(compact([
│  346:     "${local.iam_role_policy_prefix}/AmazonEKSWorkerNodePolicy",
│  347:     "${local.iam_role_policy_prefix}/AmazonEC2ContainerRegistryReadOnly",
│  348:     var.iam_role_attach_cni_policy ? local.cni_policy : "",
│  349:   ])) : k => v if local.create_iam_role }
│     ├────────────────
│     │ local.cni_policy is a string, known only after apply
│     │ local.create_iam_role is false
│     │ local.iam_role_policy_prefix is a string, known only after apply
│     │ var.iam_role_attach_cni_policy is true
│
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this resource.
│
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.

**Comment by bryantbiggs** [comment]
do not use `depends_on` across modules. once you remove `depends_on = [ module.eks_managed_node_group ]` your issue should be resolved
