### ISSUE TITLE
Support changing instance type on managed node groups

### ISSUE THREAD

**Issue by albgus** [terraform-aws-modules/terraform-aws-eks#2744]
## Is your request related to a problem? Please describe.
It's currently not possible to change the instance_types on managed node groups after creation. This makes it harder than it has to be to change/upgrade the instance types used in an EKS cluster.  

## Describe the solution you'd like.
The solution proposed by the AWS EKS team is to utilise the launch template support to set the instance types https://github.com/aws/containers-roadmap/issues/746#issuecomment-675099508. This should allow the managed node group to perform a normal rolling update, replacing all the nodes in a controlled fashion.

I have also opened a PR before summer that was closed during vacation: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2677

## Describe alternatives you've considered.
A workaround is to create a new managed node group with a new instance types setting, then later remove the old managed node group. 

Another workaround is to simply use self managed nodes, but this requires some extra effort to get the rolling updates working smoothly.

**Comment by bryantbiggs** [comment]
I don't quite follow - this module uses  a custom launch template by default. could you provide a reproduction that demonstrates the issue you are encountering?

**Comment by albgus** [comment]
It provides a launch template, but no means of setting the `instance_type` parameter on the launch template, and changing the instance type on the managed node group itself it not allowed.

This means that a change of the instance_types list triggers a replacement of the entire node group
```
  # module.eks.module.eks_managed_node_group["main"].aws_eks_node_group.this[0] must be replaced
+/- resource "aws_eks_node_group" "this" {
      ~ arn                    = "arn:aws:eks:eu-west-1:012345678910:nodegroup/aws-test-4f18d3/main/3ac53231-a26e-18c1-3d8f-593c8876357d" -> (known after apply)
      ~ capacity_type          = "ON_DEMAND" -> (known after apply)
      ~ disk_size              = 0 -> (known after apply)
      ~ id                     = "aws-test-4f18d3:main" -> (known after apply)
      ~ instance_types         = [ # forces replacement
          - "m6a.large",
          + "m7a.large",
        ]
[...]
```
... which will fail anyway due to a naming conflict (which is probably best because I don't think that operation is nesescarily safe).

```
module.eks.module.eks_managed_node_group["main"].aws_eks_node_group.this[0]: Creating...
╷
│ Error: creating EKS Node Group (aws-test-4f18d3:main): ResourceInUseException: NodeGroup already exists with name main and cluster name aws-test-4f18d3
│ {
│   RespMetadata: {
│     StatusCode: 409,
│     RequestID: "520ed65b-8e3e-4840-a15d-e832cba45e5d"
│   },
│   ClusterName: "aws-test-4f18d3",
│   Message_: "NodeGroup already exists with name main and cluster name aws-test-4f18d3",
│   NodegroupName: "main"
│ }
│ 
│   with module.eks.module.eks_managed_node_group["main"].aws_eks_node_group.this[0],
│   on .terraform/modules/eks/modules/eks-managed-node-group/main.tf line 308, in resource "aws_eks_node_group" "this":
│  308: resource "aws_eks_node_group" "this" {
│ 
╵
Releasing state lock. This may take a few moments...
```

Allowing an option to set the instance type on the launch template instead should allow changing the instance type with a managed rolling replacement of the nodes.

**Comment by bryantbiggs** [comment]
correct - the instance types in this module are set through the managed nodegroup and not on the launch template. there are no plans to change this
