### ISSUE TITLE
spot_allocation_strategy feature for managed node groups

### ISSUE THREAD

**Issue by griff92** [terraform-aws-modules/terraform-aws-eks#2745]
## Is your request related to a problem? Please describe.
Currently unable to set the spot allocation strategy on AWS managed node groups.

## Describe the solution you'd like.

It is possible to set spot allocation strategy in Self managed node groups with parameter ` spot_allocation_strategy = "capacity-optimized"` 

A similar parameter for managed node groups would be very useful.

## Additional context

I would like to be able change the spot allocation strategy of managed node groups to `price-capacity-optimized`

**Comment by bryantbiggs** [comment]
Does managed nodegroups support this?

**Comment by griff92** [comment]
> Does managed nodegroups support this?

I'm able to go through the AWS console to the ASG and change it manually on a node group there. So I assumed it does, but I could be wrong.

**Comment by bryantbiggs** [comment]
managed nodegroups do create ASGs, but that doesn't mean that they expose all of the features/functionality of the ASGs. I would try setting this in the launch template to see if this works or not

**Comment by bryantbiggs** [comment]
closing this for now - if the EKS APIs and the AWS provider support this, then we can support it here as well
