### ISSUE TITLE
Private EKS: Unable to Access Cluster with kubectl with VPN into VPC

### ISSUE THREAD

**Issue by rob-avestruz-kp** [terraform-aws-modules/terraform-aws-eks#2746]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
I'm trying to setup a private cluster that is only accessible by VPN. After creation I'm having trouble accessing the created cluster with the following commands.

```bash
aws eks --region us-east-2 update-kubeconfig --name privatecluster
kubectl get svc
```

This is code I'm using to setup eks
```
module "eks" {
    source  = "terraform-aws-modules/eks/aws"
    version = "~> 19.0"

    cluster_name    = var.cluster_name
    cluster_version = "1.27"
    
    vpc_id                                  = var.vpc.vpc_id
    subnet_ids                              = var.vpc.private_subnets
    cluster_endpoint_private_access         = true
    cluster_endpoint_public_access          = false

    eks_managed_node_groups = var.eks_managed_node_groups
}
```

I have tried creating a bastion host that I could VPN into as well to get access to the cluster through the control plane,  but I received the same timeout error. Am I missing a parameter to allow access to the control plane through a vpn?

**Comment by AlexanderStout** [comment]
Double-check your security group rules. 
Timeouts are usually indicative of AWS ACLs blocking traffic. Cluster SG should have 443 port open from your VPN subnet

**Comment by bryantbiggs** [comment]
closing since this is outside the scope of the module

**Comment by kaykhan** [comment]
@rob-avestruz-kp @AlexanderStout

I ran into the same issue on my kubernetes cluster which has both public and private subnets attached. 

- I could connect to kubectl when i was not connected to the vpn
- kubectl was timing out when i was connected to the vpn.

I added the following ingress rule `cluster_security_group_additional_rules`

```
 cluster_security_group_additional_rules = {
    kubectl_in_vpn = {
      description = "Kubectl In VPN"
      protocol    = "tcp"
      from_port   = 443
      to_port     = 443
      type        = "ingress"
      cidr_blocks = [
        "10.0.0.0/16",
      ]
    }
  }
```
  
Not sure what you meant by @AlexanderStout `open from your VPN subnet`
