### ISSUE TITLE
invalid for_each argument

### ISSUE THREAD

**Issue by mmerickel** [terraform-aws-modules/terraform-aws-eks#2747]
The issue is exactly [Issue #2681](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2681#issuecomment-1653056775). The dynamic resource names for `local.iam_role_policy_prefix` and `local.eni_policy` are dynamic and are used in the KEY of the for_each statement.

This should be changed (bw-incompat) to statically defined keys for the 3 resources being created.

**Comment by bryantbiggs** [comment]
please provide the details requested/required on the issue template

**Comment by bryantbiggs** [comment]
just looking at the error isn't enough detail - we need to see a reproduction to know what you are doing (or trying to do)

**Comment by mmerickel** [comment]
You are free to ignore this - I put significant effort into trying to make a simple repro and am failing.

Here is what I will leave you with - the terraform does not pass the smell-test - the keys are dynamic based on the value of the partition data source. This is a pitfall of using `toset()` in terraform. I was able to get past the issue in my env by running a `terraform apply -target 'module.eks.module.eks_managed_node_group["foo"].data.aws_partition.current'`. After this, the partition info was loaded successfully and the full plan/apply worked on the next run.

Obviously this doesn't happen every time, it's possible to get past it, but it could clearly be done better in this module such that the resource keys are not dependent on the partition data source.

A proper fix (albeit bw-incompat) is this:

```diff
diff --git a/modules/eks-managed-node-group/main.tf b/modules/eks-managed-node-group/main.tf
index 1d3fe81..3725176 100644
--- a/modules/eks-managed-node-group/main.tf
+++ b/modules/eks-managed-node-group/main.tf
@@ -287,7 +287,9 @@ resource "aws_launch_template" "this" {
   # Prevent premature access of policies by pods that
   # require permissions on create/destroy that depend on nodes
   depends_on = [
-    aws_iam_role_policy_attachment.this,
+    aws_iam_role_policy_attachment.worker_node,
+    aws_iam_role_policy_attachment.ecr,
+    aws_iam_role_policy_attachment.cni,
   ]
 
   lifecycle {
@@ -430,14 +432,24 @@ resource "aws_iam_role" "this" {
 }
 
 # Policies attached ref https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group
-resource "aws_iam_role_policy_attachment" "this" {
-  for_each = { for k, v in toset(compact([
-    "${local.iam_role_policy_prefix}/AmazonEKSWorkerNodePolicy",
-    "${local.iam_role_policy_prefix}/AmazonEC2ContainerRegistryReadOnly",
-    var.iam_role_attach_cni_policy ? local.cni_policy : "",
-  ])) : k => v if var.create && var.create_iam_role }
+resource "aws_iam_role_policy_attachment" "worker_node" {
+  count = var.create && var.create_iam_role ? 1 : 0
 
-  policy_arn = each.value
+  policy_arn = "${local.iam_role_policy_prefix}/AmazonEKSWorkerNodePolicy"
+  role       = aws_iam_role.this[0].name
+}
+
+resource "aws_iam_role_policy_attachment" "ecr" {
+  count = var.create && var.create_iam_role ? 1 : 0
+
+  policy_arn = "${local.iam_role_policy_prefix}/AmazonEC2ContainerRegistryReadOnly"
+  role       = aws_iam_role.this[0].name
+}
+
+resource "aws_iam_role_policy_attachment" "cni" {
+  count = var.create && var.create_iam_role && var.iam_role_attach_cni_policy ? 1 : 0
+
+  policy_arn = local.cni_policy
   role       = aws_iam_role.this[0].name
 }
```

Thanks for your time!

**Comment by kahirokunn** [comment]
I have the same issue.

**Comment by CPWu** [comment]
This issue has been reported twice now and has been repeatedly closed. Its definitely an issue when bringing up a cluster with managed node groups at the same time.
