### ISSUE TITLE
Max-pods is not set according to the instance type but set to the default value of 110 in user_data

### ISSUE THREAD

**Issue by ubasche-nex** [terraform-aws-modules/terraform-aws-eks#2748]
## Description

Max-pods is not set according to the instance type but set to the default value of 110 in user_data.

We have nodes deployed via node_groups and Karpenter. We noticed that the nodes created via node groups have the default max-pods setting of 110 instead of the value according to the instance type derived from the eni-max-pods file. Only the nodes created by Karpenter have the correct instance type specific values.
 
We don’t set the max-pods value in our terraform code and I checked the base64 user-data string from the terraform state file and it shows only the values from our code without and max-pods setting.
 
The user_data in the terraform state file matches our code. Both don’t have any settings for max-pods.
But the user_data taken from the AWS console and the output from the api client commands have an entry for “max-pods = 110”. It looks like that the max-pods setting was added somewhere else.

A similar issue has been raised before but there is no conclusion to it:
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2297

## Versions

- Module version [Required]:
Downloading registry.terraform.io/terraform-aws-modules/eks/aws 19.14.0 for eks.awseks...
- eks.awseks in .terraform/modules/eks.awseks
- eks.awseks.eks_managed_node_group in .terraform/modules/eks.awseks/modules/eks-managed-node-group
- eks.awseks.eks_managed_node_group.user_data in .terraform/modules/eks.awseks/modules/_user_data
- eks.awseks.fargate_profile in .terraform/modules/eks.awseks/modules/fargate-profile

- Terraform version:
v1.3.9

- Provider version(s):
- Finding hashicorp/null versions matching ">= 3.2.0"...
- Finding hashicorp/tls versions matching ">= 3.0.0"...
- Finding hashicorp/time versions matching ">= 0.9.0"...
- Finding hashicorp/cloudinit versions matching ">= 2.0.0"...
- Finding hashicorp/kubernetes versions matching ">= 2.10.0, >= 2.21.0"...
- Finding hashicorp/aws versions matching ">= 3.72.0, >= 4.0.0, >= 4.47.0, >= 4.54.0, >= 4.57.0, >= 5.1.0, >= 5.5.0"...
- Using hashicorp/null v3.2.1 from the shared cache directory
- Using hashicorp/tls v4.0.4 from the shared cache directory
- Using hashicorp/time v0.9.1 from the shared cache directory
- Using hashicorp/cloudinit v2.3.2 from the shared cache directory
- Installing hashicorp/kubernetes v2.23.0...
- Installed hashicorp/kubernetes v2.23.0 (signed by HashiCorp)
- Installing hashicorp/aws v5.17.0...
- Installed hashicorp/aws v5.17.0 (signed by HashiCorp)

## Reproduction Code [Required]

```
  # EKS Managed Node Group(s)
  eks_managed_node_group_defaults = {
    ami_type            = "BOTTLEROCKET_x86_64"
    platform            = "bottlerocket"
    ami_release_version = var.eks_bottlerocket_version

    bootstrap_extra_args = <<-EOT
    [settings.kubernetes]
    image-gc-high-threshold-percent = "85"
    image-gc-low-threshold-percent = "80"

    [settings.kubernetes.kube-reserved]
    cpu = "200m"
    ephemeral-storage = "1Gi"
    memory = "100Mi"

    [settings.kubernetes.system-reserved]
    cpu = "100m"
    ephemeral-storage = "1Gi"
    memory = "100Mi"
    EOT

    instance_types = ["m5a.large", "m6a.large", "m6i.large", "m5.large"]
    disk_size      = 20

    ## This seems to cause issues with the Load balancer controller
    ## attach_cluster_primary_security_group = true
    vpc_security_group_ids = []
    iam_role_additional_policies = {
      additional             = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
      ecr_pull_through_cache = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/${var.project}-${var.environment}-core-ecr-pull-through-cache"
    }

    # This policy is already attached to the `aws-node` service account via IRSA, keep nodes more secure.
    # Ref: https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html
    iam_role_attach_cni_policy = false
  }

  eks_managed_node_groups = {
    core = {
      min_size     = 3
      max_size     = 3
      desired_size = 3

      instance_types = ["c5.xlarge", "c5a.xlarge", "c6a.xlarge"]
      capacity_type  = "ON_DEMAND"

      labels = {
        nodegroup   = "core"
        provisioner = "managed-node-group"
      }

      taints = [
        {
          key    = "system-no-schedule"
          value  = "true"
          effect = "NO_SCHEDULE"
        }
      ]

      update_config = {
        # Do not delete existing nodes if new ones fail
        max_unavailable_percentage = 1 # or set `max_unavailable`
      }

      tags = {
      }
    }
  }
```

Create a new cluster with the default eks managed node group.

## Expected behavior

There is no entry in user_data for max-pods.
The max-pods setting gets derived from the  eni-max-pods and set according to the instance type.

## Actual behavior

max-pods get set to a fixed value of 110 in user_data.

## Additional context

Below is:
An extract of the code to set the userdata
The userdata of a node taken from from the AWS console
The output of the API client command
The user_data extracted from the Terraform state file
 
### Code setting user_data
```
  # EKS Managed Node Group(s)
  eks_managed_node_group_defaults = {
    ami_type            = "BOTTLEROCKET_x86_64"
    platform            = "bottlerocket"
    ami_release_version = var.eks_bottlerocket_version
 
    bootstrap_extra_args = <<-EOT
    [settings.kubernetes]
    image-gc-high-threshold-percent = "85"
    image-gc-low-threshold-percent = "80"
 
    [settings.kubernetes.kube-reserved]
    cpu = "200m"
    ephemeral-storage = "1Gi"
    memory = "100Mi"
 
    [settings.kubernetes.system-reserved]
    cpu = "100m"
    ephemeral-storage = "1Gi"
    memory = "100Mi"
    EOT
```

### Userdata of a node from the AWS console
```
settings.kubernetes.cluster-name = 'xxx'
settings.kubernetes.api-server = 'xxx.eu-west-1.eks.amazonaws.com'
settings.kubernetes.cluster-certificate = 'xxx'
settings.kubernetes.cluster-dns-ip = 'xxx'
settings.kubernetes.max-pods = 110
settings.kubernetes.node-labels.'eks.amazonaws.com/sourceLaunchTemplateVersion' = '2'
settings.kubernetes.node-labels.'eks.amazonaws.com/nodegroup-image' = 'ami-00714b26afc505311'
settings.kubernetes.node-labels.'eks.amazonaws.com/capacityType' = 'ON_DEMAND'
settings.kubernetes.node-labels.'eks.amazonaws.com/nodegroup' = 'core-xxx'
settings.kubernetes.node-labels.'eks.amazonaws.com/sourceLaunchTemplateId' = 'lt-xxx'
settings.kubernetes.node-labels.nodegroup = 'core'
settings.kubernetes.node-taints.system-no-schedule = 'true:NoSchedule'
settings.kubernetes.image-gc-high-threshold-percent = '85'
settings.kubernetes.image-gc-low-threshold-percent = '80'
settings.kubernetes.kube-reserved.cpu = '200m'
settings.kubernetes.kube-reserved.ephemeral-storage = '1Gi'
settings.kubernetes.kube-reserved.memory = '100Mi'
settings.kubernetes.system-reserved.cpu = '100m'
settings.kubernetes.system-reserved.ephemeral-storage = '1Gi'
settings.kubernetes.system-reserved.memory = '100Mi'
```
 
### apiclient output
```
ssm-user@control]$ apiclient get settings.kubernetes
{
  "settings": {
    "kubernetes": {
      "api-server": https://xxx.eu-west-1.eks.amazonaws.com/,
      "authentication-mode": "aws",
      "cloud-provider": "aws",
      "cluster-certificate": "xxx",
      "cluster-dns-ip": "xxx",
      "cluster-domain": "cluster.local",
      "cluster-name": "xxx-eks-cluster",
      "image-gc-high-threshold-percent": "85",
      "image-gc-low-threshold-percent": "80",
      "kube-reserved": {
        "cpu": "200m",
        "ephemeral-storage": "1Gi",
        "memory": "100Mi"
      },
      "max-pods": 110,
      "node-ip": "xxx",
      "node-labels": {
        "eks.amazonaws.com/capacityType": "ON_DEMAND",
        "eks.amazonaws.com/nodegroup": "core-xxx",
        "eks.amazonaws.com/nodegroup-image": "ami-00714b26afc505311",
        "eks.amazonaws.com/sourceLaunchTemplateId": "lt-xxx",
        "eks.amazonaws.com/sourceLaunchTemplateVersion": "2",
        "nodegroup": "core"
      },
      "node-taints": {
        "system-no-schedule": [
          "true:NoSchedule"
        ]
      },
      "pod-infra-container-image": "602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/pause:3.1-eksbuild.1",
      "provider-id": "aws:///eu-west-1a/i-05e91fb435eaacac4",
      "server-tls-bootstrap": true,
      "standalone-mode": false,
      "system-reserved": {
        "cpu": "100m",
        "ephemeral-storage": "1Gi",
        "memory": "100Mi"
      }
    }
  }
}
```
 
### Decrypted base64 user_data from the Terraform state file
```
% cat user_data.b64 | base64 -d
[settings.kubernetes]
image-gc-high-threshold-percent = "85"
image-gc-low-threshold-percent = "80"
 
[settings.kubernetes.kube-reserved]
cpu = "200m"
ephemeral-storage = "1Gi"
memory = "100Mi"
 
[settings.kubernetes.system-reserved]
cpu = "100m"
ephemeral-storage = "1Gi"
memory = "100Mi"
```

**Comment by bryantbiggs** [comment]
lets keep this issue over at https://github.com/bottlerocket-os/bottlerocket/issues/3449 - there isn't anything that this module is doing in terms of max pods. thanks!
