### ISSUE TITLE
Addon only support 1 minor version upgrade at a time.

### ISSUE THREAD

**Issue by cdenneen** [terraform-aws-modules/terraform-aws-eks#2749]
When setting addon's to latest if there happens to be 2 minor versions available it tries to get the latest and fails.

Currently running cluster 1.27

Had addon for vpc-cni at 1.13.4. Available were 1.14.0, 1.14.1 and 1.15.0 so it tries to apply 1.15.0 and errors:

```
│ Error: updating EKS Add-On (cdqa-use1:vpc-cni): InvalidParameterException: Updating VPC-CNI can only go up or down 1 minor version at a time
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: ""
│   },
│   AddonName: "vpc-cni",
│   ClusterName: "cdqa-use1",
│   Message_: "Updating VPC-CNI can only go up or down 1 minor version at a time"
│ }
│ 
│   with module.eks.aws_eks_addon.this["vpc-cni"],
│   on .terraform/modules/eks/main.tf line 382, in resource "aws_eks_addon" "this":
│  382: resource "aws_eks_addon" "this" {
│ 
╵
```

I can get around this by hardcoding the version or by performing the intermediate upgrade via the console but it would be nice if there happen to be 2 minor bumps that "latest" does some sort of check of what's the latest (next minor version available) and plans to apply that vs just grabbing the latest available.
Need some sort of logic that will perform the first 1.14.1 upgrade before another plan/apply to apply the 1.15.0 update.

**Comment by bryantbiggs** [comment]
while I agree that the functionality would be great, its not something we can support here in a module, and I don't think it makes sense in the AWS provider either. This would ultimately need to come from the AWS API for EKS addons

I would open an issue on the containers roadmap for this if one doesn't already exist https://github.com/aws/containers-roadmap/projects/1?query=is%3Aopen+sort%3Aupdated-desc
