### ISSUE TITLE
Allow excluding the cluster security group from the list of additional security groups.

### ISSUE THREAD

**Issue by tnils** [terraform-aws-modules/terraform-aws-eks#2751]
## Is your request related to a problem? Please describe.
I am importing EKS clusters created with eksctl. In my existing clusters, the cluster security group is not on the list of additional security groups. I can't import my existing EKS cluster without it being forced to recreate because the module forces the cluster security group to be part of the additional security groups.

## Describe the solution you'd like.
Adding a variable like `cluster_additional_security_group_ids_include_cluster_sg_id` which defaults to `true` to keep the current behavior, but allowing it to be set to `false` so that the cluster security group id is not added to the list of additional security group ids.

## Describe alternatives you've considered.
The only alternatives are to not use the module, or recreate my cluster.

**Comment by bryantbiggs** [comment]
Can you provide a reproduction? This doesn't quite make sense but seeing a repro will help clarify

**Comment by b-tanner** [comment]
I just opened https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2752, maybe that will help it make more sense.

I'm using `terraform import` to import and existing EKS cluster. In my existing cluster, the Cluster Security Group is not in the list of Additional Security Groups:

![image](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/141063987/6edf27fd-ffbd-4918-8427-468dfe77fe08)

As the module is currently, it adds the cluster security group to the list of additional security groups, but this change forces a replacement when running `terraform apply`. The submitted PR lets a variable `cluster_additional_security_group_ids_exclude_cluster_sg_id` be set to `true`, so the list of additional security groups will not have the cluster security group added.

**Comment by bryantbiggs** [comment]
which cluster security group - there is the primary security group which the EKS service creates automatically, and this module creates on additional security group which allows users to control the security groups rules

If you do not want to have this 2nd cluster security group created, you can set `create_cluster_security_group = false`

**Comment by b-tanner** [comment]
When my cluster was initially created with eksctl (`eksctl create cluster --name <name>`), it created two security groups. When viewing my cluster in the console, one of them is listed under Cluster Security Group, and one of them is under Additional Security Groups, as shown in the screenshot above.

I was hoping to be able to `terraform import` all my existing EKS resources using this module with module variables set such that when running `terraform apply` there would be few changes, and nothing replaced. 

It seemed that I should import the security group shown under Cluster Security Group in the AWS console as `module.eks.aws_security_group.cluster[0]`, and the security group listed under Additional Security Groups in the AWS console should be added with the variable `cluster_additional_security_group_ids`. But if I do that, the module tries to add the security group listed under Cluster Security Group to the list of Additional Security Groups, which forces replacement when running `terraform apply`.

I supposed I could set `create_cluster_security_group = false`, even though that security group does exist...or is the security group listed under Additional Security Groups the one that I should import into `module.eks.aws_security_group.cluster[0]`?

**Comment by bryantbiggs** [comment]
I haven't tried this but I don't think you should need to do anything with the Cluster Security Group in terms of Terraform import - that is not created nor controlled by Terraform, it was created by EKS. If anything, you may need to update the statefile manually after importing the cluster to specify the security group ID.

For the additional security group - you can import that into `module.eks.aws_security_group.cluster[0]`

**Comment by b-tanner** [comment]
Ah, that makes sense then. That get's me straightened out what to import where, it's looking like I can move forward now without any issues. Thanks!

**Comment by bryantbiggs** [comment]
awesome! sorry for any confusion - it can get complicated when resources that are created outside of Terraform are involved 😅 

Closing for now but please feel free to open a new issue for any further issues/questions
