### ISSUE TITLE
TF is adding 'kubernetes.io/cluster/${var.cluster_name}' in node security group which causes issue for ALB creation

### ISSUE THREAD

**Issue by akshay-cognologix** [terraform-aws-modules/terraform-aws-eks#2761]
We are using `terraform-aws-eks` module to create EKS cluster. 

When we have created the cluster, TF added `kubernetes.io/cluster/${var.cluster_name} : owned` tag to Node Security Group and Cluster Security Group, which caused following issue in creation of ALB, 

```
"error":"expect exactly one securityGroup tagged with kubernetes.io/cluster/my-cluster for eni eni-456875998, got 	[sg-123456789 sg-321456878] (clusterName: my-cluster)"}
```

We are able to solve this issue by manually removing `kubernetes.io/cluster/${var.cluster_name} : owned` tag from Node's Security Group. 

We need to remove `kubernetes.io/cluster/${var.cluster_name} : owned` tag from NodeSecurity Group module. 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/918aa7cc40cbc072836410747834de64d84f514d/node_groups.tf#L197

**Comment by bryantbiggs** [comment]
please see the FAQ in the docs https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#i-received-an-error-expect-exactly-one-securitygroup-tagged-with-kubernetesioclustername-

**Comment by akshay-cognologix** [comment]
We have created VPC using terraform-aws-vpc module only, not sure why `kubernetes.io/cluster/${var.cluster_name} : owned` is present for Node Security Group. We are using all default values. The ALB issue gets fixed when we remove the `kubernetes.io/cluster/${var.cluster_name} : owned` tag from Node's SG.
