### ISSUE TITLE
Disable `local_file` config in the `terraform plan`

### ISSUE THREAD

**Issue by chenrui333** [terraform-aws-modules/terraform-aws-eks#277]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?

Every time when I run the module, it would create two files:
- `+ module.eks.local_file.config_map_aws_auth`
- `+ module.eks.local_file.kubeconfig`

## If this is a bug, how to reproduce? Please include a code sample if relevant.

I am using the default setup for this module, so it should be fairly easy to reproduce.

## What's the expected behavior?

I wonder if I can remove disable them in the changelist? This would be really helpful in the CI builds.

## Environment details

* Affected module version: `1.7.0`
* OS: Linux
* Terraform version: `0.11.11`

**Comment by confiq** [comment]
`write_aws_auth_config=0` did not help?

**Comment by chenrui333** [comment]
let me try with that.

**Comment by chenrui333** [comment]
Did not realize this is newly-added config.
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/228

I guess I have to upgrade cluster to see if it works for my favor then.
