### ISSUE TITLE
Bug during the install of ALB ingress controller 

### ISSUE THREAD

**Issue by chejuro1** [terraform-aws-modules/terraform-aws-eks#2772]
## Description

ALB ingress controller pod failed 
I have installed the targetgroup . That CRD was missing
I am using the latest version of ALB ingress module 

kubectl logs -f pod/aws-alb-ingress-controller-68dd7f47b8-w69k8 -n kube-system
{"level":"info","ts":"2023-10-10T00:09:33Z","msg":"version","GitVersion":"v2.5.4","GitCommit":"fd1bbbbfad42fc1b05fc71027242e2fcc4496c44","BuildDate":"2023-07-12T22:41:48+0000"}
{"level":"info","ts":"2023-10-10T00:09:33Z","logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2023-10-10T00:09:33Z","logger":"setup","msg":"adding health check for controller"}
{"level":"info","ts":"2023-10-10T00:09:33Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-v1-pod"}    
{"level":"info","ts":"2023-10-10T00:09:33Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-v1-service"}
{"level":"info","ts":"2023-10-10T00:09:33Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-ingressclassparams"}
{"level":"info","ts":"2023-10-10T00:09:33Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":"2023-10-10T00:09:33Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":"2023-10-10T00:09:33Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-networking-v1-ingress"}
{"level":"info","ts":"2023-10-10T00:09:33Z","logger":"setup","msg":"starting podInfo repo"}
{"level":"info","ts":"2023-10-10T00:09:35Z","logger":"controller-runtime.webhook.webhooks","msg":"Starting webhook server"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting server","kind":"health probe","addr":"[::]:61779"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Stopping and waiting for non leader election runnables"}
I1010 00:09:35.162856       1 leaderelection.go:248] attempting to acquire leader lease kube-system/aws-load-balancer-controller-leader...
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Stopping and waiting for leader election runnables"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc0000ac500"}  
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc0000ac550"}  
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"ingress","source":"kind source: *v1.Ingress"}      
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"ingress","source":"kind source: *v1.Service"}      
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc0000ac5a0"}  
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc0000ac5f0"}  
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"ingress","source":"kind source: *v1beta1.IngressClassParams"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"ingress","source":"kind source: *v1.IngressClass"} 
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting Controller","controller":"ingress"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","source":"kind source: *v1beta1.TargetGroupBinding"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","source":"kind source: *v1.Service"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","source":"kind source: *v1.Endpoints"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","source":"kind source: *v1.Node"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting Controller","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting EventSource","controller":"service","source":"kind source: *v1.Service"}      
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting Controller","controller":"service"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting workers","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","worker count":3}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Shutdown signal received, waiting for all workers to finish","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting workers","controller":"service","worker count":3}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Shutdown signal received, waiting for all workers to finish","controller":"service"}   
{"level":"error","ts":"2023-10-10T00:09:35Z","logger":"controller-runtime.source","msg":"failed to get informer from cache","error":"Timeout: failed waiting for *v1.Node Informer to sync"}
{"level":"error","ts":"2023-10-10T00:09:35Z","logger":"controller-runtime.source","msg":"failed to get informer from cache","error":"Timeout: failed waiting for *v1beta1.IngressClassParams Informer to sync"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Starting workers","controller":"ingress","worker count":3}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Shutdown signal received, waiting for all workers to finish","controller":"ingress"}   
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"All workers finished","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"All workers finished","controller":"service"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"All workers finished","controller":"ingress"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Stopping and waiting for caches"}
{"level":"error","ts":"2023-10-10T00:09:35Z","logger":"controller-runtime.source","msg":"failed to get informer from cache","error":"Timeout: failed waiting for *v1.Endpoints Informer to sync"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Stopping and waiting for webhooks"}
{"level":"info","ts":"2023-10-10T00:09:35Z","msg":"Wait completed, proceeding to shutdown the manager"}
E1010 00:09:35.164623       1 leaderelection.go:330] error retrieving resource lock kube-system/aws-load-balancer-controller-leader: Get "https://172.20.0.1:443/api/v1/namespaces/kube-system/configmaps/aws-load-balancer-controller-leader": context canceled
{"level":"error","ts":"2023-10-10T00:09:35Z","logger":"setup","msg":"problem running manager","error":"open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory"}

**Comment by bryantbiggs** [comment]
This module is not directly involved with the ALB Controller

**Comment by chejuro1** [comment]
What  is the correct  alb module  to install alb ingress controller on EKS ?  
RegardsJules

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 9, 2023 at 8:29 p.m., Bryant ***@***.***> wrote:   


Closed #2772 as completed.

**Comment by bryantbiggs** [comment]
How did you install the ALB Controller?

**Comment by chejuro1** [comment]
I am using Terraform. I am looking to autonate all the process. I was able to install it manually ,but also to use terraform alb ingress controller to install it.
Sent from Yahoo Mail on Android 
 
  On Mon, Oct 9, 2023 at 9:01 p.m., Bryant ***@***.***> wrote:   


How did you install the ALB Controller?
