### ISSUE TITLE
Expose `tags_all` from the eks managed node groups

### ISSUE THREAD

**Issue by apetheriotis** [terraform-aws-modules/terraform-aws-eks#2774]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

Not really.

## Is your request related to a problem? Please describe.
Not really a problem or bug but limitation of the module. As of now this module exposes only the `eks-managed-group.labels` value as shown [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/eks-managed-node-group/outputs.tf#L54-L57). Though for our use case we need to have access to the `tags_all` that have been associated to the managed group as well. They are exposed by the native module already as shown [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#tags_all)

## Describe the solution you'd like.

As part of the `terraform-aws-eks/modules/eks-managed-node-group/outputs.tf` we would like to have not only the `output node_group_labels` but also `output node_group_tags_all`

## Describe alternatives you've considered.
I've tried to derive the info from `node_group_resources` output but it's not available there either.

**Comment by bryantbiggs** [comment]
What is the use case for this?

**Comment by apetheriotis** [comment]
@bryantbiggs we add some custom tags to the auto_scaling_group as shown in [this](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L462-L509) example. 

Though specifically to our use case we need to derive that information from the `tags` we assign to the managed group rather than the `labels`, because one of the labels is dynamic. 

For example, we need to assign the tag `is-disk-mount-available=1` to the ASG. But we cannot add that tag to the labels because that label needs to be added _dynamically_ by another process only when the disk-mount is actually available. But at the same time we need to add that tag to the ASG so that the autoscaler can scale from 0 to 1+, otherwise pods never get scheduled.

**Comment by bryantbiggs** [comment]
I'm sorry, I'm not following

**Comment by apetheriotis** [comment]
no worries. I'll try again with a concrete example. 

Our node_group config is as follows:

```
 "public_nodes" = {
    ...
    labels = {
      nodegroup-type = "public"
    }
    tags = {
        Name                                                           = "public-node",
        "k8s.io/cluster-autoscaler/enabled"                            = "true",
        "k8s.io/cluster-autoscaler/node-template/label/nodegroup-type" = "public"
    }
    ...
}
```

the above works fine when a pod to be scheduled has the appropriate selector such as:
```
 nodeSelector:
    nodegroup-type: public
```
and at the same time the autoscaler can scale the group from 0 to +1 without any problem. 

--- 
Though we have some pods that have a selector such as:
```
 nodeSelector:
    nodegroup-type: public
    is-mounted-disk-available: true
```
these pods are scheduled on the appropriated nodes natively by the k8s scheduler but the label (_is-mounted-disk-available: true_) is added dynamically on those nodes during runtime by another process that runs on the cluster that adds the label only at runtime and not when the ec2 machine is provisioned. 

All the above work fine apart from one thing. If the ASG is scaled to 0 and a new & only pod with the selector
```
 nodeSelector:
    nodegroup-type: public
    is-mounted-disk-available: true
```
is deployed on the cluster, then the autoscaler cannot scale the group from 0 because there is no tag `k8s.io/cluster-autoscaler/node-template/label/is-mounted-disk-available=true` but only the `k8s.io/cluster-autoscaler/node-template/label/nodegroup-type=public`.

One solution would be to adjust the labels as follows
```
    labels = {
      nodegroup-type = "public"
      is-mounted-disk-available: true
    }
```
but that would be misleading during normal operation because as mentioned this label is added dynamically by another process during deterministic time.

So our thinking is that instead of adding to the labels to add the required tag to the `tags` attribute of the node_group as follows:
```
 "public_nodes" = {
    ...
    labels = {
      nodegroup-type = "public"
    }
    tags = {
        Name                                                           = "public-node",
        "k8s.io/cluster-autoscaler/enabled"                            = "true",
        "k8s.io/cluster-autoscaler/node-template/label/nodegroup-type" = "public"
        "k8s.io/cluster-autoscaler/node-template/label/is-mounted-disk-available: true
    }
    ...
}
```

that way we still keep the dynamic approach to the `labels` but at the same time we apply the correct tags to the ASG that we derive from the `tags` rather than the `labels` attribute. 

I hope the above provides more info on this not so trivial edge case.

**Comment by bryantbiggs** [comment]
so it sounds like you want to add tags to the autoscaling group of the managed nodegroup, which is something that is supported today. I'm not seeing the connection as to why the `tags_all` property needs to be exported

**Comment by apetheriotis** [comment]
I believe my example above clearly states that we already use tags on the ASG and we automatically & dynamically create those ec2 asg tags based on the info we get from `node_group.labels` value. Instead I'd like to have the ability to get the values for the ASG tags from the `node_group.tags_all` as well. 

This info is already [provided](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#tags_all) by the underlying aws terraform module.

Feel free to close the issue though if no action will be taken.

**Comment by bryantbiggs** [comment]
thank you, but unfortunately this is not a change that we will be pursuing here. there are implications around creating cyclical dependencies here, it would be better to use local variables in your implementation to sync changes to both labels and tags if that is the desired intent
