### ISSUE TITLE
eks module upgrade guidance on `1.7.0` to `2.2.0`

### ISSUE THREAD

**Issue by chenrui333** [terraform-aws-modules/terraform-aws-eks#278]
I am still using `v1.7.0` to manage my module, I just saw the latest version `v2.2.0` (looks like there is no major version bump). I wonder what would be the upgrade path?

**Comment by max-rocket-internet** [comment]
Nothing specific. Just change the module version and see the terraform plan output to see what will happen. Feel free to open a specific issue if you have some problem 🙂
