### ISSUE TITLE
disk_size attribute ignored on existing eks_managed_node_group

### ISSUE THREAD

**Issue by dwarburt** [terraform-aws-modules/terraform-aws-eks#2780]
I have an EKS cluster that I have provisioned with cdktf like so:

```
    let eks = new Eks(this, `${details.name}-eks`, {
      clusterName: `${details.name}`,
      clusterVersion: "1.27",
      vpcId: vpc.vpcIdOutput,
      subnetIds: Token.asList(vpc.privateSubnetsOutput),
      eksManagedNodeGroupDefaults: {
        ami_type: "AL2_x86_64"
      },
      eksManagedNodeGroups: {
        two: {
          name: `${details.name}-4xl`,
          instance_types: ['r6i.4xlarge'],
          min_size: 1,
          max_size: 5
        }
      },
      tags: CommonTags,
      clusterEndpointPublicAccess: true
    });
```
And this worked very well. But I discovered that the default disk size was too small so I added
```
  disk_size: 80
```
to the configuration in the `two` object but it doesn't trigger a change to be detected when I run cdktf deploy, just a "no differences" output. 

Is it supported to change this disk_size from undefined to a number after the managed node group is provisioned?

terraform-aws-modules/eks/aws version is 19.17.2

EDIT:
Even on a new node_group, the disk_size parameter is ignored
![image](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/52614/67671aea-958e-4edd-9043-1e821b85280c)

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#setting-disk_size-or-remote_access-does-not-make-any-changes
