### ISSUE TITLE
bug: Issues adding Karpenter role to AWS auth-map

### ISSUE THREAD

**Issue by jomakori** [terraform-aws-modules/terraform-aws-eks#2781]
## Description

I've attempted trying to add the Karpenter IAM role (lines 65-72) to the AWS authmap, but I'm facing this error: 
```
│   on eks-cluster.tf line 63, in module "eks":
│   63:     aws_auth_roles = [
│   64:         # We need to add in the Karpenter node IAM role for nodes launched by Karpenter
│   65:         {
│   66:             rolearn  = module.karpenter.role_arn,
│   67:             username = "system:node:{{EC2PrivateDNSName}}"
│   68:             groups = [  
│   69:                 "system:bootstrappers",
│   70:                 "system:nodes"
│   71:             ]
│   72:         },
│   73:         {
│   74:             rolearn  = "arn:aws:sts::376424775662:assumed-role/Admin/default-session",
│   75:             username = "AWSumeAdminUser"
│   76:             groups = var.kubernetes_permissions_group
│   77:         },
│   78:         {
│   79:             rolearn  = "arn:aws:iam::376424775662:role/Admin",
│   80:             username = "ConsoleAdminUser"
│   81:             groups = var.kubernetes_permissions_group
│   82:         },
│   83:         {
│   84:             rolearn  = "arn:aws:sts::376424775662:assumed-role/engineers/default-session",
│   85:             username = "AWSumeEngineerUser"
│   86:             groups = var.kubernetes_permissions_group
│   87:         },
│   88:         {
│   89:             rolearn  = "arn:aws:iam::376424775662:role/engineers",
│   90:             username = "ConsoleEngineerUser"
│   91:             groups = var.kubernetes_permissions_group
│   92:         }
│   93:     ]
│ 
│ The given value is not suitable for module.eks.var.aws_auth_roles declared at .terraform/modules/eks/variables.tf:583,1-26: element types must all match for conversion to list.
```

I've applied the same role manually to the cluster with no issues, but it won't work on this TF module.

If your request is for a new feature, please use the `Feature request` template.

- [ x ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

> Customer note: I've done all the steps above + upgraded from 19.12 -> 19.17.2 (latest version) - same issue

## Versions

- Module version [Required]:
19.12 (original) -> 19.17.2 (latest)- same error on both versions

- Terraform version:
1.6.1 (latest)

- Provider version(s):
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.21.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.11.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/hkak03key/command v0.1.1

## Reproduction Code [Required]
(above)

1. Added new role to existing auth-map
2. init/apply plan
3. Error: `The given value is not suitable for module.eks.var.aws_auth_roles declared at .terraform/modules/eks/variables.tf:583,1-26: element types must all match for conversion to list.`

## Expected behavior

New Karpenter role to be applied to aws auth-map

## Actual behavior

Fails to do it do to error mentioned

### Terminal Output Screenshot(s)

(above)

**Comment by bryantbiggs** [comment]
one of your `var.*` for `groups` is most likely not a list of strings. closing for now until a proper reproduction can be provided to diagnose and troubleshoot
