### ISSUE TITLE
I get Error: Your query returned no results. Please change your search criteria and try again while upgrading to1.24

### ISSUE THREAD

**Issue by sankansm23** [terraform-aws-modules/terraform-aws-eks#2783]
I get error when i run terraform plan for upgrading the eks version from 1.23 to 1.24.  I never got this error before since i am using this module for more than 2 years.
ERROR

module.eks.module.eks.data.template_file.userdata[0]: Refreshing state... [id=35a2622eac555fcfdcc5a67d7f4a8107f044aaa064d1378f7826269e03bd10b0]

Error: Your query returned no results. Please change your search 

> criteria and try again.

  on .terraform/modules/eks.eks/data.tf line 27, in data "aws_ami" "eks_worker_windows":
  27: data "aws_ami" "eks_worker_windows" {

following is how call this module.

module "eks" {
  source                                    = "github.com/terraform-aws-modules/terraform-aws-eks?ref=v15.1.0"

This eks is deployed in us-east-1 region.
Can anyone pls help whats causing this?

**Comment by bryantbiggs** [comment]
Apologies but v15.x has been out of support for quite some time so we won't be able to help - I would suggest updating to v19.x
