### ISSUE TITLE
how to use tag_specifications ? help me.. 

### ISSUE THREAD

**Issue by jy-je** [terraform-aws-modules/terraform-aws-eks#2786]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 19.16

- Terraform version: 1.6.1

- Provider version(s): AWS

## Reproduction Code [Required]

eks_managed_node_groups = {
    github_runner6 = {

      use_name_prefix            = false
      use_custom_launch_template = false 
      launch_template_use_name_prefix = false 

      tag_specifications = ["instance"]
      launch_template_tags = {
          "Name" = "github-node"
      }

      launch_template_name = "gitgub-node"

      min_size     = 2
      max_size     = 3
      desired_size = 2

      instance_types = ["t3.xlarge"]
      capacity_type  = "ON_DEMAND"
      disk_size      = 50

    }

We changed the disk usage using "use_custom_launch_template=false". This setting did not automatically assign a Name tag when the EKS node was created as a template.
I confirmed that it is possible to register a launch resource tag in a template using launch_template_tags and tag_specifications, but it is not clear how to use it, so I would appreciate it if you could provide an example code.

please help..

**Comment by bryantbiggs** [comment]
please see the examples we have provided as well as the documentation/FAQ related to the use of the default launch templates
