### ISSUE TITLE
Bottlerocket managed node groups are being created as Amazon Linux

### ISSUE THREAD

**Issue by Shershebnev** [terraform-aws-modules/terraform-aws-eks#2789]
## Description

I'm trying to create bottlerocket based node groups, however for some reason whenever I use `ami_type = "BOTTLEROCKET_x86_64_NVIDIA"` (tried without nvidia as well), I get AL_x86_64 node group. I've looked at the examples with bottlerocket and don't see any specific things I'd also need to specify apart from what I already have (ami_type and platform). If I use `ami_id` with bottlerocket ami id, everything's fine. Am I missing something?

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
19.17.2
- Terraform version:

Terraform v1.5.0
on darwin_amd64
- Provider version(s):

+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.22.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.11.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
## Reproduction Code [Required]

I'm using terragrunt and also eks module is inside other module (I know this is probably not ideal), so here's the relevant bits:
Inside the module I have variable
```
variable "managed_node_groups" {
  description = "EKS managed node groups"
  type        = map(object({
    name                       = string
    ami_id                     = optional(string)
    ami_type                   = optional(string)
    platform                   = optional(string, "linux")
    enable_bootstrap_user_data = optional(bool, false)
    labels                     = optional(map(any))
    subnet_ids                 = list(string)
    use_name_prefix            = bool
    use_custom_launch_template = optional(bool, true)
    min_size                   = number
    max_size                   = number
    desired_size               = number
    instance_types             = list(string)
    capacity_type              = string
    block_device_mappings      = optional(map(any))
    description                = string
    enable_monitoring          = bool
    iam_role_tags              = optional(map(string))
    launch_template_tags       = optional(map(string))
    key_name                   = optional(string)
  }))
}
}
```
which is passed as is to eks module:
```
eks_managed_node_groups   = var.managed_node_groups
```
And I also have defaults defined like this:
```
  eks_managed_node_group_defaults = {
    ami_type        = "AL2_x86_64"
    create_iam_role = false
    iam_role_arn    = aws_iam_role.eks_nodegroup.arn
  }
```
Then in terragrunt file the bottlerocket node group is defined like this:
```
    g4dn_8xlarge_jupyterhub = {
      name       = "g4dn-8xlarge-jupyterhub"
      ami_type   = "BOTTLEROCKET_x86_64_NVIDIA"  # tried BOTTLEROCKET_x86_64 as well
      platform   = "bottlerocket"
      use_custom_launch_template = true  # tried without custom launch template as well
      subnet_ids = dependency.vpc.outputs.private_subnets
      labels     = merge(
        REDACTED
      )
      use_name_prefix       = true
      min_size              = 0
      max_size              = 10
      desired_size          = 0
      capacity_type         = "ON_DEMAND"
      instance_types        = ["g4dn.8xlarge"]
      block_device_mappings = {
        xvdb = {
          device_name = "/dev/xvdb"
          ebs         = {
            snapshot_id = REDACTED
          }
        }
      }
      key_name             = dependency.ssh_key.outputs.key_pair_name
      description          = REDACTED
      enable_monitoring    = true
      iam_role_tags        = local.tags
      launch_template_tags = merge(
        REDACTED
      )
    }
```
I'm certain that passing `ami_type` works in this setup since I have nodes with `ami_type` being set to value different from `eks_managed_node_group_defaults` (`AL2_x86_64_GPU`). Passing platform also works as I can see it in the output.

Tried reinitializing as well, didn't change anything

## Expected behavior
Node group has bottlerocket as ami type

## Actual behavior
Node group has AL2_x86_64 as ami type

**Comment by bryantbiggs** [comment]
hard to say with all of the added stuff you have going on, but I can say that these do work https://github.com/terraform-aws-modules/terraform-aws-eks/blob/51cc6bec880ac8dc361b60a4b05d5f2bcd98eb6a/examples/eks_managed_node_group/main.tf#L113-L125

**Comment by bryantbiggs** [comment]
closing for now with example provided above
