### ISSUE TITLE
Fargate profile can't create due to update in progress when using OIDC

### ISSUE THREAD

**Issue by cdenneen** [terraform-aws-modules/terraform-aws-eks#2790]
## Description

Using the following example: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/patterns/karpenter/main.tf
but adding an OIDC to the cluster causes issue creating Fargate profile:

```hcl
  cluster_identity_providers = {
    oidc = {
      client_id                     = local.name
      identity_provider_config_name = "AzureAD"
      issuer_url                    = "https://${local.name}.dex.domain.com"
      username_claim                = "email"
      groups_claim                  = "groups"
    }
  }
```

Error:
```
Error: creating EKS Fargate Profile (testdev-use1:kube-system): ResourceInUseException: Cannot create Fargate Profile kube-system because cluster testdev-use1 currently has update 
```
Terraform 1.6.3
terraform-aws-eks: 19.17.2

Before trying to use fargate profiles this worked fine with ordering for `eks_managed_node_groups` it's just when moving to the use of `fargate` profiles in this module that the problem arose. 

There needs to be some sort of way to enable the use of an OIDC in this module that tells the fargate profile to wait until resource is ready.

**Comment by bryantbiggs** [comment]
>  tells the fargate profile to wait until resource is ready.

Thats not possible here - thats down to the AWS APIs

**Comment by cdenneen** [comment]
It's not possible for the fargate_profile resource to `depends_on` the oidc resource?

**Comment by cdenneen** [comment]
To create an OIDC provider on a new cluster along with a fargate profile? 
Seems like a pretty regular scenario. Especially since the CDK and Terraform blueprints talks were based on using Fargate to provision Karpenter and avoid using managed node groups completely.
So adding an OIDC to a new cluster I understand might not be used by everyone but for those who need to do that it would be on every single cluster creation so therefore it's a complete block without this ordering.

**Comment by bryantbiggs** [comment]
closing issue for now since this is down to the EKS API
