### ISSUE TITLE
self-managed node groups not registered with cluster after switching to use submodule

### ISSUE THREAD

**Issue by congzhegao** [terraform-aws-modules/terraform-aws-eks#2792]
## Description

Before the cluster is created by defining self-managed node groups inside eks module. And I'm trying to follow the doc https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/self-managed-node-group/README.md to write those node groups using a few submodules. But after applying changes those nodes are no longer registered with EKS. The userdata of instances are identical so they should have the right cert and endpoint to register

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 19.17.2

- Terraform version:

- Provider version(s):

## Reproduction Code [Required]

```
module "default_node_group" {
  source           = "terraform-aws-modules/eks/aws//modules/self-managed-node-group"
  version = "~> 19.16.0"
  instance_refresh = ""
  ami_id           = "..."
  vpc_security_group_ids = [
    ...id,
  ]
  name                = "default"
  cluster_name        = module.eks-cluster.cluster_name
  cluster_version     = module.eks-cluster.cluster_version
  cluster_endpoint    = module.eks-cluster.cluster_endpoint
  cluster_auth_base64 = module.eks-cluster.cluster_certificate_authority_data
  instance_type       = var.config.default_instance_type

  post_bootstrap_user_data = local.userdata
  bootstrap_extra_args     = "--kubelet-extra-args '${local.default_node_kubelet_args}'"

  subnet_ids = local.private_subnets

  desired_size = 1
  min_size     = 1
  max_size     = 2

  iam_instance_profile_arn    = var.default_node_instance_profile_arn
  create_iam_instance_profile = false
  iam_role_use_name_prefix    = false

  block_device_mappings = ...

  autoscaling_group_tags = {
    ...
  }

  tags = {
    "Service" = local.service_tag
  }
}
```

## Expected behavior

Nodes are registered with EKS 

## Actual behavior

They're not

**Comment by bryantbiggs** [comment]
And what about the role used, does it have permissions to connect to the cluster

**Comment by congzhegao** [comment]
@bryantbiggs Thank you for helping out! I just double checked the IAM role attached and didn't notice anything suspicious. Here's my EKS module after the refactor
```
module "eks-cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 19.16.0"

  cluster_name    = local.cluster_name
  cluster_version = var.cluster_version

  cluster_addons = {
    ...
  }

  prefix_separator = ""
  iam_role_name    = local.cluster_name
  create_iam_role  = false
  iam_role_arn     = aws_iam_role.cluster.arn

  create_kms_key            = false
  cluster_encryption_config = []

  enable_irsa = false

  subnet_ids = ....

  vpc_id = ...

  create_cluster_security_group = false
  cluster_security_group_id     = aws_security_group.cluster.id

  create_node_security_group                   = false
  node_security_group_id                       = aws_security_group.nodes.id
  node_security_group_enable_recommended_rules = false

  aws_auth_roles = local.aws_auth_roles

  manage_aws_auth_configmap = true
  create_aws_auth_configmap = true

  ...
}
```

**Comment by congzhegao** [comment]
I found the issue - `node_security_group_id ` isn't inherited to the submodule so that's why.

**Comment by congzhegao** [comment]
@bryantbiggs Just one more question - what are the purposes of those disabled_ modules under https://github.com/ramseymcgrath/terraform-aws-eks/blob/master/examples/complete/README.md?
