### ISSUE TITLE
Configure remote access to nodes

### ISSUE THREAD

**Issue by damogallagher** [terraform-aws-modules/terraform-aws-eks#2793]
Is it possible to enable remote access to nodes using this module?

**Comment by bryantbiggs** [comment]
yes - what specific type of remote access are you looking for?

**Comment by damogallagher** [comment]
I would like to access the worker nodes in a private subnet from a bastion host.

Is there any examples of configuration for enabling remote access?

**Comment by bryantbiggs** [comment]
You can use the built in support through [EKS managed nodegroups](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/51cc6bec880ac8dc361b60a4b05d5f2bcd98eb6a/examples/eks_managed_node_group/main.tf#L106-L109) or you can also just use SSM session manager to drop directly into the nodes.

**Comment by damogallagher** [comment]
That is exactly what I need - thank you @bryantbiggs
