### ISSUE TITLE
EKS Managed Node group IAM Role and instance profile have different names

### ISSUE THREAD

**Issue by soura49** [terraform-aws-modules/terraform-aws-eks#2795]
## Description
* When we use `terraform-aws-eks` module for creating the cluster and eks managed node groups we use IAM Role for node groups as well.
* But the `Instance profile name` and `IAM role name`  for node groups are different? 
* Is there a way we can achieve the same name?

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by bryantbiggs** [comment]
EKS creates the instance profile with managed nodegroups so it's not controlled in this module
