### ISSUE TITLE
Error: module.eks.aws_iam_role.cluster: : invalid or unknown key: permissions_boundary

### ISSUE THREAD

**Issue by guizmaii** [terraform-aws-modules/terraform-aws-eks#280]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

When `terraform plan ...`:

`Error: module.eks.aws_iam_role.cluster: : invalid or unknown key: permissions_boundary`

## If this is a bug, how to reproduce? Please include a code sample if relevant.

I'm just updating the module from v2.1.0 to v2.2.0.
I don't change anything else in my configuration.

## What's the expected behavior?

Just work as it worked with v2.1.0.

## Are you able to fix this problem and submit a PR? Link here if you have already.

No

## Environment details

* Affected module version: v2.2.2
* OS: Linux
* Terraform version: 0.11.8

**Comment by confiq** [comment]
what is your version of aws provider? 
less than [1.30.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1360-september-13-2018) ?

**Comment by guizmaii** [comment]
"~> 1.27.0"
