### ISSUE TITLE
Unable to download the eks module when git binary is not present

### ISSUE THREAD

**Issue by alita1991** [terraform-aws-modules/terraform-aws-eks#2802]
## Description

I'm running terraform init to download the terraform-aws-module and because I don't have git, the init process failed.

## Versions

- Module version [Required]: v19.18.0
- Terraform version: not relevant
- Provider version(s): not relevant

## Reproduction Code [Required]

```
module "eks" {
  # https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/19.15.2
  source  = "terraform-aws-modules/eks/aws"
  version = "19.18.0"
```

1. import the module (main.tf)
2. run terraform init

## Expected behavior

Should download the module successfully via https (like other upstream modules)

## Actual behavior

```
│ Error: Failed to download module
│ 
│ Could not download module "eks" (main.tf:54) source code from
│ "git::https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v19.18.0": error downloading
│ 'https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v19.18.0': git must be available and on the PATH.
```

**Comment by bryantbiggs** [comment]
this is not something that the module controls - either your source is not as you have shown in the issue or something else is configured incorrectly on your machine

**Comment by alita1991** [comment]
Hi,

I tested on a fresh machine where I have no git client installed, the only workaround is the following:

```
module "eks" {
  source = "https://github.com/terraform-aws-modules/terraform-aws-eks/archive/refs/tags/v19.18.0.zip"
```

Is there any other solution for the issue I have?

Thanks

**Comment by bryantbiggs** [comment]
again, this is not something this module controls - you should open a ticket against the Terraform core project
