### ISSUE TITLE
When deleting the cluster its stuck on network as some nginx-ingress-controller LBs are still there

### ISSUE THREAD

**Issue by maxkokocom** [terraform-aws-modules/terraform-aws-eks#2808]
## Description

Terraform destroy of EKS does not allow nginx-ingress-controller to do a gracefull cleanup of aws reasources. Deletion of VPN and subnets causes the destroy to fail. This is an old error for many years, but I couldn't find an issue on EKS tf module. Found it in some other projects. Maybe provisioner running kubectl delete ns var.list_of_namespace_to_destroy_gracefully would be a solution?

**Comment by bryantbiggs** [comment]
This is outside the scope of the module - you'll need to remove those resources running on the cluster before destroying the cluster

**Comment by maxkokocom** [comment]
I don't think this is outside of the module scope. I am not saying module should magicly do it and know all different resources, but providing a mechanism to run aws/kubectl cli commands, or some other way should be a way rather then having a terraform which is failing and you have to manually go to AWS UI everytime you run destroy.
