### ISSUE TITLE
Karpenter IRSA Policy does not contain permissions to work with  IAM Instance Profile

### ISSUE THREAD

**Issue by ArchitKhanna** [terraform-aws-modules/terraform-aws-eks#2811]
## Description

After upgrading our Karpenter setup to v0.32.0, we noticed that the IAM Instance profile was not getting created by Karpenter using the spec.role field introduced in the EC2NodeClass in this release. 

The logs from the Karpenter pods show the following error -
```
{"level":"ERROR","time":"2023-11-09T10:22:08.767Z","logger":"controller","message":"Reconciler error","commit":"3a61217","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"nodeclass"},"namespace":"","name":"nodeclass","reconcileID":"d0173c52-78f1-44e8-840f-0f86562dca2f","error":"resolving instance profile, getting instance profile \"<redacted>\", AccessDenied: User: arn:aws:sts::<redacted>:assumed-role/KarpenterIRSA-<redacted>/<redacted> is not authorized to perform: iam:GetInstanceProfile on resource: instance profile <redacted> because no identity-based policy allows the iam:GetInstanceProfile action\n\tstatus code: 403, request id: <redacted>"}
```

I manually added the permissions to the policy via the AWS console and was able to get this working.  However, we would like to implement this through Terraform. 

Can the module be updated to include these permissions in the Karpenter IRSA policy or is there a way to customize this policy?

- [ y] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v19.19.0

- Terraform version: 1.1.7

- Provider version(s):
Terraform v1.1.7
on darwin_amd64
provider registry.terraform.io/hashicorp/aws v5.23.1
provider registry.terraform.io/hashicorp/cloudinit v2.3.2
provider registry.terraform.io/hashicorp/helm v2.11.0
provider registry.terraform.io/hashicorp/kubernetes v2.23.0
provider registry.terraform.io/hashicorp/local v2.4.0
provider registry.terraform.io/hashicorp/null v3.2.1
provider registry.terraform.io/hashicorp/template v2.2.0
provider registry.terraform.io/hashicorp/tls v4.0.4
provider registry.terraform.io/hashicorp/vault v3.21.0
provider registry.terraform.io/rancher/rancher2 v1.25.0

## Reproduction Code [Required]

Module Code 
```
module "karpenter" {
  count   = var.karpenter ? 1 : 0
  source  = "terraform-aws-modules/eks/aws//modules/karpenter"
  version = "19.19.0"

  cluster_name = module.aws-eks.cluster_id

  irsa_oidc_provider_arn          = module.aws-eks.oidc_provider_arn
  irsa_namespace_service_accounts = ["karpenter:karpenter"]

  create_iam_role = false
  iam_role_arn    = module.aws-eks.eks_node_iam_role_arn
}
```

Karpenter Helm Release
```
resource "helm_release" "karpenter" {
  count            = var.karpenter ? 1 : 0
  namespace        = "karpenter"
  create_namespace = true

  name       = "karpenter"
  repository = "oci://public.ecr.aws/karpenter"
  chart      = "karpenter"
  version    = "v0.32.0"

  set {
    name  = "settings.aws.clusterName"
    value = var.cluster_name
  }

  set {
    name  = "settings.aws.clusterEndpoint"
    value = module.aws-eks.cluster_endpoint
  }

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = module.karpenter[count.index].irsa_arn
  }

  set {
    name  = "settings.aws.defaultInstanceProfile"
    value = module.karpenter[count.index].instance_profile_name
  }

  set {
    name  = "settings.aws.interruptionQueueName"
    value = module.karpenter[count.index].queue_name
  }

}
```

1. Deploy Karpenter via the Terraform module on the EKS cluster
2. Create the NodeClass and NodePool in the cluster for Karpenter to use
3. Check the 'status' field in the NodeClass YAML after creation or 
4. Check the Karpenter pod logs for errors as shown above

## Expected behavior

1. Karpenter is able to create an IAM Instance Profile from the role specified and the 'status' field in the NodeClass YAML gets updated with that value as shown here - https://karpenter.sh/v0.32/concepts/nodeclasses/#statusinstanceprofile

## Actual behavior

1. Karpenter fails to create the IAM Instance Profile due to lack of permissions as shown in the following logs - 

`{"level":"ERROR","time":"2023-11-09T10:22:08.767Z","logger":"controller","message":"Reconciler error","commit":"3a61217","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"nodeclass"},"namespace":"","name":"nodeclass","reconcileID":"d0173c52-78f1-44e8-840f-0f86562dca2f","error":"resolving instance profile, getting instance profile \"<redacted>\", AccessDenied: User: arn:aws:sts::<redacted>:assumed-role/KarpenterIRSA-<redacted>/<redacted> is not authorized to perform: iam:GetInstanceProfile on resource: instance profile <redacted> because no identity-based policy allows the iam:GetInstanceProfile action\n\tstatus code: 403, request id: <redacted>"}`

**Comment by bryantbiggs** [comment]
since this was a recent change that adds new permissions that are required starting on v0.32, you'll need to opt into these additional permissions by setting `enable_karpenter_instance_profile_creation = true`

**Comment by ArchitKhanna** [comment]
@bryantbiggs I actually did set that value but I am getting the following error - happens only when I set the value.
```
╷
│ Error: Missing required argument
│
│   with helm_release.karpenter[0],
│   on main.tf line 113, in resource "helm_release" "karpenter":
│  113: resource "helm_release" "karpenter" {
│
│ The argument "set.5.value" is required, but no definition was found.
```

**Comment by bryantbiggs** [comment]
the reproduction code you provided above does not have this argument. I would suggest you take a look at the example we have provided https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/karpenter
