### ISSUE TITLE
Cannot import an old cluster because there is no way to customize cluster_additional_security_group_ids

### ISSUE THREAD

**Issue by esergion** [terraform-aws-modules/terraform-aws-eks#2813]
## Description

Trying to import an old cluster, that was created using old v17 module.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/dfed830957079301b879814e87608728576dd168/main.tf#L34

This SGs concatenating prevents importing by adding `cluster_security_group_id` to the `security_group_ids` and thus forcing cluster recreation. Concatenation was introduced with https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1680

## Versions

- Module version [Required]: 19.19.0

- Terraform version: v1.5.7

- Provider version(s): hashicorp/aws v5.22.0

## Reproduction Code [Required]

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "19.19.0"

  vpc_id     = local.vpc_id
  subnet_ids = local.subnet_ids

  cluster_name                    = local.cluster_name
  cluster_version                 = "1.28"

  cluster_addons = {
    vpc-cni = {}
    kube-proxy = {}
    coredns = {}
  }

  cluster_security_group_name            = "${local.cluster_name}-cluster-sg"
  cluster_security_group_use_name_prefix = false
  cluster_security_group_description     = local.cluster_security_group_description
  cluster_additional_security_group_ids  = ["sg-1234567891112"]
}
```

```
terraform import 'module.eks.aws_eks_cluster.this[0]' my-cluster-name
terraform plan
```

## Expected behavior

Cluster imported without recreating

## Actual behavior

```
      ~ vpc_config {
          ~ cluster_security_group_id = "sg-primaryclustersg" -> (known after apply)
          ~ endpoint_private_access   = false -> true
          ~ security_group_ids        = [ # forces replacement
              + "sg-primaryclustersg",
                # (1 unchanged element hidden) 
            ]
          ~ vpc_id                    = "vpc-0000000000000" -> (known after apply)
            # (3 unchanged attributes hidden)
        }
```

## Additional context

I think there should be some flag-variable to customize additional cluster security groups instead of just concatenating them with "primary" SG, otherwise it's not possible to import any cluster that was created with pre 18 versions of the module.

**Comment by bryantbiggs** [comment]
I suspect you are mixing up the security groups when importing.

**Comment by esergion** [comment]
> I suspect you are mixing up the security groups when importing.

Thanks, that's seems like a correct assumption, I was confusing SG created by AWS and 'cluster_security_group' in the module. Closing
