### ISSUE TITLE
Custom IAM roles for cluster and workers

### ISSUE THREAD

**Issue by erks** [terraform-aws-modules/terraform-aws-eks#282]
# Support custom IAM roles for cluster and workers

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Some organizations have restricted access to IAM resources and cannot create or update them directly. The workflow is that IAM resources are created by a separate team, then another team uses them to create and maintain the clusters/workers. Currently, this module requires a full IAM permission to be granted for a user setting up an EKS cluster/workers.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

N/A

## What's the expected behavior?

This module accepts custom IAM roles as inputs and uses those during the provisioning process without creating or updating any IAM resources directly.

## Are you able to fix this problem and submit a PR? Link here if you have already.

https://github.com/terraform-aws-modules/terraform-aws-eks/pull/338

## Environment details

* Affected module version: 2.2.1
* OS: Amazon Linux 2
* Terraform version: 0.11.11

## Any other relevant info

None.

**Comment by max-rocket-internet** [comment]
I think other people have requested this.

Is it possible to just import the pre-existing IAM resources so your `terraform apply` is not actually calling the IAM API?

**Comment by th31nitiate** [comment]
I currently agree with this and I am now having to fork this so that we can I can add IAM logging roles

**Comment by RothAndrew** [comment]
+1 on this. My team has run into this issue as well. We initially gave all of our DevSecOps people the "Power User" role, but Power User doesn't include IAM, so it didn't work.

**Comment by eperdeme** [comment]
You can use IAM boundaries to add IAM limitations but allow teams in your business to create IAM roles.

We use this feature to deny all teams from creating VPC* functions and enforce via boundary that any role they create, must inherit the boundary. It works really well to 'delegate' IAM creation but with enforced  boundaries.

**Comment by rottenbytes** [comment]
I faced the same problem. forked and patched. I opened a PR : https://github.com/terraform-aws-modules/terraform-aws-eks/pull/308

**Comment by erks** [comment]
Since https://github.com/terraform-aws-modules/terraform-aws-eks/pull/308 doesn't fully solve my use case (still require IAM write access), I took a stab at it here: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/282. Please take a look.

**Comment by max-rocket-internet** [comment]
Can those who are interested in this feature test the PR from @erks?
