### ISSUE TITLE
NodeGroup creation starting before cluster_addons  are ready

### ISSUE THREAD

**Issue by mr-pwatson** [terraform-aws-modules/terraform-aws-eks#2820]
## Description

I am creating an EKS cluster from an empty environment and wish to use the VPC-CNI addon. 

During testing if the nodegroup creation starts before the VPC-CNI installation is complete then the nodegroup is not configured for VPC-CNI

If I delete the nodegroup and rerun terraform then the nodegroup is correctly configured

I can see dataplane_wait_duration feature which will put a delay between the eks completing and the nodegroup starting, but the addons seem to take a variable amount of time to execute and this adds a permanent delay

I have adjusted time_sleep in node_groups.tf to depend on aws_eks_addon.before_compute being completed

This seems to work for VPC-CNI which can complete without a nodegroup, but isn't the case for all addons so people could end up in trouble

- [X ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version:
19.20

- Terraform version:
1.53

- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v5.25.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4

## Reproduction Code [Required]

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 19.0"

  cluster_name    = "test"
  cluster_version = 1.28

  vpc_id     = data.aws_vpc.selected.id
  subnet_ids = data.aws_subnets.selected.ids

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false

  create_cloudwatch_log_group = true
  cluster_enabled_log_types   = ["api", "audit", "authenticator", "controllerManager", "scheduler"]

  enable_irsa = true

  create_kms_key                  = true
  kms_key_deletion_window_in_days = 7
  enable_kms_key_rotation         = true
  kms_key_description             = "KMS Secrets encryption for EKS cluster."
  kms_key_enable_default_policy   = true

  cluster_addons = {
    vpc-cni = {
      most_recent               = true
      before_compute            = true
      configuration_values    = jsonencode({
        env = {
          # Reference docs https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html
          ENABLE_PREFIX_DELEGATION = "true"
          WARM_PREFIX_TARGET       = "1"
        }
      })
    }
  }
  # Managed Node Groups
  eks_managed_node_group_defaults = {
    ami_type                    = local.vars.node_group_settings.ami_type
    disk_size                   = local.vars.node_group_settings.disk_size
    iam_role_attach_cni_policy  = true
  }
  eks_managed_node_groups = {
    NodeGroup = {
      desired_size = local.vars.node_group_settings.desired_size
      max_size     = local.vars.node_group_settings.max_size
      min_size     = local.vars.node_group_settings.min_size

      instance_types = local.vars.node_group_settings.instance_types
      capacity_type  = local.vars.node_group_settings.capacity_type
    }
  }
}
```

Simply run the 

## Expected behavior

For the vpc-cni addon to complete before the nodegroup starts

## Actual behavior

30 seconds after EKS creation completes (but before the vpc-cni completes) the nodegroup creation starts 

## Additional context

It might be worth splitting the vpc-cni installation into a separate feature, but that would be a lot of work

**Comment by bryantbiggs** [comment]
I'm not quite following - the `before_compute` flag for addons is provided to specify that the addon should be resolved prior to provisioning compute resources - specifically for the VPC CNI but there may be other addons that its applicable for
