### ISSUE TITLE
Terraform support for modifying eks cluster subnets 

### ISSUE THREAD

**Issue by vrulahoti** [terraform-aws-modules/terraform-aws-eks#2822]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

Updating EKS subnets is now supported as per following new offerings by aws 
https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-eks-modification-cluster-subnets-security/ 
Though latest terraform-aws-eks module tries to recreate cluster if control plane subnets are changed. 

## Describe the solution you'd like.

When cluster subnets are modified in terraform-aws-eks module, it should update cluster subnets and not recreate cluster 
this is newly supported feature by aws
https://docs.aws.amazon.com/cli/latest/reference/eks/update-cluster-config.html 
https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-eks-modification-cluster-subnets-security/ 
## Describe alternatives you've considered.

R## Additional context

I had requirement to adapt to new subents and move away from existing subnets in same vpc. Though I could do that from UI without destroying cluster, terraform laters eks module always recreates cluster if control plane subnets are modified.

**Comment by bryantbiggs** [comment]
This is available from [v5.25.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5250-november-10-2023) 

Provided that you update your local provider version to at least 5.25, you can utilize this functionality today
