### ISSUE TITLE
Output node_security_group_id is null when using node_security_group_id

### ISSUE THREAD

**Issue by leogargu** [terraform-aws-modules/terraform-aws-eks#2828]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
`v19.20.0`
- Terraform version:
`v1.5.0`
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v5.26.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

## Reproduction Code [Required]

```hcl
################################################################################
# EKS Module
################################################################################

module "eks" {
  source = "../.."

  cluster_name                   = local.name
  cluster_endpoint_public_access = true

  cluster_addons = {
    coredns = {
      preserve    = true
      most_recent = true
    }
    kube-proxy = {
      most_recent = true
    }
    vpc-cni = {
      most_recent = true
    }
  }

  vpc_id                   = module.vpc.vpc_id
  subnet_ids               = module.vpc.private_subnets
  control_plane_subnet_ids = module.vpc.intra_subnets

  # 👉 Do not create the node SG...
  create_node_security_group = false

  eks_managed_node_groups = {
    green = {
      # 👉...because we're providing a pre-existing security group
      node_security_group_id = aws_security_group.my_group.id
      min_size     = 1
      max_size     = 10
      desired_size = 1

      instance_types = ["t3.large"]
      capacity_type  = "SPOT"

      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 100
            volume_type           = "gp3"
            iops                  = 3000
            throughput            = 150
            delete_on_termination = true
          }
        }
      }
    }
  }
}

################################################################################
# Supporting resources
################################################################################
resource "aws_security_group" "my_group" {
  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }
}

provider "aws" {
  region = local.region
}

data "aws_availability_zones" "available" {}
data "aws_caller_identity" "current" {}

locals {
  name   = "ex-${replace(basename(path.cwd), "_", "-")}"
  region = "eu-west-2"

  vpc_cidr = "10.0.0.0/16"
  azs      = slice(data.aws_availability_zones.available.names, 0, 3)

  tags = {
    Example    = local.name
    GithubRepo = "terraform-aws-eks"
    GithubOrg  = "terraform-aws-modules"
  }
}


module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 4.0"

  name = local.name
  cidr = local.vpc_cidr

  azs             = local.azs
  private_subnets = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 4, k)]
  public_subnets  = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 8, k + 48)]
  intra_subnets   = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 8, k + 52)]

  enable_nat_gateway = true
  single_nat_gateway = true

  public_subnet_tags = {
    "kubernetes.io/role/elb" = 1
  }

  private_subnet_tags = {
    "kubernetes.io/role/internal-elb" = 1
  }

  tags = local.tags
}

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.57"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.10"
    }
  }
}

################################################################################
# Outputs
################################################################################

output "node_sg_id" {
  value = module.eks.node_security_group_id
  description = "ID of the node shared security group"
}
```

```
terraform init
terraform apply
```

## Expected behavior

The output `node_sg_id` has the same value as `aws_security_group.my_group.id` 

## Actual behavior

The output `node_sg_id` is `null` (it's not returned in the Outputs)

### Terminal Output Screenshot(s)

N/A

## Additional context

To be fair, I'm not sure whether this is a bug or a documentation issue! The module outputs something called `node_security_group_id`, so I would expect it to be the id of the security group attached to the nodes, regardless of how it was created (inside or outside the module). But the output only returns the id of the security group [that the module _created_](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/ec454c51cb0026254b68cafe7aa9d05f873af990/outputs.tf#L99) (so if it doesn't create it, it returns `null`).
It'd be useful if the module returned the id of the security group actually attached to the nodes, but maybe the output name or its description just needs some tweaking?  (`"ID of the node shared security group, if create_node_security_group = true, null otherwise"`)

**Comment by bryantbiggs** [comment]
> regardless of how it was created (inside or outside the module)

Thats not how its designed. You can pass in n-number of security groups to attach to the nodes created. This output is strictly for the node security group created by the module
