### ISSUE TITLE
How to add worker nodes?

### ISSUE THREAD

**Issue by acim** [terraform-aws-modules/terraform-aws-eks#283]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

No worker nodes.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Probably not.

## What's the expected behavior?

Have some worker nodes.

## Environment details

* Affected module version: 2.2.1
* OS: OSX 10.14.3
* Terraform version: 0.11.11

## Any other relevant info

I tried to add node resource and I can see new EC2 instance in AWS Console and kubectl get nodes, but after some time it is not visible in kubectl get nodes, but still present in EC2 instances.

**Comment by brandoconnor** [comment]
Hey @acim -

It's hard to say what's going on here. From your description, the nodes are created and exist when queried via kubectl, but eventually don't show up as active/available to the cluster. I have questions:

* What does terraform tell you afterward when you run plan using the same code?
* Are there logs on the nodes indicating failure to connect? Do they have the necessary tags still? Is the `kubelet` running on them?
* What does the timeline look like on each of the events described? Minutes? hours?

Hopefully these questions help us get to the bottom of it.

**Comment by brandoconnor** [comment]
This is nearly 2 weeks stale now. Closing it out as I either your issue is resolved OR you've given up entirely on using EKS. It's okay! I'd use GKE myself anyway ;)

**Comment by acim** [comment]
I didn't tag my VPC so this was probably the reason that it didn't work. Thank you 😊
