### ISSUE TITLE
Support for `instance_maintenance_policy` block in `self_managed_node_group_defaults / self_managed_node_groups`

### ISSUE THREAD

**Issue by igor-nikiforov** [terraform-aws-modules/terraform-aws-eks#2830]
## Is your request related to a new offering from AWS?
In the latest version of AWS provider 5.26.0 was added support for `instance_maintenance_policy` which controls how many instance should be InService during replacement.

## Is your request related to a problem? Please describe.

More context about problem in AWS blog post: https://aws.amazon.com/blogs/compute/introducing-instance-maintenance-policy-for-amazon-ec2-auto-scaling/

## Describe the solution you'd like.

I want to have configuration block `instance_maintenance_policy` in `self_managed_node_group_defaults / self_managed_node_groups`.

Recently this feature was added in autoscaling module in this PR https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/251

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.0.0 :tada:
