### ISSUE TITLE
Adding annotations to `kubernetes` service

### ISSUE THREAD

**Issue by ajax-bychenok-y** [terraform-aws-modules/terraform-aws-eks#2835]
We have EKS installed with latest `terraform-aws-eks` module version.
And we are using Datadog  for monitoring everything including this EKS cluster.

For enabling [API server metrics](https://aws.github.io/aws-eks-best-practices/reliability/docs/controlplane/#monitor-control-plane-metrics) in Datadog additional annotations to `kubernetes` service are [needed](https://docs.datadoghq.com/containers/kubernetes/control_plane/?tab=helm#EKS).

The question is whether it's possible to manage these annotations with `terraform-aws-eks` module?
How `terraform-aws-eks` next apply or cluster upgrade will influence on such custom annotations?

**Comment by bryantbiggs** [comment]
Outside of the `aws-auth` configMap (which is slated to be removed soon), this module does not interact with any of the internal resources within the cluster. I would suggest taking a look at the Kubernetes Terraform provider to see if you can add the annotations with it
