### ISSUE TITLE
Launch Template ID output for EKS managed nodegroups

### ISSUE THREAD

**Issue by shezaan** [terraform-aws-modules/terraform-aws-eks#2836]
Based on documentation, the `desired_size` attribute can only be changed from outside the module. So thats what I tried doing using the following terraform code...

```
resource "aws_autoscaling_group" "modify_staging_eks1" {
  name = module.staging_eks1.eks_managed_node_groups_autoscaling_group_names[0]
  max_size = 3
  min_size = 2
  desired_capacity = 2
  launch_template {
    id = module.staging_eks1.eks_managed_node_groups_autoscaling_group_names[0].launch_template.id
  }
  depends_on = [ module.staging_eks1 ]
}
```

I however run into this error, which makes sense

```
╷
│ Error: Unsupported attribute
│ 
│   on main.tf line 146, in resource "aws_autoscaling_group" "modify_staging_eks1":
│  146:     id = module.staging_eks1.eks_managed_node_groups_autoscaling_group_names[0].launch_template[0].id
│     ├────────────────
│     │ module.staging_eks1.eks_managed_node_groups_autoscaling_group_names[0] is "eks-test-20231123151009631200000001-12c5fe5d-9b89-969f-f5b2-029f34226dfe"
│ 
│ Can't access attributes on a primitive-typed value (string).
╵

Exited with code exit status 1
```

This is the relevant part of the module...

```
  eks_managed_node_group_defaults = {
    instance_types = ["m6i.large", "m5.large", "m5n.large", "m5zn.large"]
    vpc_security_group_ids = [aws_security_group.remote_access.id]
  }

  eks_managed_node_groups = {
    # Node Group "test"
    test = {
      use_custom_launch_template = true
      # disk_size = 10
      iam_role_additional_policies = {
        AmazonEC2ContainerRegistryReadOnly = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      }
      min_size     = 1
      max_size     = 1
      desired_size = 1 # https://github.com/terraform-aws-modules/terraform-aws-eks/blob/ec454c51cb0026254b68cafe7aa9d05f873af990/docs/faq.md?plain=1#L56
      instance_types = ["t3.xlarge"]
      key_name = "staging-us-east" # SSH Key
      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 25
            volume_type           = "gp3"
            encrypted             = true
            # kms_key_id            = module.ebs_kms_key.key_arn
            delete_on_termination = true
          }
        }
      }
    }
  }
```

Also, note that `use_custom_launch_template` is not being honoured. Which is to say that while the custom LT is created, it is not what is being used by the ASG which is using its own LT but seems to be using the same (correct) block device mappings as specified above.
What am I doing wrong?

**Comment by shezaan** [comment]
That hack worked but I'm still trying to understand why the custom LT that was created by the module is not being used. The module seems to use the eks LT instead of the node group LT for some reason?

**Comment by bryantbiggs** [comment]
This module defaults to using a custom launch template because it gives users more control and they don't really know it even exists (the module creates it on their behalf). This is what provides tags to the autoscaling groups, allows you to customize the security groups used, etc. 

When a custom launch template is used, it is merged in with a launch template created by the EKS managed nodegroup (or rather, the values of the custom launch template are merged with the values provided by EKS managed nodegroup and it then creates a resulting launch template that is used)

So you can somewhat think of it as - `test-xxxx` LT + `<nodegroup supplied values>` = `eks-xxx` LT

**Comment by shezaan** [comment]
Thanks so much for the explanation and the solution to the desired_size problem. Much appreciated!!!
