### ISSUE TITLE
Error when adding dependencies on building pre_bootstrap_user_data

### ISSUE THREAD

**Issue by bronzehero** [terraform-aws-modules/terraform-aws-eks#2838]
## Description

When adding a dependency from another module to build the pre_bootstrap_user_data I'm getting the following error:

│ Error: Invalid count argument
│ 
│   on .terraform/modules/downstream-clusters-EKS.eks/modules/_user_data/main.tf line 67, in data "cloudinit_config" "linux_eks_managed_node_group":
│   67:   count = var.create && var.platform == "linux" && var.is_eks_managed_node_group && !var.enable_bootstrap_user_data && var.pre_bootstrap_user_data != "" && var.user_data_template_path == "" ? 1 : 0
│ 
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be
│ created. To work around this, use the -target argument to first apply only
│ the resources that the count depends on.

My code looks like this:

pre_bootstrap_user_data = templatefile("${path.module}/startup_script.tpl", { cluster = var.cluster-name, file_system_ids = join(" ", toset(module.efs_list[0].efs_ids)) })

My goal is to create EFS before the cluster to pass the efs_ids to the bootstrap script

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 19.20.0

## Reproduction Code [Required]

pre_bootstrap_user_data = templatefile("${path.module}/startup_script.tpl", { cluster = var.cluster-name, file_system_ids = join(" ", toset(module.efs_list[0].efs_ids)) })

## Expected behavior

No error due to adding a dependency, I would like to buils EFS before the cluster to pass the id's to the user_data

## Actual behavior

│ Error: Invalid count argument
│ 
│   on .terraform/modules/downstream-clusters-EKS.eks/modules/_user_data/main.tf line 67, in data "cloudinit_config" "linux_eks_managed_node_group":
│   67:   count = var.create && var.platform == "linux" && var.is_eks_managed_node_group && !var.enable_bootstrap_user_data && var.pre_bootstrap_user_data != "" && var.user_data_template_path == "" ? 1 : 0
│ 
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be
│ created. To work around this, use the -target argument to first apply only
│ the resources that the count depends on.

### Terminal Output Screenshot(s)

![image](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/34273273/9bdcb093-32a5-4caf-a8b0-83d7d571fe16)

## Additional context

My goal is to create EFS before the cluster to pass the efs_ids to the bootstrap script

**Comment by bryantbiggs** [comment]
please provide a minimal reproduction

you most likely have an explicit `depends_on` that you should not have

**Comment by bronzehero** [comment]
thanks @bryantbiggs!

The problem is indeed the dependency, why I should not have it? I need the efs id's in my user data.

Regards,

**Comment by bryantbiggs** [comment]
You don't need an explicit dependency when you have an implicit dependency - the user data won't be rendered until the EFS IDs are resolved, this is what Terraform handles automatically for you

**Comment by bronzehero** [comment]
I don't have a explicit dependency (depends_on) on my code I just have a reference to an external module (implicit dependency):

pre_bootstrap_user_data = templatefile("${path.module}/startup_script.tpl", { cluster = var.cluster-name, file_system_ids = join(" ", toset(module.efs_list[0].efs_ids)) })

The problem is that with the implicit dependency I get the following error:

│ on .terraform/modules/downstream-clusters-EKS.eks/modules/_user_data/main.tf line 67, in data "cloudinit_config" "linux_eks_managed_node_group":
│ 67: count = var.create && var.platform == "linux" && var.is_eks_managed_node_group && !var.enable_bootstrap_user_data && var.pre_bootstrap_user_data != "" && var.user_data_template_path == "" ? 1 : 0
│
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be
│ created. To work around this, use the -target argument to first apply only
│ the resources that the count depends on.

**Comment by bronzehero** [comment]
Hi @bryantbiggs,

I've prepared the code and below you can find how to reproduced it:

    module "eks" {
      source                   = "terraform-aws-modules/eks/aws"
      version                  = "~> 19.0"
      cluster_version          = "1.23"
      cluster_name             = var.cluster-name
      control_plane_subnet_ids = compact([var.subnet-CP-az-a, var.subnet-CP-az-b])
      subnet_ids               = compact([var.subnet-az-a, var.subnet-az-b])
      vpc_id                   = var.vpc-id
      eks_managed_node_group_defaults = {
        pre_bootstrap_user_data = templatefile("${path.module}/startup_script.tpl", { cluster = var.cluster-name, file_system_ids = join(" ", module.efs_list[0].efs_ids) })
      }
      eks_managed_node_groups = {
        green = {
          min_size     = 1
          max_size     = 10
          desired_size = 1
    
          instance_types = ["t3.large"]
          capacity_type  = "SPOT"
        }
      }
    }

The error I'm getting with this code is the following:

> │ Error: Invalid count argument
│ 
│   on .terraform/modules/downstream-clusters-EKS.eks/modules/_user_data/main.tf line 67, in data "cloudinit_config" "linux_eks_managed_node_group":
│   67:   count = var.create && var.platform == "linux" && var.is_eks_managed_node_group && !var.enable_bootstrap_user_data && var.pre_bootstrap_user_data != "" && var.user_data_template_path == "" ? 1 : 0
│ 
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be
│ created. To work around this, use the -target argument to first apply only
│ the resources that the count depends on.

**Comment by bronzehero** [comment]
Hi @bryantbiggs 

I've simplified the code to just create a single EFS and do everything inside a single module but I get same error:

    module "eks" {
      source                   = "terraform-aws-modules/eks/aws"
      version                  = "~> 19.0"
      cluster_version          = "1.23"
      cluster_name             = var.cluster-name
      control_plane_subnet_ids = compact([var.subnet-CP-az-a, var.subnet-CP-az-b])
      subnet_ids               = compact([var.subnet-az-a, var.subnet-az-b])
      vpc_id                   = var.vpc-id
      eks_managed_node_group_defaults = {
        pre_bootstrap_user_data = templatefile("${path.module}/startup_script.tpl", { cluster = var.cluster-name, file_system_ids = module.efs[0].efs_id })
      }
      eks_managed_node_groups = {
        green = {
          min_size     = 1
          max_size     = 10
          desired_size = 1
    
          instance_types = ["t3.large"]
          capacity_type  = "SPOT"
        }
      }
    }

    module "efs" {
      count  = var.efs_name != null ? 1 : 0
      source = "./modules/efs"
    
      efs_name     = var.efs_name
      kms_arn      = data.aws_kms_alias.kaas_eks_kms.arn
      cluster_name = var.cluster-name
      vpc_id       = var.vpc-id
    }

    output "efs_id" {
      value = aws_efs_file_system.efs.id
    }

> ╷
> │ Error: Invalid count argument
> │ 
> │   on .terraform/modules/downstream-clusters-EKS.eks/modules/_user_data/main.tf line 67, in data "cloudinit_config" "linux_eks_managed_node_group":
> │   67:   count = var.create && var.platform == "linux" && var.is_eks_managed_node_group && !var.enable_bootstrap_user_data && var.pre_bootstrap_user_data != "" && var.user_data_template_path == "" ? 1 : 0
> │ 
> │ The "count" value depends on resource attributes that cannot be determined
> │ until apply, so Terraform cannot predict how many instances will be
> │ created. To work around this, use the -target argument to first apply only
> │ the resources that the count depends on.
> ╵

**Comment by bryantbiggs** [comment]
Please re-visit the issue template requirements and see https://github.com/bryantbiggs/how-to-create-reproduction for additional details

Namely:
>The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

**Comment by bryantbiggs** [comment]
closing this for now since there isn't any action that we can take at this time
