### ISSUE TITLE
Add a example with assume-role in kubernetes provider

### ISSUE THREAD

**Issue by alexandreags** [terraform-aws-modules/terraform-aws-eks#2839]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
No

## Is your request related to a problem? Please describe.
No. Its more a suggestion

## Describe the solution you'd like.
In scenarios where you assume a role to deploy a EKS Cluster, only the assumed role (and/or nodes) have permission in EKS cluster.
The kubernetes provider uses eks get-token to autenticate, but uses a "before assume" credential, failing with Unauthorized error.
Maybe a update in the docs or exemple to warn about this situation

## Describe alternatives you've considered.
My dirty solution:
```
locals {
   assumerole = "${var.assumerole != "" ? "${var.assumerole}" : ""}"
}

provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    # This requires the awscli to be installed locally where Terraform is executed
    args = ["eks", "get-token", "--role-arn" ,"${local.assumerole}", "--cluster-name", module.eks.cluster_name]
    #Need improvement
  }
}
```

## Additional context
I have searched the docs and issues and not found anything related

**Comment by bryantbiggs** [comment]
this is specific to the provider and how users implement the provider - its not related to the module thats defined here

this would also apply across the various K8s related providers - kubernetes, helm, kubectl, etc.
