### ISSUE TITLE
Add cloudwatch log group tag support

### ISSUE THREAD

**Issue by BlacksmithJoe** [terraform-aws-modules/terraform-aws-eks#2840]
## Describe the solution you'd like.
Simple addition of new input to the module.
My fork for this: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2841

## Describe alternatives you've considered.
I can use plain tags input to apply tag also to the log group but it will also tag everything basically tied to cluster which is unnecessary.

## Additional context
The problem here is when I want specifically tag log group, for example to allow this log group to be exported to S3 by lambda script which need specific task to make the export happen.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 19.21.0 :tada:
