### ISSUE TITLE
Parametrise lifecycle for aws_autoscaling_schedule

### ISSUE THREAD

**Issue by hxalid** [terraform-aws-modules/terraform-aws-eks#2851]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality ( lifecycles is a built-in [Terraform meta-argument](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes))

## Is your request related to a problem? Please describe.

When we specify a recurrent `schedules` for managed node groups, it works as expected. However, as the recurrent schedule updates the start date each time to the next schedule, running Terraform apply next time sees this as a change and tries to revert the next schedule start date to the past date (which is the original start date given the first time). This obviously fails due to a validation error as follows:

```
Error: creating Auto Scaling Scheduled Action (scale-up): ValidationError: Given start time is in the past
│ 	status code: 400 ... 

modules/eks-managed-node-group/main.tf line 455, in resource "aws_autoscaling_schedule" "this":
│  455: resource "aws_autoscaling_schedule" "this"
```

Therefore, the users have to update the start_time in the Terraform file each time to bypass this issue which is not ideal.

## Describe the solution you'd like.

It may help if there is a `lifecycle` variable to pass through to the `aws_autoscaling_schedule` [resource](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v19.20.0/modules/eks-managed-node-group/main.tf#L455).

With a lifecycle variable we should be able to ignore the start_date changes as follows: 

```
lifecycle {
        ignore_changes = [start_time]
}
```
 

## Describe alternatives you've considered.

Creating the aws_autoscaling_schedule without using this terraform-aws-eks module as follows:

```
resource "aws_autoscaling_schedule" "my_schedule" {
  scheduled_action_name  = "my-schedule-name"
  min_size               = 1
  max_size               = 5
  desired_capacity       = 1
  start_time             = "2023-03-05T00:00:00Z"
  end_time               = "2024-03-05T00:00:00Z"
  time_zone              = "Etc/GMT+0"
  recurrence             = "0 0 * * *"
  autoscaling_group_name = "my-asg-name"
  lifecycle {
    ignore_changes = [start_time]
  }
}
```

## Additional context

This can be reproduced by running an example similar given in this [repo](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v19.20.0/examples/eks_managed_node_group/main.tf#L267) and wait the schedule run at least once to update the start date. Then plan and apply again. The plan phase goes ahead with no issue, but when it gets applied the error given above happens.

**Comment by bryantbiggs** [comment]
we are quite cautious and reluctant to ignore arguments because this comes with its own set of challenges -  have you researched if others are encountering this issue, what solutions or workarounds they are using, and any related issues on the AWS provider?

**Comment by hxalid** [comment]
> we are quite cautious and reluctant to ignore arguments because this comes with its own set of challenges - have you researched if others are encountering this issue, what solutions or workarounds they are using, and any related issues on the AWS provider?

Thanks for the swift response @bryantbiggs . Indeed, I did a bit of research before opening this issue.  

Seeing the `scheduled` variable is kind of new in this module, I doubt it has mass adoption yet. 

However, ignoring an argument is a Terraform [feature](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes), I linked this above as well. 

This issue is not about asking a new feature from this module per se. We are asking let's not restrict what Terraform provides in this module without a good reason. 

If I create a resource outside this module as follows, it works like a charm and as an end user I have the flexibility to control if the "start_time" needs to be ignored or not. Without this exposed in this module as a variable, the users, including myself, will have to do something like below, because it is not really usable in this module for frequent Terraform applies:

```
    resource "aws_autoscaling_schedule" "my_schedule" {
      scheduled_action_name  = "on_instance"
      min_size                            = 1
      max_size                           = 5
      desired_capacity              = 1
      start_time                          = "2023-03-05T00:00:00Z"
      end_time                            = "2024-03-05T00:00:00Z"
      time_zone                          = "Etc/GMT+0"
      recurrence                         = "0 0 * * *"
      autoscaling_group_name = "my-asg-name"
      lifecycle {
        ignore_changes = [start_time]
      }
```

There could be some other hacky work-arounds. But what we are asking here is, to not restrict what Terraform already provides. Thanks!

**Comment by bryantbiggs** [comment]
> We are asking let's not restrict what Terraform provides in this module without a good reason.

And

> If I create a resource outside this module as follows, it works like a charm and as an end user I have the flexibility to control if the "start_time" needs to be ignored or not.

I think this is the crux of the issue - you haven't grasped what you are actually asking for, which is to ignore this value for ALL users, whether they want that or not. Terraform does not support variables within lifecycle blocks so this is an all or nothing type change

**Comment by hxalid** [comment]
> Terraform does not support variables within lifecycle blocks so this is an all or nothing type change

That is unfortunately true in general, I am aware of the years old issues around this, i.e. [24188](https://github.com/hashicorp/terraform/issues/24188) and [3116](https://github.com/hashicorp/terraform/issues/3116).

However, those are the implementation details and should not limit our imaginations to abstract this feature within this module. E.g. when the `lifecycle` argument is given, this module could create "aws_autoscaling_schedule" resource with the `lifecycle` enabled, if that argument is not given, then this module could create **another** "aws_autoscaling_schedule" with not `lifecycle`set. That is not ideal - it would create two separate copies of aws_autoscaling_schedule resource. But that is probably better than introducing a non-usable feature into this module and expecting the end users will update the start_date each time as part of their daily PRs.

**Comment by hxalid** [comment]
commenting to remove the stale label.

**Comment by bryantbiggs** [comment]
this is not something that we're going to be able to support here - however, you can pass the ASG ARNs created by this module to the autoscaling schedules of your choosing with the desired configuration

**Comment by hxalid** [comment]
> this is not something that we're going to be able to support here - however, you can pass the ASG ARNs created by this module to the autoscaling schedules of your choosing with the desired configuration

Frankly, that is a surprising decision. Sure, we can always create and maintain an autoscaling schedule outside this module. This ask was more about making the autoscaling schedule added into this module usable. Unless you guys are going to disable that broken feature, I cannot wrap my head around this decision why to keep a broken feature in this module at all.
