### ISSUE TITLE
The default version of the add-on is retrieved even if an explicit version is specified

### ISSUE THREAD

**Issue by sergei-ivanov** [terraform-aws-modules/terraform-aws-eks#2855]
## Description

The EKS module uses `aws_eks_addon_version` data source to retrieve default/latest version of all add-ons, even the ones where the versions are explicitly specified through the `addon_version` map entry.

This has become an issue with the EFS CSI add-on recently, because the default version for it does not seem to exist:

```
$ aws eks describe-addon-versions --kubernetes-version 1.27 --addon-name aws-efs-csi-driver --query addons[0].addonVersions[*].compatibilities[0].defaultVersion
[
    false,
    false,
    false,
    false,
    false
]
```

As a result, even if I pass a version to the module explicitly, I have an following error on `terraform plan`.

## Versions

- Module version `19.20.0`:

- Terraform version:
```
Terraform v1.5.7
on linux_amd64
```
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v5.29.0
```

## Reproduction Code [Required]

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "19.20.0"

  create = true

  cluster_name    = "test"
  cluster_version = "1.27"

  cluster_addons = {
    aws-efs-csi-driver = {
      addon_version            = "v1.7.1-eksbuild.1"
      most_recent              = false
    }
  }
}

```

```
terraform plan
```

## Expected behavior

Data source is not instantiated for any add-ons with an explicit version.
No error on the plan.

## Actual behavior

Error on the plan.

### Terminal Output Screenshot(s)

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: reading EKS Add-On version info (aws-efs-csi-driver, 1.27): empty result
│ 
│   with module.eks.data.aws_eks_addon_version.this["aws-efs-csi-driver"],
│   on .terraform/modules/eks/main.tf line 439, in data "aws_eks_addon_version" "this":
│  439: data "aws_eks_addon_version" "this" {
│ 
╵
```

## Additional context

N/A

**Comment by sergei-ivanov** [comment]
FYI I have a patch that fixes this problem and I am working on a PR.

**Comment by bryantbiggs** [comment]
this was a hiccup in the AWS API, we  no longer need any changes here - but thank you!
