### ISSUE TITLE
aws_iam_role_policy_attachment.additional is missing an ordering constraint.

### ISSUE THREAD

**Issue by brianbraunstein** [terraform-aws-modules/terraform-aws-eks#2859]
## Description

In `terraform-aws-eks/modules/eks-managed-node-group/main.tf`, resource `aws_iam_role_policy_attachment.additional` is missing an ordering constraint that it's sibling `aws_iam_role_policy_attachment.this` has.

See this statement:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v19.21.0/modules/eks-managed-node-group/main.tf#L290

Then see that there's a sibling `resource "aws_iam_role_policy_attachment" "additional"` that doesn't get included in that `depends` statement.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v19.21.0/modules/eks-managed-node-group/main.tf#L432-L449

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v19.21.0 and also in current master branch (currently 2cb1fac31b0fc2dd6a236b0c0678df75819c5a3b)

- Terraform version: irrelevant
- Provider version(s): irrelevant

## Reproduction Code [Required]

irrelevant, see "Additional context" below.

## Expected behavior

Both `aws_iam_role_policy_attachment` resources should have the same ordering constraints.

## Actual behavior

They don't.

### Terminal Output Screenshot(s)

irrelevant

## Additional context

I noticed this only while looking through the code. I didn't directly see a problem result from this myself, so I could be wrong.  It doesn't look right to me though so I thought I should point it out so expert eyes can quickly take a look and decide if it's an issue or not.

**Comment by bryantbiggs** [comment]
I don't think this is an issue - but if you are seeing an error, please feel free to provide more details and a reproduction
