### ISSUE TITLE
Unable to define worker_groups as list of maps in json format

### ISSUE THREAD

**Issue by karthikeayan** [terraform-aws-modules/terraform-aws-eks#286]
# I have issues
When executing terraform plan against JSON formatted Terraform Configuration, getting exception as below:
`"variable worker_groups in module my-cluster-1 should be type list, got string"
`
## I'm submitting a...
* [ ] bug report
* [ ] feature request
* [x] support request
* [ ] kudos, thank you, warm fuzzy

## If this is a bug, how to reproduce? Please include a code sample if relevant.
```
  "module": {
    "my-cluster-1": {
      "cluster_name": "my-cluster-1",
      "source": "github.com/terraform-aws-modules/terraform-aws-eks",
      "subnets": [
        "${aws_subnet.worker-my-cluster-1-subnet-1.id}",
        "${aws_subnet.worker-my-cluster-1-subnet-2.id}"
      ],
      "vpc_id": "${aws_vpc.my-cluster-1.id}",
      "worker_groups": [
        [
          {
            "asg_desired_capacity": 2,
            "asg_max_size": 5,
            "instance_type": "m4.large"
          }
        ]
      ]
    }
  }
```

## What's the expected behavior?
Terraform plan should be able to parse the JSON and take this as a list of maps

## Are you able to fix this problem and submit a PR? Link here if you have already.
Not at this point of time

## Environment details

* Affected module version: 
* OS: Ubuntu 18.04.1 LTS
* Terraform version: v0.11.11

**Comment by confiq** [comment]
https://github.com/hashicorp/terraform/issues/19454
You've already asked there but this is not a limitation of module eks...

**Comment by karthikeayan** [comment]
sure, hence closing the issue.
