### ISSUE TITLE
Unable to create kubernetes config map when using the alias in kubernets provider

### ISSUE THREAD

**Issue by shettypriy** [terraform-aws-modules/terraform-aws-eks#2862]
## Versions

- Module version [Required]: 19.16.0

- Terraform version:
1.6.4
- Provider version(s):

"hashicorp/kubernetes"
      version = "2.23.0"

## Reproduction Code [Required]
provider "kubernetes" {
  alias                  = "atlantiseks"
  host                   = module.atlantis_eks_cluster.cluster_endpoint
  cluster_ca_certificate = base64decode(module.atlantis_eks_cluster.cluster_certificate_authority_data)
  token                  = data.aws_eks_cluster_auth.atlantis.token
}

 Default 
 Yes

Unable to create the kubernetes_config_map_v1_data.aws_auth[0] resource for the EKS cluster when using alias in the kubernetes provider block 

Logs : 
It just shows creating but it does not create the aws config map

module.atlantis_eks_cluster.kubernetes_config_map_v1_data.aws_auth[0]: Creating...
module.atlantis_eks_cluster.kubernetes_config_map_v1_data.aws_auth[0]: Still creating... [10s elapsed]
module.atlantis_eks_cluster.kubernetes_config_map_v1_data.aws_auth[0]: Still creating... [20s elapsed]
module.atlantis_eks_cluster.kubernetes_config_map_v1_data.aws_auth[0]: Still creating... [30s elapsed]

╷
│ Error: The configmap "aws-auth" does not exist
│ 
│   with module.atlantis_eks_cluster.kubernetes_config_map_v1_data.aws_auth[0],
│   on .terraform/modules/atlantis_eks_cluster/main.tf line 554, in resource "kubernetes_config_map_v1_data" "aws_auth":
│  554: resource "kubernetes_config_map_v1_data" "aws_auth" {

**Comment by bryantbiggs** [comment]
Please provide a reproduction

**Comment by shettypriy** [comment]
We are trying to setup a EKS cluster, using the following provider block where in we are using the **alias** in the kubernetes provider 

```
provider "kubernetes" {
alias = "atlantiseks"
host = module.atlantis_eks_cluster.cluster_endpoint
cluster_ca_certificate = base64decode(module.atlantis_eks_cluster.cluster_certificate_authority_data)
token = data.aws_eks_cluster_auth.atlantis.token
}
```
Following is the logs when apply is done

```
module.atlantis_eks_cluster.kubernetes_config_map_v1_data.aws_auth[0]: Creating...
module.atlantis_eks_cluster.kubernetes_config_map_v1_data.aws_auth[0]: Still creating... [10s elapsed]
module.atlantis_eks_cluster.kubernetes_config_map_v1_data.aws_auth[0]: Still creating... [20s elapsed]
module.atlantis_eks_cluster.kubernetes_config_map_v1_data.aws_auth[0]: Still creating... [30s elapsed]

╷
│ Error: The configmap "aws-auth" does not exist
│
│ with module.atlantis_eks_cluster.kubernetes_config_map_v1_data.aws_auth[0],
│ on .terraform/modules/atlantis_eks_cluster/main.tf line 554, in resource "kubernetes_config_map_v1_data" "aws_auth":
│ 554: resource "kubernetes_config_map_v1_data" "aws_auth" {

```

**Comment by chipshadd** [comment]
For some reason, the `aws-auth` config map does not exist in your set up.  You can have the module generate the `aws-auth` configmap by passing in `create_aws_auth_configmap = true` alongside `manage_aws_auth_configmap = true` as the latter has a dependency on the former.

**Comment by shettypriy** [comment]
Adding `create_aws_auth_configmap = true` is giving the following warning message in the aws console 

`This may be due to the current user or role not having Kubernetes RBAC permissions to describe cluster resources or not having an entry in the cluster’s auth config map`

I do not see the following getting added in the auth config because of which the above warning shows in the AWS console

```
aws_auth_roles = [
    {
      rolearn  = "arn:aws:iam::***************:role/****************************"
      username = "admin:{{SessionName}}"
      groups   = ["system:masters"]
    }
  ]
```

**Comment by shettypriy** [comment]
Thank you for the suggestion

I added `create_aws_auth_configmap = true` and applied the changes but it gave the error 

```
Error: Post "https://*****************/api/v1/namespaces/kube-system/configmaps": dial tcp 10.75.120.249:443: i/o timeout
```
 For the above erorr, I followed the fix mentioned here https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2369#issuecomment-1507831226

then commented `create_aws_auth_configmap = true`, planned and applied and was able to create the auth config succesfully

**Comment by chipshadd** [comment]
I've ran into many issues with having the module managing the `aws-auth` config maps. On initial creation everything is peachy, but running updates to it or even updates to other parts of a cluster results in intermittent issues.  I think this is due to the kubernetes provider pulling data from the module's output.  From what I understand providers cannot have dependencies on other resources and at the time of execution, terraform is unable to properly populate the config data of the kubernetes provider with the cluster data from the module.

I split out the aws_auth configmap tasks into a separate template and am manually managing it via a separate `tf apply` command.

**Comment by sz9751210** [comment]
I use the following settings and can run successfully.

```
provider "kubernetes" {
  host                   = data.terraform_remote_state.eks.outputs.cluster_endpoint
  cluster_ca_certificate = base64decode(data.terraform_remote_state.eks.outputs.cluster_certificate_authority_data)
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    args        = ["eks", "get-token", "--cluster-name", var.cluster_name]
    command     = "aws"
  }
}
```

**Comment by bryantbiggs** [comment]
I don't think this is a module issue - however, we are close to shipping v20.0 (#2858) which replaces the use of the aws-auth configmap with cluster access entries which makes this entire experience easier less problematic
