### ISSUE TITLE
Add Amazon CloudWatch log_group_class Support for Cluster Log Group

### ISSUE THREAD

**Issue by moebaca** [terraform-aws-modules/terraform-aws-eks#2866]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: Support added in [5.30.0](https://registry.terraform.io/providers/hashicorp/aws/5.30.0/docs/resources/cloudwatch_log_group)

## Is your request related to a problem? Please describe.
Amazon announced the [CloudWatch Logs Infrequent Access](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-cloudwatch-logs-infrequent-access-log-class/) log class on November 26, 2023. For the sake of cost optimization, I would like support added in the module for this cheaper log group class due to the high cost of log ingest for EKS cluster logs in STANDARD.

## Describe the solution you'd like.
I would like the ability to pass an input similar to [log_group_class](https://registry.terraform.io/providers/hashicorp/aws/5.30.0/docs/resources/cloudwatch_log_group#log_group_class) to the module - maybe something like the below example:

Name | Description | Type | Default | Required
-- | -- | -- | -- | --
cluster_enabled_log_class | Input the log class that best aligns with your use case. For more information, see Amazon CloudWatch Log classes documentation (https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatch_Logs_Log_Classes.html) | string | STANDARD | no

## Describe alternatives you've considered.
This is a pretty straightforward feature request so no alternatives are necessary.

## Additional context
- Log groups that are already created cannot be changed to a different tier without being recreated (all logs will be lost unless exported)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.0.0 :tada:
