### ISSUE TITLE
Allow modification of cluster subnets and security groups

### ISSUE THREAD

**Issue by luciano-buono** [terraform-aws-modules/terraform-aws-eks#2868]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.

  - Yes ✅: https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5250-november-10-2023. resource/aws_eks_cluster: Allow vpc_config.security_group_ids and vpc_config.subnet_ids to be updated in-place

Starting in November 2023, AWS allows to change the initial subnets and SGs in a already created EKS cluster:
- https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-eks-modification-cluster-subnets-security/
- https://aws.amazon.com/blogs/containers/enhanced-vpc-flexibility-modify-subnets-and-security-groups-in-amazon-eks/

## Is your request related to a problem? Please describe.

Until now it wasn't possible to add a new subnet to the cluster. This was a problem for clusters where you run out of available IPs addresses in a subnet.

## Describe the solution you'd like.

Right now adding a new subnet trigger a cluster recreation where it should trigger a cluster modification.

**Comment by bryantbiggs** [comment]
technically you can do this today by using the latest AWS provider FYI

**Comment by PeteMac88** [comment]
@luciano-buono Did you test it?

**Comment by luciano-buono** [comment]
Hi @PeteMac88, I just tested it. 
I used AWS 5.25 provider and EKS module v19.20.

I think that using latest module version is not neccesary, the important part is the AWS version as using an older one will result in cluster recreation.

Update is fast, 4m approx. Just make sure the desired subnet is 'elegible'. I just went into the EKS UI to simulate a manual subnet updateand checked that my subnet was listed there

**Comment by luciano-buono** [comment]
Closing as feature is already implemented

**Comment by bryantbiggs** [comment]
if the subnets that are passed to the nodegroup(s) (either self-managed or EKS managed) are changed, that will cause the group to be replaced no matter what

**Comment by PeteMac88** [comment]
@bryantbiggs Ok but in my terraform plan the `module.eks.aws_autoscaling_group.workers_launch_template` resource is updated but the `module.eks.module.node_groups.aws_eks_node_group.workers` are detroyed/recreated. I am currently using version 17.* of the eks module. Could this be the cause?
