### ISSUE TITLE
Numeric AWS profile name breaks

### ISSUE THREAD

**Issue by diversario** [terraform-aws-modules/terraform-aws-eks#287]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?
When the value of an environment variable in the AWS authentication block looks like a number module generates invalid output.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Given this block
```
  kubeconfig_aws_authenticator_env_variables = {
    AWS_PROFILE = "${var.aws_account}"
  }
```
where `var.aws_account` is a string that looks like a number `691473423738` the module produces this error:

```
Error: Error applying plan:
1 error(s) occurred:

* module.aws_eks_cluster.module.eks.null_resource.update_config_map_aws_auth: Error running command 'for i in `seq 1 10`; do \
echo "apiVersion: v1
preferences: {}
kind: Config

clusters:
- cluster:
    server: [REDACTED]
    certificate-authority-data: [REDACTED]
  name: my_cluster

contexts:
- context:
    cluster: my_cluster
    user: my_cluster
  name: my_cluster

current-context: my_cluster

users:
- name: my_cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "my_cluster"

      env:
        - name: "AWS_PROFILE"
          value: ""691473423738""

" > kube_config.yaml & \
echo "apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::691473423738:role/my_cluster-9238456897302900000
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::691473423738:role/eks_role
      username: eks_role
      groups:
        - system:masters

  mapUsers: |
    - userarn: arn:aws:iam::691473423738:user/myusername
      username: myusername
      groups:
        - system:masters

  mapAccounts: |
    - "691473423738"

" > aws_auth_configmap.yaml & \
kubectl apply -f aws_auth_configmap.yaml --kubeconfig kube_config.yaml && break || \
sleep 10; \
done; \
rm aws_auth_configmap.yaml kube_config.yaml;
': signal: interrupt. Output: error: Error loading config file "kube_config.yaml": v1.Config.AuthInfos: []v1.NamedAuthInfo: v1.NamedAuthInfo.AuthInfo: v1.AuthInfo.Exec: v1.ExecConfig.Env: []v1.ExecEnvVar: v1.ExecEnvVar.Value: ReadString: expects " or n, but found 6, error found in #10 byte of ...|,"value":69147342373|..., bigger context ...|henticator","env":[{"name":"AWS_PROFILE"
,"value":691473423738}]}}}]}|...
error: Error loading config file "kube_config.yaml": v1.Config.AuthInfos: []v1.NamedAuthInfo: v1.NamedAuthInfo.AuthInfo: v1.AuthInfo.Exec: v1.ExecConfig.Env: []v1.ExecEnvVar: v1.ExecEnvVar.Value: ReadString: expects " or n, but found 6, error found in #10 byte of ...|,"value":69147342373|..., bigger context ...|henticator","env":[{"name":"AWS_PROFILE","value":691473423738}]}}}]}|...
```

## What's the expected behavior?

The value of the env var is quoted and no error occurs.

## Are you able to fix this problem and submit a PR? Link here if you have already.

No, but the workaround is to rename the profile so that it's forced to be a string, e.g., `"aws-${var.aws_profile}".

## Environment details

* Affected module version: 2.2.1
* OS: macOS 10.14.3
* Terraform version: 0.11.11

**Comment by brandoconnor** [comment]
Hey @diversario -

Thanks for the issue submission (and the kudos). Unfortunately, I think at least the core of this issue falls outside of the scope of this module. The error generated is stemming from the `kubectl` command and its constraints around configuration and less to do with the module here. Could a better description of the `kubeconfig_aws_authenticator_env_variables` variable and its constraints help resolve the issue here? Beyond that, you might be better off bubbling this issue up to the [kubernetes/kubectl project](https://github.com/kubernetes/kubectl/issues).

I'm going to close the issue for the moment but if you have further feedback, please leave a comment and we'll figure out how to best approach the issue from within this project. Cheers!
