### ISSUE TITLE
Launch_template mime format invalid

### ISSUE THREAD

**Issue by ycam-assessfirst** [terraform-aws-modules/terraform-aws-eks#2872]
Hello
I try to used a launch template for my eks node-group, in this launch_template I set user-data with a script that worked when I create through aws GUI.
`
resource "aws_launch_template" "node_template" {
  name_prefix   = "eks-node-group"  
  key_name      = local.key_name
  user_data = filebase64("scripts/bootstrap.sh")
  vpc_security_group_ids = [
    local.node_security_group_id_alpha[0]
  ]
  tag_specifications {
    resource_type = "instance"
    tags          = local.tags
  }
  tag_specifications {
    resource_type = "volume"
    tags          = local.tags
  }
  tags = local.tags
}

module "eks-alpha" {
  source          = "terraform-aws-modules/eks/aws"
  tags            = local.tags
  version         = "19.16.0"
  create_iam_role = true
  # iam_role_arn                    = tostring(module.iam_eks_role.this[0].iam_role_arn)
  cluster_name                    = local.cluster_name_1
  cluster_version                 = local.k8s_version
  subnet_ids                      = module.vpc.public_subnets
  create_kms_key                  = true
  cluster_encryption_config       = {}
  kms_key_description             = "KMS Secrets encryption for EKS cluster."
  kms_key_enable_default_policy   = true
  cluster_endpoint_private_access = false
  cluster_endpoint_public_access  = true
  vpc_id                          = module.vpc.vpc_id
  cluster_addons = {
    coredns = {
      preserve    = true
      most_recent = true

      timeouts = {
        create = "5m"
        delete = "5m"
      }
    }
    kube-proxy = {
      most_recent = true
    }
    vpc-cni = {
      most_recent = true
    }
    aws-ebs-csi-driver = {
      most_recent = true
    }
  }

  # Extend cluster security group rules
  cluster_security_group_additional_rules = {
    egress_nodes_ephemeral_ports_tcp = {
      description      = "ALL"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
  }
  node_security_group_additional_rules = {
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    allow_cluster = {
      description                   = "Allow cluster"
      protocol                      = "-1"
      from_port                     = 0
      to_port                       = 0
      type                          = "ingress"
      source_cluster_security_group = true
    }
    allow_vpn1 = {
      description = "Allow Vpn first ip"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      cidr_blocks = ["${local.vpn1_ip}"]
    }
    allow_vpn2 = {
      description = "Allow Vpn secund ip"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      cidr_blocks = ["${local.vpn2_ip}"]
    }
    allow_vpn3 = {
      description = "Allow Vpn third ip"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      cidr_blocks = ["${local.vpn3_ip}"]
    }
    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
  }

  # EKS Managed Node Group(s)
  eks_managed_node_groups = {
    alpha-nginx = {
      name                       = "${local.alpha_nodegroup_name}-nginx"
      tags                       = local.tags
      min_size                   = local.alpha_nginx_node_group_min_size
      max_size                   = local.alpha_nginx_node_group_max_size
      desired_size               = local.alpha_nginx_node_group_desired_size
      capacity_type              = "ON_DEMAND"
      instance_type              = local.alpha_nginx_node_instance_types
      disk_size                  = local.alpha_nginx_disk_size
      create_security_group      = true
      subnet_ids                 = module.vpc.public_subnets
      enable_bootstrap_user_data = true
      use_name_prefix            = false
      create_iam_role            = false
      iam_role_arn               = aws_iam_role.node_role.arn
      taints = {
        nginx = {
          key    = "nginx"
          value  = "true"
          effect = "NO_SCHEDULE"
        }
      }
      post_bootstrap_user_data = <<-EOT
        MIME-Version: 1.0
        Content-Type: multipart/mixed; boundary=167123f181a27773ff1e0a6bdd678c878c1b88bd268ecf0896080f8edd2d

        --167123f181a27773ff1e0a6bdd678c878c1b88bd268ecf0896080f8edd2d
        Content-Type: text/x-shellscript
        Content-Type: charset="us-ascii"

        #!/bin/sh
        set -ex
        yum install -y amazon-cloudwatch-agent
        rm -rf /etc/amazon/amazon-cloudwatch-agent/amazon-cloudwatch-agent.d/default
        aws s3 cp s3://data-node-eks/cloudwatch_agent_conf/memory.json /etc/amazon/amazon-cloudwatch-agent/amazon-cloudwatch-agent.d/
        aws s3 cp s3://data-node-eks/cloudwatch_agent_conf/amazon-cloudwatch-agent.yml /etc/amazon/amazon-cloudwatch-agent/
        aws s3 cp s3://data-node-eks/cloudwatch_agent_conf/amazon-cloudwatch-agent.toml /etc/amazon/amazon-cloudwatch-agent/
        systemctl enable amazon-cloudwatch-agent
        systemctl restart amazon-cloudwatch-agent
        sed -i -E "s/^USE_MAX_PODS=\"\\$\{USE_MAX_PODS:-true}\"/USE_MAX_PODS=false/" /etc/eks/bootstrap.sh
        KUBELET_CONFIG=/etc/kubernetes/kubelet/kubelet-config.json
        echo "$(jq ".maxPods=128" $KUBELET_CONFIG)" > $KUBELET_CONFIG
        --167123f181a27773ff1e0a6bdd678c878c1b88bd268ecf0896080f8edd2d--
      EOT
    }
    alpha-redis = {
      name                       = "${local.alpha_nodegroup_name}-redis"
      ami_type                   = "AL2_x86_64"
      tags                       = local.tags
      min_size                   = 1
      max_size                   = 1
      desired_size               = 1
      capacity_type              = "ON_DEMAND"
      instance_type              = local.alpha_redis_node_instance_types
      disk_size                  = local.alpha_redis_disk_size
      create_security_group      = true
      subnet_ids                 = module.vpc.public_subnets
      enable_bootstrap_user_data = true
      use_name_prefix            = false
      create_iam_role            = false
      use_custom_launch_template = true
      iam_role_arn               = aws_iam_role.node_role.arn
      launch_template_id         = aws_launch_template.node_template.id 
      launch_template_version = "1"
      taints = {
        redis = {
          key    = "redis"
          value  = "true"
          effect = "NO_SCHEDULE"
        }
      }
    }
  }
  eks_managed_node_group_defaults = {
    disk_size      = local.alpha_disk_size
    instance_types = local.alpha_node_instance_types
  }
}
`
And my bootstrap.sh script
`
mkdir -p  /data/logs
chmod 777 /data/logs
aws s3 cp s3://data-node-eks/volumes.tar.gz /data/volumes.tar.gz
cd /data/ && tar xzf volumes.tar.gz
yum install -y amazon-cloudwatch-agent
rm -rf /etc/amazon/amazon-cloudwatch-agent/amazon-cloudwatch-agent.d/default
aws s3 cp s3://data-node-eks/cloudwatch_agent_conf/memory.json /etc/amazon/amazon-cloudwatch-agent/amazon-cloudwatch-agent.d/
aws s3 cp s3://XXXXX/XXXXX/amazon-cloudwatch-agent.yml /etc/amazon/amazon-cloudwatch-agent/
aws s3 cp s3://XXXXX/cloudwatch_agent_conf/amazon-cloudwatch-agent.toml /etc/amazon/amazon-cloudwatch-agent/
systemctl enable amazon-cloudwatch-agent
systemctl restart amazon-cloudwatch-agent
sed -i -E "s/^USE_MAX_PODS=\"\\$\{USE_MAX_PODS:-true}\"/USE_MAX_PODS=false/" /etc/eks/bootstrap.sh
KUBELET_CONFIG=/etc/kubernetes/kubelet/kubelet-config.json
echo "$(jq ".maxPods=128" $KUBELET_CONFIG)" > $KUBELET_CONFIG
`
The error message  I got when I run my terraform : 
`│ Error: waiting for EKS Node Group (af-prod-eu-west-3-alpha:af-production-alpha-redis) create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: : Ec2LaunchTemplateInvalidConfiguration: User data was not in the MIME multipart format.
│ 
│   with module.eks-alpha.module.eks_managed_node_group["alpha-redis"].aws_eks_node_group.this[0],
│   on .terraform/modules/eks-alpha/modules/eks-managed-node-group/main.tf line 308, in resource "aws_eks_node_group" "this":
│  308: resource "aws_eks_node_group" "this" {
`
Thanks for your help

**Comment by bryantbiggs** [comment]
please see our examples - you pass standard text/strings into the user data inputs, it should not be formatted in MIME multi-part format
