### ISSUE TITLE
Option to add security group in managed node groups

### ISSUE THREAD

**Issue by yuvraj9** [terraform-aws-modules/terraform-aws-eks#2877]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Describe the problem
I am trying to create a managed nodegroup for my EKS cluster but i am unable to attach custom security group to it. Only option i see is to use a custom launch template for the same. 

## Describe the solution you'd like.
I would like to see an option to do this without creating a custom launch template.

## Describe alternatives you've considered.
Alternative was to create a custom launch template

**Comment by bryantbiggs** [comment]
EKS managed nodegroups do not support this with the default launch template

**Comment by yuvraj9** [comment]
@bryantbiggs but terraform already creates a custom launch template for us right? So it should be possible to attach the extra security groups in it instead of creating a launch template from scratch which user have to manage 🤔
