### ISSUE TITLE
activation of networkpolicys for managed EKS addons

### ISSUE THREAD

**Issue by David-PIC** [terraform-aws-modules/terraform-aws-eks#2878]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v19.21.0

- Terraform version: 1.4.2

## Reproduction Code [Required]

```
cluster_addons = {
    vpc-cni = {
    version        = "v1.15.5-eksbuild.1"
    before_compute = true
    configuration_values = jsonencode({
      env = {
        ENABLE_PREFIX_DELEGATION = "true",
        AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG = "true",
        ENI_CONFIG_LABEL_DEF = "topology.kubernetes.io/zone",
        WARM_PREFIX_TARGET = "1",
      },
      VpcCni = {
        properties = {
          enableNetworkPolicy = "true",
          nodeAgent = {
            enablePolicyEventLogs = "true"
          }
        }
      }
    })
  }
 }
```

## Expected behavior

The EKS Addon VPC-CNI is being created and the enableNetworkPolicy and enablePolicyEventLogs value is set to true.

## Actual behavior

Error message:  Error: updating EKS Add-On (infrastructure-dev:vpc-cni): operation error EKS: UpdateAddon, https response error StatusCode: 400, RequestID: xxxy-xxxxy-xxxxy, InvalidParameterException: ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.vpc: is not defined in the schema and the schema does not allow additional properties]

## Additional context

I also tried it with the following input:
```
jsonencode({
      env = {
        ENABLE_PREFIX_DELEGATION = "true",
        AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG = "true",
        ENI_CONFIG_LABEL_DEF = "topology.kubernetes.io/zone",
        WARM_PREFIX_TARGET = "1",
      },
      enableNetworkPolicy = "true",
      nodeAgent = {
        enablePolicyEventLogs = "true"
      }
      })
```
```
jsonencode({
      env = {
        ENABLE_PREFIX_DELEGATION = "true",
        AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG = "true",
        ENI_CONFIG_LABEL_DEF = "topology.kubernetes.io/zone",
        WARM_PREFIX_TARGET = "1",
      },
      vpc = {
        cni = {
          properties = {
            enableNetworkPolicy = "true",
            nodeAgent = {
              enablePolicyEventLogs = "true"
            }
          }
        }
      }
    })

```

**Comment by CarlJendrik** [comment]
We have the same issue, need a fix, fast please.

**Comment by bryantbiggs** [comment]
This is not an issue with the module - you will need to follow the directions here https://docs.aws.amazon.com/eks/latest/userguide/cni-network-policy.html

**Comment by David-PIC** [comment]
I have now tested it with the following json configuration:

```
configuration_values = jsonencode({
      enableNetworkPolicy = "true"
    })
```
But I get the same error:
│ Error: updating EKS Add-On (infrastructure-dev:vpc-cni): operation error EKS: UpdateAddon, https response error StatusCode: 400, RequestID: xxxx-xxxx-xxxx-xxxx, InvalidParameterException: ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.enableNetworkPolicy: is not defined in the schema and the schema does not allow additional properties]

Does anyone have any idea what it might be?
