### ISSUE TITLE
Worker role additional policies are not getting added

### ISSUE THREAD

**Issue by ravikiran-talluri** [terraform-aws-modules/terraform-aws-eks#2879]
## Description

I was trying to add additional policies to the worker node IAM role but I was not able to. I am trying to create eks managed node group.

## Versions

- Module version [Required]: 19.20.0

- Terraform version: 1.6.1
- Provider version(s): 5.22
## Reproduction Code [Required]

`  eks_managed_node_groups = {
    example-workers = {
      create_iam_role          = true
      min_size     = 5
      max_size     = 20
      desired_size = 5
     instance_types = ["m6.xlarge"]
     iam_role_additional_policies =  {
      "policy1" = "arn:aws:iam::aws:policy/PolicyARN1",
      "policy2" = "arn:aws:iam::aws:policy/PolicyARN2",
      "policy3" = "arn:aws:iam::aws:policy/PolicyARN3",
      "policy4" = "arn:aws:iam::aws:policy/PolicyARN4",
      "policy5" = "arn:aws:iam::aws:policy/PolicyARN5"
      }
      capacity_type  = "SPOT"
    }
  }
`

## Expected behavior

All policies should get added to the IAM role created

## Actual behavior

additional policies are not getting added as specified

**Comment by bryantbiggs** [comment]
please provide a reproduction
