### ISSUE TITLE
Destroy fails when protect_from_scale_in = true

### ISSUE THREAD

**Issue by hobti01** [terraform-aws-modules/terraform-aws-eks#288]
# I have issues

## I'm submitting a...

* [x ] bug report
* [x ] kudos, thank you, warm fuzzy

## What is the current behavior?

* `autoscaling_enabled = true`, therefore `protect_from_scale_in = true`
* Make changes that cause an ASG re-creation
* Apply

```
Error: Error applying plan:
...

* module.region-us-east-1.module.eks.aws_autoscaling_group.workers[0] (destroy): 1 error(s) occurred:

* aws_autoscaling_group.workers.0 (deposed #0): 1 error(s) occurred:

* aws_autoscaling_group.workers.0 (deposed #0): group still has 3 instances
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

AWS logs indicate that there is an attempt to scale the ASG to zero before deleting - but this cannot be done because `protect_from_scale_in = true`.

Terraform is wedged until timeout.

## What's the expected behavior?

ASG and instances are removed.

## Are you able to fix this problem and submit a PR? Link here if you have already.

I can manually remove the ASG and instances, but it would be great if this case was handled.  Sorry but not knowledgable enough about the module to submit a PR.

## Environment details

* Affected module version: 2.2.0
* Terraform version: 0.11.13

## Any other relevant info

Many thanks for the module and the frequent updates!

**Comment by max-rocket-internet** [comment]
Thanks for the Kudos 💜

Please see https://github.com/terraform-aws-modules/terraform-aws-eks/issues/176

In short: You can't have `protect_from_scale_in` enabled and still be able to destroy the cluster with terraform.

**Comment by stefansedich** [comment]
@max-rocket-internet we can now use `asg_force_delete` on the worker group and for my cases anyway it has been destroying without issue even with `protect_from_scale_in`.
