### ISSUE TITLE
vpc-cni driver aws-node service account not being annotated with IRSA role arn

### ISSUE THREAD

**Issue by samispurs** [terraform-aws-modules/terraform-aws-eks#2880]
## Description

Using v19.19.0 or higher, when trying to deploy a new cluster with eks version 1.28, we noticed that the aws-node service account used with the vpc-cni driver does not update the annotation to be able to use the IRSA role arn.  This prevents the managed nodes from joining the cluster as the vpc-cni pods do not have the correct permissions.

"Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"

Unauthorized operation: failed to call ec2:DescribeNetworkInterfaces due to missing permissions.

With the same code we are able to deploy either eks versions 1.26 or 1.27 with out issues.  As a workaround we had to create a null_resource and local-exec that executes the command kubectl annotate serviceaccount -n kube-system aws-node eks.amazonaws.com/role-arn= right after the cluster is created. The vpc-cni driver then uses the correct irsa role with the correct permissions to enable the nodes to join the cluster.

If we specify a addon version, it seems that v1.15.1-eksbuild.1 is used regardless of the version specified on initial cluster creation. Only when the TF code executes for managing the addon does the version get applied.

I'm not able to determine what is responsible for annotating the aws-node service account.  This was automagically happening for eks cluster 1.26/1.27.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
source  = "terraform-aws-modules/eks/aws"
  version = "19.19.0"

Terraform v1.6.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.31.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.3
+ provider registry.terraform.io/hashicorp/helm v2.12.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.25.2
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/time v0.10.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5

 No
 Yes
 terraform plan/apply

## Expected behavior
The cluster should annotate the aws-node service account with the arn of the irsa role for the vpc-cni.

## Actual behavior

Annotation field is blank.

**Comment by bryantbiggs** [comment]
you should open a support ticket with AWS - this module doesn't have any control over the EKS addon annotations
