### ISSUE TITLE
Error handling aws_auth_users

### ISSUE THREAD

**Issue by GuilleAmutio** [terraform-aws-modules/terraform-aws-eks#2884]
## Description

When setting the `aws_auth_users` variable to the value defined on the example, it throws an error noting that the groups attribute should be a string instead of a list of strings, as the example shows.

## Versions

- Module version [Required]:

- Terraform version:
Terraform v1.6.6
on linux_amd64
- Provider version(s):
+ provider registry.terraform.io/fluxcd/flux v1.2.1
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.22.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.3
+ provider registry.terraform.io/hashicorp/helm v2.12.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.24.0
+ provider registry.terraform.io/hashicorp/time v0.9.2
+ provider registry.terraform.io/hashicorp/tls v4.0.5

## Expected behavior

I should be able to define a list of maps, setting multiple users with N number of groups attached to each.

## Actual behavior

If we use the list of maps as the Terraform Registry example shows:
```
  aws_auth_users = [
    {
      userarn  = "arn:aws:iam::66666666666:user/user1"
      username = "user1"
      groups   = ["system:masters"]
    },
    {
      userarn  = "arn:aws:iam::66666666666:user/user2"
      username = "user2"
      groups   = ["system:masters"]
    },
  ]
```
And we run `terraform apply, it will prompt: 
```
│ Error: Invalid value for input variable
│ 
│   on terraform.tfvars line 14:
│   14: eks_iam_roles_users= [
│   15:   {
│   16:     userarn  = "arn:aws:iam::66666666666:user/user1"
│   17:     username = "user1"
│   18:     groups   = ["system:masters"]
│   19:   },
│   20:   {
│   21:     userarn  = "arn:aws:iam::66666666666:user/user2"
│   22:     username = "user1"
│   23:     groups   = ["system:masters"]
│   24:   },
│   25: ]
│ 
│ The given value is not suitable for var.eks_iam_roles_users declared at variables.tf:66,1-31: element 0: element "groups": string required.
```

If we set the groups to a string instead of a list of strings, then the YAML will be malformed

### Terminal Output Screenshot(s)

![image](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/56632305/d2e5a37c-25dd-4e67-80fd-3e61fb269efc)

**Comment by bryantbiggs** [comment]
>  on terraform.tfvars line 14:
│   14: eks_iam_roles_users= [
│   15:   {
│   16:     userarn  = "arn:aws:iam::66666666666:user/user1"
│   17:     username = "user1"
│   18:     groups   = ["system:masters"]
│   19:   },
│   20:   {
│   21:     userarn  = "arn:aws:iam::66666666666:user/user2"
│   22:     username = "user1"
│   23:     groups   = ["system:masters"]
│   24:   },
│   25: ]

This isn't the code we provide here - this looks like you are wrapping the module and the variable type for your `eks_iam_roles_users` is incorrect

**Comment by bryantbiggs** [comment]
closing with guidance above - in v20.x (#2858) we are removing the configmap and relegating it to a sub-module till we remove it entirely in a later release. Cluster access entries would be the preferred path forward
