### ISSUE TITLE
feature request - a bastion instance for worker nodes debugging

### ISSUE THREAD

**Issue by brant4test** [terraform-aws-modules/terraform-aws-eks#289]
## I'm submitting a...

* [x] feature request

## What is the current behavior?

Terraform-aws-eks v2.2.1 has both EKS cluster and worker instances placed within private_subnets, which is great! 
But without any public IPs for worker instances, how could an admin log into instances for debugging?

## What's the expected behavior?

How about setup a bastion instance in one of the public subsets?

## Environment details

* Affected module version: v2.2.1
* OS: Ubuntu 16.04.3 LTS
* Terraform version: Terraform v0.11.11

## Any other relevant info

Thanks!

**Comment by max-rocket-internet** [comment]
Hi @brant4test 

This won't be added to this module as it's not related to EKS but more a general AWS problem. Fortunately there are a couple of great solutions!

Here's one from me:
https://github.com/deliveryhero/tf-ssh-bastion

And here's one from @antonbabenko:
https://github.com/terraform-community-modules/tf_aws_bastion_s3_keys

Enjoy 💙
