### ISSUE TITLE
Ability to set both custom disk_size and security groups

### ISSUE THREAD

**Issue by jpambrun-vida** [terraform-aws-modules/terraform-aws-eks#2891]
## Is your request related to a problem? Please describe.
I was trying to set disk_size as I am running tensorflow and I am always running out of space since the docker image is so large. I notice it had no effects and found the numerous related github issues and [FAQ entry](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a68aac6cf29011e95405207d409d03360d3af56d/docs/faq.md?plain=1#L12). 

However, the way I read it, I can either have custom security groups or custom disk size? This mutual exclusion is odd and very limiting. I did try and it does make the cluster inaccessible.

## Describe the solution you'd like.
I would like to be able to set both custom security groups and custom disk size. 

## Describe alternatives you've considered.
I am at a loss for ideas.

**Comment by bryantbiggs** [comment]
This is down to the EKS API https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#setting-disk_size-or-remote_access-does-not-make-any-changes

I would recommend you stay on the custom launch group route that this module defaults to use - it makes it pretty much transparent to users. You just need to specify your disk requirements in a different way to achieve the same outcome:

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a68aac6cf29011e95405207d409d03360d3af56d/examples/eks_managed_node_group/main.tf#L204-L216
