### ISSUE TITLE
Cannot resize my managed node group using terraform

### ISSUE THREAD

**Issue by AlmirKadric** [terraform-aws-modules/terraform-aws-eks#2894]
## Description

Currently the desired_size value for managed node groups is within the ignore_changes block, causing any upscaling of the group to fail.

- [✅ ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 19.21.0

- Terraform version:
Terraform v1.7.2
on darwin_amd64
- Provider version(s):
provider registry.terraform.io/hashicorp/aws v5.34.0
provider registry.terraform.io/hashicorp/cloudinit v2.3.3
provider registry.terraform.io/hashicorp/kubernetes v2.25.2
provider registry.terraform.io/hashicorp/null v3.2.2
provider registry.terraform.io/hashicorp/time v0.10.0
provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]

if i have an initial node group consisting of a single node, but then wish to scale up to 2 nodes I would change
```
min_size = 1->2
max_size = 1->2
desired_size = 1->2
```

However doing so will result in the below change and error:
```
# module.eks.module.eks_managed_node_group["default"].aws_eks_node_group.this[0] will be updated in-place
  ~ resource "aws_eks_node_group" "this" {
        id                     = "default:default-20240203121826050900000008"
        tags                   = {
            "Name" = "default-default"
        }
        # (16 unchanged attributes hidden)

      ~ scaling_config {
          ~ max_size     = 1 -> 2
          ~ min_size     = 1 -> 2
            # (1 unchanged attribute hidden)
        }

        # (3 unchanged blocks hidden)
    }

module.eks.module.eks_managed_node_group["default"].aws_eks_node_group.this[0]: Modifying... [id=default:default-default-20240203121826050900000008]
╷
│ Error: updating EKS Node Group (default:default_spot-20240203121826050900000008) config: operation error EKS: UpdateNodegroupConfig, https response error StatusCode: 400, RequestID: c1d8001f-3325-48ea-bb8e-28c0fd477c78, InvalidParameterException: Minimum capacity 2 can't be greater than desired size 1
│
│   with module.eks.module.eks_managed_node_group["default"].aws_eks_node_group.this[0],
│   on .terraform/modules/eks/modules/eks-managed-node-group/main.tf line 308, in resource "aws_eks_node_group" "this":
│  308: resource "aws_eks_node_group" "this" {
```

see above

## Expected behavior

The node group should scale up successfully

## Actual behavior

A terraform error occurs

### Terminal Output Screenshot(s)

Error is above

## Additional context

NA

**Comment by bryantbiggs** [comment]
This is documented in our FAQ

https://github.com/bryantbiggs/eks-desired-size-hack

**Comment by AlmirKadric** [comment]
thanks for the information
