### ISSUE TITLE
[Karpenter] Allow pod-identities statement to be disabled

### ISSUE THREAD

**Issue by tculp** [terraform-aws-modules/terraform-aws-eks#2901]
## Is your request related to a problem? Please describe.
EKS pod-identities are not available in all regions. Thus the newest version of the Karpenter sub-module does not work in such regions when trying to create an IAM role:

```
Error: creating IAM Role (KarpenterController-20240205212716330000000002): MalformedPolicyDocument: Invalid principal in policy: "SERVICE":"pods.eks.amazonaws.com"
```

If the pod-identity statement was able to be disabled, this would not be an issue and the toggleable IRSA statement would be used instead.

## Describe the solution you'd like.
An enable_pod_identities variable (defaults to true)

## Describe alternatives you've considered.
Continuing to use the previous module version, without the nice new updated Karpenter policy, access entries, etc.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.2.0 :tada:
