### ISSUE TITLE
EKS Managed Node Group Destroyed Before Workloads are Migrated

### ISSUE THREAD

**Issue by hjeffries94** [terraform-aws-modules/terraform-aws-eks#2905]
## Description

Last weekend, I ran in a change in our production environment which resulted in significant downtime. In a nutshell, a new node group was spun up, and as soon as that finished in TF, the old node group was destroyed, rather than workloads be migrated first. The expectation here is that the module would have waited for the workloads on the old nodes to be migrated across to the new, before the termination signal was sent to all the instances in the old node group.

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 19.21.0

- Terraform version: 1.5.7
- Provider version(s): N/A

Running a terraform apply to replace the old node group with a new node group. This is specifically when changing instance type:
```
module.eks-cluster.module.eks_managed_node_group["ondemand"].aws_eks_node_group.this[0] must be replaced
+/- resource "aws_eks_node_group" "this" {
      ~ arn                    = "arn:aws:eks:eu-west-1:446122446960:nodegroup/prod1/prod1-ondemand-20231029093419615600000018/e8c5bd64-6220-9161-b8a5-4faaeb8c8f35" -> (known after apply)
      ~ disk_size              = 0 -> (known after apply)
      ~ id                     = "prod1:prod1-ondemand-20231029093419615600000018" -> (known after apply)
      ~ instance_types         = [ # forces replacement
          - "m5.4xlarge",
          + "r6i.4xlarge",
        ]
      - labels                 = {} -> null
      ~ node_group_name        = "prod1-ondemand-20231029093419615600000018" -> (known after apply)
      ~ release_version        = "1.25.15-20231116" -> (known after apply)
      ~ resources              = [
          - {
              - autoscaling_groups              = [
                  - {
                      - name = "eks-prod1-ondemand-20231029093419615600000018-e8c5bd64-6220-9161-b8a5-4faaeb8c8f35"
                    },
                ]
              - remote_access_security_group_id = ""
            },
        ] -> (known after apply)
      ~ status                 = "ACTIVE" -> (known after apply)
        tags                   = {
            "Cluster"      = "prod1"
            "EnvType"      = "prod"
            "Environment"  = "prod1"
            "Name"         = "prod1-ondemand"
            "Terraform"    = "eks"
            "cluster_name" = "prod1"
        }
        # (9 unchanged attributes hidden)

      ~ launch_template {
            id      = "lt-0f7037b741d28833d"
          ~ name    = "ondemand-20231029093419335800000014" -> (known after apply)
          ~ version = "2" -> (known after apply)
        }

      ~ scaling_config {
          ~ desired_size = 50 -> 44
            # (2 unchanged attributes hidden)
        }

      ~ update_config {
          - max_unavailable            = 0 -> null
          ~ max_unavailable_percentage = 80 -> 33
        }
```

## Expected behavior

- New node group to spin up
- Migration of workloads from old node group to new
- Termination of old node group and instances

## Actual behavior

- New node group spun up
- Once the new node group is created, the nodes within the old node group start terminating
- Workloads are moved over forcefully, resulting in downtime (all replicas moved simultaneously)
- Old node group terminated once all instance within were terminated

### Terminal Output

```
module.eks-cluster.module.eks_managed_node_group["ondemand"].aws_eks_node_group.this[0]: Creation complete after 1m38s [id=prod1:prod1-ondemand-20240203102001123600000004]
module.eks-cluster.module.eks_managed_node_group["ondemand"].aws_eks_node_group.this[0] (deposed object 485349b2): Destroying... [id=prod1:prod1-ondemand-20231029093419615600000018]
module.eks-cluster.module.eks_managed_node_group["spotless"].aws_eks_node_group.this[0]: Still destroying... [id=prod1:prod1-spotless-20231029093419615400000016, 20s elapsed]
module.eks-cluster.module.eks_managed_node_group["ondemand"].aws_eks_node_group.this[0]: Still destroying... [id=prod1:prod1-ondemand-20231029093419615600000018, 10s elapsed]
```

Note how the module begins destroying the old node group as soon as the new one has been provisioned.

## Additional context

Ignore spotless, that's an unused node group, it's the ondemand node group that's the issue.

Please let me know if you require any further detail.

**Comment by bryantbiggs** [comment]
> The expectation here is that the module would have waited for the workloads on the old nodes to be migrated across to the new, before the termination signal was sent to all the instances in the old node group.

This is not behavior the module controls, there isn't anything that we can do here for this
