### ISSUE TITLE
[Karpenter] TF apply fails with eks module v20 when enable_spot_termination=false and create_iam_role=true

### ISSUE THREAD

**Issue by nikoshet** [terraform-aws-modules/terraform-aws-eks#2906]
## Description

Currently, while migrating on the latest v20.2.0 EKS TF Module version, when using:
`enable_spot_termination=false`  and `create_iam_role=true` in order to create the Karpenter controller role, I get the following error, since aws_sqs_queue resource is created if enable_spot_termination is true:
```
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/karpenter/modules/karpenter/main.tf line 257, in data "aws_iam_policy_document" "controller":
│  257:     resources = [aws_sqs_queue.this[0].arn]
│     ├────────────────
│     │ aws_sqs_queue.this is empty tuple
│ 
│ The given key does not identify an element in this collection value: the
│ collection has no elements.
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
20.2.0
- Terraform version:
v1.7.2
- Provider version(s):
aws v5.35.0

## Reproduction Code [Required]

- Use the above versions and configuration for the Karpenter role
- Run terraform apply

## Expected behavior

The Karpenter controller role should be created while allowing to have enable_spot_termination false.

## Actual behavior

I get the above error and can't execute `terraform apply`

## Terminal Output Screenshot(s)

<img width="412" alt="Screenshot 2024-02-06 at 6 53 52 PM" src="https://github.com/terraform-aws-modules/terraform-aws-eks/assets/20300694/eff2a078-7ccc-4c44-aee8-966dd6f9b987">

**Comment by bryantbiggs** [comment]
we could do something to alleviate this, but is there any reason why you don't want the instance termination handling? It says spot but its really more than that - any EC2 instance health events or AZ rebalancing, etc.

**Comment by nikoshet** [comment]
> we could do something to alleviate this, but is there any reason why you don't want the instance termination handling? It says spot but its really more than that - any EC2 instance health events or AZ rebalancing, etc.

I am already using AWS node termination handler so I think that it's not needed in my case.

**Comment by bryantbiggs** [comment]
But why - Karpenter handles all of this natively for you, why the need for lord when you can accomplish the same with less

**Comment by pavlospt** [comment]
@bryantbiggs hello 👋 Nick’s colleague here. By natively you mean through SQS? Either way though I don’t think the module should be breaking when someone disables the spot termination feature, so I guess we can rethink how we handle the spot termination and let Karpenter handle it and also merge the PR to fix the issue :) What do you think?

**Comment by bryantbiggs** [comment]
> I don’t think the module should be breaking when someone disables the spot termination feature

I agree so we will use the PR attached to fix this. However, I strongly recommend using the instance termination handling capabilities that Karpenter provides over node termination handler - these are two different systems that were designed separately and there are gaps when trying to use the two in combination. If it made sense to use node termination handler, the Karpenter team would have said to simply use node termination handler
