### ISSUE TITLE
terraform failing to create aws_iam_role_policy_attachment during planning 

### ISSUE THREAD

**Issue by pdeva** [terraform-aws-modules/terraform-aws-eks#2908]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 20.2.0

- Terraform version: 1.7.2

- Provider version(s):
aws 5.35.0

## Reproduction Code [Required]

```tf
module "eks_managed_node_group" {
  depends_on = [module.eks_cluster_k1]
  for_each   = toset([module.vpc.private_subnet_ids[0]])
  source     = "terraform-aws-modules/eks/aws//modules/eks-managed-node-group"
  version = "~> 20.2.0"

  name            = "ng-core"
  cluster_name    = local.cluster_name
  cluster_version = local.cluster_version

  cluster_primary_security_group_id = module.eks_cluster_k1.cluster_primary_security_group_id

  vpc_security_group_ids = [aws_security_group.allow_us_east_1.id, module.vpc.default_security_group_id]

  min_size     = 1
  max_size     = 1
  desired_size = 1

  instance_types = ["m7g.large"]
  capacity_type  = "ON_DEMAND"
  ami_type       = "BOTTLEROCKET_ARM_64"
  subnet_ids     = [each.value]
}

```

## Expected behavior
Should work without issues

## Actual behavior

Seeing errors during planning phase

### Terminal Output Screenshot(s)
![Screenshot 2024-02-06 at 9 16 13 AM](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/3190176/b7fc6e54-3525-453d-8d5a-3c23e1f3539b)

**Comment by bryantbiggs** [comment]
you are doing two things that are really bad, one of which won't work when creating resources for the first time

```hcl
module "eks_managed_node_group" {
  # See - https://github.com/hashicorp/terraform/issues/26383#issuecomment-699149145
  # Do not use `depends_on` like this, it already implicitly is dependent on the cluster due to the information it requires from the control plane
  depends_on = [module.eks_cluster_k1]
  # See - https://github.com/hashicorp/terraform/issues/30937
  # You should use static keys when iterating over objects with `for_each`
  for_each   = toset([module.vpc.private_subnet_ids[0]])
}
```

For now, there isn't any module changes related to this error - you will need to modify how you are using the module to remediate the errors

**Comment by pdeva** [comment]
thank you. i didnt know about these 2 pitfalls. especially the one about depends_on still confuses me heh.
