### ISSUE TITLE
worker_groups_launch_template failed to update asg_desired_capacity number

### ISSUE THREAD

**Issue by brant4test** [terraform-aws-modules/terraform-aws-eks#291]
# I have issues

## I'm submitting a...

* [x] bug report

## What is the current behavior?
I updated asg_desired_capacity from 2 to 4, and asg_max_size from 4 to 5, eventually only asg_max_size got updated into Spot ASG, the number of asg_desired_capacity stays the same 2

```
$ vi terraform-aws-modules\terraform-aws-eks\examples\eks_test_fixture\main.tf
...
  worker_groups_launch_template = [
    {
      # This will launch an autoscaling group with only Spot Fleet instances
      name                                     = "workers_group_launch_template_spot"
      instance_type                            = "m4.large"
      override_instance_type                   = "t2.large"
      asg_desired_capacity                     = "4"
      asg_max_size                             = "5"
      asg_min_size                             = "1"
...
```
$ terraform plan
```
  ~ update in-place
Terraform will perform the following actions:
  ~ module.eks.aws_autoscaling_group.workers_launch_template
      max_size: "4" => "5"
Plan: 0 to add, 1 to change, 0 to destroy.
```

$ terraform apply
```
module.eks.aws_autoscaling_group.workers_launch_template: Modifying... (ID: test-eks-AbEd-workers_group_launch_template_spot20190222043445948300000014)
  max_size: "4" => "5"
module.eks.aws_autoscaling_group.workers_launch_template: Modifications complete after 0s (ID: test-eks-AbEd-workers_group_launch_template_spot20190222043445948300000014)
```
## What's the expected behavior?

Should've implemented asg_desired_capacity 4, and asg_max_size 5 in AWS.
Any tips?

## Environment details

* Affected module version: v2.2.1
* OS: Ubuntu 16.04.3 LTS
* Terraform version: Terraform v0.11.11

## Any other relevant info

Thanks!

**Comment by brant4test** [comment]
@confiq Anything I missed?

**Comment by RothAndrew** [comment]
Working as intended. Desired capacity isn't changed after initial creation because it would conflict with runtime autoscalers like cluster-autoscaler.

**Comment by confiq** [comment]
> @confiq Anything I missed?

I would not call this a bug. It might be it's not documented well but not a bug...

**Comment by brant4test** [comment]
Thank you! Not yet installed cluster-autoscaler, will do soon.

**Comment by stefansedich** [comment]
@brant4test I ended up appending the capacity to the name so that a change in desired capacity could force a re-create. This in combination with `asg_force_delete` on the worker group I can force a group to 0 which will remove the nodes, has proved useful for my blue/green worker groups so that I can force a group to spin down after I have drained and moved pods from one group to another and ensure that the group is no longer visible to the autoscaler.

```
"name", "foo-${var.desired_capacity}",
```

**Comment by woqer** [comment]
So there is no way to resize using Terraform? I understand the issues for autoscaler, but it should be optional to ignore or not `desired_capacity`.

We are trying to have some blue/green setup which implies having alwas 2 ASGs running, one with zero size and the other with the desired size and everytime we need to update the AMI we just move things to the other ASG, which needs resize on both groups.

**Comment by max-rocket-internet** [comment]
> So there is no way to resize using Terraform?

Correct.

Currently it's not possible to support both ways as lifecycle rules in Terraform don't support interpolation. Therefore we support the most common and correct method, which is to use the cluster-autoscaler.

Also worth noting that scaling down the ASG is usually a manual process anyway. To do this safely you need to drain the node and then terminate it. If you are scaling the cluster down solely via changing the ASG min/max/desired, then the ASG will just terminate some instance without draining, which in many situations is not desirable. But I understand in your usecase it might be OK.

Hope that makes sense!
