### ISSUE TITLE
module.eks.aws_eks_access_entry.this["cluster_creator"] must be replaced when running from another user

### ISSUE THREAD

**Issue by aaadipop** [terraform-aws-modules/terraform-aws-eks#2911]
## Description

After upgrading from v19 to v20 when I try to run terraform apply from another user the plan wants to change the `aws_eks_access_entry.this["cluster_creator"]` resource with the role/iam user which runs the command

- [ x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

Terraform v1.6.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.35.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.3
+ provider registry.terraform.io/hashicorp/helm v2.12.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.25.2
+ provider registry.terraform.io/hashicorp/local v2.4.1
+ provider registry.terraform.io/hashicorp/random v3.6.0
+ provider registry.terraform.io/hashicorp/time v0.10.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]

```
module "eks" {
  source                          = "terraform-aws-modules/eks/aws"
  # version                         = "19.18.0"
  version                         = "20.0.1"

  cluster_name                    = local.cluster_name
  cluster_version                 = local.cluster_version

  vpc_id                          = var.vpc_id
  subnet_ids                      = var.vpc_subnets

  cluster_endpoint_public_access  = true

  kms_key_administrators          = ["arn:aws:iam::12345:user/cluster_creator", var.github_iam_role]

  # Cluster access entry
  authentication_mode = "API_AND_CONFIG_MAP"
  enable_cluster_creator_admin_permissions = true

  access_entries = {
    github_role = {
      kubernetes_groups = []
      principal_arn     = var.github_iam_role

      policy_associations = {
        admin = {
          policy_arn = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"
          access_scope = {
            type = "cluster"
          }
        }
      }
    }
  }

  cluster_addons = {
    coredns = {
      most_recent = true
    }
    kube-proxy = {
      most_recent = true
    }
    vpc-cni = {
      most_recent = true
    }
    # used by elastic
    aws-ebs-csi-driver = {
      most_recent = true
    }
  }

  eks_managed_node_group_defaults = {
    instance_types  = ["t4g.2xlarge"] 
    ami_id          = data.aws_ami.ami_arm.image_id

    autoscaling_group_tags = merge({
      "k8s.io/cluster-autoscaler/enabled" : true,
      "k8s.io/cluster-autoscaler/${local.cluster_name}" : "owned"
    }, var.tags)

    iam_role_additional_policies = {
      AmazonEBSCSIDriverPolicy            = "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
      AmazonEKSVPCCNIRole                 = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
    }

    iam_role_attach_cni_policy = true
  }

  eks_managed_node_groups = {
    default = {
      name            = "default"
      min_size        = 3
      max_size        = 6
      desired_size    = 3

      instance_types  = ["t3.2xlarge"]
      ami_id          = data.aws_ami.ami_x86.image_id

      disk_size       = 100

      use_custom_launch_template = false
      remote_access = {
        ec2_ssh_key   = var.ssh_key_id
      }

      update_config = {
        max_unavailable_percentage = 33 # or set `max_unavailable`
      }
    }

  }
```

apply the plan from two different users or roles

GitHubActions

yep, everythime a fresh runner

terraform plan && terraform apply

## Expected behavior

I expect to keep the real cluster creator ( the user who actually create the cluster ) and further updates to be made from any other user ( ex. pipeline_job or another IAM user ) without changing the `aws_eks_access_entry.this["cluster_creator"]` resource

## Actual behavior

The plan wanna replace the following resource:

```
# module.eks.module.eks.aws_eks_access_entry.this["cluster_creator"] must be replaced
-/+ resource "aws_eks_access_entry" "this" {
      ~ access_entry_arn  = "arn:aws:eks:eu-west-1:***:access-entry/infra/user/***/cluester_creator/d8c6bc42-..." -> (known after apply)
      ~ created_at        = "2024-02-05T09:06:50Z" -> (known after apply)
      ~ id                = "infra:arn:aws:iam::***:user/cluester_creator" -> (known after apply)
      ~ kubernetes_groups = [] -> (known after apply)
      ~ modified_at       = "2024-02-05T09:06:50Z" -> (known after apply)
      ~ principal_arn     = "arn:aws:iam::***:user/cluester_creator" -> "arn:aws:iam::***:role/pipeline_job" # forces replacement
        tags              = {
            "Application" = "infra"
            "CreatedBy"   = "terraform"
            "Environment" = "prod"
        }
      ~ user_name         = "arn:aws:iam::***:user/cluester_creator" -> (known after apply)
        # (3 unchanged attributes hidden)
    }
```

## Additional context

I create the cluster with version 19 then I upgrade to v20 applying all changes from my pc. When I trigger the terraform apply in GitHub Actions pipeline, the plan wants to change the `aws_eks_access_entry.this["cluster_creator"]` resource from my IAM user arn with the GitHubActions Role arn

**Comment by bryantbiggs** [comment]
when you enable cluster access entry on your cluster, EKS will automatically add access entries for any roles used by EKS managed nodegroups, EKS Fargate profiles, as well as the role that was used to create the cluster - this role was previously not visible to users when using the `aws-auth` configmap. So you can't set `enable_cluster_creator_admin_permissions = true` if there is already an access entry with the same role

**Comment by aaadipop** [comment]
`So you can't set enable_cluster_creator_admin_permissions = true if there is already an access entry with the same role` , yes, you're right, at the first `terraform apply` after version change I got an error related to this

I manually detete that entry from `aws console -> eks -> access` between `terraform apply` and `yes` ( when you type `yes` to approve changes ) and terraform create the access entry for my user 

everything works as expected if I run it from the same user, but the problem is when I run `terraform apply` from another user ( or from another Role )

as described above, the following code will trigger a recreate for `# module.eks.aws_eks_access_entry.this["cluster_creator"] must be replaced` if is triggered from another user than the one who `apply` the plan first time

the code:
```
module "eks" {
  source                          = "terraform-aws-modules/eks/aws"
  # version                         = "19.18.0"
  version                         = "20.0.1"

  cluster_name                    = local.cluster_name
  cluster_version                 = local.cluster_version

  vpc_id                          = var.vpc_id
  subnet_ids                      = var.vpc_subnets

  cluster_endpoint_public_access  = true

  kms_key_administrators          = ["arn:aws:iam::12345:user/cluster_creator", var.github_iam_role]

  # Cluster access entry
  authentication_mode = "API_AND_CONFIG_MAP"
  enable_cluster_creator_admin_permissions = true

  access_entries = {
    github_role = {
      kubernetes_groups = []
      principal_arn     = var.github_iam_role

      policy_associations = {
        admin = {
          policy_arn = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"
          access_scope = {
            type = "cluster"
          }
        }
      }
    }
  }

  cluster_addons = {
    coredns = {
      most_recent = true
    }
    kube-proxy = {
      most_recent = true
    }
    vpc-cni = {
      most_recent = true
    }
    # used by elastic
    aws-ebs-csi-driver = {
      most_recent = true
    }
  }

  eks_managed_node_group_defaults = {
    instance_types  = ["t4g.2xlarge"] 
    ami_id          = data.aws_ami.ami_arm.image_id

    autoscaling_group_tags = merge({
      "k8s.io/cluster-autoscaler/enabled" : true,
      "k8s.io/cluster-autoscaler/${local.cluster_name}" : "owned"
    }, var.tags)

    iam_role_additional_policies = {
      AmazonEBSCSIDriverPolicy            = "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
      AmazonEKSVPCCNIRole                 = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
    }

    iam_role_attach_cni_policy = true
  }

  eks_managed_node_groups = {
    default = {
      name            = "default"
      min_size        = 3
      max_size        = 6
      desired_size    = 3

      instance_types  = ["t3.2xlarge"]
      ami_id          = data.aws_ami.ami_x86.image_id

      disk_size       = 100

      use_custom_launch_template = false
      remote_access = {
        ec2_ssh_key   = var.ssh_key_id
      }

      update_config = {
        max_unavailable_percentage = 33 # or set `max_unavailable`
      }
    }

  }
```

steps to reproduce:
1. run the above code with `terraform apply` to create a cluster ( fill with your variables / subnets first )
2. check current caller identity ( `aws sts get-caller-identity` )
3. assume an IAM Role ( `eval $(aws sts assume-role --role-arn "add:your:role:arn:here/GitHubActions" --role-session-name AWSCLI-Session | jq -r '.Credentials | "export AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey)\nexport AWS_SESSION_TOKEN=\(.SessionToken)\n"')` )
4. check if role was assumed ( `aws sts get-caller-identity` )
5. run `terraform apply` and check if `module.eks.aws_eks_access_entry.this["cluster_creator"]` will be replaced or not

thanks,

**Comment by bryantbiggs** [comment]
correct - that is expected. the entity that is executing the Terraform commands is the entity that is added via access entry. so if there are multiple entities executing Terraform commands against the same module definition, thats going to keep showing up in your diffs. I would suggest either using one entity for the Terraform commands, or you will need to map in the roles yourself via the `access_entries` variable

**Comment by aaadipop** [comment]
yep, worked with 

```
enable_cluster_creator_admin_permissions = false

access_entries = {
    all_users_here
}
```

thanks 

super fast response :)
