### ISSUE TITLE
Pods running in two different node groups cannot see each other

### ISSUE THREAD

**Issue by jsuto** [terraform-aws-modules/terraform-aws-eks#2914]
## Description

I have a testpod in nodegroup1, and there's an nginx pod running in nodegroup2. How to achieve that testpod could reach the nginx pod using curl?

## Versions

20.2.0

## Reproduction Code [Required]

The code in this repo's examples/eks_managed_node_group directory

## Expected behavior

With some extra config testpod should access the other pod running on a different nodegroup.

Probably it's possible to do with the current release of the module, however I couldn't figure out.

**Comment by FernandoMiguel** [comment]
are they using the same Security Group?

**Comment by jsuto** [comment]
You are right, they weren't. I tweaked the nodegroups to use the same sg, and now it works.
