### ISSUE TITLE
Can't create outposts cluster.

### ISSUE THREAD

**Issue by ripa79** [terraform-aws-modules/terraform-aws-eks#2925]
## Description

Can't create outposts cluster. This is due https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v20.2.1/main.tf#L43 cannot be changed. Error message is like:
Error: creating EKS Cluster (<cluster name>): operation error EKS: CreateCluster, https response error StatusCode: 400, RequestID: xxx, InvalidParameterException: Local Amazon EKS cluster only supports bootstrapClusterCreatorAdminPermissions=true and authenticationMode=CONFIG_MAP for AccessConfig.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by ripa79** [comment]
i managed to create the outposts local eks cluster with these changes:
https://github.com/ripa79/terraform-aws-eks/commit/ebb166ab4b27bc873879f375672752c674bfe13a

**Comment by ValKiriann** [comment]
Please, post an update to this issue

**Comment by ripa79** [comment]
i have the fix in place in my own repo https://github.com/ripa79/terraform-aws-eks/commit/ebb166ab4b27bc873879f375672752c674bfe13a i need to check what is needed in order to put pull reques to this repo...

**Comment by ripa79** [comment]
Due to https://github.com/hashicorp/terraform/issues/24188 we cannot dynamically set lifecycle and outpost cluster requires this:
https://github.com/ripa79/terraform-aws-eks/blob/changes_needed_for_outposts/main.tf#L30-L32
basically I'm stuck fixing this properly.
