### ISSUE TITLE
error running tf plan for karpenter submodule

### ISSUE THREAD

**Issue by pdeva** [terraform-aws-modules/terraform-aws-eks#2927]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version: 1.7.3

- Provider version(s): 20.2.1

## Reproduction Code [Required]

```
module "karpenter" {
  source               = "terraform-aws-modules/eks/aws//modules/karpenter"
  cluster_name         = var.cluster_name
  create_node_iam_role = false
  node_iam_role_arn    = module.cluster_roles.worker_node_role_arn
  create_access_entry  = false
}
```

## Expected behavior
should work. like i am literally setting `create_node_iam_role=false` to avoid that entire block...

## Actual behavior
Getting this error

![Screenshot 2024-02-14 at 10 04 57 PM](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/3190176/3a770b63-7a50-4aa8-a25a-1d1d6376ffc9)

**Comment by bryantbiggs** [comment]
I am unable to produce, this creates without issue:

```hcl
module "karpenter" {
  source               = "terraform-aws-modules/eks/aws//modules/karpenter"
  
  cluster_name         = "something"
  create_node_iam_role = false
  node_iam_role_arn    = "arn:aws:iam::111111111111:role/something"
  create_access_entry  = false
}
```
