### ISSUE TITLE
Enable the snapshot functionality of the Amazon EBS CSI driver

### ISSUE THREAD

**Issue by MauroSoli** [terraform-aws-modules/terraform-aws-eks#2928]
## Is your request related to a problem? Please describe.
To enable the [external-snapshot](https://github.com/kubernetes-csi/external-snapshotter?tab=readme-ov-file) feature, [officially supported by EBS CSI driver](https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html) is necessary that the following resources are deployed before the EBS CSI driver addon:

- [CustomResourceDefinition](https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd) (CRD) for volumesnapshotclasses, volumesnapshots, and volume snapshot contents;
- [RBAC](https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml) (ClusterRole, ClusterRoleBinding, and so on);
- [controller deployment](https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml);

## Describe the solution you'd like.
It would be great to enable a feature flag to install the above dependencies before the EBS CSI driver deployment.

## Describe alternatives you've considered.
Alternatively, it may be enough to run some custom Kubernetes manifests before the addons deployment.

**Comment by bryantbiggs** [comment]
this module is not intended to go inside the cluster (i.e. - use the Kubernetes provider), and instead this functionality should be provided by the EKS addon. 

instead, you can raise an issue on https://github.com/aws-ia/terraform-aws-eks-blueprints-addons to see if it can be supported there
