### ISSUE TITLE
"Invalid Instance type" when adding new c7g.large worker group.

### ISSUE THREAD

**Issue by Jod9** [terraform-aws-modules/terraform-aws-eks#2929]
## Description

We currently use c6g.large EC2 instances in our EKS cluster and are attempting to add a new c7g.large worker group. When attempting to apply the plan after adding the new worker group, we receive the following error: 
```
 Error: Error creating launch configuration: ValidationError: The specified instance type c7g.large is not valid
 	status code: 400, request id: 2a1a9ff9-5ce6-4a75-880a-ada016f2eb78
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 17.24.0

- Terraform version: 1.3.6
- Provider version(s): 3.76.1

## Reproduction Code [Required]

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "17.24.0"
  cluster_name    = "Staging"
  cluster_version = "1.25"
  subnets         = Redacted

  vpc_id = Redacted

  write_kubeconfig = false

  worker_groups = [{
    name          = "worker-group-arm64"
    instance_type = "c6g.large"
    ami_id        = "ami-0f736a8279bce10fc"
    asg_max_size  = 10
    asg_min_size  = 1
    root_volume_type      = "gp3"
    protect_from_scale_in = true
    tags = [
      {
        "key"                 = "k8s.io/cluster-autoscaler/enabled"
        "propagate_at_launch" = "false"
        "value"               = "true"
      },
      {
        "key"                 = "k8s.io/cluster-autoscaler/staging"
        "propagate_at_launch" = "false"
        "value"               = "true"
      }
    ]
    }, {
    name          = "worker-group-amd64-2"
    instance_type = "t3.medium"
    ami_id        = "ami-0ad2b47f0f8992f6a"
    asg_max_size  = 10
    asg_min_size  = 1
    root_volume_type      = "gp3"
    protect_from_scale_in = true
    tags = [
      {
        "key"                 = "k8s.io/cluster-autoscaler/enabled"
        "propagate_at_launch" = "false"
        "value"               = "true"
      },
      {
        "key"                 = "k8s.io/cluster-autoscaler/staging"
        "propagate_at_launch" = "false"
        "value"               = "true"
      }
    ]
    }, {
    name          = "staging-worker-group-arm64-graviton3"
    instance_type = "c7g.large"
    ami_id        = "ami-044095a8d8d61398a"
    asg_max_size  = 10
    asg_min_size  = 1
    root_volume_type      = "gp3"
    protect_from_scale_in = true
    tags = [
      {
        "key"                 = "k8s.io/cluster-autoscaler/enabled"
        "propagate_at_launch" = "false"
        "value"               = "true"
      },
      {
        "key"                 = "k8s.io/cluster-autoscaler/staging"
        "propagate_at_launch" = "false"
        "value"               = "true"
      }
    ]
  }]
}

```

- Add new worker group using c7g instance type

## Expected behavior

Expected plan to apply & new worker group to be created with c7g instance type.

## Actual behavior

Apply failure with invalid instance type error

### Terminal Output Screenshot(s)

![Screenshot 2024-02-15 at 10 38 58](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/109076088/0bc6f937-75cb-49d1-bbf2-5c91375c16a2)

## Additional context

We are doing this in eu-west-2 so the instance type is available to us.

**Comment by bryantbiggs** [comment]
this module does not pose any limitations on instance types used - however, you are using a quite old version of the module so I don't know if that version had any restrictions. either way, I don't think there is anything we can do here since we do not backport changes to prior version. you could look at forking a copy at v17 and making any changes, but I would suggest updating to the latest instead
