### ISSUE TITLE
What do I have to take into account for my cluster to be created on an existing vpc?

### ISSUE THREAD

**Issue by jmbravo** [terraform-aws-modules/terraform-aws-eks#2930]
I see that there's a specific vpc module:

`module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = local.name
  cidr = local.vpc_cidr

  azs             = local.azs
  private_subnets = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 4, k)]
  public_subnets  = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 8, k + 48)]
  intra_subnets   = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 8, k + 52)]

  enable_nat_gateway = true
  single_nat_gateway = true

  public_subnet_tags = {
    "kubernetes.io/role/elb" = 1
  }

  private_subnet_tags = {
    "kubernetes.io/role/internal-elb" = 1
    # Tags subnets for Karpenter auto-discovery
    "karpenter.sh/discovery" = local.name
  }

  tags = local.tags
}
`

But imagine I already have a VPC with cidr 10.77.248.0/21 with id vpc-xxxxxxxxxxxxx

How do I deal with this?

Please, tag this as question

Thank you

**Comment by FernandoMiguel** [comment]
i dont understand your question @jmbravo 
you pick what cidrs to use

**Comment by jmbravo** [comment]
I have an existing VPC, and I want EKS to use the existing one.

**Comment by jmbravo** [comment]
> what's your `local.vpc_cidr` ?

  The default one vpc_cidr = "172.16.0.0/16", but my idea is to use the cidr of my existing vpc (10.77.248.0/21) as well as its subnets.

**Comment by FernandoMiguel** [comment]
So use the one you want.
I'm failing to grasp what is not working for you.

**Comment by jmbravo** [comment]
> So use the one you want. I'm failing to grasp what is not working for you.

Sorry for the vague explanation.

I know I can put the cidr I want in there, what I want to know is if I need to make further changes to the vpc module to make it use my existing vpc and its subnets correctly.

That vpc is already in use and I don't want to screw anything up.

**Comment by FernandoMiguel** [comment]
The eks module has nothing to do with the vpc module.
They are independent runs/states

**Comment by jmbravo** [comment]
> The eks module has nothing to do with the vpc module. They are independent runs/states

Oh, I didn't see it pointed to a different module 🤦‍♂️, so I only have to take into account the following ones in the eks module, and delete/comment the vpc module part:

vpc_cidr = "172.16.0.0.0/16"
vpc_id = vpc-xxxxxxxxxxx
subnet_ids = [subnet-ixxxxxxx, subnet-ixxxxxxx].
control_plane_subnet_ids = [subnet-ixxxxxxx, subnet-ixxxxxxx]

**Comment by FernandoMiguel** [comment]
That's a terrible cidr to use

**Comment by jmbravo** [comment]
> That's a terrible cidr to use

It was the example lol mine is 10.77.248.0/21

**Comment by FernandoMiguel** [comment]
plan for extended carrier grade NAT subnets for your pods.
your private subnets will fill up quite quickly

**Comment by jmbravo** [comment]
> plan for extended carrier grade NAT subnets for your pods.
> 
> your private subnets will fill up quite quickly 

This cluster won't have more than 150 pods, so only with one of the subnets I'll be fine, so it has like 230 IPs free to use.

**Comment by FernandoMiguel** [comment]
the hosts ENIs use IPs.
auxiliar services use IPs (dns, kubeproxy, ebs, etc)
