### ISSUE TITLE
 Need clarity on combined IAM role for VPC CNI and CloudWatch for NetworkPolicy logging

### ISSUE THREAD

**Issue by avgKol** [terraform-aws-modules/terraform-aws-eks#2934]
Hello! I'm looking to configure Kubernetes NetworkPolicy logging within my EKS cluster, utilizing the Amazon VPC CNI plugin and sending logs to CloudWatch. Here's my current approach based on examples:

**Cluster Addons**

```terraform
cluster_addons = {
  vpc-cni = {
   most_recent       = true
   before_compute      = true
   service_account_role_arn = module.vpc_cni_irsa.iam_role_arn
   configuration_values = jsonencode({
    enableNetworkPolicy = "true",
    nodeAgent = {
     enableCloudWatchLogs = "true"
   }
  })
 }
}
```

**IAM Role Module**

```terraform
module "vpc_cni_irsa" {
  source = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 5.0"

  role_name_prefix   = "VPC-CNI-IRSA"
  attach_vpc_cni_policy = true
  vpc_cni_enable_ipv4  = true

  oidc_providers = {
   main = {
    provider_arn        = module.eks.oidc_provider_arn
    namespace_service_accounts = ["kube-system:aws-node"]
  }
 }

  tags = var.tags
}
```

**The Issue**

The VPC CNI policy ([https://github.com/terraform-aws-modules/terraform-aws-iam/blob/f37809108f86d8fbdf17f735df734bf4abe69315/modules/iam-role-for-service-accounts-eks/policies.tf#L1381](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/f37809108f86d8fbdf17f735df734bf4abe69315/modules/iam-role-for-service-accounts-eks/policies.tf#L1381)) seems to be missing necessary permissions for CloudWatch logging as outlined in the AWS docs ([https://docs.aws.amazon.com/eks/latest/userguide/cni-network-policy.html#network-policies-troubleshooting](https://docs.aws.amazon.com/eks/latest/userguide/cni-network-policy.html#network-policies-troubleshooting)):

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "VisualEditor0",
      "Effect": "Allow",
      "Action": [
        "logs:DescribeLogGroups",
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents"
      ],
      "Resource": "*"
    }
  ]
}
```

**Questions**

1. **Existing Submodule?**  Is there an existing Terraform module within this repository that combines the VPC CNI and CloudWatch permissions into a single IAM role suitable for assumption by EKS ServiceAccounts? 

2. **Best Approach?** If not, could you suggest the preferred method for achieving this? Would it involve:
    * Modifying the existing `iam-role-for-service-accounts-eks` module?
    * Creating a separate module specifically for NetworkPolicy logging?

Thanks for your assistance in creating a streamlined setup for network policy logging!

**Comment by bryantbiggs** [comment]
> Modifying the existing iam-role-for-service-accounts-eks module?

Yes, we should add this under a flag since the addon now supports this. Please also open an issue or PR on the successor to the IRSA sub-module here as well https://github.com/clowdhaus/terraform-aws-eks-pod-identity (still a work in progress that I need to wrap up soon)

**Comment by bryantbiggs** [comment]
actually, thinking about this a bit more so that it follows with how we handle CloudWatch logs in general. We should figure out the best path to support creating the CloudWathc log group in Terraform - this is what IaC users typically want so you can tag it, control the log expiration, etc. This is another one of those areas where I'm a bit fuzzy on whether that should be defined in the cluster module here, or the module that creates the role. 

Do you know what the name of the log group is thats created when you enable this (and how that relates to the cluster name)?
