### ISSUE TITLE
Can not create an access_entry without a policy_association

### ISSUE THREAD

**Issue by andrewhharmon** [terraform-aws-modules/terraform-aws-eks#2947]
## Description

I'mm trying to create an access entry that uses only K8s groups and I do not want to associate an access policy. The module seems to fail to pickup access entries unless they have a policy_associations section that is not empty

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by bryantbiggs** [comment]
we won't be able to help without a reproduction

**Comment by bryantbiggs** [comment]
closing for now - please feel free to provide a reproduction for us to help triage and troubleshoot
