### ISSUE TITLE
Support AL2023

### ISSUE THREAD

**Issue by tropnikovvl** [terraform-aws-modules/terraform-aws-eks#2948]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
AL2023 has already been launched in test mode, how can it be adapted to this module? Considering the changed approach to bootstrap instances. https://github.com/awslabs/amazon-eks-ami/issues/1672

## Describe the solution you'd like.
Transition from AL2 to AL2023 for all types of instances

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.5.0 :tada:
