### ISSUE TITLE
desired_size should not ignore_changes

### ISSUE THREAD

**Issue by islishude** [terraform-aws-modules/terraform-aws-eks#2961]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0be0a99b1a323f6df0888703456c2505ce4ec494/modules/eks-managed-node-group/main.tf#L453-L458

I don't think we can update instance count due to this

is there a reason for that?

**Comment by bryantbiggs** [comment]
yes, because it conflicts with things like cluster autoscaler which are used for scaling the node groups
