### ISSUE TITLE
Consider adding more default tags to autoscaled node groups?

### ISSUE THREAD

**Issue by tbarrella** [terraform-aws-modules/terraform-aws-eks#297]
## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Cluster Autoscaler node groups are tagged with "k8s.io/cluster-autoscaler/enabled" (which is helpful) 

## What's the expected behavior?
It would be helpful if they were also tagged with "k8s.io/cluster-autoscaler/{cluster_name}" as [recommended](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#auto-discovery-setup) in case you have multiple clusters

It would also be helpful if they were automatically tagged with "k8s.io/cluster-autoscaler/node-template/resource/ephemeral-storage": "{root_volume_size}Gi" to support autoscaling from 0 (see https://github.com/kubernetes/autoscaler/issues/1650)

## Are you able to fix this problem and submit a PR? Link here if you have already.
Seems I may be able if people are ok with these being added by default

**Comment by brandoconnor** [comment]
Hola @tbarrella ! 👋 

I appreciate the issue you're raising and the links to the docs. I'm onboard with what you're pitching so feel free to start in on the PR at your convenience.

**Comment by tbarrella** [comment]
Hello, ok cool! Am trying now

**Comment by max-rocket-internet** [comment]
PR merged. Thanks again 💙
