### ISSUE TITLE
Encounter an error  when upgrade v20.8.3  form v20.8.2

### ISSUE THREAD

**Issue by shencan** [terraform-aws-modules/terraform-aws-eks#2971]
## Description

v20.8.3 version add validate_cluster_service_cidr, if I upgrade v20.8.3  form v20.8.2 and not change any terraform code, will Encounter an error.  I think it needs to be compatible with the previous version

## Versions

- Module version [Required]:  v20.8.3

- Terraform version:   v1.5.5
- Provider version(s):  5.40.0
  

## Reproduction Code [Required]

```
 error running Plan: rpc error: code = Internal desc = exit status 1

        Error: Resource precondition failed

          on .terraform/modules/eks-nodegroup/modules/_user_data/main.tf line 10, in resource "null_resource" "validate_cluster_service_cidr":
          10:       condition     = var.create ? length(local.cluster_service_cidr) > 6 : true
            ├────────────────
            │ local.cluster_service_cidr is ""
            │ var.create is true

        `cluster_service_cidr` is required when `create = true`
```

**Comment by clevandowski** [comment]
Got same problem

**Comment by bryantbiggs** [comment]
this is an error that is now apparent - where before it was silent. please see https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2970#issuecomment-1991998303 for more details. 

I'll leave this issue open in case others come here with the same question but this is expected and you should adjust your nodegroup accordingly to ensure the appropriate value for service CIDR is passed correctly

**Comment by rbadenhorst-accenture** [comment]
Same problem for me. To resolve the issue I tried to get the cluster_service_cidr output from the eks module but it's non-existent. Any ideas on how to resolve that?

**Comment by bryantbiggs** [comment]
You can see how its used here in the example https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1627231af669796669ce83e0a4672a7e6d94a0b3/examples/eks_managed_node_group/main.tf#L363

To be clear, this is only present when not using the integrated node group creation. When using integrated node groups, the module will ensure this value is passed down from the control plane to nodes correctly. If you break out into isolated node group definitions, this value needs to be passed through as shown in the example just above

**Comment by rbadenhorst-accenture** [comment]
Thanks, I saw that but it doesn't work. I've put my node groups in a sub folder so when I try that, I get this error.

```
Error: Reference to undeclared module
│
│   on alt-gpu-node-groups/eks-alt-gpu-node-groups.tf line 6, in module "alt_gpu_node_groups":
│    6:   cluster_service_cidr              = module.eks.cluster_service_cidr
```

So I tried to pass it in a variable from the root, but it still complains that module.eks.cluster_service_cidr doesn't have such an attribute. 

I then output the entire eks.module object as an output to see if cluster_service_cidr is in it, but it's not. See attached.
[outputs.txt](https://github.com/terraform-aws-modules/terraform-aws-eks/files/14593112/outputs.txt)

FYI, the output resource is

output "cluster_service_cidr" {
  value = module.eks
}

Oh and I've using a for_each to create the node groups, don't know if that is an issue.

**Comment by bryantbiggs** [comment]
I mean, I've showed you my code 😅 which works - its a bit challenging to offer any guidance on what you might be doing without seeing a reproduction

**Comment by osuka** [comment]
For people like us that extended some prior code base where we had the clusters already created with the bundled [aws eks cluster resource ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster) directly, we find it doesn't have that [output](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1627231af669796669ce83e0a4672a7e6d94a0b3/outputs.tf#L55) so there is no easy fix to pass it. Had to dig into the aws eks module you are using to see what that parameter is meant to contain.

```tf
output "cluster_service_cidr" {
  description = "The CIDR block where Kubernetes pod and service IP addresses are assigned from"
  value       = try(aws_eks_cluster.this[0].kubernetes_network_config[0].service_ipv4_cidr, aws_eks_cluster.this[0].kubernetes_network_config[0].service_ipv6_cidr, null)
}
```

For anyone seeing this bug, the `cluster_service_cidr` parameter can be obtained from your aws_eks_cluster doing that. In the case of this issue it seems @shencan is using a custom eks module that also doesn't have that output, so they can either add it to the custom module or simply use an expression like the above `try` directly

**Comment by bryantbiggs** [comment]
I am curious to learn more about these setups. For example:
1. What is the motivation for creating detached nodegroups
2. What customizations are you performing where changes here that are meant to be mostly internal are impacting you, but yet you can't use the route thats described by this module (i.e. - from @osuka's description above, it sounds like you have a custom control plane implementation, but use the different nodegroup modules defined in this project - is that correct?)

**Comment by rknightion** [comment]
For 1. we have two ways of building clusters - a legacy approach (made with raw HCL and the AWS provider) and a new way built upon this very terraform module. 
As part of modernising the legacy model we've made use of some of the submodules for quite some time (such as Karpenter but also the managed node group one). That's how we've got control planes not created by the module but worker node groups and other parts that are. 

Naturally that comes with its own set of (manageable) risks and incompatibilities that usually result in a custom data block or custom output to provide the values needed. Osuka's approach above solved this for us and aside from running completely different terraform deployments for worker node groups vs control plane I'm not sure why Osuka's approach wouldn't work for someone.

**Comment by osuka** [comment]
Thanks @bryantbiggs, we may be not using the module as intended but for us this module was a way to generate nodegroups in a nicer way than with the aws resources directly.

We ended up with exactly the same setup as @rknightion above so it may not be that uncommon. The legacy aws_eks_cluster cluster that can't be recreated without disruption. When needing new nodegroups we used the module and linked it to that one, in what we assumed was a valid use case scenario.

The real bug that this version introduced is that it suddenly made necessary to pass this parameter that is defined as optional. 

```
variable "cluster_service_cidr" {
  description = "The CIDR block (IPv4 or IPv6) used by the cluster to assign Kubernetes service IP addresses. This is derived from the cluster itself"
  type        = string
  default     = ""
}
```

Moving forward we are removing all these nodegroups in any case, and moving to karpenter as most teams so don't lose too much sleep over our use case :).

**Comment by rbadenhorst-accenture** [comment]
FYI the cluster_service_cidr output not being present in the EKS object was resolved by forcing the upgrade of the eks module. I could then pass it into the other module and the error is no longer appearing.

Thanks!

**Comment by NeckBeardPrince** [comment]
I upgraded to `v20.8.3` as well. When running apply I get this. I'm not sure what will be replaced.


```
Terraform will perform the following actions:

  # module.eks.time_sleep.this[0] must be replaced
+/- resource "time_sleep" "this" {
      ~ id              = "2024-03-05T20:00:35Z" -> (known after apply)
      ~ triggers        = { # forces replacement
          + "cluster_service_cidr"               = "10.100.0.0/16"
            # (4 unchanged elements hidden)
        }
        # (1 unchanged attribute hidden)
    }

  # module.eks.module.eks_managed_node_group["development-primary"].module.user_data.null_resource.validate_cluster_service_cidr will be created
  + resource "null_resource" "validate_cluster_service_cidr" {
      + id = (known after apply)
    }

  # module.eks.module.eks_managed_node_group["development-spot"].module.user_data.null_resource.validate_cluster_service_cidr will be created
  + resource "null_resource" "validate_cluster_service_cidr" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 1 to destroy.
```

**Comment by bryantbiggs** [comment]
nothing material based on the plan diff - we're just enforcing that the cluster service CIDR is passed from the control plane down to the nodes correctly. The `time_sleep` resource is just  used as a pass through to be able to wait some time, and the `null_resource` there is just so we can have a precondition check to enforce this at a somewhat awkward spot https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1627231af669796669ce83e0a4672a7e6d94a0b3/modules/_user_data/main.tf#L1-L14
