### ISSUE TITLE
Not able to pass lable to node

### ISSUE THREAD

**Issue by 223311** [terraform-aws-modules/terraform-aws-eks#2976]
Hello team,

I'm currently attempting to create a node with an additional node label. Previously, we used to pass this using `kubelet_extra_args= --node-labels=app=test` to the module, and the label would be added to the node. However, I'm unable to locate the same configuration for version 19.19.1 onward. Has there been any change to this variable?

Could you please assist in identifying where we pass this information now?

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1627231af669796669ce83e0a4672a7e6d94a0b3/examples/eks_managed_node_group/main.tf#L215

**Comment by 223311** [comment]
Thanks @bryantbiggs
