### ISSUE TITLE
cloudinit_pre_nodeadm not being passed to _user_data module

### ISSUE THREAD

**Issue by KingLeak95** [terraform-aws-modules/terraform-aws-eks#2980]
## Description

I believe by these [lines](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1627231af669796669ce83e0a4672a7e6d94a0b3/node_groups.tf#L330-L341) that the variable is is not being passed for eks_managed_groups 

If your request is for a new feature, please use the `Feature request` template.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 20.8.3

- Terraform version:
1.7
- Provider version(s):
AWS 5.43

## Reproduction Code [Required]

```
ami-tests = {
      platform = "al2023"

      min_size     = 1
      max_size     = 3
      desired_size = 1
      ami_id       = data.aws_ami.al2023_ami.id


      cloudinit_pre_nodeadm = [
        {
          content_type = "text/x-shellscript; charset=\"us-ascii\""
          content      = <<-EOT
            #!/bin/bash
            #!/bin/bash
        TOKEN=$(curl --request PUT "http://169.254.169.254/latest/api/token" --header "X-aws-ec2-metadata-token-ttl-seconds: 10")
ZONE=$(curl http://169.254.169.254/latest/meta-data/placement/region --header "X-aws-ec2-metadata-token: $TOKEN")
IP_BASED_NAME=$(curl http://169.254.169.254/latest/meta-data/hostname --header "X-aws-ec2-metadata-token: $TOKEN" | cut -f1 -d".")
hostnamectl set-hostname --static $IP_BASED_NAME.$ZONE.compute.internal
      EOT
        },
        {
          content_type = "application/node.eks.aws"
          content      = <<-EOT
            ---
            apiVersion: node.eks.aws/v1alpha
            kind: NodeConfig
            spec:
              kubelet:
                config:
                  shutdownGracePeriod: 30s
                  featureGates:
                    DisableKubeletCloudCredentialProviders: true

          EOT
        }
      ]
    }
```

Attempt to pass cloudinit_pre_nodeadm

## Expected behavior

`cloudinit_pre_nodeadm` is prepended to user_data

## Actual behavior

``cloudinit_pre_nodeadm` is ignored and only the templated data is send

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.8.4 :tada:
