### ISSUE TITLE
api error ExpiredTokenException: The security token included in the request is expired

### ISSUE THREAD

**Issue by marcossantosscott** [terraform-aws-modules/terraform-aws-eks#2991]
## Description

Hello Everyone, I'm using this module to create eks managed node group.  I managed to create the managed node group without problems using the AL2 type ami.

however, when creating the node using this ami it does not have imdsv2 enabled by default and also creates the instance with the gp2 disk.

I changed my code, and created a launchtemplate and put it to be used to create nodes, so it worked properly.

After researching, I saw that al2023 type amis already create the instance with metadata enabled and gp3 disk.

I changed the code and using the data resource, to obtain the most recent ami of type al2023, then creating the nodegroup it keeps creating for a long time until it gives the error "api error ExpiredTokenException: The security token included in the request is expired".

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:
Terraform v1.7.5
- Provider version(s):
 provider registry.terraform.io/hashicorp/aws v5.42.0
 provider registry.terraform.io/hashicorp/cloudinit v2.3.3
 provider registry.terraform.io/hashicorp/null v3.2.2

## Reproduction Code [Required]

`module "eks_managed_node_group" {
  source = "terraform-aws-modules/eks/aws//modules/eks-managed-node-group"

  name                 = "eks-nodegroup-gerenciado-v2"
  cluster_name         = var.cluster_name
  cluster_version      = "1.28"                 
  cluster_service_cidr = var.cluster_service_cidr
  create_iam_role      = var.create_iam_role
  iam_role_arn         = var.iam_role_arn
  ami_id = data.aws_ami.eks_node_ami.id
  #ami_release_version = var.ami_release_version
  #use_latest_ami_release_version = var.use_latest_ami_release_version
  #ami_type                       = var.ami_type
  subnet_ids                     = ["subnet-03310f951190ad409", "subnet-03340f19043fccf3c", "subnet-04363f9581e2efb04"]
  min_size         = 2
  max_size         = 3
  desired_size     = 2
  instance_types = ["t3.medium"]
  
  tags = {
    Environment = "hml"
    Terraform   = "true"
  }
}
`
`data "aws_ami" "eks_node_ami" {
  filter {
    name   = "name"
    values = ["*"] # Use "*" para buscar todas as AMI  # Expressão regular para filtrar o nome da AMI
  }
  name_regex  = "^amazon-eks-node-al2023-x86_64-standard-1.29-.*"
  most_recent = true
  owners      = ["602401143452"] # Owner ID da AWS para AMIs do Amazon EKS
}

output "ami-eks" {
  value = data.aws_ami.eks_node_ami.id
}`

`variable "create" {
  description = "Determines whether to create EKS managed node group or not"
  type        = bool
  default     = true
}

variable "cluster_service_cidr" {
  description = "The CIDR block (IPv4 or IPv6) used by the cluster to assign Kubernetes service IP addresses. This is derived from the cluster itself"
  type        = string
  default     = "172.20.0.0/16"

}

variable "cluster_name" {
  description = "Name of associated EKS cluster"
  type        = string
  default     = "eks-cluster"
}

variable "iam_role_use_name_prefix" {
  description = "Determines whether the IAM role name (`iam_role_name`) is used as a prefix"
  type        = bool
  default     = false
}

variable "create_iam_role" {
  description = "Determines whether an IAM role is created or to use an existing IAM role"
  type        = bool
  default     = false
}

variable "iam_role_arn" {
  description = "Existing IAM role ARN for the node group. Required if `create_iam_role` is set to `false`"
  type        = string
  default     = "arn:aws:iam::265003643050:role/AmazonEKSNodeRole"
}

variable "create_launch_template" {
  description = "Determines whether to create a launch template or not. If set to `false`, EKS will use its own default launch template"
  type        = bool
  default     = false
}

variable "use_custom_launch_template" {
  description = "Determines whether to use a custom launch template or not. If set to `false`, EKS will use its own default launch template"
  type        = bool
  default     = false
}'

I basically run terraform plan and apply, it runs for about 10 minutes and then gives the error

## Expected behavior

Create the node group and add nodes to the cluster

## Actual behavior

the nodegroup is created, but nodes are not added.
In terminal as received this error " Error: waiting for EKS Node Group (eks-cluster:eks-nodegroup-gerenciado-v2-20240327131813192900000001) create: operation error EKS: DescribeNodegroup, https response error StatusCode: 403, RequestID: bd92e1a8-7359-4995-9d22-7a0c071a3e94, api error ExpiredTokenException: The security token included in the request is expired"

### Terminal Output Screenshot(s)

![image](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/96556983/79a0d6bd-dad8-429b-8313-afcd05f3d971)

**Comment by bryantbiggs** [comment]
looks like your AWS credentials expired in the middle of applying - this is outside the module's control
