### ISSUE TITLE
Best Practice to perform Module Upgrades

### ISSUE THREAD

**Issue by devops-inthe-east** [terraform-aws-modules/terraform-aws-eks#2995]
Hey All,

Need to clarify few things

1. Can I skip module versions when upgrading a specific modules.
2. Like moving from 17.0.0 to 20.0.0

**Comment by bryantbiggs** [comment]
Maybe - its not something we have tried or documented

**Comment by devops-inthe-east** [comment]
ok, 

I do understand that every team has it own way to perform the upgrades.
However is it safe to assume that upgrading one major version at a time is ideal. 

As my env uses 17.0.0 modules, i.e pretty stable thanks the community's collective efforts. 
However, since Launch Configuration are Deprecated and being replaced with Launch Templates. 

Which is not included in this module 17.0.0. I prefer to upgrade the module to 18.0.0. 
However there are some breaking change.
So I considered to skip this module and preferred the latest one.

**Comment by 170031284** [comment]
Absolutely you can skip the version but it is always good to practice systematic approach. While changing from version 17.0.0 to version 20.0.0, Terraform will use it directly if you mention in the configuration. , it is always important to keep trace of changes in each version to avaoid compatibility issues .
