### ISSUE TITLE
EKS patch version update

### ISSUE THREAD

**Issue by cdenneen** [terraform-aws-modules/terraform-aws-eks#2999]
I've noticed that when you specify a version of cluster_version = 1.28 it had come up with 1.28.6 but other clusters came up with 1.28.7.
I've done terraform updates on the 1.28.6 cluster and it's not trying to upgrade to the latest patched version. Is this by design?
Is there a way to perform these upgrades with the module?

**Comment by bryantbiggs** [comment]
This is controlled by EKS https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html

When platform versions are being rolled out, you may see this discrepancy until all of your clusters have been updated to the latest platform version

**Comment by bryantbiggs** [comment]
closing since this is up to the EKS service and not something controlled through the API currently
