### ISSUE TITLE
Propagate aws provider default tags to cluster_primary_security_group resource

### ISSUE THREAD

**Issue by stevo-f3** [terraform-aws-modules/terraform-aws-eks#3002]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

Have all resources created by a module have aws provider default tags for cost attribution, monitoring/alerting etc.

## Describe the solution you'd like.

Add `data "aws_default_tags" "current" {}` and merge the tags in https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L111

## Describe alternatives you've considered.

- configuring cluster_tags var - unwanted side-effect is recurring changes (tags vs tags_all) in plans for other resources which already get default tags from aws provider
- forking EKS module and making custom change

**Comment by bryantbiggs** [comment]
we had that and removed it. if you want to add tags to the security group created by EKS, you can use the `cluster_tags` variable. 

Also, security groups do not cost money nor show up in  monitoring/alerting
