### ISSUE TITLE
access entry "cluster_creator" is destroyed before the cluster components are destroyed

### ISSUE THREAD

**Issue by rohits2290** [terraform-aws-modules/terraform-aws-eks#3005]
## Description

access entry "cluster_creator" is destroyed before the cluster components are destroyed. This results in Terraform not able to destroy other in-cluster components such as karpenter, etc...
## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

Terraform
- Module version [Required]: 20.8.5

- Terraform version:
Terraform v1.7.5
on darwin_arm64

- Provider version(s):
+ provider registry.terraform.io/alekc/kubectl v2.0.4
+ provider registry.terraform.io/hashicorp/aws v5.44.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.3
+ provider registry.terraform.io/hashicorp/helm v2.13.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.27.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/time v0.11.1
+ provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 20.8"

  cluster_name                   = local.name
  cluster_version                = "1.28"
  cluster_endpoint_public_access = true
  cluster_endpoint_public_access_cidrs = ["<my_ip>"]

  vpc_id     = data.aws_vpc.vpc.id
  subnet_ids = data.aws_subnets.private.ids

  enable_cluster_creator_admin_permissions = true

  create_cluster_security_group = false
  create_node_security_group    = false

  cluster_addons = {
    coredns = {
      configuration_values = jsonencode({
        computeType = "Fargate"
        resources = {
          limits = {
            cpu = "0.25"
            memory = "256M"
          }
          requests = {
            cpu = "0.25"
            memory = "256M"
          }
        }
      })
    }
    kube-proxy = {}
    vpc-cni    = {}
  }

  fargate_profiles = {
    karpenter = {
      selectors = [
        { namespace = "karpenter" }
      ]
    }
    kube_system = {
      name = "kube-system"
      selectors = [
        { namespace = "kube-system" }
      ]
    }
  }

  tags = merge(local.tags, {
    "karpenter.sh/discovery" = local.name
  })
}

module "karpenter" {
  source  = "terraform-aws-modules/eks/aws//modules/karpenter"

  cluster_name = module.eks.cluster_name
  enable_irsa            = true
  irsa_oidc_provider_arn = module.eks.oidc_provider_arn

  node_iam_role_additional_policies = {
    AmazonSSMManagedInstanceCore = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  }

  tags = local.tags
}

resource "kubectl_manifest" "karpenter_node_pool" {
  yaml_body = <<-YAML
    apiVersion: karpenter.sh/v1beta1
    kind: NodePool
    metadata:
      name: test-nodepool
    spec:
      template:
        metadata:
          labels:
            managedBy: karpenter
            nodepool: test-nodepool
        spec:
          requirements:
            - key: "karpenter.k8s.aws/instance-family"
              operator: In
              values: ["t3a"]
            - key: "topology.kubernetes.io/zone"
              operator: In
              values: ${jsonencode(local.azs)}
            - key: "kubernetes.io/arch"
              operator: In
              values: ["arm64", "amd64"]
            - key: "karpenter.sh/capacity-type"
              operator: In
              values: ["spot", "on-demand"]
          nodeClassRef:
            name: test-nodeclass
      kubelet:
          containerRuntime: containerd
          podsPerCore: 100
      limits:
        cpu: 1000
      disruption:
        consolidationPolicy: WhenEmpty
        consolidateAfter: 600s
        expireAfter: 720h # 30 * 24h = 720h
  YAML

  depends_on = [
    helm_release.karpenter
  ]
}

resource "kubectl_manifest" "karpenter_node_class" {
  yaml_body = <<-YAML
    apiVersion: karpenter.k8s.aws/v1beta1
    kind: EC2NodeClass
    metadata:
      name: test-nodeclass
    spec:
      amiFamily: AL2
      role: ${module.karpenter.node_iam_role_name}
      subnetSelectorTerms:
        - tags:
            karpenter.sh/discovery: ${module.eks.cluster_name}
      securityGroupSelectorTerms:
        - tags:
            karpenter.sh/discovery: ${module.eks.cluster_name}
      tags:
        karpenter.sh/discovery: ${module.eks.cluster_name}
  YAML
  depends_on = [
    kubectl_manifest.karpenter_node_pool
  ]
}
```

 no
 Yes
 terraform destory.
The cluster doesn't have any access entries apart from the "cluster_creator" set as true. It does have standard EC2_LINUX and FARGATE_LINUX as system:node (permissions)

## Expected behavior

access entry should be deleted after all cluster components are destroyed

## Actual behavior

> 
> module.eks.aws_eks_access_entry.this["cluster_creator"]: Destruction complete after 1s
> 
> │ Error: test-nodeclass failed to delete kubernetes resource: ec2nodeclasses.karpenter.k8s.aws "test-nodeclass" is forbidden: User "arn:aws:sts::<my-account>:assumed-role/<my-admin-role>" cannot delete resource "ec2nodeclasses" in API group "karpenter.k8s.aws" at the cluster scope
> |

**Comment by bryantbiggs** [comment]
this is outside the control of the module. With controllers like Karpenter that create additional AWS resources, you will need to remove those controllers prior to tearing down the cluster they are running on
