### ISSUE TITLE
Autoscaling group name without any suffix/prefix

### ISSUE THREAD

**Issue by ajays-y** [terraform-aws-modules/terraform-aws-eks#3007]
I am using eks managed node-groups using the provided modules, i am not able to get autoscaling group name proper for the nodegroups, 

currently i am getting it like : eks-{nodegroup-name}-58c776863-98-7837-988929yg8fh-something like this
Expected: {nodegroup-name}

How can i achieve with this ? I tried playing around with use_name_prefix variable but didnt get much.

Any help is appreciated :)

**Comment by 170031284** [comment]
Hey ,
Just check if you are using the updated module . I advice to check the version and also verify if the version you are working on is supporting prefix names . Also some terraform modules has capacity to override the customised name . Also check your syntax and make your your run it properly.

**Comment by ajays-y** [comment]
It supports prefix names, previously nodegroup names also used to come on that manner, I used use_name_prefix = false under eks_managed_nodegroup_defaults , it fixed the naming of nodegroup name but not the auto scaling group.
If there is any working tested example, would be more helpful

**Comment by bryantbiggs** [comment]
when using EKS Managed nodegroups, you will always get an ASG with a name that has randomness added to it - it has always been this way since MNG was released

**Comment by ajays-y** [comment]
That is unfortunate, any other workarounds to achieve this ?

**Comment by bryantbiggs** [comment]
What are you trying to do

**Comment by ajays-y** [comment]
Just trying to make sure ASG are created with proper names with terraform, we have some custom scripts which parse these and make use further.

**Comment by bryantbiggs** [comment]
Then you will need to use self-managed nodegroups

**Comment by bryantbiggs** [comment]
that would be up to the EKS service, but I highly doubt that would happen. The randomness in the ASG names is intentional, allowing the managed nodegroup to replace ASGs as needed without or have multiple ASGs without name conflicts

> we have some custom scripts which parse these and make use further.
I would also advise you not do this and leave these to MNG to manage, otherwise create separate ASGs that you control 

Closing this for now since there is no action required here
