### ISSUE TITLE
Doc improvement for cluster_addons

### ISSUE THREAD

**Issue by VardyNg** [terraform-aws-modules/terraform-aws-eks#3008]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
I have been working on a project to provision EKS with Add-ons using the module.
While configuring `cluster_addons`, I found it is not easy to find the accepted plugin names list, I did some searching and testing and finally understand it is the Add-ons name defined in this [AWS Doc](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html)

## Describe the solution you'd like.
I think it would be great to add reference to this doc, so that others can know where to find the plugin name and supply to the `cluster_addons`

## Describe alternatives you've considered.
NA

## Additional context
NA

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.12.0 :tada:
