### ISSUE TITLE
ami_type for self manager node groups

### ISSUE THREAD

**Issue by jgournet** [terraform-aws-modules/terraform-aws-eks#3009]
## Is your request related to a new offering from AWS?
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider

## Is your request related to a problem? Please describe.
EKS managed groups have this nice feature of "ami_type" that translates an ami type to an ami ID (via reading SSM parameters from AWS):
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/eks-managed-node-group/main.tf#L344

## Describe the solution you'd like.
Could this feature be added to self managed node groups ? (which would use the /ami_id ssm parameter instead of /release_version)

## Describe alternatives you've considered.
I could have an additional terraform data to retrieve the ami_id based on my own search pattern - but would be nice if it could be integrated in this module.

## Additional context
I'm interested in using AL2023 image, which requires a few additional things (like passing a YAML config and using IMDSv2) - if the module could also handle it, that would be nice :) (ok, I might be asking for too much here)

**Comment by bryantbiggs** [comment]
> I'm interested in using AL2023 image, which requires a few additional things (like passing a YAML config and using IMDSv2) - if the module could also handle it, that would be nice :) (ok, I might be asking for too much here)

this module already supports AL2023, what else is missing?

**Comment by jgournet** [comment]
> this module already supports AL2023, what else is missing?
Sorry, I might have missed it - for self managed node groups, all I could find was to pass a ami_id; while eks-managed-node-group has a "ami_type" functionality

**Comment by bryantbiggs** [comment]
correct - that is due to the EKS MNG API. 

If you look at the examples we provide, nearly everything is covered there https://github.com/terraform-aws-modules/terraform-aws-eks/blob/afadb14e44d1cdbd852dbae815be377c4034e82a/examples/self_managed_node_group/main.tf#L75-L96

**Comment by jgournet** [comment]
Than you !
