### ISSUE TITLE
Cluster autoscaler is not able to increase worker node

### ISSUE THREAD

**Issue by shindanim** [terraform-aws-modules/terraform-aws-eks#301]
# I have issues
with increasing worker node for exceeded pods.

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ / ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Hello, now I'm trying to enable the cluster autoscaler
When `terragrunt apply` for the first time, it seems that it is applied to the aws also well, it can be checked in the aws console. 

After then, however, when I try to deploy some pods whose number is exceed for capacity of all nodes, 
the pod deploy is failed because of `nodes are available: 5 Insufficient pods.`

Is there anything that I missed ? 

## If this is a bug, how to reproduce? Please include a code sample if relevant.
```
  worker_groups = [                                                                                                     
    {                                                                                                                   
      instance_type                 = "t2.nano"                                                                         
      root_volume_size              = "100"                                                                             
      asg_max_size                  = 9                                                                                 
      asg_desired_capacity          = 5                                                                                 
      asg_force_delete              = true                                                                              
      key_name                      = "eks_nano"                                                                      
      autoscaling_enabled           = true                                                                              
      additional_security_group_ids = "${aws_security_group.eks_nano_sg_instance.id}"                                 
    },                                                                                                                  
  ]   
```

## What's the expected behavior?
The CA increases more node for the new pod

## Environment details
* Affected module version: terraform-aws-eks?ref=v2.0.0
* OS: Ubuntu 16.04 LTS
* Terraform version: 
Terraform v0.11.11
+ provider.aws v2.1.0
+ provider.local v1.1.0
+ provider.null v2.1.0
+ provider.template v2.1.0
terraform-aws-eks?ref=v2.0.0

**Comment by max-rocket-internet** [comment]
Hi @shindanim, you need to actually install the cluster-autoscaler yourself. This is not done in TF. This is a pod that runs in your cluster. Some details here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/autoscaling.md

Have you done that already?

**Comment by shindanim** [comment]
@max-rocket-internet  
Thanks for you reply.
Actually, I've not installed the `cluster-autoscaler` so I tried to install it. 
However, the autoscaler pod didn't work well with status `CrashLoopBackOff`
and the kubectl event log is following 
```
Error: failed to start container "cluster-autoscaler": Error response from daemon: OCI runtime create failed: container_linux.go
```
Do you have any idea regarding that ?

**Comment by shindanim** [comment]
Helm install succeeded after fixing ca-certificate.crt to ca-bundle.crt.
Howerver, cluster-autoscaling is not working yet. 
I guess it is because of `default` namespace instead of `kube-system`. 
The problem is I don't know how to fix namespace of autoscaler from `values.yaml` :/.

**Comment by shindanim** [comment]
Finally I got my CA after following guide (https://eksworkshop.com/scaling/deploy_ca/)
and cluster make new node id there is insufficient place to assign pods. 
Cluster size down works well, too. 
Regarding size down of worker node, is there anyone who knows what is the trigger point for scale down?
Insufficient space is no doubt for scale up, but I can't find the trigger point for scale down.

**Comment by max-rocket-internet** [comment]
Cool, glad you got it resolved.

Downscaling is covered here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-scale-down-work
