### ISSUE TITLE
Ask about upgrade flow for managed node group

### ISSUE THREAD

**Issue by vietwow** [terraform-aws-modules/terraform-aws-eks#3011]
## Description

I'm going to upgrade my EKS cluster (which is provisioned by terraform-aws-eks v20.8.4, with managed node groups) using **max_unavailable** with value 1, which means I expected the upgrade process will be rolling one-by-one node. 

My code for managed node group is :

```
data "aws_ami" "eks_golden_image" {
  most_recent = true
  owners      = ["xxxxx"]

  filter {
    name   = "name"
    values = ["golden_image_amazon_linux_2_vEKS_3.0.10_2023-07-28_09-31-11"]
  }
}
```

```
...
  eks_managed_node_groups = {
    managed-nodes = {
      node_group_name = "managed-nodes-m6i-2xlarge"
      instance_types  = ["m6i.2xlarge"]

      min_size      = 1
      desired_size  = 1
      max_size      = 6
      ami_type      = "CUSTOM" # AL2_x86_64, AL2_x86_64_GPU, AL2_ARM_64, CUSTOM
      ami_id        = data.aws_ami.eks_golden_image.image_id
      capacity_type = "ON_DEMAND"

      create_iam_role = true
      iam_role_additional_policies = {
        AmazonSSMManagedInstanceCore = "arn:${data.aws_partition.current.partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
        CloudWatchAgentServerPolicy  = "arn:${data.aws_partition.current.partition}:iam::aws:policy/CloudWatchAgentServerPolicy"
      }
      iam_role_permissions_boundary = data.aws_iam_policy.role_permissions_boundary.arn

      create_launch_template = true # false will use the default launch template

      ssh_security_group_id = ""
      enable_monitoring     = true

      ebs_optimized = true

      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 160
            volume_type           = "gp3"
            iops                  = 3000
            throughput            = 150
            encrypted             = true
            delete_on_termination = true
          }
        }
      }

      additional_tags = merge(
        local.tags,
        { "InstanceType" = "on-demand" }
      )

      launch_template_tags = merge(
        local.tags,
        { "InstanceType" = "on-demand" }
      )

      update_config = {
        max_unavailable = 1
      }
    }
...
```

From what I'm understanding, I only need to change "eks_golden_image" with newer AMI id and then terraform apply, so it will rolling upgrade (one by one) my managed group ? Is it right ?

If yes, I also read another article here https://dev.to/ashiqursuperfly/eks-multiple-kubernetes-version-jump-using-terraform-lp7 and it confused me as it said that once we changed AMI id in terraform code, we need to run instance refresh for the autoscaling group the k8s. So do we really need to do this step ?

Hope someone could share the exact upgrade flow for terraform-aws-eks with managed node group. Thank you so much.

## Versions

- Module version [Required]: v20.8.4

- Terraform version:

- Provider version(s):

**Comment by vietwow** [comment]
> this is how MNG updates nodes https://docs.aws.amazon.com/eks/latest/userguide/managed-node-update-behavior.html

Hi @bryantbiggs , yes I have already read it, that's why I used `updateConfig` to control the upgrade the behaviour. My question in this context is the flow when using this terraform module, is it just change AMI in the `ami_id` like I described ? And do we need to run refresh instance in managed instance group ? Thanks

**Comment by bryantbiggs** [comment]
> is it just change AMI in the ami_id like I described ?

Maybe, hard to tell without seeing the full config

The module does thread the dependencies correctly to update a cluster. For example, if using EKS MNG and not specifying a custom AMI, you would simply change the cluster version and it would:
1. Upgrade the control plane
2. Upgrade the EKS addons to their respective default/latest equivalents for the given cluster version
3. Roll out an AMI to the nodegroups with an AMI that matches the cluster version

With a custom AMI, you would need to supply the new AMI that associated with the cluster version that you are upgrading to. 

If you are not managing EKS addons through the module, this is an area you will have to manage manually and ensure you are using version that are compatible with the cluster version you are upgrading to

**Comment by vietwow** [comment]
> > is it just change AMI in the ami_id like I described ?
> 
> Maybe, hard to tell without seeing the full config
> 
> The module does thread the dependencies correctly to update a cluster. For example, if using EKS MNG and not specifying a custom AMI, you would simply change the cluster version and it would:
> 
> 1. Upgrade the control plane
> 2. Upgrade the EKS addons to their respective default/latest equivalents for the given cluster version
> 3. Roll out an AMI to the nodegroups with an AMI that matches the cluster version
> 
> With a custom AMI, you would need to supply the new AMI that associated with the cluster version that you are upgrading to.
> 
> If you are not managing EKS addons through the module, this is an area you will have to manage manually and ensure you are using version that are compatible with the cluster version you are upgrading to

Hi @bryantbiggs 

Here is full code in case you need :

```
data "aws_ami" "eks_golden_image" {
  most_recent = true
  owners      = ["xxxxxx"]

  filter {
    name   = "name"
    values = ["golden_image_amazon_linux_2_vEKS_3.0.10_2023-07-28_09-31-11"]
  }
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.8.4"

  # EKS CLUSTER
  cluster_name    = var.cluster_name
  cluster_version = var.eks_version

  vpc_id     = var.vpc_id
  subnet_ids = var.subnet_ids

  iam_role_permissions_boundary = var.iam_role_permissions_boundary

  cluster_endpoint_public_access  = false
  cluster_endpoint_private_access = true

  enable_cluster_creator_admin_permissions = true

  access_entries = {
    administrator_bootstrap = {
      kubernetes_groups = []
      principal_arn     = local.sso_arn

      policy_associations = {
        admin = {
          policy_arn = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"
          access_scope = {
            type = "cluster"
          }
        }
      }
    }
  }

  enable_irsa = true

  # Extend cluster security group rules
  cluster_security_group_additional_rules = {
    ingress_api_server_tcp = {
      description = "Access EKS API Server."
      protocol    = "tcp"
      from_port   = 443
      to_port     = 443
      type        = "ingress"
      cidr_blocks = [for k, v in var.allowed_vpc_cidrs : v]
    }

    egress_tcp = {
      description = "Access outside from EKS."
      protocol    = "tcp"
      from_port   = 0
      to_port     = 0
      type        = "egress"
      cidr_blocks = ["0.0.0.0/0"]
    }
  }

  ## EKS MANAGED NODE GROUPS

  eks_managed_node_groups = {
    managed-nodes = {
      node_group_name = "managed-nodes-m6i-2xlarge"
      instance_types  = ["m6i.2xlarge"]

      min_size      = 1
      desired_size  = 1
      max_size      = 6
      ami_type      = "CUSTOM" # AL2_x86_64, AL2_x86_64_GPU, AL2_ARM_64, CUSTOM
      ami_id        = data.aws_ami.eks_golden_image.image_id
      capacity_type = "ON_DEMAND"

      create_iam_role = true
      iam_role_additional_policies = {
        AmazonSSMManagedInstanceCore = "arn:${data.aws_partition.current.partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
        CloudWatchAgentServerPolicy  = "arn:${data.aws_partition.current.partition}:iam::aws:policy/CloudWatchAgentServerPolicy"

      }
      iam_role_permissions_boundary = var.iam_role_permissions_boundary

      create_launch_template = true # false will use the default launch template

      ssh_security_group_id = ""
      enable_monitoring     = true

      ebs_optimized = true

      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 160
            volume_type           = "gp3"
            iops                  = 3000
            throughput            = 150
            encrypted             = true
            delete_on_termination = true
          }
        }
      }

      additional_tags = merge(
        var.tags,
        { "InstanceType" = "on-demand" }
      )

      launch_template_tags = merge(
        var.tags,
        { "InstanceType" = "on-demand" }
      )
    }

  node_security_group_additional_rules = {
    # Extend node-to-node security group rules. Recommended and required for the Add-ons
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    # Recommended outbound traffic for Node groups
    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }

    ingress_cluster_to_node_all_traffic = {
      description                   = "Cluster API to Nodegroup all traffic"
      protocol                      = "-1"
      from_port                     = 0
      to_port                       = 0
      type                          = "ingress"
      source_cluster_security_group = true
    }
  }
}
```

so in this case, I just need to change `"golden_image_amazon_linux_2_vEKS_3.0.10_2023-07-28_09-31-11"`(in resource data aws_ami) to another AMI id and do terraform apply, then that's all (and I don't need to run instance refresh like the article I mentioned above). Please confirm if I'm right ?

Thank you so much for your support
