### ISSUE TITLE
No tagging for managed node groups

### ISSUE THREAD

**Issue by oc-stephen-bennett** [terraform-aws-modules/terraform-aws-eks#3015]
Hi, 

Apologies not sure to class this as a bug or feature request?

When creating a managed node group we are not getting tags to the autoscaling group or any of the ec2 instances / resources. we add as default tags to the provider or in the module 

example:

```
provider "aws" {
  default_tags {
    tags = {
      terraform           = "true"
    }
  }
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  ...

  eks_managed_node_groups = {
    charlie = {
        ....

        tags = {
          terraform           = "true"
        }
      }
    }
  }

**Comment by tanadeau** [comment]
We're also seeing this issue.

**Comment by bryantbiggs** [comment]
You should pass tags via the `tags` input variable

**Comment by tanadeau** [comment]
The root cause seems to be https://github.com/hashicorp/terraform-provider-aws/issues/32328 where the provider default tags are not being passed into `tag_specifications`
