### ISSUE TITLE
access_entries with custom resources

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [terraform-aws-modules/terraform-aws-eks#3016]
## Is your request related to a problem? Please describe.
I'd like to have authentication role for developers who can view whole cluster and have admin access on particular namespaces. With the following code developers are not able to interact with custom resources

```hcl
    eks-devs = {
      kubernetes_groups = []
      principal_arn     = "arn:aws:iam::${local.account_id}:role/eks-devs"

      policy_associations = {
        edit_dev_namespaces = {
          policy_arn = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSAdminPolicy"
          access_scope = {
            namespaces = concat(["default"], var.dev_namespaces)
            type       = "namespace"
          }
        }
        readonly = {
          policy_arn = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSViewPolicy"
          access_scope = {
            type = "cluster"
          }
        }
      }
    }
```

Helm error:
```
Error: UPGRADE FAILED: could not get information about the resource: servicemonitors.monitoring.coreos.com "dev-preview-cardanojs-backend-monitor" is forbidden: User "arn:aws:sts::926093910549:assumed-role/eks-devs/EKSGetTokenAuth" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "dev-preview"
```

## Describe the solution you'd like.
Basically any kind of fix for this, maybe docs improvement is all that is missing.
Defining resources with which user interact or a way to define additional k8s role would be great

## Describe alternatives you've considered.

Reverting to eks-auth module

**Comment by bryantbiggs** [comment]
this is something that EKS will need to support first - please follow https://github.com/aws/containers-roadmap/issues/2244
