### ISSUE TITLE
Pre-bootstrap user data for al2023

### ISSUE THREAD

**Issue by tropnikovvl** [terraform-aws-modules/terraform-aws-eks#3017]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
At the moment, you can make a pre-bootstrap user data for regular Linux, but it’s not clear how to do it for al2023.

[Complete example file](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_managed_node_group/main.tf#L204)
[Linux](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/templates/linux_user_data.tpl#L5)
[AL2023](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/templates/al2023_user_data.tpl)

## Describe the solution you'd like.
Make it possible to use pre-bootstrap user data for al2023

**Comment by bryantbiggs** [comment]
its there in the examples - thats why we provide examples https://github.com/terraform-aws-modules/terraform-aws-eks/blob/afadb14e44d1cdbd852dbae815be377c4034e82a/examples/user_data/main.tf#L117-L139

**Comment by tropnikovvl** [comment]
@bryantbiggs 
I saw this example, but it’s not clear from it how to add, for example, a bash script

**Comment by bryantbiggs** [comment]
whats not clear? AL2023 EKS AMI uses Multi-part MIME data format which is what we support here

**Comment by tropnikovvl** [comment]
@bryantbiggs 
Does this mean that this is how it should work?

```
module "eks_mng_al2023_additional" {
  source = "../../modules/_user_data"

  platform = "al2023"

  # Hard requirement
  cluster_service_cidr = local.cluster_service_cidr

  cloudinit_pre_nodeadm = [{
    content      = <<-EOT
      echo "All done"
    EOT
    content_type = "text/x-shellscript; charset=\"us-ascii\""
  }]
}

```

**Comment by bryantbiggs** [comment]
have you tried it 🙃

**Comment by tropnikovvl** [comment]
I haven’t tried it yet, I want a full understanding of how it works
