### ISSUE TITLE
Add tag_specifications to ASG created by eks_managed_nodegroup 

### ISSUE THREAD

**Issue by not-ajay** [terraform-aws-modules/terraform-aws-eks#3022]
Currently the tag_specifications in ASG created by eks_managed_nodegroup has only instance and volume, i need to add 2 more to this, how can i do this for the ASG launch template created by eks_managed_nodegroup : 

I tested by using custom launch template and providing below in eks_managed_node_group_defaults : 
tag_specifications = ["instance", "volume", "network-interface", "spot-instances-request"]

Same i want in the launch template for ASG which is created by eks_managed_nodegroup. 

Any help is apreciated :)

**Comment by not-ajay** [comment]
@bryantbiggs Can you take a look and suggest ?

**Comment by bryantbiggs** [comment]
There are variables for this https://github.com/terraform-aws-modules/terraform-aws-eks/blob/92fca6fcf94777c55eeccb398fa546a43b958475/modules/eks-managed-node-group/variables.tf#L324-L328

**Comment by not-ajay** [comment]
Hey @bryantbiggs , Eventhough i have added the  tag_specifications variable with required resources, it doesnt seem to be propagated to the launch template created by eks managed nodegroup. 

I took help of AWS support and found this issue in open at their end : https://github.com/aws/containers-roadmap/issues/1496
