### ISSUE TITLE
Karpenter example does not work, pods are pending (version 20.8.5)

### ISSUE THREAD

**Issue by ioga** [terraform-aws-modules/terraform-aws-eks#3027]
## Description

Hello, I am trying out the karpenter example, and karpenter pods won't get scheduled.
Same symptoms as https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2943 , but it doesn't work despite the tolerations added in the fix mentioned in that issue. The error message in kubectl describe pod is:

```
Warning  FailedScheduling  82s (x8 over 36m)   default-scheduler  0/2 nodes are available: 2 Too many pods. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod.
```

CoreDNS pods in `kube-system` namespace has scheduled fine.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 20.8.5

- Terraform version:
```
Terraform v1.8.2
on darwin_amd64
+ provider registry.terraform.io/alekc/kubectl v2.0.4
+ provider registry.terraform.io/hashicorp/aws v5.47.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.4
+ provider registry.terraform.io/hashicorp/helm v2.13.1
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/time v0.11.1
+ provider registry.terraform.io/hashicorp/tls v4.0.5
```

## Reproduction Code [Required]

Stock `karpenter` example.

```
cd terraform-aws-eks-20.8.5/examples/karpenter/
# update region and cluster name in the `locals` section
terraform init
terraform apply -auto-approve
aws eks --region <region> update-kubeconfig --name <cluster name>
kubectl get pods -n karpenter
```

## Expected behavior

karpenter pods will be running

## Actual behavior

karpenter pods are pending

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.10.0 :tada:
