### ISSUE TITLE
chmod 644 kubeconfig & config-map-aws-auth

### ISSUE THREAD

**Issue by pkelleratwork** [terraform-aws-modules/terraform-aws-eks#303]
# I have issues

## I'm submitting a... 

* [X] bug report
* [ ] feature request
* [ ] support request
* [X] kudos, thank you, warm fuzzy

## What is the current behavior?
kubeconfig and config-map-aws-auth are created with execute privlages. they do not need this
`-rwxr-xr-x  1 username  staff    337 Mar 12 20:50 config-map-aws-auth_testeks2.yaml`

`-rwxr-xr-x  1 username  staff   1880 Mar 12 20:50 kubeconfig_testeks2`

## What's the expected behavior? 
kubeconfig and config-map-aws-auth should have 644 privileges `-rw-r--r--`

## Environment details

* Affected module version:
* OS:
* Terraform version: 
terraform 0.11.11
provider ~>2.0
module 
	source terraform-aws-modules/eks/aws version 2.2.21
## Any other relevant info
this is an awesome project!

**Comment by max-rocket-internet** [comment]
What is your umask? Could be that.

Also, hard to make a PR to add some chmod command as this will fail on Windows 😅

**Comment by max-rocket-internet** [comment]
Ah, it's an issue in the local file provider: https://github.com/terraform-providers/terraform-provider-local/issues/19

**Comment by pkelleratwork** [comment]
ahh - cool. thanks for looking at this. this is a great project - thanks for doing it.

**Comment by confiq** [comment]
I guess we can close the issue for this but out of curiosity, did `+x` interfere with your work?

**Comment by pkelleratwork** [comment]
@confiq nope, this did not interfere with anything, i just happened to notice it.
