### ISSUE TITLE
The module should support eks add-ons deploy flag

### ISSUE THREAD

**Issue by VardyNg** [terraform-aws-modules/terraform-aws-eks#3033]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

### Context
As AWS China Region do not support some of the **managed** add-on (e.g. efs) [Reference](https://docs.amazonaws.cn/eks/latest/userguide/efs-csi.html).
Quote: 

Amazon EFS 驱动程序在此 Amazon Web Services 区域中仅支持自行管理安装。有关如何将其添加为自行管理安装的说明，请参阅 GitHub 上的 [安装](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/README.md#installation)。

Which translate to 
Amazon EFS Driver in this AWS region only support self-managed installation. For how to add it as a self-managed add-on, please refer to the [Installation](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/README.md#installation) on GitHub.

### Module behaviour
When deploying EKS using this module with add-on `aws-efs-csi-driver`, Terraform will report error as the efs driver is not supported when installed in the managed way.

```terraform
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.10.0"
 ....
  cluster_addons = {
    aws-efs-csi-driver ={
      most_recent = true
      service_account_role_arn = aws_iam_role.efs_role.arn
    }
  }

...
}
```

```
kubernetes_persistent_volume_claim_v1.default: Still creating... [4m40s elapsed]
module.eks.data.aws_eks_addon_version.this["aws-efs-csi-driver"]: Still reading... [4m50s elapsed]
kubernetes_persistent_volume_claim_v1.default: Still creating... [4m50s elapsed]
module.eks.data.aws_eks_addon_version.this["aws-efs-csi-driver"]: Still reading... [5m0s elapsed]
╷
│ Error: client rate limiter Wait returned an error: context deadline exceeded
│ 
│   with kubernetes_persistent_volume_claim_v1.default,
│   on k8s.tf line 22, in resource "kubernetes_persistent_volume_claim_v1" "default":
│   22: resource "kubernetes_persistent_volume_claim_v1" "default" {
│ 
╵
╷
│ Error: reading EKS Add-On version info (aws-efs-csi-driver, 1.29): empty result
│ 
│   with module.eks.data.aws_eks_addon_version.this["aws-efs-csi-driver"],
│   on .terraform/modules/eks/main.tf line 484, in data "aws_eks_addon_version" "this":
│  484: data "aws_eks_addon_version" "this" {
│ 
```

## Describe the solution you'd like.

I think it would be nice to add a flag, like the use of Terraform [Feature Toggles](https://www.hashicorp.com/blog/terraform-feature-toggles-blue-green-deployments-canary-test), to control the deployment by giving the `count` value. For example, `count=0` means do not deploy.

The input would be something like:
```terraform
  cluster_addons = {
    aws-efs-csi-driver ={
      most_recent = true
      service_account_role_arn = aws_iam_role.efs_role.arn
      deploy = false # <- here, we specify the add-on but do not deploy it
    }
  }
```

By doing this, we can do something like
```terraform
```terraform
  cluster_addons = {
    aws-efs-csi-driver ={
      most_recent = true
      service_account_role_arn = aws_iam_role.efs_role.arn
      deploy = var.region == "cn-north-1"  || var.region == "cn-northwest-1" ? false : true # if is China region, do not deploy. Otherwise, deploy it.
    }
  }
```

## Describe alternatives you've considered.

A solution to this would be to define the `aws_eks_addon` resource as a separate resource, so that I can control whether to deploy it or not, by using `count`

```terraform

resource "aws_eks_addon" "efs-driver" {
  count                       =  var.region == "cn-north-1"  || var.region == "cn-northwest-1" ? 0 : 1
  cluster_name                = module.eks.cluster_name
  addon_name                  = "aws-efs-csi-driver"
  service_account_role_arn    = aws_iam_role.efs_role.arn 
}


```
Another consideration would be to use [dynamic block](https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks) in the Module, but it is not supported in `module` and work on `resource`.

**Comment by bryantbiggs** [comment]
If you wish to NOT deploy the addon, simply do not add it into the list of addons 😅

**Comment by VardyNg** [comment]
@bryantbiggs  I don't think it as trivial as it seems to be, currently there is no way to control add-on deployment conditionally, in my case, that's whether the region is AWS China Region or not. 

The current module requires developers to modify the TF code if it has to be deployed in AWS China Region.

**Comment by bryantbiggs** [comment]
Let me guess, you are using Terraform workspaces

**Comment by VardyNg** [comment]
Not exactly 👀 , let me explain the issue that I am facing and why I think this feature would be useful.

In my case, I have a TF project deploying EKS using this module, it is looking something like:
```terraform
locals {
  region = var.region
}

provider "aws" {
  region = local.region
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.10.0"
 ....
  cluster_addons = {
    aws-efs-csi-driver ={
      most_recent = true
      service_account_role_arn = aws_iam_role.efs_role.arn
    }
  }
}
```

The above work fine in AWS Global Region (and Gov-Cloud I assume), but in the case of AWS China Region, again, this region doesn't do managed add-on for efs driver. If I am going to deploy it in China region, it would fail as the add-on is not supported.

To handle this, one way to go is to first determine what region are we deploying, if it is AWS China (`cn-north-1` and `cn-northwest-1`), we do not deploy this add-on. 

However, since we can't set condition specific for the `cluster_addons` value, I will need to change the module itselves in order to fulfil this need.

My workaround for this is become

```terraform
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.10.0"
 ....
}

resource "aws_eks_addon" "efs-driver" {
  count                       =  var.region == "cn-north-1"  || var.region == "cn-northwest-1" ? 0 : 1
  cluster_name                = module.eks.cluster_name
  addon_name                  = "aws-efs-csi-driver"
  service_account_role_arn    = aws_iam_role.efs_role.arn 
}

```

I hope it help explain the situation :D

**Comment by bryantbiggs** [comment]
I don't follow - why is the region a variable if you aren't using workspaces? 

In short - Terraform is declarative. What you see is what you get. If you want something deployed, you define that in your configuration. If you do not want it deployed, you do not define it in your configuration.

**Comment by VardyNg** [comment]
Not exactly, the region is being a variable because the TF project allow developers to choose which region. I think it is a common usecase for Terraform, especially for a Terraform Module.

Altogether, I don't think this option violates the best practice of using Terraform, which provide allow resource with condition, i.e. input, like the use of 'count', 'for_each', and 'dynamic'.

Anyway, I think this feature is a good-to-have, as I have a workaround for this :)
