### ISSUE TITLE
fargate-profile: restrict role access based on SourceArn (or custom assume_role_policy)

### ISSUE THREAD

**Issue by cpboyd** [terraform-aws-modules/terraform-aws-eks#3038]
## Is your request related to a problem? Please describe.
Per [AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/pod-execution-role.html#check-pod-execution-role):
> To avoid a confused deputy security problem, it's important that the role restricts access based on SourceArn.

## Describe the solution you'd like.
Add a `condition` to the current `assume_role_policy`:
```hcl
data "aws_region" "current" {}

data "aws_iam_policy_document" "assume_role_policy" {
  count = local.create_iam_role ? 1 : 0

  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["eks-fargate-pods.amazonaws.com"]
    }

    condition {
      test     = "ArnLike"
      variable = "aws:SourceArn"

      values = [
        "arn:${data.aws_partition.current.partition}:eks:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:fargateprofile/${var.cluster_name}/*",
      ]
    }
  }
}
```

## Describe alternatives you've considered.
Allow users to specify a custom `condition` block for `assume_role_policy`.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.11.0 :tada:
