### ISSUE TITLE
Error: waiting for Security Group with node_security_group_additional_rules

### ISSUE THREAD

**Issue by eltalkarim** [terraform-aws-modules/terraform-aws-eks#3040]
## Description

I want to allow traffic from an ALB to EKS the node ports. I am creating a security group (in TF) before attaching to the ALB.  Furthermore, I am referencing it one of node_security_group_additional_rules rule as source. 

## Versions

- Module version [Required]: 19.21.0"
- Terraform version: 1.6.6
- Provider version(s): 5.36.0

## Reproduction Code [Required]

1- Add terraform code to create a security group
2- Reference it as source as illustrated in the code below

```    
ingress_from_alb = {
      protocol    = "tcp"
      from_port   = 1025
      to_port     = 65535
      type        = "ingress"
      source      = aws_security_group.alb_sg.id
      description = "ALB Access to Node Ports"
    }
```
3- Run terraform apply

## Expected behavior

The creation of the EKS cluster should success from first attempt

## Actual behavior

On first apply the eks resource does not find the security group although the logs shows it has been created:

```module.cloud.module.aws[0].module.eks.aws_security_group.alb_sg: Creation complete after 4s [id=sg-072055c88efd5d461]```

```
Error: waiting for Security Group (sg-06418771065286927) Rule (sgrule-4136029172) create: couldn't find resource

  with module.cloud.module.aws[0].module.eks.module.eks.aws_security_group_rule.node["ingress_from_alb"],
  on .terraform/modules/cloud.aws.eks.eks/node_groups.tf line 207, in resource "aws_security_group_rule" "node":
 207: resource "aws_security_group_rule" "node" {

```
On second apply the cluster creation works.

## Additional context

1) We are using Terragrunt. 
2) Not sure if this issue is related: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2997. However, we are creating other node_security_group_additional_rules in the same cluster without any problems. This leads me to believe it could be related to the use of the "source".

**Comment by bryantbiggs** [comment]
```diff
  ingress_from_alb = {
      protocol                 = "tcp"
      from_port                = 1025
      to_port                  = 65535
      type                     = "ingress"
-     source                   = aws_security_group.alb_sg.id
+     source_security_group_id = aws_security_group.alb_sg.id
      description              = "ALB Access to Node Ports"
    }
```
