### ISSUE TITLE
Allow tags in metadata and launch template tags not being applied to eks managed launch template

### ISSUE THREAD

**Issue by mtprovenir** [terraform-aws-modules/terraform-aws-eks#3046]
## Description

It appears that when `create_launch_template = true` and `launch_template_tags` are defined, as well as defining `metadata_options`, those are not copied to the resulting `eks-xxx` launch template.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 20.11.1

- Terraform version: OpenTofu v1.7.1

- Provider version(s):
```OpenTofu v1.7.1
on linux_arm64
+ provider registry.opentofu.org/hashicorp/aws v5.49.0
+ provider registry.opentofu.org/hashicorp/cloudinit v2.3.4
+ provider registry.opentofu.org/hashicorp/helm v2.13.2
+ provider registry.opentofu.org/hashicorp/kubernetes v2.30.0
+ provider registry.opentofu.org/hashicorp/null v3.2.2
+ provider registry.opentofu.org/hashicorp/time v0.11.1
+ provider registry.opentofu.org/hashicorp/tls v4.0.5
```

## Reproduction Code [Required]

```
...
  eks_managed_node_group_defaults = {
    create_launch_template     = true
    launch_template_tags       = var.default_tags
    create_iam_role            = false
    iam_role_arn               = aws_iam_role.worker_iam_role.arn
    use_name_prefix            = false
  }

  eks_managed_node_groups = {
    karpenter-controller-ng = {
      name                 = "karpenter-controller-ng"
      ami_type             = "BOTTLEROCKET_ARM_64"
      min_size             = 3
      max_size             = 3
      desired_size         = 3
      instance_types       = ["t4g.small"]
      subnet_ids           = var.private_subnets
      launch_template_tags = var.default_tags

      metadata_options = {
        http_endpoint               = "enabled"
        http_tokens                 = "required"
        instance_metadata_tags      = "enabled"
        http_put_response_hop_limit = 2
      }

      bootstrap_extra_args = <<-EOF
        [settings.bootstrap-containers.bootstrap]
        source = "xxx.dkr.ecr.eu-west-1.amazonaws.com/bottlerocket-bootstrap:1.0"
        mode = "once"
        essential = true
      EOF

      taints = [
        {
          key    = "purpose"
          value  = "karpenter-only"
          effect = "NO_SCHEDULE"
        }
      ]

      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 10
            volume_type           = "gp3"
            iops                  = 3000
            throughput            = 125
            encrypted             = true
            kms_key_id            = data.aws_kms_key.ebs.arn
            delete_on_termination = true
          }
        }
      }
    }
  }
```

Use above snippet.

## Expected behavior

The tags also copied to the template tags, and the `Allow tags in metadata` set to enabled.

## Actual behavior

The tags are only copied to the `resource tags` inside the launch template, not the template itself. `Allow tags in metadata` is also left undefined, despite being set on the user created launch template.

### Terminal Output Screenshot(s)
![image](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/168411899/96653cca-38fc-4dfd-bf72-9501ef916b27)
![image](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/168411899/fbe170ed-0c19-4719-8e6f-226a704a8d08)

**Comment by mtprovenir** [comment]
I had a cursory glance at the module code and it _looks_ right (at least, for the `Allow tags in metadata` option, which is what I'm mainly concerned about), which makes me think the issue may be upstream when the aws provider creates the launch template from the EKS node group.

If that is indeed the case, without doing _really_ heinous stuff, I'm wondering if the only reasonable solution is to use a self managed node group instead.

Would be interested in your thoughts.

**Comment by bryantbiggs** [comment]
already discussed in #1977
