### ISSUE TITLE
accessEntries not removed on node group(s) deletion

### ISSUE THREAD

**Issue by trourance** [terraform-aws-modules/terraform-aws-eks#3047]
## Description

I have migrated from 18.x to 19.x, then to 20.8.5. After that, I have removed two existing node groups, aaa and bbb. The existing entries in aws-auth mapRoles ConfigMap have been removed, as well as the related roles, "arn:aws:iam::xxx:role/aaa-eks-node-group-20221201150459530700000002" and "arn:aws:iam::xxx:role/bbb-eks-node-group-20220816140750090300000003".
But the roles are still listed in AccessEntries:
`$ aws eks list-access-entries --cluster-name test`
```{
    "accessEntries": [
        "arn:aws:iam::xxx:role/aaa-eks-node-group-20221201150459530700000002",
        "arn:aws:iam::xxx:role/bbb-eks-node-group-20220816140750090300000003",
```

- [ yes ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 20.8.5

- Terraform version: v1.8.3
- Provider version(s): registry.terraform.io/hashicorp/aws v5.42.0

## Reproduction Code [Required]

Migrate from 18.x to 20.x.
Remove node group(s).

## Expected behavior

Entries related to non existent role(s) for deleted node group(s) should be removed from AccessEntries.

## Actual behavior

AccessEntries are not removed.

**Comment by bryantbiggs** [comment]
is this for self-managed node groups or EKS managed node groups?

**Comment by trourance** [comment]
This is for EKS managed node groups.

**Comment by bryantbiggs** [comment]
EKS manages those entries, not this module. Closing out since this is down to the service and not something the module can/will control
