### ISSUE TITLE
Multiple map_roles causes a problem with auth configuration

### ISSUE THREAD

**Issue by krish7919** [terraform-aws-modules/terraform-aws-eks#305]
# I have issues

... with configuring multiple elements in `map_roles` list which does not get rendered properly thereby causing auth to the cluster to fail, resulting in redeployment of EKS cluster.

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I see this when I run a `kubectl -n kube-system edit cm aws-auth` command:

```
data:
  mapAccounts: ""
  mapRoles: "- rolearn: arn:aws:iam::1234567890:role/aws-iam-role-worker-role\n
    \ username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n
    \   - system:nodes\n\n- rolearn: arn:aws:iam::1234567890:role/admin\n  username:
    \n  groups:\n    - system:masters\n- rolearn: arn:aws:iam::1234567890:role/devops\n
    \ username: \n  groups:\n    - system:masters\n"
  mapUsers: |
    - userarn: arn:aws:iam::1234567890:user/aws-iam-user-eks
      username: admin
      groups:
        - system:masters
kind: ConfigMap
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Configure 2 entries in `map_roles` input like:

```
[
    {
      "group"    = "system:masters"
      "role_arn" = "arn:aws:iam::${ data.aws_caller_identity.current.account_id }:role/admin"
      "username" = ""
    },
    {
      "group"    = "system:masters"
      "role_arn" = "arn:aws:iam::${ data.aws_caller_identity.current.account_id }:role/devops"
      "username" = ""
    },
  ]
```

## What's the expected behavior?

Should render the YAML correctly.

## Are you able to fix this problem and submit a PR? Link here if you have already.
If I succeed to fix this, I will have a PR out.

## Environment details

* Affected module version:
* OS:
`MacOS`

* Terraform version:
```
$ terraform --version
Terraform v0.10.8
```

**Comment by krish7919** [comment]
Another point to note is the the auth-aws ConfigMap file written locally from the module renders properly.

**Comment by krish7919** [comment]
Ok. The code is exactly the same for `mapRoles` and `mapUsers` apart from the fact that, in `mapRoles`, we concat the `worker_role_Arn`.

Adding a newline in between then works and the YAML is rendered properly; diff below:

```
diff --git a/templates/config-map-aws-auth.yaml.tpl b/templates/config-map-aws-auth.yaml.tpl
index 86f4f5f..1caa424 100644
--- a/templates/config-map-aws-auth.yaml.tpl
+++ b/templates/config-map-aws-auth.yaml.tpl
@@ -6,6 +6,7 @@ metadata:
 data:
   mapRoles: |
 ${worker_role_arn}
+
 ${map_roles}
   mapUsers: |
 ${map_users}
```


I will test it better and find out if this works for sure before confirming this as resolved.

**Comment by krish7919** [comment]
No, jumped too soon. Does not work.

But the `kubectl` debug logs definitely state that this is a client side issue, no surprises there.

**Comment by krish7919** [comment]
There is something going on here - I reapplied the config a couple of times and it applied the right one at the 3rd attempt. I have logged in as users with different role binding and can authenticate to the cluster correctly.

Any reason why this can happen? I couldn't see any issues in the `aws-iam-authenticator` repo either.

**Comment by max-rocket-internet** [comment]
A lot has changed since this issue was opened so I'll close it now. Feel free to reopen after testing on latest version of this module 🙂
