### ISSUE TITLE
Changing authentication_mode in latest module version does not result in any changes to infrastructure

### ISSUE THREAD

**Issue by Jengah** [terraform-aws-modules/terraform-aws-eks#3052]
## Description
I believe there is a regression in `authentication_mode` introduced in 20.11.1.  Changing the value of `authentication_mode` from `API_AND_CONFIG_MAP` -> `API` results in "No changes. Your infrastructure matches the configuration." Pinning module version 20.11.0 results in the expected changes to `authentication_mode` being recognized by Terraform.

My hunch is that [this ignore change](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3042) is actually ignoring the entire `access_config` block and not just `bootstrap_cluster_creator_admin_permissions`

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 20.12.0

- Terraform version: v1.8.4

- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v5.51.1
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.4
+ provider registry.terraform.io/hashicorp/kubernetes v2.30.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/time v0.11.2
+ provider registry.terraform.io/hashicorp/tls v4.0.5
```

## Reproduction Code [Required]
```
module "data" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.12.0"

  authentication_mode = "API_AND_CONFIG_MAP"  # Toggling this value to "API" results in no changes to infrastructure
}
```

Not using workspace and local cache cleared many times during troubleshooting this issue.

- Upgraded to latest v20 (20.12.0)
- Attempted to switch authentication_mode from `API_AND_CONFIG_MAP` to `API`
- `terraform plan` results in "No changes. Your infrastructure matches the configuration."
- Pin to module version 20.11.1 and try again == same result
- Pin to module versoin 20.11.0 and try again == working as expected

## Expected behavior

I would expect that changing the `authentication_mode` to a valid value would result in the appropriate changes being present in my `terraform plan`

## Actual behavior

Changing the `authentication_mode` to a valid value does not result in any changes to infrastructure when running `terraform plan`

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.13.1 :tada:
