### ISSUE TITLE
Request to do not include other terraform-aws-modules inside the terraform-aws-eks

### ISSUE THREAD

**Issue by haofeif** [terraform-aws-modules/terraform-aws-eks#3054]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 

## Is your request related to a problem? Please describe.

Yes

## Describe the solution you'd like.

In the below KMS key feature, the [terraform-aws-modules/kms/aws](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L226C14-L226C40) is being called for the `terraform-aws-eks` module. 

In some of our customers, they do not have access to public terraform modules. Instead, they will create a local github repo in their organization to sync with the public terraform module `terraform-aws-eks` via github link.  In this case, when they do a sync for this, they have to manually go in this to change the `terraform-aws-modules` to their corresponding local repo, which will make the experiences not as pleasant and straightforward.

## Describe alternatives you've considered.
Replace the kms features with aws_provider terraform resource. 

## Additional context
N/A

**Comment by bryantbiggs** [comment]
we do not have any plans to remove this module, and in fact we have plans to replace some of the duplicated functionality for ASGs/launch templates with the ASG module in the next major version release https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-20.0.md#%EF%B8%8F-upcoming-changes-planned-in-v210-%EF%B8%8F

**Comment by haofeif** [comment]
@bryantbiggs okay. What about an another alternative ?

for these two lines, add `custom_terraform_registry_version_url`  as `Inputs` ?

From
```terraform
  source  = "terraform-aws-modules/kms/aws"
  version = "2.1.0" # Note - be mindful of Terraform/provider version compatibility between modules
``` 

to 

```terraform
variable "custom_terraform_registry_version_url" {
  description = "URL for custom Terraform registry version"
  type        = string
  default     = ""
}

locals {
  version = var.custom_terraform_registry_version_url != "" ? "" : "2.1.0"
}


  source = try(var.custom_terraform_registry_version_url, "terraform-aws-modules/kms/aws")
  version = local.version
```

As for private terraform registry, customers do want to leverage the full benefits of the public registry. Some customers use github or gitlab with the following format:
```terraform
source = "git@gitlab.com:XXX/terraform-aws-eks.git?ref=v20.12.0"
```

**Comment by bryantbiggs** [comment]
does that work? https://github.com/hashicorp/terraform/issues/1439

they are better off forking and updating these values on their own

**Comment by haofeif** [comment]
> does that work? [hashicorp/terraform#1439](https://github.com/hashicorp/terraform/issues/1439)
> 
> they are better off forking and updating these values on their own

it doesnt seem to address the same issue. We have no issues using the `source = "git@gitlab.com:XXX/terraform-aws-eks.git?ref=v20.12.0"`. Only when it has hard coded code inside of the module using another public terraform module it is making it difficult.

Customers did a fork a year ago, and made changes directly on the forked module. Now they found it extremely hard to sync  with the latest changes from the public terraform-aws-eks module. 

Hence, they made a pivot, which is to develop a `terraform-aws-eks-customer-wrapper` to incorporate the customer related changes that they would like to make, and make a local copy of the `terraform-aws-eks` module in their private gitlab. in this case, they could both enjoy syncing with the new changes from public repo, while making custom settings on their wrapper without touching the backend module. 

It is all working fine, but the sub hard coded module like this one is challenging. They might need to `git fetch remote`, `git push --force` with new changes, then find out the `terraform-aws-modules/kms/aws` and replace that with `source = "git@gitlab.com:XXX/terraform-aws-kms.git?ref=v2.1.0"`, instead of only touching their wrapper module.

**Comment by haofeif** [comment]
@bryantbiggs you see the current design for the customer. It will be quite difficult to manage without making the changes as above.

<img width="603" alt="image" src="https://github.com/terraform-aws-modules/terraform-aws-eks/assets/56006724/d375c624-af54-41e0-8b88-1eeb56e3d635">

**Comment by bryantbiggs** [comment]
@haofeif you are not listening - the two solutions you proposed are not going to be feasible:
1. We are not removing the KMS module
2. Terraform does not support variables for a module source
