### ISSUE TITLE
how to assign additional security groups to a node

### ISSUE THREAD

**Issue by aliartiza75** [terraform-aws-modules/terraform-aws-eks#3060]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is available in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality
NO

## Is your request related to a problem? Please describe.

I am deploying a self-managed EKS cluster using the module version. I want to assign additional security groups to node groups. In previous versions, I was able to do it using this variable ``vpc_security_group_ids`` but it is not possible now. Currently, either I can create a security [create_node_security_group](https://github.com/terraform-aws-modules/terraform-aws-eks#input_create_node_security_group) or use [node_security_group_id](https://github.com/terraform-aws-modules/terraform-aws-eks#input_node_security_group_id) to assign a security group.

## Describe the solution you'd like.

I want the default sg to be created, as well as the option to assign existing security groups.

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/098c6a86ca716dae74bd98974accc29f66178c43/modules/eks-managed-node-group/variables.tf#L164-L168
