### ISSUE TITLE
Can't deploy aws-ebs-csi-driver with Karpenter

### ISSUE THREAD

**Issue by RobinFrcd** [terraform-aws-modules/terraform-aws-eks#3067]
## Description

Hi, I've started my EKS cluster with the module and I've enabled **aws-ebs-csi-driver**. The thing is, I want to use Karpenter, I followed the doc and my eks_managed_node_group is set like this
```
    small = {
      min_size     = 1
      max_size     = 10
      desired_size = 2

      instance_types = ["t3.small", "t3a.small", "t2.small"]
      capacity_type  = var.use_spot ? "SPOT" : "ON_DEMAND"
      
      labels = {
        # Used to ensure Karpenter runs on nodes that it does not manage
        "karpenter.sh/controller" = "true"
      }

      taints = {
        # The pods that do not tolerate this taint should run on nodes
        # created by Karpenter
        karpenter = {
          key    = "karpenter.sh/controller"
          value  = "true"
          effect = "NO_SCHEDULE"
        }
      }
    }
```
because of the taints, I have some **ebs-csi-controller** pods that don't start `(0/3 nodes are available: 3 node(s) had untolerated taint {karpenter.sh/controller: true})`. I saw in the doc too that setting `ebs.csi.aws.com/agent-not-ready:NoExecute` may help, but I don't know how to configure this with the terraform module. Any idea ?
- I had the same issue with the alb-controller, but as it's managed by a helm chart it was easy to set the tolerations
- And with core, possible to set with:
 ```      configuration_values = jsonencode({
        tolerations = [
          # Allow CoreDNS to run on the same nodes as the Karpenter controller
          # for use during cluster creation when Karpenter nodes do not yet exist
          {
            key    = "karpenter.sh/controller"
            value  = "true"
            effect = "NoSchedule"
          }
        ]
      })
```
Thanks !

## Versions

- Module version [Required]: 20.13.1

**Comment by bryantbiggs** [comment]
the module will handle the addon version for you - by default it uses the default addon version for the given cluster version. using a static value like this can be error prone since you'll need to remember to change the version across cluster upgrades

**Comment by RobinFrcd** [comment]
Thanks for answers ! 
Working like a charm with:
```hcl
    aws-ebs-csi-driver = {
      most_recent = true
      service_account_role_arn = module.irsa-ebs-csi.iam_role_arn
      configuration_values = jsonencode({ 
        controller: { 
          tolerations: [{ 
            key: "karpenter.sh/controller", 
            operator: "Equal", 
            value: "true", 
            effect: "NoSchedule" 
          }] 
        } 
      })
    }
```
