### ISSUE TITLE
How to drain worker node for new instance type ?

### ISSUE THREAD

**Issue by shindanim** [terraform-aws-modules/terraform-aws-eks#307]
# I have issues
How can I drain old worker nodes to migrate to new instance type ? 

## I'm submitting a...

* [*] support request

## What is the current behavior?
Hello, now my instance type has been changed to bigger one.
Launch Configuration and ASG are also updated with new instance type,
hence I checked that cluster-autoscaler makes new node to unscheduled, new pod with new and bigger instance type. 
However, the previously run nodes have not been replaced with new instance type.
Searching the solution, I found following issue.[1]

> If you want to replace all instances in the cluster with the new type then you need to scale up the amount of instances in the ASG, then drain the old smaller instances, then terminate them.

But how old nodes can be drained ..?
If I terminate EC2 instances with AWS console in gui way, I might be able to, but I'd like to get code layer solution using terraform if there is any.
 
[1] https://github.com/terraform-aws-modules/terraform-aws-eks/issues/241

## What's the expected behavior?
Old worker node instance type can be replaced with new instance type automatically.

## Environment details

* Affected module version:
* OS: Ubuntu LTS 16.04
* Terraform version: v0.11.11
    + provider.aws v2.2.0 
    + provider.local v1.1.0
    + provider.null v2.1.0
    + provider.template v2.1.0

**Comment by max-rocket-internet** [comment]
Hi @shindanim 

You can drain a node like this: `kubectl drain --ignore-daemonsets --delete-local-data --timeout=600s <node name>`

Once this completes, you should have only daemonset pods on the node and then you can terminate it in the EC2 console.

Enjoy!

**Comment by shindanim** [comment]
@max-rocket-internet Thank you for your help :)
