### ISSUE TITLE
create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: i-089cae66b828ac922, i-0cd41e8867fda97cb: NodeCreationFailure: Instances failed to join the kubernetes cluster

### ISSUE THREAD

**Issue by asark67** [terraform-aws-modules/terraform-aws-eks#3074]
## Description

When trying to create a cluster I am getting the above error.

Points to note the VPCs and Subnets are already created and control plane subnets are the same as data subnets

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 20.14.0

- Terraform version:
Terraform v1.8.5
on linux_amd64

- Provider version(s):
+ provider registry.terraform.io/alekc/kubectl v2.0.4
+ provider registry.terraform.io/hashicorp/aws v5.50.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.4
+ provider registry.terraform.io/hashicorp/helm v2.13.2
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/time v0.11.1
+ provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.14.0"

  cluster_name    = "test-cluster"
  cluster_version = "1.30"

  enable_cluster_creator_admin_permissions = true
  cluster_endpoint_public_access           = true

  enable_irsa = false

  iam_role_permissions_boundary = var.permissions_boundary_arn

  cluster_addons = {
    coredns                = {}
    eks-pod-identity-agent = {}
    kube-proxy             = {}
    vpc-cni                = {}
  }

  vpc_id                   = var.network.vpc_id
  subnet_ids               = var.network.subnet_ids
  control_plane_subnet_ids = var.network.control_plane_subnet_ids

  eks_managed_node_groups = {
    karpenter = {
      ami_type       = "AL2_x86_64"
      instance_types = ["t2.large", "t3.large", "m4.large", "m5.large", "m6i.large"]
      min_size       = 2
      max_size       = 3
      desired_size   = 2
      taints         = {
        addons = {
          key    = "CriticalAddonsOnly"
          value  = "true"
          effect = "NO_SCHEDULE"
        }
      }

      attach_cluster_primary_security_group = true

      subnet_ids = var.network.subnet_ids

      iam_role_permissions_boundary = var.permissions_boundary_arn
      iam_role_additional_policies  = {
        AmazonSSMManagedInstanceCore = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
      }
    }
  }

  iam_role_additional_policies = {
        AmazonSSMManagedInstanceCore = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  }

  tags = merge(local.tags, {
    "karpenter.sh/discovery" = "test-cluster"
  })
}
```

Run code provided

## Expected behavior

Cluster to be be created with 2 nodes

## Actual behavior

Cluster is created but nodes cannot join the cluster

**Comment by Daemoen** [comment]
The above code missing information to reproduce.  What are your variables / config for your vpc ?  You basically say that the 'network stuff is done', but without seeing the whole picture, not sure how people are expected to reproduce without the variables you are supplying.

**Comment by asark67** [comment]
VPC was created by central team and was missing some vpc endpoints ecr_dkr and ecr_api
