### ISSUE TITLE
`pre_bootstrap_user_data` breaking change from 20.8.5 to 20.9.0

### ISSUE THREAD

**Issue by bennesp** [terraform-aws-modules/terraform-aws-eks#3076]
## Description

I am trying to upgrade our clusters from using module version 20.8.5 to the latest.
However, when jumping from v20.8.5 to v20.9.0 a diff is detected by `terraform plan`: terraform wants to set user_data in `module.eks.module.eks_managed_node_group["large_on_demand"].aws_launch_template.this[0]` to null

I tried to search opened and closed issues, and also look at changelog and at code changes, but I cannot understand why this is happening.

I am using:
- managed node groups
- ami_type `AL2023_x86_64_STANDARD`
- I am not specifying any custom AMI
- I am feeding user data using `pre_bootstrap_user_data` containing a custom bash script

## Versions

- Module version [Required]: 20.9.0

- Terraform version:
```
Terraform v1.8.5 on darwin_arm64
```
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v5.55.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.4
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/time v0.11.2
+ provider registry.terraform.io/hashicorp/tls v4.0.5
```

## Reproduction Code [Required]

I am not sure if this is sufficient to reproduce the problem:

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.9.0"

  # ...

  eks_managed_node_groups = {

    "large_on_demand" = {
      ami_type = "AL2023_x86_64_STANDARD"

      # ...

      pre_bootstrap_user_data = <<-EOT
        #!/bin/bash
        EXTRA_CONF='{"imageGCLowThresholdPercent": 50, "imageGCHighThresholdPercent": 70}'
        jq --argjson extra_conf "$EXTRA_CONF" '. + $extra_conf' \
          /etc/kubernetes/kubelet/kubelet-config.json > /tmp/kubelet-config.json
        mv /tmp/kubelet-config.json /etc/kubernetes/kubelet/kubelet-config.json
      EOT

      # ...

    }

  # ...

  }

  # ...
}
```

## Expected behavior

No diff are shown from v20.8.5 to v20.9.0 OR the change is breaking and documentation on how to migrate is present

## Actual behavior

during `terraform plan`, user_data will be changed to be null 

### Terminal Output Screenshot(s)

![Screenshot 2024-06-21 alle 17 28 33](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/5445545/badf62c7-e203-4eac-8b17-4f4216727c55)

**Comment by RodrigoMenezes-Vantage** [comment]
I noticed this today as well while trying to use `v20.14.0` it seems that pre_bootstrap_user_data is being completely ignored on newer versions. To do a test added the following to my node group and can see the command in the base64 decoded user-data in `v20.8.5` but it's completely gone in newer versions. 

```
      enable_bootstrap_user_data = true
      pre_bootstrap_user_data = "echo TEST"
```

**Comment by bryantbiggs** [comment]
AL2023 AMIs do not use shell script user data, nor do they use the `pre_bootstrap_user_data`/`post_bootstrap_user_data` arguments

**Comment by bennesp** [comment]
Thank you @bryantbiggs for answering this.

We were using another `ami_type` in the past that supported the bash script in the user data.
However, as you say, AL2023 does not support them.

Demonstration:
1. `/etc/kubernetes/kubelet/kubelet-config.json` file is empty on nodes
2. `kubectl get --raw "/api/v1/nodes/<node_name>/proxy/configz" | jq` returns the full node configuration with unchanged `imageGCLowThresholdPercent` or `imageGCHighThresholdPercent`

This was indeed a bug in how we used the module, that was somehow "hidden" and now it's explicit.

According to https://docs.aws.amazon.com/linux/al2023/ug/cloud-init.html, it should be possible to customize `AL2023` instances by using an AWS customized version of cloud-init

We will switch to `cloudinit_pre_nodeadm` parameter, as shown in this example: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/7cd3be3fbbb695105a447b37c4653a00b0b51b94/examples/eks-managed-node-group/eks-al2023.tf#L32C7-L47

Thank you

**Comment by RodrigoMenezes-Vantage** [comment]
If anyone else hits this and is trying to inject a script using `pre_bootstrap_user_data` into an AL2023 machine, you should be able to leverage `cloudinit_pre_nodeadm` using multipart instead to accomplish this.

```
      cloudinit_pre_nodeadm = [
          {
            content_type = "text/x-shellscript"
            content      = "<Script Content>"
          }
      ] 
```

**Comment by saintmalik** [comment]
can i set maxpod value with this i am also using al2023 ami, is it possible @RodrigoMenezes-Vantage

**Comment by RodrigoMenezes-Vantage** [comment]
You should be able to do so with NodeConfig like @bennesp configured the kubelet above. But you'll have to lookup the exact syntax
