### ISSUE TITLE
Aws eks addon version result crashes with adot

### ISSUE THREAD

**Issue by miachm** [terraform-aws-modules/terraform-aws-eks#3079]
## Description

When I try to install adot:

````terraform
  cluster_addons = {
    amazon-cloudwatch-observability = {
      most_recent   = true
   }
}
````

Terraform plan crashes:

`│ Error: reading EKS Add-On version info (adot, 1.30): empty result
│ 
│   with module.eks.data.aws_eks_addon_version.this["adot"],
│   on .terraform/modules/eks/main.tf line 490, in data "aws_eks_addon_version" "this":
│  490: data "aws_eks_addon_version" "this" {`

I did a research and it seems like the API call "describe-addon-versions" returns an empty list for the kubernetes cluster 1.30.

I think the program should be able to ignore this problem, or at the bare least, don't execute the datasource if you provide the addon version.

## Versions

- Module version [Required]: `20.14.0`

- Terraform version: 1.8
- Provider version(s): v5.55.0

## Reproduction Code [Required]

````terraform
module "eks" {
  source                         = "terraform-aws-modules/eks/aws"
  version                        = "~> 20.14.0"
  cluster_name                   = "test"
  cluster_version                = "1.30"

  cluster_addons = {
    amazon-cloudwatch-observability = {
      most_recent   = true

    }
}
}
````

 No
 Yes
 It fails in the terraform plan

## Expected behavior

To install the addon like I can do in the UI.

**Comment by bryantbiggs** [comment]
ADOT currently does not support 1.30

**Comment by miachm** [comment]
@bryantbiggs I can install it from the AWS console.

**Comment by bryantbiggs** [comment]
ADOT currently does not support 1.30

**Comment by bryantbiggs** [comment]
closing since this is not related to the module - you will need for the ADOT addon to support 1.30
