### ISSUE TITLE
eks node group: should print a warning when `use_name_prefix` = false

### ISSUE THREAD

**Issue by mhughdo** [terraform-aws-modules/terraform-aws-eks#3086]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑

## Is your request related to a problem? Please describe.

- When the `use_name_prefix` option is set to false, there's no problem when creating the node group for the first time. 
- However, if a node group already exists and there's a change to it, that node group will be re-created (deleted first then created) when running terraform apply which will cause an error: `ResourceInUseException: NodeGroup already exists with name xxx and cluster name yyy`, resulting in some downtime because no node is available.

![18999abccd2bf9830ca33f92d2da0936de7b7f7553e327a9bd84d821595e0d96](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/15611134/3c7a5106-b907-46b8-bbfb-0047e39b8ac7)

## Describe the solution you'd like.

- A warning is printed when `use_name_prefix=false` is used, or at least the document should be updated to give a warning about this.

**Comment by bryantbiggs** [comment]
I don't think that is valid - if users opt out of the default settings and create issues for themselves, we cannot protect them from the various different ways they can cause conflicts
