### ISSUE TITLE
Switch to the AWS CC Provider

### ISSUE THREAD

**Issue by adrianmace** [terraform-aws-modules/terraform-aws-eks#3089]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

N/A

## Is your request related to a problem? Please describe.

I am frustrated when AWS release new features, but there is a [significant delay](https://github.com/hashicorp/terraform-provider-aws/pull/38162) before it is available in the AWS provider. I am further frustrated that these options are often available in near-real-time [via the AWS CC provider](https://github.com/hashicorp/terraform-provider-awscc/blob/main/internal/aws/eks/cluster_resource_gen.go#L116).

## Describe the solution you'd like.

By switching to the AWS CC provider, we get access to all the latest options as soon as they're available.

## Additional context

Not sure how this would go re: migrations.

**Comment by bryantbiggs** [comment]
switching to `awscc` is a breaking change and it still very, very early days for `awscc` - in addition, we will still require the `aws` provider for all of the missing functionality in `awscc`. At this time we do not have any plans to migrate to `awscc`
