### ISSUE TITLE
Support creating a cluster with no default unmanaged add-ons: bootstrap_self_managed_addons=false.

### ISSUE THREAD

**Issue by raonitimo** [terraform-aws-modules/terraform-aws-eks#3093]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality
  - v5.58.0 - https://github.com/hashicorp/terraform-provider-aws/pull/38162

## Is your request related to a problem? Please describe.
I want to use a different CNI (Cilium) and I want to install CoreDNS using my own Helm chart so I can have full control over the config.

## Describe the solution you'd like.
I want to pass `bootstrap_self_managed_addons=false` to the `eks_cluster` resource.

## Describe alternatives you've considered.
At the moment I have a null_resource that removes the provisioned resources after the cluster is created.

## Additional context
I'm happy to raise a PR and implement this.

**Comment by spr-mweber3** [comment]
@bryantbiggs AWS provider 5.58.0 includes the required changes. #3099 seems to already implement that.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.18.0 :tada:
