### ISSUE TITLE
metadata_options not reflecting in nodes when use_custom_launch_template = false

### ISSUE THREAD

**Issue by Imranonline** [terraform-aws-modules/terraform-aws-eks#3095]
Hello,
I am trying to create the cluster using the module but when i am using the metadata option along with use_custom_launch_template = false   it doesnt reflect in the cluster /nodes 

` eks_managed_node_groups = {
    staging_1 = {
      use_custom_launch_template = false
      disk_size = 50
      min_size     = 3
      desired_size = 3
      max_size     = 4
      metadata_options = {
          "http_endpoint": "enabled",
          "http_put_response_hop_limit": 1,
          "http_tokens": "optional"
        }
      subnet_ids = ["subnet-XXX","subnet-XXXX"]

      instance_types = ["c5.4xlarge"]
    }

    }`

**Comment by bryantbiggs** [comment]
This is not supported through the default launch template, you will need to let the module create the custom launch template in order to allow you to set those values (i.e. - ` use_custom_launch_template = true`)

**Comment by Imranonline** [comment]
use_custom_launch_template = true doesnt make me set the disk size. 
I want to use a custom GB disk size but for that i need to make use_custom_launch_template = false as per the documentation

**Comment by bryantbiggs** [comment]
this is not a module issue - this is down to the EKS API 

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/d7aea4ca6b7d5fa08c70bf67fa5e9e5c514d26d2/tests/eks-managed-node-group/main.tf#L235-L248
