### ISSUE TITLE
Improve Karpenter example - Multiple tagged security groups found for instance

### ISSUE THREAD

**Issue by AlissonRS** [terraform-aws-modules/terraform-aws-eks#3096]
The karpenter example adds `karpenter.sh/discovery` to the `tags` variable, which ends up added to all three security groups:

- EKS node shared security group
- EKS cluster security group
- EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads.	
```
module "eks" {

  tags = merge(local.common_tags, {
    # NOTE - if creating multiple security groups with this module, only tag the
    # security group that Karpenter should utilize with the following tag
    # (i.e. - at most, only one security group should have this tag in your account)
    "karpenter.sh/discovery" = var.cluster_name
  })
}
```
This causes Karpenter to attach multiple security groups to its nodes, thus causing Load Balancers to fail syncing:
```
Error syncing load balancer: failed to ensure load balancer: Multiple tagged security groups found for instance i-xxxxxxxxxxxx
```
This took me several hours digging until I found #1986 and understood the issue (wish someone had updated the docs/examples back then).

Instead, it's best if the karpenter example only adds the karpenter tag to `node_security_group_tags`, so only the EKS node shared security group gets the tag.

Some users may prefer attaching the cluster security group to nodes, but since this is not the default behavior of this module, users are then expected to know what they are doing and add the karpenter tag in the right place.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.20.0 :tada:
