### ISSUE TITLE
Error: Unsupported attribute for provider_key_arn when Upgrading to V19 from v18

### ISSUE THREAD

**Issue by aj-kyriba** [terraform-aws-modules/terraform-aws-eks#3101]
## Description

Hello Team
I am trying to upgrade to EKS V19 from V18. However I have this error when using the new version for a existing cluster that have Secrets encryption=off.
So I set the value `create_kms_key=false `

And I get the error 

```
Error: Unsupported attribute
on .terraform/modules/eks.eks/main.tf line 67, in resource "aws_eks_cluster" "this":
        key_arn = var.create_kms_key ? module.kms.key_arn : encryption_config.value.provider_key_arn
encryption_config.value is object with 1 attribute "resources"
This object does not have an attribute named "provider_key_arn".
```

Since the Secrets encryption is OFF, there is no provider_key_arn associated to this eks cluster. 
So how can I handle this case where I need to set `create_kms_key=false ` 

- [X ] ✋ I have searched the open/closed issues and my issue is not listed.

- Module version [Required]:V19.21.0

- Terraform version: 1.7.4

- Provider version(s): 
- aws = ">= 3.72.0"

## Reproduction Code [Required]

Set create_kms_key=false when invoking the module

## Expected behavior
TF Plan run successfully 

## Actual behavior
```
Error: Unsupported attribute
on .terraform/modules/eks.eks/main.tf line 67, in resource "aws_eks_cluster" "this":
        key_arn = var.create_kms_key ? module.kms.key_arn : encryption_config.value.provider_key_arn
encryption_config.value is object with 1 attribute "resources"
This object does not have an attribute named "provider_key_arn".
```

**Comment by assiakhateeb** [comment]
+1 
facing same issue

**Comment by aj-kyriba** [comment]
hi team, any idea how this can be fixed ?

**Comment by bryantbiggs** [comment]
you haven't provided the required details on the issue - you just show an error message. how would you like us to troubleshoot without any details?

**Comment by aj-kyriba** [comment]
hi @bryantbiggs 
Please let me know what details you would like to have? 
For the issues, when trying to upgrade to V19 for a cluster that have currently Secrets encryption is OFF, there is no provider_key_arn associated to this eks cluster. So how can I handle this case where I need to set create_kms_key=false

**Comment by cloudchristina** [comment]
I am facing the same issue.

I am using the module, but then `tf plan` already pop up the errors `│ Error: Unsupported attribute
│ 
│   on .terraform/modules/ebs_csi_driver_irsa/modules/iam-role-for-service-accounts-eks/main.tf line 52, in data "aws_iam_policy_document" "this":
│   52:         variable = "${replace(statement.value.provider_arn, "/^(.*provider/)/", "")}:sub"
│     ├────────────────
│     │ statement.value is object with 2 attributes
│ 
│ This object does not have an attribute named "provider_arn".`
<img width="733" alt="Screenshot 2024-07-31 at 10 02 30 PM" src="https://github.com/user-attachments/assets/67ec8470-6f2b-481a-89d3-1a44ddd3ca72">
<img width="1020" alt="Screenshot 2024-07-31 at 10 03 03 PM" src="https://github.com/user-attachments/assets/9baf17f2-3744-44e9-b509-95066b1bdf3e">

**Comment by rupertgti** [comment]
I have the same issue and fixed it with this solution https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2989#issuecomment-2020573918
