### ISSUE TITLE
Add flexibility to choose cloudwatch event rule name

### ISSUE THREAD

**Issue by paliwalvimal** [terraform-aws-modules/terraform-aws-eks#3103]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality - **feature request is not provider specific**

## Is your request related to a problem? Please describe.

we have a flag to decide whether to use `name` param or `name_prefix` for all the resources except cloudwatch event rule resource. i feel we should provide the same flexibility for this resource too.

the reason behind the ask is that we have our own prefix that we apply for all the resources and because of that we are receiving error message saying rule name should be less than 64 characters.

## Describe the solution you'd like.

introduce a new var `event_rule_use_name_prefix`
```hcl
name          = var.event_rule_use_name_prefix ? null : "${var.rule_name}-${each.value.name}"
name_prefix   = var.event_rule_use_name_prefix ? "${var.rule_name}-${each.value.name}-" : null
```

## Additional context

happy to create a pr for the above request

**Comment by bryantbiggs** [comment]
hello, and thank you for the issue! I don't believe it makes sense to make this type of change as that only gives users a new ways to cause naming conflicts. instead, I would look at shortening the value used for `rule_name_prefix`
