### ISSUE TITLE
EKS cluster module doesn't create a cluster access entry for SSO users

### ISSUE THREAD

**Issue by marcleblanc2** [terraform-aws-modules/terraform-aws-eks#3105]
## Description

This section doesn't create an access entry for AWS SSO authenticated users, it'd be awesome if it could :) 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/705eb80cfacf563f74f760261c2154d2fd9f1d87/main.tf#L149-L163

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 20.20
- Terraform version: v1.9.2
- Provider version(s): 
provider registry.terraform.io/hashicorp/aws v5.59.0

## Reproduction Code [Required]
https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/ipv6-eks-cluster

 No
 No

1. Log in to aws cli as SSO user
2. Deploy EKS cluster
3. kubectl get nodes

## Expected behavior

Get a list of nodes

## Actual behavior

error: You must be logged in to the server (Unauthorized)

**Comment by bryantbiggs** [comment]
this looks like you are having people, not automation, create clusters - is that correct?

**Comment by CVanF5** [comment]
Not OP, but yes in our case we have both automation and SSO users creating clusters

**Comment by bryantbiggs** [comment]
if using SSO, then I would suggest mapping the SSO role via a cluster access entry that you define in your cluster definition

**Comment by bryantbiggs** [comment]
we won't be able to infer if an SSO user is creating the cluster and then mapping that to the appropriate details - instead, users should create an access entry for that role
