### ISSUE TITLE
Can't pass tags to EC2 instance from eks managed node group

### ISSUE THREAD

**Issue by ricardsantacreu** [terraform-aws-modules/terraform-aws-eks#3109]
## Description

I'm trying to set tags for EC2 instances launched by EKS managed nodegroup, I can see tags on EKS, managed nodegroups, but tags does not appear on EC2 instances

- ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 20.13.1

- Terraform version: 1.9.3
- Provider version(s):

hashicorp/aws v5.40.0
hashicorp/cloudinit v2.3.4
hashicorp/helm v2.11.0
hashicorp/http v3.4.0
hashicorp/time v0.9.1
hashicorp/null v3.2.2
hashicorp/kubernetes v2.23.0
hashicorp/tls v4.0.5
hashicorp/dns v3.3.2

## Reproduction Code [Required]

```
eks_managed_node_groups = {
    "node_group" = {
      min_size     = 1
      max_size     = 3
      desired_size = 3

      ami_type = "AL2_x86_64"
      use_latest_ami_release_version = true

      instance_types = var.instance_types

      use_custom_launch_template = false

      launch_template_tags = {
        "tag1"    = "test1"
        "tag2"    = "test2"
        "tag3"    = "test3"
        "propagate_at_launch"   = true

      }

      tags = {
        "tag1"    = "test1"
        "tag2"    = "test2"
        "tag3"    = "test3"
        "propagate_at_launch"   = true
      }
    }
  }
```

## Expected behavior

Tags should appear on the EC2 instance

## Actual behavior

Tags are not showing it on EC2 instance

**Comment by bryantbiggs** [comment]
> use_custom_launch_template = false

This is your issue - you need to use the custom launch template which is the default behavior of this module
