### ISSUE TITLE
Add upgrade_policy config block for aws_eks_cluster

### ISSUE THREAD

**Issue by dawidmalina** [terraform-aws-modules/terraform-aws-eks#3110]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.61.0

## Describe the solution you'd like.
Add upgrade_policy config block for aws_eks_cluster that would allow us to set the version policy for both new and existing clusters.

`STANDARD` - Your EKS cluster eligible for automatic upgrade at the end of standard support. You will not incur extended support charges with this setting but you EKS cluster will automatically upgrade to the next supported Kubernetes version in standard support.

`EXTENDED` - Your EKS cluster will enter into extended support once the Kubernetes version reaches end of standard support. You will incur extended support charges with this setting. You can upgrade your cluster to a standard supported Kubernetes version to stop incurring extended support charges. Clusters running on extended support will be eligible for automatic upgrade at the end of extended support.

## Additional context
https://docs.aws.amazon.com/eks/latest/userguide/view-upgrade-policy.html

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.21.0 :tada:
