### ISSUE TITLE
Add depends_on for the 'resource "aws_eks_addon" "before_compute"'

### ISSUE THREAD

**Issue by ChauAnhTuan** [terraform-aws-modules/terraform-aws-eks#3114]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
In some use cases, the vpc-cni cannot be completed before adding the node to the cluster. So many node groups cannot set the pod limit to 110.

## Describe the solution you'd like.
Please add depends_on for the "self_managed_node_group" module

**Comment by bryantbiggs** [comment]
we already have this supported today https://github.com/terraform-aws-modules/terraform-aws-eks/blob/5fe865e860c4cc8506c639f2e63bc25e21a31b37/main.tf#L527-L531
