### ISSUE TITLE
Add gitlab ci for module creation

### ISSUE THREAD

**Issue by brackend** [terraform-aws-modules/terraform-aws-eks#3124]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider

## Is your request related to a problem? Please describe.
Gitlab can mirror public repos.  Gitlab has a build in template for scanning and creating terraform module in registry format with the same project.  Users can then "source" the module and "version" in parent code.
The problem is, adding a ci template file breaks the mirror.

## Describe the solution you'd like.
would it be possible to add .gitlab-ci.yml.  See content below.  
This would automatically scan and generate a terraform module in gitlab.  
The template is built into gitlab.

## Describe alternatives you've considered.
Not aware of any.  Adding a .gitlab-ci.yml to a mirrored repo will break the mirror on gitlab.  Not sure if there is another way of running a pipeline for the project to create the terraform module without adding a ci file directly to the branch.

## Additional context
`
include:
  - template: Terraform/Module-Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Module-Base.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml          # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.gitlab-ci.yml

stages:
  - validate
  - build
  - test
  - deploy

fmt:
  extends: .terraform-module:fmt

# See the included job template at `Terraform/Module-Base.gitlab-ci.yml` to learn about supported variables.
deploy:
  extends: .terraform-module:deploy
  rules:
    - if: $CI_COMMIT_TAG

`

**Comment by bryantbiggs** [comment]
I don't believe those are valid here - those would be provided in your repository when you create your cluster definition using this module
