### ISSUE TITLE
Use aws_vpc_security_group_egress_rule and aws_vpc_security_group_ingress_rule instead of aws_security_group_rule

### ISSUE THREAD

**Issue by OscarPoels** [terraform-aws-modules/terraform-aws-eks#3125]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: `4.56.0`

## Is your request related to a problem? Please describe.
Security group rules can lead to some problems, by letting you import non existing ones for example,
The [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_egress_rule) says : 
```They struggle with managing multiple CIDR blocks, and tags and descriptions due to the historical lack of unique IDs```

## Describe the solution you'd like.
Use aws_vpc_security_group_egress_rule and aws_vpc_security_group_ingress_rule instead of aws_security_group_rule as recommended in the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_egress_rule)
```Using aws_vpc_security_group_egress_rule and [aws_vpc_security_group_ingress_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_ingress_rule) resources is the current best practice.```

## Additional context
I can contribute and provide a MR if needed

**Comment by bryantbiggs** [comment]
Thank you but this change is unnecessary at this time
