### ISSUE TITLE
[karpenter] enable ability to import existing eventbridge rules

### ISSUE THREAD

**Issue by k24dizzle** [terraform-aws-modules/terraform-aws-eks#3127]
Since there isn't a way to specify the name of these [rules](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1604c6cdc8cedcd47b7357c5068dc11d0ed1d7e5/modules/karpenter/main.tf#L579-L590):

```
resource "aws_cloudwatch_event_rule" "this" {
  for_each = { for k, v in local.events : k => v if local.enable_spot_termination }

  name_prefix   = "${var.rule_name_prefix}${each.value.name}-"
  description   = each.value.description
  event_pattern = jsonencode(each.value.event_pattern)

  tags = merge(
    { "ClusterName" : var.cluster_name },
    var.tags,
  )
}

``` 

(only the `name_prefix`), it isn't easy to import these rules.

<img width="827" alt="Screenshot 2024-08-16 at 1 55 42 PM" src="https://github.com/user-attachments/assets/2772ad68-b4e9-43af-8efa-6f994c699b0f">

Is it ok having multiple duplicate eventbridge rules that route to the karpenter sqs interruption queue? Will karpenter be able to deduplicate them?

**Comment by bryantbiggs** [comment]
Are those for the same cluster or different clusters? Why so many copies of rules?

**Comment by k24dizzle** [comment]
> Are those for the same cluster or different clusters? Why so many copies of rules?

same cluster, I kept deleting my terraform state file so that's why it continued to make copies

**Comment by bryantbiggs** [comment]
I would just delete all of the rules manually and re-apply and that should leave just one set of the rules

**Comment by bryantbiggs** [comment]
closing since this isn't a module relate issue
