### ISSUE TITLE
Timeout issue using cluster_endpoint output to create kubernetes objects

### ISSUE THREAD

**Issue by johnraber** [terraform-aws-modules/terraform-aws-eks#313]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Attempting to use this module's outputs (cluster_endpoint, cluster_token, and cluster_ca_certificate)  to populate the standard kubernetes provider which another module depends. This dependent module calls the API server (cluster_endpoint) to create kubernetes objects.  It appears the API server endpoint/url is returned before the API can receive creation requests.

1 error(s) occurred:

kubernetes_service_account.nginx: Post https://redacted-api-server.sk1.us-west-2.eks.amazonaws.com/api/v1/namespaces/default/serviceaccounts: dial tcp redacted-ip: i/o timeout

If I rerun terraform apply after waiting a minute, the service account is successfully created.  This behavior is very consistent.  This leads me to believe it is a timing issue.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```

provider "aws" {
  version    = ">= 2.0.0"
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"

  region = "${var.aws_region}"
}


provider "kubernetes" {
  host                   = "${module.cluster_endpoint}"
  cluster_ca_certificate = "${base64decode(module.cluster_ca_certificate)}"
  token                  = "${module.cluster_token}"
  load_config_file       = false
}

module "cluster" {
  source           = "terraform-aws-modules/eks/aws"
  cluster_name     = "ralph"
  cluster_version  = "1.11"
  subnets          = ["${module.vpc.public_subnets}", "${module.vpc.private_subnets}"]
  vpc_id           = "${module.vpc.vpc_id}"
  manage_aws_auth  = true

  cluster_create_security_group = true
  cluster_create_timeout        = "15m"
  cluster_delete_timeout        = "15m"

  worker_groups = [
    {
      instance_type        = "${var.node_instance_type}"
      asg_min_size         = "${var.min_size}"
      asg_max_size         = "${var.max_size}"
      asg_desired_capacity = "${var.desired_capacity}"
      autoscaling_enabled  = true
    }
  ]

  tags = {
    environment = "${var.environment}"
  }
}

# this module creates service account resource
module "nginx" {
  source = "../mod-nginx-ingress"
 
    providers = {
      kubernetes = "kubernetes"
      aws = "aws"
  }
}

## nginx module main.tf snippet
resource "kubernetes_service_account" "nginx" {
  metadata {
    name      = "ingress-nginx"
    namespace = "default"
  }
}
```

## What's the expected behavior?
The expected behavior is that the API server endpoint (output 'cluster_endpoint')  from this module is usable straight away.

## Environment details

* Affected module version:
* OS:  
* Terraform version:
    Terraform v0.11.11
      + provider.aws v2.3.0

**Comment by max-rocket-internet** [comment]
Hey @johnraber 
This is not an issue that we can solve in this module, this is a general Terraform issue.

The problem is that there is no `depends_on` option for providers. In your code example, the `kubernetes` provider depends on the cluster module. For example, I've had the same problem with the `postgresql` provider that depends on an AWS RDS instance.

You should follow this issue here: https://github.com/hashicorp/terraform/issues/2430

Hope that helps!

**Comment by johnraber** [comment]
Thanks @max-rocket-internet ......  this info does indeed help from a verification perspective.  Greatly appreciate the link and all the work you all do.

**Comment by llibicpep** [comment]
FYI this is little beyond `depends_on` for providers. I'm using terragrunt and have a sequence of modules, my first module creates EKS cluster and second module using `eks_cluster` data resource to discover that cluster and throwing in K8s objects. Second module kicks off only after the first one completely finishes i.e. `eks_cluster` resource fully ready, which essentially almost like `depends_on` for the entire module and even longer than that as some time goes into second module `init` and refresh/plan. Yet I encounter same `i/o timeout` error. It is just fyi, this is indeed have nothing to do with this module - sounds like `eks_cluster` resource bug.

**Comment by max-rocket-internet** [comment]
@llibicpep you can see the discussion in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/621 about the specifics of this problem.

**Comment by ngortheone** [comment]
I have the same problem
