### ISSUE TITLE
Support conditional instance refreshing configuration

### ISSUE THREAD

**Issue by ramseymcgrathfd** [terraform-aws-modules/terraform-aws-eks#3133]
## Is your request related to a problem? Please describe.
Currently its not possible to enable and disable instance refreshes in same self-managed node group module call. The module can either have refreshes enabled or disabled but it's not configurable.

## Describe the solution you'd like.
A user should be able to pass in {} for the instance refresh argument to disable refreshes in that particular module call.

## Describe alternatives you've considered.
Dynamic arguments: cannot be used in a module definition
Passing in null for the configuration: there is a length() check on the argument that blocks this
Passing in {} in the current configuration: a true/false error will be thrown because true and false are not the same values.

**Comment by bryantbiggs** [comment]
> Currently its not possible to enable and disable instance refreshes in same self-managed node group module call. The module can either have refreshes enabled or disabled but it's not configurable.

This is simply not true - it is configurable. We won't be able to take this further without a reproduction

**Comment by ramseymcgrathfd** [comment]
Its easy to recreate. We want a conditional in the module call, but you can't do it without my pr or replacing the length() check with something else. 

Setting a conditional between instance_refresh{} and {} will fail due to the inconsistent return type:

```
 Error: Inconsistent conditional result types
 
   on main.tf line 184, in module "self_managed_node_group":
  184:   instance_refresh = var.instance_refresh ? {
  185:     preferences = {
  186:         min_healthy_percentage = var.instance_maintenance_policy.min_healthy_percentage
  187:       }
  188:       strategy = "Rolling"
  189:     } : {}
     ├────────────────
     │ var.instance_maintenance_policy.min_healthy_percentage is a number
     │ var.instance_refresh is a bool
 
 The true and false result expressions must have consistent types. The 'true' value includes object attribute "preferences", which is absent in the 'false'
 value.
 ```
 
 You can use null for the return types to pass but that will fail the length check
 
 ```
 Error: Invalid function argument

   on .terraform/modules/spot_self_managed_node_groups.self_managed_node_group/modules/self-managed-node-group/main.tf line 530, in resource "aws_autoscaling_group" "this":
  530:     for_each = length(var.instance_refresh) > 0 ? [var.instance_refresh] : []
     ├────────────────
     │ while calling length(value)
     │ var.instance_refresh is null

 Invalid value for "value" parameter: argument must not be null.
```

My PR to check for the {} case should resolve this fine

**Comment by bryantbiggs** [comment]
I don't know if its easy to recreate because I would simply argue - don't write Terraform like that. This is requesting a module level change because of less than ideal practices in terms of Terraform usage (it also looks like this is because you are re-wrapping this module which is yet another layer of - why?) 

regardless - you can resolve this on your end without any changes here if you want to continue on your current path/approach:

```hcl
instance_refresh =  { for k,v in {
  preferences = {
    min_healthy_percentage = var.instance_maintenance_policy.min_healthy_percentage
  }
  strategy = "Rolling"
}: k => v if var.instance_refresh }
  ```
  
  (Might need to double check/tweak - I don't have anything up at the moment to verify but thats the gist of it)

**Comment by ramseymcgrathfd** [comment]
We rewrap and call the node group modules separately from control-plane module for some more complex deployments. That syntax is hacky but works so it'll close the issue. Practice-wise every other argument in the module safely handles a null or {} input so it's hardly a ground breaking change to align it. Either way thanks
