### ISSUE TITLE
OIDC URL alternatives to use on `aws_eks_identity_provider_config` for IRSA

### ISSUE THREAD

**Issue by igorbrites** [terraform-aws-modules/terraform-aws-eks#3135]
## Is your request related to a problem? Please describe.

As of [v20.13.0](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3055) and [Kubernetes v1.30](https://github.com/kubernetes/kubernetes/pull/123561), we can't use the same URL for the cluster OIDC identity provider and the Service Account issuer. According to [this answer on AWS re:Post](https://repost.aws/questions/QUM2Zyd5KsT4yKV1qheHKaeQ/eks-upgrade-from-1-29-to-1-30#ANg7mPzc6sT7mu9sqxl_iYrQ), if we bypass the lock created by @bryantbiggs on the module and create the `aws_eks_identity_provider_config` after the cluster creation/upgrade using the same URL, the API server will crash.

So, what is the alternative to keep using IRSA? Which URL do we need to pass to the  `aws_eks_identity_provider_config`, as using the cluster's one is incorrect? Or did I miss something?

## Describe the solution you'd like.
A doc or variable description explaining the change and which are the alternatives.

## Describe alternatives you've considered.
None so far, we postponed the clusters upgrade to 1.30 until we have a better understanding of this.

## Additional context

![help](https://y.yarn.co/bb32d2fb-1709-44c8-93e7-9250f36ae8d5_text.gif)

**Comment by bryantbiggs** [comment]
you don't need to create a custom identity provider to use IRSA - IRSA already trusts the cluster 

[EKS identity providers](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c60b70fbc80606eb4ed8cf47063ac6ed0d8dd435/main.tf#L560-L590) are for mapping external identity providers such as Okta, Ping Identity, Auth0, etc. to establish trust for machine-to-machine type authentication. If you use an external identity provider for your users and you want to provide them access to the cluster using that identity provider - you would use an EKS identity provider; this is not for IRSA

When using IRSA with this module, the trust is already setup with the EKS cluster https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c60b70fbc80606eb4ed8cf47063ac6ed0d8dd435/main.tf#L357 - theres nothing further for users to do in terms of using IRSA when `enable_irsa = true`

**Comment by igorbrites** [comment]
Oh ok, I got it! So right now I'm using the `cluster_identity_providers` var to create a STS client. You're saying that I can simply remove it, and the IRSA will keep working?

This is what I have:

```hcl
  cluster_identity_providers = {
    sts = {
      client_id = "sts.amazonaws.com"
    }
  }
```

If I understood correctly, can I delete these lines and profit?

**Comment by bryantbiggs** [comment]
that is correct!

**Comment by igorbrites** [comment]
Awesome! Thanks for the clarification @bryantbiggs!
