### ISSUE TITLE
Support using Cilium as a CNI

### ISSUE THREAD

**Issue by marcofranssen** [terraform-aws-modules/terraform-aws-eks#3139]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

When trying to bootstrap a new cluster without EKS managed addons (so we can use cilium CNI) we end up with a Chicken vs Egg problem.

When the cluster is created, the EKS managed nodes will forever be stuck in a Not Ready state. This means the next steps will never happen from a terraform perspective until it times out.

## Describe the solution you'd like.

It would be great if we have an option to install cilium before the EKS managed nodes are being provisioned.

## Describe alternatives you've considered.

Not using the module, but using the AWS provider resources directly (recreating this module with out own custom needs).

## Additional context

When provisioning the cluster we start with EKS managed nodegroups to run core components like Karpenter. All the other nodes we manage via Karpenter. However for these initial EKS managed nodes to be `Ready` they need a CNI at the moment for the Terraform to continue. On a existing cluster we can easily install cilium, update node taints, remove the `aws-node` DaemonSet etc. But that isn't great to provision a new cluster.

**Comment by bryantbiggs** [comment]
we don't intend on having any providers that access inside the cluster within this module (i.e - the Helm/Kubernetes/kubeclt providers) - that is a very problematic approach
