### ISSUE TITLE
Module assigning incorrect security groups

### ISSUE THREAD

**Issue by andrewbcoyle** [terraform-aws-modules/terraform-aws-eks#3140]
## Description

When provisioning a fresh EKS cluster w module v20.24, the security groups that are created and assigned to the cluster are incorrect.  TF assigns the "cluster" sg as the "node" sg, and the node sg isn't assigned.  The cluster sg that gets assigned is a different sg that appears to be using default settings.

I have named the sg's according to their role ("EKS node security group") and output the results for both sg's.  

After creation TF returns:
```
cluster-security-group = "sg-03f2460cef7842784"
node-security-group = "sg-0dc39183da4477e98"
```

However when I look in the console, I see "sg-03f2460cef7842784" is the node sg, "sg-0dc39183da4477e98" is created and named correctly as the node security group but isn't assigned to anything, and the cluster sg displayed in the console is "sg-0d6cda72afcca7336" and named "eks-cluster-sg-nameofmycluster-196899026"

- [ * ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 20.24

- Terraform version:
Terraform v1.9.5
on darwin_arm64
- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v5.64.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.4
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/time v0.12.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]

```yaml
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 20.24"

  cluster_name        = local.platform_name
  cluster_version     = var.kubernetes_ver
  authentication_mode = "API"

  vpc_id = data.aws_vpc.network.id
  subnet_ids = flatten([
    data.aws_subnets.private.ids,
    data.aws_subnets.public.ids
  ])
  cluster_endpoint_public_access = true
  cluster_security_group_name    = "EKS Cluster Security Group"
  node_security_group_name       = "EKS Node Security Group"

  enable_cluster_creator_admin_permissions = true

  cloudwatch_log_group_retention_in_days = 90
  cluster_enabled_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler"
  ]

  fargate_profiles = {
    # kube-system Fargate profile must be set here so coreDNS comes up correctly.
    kube-system = {
      name       = "kube-system"
      selectors  = [{ namespace = "kube-system" }]
      subnet_ids = data.aws_subnets.private.ids
      tags       = { "utexas:application" = "kube-system" }
    }
  }
  fargate_profile_defaults = {
    iam_role_additional_policies = {
      additional = aws_iam_policy.fargate_logging.arn
    }
  }
}

output "cluster-security-group" {
  value = module.eks.cluster_security_group_id
}

output "node-security-group" {
  value = module.eks.node_security_group_id
}
```
([eks_tf.zip](https://github.com/user-attachments/files/16768312/eks_tf.zip))

1) provision a new EKS cluster w module v20.24
2) (optional) specify names for `cluster_security_group_name` and `node_security_group_name` and add them to `outputs`
```
output "cluster-security-group" {
  value = module.eks.cluster_security_group_id
}

output "node-security-group" {
  value = module.eks.node_security_group_id
}
```
3) Go into AWS console and inspect what SGs actually got assigned.  Observe Cluster sg is default, node sg is actually the cluster sg, and the actual node sg is created correctly (with expected rules) and not assigned.

## Expected behavior

Module should correctly provision and assign sg's

## Actual behavior

1) Default Cluster SG is created with default settings and assigned to cluster
2) The specified Cluster SG is created and assigned as the node SG
3) The specified Node SG is created and not assigned to cluster at all.

### Terminal Output Screenshot(s)
TF output (which shows the correct sg id's)
<img width="379" alt="Screenshot 2024-08-27 at 3 06 15 PM" src="https://github.com/user-attachments/assets/9f775a86-6f51-4d8b-a410-69c0c19ac6c1">
Console output which shows cluster sg as the node sg, and a new sg as the cluster sg.
<img width="240" alt="Screenshot 2024-08-27 at 3 06 58 PM" src="https://github.com/user-attachments/assets/a95f1131-f1bf-4e0f-bfe4-7ee105e3a77f">

**Comment by andrewbcoyle** [comment]
I'll also add that for the Node SG that gets created, the SG it allows traffic from is the *correct* Cluster SG, not the SG that actually gets created and assigned as the Cluster SG.

**Comment by bryantbiggs** [comment]
this is just how EKS Fargate operates - you don't have the option to change/specify the security groups used by Fargate profiles; the cluster created security group is automatically used

Ref: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c60b70fbc80606eb4ed8cf47063ac6ed0d8dd435/tests/fargate-profile/main.tf#L47-L49

**Comment by andrewbcoyle** [comment]
Ok I apologize I must be confused then.  The groups that get created don't have the needed ports open.  The node group that gets created (but not assigned) has all the "recommended rules" I need for the control plane to communicate with pods (like 10250).

How do I "node_security_group_enable_recommended_rules" on this SG?

**Comment by andrewbcoyle** [comment]
Ok disregard this.  I had one of my open tickets resolved by AWS and the issue I was experiencing was actually tied to that (Port 10250 cant be used w Fargate).  I think I just confused myself here.  Thanks for the assistance and all the work you put into this module!
