### ISSUE TITLE
Instance maintenance policy for eks managed node groups

### ISSUE THREAD

**Issue by schealex** [terraform-aws-modules/terraform-aws-eks#3144]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider

## Is your request related to a problem? Please describe.

Why was the change #2830 only added to self managed node groups? We are using eks managed node groups and would like to have the option aswell

**Comment by bryantbiggs** [comment]
Does EKS managed node groups support this?

**Comment by bryantbiggs** [comment]
closing for now - once this functionality is supported by EKS managed node groups then we can support it here as well

**Comment by schealex** [comment]
sorry for the late response, as far as i can tell EKS managed node groups support this. We can manually adjust the settings via AWS 

![image](https://github.com/user-attachments/assets/50818402-e1a6-4615-bad4-8bcdaa7fb6ff)

but are unable to set those via the module
