### ISSUE TITLE
Impact of the CloudWatch "enabled_metrics "

### ISSUE THREAD

**Issue by devops-inthe-east** [terraform-aws-modules/terraform-aws-eks#3156]
## Description

I wanted to clarify when the configuration enabled for self managed worker nodes:

'''
enabled_metrics  : ["GroupMinSize", "GroupMaxSize", "GroupDesiredCapacity", "GroupInServiceInstances"] 

'''

Does it create a CloudWatch Agent on the worker node to track these metrics.

**Comment by bryantbiggs** [comment]
No
