### ISSUE TITLE
User Data Output

### ISSUE THREAD

**Issue by derek-howard** [terraform-aws-modules/terraform-aws-eks#3159]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
Currently if you use the EKS module, and have the `eks-managed-node-group` module inside of it, you cannot utilize the `user_data` output by the `_user_data` module

## Describe the solution you'd like.
I would like to reach the user data provided by the user data module inside the `eks-managed-node-group` module.

## Describe alternatives you've considered.
I am currently pulling the user_data out of the module manually and placing it where it needs to go outside of terraform, versus just grabbing an output.

**Comment by bryantbiggs** [comment]
what are you trying to do and why?

**Comment by derek-howard** [comment]
I am deploying a karpenter app template into ArgoCD, and it appears it is missing some necessary user_data for it to connect to the EKS cluster (using Bottlerocket). So I just want to be able to pull that information directly out of the module and drop it into my karpenter app template.

**Comment by bryantbiggs** [comment]
hmmm, that sounds suspect. if you are using Karpenter, you shouldn't need to take the user data from this project for the nodes created by Karpenter

**Comment by derek-howard** [comment]
> hmmm, that sounds suspect. if you are using Karpenter, you shouldn't need to take the user data from this project for the nodes created by Karpenter

I will dig into this more on my side then. I guess something small is missing and I just need to find it. Will close this issue unless something comes up where this is needed again.
