### ISSUE TITLE
Change default value for `irsa_namespace_service_accounts` to reflect changes from v0.33

### ISSUE THREAD

**Issue by gaelayo** [terraform-aws-modules/terraform-aws-eks#3161]
## Description

Since `v0.33`, karpenter recommends to stop using the `karpenter` namespace and deploy karpenter inside the `kube-system` instead. 
This change has been reflected during the introduction of #3031 , but was not applied to the value `irsa_namespace_service_accounts`, which is still `["karpenter:karpenter"]` by default, when I think it should be switched to `["kube-system:karpenter"]`.

**Comment by bryantbiggs** [comment]
that would be a breaking change and one we would need to consider in the next major release
