### ISSUE TITLE
`inline_policy` argument is deprecated in `aws_iam_role`

### ISSUE THREAD

**Issue by jmgalvez** [terraform-aws-modules/terraform-aws-eks#3162]
## Description

Just to report a deprecated issue. With the new version of the Terraform AWS Provider 5.68.0 (https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.68.0) there is a **deprecated** warning to use _aws_iam_role_policies_exclusive or aws_iam_role_policy_ instead of _inline_policy_

```
NOTES:

- resource/aws_iam_role: The inline_policy argument is deprecated. Use the aws_iam_role_policy resource instead. If Terraform should exclusively manage all inline policy associations (the current behavior of this argument), use the aws_iam_role_policies_exclusive resource as well. (https://github.com/hashicorp/terraform-provider-aws/issues/39203)
```

With the previous versions of the AWS Provider <= v5.67.0 there is no such warning.

## Versions

- Module version: **20.24.1**

- Terraform version: **1.9.6**
- Provider version(s): **AWS Provider v5.68.0**

## Reproduction Code

Terraform init
Terraform plan

## Expected behavior

No warnings.

## Actual behavior

```
│ Warning: Argument is deprecated
│
│   with module.eks.aws_iam_role.this[0],
│   on .terraform/modules/eks/main.tf line 402, in resource "aws_iam_role" "this":
│  402: resource "aws_iam_role" "this" {
│
│ Use the aws_iam_role_policy resource instead. If Terraform should exclusively manage all inline policy associations (the current behavior of this argument), use the aws_iam_role_policies_exclusive resource as well.
╵
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.24.2 :tada:
