### ISSUE TITLE
Add support to provision EKS 1.31 cluster

### ISSUE THREAD

**Issue by varunm17** [terraform-aws-modules/terraform-aws-eks#3164]
## Is your request related to a new offering from AWS?
* Yes, AWS recently added support for EKS 1.31

## Is your request related to a problem? Please describe.
* Creating EKS 1.31 cluster is giving below error:
```operation error EKS: CreateCluster, https response error StatusCode: 400, RequestID: XXX-XXX-XXX-XXX-XXX, InvalidParameterException: unsupported Kubernetes version 1.31```

## Describe the solution you'd like.
* Provisioning EKS 1.31 cluster shoudl be supported

## Describe alternatives you've considered.
* None

## Additional context
* NA

**Comment by bryantbiggs** [comment]
When EKS supports 1.31 then it will work
