### ISSUE TITLE
Replace the `enable-docker-bridge` parameter with a generic one

### ISSUE THREAD

**Issue by RothAndrew** [terraform-aws-modules/terraform-aws-eks#317]
# I have issues

per @max-rocket-internet's comment [here](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/310#issuecomment-475629728) in #310 :

> Maybe we just replace the enable-docker-bridge parameter with just a general parameter like bootstrap_extra_args that defaults to "". This is safer for AMI changes, will solve this issue and means people can change the docker bridge setting also.

Note: This would be a breaking change which would mean a major version bump.

## I'm submitting a...

* [ ] bug report
* [X] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Older AMI's don't work since they don't have the new `--enable-docker-bridge` flag, but this module adds it with a `true` or `false`. Changing it to a generic parameter like `bootstrap_extra_args` will eliminate that issue and add future proofing for other similar stuff that may come up in the future.

## Are you able to fix this problem and submit a PR? Link here if you have already.

I am capable of doing a PR. I don't have the time right now, but if this sits untouched for long enough I will eventually come along to do it.

Fixes #310

**Comment by max-rocket-internet** [comment]
Maybe @michaelmccord can make the PR 😃

**Comment by michaelmccord** [comment]
@max-rocket-internet -- I'll try and make some time to get around to this.

**Comment by max-rocket-internet** [comment]
I made a PR: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/320

@RothAndrew could you test it perhaps??

**Comment by RothAndrew** [comment]
I will give it a shot :)

**Comment by RothAndrew** [comment]
Testing this now, about 20 days late, sorry :)

**Comment by max-rocket-internet** [comment]
This was resolved with the PR above.
