### ISSUE TITLE
Avoiding drift with cluster_addons.most_recent

### ISSUE THREAD

**Issue by BeyondEvil** [terraform-aws-modules/terraform-aws-eks#3173]
Not a bug per se, but since `Discussions` isn't activated for this repository, I'll ask the question here. 🙇 

We have:

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.24.0"
  ...

  cluster_addons = {
    coredns = {
      most_recent = true
    }
    kube-proxy = {
      most_recent = true
    }
    vpc-cni = {
      most_recent = true
    }
  }
  ...
```

And `most_recent` is causing state drift.

Since we can't use lifecycle.ignore_changes on modules, is there another way (apart from hardcoding a version) to solve it?

**Comment by bryantbiggs** [comment]
closing as answered
