### ISSUE TITLE
bootstrap_extra_args (bottlerocket) ignored if use_custom_launch_template=false

### ISSUE THREAD

**Issue by kr4sv** [terraform-aws-modules/terraform-aws-eks#3175]
When `use_custom_launch_template` is set to `false` on a managed node group, `bootstrap_extra_args` are no longer appended to the bottlerocket user_data.

#    bootstrap_extra_args not appended
    managed-ondemand-nvidia = {
      use_custom_launch_template = false
      instance_types             = var.gpu_types
      ami_type                   = "BOTTLEROCKET_x86_64_NVIDIA"
      disk_size                  = var.mng_disk_size
      subnet_ids                 = [module.vpc.private_subnets[0]]
      bootstrap_extra_args       = <<-EOT
        [kubelet-device-plugin.nvidia]
        device-list-strategy = "envvar"
      EOT
      }

#    bootstrap_extra_args correctly appended
    managed-ondemand-nvidia = {
      instance_types             = var.gpu_types
      ami_type                   = "BOTTLEROCKET_x86_64_NVIDIA"
      subnet_ids                 = [module.vpc.private_subnets[0]]
      bootstrap_extra_args       = <<-EOT
        [kubelet-device-plugin.nvidia]
        device-list-strategy = "envvar"
      EOT
      }

Not sure if this is by design (not documented though) or unintentional.

**Comment by bryantbiggs** [comment]
additional user data is only supported by EKS managed node groups via a custom launch template
