### ISSUE TITLE
why not just have ami_id as var? I need [EKS-opitmized-ami with GPU support](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html) which can't be matched with the filter.

### ISSUE THREAD

**Issue by leonmax** [terraform-aws-modules/terraform-aws-eks#319]
why not just have ami_id? I need [EKS-opitmized-ami with GPU support](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html) which can't be matched with the filter.

_Originally posted by @leonmax in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/295#issuecomment-476433122_

**Comment by max-rocket-internet** [comment]
Of course you can use `ami_id ` in your workers group map:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L42

Same for Launch Templates 😃

**Comment by leonmax** [comment]
Oh, `image_id`! I've missed that. Thanks!
