### ISSUE TITLE
Not logged into the server error when running kubectl get nodes after provisioning cluster using the module

### ISSUE THREAD

**Issue by rprakashg-redhat** [terraform-aws-modules/terraform-aws-eks#3198]
## Description

Just recently upgraded the module version to latest and provisioned a cluster. After running update kubeconfig I'm receiving error below

error: You must be logged in to the server (Unauthorized)
I'm  using same credentials I used to provision the cluster. Seems like some changes in current version.

**Comment by bryantbiggs** [comment]
Please provide the details required on the issue template

**Comment by rprakashg-redhat** [comment]
Ok adding this enable_cluster_creator_admin_permissions = true fixed. I guess earlier version it was default setting up creator as admin. Seems like this behavior is changed in new version
