### ISSUE TITLE
EKS Managed Node Group Module - policies being detached using 20.28.0

### ISSUE THREAD

**Issue by jan-g** [terraform-aws-modules/terraform-aws-eks#3200]
## Description

I'm using terraform-aws-modules/eks/aws//modules/eks-managed-node-group directly.

During planning, a delete & recreation of the policy attachments for the node group is being planned.

However, after execution, no policies are attached to the nodepool's role.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 20.28.0

- Terraform version: ~> 1.7.0
- Provider version(s): aws at 5.74.0

## Expected behavior

Should be able to do things like, eg, pull images.

## Actual behavior

The old policy attachments are dropped, but not re-added.

**Comment by bryantbiggs** [comment]
without a reproduction we won't be able to help triage or troubleshoot
