### ISSUE TITLE
a default HTTPS ingress rule should be injected in cluster_primary_security_group to allow node-group security group

### ISSUE THREAD

**Issue by dsantanu** [terraform-aws-modules/terraform-aws-eks#3204]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

Amazon EKS created SG (aka `cluster_primary_security_group`) needs a inbound rule to allow traffic from node-group instances; otherwise it fails to join the node group, with the below error:
> [ERROR]: The cluster Security Group sg-020b0c1fexxxxxxxx is not allowing traffic from the worker node.

## Describe the solution you'd like.

in the `main.tf` we should have a default rule allowing https traffic from node `node_security_group`, something like this:
```
resource "aws_security_group_rule" "traffic_from_nodes" {
  for_each                 = var.service_enabled ? toset([var.service_name]) : []
  type                     = "ingress"
  from_port                = 443
  to_port                  = 443
  protocol                 = "tcp"
  source_security_group_id = aws_security_group.node[0].id
  security_group_id        = aws_eks_cluster.this[0].vpc_config[0].cluster_security_group_id
  description              = "Allow traffic from the worker nodes"
}
```

## Describe alternatives you've considered.

Using this repo as the child-module, this thing can be done doe now i the parent module, as a work around:

```
resource "aws_security_group_rule" "traffic_from_nodes" {
  for_each                 = var.service_enabled ? toset([var.service_name]) : []
  type                     = "ingress"
  from_port                = 443
  to_port                  = 443
  protocol                 = "tcp"
  source_security_group_id = module.cluster.node_security_group_id
  security_group_id        = module.cluster.cluster_primary_security_group_id
  description              = "Allow traffic from the worker nodes"
}
```

**Comment by bryantbiggs** [comment]
closing due to lack of reproduction

**Comment by dsantanu** [comment]
can you explain what does it mean - `due to lack of reproduction` ?
Using this module, the nodes are constantly failing to join the node group and using TroubleshootEKSWorkerNode Runbook, it reports that the above security group rule is missing. I provided the actual error and also the code that I'm using to work around it - what exactly it's lacking?

**Comment by bryantbiggs** [comment]
> You should not close anything within 20 mins, without giving any proper reason, IMO

rather strong words to use on something that is provided to you for free

I gave a reason - you intentionally deleted the required section from the issue template and did not provide the required reproduction so how can I even begin to triage? 
<img width="307" alt="image" src="https://github.com/user-attachments/assets/1e090e73-f778-47da-a1e1-f4b3a9fec6c3">
