### ISSUE TITLE
No Terraform State For Managed Node Groups Access Entry

### ISSUE THREAD

**Issue by timetofaceit** [terraform-aws-modules/terraform-aws-eks#3207]
Hi! 👋

I don't know if I'm missing something from the documentation or this is a bug from the module side, but there is a problem with `access_entry` when you are creating a new EKS managed node group.

Problem - EKS module doesn't create a terraform state for it. 😢 

When you remove your managed node group, it leaves `access_entry` created and you can see it in AWS console, and when you remove it by hand in the AWS console (while your managed group is still active) EKS module doesn't recreate it. 😞 

I'm using version - 20.24.1

**Comment by bryantbiggs** [comment]
correct - the access entry for EKS managed node groups and EKS Fargate profiles is handled by the EKS service and therefore does not show up in Terraform. If you check the codebase, you will see there aren't any access entry resources in either the MNG or Fargate profile sub-modules
