### ISSUE TITLE
Can ASG of EKS Managed Node Group have mixed Spot and On-Demand capacity type? 

### ISSUE THREAD

**Issue by mansingcollis** [terraform-aws-modules/terraform-aws-eks#3215]
## Description

I'm using the combination of spot and on-demand instance type in the inEKS Managed Node group to optimize the cost. The documentation https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html says a managed node group with ASG can either contain only On-Demand or only Amazon EC2 Spot Instances. However, the management console does show option to set the combination. So I was wondering if there is any way to set mix of instance types using the module, I tried with passing multiple CapacityType to --node-labels in bootstrap_Extra_args but that is not working. 

![image](https://github.com/user-attachments/assets/48d5b0c7-def9-4235-bf6e-2c75036749e7)

Any help is really appreciated!

**Comment by bryantbiggs** [comment]
closing for now - the EKS managed nodegroup APIs need to support the behavior. If you bypass MNG and directly modify the ASG, that can cause issues or not function as you might intend
