### ISSUE TITLE
BUG::Stuck on module.eks.aws_security_group_rule.node when create_node_security_group is true 

### ISSUE THREAD

**Issue by vazkarvishal** [terraform-aws-modules/terraform-aws-eks#3217]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

## Versions

- Module version 20.29.0:

- Terraform version:
Terraform v1.5.1
on darwin_arm64
- Provider version(s):
Terraform v1.5.1
on darwin_arm64
+ provider registry.terraform.io/alekc/kubectl v2.1.3
+ provider registry.terraform.io/hashicorp/aws v5.77.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.5
+ provider registry.terraform.io/hashicorp/helm v2.16.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.33.0
+ provider registry.terraform.io/hashicorp/null v3.2.3
+ provider registry.terraform.io/hashicorp/time v0.12.1
+ provider registry.terraform.io/hashicorp/tls v4.0.6
+ provider registry.terraform.io/kreuzwerker/docker v3.0.2

## Reproduction Code [Required]

- create the EKS cluster with `create_node_security_group` set to `true`

## Expected behavior

The cluster should be created with the required security group, without hanging on the ingress rule step

### Terminal Output Screenshot(s)

<img width="921" alt="image" src="https://github.com/user-attachments/assets/9a96a5a9-513b-4b6c-9823-c56465392dd8">

**Comment by bryantbiggs** [comment]
Closing due to lack of reproduction

**Comment by vazkarvishal** [comment]
> Closing due to lack of reproduction

Hey @bryantbiggs  I have just tried using the module again and it still fails when the flag is set to true

<img width="834" alt="image" src="https://github.com/user-attachments/assets/b9b090fa-fef8-4247-b267-6aa8265d9a50">

<img width="910" alt="image" src="https://github.com/user-attachments/assets/c389d4df-8989-429c-a0ba-a2e537caf122">


**Source Code**
```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.29.0"

  cluster_name                   = local.name
  cluster_version                = local.cluster_version
  cluster_endpoint_public_access = true

  cluster_addons = {
    kube-proxy = { most_recent = true }
    coredns    = { most_recent = true }
  }

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  create_cloudwatch_log_group              = false
  create_cluster_security_group            = false
  create_node_security_group               = true
  authentication_mode                      = "API_AND_CONFIG_MAP"
  enable_cluster_creator_admin_permissions = true

  eks_managed_node_groups = {
    mg_5 = {
      node_group_name = "managed-ondemand"
      instance_types  = ["m4.large", "m5.large", "m5a.large", "m5ad.large", "m5d.large", "t2.large", "t3.large", "t3a.large"]

      create_security_group = false

      subnet_ids   = module.vpc.private_subnets
      max_size     = 2
      desired_size = 2
      min_size     = 2

      # Launch template configuration
      create_launch_template = true              # false will use the default launch template
      launch_template_os     = "amazonlinux2eks" # amazonlinux2eks or bottlerocket

      labels = {
        intent = "control-apps"
      }
    }
  }

  tags = merge(local.tags, {
    "karpenter.sh/discovery" = local.name
  })
}
```

**Comment by bryantbiggs** [comment]
create_cluster_security_group must be set to true, otherwise the node security group doesn't have a security group to reference for its rules

**Comment by vazkarvishal** [comment]
> create_cluster_security_group must be set to true, otherwise the node security group doesn't have a security group to reference for its rules

Should we mention that in the documentation and/or the variable description? I am happy to contribute.

**Comment by bryantbiggs** [comment]
no - its not clear what you are trying to do. most of your configs are either already the default or not valid. why not use this configuration which does the same but is simpler and doesn't cause issues? 

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.29.0"

  cluster_name                   = local.name
  cluster_version                = local.cluster_version
  cluster_endpoint_public_access = true

  cluster_addons = {
    kube-proxy = { most_recent = true }
    coredns    = { most_recent = true }
  }

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  create_cloudwatch_log_group = false

  enable_cluster_creator_admin_permissions = true

  eks_managed_node_groups = {
    mg_5 = {
      node_group_name = "managed-ondemand"
      instance_types  = ["m4.large", "m5.large", "m5a.large", "m5ad.large", "m5d.large", "t2.large", "t3.large", "t3a.large"]

      subnet_ids   = module.vpc.private_subnets
      max_size     = 2
      desired_size = 2
      min_size     = 2

      labels = {
        intent = "control-apps"
      }
    }
  }

  tags = merge(local.tags, {
    "karpenter.sh/discovery" = local.name
  })
}
```

**Comment by vazkarvishal** [comment]
@bryantbiggs  thanks for your help so far. I am trying to use secondary CNI with prefix delegation and `AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG` set true, to create an overlay network for the pods. Thus using  the [VPC module]("terraform-aws-modules/vpc/aws") with `intra_subnets` of 100.64 range.
