### ISSUE TITLE
 EKS managed nodegroup autoscaling

### ISSUE THREAD

**Issue by kinappy** [terraform-aws-modules/terraform-aws-eks#3222]
Unless I'm doing something wrong or misunderstanding, there seems to be an issue with the EKS autoscaling.

I deployed a test environment using the karpenter example.
https://github.com/terraform-aws-modules/terraform-aws-eks/tree/v20.30.1/examples/karpenter

The only thing I changed was:
In the  eks_managed_node_groups I change the instance_types.
	
	instance_types = ["t3.medium"]
		
In resource "kubectl_manifest" "karpenter_node_pool", I changed the requirements.
	
	requirements:
		- key: "node.kubernetes.io/instance-type"
		operator: In
		values: ["t3.medium"]
		- key: "kubernetes.io/arch"
		operator: In
		values: ["amd64"]
		- key: "karpenter.sh/capacity-type"
		operator: In
		values: ["on-demand"]
		
I also removed resource "kubectl_manifest" "karpenter_example_deployment" due to an issue with the amount of connections.
		
After deploying I can could see the running nodes

	$kubectl get nodes
	NAME                                        STATUS   ROLES    AGE   VERSION
	ip-10-0-17-174.eu-west-1.compute.internal   Ready    <none>   62m   v1.31.2-eks-94953ac
	ip-10-0-43-58.eu-west-1.compute.internal    Ready    <none>   62m   v1.31.2-eks-94953ac

I created a test deployment using nginx and could see karpenter created a new node.

	$kubectl get nodes
	NAME                                        STATUS   ROLES    AGE     VERSION
	ip-10-0-17-174.eu-west-1.compute.internal   Ready    <none>   69m     v1.31.2-eks-94953ac
	ip-10-0-19-9.eu-west-1.compute.internal     Ready    <none>   2m44s   v1.31.2-eks-94953ac
	ip-10-0-43-58.eu-west-1.compute.internal    Ready    <none>   69m     v1.31.2-eks-94953ac
	
Scaled the deployment to 3 pods and can see additional nodes created.

	$kubectl get nodes
	NAME                                        STATUS   ROLES    AGE     VERSION
	ip-10-0-12-122.eu-west-1.compute.internal   Ready    <none>   3m47s   v1.31.2-eks-94953ac
	ip-10-0-17-174.eu-west-1.compute.internal   Ready    <none>   80m     v1.31.2-eks-94953ac
	ip-10-0-19-9.eu-west-1.compute.internal     Ready    <none>   13m     v1.31.2-eks-94953ac
	ip-10-0-37-52.eu-west-1.compute.internal    Ready    <none>   3m48s   v1.31.2-eks-94953ac
	ip-10-0-43-58.eu-west-1.compute.internal    Ready    <none>   80m     v1.31.2-eks-94953ac
	
To me, this looks to work as expected.
Next I wanted to try and scale the managed node group.
I expected that, if I deploy enough containers which are allowed in this group by the taint, everntually I should see the managed node group scale from 2 to 3.

      min_size     = 2
      max_size     = 3
      desired_size = 2

I deleted the nginx deployment and karpenter eventually removed the extra nodes created.

	kubectl get nodes
	NAME                                        STATUS   ROLES    AGE   VERSION
	ip-10-0-17-174.eu-west-1.compute.internal   Ready    <none>   88m   v1.31.2-eks-94953ac
	ip-10-0-43-58.eu-west-1.compute.internal    Ready    <none>   88m   v1.31.2-eks-94953ac
	
	
I remove the pod and node affinity details from the coredns deployment and could see the pods were recreated.
I still had the same issue if I never updated these details but, the controller logs would warn me about the affinity.

	kube-system   coredns-66fb7cfb6d-94n2v       1/1     Running   0          49s
	kube-system   coredns-66fb7cfb6d-xlskt       1/1     Running   0          49s
	
I then scaled the coredns deployment

	kubectl -n kube-system scale deployment coredns --replicas 12
	deployment.apps/coredns scaled

I could see coredns was scaled over the two nodes

	kube-system   coredns-66fb7cfb6d-5c8q4       1/1     Running   0          97s     10.0.27.42    ip-10-0-17-174.eu-west-1.compute.internal   <none>           <none>
	kube-system   coredns-66fb7cfb6d-8j8rw       1/1     Running   0          97s     10.0.30.213   ip-10-0-17-174.eu-west-1.compute.internal   <none>           <none>
	kube-system   coredns-66fb7cfb6d-94n2v       1/1     Running   0          3m46s   10.0.47.31    ip-10-0-43-58.eu-west-1.compute.internal    <none>           <none>
	kube-system   coredns-66fb7cfb6d-hvbr4       1/1     Running   0          97s     10.0.37.243   ip-10-0-43-58.eu-west-1.compute.internal    <none>           <none>
	kube-system   coredns-66fb7cfb6d-jdjfm       1/1     Running   0          97s     10.0.33.117   ip-10-0-43-58.eu-west-1.compute.internal    <none>           <none>
	kube-system   coredns-66fb7cfb6d-q6d2k       1/1     Running   0          97s     10.0.23.99    ip-10-0-17-174.eu-west-1.compute.internal   <none>           <none>
	kube-system   coredns-66fb7cfb6d-q7c49       1/1     Running   0          97s     10.0.47.60    ip-10-0-43-58.eu-west-1.compute.internal    <none>           <none>
	kube-system   coredns-66fb7cfb6d-slqbn       1/1     Running   0          97s     10.0.19.179   ip-10-0-17-174.eu-west-1.compute.internal   <none>           <none>
	kube-system   coredns-66fb7cfb6d-sr4tm       1/1     Running   0          97s     10.0.28.231   ip-10-0-17-174.eu-west-1.compute.internal   <none>           <none>
	kube-system   coredns-66fb7cfb6d-tbpbl       1/1     Running   0          97s     10.0.39.174   ip-10-0-43-58.eu-west-1.compute.internal    <none>           <none>
	kube-system   coredns-66fb7cfb6d-v78rv       1/1     Running   0          97s     10.0.16.38    ip-10-0-17-174.eu-west-1.compute.internal   <none>           <none>
	kube-system   coredns-66fb7cfb6d-xlskt       1/1     Running   0          3m46s   10.0.39.38    ip-10-0-43-58.eu-west-1.compute.internal    <none>           <none>

I kept scaling until I could see an additional node created.

	kubectl get nodes
	NAME                                        STATUS   ROLES    AGE    VERSION
	ip-10-0-17-174.eu-west-1.compute.internal   Ready    <none>   133m   v1.31.2-eks-94953ac
	ip-10-0-43-58.eu-west-1.compute.internal    Ready    <none>   133m   v1.31.2-eks-94953ac
	ip-10-0-5-97.eu-west-1.compute.internal     Ready    <none>   105s   v1.31.2-eks-94953ac

If I check my managed node group, I see only 2.
kubectl get nodes -l eks.amazonaws.com/nodegroup=karpenter-2024112711053719860000001f --no-headers | wc -l
2

Does this mean my eks managed node group scaling is not working as expected? I expected the new node would be part of his node group.

Is this expected or am I doing something wrong and there is a better way to test this?

![image](https://github.com/user-attachments/assets/36415c3a-fd43-4d6f-bbf8-64c668bd8c33)

**Comment by bryantbiggs** [comment]
an autoscaling group does not automatically scale on its own - it provides the means for something to tell it to scale up or down. Typically, you would deploy cluster-autoscaler which would control the desired capacity field of the ASG

closing since this is not a module issue
