### ISSUE TITLE
please update EKS Automode.

### ISSUE THREAD

**Issue by yeoli9** [terraform-aws-modules/terraform-aws-eks#3226]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

- https://aws.amazon.com/ko/blogs/aws/streamline-kubernetes-cluster-management-with-new-amazon-eks-auto-mode/?trk=d57158fd-77e3-423f-9e1e-005fd2a64d89&sc_channel=el
- https://docs.aws.amazon.com/ko_kr/eks/latest/userguide/automode.html

eks module doesn't support EKS AutoMode.

**Comment by yeoli9** [comment]
Wow Thank you.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.31.0 :tada:
