### ISSUE TITLE
Not able to Enable EKS auto mode on existing cluster  without built in node pools of EKS Auto Mode

### ISSUE THREAD

**Issue by jatinmehrotra** [terraform-aws-modules/terraform-aws-eks#3229]
## Description

-  I am trying to enable EKS auto mode on existing cluster 
- After reading this [issue](https://github.com/hashicorp/terraform-provider-aws/issues/40411), i understood i cant use built in node pool so need to use custom node pool
- But before creating custom node pool i would like to simply enable eks auto mode in my existing cluster

## Versions

- Module version [Required]: ~>20.0

- Terraform version:  1.9.2

- Provider version(s): 

## Reproduction Code [Required]

- Not include vpc module code

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 20.31"

  cluster_name                   = local.cluster_name
  cluster_version                = "1.30"
  cluster_endpoint_public_access = true


  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  cluster_compute_config = {
    enabled = true
    # node_pools = ["general-purpose"]
  }

  enable_cluster_creator_admin_permissions = true

  eks_managed_node_group_defaults = {
    ami_type       = "AL2_x86_64"
    instance_types = ["m5.large"]
    # instance_types = ["t3.small"]
    # vpc_security_group_ids = [aws_security_group.all_worker_mgmt.id]
    iam_role_additional_policies = {
      ebs_policy                                 = "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy" #IAM rights needed by CSI driver
      auto_scaling_policy                        = "arn:aws:iam::aws:policy/AutoScalingFullAccess"
      cloudwatch_container_insights_agent_policy = "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
      xray_policy                                = "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"
    }
  }

  eks_managed_node_groups = {

    node_group = {
      min_size     = 2
      max_size     = 5
      desired_size = local.node_group_desired_size
    }
  }

  node_security_group_additional_rules = {
    http_traffic_node_to_node = {
      description = "Allow inbound HTTP from self"
      from_port   = 80
      to_port     = 80
      protocol    = "tcp"
      self        = true
      type        = "ingress"
    }
  }

}

```

- Create the cluster without the following code to simulate existing cluster use case

```
 cluster_compute_config = {
    enabled = true
    # node_pools = ["general-purpose"]
  }
```

- after creating cluster add the above code 

## Expected behavior

- I expected that EKS auto mode will be enabled without using built in node pools

## Actual behavior

- Trying to recreate the cluster

### Terminal Output Screenshot(s)

```
╷
│ Error: creating EKS Cluster (eks-auto-test-jatin): operation error EKS: CreateCluster, https response error StatusCode: 409, RequestID: 5ba81077-baee-4631-9b6e-1219d12d7096, ResourceInUseException: Cluster already exists with name: eks-auto-test-jatin
│ 
│   with module.eks.aws_eks_cluster.this[0],
│   on .terraform/modules/eks/main.tf line 30, in resource "aws_eks_cluster" "this":
│   30: resource "aws_eks_cluster" "this" {
│ 
╵
```
<img width="900" alt="Screenshot 2024-12-06 at 1 17 42" src="https://github.com/user-attachments/assets/ff1ecd8b-717b-4cba-999f-b64eb925261e">

**Comment by bryantbiggs** [comment]
This isn't a module issue - the error message explains the issue

> ResourceInUseException: Cluster already exists with name: eks-auto-test-jatin

**Comment by jatinmehrotra** [comment]
@bryantbiggs 

I think there is confusion here. Tt is trying to recreate the cluster which is already there in this case `eks-auto-test-jatin`. My existing cluster name is `eks-auto-test-jatin` and then i am trying to add the EKS auto Mode and during terraform apply it is trying to recreate the cluster but it finds a already existing cluster so throwing that error.

**Comment by bryantbiggs** [comment]
It is not the same scenario - you will need to set `bootstrap_self_managed_addons = true` for your use case

**Comment by jatinmehrotra** [comment]
@bryantbiggs 

You were right, not the module issue `bootstrap_self_managed_addons = true` was the issue.

Thank you
