### ISSUE TITLE
Include worker_iam_instance_profile_arn as an output

### ISSUE THREAD

**Issue by soapergem** [terraform-aws-modules/terraform-aws-eks#323]
Currently there are outputs for `worker_iam_role_name` and `worker_iam_role_arn` but I need at least `worker_iam_instance_profile_arn` as well. While you can [look up an instance profile for a role](https://docs.aws.amazon.com/cli/latest/reference/iam/list-instance-profiles-for-role.html) using `aws` CLI commands, Terraform doesn't provide a path to do this directly using the existing [data sources](https://www.terraform.io/docs/providers/aws/d/iam_instance_profile.html). Thus we really need this as an output variable in this module.

**Comment by max-rocket-internet** [comment]
Cool. Feel free to make a PR.

**Comment by soapergem** [comment]
As requested, I've made the PR. Since it's so simple and straight-forward (just adding outputs), any chance you could get this merged in soon?

**Comment by soapergem** [comment]
Bueller? Anyone? :)

**Comment by max-rocket-internet** [comment]
Done: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/329
