### ISSUE TITLE
Additional policies for Managed node group IAM Role

### ISSUE THREAD

**Issue by vietwow** [terraform-aws-modules/terraform-aws-eks#3230]
Hi,

I'm using latest version of module "20.31.0".

For adding additional IAM policies, the module have supported :
- `iam_role_additional_policies` : Additional policies for **Cluster** IAM Role
- `node_iam_role_additional_policies` : Additional policies for EKS **Auto** node IAM role

but in my (common) case, I would need add additional policies for EKS managed (not Auto) node IAM role. I tried to read https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/variables.tf#L667-L687 and in the code, looks like there is no support for this, please correct me If I'm wrong. Thank you.

Best Regards,
VietNC

**Comment by bryantbiggs** [comment]
it just goes inside the node group definition block https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c63a57908d7b4d51895d3f8502d60daae758b761/tests/eks-managed-node-group/main.tf#L299-L302
