### ISSUE TITLE
EKS Auto Mode for Terragrunt examples

### ISSUE THREAD

**Issue by release-managers** [terraform-aws-modules/terraform-aws-eks#3231]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

**Comment by bryantbiggs** [comment]
Thank you for the request - unfortunately we won't be supporting this at this time
