### ISSUE TITLE
Node IAM role for EKS Auto on existing cluster is not being created when built in node pools are not mentioned explicilty

### ISSUE THREAD

**Issue by jatinmehrotra** [terraform-aws-modules/terraform-aws-eks#3232]
## Description

- I am trying to Enable EKS auto on existing cluster without explicitly mentioning built-in node pools
- When I tried to create output for `node_iam_role_arn` or `node_iam_role_name`. Output is not being generated 
- If I do the same for New Cluster where I am using built-in node pools then output is being generated which means node_iam_role for EKS Auto for NEW cluster where built-in node pools is mentioed is being created automatically

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 20.31

- Terraform version:

Terraform v1.9.2
- Provider version(s):

v5.80

## Reproduction Code [Required]

- eks.tf

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 20.31"

  cluster_name    = "example"
  cluster_version = "1.31"

  # Optional
  cluster_endpoint_public_access = true

  # Optional: Adds the current caller identity as an administrator via cluster access entry
  enable_cluster_creator_admin_permissions = true

 bootstrap_self_managed_addons = true
  cluster_compute_config = {
    enabled = true
  }

  vpc_id     = "vpc-1234556abcdef"
  subnet_ids = ["subnet-abcde012", "subnet-bcde012a", "subnet-fghi345a"]

  tags = {
    Environment = "dev"
    Terraform   = "true"
  }
}

```

- output.tf

```
output "node_iam_role_arn" {
  value = module.eks.node_iam_role_arn
}

output "node_iam_role_name" {
  value = module.eks.node_iam_role_name
}

output "cluster_name" {
  value = module.eks.cluster_name
}
```

- Create a cluster without EKS auto enabled
- Enabled it 
- Try to use output.tf only cluster_name will be output

- if you do the same for new cluster with EKS auto `node_iam_role`  and `node_iam_role_arn` will be shown
## Expected behavior

- `node_iam_role` for EKS auto to be created even when built-in node pools are not mentioned explicitly 

## Actual behavior

- After enabling `node_iam_role` for EKS auto which is supposed to be created automatically is not being created.

### Terminal Output Screenshot(s)

NA

## Additional context

- This also leads to another problem That user cannot use custom node class and custom node pools as node iam role is not being generated when built-in node pools are not generated because node iam role cannot be changed after EKS auto is enabled 

Refs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#node_role_arn-1

>  This value cannot be changed after the compute capability of EKS Auto Mode is enabled..

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.31.1 :tada:
