### ISSUE TITLE
Terraform apply fails after importing EKS cluster with Auto Mode disabled

### ISSUE THREAD

**Issue by cw-juyeonyu** [terraform-aws-modules/terraform-aws-eks#3236]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:
1.10.1
- Provider version(s):
20.31.1

## Reproduction Code [Required]

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.31.1"

  cluster_name    = "dev-cluster"
  cluster_version = "1.31"

  cluster_compute_config = {
    enabled = false
  }

  .......
}

1. Enable EKS Auto Mode using AWS CLI:
```bash
aws eks update-cluster-config --name dev-cluster \
    --compute-config enabled=true \
    --kubernetes-network-config '{"elasticLoadBalancer":{"enabled": true}}' \
    --storage-config '{"blockStorage":{"enabled": true}}'
```

2. Disable EKS Auto Mode using AWS CLI:
```bash
aws eks update-cluster-config --name dev-cluster \
    --compute-config enabled=false \
    --kubernetes-network-config '{"elasticLoadBalancer":{"enabled": false}}' \
    --storage-config '{"blockStorage":{"enabled": false}}'
```

3. Import Terraform state for EKS cluster:
```
terraform import "module.eks.aws_eks_cluster.this[0]" dev-cluster
```

4. Run Terraform Plan & Apply
```
# plan
~ resource "aws_eks_cluster" "this" {
        id                            = "dev-cluster"
        name                          = "dev-cluster"
        # (12 unchanged attributes hidden)
      - storage_config {
          - block_storage {
              - enabled = false -> null
            }
        }
        # (7 unchanged blocks hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.

# error message
Error: updating EKS Cluster (dev-cluster) compute config: operation error EKS: UpdateClusterConfig, https response error StatusCode: 400, RequestID: xxxxxxx, InvalidParameterException: The type for cluster update was not provided.
```

## Expected behavior

Prevent Terraform apply from failing when EKS Auto Mode is disabled.

**Comment by bryantbiggs** [comment]
Why not create it with Terraform instead of out of band and import?

**Comment by cw-juyeonyu** [comment]
> Why not create it with Terraform instead of out of band and import?

Because the Terraform execution plan attempted to delete and recreate the EKS Cluster.

**Comment by willejs** [comment]
Yeah, i think enabling auto mode on an existing cluster is actually a breaking change, which is the actual issue here.

**Comment by bryantbiggs** [comment]
It's not clear from the info provided but are you referring to https://github.com/hashicorp/terraform-provider-aws/issues/40411

**Comment by cw-juyeonyu** [comment]
> It's not clear from the info provided but are you referring to [hashicorp/terraform-provider-aws#40411](https://github.com/hashicorp/terraform-provider-aws/issues/40411)

Thank you for letting me know about the related AWS provider issue. I'm currently using AWS provider version 5.80.0 and I'll wait for version 5.81.0 to be released.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.31.3 :tada:

**Comment by cw-juyeonyu** [comment]
I don't think this issue has been resolved yet.

I create a new EKS cluster with a managed node group, and after initial deployment, I tried to enable EKS Auto mode. Subsequently, when attempting to disable the Auto mode, an error occurred.

**Steps to Reproduce**
1. Create and EKS Cluster with Managed Node Group
2. Added the following Terraform configuration to the created cluster and applied the changes
```hcl
cluster_compute_config = {
  enabled = true
}
```
3. Updated the following Terraform configuration to the cluster and attempted to disable EKS Auto Mode, but faced an error when trying to apply the changes
```hcl
cluster_compute_config = {
  enabled = false
}
```

**Error Message**

```
Error: compute_config.enabled, kubernetes_networking_config.elastic_load_balancing.enabled, and storage_config.block_storage.enabled must all be set to either true or false
│
│   with module.eks.aws_eks_cluster.this[0],
│   on .terraform/modules/eks/main.tf line 35, in resource "aws_eks_cluster" "this":
│   35: resource "aws_eks_cluster" "this" {
```

**Comment by bryantbiggs** [comment]
Please provide a full reproduction

**Comment by cw-juyeonyu** [comment]
> Please provide a full reproduction

1. Create cluster configuration
```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.31.3"

  cluster_name    = var.cluster_name
  cluster_version = "1.31"

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  bootstrap_self_managed_addons = false

  enable_cluster_creator_admin_permissions = true

  cluster_security_group_description = format(
    "EKS cluster [%s] security group",
    var.cluster_name
  )

  cloudwatch_log_group_retention_in_days = 3

  iam_role_use_name_prefix     = false
  iam_role_additional_policies = {
    AmazonEKSVPCResourceController = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
    AmazonEKSClusterPolicy         = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
    AmazonEFSCSIDriverPolicy       = "arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy"
  }

  enable_irsa = true

  vpc_id     = data.aws_vpc.current_vpc.id
  subnet_ids = data.aws_subnets.private_subnet_app.ids

  eks_managed_node_group_defaults = {
    ami_type = "AL2023_x86_64_STANDARD"
  }

  eks_managed_node_groups = {
    node_group_defaults = {
      name            = format("%s-node-group-defaults-m7i-large", var.cluster_name)
      use_name_prefix = false

      instance_types = ["m7i.large"]
      ebs_optimized  = true
      capacity_type  = "ON_DEMAND"

      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_type = "gp3"
            encrypted   = true
          }
        }
      }

      min_size     = 1
      max_size     = 1
      desired_size = 1

      iam_role_use_name_prefix = false
      iam_role_name            = format("%s-worker-nodes", var.cluster_name)

      tag_specifications = ["instance", "volume", "network-interface", "spot-instances-request"]
    }
  }
}
```

2. Enable EKS Auto Mode
```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.31.3"

  cluster_name    = var.cluster_name
  cluster_version = "1.31"

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  bootstrap_self_managed_addons = false

  cluster_compute_config = {
    enabled = true
  }

  enable_cluster_creator_admin_permissions = true

  cluster_security_group_description = format(
    "EKS cluster [%s] security group",
    var.cluster_name
  )

  cloudwatch_log_group_retention_in_days = 3

  iam_role_use_name_prefix     = false
  iam_role_additional_policies = {
    AmazonEKSVPCResourceController = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
    AmazonEKSClusterPolicy         = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
    AmazonEFSCSIDriverPolicy       = "arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy"
  }

  enable_irsa = true

  vpc_id     = data.aws_vpc.current_vpc.id
  subnet_ids = data.aws_subnets.private_subnet_app.ids

  eks_managed_node_group_defaults = {
    ami_type = "AL2023_x86_64_STANDARD"
  }

  eks_managed_node_groups = {
    node_group_defaults = {
      name            = format("%s-node-group-defaults-m7i-large", var.cluster_name)
      use_name_prefix = false

      instance_types = ["m7i.large"]
      ebs_optimized  = true
      capacity_type  = "ON_DEMAND"

      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_type = "gp3"
            encrypted   = true
          }
        }
      }

      min_size     = 1
      max_size     = 1
      desired_size = 1

      iam_role_use_name_prefix = false
      iam_role_name            = format("%s-worker-nodes", var.cluster_name)

      tag_specifications = ["instance", "volume", "network-interface", "spot-instances-request"]
    }
  }
}
```

3. Disable EKS Auto Mode
```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.31.3"

  cluster_name    = var.cluster_name
  cluster_version = "1.31"

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  bootstrap_self_managed_addons = false

  cluster_compute_config = {
    enabled = false
  }

  enable_cluster_creator_admin_permissions = true

  cluster_security_group_description = format(
    "EKS cluster [%s] security group",
    var.cluster_name
  )

  cloudwatch_log_group_retention_in_days = 3

  iam_role_use_name_prefix     = false
  iam_role_additional_policies = {
    AmazonEKSVPCResourceController = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
    AmazonEKSClusterPolicy         = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
    AmazonEFSCSIDriverPolicy       = "arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy"
  }

  enable_irsa = true

  vpc_id     = data.aws_vpc.current_vpc.id
  subnet_ids = data.aws_subnets.private_subnet_app.ids

  eks_managed_node_group_defaults = {
    ami_type = "AL2023_x86_64_STANDARD"
  }

  eks_managed_node_groups = {
    node_group_defaults = {
      name            = format("%s-node-group-defaults-m7i-large", var.cluster_name)
      use_name_prefix = false

      instance_types = ["m7i.large"]
      ebs_optimized  = true
      capacity_type  = "ON_DEMAND"

      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_type = "gp3"
            encrypted   = true
          }
        }
      }

      min_size     = 1
      max_size     = 1
      desired_size = 1

      iam_role_use_name_prefix = false
      iam_role_name            = format("%s-worker-nodes", var.cluster_name)

      tag_specifications = ["instance", "volume", "network-interface", "spot-instances-request"]
    }
  }
}
```

I believe the note in the following link is related to this error.
[Amazon EKS User Guide > EKS Auto Mode > Configure > Disable EKS Auto Mode](https://docs.aws.amazon.com/eks/latest/userguide/auto-disable.html#_disable_eks_auto_mode_cli)
![image](https://github.com/user-attachments/assets/85843f1c-402d-4108-a935-969d0a700286)

**Comment by Boface** [comment]
> > Please provide a full reproduction
> 
> 1. Create cluster configuration
> 
> ```hcl
> module "eks" {
>   source  = "terraform-aws-modules/eks/aws"
>   version = "20.31.3"
> 
>   cluster_name    = var.cluster_name
>   cluster_version = "1.31"
> 
>   cluster_endpoint_private_access = true
>   cluster_endpoint_public_access  = true
> 
>   bootstrap_self_managed_addons = false
> 
>   enable_cluster_creator_admin_permissions = true
> 
>   cluster_security_group_description = format(
>     "EKS cluster [%s] security group",
>     var.cluster_name
>   )
> 
>   cloudwatch_log_group_retention_in_days = 3
> 
>   iam_role_use_name_prefix     = false
>   iam_role_additional_policies = {
>     AmazonEKSVPCResourceController = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
>     AmazonEKSClusterPolicy         = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
>     AmazonEFSCSIDriverPolicy       = "arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy"
>   }
> 
>   enable_irsa = true
> 
>   vpc_id     = data.aws_vpc.current_vpc.id
>   subnet_ids = data.aws_subnets.private_subnet_app.ids
> 
>   eks_managed_node_group_defaults = {
>     ami_type = "AL2023_x86_64_STANDARD"
>   }
> 
>   eks_managed_node_groups = {
>     node_group_defaults = {
>       name            = format("%s-node-group-defaults-m7i-large", var.cluster_name)
>       use_name_prefix = false
> 
>       instance_types = ["m7i.large"]
>       ebs_optimized  = true
>       capacity_type  = "ON_DEMAND"
> 
>       block_device_mappings = {
>         xvda = {
>           device_name = "/dev/xvda"
>           ebs = {
>             volume_type = "gp3"
>             encrypted   = true
>           }
>         }
>       }
> 
>       min_size     = 1
>       max_size     = 1
>       desired_size = 1
> 
>       iam_role_use_name_prefix = false
>       iam_role_name            = format("%s-worker-nodes", var.cluster_name)
> 
>       tag_specifications = ["instance", "volume", "network-interface", "spot-instances-request"]
>     }
>   }
> }
> ```
> 
> 2. Enable EKS Auto Mode
> 
> ```hcl
> module "eks" {
>   source  = "terraform-aws-modules/eks/aws"
>   version = "20.31.3"
> 
>   cluster_name    = var.cluster_name
>   cluster_version = "1.31"
> 
>   cluster_endpoint_private_access = true
>   cluster_endpoint_public_access  = true
> 
>   bootstrap_self_managed_addons = false
> 
>   ###### ADD ########
>   cluster_compute_config = {
>     enabled = true
>   }
>   ###### ADD ########
> 
>   enable_cluster_creator_admin_permissions = true
> 
>   cluster_security_group_description = format(
>     "EKS cluster [%s] security group",
>     var.cluster_name
>   )
> 
>   cloudwatch_log_group_retention_in_days = 3
> 
>   iam_role_use_name_prefix     = false
>   iam_role_additional_policies = {
>     AmazonEKSVPCResourceController = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
>     AmazonEKSClusterPolicy         = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
>     AmazonEFSCSIDriverPolicy       = "arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy"
>   }
> 
>   enable_irsa = true
> 
>   vpc_id     = data.aws_vpc.current_vpc.id
>   subnet_ids = data.aws_subnets.private_subnet_app.ids
> 
>   eks_managed_node_group_defaults = {
>     ami_type = "AL2023_x86_64_STANDARD"
>   }
> 
>   eks_managed_node_groups = {
>     node_group_defaults = {
>       name            = format("%s-node-group-defaults-m7i-large", var.cluster_name)
>       use_name_prefix = false
> 
>       instance_types = ["m7i.large"]
>       ebs_optimized  = true
>       capacity_type  = "ON_DEMAND"
> 
>       block_device_mappings = {
>         xvda = {
>           device_name = "/dev/xvda"
>           ebs = {
>             volume_type = "gp3"
>             encrypted   = true
>           }
>         }
>       }
> 
>       min_size     = 1
>       max_size     = 1
>       desired_size = 1
> 
>       iam_role_use_name_prefix = false
>       iam_role_name            = format("%s-worker-nodes", var.cluster_name)
> 
>       tag_specifications = ["instance", "volume", "network-interface", "spot-instances-request"]
>     }
>   }
> }
> ```
> 
> 3. Disable EKS Auto Mode
> 
> ```hcl
> module "eks" {
>   source  = "terraform-aws-modules/eks/aws"
>   version = "20.31.3"
> 
>   cluster_name    = var.cluster_name
>   cluster_version = "1.31"
> 
>   cluster_endpoint_private_access = true
>   cluster_endpoint_public_access  = true
> 
>   bootstrap_self_managed_addons = false
> 
>   ###### UPDATE ########
>   cluster_compute_config = {
>     enabled = false
>   }
>   ###### UPDATE ########
> 
>   enable_cluster_creator_admin_permissions = true
> 
>   cluster_security_group_description = format(
>     "EKS cluster [%s] security group",
>     var.cluster_name
>   )
> 
>   cloudwatch_log_group_retention_in_days = 3
> 
>   iam_role_use_name_prefix     = false
>   iam_role_additional_policies = {
>     AmazonEKSVPCResourceController = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
>     AmazonEKSClusterPolicy         = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
>     AmazonEFSCSIDriverPolicy       = "arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy"
>   }
> 
>   enable_irsa = true
> 
>   vpc_id     = data.aws_vpc.current_vpc.id
>   subnet_ids = data.aws_subnets.private_subnet_app.ids
> 
>   eks_managed_node_group_defaults = {
>     ami_type = "AL2023_x86_64_STANDARD"
>   }
> 
>   eks_managed_node_groups = {
>     node_group_defaults = {
>       name            = format("%s-node-group-defaults-m7i-large", var.cluster_name)
>       use_name_prefix = false
> 
>       instance_types = ["m7i.large"]
>       ebs_optimized  = true
>       capacity_type  = "ON_DEMAND"
> 
>       block_device_mappings = {
>         xvda = {
>           device_name = "/dev/xvda"
>           ebs = {
>             volume_type = "gp3"
>             encrypted   = true
>           }
>         }
>       }
> 
>       min_size     = 1
>       max_size     = 1
>       desired_size = 1
> 
>       iam_role_use_name_prefix = false
>       iam_role_name            = format("%s-worker-nodes", var.cluster_name)
> 
>       tag_specifications = ["instance", "volume", "network-interface", "spot-instances-request"]
>     }
>   }
> }
> ```
> 
> I believe the note in the following link is related to this error. [Amazon EKS User Guide > EKS Auto Mode > Configure > Disable EKS Auto Mode](https://docs.aws.amazon.com/eks/latest/userguide/auto-disable.html#_disable_eks_auto_mode_cli) ![image](https://private-user-images.githubusercontent.com/78328472/395408321-85843f1c-402d-4108-a935-969d0a700286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjI5MzcsIm5iZiI6MTczNDQyMjYzNywicGF0aCI6Ii83ODMyODQ3Mi8zOTU0MDgzMjEtODU4NDNmMWMtNDAyZC00MTA4LWE5MzUtOTY5ZDBhNzAwMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA4MDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5OGVjOWU2YTViYzVlZTYxY2U2NDdjMmM4MzVkZWI2OGUxMmE5ZGY3YTdhZjhmYjQ0MGJiYjRjMDA5MzE4MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O4YnRiJuJjHLS2g7v8lS5xHNYGzVzXC0qEu3FxTkugw)

Getting the exact same issue, waiting for a fix

**Comment by Boface** [comment]
Getting the exact same issue as @cw-juyeonyu. I'm currently on 20.31.4 for the module and provider verison 5.81.0. I enabled and disabled EKS Auto Mode and attempted to apply the plan.
`
│ 
│   with module.eks.aws_eks_cluster.this[0],
│   on .terraform/modules/eks/main.tf line 35, in resource "aws_eks_cluster" "this":
│   35: resource "aws_eks_cluster" "this" {
│ 
`
