### ISSUE TITLE
EKS Auto Mode - Failed to create when node_pools is not set, node_role_arn is set

### ISSUE THREAD

**Issue by erezzarum** [terraform-aws-modules/terraform-aws-eks#3238]
## Description
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

Using EKS Auto Mode without providing nodepools fails.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 20.31.1

- Terraform version: 1.73

- Provider version(s): 5.80.0

## Reproduction Code [Required]

```
module "eks" {
...
...
  cluster_compute_config = {
    enabled = true
  }
...
...
}
```

## Expected behavior

Enable EKS Auto Mode without any pre-defined nodepools but create the node role.

## Actual behavior

Fail to create cluster, as nodepools can not be empty if node role is provided, which is provided by default regardless if nodepools is set or no.

### Terminal Output Screenshot(s)

```
Error: creating EKS Cluster (cluster-demo): operation error EKS: CreateCluster, https response error StatusCode: 400, RequestID: 9055f212-bdb4-4157-b03f-ce3addb3532d, InvalidParameterException: When Compute Config nodeRoleArn is not null or empty, nodePool value(s) must be provided.
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.31.2 :tada:
