### ISSUE TITLE
Karpenter 1.0.0 does not have v1beta1 version and have issue: [karpenter.k8s.aws/v1beta1/EC2NodeClass] isn't valid for cluster, check the APIVersion and Kind fields are valid

### ISSUE THREAD

**Issue by sushanku** [terraform-aws-modules/terraform-aws-eks#3244]
## Description
- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions 20.31.4

- Module version [Required]: 20.31.4

terraform {
  required_version = ">= 1.3.2"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.81"
    }
    helm = {
      source  = "hashicorp/helm"
      version = ">= 2.7"
    }
    kubectl = {
      source  = "alekc/kubectl"
      version = ">= 2.0"
    }
  }
}

I am using karpenter example to create eks with karpenter but I am getting a following error:
`
│ Error: default failed to create kubernetes rest client for update of resource: resource [karpenter.k8s.aws/v1beta1/EC2NodeClass] isn't valid for cluster, check the APIVersion and Kind fields are valid
│
│   with kubectl_manifest.karpenter_node_class,
│   on main.tf line 151, in resource "kubectl_manifest" "karpenter_node_class":
│  151: resource "kubectl_manifest" "karpenter_node_class" {
`

I am not sure I am facing this issue. I have tried this on MacOS and Ubuntu thinking if different distro will help. But similar issue occurs. This 20.31.4 module version uses karpenter 1.1.0

**Comment by sushanku** [comment]
Just checked the karpenter documentation and found out that api version for nodepool and nodeclass has changed from beta version to v1.

Also, nodeClassRef.group and nodeClassRef.kind are strictly required. Ensure these values are set for all NodePools / NodeClaims before upgrading.

Could this be applied to the karpenter examples as well? Otherwise karpenter examples are just breaking.

Migration guide
https://karpenter.sh/v1.0/upgrading/v1-migration/#kubelet-configuration-migration

**Comment by antonbabenko** [comment]
This issue has been resolved in version 20.31.6 :tada:
