### ISSUE TITLE
authentication_mode changes are ignored

### ISSUE THREAD

**Issue by tdbertelli** [terraform-aws-modules/terraform-aws-eks#3246]
## Description

I wanted to upgrade from version 19.21 to 20.0. This worked well for some of my clusters but some had issues with the variable `bootstrap_cluster_creator_admin_permissions` being set to true, for reason unknown, but the end result was that it tried to replace the cluster.
I saw this was a bug solved on version 20.11.1, so I switched to that version. Now, the problem was gone, but unfortunately it seems the module no longer takes in changes to `authentication_mode`, probably because of the lifecycle rule that does not target the bootstrap_cluster_creator_admin_permissions specifically but rather the entire block.

I ended up manually upgrading to see if terraform would pick up the changes, but it did not.

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 20.11.1
- Terraform version: v1.10.3
- Provider version(s):
provider registry.terraform.io/hashicorp/aws v5.81.0
provider registry.terraform.io/hashicorp/azurerm v3.94.0
provider registry.terraform.io/hashicorp/cloudinit v2.3.5
provider registry.terraform.io/hashicorp/dns v3.4.1
provider registry.terraform.io/hashicorp/helm v2.16.1
provider registry.terraform.io/hashicorp/kubernetes v2.20.0
provider registry.terraform.io/hashicorp/null v3.2.3
provider registry.terraform.io/hashicorp/time v0.12.1
provider registry.terraform.io/hashicorp/tls v4.0.6

## Reproduction Code [Required]
```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.11.1"
  authentication_mode = "API_AND_CONFIG_MAP"
  ...
  }
  
```
but on my remote state:
```
"authentication_mode": "CONFIG_MAP",
```
aws cli:  
``` 
    "accessConfig": {
        "authenticationMode": "API_AND_CONFIG_MAP"
    },

```

## Expected behavior

On your module, change the value of authentication_mode to any of the accepted values

## Actual behavior

Terraform reports a change must be made

## Additional context

This is more of a question than a bug report, I believe. I wish to know if this is reproducible your enviroment.

**Comment by bryantbiggs** [comment]
authentication mode is there https://github.com/terraform-aws-modules/terraform-aws-eks/blob/ed43ce7ec6004512ec22adfd3302a2cbdb3b6f23/variables.tf#L41-L45

and its not ignored. however, you can move from the configmap to API, but you cannot reverse. So these order of operations are valid:
`CONFIG_MAP` -> `API_AND_CONFIG_MAP` -> `API`

But you cannot do `API` -> `API_AND_CONFIG_MAP` nor `API_AND_CONFIG_MAP` -> `CONFIG_MAP`

**Comment by tdbertelli** [comment]
Thanks for the prompt response. I am aware I cannot downgrade, only upgrade. 
What I mean - if you change that value on your code, does terraform notice? No need to apply, just a plain plan. This is the only question I need. Because it seems to ignore it after 20.11.1, at least on my code.

**Comment by tdbertelli** [comment]
Many thanks. If this the case, the problem must be on my end.
