### ISSUE TITLE
EBS-optimized defaults (e.g. for r5)

### ISSUE THREAD

**Issue by tbarrella** [terraform-aws-modules/terraform-aws-eks#325]
# I have issues

## I'm submitting a...

* [x] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

When creating a worker ASG for an r5 instance type, `ebs_optimized` is set to `false` by default

## What's the expected behavior?

Seems based on https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html that these support free EBS optimization by default

`workers.tf` selects `false` for any instance type not in the map in `local.tf`. Adding r5 instance types to that map would fix this, but I wasn't sure how these values are usually populated (they don't all match the table above) or if there's a way to reduce maintenance as new instance types come out. It looks like all of the instance types mentioned in https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html that aren't EBS-optimized by default are previous generation instances https://aws.amazon.com/ec2/previous-generation/

## Are you able to fix this problem and submit a PR? Link here if you have already.

Maybe, although not sure about the best approach

**Comment by max-rocket-internet** [comment]
Closing this old issue. Feel free to open a new one when running against latest release 🙂
