### ISSUE TITLE
EKS - k8s v.1.2 upgrade

### ISSUE THREAD

**Issue by chenrui333** [terraform-aws-modules/terraform-aws-eks#326]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## AWS news
https://aws.amazon.com/about-aws/whats-new/2019/03/amazon-eks-now-supports-kubernetes-version-1-12-and-cluster-vers/

**Comment by confiq** [comment]
when you change `cluster_version=>1.12`, it will automatically upgrade.

![image](https://user-images.githubusercontent.com/277770/55226718-f3d31a80-5215-11e9-9f5f-04c7c1e94f96.png)

We might change the [default](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/variables.tf#L12) value if needed. Since it's a tiny change, I can volunteer for that.

**Comment by chenrui333** [comment]
how was like upgrading from v1.10 to v1.11?

**Comment by confiq** [comment]
Never did that...

**Comment by chenrui333** [comment]
ok. I think there is already a PR for the upgrade: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/327

**Comment by chenrui333** [comment]
ok, 1.10 -> 1.11 is pretty much the same, :)
`module.eks.aws_eks_cluster.this: Modifications complete after 21m38s`

**Comment by max-rocket-internet** [comment]
PR was merged. Update your module version to latest commit ID or wait a few days for a new release 🙂

**Comment by syst0m** [comment]
This actually only upgrades the EKS control plane, right?
Does the upgrade process with this module cause downtime?

**Comment by max-rocket-internet** [comment]
> This actually only upgrades the EKS control plane, right?

Correct. You can see when it's done as the Server Version in `kubectl version` will change.

> Does the upgrade process with this module cause downtime?

Nope. In theory the k8s API will be done for a small amount of time but this doesn't affect running nodes or pods in a negative way.

After updating EKS you can update your nodes to a newer AMI.
