### ISSUE TITLE
Getting`invalid or unknown key: endpoint_private_access` error when upgrading to 2.3.1

### ISSUE THREAD

**Issue by chenrui333** [terraform-aws-modules/terraform-aws-eks#330]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Getting error when upgrading to v2.3.1
```
Error: module.eks.aws_eks_cluster.this: vpc_config.0: invalid or unknown key: endpoint_private_access



Error: module.eks.aws_eks_cluster.this: vpc_config.0: invalid or unknown key: endpoint_public_access
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.
My setup is like this:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/8b2e1c2dd8/examples/eks_test_fixture/main.tf#L158-L175

## What's the expected behavior?
No errors

## Environment details

* Affected module version: v2.3.1
* OS: Mac
* Terraform version: v0.11.13

**Comment by chenrui333** [comment]
I actually dont have issue with 2.3.0 though.

**Comment by elatt** [comment]
This option was added between 2.3.0 and 2.3.1 (https://github.com/terraform-aws-modules/terraform-aws-eks/commit/806edb600187f3889041c54c62dbdf07744d1a4f)

I'm having the same issue upgrading from 2.3.0 to 2.3.1. I even tried to manually hack the state file to add this option in but that didn't seem to help.

**Comment by chenrui333** [comment]
Yeah, I know this is newly added option.

@elatt what is the version for your vpc module?

**Comment by elatt** [comment]
Ah, I think I resolved the issue. It is a new-ish option in the `AWS` provider plugin: https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#230-march-21-2019

You'll have to update your version of the plugin and now things are working.

**Comment by chenrui333** [comment]
I thought I used the latest version? Here is the output:
```
$ terraform version
Terraform v0.11.13
+ provider.aws v1.54.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

**Comment by alexsn** [comment]
You need to upgrade aws provider to ~>2.0 or stick with version 2.3.0 of this module:
```
$ terraform version
Terraform v0.11.13
+ provider.aws v2.3.0
+ provider.external v1.1.0
+ provider.helm v0.9.0
+ provider.kubernetes v1.5.2
+ provider.local v1.2.0
+ provider.null v2.1.0
+ provider.random v2.1.0
+ provider.template v2.1.0
```
I assume it's not possible for terraform modules to specify requirements right?

**Comment by chenrui333** [comment]
it is possible, the syntax would be like this:
```
provider "aws" {
  version = ">= 1.24.0"
}
```

**Comment by alexsn** [comment]
@chenrui333 - Providers are normally defined in the root module (e.g. main.tf). See terraform [doc](https://www.terraform.io/docs/configuration/modules.html#providers-within-modules) section regarding this.

**Comment by chenrui333** [comment]
indeed, I just filed a PR regarding this. 😄

**Comment by JoshuaEdwards1991** [comment]
Just run:
`brew upgrade terraform`
`terraform init -upgrade`
`terraform get -update`
This will update your Terraform to the latest version, and upgrade your providers.

**Comment by max-rocket-internet** [comment]
Resolve in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/334

Thanks @chenrui333!
