### ISSUE TITLE
EKS Windows Preview

### ISSUE THREAD

**Issue by mnohai-mdsol** [terraform-aws-modules/terraform-aws-eks#335]
## I'm submitting a...
* [x] support request

Windows 2019 Worker nodes as seen in [eks-windows-preview](https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-windows-preview)

**Comment by jrob** [comment]
It's out of preview.

https://docs.aws.amazon.com/en_pv/eks/latest/userguide/windows-support.html

**Comment by max-rocket-internet** [comment]
Merged now
