### ISSUE TITLE
AssumeRole for autoscaling gives access denied

### ISSUE THREAD

**Issue by spaghettifunk** [terraform-aws-modules/terraform-aws-eks#336]
# I have issues

In scaling up the nodes when I am trying to schedule more pods that can fit the current nodes resources. Basically, the error stands in the role that is assumed. It seems that the policy attached is not sufficient (but it's a wild guess). Could be a configuration issue as well.

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request
* [ ] kudos, thank you, warm fuzzy 

## What is the current behavior?
From the logs of the `autoscaler` pod it comes out that the user has `AccessDenied` when trying to scale-up.

```
I0405 08:52:03.797003       1 factory.go:33] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cluster-autoscaler-status", UID:"804a1081-577c-11e9-9ebc-0a29a76a11fa", APIVersion:"v1", ResourceVersion:"131545", FieldPath:""}): type: 'Warning' reason: 'FailedToScaleUpGroup' Scale-up failed for group rtl-di-eks-cluster-xxxxxxxxxx: AccessDenied: User: arn:aws:sts::12345678912345:assumed-role/rtl-di-eks-cluster234567000000000001233/i-0d324j234h432423 is not authorized to perform: autoscaling:SetDesiredCapacity on resource: arn:aws:autoscaling:eu-west-1:12345678912345:autoScalingGroup:ed18a399-af83-4451-aa7d-cbd87525b536:autoScalingGroupName/rtl-di-eks-cluster-xxxxxxxxxx
	status code: 403, request id: 15614fdc-5780-11e9-a067-1b91a3898bb6
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

This is the configuration of my EKS

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "${terraform.workspace}-eks-cluster"
  subnets         = "${module.vpc_module.public_subnets}"
  manage_aws_auth = true
  cluster_version = "1.11"

  worker_groups = [
    {
      instance_type         = "m4.large"
      key_name              = "${module.key_module.key_name}"
      asg_desired_capacity  = 3
      asg_min_size          = 2
      asg_max_size          = 10
      autoscaling_enabled   = true
      protect_from_scale_in = true
    },
  ]

  tags = {
    Environment                         = "${terraform.workspace}"
    "k8s.io/cluster-autoscaler/enabled" = "true"
  }

  vpc_id = "${module.vpc_module.vpc_id}"
}
```

and this is the configuration of the `autoscaler` (I use the `helm provider` to install it)

```
resource "helm_release" "cluster-autoscaler" {
  name      = "cluster-autoscaler"
  namespace = "kube-system"
  chart     = "stable/cluster-autoscaler"

  set {
    name  = "rbac.create"
    value = "true"
  }

  set {
    name  = "autoDiscovery.clusterName"
    value = "rtl-di-eks-cluster"
  }

  set {
    name  = "awsRegion"
    value = "eu-west-1"
  }

  set {
    name  = "sslCertPath"
    value = "/etc/kubernetes/pki/ca.crt"
  }

  set {
    name  = "cloudProvider"
    value = "aws"
  }
}
```

## What's the expected behavior?

The `"user"` should be able to assume the role correctly and scale-up the nodes.

## Environment details

* Affected module version: `terraform-aws-modules/eks/aws 2.3.1`
* OS: `Mac OS X`
* Terraform version: `Terraform v0.11.13`

**Comment by max-rocket-internet** [comment]
I would remove the `"k8s.io/cluster-autoscaler/enabled" = "true"` tag from your TF code. The `autoscaling_enabled   = true` option in the worker group map will add this tag anyway. So I think perhaps due to this crossover, your tags are not setup correctly for [the condition in the IAM policy](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L220-L223)?

**Comment by spaghettifunk** [comment]
ahhhhhhhhhhh yes!! thank you very much :)
