### ISSUE TITLE
support EKS logs

### ISSUE THREAD

**Issue by confiq** [terraform-aws-modules/terraform-aws-eks#337]
## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?

We depend on the issue [8204](https://github.com/terraform-providers/terraform-provider-aws/issues/8204), but when that is implemented, we can configure logs for EKS. 

## Are you able to fix this problem and submit a PR? Link here if you have already.
Not yet

## Environment details
Terraform v0.11.13
+ provider.aws v2.4.0 <- can't work with this
+ provider.kubernetes v1.5.2
+ provider.local v1.1.0
+ provider.null v2.1.0
+ provider.template v1.0.0

## Any other relevant info

At the moment, we don't have requirements for AWS provider (correct me if I'm mistaken) but right now this module can't work with >v2.2 anyway (cluster_endpoints).
EDIT: Any suggestions on how to make provider aws version as a requirement?

**Comment by chenrui333** [comment]
it has been released as provider v2.6.0 :)

**Comment by max-rocket-internet** [comment]
And merged. Please test and I'll make a release soon.

**Comment by chenrui333** [comment]
Sure, I will do a quick check on this today.

**Comment by chenrui333** [comment]
BTW, if we want to release, we need to update the provider version in here too:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks_test_fixture/main.tf#L6

**Comment by confiq** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/347

I'm closing this issue

**Comment by chenrui333** [comment]
I forgot to update here, I have run with aws provider 2.6.0 for last weekend without any issue.

**Comment by chenrui333** [comment]
@max-rocket-internet I think we do need to enforce the provider version with the new feature of eks logs.

**Comment by confiq** [comment]
@chenrui333 the question is how? according to the https://github.com/terraform-aws-modules/terraform-aws-eks/pull/347/files , we only update example how to use the module

**Comment by chenrui333** [comment]
yeah, indeed, I was think of enforcing the module version in the module level. 

You might be interested with this issue I submitted, https://github.com/hashicorp/terraform/issues/20996

**Comment by chenrui333** [comment]
For now, I might gonna update the provider version.

**Comment by max-rocket-internet** [comment]
> I think we do need to enforce the provider version with the new feature of eks logs.

Indeed. I'm not sure how though. I think in the past we had providers defined inside the module itself but then TF community moved away from this I think?

**Comment by max-rocket-internet** [comment]
Already had a issue for this: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/348
