### ISSUE TITLE
Mark kubeconfig output as "sensitive"

### ISSUE THREAD

**Issue by discordianfish** [terraform-aws-modules/terraform-aws-eks#344]
## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
The kubeconfig output is not marked sensitive, so terraform logs it.

## What's the expected behavior?
It shouldn't be logged since it's highly sensitive.

## Are you able to fix this problem and submit a PR? Link here if you have already.
Should be straight forward, will send a PR soon.

**Comment by max-rocket-internet** [comment]
But it's not sensitive? There's no credentials in it 🙂

**Comment by discordianfish** [comment]
@max-rocket-internet You're right, I didn't realize that when I opened the issue. Sorry about the noise! :)
