### ISSUE TITLE
Is the VPC tagged automatically - by the eks  resource? (kubernetes.io/cluster/<cluster-name>)

### ISSUE THREAD

**Issue by javapapo** [terraform-aws-modules/terraform-aws-eks#345]
Hello

According to AWS documentation here: https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html , EKS will tag accordingly the VPC. 
Does this happen behind the scenes?

We have spinned a couple of clusters using terraform using standard stuff like

```yaml
resource "aws_eks_cluster" "example" {
  enabled_cluster_log_types = ["api", "audit"]
  name                      = "example"
  role_arn                  = "${aws_iam_role.example.arn}"

  vpc_config {
    subnet_ids = ["${aws_subnet.example1.id}", "${aws_subnet.example2.id}"]
  }
}
```

But when I check the `tags` on the VPCs I dont see the tag

```bash
kubernetes.io/cluster/<cluster-name>
```

Is it something that is supposed to happen, do I have to do it manually? or small bug?

Thanks for any tips

**Comment by javapapo** [comment]
Is there any case - this happens only the first upon initial provisioning - and then if another stack -updates the VPCs, the tag gets lost ?

**Comment by javapapo** [comment]
Another stack is - nuking the tags

**Comment by max-rocket-internet** [comment]
I've never seen the tags on VPCs but other people seem to mention it.

**Comment by javapapo** [comment]
^^ yes EKS adds tags in the VPC level and in certain subnets
