### ISSUE TITLE
terraform plan fails after upgrading from 2.3.1 to 3.0.0

### ISSUE THREAD

**Issue by cwiggs** [terraform-aws-modules/terraform-aws-eks#348]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
`terraform plan` fails with this error: `Error: module.eks.aws_eks_cluster.this: : invalid or unknown key: enabled_cluster_log_types`

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Update version from 2.3.1 to 3.0.0, run `terraform plan`

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "3.0.0"
  cluster_name    = "${local.cluster_name}"
  kubeconfig_name = "${local.cluster_name}"
  subnets         = "${local.subnets}"
  tags            = "${local.tags}"
  vpc_id          = "${local.vpc_id}"

  cluster_endpoint_private_access = "${var.cluster_endpoint_private_access}"
  cluster_enabled_log_types = []

  worker_groups      = "${local.worker_groups}"
  worker_group_count = "${length(local.worker_groups)}"

  map_users = "${local.map_users}"
  map_roles = "${local.map_roles}"

  map_users_count = "${length(local.map_users)}"
  map_roles_count = "${length(local.map_roles)}"

  write_aws_auth_config = "${var.write_aws_auth_config}"
  write_kubeconfig      = "${var.write_kubeconfig}"

  # Set up the aws profile for aws-iam-authenticator:
  kubeconfig_aws_authenticator_env_variables = {
    AWS_PROFILE = "${var.aws_profile}"
  }
}
```

## What's the expected behavior?
`terraform plan` should succeed.

## Are you able to fix this problem and submit a PR? Link here if you have already.
Yes

## Environment details

* Affected module version: 3.0.0
* OS: MacOS 10.13.4
* Terraform version: v0.11.13
* provider.aws v2.6.0

**Comment by cwiggs** [comment]
Looks like running a `terraform init -upgrade=true` updated the AWS provider form 2.4.0 to 2.6.0 and that fixed the issue.

**Comment by syst0m** [comment]
@cwiggs Isn't the latest AWS provider version 2.13.0? 
https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md

I'm also experiencing the same issue as you, after upgrading from 2.31 to 4.0.2.
