### ISSUE TITLE
Config map + EKS Private Endpoint

### ISSUE THREAD

**Issue by tacf** [terraform-aws-modules/terraform-aws-eks#356]
Hey, this is not actually an issue, most probably some lack on knowledge on my side on how to fix this.

The setup i'm trying to achieve is that of having a EKS cluster with access only through a Baistion. Problem is that since i'm removing the public endpoint there seems no way of terraform applying the auth config map (wich makes sense since the endpoint is not publicly available) which leads to nodes not being able to join.

How do you guys usually work around this issue?

Thanks in advance

**Comment by RothAndrew** [comment]
I guess run the terraform script from the bastion?

**Comment by tacf** [comment]
No, i'm provision EKS + Bastion externally.

**Comment by max-rocket-internet** [comment]
Terraform runs `kubectl` to apply the configmap. So either:
1. Set `manage_aws_auth` to false and apply it manually from the bastion yourself
2. Run Terraform from the bastion

It's not more complicated than that. I guess a third option could could be to set up some SSH port forwarding though 🙂

**Comment by tacf** [comment]
Yup, i guess that's basically it. Just wanted to make sure i'm not missing something :)
