### ISSUE TITLE
Missing aws-iam-authenticator should fail apply

### ISSUE THREAD

**Issue by pcj** [terraform-aws-modules/terraform-aws-eks#357]
During an apply of this module it would be preferable to hard-stop and fail the apply if relevant tools are not present, including aws-iam-authenticator.  As it is the apply happily continues on, creating a false sense of success.

Recommend using the `on_failure = "fail"` option for local-exec:

 https://github.com/terraform-aws-modules/terraform-aws-eks/blob/d3c1bd623798f020f87f89d1778a51220396d03a/aws_auth.tf#L10-L33

Related #341

**Comment by max-rocket-internet** [comment]
I think this is a duplicate. Please add your thoughts to the existing issue 🙂
