### ISSUE TITLE
Support multiple instance types in ASG with Launch Templates

### ISSUE THREAD

**Issue by max-rocket-internet** [terraform-aws-modules/terraform-aws-eks#360]
# I have issues

I'm submitting a feature request

## What is the current behaviour?

When using Launch Templates via the `worker_groups_launch_template`, you can only have 2 instances types per worker group. It's set [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/18baeea1fce469a95170889b52d6e3aebb15727e/workers_launch_template.tf#L28-L34) and has a fixed limit of 2 different types, the minimum.

## What's the expected behaviour?

You can have up to 20 different instances types in the ASG. Having a broad Mixed Instances Policy is very important when using spot instances as you want a diverse selection of types so that when a spot prices goes to or above the on-demand price, another type can be used.

## Are you able to fix this problem and submit a PR? Link here if you have already.

I don't think so.

We can simply add more `override` sections to `aws_autoscaling_group.workers_launch_template.mixed_instances_policy.launch_template`, e.g.:

```hcl
    launch_template {
      override {
        instance_type = "${lookup(var.worker_groups_launch_template[count.index], "instance_type", local.workers_group_launch_template_defaults["instance_type"])}"
      }

      override {
        instance_type = "${lookup(var.worker_groups_launch_template[count.index], "override_instance_type", local.workers_group_launch_template_defaults["override_instance_type"])}"
      }

      override {
        instance_type = "${lookup(var.worker_groups_launch_template[count.index], "override_instance_type_1", "")}"
      }

      override {
        instance_type = "${lookup(var.worker_groups_launch_template[count.index], "override_instance_type_2", "")}"
      }
```

But we need default values for each override in case they are not used. If we use `""` like above, terraform applies the change on every `terraform apply`:

```
  ~ module.cluster1.aws_autoscaling_group.workers_launch_template[0]
      mixed_instances_policy.0.launch_template.0.override.#: "2" => "4"

  ~ module.cluster1.aws_autoscaling_group.workers_launch_template[1]
      mixed_instances_policy.0.launch_template.0.override.#: "2" => "4"
```

I'm not sure how to fix this. Even if we could define the LT outside of the module, it wouldn't help because the instances types are defined on the ASG.

**Comment by max-rocket-internet** [comment]
I think it's a provider issue: https://github.com/terraform-providers/terraform-provider-aws/issues/8475

**Comment by max-rocket-internet** [comment]
Fixed in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/371

**Comment by thuandt** [comment]
@max-rocket-internet 

I tried to use this module (4.0.2) with `worker_group_launch_template_mixed` follow this [docs](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v4.0.2/docs/spot-instances.md) but terraform return error

`Error: module "eks": "worker_group_launch_template_mixed" is not a valid argument`.

Can you help me understand what is right way to use eks workers module with mixed_instances_policy?
