### ISSUE TITLE
worker_groups target_group_arns throws error. 

### ISSUE THREAD

**Issue by Dahs81** [terraform-aws-modules/terraform-aws-eks#366]
# I have issues

## I'm submitting a...

* [x ] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

When I provide a custom target_group_arns to the worker_groups, it throws this error:

```
module.test-cluster.aws_autoscaling_group.workers: lookup: lookup() may only be used with flat maps, this map contains elements of type list in:

${compact(split(",", coalesce(lookup(var.worker_groups[count.index], "target_group_arns", ""), local.workers_group_defaults["target_group_arns"])))}
```

Because there is a list inside of the map, terraform will not handle this case.

I also attempted to add it to the workers_group_defaults like this. but it just ignored that:

```
  workers_group_defaults {
      target_group_arns = [
        "${aws_lb_target_group.nginx_lb_tg_http.arn}",
        "${aws_lb_target_group.nginx_lb_tg_https.arn}",
      ]
    }
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

1. Create an nlb and 2 target groups
1. Add the `target_group_arns` to the `worker_groups` map

```
worker_groups = [
    {
      instance_type        = "m4.large"
      asg_desired_capacity = 3
      asg_max_size         = 5
      asg_min_size         = 2
      subnets              = "${join(",", module.vpc.private_subnets)}"

      target_group_arns = [
        "${aws_lb_target_group.nginx_lb_tg_http.arn}",
        "${aws_lb_target_group.nginx_lb_tg_https.arn}",
      ]
    },
  ]
```

## What's the expected behavior?

It should add the target groups to the asg

## Are you able to fix this problem and submit a PR? Link here if you have already.

I will attempt to fix it, but I'm not 100% sure why terraform doesn't work for maps with lists in them yet.

I'd like to see if anyone else has a workaround for this before I jump into it.

## Environment details

Running on local macbook.

* Affected module version: master
* OS: MacOS
* Terraform version: v0.11.7
                                   provider.aws v2.8.0

## Any other relevant info

It seems that there are several other properties inside of workers.tf that are using something similar:

```
["${compact(split(",", coalesce(lookup(var.worker_groups[count.index], "PROPERTY_NAME", ""), local.workers_group_defaults["PROPERTY_NAME"])))}"]
```

i.e. suspended_processes, enabled_metrics, vpc_zone_identifier, and target_group_arns.

**Comment by Dahs81** [comment]
Nevermind, I figured it out. It turns out the authors have it where the user passes in a string of arns and not a list, which then gets compacted into a list for the underlying aws_asg to use.

Here's an example, just in case others run across this:

```
worker_groups = [
    {
      instance_type        = "m4.large"
      asg_desired_capacity = 2
      asg_max_size         = 5
      asg_min_size         = 2
      subnets              = "${join(",", module.vpc.private_subnets)}"

      target_group_arns = "${aws_lb_target_group.nginx_lb_tg_http.arn},${aws_lb_target_group.nginx_lb_tg_https.arn}",
    },
  ]
```

Closing.

**Comment by max-rocket-internet** [comment]
> It turns out the authors have it where the user passes in a string of arns and not a list, which then gets compacted into a list for the underlying aws_asg to use.

Correct. To be clear, this is a Terraform limitation where you can't merge a list inside a map. So we make a list into a long string, then merge, then split.

Hopefully when Terraform 0.12 is released we can remove this annoying workarounds 😃
