### ISSUE TITLE
We should ignore changes to node ASG desired_capacity

### ISSUE THREAD

**Issue by max-rocket-internet** [terraform-aws-modules/terraform-aws-eks#38]
# I have issues

## I'm submitting a

* [ ] feature request

The reason is that after cluster creation, almost everyone will run the [k8s node autoscaler](https://github.com/kubernetes/autoscaler). This autoscaler is changing the `desired_capacity` to suit resources required by the cluster. So when the cluster autoscales, then TF is run again later, you see something like this:

```
  ~ module.cluster_1.aws_autoscaling_group.workers
      desired_capacity:   "5" => "3"
```

You can just add a lifecycle statement to resource `aws_autoscaling_group.workers`:

```
  lifecycle {
    ignore_changes = [ "desired_capacity" ]
  }
```

**Comment by brandoconnor** [comment]
Heh you're on the same wavelength as @ozbillwang . He submitted this exact change 16 hours ago here: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/36/files

I'll close this now and plan to release over the next day or so. Closing this up.
