### ISSUE TITLE
Remove instances_distribution definition in the workers_launch_template.tf

### ISSUE THREAD

**Issue by Janesee3** [terraform-aws-modules/terraform-aws-eks#380]
## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [X] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Even though I set the `spot_instance_pool = 0` in  the `workers_launch_template` definition, a number of extra instances (as specified in the `instances_distribution` definition found in the `workers_launch_template.tf`) are spun up.

## What's the expected behavior?
Should have ability to turn off or remove the `instances_distribution` definition

## Environment details

* Affected module version: 2.3.1
* Terraform version: 1.11.X

**Comment by max-rocket-internet** [comment]
`instances_distribution` is not in `workers_launch_template.tf`. So I think you are using an older version of the module or you mean `workers_launch_template.tf`?

**Comment by max-rocket-internet** [comment]
Ah yes, you wrote:

> Affected module version: 2.3.1

I fixed this issue in version `v4.0.2` by splitting the launch template stuff into 2 parts:

- workers_launch_template
- workers_launch_template_mixed

**Comment by max-rocket-internet** [comment]
I hope that makes sense! Please update this issue if you have issues with the new arrangement.

**Comment by Janesee3** [comment]
Oh I see, thanks for the prompt reply! I will try that out
