### ISSUE TITLE
no error when terraform apply, but get node "No resources found."

### ISSUE THREAD

**Issue by phuthinh2202** [terraform-aws-modules/terraform-aws-eks#388]
# I have issues
no error appear when i enter "terraform apply", but when it done, i get view node, it say "no resources found".

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ v] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

`$ kubectl get all --all-namespaces=true
NAMESPACE     NAME                           READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-6446cc57d9-ctntj   0/1     Pending   0          9m31s
kube-system   pod/coredns-6446cc57d9-tnwl6   0/1     Pending   0          9m31s

NAMESPACE     NAME                 TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
default       service/kubernetes   ClusterIP   172.20.0.1    <none>        443/TCP         9m41s
kube-system   service/kube-dns     ClusterIP   172.20.0.10   <none>        53/UDP,53/TCP   9m41s

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/aws-node     0         0         0       0            0           <none>          9m31s
kube-system   daemonset.apps/kube-proxy   0         0         0       0            0           <none>          9m36s

NAMESPACE     NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   2         2         2            0           9m31s

NAMESPACE     NAME                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-6446cc57d9   2         2         0       9m32s
$ kubectl get all --all-namespaces=true
NAMESPACE     NAME                           READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-6446cc57d9-ctntj   0/1     Pending   0          13m
kube-system   pod/coredns-6446cc57d9-tnwl6   0/1     Pending   0          13m

NAMESPACE     NAME                 TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
default       service/kubernetes   ClusterIP   172.20.0.1    <none>        443/TCP         13m
kube-system   service/kube-dns     ClusterIP   172.20.0.10   <none>        53/UDP,53/TCP   13m

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/aws-node     0         0         0       0            0           <none>          13m
kube-system   daemonset.apps/kube-proxy   0         0         0       0            0           <none>          13m

NAMESPACE     NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   2         2         2            0           13m

NAMESPACE     NAME                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-6446cc57d9   2         2         0       13m
$ kubectl get configmaps
No resources found.
$ kubectl --namespace=kube-system get configmap
NAME                                 DATA   AGE
aws-auth                             3      11m
coredns                              1      17m
extension-apiserver-authentication   5      17m
kube-proxy                           1      17m
kube-proxy-config                    1      17m
$ kubectl get nodes
No resources found.`

## Environment details

* Affected module version: 4.0.2
* OS: MacOS
* Terraform version:
Terraform v0.11.13
+ provider.aws v2.13.0
+ provider.local v1.2.2
+ provider.null v2.1.2
+ provider.template v2.1.2

**Comment by phuthinh2202** [comment]
I use "worker_groups_launch_template_mixed" no work, but when i change to worker_group like example:
`  worker_groups = [
    {
      name                = "on-demand-1"
      instance_type       = "m4.xlarge"
      asg_max_size        = 1
      autoscaling_enabled = true
      kubelet_extra_args  = "--node-labels=kubernetes.io/lifecycle=normal"
      suspended_processes = "AZRebalance"
    },
    {
      name                = "spot-1"
      spot_price          = "0.199"
      instance_type       = "c4.xlarge"
      asg_max_size        = 20
      autoscaling_enabled = true
      kubelet_extra_args  = "--node-labels=kubernetes.io/lifecycle=spot"
      suspended_processes = "AZRebalance"
    },
    {
      name                = "spot-2"
      spot_price          = "0.20"
      instance_type       = "m4.xlarge"
      asg_max_size        = 20
      autoscaling_enabled = true
      kubelet_extra_args  = "--node-labels=kubernetes.io/lifecycle=spot"
      suspended_processes = "AZRebalance"
    }
  ]`

then work.

**Comment by max-rocket-internet** [comment]
Hi @phuthinh2202, this is normally because either:

1. Nodes can't reach EKS endpoint. (e.g. in private subnet)
2. Nodes can't authenticate to EKS service. (e.g. the `aws-auth` configmap was not applied, wrong instance profile, etc)

Maybe have a look at these similar issues:
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/358
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/310
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/304

**Comment by phuthinh2202** [comment]
the different between "no work" with "worked", i just edit from "worker_groups_launch_template_mixed" to use "worker_groups" and about the result is same, include the aws-auth configmap was created. :D

**Comment by max-rocket-internet** [comment]
So it's resolved?

**Comment by phuthinh2202** [comment]
yah, i used "worker_group" have no problem. I can access my eks cluster, but all worker have public ipv4, althrough i have set public_ip = false in "worker_group" object.
