### ISSUE TITLE
how to handle vpc dns options?

### ISSUE THREAD

**Issue by hhuuggoo** [terraform-aws-modules/terraform-aws-eks#389]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ x] support request
* [x ] kudos, thank you, warm fuzzy

I'm working with a VPC that has dhcp options setup with multiple domain names.  In my case I have 2 domains in the search path

- us-east-2.compute.internal
- mycorp.internal

The problem I run into, is that according to:  [aws docs](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html#DHCPOptions), 

"Some Linux operating systems accept multiple domain names separated by spaces. However, other Linux operating systems and Windows treat the value as a single domain, which results in unexpected behavior. If your DHCP options set is associated with a VPC that has instances with multiple operating systems, specify only one domain name."

This appears to be the case with the amazon linux eks ami - I get a hostname that looks like this: `ip-10-0-1-199.us-east-2.compute.internalmycorp.internal`.  This is a problem, because in our case, it exceeds the 63 character limit for the kubernetes hostname metadata tag, and nodes cannot join the cluster.

Has anyone dealt with this, or has suggestions work workarounds?

**Comment by okgolove** [comment]
Hi @hhuuggoo! Have you found a workaround?

**Comment by barryib** [comment]
How this is related to terraform-aws-eks module ? This module will only deploy EKS.

**Comment by diclophis** [comment]
@okgolove / @hhuuggoo cross check your DHCP options set in AWS for multiple `domain-name` options ... I think its a limitation in the AWS EKS AMI ...

**Comment by okgolove** [comment]
@diclophis I think this is kubelet feature, not EKS. I've checked kubelet cloud code related to AWS and nodename is requested from EC2 metadata if you use --cloud=aws. And you can do nothing to that. 🤷‍♂️
