### ISSUE TITLE
Additional worker IAM role assume role policy

### ISSUE THREAD

**Issue by toughrogrammer** [terraform-aws-modules/terraform-aws-eks#391]
# I have issues

I'm using kiam and it needs trust relationship to kiam server IAM role. But there is no way to specify additional assume role policy for `aws_iam_role.workers`

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

`awm_iam_role.workers` use `data.aws_iam_policy_document.workers_assume_role_policy.json` and `data.aws_iam_policy_document.workers_assume_role_policy` has `ec2.amazonaws.com` principals only.

## What's the expected behavior?

There should be additional principal variables.

**Comment by mariogeorgievft** [comment]
We are currently experiencing the same issue. 
Changing the whole role for the workers is also not possible, 

Any ways to circumvent this? 

Best Regards, 

Mario
