### ISSUE TITLE
Resource 'data.aws_eks_cluster_auth.cluster-auth' does not have attribute 'token' for variable 'data.aws_eks_cluster_auth.cluster-auth.token

### ISSUE THREAD

**Issue by SubhakarKotta** [terraform-aws-modules/terraform-aws-eks#397]
When destroying the cluster using terraform facing the below issue

+ terraform version
Terraform v0.11.14

Your version of Terraform is out of date! The latest version
is 0.12.2. You can update by downloading from www.terraform.io/downloads.html
[Pipeline] sh
+ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
[Pipeline] sh
+ helm version --client
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
[Pipeline] sh
+ aws --version
aws-cli/1.16.180 Python/2.7.16 Linux/3.10.0-957.5.1.el7.x86_64 botocore/1.12.170

```hcl

data "aws_eks_cluster_auth" "cluster-auth" {
  name       = "${module.eks.cluster_id}"
  depends_on = ["module.eks"]
}

provider "kubernetes" {
  host                   = "${module.eks.cluster_endpoint}"
  cluster_ca_certificate = "${base64decode(module.eks.cluster_certificate_authority_data)}"
  token                  = "${data.aws_eks_cluster_auth.cluster-auth.token}"
}

resource "kubernetes_service_account" "tiller" {
  metadata {
    name      = "tiller"
    namespace = "kube-system"
  }
  automount_service_account_token = true
}

resource "kubernetes_cluster_role_binding" "tiller" {
  metadata {
    name = "tiller"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "cluster-admin"
  }

  subject {
    kind      = "ServiceAccount"
    name      = "tiller"
    namespace = "kube-system"
  }

  depends_on = [
    "kubernetes_service_account.tiller",
  ]
}

provider "helm" {
  install_tiller  = true
  tiller_image    = "gcr.io/kubernetes-helm/tiller:v2.14.0"
  service_account = "${kubernetes_service_account.tiller.metadata.0.name}"
  namespace       = "${kubernetes_service_account.tiller.metadata.0.namespace}"

  kubernetes {
    host                   = "${module.eks.cluster_endpoint}"
    cluster_ca_certificate = "${base64decode(module.eks.cluster_certificate_authority_data)}"
    token                  = "${data.aws_eks_cluster_auth.cluster-auth.token}"
  }
}
data "helm_repository" "incubator" {
  name       = "incubator"
  url        = "https://kubernetes-charts-incubator.storage.googleapis.com"
  depends_on = ["kubernetes_service_account.tiller", "kubernetes_cluster_role_binding.tiller"]
}

data "helm_repository" "stable" {
  name       = "stable"
  url        = "https://kubernetes-charts.storage.googleapis.com/"
  depends_on = ["kubernetes_service_account.tiller", "kubernetes_cluster_role_binding.tiller"]
}

resource "helm_release" "mydatabase" {
  name  = "mydatabase"
  chart = "stable/mariadb"

  set {
    name  = "mariadbUser"
    value = "foo"
  }

  set {
    name  = "mardiadbPassword"
    value = "qux"
  }

  depends_on = [
    "kubernetes_service_account.tiller",
  ]
}
```

null_resource.tags_as_list_of_maps: Refreshing state... (ID: 7438599710236361932)
data.aws_caller_identity.current: Refreshing state...
aws_vpc.this: Refreshing state... (ID: vpc-043cc44e12b6b7997)
aws_db_parameter_group.this: Refreshing state... (ID: demo-cloud-20190618062309913200000002)
data.aws_region.current: Refreshing state...
data.aws_ami.eks_worker: Refreshing state...
data.aws_iam_policy_document.cluster_assume_role_policy: Refreshing state...
data.aws_iam_policy_document.workers_assume_role_policy: Refreshing state...
aws_iam_role.cluster: Refreshing state... (ID: demo-cloud20190618062309913000000001)
aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy: Refreshing state... (ID: demo-cloud20190618062309913000000001-20190618062312939900000004)
aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy: Refreshing state... (ID: demo-cloud20190618062309913000000001-20190618062312898000000003)
aws_security_group.cluster: Refreshing state... (ID: sg-035f8f31f3b1a83d7)
aws_security_group.sec_grp_rds: Refreshing state... (ID: sg-09aa24bc314c0c13c)
aws_route_table.public: Refreshing state... (ID: rtb-0889dfd28ece1ddd8)
aws_internet_gateway.this: Refreshing state... (ID: igw-0dd43030d8cf9112c)
aws_subnet.public[1]: Refreshing state... (ID: subnet-0b3dea78cacbd1792)
aws_subnet.public[0]: Refreshing state... (ID: subnet-008bd053195f09396)
aws_route.public_internet_gateway: Refreshing state... (ID: r-rtb-0889dfd28ece1ddd81080289494)
aws_security_group_rule.cluster_egress_internet: Refreshing state... (ID: sgrule-3119464060)
aws_route_table_association.public[0]: Refreshing state... (ID: rtbassoc-09d786d2e620c5ebc)
aws_db_subnet_group.this: Refreshing state... (ID: demo-cloud-20190618062334879500000007)
aws_route_table_association.public[1]: Refreshing state... (ID: rtbassoc-0fa94cec4dcdec932)
aws_eks_cluster.this: Refreshing state... (ID: demo-cloud)
aws_security_group.workers: Refreshing state... (ID: sg-05ccde5a268bccccb)
aws_iam_role.workers: Refreshing state... (ID: demo-cloud20190618063338490400000009)
data.template_file.kubeconfig: Refreshing state...
data.aws_iam_policy_document.worker_autoscaling: Refreshing state...
local_file.kubeconfig: Refreshing state... (ID: 9f93fd1fc1dd67cb9291b222159319a0bd8ef13b)
aws_iam_policy.worker_autoscaling: Refreshing state... (ID: arn:aws:iam::045654838477:policy/eks-wo...g-demo-cloud2019061806333849420000000a)
aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly: Refreshing state... (ID: demo-cloud20190618063338490400000009-2019061806334179330000000e)
aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy: Refreshing state... (ID: demo-cloud20190618063338490400000009-2019061806334176090000000c)
aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy: Refreshing state... (ID: demo-cloud20190618063338490400000009-2019061806334177670000000d)
aws_iam_instance_profile.workers: Refreshing state... (ID: demo-cloud2019061806334079190000000b)
data.template_file.userdata: Refreshing state...
aws_db_instance.this: Refreshing state... (ID: demo-cloud)
aws_security_group_rule.workers_ingress_cluster_https: Refreshing state... (ID: sgrule-926181831)
aws_security_group_rule.cluster_https_worker_ingress: Refreshing state... (ID: sgrule-2266076286)
aws_security_group_rule.workers_ingress_self: Refreshing state... (ID: sgrule-3143625132)
aws_security_group_rule.workers_ingress_cluster: Refreshing state... (ID: sgrule-566156914)
aws_security_group_rule.allow-workers-nodes-communications: Refreshing state... (ID: sgrule-1673000143)
aws_security_group_rule.workers_egress_internet: Refreshing state... (ID: sgrule-247314009)
aws_iam_role_policy_attachment.workers_autoscaling: Refreshing state... (ID: demo-cloud20190618063338490400000009-2019061806334251930000000f)
data.template_file.worker_role_arns: Refreshing state...
aws_launch_configuration.workers: Refreshing state... (ID: demo-cloud-020190618063350673700000010)
data.template_file.config_map_aws_auth: Refreshing state...
null_resource.update_config_map_aws_auth: Refreshing state... (ID: 3129622494010781780)
local_file.config_map_aws_auth: Refreshing state... (ID: da04506ac539e1691867092664f64ffc39f9ad3b)
aws_autoscaling_group.workers: Refreshing state... (ID: demo-cloud-020190618063354975700000011)
kubernetes_service_account.tiller: Refreshing state... (ID: kube-system/tiller)
kubernetes_cluster_role_binding.tiller: Refreshing state... (ID: tiller)
helm_release.mydatabase: Refreshing state... (ID: mydatabase)
module.eks.null_resource.update_config_map_aws_auth: Destroying... (ID: 3129622494010781780)
module.eks.null_resource.update_config_map_aws_auth: Destruction complete after 0s
module.eks.aws_iam_role_policy_attachment.workers_autoscaling: Destroying... (ID: demo-cloud20190618063338490400000009-2019061806334251930000000f)
module.eks.aws_security_group_rule.workers_ingress_self: Destroying... (ID: sgrule-3143625132)
aws_security_group_rule.allow-workers-nodes-communications: Destroying... (ID: sgrule-1673000143)
module.vpc.aws_route_table_association.public[0]: Destroying... (ID: rtbassoc-09d786d2e620c5ebc)
module.eks.aws_security_group_rule.workers_egress_internet: Destroying... (ID: sgrule-247314009)
module.eks.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy: Destroying... (ID: demo-cloud20190618063338490400000009-2019061806334176090000000c)
module.db.module.db_instance.aws_db_instance.this: Destroying... (ID: demo-cloud)
module.eks.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly: Destroying... (ID: demo-cloud20190618063338490400000009-2019061806334179330000000e)
module.eks.aws_security_group_rule.workers_ingress_cluster_https: Destroying... (ID: sgrule-926181831)
module.eks.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy: Destroying... (ID: demo-cloud20190618063338490400000009-2019061806334177670000000d)
module.eks.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy: Destruction complete after 1s
module.eks.aws_security_group_rule.cluster_https_worker_ingress: Destroying... (ID: sgrule-2266076286)
module.eks.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy: Destruction complete after 1s
module.eks.aws_security_group_rule.cluster_egress_internet: Destroying... (ID: sgrule-3119464060)
module.eks.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly: Destruction complete after 1s
module.vpc.aws_route.public_internet_gateway: Destroying... (ID: r-rtb-0889dfd28ece1ddd81080289494)
module.eks.aws_iam_role_policy_attachment.workers_autoscaling: Destruction complete after 1s
module.eks.aws_autoscaling_group.workers: Destroying... (ID: demo-cloud-020190618063354975700000011)
module.vpc.aws_route_table_association.public[0]: Destruction complete after 1s
module.vpc.aws_route_table_association.public[1]: Destroying... (ID: rtbassoc-0fa94cec4dcdec932)
module.vpc.aws_route.public_internet_gateway: Destruction complete after 1s
module.eks.aws_security_group_rule.workers_ingress_cluster: Destroying... (ID: sgrule-566156914)
module.vpc.aws_route_table_association.public[1]: Destruction complete after 2s
module.eks.aws_iam_policy.worker_autoscaling: Destroying... (ID: arn:aws:iam::045654838477:policy/eks-wo...g-demo-cloud2019061806333849420000000a)
module.eks.aws_security_group_rule.workers_ingress_self: Destruction complete after 3s
module.vpc.aws_internet_gateway.this: Destroying... (ID: igw-0dd43030d8cf9112c)
aws_security_group_rule.allow-workers-nodes-communications: Destruction complete after 3s
module.vpc.aws_route_table.public: Destroying... (ID: rtb-0889dfd28ece1ddd8)
module.eks.aws_security_group_rule.cluster_https_worker_ingress: Destruction complete after 3s
module.eks.aws_iam_policy.worker_autoscaling: Destruction complete after 1s
module.eks.aws_security_group_rule.workers_egress_internet: Destruction complete after 5s
module.eks.aws_security_group_rule.cluster_egress_internet: Destruction complete after 5s
module.vpc.aws_route_table.public: Destruction complete after 4s
module.eks.aws_security_group_rule.workers_ingress_cluster_https: Destruction complete after 8s
module.db.db_instance.aws_db_instance.this: Still destroying... (ID: demo-cloud, 10s elapsed)
module.eks.aws_security_group_rule.workers_ingress_cluster: Destruction complete after 7s
module.eks.aws_autoscaling_group.workers: Still destroying... (ID: demo-cloud-020190618063354975700000011, 10s elapsed)
module.vpc.aws_internet_gateway.this: Still destroying... (ID: igw-0dd43030d8cf9112c, 10s elapsed)
module.db.db_instance.aws_db_instance.this: Still destroying... (ID: demo-cloud, 20s elapsed)
module.eks.aws_autoscaling_group.workers: Still destroying... (ID: demo-cloud-020190618063354975700000011, 20s elapsed)
module.vpc.aws_internet_gateway.this: Still destroying... (ID: igw-0dd43030d8cf9112c, 20s elapsed)
module.db.db_instance.aws_db_instance.this: Still destroying... (ID: demo-cloud, 30s elapsed)
module.eks.aws_autoscaling_group.workers: Still destroying... (ID: demo-cloud-020190618063354975700000011, 30s elapsed)
module.vpc.aws_internet_gateway.this: Still destroying... (ID: igw-0dd43030d8cf9112c, 30s elapsed)
module.db.db_instance.aws_db_instance.this: Still destroying... (ID: demo-cloud, 40s elapsed)
module.eks.aws_autoscaling_group.workers: Still destroying... (ID: demo-cloud-020190618063354975700000011, 40s elapsed)
module.vpc.aws_internet_gateway.this: Still destroying... (ID: igw-0dd43030d8cf9112c, 40s elapsed)
module.db.db_instance.aws_db_instance.this: Still destroying... (ID: demo-cloud, 50s elapsed)
module.eks.aws_autoscaling_group.workers: Still destroying... (ID: demo-cloud-020190618063354975700000011, 50s elapsed)
module.vpc.aws_internet_gateway.this: Still destroying... (ID: igw-0dd43030d8cf9112c, 50s elapsed)
module.vpc.aws_internet_gateway.this: Destruction complete after 54s
module.db.db_instance.aws_db_instance.this: Still destroying... (ID: demo-cloud, 1m0s elapsed)
module.eks.aws_autoscaling_group.workers: Still destroying... (ID: demo-cloud-020190618063354975700000011, 1m0s elapsed)
module.db.db_instance.aws_db_instance.this: Still destroying... (ID: demo-cloud, 1m10s elapsed)
module.eks.aws_autoscaling_group.workers: Still destroying... (ID: demo-cloud-020190618063354975700000011, 1m10s elapsed)
module.db.db_instance.aws_db_instance.this: Still destroying... (ID: demo-cloud, 1m20s elapsed)
module.eks.aws_autoscaling_group.workers: Still destroying... (ID: demo-cloud-020190618063354975700000011, 1m20s elapsed)
module.eks.aws_autoscaling_group.workers: Destruction complete after 1m22s
module.eks.null_resource.tags_as_list_of_maps: Destroying... (ID: 7438599710236361932)
module.eks.aws_launch_configuration.workers: Destroying... (ID: demo-cloud-020190618063350673700000010)
module.eks.null_resource.tags_as_list_of_maps: Destruction complete after 0s
module.eks.aws_launch_configuration.workers: Destruction complete after 1s
module.eks.aws_iam_instance_profile.workers: Destroying... (ID: demo-cloud2019061806334079190000000b)
module.eks.aws_security_group.workers: Destroying... (ID: sg-05ccde5a268bccccb)
module.eks.aws_iam_instance_profile.workers: Destruction complete after 2s
module.eks.aws_iam_role.workers: Destroying... (ID: demo-cloud20190618063338490400000009)
module.eks.aws_security_group.workers: Destruction complete after 3s
module.db.db_instance.aws_db_instance.this: Still destroying... (ID: demo-cloud, 1m30s elapsed)
module.eks.aws_iam_role.workers: Destruction complete after 4s
module.db.db_instance.aws_db_instance.this: Still destroying... (ID: demo-cloud, 1m40s elapsed)
module.db.db_instance.aws_db_instance.this: Still destroying... (ID: demo-cloud, 1m50s elapsed)
module.db.db_instance.aws_db_instance.this: Still destroying... (ID: demo-cloud, 2m0s elapsed)
module.db.module.db_instance.aws_db_instance.this: Destruction complete after 2m4s
aws_security_group.sec_grp_rds: Destroying... (ID: sg-09aa24bc314c0c13c)
module.db.module.db_parameter_group.aws_db_parameter_group.this: Destroying... (ID: demo-cloud-20190618062309913200000002)
module.db.module.db_subnet_group.aws_db_subnet_group.this: Destroying... (ID: demo-cloud-20190618062334879500000007)
module.db.module.db_subnet_group.aws_db_subnet_group.this: Destruction complete after 1s
module.db.module.db_parameter_group.aws_db_parameter_group.this: Destruction complete after 1s
aws_security_group.sec_grp_rds: Destruction complete after 3s

Error: Error applying plan:

2 errors occurred:
	* provider.kubernetes: Resource 'data.aws_eks_cluster_auth.cluster-auth' does not have attribute 'token' for variable 'data.aws_eks_cluster_auth.cluster-auth.token'
	* provider.helm: Resource 'data.aws_eks_cluster_auth.cluster-auth' does not have attribute 'token' for variable 'data.aws_eks_cluster_auth.cluster-auth.token'

**Comment by virmanv** [comment]
Hello

Encountered the same issue  and looks like aws_eks_cluster_auth doesn't have the attribute. So did a work around for this one:

`data "external" "token" {
  program = ["bash", "${path.module}/scripts/token.sh"]

  query {
    cluster_name = "${local.cluster_name}"
  }
}`

`provider "kubernetes" {
  token                  = "${data.external.token.result.token}"
  host                   = "${var.cluster_endpoint}"
  cluster_ca_certificate = "${base64decode("${var.cluster_certificate_authority_data}")}"
  load_config_file       = false
}`
**token.sh**
#!/bin/bash
set -e
eval "$(jq -r '@sh "CLUSTER_NAME=\(.cluster_name)"')"
TOKEN=$(aws-iam-authenticator token -i $CLUSTER_NAME | jq -r .status.token)
jq -n --arg token "$TOKEN" '{"token": $token}'

**Comment by vrathore18** [comment]
@virmanv : the token script is throwing error:

```
Error: failed to execute "bash": ./scripts/token.sh: line 3: jq: command not found
./scripts/token.sh: line 4: jq: command not found
Error: flag needs an argument: 'i' in -i
Usage:
  aws-iam-authenticator token [flags]

Flags:
      --cache                  Cache the credential on disk until it expires. Uses the aws profile specified by AWS_PROFILE or the default profile.
      --forward-session-name   Enable mapping a federated sessions caller-specified-role-name attribute onto newly assumed sessions. NOTE: Only applicable when a new role is requested via --role
  -h, --help                   help for token
  -r, --role string            Assume an IAM Role ARN before signing this token
      --token-only             Return only the token for use with Bearer token based tools

Global Flags:
  -i, --cluster-id ID       Specify the cluster ID, a unique-per-cluster identifier for your aws-iam-authenticator installation.
  -c, --config filename     Load configuration from filename
  -l, --log-format string   Specify log format to use when logging to stderr [text or json] (default "text")



  on provider.tf line 46, in data "external" "token":
  46: data "external" "token" {
```

**Comment by jondunning** [comment]
@virmanv ensure you have jq installed. On a mac `brew install jq`

**Comment by jondunning** [comment]
@vrathore18 See my comment above
