### ISSUE TITLE
change of security group forces new cluster

### ISSUE THREAD

**Issue by lasse-kristensen** [terraform-aws-modules/terraform-aws-eks#398]
# I have issues

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
``` 
      vpc_config.0.security_group_ids.268129510: "" => "sg-06db7e4299b7f38e6" (forces new resource)
      vpc_config.0.security_group_ids.276351866: "sg-0899b7c4c8baa1c31" => "" (forces new resource)
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Create a EKS cluster, then change security_group_ids in vpc_config and plan and apply.

## What's the expected behavior?

Change the the security group without force of a new EKS cluster

## Environment details

* Affected module version:
* OS: ubuntu 18.04
* Terraform version:

Terraform v0.11.13
+ provider.aws v2.4.0

**Comment by confiq** [comment]
this is a limitation of AWS and no terraform.  We talked about something similar 
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/276

feel free to close

**Comment by lasse-kristensen** [comment]
You are absolutely correct my bad.
Thanks for the fast response

**Comment by confiq** [comment]
no worries... 
It's simply bad design...

my 2 cents
