### ISSUE TITLE
Cluster and worker security group specification doesn't work

### ISSUE THREAD

**Issue by jimbeck** [terraform-aws-modules/terraform-aws-eks#40]
# I have issues
I am creating an eks cluster with providing a `cluster_security_group_id` and `worker_security_group_id`.

## I'm submitting a

* [X] bug report
* [ ] feature request
* [ ] support request

## What is the current behavior
When specifying a security group aka `cluster_security_group_id = "sg-123"` or `worker_security_group_id = "sg-123"`. I get 
```
Error: Error running plan: 1 error(s) occurred:
module.eks.local.cluster_security_group_id: local.cluster_security_group_id: Resource 'aws_security_group.cluster' not found for variable 'aws_security_group.cluster.id'`<br>
```

## If this is a bug, how to reproduce? Please include a code sample
Create an eks cluster with a cluster_security_group_id or worker_security_group_id specified.<br>
Terraform does not support short circut evaluation in it's ternary operator. The fix to the issue is specified [here](http://67bricks.com/blog/?p=85)

## What's the expected behavior
We should be able to create an EKS cluster while specifying cluster sg or worker sg as the documentation currently specifies.

## Environment

* Affected module version: 1.1.0
* OS: 
* Terraform version: 0.11.7

**Comment by brandoconnor** [comment]
Ahh I wish I would have tested for this now. Thanks I'll merge now.
