### ISSUE TITLE
aws_auth.tf: At 2:14: Unknown token: 2:14 IDENT

### ISSUE THREAD

**Issue by su-sfeng** [terraform-aws-modules/terraform-aws-eks#403]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

`module eks: Error parsing .terraform/modules/e124779d053ea43ba90722b1e78f4e6f/aws_auth.tf: At 2:14: Unknown token: 2:14 IDENT var.write_aws_auth_config`

We use Terraform 0.11. I see the problem is because the module now requires Terraform 0.12. 

How can I pin module version to  v4.0.2, that would address the issue and allow us time to migrate terraform 0.11 code. 

Thanks!

**Comment by xueshanf** [comment]
I was able to use ref in git source to pull and v4.0.0 version, like so
```module "eks" {
  source                    = "github.com/terraform-aws-modules/terraform-aws-eks?ref=v4.0.2"
```
problem resolved.

**Comment by su-sfeng** [comment]
use git ref in source.
