### ISSUE TITLE
New location of `worker_group_tags`

### ISSUE THREAD

**Issue by sc250024** [terraform-aws-modules/terraform-aws-eks#408]
# I have issues

This is just a quick question surrounding v5.0.0 of the module, and Terraform 0.12 support.

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [X] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

In the Terraform v0.11.X version of the module (https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/4.0.2), there was an option called `worker_group_tags`, which I previously used to override the `Name` tag on the EC2 instances; in this way, I could tell what kind of instance it was quickly (spot vs. ondemand, public subnet vs. private subnet, etc.)

I'm wondering how this is accomplished in v5.X.X ? I've successfully created a cluster, but all of the EC2 instances have the same `Name` tag despite being separate types.

## What's the expected behavior?

Just looking for what the new way to do `worker_group_tags` is 🙂. Thank you!

## Environment details

* Affected module version: v5.0.0
* OS: macOS 10.14.5
* Terraform version:
```
Terraform v0.12.2
+ provider.aws v2.16.0
+ provider.local v1.2.2
+ provider.null v2.1.2
+ provider.template v2.1.2
```

**Comment by max-rocket-internet** [comment]
Not sure if it helps but you can set a name of each work group that will affect all instance names. Here's what I'm using:

```hcl

  worker_groups_launch_template = [
    {
      name                = "on-demand-1"
      instance_type       = "m5.xlarge"
  ]

  worker_groups_launch_template_mixed = [
    {
      name                     = "prom-spot-1"
      override_instance_type_1 = "r5.4xlarge"
      override_instance_type_2 = "r5a.4xlarge"
      override_instance_type_3 = "r5ad.4xlarge"
      override_instance_type_4 = "c5.9xlarge"
    {
      name                     = "spot-1"
      override_instance_type_1 = "m5.2xlarge"
      override_instance_type_2 = "c5.2xlarge"
      override_instance_type_3 = "t3.2xlarge"
      override_instance_type_4 = "r5.2xlarge"
      spot_instance_pools      = 4
  ]
```

I think it will be destructive for you to set this now though.

**Comment by stefansedich** [comment]
@sc250024 looks like `tags` is not part of the worker_group itself, just moved over to this module moved mine from `worker_group_tags to a nested `tags` for the worker group and it appears to work!

**Comment by sc250024** [comment]
@stefansedich Would you mind posting an example? I tried both methods, and it doesn't seem to work for me.
