### ISSUE TITLE
Creating CloudWatch Log Group failed: ResourceAlreadyExistsException

### ISSUE THREAD

**Issue by lucasvianna** [terraform-aws-modules/terraform-aws-eks#411]
This problem should be related to https://github.com/terraform-providers/terraform-provider-aws/issues/7406, but this problem makes the update impossible.

With the version v5.0.0 I can't apply the changes because:
```
 Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists
	status code: 400, request id: 89b8f8a6-820d-836a2f69df1b:  The CloudWatch Log Group '/aws/eks/cluster-name/cluster' already exists.
```
## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## Environment details
Terraform v0.12.2
provider.aws v2.16.0

* Affected module version: v5.0.0
* OS: MacOS 10.14.5
* Terraform version: v0.12.2

**Comment by max-rocket-internet** [comment]
Yes it's a new resource that will clash with the one that already exists if you have logging already enabled. You can just import the resource to resolve the issue:

```
terraform import module.your_module.aws_cloudwatch_log_group.this "/aws/eks/cluster-name/cluster"
```

**Comment by jimmymills** [comment]
Whenever I run this import, I see a message for "Import complete!" and then during the refresh that runs as the second step of the import I run into #402 where I see in the output ```|----------------
    | aws_security_group.cluster is empty tuple
    | var.cluster_security_group_id is ""``` and a similar error with ```|----------------
    | aws_security_group.workers is empty tuple
    | var.worker_security_group_id is ""``` even though I am definitely passing in cluster_security_group_id and worker_security_group_id

**Comment by bagarYas** [comment]
I am also facing similar issue. this issue is mostly related to the resources log groups created by AWS. Since terraform has no control on these resources it fails stating log group already exists.  I am facing an issues with /aws/lamda/xxxxx

**Comment by bhalothia** [comment]
I'm facing the same issue. I wanted to enable EKS control plane logging, so I imported the default log group created by AWS EKS and enabled the logging. However, I'm getting this error if I try to update the log group with any new properties:

```
Error: Error applying plan:

1 error occurred:
	* module.eks_cluster.aws_cloudwatch_log_group.log-group: 1 error occurred:
	* aws_cloudwatch_log_group.log-group: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists
	status code: 400, request id: [REDACTED]:  The CloudWatch Log Group '[REDACTED]' already exists.
```

**Comment by chewmanfoo** [comment]
@bagarYas  what was the resolution?  I'm facing this issue with Lambda LogGroups created automatically by the AWS API when a Lambda Function is created, trying to manage them after they were created outside of terraform.  I see the message, I import them, I try again and I see the message again.

**Comment by barneyparker** [comment]
If you are providing `logs:CreateLogGroup` permission, you are explicitly allowing AWS to create the log group under the IAM role/policy.  Without that permission AWS wont actually create the log group on your behalf, and the operation would fail internally (and silently except within CloudTrail).

This does mean you need to explicitly create the correct log group in Terraform, but this is already being done, otherwise you wouldn't be seeing the error!

**Comment by bilalbayasut** [comment]
I tried to do the import, but it always asking the env var, and the cli has no option to add --var-file, any idea ?

**Comment by barneyparker** [comment]
@bilalbayasut that is a slightly annoying import feature - having to provide variable values because you can't include .tfvars files etc!

All you can do here is know what they should be, and when prompted, type the missing values

You could add a temporary .tf file with the missing vars preset just to get you past the import

Ideally you should let Terraform create the resource, so you could delete the log group and then apply quickly - which isn't ideal....

**Comment by bilalbayasut** [comment]
I've solved this by removing the log groups in aws console, and renaming the name property in log_groups resource in terraform, and then applied it

**Comment by daroga0002** [comment]
In current version of module  (and few back) it is handled by creating a cloudwatch log group before creating a EKS so this should avoid such situations so closing this issue.

Code is here:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1d848b56bf7c43ce708bd7cdee45589f816e05f0/cluster.tf#L51
