### ISSUE TITLE
deploying worker nodes on private subnets

### ISSUE THREAD

**Issue by luisamador** [terraform-aws-modules/terraform-aws-eks#413]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I'm trying to get my EKS worker nodes deployed only on private subnets.

```
workers_group_defaults {
    subnets = ["${data.terraform_remote_state.common.private_subnets}"] #Launch Worker nodes on private subnets only.
  }
```

after running `terraform plan` I get this error message:

```
Error: Error refreshing state: 1 error(s) occurred:

* module.eks.data.template_file.userdata: 1 error(s) occurred:

* module.eks.data.template_file.userdata: At column 86, line 1: map "local.workers_group_defaults" does not have homogenous types. found TypeString and then TypeList in:

${lookup(var.worker_groups[count.index], "pre_userdata", local.workers_group_defaults["pre_userdata"])}
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Define the worker_group_defaults within your EKS module and pass in a list of private subnets.
```
workers_group_defaults {
    subnets = ["${data.terraform_remote_state.common.private_subnets}"] #Launch Worker nodes on private subnets only.
  }
```

## What's the expected behavior?
The EKS worker nodes get deployed on the specified private subnets.

## Environment details

* Affected module version: 4.0.2
* OS: macOS Sierra 10.12.6
* Terraform version: 0.11.7
* AWS provider version: 2.16.0

**Comment by btsuhako** [comment]
What's the output type of `data.terraform_remote_state.common.private_subnets`?

The `subnets` variable accepts a list of strings (https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/variables.tf#L75), so if your output is already a list, might try the following:

```terraform
workers_group_defaults {
    subnets = "${data.terraform_remote_state.common.private_subnets}" #Launch Worker nodes on private subnets only.
  }
```
