### ISSUE TITLE
IAM role specific to each worker group

### ISSUE THREAD

**Issue by danhiris** [terraform-aws-modules/terraform-aws-eks#415]
# When I specify a different iam role for each worker group, that iam role doesn't get created so the apply fails as it's missing when it tries to assign it.

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## Environment details

* Affected module version: 4.0.2 (same logic is in 5.0.0)
* OS: OSX, Linux
* Terraform version: v0.11.14

**Comment by max-rocket-internet** [comment]
Yes I think the current implementation is one of:
1. You supply the IAM roles from outside of the module. Can be per worker group
2. All worker groups share the same IAM role.

**Comment by max-rocket-internet** [comment]
This is now possible
