### ISSUE TITLE
Arguments not expected there using terraform 0.12 and terraform-aws-eks v5.0.0

### ISSUE THREAD

**Issue by ivanguravel** [terraform-aws-modules/terraform-aws-eks#417]
## I'm submitting a...

* [ ] bug report
* [ ] support request

## What is the current behavior?
After updating terraform to latest 0.12.2 version, changed my use of the module to v5.0.0 of the terraform-aws-eks module as per: https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v5.0.0 .

Also I updated aws and random providers to the : https://github.com/hashicorp/terraform/issues/21235#issuecomment-490251511

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Currently i have:

```
module "eks" {
  source       = "terraform-aws-modules/eks/aws"
  cluster_name = "somecluster"

  kubeconfig_aws_authenticator_env_variables = {
    AWS_PROFILE = "..."
  }

  version                              = "5.0.0"
  // other variables  
   worker_group_count                   = "${var.worker_group_count}"
   map_users_count                      = "${length(var.map_users)}"
   map_roles_count = "1"
}
```

and errors output after `terraform plan`:

```
Error: Unsupported argument

  on main.tf line 261, in module "eks":
 261:   worker_group_count                   = "${var.worker_group_count}"

An argument named "worker_group_count" is not expected here.


Error: Unsupported argument

  on main.tf line 264, in module "eks":
 264:   map_users_count                      = "${length(var.map_users)}"

An argument named "map_users_count" is not expected here.


Error: Unsupported argument

  on main.tf line 275, in module "eks":
 275:   map_roles_count = "1"

An argument named "map_roles_count" is not expected here.
```

## What's the expected behavior?
successfully eks installation, because for terraform 0.11.8 and terraform-eks release `4.0.2` working fine

## Environment:
* OS: Centos7
* Terraform version: v0.12.2

## Any other relevant info
+ provider.aws v2.16.0
+ provider.external v1.2.0
+ provider.http v1.1.1
+ provider.local v1.2.2
+ provider.null v2.1.2
+ provider.random v2.1.0
+ provider.template v2.1.2
+ provider.tls v2.0.1

**Comment by nauxliu** [comment]
Please read the 5.0 upgrade guide https://github.com/terraform-aws-modules/terraform-aws-eks/pull/394

**Comment by confiq** [comment]
> ## What's the expected behavior?
> successfully eks installation, because for terraform 0.11.8 and terraform-eks release 4.0.2 working fine

but you had to refactor the terraform 0.12 upgrade no?
