### ISSUE TITLE
Autoscaling_enabled not picked up from worker_groups variable

### ISSUE THREAD

**Issue by Blokje5** [terraform-aws-modules/terraform-aws-eks#418]
# I have issues
When specifying `autoscaling_enabled = "true"` as part of the `worker_groups`, the tag in the ASG is not overwritten.

## I'm submitting a...

* [√ ] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

With the following worker_groups setup, passed to the EKS module:
```terraform
  worker_groups = [{
    instance_type        = "t2.medium"
    ami_id               = "ami-098fb7e9b507904e7"
    asg_desired_capacity = "${var.asg_min_size}"
    asg_max_size         = "${var.asg_max_size}"
    asg_min_size         = "${var.asg_min_size}"
    autoscaling_enabled  = "true"
  }]
```

The ec2 instances are still created with the tag `k8s.io/cluster-autoscaler/disabled = true` 

## What's the expected behavior?
Specifying the autoscaling_enabled flag in the worker_groups should set tag the ASG with `k8s.io/cluster-autoscaler/enabled = true` 

## Issue

The code in `workers.tf` line 81 only checks the defaults, and does not check if the autoscaling_enabled is set in the worker_groups variable.
```terraform
 "key" = "k8s.io/cluster-autoscaler/${lookup(
          var.worker_groups[count.index],
          "autoscaling_enabled",
          local.workers_group_defaults["autoscaling_enabled"],
        ) ? "enabled" : "disabled"}"
```

## Environment details

* Affected module version: 2.2.1
* OS: MacOs
* Terraform version: 0.11.14

**Comment by dpiddockcmp** [comment]
The source code for version 2.2.1 is different to the current contents of `master`. The line you should be looking at is here: [workers.tf](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/87114b0bd032ab050f98ed45afb29f8c6a15b060/workers.tf#L21)

This dates to when the module compared boolean inputs against 1 or 0.

You're passing in a string which will always fail to match. Try the boolean value `true` or the int `1`.

**Comment by Blokje5** [comment]
You are tight, completely missed the fact that it was a string and not a bool. Thanks for catching that. Ill close the issue.
