### ISSUE TITLE
Not able to run example/basic

### ISSUE THREAD

**Issue by kshailen** [terraform-aws-modules/terraform-aws-eks#419]
# I have issues
shailendras-mbp:basic shaikuma$ terraform init
Initializing modules...
- module.vpc
Error downloading modules: Error loading modules: no versions for "terraform-aws-modules/vpc/aws" found matching "5.0.0"
shailendras-mbp:basic shaikuma$ pwd
/Users/shaikuma/Desktop/EKS/terraform-aws-eks_new/terraform-aws-eks/examples/basic
## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

When I am initializing examples/baisc, it's not able to download terraform-aws-modules/vpc/aws I noticed there is no directory inside terraform-aws-modules with vpc/aws name

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by confiq** [comment]
I thought the purpose of these examples are just to show the developer how to use the module and not to really work...

**Comment by dpiddockcmp** [comment]
Did you modify the example in any way? It looks like you've modified the VPC module import to use `version = 5.0.0` which does not exist. It should be 2.something. The example currently has `2.6.0`. 

`terraform init` works for the example/basic in v5.0.0 and master:
```
$ terraform init
Initializing modules...
- eks in ../..
Downloading terraform-aws-modules/vpc/aws 2.6.0 for vpc...
- vpc in .terraform/modules/vpc/terraform-aws-modules-terraform-aws-vpc-4b28d3d

Initializing the backend...
```

**Comment by kshailen** [comment]
with 2.6.0 I am getting different type of error:
```bash
shailendras-mbp:basic shaikuma$ pwd
/Users/shaikuma/Desktop/EKS/terraform-aws-eks_new/terraform-aws-eks/examples/basic
shailendras-mbp:basic shaikuma$ 
```

**Comment by kshailen** [comment]
updated terraform from 0.11.8 to  0.12.3 version. Now it's working.

**Comment by max-rocket-internet** [comment]
Cool. Glad you got it working.
