### ISSUE TITLE
Allow pre-userdata script on worker launch config

### ISSUE THREAD

**Issue by jimbeck** [terraform-aws-modules/terraform-aws-eks#42]
# I have issues
I want to be able to run additional user data **before** the plugin user data on the worker launch config.
I am behind a proxy and need to configure the proxy information before anything else happens.

## I'm submitting a

* [ ] bug report
* [x] feature request
* [ ] support request

## What is the current behavior
The plugin only provides a way to specify additional user data that runs after the plugins user data.

## Environment

* Affected module version: 1.1.0
* OS:
* Terraform version: 0.11.7

**Comment by brandoconnor** [comment]
This is merged and released.
