### ISSUE TITLE
worker nodes unable to connect to the cluster

### ISSUE THREAD

**Issue by opencatersf** [terraform-aws-modules/terraform-aws-eks#420]
## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ * ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I am having issues getting the worker nodes to connect to my eks cluster. when i logged in to the worker node i am getting the error below. This is also using a public subnet from my vpc. aws_auth gets created with no issues and ec2 instances are also using the right instance profile. the version im using is Version":"5.0.0"

Jun 30 03:08:19 ip-10-100-5-7 kubelet: E0630 03:08:19.149994    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:19 ip-10-100-5-7 kubelet: E0630 03:08:19.250192    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:19 ip-10-100-5-7 kubelet: E0630 03:08:19.350403    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:19 ip-10-100-5-7 kubelet: E0630 03:08:19.450605    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:19 ip-10-100-5-7 kubelet: E0630 03:08:19.550837    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:19 ip-10-100-5-7 kubelet: E0630 03:08:19.651064    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:19 ip-10-100-5-7 kubelet: E0630 03:08:19.751273    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:19 ip-10-100-5-7 kubelet: E0630 03:08:19.770595    4420 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Unauthorized
Jun 30 03:08:19 ip-10-100-5-7 kubelet: E0630 03:08:19.851962    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:19 ip-10-100-5-7 kubelet: E0630 03:08:19.900817    4420 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Unauthorized
Jun 30 03:08:19 ip-10-100-5-7 kubelet: E0630 03:08:19.900859    4420 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
Jun 30 03:08:19 ip-10-100-5-7 kubelet: E0630 03:08:19.952483    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:20 ip-10-100-5-7 kubelet: E0630 03:08:20.052714    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:20 ip-10-100-5-7 kubelet: E0630 03:08:20.152924    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:20 ip-10-100-5-7 kubelet: E0630 03:08:20.253136    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:20 ip-10-100-5-7 kubelet: E0630 03:08:20.353369    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:20 ip-10-100-5-7 kubelet: E0630 03:08:20.453600    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:20 ip-10-100-5-7 kubelet: E0630 03:08:20.553818    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:20 ip-10-100-5-7 kubelet: E0630 03:08:20.654032    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:20 ip-10-100-5-7 kubelet: E0630 03:08:20.754252    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:20 ip-10-100-5-7 kubelet: E0630 03:08:20.854445    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found
Jun 30 03:08:20 ip-10-100-5-7 kubelet: E0630 03:08:20.897784    4420 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Unauthorized
Jun 30 03:08:20 ip-10-100-5-7 kubelet: E0630 03:08:20.954949    4420 kubelet.go:2266] node "ip-10-100-5-7.us-west-2.compute.internal" not found

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Here is my main.tf 

variable "vpc_id" {
  default = "vpc-001670fb"
}

variable "subnets" {
  default = ["subnet-0a4c92b3", "subnet-0e414456"]
  type    = list(string)
}

variable "vpc_env_name" {
  default = "production"
}

variable "cluster_version" {
  default = "1.13"
}

variable "cluster_name" {
  default = "eks-cluster-us-west-2-01"
}

variable "office_sg" {
  default = ["sg-0a92c8b"]
  type    = list(string)
}

variable "map_roles" {
  description = "Additional IAM roles to add to the aws-auth configmap."
  type        = list(map(string))

  default = [
    {
      role_arn = "arn:aws:iam:::role/devops"
      username = "devops"
      group    = "system:masters"
    },
  ]
}

provider "aws" {
  region  = "us-west-2"
  profile = "sa-terraform"
}

terraform {
  backend "s3" {
    bucket  = "eks-cluster-operations-terraform"
    key     = "eks-clusters-terraform-module/eks-cluster-us-west-2-01"
    region  = "us-west-2"
    profile = "sa-terraform"
  }
}

module "eks-clusters-terraform-module" {
  source                               = "terraform-aws-modules/eks/aws"
  cluster_name                         = var.cluster_name
  cluster_version                      = "1.13"
  subnets                              = var.subnets
  vpc_id                               = var.vpc_id
  worker_additional_security_group_ids = var.office_sg
  manage_aws_auth                      = "true"
  map_roles                            = var.map_roles
  kubeconfig_aws_authenticator_env_variables = {
    AWS_PROFILE = "devops"
  }

  tags = {
    Environment = "shared"
  }

worker_groups = [
    {
      name = "generalPurpose_2a"
      instance_type = "t2.medium"
      asg_min_size = 1
      asg_max_size  = 2
      autoscaling_enabled = true
      protect_scale_in = true
      asg_desired_capacity = 1
      key_name = ""
    },
    {
      name = "generalPurpose_2b"
      instance_type = "t2.medium"
      asg_min_size = 1
      asg_max_size  = 2
      autoscaling_enabled = true
      protect_scale_in = true
      asg_desired_capacity = 1
      key_name = ""
    }
  ]
}

## Environment details

* Affected module version:
* OS: OSX
* Terraform version:
Terraform v0.12.3
+ provider.aws v2.17.0
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.template v2.1.2

**Comment by opencatersf** [comment]
Updating with the AMI i am using: amazon-eks-node-1.13-v20190614

**Comment by max-rocket-internet** [comment]
I think this is your problem: ` Failed to list *v1.Pod: Unauthorized`

Check that your `aws-auth` configmap was applied and has the correct `rolearn`

**Comment by opencatersf** [comment]
@max-rocket-internet config map looks good to me

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam:::role/eks-cluster-us-west-2-0120190701201308460600000006
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam:::role/devops
      username: devops
      groups:
        - system:masters

  mapUsers: |

  mapAccounts: |

**Comment by opencatersf** [comment]
i also checked the kubeconfig inside the worker nodes seems right.

apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://140922E6BD597ABCDEC9E72A3CE9CE.yl4.us-west-2.eks.amazonaws.com
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubelet
  name: kubelet
current-context: kubelet
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - eks-cluster-us-west-2-01
      command: /usr/bin/aws-iam-authenticator
      env: null

**Comment by opencatersf** [comment]
I tried running this on public subnets now but same issue. seems like 

Jul  1 21:03:15 ip-10-72-171-192 kubelet: I0701 21:03:15.275924    4431 kubelet_node_status.go:279] Setting node annotation to enable volume controller attach/detach
Jul  1 21:03:15 ip-10-72-171-192 kubelet: I0701 21:03:15.276524    4431 kubelet_node_status.go:327] Adding node label from cloud provider: beta.kubernetes.io/instance-type=t2.medium
Jul  1 21:03:15 ip-10-72-171-192 kubelet: I0701 21:03:15.276873    4431 kubelet_node_status.go:338] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=us-west-2b
Jul  1 21:03:15 ip-10-72-171-192 kubelet: I0701 21:03:15.277221    4431 kubelet_node_status.go:342] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=us-west-2

**Comment by opencatersf** [comment]
i got this figured out. looks like the aws_auth configmap is not applying automatically, I had to apply it manually in order for the workers to join the cluster. is this a bug?

**Comment by davi5e** [comment]
Same here, but still haven't figured out how to re-apply `configmap/aws-auth` so the EC2 instance can join...

The command below **did not** work:
```bash
kubectl get -n kube-system configmap/aws-auth -o yaml | kubectl replace -f -
```

**Comment by renperez** [comment]
@davi5e are you connected to the cluster? what is the output of your kubectl cluster-info

**Comment by davi5e** [comment]
```
$ kubectl cluster-info
Kubernetes master is running at https://FD682B64C213C073209FDA092F6CCBCC.gr7.us-east-1.eks.amazonaws.com
CoreDNS is running at https://FD682B64C213C073209FDA092F6CCBCC.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Comment by davi5e** [comment]
So, I figured out **what** was causing my problem, but I don't know _why_...

Once I compared the [EKS basic example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v5.0.0/examples/basic/main.tf) with the [VPC module I used as a template](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/v2.7.0/examples/complete-vpc/main.tf) I noticed that EC2 endpoints were a really bad idea and now the nodes join just fine.

In the VPC (using [terraform-aws-modules/vpc/aws v2.7.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/tree/v2.7.0)) I just removed the following:
```tf
  # VPC Endpoint for EC2
  enable_ec2_endpoint              = false
  ec2_endpoint_private_dns_enabled = false
  ec2_endpoint_security_group_ids  = []
```

**Comment by karolinepauls** [comment]
So this may be circumstantial but I found that when following the basic example, the created VPC lacks `enable_dns_hostnames = true`, which, to my understanding makes it impossible to resolve hostnames like `ip-10-100-5-7.us-west-2.compute.internal`. AWS docs on it are somewhat muddy (as usual) but I think this setting enables VPC-internal resolution of assigned private and public IPs. Enabling it seems to work with some delay - I was able to dig/ssh to a worker node from a bastion host in the same VPC but a public subnet, using its hostname rather than the IP.

While I was able to resolve a worker's hostname from the bastion, kubernetes continued to fail to do so - same error in logs, which went like:

```
Jul 24 11:18:46 ip-10-0-1-36.eu-west-1.compute.internal kubelet[4355]: E0724 11:18:46.602539    4355 kubelet.go:2236] node "ip-10-0-1-36.eu-west-1.compute.internal" not found                                                                
Jul 24 11:18:46 ip-10-0-1-36.eu-west-1.compute.internal kubelet[4355]: E0724 11:18:46.682540    4355 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:442: Failed to list *v1.Service: Unauthorized                                 
Jul 24 11:18:46 ip-10-0-1-36.eu-west-1.compute.internal kubelet[4355]: E0724 11:18:46.703201    4355 kubelet.go:2236] node "ip-10-0-1-36.eu-west-1.compute.internal" not found                                                                
Jul 24 11:18:46 ip-10-0-1-36.eu-west-1.compute.internal kubelet[4355]: E0724 11:18:46.803935    4355 kubelet.go:2236] node "ip-10-0-1-36.eu-west-1.compute.internal" not found                                                                
Jul 24 11:18:46 ip-10-0-1-36.eu-west-1.compute.internal kubelet[4355]: E0724 11:18:46.900234    4355 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized                             
Jul 24 11:18:46 ip-10-0-1-36.eu-west-1.compute.internal kubelet[4355]: E0724 11:18:46.900771    4355 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Node: Unauthorized    
```

however after correcting and applying terraform (i previously downscaled the workers and enabled DNS resolution in the VPC manually), it updated the workers launch template and the cluster, after which nodes started being discovered.


There are 2 possibilities then:

1) Not enabling DNS resolution may break node registration (yesterday out of my 2 attempts it worked once and didn't work once, today it failed once, then i turned DNS resolution on)
2) DNS resolution may have nothing to do with it and I just got lucky when doing update-in-place with TF today. However, when I destroyed and recreated the cluster, it found the nodes immediately.

I cannot run many experiments like that because the full create-destroy cycle takes around 25 minutes.

_Seriously, if you can, just use K8s on GCP._

**Comment by karolinepauls** [comment]
So to keep it short, one actionable item from my comment above is the question:

Why is DNS resolution not enabled by default in the example? Could this interfere with node discovery or cluster configuration?

**Comment by max-rocket-internet** [comment]
> Why is DNS resolution not enabled by default in the example? 

It is now: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/basic/main.tf#L96

Will close this as there's been no updates. Also issues just like this have been covered in detail so I think there's already enough info available.
