### ISSUE TITLE
Removing aws_auth_configmap.yaml in case of creating several clusters

### ISSUE THREAD

**Issue by volodymyrilov** [terraform-aws-modules/terraform-aws-eks#421]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
*  support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
In case of provisioning two(or more) eks cluster without dependencies both  installation will use same file aws_auth_configmap.yaml

## If this is a bug, how to reproduce? Please include a code sample if relevant.
try to install two or more clusters in one shot.

## What's the expected behavior?
each cluster use own aws_auth_configmap.yaml

## Are you able to fix this problem and submit a PR? Link here if you have already.
yes  https://github.com/GloballogicPractices/terraform-aws-eks/commit/e29f1db8ae4302cd22a2693a0fb42f4179b18e9f
## Environment details

* Affected module version: all 
* OS: ubuntu 18.*
* Terraform version: 0.11.13,

**Comment by max-rocket-internet** [comment]
Are you sure? Because `working_dir` is already set to `"${path.module}"`?
https://github.com/GloballogicPractices/terraform-aws-eks/commit/e29f1db8ae4302cd22a2693a0fb42f4179b18e9f#diff-2812d2bbb29e6bacd1bed6f9acf4a797L12

Perhaps it's a bug in terraform?

**Comment by volodymyrilov** [comment]
HI! i've done couple additional verification and it more related to terraform:
in case of using git path as module source - terraform will create one temporary folder for each usage of module
in case of using terraform-aws-modules/eks/aws as module source - terraform will create only one temporary folder with module, and my fix won't work. 
To fix this issue its better to use for example cluster name as prefix for aws_auth_configmap.yaml
I can do that change and create pull request.

**Comment by max-rocket-internet** [comment]
> in case of using git path as module source - terraform will create one temporary folder for each usage of module


> in case of using terraform-aws-modules/eks/aws as module source - terraform will create only one temporary folder with module, and my fix won't work.

Interesting! Wasn't aware of that difference.
