### ISSUE TITLE
Changing to self-managed IAM causes cycles

### ISSUE THREAD

**Issue by pforman-zymergen** [terraform-aws-modules/terraform-aws-eks#427]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

When attempting to change a cluster to "manage_worker_iam_resources	= false" (in this case, because I want to be able to host external-dns pods), the change creates a cycle that can't be applied.  

`Error: Cycle: module.eks1.aws_launch_configuration.workers (destroy deposed ca6b9042), module.eks-zre.aws_autoscaling_group.workers (destroy deposed e99270b1), module.eks1.aws_iam_instance_profile.workers[0] (destroy), module.eks1.aws_iam_role.workers[0] (destroy), module.eks1.local.default_iam_role_id, module.eks1.local.workers_group_defaults_defaults, module.eks1.local.workers_group_defaults, module.eks1.aws_launch_configuration.workers[0], module.eks1.aws_autoscaling_group.workers[0]`

It's not possible to restrict this with a `terraform plan -target`, as there's a dependency loop there, and it's also not possible to add a new group with a different role and migrate, because "manage_worker_iam_resources" applies to all groups in a cluster.

Only *removing all the pools* from the config will allow this to proceed.  (or deleting the entire cluster, but that's even more drastic.)

I found this in a test cluster, but this would be a nasty bug to trip over while looking to migrate from a default to a custom configuration after time.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Create a cluster with a worker group and default settings, then add "manage_worker_iam_resources" to  "false" and provide an instance_profile for the group.  Observe plan cycle.

## What's the expected behavior?
Some method of migrating existing groups from a managed to an unmanaged (or partially managed) config without major impact to the EKS cluster.

Making the managed config independent from the value of `iam_instance_profile_name` would likely fix the issue, but might make defaulting to a correct value harder.

## Are you able to fix this problem and submit a PR? Link here if you have already.

Possibly, but not immediately.

## Environment details

* Affected module version: 5.0.0
* OS:  OSX and Linux
* Terraform version:  0.12.2

**Comment by michcio1234** [comment]
I am observing a very similar behaviour after I tried to switch to `worker_create_security_group = false`.
I added a switch, provided `worker_security_group_id` and got this:
```
Error: Cycle: 
module.eks.aws_launch_configuration.workers (destroy deposed f0bbc920)
module.eks.random_pet.workers (destroy deposed 4a39cef0)
module.eks.aws_launch_configuration.workers (destroy deposed 043be7d5)
module.eks.output.worker_security_group_id
module.rds_sg.var.computed_ingress_with_source_security_group_id
module.rds_sg.aws_security_group_rule.computed_ingress_with_source_security_group_id[0]
module.eks.aws_security_group_rule.cluster_https_worker_ingress[0]
module.eks.aws_launch_configuration.workers[1]
module.eks.random_pet.workers[1]
module.eks.aws_autoscaling_group.workers[0]
module.eks.random_pet.workers (destroy deposed 379c4408)
module.eks.aws_security_group.workers[0] (destroy)
module.eks.local.worker_security_group_id
module.eks.aws_launch_configuration.workers[0]
module.eks.random_pet.workers[0]
module.eks.aws_autoscaling_group.workers[1]
```

**Comment by colijack** [comment]
We're getting this issue too, was wondering if anyone has come up with a good workaround?

**Comment by michcio1234** [comment]
Unfortunately, the easiest way I found to do it was to delete the cluster and re-create it. Fortunately it worked pretty well with `terraform destroy --target module.eks` - I didn't want to destroy all of my other resources.

**Comment by mcavoyk** [comment]
Also getting this issue when replacing `additional_security_group_ids` with a new security group id.
```
Error: Cycle:
module.eks.aws_autoscaling_group.workers[0], 
module.eks.aws_launch_configuration.workers[0], 
module.eks.random_pet.workers[0], 
module.eks.random_pet.workers[0] (destroy deposed 9ad411ac),
module.eks.aws_launch_configuration.workers[0] (destroy deposed 1579bf3e),
aws_security_group.nodes (destroy)
```

**Comment by hristov-hs** [comment]
hitting the same issue on tf module version 10.0.0, want to get to latest.
Any work on this anticipated ?

**Comment by michcio1234** [comment]
@2tim unfortunately I don't have any other solution. :/

**Comment by timurista** [comment]
Seems like documentation could be clearer to avoid this. Thanks @michcio1234 this worked `terraform destroy --target module.eks`
