### ISSUE TITLE
Tags for worker_groups are not working correctly 

### ISSUE THREAD

**Issue by andridzi** [terraform-aws-modules/terraform-aws-eks#428]
When trying to execute terraform plan I got following error:
``` 
Error: Invalid function argument

  on ../../workers.tf line 105, in resource "aws_autoscaling_group" "workers":
--------------------
105:       lookup(
 106:
 107:
 108:
 109:
 110:
    |----------------
    | count.index is 0
    | var.worker_groups is tuple with 1 element

Invalid value for "seqs" parameter: all arguments must be lists or tuples; got
object.
```

That's happening when I'm adding the next configuration:

```      
  worker_groups = [
    {
      instance_type = "m4.large"
      asg_max_size  = 5
      tags = {
        key                 = "foo"
        value               = "bar"
        propagate_at_launch = true
      }
    }
  ]
```

Without tags it works fine

Could you please help?
Thanks

**Comment by andreimc** [comment]
example is wrong mate try this:

```
      tags = [{
        key                 = "Name"
        value               = "blah"
        propagate_at_launch = true
      }]
```

**Comment by andridzi** [comment]
thanks

**Comment by jayhoughton** [comment]
I ran into this recently, how about fixing the example?

**Comment by ggeorgiadis** [comment]
Hi, I faced the same problem, but when I changed the tags to a list I get the following error:
```terraform
Error: k8s-main-eks-general-purpose20190718121718386800000001: invalid tag attributes: value missing

  on .terraform/modules/eks.eks-terraform/terraform-aws-modules-terraform-aws-eks-9c3d222/workers.tf line 3, in resource "aws_autoscaling_group" "workers":
   3: resource "aws_autoscaling_group" "workers" {
```

My workers look like this:
```terraform
worker_groups = [
    {
      name                 = "General Purpose"
      instance_type        = "m4.xlarge"
      key_name             = "${var.key_name}"
      asg_desired_capacity = 3
      asg_min_size         = 1
      asg_max_size         = 4
     
      tags = [{
        key                 = "Type"
        value               = "general_purpose"
        propagate_at_launch = true
      }]

      autoscaling_enabled  = true
      ebs_optimized = true

      subnets = "${var.private_subnets}"
    }
  ]
```

Any ideas why this might be happening?

Thanks

**Comment by jayhoughton** [comment]
> Hi, I faced the same problem, but when I changed the tags to a list I get the following error:
> 
> ```terraform
> Error: k8s-main-eks-general-purpose20190718121718386800000001: invalid tag attributes: value missing
> 
>   on .terraform/modules/eks.eks-terraform/terraform-aws-modules-terraform-aws-eks-9c3d222/workers.tf line 3, in resource "aws_autoscaling_group" "workers":
>    3: resource "aws_autoscaling_group" "workers" {
> ```
> 
> My workers look like this:
> 
> ```terraform
> worker_groups = [
>     {
>       name                 = "General Purpose"
>       instance_type        = "m4.xlarge"
>       key_name             = "${var.key_name}"
>       asg_desired_capacity = 3
>       asg_min_size         = 1
>       asg_max_size         = 4
>      
>       tags = [{
>         key                 = "Type"
>         value               = "general_purpose"
>         propagate_at_launch = true
>       }]
> 
>       autoscaling_enabled  = true
>       ebs_optimized = true
> 
>       subnets = "${var.private_subnets}"
>     }
>   ]
> ```
> 
> Any ideas why this might be happening?
> 
> Thanks

I can corroborate this error as well. I was getting the same exact `workers.tf line 3, in resource "aws_autoscaling_group" "workers" `error message at end of my `apply`.

I removed all tags from my `worker_groups` to fix (using a shell script to apply tags).

**Comment by ggeorgiadis** [comment]
@jayhoughton Did you have to delete the cluster and recreate it? For me removing the tags and hit apply again, throws the same error unfortunately .

**Comment by jayhoughton** [comment]
> @jayhoughton Did you have to delete the cluster and recreate it? For me removing the tags and hit apply again, throws the same error unfortunately .

Yes I deleted and recreated.

**Comment by ggeorgiadis** [comment]
Strange. Even if I delete all the state files and I try to recreate it without tags, it complains about the same thing. My terraform version is 0.12.4

**Comment by bastienk** [comment]
I have the same issue with terraform 0.12.17
Does someone have a solution?

**Comment by andelhie** [comment]
This is very much still a problem.  TF 0.12.20

**Comment by dpiddockcmp** [comment]
Setting tags worked for me on a clean state using the basic example as a base.

I added the following tag to the worker group:
```
 tags = [{
   key                 = "Type"
   value               = "general_purpose"
   propagate_at_launch = true
 }]
```
The created ASG had the following tags set:
```
"Tags": [
    {
        "ResourceId": "test-eks-ecTdLO7J-worker-group-220200206103141850800000012",
        "ResourceType": "auto-scaling-group",
        "Key": "Environment",
        "Value": "test",
        "PropagateAtLaunch": true
    },
    {
        "ResourceId": "test-eks-ecTdLO7J-worker-group-220200206103141850800000012",
        "ResourceType": "auto-scaling-group",
        "Key": "GithubOrg",
        "Value": "terraform-aws-modules",
        "PropagateAtLaunch": true
    },
    {
        "ResourceId": "test-eks-ecTdLO7J-worker-group-220200206103141850800000012",
        "ResourceType": "auto-scaling-group",
        "Key": "GithubRepo",
        "Value": "terraform-aws-eks",
        "PropagateAtLaunch": true
    },
    {
        "ResourceId": "test-eks-ecTdLO7J-worker-group-220200206103141850800000012",
        "ResourceType": "auto-scaling-group",
        "Key": "Name",
        "Value": "test-eks-ecTdLO7J-worker-group-2-eks_asg",
        "PropagateAtLaunch": true
    },
    {
        "ResourceId": "test-eks-ecTdLO7J-worker-group-220200206103141850800000012",
        "ResourceType": "auto-scaling-group",
        "Key": "Type",
        "Value": "general_purpose",
        "PropagateAtLaunch": true
    },
    {
        "ResourceId": "test-eks-ecTdLO7J-worker-group-220200206103141850800000012",
        "ResourceType": "auto-scaling-group",
        "Key": "k8s.io/cluster/test-eks-ecTdLO7J",
        "Value": "owned",
        "PropagateAtLaunch": true
    },
    {
        "ResourceId": "test-eks-ecTdLO7J-worker-group-220200206103141850800000012",
        "ResourceType": "auto-scaling-group",
        "Key": "kubernetes.io/cluster/test-eks-ecTdLO7J",
        "Value": "owned",
        "PropagateAtLaunch": true
    }
],
```

```
Terraform v0.12.20
+ provider.aws v2.47.0
+ provider.kubernetes v1.10.0
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.template v2.1.2
```
From master. `626a393`

If you are still having problems, open a new issue with:
- the version of the module you're using
- output of `terraform -version`
- a minimum example of what does not work. If you can't get a minimum working example then you'll need to share your full config. Or what steps trigger the issue.
