### ISSUE TITLE
Clarity needed on authenticating the kubernetes provider while using this module

### ISSUE THREAD

**Issue by brandonjbjelland** [terraform-aws-modules/terraform-aws-eks#430]
## I'm submitting a...

* [x] feature request
* [x] support request
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?

From [this google group thread](https://groups.google.com/forum/#!topic/terraform-tool/_kCtKyenaYE): Users are left figuring out on their own how to use the kubernetes provider alongside this module.

## Suggested fix

We should make the case of using the kubernetes provider simpler by exporting the necessary outputs (if possible, one is data source derived) and crafting a test fixture example that shows how authentication with the kubernetes provider works.

## Are you able to fix this problem and submit a PR? Link here if you have already.

Yes, but it's not yet prepared.

## Environment details

* Affected module version: all
* OS: Any
* Terraform version: 0.12+ (not looking to support 0.11 in this case)

**Comment by max-rocket-internet** [comment]
Hi @brandoconnor 👋
Good idea!
