### ISSUE TITLE
What to commit

### ISSUE THREAD

**Issue by silasb** [terraform-aws-modules/terraform-aws-eks#431]
# I don't have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request
* [x] kudos, thank you, warm fuzzy

Just got a cluster stood up :rocket: and have a question on what I should be committing to my repo.  I see two files created:

* config-map-aws-auth_ephemeral-cluster.yaml
* kubeconfig_ephemeral-cluster

I'm thinking that I should gitignore these files, but I wanted to check first.

**Comment by max-rocket-internet** [comment]
We commit them both. They are not sensitive 🙂

**Comment by silasb** [comment]
Thanks.
