### ISSUE TITLE
workers id as an output for dns assignment

### ISSUE THREAD

**Issue by hamzamp** [terraform-aws-modules/terraform-aws-eks#432]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request
* [ ] kudos, thank you, warm fuzzy

Please I just start using this module and I want to have EC2 instances ids (workers), created by the module as an output, to assign a hostname to each instance based on Route53 dns.

Thank you

**Comment by max-rocket-internet** [comment]
I don't think this is possible
