### ISSUE TITLE
Nodes cannot join a cluster created with public api endpoint disabled and the private one enabled

### ISSUE THREAD

**Issue by carlosrmendes** [terraform-aws-modules/terraform-aws-eks#434]
Private EKS cluster created using this `main.tf`

```
terraform {
  required_version = ">= 0.12.0"
}

provider "aws" {
  version = ">= 2.11"
  region  = var.region
}

provider "random" {
  version = "~> 2.1"
}

provider "local" {
  version = "~> 1.2"
}

provider "null" {
  version = "~> 2.1"
}

provider "template" {
  version = "~> 2.1"
}

data "aws_availability_zones" "available" {
}

locals {
  cluster_name = "test-eks-lt-${random_string.suffix.result}"
}

resource "random_string" "suffix" {
  length  = 8
  special = false
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.6.0"

  name           = "test-vpc-lt"
  cidr           = "10.0.0.0/16"
  azs            = data.aws_availability_zones.available.names
  public_subnets = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]
  private_subnets     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]

  tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
  }
}

module "eks" {
  source       = "../.."
  cluster_name = local.cluster_name
  subnets      = module.vpc.private_subnets
  vpc_id       = module.vpc.vpc_id

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false

  worker_groups_launch_template = [
    {
      name                 = "worker-group-1"
      instance_type        = "t2.small"
      asg_desired_capacity = 2
      public_ip            = true
    },
    {
      name                 = "worker-group-2"
      instance_type        = "t2.medium"
      asg_desired_capacity = 1
      public_ip            = true
    },
  ]
}
```

After the apply if I run `kubectl get nodes` it shows `No resources found.`, even if I wait a while.

If I switch the boolean values of `cluster_endpoint_private_access` and `cluster_endpoint_public_access` the nodes join successfully to the cluster and then, even after that I switch back to private api enpoints.

**Comment by carlosmkb** [comment]
I realized that the aws-auth configmap was not created, but after I created it, with the correct workers role arn, the nodes still cannot join to the cluster.

**Comment by abdennour** [comment]
The same pain @carlosmkb . Honestly, Provisioning a k8s cluster with other cloud providers is smooth and cost-effective.

**Comment by max-rocket-internet** [comment]
Can you try this? https://github.com/terraform-aws-modules/terraform-aws-eks/issues/420#issuecomment-510956819

**Comment by max-rocket-internet** [comment]
The 3 examples in [examples](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples) all work when I test them. So could you please compare what you have with what is there and try to narrow down the cause? Specifically check:

- Are you disabling or changing anything related to DNS in your VPC?
- Are your work nodes in subnets that can reach the internet or your EKS API endpoint?
