### ISSUE TITLE
`target_group_arns` option not supporting lists

### ISSUE THREAD

**Issue by Mrngilles** [terraform-aws-modules/terraform-aws-eks#437]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I am trying to add target groups to the Autoscaling group, using the `target_group_arns` option from the `worker_groups` variable.
When setting this variable as a list, empty or not (it is defined by default as a list), I get the error:

```
module.eks.aws_autoscaling_group.workers: lookup: lookup() may only be used with flat maps, this map contains elements of type list in:

${compact(split(",", coalesce(lookup(var.worker_groups[count.index], "target_group_arns", ""), local.workers_group_defaults["target_group_arns"])))}
```

However, when I input a string of multiple comma-separated arns, it accepts them and works as intended

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```terraform
module "eks" {
  source                               = "terraform-aws-modules/eks/aws"
  version                              = "4.0.2"
  cluster_name                         = "test-cluster"
  worker_groups                        = [
{
    ami_id               = "ami-0e82e73403dd69fa3"
    instance_type        = "m5a.xlarge"
    asg_desired_capacity = "2"
    asg_max_size         = "2"
    asg_min_size         = "2"
    target_group_arns = [] # Should work, does not
#   target_group_arns = ["<arn1>", "<arn2>"] # Should work, does not
#   target_group_arns = "<arn1>,<arn2>" # Works, should probably not
  }
]
  worker_group_count                   = "1"
}
```

## What's the expected behavior?

I would expect that using a list, the `terraform apply works and the arns are added to the ASG target_groups

## Environment details

* Affected module version: 4.0.2
* OS: OS X 
* Terraform version: 0.11.14

**Comment by dpiddockcmp** [comment]
You're reading the documentation for v5 of the module which is for Terraform 0.12 and the new HCL2 syntax. 

Terraform 0.11 did not do well with lists in lists or interpolation syntax.

Check the comments for the version of the module you're using:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v4.0.2/local.tf#43
`target_group_arns             = ""                              # A comma delimited list of ALB target group ARNs to be associated to the ASG`

**Comment by Mrngilles** [comment]
Ah, my bad sorry.
Thanks

Le mer. 17 juil. 2019 à 15:33, Daniel Piddock <notifications@github.com> a
écrit :
