### ISSUE TITLE
Document IAM permissions required to use this module

### ISSUE THREAD

**Issue by IvanBoyko** [terraform-aws-modules/terraform-aws-eks#439]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

I couldn't find any documentation about AWS permissions required to use this module.
We are tightening our security and want to define an IAM Policy with just mandatory permissions.

Or what's the right approach to find those out, instead of banging `terraform apply` million times and adding them one by one?

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by max-rocket-internet** [comment]
Hey @IvanBoyko there's some doc here: https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/eks_test_fixture#iam-permissions

Perhaps it's not obvious though and should be moved into [docs](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/docs)?

**Comment by IvanBoyko** [comment]
Many thanks, @max-rocket-internet , I'll give it a go.
Indeed it might be better to move it to docs and even to reference it on the main `README.md`

**Comment by ffjia** [comment]
I like the idea to move it to `README.md`, and the policy needs to be updated :)

**Comment by max-rocket-internet** [comment]
> Indeed it might be better to move it to docs and even to reference it on the main README.md

Sounds good. PRs welcome.

**Comment by kahootali** [comment]
@max-rocket-internet I have created a PR for this, can you take a look at it?
