### ISSUE TITLE
aws auth map_users multiple groups

### ISSUE THREAD

**Issue by esvirskiy** [terraform-aws-modules/terraform-aws-eks#441]
# I have issues
Adding a user to more than one group with map_users

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

A user can only exist in one group

## What's the expected behavior?
Multiple groups can be assigned to a user. Example:

      user_arn = "arn:aws:iam::9999999999:user/user"
      username = "user"
      groups = ["system:masters", "system:basic-user"]
    },

## Environment details

* Affected module version:
* OS: 
* Terraform version: v0.11.13

**Comment by max-rocket-internet** [comment]
Does this PR from @nauxliu work for you? https://github.com/terraform-aws-modules/terraform-aws-eks/pull/424

**Comment by max-rocket-internet** [comment]
This was resolved ages ago.
