### ISSUE TITLE
Error: Variables not allowed while running terraform apply

### ISSUE THREAD

**Issue by ynraju4** [terraform-aws-modules/terraform-aws-eks#442]
# I have issues

## I'm submitting a...
[root@linux01 terraform-aws-eks]# terraform apply
var.cluster_name
  Name of the EKS cluster. Also used as a prefix in names of related resources.

  Enter a value: firsteks

var.subnets
  A list of subnets to place the EKS cluster and workers within.

  Enter a value: <given subnet-id>

var.vpc_id
  VPC where the cluster and workers will be deployed.

  Enter a value: <given vpc-id>

provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Enter a value: us-east-1

Error: Variables not allowed

  on <value for var.subnets> line 1:
  (source code not available)

Variables may not be used here.

[root@linux01 terraform-aws-eks]

* [ ] bug report
Error: Variables not allowed
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## Are you able to fix this problem and submit a PR? Link here if you have already.

Not able to fix

## Environment details
Using default variables

* Affected module version:
* OS:  RHEL-8.0.0_HVM-20190618-x86_64-1-Hourly2-GP2 (ami-0c322300a1dd5dc79)
* Terraform version:
Terraform v0.12.5
+ provider.aws v2.20.0
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.template v2.1.2

**Comment by max-rocket-internet** [comment]
You're not supposed to run terraform from the root of this repo. Try from `examples/basic` 🙂
