### ISSUE TITLE
EKS k8s v1.11 -> v1.13 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [terraform-aws-modules/terraform-aws-eks#443]
# I have issue

Right now, I am trying to use the latest and greatest v5.0.0 EKS module to do the upgrade. The tf plan looks good, and then I went straight to do the upgrade.

I did not specify cluster_version (so it should be 1.13 by default). I kind of expect it should go straight to v1.13, but seems have step in the middle of using v1.12.

Not sure if that is common upgrade process for everyone.

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?

v1.11 to v1.13 upgrade becomes like v1.11 to v1.12 to v1.13 two upgrades.

## Environment details

All are the latest.

* Affected module version: v5.0.0
* OS: Mac
* Terraform version: 0.12.5

**Comment by chenrui333** [comment]
OK, it turns out I have to explicitly specify cluster_version to v1.13 (to upgrade the cluster to v1.13). That is interesting.

**Comment by chenrui333** [comment]
Also the `cluster_version` on the registry info page needs to be updated:
![image](https://user-images.githubusercontent.com/1580956/61829493-09a8c300-ae37-11e9-8ce4-6f9201c833ba.png)

**Comment by dpiddockcmp** [comment]
Hi. AWS only allows you to upgrade a single minor version at a time. 1.11 -> 1.12 -> 1.13 etc. I highly recommend reading the upgrade documentation for other steps to perform within your cluster when upgrading. AWS does not manage any of the resources within your cluster:
https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

The default cluster version in module version 5.0.0 is 1.12. master branch has been updated to 1.13 but this has not been released yet.
