### ISSUE TITLE
`autoscaling_enabled = true` provision tag which not fit cluster autoscaler helm-chart

### ISSUE THREAD

**Issue by insider89** [terraform-aws-modules/terraform-aws-eks#444]
# I have issues
When you set `autoscaling_enabled = true`, it adds the following tag to ASG: `kubernetes.io/cluster/YOUCLUSTERNAME`, but cluster autoscaler helm chart use following tag to discover ASG `k8s.io/cluster/YOUCLUSTERNAME`, please see latest changes [here](https://github.com/helm/charts/commit/9587fab922920a33247f3f2b815ce0585a995562#diff-0b4714d45280a44e975e49e088149d8a).
## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?

Current cluster autoscaler cannot discover ASG with autodiscovery enabled.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Install cluster autoscaler with autodiscovery set to true.

## What's the expected behavior?

Cluster autosclaler can discovery ASG automatically.

## Environment details

* Affected module version: 4.0.2
* OS: macos
* Terraform version:0.11.14

**Comment by jpke** [comment]
running into this also b/c of the update to cluster-autoscaler helm chart

**Comment by max-rocket-internet** [comment]
OK I see!

I think we add both tags for now? Can someone make a PR?

**Comment by insider89** [comment]
I've tried, but I don't have permission to do it.
```
git push -u origin change-tag-for-asg-autodiscovery
ERROR: Permission to terraform-aws-modules/terraform-aws-eks.git denied to insider89.
```

**Comment by max-rocket-internet** [comment]
@insider89 you make a fork and then create a PR from your fork. It's the standard procedure for public repos otherwise you need to allow everyone write access.

**Comment by insider89** [comment]
Hello @max-rocket-internet. I've created PR, please take a look https://github.com/terraform-aws-modules/terraform-aws-eks/pull/454

**Comment by max-rocket-internet** [comment]
Resolved in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/454

**Comment by insider89** [comment]
Could you please add tag to master v5.1.1?
