### ISSUE TITLE
Could a new release be cut?

### ISSUE THREAD

**Issue by jeffb4** [terraform-aws-modules/terraform-aws-eks#445]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [X] support request
* [X] kudos, thank you, warm fuzzy

## What is the current behavior?

The last release was on May 7th and it's a good release, but I'd like some of the features (like KMS encrypted log streams) that have been incorporated since.

I don't know if a lot of regressions need to be fixed before cutting a new release but if not it'd be super awesome.

At any rate, thank you maintainers for an extremely useful module :)

**Comment by max-rocket-internet** [comment]
> The last release was on May 7th

It was in June, for TF 0.12 😄

But you are right @jeffb4, it has been a while. I was waiting to get the these issues resolved before creating a new release (they all look related):

https://github.com/terraform-aws-modules/terraform-aws-eks/issues/435
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/434
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/429
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/420

Can you test latest commit in master just to see if there's any issues in your environment: `source = git@github.com:terraform-aws-modules/terraform-aws-eks.git?ref=f755300550e0f1975d18f415e4827003a257dc45`

I'll create a new release early next week.

**Comment by DzmitrySudnik** [comment]
I've tested `source = git@github.com:terraform-aws-modules/terraform-aws-eks.git?ref=f755300550e0f1975d18f415e4827003a257dc45` in my environment: works fine including the cloudwatch logs kms encryption

**Comment by jeffb4** [comment]
After the fact (already closed) - but thanks 👍 And I have no idea how I got my Mays and my Junes mixed up.
