### ISSUE TITLE
Override the default ingress rule that allows communication with the EKS cluster API.   

### ISSUE THREAD

**Issue by jimbeck** [terraform-aws-modules/terraform-aws-eks#45]
# I have issues
I would prefer to use the default security groups created for the cluster, but do not want the default API/32 to be used.
## I'm submitting a

* [ ] bug report
* [x] feature request
* [ ] support request

## What is the current behavior
Currently, if you use the default security groups it will create a security group role that allows communication with the eks cluster over the current API/32 cidr.
## What's the expected behavior
I want to override the API/32 cidr and specify my own.
## Environment

* Affected module version: 1.1.0
* OS:
* Terraform version: 0.11.7

**Comment by brandoconnor** [comment]
This can be closed with the merge of #46
