### ISSUE TITLE
worker_group_tags doesn't work

### ISSUE THREAD

**Issue by eug-maly** [terraform-aws-modules/terraform-aws-eks#451]
# I have issues
Cannot add tags per worker_group
## I'm submitting a...

* [ ] bug report
* [x] support request
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?
I want to have 2 worker groups, each with custom tag. For example, if I use this template - https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v4.0.2/examples/basic/main.tf

I've added to variables.tf:
`
variable "worker_group_tags" {
  description = "A map defining extra tags to be applied to the worker group ASG."
  type        = "map"

  default = {
    worker-group-1 = [
      { selector = "wg1" },
      { tag2 = "value2" }
    ]
    worker-group-2 = [
      { selector = "wg2" },
      { tag2 = "value2" }
    ]
  }
}
`

However, no tags were added.

## What's the expected behavior?
Tags are added as specified 

## Environment details

* Affected module version:v4.0.2
* OS:
* Terraform v0.11.14
+ provider.aws v2.20.0
+ provider.helm v0.10.0
+ provider.kubernetes v1.8.1
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.template v2.1.2

**Comment by eug-maly** [comment]
Found that it was implemented in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/252
and example was added (but now it is missed in examples):
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/252/commits/062c229affeefbbebe9d527319e5bbca63d567e6

**Comment by max-rocket-internet** [comment]
Maybe we need a better example of this?

**Comment by eug-maly** [comment]
I didn't find the help on stackoverflow and telegram chats in a short time. so, better example could save someone's time
