### ISSUE TITLE
Pass different kubelet args based on purchase option

### ISSUE THREAD

**Issue by kencieszykowski** [terraform-aws-modules/terraform-aws-eks#455]
# I have issues

Looking to launch an ASG with mixed instances and mixed purchase options.  We'd like to have a base of 3 OnDemand instances (for core cluster services) and the rest be fulfilled with spot instances.  

The feature request would be to pass extra Kubelet args to the OnDemand instances vs. the Spot instances.  I cannot currently see a way this happens, as kubelet args are passed globally for the ASG.

## I'm submitting a...

* [ ] bug report
* [x ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Any instance launched by an ASG receives the same Kubelet args and labels.

## What's the proposed behavior?

Toss different labels via Kubelet for Spot instances vs. base OnDemand instances.  

For example:
node-role.kubernetes.io/spot-worker=true

## Are you able to fix this problem and submit a PR? Link here if you have already.

No :(

## Any other relevant info

If there is a way to do this outside of a feature request (or creating multiple ASGs) I am all ears.  Thank you!

**Comment by max-rocket-internet** [comment]
> The feature request would be to pass extra Kubelet args to the OnDemand instances vs. the Spot instances

This is simply not possible. Even without this module it's not possible 😃

I think you have 2 options:

1. Use multiple worker groups, each with different `kubelet_extra_args`.
2. Write some user-data script that applies to all instance and can detect what type of instance it is and change the kubelet args in there.

**Comment by kencieszykowski** [comment]
Wonderful-- thanks a lot for the quick response and the options.  Will likely go with the second option here.  Appreciate it!

**Comment by toneill818** [comment]
If you want to set the lifecycle label, you can pull it from the instance metadata.
``` bash
kubelet_extra_args   = "--node-labels=node.kubernetes.io/lifecycle=`curl -s http://169.254.169.254/latest/meta-data/instance-life-cycle`"`
```

This will set the lifecycle to either "spot" or "on-demand".
