### ISSUE TITLE
Worker Security Group IDs fail to coalesce at cluster creation

### ISSUE THREAD

**Issue by wmorgan6796** [terraform-aws-modules/terraform-aws-eks#456]
# I have issues

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
During cluster creation I get the following error:

Error: Error in function call

  on .terraform/modules/cluster/terraform-aws-modules-terraform-aws-eks-6ea3582/local.tf line 22, in locals:
  22:   worker_security_group_id = coalesce(
  23: 
  24: 
  25: 
    |----------------
    | aws_security_group.workers is empty tuple
    | var.worker_security_group_id is ""

Call to function "coalesce" failed: no non-null, non-empty-string arguments.**

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Create an EKS cluster in conjuction with the aws-vpc module from terraform. We use the default values for all worker security group vars as we don't touch them.

## What's the expected behavior?

The cluster gets created correctly.

## Are you able to fix this problem and submit a PR? Link here if you have already.
Still debugging issue

## Environment details

* Affected module version: 5.1
* OS: Mac OS 10.14.6
* Terraform version: 0.12.5

**Comment by max-rocket-internet** [comment]
Duplicate of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/402
