### ISSUE TITLE
Tags not working as intended.

### ISSUE THREAD

**Issue by itsSaad** [terraform-aws-modules/terraform-aws-eks#457]
# I have issues
I have the following TF config.

``` hcl
locals {
  tags = {
    "Environment" = var.environment
    "Platform"    = var.platform
    "Provisioner" = var.provisioner
    "Component" = ""
  }
}

module "eks_cluster" {
  source       = "terraform-aws-modules/eks/aws"
  cluster_name = local.name
  subnets      = local.private_subnets
  vpc_id       = local.vpc_id

  worker_groups_launch_template = [{
    name                 = "default-worker-group"
    instance_type        = var.worker_instance_type
    asg_desired_capacity = 1
    tags = merge(local.tags, map("Component", "workers"))
  }]
  tags = merge(local.tags, map("Component", "master"))
}

```
I want to have different tags on the main resources but different tags on the worker resources. Atm all the tags are concatenated into a single list via this line in the code: 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L68
I would like to use completely different tags or some different set of tags for certain resources, By using `merge` instead of `concat`, I believe we can achieve this.
## I'm submitting a...

*  bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Current behaviour is that all tags are combined. If duplicate keys are passed TF will fail.

## Are you able to fix this problem and submit a PR? Link here if you have already.
If we agree on a solution, I can send a PR.

* Affected module version:v5.0.0
* OS: MacOS
* Terraform version:0.12.5

**Comment by itsSaad** [comment]
This is a related issue as well: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/428

**Comment by itsSaad** [comment]
Any feedback about this issue? I would want to have different tags for workers vs the rest of the resuorces and this does not permit that option

**Comment by max-rocket-internet** [comment]
> By using merge instead of concat, I believe we can achieve this.

Sounds reasonable to me. Feel free to make a PR 😃
