### ISSUE TITLE
Specify multiple cluster/worker security groups

### ISSUE THREAD

**Issue by jimbeck** [terraform-aws-modules/terraform-aws-eks#47]
# I have issues

## I'm submitting a

* [ ] bug report
* [x] feature request
* [ ] support request

## What is the current behavior
The EKS plugin currently supports being able to pass in 1 cluster and worker security group by id.
## What's the expected behavior
I think it would make sense to support specifying an array of security group ids.
## Environment

* Affected module version:
* OS:
* Terraform version:

## Other relevant info
We have a use case where we need to attach multiple security groups. Some of which are predefined.

**Comment by tomfotherby** [comment]
We currently use multiple security groups for our Workers as well. This feature would be handy for our migration to this module.

**Comment by tomfotherby** [comment]
Yes, you have it right.

No PR planned from me - I'd be afraid to introduce more problems than I solve ;). Seems the changes planned in Terraform 0.12 might help with this issue as vars will be able to be lists.

**Comment by brandoconnor** [comment]
We all eagerly await the chaos and harmony that 0.12.x promises to bring 😈

**Comment by jimbeck** [comment]
```
1. to have multiple security groups possible for the eks cluster.
2. to allow any of the worker groups to have one or more SG groups.
```
I can create a PR for the first one later today or tomorrow.
I can take a look at the second one later this week.

**Comment by tomfotherby** [comment]
I guess it's not hard for folks that currently use multiple Security Groups to merge them into 1 as a workaround. Having said that, we would love this feature and waiting for TF v0.12 would be a shame.

**Comment by brandoconnor** [comment]
Thanks @jimbeck . Yea I can make a try at the PR for what @tomfotherby is after.

**Comment by max-rocket-internet** [comment]
Now supported 👌
