### ISSUE TITLE
cluster_security_group_id not creating ingress rule with caller public IP/32

### ISSUE THREAD

**Issue by albertoal** [terraform-aws-modules/terraform-aws-eks#471]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

As shown in the docs, if not providing a `cluster_security_group_id`, a cluster security group gets created that provides access to the workers as well as the callers' IP/32:

> If not given, a security group will be created with necessary ingres/egress to work with the workers and provide API access to your current IP/32.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/b8b3b5820e18f6f054314e460ef5332c75d35e90/variables.tf#L23

The security group does get created correctly, but the rule doesn't get added. I believe this is because a resource `aws_security_group_rule` which creates the relevant ingress rule, is missing.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```
module "cluster" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "5.1.0"
  cluster_name    = "${local.environment}-${local.service}-cluster"
  subnets         = var.subnets
  vpc_id          = var.vpc

  worker_groups = [
    {
      instance_type = "t3.medium"
      asg_max_size  = 2
      tags = [{
        key                 = "Name"
        value               = "${local.environment}-${local.service}-node"
        propagate_at_launch = true
      }]
    }
  ]

  tags = local.tags
}
```

## What's the expected behavior?

`aws_security_group_rule` of type ingress attached to `aws_security_group.cluster[0].id` which contains the caller IPv4 in CIDR /32 format.

## Are you able to fix this problem and submit a PR? Link here if you have already.

Yes, but this is currently not supported natively in terraform, and an external data source will need to be added to call a service like `myip.opendns.com` in order to store the callers IP. If the project maintainers are happy to create this external dependency, I'm happy to do this otherwise, I can create a PR to remove references to it in the docs.

## Environment details

* Affected module version: 5.1.0
* OS: 
* Terraform version: 0.12.6

## Any other relevant info

Screenshot of the resulting security group, lacking the inbound rule:

<img width="1411" alt="Screen Shot 2019-08-15 at 9 56 24 AM" src="https://user-images.githubusercontent.com/1752588/63111744-32f2d580-bf43-11e9-89e6-033809da12ff.png">

**Comment by dpiddockcmp** [comment]
Oops that's super old documentation from a misunderstanding when the module was first written.

That documentation needs updating to remove mention of the caller's IPv4 address. You cannot add filters to the cluster's public endpoint.

**Comment by albertoal** [comment]
Hey @dpiddockcmp that makes sense - thanks for the update to the docs. Do you think it's worth clarifying that if setting `cluster_endpoint_public_access` to `true`, then a `cluster_security_group_id` with access to the caller IP needs to be passed? I know this can sound obvious but might be worth noting or adding an example as otherwise the cluster creation will throw an error like the following if using `aws_auth`:

```
module.cluster.null_resource.update_config_map_aws_auth[0] (local-exec): error: unable to recognize "aws_auth_configmap.yaml": Get https:/{cluster-endpoint}.eks.amazonaws.com/api?timeout=32s: dial tcp {cluster-ip}:443: i/o timeout
```

**Comment by dpiddockcmp** [comment]
The public endpoint is always world accessible. AWS currently does not allow us to restrict access. There's no need to add the caller's IP to a security group.

**Comment by albertoal** [comment]
Thanks for clarifying @dpiddockcmp - I tested this and you are right; the public endpoint is world accessible unless explicitly disabled.

The error above was probably due to me setting `cluster_endpoint_public_access` to false initially.

All clear now. Thanks for your help!
