### ISSUE TITLE
getting error "This object does not have an attribute named "latest_version".

### ISSUE THREAD

**Issue by anup1384** [terraform-aws-modules/terraform-aws-eks#479]
I have an issue while running terraform plan.
Error: Unsupported attribute

  on terraform-aws-eks/workers.tf line 247, in resource "random_pet" "workers":
 247:           aws_launch_configuration.workers[count.index].latest_version
    |----------------
    | aws_launch_configuration.workers is tuple with 1 element
    | count.index is 0

This object does not have an attribute named "latest_version".

**Comment by barryib** [comment]
Thanks @anup1384 for reporting this. Launch configuration doesn't have version. I'll make a new PR to fix this.

**Comment by barryib** [comment]
@anup1384 Is https://github.com/terraform-aws-modules/terraform-aws-eks/pull/482 fix your issue ?

**Comment by vranystepan** [comment]
@barryib yesterday we did the same fix in our codebase and it works good 👍 Thank you very much!
