### ISSUE TITLE
Add support for adding container insights

### ISSUE THREAD

**Issue by cplee** [terraform-aws-modules/terraform-aws-eks#484]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I'd like to add support to provision the necessary resources within the cluster to enable [Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-EKS.html).

Before I begin, i'm looking for feedback on my approach:

* New module variable named `cluster_container_insights_metrics` to turn on feature (default == false)
* Update the cluster IAM role to include the policy `CloudWatchAgentServerPolicy` (assuming `manage_cluster_iam_resources` == true)
* If enabled, provision the necessary serviceaccount, clusterrole, clusterrolebinding, configmap, daemonset for Container Insights (see: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html)
* New module variable named `cluster_container_insights_logs` to turn on feature (default == false)
* If enabled, provision the necessary serviceaccount, clusterrole, clusterrolebinding, configmap, daemonset for Container Insights logs(see: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html)

## What's the expected behavior?
When enabled, the cluster has container insights metrics and/or logs configured for the cluster

## Are you able to fix this problem and submit a PR? Link here if you have already.
Yes, once I hear 👍 

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by max-rocket-internet** [comment]
Hi @cplee!

I'm always open to be persuaded but my feeling here would be to not include this. The reasons are covered in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/99 but I'll reiterate here:

- This module is already complicated enough 
- If we add this then why not Sysdig? and New Relic?
- There are already much better tools for this that manage installation, upgrades and different settings (Helm)

I would suggest you make a Helm Chart for Container Insights 🙂

**Comment by max-rocket-internet** [comment]
Also, FYI there's already a cloudwatch pluging for fluent-bit: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit

**Comment by cplee** [comment]
Sounds good, thanks

**Comment by moniecodes** [comment]
Hi, I have read all the various responses about cluster add-ons, and generally agree. However, I have a case for Container Insights. Since CloudWatch Container Insights are now available as a built in AWS feature with EKS resources, and can easily be added as a setting. It is also supported in the primitive form here
https://www.terraform.io/docs/providers/aws/r/ecs_cluster.html#setting

Can we please simply add a settings option to this module, and pass it through here, such that we can easily enable containerInsights
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/cluster.tf#L9

Thanks!

**Comment by max-rocket-internet** [comment]
@moniecodes I think you are mixing up ECS and EKS.

**Comment by moniecodes** [comment]
Yes, I just noticed this and deleted my comment! arg, wishful thinking.. I imagine if it was available so easily support would have been added. Thanks
