### ISSUE TITLE
Adding ASGs to cluster after initial creation?

### ISSUE THREAD

**Issue by kencieszykowski** [terraform-aws-modules/terraform-aws-eks#485]
# I have issues

I'm hitting a mental block here and am curious if this module can apply to the behavior I'm lookin for.  

We are looking to deploy a couple of rather monolithic clusters with ASGs for different types of applications.  I've forked the module to suit our environment (especially since we need to stay on 4.0.2 because of TF 11), but cannot seem to figure out how to call the module to create additional ASGs in a cluster that's been set up.

Right now I have created two mixed instance type ASGs using the module for cluster A; if I want to iterate and create another ASG (and eventually yet another one), while keeping all of the others live, is this possible? 

Apologies for the newb question, and thank you for the advice!

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [X] support request
* [ ] kudos, thank you, warm fuzzy

**Comment by max-rocket-internet** [comment]
Sure that's possible (if I understand correctly). Perhaps you are missing the `xx_count` variables?

Here's one of our clusters:

```hcl
  worker_group_count                       = 0
  worker_group_launch_template_count       = 1
  worker_group_launch_template_mixed_count = 2

  worker_groups_launch_template = [
    {
      name                = "on-demand-1"
      instance_type       = "m5.xlarge"
      asg_max_size        = 40
      asg_min_size        = 0
      autoscaling_enabled = false
  ]

  worker_groups_launch_template_mixed = [
    {
      name                     = "prom-spot-1"
      override_instance_type_1 = "r5.4xlarge"
      override_instance_type_2 = "r5a.4xlarge"
      override_instance_type_3 = "r5ad.4xlarge"
      override_instance_type_4 = "c5.9xlarge"
      spot_instance_pools      = 4
      asg_max_size             = 1
    },
    {
      name                     = "spot-1"
      override_instance_type_1 = "m5.2xlarge"
      override_instance_type_2 = "c5.2xlarge"
      override_instance_type_3 = "t3.2xlarge"
      override_instance_type_4 = "r5.2xlarge"
      spot_instance_pools      = 4
      asg_max_size             = 30
      autoscaling_enabled      = true
  ]
```
