### ISSUE TITLE
Unable to perform initial creation of aws_auth configmap

### ISSUE THREAD

**Issue by AlexMichaelJonesNC** [terraform-aws-modules/terraform-aws-eks#486]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [x] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
It's possible this is somehow user error, since I have used the module recently, and it worked fine, but there appears to be a chicken and egg problem in setting up AWS auth.  

The module fails to upload the aws_auth config map because it's use `--kubeconfig` and setting it to use a kubeconfig that is using the newly provisioned AWS role. The problem is that since the aws_auth config map hasn't been created yet, that role has no permissions and is not able to be used to upload the configmap, it fails with an unauthorized request to k8s. 

The offending line should be this one. https://github.com/terraform-aws-modules/terraform-aws-eks/blob/8580b678139ff491db2ff25f414c913bf7d37008/aws_auth.tf#L18

The easy workaround I've been using is to remove the role from the kubeconfig locally and applying the config map by hand, and then running terraform again to finish out our apply. 

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Create a EKS cluster with the module. The behavior should be present if the module is configured to apply aws_auth to the cluster

## What's the expected behavior?
the aws_auth file should upload successfully, possibly using a custom version of the kubeconfig that doesn't attempt to set a role (until after the role is created) 

## Are you able to fix this problem and submit a PR? Link here if you have already.
If this is confirmed to be a bug, I can make a PR, but I'm not exactly sure what the right fix would be. Making a second rendered kubeconfig seems heavy handed, and there might be something better.

## Environment details

* Affected module version: 4.0.2
* OS: OsX
* Terraform version: 0.11.13

**Comment by max-rocket-internet** [comment]
> The problem is that since the aws_auth config map hasn't been created yet, that role has no permissions and is not able to be used to upload the configmap, it fails with an unauthorized request to k8s.

If you create the cluster then you should have access to apply the configmap: https://docs.aws.amazon.com/eks/latest/userguide/create-cluster.html

> When an Amazon EKS cluster is created, the IAM entity (user or role) that creates the cluster is added to the Kubernetes RBAC authorization table as the administrator (with system:master permissions. Initially, only that IAM user can make calls to the Kubernetes API server using kubectl.

**Comment by AlexMichaelJonesNC** [comment]
Yes, I was able to resolve the issue by applying the configmap manually, but to me it still seems like a problem that the module cannot successfully apply the configmap itself. The code to do so simple does not work.

This limitation should either be mentioned somewhere in the readme, or resolved. I'm just trying to figure out what approach seems reasonable before I open a PR. I've not contributed to here before, and I want to do my best to make sure a PR would be accepted before I invest any significant effort.

**Comment by max-rocket-internet** [comment]
> seems like a problem that the module cannot successfully apply the configmap itself

Yes. You applying it manually and the module doing it should be effectively the same.

> This limitation should either be mentioned somewhere in the readme

It's a bug then. It should be applied by the module.

If you can debug on in your env workout why it's not working and create a PR to fix then great!

**Comment by AlexMichaelJonesNC** [comment]
I managed to track this down to our use of `kubeconfig_aws_authenticator_additional_args` setting to set a role change as part of our auth scheme (after creation we manage all k8s access via roles).

`kubeconfig_aws_authenticator_additional_args = ["-r", "${var.admin_primary_role}"]`

I can't think of a sane way to handle the initial bootstrap given that this is an optional flag, and it's just our use of it that causes the problem. 

Since its our settings that are causing the problem, I don't think I would count this as a bug anymore. 

Thank you for all the help and for maintaining this great project.
