### ISSUE TITLE
EKS upgrade Using Terraform

### ISSUE THREAD

**Issue by dhineshbabuelango** [terraform-aws-modules/terraform-aws-eks#487]
Hi All, We are using terraform to provision EKS cluster and worker nodes.

To upgrade the EKS cluster using terraform, we tried just changing the version number(for EKS master) and the worker node AMI(for worker node upgrade) and it was working fine as expected. 

But AWS mentioned to check and upgrade  the below components as part of the EKS upgrade. Can this be achieved in terraform itself.

Update kube-proxy, CoreDNS, Amazon VPC CNI, and GPU Support

Also I have been going through the below link for worker node upgrade and they have asked to create a new worker group, does this really needed or we can just update teh AMI id to the new worker node and doubt the autoscaling group desired count for the new set of nodes to get provisioned and then destroy the old nodes.

https://www.bluematador.com/blog/upgrading-kubernetes-on-eks-with-terraform

**Comment by hunterchris** [comment]
@dhineshbabuelango You can use the `kubernetes` provider and create the deployment/daemonset definitions in terraform. An example of the `aws-node` definition would be:
```
resource "kubernetes_daemonset" "aws-node" {
  metadata {
    name      = "aws-node"
    namespace = "kube-system"
    labels {
      k8s-app = "aws-node"
    }
  }
  spec {
    revision_history_limit = 10
    selector {
      match_labels {
        k8s-app = "aws-node"
      }
    }
    template {
      metadata {
        labels {
          k8s-app = "aws-node"
        }
      }
      spec {
        service_account_name   = "aws-node"
        dns_policy                       = "ClusterFirst"
        host_network                   = "true"
        restart_policy                   = "Always"
        termination_grace_period_seconds = 30
        volume {
          name = "cni-bin-dir"
          host_path {
            path = "/opt/cni/bin"
          }
        }
        volume {
          name = "cni-net-dir"
          host_path {
            path = "/etc/cni/net.d"
          }
        }
        volume {
          name = "log-dir"
          host_path {
            path = "/var/log"
          }
        }
        volume {
          name = "dockersock"
          host_path {
            path = "/var/run/docker.sock"
          }
        }
        toleration {
          operator = "Exists"
        }
        container {
          image             = "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:${var.awsnode_release}"
          name              = "aws-node"
          image_pull_policy = "Always"

          volume_mount {
            name       = "cni-bin-dir"
            mount_path = "/host/opt/cni/bin"
          }
          volume_mount {
            name       = "cni-net-dir"
            mount_path = "/host/etc/cni/net.d"
          }
          volume_mount {
            name       = "log-dir"
            mount_path = "/host/var/log"
          }
          volume_mount {
            name       = "dockersock"
            mount_path = "/var/run/docker.sock"
          }
          env {
            name  = "AWS_VPC_K8S_CNI_LOGLEVEL"
            value = "DEBUG"
          }
          env {
            name = "MY_NODE_NAME"
            value_from {
              field_ref {
                field_path  = "spec.nodeName"
                api_version = "v1"
              }
            }
          }
          env {
            name = "WATCH_NAMESPACE"
            value_from {
              field_ref {
                field_path = "metadata.namespace"
              }
            }
          }
          port {
            container_port = "61678"
            host_port      = "61678"
            name           = "metrics"
            protocol       = "TCP"
          }
          security_context {
            allow_privilege_escalation = false
            privileged                 = true
          }
          resources {
            requests {
              cpu = "10m"
            }
          }
        }
      }
    }
  }
}
```
The variable `awsnode_release` will do the trick. Also, make sure to pick the ECR registry that matches your region.

**Comment by max-rocket-internet** [comment]
> But AWS mentioned to check and upgrade the below components as part of the EKS upgrade.
> Update kube-proxy, CoreDNS, Amazon VPC CNI, and GPU Support

Yes, super important 😃

> Can this be achieved in terraform itself

For sure but not in this module presently.

That example from @hunterchris is a great starting point but you must be very careful if you using something like this as it's not as simple as updating docker image tag of `amazon-k8s-cni`. There are quite a few other changes to associated resources and settings. For example compare [1.4](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.4/aws-k8s-cni.yaml) with [1.5](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.5/aws-k8s-cni.yaml)

> we can just update teh AMI id to the new worker node and doubt the autoscaling group desired count for the new set of nodes to get provisioned and then destroy the old nodes.

Yes, you can do this. That's what I think most users are doing now. Some details are here: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/412#issuecomment-507270902

**Comment by dhineshbabuelango** [comment]
Thanks Max and Chris.
