### ISSUE TITLE
Provision the EKS cluster and join the worker nodes without using Kubectl

### ISSUE THREAD

**Issue by dhineshbabuelango** [terraform-aws-modules/terraform-aws-eks#488]
Hi All, 
We are using terraform to provision EKS. Once the EKS master and worker nodes are provisioned through terraform, we will run a kubectl command to create a config map aws-auth  to enable worker nodes to join your cluster. Can this be achieved in terraform itself without running any kubectl commands. 

![image](https://user-images.githubusercontent.com/51995628/64000980-6fc0ee00-cb39-11e9-9bcd-93911669dadb.png)

**Comment by max-rocket-internet** [comment]
Yes, it's already done automatically by this module.

**Comment by dhineshbabuelango** [comment]
Hi Max, it’s automatically done?
Could you please give me more details if possible. On which module?
Thanks again for your reply.

**Comment by max-rocket-internet** [comment]
In here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/aws_auth.tf

**Comment by dhineshbabuelango** [comment]
Thanks Max,  I tried it is working. But when we provision a new EKS cluster with only private endpoint enabled, will we be still able to apply the aws-auth config map. Since we are running terraform from our local and EKS endpoint will not be resolved outside of its VPC, with only private endpoint enabled, will we be able to run the aws-auth configmap

**Comment by max-rocket-internet** [comment]
> when we provision a new EKS cluster with only private endpoint enabled, will we be still able to apply the aws-auth config map

Nope 🙂

**Comment by dhineshbabuelango** [comment]
Thanks Max, so we can run aws-auth config map for private endpoint only enabled EKS cluster, if we run the terraform scripts inside a ec2 instance which is running in the same VPC as EKS cluster

**Comment by max-rocket-internet** [comment]
Exactly. Terraform is running kubectl, kubectl needs to auth and connect to the EKS API endpoint. You can make that happen by running Terraform from within your VPC, or using a VPN, or SSH tunnelling etc.

**Comment by max-rocket-internet** [comment]
Sorry, I didn't mean to close the issue so feel free to reopen it 🙂

**Comment by dhineshbabuelango** [comment]
Thanks Max, that answered my question :)
