### ISSUE TITLE
Examples currently as of 5.1.0 are applicable for the master and not the release version

### ISSUE THREAD

**Issue by mariogeorgievft** [terraform-aws-modules/terraform-aws-eks#491]
Trying to do the examples with 5.1.0 will result in errors, because they have been set up for the master changes, rather than the release.

Please take a look at it. 

Thanks!

**Comment by max-rocket-internet** [comment]
They are supposed to be for master.

If you want to run an example for `5.1.0` then you need to look at the examples from that tag:
https://github.com/terraform-aws-modules/terraform-aws-eks/tree/v5.1.0/examples

Make sense? 🙂

**Comment by mariogeorgievft** [comment]
Understood, thank you!
