### ISSUE TITLE
Broken link to spot instances doc in registry page

### ISSUE THREAD

**Issue by marcelloromani** [terraform-aws-modules/terraform-aws-eks#493]
The module documentation page in Terraform Registry

https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/5.1.0

contians a link to a document which supposedly tells the user "How to use spot instances with this module"

The link is: https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/docs/spot-instances.md

which returns a 404 Not Found error

The correctr link to the markdown file on github is https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/spot-instances.md

**Comment by marcelloromani** [comment]
There is a potential problem here though. The module version published in the terraform registry has a specific version.
The absolute URL would always point to master.
This means the documentation could appear out of date if changes occur between the version the user has selected on the terraform registry page and master.

It seems to be this is a limit of the terraform registry interface, which apparently only supports the README file.

Anyhow, the same applies for other links to documentation, so here's the PR.

**Comment by max-rocket-internet** [comment]
> The absolute URL would always point to master.

Yep true. I don't see how to solve that nicely unfortunately.

Thanks for the PR.
