### ISSUE TITLE
OIDC Identity Issuer Option

### ISSUE THREAD

**Issue by joshkurz** [terraform-aws-modules/terraform-aws-eks#495]
When will these options be available in tf? https://docs.aws.amazon.com/eks/latest/APIReference/API_Identity.html

Would like to create clusters with AWS OIDC issuer URLs. 

Is it on the roadmap? I could help get this in the project if not.

**Comment by skang0601** [comment]
This has to be resolved further upstream FYI. 
The Terraform Providers currently do not expose this field and the aws go sdk does not seem to as well as of yet.

**Comment by joshkurz** [comment]
gotcha, made a comment here https://github.com/weaveworks/eksctl/pull/1265#issuecomment-528103860 seeing what the plan was to get that fork upstream or if something else needed to be done. I don't see any reference in upstream of oidc for eks.

**Comment by barryib** [comment]
FYI There is an issue tracking this in [terraform-provider-aws](https://github.com/terraform-providers/terraform-provider-aws/issues/9995).

**Comment by morganchristiansson** [comment]
Terraform aws provider 2.28.0 will have oidc support. Being released on thursday supposedly. https://github.com/terraform-providers/terraform-provider-aws/issues/9995#issuecomment-528924285

Upcoming changelog: https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md

ENHANCEMENTS:
data-source/aws_eks_cluster: Add identity attribute (support getting OIDC issuer URL) [GH-10006]
resource/aws_eks_cluster: Add identity attribute (support getting OIDC issuer URL) [GH-10006]
