### ISSUE TITLE
Shell Script inside Terraform EKS

### ISSUE THREAD

**Issue by dhineshbabuelango** [terraform-aws-modules/terraform-aws-eks#501]
Hi All, We are using Terraform to provision EKS cluster. 
I am trying to run a shell script inside terraform after the EKS master and autoscaling group completed., the module looks like below

![image](https://user-images.githubusercontent.com/51995628/64679962-5ca20c80-d4af-11e9-995d-8b32bd0ae5ef.png)

I want to pass the eks cluster name in the shell script.

**Comment by barryib** [comment]
Ok. What is the question ? Your null_ressource is not working as expected ? What is the problem ? Can you elaborate please.

**Comment by dhineshbabuelango** [comment]
Hi @barryib, thanks for your reply.
Actually, I am trying to run a shell script inside terraform, I trigger the script like below

sh /Users/dhineshbabu.elango/Documents/Terraform_shellScripts/bin/eks_app_provision.sh "test-eks-dev"

In the above command, test-eks-dev is my cluster name, actually instead of hardcoding the cluster name, is there any way I can get input from terraform like var.test_cluster_name.

**Comment by barryib** [comment]
You can run your provisionner like this.

```hcl
variable "test_cluster_name" {
  value = "your_cluster_name_here"
}

# call the terraform-aws-eks module to deploy your EKS cluster
module "my_cluster" {
  source       = "terraform-aws-modules/eks/aws"
  cluster_name = var.cluster_name

  # ...
}

# Use the cluster_id output in your null resource
resource "null_resource" "eks_master_worker_join" {
  provisioner "local-exec" {
    command = "sh /Users/dhineshbabu.elango/Documents/Terraform_shellScripts/bin/eks_app_provision.sh ${module.my_cluster.cluster_id}"
  }
}
```

You can also depends on `workers_asg_arns` or workers_asg_names output to run when ASG are ready.

**Comment by dhineshbabuelango** [comment]
Thanks @barryib for your response. 
In my case, both cluster provisioning and null resource will come in the same module, however i slightly changed the script based on your suggestion, it is working fine now.

The script now works like below.

command = "sh /Users/dhineshbabu.elango/Documents/Terraform_shellScripts/bin/eks_app_provision.sh ${aws_eks_cluster.master-node.name}"

Thanks for your help.

**Comment by barryib** [comment]
Great. Closing this.
