### ISSUE TITLE
Credentials in non-default location causes token authentication to fail

### ISSUE THREAD

**Issue by nbhargava** [terraform-aws-modules/terraform-aws-eks#509]
# I have issues

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [X] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

The module doesn't seem to be able to apply the auth ConfigMap when using credentials from a non-default source. 

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Remove any AWS credentials from `~/.aws/credentials` and put them in the current working directory. When running, `module.eks.null_resource.update_config_map_aws_auth[0]` will continually fail and retry. After 10 retries, it silently marks creation as done instead of marking it as failed.

Below I've included a snippet which includes the appropriate env variables which when passed to `aws-iam-authenticator`, should work (i.e. it works fine when running those commands normally with the provided env variable).

```
module "eks" {
  source       = "terraform-aws-modules/eks/aws"
  cluster_name = local.cluster_name
  subnets      = module.vpc.public_subnets

  vpc_id = module.vpc.vpc_id

  worker_groups = [
    {
      name                          = "worker-group-2"
      instance_type                 = "t2.medium"
      asg_desired_capacity          = 2
    },
  ]

  kubeconfig_aws_authenticator_env_variables = {
    AWS_SHARED_CREDENTIALS_FILE = "./creds"
  }

  manage_aws_auth = true
}
```

## What's the expected behavior?

Ideally, it should pick up the credentials file from the non-default location. At minimum, it should fail instead of silently being marked as created

## Are you able to fix this problem and submit a PR? Link here if you have already.

I'm not sure where this problem is, but if I were pointed in the right direction, I could take a stab at it.

## Environment details

* Affected module version: 5.1.0
* OS: macOS 10.14.6
* Terraform version: v0.12.6

## Any other relevant info

**Comment by max-rocket-internet** [comment]
Perhaps `AWS_SHARED_CREDENTIALS_FILE` doesn't work for `aws-iam-authenticator`? can you test that?

**Comment by nbhargava** [comment]
Yup, it seems to be a valid env variable that is actually read.

```
$ aws-iam-authenticator token -i test-eks-NDPMHNd5
could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

$ AWS_SHARED_CREDENTIALS_FILE=./creds-moved aws-iam-authenticator token -i test-eks-NDPMHNd5
{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1alpha1","spec":{},"status":{"expirationTimestamp":"2019-09-16T14:42:52Z","token":<redacted>}}
```
