### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by wmorgan6796** [terraform-aws-modules/terraform-aws-eks#512]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [X] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Currently the README says that releases will be done at least every 2 weeks on the repo, but currently there hasn't been a new release since July.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

N/A

## What's the expected behavior?

Its expected that a release will be done every 2 weeks, yet it hasn't been. We've been waiting on new features, including the OIDC support, but are weary of pointing to an individual commit or to the master branch. What can be done to get back on track with releases?

## Environment details

* Affected module version:
* OS:
* Terraform version:

## Any other relevant info
This is a great plugin and we have been relying on it for a while now. It is disheartening that the release schedule has fallen off.

**Comment by max-rocket-internet** [comment]
> Currently the README says that releases will be done at least every 2 weeks

I'll remove this. None of the other modules in the org are committing to any release timeframe.

> What can be done to get back on track with releases?

One or both of:

1. More spare time in my life
2. More maintainers of this repo

> weary of pointing to an individual commit

Don't be 😃

@wmorgan6796 (or anyone) please can you test this:

```
source = "git::https://github.com/terraform-aws-modules/terraform-aws-eks.git?ref=43d7f00e983c97e81c2c217814aad56977b15909"
```

If it looks OK, I'll merge https://github.com/terraform-aws-modules/terraform-aws-eks/pull/514

**Comment by wmorgan6796** [comment]
To test, what needs to be done? I can test the large features that are in this release by just using them and ensuring that they're set up correctly. Would there be anything else?

**Comment by max-rocket-internet** [comment]
Sorry, I should have been more specific. Just run `terraform plan` in your environment with this module source and see if there's any issues that are not already noted, like breaking changes. No need to test specific features!

**Comment by jjshanks** [comment]
Note that the commit is on a fork so you actually need a source of

```
source = "git::https://github.com/max-rocket-internet/terraform-aws-eks.git//?ref=43d7f00e983c97e81c2c217814aad56977b15909"
```

**Comment by barryib** [comment]
> One or both of:
>- More spare time in my life
>- More maintainers of this repo

@max-rocket-internet If you need more help to maintain this repo, I can help. Just let me know.

**Comment by max-rocket-internet** [comment]
Here: https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v6.0.0

**Comment by max-rocket-internet** [comment]
@barryib can you message me on Kubernetes Slack org? `max.williams` 🙂
