### ISSUE TITLE
Destroy fails on an empty state

### ISSUE THREAD

**Issue by mbevc1** [terraform-aws-modules/terraform-aws-eks#513]
# I have issues
Destroying on empty state.

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
```Error: Error in function call

  on .terraform/modules/eks/terraform-aws-modules-terraform-aws-eks-6ea3582/local.tf line 6, in locals:
   6:   cluster_security_group_id = coalesce(
   7: 
   8: 
   9: 
    |----------------
    | aws_security_group.cluster is empty tuple
    | var.cluster_security_group_id is ""

Call to function "coalesce" failed: no non-null, non-empty-string arguments.
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Run it on empty state with no infrastructure provisioned.

## What's the expected behaviour?
Do nothing and exit without error.

## Are you able to fix this problem and submit a PR? Link here if you have already.
Can do if nobody beats me to it :smile: 

## Environment details

* Affected module version: v5.1.0
* OS: Linux
* Terraform version: 0.12.8

## Any other relevant info
/

**Comment by barryib** [comment]
Closing as duplicate https://github.com/terraform-aws-modules/terraform-aws-eks/issues/402 and resolved by https://github.com/terraform-aws-modules/terraform-aws-eks/pull/459

Feel free to reopen the issue if the provided PR doesn't resolve your problem.
