### ISSUE TITLE
Terraform Module forcing EKS Cluster recreation in case of instance_type change or ami change

### ISSUE THREAD

**Issue by jmukhtar** [terraform-aws-modules/terraform-aws-eks#518]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [x] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
We are running an EKS Cluster that was created using the terraform-aws-eks module. We need to change the instance type from t3.medium to r4.large. We updated the instance_type field and run terraform apply, terraform is trying to recreate the cluster as well. 

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Not sure if it's a bug or our understanding. We have a very simple configuration

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "5.1.0"

  cluster_name                    = "eks-devtest"
  subnets                         = [aws_subnet.eks-privateAzA.id, aws_subnet.eks-privateAzB.id]
  vpc_id                          = aws_vpc.eks-vpc.id
  config_output_path              = "/tmp/"
  cluster_endpoint_private_access = "true"
  write_aws_auth_config           = "false"
  write_kubeconfig                = "false"

  worker_groups = [
    {
      instance_type         = "t3.medium"
      asg_max_size          = 5
      autoscaling_enabled   = true
      protect_from_scale_in = true
    },
  ]

  workers_group_defaults = {
    key_name = "devKey"
  }

  tags = {
    environment = "DevEnv"
    technology  = "EKS"
  }
}
```

Once created, we changed the instance_type to r4.large and run terraform plan followed by terraform apply and got following error

```
  # module.eks.aws_eks_cluster.this must be replaced
+/- resource "aws_eks_cluster" "this" {
.
.
.
.
Plan: 3 to add, 2 to change, 2 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.eks.aws_eks_cluster.this: Creating...

Error: error creating EKS Cluster (eks-devtest): ResourceInUseException: Cluster already exists with name: eks-devtest
	status code: 409, request id: bb131dff-0156-456f-a47e-46bd45ce7506
```

## What's the expected behavior?
Expected behaviour should be to update the worker nodes instance type

## Are you able to fix this problem and submit a PR? Link here if you have already.
No

## Environment details
Dev

* Affected module version:
* OS: Amazon Linux
* Terraform version: v0.12.6

## Any other relevant info

**Comment by barryib** [comment]
Can you provide the terraform plan output for `module.eks.aws_eks_cluster` ? From the provider code, it only force replacement when one of these argument change : [name](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_eks_cluster.go#L90), [role_arn](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_eks_cluster.go#L100), [security_group_ids](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_eks_cluster.go#L132) or [subnet_ids](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_eks_cluster.go#L138).

**Comment by jmukhtar** [comment]
# module.eks.aws_eks_cluster.this must be replaced
+/- resource "aws_eks_cluster" "this" {
      ~ arn                       =
"arn:aws:eks:eu-west-1:AWS_ACCOUNT_ID:cluster/eks-devtest" -> (known after
apply)
      ~ certificate_authority     = [
          - {
              - data =
"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1EVXlNVEE1TVRnME5Wb1hEVEk1TURVeE9EQTVNVGcwTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSlVFCm1PR2xrRnpjOXFubUhXdkJQOTZQK0tuVG03dU11cDd6UTh5QUo2Zmhxc05kMU1SSWp6VWRONDNoZXp0RU1qalUKd2hLdEFDdEwrR3FkdTVGVDRlYlhXZFlsTTZGQVBwczI0Z3J1YTZuSVV1NlJSRWFPcHlVQVFob0d2c2IvMGxoeAp5QlFSY0N3RWdWaWgzV0MrUlRzN0dTTkx3cG0zK1A5TVhHWEtuRTF5SWhpekJ3RVEwZHJ6VEJHRkcwV1RiSVdYCncyR1hjOGp5WmdJcFJISzlyOUJBRlhuRFAzRDFkM0tNeGI4RVBUVndvSHZraVpIMjE3THVIWE4zV1lyNmQyZ3MKU0pZd1BFZDdUU2xFbURYNG9lZW42SWY1b1haazhROVJYYmpNaWp0RWx1NkRlMHhCTWYzY0RyT2FnUGpyeGt1WAptRW1TOWh4Y2ZOa2xuRnJncnI4Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIcXRUbnJzV1VWbkdKajJtREtuNG5UaUJQbkUKQWpkVUhVWjFXcmd3OXFjaWx5L1NSdWtvYW9JQmFmU2pSUnNBOEVxWHo2TnBKbTRlbHE4N2IzUXFBNXlwQ2tnZQpwU2s3dUpndCttT21nYzJlOHl4TkZLQjd1ZmhqNUw1WEh4b0V3OXhBcmJCVzg4eFo3cW9KS2hTc2orTkRGVm9FCldTTE9zcnZGQzd4eUZsQ3YrS2l5RWpMcWw0MmtJemZ5OWIrTW44bGJ2SURIY3EvK3VoZnU3RXNGSVdmSHFDVlAKNWRqSGppYXB1WVMyakdDTkUydjFjbVRXMVRQUlNLb2I1SDNrS0lPeGpKakhmNDh3N0xGMmswS0FyMHdYRWozRApraGdYMEZIeW8vZGJ2a3ZPelk1WjFXZk1Rd21wQ01kbzFUQTg2Y0tJUHZmMkFYSTJxcVBoYTdGbGhTaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
            },
        ] -> (known after apply)
      ~ created_at                = "2019-05-21 09:11:26 +0000 UTC" ->
(known after apply)
      - enabled_cluster_log_types = [] -> null
      ~ endpoint                  = "
https://LONG_BORING_ID.sk1.eu-west-1.eks.amazonaws.com" -> (known after
apply)
      ~ id                        = "eks-devtest" -> (known after apply)
      ~ identity                  = [
          - {
              - oidc = [
                  - {
                      - issuer = "
https://oidc.eks.eu-west-1.amazonaws.com/id/ANOTHER_LONG_ID"
                    },
                ]
            },
        ] -> (known after apply)
        name                      = "eks-devtest"
      ~ platform_version          = "eks.4" -> (known after apply)
        role_arn                  =
"arn:aws:iam::AWS_ACCOUNT:role/eks-devtest20190521091115568800000001"
      ~ status                    = "ACTIVE" -> (known after apply)
        version                   = "1.13"

        timeouts {
            create = "15m"
            delete = "15m"
        }


It also looks like we are being forced to use a new AMI

image_id                         = "ami-0199284372364b02a" ->
"ami-00ea6211202297fe8" # forces replacement

Any help as to how to get around this would be really helpful


--------
Regards,
Junaid

**Comment by jmukhtar** [comment]
# module.eks.aws_eks_cluster.this must be replaced
+/- resource "aws_eks_cluster" "this" {
      ~ arn                       =
"arn:aws:eks:eu-west-1:AWS_ACCOUNT_ID:cluster/eks-devtest" -> (known after
apply)
      ~ certificate_authority     = [
          - {
              - data =
"DATA"
            },
        ] -> (known after apply)
      ~ created_at                = "2019-05-21 09:11:26 +0000 UTC" ->
(known after apply)
      - enabled_cluster_log_types = [] -> null
      ~ endpoint                  = "
https://LONG_BORING_ID.sk1.eu-west-1.eks.amazonaws.com" -> (known after
apply)
      ~ id                        = "eks-devtest" -> (known after apply)
      ~ identity                  = [
          - {
              - oidc = [
                  - {
                      - issuer = "
https://oidc.eks.eu-west-1.amazonaws.com/id/ANOTHER_LONG_ID"
                    },
                ]
            },
        ] -> (known after apply)
        name                      = "eks-devtest"
      ~ platform_version          = "eks.4" -> (known after apply)
        role_arn                  =
"arn:aws:iam::AWS_ACCOUNT:role/eks-devtest20190521091115568800000001"
      ~ status                    = "ACTIVE" -> (known after apply)
        version                   = "1.13"

        timeouts {
            create = "15m"
            delete = "15m"
        }


It also looks like we are being forced to use a new AMI

image_id                         = "ami-0199284372364b02a" ->
"ami-00ea6211202297fe8" # forces replacement

Any help as to how to get around this would be really helpful

**Comment by jmukhtar** [comment]
Thanks for your tip @barryib it was the subnet that was causing the cluster recreation. 

On a side note, it might be a good idea to know how to remove a subnet from a running EKS cluster via terraform

**Comment by dpiddockcmp** [comment]
You cannot currently change the security groups or subnets associated with a cluster. This is an AWS limitation. 

From the [API docs](https://docs.aws.amazon.com/eks/latest/APIReference/API_UpdateClusterConfig.html):
> **Important**
> At this time, you can not update the subnets or security group IDs for an existing cluster.

**Comment by bry5an** [comment]
> It also looks like we are being forced to use a new AMI
> 
> image_id = "ami-0199284372364b02a" ->
> "ami-00ea6211202297fe8" # forces replacement

I'm having the same issue with the force replacement. I just manually set the created `image_id` to avoid the change. Ideally some sort of lifecycle ignore_changes setup would be ideal

`   worker_groups = [
    {
      name                          = "${var.node_group_1}"
      instance_type                 = "${var.node_group_1_instance_type}"
      additional_userdata           = "echo foo bar"
      asg_desired_capacity          = 2
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_one.id]
      ami_id = "ami-07be7092831897fd6"
    },
  ]`

**Comment by dpiddockcmp** [comment]
Are you able to provide your full module definition and the diff output?

The AMI will get updated occasionally. This should only cause the launch configuration or template to be recreated and the ASG to be updated. It shouldn't be triggering an eks_cluster replacement.
