### ISSUE TITLE
How to specify subnet in worker groups

### ISSUE THREAD

**Issue by kahootali** [terraform-aws-modules/terraform-aws-eks#521]
I want to run EKS with 3 nodes on private subnet and 2 nodes on public subnet with different labels on each worker group. How can I do that? 

Currently I think, there is only a way to specify subnet for EKS, not at worker group, but I want to specify at worker group.

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request
* [x] kudos, thank you, warm fuzzy

## Environment details

* Affected module version: 5.1.0
* Terraform version: 0.12.7

**Comment by dpiddockcmp** [comment]
You can customize the subnet for your worker groups and pass extra options to kubelet via the `worker_groups` list map.

Something like:

```HCL
module "eks" {
  # ...
  worker_groups = [
    {
      name    = "private"
      subnets = var.private_subnets
      kubelet_extra_args = "--node-labels=subnet=private"
    },
    {
      name    = "public"
      subnets = var.public_subnets
      kubelet_extra_args = "--node-labels=subnet=public"
    }
  ]
}
```

**Comment by barryib** [comment]
For information, everything you can define per worker group is here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf#L23-L75.

Closing this. Feel free to re-open it if the proposed solution doesn't work for you.
