### ISSUE TITLE
worker nodes are not adding to EKS cluster

### ISSUE THREAD

**Issue by saravana-code** [terraform-aws-modules/terraform-aws-eks#534]
# I have issues

## I'm submitting a...

* [ *] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
 kubectl get nodes
No resources found.

# kubectl get all --all-namespaces
NAMESPACE     NAME                           READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-754cb4f968-7lkxs   0/1     Pending   0          24m
kube-system   pod/coredns-754cb4f968-qhhz2   0/1     Pending   0          24m

NAMESPACE     NAME                 TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
default       service/kubernetes   ClusterIP   172.20.0.1    <none>        443/TCP         24m
kube-system   service/kube-dns     ClusterIP   172.20.0.10   <none>        53/UDP,53/TCP   24m

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/aws-node     0         0         0       0            0           <none>          24m
kube-system   daemonset.apps/kube-proxy   0         0         0       0            0           <none>          24m

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   0/2     2            0           24m

NAMESPACE     NAME                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-754cb4f968   2         2         0       24m

## What's the expected behavior?

nodes need to add to cluster

## Environment details

* Affected module version: tried in 3.0.0 , 4.0.0
* OS:  amazon-eks-node-1.14-v20190906 (ami-0f841722be384ed96)
 us-east-2
* Terraform version:
Terraform v0.11.7

(have tried in another versions as well)

**Comment by max-rocket-internet** [comment]
> support request - read the FAQ first! 

👀

**Comment by saravanakumarangamuthu** [comment]
I have read it max and tried them as well, but same issue with different versions as well

**Comment by saravanakumarangamuthu** [comment]
can someone give me some more info about this sentences in docs : 

"Your nodes need to be able to contact the EKS cluster endpoint. By default the module only creates a public endpoint. You should also enable the private endpoint by setting cluster_endpoint_private_access = true on this module.
If you have the private endpoint enabled ensure that you also have VPC DNS enabled. Set enable_dns_hostnames = true on your aws_vpc resource or the terraform-aws-module/vpc/aws community module. "

"enable_dns_hostnames = true " where should I pass this info, is it on https://github.com/terraform-aws-modules/terraform-aws-vpc if yes, how can I do it for a VPC which is created manually via AWS console? is there a way I can define it on the "eks" module?

module "eks" {
  source        = "terraform-aws-modules/eks/aws"
  version       = "3.0.0"
  cluster_name  = "${local.cluster_name}"
  subnets       = "${var.subnets}"
  tags          = "${local.tags}"
  vpc_id        = "${var.vpc_id}"
  worker_groups = "${local.worker_groups}"
  cluster_endpoint_private_access = "true"
}

**Comment by dpiddockcmp** [comment]
You need to have DNS hostnames enabled on the VPC. See the official docs [here](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-updating) for more.

I'll add a PR to expand and clarify that section of the FAQ

**Comment by rampatnaik** [comment]
Yes we have both enabled.

**Comment by dpiddockcmp** [comment]
Please include:
- terraform source of how you are using this module
- output of `kubectl -n kube-system get configmap aws-auth`

I believe you are not using terraform to manage the VPC?
How are your worker node subnets configured?

**Comment by rampatnaik** [comment]
we are using VPC , IAM, SG, Subnet creation from terraform

**Comment by tthayer** [comment]
I ran into this issue. When building the cluster it throws errors near the end of the process stating that it can't find the aws-auth config file to import from. The terraform apply completes successfully but nodes do not communicate with the master. I found a copy of the config-map-aws-auth_CLUSTERNAME.yaml file in my terragrunt cache and applied it with `kubectl apply -f /long/path/config-map-aws-auth_CLUSTERNAME.yaml` and immediately after that the nodes started communicating.

**Comment by oesah** [comment]
I think I know the problem: We need to have the aws-auth configmap in the cluster, so you can just apply the file generated by the terraform script and apply it to your cluster, as @tthayer suggested. I did not need to go through the cache though, the file is generated locally (or in the pipeline container), so all I do is apply it after `terraform apply`.

**Comment by shanmugakarna** [comment]
Please review https://github.com/terraform-aws-modules/terraform-aws-eks/pull/606

**Comment by max-rocket-internet** [comment]
> Please review #606

Unrelated. Your PR is related to a change that was merged much later than this issue was created.

**Comment by t5unamie** [comment]
@max-rocket-internet 

I have the same problem with version

Terraform version:
Terraform v0.12.16

of terraform.

I know it's not a network issue cause I added a ssh key to the ASG and can csee the cloudinit command running with no errors. Yet it does not register with the Cluster. I ahve also done tests from the node to the end point.

I have public and private subnets. a property NAT gateway setup and the private nodes can reach the endpoint which is public accessible only. DNS hostname are turned on.

I have tried using v7.0.0 and v6.0.2 versions of the module. Both give me the same error. The worker nodes don't become available to the cluster and when trying to start a pod. It complain no nodes available for scheduling.

**Comment by max-rocket-internet** [comment]
No update from OP in a couple of months so I will close this.

To others in this thread, please check FAQ here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#why-are-nodes-not-being-registered

If you still have issues then please test with master as there's been major changes in the way `aws-auth` configmap is handled. Then feel free to open another issue 🙂

I will make a new release this week.

**Comment by dvdantunes** [comment]
> I think I know the problem: We need to have the aws-auth configmap in the cluster, so you can just apply the file generated by the terraform script and apply it to your cluster, as @tthayer suggested. I did not need to go through the cache though, the file is generated locally (or in the pipeline container), so all I do is apply it after `terraform apply`.

I was following the [Learn Terraform - Provision an EKS Cluster (AWS)](https://learn.hashicorp.com/terraform/kubernetes/provision-eks-cluster) quick start and had a similar issue. In my case I needed to execute `terraform apply` a second time. Only in the second time some configurations were updated and the `aws-auth` was created, allowing the nodes to be registered
