### ISSUE TITLE
Error parsing aws_auth_configmap.yaml to JSON

### ISSUE THREAD

**Issue by polaaditya** [terraform-aws-modules/terraform-aws-eks#535]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
terraform apply has failed to create the resource

## If this is a bug, how to reproduce? Please include a code sample if relevant.
its from the examples/basic directory used to create EKS cluster

## What's the expected behavior?
aws_auth_configmap.yaml which is created should be used to apply configuration using kubectl apply the configMap, am not sure why it is being converted to JSON

## Are you able to fix this problem and submit a PR? Link here if you have already.
No

## Environment details

* Affected module version: Latest
* OS: MacOS X (10.14.6 )
* Terraform version: v0.12.9

**Comment by polaaditya** [comment]
` YAML to JSON: yaml: line 10: could not find expected ':'
module.eks.null_resource.update_config_map_aws_auth[0]: Still creating... [2m30s elapsed]
module.eks.null_resource.update_config_map_aws_auth[0]: Creation complete after 2m38s [id=6915556055388464062]

Error: Provider produced inconsistent final plan

When expanding the plan for module.eks.aws_autoscaling_group.workers[1] to
include new values learned so far during apply, provider "aws" produced an
invalid new value for .initial_lifecycle_hook: planned set element
cty.ObjectVal(map[string]cty.Value{"default_result":cty.UnknownVal(cty.String),
"heartbeat_timeout":cty.UnknownVal(cty.Number),
"lifecycle_transition":cty.UnknownVal(cty.String),
"name":cty.UnknownVal(cty.String),
"notification_metadata":cty.UnknownVal(cty.String),
"notification_target_arn":cty.UnknownVal(cty.String),
"role_arn":cty.UnknownVal(cty.String)}) does not correlate with any element in
actual.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
`

**Comment by barryib** [comment]
closing duplicates #527
