### ISSUE TITLE
v6.0.1 with Terraform 0.11.3. Unable to init

### ISSUE THREAD

**Issue by nodesocket** [terraform-aws-modules/terraform-aws-eks#543]
Hello,

I want to use version `v6.0.1` of this module as I need GPU support and the ability to specify the AMI. However, I am stuck running Terraform version `0.11.13`. Is there a way to use `v6.0.1` with my pinned version of Terraform?

Currently when I run `terraform init` I am getting:

```
Error downloading modules: Error loading modules: module k8s: Error parsing .terraform/modules/f78b420f851c1a6d52f563f537a4ebba/terraform-aws-modules-terraform-aws-eks-07c61b6/aws_auth.tf: At 2:14: Unknown token: 2:14 IDENT var.write_aws_auth_config
```

**Comment by barryib** [comment]
The v6.0.1 is not compatible with Terraform 0.11.x. More info in he FAQ https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#aws_authtf-at-214-unknown-token-214-ident

Closing this. Feel free to open it if needed.

**Comment by max-rocket-internet** [comment]
Version `4.0.2` was the last one that was for TF `0.11`. You can set the AMI with this version:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v4.0.2/workers.tf#L43

Or, there's a branch you can try but it's not really maintained, it just has some fixes back ported: https://github.com/terraform-aws-modules/terraform-aws-eks/tree/tf0.11
