### ISSUE TITLE
worker_groups_launch_template_mixed has not updated in README

### ISSUE THREAD

**Issue by random1st** [terraform-aws-modules/terraform-aws-eks#546]
# I have issues
Create spot configuration as described.
An argument named "worker_groups_launch_template_mixed" is not expected here.
## I'm submitting a...

* [ ] bug report

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by max-rocket-internet** [comment]
Hey @random1st, the examples were just updated in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/545

Have a look and see if it's now clear 🙂
