### ISSUE TITLE
Use Kubernetes provider

### ISSUE THREAD

**Issue by gdurandvadas** [terraform-aws-modules/terraform-aws-eks#547]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Currently the whole solution is tied to a local terraform run, meaning, it not possible to use this module in Terraform Cloud.

## What's the expected behavior?

By using Kubernetes provider it could be run anywhere without dependencies.

Example:
```hcl
module "kubernetes" {
  source       = "../.."
  cluster_name = local.cluster_name
  subnets      = module.vpc.private_subnets
  vpc_id = module.vpc.vpc_id

  worker_groups = [
    {
      name                          = "worker-group-1"
      instance_type                 = "t2.small"
      additional_userdata           = "echo foo bar"
      asg_desired_capacity          = 2
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_one.id]
    },
  ]
}

data "aws_eks_cluster_auth" "this" {
  depends_on  = [module.kubernetes]
  name        = local.cluster_name
}

# Wait for EKS Endpoint to be available
resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep 60"
  }
}

provider "kubernetes" {
  version                = "~> v1.9.0"
  host                   = module.kubernetes.cluster_endpoint
  cluster_ca_certificate = "${base64decode(module.kubernetes.cluster_certificate_authority_data)}"
  #token                  = data.aws_eks_cluster_auth.this.token
  load_config_file       = false
  # Token workaround
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    args        = ["token", "-i", "${local.cluster_name}"]
    command     = "aws-iam-authenticator"
  }
}

resource "kubernetes_config_map" "aws-auth" {
  metadata {
    name = "aws-auth"
    namespace = "kube-system"
  }

  data = {
    mapRoles = <<ROLES
- rolearn: ${module.kubernetes.worker_iam_role_arn}
  username: system:node:{{EC2PrivateDNSName}}
  groups:
    - system:bootstrappers
    - system:nodes
- rolearn: "arn:aws:iam::${data.aws_caller_identity.this.account_id}:role/OrganizationAccountAccessRole"
  username: admin
  groups:
    - system:masters
ROLES
    mapUsers = <<USERS
- userarn: ${data.aws_caller_identity.this.arn}
  username: terraform
  groups:
    - system:masters
USERS
  }
}
```

Regarding the usage of the `aws_eks_cluster_auth`, there are some inconsistency regarding the token, I've open a issue in the `terraform-aws-provider`
https://github.com/terraform-providers/terraform-provider-aws/issues/10362

## Environment details

* Affected module version: v6.0.1
* OS: MacOS 10.14.6
* Terraform version: v0.12.9

**Comment by dpiddockcmp** [comment]
Hi. This is being discussed in a PR: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/355

**Comment by barryib** [comment]
#355 is now merged, but there is still an issue with the EKS endpoint discussed in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/621 and with a possible fix  https://github.com/terraform-aws-modules/terraform-aws-eks/pull/639

**Comment by barryib** [comment]
Closing this. We're now using kubernetes provider.
