### ISSUE TITLE
Amazon EKS Cluster Tagging

### ISSUE THREAD

**Issue by morganchristiansson** [terraform-aws-modules/terraform-aws-eks#548]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

We're not yet using the recently added EKS cluster tagging support. https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-eks-supports-cluster-tagging/

## Are you able to fix this problem and submit a PR? Link here if you have already.

Support for eks cluster tagging was just merged in the provider https://github.com/terraform-providers/terraform-provider-aws/pull/10307. Once released we can support it.

PR will look something like this: https://github.com/terraform-aws-modules/terraform-aws-eks/compare/master...morganchristiansson:tags

**Comment by morganchristiansson** [comment]
terraform-provider-aws v2.31.0 has been released

> resource/aws_eks_cluster: Add tags argument (#10307)

https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v2.31.0

**Comment by max-rocket-internet** [comment]
Cool. PR welcome 😃

**Comment by morganchristiansson** [comment]
PR #550 submitted
