### ISSUE TITLE
How to use cluster Autoscaling policy when using something like kube2iam

### ISSUE THREAD

**Issue by kkapoor1987** [terraform-aws-modules/terraform-aws-eks#552]
# I have issues
Not able to use Cluster Autoscaling policy attached to worker nodes when using Kube2iam. 

## I'm submitting a...

* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Currently, if I enable autoscaling we can see worker nodes gets CA IAM policies attached to worker nodes. In presence of Kube2iam documentation is not clear how to use this policy. 
Thus we have to write our own CA policy and then use it in presence of kube2iam 

## What's the expected behavior?
Module should have CA policy arn as an output which can be then used by folks using the module.

## Environment details

* Affected module version: v5.0.0
* OS:
* Terraform version:v 0.12.4

**Comment by kkapoor1987** [comment]
@max-rocket-internet  Would great if you can provide some guidance on this

**Comment by max-rocket-internet** [comment]
I don't really get what you are wanting? If you are using Kube2iam then write your own policy and let the cluster-autoscaler use it?

**Comment by kkapoor1987** [comment]
@max-rocket-internet That was exactly my question. Is there any way I can use the CA IAM policy already created by the module in presence of kube2iam

**Comment by max-rocket-internet** [comment]
I don't know sorry, I've never used kube2iam. Can you just copy the ARN of the policy and use it in the `iam.amazonaws.com/role` annotation?

**Comment by dpiddockcmp** [comment]
Need to create a role associated with the policy.

Since 6.0.2 the module has `worker_autoscaling_policy_arn` and `workder_autoscaling_policy_name` outputs for easy TF access to the created policy.

Example (untested, for my sins):
```hcl
module "eks" {
  version = "~> 6.0"
  # ....
}

data "aws_iam_policy_document" "assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "AWS"
      identifiers = [module.eks.worker_iam_role_arn]
    } 
  } 
} 

resource "aws_iam_role" "autoscaling" {
  name               = "my-cluster-autoscaling"
  assume_role_policy = data.aws_iam_policy_document.assume.json
} 

resource "aws_iam_role_policy_attachment" "autoscaling" {
  role       = aws_iam_role.autoscaling.name
  policy_arn = module.eks.worker_autoscaling_policy_arn
}
```

Then add an annotation to the autoscaler Deployment: `iam.amazonaws.com/role: my-cluster-autoscaling`

**Comment by kkapoor1987** [comment]
@dpiddockcmp Yea this makes sense. I want to do something like this but I waiting to upgrade to v6 due bug related to  "inconsistent plan due ASG lifecycle hooks"

**Comment by kkapoor1987** [comment]
@dpiddockcmp I was hoping to do same with v5 but seems like that is not possible.
