### ISSUE TITLE
Cloudwatch log group - is it possible for the aws_cloudwatch_log_group resource to update existing log groups which are created by lambda without destroying them ?

### ISSUE THREAD

**Issue by ameynawar** [terraform-aws-modules/terraform-aws-eks#557]
# I have issues

while updating retention policy for the existing Cloudwatch log groups. I have some log groups which are created by lambda's . So i wanted to the change the retention policy for the those log groups . I tried to to redeploy those lambda with attached log groups who have same name as previous and added the retention policy to it . But it failed so I used terraform import to import existing log groups and add retention policy. It worked but it destroyed current log groups and created it again with updated log retention policy. So i want to know is there is any workaround this situation ? 

## I'm submitting a...

* * [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
After importing the existing log group if you update those log group it destroy them and recreated with update .

## If this is a bug, how to reproduce? Please include a code sample if relevant.
terraform import aws_cloudwatch_log_group.example_log_group /aws/lambda/existing_log_group_name

resource "aws_cloudwatch_log_group" "example_log_group" {
  name              = "/aws/lambda/existing_log_group_name"
 #change in existing log groups retention_policy 
retention_in_days = 90
}

## What's the expected behavior?
It should update the existing log groups without destroying them .Just update the policy to them.

## Environment details

* Affected module version:
* OS:osX
* Terraform version:Terraform v0.11.2

**Comment by max-rocket-internet** [comment]
Not sure what you are asking here or what this module has to do with any log groups for AWS Lambda?

**Comment by ameynawar** [comment]
@max-rocket-internet I was asked to modify a retention policy of a cloudwatch log group that is not managed by the terraform. So tried to update the cloudwatch log group using terraform with the same name as the existing but it failed so I raised this question.  If this is wrong forum to ask this question then please guide me to right forum to address this issue. Thank you.

**Comment by barryib** [comment]
If you want to manage something created outside of Terraform with Terraform, you have to import it first.

But if you want to continue to manage the cloudwatch log group outside of Terraform, maybe we can a variable like (cluster_manage_cloudwatch) here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/cluster.tf#L2 to enable or disable cloudwath log group creation.

**Comment by ameynawar** [comment]
@barryib  I tried importing but it was recreating a cloudwatch log group. so  I didn't follow that path. plus I don't have permission to do such actions in the prod environment.

**Comment by ameynawar** [comment]
No. I am not deploying eks cluster . Can you provide me a link to aws provider or lambda module repository module ??

**Comment by barryib** [comment]
@ameynawar I don't even know what you're using or trying to do. Maybe Google will have more answers ?

Closing this. Feel free to re-open it if you start using this module to deploy an EKS cluster.
