### ISSUE TITLE
Global Disable Module Switch

### ISSUE THREAD

**Issue by maganuk** [terraform-aws-modules/terraform-aws-eks#558]
Can we add a Global switch to disable or enable the module entirely?

**Comment by TBeijen** [comment]
This would greatly help tfvars based setups where not all accounts need all the clusters. Putting all  the clusters in separate projects is not always possible because of also needing to manage VPC and subnets tags.

Is this considered desirable? If so, I don't mind starting on it.

**Comment by maganuk** [comment]
This is exactly what I need it for!

**Comment by dpiddockcmp** [comment]
This is already being worked on in #580 . And there's a duplicate solution in #588

**Comment by barryib** [comment]
Since #580 is merged, i'm closing this.
