### ISSUE TITLE
Cluster-autoscaling doesn't have autoscaling permissions because of tags 

### ISSUE THREAD

**Issue by rvoitenko** [terraform-aws-modules/terraform-aws-eks#559]
# I have issues
I want to enable worker node autoscaling, so I set "autoscaling_enabled  = true" for worker group and installed cluster-autoscaler chart.
But it complains that it doesn't have permissions to do "autoscaling:SetDesiredCapacity".
After investigation I found that workers ec2 IAM role include policy generated by terraform-aws-eks with name eks-worker-autoscaling-*.  The policy has the following condition(https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L407):

```

            "Condition": {
                "StringEquals": {
                    "autoscaling:ResourceTag/k8s.io/cluster-autoscaler/enabled": "true",
                    "autoscaling:ResourceTag/kubernetes.io/cluster/<cluster_name>": "owned"
                } 
```
I have found that workers instances has tag " kubernetes.io/cluster/<cluster_name>: owned" but not "k8s.io/cluster-autoscaler/enabled". Than I've checked autoscaling group and found that this tag is not propagated from ASG to EC2 instances:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers_launch_template.tf#L189
That's why EC2 workers doesn't have permissions to run "autoscaling:SetDesiredCapacity".

So my question is any reason why "cluster-autoscaler/enabled" not propagated to EC2 instances ?

## I'm submitting a...

* [* ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Cluster-autoscaler doesn't have enough permission with default setup if you follow https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/autoscaling.md 

## What's the expected behavior?
Workers have enough permissions to do autoscaling when "autoscaling_enabled   = true"

## Are you able to fix this problem and submit a PR? Link here if you have already.
I can create PR to fix this after I get answers to my questions, maybe I setup it wrong way.
As temporary workaround I have added additional worker policy "arn:aws:iam::aws:policy/AutoScalingFullAccess", which is not perfect from security point.

## Environment details

* Affected module version: 6.0.2
* OS: macOS
* Terraform version:
```
Terraform v0.12.10
+ provider.aws v2.32.0
+ provider.helm v0.10.2
+ provider.http v1.1.1
+ provider.kubernetes v1.9.0
```

**Comment by max-rocket-internet** [comment]
> I have found that workers instances has tag " kubernetes.io/cluster/<cluster_name>: owned" but not "k8s.io/cluster-autoscaler/enabled"

It's not a tag on the instance, it's on the ASG: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L107-L115

**Comment by max-rocket-internet** [comment]
I mean the condition in the policy for a tag on the ASG, not on the instance

**Comment by rvoitenko** [comment]
> I mean the condition in the policy for a tag on the ASG, not on the instance

yes, exactly, but I think this tag should be propagated to instances on lunch, right ?

**Comment by max-rocket-internet** [comment]
The policy is about the ASG. Nothing to do with the instances.

https://docs.aws.amazon.com/autoscaling/ec2/userguide/control-access-using-iam.html#policy-auto-scaling-condition-keys

https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonec2autoscaling.html#amazonec2autoscaling-policy-keys

> autoscaling:ResourceTag/${TagKey} | The value of a tag attached to a resource.

The instance is not the resource, it's the ASG.

**Comment by rvoitenko** [comment]
yes,  I understand this.
But when cluster-autoscaler trying to do scale action it's assume EC2 worker instance profile, it's not working on behalf of ASG. 
And AWS deny this autoscale action coming from EC2, because it doesn't have tag cluster-autoscaler/enabled=true

**Comment by max-rocket-internet** [comment]
> And AWS deny this autoscale action coming from EC2, because it doesn't have tag cluster-autoscaler/enabled=true

This is not my understanding of how it works 🙂

**Comment by rvoitenko** [comment]
> > And AWS deny this autoscale action coming from EC2, because it doesn't have tag cluster-autoscaler/enabled=true
> 
> This is not my understanding of how it works 🙂

can you explain than how it works ?
I can provide of logs of cluster-autoscaler as proof. It doesn't work if you don't have   
workers_additional_policies   = ["arn:aws:iam::aws:policy/AutoScalingFullAccess"]

**Comment by max-rocket-internet** [comment]
> I can provide of logs of cluster-autoscaler as proof.

That's not going to help.

> can you explain than how it works ?

I think it's like this:

1. The cluster-autoscaler starts in a pod and wants to auth to an AWS API
2. It assumes the role of the instance profile as allowed in the `workers_assume_role_policy`
3. This role has a policy attached, `worker_autoscaling`, that allows `autoscaling:SetDesiredCapacity` (one example) on all resources that have those 2 tags and values set.

I could be wrong though.
