### ISSUE TITLE
Reduce duplication by merging worker_groups and worker_groups_launch_template?

### ISSUE THREAD

**Issue by max-rocket-internet** [terraform-aws-modules/terraform-aws-eks#563]
Would be great now that we've been on TF 0.12 for a while now.

We could just add a `type` option to the worker group map to set whether it's LT or LC based?
And then remove `workers_launch_template.tf` completely?

**Comment by barryib** [comment]
When I started using this module (in Terraform 0.12), this was my first thought :)

I think this will be done with for_each support and will probably solve https://github.com/terraform-aws-modules/terraform-aws-eks/issues/476

**Comment by ArchiFleKs** [comment]
I did a little testing:

with for example this structure:

```
  worker_groups = [
    {
      type = "LC"
      instance_type = "m4.large"
      asg_max_size  = 5
      tags = [{
        key                 = "foo"
        value               = "bar"
        propagate_at_launch = true
      }
    },
    {
      type = "LT"
      instance_type = "m4.large"
      asg_max_size  = 5
      tags = [{
        key                 = "foo"
        value               = "bar"
        propagate_at_launch = true
      },
      {
      type = "LT"
      instance_type = "m4.large"
      asg_max_size  = 5
      tags = [{
        key                 = "foo"
        value               = "bar"
        propagate_at_launch = true
      }
   ]
```

Doing this `lookup({for r in var.worker_groups: r.type => r...}, "LT")`

returns:

```
[
    {
      type = "LT"
      instance_type = "m4.large"
      asg_max_size  = 5
      tags = [{
        key                 = "foo"
        value               = "bar"
        propagate_at_launch = true
      },
      {
      type = "LT"
      instance_type = "m4.large"
      asg_max_size  = 5
      tags = [{
        key                 = "foo"
        value               = "bar"
        propagate_at_launch = true
      }
   ]
```

**Comment by js-timbirkett** [comment]
@barryib @max-rocket-internet - I've been considering moving workers / workers_launch_templates to a sub-module like node_groups.

A question I have is: What is the benefit of supporting both Launch Config and Launch Template type worker groups? Can we do everything with Launch templates or are there limitations?

I also think that we could support usage of the node / worker group submodules directly, this would solve the issues that people face when trying to do something after the EKS control plane has been created but before the nodes or workers have been created. Specifically custom CNI configuration.
