### ISSUE TITLE
Allow completely replacing userdata

### ISSUE THREAD

**Issue by snstanton** [terraform-aws-modules/terraform-aws-eks#564]
I have a custom worker AMI that has different requirements for the userdata block.  The standard template does not work for me, so I'd like the ability to supply my own template instead of the default.

**Comment by max-rocket-internet** [comment]
Great idea

**Comment by barryib** [comment]
Closing this because https://github.com/terraform-aws-modules/terraform-aws-eks/pull/565 is now merged.
