### ISSUE TITLE
Instances names are the same when use only one worker_groups

### ISSUE THREAD

**Issue by firemanxbr** [terraform-aws-modules/terraform-aws-eks#566]
## Issue

**For example:**
```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "6.0.2"
  cluster_name    = local.cluster_name
  cluster_version = "1.14"
  subnets         = "${var.subnets}"

  tags = {
    environment = local.environment
  }

  vpc_id = "${var.vpc_id}"

  worker_groups = [
    {
      instance_type         = "m4.large"
      asg_desired_capacity  = 3
      asg_max_size          = 5
    }
  ]
}
```

In this case, the code will create 3 instances(EKS Worker Nodes) with the same name, e.g: "_cluster-0-eks_asg_". If I add the variable "_name_" inside of the code block of "_worker_groups_" it will replace the name to keep the same name to all instances desired in the variable "asg_desired_capacity". 

## Type
I'm submitting it as a:
* [X] bug report

## What's the expected behavior?
It will be nice if the "_worker_groups_" get the variable "_name_" and use the "_random_id_" to increment the instance name defined as "Name" "Tag". 

**Suggestion Pattern:** [cluster-name]-[random_id]-eks_asg
**Reference:** https://www.terraform.io/docs/providers/random/r/id.html

* Terraform version:

## Terraform and Module versions:
**Terraform:** 0.12.10
**EKS Module:** 6.0.2

**Comment by max-rocket-internet** [comment]
I don't think this is possible. Any instances that are created from an ASG get the same tags, including the `Name` tag. It's not a terraform issue, it's how ASGs work. Or am I wrong?

**Comment by dpiddockcmp** [comment]
You're right, Max. Tags are applied by the ASG and are the same for all instances in that ASG. This is how AWS works.

`Name` tag is just conventional sugar for the AWS console.

**Comment by hgranillo** [comment]
@firemanxbr You can add a `pre_userdata` script to edit/create the `Name` tag. For example.

```
PLACEMENT=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | awk '{ print substr($1, 1, length($1)-1) }'`
aws configure set default.region $PLACEMENT
aws configure set default.output text
INSTANCE_ID=`/opt/aws/bin/ec2-metadata -i | awk '{ print $2 }'`
IP_ADDRESS=`/opt/aws/bin/ec2-metadata -o | awk '{ print $2 }'`
DOMAIN=`grep search /etc/resolv.conf | awk '{ print $2 }'`
HOSTNAME=`/opt/aws/bin/ec2-metadata -h | awk '{ print $2 }'`
hostname $HOSTNAME
sed -i "s/HOSTNAME=localhost.localdomain/HOSTNAME=$HOSTNAME/g" /etc/sysconfig/network
echo "$IP_ADDRESS $HOSTNAME" >> /etc/hosts
aws ec2 create-tags --resources $INSTANCE_ID --tags Key="Name",Value="$HOSTNAME"
```

For this to work you need to add `ec2:Describe*` and `ec2:CreateTags` to the instance IAM Role.
