### ISSUE TITLE
DNS resolution failure on new cluster under certain VPC conditions.

### ISSUE THREAD

**Issue by mattronix** [terraform-aws-modules/terraform-aws-eks#567]
# I have issues

## I'm submitting a...

* [X ] bug report

## What is the current behavior?

Currently when deploy an EKS cluster with this module and set the vpc attribute DNS hostnames = enabled before deploying the cluster all DNS resolution fails.

When i set the vpc attrubute DNS hostnames = enabled after deploying the cluster with this module hostnames are able to resolve just fine. 

In both cases above i have DNS resolution = enabled
## If this is a bug, how to reproduce? Please include a code sample if relevant.

Create a VPC with:
1.  DNS hostnames = enabled and DNS resolution= enabled 
2. deploy eks cluster with the module. 
3.  kubectl apply -f https://k8s.io/examples/admin/dns/busybox.yaml   # deploy busy box
4. kubectl exec -ti busybox -- nslookup kubernetes.default 

### Expected Output (Working):

**Resolving host EC2**
> nslookup ip-10-0-2-72.eu-central-1.compute.internal
Server:    10.0.2.72
Address 1: 10.0.2.72

**Resolving cluster dns name**
/ # nslookup kubernetes.default
Server:    172.20.0.10
Address 1: 172.20.0.10 kube-dns.kube-system.svc.cluster.local

### Expected output (Not Working):

**Resolving host EC2**
/ # nslookup ip-10-0-2-180.eu-central-1.compute.internal
Server:    172.20.0.10
Address 1: 172.20.0.10

**Resolving cluster dns name**

/ # nslookup kubernetes.default
Server:    172.20.0.10
Address 1: 172.20.0.10

nslookup: can't resolve 'kubernetes.default'

## Environment details

* Affected module version: Commit: 4369f02
* OS: Standard OS from module
* Terraform version: Terraform v0.12.7

## Any other relevant info

Code base is public and found here: https://git.uptic.nl/uptic-public-projects/eks-demo-hpa

**Comment by max-rocket-internet** [comment]
The examples provided in [here](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples) work but they use the common VPC module to manage all the VPC related resources. Can you try an example and work out the difference to your env?

**Comment by mattronix** [comment]
thanks will investigate
