### ISSUE TITLE
Terraform destroy fails when state is empty

### ISSUE THREAD

**Issue by miguelaferreira** [terraform-aws-modules/terraform-aws-eks#568]
# I have issues

Terraform destroy fails when state is empty.

I've seen other issues that refer to similar problems, like #513 and #402. But those issues are not related to the same error I'm seeing.

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?

When `terraform destroy` is called on an empty state, terraform errors with `Error: Invalid index`.
The expressions that trigger this behaviour are things like:
```hcl
cluster_security_group_id = var.cluster_create_security_group ? aws_security_group.cluster[0].id : var.cluster_security_group_id
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```bash
$ cd examples/basic
$ terraform init
Initializing modules...
...
$ terraform destroy
module.eks.data.aws_region.current: Refreshing state...
data.aws_availability_zones.available: Refreshing state...
module.eks.data.aws_caller_identity.current: Refreshing state...
module.eks.data.aws_iam_policy_document.cluster_assume_role_policy: Refreshing state...
module.eks.data.aws_iam_policy_document.workers_assume_role_policy: Refreshing state...
module.eks.data.aws_ami.eks_worker: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes


Error: Invalid index

  on ../../local.tf line 11, in locals:
  11:   cluster_security_group_id = var.cluster_create_security_group ? aws_security_group.cluster[0].id : var.cluster_security_group_id
    |----------------
    | aws_security_group.cluster is empty tuple

The given key does not identify an element in this collection value.

```

## What's the expected behavior?

```
$ terraform destroy
Destroy complete! Resources: 0 destroyed.
```

## Are you able to fix this problem and submit a PR? Link here if you have already.

PR #569

## Environment details

* Affected module version: current `master` 
* OS: Mac OSX
* Terraform version: v0.12.12

## Any other relevant info

The reason why it is important for me to have the destroy command work well on an empty state is that I'm using this module in a project that uses terragrunt to "glue together" a tree of modules. When destroying, terragrunt will want to call `terraform destroy` on all the modules it knows about. Turns out that when an attempt to destroy the entire tree of modules does not completely finish, subsequent attempts will try and destroy modules that have already been destroyed and, therefore, have empty states. At that point this issue surfaces.

**Comment by max-rocket-internet** [comment]
It would be cool if this could be solved in TF itself. Is there a github issue already existing?

**Comment by vrathore18** [comment]
We are still facing the issue. when we can expect a new release with the fix?

**Comment by jross-ai** [comment]
Any update on a solution here?

**Comment by miguelaferreira** [comment]
@jross-ai are you still experiencing the same issue with `v7.0.0` or above?
PR #569 should have addressed it.

**Comment by tkent** [comment]
@miguelaferreira 

This is still happening in `v12.1.0` and the master branch because some other local values (presumably added after your fixes) directly reference element tuples by their index.

Specifically `endpoint`, `cluster_auth_base64` , and `aws_authenticator_command_args`.

See https://github.com/terraform-aws-modules/terraform-aws-eks/blob/f2c4383719354c5bfcb4f15d34555e6b1cc5406d/local.tf#L141

Here's what the error output looks like.

```
Error: Invalid index

  on .terraform/modules/eks/terraform-aws-eks-12.1.0/local.tf line 143, in locals:
 143:     endpoint                          = aws_eks_cluster.this[0].endpoint
    |----------------
    | aws_eks_cluster.this is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/eks/terraform-aws-eks-12.1.0/local.tf line 144, in locals:
 144:     cluster_auth_base64               = aws_eks_cluster.this[0].certificate_authority[0].data
    |----------------
    | aws_eks_cluster.this is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/eks/terraform-aws-eks-12.1.0/local.tf line 146, in locals:
 146:     aws_authenticator_command_args    = length(var.kubeconfig_aws_authenticator_command_args) > 0 ? var.kubeconfig_aws_authenticator_command_args : ["token", "-i", aws_eks_cluster.this[0].name]
    |----------------
    | aws_eks_cluster.this is empty tuple

The given key does not identify an element in this collection value.
```

If I end up with free time, I'll send in a PR to fix it.  I assume it will just require a better test condition on the `local.kubeconfig`, but it may require more than that.

**Comment by thpang** [comment]
Also having the same issue.

**Comment by canthony** [comment]
Same issue on 12.1.0

```
Error: Invalid index

  on .terraform/modules/eks/terraform-aws-eks-12.1.0/local.tf line 143, in locals:
 143:     endpoint                          = aws_eks_cluster.this[0].endpoint
    |----------------
    | aws_eks_cluster.this is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/eks/terraform-aws-eks-12.1.0/local.tf line 144, in locals:
 144:     cluster_auth_base64               = aws_eks_cluster.this[0].certificate_authority[0].data
    |----------------
    | aws_eks_cluster.this is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/eks/terraform-aws-eks-12.1.0/local.tf line 146, in locals:
 146:     aws_authenticator_command_args    = length(var.kubeconfig_aws_authenticator_command_args) > 0 ? var.kubeconfig_aws_authenticator_command_args : ["token", "-i", aws_eks_cluster.this[0].name]
    |----------------
    | aws_eks_cluster.this is empty tuple

The given key does not identify an element in this collection value.
```

**Comment by thpang** [comment]
My team has found that if there are items that affect the infrastructure that terraform is not aware of, i.e. one stands up their kubernetes infrastructure with terraform and then deploys content into that infrastructure with ansible, timeouts can occur. Once those times happen, the tfstate file is not happy and now has trouble with outputs/locals/etc that have collection or tuple information they should be referencing. Even doing a refresh with terraform does not correct the state in the state file to clear this up.

**Comment by jross-ai** [comment]
> My team has found that if there are items that affect the infrastructure that terraform is not aware of, i.e. one stands up their kubernetes infrastructure with terraform and then deploys content into that infrastructure with ansible, timeouts can occur. Once those times happen, the tfstate file is not happy and now has trouble with outputs/locals/etc that have collection or tuple information they should be referencing. Even doing a refresh with terraform does not correct the state in the state file to clear this up.

Do you have a typical workaround that you implement?

**Comment by dpiddockcmp** [comment]
This is one of those annoying edge cases when half the state has been removed. `terraform state list` would give some hints on what resources are remaining to destroy. Maybe shine some light on where the issue is.

Running `terraform destroy` on one of the example folders shows that it works correctly on a totally empty state and thus the difficulty in testing fixes.

**Comment by clushie** [comment]
For me I failed removing my cluster because I forgot uninstalling helm/ingress/route53 before running `terraform destroy`.

Error message is quite similar, `terraform state list` meanwhile shows no output (so the eks cluster is already gone?)

**Comment by acutchin-bitpusher** [comment]
This issue is bedevliing my development efforts right now. Also curious about the apparent abandonment of this issue and lack of workarounds. Are other organizations creating EKS clusters and never destroying them, so not encountering this bug (yet)?

**Comment by barryib** [comment]
@acutchin-bitpusher @clushie  Can you please test this and let me know if it solves your issue.
