### ISSUE TITLE
root_block_device  missed

### ISSUE THREAD

**Issue by ozbillwang** [terraform-aws-modules/terraform-aws-eks#57]
# I have issues

running EKS cluster for a week, get disk space issue, need feature to control and extend with larger  size.

## I'm submitting a...

* [X ] feature request

## What is the current behavior?

No control on root block device,  disk space is used out quickly

## What's the expected behavior?

```
The root_block_device mapping supports the following:

volume_type - (Optional) The type of volume. Can be "standard", "gp2", or "io1". (Default: "standard").
volume_size - (Optional) The size of the volume in gigabytes.
iops - (Optional) The amount of provisioned IOPS. This must be set with a volume_type of "io1".
delete_on_termination - (Optional) Whether the volume should be destroyed on instance termination (Default: true).
```
Currently, only enable `delete_on_termination`

## Are you able to fix this problem and submit a PR? Link here if you have already.

Yes, I will

## Environment details

* Affected module version: v1.1.0
* OS: Ubuntu
* Terraform version: 0.11.7

**Comment by brandoconnor** [comment]
I like the idea. Waiting on your mark to PR this.

**Comment by max-rocket-internet** [comment]
This has been addressed here: https://github.com/terraform-aws-modules/terraform-aws-eks/commit/b71e3e09282ae1e8661e965543463620639930ef
