### ISSUE TITLE
how to disable windows support

### ISSUE THREAD

**Issue by liwei0802** [terraform-aws-modules/terraform-aws-eks#582]
# I have issues

when i run 'terraform plan' its poping up error message below. I am just thinking how can we simple disable windows support?
Error: Your query returned no results. Please change your search criteria and try again.

  on .terraform/modules/my-cluster/terraform-aws-modules-terraform-aws-eks-55ff38c/data.tf line 32, in data "aws_ami" "eks_worker_windows":
  32: data "aws_ami" "eks_worker_windows" {

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by kiefersmith** [comment]
I'm getting the same error.  This causes any plan action to fail...

**Comment by kiefersmith** [comment]
@liwei0802 You can just tie your module to the previous version and it should work.

**Comment by max-rocket-internet** [comment]
Maybe @hodduc can take a look since they made the windows PR 🙂

**Comment by hodduc** [comment]
🤔.. If you are using cluster_version <= 1.13, there is no AMI for that cluster version, but terraform will try to find it and fail. ( https://github.com/hashicorp/terraform/issues/16380 ). I missed that case. 

A possible workaround: Set `var.worker_ami_name_filter_windows` to `*`. Some random AMI will came out from data block, but it will not be used anyway unless using Windows workers.

**Comment by hodduc** [comment]
I think there can be two fix:
* Add `count = (var.cluster_version is greater or equal than "1.14") ? 1 : 0` on `data.aws_ami.eks_worker_windows`
* Add some flag to enable/disable Windows, then add `count = var.enable_windows ? 1 : 0` on `data.aws_ami.eks_worker_windows`

@max-rocket-internet Does this looks fine?

**Comment by max-rocket-internet** [comment]
> Add some flag to enable/disable Windows

That doesn't sound super elegant.

Can you add some conditions into `local.worker_ami_name_filter_windows` so that if k8s version is less than 1.14 then it doesn't fail?

Maybe something like this?

```
  worker_ami_name_filter_windows = var.worker_ami_name_filter_windows != "" ? var.worker_ami_name_filter_windows : tonumber(var.cluster_version) < 1.14 ? local. worker_ami_name_filter : "Windows_Server-2019-English-Core-EKS_Optimized-${var.cluster_version}-*"
```

**Comment by oschrenk** [comment]
Can this be re-opened?

 This still happens with the basic example with these versions


```
terraform-aws-modules/eks/aws 12.2.0 for eks...

Terraform v0.12.9
+ provider.aws v2.70.0
```

event with `cluster_version` set to `1.17`

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = local.cluster_name
  cluster_version = "1.17"
 ...
```

I used   `worker_ami_name_filter_windows = "*"` as instructed by @hodduc (thanks) as a workaround.

**Comment by icco** [comment]
This happened to me today on cluster_version of 1.20

**Comment by barryib** [comment]
I just opened https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1371 to address this. Will you please review it and test it ?
