### ISSUE TITLE
Cloud-init support

### ISSUE THREAD

**Issue by thomas-brx** [terraform-aws-modules/terraform-aws-eks#585]
# I have a feature request

## I'm submitting a...

* [ ] bug report
* [X] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [X] kudos, thank you, warm fuzzy

## What is the current behavior?
`terraform-aws-eks` allows modifying the cloud-init script by using `additional_userdata` and `pre_userdata`, and also to override the template completely.

## What's the expected behavior?
It would be great if it was possible to add [MIME-parts](https://www.terraform.io/docs/providers/template/d/cloudinit_config.html) to the userdata, to be able to use all features of cloud-init, like:

```
worker_groups = [
    {
      ...
      userdata_parts = [
        {
          content_type = "text/cloud-config"
          filename = "cloud-config"
          merge_type = "list(append)+dict(recurse_array)+str()"

          content = <<CLOUD_CONFIG
packages:
  - strace

bootcmd:
  - echo "ENVIROMNET=${var.environment}" >> /etc/environment
CLOUD_CONFIG
        },
      ]
    }
  ]
```
## Are you able to fix this problem and submit a PR? Link here if you have already.

https://github.com/terraform-aws-modules/terraform-aws-eks/pull/584

**Comment by max-rocket-internet** [comment]
We could also just allow setting the complete user-data per worker group which would completely replace the existing user-data if supplied. This would save the extra complexity in this module.

**Comment by max-rocket-internet** [comment]
Closing in favour of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/601

The reason is that we are trying to make the module more simple. By allowing a user to completely replaces the user data this gives ultimate flexibility while not making the module manage another resources. I hope that makes sense!
