### ISSUE TITLE
Failing destroy-time provisioner does not abort resource deletion

### ISSUE THREAD

**Issue by syst0m** [terraform-aws-modules/terraform-aws-eks#586]
# I have issues
Created a destroy-time provisioner which looks for LoadBalancer services, 
and fails if it finds any.
The idea is to abort the destroy if LoadBalancer services exist, and ensure they have been migrated.
I had to create a `null_resource` with a destroy-time provisioner, which depends on the eks module.

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
The provisioner runs and exits with status code 1, but the destroy does not abort
and the cluster gets deleted.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
```resource "null_resource" "cluster_destroy" {
  depends_on = [module.eks.cluster_endpoint]

  provisioner "local-exec" {
    when = "destroy"
    interpreter = ["bash", "-c"]
    command = <<EOF
kubectl \
  --kubeconfig <(echo "${module.eks.kubeconfig}") \
  get svc \
  | grep LoadBalancer

if [ $? -eq 1 ]
then
  kubectl \
    --kubeconfig <(echo "${module.eks.kubeconfig}") \
    delete \
    --all \
    namespaces
else
  echo "PUBLIC LOAD BALANCERS DETECTED. QUITTING..."; exit 1
fi
EOF
  }
}
```

The provisioner runs and fails, but destroy proceeds and all clsuter resources are deleted:
```
module.habito-eks-forrest.null_resource.cluster_destroy (local-exec): Executing: ["bash" "-c" "kubectl \\\n  --kubeconfig <(echo \"apiVersion: v1\npreferences: {}\nkind: Config\n\nclusters:\n- cluster:\n    server: https://XXXX=\n  name: eks_forrest\n\ncontexts:\n- context:\n    cluster: eks_forrest\n    user: eks_forrest\n  name: eks_forrest\n\ncurrent-context: eks_forrest\n\nusers:\n- name: eks_forrest\n  user:\n    exec:\n      apiVersion: client.authentication.k8s.io/v1alpha1\n      command: aws-iam-authenticator\n      args:\n        - \"token\"\n        - \"-i\"\n        - \"forrest\"\n        - -r\n        - arn:aws:iam::XXX:role/Administrator\n\n\") \\\n    delete \\\n    --all \\\n    namespaces\nelse\n  echo \"PUBLIC LOAD BALANCERS DETECTED. QUITTING...\"; exit 1\nfi\n"]
```

## What's the expected behavior?
When the provisioner fails, destroy of the cluster is aborted.

## Are you able to fix this problem and submit a PR? Link here if you have already.
I submitted a PR which adds count to all resources:
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/580

But, there would be issues with migration of resources.

## Environment details

* Affected module version: 6.0.2
* OS: Ubuntu 18.04.3 LTS
* Terraform version: v0.12.10

**Comment by max-rocket-internet** [comment]
The PR was merged so I will close this but also bear in mind that cleaning up AWS resources created by k8s is out of the scope of this module. Also this might be interesting to you: 
https://github.com/kubernetes/kubernetes/pull/85023
https://github.com/kubernetes/enhancements/issues/980
