### ISSUE TITLE
handling config_output_path when it starts with tilde

### ISSUE THREAD

**Issue by swapzero** [terraform-aws-modules/terraform-aws-eks#587]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Using `~` in `config_output_path`  does not work

## If this is a bug, how to reproduce? Please include a code sample if relevant.
- configuration
```
...
variable "write_kubeconfig" {
  description = "..."
  type        = bool
  default     = true
}
...
variable "config_output_path" {
  description = "..."
  type        = string
  default     = "~/.kube/"
}
...
```
- run `terraform apply`
```
# it creates "~" directory in CWD
$ pwd
.../terraform-aws-eks/examples/basic

$ ls -l
drwxr-xr-x   3 user  staff      96 Nov  8 11:48 ~

$ ls "~/.kube/"
config-map-aws-auth_bender.yaml	kubeconfig_bender
```

## What's the expected behavior?
it should create the config in /path/to/user/home/dir/.kube/ (`pathexpand` on the filename fixes this)
e.g:
```
resource "local_file" "kubeconfig" {
  count    = var.write_kubeconfig ? 1 : 0
  content  = data.template_file.kubeconfig.rendered
  filename = pathexpand("${substr(var.config_output_path, -1, 1) == "/" ? "${var.config_output_path}kubeconfig_${var.cluster_name}" : var.config_output_path}")
}
```

## Environment details

* Affected module version:
* OS: macOS Mojave
* Terraform version: 0.12.13

**Comment by jayaramcloud** [comment]
I also have this same issue now.

**Comment by dpiddockcmp** [comment]
This is discussed in the provider's repo: https://github.com/hashicorp/terraform-provider-local/pull/34

You can use `pathexpand` to convert the filename to a full path. This will then end up in your state file.
