### ISSUE TITLE
Module should be updated to use AWS CLI to authenticate instead of aws-iam-authenticator

### ISSUE THREAD

**Issue by uyenle57** [terraform-aws-modules/terraform-aws-eks#589]
# I have issues

## I'm submitting a...

* [ ] bug report
* [*] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Module not able to run kubectl commands because of the following error:
`aws-iam-authenticator": executable file not found in $PATH`

## What's the expected behavior?
Module should be updated to the newest authentication method, which is using AWS CLI instead of aws-iam-authenticator.

## Are you able to fix this problem and submit a PR? Link here if you have already.
Fixed by installing aws-iam-authenticator.

## Environment details

* Affected module version: 6.0.2
* OS: Ubuntu 16.04
* Terraform version: 0.12

## Any other relevant info
* EKS cluster version: 1.14

**Comment by max-rocket-internet** [comment]
You can use it if you want, details are here: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/383#issuecomment-495178057

One draw back of the AWS CLI is it has a lot of dependencies as it's written in python.

If you have strong feelings either way, please add it to the discussion in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/589 🙂
