### ISSUE TITLE
How to run cluster initialization script after install?

### ISSUE THREAD

**Issue by TarekAS** [terraform-aws-modules/terraform-aws-eks#590]
# I have issues

I want to automatically run a script after the module is installed, but since the `local-exec` provisioner does not work on modules, I'm struggling to find a way to automate this.
Is there a recommended way to do this?

## I'm submitting a...

* [ ]  bug report
* [ ]  feature request
* [x]  support request
* [ ]  kudos, thank you, warm fuzzy

**Comment by max-rocket-internet** [comment]
I think if you just use the module output `cluster_endpoint` in your resource it should work?

**Comment by TarekAS** [comment]
This worked, thanks!
