### ISSUE TITLE
aws_auth ConfigMap can't apply with assumed role...

### ISSUE THREAD

**Issue by rojopolis** [terraform-aws-modules/terraform-aws-eks#598]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/2d52e06786cdb9feb742b7fc1968ffa5b87cf255/aws_auth.tf#L16

If the AWS provider is configured with an assumed role, then this local-exec fails because the generated kubeconfig does not include a "-r" option to assume the role.  The apply fails, but doesn't abort the Terraform apply which results in a misconfigured cluster.

**Comment by max-rocket-internet** [comment]
I think you can just set `kubeconfig_aws_authenticator_additional_args`, right? https://github.com/terraform-aws-modules/terraform-aws-eks#inputs

**Comment by schittler** [comment]
We ran into this yesterday and I can confirm you need to set it in additional args (or if you can ensure the role is in a profile on every users machine, set the environment with `AWS_PROFILE` instead)
