### ISSUE TITLE
Support EKS Managed Node Groups

### ISSUE THREAD

**Issue by wmorgan6796** [terraform-aws-modules/terraform-aws-eks#599]
# I have issues

## I'm submitting a...

* [ ] bug report
* [X ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Today AWS announced Managed Node Groups for EKS. This module should strive to support that as quickly as possible. The [relevant PR](https://github.com/terraform-providers/terraform-provider-aws/issues/10915) has been merged within the latest release of the AWS provider.

## What's the expected behavior?
Supporting managed node groups.

## Are you able to fix this problem and submit a PR? Link here if you have already.
Unsure if I'll have time this week to do this, but can get to it next week.

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by reegnz** [comment]
The terraform aws provider supports it: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/599
Pretty nice that AWS takes the terraform aws provider seriously and rolls out the feature on the same day the SDK starts supporting it.

**Comment by vishnuhd** [comment]
I am sorry to put it harshly, but approximately when can we use the module for Managed Node Groups?
We are in a sort of dilemma to either continue using this awesome module or create our own for our new EKS cluster.

**Comment by wmorgan6796** [comment]
I think the usefulness of the managed node groups is neutered a bit until we can set kubelet flags.

**Comment by max-rocket-internet** [comment]
> I am sorry to put it harshly, but approximately when can we use the module for Managed Node Groups?

When there's a PR merged for that.

**Comment by wmorgan6796** [comment]
I've filed a pull request for the feature [here](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/602)

**Comment by max-rocket-internet** [comment]
Nice @wmorgan6796! Perhaps @vishnuhd can test this PR?

**Comment by wmorgan6796** [comment]
#602

**Comment by eytanhanig** [comment]
Given that we already have variables like `worker_groups`, `worker_groups_launch_template`, etc, do we want to use something along the lines of `node_groups` instead of the more complicated `worker_group_managed_node_groups`?

**Comment by wmorgan6796** [comment]
The PR associated with this issue has been merged and I will be closing it.
