### ISSUE TITLE
Allow custom user-data per worker group

### ISSUE THREAD

**Issue by max-rocket-internet** [terraform-aws-modules/terraform-aws-eks#601]
Something like this:

```hcl

  worker_groups_launch_template = [
    {
      name                = "wg1"
      instance_type       = "m5.xlarge"
      asg_min_size        = 5
      user_data        = data.template_file.my_custom_userdata.rendered
    }
```

This would allow people to completely replace the user data and also to [template_cloudinit_config](https://www.terraform.io/docs/providers/template/d/cloudinit_config.html)

**Comment by efernandes-ANDigital** [comment]
@max-rocket-internet Does setting pre_userdata in the worker_groups_launch_template not replace  the launch configuration per worker group?

**Comment by max-rocket-internet** [comment]
You see what it does here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/templates/userdata.sh.tpl

**Comment by barryib** [comment]
@max-rocket-internet does https://github.com/terraform-aws-modules/terraform-aws-eks/pull/565 resolves this ?

**Comment by max-rocket-internet** [comment]
Yes

**Comment by galindro** [comment]
@max-rocket-internet when #565 will be released?

**Comment by galindro** [comment]
Oh, my bad... it is already in place: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v8.2.0/local.tf#L43
