### ISSUE TITLE
Nat gateway EIP

### ISSUE THREAD

**Issue by LouisDinatale** [terraform-aws-modules/terraform-aws-eks#603]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [* ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

When creating a nat gateway is there a way to use a specific EIP you already have?

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by max-rocket-internet** [comment]
There is, it's the `external_nat_ip_ids` option on the [terraform-aws-vpc](https://github.com/terraform-aws-modules/terraform-aws-vpc) module. If you don't have the EIP in your TF code base you can import it: https://www.terraform.io/docs/providers/aws/r/eip.html#import

This is not part of this module BTW so I will close this issue 🙂

**Comment by LouisDinatale** [comment]
Thank you very much.
