### ISSUE TITLE
[feature] Fargate for EKS

### ISSUE THREAD

**Issue by chenrui333** [terraform-aws-modules/terraform-aws-eks#609]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [x] kudos, thank you, warm fuzzy

## new announcement

https://aws.amazon.com/about-aws/whats-new/2019/12/run-serverless-kubernetes-pods-using-amazon-eks-and-aws-fargate/

Run Serverless Kubernetes Pods Using Amazon EKS and AWS Fargate
Posted On: Dec 3, 2019

You can now use Amazon Elastic Kubernetes Service (EKS) to run Kubernetes pods on AWS Fargate, the serverless compute engine built for containers on AWS. This makes it easier than ever to build and run your Kubernetes applications in the AWS cloud.

EKS support for Fargate is available in US East (Virginia), US East (Ohio), Europe (Ireland), and Asia Pacific (Tokyo) regions.

## Related AWS container-roadmap issue

https://github.com/aws/containers-roadmap/issues/32#issuecomment-561249391

**Comment by max-rocket-internet** [comment]
How does this look from a Terraform perspective? What new resources?

**Comment by chenrui333** [comment]
Yeah, I dont know quite much at this moment either.

**Comment by dpiddockcmp** [comment]
Provider 2.41.0 added [`aws_eks_fargate_profile`](https://www.terraform.io/docs/providers/aws/r/eks_fargate_profile.html). 

These need a suitable IAM role to be created: [docs](https://docs.aws.amazon.com/eks/latest/userguide/pod-execution-role.html)

We could also handle a map of profile name to namespace and labels, and create the profiles in a `for_each`.

**Comment by ivankatliarchuk** [comment]
There is currently a limitation. Not every region support it.

> If you want to explore Amazon EKS on AWS Fargate yourself, you can try it now by heading on over to the EKS console in the following regions: US East (N. Virginia), US East (Ohio), Europe (Ireland), and Asia Pacific (Tokyo). ([reference](https://aws.amazon.com/blogs/aws/amazon-eks-on-aws-fargate-now-generally-available/))

**Comment by marcust** [comment]
AWS tracks the roll-out progress in their public roadmap: https://github.com/aws/containers-roadmap/issues/620

**Comment by rblaine95** [comment]
I'd just like to toss in a +1 for this feature request.  

Been banging my head against adding Fargate to EKS via Terraform for the last day or so, modding other Terraform modules (`terraform-module/eks-fargate-profile/aws`) to accept `list(string)` instead of just `string` and then working the compatibility of that, resulting in a mild migraine.

**Comment by ImIOImI** [comment]
I'm really interested in seeing fargate profiles added as well.

**Comment by Vlli** [comment]
This would be extremly useful.

**Comment by xposix** [comment]
Adding Fargate on a deployment only requires few lines of code, it's very quick, this is mine:
```
module "eks_fargate" {
  source  = "terraform-module/eks-fargate-profile/aws"
  version = "2.2.5"

  cluster_name = data.terraform_remote_state.eks_cluster.outputs.cluster_id
  subnet_ids   = data.aws_subnet_ids.private.ids
  namespaces = [
    "jenkins"
  ]
  labels = {
    "app.kubernetes.io/name" = "jenkins-fargate-slaves"
  }
  tags = local.project_tags
}
```

I totally understand that argument where people would like to keep the module simple, otherwise they become a mess.

**Comment by barryib** [comment]
The PR #1067 add fargate support. We need help for tests and review.

**Comment by barryib** [comment]
[v13.2.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v13.2.0) is released with the EKS fargate support.
