### ISSUE TITLE
Local Exec Unauthorized on applying ConfigMap

### ISSUE THREAD

**Issue by dannyburke1** [terraform-aws-modules/terraform-aws-eks#612]
# I have issues
I'm trying to update the config the map via the map roles and getting the follow error:

`module.eks.null_resource.update_config_map_aws_auth (local-exec): error: unable to recognize "./kubernetes/config-map.yaml": Unauthorized`

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

I've been updating the ConfigMap for an EKS upgrade and have been struggling with the above error all day.

I'm logged in with AWS config with our full admin role, the same roll that created the customer. 

I'm using Terraform v0.11.14
Module version: v2.1.0 (However tried many different version) 

I've tried passing in:
`manage_aws_auth        = true`
` kubeconfig_aws_authenticator_additional_args = ["-r", "rolename"]`

And also the profile of the aws config however I can't get back into the cluster.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```
`module "eks" {
  version                = "2.1.0"
  source                 = "terraform-aws-modules/eks/aws"
  cluster_name           = "${var.name}-${var.environment}"
  manage_aws_auth        = true
  cluster_version        = "${var.eks_cluster_version}"
  config_output_path     = "./kubernetes/"
  map_roles_count        = 2
  map_roles              = "${var.eks_map_roles}"
  map_users              = "${var.eks_map_users}"
  worker_group_count     = "${var.eks_worker_group_count}"
  worker_groups          = "${var.eks_worker_groups}"
  workers_group_defaults = "${var.eks_workers_group_defaults}"
  subnets                = "${module.vpc.private_subnets}"
  vpc_id                 = "${module.vpc.vpc_id}"
}`
```

## What's the expected behavior?

Errors with Unauthorized

## Environment details

* Affected module version: All 
* OS: Mac OSX Mojave v10.14.3
* Terraform version: 0.11.14

**Comment by dpiddockcmp** [comment]
This is sort of explained in the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html#unauthorized)

Only IAM users/roles who have been granted write access to the aws-auth ConfigMap by the aws-auth ConfigMap are allowed to update the ConfigMap. Like via the default `system:masters` group.

If this is the first time you're creating the cluster then it **must** be done by an IAM user/role with suitable permissions. Not the AWS account root user.

If this is an existing cluster that has lost or corrupted its aws-auth then only the IAM user/role that originally created the cluster can update the ConfigMap. Unfortunately the master IAM user/role is secret information that is hidden inside the master nodes and is not accessible. You just have to somehow remember who it was.

It might also be easier to debug without using the module. Are you allowed to edit the ConfigMap? `kubectl -n kube-system auth can-i edit configmap/aws-auth`

**Comment by dannyburke1** [comment]
> This is sort of explained in the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html#unauthorized)
> 
> Only IAM users/roles who have been granted write access to the aws-auth ConfigMap by the aws-auth ConfigMap are allowed to update the ConfigMap. Like via the default `system:masters` group.
> 
> If this is the first time you're creating the cluster then it **must** be done by an IAM user/role with suitable permissions. Not the AWS account root user.
> 
> If this is an existing cluster that has lost or corrupted its aws-auth then only the IAM user/role that originally created the cluster can update the ConfigMap. Unfortunately the master IAM user/role is secret information that is hidden inside the master nodes and is not accessible. You just have to somehow remember who it was.
> 
> It might also be easier to debug without using the module. Are you allowed to edit the ConfigMap? `kubectl -n kube-system auth can-i edit configmap/aws-auth`

Hi! Thanks for getting back to me.

This seems to have ultimately been caused by the cluster module moving from one to another and a cluster that hadn't been updated in a long while, our mapped roles was overwritten by the defaults somewhere in terraform vars and caused our usual role to be wiped, leaving just the eks worker iam role to be left in.

We used a shared role to create resources, however I wanted to check CloudTrail to see how this cluster was created because ultimately the shared role would work as usual.

Ultimately, we had lost all control of the auth with the cluster, even when using the root account user as a last port of call.

In the end we fixed, which involved ssh'ing into one of the worker nodes and editing the configmap from there to allow our role access again as `system:masters`.

Again, 

Thanks for your response.

Danny
