### ISSUE TITLE
workers not being created in private subnets only

### ISSUE THREAD

**Issue by t5unamie** [terraform-aws-modules/terraform-aws-eks#613]
When using the default example given, while passing in public and private subnets. The workers are randomly put in public and private subnets.

It should be possible to put all the worker nodes into the private subnets and the ELB created in the public. However there does'nt seem to an example of this.

## What is the current behavior?

worker nodes are randomly assigned to public or private subnets.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Us ethe default example and passing subnets for bother public/private subnets and select ASAG size of 4 when you have 6 subnets in the list. 3 of each public and private.

## What's the expected behavior?

That all workers get started in private.

**Comment by max-rocket-internet** [comment]
> What's the expected behavior? That all workers get started in private.

Then just pass private subnets only. Why would you pass both when want to use only private subnets for your nodes?

**Comment by t5unamie** [comment]
I think I miss understood

https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html

Thats seems to imply we have to add both public and private subnets for thepublic ELB created by kubernetes to occur.

**Comment by t5unamie** [comment]
after testing, this indeeds seems to be a problem. If you don't add an public subnet to the subnet list. It won't allow you to create public ELB even thow the kubernetes templates request it.

**Comment by dpiddockcmp** [comment]
Hi @t5unamie ,

The Kubernetes Service controller, when run in AWS, uses tags on the subnets to know where it is allowed to create ELBs. The VPC and all subnets you want to use have to be tagged with `kubernetes.io/cluster/$cluster_name = shared`. The controller will then look at the routing rules to figure out which is "public" and which "private" if no other tags are set.

Public ELBs will only be created in "public" subnets. Private ELBs will prefer "private" subnets and fall back to "public" if no privates exist. You can also use tags on subnets to hint to the controller which subnets to use. This is especially important if you have multiple subnets of the same type in the same AZ as an ELB can only use one subnet per AZ:
- Private subnets with `kubernetes.io/role/internal-elb = 1`
- Public subnets with `kubernetes.io/role/elb = 1`

The EKS service will apply these tags to your VPC and subnets for you when you create the cluster. Terraform will remove these tags on subsequent runs if you also manage your VPC with Terraform and don't assign the tags. Or ignore them with the new provider [`ignore_tag_prefixes`](https://www.terraform.io/docs/providers/aws/#ignore_tag_prefixes) and `ignore_tags` options.

You are not required to assign all public and private subnets to EKS. Just assign it enough to cover the AZs you are using so it will create suitable ENIs. And ensure you have the subnets tagged.

Appropriate subnet tagging, using this org's VPC module, is shown in the basic example [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/fb61b48c26315d300eac2f6f1e7830426cae5716/examples/basic/main.tf#L114..L126)

Another option, to directly address your original issue, is to pass in the private subnet IDs to your worker group or the default for all groups:
```
module "eks_cluster" {
  # ...
  workers_group_defaults = {
    subnets = module.vpc.private_subnets
  }
} 
```

HTH

**Comment by max-rocket-internet** [comment]
Amen @dpiddockcmp 🙏
