### ISSUE TITLE
Worker nodes not added & aws-auth not applied

### ISSUE THREAD

**Issue by t5unamie** [terraform-aws-modules/terraform-aws-eks#615]
# I have issues

v7.0.0 & v6.02 errors with the statment below and worker nodes not added to cluster.

It errors out with

module.eks_cluster.null_resource.update_config_map_aws_auth[0]: Still creating... [2m0s elapsed]
module.eks_cluster.null_resource.update_config_map_aws_auth[0] (local-exec): could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
module.eks_cluster.null_resource.update_config_map_aws_auth[0] (local-exec): 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
module.eks_cluster.null_resource.update_config_map_aws_auth[0] (local-exec): Unable to connect to the server: getting token: exec: exit status 1
module.eks_cluster.null_resource.update_config_map_aws_auth[0]: Still creating... [2m10s elapsed]

## I'm submitting a...

* [*] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ *] kudos, thank you, warm fuzzy

## What is the current behavior?

failed to create aws_auth

## What's the expected behavior?

That it creates the aws_auth configmap

## Environment details

* Affected module version:
v7.0.0 & v6.02
* OS:
MAc latest update
* Terraform version:
terraform --version
Terraform v0.12.17
+ provider.aws v2.39.0

## Any other relevant info

the eks cluster does provide the endpoint so I could correct your example from

https://github.com/terraform-aws-modules/terraform-aws-eks/commit/93636625740c63fd89ad8bc60ad180761288c54d

however the token was nested some where and still working out the properties. As you can see the data provider only passes the ID and not the endpoint nor the token. Yet the references assume that they exit under there.

Code below.

My VPC module
`
module "vpc" {
source = "terraform-aws-modules/vpc/aws"
name = "${terraform.workspace}"
cidr = "10.0.0.0/16"
azs = "${lookup(var.workspace_to_az, terraform.workspace )}"
private_subnets = "${lookup(var.workspace_to_private_subnets, terraform.workspace )}"
public_subnets = "${lookup(var.workspace_to_public_subnets, terraform.workspace )}"

enable_nat_gateway = true
single_nat_gateway = true
reuse_nat_ips = true
one_nat_gateway_per_az = false
external_nat_ip_ids = data.terraform_remote_state.eu-eip-nat.outputs.eu-aws_eip_id

enable_dns_hostnames = true
enable_dns_support = true

tags = {
Terraform = "true"
Environment = "${lookup(var.workspace_to_env, terraform.workspace )}"
Name = "${terraform.workspace}"
"kubernetes.io/cluster/${terraform.workspace}" = "shared"
}

private_subnet_tags = {
Terraform = "true"
Environment = "${lookup(var.workspace_to_env, terraform.workspace )}"
Name = "private-${terraform.workspace}"
"kubernetes.io/role/internal-elb" = "1"
"kubernetes.io/cluster/${terraform.workspace}" = "shared"

}

public_subnet_tags = {
Terraform = "true"
Environment = "${lookup(var.workspace_to_env, terraform.workspace )}"
Name = "public-${terraform.workspace}"
"kubernetes.io/role/elb" = "1"
"kubernetes.io/cluster/${terraform.workspace}" = "shared"
}

}

output "pr_routing_tb" {
value = module.vpc.private_route_table_ids
}

output "vpc_id" {
value = module.vpc.vpc_id
}

output "public_subnets_ids" {
value = module.vpc.public_subnets
}

output "private_subnets_ids" {
value = module.vpc.private_subnets
}

output "subnets_ids" {
value = concat(module.vpc.private_subnets, module.vpc.public_subnets)
}

resource "aws_eip" "nat" {
count = 3

vpc = true
}
`
okay this is the module code

`provider "null" {
version = "~> 2.1"
}

provider "template" {
version = "~> 2.1"
}

resource "aws_security_group" "all_worker_mgmt" {
name_prefix = "all_worker_management"
vpc_id = data.terraform_remote_state.networking.outputs.vpc_id

ingress {
from_port = 22
to_port = 22
protocol = "tcp"

cidr_blocks = [
  "10.0.0.0/16",
  "172.16.0.0/12",
  "192.168.0.0/16",
]
}
}

module "eks_cluster" {
source = "terraform-aws-modules/eks/aws"
cluster_name = terraform.workspace
subnets = data.terraform_remote_state.networking.outputs.private_subnets_ids
vpc_id = data.terraform_remote_state.networking.outputs.vpc_id
cluster_endpoint_private_access = false
cluster_endpoint_public_access = true
worker_additional_security_group_ids = [aws_security_group.all_worker_mgmt.id]

worker_groups = [
{
instance_type = "t2.medium"
asg_min_size = 1
asg_max_size = 1
key_name = "XXXexample"
tags = [{
key = "NAME"
value = terraform.workspace
propagate_at_launch = true
}]
}
]

tags = {
environment = terraform.workspace
}

}`

I don't understand why I get the error. It's correctly creating it in the correct subnet/vpc.

I have checked the FAQ and also connected to the node's and checked if the cloud init runs successfully. The bootstrap has no errors.

I check the node can connect to the endpoint which it can. It curls just find to the endpoint so not a netwprk issue.

I checked the dns mapping and it indeed does goes to the public IP address for the endpoint.

I checked the the worker node could reach the internet at the same time as reaching the endpoint.

I am at a **loss.**

**Comment by t5unamie** [comment]
wait how do I know which ones a stable tag if so many of these are broken. I just tested v6.02 and have seen the same problem.

**Comment by t5unamie** [comment]
okay this is the module code

`provider "null" {
  version = "~> 2.1"
}

provider "template" {
  version = "~> 2.1"
}

resource "aws_security_group" "all_worker_mgmt" {
  name_prefix = "all_worker_management"
  vpc_id      = data.terraform_remote_state.networking.outputs.vpc_id

  ingress {
    from_port = 22
    to_port   = 22
    protocol  = "tcp"

    cidr_blocks = [
      "10.0.0.0/16",
      "172.16.0.0/12",
      "192.168.0.0/16",
    ]
  }
}

module "eks_cluster" {
  source       = "terraform-aws-modules/eks/aws"
  cluster_name = terraform.workspace
  subnets      = data.terraform_remote_state.networking.outputs.private_subnets_ids
  vpc_id       = data.terraform_remote_state.networking.outputs.vpc_id
  cluster_endpoint_private_access	=	false
  cluster_endpoint_public_access	=	true
  worker_additional_security_group_ids = [aws_security_group.all_worker_mgmt.id]

  worker_groups = [
    {
      instance_type = "m2.medium"
      asg_min_size  = 1
      asg_max_size  = 1
      key_name      = "XXXexample" 
      tags = [{
        key                 = "NAME"
        value               = terraform.workspace
        propagate_at_launch = true
      }]
    }
  ]

  tags = {
    environment = terraform.workspace
  }



  }`

I don't understand why I get the error. It's correctly creating it in the correct subnet/vpc.

I have checked the FAQ and also connected to the node's and checked if the cloud init runs successfully. The bootstrap has no errors.

I check the node can connect to the endpoint which it can. It curls just find to the endpoint so not a netwprk issue.

I checked the dns mapping and it indeed does goes to the public IP address for the endpoint. 

I checked the the worker node could reach the internet at the same time as reaching the endpoint.


I am at a loss.

**Comment by t5unamie** [comment]
My VPC module
`
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  name = "${terraform.workspace}"
  cidr = "10.0.0.0/16"
  azs             = "${lookup(var.workspace_to_az, terraform.workspace )}"
  private_subnets = "${lookup(var.workspace_to_private_subnets, terraform.workspace )}"
  public_subnets  = "${lookup(var.workspace_to_public_subnets, terraform.workspace )}"

  enable_nat_gateway = true
  single_nat_gateway = true
  reuse_nat_ips      = true
  one_nat_gateway_per_az = false
  external_nat_ip_ids = data.terraform_remote_state.eu-eip-nat.outputs.eu-aws_eip_id

  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Terraform = "true"
    Environment = "${lookup(var.workspace_to_env, terraform.workspace )}"
    Name = "${terraform.workspace}"
    "kubernetes.io/cluster/${terraform.workspace}" = "shared"
  }

  private_subnet_tags = {
    Terraform = "true"
    Environment = "${lookup(var.workspace_to_env, terraform.workspace )}"
    Name = "private-${terraform.workspace}"
    "kubernetes.io/role/internal-elb" = "1"
    "kubernetes.io/cluster/${terraform.workspace}" = "shared"

  }

  public_subnet_tags = {
    Terraform = "true"
    Environment = "${lookup(var.workspace_to_env, terraform.workspace )}"
    Name = "public-${terraform.workspace}"
    "kubernetes.io/role/elb" = "1"
    "kubernetes.io/cluster/${terraform.workspace}" = "shared"
  }

}

output "pr_routing_tb" {
  value = module.vpc.private_route_table_ids
}

output "vpc_id" {
  value = module.vpc.vpc_id
}

output "public_subnets_ids" {
  value = module.vpc.public_subnets
}

output "private_subnets_ids" {
  value = module.vpc.private_subnets
}

output "subnets_ids" {
  value = concat(module.vpc.private_subnets, module.vpc.public_subnets)
}

resource "aws_eip" "nat" {
  count = 3

  vpc = true
}
`

**Comment by t5unamie** [comment]
Interesting I looked through
 https://github.com/terraform-aws-modules/terraform-aws-eks/issues/534

`apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::XXXXXXXXXXX:role/XXXXXXXXXXXXXXXXXXXXXXX
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes`

tried to run with the yaml file above which gets produced by terraform apply.

kubectl apply -f config-map-aws-auth_prod-cluster.yaml 

Get the following error

error: SchemaError(io.k8s.apimachinery.pkg.apis.meta.v1.Preconditions): invalid object doesn't have additional properties

**Comment by t5unamie** [comment]
God damn it, it was my kubctl version that was broken.

Upgrading it to 10.16

you need to update the READme. As kubectl 1.10 does not work with modules v7.0.0 or v6.0.2

the below version works

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:25:00Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b8860f", GitCommit:"b8860f6c40640897e52c143f1b9f011a503d6e46", GitTreeState:"clean", BuildDate:"2019-11-25T00:55:38Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by t5unamie** [comment]
There is defiantly something wrong with kubctl run.

`module.eks_cluster.null_resource.update_config_map_aws_auth[0]: Still creating... [40s elapsed]
module.eks_cluster.null_resource.update_config_map_aws_auth[0] (local-exec): could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
module.eks_cluster.null_resource.update_config_map_aws_auth[0] (local-exec): 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
module.eks_cluster.null_resource.update_config_map_aws_auth[0] (local-exec): could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
module.eks_cluster.null_resource.update_config_map_aws_auth[0] (local-exec): 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
module.eks_cluster.null_resource.update_config_map_aws_auth[0] (local-exec): error: unable to recognize "aws_auth_configmap.yaml": Get https://XXXXXXXXXX.eks.amazonaws.com/api?timeout=32s: getting credentials: exec: exit status 1`

**Comment by dpiddockcmp** [comment]
How is your AWS provider configured? Terraform appears to strip out or not pass on environment variables to local-exec.

If you're using an aws profile you'll need to pass it through to the generated kubeconfig:
```
module "eks_cluster" {
  # ...
  kubeconfig_aws_authenticator_env_variables = {
    AWS_PROFILE = "my_aws_profile"
  }
}
```

**Comment by t5unamie** [comment]
This works, closing this out
