### ISSUE TITLE
EKS Managed node groups autoscaling

### ISSUE THREAD

**Issue by steve21168** [terraform-aws-modules/terraform-aws-eks#622]
# Request to improve aws_eks_node_group module

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

In the aws_eks_node_group scaling_config block you are required to set the desired size.  This is undesirable b/c I want to let my nodes autoscale within the min-max range I set.  Everytime my terraform is deployed it tries to reset the ASG to the desired size set within terraform.  

I believe desired size should be optional.  When you use an ASG directly with Terraform the desired_capacity is optional and would expect the same for this API that manages an ASG behind the scenes.

## What's the expected behavior?

Would expect to set a scaling min and max size without setting a hard desired size.

**Comment by max-rocket-internet** [comment]
I think you need something like this? https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers_launch_template.tf#L214-L218

**Comment by steve21168** [comment]
@max-rocket-internet Sorry for the confusion I posted this in the wrong place.  I was referring to fixing the official AWS provider resource `aws_eks_node_group` 

If anyones interested I opened an issue for this there now:
https://github.com/terraform-providers/terraform-provider-aws/issues/11296
