### ISSUE TITLE
EKS Managed groups: public_ip and worker_additional_security_group_ids configuration fields are ignored

### ISSUE THREAD

**Issue by xposix** [terraform-aws-modules/terraform-aws-eks#623]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
When I define node_groups with the same configuration I had with worker groups, the following fields are ignored:
* public_ip
* worker_additional_security_group_ids

## If this is a bug, how to reproduce? Please include a code sample if relevant.
The following code create ec2 worker nodes with public IP (on private subnets) and doesn't attach the SG deployed below.
```
module "eks-cluster" {
  source = "github.com/terraform-aws-modules/terraform-aws-eks"
  cluster_name = "mytests"
  subnets      = data.terraform_remote_state.networking.outputs.private_subnets
  vpc_id       = data.terraform_remote_state.networking.outputs.vpc_id

  node_groups = [
    {
      name = "mytest_node_groups"
      instance_type = "t3.large"
      asg_max_size  = 2
      autoscaling_enabled = true
      public_ip = false
      key_name = "XXXXXX"
      tags = [{
        key                 = "foo"
        value               = "bar"
        propagate_at_launch = true
      }]
      worker_additional_security_group_ids = [
        aws_security_group.EFS_client
      ]
    }
  ]

  tags = {
    environment = "test"
  }
}

resource "aws_security_group" "EFS_client" {
  name        = "EFS_client"
  description = "Allow EFS outbound traffic"
  vpc_id      = data.terraform_remote_state.networking.outputs.vpc_id
}
```

## What's the expected behavior?
The EC2 instance should only have private IP address and the aws_security_group.EFS_client SG attached to it.

## Are you able to fix this problem and submit a PR? Link here if you have already.
No, sorry

## Environment details

* Affected module version: current master branch 
* OS: Mac OS X latest version
* Terraform version: Terraform v0.12.16

**Comment by nxf5025** [comment]
This isn't a bug. The features just haven't been released by Amazon yet ( https://www.terraform.io/docs/providers/aws/r/eks_node_group.html)

AWS issues:
sgs - https://github.com/aws/containers-roadmap/issues/624
public ip - https://github.com/aws/containers-roadmap/issues/607

**Comment by xposix** [comment]
Mmmm alright, it’s not very intuitive then….
