### ISSUE TITLE
Can you do a new release with node groups?

### ISSUE THREAD

**Issue by davisford** [terraform-aws-modules/terraform-aws-eks#628]
# I have issues

We are trying to use the cluster auto-scaler with EKS.  EKS requires node groups to work properly with auto scaler.  I see you've added support for node groups on Dec. 4.  Is it possible to create a new release?  We are having trouble trying to pull the module down by git hash, but perhaps I am missing something.

**Comment by max-rocket-internet** [comment]
> EKS requires node groups to work properly with auto scaler

No it doesn't. Or you mean a different autoscaler? Like not the cluster-autoscaler?

> Is it possible to create a new release? 

I'm keen to do this but there's a few issues that I think we should resolve first:

https://github.com/terraform-aws-modules/terraform-aws-eks/issues/623
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/627

@davisford perhaps you could test that PR?

**Comment by davisford** [comment]
Yes, I mean the cluster auto-scaler

If I have the time, I'll try to test the PR -- juggling 9000 things, but will do my best.

**Comment by max-rocket-internet** [comment]
> backed by Amazon EBS volumes and using the Kubernetes Cluster Autoscaler

In this case you create an ASG per AZ. But if you are not using EBS volumes then it doesn't matter.

> Will see if I can test out the PRs -- I assume you mean by actually deploying. I can run TF plan and check the output

Great! I am not using managed node groups so can't really test properly.

**Comment by davisford** [comment]
Yes, I am using EBS volumes heavily so node groups are important for us.

**Comment by iterion** [comment]
It doesn't seem like there is anything to be done for https://github.com/terraform-aws-modules/terraform-aws-eks/issues/623 - if there is I'm happy to try to tackle it to unblock a release.

**Comment by max-rocket-internet** [comment]
@iterion sure but base it off this PR that will be merged very soon: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/650
