### ISSUE TITLE
How to tag autoscaling groups created by eks node groups?

### ISSUE THREAD

**Issue by chrisreiche** [terraform-aws-modules/terraform-aws-eks#636]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
The module is working fine for deploying but our Cloud Services team has a requirement that autoscaling groups have specific tags on them.  The tags on node groups do not propagate so I am trying to understand how to have terraform update the tags on the autoscaling groups created by node groups.  Any examples would be helpful.  Thanks!

**Comment by dpiddockcmp** [comment]
Unfortunately this is outside the scope of this module and terraform. It can't control the tags on the generated autoscaling groups as there's no support via the API. 

Not sure if you could do a hack with a lambda that gets triggered when autoscaling groups are modified?

I'd suggest raising an issue with your requirements on the AWS containers roadmap repo: https://github.com/aws/containers-roadmap

**Comment by max-rocket-internet** [comment]
The AWS docs say:

> These tags do not propagate to other resources in the node group, such as Auto Scaling groups or instances

So I will close 🙂
