### ISSUE TITLE
stop making this module hard to integrate with terragrunt

### ISSUE THREAD

**Issue by einyx** [terraform-aws-modules/terraform-aws-eks#638]
Some of the logic has to be declared outside of the scope of the module,
making integrating with terragrunt a bit harder (you need to go to manual control to bootstrap)

This seems to be the new way to go in the master branch while tags are still seems to be fine.

The refactoring logic seems to be following an antipattern since the latest 7.0.1 -> master release
Am I missing something? :)

**Comment by max-rocket-internet** [comment]
I've only used Terragrunt briefly so you will need to be more specific, with examples.

**Comment by einyx** [comment]
look at the code v0.7.1 vs master, seems like a big shift in the logic behind the module,
regardless specific code snippet, seems like we are breaking out of the scope of the module, having to declare providers externally and TF data sources.

**Comment by shanesveller** [comment]
You should be using your own wrapper code that includes this module in-line, and pointing Terragrunt at _that_ as your `include`. This pattern works well for me personally.

**Comment by barryib** [comment]
I use Terragrunt a lot, and wrote a module which include the terraform-aws-eks module as @shanesveller suggested. Working great so far (almost 2 years now).

Closing this. Feel free to re-open it if the proposed solution doesn't work for you, or if you have another proposal.
