### ISSUE TITLE
No any logs exported to Cloudwatch

### ISSUE THREAD

**Issue by ozbillwang** [terraform-aws-modules/terraform-aws-eks#64]
# I have issues

I have difficulty to troubleshooting EKS nodes issue, for example, `OutOfDisk` issue. I go to cloudwatch, there is no any instance logs or /var/log/message logs.
 
> OutOfDisk        Unknown   Fri, 13 Jul 2018 00:11:01 +0000   Fri, 13 Jul 2018 00:11:43 +0000   NodeStatusUnknown         Kubelet stopped posting node status.

Currently there is no key pair set and I can't login the eks nodes to do further check.

## I'm submitting a...

* [X] feature request
* [X] support request

## What is the current behavior?

No any logs from EKS cluster.

## What's the expected behavior?

I need some ways to review the logs when something happened.

## Are you able to fix this problem and submit a PR? Link here if you have already.

not sure how to fix this issue, need help.

## Environment details

* Affected module version: v1.1.0
* OS: Ubuntu
* Terraform version: 0.11.7

**Comment by brandoconnor** [comment]
Hey @ozbillwang -

Bummer that you're running into issues. I don't know that this module is going to help you with that problem specifically but I can give you a little guidance.

I see the core issue is the images you're running. This module does what it can to give you access to hosts, as `keypair` is offered as a variable of each worker ASG, so you have a mechanism for access. You can install and configure the cloudwatch logs agent either in userdata or within an image building proces outside of terraform entirely (recommended).

If this is a common enough ask or if someone wants to take on the work, I would consider adding a variable flag to install, configure and enable the cloudwatch logs agent on each host. Overall, it's not the best pattern (would rather bake this and other primitives into an image) but I can see people potentially wanting this experience out of the box.

**Comment by ozbillwang** [comment]
sure, I just found it [key_name](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/75f6f1e4ef3b76e1f4f20f7635dede866960c286/workers.tf#L30) 

For logs, seems I need deal it with myself, for example, build a new AMI from the exist EKS ami. Let me think about it.  Thanks alot.
