### ISSUE TITLE
Managed Node Groups do not support ami_type without specifying it on every element of node_groups

### ISSUE THREAD

**Issue by andres-de-castro** [terraform-aws-modules/terraform-aws-eks#640]
# I have issues

## I'm submitting a...

* [X ] bug report

## What is the current behavior?

Does not support variable ami_types without defining ami_type in every sub node group

## If this is a bug, how to reproduce? Please include a code sample if relevant.

`  node_groups = [
    {
      name = "cpu-node-group"

      node_group_desired_capacity = 2
      node_group_max_capacity     = 4
      node_group_min_capacity     = 1

      instance_type = "c5.2xlarge"
      disk_size     = 250
      node_group_k8s_labels = {
        node-group   = "cpu-node-group"
        Cluster_Name = local.cluster_name
      }
      remote_access = {
        ec2_ssh_key               = aws_key_pair.all_nodes_key_pair.key_name
        source_security_group_ids = [aws_security_group.office.id]
      }
    },
    {
      name                        = "gpu-node-group"
      node_group_desired_capacity = 2
      node_group_max_capacity     = 4
      node_group_min_capacity     = 1

      instance_type = "g4dn.xlarge"
      ami_type      = "AL2_x86_64_GPU"
      disk_size     = 250
      node_group_k8s_labels = {
        node-group   = "gpu-node-group"
        Cluster_Name = local.cluster_name
      }
      remote_access = {
        ec2_ssh_key               = aws_key_pair.all_nodes_key_pair.key_name
        source_security_group_ids = [aws_security_group.office.id]
      }
    }
  ]`

## What's the expected behavior?

Should create a node group with ami_type GPU and one non (default)

## Environment details

* Affected module version:
* OS: Darwin Catalina, latest
* Terraform version: terraform cloud 0.12.8

**Comment by dpiddockcmp** [comment]
Input data structure for node groups was changed in #650 and released in v8.0.0. There's now a `node_groups_defaults` variable that sets common options for all node groups.
