### ISSUE TITLE
Managed node group limits to 1 instance type (TF resource allows multiple)

### ISSUE THREAD

**Issue by TBeijen** [terraform-aws-modules/terraform-aws-eks#642]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

The new managed node groups addition only allows specifying a single instance type, whereas 
the underlying terraform resource [accepts a list of instance types](https://www.terraform.io/docs/providers/aws/r/eks_node_group.html#instance_types) so this seems needlessly limiting and inconsistent.

## Are you able to fix this problem and submit a PR? Link here if you have already.

My suggestion is to replace this:
```
instance_types  = [lookup(each.value, "instance_type", null)]
```
with:
```
instance_types  = lookup(each.value, "instance_types", [])
```

This changes the expected key in `node_groups` but as that isn't released yet that seems acceptable. 

I'll add a PR shortly.

## Any other relevant info

Originally reported in #620

**Comment by TBeijen** [comment]
Gave it a try. Ran into TF errors resulting in: https://github.com/terraform-providers/terraform-provider-aws/issues/11414

(Reading back on #602 I surprisingly can't find any mention of the `instance_type`/`instance_types` discrepancy. All in all, with also some quirks in the provider, managed nodes atm feels like a minefield with a lot of trial-and-error. Besides the examples already present I plan to add a `/docs/managed_nodes.md` page in #644)

**Comment by dpiddockcmp** [comment]
This is a fairly typical trick from Terraform AWS documentation. If you write it vague then you won't be out of date when AWS moves the goal posts 😄 . Highly frustrating from a user point of view where you often have to guess if the provider wants a list or string.

The [upstream API](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html#AmazonEKS-CreateNodegroup-request-instanceTypes) takes a list and specifies in the documentation that currently only a single option is supported. Which explains the provider's choice.

Although the provider does enforce the [max 1 item](https://github.com/terraform-providers/terraform-provider-aws/blob/71a088de6f70e1caa2f8f6da877514059f979c42/aws/resource_aws_eks_node_group.go#L68) 🤷‍♂ 

Short term usability would support going with the singular. No telling how long it will take before AWS supports multiple, or even how that would look.
