### ISSUE TITLE
ConfigMap connection refused

### ISSUE THREAD

**Issue by a7i** [terraform-aws-modules/terraform-aws-eks#645]
# I have issues creating a new EKS cluster using `master` as ref.

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
When creating a cluster, I get the following error:
`Error: Post http://localhost/api/v1/namespaces/kube-system/configmaps: dial tcp 127.0.0.1:80: connect: connection refused`

As of 2 days ago, I was able to create clusters successfully so this is a new regression.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
```
module eks {
  source = "github.com/terraform-aws-modules/terraform-aws-eks?ref=master"
  cluster_name    = local.name
  cluster_version = var.eks_config.cluster_version
  subnets         = module.vpc.private_subnets
  vpc_id          = module.vpc.vpc_id

  cluster_endpoint_private_access = true
  write_kubeconfig = false

  node_groups = [
    for wg in var.eks_config.node_groups : {
      name                          = wg.name
      instance_type                 = wg.instance_type
      ami_id                        = data.aws_ami.eks_worker.id
      node_group_desired_capacity   = wg["desired_capacity"]
      node_group_max_capacity       = wg["max_capacity"]
      node_group_min_capacity       = wg["min_capacity"]
      additional_security_group_ids = join(",", [aws_security_group.eks_wg.id, aws_security_group.aurora.id])

      node_group_k8s_labels = {
        "instance-family" = substr(wg.instance_type, 0, 2)
      }

      tags = merge(
        var.tags,
        {
          "k8s.io/cluster-autoscaler/${local.name}" = true
          "Visibility"                              = "private"
        },
      )
    }
  ]
}
```

## What's the expected behavior?
To be able to create a cluster successfully without errors. I have both private and public endpoint enabled.

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by a7i** [comment]
Issue was with my networking configuration.

**Comment by sumowrestler** [comment]
@a7i I'm also seeing this error, what specific settings were causing this. I.e. my cluster is created successfully then this error occurs after the fact.

**Comment by jmorgan415** [comment]
@a71 Yes, please answer with something more verbose.  I too am seeing this issue.

**Comment by a7i** [comment]
Hi @jmorgan415 

I was running my build inside of a Docker container and it required using **Host Networking**

In my case, I am using docker-compose, so this would be the syntax below (docker-compose.yaml):
```
version: "3.7"

services:
  iac:
    network_mode: host
    build:
      context: .
    environment:
      TF_IN_AUTOMATION: ${TF_IN_AUTOMATION}
      ENVIRONMENT:
      AWS_DEFAULT_REGION:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
```

Notice `network_mode: host`

**Comment by bcouetil** [comment]
Same problem here, but I'm not inside a container. Don't know what to do...

**Comment by bcouetil** [comment]
Solved. My problem : I used an old `main.tf` of mine, before the needs to declare the Kubernetes provider (see README).

#659 helped me, thanks.

**Comment by sahotay** [comment]
I came across the same issue, the problem was I didn't define ```provider "kubernetes" {``` in my main.yml.

Before:
```
module "eks" {
  source                        = "terraform-aws-modules/eks/aws"
  version                       = "12.0.0"
  cluster_name             = "minuscule"
  subnets                      = module.vpc.public_subnets
  vpc_id                         = module.vpc.vpc_id
  worker_groups_launch_template = [
    {
      name                             = "worker-group-1"
      instance_type              = "t3.small"
      asg_desired_capacity = 2
      public_ip                      = true
    }
  ]
}
```

To solve this issue:-
```
data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "~> 1.11"
}

module "eks" {
  source                        = "terraform-aws-modules/eks/aws"
  version                       = "12.0.0"
  cluster_name             = "minuscule"
  subnets                      = module.vpc.public_subnets
  vpc_id                         = module.vpc.vpc_id
  worker_groups_launch_template = [
    {
      name                            = "worker-group-1"
      instance_type              = "t3.small"
      asg_desired_capacity = 2
      public_ip                      = true
    }
  ]
}

```

I would suggest seeing an example here as this may change with new TF version (https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples)
