### ISSUE TITLE
config_map_aws_auth file is created on every terraform apply

### ISSUE THREAD

**Issue by rajalokan** [terraform-aws-modules/terraform-aws-eks#646]
# I have issues
Getting new config_map_aws_auth file created everytime I run `terraform apply`
## I'm submitting a...

[X] bug report
 
## What is the current behavior?
Shows up as new resource for every run.

## What's the expected behavior?
Since resource is already created, this shouldn't be created everytime.

## Are you able to fix this problem and submit a PR? Link here if you have already.
Not sure. But believe this is because of terraform `cloud` instance. I'm running my code in terraform cloud and I think subsequent runtime is different. This leads to creating the resource every time. I feel there should be a way to resolve this in terraform cloud. 

## Environment details

* Affected module version: 7.0.1
* OS:  Linux
* Terraform version: 0.12.16

**Comment by manpreetsnehra** [comment]
Probably becuase aws-auth is implemented currently using local-exec which is not really a stateful way of keeping that info. so its just implemented everytime.

**Comment by barryib** [comment]
We are now using the kubernetes provider to manage the `aws-auth` configmap, which is stateful. Upgrade to `v8.0.0`.
