### ISSUE TITLE
Add support for Public IP Access Whitelist

### ISSUE THREAD

**Issue by troyfontaine** [terraform-aws-modules/terraform-aws-eks#647]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

The feature isn't supported yet.  I'm not able to use Terraform to add CIDRs to the whitelist on the public-facing EKS Endpoint via terraform-aws-eks.  See [here](https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html#w242aac13c21c17b9b3) for the latest update to this feature on AWS.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Functionality is not supported.

## What's the expected behavior?

That terraform-aws-eks would allow me to specify CIDRs to allow access to the public-facing EKS Endpoint.

## Are you able to fix this problem and submit a PR? Link here if you have already.

Sorry, I'm not able to fix this myself.

## Environment details

* Affected module version: 
* OS:
* Terraform version:

**Comment by dpiddockcmp** [comment]
This is totally blocked on the AWS provider having support for the new [publicAccessCidrs](https://docs.aws.amazon.com/eks/latest/APIReference/API_VpcConfigRequest.html#AmazonEKS-Type-VpcConfigRequest-publicAccessCidrs) API option. 

An issue has been raised for this: https://github.com/terraform-providers/terraform-provider-aws/issues/11397

**Comment by andjelx** [comment]
Seems a new AWS Provider supporting publicAccessCidrs (v2.44.0) will be released tomorrow 👍

**Comment by sidprak** [comment]
I opened a PR for this: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/673. This is my first time opening a PR in this repo. What's the process for getting it reviewed?

**Comment by barryib** [comment]
Resolved by #673

**Comment by andjelx** [comment]
Dear @barryib @max-rocket-internet @brandonjbjelland @dpiddockcmp is it possible to include this functionality in the next minor release .e.g. 8.0.1?
If so when we can expect such - this feature is very interesting for us.
