### ISSUE TITLE
Variable create_eks is missing in releases

### ISSUE THREAD

**Issue by wilkej** [terraform-aws-modules/terraform-aws-eks#648]
# I have issues
using the variable create_eks 
## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Loading the different versions of the module, tested version 6 and 7 the create_eks variable is not available

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```
module "eks" {
 source  = "terraform-aws-modules/eks/aws"
 version = "7.0.1"
...
}
```

and get the error 

```
Error: Unsupported argument

  on xxx.tf line 182, in module "eks":
 182:   create_eks = false

An argument named "create_eks" is not expected here.
```

## What's the expected behavior?

The argument is supported, as it is available in the master branch

## Are you able to fix this problem and submit a PR? Link here if you have already.

If I do, the following it works. However I don't like to pin the module to master

```
module "eks" {
  source = "git::https://github.com/terraform-aws-modules/terraform-aws-eks.git?ref=master"
  ...
}

```
## Environment details

* Affected module version: 7.0.1
* OS:
* Terraform version: Terraform v0.12.18

**Comment by max-rocket-internet** [comment]
That's because there is no release with that change included: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/CHANGELOG.md#v8---2019--

**Comment by max-rocket-internet** [comment]
It will be included in the next release once we move managed node groups out of the core module and decide whether to keep the Kubernetes provider 🙂
