### ISSUE TITLE
eks cluster instance missing tags when deploying with tf011

### ISSUE THREAD

**Issue by luisamador** [terraform-aws-modules/terraform-aws-eks#654]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
The EKS cluster instances created via the 0.11 branch of this module are not being tagged.

## What's the expected behavior?

Add tags to the eks cluster instances deployed by the 0.11 branch of this module.

The `tags` attribute is missing here:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/tf0.11/cluster.tf#L1

* Affected module version: latest
* Terraform version: 0.11

**Comment by max-rocket-internet** [comment]
Sorry but we don't support TF 0.11 any more.

**Comment by luisamador** [comment]
Ah right I see, thanks for letting me know. It would be nice to add a comment to the README.me file to make clear that Terraform 0.12 is a requirement and that Terraform 0.11 is not supported anymore.

**Comment by max-rocket-internet** [comment]
It's in here, which is pretty standard for TF modules: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/versions.tf#L2

But feel free to make a PR for the main readme 🙂

**Comment by luisamador** [comment]
only the master branch has the version.tf file, it's missing from the `tf0.11` branch, I'll do a PR for the main readme.
