### ISSUE TITLE
Support for editable role trust relationships 

### ISSUE THREAD

**Issue by bee-keeper** [terraform-aws-modules/terraform-aws-eks#655]
# I have issues

## I'm submitting a...

* [Y ] feature request

## What is the current behavior?
workers_assume_role_policy [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/data.tf#L20) is hardcoded to ec2.amazonaws.com and I may want to use other services. 

## What's the expected behavior?
I'd like to add whichever services I want here

## Are you able to fix this problem and submit a PR? Link here if you have already.
Yes, but want to check that you think this makes sense first.

Great module btw, definitely makes working with EKS a LOT easier!

**Comment by max-rocket-internet** [comment]
I'm curious why you would want to assume an EKS worker node policy from somewhere other than EC2? Is that so you can have physical workers or something?

**Comment by bee-keeper** [comment]
Hi there and yes.  But actually thinking about this I suppose it makes more sense to just create my own role and pass that in instead?

**Comment by max-rocket-internet** [comment]
> But actually thinking about this I suppose it makes more sense to just create my own role and pass that in instead?

Yes, exactly 🙂

**Comment by bee-keeper** [comment]
I'm closing the issue in this case.  Thanks
