### ISSUE TITLE
terraform apply works fine, but kubectl get nodes says "No resources found.

### ISSUE THREAD

**Issue by AmitThakkar** [terraform-aws-modules/terraform-aws-eks#669]
# I have issues
I am using the main.tf file https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/spot_instances/main.tf with some environment-specific changes. When I do  `terraform apply` works fine, but when I do  `kubectl get nodes` says  **No resources found.**

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
```
kubectl get nodes
No resources found.
```

```
kubectl get po --all-namespaces
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
amit          amit-nginx                 0/1     Pending   0          15h
kube-system   coredns-5b5455fd88-k2mhb   0/1     Pending   0          15h
kube-system   coredns-5b5455fd88-n25g6   0/1     Pending   0          15h
```

When I login in AWS Console, it show EC2 instances Running

## Environment details

* Affected module version:
* OS: MAC
* Terraform version:
Terraform v0.12.18
+ provider.aws v2.43.0
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

**Comment by max-rocket-internet** [comment]
HI @AmitThakkar !
Please be sure to check the FAQ as this issue comes up a lot: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#why-are-nodes-not-being-registered

**Comment by AmitThakkar** [comment]
@max-rocket-internet Thanks :) 
It was because of the DNS issue in our VPC.
