### ISSUE TITLE
Can not assign node group name

### ISSUE THREAD

**Issue by jinh574** [terraform-aws-modules/terraform-aws-eks#670]
# I have issues
I can't assign name on node groups.

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
There is no field to assign node group name

## What's the expected behavior?
When I put a name on 'name' field, it should assign node group name.

## Environment details

* Affected module version: 8.0.0
* OS: macOS
* Terraform version: 0.12.18

**Comment by barryib** [comment]
closing this issue. See https://github.com/terraform-aws-modules/terraform-aws-eks/pull/671#issuecomment-572639975 for info.
