### ISSUE TITLE
Sudden issues using 6.0.2 (file not found?)

### ISSUE THREAD

**Issue by slikk66** [terraform-aws-modules/terraform-aws-eks#674]
Suddenly today getting this error, on this module only, others are OK.. did something happen to the files?

````
Error: Failed to download module

Could not download module "cluster" (main.tf:37) source code from
"https://api.github.com/repos/terraform-aws-modules/terraform-aws-eks/tarball/v6.0.2//*?archive=tar.gz":
Error opening a gzip reader for /tmp/getter641506871/archive: EOF.

[terragrunt] 2020/01/10 00:04:40 Hit multiple errors:
exit status 1
````

**Comment by barryib** [comment]
Is this similar to https://github.com/terraform-aws-modules/terraform-aws-eks/issues/672 ?

Fixed with https://github.com/terraform-aws-modules/terraform-aws-eks/issues/672#issuecomment-572737912

**Comment by slikk66** [comment]
yes, looks like its same thing.. I'll close this. thank you
