### ISSUE TITLE
error retrieving community module

### ISSUE THREAD

**Issue by jonathancolby-olx** [terraform-aws-modules/terraform-aws-eks#677]
# I have issues retrieving the community module with terraform

Perhaps this is a temporary glitch, but several checks on different networks and terraform code bases all get this error when initializing the module.

If no one can confirm the same issue, i will close this issue and investigate more on my side.

```
Error: Failed to download module

Could not download module "eks" (cluster.tf:86) source code from
"https://api.github.com/repos/terraform-aws-modules/terraform-aws-eks/tarball/v7.0.1//*?archive=tar.gz":
Error opening a gzip reader for /tmp/getter983949058/archive: EOF.
```

```
Could not download module "eks" (cluster.tf:86) source code from
"https://api.github.com/repos/terraform-aws-modules/terraform-aws-eks/tarball/v8.0.0//*?archive=tar.gz":
Error opening a gzip reader for
/var/folders/26/n8ph__7573796vsw8qdbnjkh8tn2t1/T/getter987969210/archive: EOF.


Error: Failed to download module
```

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

see above

## If this is a bug, how to reproduce? Please include a code sample if relevant.

attempt a terraform plan/apply  for this module

```
module "eks" {
  source                          = "terraform-aws-modules/eks/aws"
  version                         = "v7.0.1"
  cluster_name                    = "foo-cluster"
...
}
```

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by dpiddockcmp** [comment]
4th time today for an issue that's caused by the broken Hashicorp infra 😅 

Only known solutions so far is are upgrade to Terraform 0.12.19 or directly reference the git repo:

`source = "github.com/terraform-aws-modules/terraform-aws-eks?ref=7.0.1"`

It sucks. There's nothing we can do. Hashicorp need to fix it. Keep an eye on https://github.com/hashicorp/terraform/issues/23829 and see what they say.

**Comment by jonathancolby-olx** [comment]
OK.  thanks for the quick feedback. I was looking for confirmation it wasn't my side.
