### ISSUE TITLE
Defined Desired Capacity is 1 but Created AutoScaling Group Desired Capacity is 2

### ISSUE THREAD

**Issue by AmitThakkar** [terraform-aws-modules/terraform-aws-eks#678]
# I have issues
Defined Desired Capacity is 1 but Created AutoScaling Group Desired Capacity is 2

## I'm submitting a...

* bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I am creating EKS Cluster with spot instances and defining the desired capacity to 1. But the resource has the desired capacity is 2 and two ec2 instances are running.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/spot_instances/main.tf#L81
Changed the desired capacity to 1 in the above line.

## What's the expected behavior?
Desired capacity should be 1.

**Comment by dpiddockcmp** [comment]
Desired capacity cannot be modified by Terraform after creation of the resources. This is a "feature" of how Terraform works as we've set a lifecycle rule to not break the Cluster Autoscaler. Lifecycle rules can only be hardcoded currently.

You will need to directly modify existing ASGs via the AWS console or CLI tool.

**Comment by AmitThakkar** [comment]
I creating a new resource after deleting the old one. Still getting the same.

**Comment by dpiddockcmp** [comment]
I just modified examples/spot_instances_main.tf to set `asg_desired_capacity = 1` and ran a plan on an empty state:
```hcl
  # module.eks.aws_autoscaling_group.workers_launch_template[0] will be created
  + resource "aws_autoscaling_group" "workers_launch_template" {
      + arn                       = (known after apply)
      + availability_zones        = (known after apply)
      + default_cooldown          = (known after apply)
      + desired_capacity          = 1
```

How are you deleting the resource? You may have to remove it from the terraform state file and not just AWS for the change to be picked up: `terraform state rm module.eks.aws_autoscaling_group.workers_launch_template[0]`

**Comment by AmitThakkar** [comment]
I deleted terraform state as well, but same error. I run from a different folder and It worked. Seems some terraform cache gotcha.
