### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by maganuk** [terraform-aws-modules/terraform-aws-eks#680]
Hi,

I saw that there was a PR added for Windows Compatibility, however in cluster.tf even this line should have the ability to specify a custom interpretor

    provisioner "local-exec" {
        command = <<EOT
        until curl -k -s ${aws_eks_cluster.this[0].endpoint}/healthz >/dev/null; do sleep 4; done
      EOT
    }

Without that, its not possible to create a cluster

**Comment by barryib** [comment]
@maganuk Thanks for opening this issue. There was a long discussion about this on https://github.com/terraform-aws-modules/terraform-aws-eks/pull/639 and called for help to windows users to help is test this.

Could you please take a time on this issue and open a PR to fix this ? I can help you with this.

Do you have a working curl (or equivalent) command on Windows to do a HTTP GET on the healthz endpoint ?

**Comment by maganuk** [comment]
I need a day or two to figure this out. Curl is not installed by default on Windows and it would be odd to require the user to install any third party packages. Lets try and figure out if we can do this using terraform. Usually the delay will not be more that 8-10 seconds. Can we not delay the execution of the next step by a few seconds, instead of pinging the url to see if its alive?

**Comment by barryib** [comment]
Actually, there is `Invoke-RestMethod` in powershell https://discoposse.com/2012/06/30/powershell-invoke-restmethod-putting-the-curl-in-your-shell/. Maybe we can use that ?

> Usually the delay will not be more that 8-10 seconds.

I think we don't really know how long it'll take. So I'll really prefer pinging until it's alive rather than waiting and hoping that it'll take less than 10 seconds.

**Comment by sanjeevgiri** [comment]
I have a potential fix for this, however I am not able to create a branch for pull request. Is there anyway something I need to do to be able to create a branch?

**Comment by dpiddockcmp** [comment]
@sanjeevgiri 
> I have a potential fix for this, however I am not able to create a branch for pull request. Is there anyway something I need to do to be able to create a branch?

You need to Fork the repo to your own account using the buttons in the github interface, push your changes there and then open a PR. See [github's docs](https://guides.github.com/activities/forking/) for the full details

**Comment by barryib** [comment]
Closing this as the wait command is now configurable.

**Comment by avoidik** [comment]
wouldn't it be better to make `interpreter` item configurable?
