### ISSUE TITLE
Instances failed to join the kubernetes cluster

### ISSUE THREAD

**Issue by guruprasadk8** [terraform-aws-modules/terraform-aws-eks#682]
Instances failed to join the kubernetes cluster

## I'm submitting a...

* [*] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Instances failed to join the kubernetes cluster	
## If this is a bug, how to reproduce? Please include a code sample if relevant.
Create 2 account, From management account created EKS cluster in Non Prod. 
used 2 provides:
https://www.terraform.io/docs/providers/aws/r/eks_cluster.html
https://www.terraform.io/docs/providers/aws/r/eks_node_group.html
## What's the expected behavior?
Created cluser and worker node. but worker node not able to attach the cluster. 
## Environment details
Production
* Affected module version: 1.14 
* OS: RHEL
* Terraform version: 1.14

## Any other relevant info
using proxy
![image](https://user-images.githubusercontent.com/59863341/72324814-e719a780-36ff-11ea-909b-7cf0bcea2664.png)

**Comment by max-rocket-internet** [comment]
![Screen Shot 2020-01-14 at 09 47 26](https://user-images.githubusercontent.com/8859277/72328266-e6a6ef80-36b2-11ea-942f-29fa3b51ecbf.png) 👀

**Comment by dpiddockcmp** [comment]
Are you even using this Terraform module or just looking for generic AWS EKS help?

**Comment by guruprasadk8** [comment]
Problem fixed.
For proxy setup we have to enable ecr endpoint. i have added dkr and api ecr endpoint.

**Comment by bitgandtter** [comment]
@guruprasadk8 can you please elaborate on the fix/solution? I'm facing the same issue. Thanks in advance

**Comment by vishnu123sai** [comment]
Can you please explain this

**Comment by adruzenko** [comment]
I faced the same issue. It was caused by restricting an access to Amazon EKS public API server endpoint with **cluster_endpoint_public_access_cidrs** option. I resolved the issue by enabling EKS private API server endpoint with   **cluster_endpoint_private_access  = true**
