### ISSUE TITLE
Name of cluster in kubeconfig is prefixed with eks-

### ISSUE THREAD

**Issue by AmitThakkar** [terraform-aws-modules/terraform-aws-eks#684]
# I have issues
Name of cluster in kubeconfig is prefixed with **eks-**

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Name of cluster in kubeconfig is prefixed with **eks-**. Lets say if cluster name is ABC then kubeconfig will have eks-ABC under the name in the cluster.

**Comment by max-rocket-internet** [comment]
This was a originally convention copied from GKE. They do the same there with `gke-`. Feel free to make a PR to change.
