### ISSUE TITLE
Support the Amazon EBS CSI Driver Storage Class

### ISSUE THREAD

**Issue by jmpsf** [terraform-aws-modules/terraform-aws-eks#685]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

AWS states in it's [docs](https://docs.aws.amazon.com/eks/latest/userguide/storage-classes.html)

>  For Kubernetes 1.14 and above clusters, the Amazon EBS CSI Driver is available for managing storage. The existing in-tree Amazon EBS plugin is still supported, but by using a CSI driver, you benefit from the decoupling of Kubernetes upstream release cycle and CSI driver release cycle. Eventually, the in-tree plugin will be deprecated in favor of the CSI driver.

But, as far as I've seen from the readme and examples, the terraform module doesn't support it. 

## What's the expected behavior?

The module could have a boolean variable to enable this driver storage. 

From the [docs](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) we would only need to add the following policy (most of the permissions are already present).

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ec2:AttachVolume",
        "ec2:CreateSnapshot",
        "ec2:CreateTags",
        "ec2:CreateVolume",
        "ec2:DeleteSnapshot",
        "ec2:DeleteTags",
        "ec2:DeleteVolume",
        "ec2:DescribeInstances",
        "ec2:DescribeSnapshots",
        "ec2:DescribeTags",
        "ec2:DescribeVolumes",
        "ec2:DetachVolume"
      ],
      "Resource": "*"
    }
  ]
}
```

## Are you able to fix this problem and submit a PR? Link here if you have already.

I can make a PR to create and attach the policy if the user sets `use_ebs_csi_driver` if you agree to.

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by max-rocket-internet** [comment]
Those permissions are already present in `arn:aws:iam::aws:policy/AmazonEKSClusterPolicy`?

**Comment by jmpsf** [comment]
Ok, I only saw the node policy, sorry

**Comment by max-rocket-internet** [comment]
No worries. To be clear, it's the EKS service that is requesting and attaching storage, not the nodes themselves.

**Comment by PaulHatch** [comment]
@max-rocket-internet, AmazonEKSClusterPolicy seems to be missing snapshot permissions from that list though, specifically CreateSnapshot, DeleteSnapshot, and DescribeSnapshots as well as DeleteTags and DescribeTags.

**Comment by GerardoGR** [comment]
According to Amazon's CSI driver [docs](https://aws.amazon.com/premiumsupport/knowledge-center/eks-persistent-storage/), the policy with the permissions should be applied to the workers. Because this is not the case currently with the module, I think this ticket is still valid.
