### ISSUE TITLE
Unable to define additonal EBS volumes for the launch templates

### ISSUE THREAD

**Issue by josh-stableprice** [terraform-aws-modules/terraform-aws-eks#687]
# I have issues attaching an additional EBS volume to my launch templates for use in cluster wide storage.

I want to have a minimally sized root storage volume with a larger attached EBS volume, which is used via Rook/Ceph 

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I attempt to specify additional volumes under worker_groups_launch_template as per the documentation for aws_launch_template resource, however I get told that this isn't possible

## If this is a bug, how to reproduce? Please include a code sample if relevant.
```
module "eks" {
  source = "terraform-aws-modules/eks/aws"
  version = "7.0.1"

  cluster_name = var.cluster_name
  subnets = var.private_subnet_ids

  tags = {
    Environment = var.environment
    GithubRepo = "terraform-aws-eks"
    GithubOrg = "terraform-aws-modules"
  }

  vpc_id = var.vpc_id

  worker_groups_launch_template = [
    {
      name = "spot-1"
      override_instance_types = var.instance_types
      spot_instance_pools = length(var.instance_types)
      asg_max_size = 10
      asg_desired_capacity = 5
      autoscaling_enabled = true
      kubelet_extra_args = "--node-labels=kubernetes.io/lifecycle=spot"
      public_ip = true
      eni_delete = true
      volumes = [{
        device_name = "/dev/sdb"
        volume_size = 2000
        encrypted = true
      }]
    },

    {
      name = "on-demand-1"
      instance_type = "t3.medium"
      asg_max_size = 10
      asg_min_size = 0
      asg_desired_capacity = 0
      autoscaling_enabled = true
      kubelet_extra_args = "--node-labels=spot=false"
      public_ip = true
      eni_delete = true
      volumes = [{
        device_name = "/dev/sdb"
        volume_size = 2000
        encrypted = true
      }]
    }
  ]
}
```

## What's the expected behavior?
I'm able to pass in a volume definition of the same or similar form as the definition on aws_launch_template resource and I end up with an ASG with EBS volumes created and attached.

## Environment details

* Affected module version: 7.0.1
* OS: Linux
* Terraform version: 0.12.19

**Comment by josh-stableprice** [comment]
Added a code sample to show what I'd guess the config for this would be

**Comment by jaimehrubiks** [comment]
Also very interested

**Comment by barryib** [comment]
This is now implemented in https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v11.0.0.
