### ISSUE TITLE
Attach AWS Managed Policy To Worker Nodes IAM Role

### ISSUE THREAD

**Issue by AmitThakkar** [terraform-aws-modules/terraform-aws-eks#692]
# I have issues
No option to defined the Managed Policy(e.g. CloudWatchAgentServerPolicy) to Worker Nodes IAM Role.

## I'm submitting a...
* [ ] bug report
* [ ] feature request
* support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Right now, I can't find a way to define manage policies, to attach worker nodes role.

**Comment by max-rocket-internet** [comment]
You can just attach a role like this:

```
resource "aws_iam_policy_attachment" "my_policy" {
  name       = "eks_my_policy"
  roles      = [module.my_cluster.worker_iam_role_name]
  policy_arn = aws_iam_policy.my_policy.arn
}
```

**Comment by AmitThakkar** [comment]
@max-rocket-internet Thank you very much for your quick help.
