### ISSUE TITLE
EKS on Fargate: alb ingress controller not getting address

### ISSUE THREAD

**Issue by farooqte96** [terraform-aws-modules/terraform-aws-eks#694]
I created an alb ingress controller on EKS on Fargate. when i run a sample 2048 application, i am not getting ingress address field 

kubectl get ingress 2048-ingress -n kube-system
NAME           HOSTS   ADDRESS   PORTS   AGE
2048-ingress   *                 80      11m

and logs of ingress report following errors as shown:

E0117 13:09:12.698641       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to get AWS tags. Error: WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: dial tcp: i/o timeout"  "controller"="alb-ingress-controller" "request"={"Namespace":"kube-system","Name":"2048-ingress"}

I have used aws_open_id_connect provider for my eks cluster, so does someone see the issue why i am getting these errors and how can i get a ingress url attached to my service.

BR

**Comment by srinisdevops** [comment]
I am facing the same issue where Ingress address is not populated. I have used VPC module as well as AWS providers to create the VPC for my EKS cluster. During Ingress deployment, I will get time out error. When I apply the coreDNS patch using the [workaround](https://github.com/hashicorp/terraform-provider-aws/issues/11327) the pods run properly but not getting ingress address. Can you please let me know what is going on? I have come across the same exact issue here but I don't see any suggestions here.
