### ISSUE TITLE
Is autoscaling enabled automatically with managed node groups ?

### ISSUE THREAD

**Issue by ficofer** [terraform-aws-modules/terraform-aws-eks#697]
# I have issues with autoscaling setup with version 8.0.0 using managed node groups.

* [X] support request

Following https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/autoscaling.md

I have used the new release configuring the set up like the following:

```
module "eks-cluster" {
  ...
  node_groups = [
    {
      name          = var.eks_node_group_name
      instance_type = var.eks_pool_instance_type

      node_group_desired_capacity = var.eks_cluster_min_size
      node_group_max_capacity     = var.eks_cluster_max_size
      node_group_min_capacity     = var.eks_cluster_min_size
      disk_size                   = var.eks_disk_size

      node_group_k8s_labels = {
        Environment = var.environment
        Terraform   = "true"
        Cluster     = var.eks_cluster_name
      }
    }
  ]

  tags = {
    Terraform   = "true"
    Cluster     = var.eks_cluster_name
    Environment = var.environment
  }

  map_users     = var.tf_admins
  
}
```

I see that this generates a node group with an ASG related to it:

```
Autoscaling group name
eks-234135135-c037-cd4c-7416-3241f43f43
```

My question is I should only install the helm chart `stable/cluster-autoscaler` and I will be good to go ? What would be a good test scenario to see if autoscaling is working ?

Thanks a lot for the support.

**Comment by dpiddockcmp** [comment]
Hi,

The code snippet you've posted is not compatible with the 8.0.0 release, it looks like master branch before #650 was merged.

I'd recommend that you use 8.1.0 if you want to enable node group autoscaling. It contains a vital fix for node group autoscaling.

For managed node groups you just need to install the cluster autoscaler per the instructions. Then create more pods than your existing worker nodes can support.

**Comment by 0verc1ocker** [comment]
I have been working with release 8.1.0 and the required AWS tags and iam policies are at the right places for the cluster-autoscaler to work just when using the nodegroup_defaults (not required) and node_group fields in the module.

Checklist for the cluster-autoscaler with node-groups:
- [ ] Make sure that the AWS tags exists in the subnets and the ASG for the nodegroup is also tagged with `k8s.io/cluster-autoscaler/enabled | true` and `k8s.io/cluster-autoscaler/{cluster_name} | owned`.


- [ ] Verify that the module has created a autoscaler IAM policy (ASG lookup and configure permissions) and attached it to the eks nodegroup IAM role in AWS
