### ISSUE TITLE
Error running command to update_config_map_aws_auth

### ISSUE THREAD

**Issue by dperic123** [terraform-aws-modules/terraform-aws-eks#70]
# I have issues
Please Help! I ran everything with defaults other then setting the VPC and Subnet

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [X ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I get this error running the Terraform apply
Error: Error applying plan:

1 error(s) occurred:

* null_resource.update_config_map_aws_auth: Error running command 'kubectl apply -f .//config-map-aws-auth_EKSClusterTest.yaml --kubeconfig .//kubec
onfig_EKSClusterTest': exit status 1. Output: Unable to connect to the server: getting token: exec: exec: "aws-iam-authenticator": executable file n
ot found in %PATH%

## What's the expected behavior?
Set the config on the instance

## Are you able to fix this problem and submit a PR? Link here if you have already.
No can I please have help?
## Environment details

* Affected module version:
* OS:
* Terraform version:

## Any other relevant info
First time setting this up!

**Comment by brandoconnor** [comment]
Hey @dperic123 -

This is exactly what I tried to fix before releasing the latest version and should work there. Can you try using the latest version of the module (`1.3.0`) and see if this still happens?

@ozbillwang - this is the exact problem I saw and solved that we discussed elsewhere. Im unsure when it was introduced as a problem but likely between 1.1.0 and 1.2.x

**Comment by ozbillwang** [comment]
@brandoconnor 

That's not the problem. The error is about the naming of `aws-iam-authenticator`, it used to be called `heptio-authenticator-aws`.

So just copy it and rename to `aws-iam-authenticator` and put it in /usr/bin or /usr/local/bin, this problem should be fixed.

**Comment by dperic123** [comment]
Let me test. I'm using a windows jump box and set it in the environment variables.

**Comment by dperic123** [comment]
Looks like the error I get now is:
* null_resource.update_config_map_aws_auth: Error running command 'kubectl apply -f .//config-map-aws-auth_EKSClusterTes
t.yaml --kubeconfig .//kubeconfig_EKSClusterTest': exit status 1. Output: error: You must be logged in to the server (th
e server has asked for the client to provide credentials)

**Comment by brandoconnor** [comment]
Sorry, @ozbillwang  I misread the error but it presents a similar error to the path issue I saw.

@dperic123 - I can't say I've tried this on Windows yet aside from Linux within Windows (WSL). Your AWS credentials should be assumed from your shell that ran terraform and any other authentication bits should be contained in the config file there.

**Comment by dperic123** [comment]
Hey so I got it working! Now how do I connect to the actual EKS cluster to set up the dashboard? 
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by brandoconnor** [comment]
@dperic123 - It's difficult to help when I can't see what your code looks like and I don't know what you tried when troubleshooting. This module aims to get you to the point where a worker cluster is live and connected to a live EKS control plane with any configuration needed to communicate to that cluster local. It sounds like you've reached this point but you're struggling to get further in connecting to the dashboard service.

AWS has [good docs](https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html) on how to get you this far. By your description, it sounds like you don't have the dashboard proxy up. Read up on that link and comment back (with code samples and what was tried) if you've gone through those docs and still see trouble. I'm sure you can make it go! 💨
