### ISSUE TITLE
tags seems to be ignored by "aws_eks_node_group" resource

### ISSUE THREAD

**Issue by swapzero** [terraform-aws-modules/terraform-aws-eks#700]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

tags added through `additional_tags` do not seem to be set

## If this is a bug, how to reproduce? Please include a code sample if relevant.

just set this in the nodegroup definition:
```
additional_tags = {
  TestTag = "blah"
}
```
terraform apply will show that `tags` property of `aws_eks_node_group` resource will be set to {TestTag = "blah"} but it is not listed in the node groups "Tags" tab.

## What's the expected behavior?
Tags should be set and yet it does not appear to be a bug in this module. 
Do you have any idea of what might be happening?

## Environment details

* Affected module version: 8.0.1
* OS: MacOS Mojave
* Terraform version:
```
terraform version
Terraform v0.12.19
+ provider.aws v2.45.0
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

**Comment by swapzero** [comment]
This is **NOT** an issue with the module, what I was expecting was to see the tags propagated to the underlying ASGs created by the node group...

**Comment by dpiddockcmp** [comment]
Yes, it has been requested in their roadmap https://github.com/aws/containers-roadmap/issues/608
