### ISSUE TITLE
IRSA is not fully configured for EKS workers. Unable to assume role due to missing permissions when managed by module

### ISSUE THREAD

**Issue by josh-stableprice** [terraform-aws-modules/terraform-aws-eks#702]
# I have issues
Trying to use IRSA with a module controlled worker assume_role policy. I am forced to use this to get alb-ingress-controller up and running however I get the following.
```
failed to build LoadBalancer configuration due to failed to get AWS tags. Error: WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
```
## I'm submitting a...

* [ X ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Worker assume role policy does not implement 'sts:AssumeRoleWithWebIdentity' as can be seen: https://www.terraform.io/docs/providers/aws/r/eks_cluster.html

## Are you able to fix this problem and submit a PR? Link here if you have already.
PR made in #702 

The source document would need to look similar to this.
```
data "aws_iam_policy_document" "example_assume_role_policy" {
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    effect  = "Allow"

    condition {
      test     = "StringEquals"
      variable = "${replace(aws_iam_openid_connect_provider.example.url, "https://", "")}:sub"
      values   = ["system:serviceaccount:kube-system:aws-node"]
    }

    principals {
      identifiers = ["${aws_iam_openid_connect_provider.example.arn}"]
      type        = "Federated"
    }
  }
}
```

## Environment details

* Affected module version: 8.1.0
* OS: Linux
* Terraform version: 0.12

**Comment by dpiddockcmp** [comment]
The worker node role is for the worker nodes to use, not a pod which needs a different set of permissions.

You need to create a new IAM role for the ALB service, with the correct set of permissions attached and then specify that in the service's `eks.amazonaws.com/role-arn` annotation.

Alternatively you could not use IRSA and let the ALB pod pick up the node's role.

**Comment by josh-stableprice** [comment]
Oh wow, I totally misunderstood how that worked. Sorry for wasting peoples time...
