### ISSUE TITLE
Manually deleted node group (AWS console) is not recreated by the module

### ISSUE THREAD

**Issue by swapzero** [terraform-aws-modules/terraform-aws-eks#704]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

node group is not recreated after **manually deleting** it from AWS console

**NOTE**: it works just fine for worker_groups (standard ASGs)

## If this is a bug, how to reproduce? Please include a code sample if relevant.

- use a config like the following for `node_groups`
  ```
  node_groups = {
    "ng-1a" = {
      "desired_capacity" = 1
      "instance_type"    = "t2.small"
      "name"             = "ng-1a"
      "subnets" = [
        module.vpc.public_subnets[0],
      ]
    }
    "ng-1b" = {
      "desired_capacity" = 1
      "instance_type"    = "t2.small"
      "name"             = "ng-1b"
      "subnets" = [
        module.vpc.public_subnets[1],
      ]
    }
    "ng-1c" = {
      "desired_capacity" = 1
      "instance_type"    = "t2.small"
      "name"             = "ng-1c"
      "subnets" = [
        module.vpc.public_subnets[2],
      ]
    }
  }
  ```
- go to **AWS console -> EC2 -> Auto Scaling Groups** and delete one managed node group (wait for it to be deleted)
- run `terraform plan`
  ```
  $ terraform plan
   ...
   module.eks.data.null_data_source.node_groups[0]: Refreshing state...
   module.eks.module.node_groups.random_pet.node_groups["ng-1b"]: Refreshing state... 
   [id=trusty-lab]
   module.eks.module.node_groups.random_pet.node_groups["ng-1c"]: Refreshing state... 
   [id=internal-rhino]
   module.eks.module.node_groups.random_pet.node_groups["ng-1a"]: Refreshing state... 
   [id=emerging-terrapin]
   module.eks.module.node_groups.aws_eks_node_group.workers["ng-1c"]: Refreshing state... 
   [id=bender:bender-ng-1c-internal-rhino]
   module.eks.module.node_groups.aws_eks_node_group.workers["ng-1a"]: Refreshing state... 
   [id=bender:bender-ng-1a-emerging-terrapin]
   module.eks.module.node_groups.aws_eks_node_group.workers["ng-1b"]: Refreshing state... 
   [id=bender:bender-ng-1b-trusty-lab]

   ------------------------------------------------------------------------

  No changes. Infrastructure is up-to-date.
  ```

## What's the expected behavior?
The missing node group should appear in `terraform plan` output as a resource to be created.

## Environment details

* Affected module version: 8.1.0
* OS: MacOS Mojave
* Terraform version:
```
Terraform v0.12.19
+ provider.aws v2.45.0
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

**Comment by dpiddockcmp** [comment]
This is probably an aws provider bug. We have no control over how the provider does refreshing of resources.

**Comment by swapzero** [comment]
Argh, what an oversight...apparently, deleting a "byproduct" of actual node group resource is silly and probably dangerous.
Yup, you're totally right, "one cannot simply delete the nodegroup asg"!
