### ISSUE TITLE
Error on EKS local-exec provisioning step

### ISSUE THREAD

**Issue by ThelonKarrde** [terraform-aws-modules/terraform-aws-eks#705]
# I have issues
The issue appears for some reason on the provisioning EKS cluster.

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Once I'm trying to make `terraform apply` it's starting to create an EKS cluster.
After some creating time, when cluster itself created and the process goes to local-exec modules, I got this error message:
```
module.staging-kubernetes-cluster.module.staging-kubernetes.aws_eks_cluster.this[0]: Still creating... [9m20s elapsed]
module.staging-kubernetes-cluster.module.staging-kubernetes.aws_eks_cluster.this[0]: Still creating... [9m30s elapsed]
module.staging-kubernetes-cluster.module.staging-kubernetes.aws_eks_cluster.this[0]: Still creating... [9m40s elapsed]
module.staging-kubernetes-cluster.module.staging-kubernetes.aws_eks_cluster.this[0]: Still creating... [9m50s elapsed]
module.staging-kubernetes-cluster.module.staging-kubernetes.aws_eks_cluster.this[0]: Still creating... [10m0s elapsed]
module.staging-kubernetes-cluster.module.staging-kubernetes.aws_eks_cluster.this[0]: Still creating... [10m10s elapsed]
module.staging-kubernetes-cluster.module.staging-kubernetes.aws_eks_cluster.this[0]: Provisioning with 'local-exec'...
module.staging-kubernetes-cluster.module.staging-kubernetes.aws_eks_cluster.this[0] (local-exec): Executing: ["/bin/sh" "-c" "    until curl -k -s https://A85E587C9B65E26FE562442111421A70.gr7.us-east-1.eks.amazonaws.com/healthz >/dev/null; do sleep 4; done\r\n"]
module.staging-kubernetes-cluster.module.staging-kubernetes.aws_eks_cluster.this[0] (local-exec): /bin/sh: -c: line 1: syntax error: unexpected end of file
```

If I'm trying to reproduce that command locally - it's passes without any errors.

The error came with `v8.x.x` version of the module when this string was added: [link](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/82aefb20f5dc1e4d195a3d19d6c091e1ed405932/cluster.tf#L37)

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Simply copied part of code from the documentation.
I've tried to launch `terraform apply` on `macOS Catalina 10.15.2`.
Terraform version is `v0.12.16`.
Tried `zsh` and `bash`.

```
module "staging-kubernetes" {
  source       = "terraform-aws-modules/eks/aws"
  cluster_name = var.eks_cluster_name
  subnets      = var.eks_private_subnets
  vpc_id       = var.eks_vpc_id
  version = "8.1.0"
  worker_groups_launch_template = [
    {
      name                          = "eks-cluster-worker-node"
      instance_type                 = var.eks_worker_instance_type
      asg_min_size                  = var.eks_worker_instance_min_number
      asg_max_size                  = var.eks_worker_instance_max_number
      asg_desired_capacity          = var.eks_worker_instance_desired_number
      root_volume_size              = var.eks_worker_instance_volume_size
      root_volume_type              = var.eks_worker_instance_volume_type
      public_ip                     = false
      additional_security_group_ids = var.eks_security_group_ids
      tags = [{
        key                 = "environment"
        value               = var.environment
        propagate_at_launch = true
        },
        {
          key                 = "region"
          value               = var.region
          propagate_at_launch = true
        },
        {
          key                 = "KubernetesCluster"
          value               = var.eks_cluster_name
          propagate_at_launch = true
        }
      ]
    }
  ]
  tags = {
    KubernetesCluster = var.eks_cluster_name
    environment       = var.environment
    region            = var.region
  }
}

```

## Environment details

* Module versions: `v8.x.x`
* OS: `macOS Catalina 10.15.2`
* Terraform version: `v0.12.16`

**Comment by kkapoor1987** [comment]
Looks like we need to have curl installed.

**Comment by ThelonKarrde** [comment]
`curl` is installed locally on system

**Comment by dpiddockcmp** [comment]
Was this code checked out on Windows? Or I guess `terraform init` done from Windows? I'm wondering where that `\r\n` at the end of the command came from which is the source of your error. 

I don't currently have access to a Windows environment to check if that's the problem.

**Comment by ThelonKarrde** [comment]
No, both terraform init and apply was done from `macOS 10.15.2`. Indeed it looks like CRLF line endings, but there is no reason for my system to add them to command.

**Comment by ThelonKarrde** [comment]
Okay, that's indeed an issue with local system.
Git autocrlf is enabled and somehow it's replacing all line endings on a fly.

I will close this issue.
