### ISSUE TITLE
EKS Cluster created without aws_auth config map

### ISSUE THREAD

**Issue by bensussman** [terraform-aws-modules/terraform-aws-eks#707]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
When I create an EKS cluster with `map_roles` specified, not only do the `map_roles` not correctly get propagated to the EKS cluster, but the eks cluster has no `aws_auth` config map at all!

## If this is a bug, how to reproduce? Please include a code sample if relevant.
I create an eks cluster using the following (where var.kubectl_users is a list of IAM users or in my case the account ID of the users i would like to be able to access the EKS cluster):

```
# EKS cluster for api and other services
resource "aws_iam_role" "kube_manager" {
  name = "Spell-Kube-Manager-${random_id.suffix.hex}"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": { "AWS": "${var.kubectl_users}" },
      "Effect": "Allow"
    }
  ]
}
EOF
}

module "eks" {
  source       = "terraform-aws-modules/eks/aws"
  cluster_name = local.eks_cluster_name
  subnets      = var.subnet_ids
  vpc_id       = var.vpc_id
  enable_irsa  = true

  cluster_enabled_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]

  map_roles = [
    {
      rolearn  = aws_iam_role.kube_manager.arn
      username = "manage-eks"
      groups   = ["system:masters"]
    },
  ]

  worker_groups = [
    {
      instance_type        = "m5.large"
      asg_max_size         = 9
      asg_min_size         = 9
      asg_desired_capacity = 9
      tags = [{
        key                 = local.eks_cluster_name
        value               = "true"
        propagate_at_launch = true
      }]
    }
  ]
  workers_additional_policies = [
    aws_iam_policy.write_s3.arn
  ]
}
```

## What's the expected behavior?
I expect to be able to see the aws_auth configmap populated with the mapped roles. However:
```
kubectl get cm aws-auth -n kube-system
Error from server (NotFound): configmaps "aws-auth" not found
```
I didn't think it was even possible for EKS clusters to have no aws_auth config map!

## Environment details

* Affected module version:
* OS: Mac OS 10.14.6
* Terraform version:
```
Terraform v0.12.17
+ provider.aws v2.45.0
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1
```

## Any other relevant info
This was working just a month ago. We rebuilt our EKS cluster today when trying to get OIDC / `enable_irsa = true` to work. However that didn't seem to work either! Because
```
$ aws eks describe-cluster --name Spell-eks --query "cluster.identity.oidc.issuer" --output text
None
```
which implies that OIDC / IRSA was NOT correctly enabled.

EDIT: I just re-ran our main.tf from scratch the the `aws-auth` config map is STILL MISSING even WITHOUT `enable_irsa  = true`

**Comment by GregSharpe1** [comment]
@bensussman Hey, I think I'm seeing a similar issue. I'm left with this output after the first run: 
```
Error: configmaps "aws-auth" already exists

  on .terraform/modules/eks/terraform-aws-modules-terraform-aws-eks-c9b9c96/aws_auth.tf line 52, in resource "kubernetes_config_map" "aws_auth":
  52: resource "kubernetes_config_map" "aws_auth" {
```

Is this similar behaviour for yourself?

**Comment by bensussman** [comment]
I was able to fix this by adding 

```
data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "~> 1.10"
}
```

I had to read and re-read the "important notes" in the changelog and the example to understand what it was talking about https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/CHANGELOG.md#important-notes i wish this had been better written, much of it i still don't understand (what "import" is it referring to? i never use the term "import" in my main.tf, so i don't understand when to use that. it doesn't seem necessary either).

Ultimately, this update feels like a step back in terms of usability for this library, but now that i've got it working I can only hope there isn't ANOTHER breaking change with a step back.
