### ISSUE TITLE
ASG workers on spot instances

### ISSUE THREAD

**Issue by filiphaftek** [terraform-aws-modules/terraform-aws-eks#72]
# I have issues
It is great that with this module I can use more than one ASG worker pool. Would be nice to be able to use spot instances i.e. for background jobs or any applications that can recover very fast from replaced node.

## I'm submitting a...
* [x] feature request

## What is the current behavior?
Cannot use spot instances as worker nodes (or at least do not know how)

## What's the expected behavior?
I could define that one (or all) of my worker nodes ASG are using spot instances.

**Comment by brandoconnor** [comment]
Hey @filiphaftek 👋  interesting thought! Looks like you have some solid support in 👍 for this feature already.

Per [terraform AWS docs](https://www.terraform.io/docs/providers/aws/r/launch_configuration.html#spot_price):

> Simply specifying the `spot_price` parameter will set the price on the Launch Configuration which will attempt to reserve your instances at this price

So this seems like an easy addition with one likely caveat: if `spot_price` is specified and we want demand hosts, what value will work there? Perhaps a blank string will produce on-demand hosts but potentially not. I'll leave that homework to the reader.

Are you able to do a PR for this change? It should be specified as the other `workers_group_defaults` variables work.

**Comment by filiphaftek** [comment]
Hi @brandoconnor , I can test it and make a PR but not in few upcoming days. I saw this `spot_price ` variable, but need to check if `aws_spot_fleet_request` won't be also necessary.  Will try to make this as simple as possible. Thank you.

**Comment by max-rocket-internet** [comment]
We will also need this soon 🙂

**Comment by joonjeong** [comment]
Nice features, I'm looking forward to it, too

**Comment by max-rocket-internet** [comment]
That PR was merged so I think we can close this issue now. Enjoy your cost savings!

**Comment by max-rocket-internet** [comment]
Also, FYI, you need something to catch the termination notification and gracefully drain the node. We use this: https://github.com/mumoshu/kube-spot-termination-notice-handler

**Comment by fdornberger** [comment]
@joonjeong This is a nice PR. Trying to use it though, I face some difficulties.

When I place  the spot_price my worker_groups configuration as shown below, the value isn't picked up. For the other variables such as key_name or instance_type, this is well working. Am I doing something wrong?

```hcl
  worker_groups = "${list(
                  map("asg_desired_capacity", "${var.worker_asg_desired_capacity}",
                      "asg_max_size", "${var.worker_asg_max_size}",
                      "asg_min_size", "${var.worker_asg_min_size}",
                      "instance_type", "${var.worker_instance_type}",
                      "key_name", "${var.worker_key_name}",
                      "additional_userdata", "${var.worker_additional_userdata}",
                      "name", "${var.worker_name}",
                      "spot_price", "0.0069",
                      ),
  )}"
```
