### ISSUE TITLE
Error while loading EKS module

### ISSUE THREAD

**Issue by sagar-babar** [terraform-aws-modules/terraform-aws-eks#723]
Hi,

I am facing issues while doing the terraform plan with below error

Error loading modules: module dev_cluster: Error parsing .terraform/modules/fb2f2f132eb332b3f9310319e400ad0f/terraform-aws-modules-terraform-aws-eks-dd06c59/aws_auth.tf: At 5:14: Unknown token: 5:14 IDENT var.create_eks

Can someone help with this? 

Thanks

**Comment by confiq** [comment]
Why would you delete the default template when creating an issue? The template for the issue is there for a reason... 

What terraform version do you have?

**Comment by sagar-babar** [comment]
Thanks @confiq , I was running wrong with Terraform version. It's working after moving it to the latest version
