### ISSUE TITLE
EKS create timeouts inconsistent between module and resource (over two repositories)

### ISSUE THREAD

**Issue by verdverm** [terraform-aws-modules/terraform-aws-eks#726]
The default value here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/variables.tf#L189

Is not consistent with the default value here: https://github.com/terraform-providers/terraform-provider-aws/issues/5165

It should be updated to "30m" to reflect the good default value selected else where.

**Comment by confiq** [comment]
I totally agree! 
the defaults should come from upstream. Do you mind to open a PR? If not, I can do it

**Comment by barryib** [comment]
@verdverm @confiq Thanks for opening this issue. Can you please open a PR for this ?

**Comment by confiq** [comment]
I have a feeling that I've hijacked this issue :)
 I've create the PR for this

**Comment by barryib** [comment]
Resolved by #736
