### ISSUE TITLE
Using computed values in worker group parameters results in `value of 'count' cannot be computed` error

### ISSUE THREAD

**Issue by laverya** [terraform-aws-modules/terraform-aws-eks#73]
# I have issues

## I'm submitting a...

* [x] bug report

## What is the current behavior?

`terraform plan` produces this output when any worker group parameters are computed values:

```
laverya:~/dev$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.http.workstation_external_ip: Refreshing state...
data.aws_region.current: Refreshing state...
data.aws_availability_zones.available: Refreshing state...
data.aws_iam_policy_document.cluster_assume_role_policy: Refreshing state...
data.aws_iam_policy_document.workers_assume_role_policy: Refreshing state...
data.aws_ami.eks_worker: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* module.eks.data.template_file.userdata: data.template_file.userdata: value of 'count' cannot be computed
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```
provider "aws" {
  version = "~> 1.27"
  region  = "us-east-1"
}

data "aws_availability_zones" "available" {}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "1.37.0"
  name    = "eks-vpc"
  cidr    = "10.0.0.0/16"
  azs     = ["${data.aws_availability_zones.available.names[0]}", "${data.aws_availability_zones.available.names[1]}", "${data.aws_availability_zones.available.names[2]}"]

  private_subnets    = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets     = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]

  tags = "${map("kubernetes.io/cluster/terraform-eks", "shared")}"
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "1.3.0"
  cluster_name = "terraform-eks"
  subnets = ["${module.vpc.private_subnets}", "${module.vpc.public_subnets}"]
  tags    = "${map("Environment", "test")}"
  vpc_id = "${module.vpc.vpc_id}"

  worker_groups = [
    {
      name          = "default-m5-large"
      instance_type = "m5.large"

      subnets = ""
      # subnets = "${join(",", module.vpc.private_subnets)}"
    },
  ]
}
```

Uncomment `subnets = "${join(",", module.vpc.private_subnets)}"` to replace `subnets = ""` in the worker_groups config and run `terraform plan`.

## What's the expected behavior?

`terraform plan` completes and a plan is produced.

## Are you able to fix this problem and submit a PR? Link here if you have already.

I have not yet identified the root cause.

## Environment details

* Affected module version: 1.3.0
* OS: Ubuntu 16.04
* Terraform version: Terraform v0.11.7

## Any other relevant info

This makes it rather difficult to assign subnets to worker groups.

**Comment by brandoconnor** [comment]
Hey there @laverya . Indeed this is a strange bug 🐛 

Completely bizarre that the subnet configuration has anything to do with the `count` of the userdata. This is a shot in the dark but can you try specifying your worker group configuration as a `local` using `list(map())` as I do in the test fixture. Perhaps the way a bare literal is passed like this gives terraform problems.

**Comment by laverya** [comment]
I've been debugging a bit myself and it seems to be these three locations: 

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L8
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L33
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/data.tf#L78

I don't think `length()` can be applied to computed values.

As for specifying the worker group as a local - yep, first thing I tried 😄 

The solution I'm trying locally right now is to add a `worker_group_count` variable that needs to be manually specified by the user & have those three locations refer to it instead. Not pretty (and not backwards compatible) but it seems to work

**Comment by brandoconnor** [comment]
Yea I resorted to doing the same in the alb module I maintain. For whatever reason, until now I hadn't seen this problem arise, even when specifying multiple worker groups... unsure which change introduced this along the way. If we need to give a top level var of `worker_group_count`, that's not ideal but also not the worst situation.

**Comment by mars64** [comment]
I ran into this when overriding security group with sg's that I created in-line (using `local` versions of `cluster_security_group_id` and `worker_security_group_id`. I'm able to work around the issue by commenting out the module and applying only the security group changes. Once the security groups exist, I am able to apply the module properly.

**Comment by jeff-french** [comment]
I'm facing this issue when using the `map_roles` functionality to map role ARNs to kubernetes groups. If I specify the ARNs explicitly it works fine, but if I use interpolation to specify the ARN of a role that is also being created by Terraform I get the error about `value of 'count' cannot be computed`. 

Simplified example:

```
data "aws_iam_policy_document" "kube_admin" {
  statement {
    effect = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      identifiers = ["ec2.amazonaws.com"]
      type = "Service"
    }
  }
}

resource "aws_iam_role" "kube_admin" {
  name = "kubernetes-admin"
  assume_role_policy = "${data.aws_iam_policy_document.kube_admin.json}"
}

module "eks" {
  ...
  map_roles = [
    {
      role_arn = "${aws_iam_role.kube_admin.arn}"
      username = "admin"
      group = "system:masters"
    }
  ]
}
```
When running a plan it gives the error:

```
 * module.eks.data.template_file.map_roles: data.template_file.map_roles: value of 'count' cannot be computed
```

If I change to `role_arn = "some-static-string"` everything works fine. This also applies to `map_users` and `map_accounts`. 

This [comment](https://github.com/hashicorp/terraform/issues/18115#issuecomment-397778718) on the Terraform issue board indicates that this is a limitation of the current design:

> In the current version of Terraform, there is a restriction where passing a list that contains any values that are <computed> to a function will force the function result to always be <computed> itself.

Sounds like that might improve a bit when Terraform `v0.12` ships, but for now we'll need a workaround to make these things work.

I see PR #75 that proposes to use a separate variable to get around this problem for worker groups. Is that the same solution we should use for any of these problems that are related to count not being a computed value? If so, I can submit a PR with those changes.

**Comment by brandoconnor** [comment]
@jeff-french you've got the right idea. I've seen this same problem in a few contexts now and the only way I've seen it worked around is having that separate count variable. It's fragile, not great, but also could be worse. The work in #75 has been merged and released so let me know after upgrade if you're still seeing this.

**Comment by amitlt** [comment]
@brandoconnor I ran into it while trying to set `cluster_security_group_id` to be a locally created resource.

excerpt:
`module "eks_cluster" {
    source                  = "terraform-aws-modules/eks/aws"
    cluster_name            = "${local.full_name}"
    subnets                 = "${data.terraform_remote_state.vpc.mgmt_subnets}"
    tags                    = "${local.tags}"
    vpc_id                  = "${data.terraform_remote_state.vpc.vpc_id}"
    create_elb_service_linked_role = true

    worker_groups           = "${local.worker_groups}"

    cluster_security_group_id = "${aws_security_group.cluster_sg.id}"
    worker_additional_security_group_ids = [ "${aws_security_group.worker_nodes_sg.id}" ]
}

resource "aws_security_group" "cluster_sg" {
  name = "${local.full_name}"
  description = "sg for ${local.full_name}"
  vpc_id = "${data.terraform_remote_state.vpc.vpc_id}"


  ingress {
      from_port = 22
      to_port = 22
      protocol = "tcp"
      cidr_blocks = ["${var.mgmt_cidr_blocks}"]
  }

# Allow all outbound
  egress {
      from_port = 0
      to_port = 0
      protocol = "-1"
      cidr_blocks = ["0.0.0.0/0"]
  }

  tags {
    Name = "${local.full_name}"
    env = "${var.env}"
  }
}`

results in `module.eks_cluster.aws_security_group.cluster: aws_security_group.cluster: value of 'count' cannot be computed`

I suggest it should receive the same treatment `worker_groups_count` got and maybe have a `use_custom_cluster_sg` variable, and use it instead of the count [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/cluster.tf#L27), at least until terraform provides a suitable workaround.
