### ISSUE TITLE
Node_groups do not allow the addition of bootstrap_extra_args as worker_groups do

### ISSUE THREAD

**Issue by linxcat** [terraform-aws-modules/terraform-aws-eks#730]
# I have issues

## I'm submitting a...

* [X] bug report
* [X] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Managed node groups do not have the same capability to receive "bootstrap_extra_args" which is necessary for the flag "--enable-docker-bridge true" to fix the use of docker commands in kubernetes containers.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Creating a worker nodes using worker_group allows for this behaviour (defaults are fine)
```
  worker_groups = [
    {
      # Other parameters omitted for brevity
      bootstrap_extra_args = "--enable-docker-bridge true"
    }
  ]
```
creating a node_group has no such option

## What's the expected behavior?
Managed node_groups should have all the same features as self-provisioned worker_groups

## Are you able to fix this problem and submit a PR? Link here if you have already.
I am not

## Environment details

* Affected module version: All
* OS: Local - Mac, EKS - AWSLinux
* Terraform version: 0.12.19

**Comment by dpiddockcmp** [comment]
This is a limitation on the node group service as currently supplied by AWS. It is not possible. If you need to set these options then you will have to stick to classic worker groups.

**Comment by max-rocket-internet** [comment]
Reference: https://github.com/aws/containers-roadmap/issues/596

Here's a current list of what people are asking for:
https://github.com/aws/containers-roadmap/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%5BEKS%5D+

**Comment by linxcat** [comment]
Thank you for this information! Closing

**Comment by 0verc1ocker** [comment]
So from workers_groups, I switched to node_groups because they are easier to manage. Now I will have to switch back to node_groups since bootstrapping with user_data is not supported yet and we need lots of customization for security... :trollface: :cry:

**Comment by nirmalpathak** [comment]
I tried this ugly hack to enable the `docker0` bridge with `node_groups` using `pre_userdata`.

`pre_userdata = "sed -i 's/ENABLE_DOCKER_BRIDGE:.*/ENABLE_DOCKER_BRIDGE:-true}\"/' /etc/eks/bootstrap.sh"`
