### ISSUE TITLE
Worker Groups should support a map of maps

### ISSUE THREAD

**Issue by mcavoyk** [terraform-aws-modules/terraform-aws-eks#732]
# I have issues

## I'm submitting a...

* [x] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Related to https://github.com/terraform-aws-modules/terraform-aws-eks/issues/476,  `worker_groups` and `worker_groups_launch_template` are both list of maps, as a result removing one worker group can end up causing cycles or changes to all worker groups in the indexes after the modified worker group.

`node_groups` uses map of maps which allows removal of an element without shifting other elements, this seems like better behavior. A map of map for worker group may also allow for Launch Template/Launch Config as a setting of the worker group rather than a different input as mentioned https://github.com/terraform-aws-modules/terraform-aws-eks/issues/563.

**Comment by max-rocket-internet** [comment]
> node_groups uses map of maps which allows removal of an element without shifting other elements, this seems like better behavior

It is better but `worker_groups` and `worker_groups_launch_template` were made before map of maps was possible, pre TF 0.12.

I think this change would be breaking? We should also just merge `worker_groups` and `worker_groups_launch_template` together.

**Comment by dpiddockcmp** [comment]
Could move it all to a submodule at the same time.

Such a breaking change that it would be easier for users to target create resources in the submodule, taint and drain the old nodes, then do a full apply to clean up the old ASGs.

One big round of pain to remove some old headaches?

**Comment by max-rocket-internet** [comment]
Good idea @dpiddockcmp

**Comment by josh-stableprice** [comment]
I'm glad to see this is being considered, and as I'm someone who is experiencing this cycle from trying to remove an item from worker group launch template, how do you typically deal with it?

**Comment by johnpekcan** [comment]
Thanks for removing `stale` @barryib 😇

**Comment by Xyaren** [comment]
Nononono... This is still a Problem :)
Please don't let this go down in other Issues

**Comment by johnpekcan** [comment]
bump for stale 😇

**Comment by johnpekcan** [comment]
bump 😇

**Comment by Art3mK** [comment]
bump

**Comment by Art3mK** [comment]
@barryib , could you reopen that, plz, this is still valid I think.
