### ISSUE TITLE
Forced Replacement of launch configurations without changes in code

### ISSUE THREAD

**Issue by Krishna1408** [terraform-aws-modules/terraform-aws-eks#737]
# I have issues

## I'm submitting a...

* [ ] bug report

## What is the current behavior?

I have clusters created using `terrafrom-aws-eks` module. They are all running fine. Today when I went to do a code change for S3 bucket, I realised that all my launch configuration for EKS are also being re-created. I have not done any change to my EKS module nor EKS files, so I expect no changes when I run terraform plan. This is how my `eks.tf` looks like:

```hcl
module "eks" {
  source = "../../../modules/aws/terraform-eks"

  env             = local.env
  cluster_name    = local.cluster_name
  cluster_version = 1.14

  subnets = module.vpc.private_subnets
  vpc_id  = module.vpc.vpc_id

  worker_groups = [
    {
      name                 = "terraform-1"
      instance_type        = "t3.large"
      key_name             = "eks-dev"
      bootstrap_extra_args = "--enable-docker-bridge true"
      kubelet_extra_args   = "--node-labels=env=Test,service=docker,team=platform"
      node_group_k8s_labels = {
        Environment = "Test"
        Team        = "Platform"
        Service     = "Docker"
                                                  }
      asg_max_size = "5" # Maximum worker capacity in the autoscaling group.
      asg_min_size = "0"
    }

    ]

  map_roles    = var.map_roles
  map_users    = var.map_users
}
```

Below is the output of plan:

```hcl
  # module.eks.aws_launch_configuration.workers[0] must be replaced
+/- resource "aws_launch_configuration" "workers" {
        associate_public_ip_address      = false
        ebs_optimized                    = true
        enable_monitoring                = true
        iam_instance_profile             = "sennder-admin-cluster20200106121106098100000008"
      ~ id                               = "sennder-admin-cluster-terraform-12020010612110773630000000d" -> (known after apply)
        image_id                         = "ami-07034b303e1ffc843"
        instance_type                    = "t3.large"
        key_name                         = "eks-dev"
      ~ name                             = "sennder-admin-cluster-terraform-12020010612110773630000000d" -> (known after apply)
        name_prefix                      = "sennder-admin-cluster-terraform-1"
        security_groups                  = [
        ]
      ~ user_data_base64                 = "BIG BLOCK OF BASE64" -> (known after apply) # forces replacement
      - vpc_classic_link_security_groups = [] -> null

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + no_device             = (known after apply)
          + snapshot_id           = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      ~ root_block_device {
            delete_on_termination = true
          ~ encrypted             = false -> (known after apply)
            iops                  = 0
            volume_size           = 100
            volume_type           = "gp2"
        }
    }

  # module.eks.random_pet.workers[0] must be replaced
+/- resource "random_pet" "workers" {
      ~ id        = "amusing-parakeet" -> (known after apply)
      ~ keepers   = {
          - "lc_name" = "sennder-admin-cluster-terraform-12020010612110773630000000d"
        } -> (known after apply) # forces replacement
        length    = 2
        separator = "-"
    }


  # module.eks.local_file.kubeconfig[0] must be replaced
-/+ resource "local_file" "kubeconfig" {
      ~ content              = "" -> (known after apply) # forces replacement
        directory_permission = "0777"
        file_permission      = "0777"
        filename             = "./kubeconfig_sennder-admin-cluster"
      ~ id                   = "d2ea96f32318207ab27000f3d7ff80a70ae6b321" -> (known after apply)
    }

```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

I just did:

```
terraform init
terraform plan
```

## What's the expected behavior?

I should get response similar to:

```

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```
I also checked the User data for existing configurations and I see that it's not changed at all. I see same base64 encoded value of user data for both exiting launch config and the one terraform is creating.

## Environment details

Terraform version:
`Terraform v0.12.13`

Terraform providers being used:
```hcl
terraform {
  required_version = ">= 0.12.0"
}

provider "aws" {
  region  = var.region
}

provider "random" {
  version = "~> 2.1"
}

provider "local" {
  version = "~> 1.2"
}

provider "null" {
  version = "~> 2.1"
}

provider "template" {
  version = "~> 2.1"
}

resource "random_string" "suffix" {
  length  = 8
  special = false
}
```

* Affected module version:
* OS:
* Terraform version:

**Comment by manfredlift** [comment]
I have noticed the same, modifying indirectly related resources forces a recreation of `aws_launch_configuration` with the plan showing `(known after apply) # forces replacement` for every attribute.

**Comment by max-rocket-internet** [comment]
For every `terraform apply`? Like repeatedly?

**Comment by Krishna1408** [comment]
AFter the changes are applied, it gets back to normal (for some weeks ) and then repeats. But it has happened repeatedly and It's a nightmare for production. So far we are not pushing any changes to production to maintain status quo.

**Comment by dpiddockcmp** [comment]
It's because AWS released a new AMI for the worker nodes. By default the module picks the latest and replaces the launch configuration to use it.

If unexpected changes like this are bad for you, you should use one of the variable to lock the worker AMI you use: `ami_id` in the workers map or `worker_ami_name_filter` variable.

**Comment by sassimatias** [comment]
having the same issue, in my case it marks `name_prefix` as modified and forces replacement

**Comment by clairefinnie** [comment]
also having the same issue. For us it looks like the directory permissions on the local file resources used for kubeconfig, that causes the force replacement.


`  # module.eks.local_file.kubeconfig[0] must be replaced
-/+ resource "local_file" "kubeconfig" {

...
        EOT
      + directory_permission = "0777" # forces replacement
      + file_permission      = "0777" # forces replacement
        filename             = "./k8-output/kubeconfig_ds---"
      ~ id                   = "46a63080b3-------b" -> (known after apply)`

**Comment by max-rocket-internet** [comment]
I am also seeing this but it's just LC, not the ASG.

**Comment by max-rocket-internet** [comment]
Funny though, if you do a second apply immediately after the first one, there is no further changes. But at some point changes come back 🤔

**Comment by krishnasennder** [comment]
I am facing the same @max-rocket-internet . The way it works is that the LC thing causes change in launch configurations. Then the launch configurations causes changes in autoscaling groups. The launch configs are getting destroyed and recreated not the autoscaling groups.

**Comment by Art3mK** [comment]
Also seeing this. We just created few clusters with this module, without passing `target_group_arns`. Then after adding NLB in front of EKS, and adding `target_group_arns` to `workers_group_defaults` I'm seeing terraform wanting to replace LC and ASG, because of name_prefix change:
```
  # module.eks.aws_launch_template.workers_launch_template[2] must be replaced
+/- resource "aws_launch_template" "workers_launch_template" {
      ~ arn                     = "arn:aws:ec2:eu-north-1:123456789012:launch-template/lt-0968daaae8037e1c1" -> (known after apply)
      ~ default_version         = 1 -> (known after apply)
      - disable_api_termination = false -> null
      ~ ebs_optimized           = "true" -> (known after apply)
      ~ id                      = "lt-0968daaae8037e1c1" -> (known after apply)
      ~ image_id                = "ami-0f29ff24640121046" -> (known after apply)
      ~ instance_type           = "t3.large" -> (known after apply)
      + key_name                = (known after apply)
      ~ latest_version          = 2 -> (known after apply)
      ~ name                    = "example-apps-cluster-spot-320200227133342053200000007" -> (known after apply)
      ~ name_prefix             = "example-apps-cluster-spot-3" -> (known after apply) # forces replacement
      - security_group_names    = [] -> null
      ~ user_data               = "..." -> (known after apply)
      - vpc_security_group_ids  = [] -> null

      ~ block_device_mappings {
          ~ device_name = "/dev/xvda" -> (known after apply)

          ~ ebs {
                delete_on_termination = "true"
              ~ encrypted             = "true" -> (known after apply)
              ~ iops                  = 0 -> (known after apply)
              + kms_key_id            = (known after apply)
              ~ volume_size           = 100 -> (known after apply)
              ~ volume_type           = "gp2" -> (known after apply)
            }
        }

      ~ credit_specification {
          ~ cpu_credits = "standard" -> (known after apply)
        }

      ~ iam_instance_profile {
            name = "example-apps-cluster20200227133341819300000001"
        }

      + instance_market_options {
          + market_type = (known after apply)
        }

      ~ monitoring {
          ~ enabled = true -> (known after apply)
        }

      ~ network_interfaces {
          ~ associate_public_ip_address = "false" -> (known after apply)
          ~ delete_on_termination       = true -> (known after apply)
          - device_index                = 0 -> null
          - ipv4_address_count          = 0 -> null
          - ipv4_addresses              = [] -> null
          - ipv6_address_count          = 0 -> null
          - ipv6_addresses              = [] -> null
          ~ security_groups             = [
              - "sg-02b2d0fe4b621a404",
            ] -> (known after apply)
        }

      ~ placement {
          + group_name = (known after apply)
          ~ tenancy    = "default" -> (known after apply)
        }

      ~ tag_specifications {
            resource_type = "volume"
          ~ tags          = {
              - "Name"    = "example-apps-cluster-spot-3-eks_asg"
              - "Owner"   = "..."
              - "Project" = "..."
            } -> (known after apply)
        }
    }
```

ASG is recreated also because of name_prefix change (while it will be the same in result).

**Comment by max-rocket-internet** [comment]
This issue is getting really annoying 😅 Does anyone have a fix?

**Comment by Krishna1408** [comment]
@max-rocket-internet @Art3mK @clairefinnie : Changes in launch configurations are okay as long as it doesn't cause `replacement of autoscaling groups` 

Also, the terraform module is picking up updated ami's for EKS workers. If you pin the version of AMI's the launch configs will change less number of time. As well keeping changes low for worker group section helps a bit.

**Comment by Art3mK** [comment]
@Krishna1408, not sure what you tried to explain.

IIUC changes in launch templates, like AMI id or smth shouldn't affect ASGs if `asg_recreate_on_change` is false. But I see different behavior, when ASG is recreated because of passing some related parameters like target group ARN, etc

**Comment by max-rocket-internet** [comment]
> Changes in launch configurations are okay as long as it doesn't cause replacement of autoscaling groups

I know that but it's still annoying. The LC or LT shouldn't be replaced unless there is changes to it, like AMI or user-data. But right now, it's regularly replaced without any relevant changes 🙂

**Comment by barryib** [comment]
> This issue is getting really annoying 😅 Does anyone have a fix?

@max-rocket-internet please share your entire plan and debug output.

**Comment by soptim-bema** [comment]
Hello everyone,

I seem to have the same issue with an aws_launch_configuration, but instead eks I am using ecs.

I seem to be able to reproduce the issue by running a GitLab-pipeline and then running `terraform apply` from a different machine manually.

Here is the unnecessary/unwanted part:

 ```
# module.ecs_cluster.aws_launch_configuration.ecs must be replaced
+/- resource "aws_launch_configuration" "ecs" {
      ~ arn                              = "arn:aws:autoscaling:eu-central-1:149004727281:launchConfiguration:d0311be1-6c75-4bbc-a741-492c1b61cc9a:launch
ConfigurationName/dev-ecs-app20200414100322327300000005" -> (known after apply)
        associate_public_ip_address      = false
      ~ ebs_optimized                    = false -> (known after apply)
        enable_monitoring                = true
        iam_instance_profile             = "dev-app"
      ~ id                               = "dev-ecs-app20200414100322327300000005" -> (known after apply)
        image_id                         = "<image-id>"
        instance_type                    = "t2.medium"
        key_name                         = "dev-app"
      ~ name                             = "dev-ecs-app20200414100322327300000005" -> (known after apply)
        name_prefix                      = "dev-ecs-app"
        security_groups                  = [
            "sg-00f9a1465484b7a1d",
        ]
      ~ user_data                        = "34bbc7fa5c88ba473b17166606b899856e6cbffa" -> "0fc8f322edb90a9e3145b27ebd0b4872a942303b" # forces replacement
      - vpc_classic_link_security_groups = [] -> null

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + no_device             = (known after apply)
          + snapshot_id           = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      ~ root_block_device {
            delete_on_termination = true
          ~ encrypted             = false -> (known after apply)
          ~ iops                  = 0 -> (known after apply)
            volume_size           = 30
            volume_type           = "standard"
        }
    }
```

As @barryib requested, I attached a debug output of `terraform plan`.
I had to anonymize some parts though. Does this help in order to find the issue?
[plan_anonym.txt](https://github.com/terraform-aws-modules/terraform-aws-eks/files/4487408/plan_anonym.txt)

**Comment by geethaka** [comment]
> @Krishna1408, not sure what you tried to explain.
> 
> IIUC changes in launch templates, like AMI id or smth shouldn't affect ASGs if `asg_recreate_on_change` is false. But I see different behavior, when ASG is recreated because of passing some related parameters like target group ARN, etc

@Art3mK I'm also facing the same issue. adding a new target group it recreates asg. were you able to overcome that ?

**Comment by errogaht** [comment]
the same for me... some times i come to terraform to change soething not related to this module and i am getting 
module.eks.random_pet.workers[0] must be replaced
module.eks.random_pet.workers[1] must be replaced
module.eks.aws_launch_configuration.workers[1] must be replaced
module.eks.aws_launch_configuration.workers[0] must be replaced
 module.eks.aws_autoscaling_group.workers[1] will be updated in-place
module.eks.aws_autoscaling_group.workers[0] will be updated in-place

**Comment by ankitabhopatkar13** [comment]
Same issue for us, as with all the replacement, Terraform tried to delete the `worker security group` and as it's attached to n number of eks workers/enis and other security groups, it can't be deleted and Terraform run failed and as per logs it ended up deleting a few security group rules. We had to rotate all the nodes to make the system work again.

The difference that showed in our apply was adding the `name_prefix` to worker security group, which when I checked in previous versions of statefile was always there!

**Comment by zioalex** [comment]
Hallo another case of the same problem. How can we get more attention here?

**Comment by dpiddockcmp** [comment]
This is currently impossible to debug without someone catching more information. "sometimes a thing gets updated, can't reproduce" isn't helpful. There could even be multiple sources of the "mysterious" updates.

What triggered the recreation of your launch template?

Is it because AWS released a new AMI version? That's expected. Lock the AMI version if it's a problem for you.

Is it a line ending change in the userdata script? Ensure terraform is only run from one infrastructure. Windows has different line endings to linux/mac!

Post full Terraform output, not just the launch template diff.

**Comment by pjanuario** [comment]
I am also having this problem in 2 different clusters that are configured using this module. I see that some changes are related to AMI not being specified but doesn't seem the only one.

Version: Terraform v0.13.1
Module Version: 12.2.0
Configuration:

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "12.2.0"

  vpc_id          = module.vpc.vpc_id
  cluster_name    = var.cluster_name
  cluster_version = var.cluster_version
  subnets         = module.vpc.private_subnets

  tags = {
    Terraform   = "true"
    Environment = var.environment
  }

  cluster_encryption_config = [
    {
      provider_key_arn = aws_kms_key.eks.arn
      resources        = ["secrets"]
    }
  ]

  cluster_enabled_log_types     = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
  cluster_log_retention_in_days = 30

  worker_groups = [
    {
      name                 = var.cluster_worker_group_name
      instance_type        = var.cluster_worker_group_instance_type
      asg_desired_capacity = var.cluster_worker_group_asg_desired_capacity
    }
  ]

  map_roles    = var.cluster_map_roles
  map_users    = var.cluster_map_users
  map_accounts = var.cluster_map_accounts
}
```

Change manifest:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
+/- create replacement and then destroy

Terraform will perform the following actions:

  # module.environment.module.eks.aws_autoscaling_group.workers[0] will be updated in-place
  ~ resource "aws_autoscaling_group" "workers" {
        arn                       = "arn:aws:autoscaling:us-east-2:XXX:autoScalingGroup:YYY:autoScalingGroupName/tst-eks-worker-group-default2020102915033234360000000d"
        availability_zones        = [
            "us-east-2a",
            "us-east-2b",
            "us-east-2c",
        ]
        default_cooldown          = 300
        desired_capacity          = 2
        enabled_metrics           = []
        force_delete              = false
        health_check_grace_period = 300
        health_check_type         = "EC2"
        id                        = "tst-eks-worker-group-default2020102915033234360000000d"
      ~ launch_configuration      = "tst-eks-worker-group-default20201029153833268400000001" -> (known after apply)
        load_balancers            = []
        max_instance_lifetime     = 0
        max_size                  = 3
        metrics_granularity       = "1Minute"
        min_size                  = 1
        name                      = "tst-eks-worker-group-default2020102915033234360000000d"
        name_prefix               = "tst-eks-worker-group-default"
        protect_from_scale_in     = false
        service_linked_role_arn   = "arn:aws:iam::XXX:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
        suspended_processes       = [
            "AZRebalance",
        ]
        tags                      = [
            {
                "key"                 = "Name"
                "propagate_at_launch" = "true"
                "value"               = "tst-eks-worker-group-default-eks_asg"
            },
            {
                "key"                 = "Terraform"
                "propagate_at_launch" = "true"
                "value"               = "true"
            },
            {
                "key"                 = "k8s.io/cluster/tst-eks"
                "propagate_at_launch" = "true"
                "value"               = "owned"
            },
            {
                "key"                 = "kubernetes.io/cluster/tst-eks"
                "propagate_at_launch" = "true"
                "value"               = "owned"
            },
        ]
        target_group_arns         = []
        termination_policies      = []
        vpc_zone_identifier       = [
            "subnet-111",
            "subnet-222",
            "subnet-333",
        ]
        wait_for_capacity_timeout = "10m"
    }

  # module.environment.module.eks.aws_launch_configuration.workers[0] must be replaced
+/- resource "aws_launch_configuration" "workers" {
      ~ arn                              = "arn:aws:autoscaling:us-east-2:XXX:launchConfiguration:XZZZ:launchConfigurationName/tst-eks-worker-group-default20201029153833268400000001" -> (known after apply)
        associate_public_ip_address      = false
        ebs_optimized                    = false
        enable_monitoring                = true
        iam_instance_profile             = "tst-eks20201029150315481600000008"
      ~ id                               = "tst-eks-worker-group-default20201029153833268400000001" -> (known after apply)
      ~ image_id                         = "ami-0dc6bc43da1b962d8" -> "ami-005ecc78d7cd1157d" # forces replacement
        instance_type                    = "t2.medium"
      + key_name                         = (known after apply)
      ~ name                             = "tst-eks-worker-group-default20201029153833268400000001" -> (known after apply)
        name_prefix                      = "tst-eks-worker-group-default"
        security_groups                  = [
            "sg-444",
        ]
        user_data_base64                 = "****"
      - vpc_classic_link_security_groups = [] -> null

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + no_device             = (known after apply)
          + snapshot_id           = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

        root_block_device {
            delete_on_termination = true
            encrypted             = false
            iops                  = 0
            volume_size           = 100
            volume_type           = "gp2"
        }
    }

  # module.environment.module.eks.random_pet.workers[0] must be replaced
+/- resource "random_pet" "workers" {
      ~ id        = "touching-cheetah" -> (known after apply)
      ~ keepers   = {
          - "lc_name" = "tst-eks-worker-group-default20201029153833268400000001"
        } -> (known after apply) # forces replacement
        length    = 2
        separator = "-"
    }

Plan: 2 to add, 1 to change, 2 to destroy.
```

**Comment by pre** [comment]
Almost any change to a launch_template will also cause a managed node group to be recreated if it has a random_pet in its name. 

It goes badly against the idea of launch templates, as you should be able to update the node group to a newer version of the launch template. Instead, the whole node group is to be recreated (due to random_pet) - as a result the Managed Node Group is more like a WaitingToBeRecreated Node Group.

It would be great it was possible to define `node_groups = { .. }` without random_pet being involved at all. Even if I define explicit node group name name , name_prefix or any combination, the random_pet seems always to be there.

**Comment by pre** [comment]
There is `asg_recreate_on_change` as a workaround for `random_pet` in `workers` (https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1013#issuecomment-694738999), but such option doesn't  seem to be available for Managed Node Groups.

**Comment by TBeijen** [comment]
Running into same issue. What I'm doing:

* Adding an ALB, introducing a new target_group
* Adding that to the `worker_group` `target_group_arns` list.

Relevant part of plan output:
```
       metrics_granularity       = "1Minute"
        min_size                  = 2
      ~ name                      = "tools-ng-a20200305141842546200000016" -> (known after apply)
      ~ name_prefix               = "tools-ng-a" -> (known after apply) # forces replacement
```

----
Since `aws_autoscaling_group` `name_prefix` uses random_pet based on `asg_recreate_on_change` value, which is looked up from `var.worker_groups_launch_template`, defaulting to `local.workers_group_defaults`....

I tried setting `asg_recreate_on_change = false` _in_ the `worker_groups_launch_template`, to rule out issues with lookup of defaults.

So, like this:
```
  worker_groups_launch_template = [
      {
        name                    = "ng-a"
        # previously was only set in 
        asg_recreate_on_change  = false
      }
    ]

  workers_group_defaults = {
    public_ip = false
    subnets   = var.private_subnets

    asg_recreate_on_change = false
  }
```

This changed:
* No more name_prefix change in asg. Resource 'will be updated in-place' (Good!)
* Where previously 'plan' showed the target_group being added, now the `target_group_arns` in tf plan output shows no change (WTF!)

It's hardly getting any clearer...

**Comment by LeeSaferite** [comment]
One aspect I'm seeing, and I'm sorry if I missed someone talking about it in above, is that the userdata changes due to line endings. All of our TF files use LF and the data coming back from AWS replaces that with CRLF instead. This makes it constantly want to update.

**Comment by ashishjullia** [comment]
Hi, after reading almost all the comments on different issues regarding this, unable to find a proper solution to this.

Anyone with a workaround or a solution for this?
