### ISSUE TITLE
Expose kube-proxy metrics on 0.0.0.0

### ISSUE THREAD

**Issue by lyz-code** [terraform-aws-modules/terraform-aws-eks#742]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

kube-proxy is configured by default to `metricsBindAddress: 127.0.0.1:10249` which makes it [impossible to export kube proxy metrics to prometheus server via prometheus operator](https://github.com/kubernetes/kubernetes/issues/74011).

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Target the eks cluster with:

```bash
kubectl describe -n kube-system cm kube-proxy-config | grep metrics 
```

## What's the expected behavior?

The metrics server should be binded to `0.0.0.0:10249` or at least give the option to do so.

## Are you able to fix this problem and submit a PR? Link here if you have already.

I could do the PR if you feel that it's something that should be fixed.

## Environment details

* Affected module version: 8.0.0
* OS: Irrelevant
* Terraform version: v0.12.19

**Comment by max-rocket-internet** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/731

🙂

**Comment by lyz-code** [comment]
Oups, sorry. 

So the solution is to manually edit the configmap on each deployment?

**Comment by max-rocket-internet** [comment]
> So the solution is to manually edit the configmap on each deployment?

Totally up to you. You could do it manually, apply it with terraform but outside of this module or some other way.
