### ISSUE TITLE
How to specify image id or ami id in the worker launch template?

### ISSUE THREAD

**Issue by manoj-cb** [terraform-aws-modules/terraform-aws-eks#743]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by max-rocket-internet** [comment]
https://github.com/aws/containers-roadmap/issues/741

**Comment by garvizmx** [comment]
I have the following launch template for a graviton asg:
You can of course modified you kubelet args with your own needs.

`{
      name                 = "worker-spot-g"
      override_instance_types = ["m6g.4xlarge"]
      spot_instance_pools     = 4
      asg_max_size            = 20
      asg_desired_capacity    = 1
      kubelet_extra_args      = "--node-labels=nodes=shared,authentication-token-webhook=true,authorization-mode=Webhook --register-with-taints=node.kubernetes.io/worker=true:NoSchedule,node.kubernetes.io/lifecycle=spot"
      ami_id                  = "ami-0ec3e069e3dc4757b"
      public_ip            = false
      tags = [
        {
          "key"                 = "k8s.io/cluster-autoscaler/enabled"
          "propagate_at_launch" = "false"
          "value"               = "true"
        },
        {
          "key"                 = "k8s.io/cluster-autoscaler/${local.cluster_name}"
          "propagate_at_launch" = "false"
          "value"               = "true"
        }
      ]
    },
`

**Comment by agconti** [comment]
Can you specify the graviton ami with `worker_ami_name_filter` instead?

**Comment by agconti** [comment]
I figured this out. You can use:

```
 worker_ami_name_filter="amazon-eks-arm64-node-${var.cluster_version}-v*"
```

The benefit of this method over @garvizmx's approach is that it will always use the most up-to-date ami for your eks version.

**Comment by adilsonmenechini** [comment]
Error when using "worker_groups_launch_template" to recognize workers

```
kubectl get nodes                                                        
No resources found
```

```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = var.cluster_name
  cluster_version = var.eks_version
  subnets         = module.vpc.public_subnets
  vpc_id          = module.vpc.vpc_id
  enable_irsa     = true

  worker_groups_launch_template = [
    {
      name                    = "Devolp"
      override_instance_types = ["t3.medium", "t3.large"]
      root_encrypted          = true
      root_volume_size        = var.dev_root_volume_size
      key_name                = var.key_name
      asg_force_delete        = true

      asg_min_size                             = var.dev_asg_min_size
      asg_desired_capacity                     = var.dev_asg_desired_capacity
      on_demand_base_capacity                  = var.dev_on_demand_base_capacity
      on_demand_percentage_above_base_capacity = var.dev_on_demand_percentage
      asg_max_size                             = var.dev_asg_max_size
      spot_instance_pools                      = var.dev_spot_instance_pools

      enabled_metrics    = ["GroupMinSize", "GroupMaxSize", "GroupDesiredCapacity"]
      kubelet_extra_args = "--node-labels=worker=devolp --node-labels=node.kubernetes.io/lifecycle=`curl -s http://169.254.169.254/latest/meta-data/instance-life-cycle`"
      tags = [
        {
          "key"                 = "k8s.io/cluster-autoscaler/enabled"
          "propagate_at_launch" = "false"
          "value"               = "true"
        },
        {
          "key"                 = "k8s.io/cluster-autoscaler/${var.cluster_name}"
          "propagate_at_launch" = "false"
          "value"               = "true"
        }
      ]
    },
  ]
}
```

**Comment by xposix** [comment]
That's a little bit of a downside when you have different worker types on the same cluster (ARM or GPUs)

**Comment by barryib** [comment]
> That's a little bit of a downside when you have different worker types on the same cluster (ARM or GPUs)

You can define your own ami datasource, your own filter and pass the AMI ID to your worker groups.

```hcl
data "aws_ami" "my_worker_ami" { 
filter { 
name = "name" 
values = ["your-filter"] 
} 
most_recent = true 
owners = ["your-owner-alias-or-id]
}

# In your module call
module "eks" {
worker_groups = {
ami_id = data.aws_ami.my_worker_ami.id
}
}
```
