### ISSUE TITLE
wait_for_cluster_cmd fails when manage_aws_auth is enabled but public_access is disabled.

### ISSUE THREAD

**Issue by slimm609** [terraform-aws-modules/terraform-aws-eks#744]
## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
When creating a cluster with `manage_aws_auth = true` and `cluster_endpoint_public_access = false`, the wait_for_cluster_cmd will never complete successfully because there is no access to the cluster except from its own security group. 

## If this is a bug, how to reproduce? Please include a code sample if relevant.
`manage_aws_auth = true`
`cluster_endpoint_public_access = false`

## Are you able to fix this problem and submit a PR? Link here if you have already.
Yes. 
## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by barryib** [comment]
This fix has been released in https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v11.0.0
