### ISSUE TITLE
Not possible to create node group with `attach_worker_cni_policy = false`

### ISSUE THREAD

**Issue by 3oris** [terraform-aws-modules/terraform-aws-eks#746]
## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

When setting `attach_worker_cni_policy = false` with a node_group configuration (that otherwise works), node_group creation yields
```
Error: error creating EKS Node Group (dev_xxx:dev_xxx-0-lasting-ringtail): InvalidParameterException: The provided role doesn't have the Amazon EKS Managed Policies associated with it. Please ensure the following policies [arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy, arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy, arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly] are attached
{
  ClusterName: "dev_xxx",
  Message_: "The provided role doesn't have the Amazon EKS Managed Policies associated with it. Please ensure the following policies [arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy, arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy, arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly] are attached",
  NodegroupName: "dev_xxx-0-lasting-ringtail"
}

  on .terraform/modules/eks-cluster/terraform-aws-modules-terraform-aws-eks-dd06c59/modules/node_groups/node_groups.tf line 1, in resource "aws_eks_node_group" "workers":
   1: resource "aws_eks_node_group" "workers" {
```

## What's the expected behavior?

Be able to start a node group without the `AmazonEKS_CNI_Policy` attached

## Environment details

* Terraform version: 1.12.20

## Any other relevant info

We want to make use of the `attach_worker_cni_policy` option in order to limit the overly permissive node role. We deploy the CNI Plugin with IRSA enabled SA, so we don't need the policy attached to the node.

Further reference:

* https://docs.aws.amazon.com/eks/latest/userguide/worker_node_IAM_role.html
* https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-cni-walkthrough.html , esp. step 7 remove AmazonEKS_CNI_Policy )
* https://github.com/aws/eks-charts/issues/57#issuecomment-588983667 (implement IRSA for `aws-node` CNI plugin in terraform)

**Comment by max-rocket-internet** [comment]
This error comes from the AWS API though, right? If so, how can we resolve that in this module?

**Comment by 3oris** [comment]
If this is the case, did I misunderstand the purpose of this flag?

**Comment by 3oris** [comment]
After some research we found this: https://github.com/aws/containers-roadmap/issues/766 - so this might be something becoming possible in the future.

**Comment by max-rocket-internet** [comment]
> did I misunderstand the purpose of this flag?

No, the purpose is correct, it's just that AWS won't let you create a node group without the policy attached to the role.

We could simply remove the `attach_worker_cni_policy` option node groups in this module?
