### ISSUE TITLE
Possible to update cni/coredns version similar to eksctl

### ISSUE THREAD

**Issue by rverma-jm** [terraform-aws-modules/terraform-aws-eks#747]
## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Currently the module creates a new eks cluster with the default versions of cni/coreos. It would be nice if the module provides an upgrade path to cni plugin as well as coredns. Similar functionalities are provided by eksctl which is also used for cluster management.

## Any other relevant info
Since we are already having a kubernetes provider as part of the module to apply auth config, we can leverage the same provider for an upgrade plan.

**Comment by dpiddockcmp** [comment]
Unfortunately this is near impossible for Terraform with the kubernetes provider as it currently stands. The kubernetes provider assumes that only it creates resources. There is no option to forcefully overwrite an existing resource. It will simply give you an error that a resource of that type and name already exists.

You can manually import an existing resource if you want to manage it with Terraform, however that's not really a working solution for a module that creates the cluster.

This module's maintainers have previously been hesitant about the increasing scope of the module. It's already big enough. Maintenance of resources within the cluster are up to users.

Technically the module does not create the CNI plugin or coredns. They are created by the AWS EKS service as part of bootstrapping the cluster. AWS provides no maintenance of these resources either.

**Comment by max-rocket-internet** [comment]
> This module's maintainers have previously been hesitant about the increasing scope of the module

Yes 💯

> which is also used for cluster management.

This module is not for "cluster management", it's for managing the associated AWS resources and the `aws-auth` configmap. There are much better tools for managing k8s resources, for example Helm, ksonnet/jsonnet, tonka, kustomize etc.

Anything that would be possible in this module would also be possible to do outside of this module in a nice way I think. Is there any output missing that prevents this?

Also, there are public Helm charts for coredns and the aws-vpc-cni that are stable 😃

https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni
https://github.com/helm/charts/tree/master/stable/coredns
