### ISSUE TITLE
Can't increase cluster size via TF

### ISSUE THREAD

**Issue by slimm609** [terraform-aws-modules/terraform-aws-eks#748]
# I have issues

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/10ca272e5b7ce006a721c99ef8906720ff5cd6ee/modules/node_groups/node_groups.tf#L48

This line prevents you from increasing the desired size of the cluster
 ignore_changes        = [scaling_config.0.desired_size]

You can't increase the "desired size because it is ignored.

```
~ scaling_config {
            desired_size = 3
          ~ max_size     = 3 -> 4
          ~ min_size     = 3 -> 4
        }
```

with this error.    
```
}
  ClusterName: "eks-uw2-prod-ops",
  Message_: "Minimum capacity 4 can't be greater than desired size 3",
  NodegroupName: "eks-uw2-prod-ops-node_group_a-gorgeous-liger"
}
```

## What's the expected behavior?

Be able to increase the size of the node group

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by max-rocket-internet** [comment]
![Screen Shot 2020-02-26 at 12 39 40](https://user-images.githubusercontent.com/8859277/75341596-155cdc00-5895-11ea-870a-2cb3cb030385.png) 👀👀

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#why-does-changing-the-worker-groups-desired-count-not-do-anything

**Comment by max-rocket-internet** [comment]
Essentially it's designed this way. If you want to change the desired size then you need to set it on creation or manually.
