### ISSUE TITLE
Tags for Cluster Autoscaler

### ISSUE THREAD

**Issue by paulalex** [terraform-aws-modules/terraform-aws-eks#749]
I am finding that the module does not tag the ASG's it creates with `k8s.io/cluster-autoscaler/enabled`, should it be tagging with this label? 

Was this previously added by the module to the ASG?

**Comment by max-rocket-internet** [comment]
Correct. This was removed but it's simple to add, see an example here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa/main.tf#L73-L84

**Comment by paulalex** [comment]
Thanks, I had already added it but was not sure if I needed to or had a misconfigured implementation after upgrading.

**Comment by max-rocket-internet** [comment]
Cool 🙂
