### ISSUE TITLE
Private endpoint = true, no NAT, registration does not work

### ISSUE THREAD

**Issue by BenICE** [terraform-aws-modules/terraform-aws-eks#759]
# I have issues (ohh yeah)

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
If I do the following:

- Private subnet without NAT (but enable_dns_hostnames = true and enable_dns_support = true)
- aws_eks_node_group normal setup
- aws_eks_cluster with
  - endpoint_private_access = true
  - endpoint_public_access  = true

I would assume I do not need a NAT, but the registration fails.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Standard EKS setup with the parameters from above

## What's the expected behavior?
In my opinion if the private access endpoint is activated a NAT should not be required, or am I wrong? Any guidance? Or is this simply not possible?

## Environment details

* Affected module version:
* OS: CentOS
* Terraform version: /v0.12.21

**Comment by max-rocket-internet** [comment]
I don't think it's related to this module: https://github.com/aws/containers-roadmap/issues/607
And: https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html

> Amazon EKS managed node groups can be launched in both public and private subnets. The only requirement is for the subnets to have outbound internet access. Amazon EKS automatically associates a public IP to the instances started as part of a managed node group to ensure that these instances can successfully join a cluster.

**Comment by BenICE** [comment]
I think, the linked github has nothing to do with the question. It talks about public IPs on EC2 units. I discuss the need for a NAT gateway.

The later quote is interessting. I read it as well...but I assumed it was not updated after the introduction of private endpoints. 
But I debugged a worker node and why it cannot connect to the cluster. The reason is during its init process it uses yum to init the worker node. As the yum repos are just available outside -> you need the NAT. Once the worker is initalized, you can turn of the NAT (of course not really a good idea as the managed nodes might want to talk to yum at any time).

As you said, not a module issue
