### ISSUE TITLE
Fails to create cluster and gets stuck in `wget` loop

### ISSUE THREAD

**Issue by agconti** [terraform-aws-modules/terraform-aws-eks#760]
# I have issues
I'm trying to create an EKS cluster using the boilerplate from /examples/basic. My terraform apply fails to create a cluster and gets stuck in a loop of `Still creating...` and trying to call `wget`.

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
The terraform eks modules fails to create an EKS cluster and seems to be stuck in an infinite loop trying to use `wget`. Here's an example of the logs I see after `terraform apply`.

```
module.eks.null_resource.wait_for_cluster[0]: Still creating... [1h14m11s elapsed]
module.eks.null_resource.wait_for_cluster[0] (local-exec): /bin/sh: wget: command not found
module.eks.null_resource.wait_for_cluster[0] (local-exec): /bin/sh: wget: command not found
module.eks.null_resource.wait_for_cluster[0] (local-exec): /bin/sh: wget: command not found

....

module.eks.null_resource.wait_for_cluster[0]: Still creating... [1h15m21s elapsed]
module.eks.null_resource.wait_for_cluster[0] (local-exec): /bin/sh: wget: command not found
module.eks.null_resource.wait_for_cluster[0] (local-exec): /bin/sh: wget: command not found
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Apply this terraform pulled from examples/basic:

```terraform
resource "aws_security_group" "worker_group_mgmt_one" {
  name_prefix = "worker_group_mgmt_one"
  vpc_id      = module.vpc.vpc_id

  ingress {
    from_port = 22
    to_port   = 22
    protocol  = "tcp"

    cidr_blocks = [
      "10.0.0.0/8",
    ]
  }
}

resource "aws_security_group" "worker_group_mgmt_two" {
  name_prefix = "worker_group_mgmt_two"
  vpc_id      = module.vpc.vpc_id

  ingress {
    from_port = 22
    to_port   = 22
    protocol  = "tcp"

    cidr_blocks = [
      "192.168.0.0/16",
    ]
  }
}

resource "aws_security_group" "all_worker_mgmt" {
  name_prefix = "all_worker_management"
  vpc_id      = module.vpc.vpc_id

  ingress {
    from_port = 22
    to_port   = 22
    protocol  = "tcp"

    cidr_blocks = [
      "10.0.0.0/8",
      "172.16.0.0/12",
      "192.168.0.0/16",
    ]
  }
}

module "eks" {
  source       = "terraform-aws-modules/eks/aws"
  cluster_name = var.cluster_name
  subnets      = module.vpc.private_subnets

  tags = {
    Environment = var.environment
  }

  vpc_id = module.vpc.vpc_id

  worker_groups = [
    {
      name                          = "worker-group-1"
      instance_type                 = "t2.small"
      additional_userdata           = "echo foo bar"
      asg_desired_capacity          = 2
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_one.id]
    },
    {
      name                          = "worker-group-2"
      instance_type                 = "t2.medium"
      additional_userdata           = "echo foo bar"
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_two.id]
      asg_desired_capacity          = 1
    },
  ]

  worker_additional_security_group_ids = [aws_security_group.all_worker_mgmt.id]
  map_roles                            = var.map_roles
  map_users                            = var.map_users
  map_accounts                         = var.map_accounts
}
```

## What's the expected behavior?
I expect that I'm able to create an eks cluster with the module. 

## Environment details

* Affected module version: v9.0.0
* OS: OSX
* Terraform version:
```
Terraform v0.12.21
+ provider.aws v2.50.0
+ provider.http v1.1.1
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```
## Any other relevant info

If I can give you any more relevant info, please let me know!

**Comment by robgeiner** [comment]
look at [757](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/757)

**Comment by agconti** [comment]
@robgeiner thanks for your help! the suggestion in #757 solved my issue. 💖 I read it before opening up this issue but mistakenly thought it didn't apply to me.

Should I continue to use my own custom `wait_for_cluster_cmd` in the future or will this be patched?

**Comment by robgeiner** [comment]
from the sounds of the responses to #757, there is no plan to patch it.  Folks need to either update their wget versions (preferred) or use the wait_for_cluster_cmd to regress the test. Personally, I'm using wait_for_cluster_cmd until I can validate that all the potential clients are updated.
