### ISSUE TITLE
plan shows changes when no code has been modified

### ISSUE THREAD

**Issue by icwr** [terraform-aws-modules/terraform-aws-eks#763]
# I have issues with infrastructure changes showing up when the code has not been modified. 

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

After creating an EKS cluster successfully. Immediately after (without changing code) I run plan, apply again and it shows tags being removed on vpc and subnets that were previously added during create. 

e.g.:

```
# module.network.aws_subnet.private[0] will be updated in-place
  ~ resource "aws_subnet" "private" {
      ~ tags                            = {
          - "kubernetes.io/cluster/mycluster" = "shared" -> null
            "kubernetes.io/role/internal-elb" = "1"
        }
    }

  # module.network.aws_subnet.private[1] will be updated in-place
  ~ resource "aws_subnet" "private" {
      ~ tags                            = {
          - "kubernetes.io/cluster/mycluster" = "shared" -> null
            "kubernetes.io/role/internal-elb" = "1"
        }
    }

  # module.network.aws_vpc.this[0] will be updated in-place
  ~ resource "aws_vpc" "this" {
      ~ tags                             = {
          - "kubernetes.io/cluster/mycluster" = "shared" -> null
        }
    }
```
In addition to this, I had a case where *only* adding more EKS log types to the array in my variables file caused all the above changes plus the following:

e.g.
```
  # module.eks.aws_iam_role.cluster[0] will be updated in-place
  ~ resource "aws_iam_role" "cluster" {
        arn                   = "somearn"
      ~ assume_role_policy    = jsonencode(
          ~ {
              ~ Statement = [
                    {
                        Action    = "sts:AssumeRole"
                        Effect    = "Allow"
                        Principal = {
                            Service = "eks.amazonaws.com"
                        }
                        Sid       = "EKSClusterAssumeRole"
                    },
                  - {
                      - Action    = "sts:AssumeRole"
                      - Effect    = "Allow"
                      - Principal = {
                          - AWS = "somearn"
                        }
                      - Sid       = "EKSClusterAssumeRole1"
                    },
                ]
                Version   = "2012-10-17"
            }
        )

  # module.eks.kubernetes_config_map.aws_auth[0] will be updated in-place
  ~ resource "kubernetes_config_map" "aws_auth" {
        binary_data = {}
      ~ data        = {
            "mapAccounts" = jsonencode([])
          ~ "mapRoles"    = <<~EOT
              - - groups:
              -   - system:masters
              -   rolearn: <arn_xxx>
              -   username: deploy
              - - groups:
              -   - system:masters
              -   rolearn: <arn_yyy>
              -   username: k8sadmin
              - - groups:
              -   - system:bootstrappers
              -   - system:nodes
              -   - system:node-proxier
              -   rolearn: <arn_fargate>
              -   username: system:node:{{SessionName}}
              + - rolearn: <somearn>
              +   username: system:node:{{EC2PrivateDNSName}}
              +   groups:
              +     - system:bootstrappers
              +     - system:nodes
              + 
              + - "groups":
              +   - "system:masters"
              +   "rolearn": <arn_xxx>
              +   "username": "deploy"
              + - "groups":
              +   - "system:masters"
              +   "rolearn": <arn_yyy>
              +   "username": "k8sadmin"
              + 
            EOT
```
why would any of this be affected by a simple variables change?

## If this is a bug, how to reproduce? Please include a code sample if relevant.

After creating EKS cluster, immediately run plan apply again.

## What's the expected behavior?

No changes show up.

## Environment details

* Affected module version: 9.0.0
* OS: osx 10.14
* Terraform version: 12.21

**Comment by daroga0002** [comment]
your difference in plan is caused because EKS (in general this requirement incoming from K8s upstream)  require a special tags on subnets which are documented here:
https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html

if those tags dont exist AWS EKS will create them automatically (so you don`t require adding them to your initial VPC terraform code), but later this is causing this plan difference. Removing those tags by applying plan can cause problems as EKS will loose knowledge which subnets can use and break it.

To workaround it you can use lifecycle in terraform VPC code which will ignore such changes or simply include those tags in code which is creating your VPC and subnets.

If you are using VPC module from https://registry.terraform.io/modules/terraform-aws-modules/vpc/ then you can make it similar to:
```
locals {
  eks_tags              = { "kubernetes.io/cluster/kubernetes" = "shared" }
  eks_internal_elb_tags = { "kubernetes.io/role/internal-elb" = "1" }
  eks_external_elb_tags = { "kubernetes.io/role/elb" = "1" }
}


module "vpc" {
  # https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/2.25.0
  source                       = "terraform-aws-modules/vpc/aws"
  version                      = "2.25.0"
  name                         = "kubernetes"
  cidr                         = var.vpc_cidr
  azs                          = local.availability_zones
  private_subnets              = var.subnets[*][0]
  public_subnets               = var.subnets[*][1]
  vpc_tags                     = local.eks_tags
  public_subnet_tags           = merge(local.eks_tags, local.eks_external_elb_tags)
  private_subnet_tags          = merge(local.eks_tags, local.eks_internal_elb_tags)
  tags                         = local.common_tags
}
```

**Comment by icwr** [comment]
i had the external/internal tags but somehow i missed the _shared_ tags. thanks for this! i think this will address that issue but still concerned about the other changes that showed up after adding the additional log types.

**Comment by dpiddockcmp** [comment]
This is the section of the aws-auth that's actually changing:
```
              - - groups:
              -   - system:bootstrappers
              -   - system:nodes
              -   - system:node-proxier
              -   rolearn: <arn_fargate>
              -   username: system:node:{{SessionName}}
              + - rolearn: <somearn>
              +   username: system:node:{{EC2PrivateDNSName}}
              +   groups:
              +     - system:bootstrappers
              +     - system:nodes
```
Are you using fargate? Looks like you're saying the fargate role is being replaced by the module's default EC2 node role. I wonder if there's some special fargate magic we need to add to the module?

Not sure about the `AssumeRole` section that is being removed. "somearn" isn't very descriptive 🙂 . Is it also fargate related?

**Comment by icwr** [comment]
correct, using fargate. sorry, i could have obscured those better but iirc that "somearn" was not related to fargate. i've tried reproducing this again and not having luck. if i run into it again i will let you all know. thanks again for the help.
