### ISSUE TITLE
Feature request: Support for envelope encryption for secrets with AWS KMS

### ISSUE THREAD

**Issue by kuuji** [terraform-aws-modules/terraform-aws-eks#767]
## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## Description

Amazon just released support for envelope encryption for secrets using KMS.  -> https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-eks-adds-envelope-encryption-for-secrets-with-aws-kms/

It looks like the terraform resource has been updated and already supports it -> https://www.terraform.io/docs/providers/aws/r/eks_cluster.html#encryption_config-1

This feature request is to add support in this module. I'm willing to take a stab at it since it looks pretty straightforward, just wanted to make sure no one is already working on this before I give it a try.

Edit : Not sure if it'll be that straightforward since the `encryption_config` parameter is an optional block that includes a required block. 
The only solution I can think of is to duplicate the cluster resource and add `encryption_config` to the new one. And control which one is used with a count and a ternary. Open to suggestions for a better way.
Edit 2 : I guess I could use a for_each and a dynamic block for that.

**Comment by barryib** [comment]
Resolved by https://github.com/terraform-aws-modules/terraform-aws-eks/pull/772
