### ISSUE TITLE
State of worker group launch templates stored with keys instead of indices

### ISSUE THREAD

**Issue by isaaguilar** [terraform-aws-modules/terraform-aws-eks#778]
# I have issues...

changing/adding/updating worker groups 

It would be nice, particularly for worker/node groups, to store state using keys instead of indices. I've run into issues with state wanting to destroy resources when indices get re-ordered. This issue is already documented in this faq https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#how-do-i-safely-remove-old-worker-groups 

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [x] kudos, thank you, warm fuzzy

## Are you able to fix this problem and submit a PR? Link here if you have already.

No PR, but I have made some changes in a fork that suited my needs. I did, however, have to remove a feature (namely `data.aws_iam_instance_profile.custom_worker_group_launch_template_iam_instance_profile`).]. 

Here's my changes: https://github.com/terraform-aws-modules/terraform-aws-eks/compare/master...isaaguilar:day2-ready-launch-templates

This module was a great jumping off point. I hope the changes could be used in some future releases. 

## Environment details

* Affected module version:
* OS: osx
* Terraform version: 0.12.23

**Comment by barryib** [comment]
Duplicates https://github.com/terraform-aws-modules/terraform-aws-eks/issues/476

You should also follow https://github.com/terraform-aws-modules/terraform-aws-eks/issues/774
