### ISSUE TITLE
Some automation for changelog management

### ISSUE THREAD

**Issue by max-rocket-internet** [terraform-aws-modules/terraform-aws-eks#781]
It would be good to:
- Have it managed by a template or something similar
- Have a github action fail if it's not updated so we don't have to keep telling people

Maybe we try this? https://github.com/git-chglog/git-chglog

**Comment by antonbabenko** [comment]
I like `git-chglog` very much and using it in all other projects. I would really appreciate if you update this repo to use `Makefile` like this - https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/Makefile

Currently, my release command for all other modules is:
```
make changelog && git commit -a -m "Updated CHANGELOG" && git push && make release
```

**Comment by max-rocket-internet** [comment]
People still using Makefiles?? 🤔

**Comment by barryib** [comment]
I tried that few weeks ago and I totally messed up the changelog. I wasn't able to manage properly notes and breaking changes.

Furthermore, how can we continue to support the old changelog (with past release notes) with the new one (generated with git-chglog) ?

> People still using Makefiles?? 🤔

I do 😊

**Comment by barryib** [comment]
@antonbabenko How do you manage changelog items ? Do you define convention for commits and PR titles ?

**Comment by antonbabenko** [comment]
Yes, Makefiles are everywhere :)

I don't manage changelog items but I do the following:
1. Always squash commits during PR merge
2. Have informative git commit message because it will end up in CHANGELOG automatically

**Comment by max-rocket-internet** [comment]
> Always squash commits during PR merge

You can just enforce this in the repo settings

**Comment by js-timbirkett** [comment]
Hey 👋 

git-chglog is great when combined with conventional commits.

At my workplace I've started using it with a config that dumps all non compliant commits in their own section. Example:
![Screenshot 2020-03-12 at 11 36 52 AM](https://user-images.githubusercontent.com/57101177/76517764-d3679480-6455-11ea-839b-e69cd97abc2a.png)

I'm experimenting with curating commits at PR time using "squash and merge" to allow me to write a nice commit message at that point that will appear in the CHANGELOG.md

Something worth notingg is that git-chglog rewrites the entire CHANGELOG every time it's run so you can play around with the configuration / template without worrying about breaking things irrevocably.

**Comment by max-rocket-internet** [comment]
That looks nice @js-timbirkett 👍
