### ISSUE TITLE
Generated config not saved to correct output path

### ISSUE THREAD

**Issue by stevefaro** [terraform-aws-modules/terraform-aws-eks#79]
# I have issues with when generated config-map is output to a folder

## I'm submitting a...

[ * ] bug report

## What is the current behavior?
The generated config-map-aws-auth***.yaml and kubeconfig.yaml file is saved to the root folder, the file name is appended with the value of the config_output_path variable

## If this is a bug, how to reproduce? Please include a code sample if relevvant.
Create a cluster with a custom config_output_path

## What's the expected behavior?
The config-map-aws-auth***.yaml file should be saved to the config_output_path

## Are you able to fix this problem and submit a PR? Link here if you have already.

aws_auth.tf 
line 3 - missing / 
filename = "${var.config_output_path}/config-map-aws-auth_${var.cluster_name}.yaml"

line 9 - missing /
command = "kubectl apply -f ${var.config_output_path}/config-map-aws-auth_${var.cluster_name}.yaml --kubeconfig ${var.config_output_path}/kubeconfig_${var.cluster_name}"

kubectl.tf
line 3 - missing /
 filename = "${var.config_output_path}/kubeconfig_${var.cluster_name}"

**Comment by hobbsh** [comment]
What does your module call look like? I use a relative path for `config_output_path` and dont have any issues.

**Comment by hobbsh** [comment]
You need a trailing slash. According to the variable documentation:

```
Determines where config files are placed if using configure_kubectl_session and you want config files to land outside the current working directory. Should end in a forward slash / .
```

**Comment by brandoconnor** [comment]
@hobbsh , I owe you a beer.
