### ISSUE TITLE
Broader support of kubelet flags

### ISSUE THREAD

**Issue by perryao** [terraform-aws-modules/terraform-aws-eks#80]
I have a need to to taint nodes and did a quick implementation to support passing taints to the register-with-taints kubelet flag. Take a look here: https://github.com/perryao/terraform-aws-eks/commit/435f62e736554a7615794947369cd85ae992628c.

But figured it might be worth talking through a solution that supports more of the flags without the need for one-off PRs for each one.

What do you think?

Flag docs here: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by perryao** [comment]
@brandoconnor on this flag, the docs say `Register the node with the given list of taints`. This would be used to taint nodes in a way that require pods to declare tolerations in order to run on those nodes. They describe tainting existing nodes here:  https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/. But my understanding is that this flag to kubelet allows the node to be tainted when it's registered.

My only thought on making it "better" would be your map-embedded variable idea for common args, but updating userdata.sh.tpl in a way that loops over key-values and appends args to kubelet. Instead of needing to duplicate this check (https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/templates/userdata.sh.tpl#L13) for every possible argument. 

Maybe passing the arguments as JSON and using jq to loop over them?

Or possibly converting the terraform map to a bash associative array and looping over keys-values there? Not sure if terraform interpolation would allow this yet though.

**Comment by max-rocket-internet** [comment]
We just merged a PR https://github.com/terraform-aws-modules/terraform-aws-eks/pull/100 to follow the new AWS user-data script. This includes `kubelet_extra_args`. I think this solves this issue.
