### ISSUE TITLE
Cluster Autoscaler with IRSA

### ISSUE THREAD

**Issue by acarsercan** [terraform-aws-modules/terraform-aws-eks#801]
Hi,

Having problems with enabling Cluster autoscaler using IRSA with the module

## I'm submitting a...

* [*] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!

## What is the current behavior?
Running example here - https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/irsa

But seen error
`E0317 11:46:48.531388       1 aws_manager.go:261] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
	status code: 403, request id: ccab18b4-4786-49a4-9168-d63c2dadccd4`

`F0317 11:46:48.531413       1 aws_cloud_provider.go:376] Failed to create AWS Manager: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity`

Not sure what I missed out

## What's the expected behavior?
Cluster autoscaler to work with existing cluster and ASG

Module version 10.0
EKS 1.15

**Comment by acarsercan** [comment]
Installed CA in wrong namespace

**Comment by djesionek** [comment]
Hi @acarsercan, could you share a bit more information about which was the right namespace at the end? I get the same issue deploying the CA to the kube-system namespace

**Comment by acarsercan** [comment]
I hit the same error although the namespace is correct,not sure what is causing it

**Comment by max-rocket-internet** [comment]
The namespace is used in the assume role policy. So if the namespace in the policy does not match the namespace of the service account then it won't work.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa/irsa.tf#L8

**Comment by djesionek** [comment]
I deployed the autoscaler into kube-system which is also the value for local.k8s_service_account_namespace as in the example. It worked for me using the (deprecated) chart cluster-autoscaler from https://kubernetes-charts.storage.googleapis.com apparently. Now using the autoscaler repo https://kubernetes.github.io/autoscaler with the chart cluster-autoscaler-chart i get this error.

I noticed that the values format changed a bit since so I adjusted the only part I saw was different from the example shown here:
`rbac:
  create: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::<AWS_ACCOUNT_ID>:role/cluster-autoscaler"`

But that didn't change much unfortunately, so any other ideas on what might be wrong?

@acarsercan have you another solution that works for you now since this ticket wasn't followed up on by you?

**Comment by acarsercan** [comment]
As per my reply earlier, I have not found a solution

**Comment by max-rocket-internet** [comment]
> so any other ideas on what might be wrong?

Then you need to work out what the difference between the 2 charts is.

1. The role assume role policy must match the serviceAccount create by the chart
2. The role ARN annotation on the serviceAccount has to match a real role
3. The OIDC details must be correct
4. The app inside the container must be using a recent version of the AWS SDK so it supports the new "assume role with web identity" flow

That's about all I can think of 🙂

**Comment by toneill818** [comment]
@djesionek I had a similar issue when using the new chart. It appears the serviceAccount name changed and my OIDC was expecting the old name. Setting it back using rbac.serviceAccount.name worked for me.

**Comment by acarsercan** [comment]
Anyone got a working example?

**Comment by brunzefb** [comment]
Hi, I'm running into the same issue with a brand new eks 1.21 cluster.  The solution is a bit  complicated, but seems to work
First you need the policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeTags",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "ec2:DescribeLaunchTemplateVersions",
                "sts:AssumeRoleWithWebIdentity",
                "sts:GetFederationToken"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```
These are the permissions the autoscaler needs, nothing new here.  Note the policy name.
Next create a role.  The role has to have the policy (above) attached.  In the 'Trust relationships' tab, my trusted entity looks like this:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::ACCOUNT:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/DEADBEEF5D4FFC1E3D032B5A2BCE313"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-2.amazonaws.com/id/DEADBEEF5D4FFC1E3D032B5A2BCE313:sub": "system:serviceaccount:kube-system:aws-cluster-autoscaler"
                }
            }
        }
    ]
}
```
OK, where do your get the `arn:aws:iam::ACCOUNT:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/DEADBEEF5D4FFC1E3D032B5A2BCE313` from?   Go to the AWS console, to the EKS, pick your cluster, got to the configuration tab and select details. The OpenID Connect provider URL is listed there. If its not listed, follow the instructions [here](https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html).   Or you can use bash/aws sdk
```
function fix_oidc_thumbprints() {
  local dnsname="oidc.eks.$AWS_REGION.amazonaws.com"
  openssl s_client \
            -servername $dnsname \
            -showcerts \
            -connect $dnsname:443 < /dev/null  2> /dev/null \
            | sed -n '/BEGIN\ CERTIFICATE/,/END\ CERTIFICATE/ p' \
            | sed -n '/END CERTIFICATE/,$ p' \
            | tail -n +2 \
            | tail -n 26 > certificate.crt
  local thumbprint=$(openssl x509 -in certificate.crt -fingerprint -noout | \
    awk '{split($0,a,"="); print a[2]}' | sed 's/://g')
  rm -rf certificate.crt
  echo $thumbprint
  local arn=$(aws iam list-open-id-connect-providers | \
    jq -r  '.OpenIDConnectProviderList[].Arn' | grep $AWS_REGION | head -n 1)
  aws iam update-open-id-connect-provider-thumbprint  \
    --open-id-connect-provider-arn $arn  \
    --thumbprint-list $thumbprint
}
```
I have a bash function for the deployment of the autocluster too, in case like you want to automate it.
```
function deploy_cluster_autoscaler() {
  # From https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html
  fix_oidc_thumbprints
  cd $DIRECTORY
  cd ../../../sciex-devops-cluster-autoscaler/helm3/cluster-autoscaler
  helm3 dependency build
  local role_name="amazon-eks-autoscaler-role-$RANDOM_SUFFIX"
  local annotationArn=$(aws iam list-roles | \
                        jq -r --arg role_name "$role_name" '.[][] | select(.RoleName==$role_name).Arn')
  echo $annotationArn
  local serviceaccountname="aws-cluster-autoscaler"
  cluster_version=$(yq eval '.eks-cluster-version' $DIRECTORY/../environment.yaml)
  cluster_version_with_v=$(printf "v%s.0" $cluster_version)

  helm3 upgrade --install \
    aws-cluster-autoscaler \
    ./ \
    --values values.yaml  \
    --set autoDiscovery.clusterName=$EKS_CLUSTER_NAME \
    --set "autoDiscovery.tags={k8s.io/cluster-autoscaler/enabled, k8s.io/cluster-autoscaler/$EKS_CLUSTER_NAME}" \
    --set awsRegion=$AWS_REGION \
    --set 'podAnnotations.iam\.amazonaws\.com/role='${annotationArn} \
    --set 'rbac.serviceAccount.annotations.eks\.amazonaws\.com/role-arn'="ingress-controller-role-$RANDOM_SUFFIX" \
    --set rbac.serviceAccount.serviceAccountName=$serviceaccountname \
    --set image.tag=$cluster_version_with_v \
    --namespace kube-system \
    --debug
}
```
Good luck -- this stuff is not simple.

**Comment by bryantbiggs** [comment]
@brunzefb we have a new IAM module for use with EKS that provides a lot of these integrations and policies out of the box FYI

https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-role-for-service-accounts-eks

```hcl
module "cluster_autoscaler_irsa_role" {
  source    = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version   = " ~> 4.14"

  role_name                        = "cluster-autoscaler"
  attach_cluster_autoscaler_policy = true
  cluster_autoscaler_cluster_ids   = [module.eks.cluster_id]

  oidc_providers = {
    ex = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:cluster-autoscaler"]
    }
  }

  tags = local.tags
}
```

Plus we have a working example for deploying the cluster autoscaler using the EKS module, the IAM sub-module, and the cluster autoscaler helm chart https://github.com/terraform-aws-modules/terraform-aws-eks/blob/4898bf326d7019fdd9cc33b533a226d6ef3a0f52/examples/irsa_autoscale_refresh/charts.tf#L9-L78
