### ISSUE TITLE
well done work

### ISSUE THREAD

**Issue by b2cbre** [terraform-aws-modules/terraform-aws-eks#813]
## I'm submitting a...

* [x] kudos, thank you, warm fuzzy

## What is the current behavior?

This module has been unexpectedly helpful in our team's efforts to prototype EKS cluster & node pool management with Terraform. I say unexpectedly because it addresses many nuances, even for the node groups feature, that we were not aware of prior to utilizing this module.

So thank you.

**Comment by max-rocket-internet** [comment]
Thank you @b2cbre
