### ISSUE TITLE
Get the security group of aws_eks_node_group as an output.

### ISSUE THREAD

**Issue by sa-mao** [terraform-aws-modules/terraform-aws-eks#816]
# I have issues
Hello and thanks for your help :)
How would you get access to the security group attached with the aws_eks_node_group resource created by this module. Terraform's documentation doesn't seem to mention anything about this. 
## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## Environment details

* Affected module version: 8.2.0
* OS: MacOS.
* Terraform version: Terraform v0.12.24

**Comment by ratheo** [comment]
Node group workers use the EKS cluster security group. There is a PR to address this issue. https://github.com/terraform-aws-modules/terraform-aws-eks/pull/792

**Comment by fregatte** [comment]
Hi guys,
as I can see, the PR #792 has been closed without merge. Are there other methods to get the right security group for aws_eks_node_group?

**Comment by max-rocket-internet** [comment]
You could use a data resource for `security_group`: https://www.terraform.io/docs/providers/aws/d/security_group.html

Use an output as the `name` or filter by tags that are unique to your ASG 🙂

**Comment by kostas-rs** [comment]
> You could use a data resource for `security_group`: https://www.terraform.io/docs/providers/aws/d/security_group.html
> 
> Use an output as the `name` or filter by tags that are unique to your ASG 🙂

That's what i am currently doing to access them but this doesn't work during the first apply because the security group doesn't exist yet. It would be great to have it as module output.

**Comment by calvinbui** [comment]
A workaround I'm using at the moment:
```
data "aws_eks_cluster" "main" {
  name = module.eks.cluster_id
}

output "cluster_security_group_id" {
  value = data.aws_eks_cluster.main.vpc_config.0.cluster_security_group_id
}
```

**Comment by barryib** [comment]
Closing. Duplicates https://github.com/terraform-aws-modules/terraform-aws-eks/issues/799.
