### ISSUE TITLE
Error: Get http://localhost/.../aws-auth: dial tcp 127.0.0.1:80: connect: connection refused

### ISSUE THREAD

**Issue by nick4fake** [terraform-aws-modules/terraform-aws-eks#817]
As soon as I try to refresh state after initial cluster creation it fails with k8s config map update:
````
Error: Get http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth: dial tcp 127.0.0.1:80: connect: connection refused
````

Terraform version: 0.12.24
Module version: v10.0.0
Kubernetes provider: 1.11.1

Provider config:
````
provider "kubernetes" {
  host                   = data.aws_eks_cluster.this.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.this.token
  load_config_file = false
  version = "~> 1.11"
}
````

There are no "KUBE*" environment variables.

Relevant issues:
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/733
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/713

I've tried everything possible:
* Completely deleting ~/.kube folder
* Setting load_config_file to true/false
* Setting config_path to missing or existing kubeconfig file
* Creating resources one by one

**Comment by barryib** [comment]
@nick4fake Are you sure you're using the kubernetes provider 1.11.1 ? Can you please use `>= 1.11.1` as version constraint.

```hcl
provider "kubernetes" {
  host                   = data.aws_eks_cluster.this.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.this.token
  load_config_file = false
  version = ">= 1.11.1"
}
```

**Comment by nick4fake** [comment]
@barryib yep
![image](https://user-images.githubusercontent.com/1065993/77451787-ce172c00-6dfd-11ea-8888-233da72c8e58.png)

**Comment by barryib** [comment]
Ok. Can you please share your eks cluster datasources configuration `data.aws_eks_cluster*` and test this with the version `1.10` of the kubernetes provider ?

**Comment by nick4fake** [comment]
I've originally tested it with 1.10, upgraded to 1.11.1 only to check if issue still preset.

As for datasource - I'm sorry, should have removed that before posting. Anyway, this is the config I've tried the last time:
![image](https://user-images.githubusercontent.com/1065993/77461908-f9087c80-6e0b-11ea-8bcd-bfd55e1276a0.png)

Still the same issue after removing all depends_on:
![image](https://user-images.githubusercontent.com/1065993/77462054-3240ec80-6e0c-11ea-80fb-be41a5b4ca84.png)

Let me just delete everything and start from scratch once again,

**Comment by adri** [comment]
Disclaimer: I'm a bit of a terraform noob. Also running into this issue. I'm using Terraform Cloud and created a cluster using version 1.11.1. After I was done with some tests I wanted to delete the cluster and I removed the definitions. During the `plan` phase I ran into this error `Error: Get http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth: dial tcp 127.0.0.1:80: connect: connection refused`.  

I manually deleted the EKS cluster and ASGs in AWS. Now when I want re-create the cluster I get errors like this. Is there anyway I can get out of this situation? 

```
Error: name must not be empty, got 

  on eks-cluster.tf line 5, in data "aws_eks_cluster" "cluster":
   5: data "aws_eks_cluster" "cluster" {



Error: name must not be empty, got 

  on eks-cluster.tf line 9, in data "aws_eks_cluster_auth" "cluster":
   9: data "aws_eks_cluster_auth" "cluster" {



Error: Invalid index

  on .terraform/modules/eks/terraform-aws-eks-11.0.0/data.tf line 74, in data "template_file" "kubeconfig":
  74:     endpoint                  = aws_eks_cluster.this[0].endpoint
    |----------------
    | aws_eks_cluster.this is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/eks/terraform-aws-eks-11.0.0/data.tf line 75, in data "template_file" "kubeconfig":
  75:     cluster_auth_base64       = aws_eks_cluster.this[0].certificate_authority[0].data
    |----------------
    | aws_eks_cluster.this
```

**Comment by adri** [comment]
Eventually I had to:
1. Locally configure terraform to connect to the remote state on Terraform Cloud
2. Remove the ConfigMap state
    ```
    terraform state rm 'module.eks.kubernetes_config_map.aws_auth[0]'
    ```
3. Commit again the removal of the code (just delete file with the EKS definitions)

Now all resources got destroyed.

**Comment by sc250024** [comment]
I'm running into this same issue, but for slightly separate reasons. I am wanting to put this `terraform-aws-eks` module into a deployment pipeline for easy cluster updates. I have the `main.tf` file set to the following:

```hcl
provider kubernetes {
  config_path      = module.eks.kubeconfig_filename
  load_config_file = true
}

module eks {
  cluster_enabled_log_types     = var.cluster_enabled_log_types
  cluster_name                  = var.cluster_name
  enable_irsa                   = true
  manage_aws_auth               = true
  map_accounts                  = var.map_accounts
  map_roles                     = var.map_roles
  map_users                     = var.map_users
  source                        = "terraform-aws-modules/eks/aws"
  subnets                       = var.private_subnets
  version                       = "11.0.0"
  vpc_id                        = var.vpc_id
  worker_groups                 = module.common_worker_groups.worker_groups
  worker_groups_launch_template = module.common_worker_groups.worker_groups_launch_template
  write_kubeconfig              = true

  cluster_encryption_config = [
    {
      provider_key_arn = aws_kms_key.eks.arn
      resources        = ["secrets"]
    }
  ]
}
```

When I _initially_ create the cluster, the provider loads the file that was just created, and since I have `manage_aws_auth` set to `true`, the Kubernetes provider uses the `kubeconfig` output to actually create the `ConfigMap` object in Kubernetes.

However, once the initial creation is completed, and the `kubeconfig` state is in Terraform, all subsequent runs fail because the `kubeconfig` file is no longer there anymore. That's when I receive the error in this issue title.

**Comment by sc250024** [comment]
**UPDATE**: I just tried the following block for the `kubernetes` provider. Before implementing this it failed, but with this new config, it seems to work on the second approach after initial creation:

```hcl
provider kubernetes {
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  host                   = module.eks.cluster_endpoint
  load_config_file       = false

  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    args        = ["token", "--cluster-id", module.eks.cluster_id]
    command     = "aws-iam-authenticator"
  }
}
```

@barryib Maybe the module could set an `output` for the `exec` block? That way someone wouldn't have to re-create it like I just did?

**Comment by barryib** [comment]
@sc250024 you already have the [`kubeconfig `](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/outputs.tf#L56) output which outputs the rendered config it self. You can write it in file with [local_file](https://www.terraform.io/docs/providers/local/r/file.html).

But using [auth token](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/basic/main.tf#L26-L40) instead of kubeconfig doesn't work for you ?

**Comment by sc250024** [comment]
> @sc250024 you already have the [`kubeconfig`](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/outputs.tf#L56) [](/terraform-aws-modules/terraform-aws-eks/blob/HEAD@{2020-04-22T20:18:53Z}/outputs.tf#L56) output which outputs the rendered config it self. You can write it in file with [local_file](https://www.terraform.io/docs/providers/local/r/file.html).
> 
> But using [auth token](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/basic/main.tf#L26-L40) [](/terraform-aws-modules/terraform-aws-eks/blob/HEAD@{2020-04-22T20:18:53Z}/examples/basic/main.tf#L26-L40) instead of kubeconfig doesn't work for you ?

@barryib That's ... actually much easier. Well I feel like an asshole! Disregard my previous comments.

**Comment by barryib** [comment]
@sc250024 😂 it's ok. It happens sometimes.

@nick4fake Are you still experiencing this issue ? Can we close it ?

**Comment by slotlocker2** [comment]
Guess this is because the Kubernetes provider might get initialised before the actual EKS resources are created. 
From https://www.terraform.io/docs/providers/kubernetes/index.html

`IMPORTANT WARNING When using interpolation to pass credentials to the Kubernetes provider from other resources, these resources SHOULD NOT be created in the same apply operation where Kubernetes provider resources are also used. This will lead to intermittent and unpredictable errors which are hard to debug and diagnose. The root issue lies with the order in which Terraform itself evaluates the provider blocks vs. actual resources. Please refer to this section of Terraform docs for further explanation.`

**Comment by st33v** [comment]
I get this error using v11.0.0 and no `provider "kubernetes"` block. I get the error from the module itself. Is there an external dependency that is not documented?

It works on my laptop but when I run terraform with this module in my pipeline, in a docker container, I get the error. 🤷

**Comment by dpiddockcmp** [comment]
@st33v if you have no kubernetes provider block then the kubernetes provider will use your default kube config file in `~/.kube/config` for communicating to a kubernetes cluster. Or the `KUBE_CONFIG` environment variable. Not very useful for configuring the cluster just created by the module.

Configuration samples for the kubernetes block are documented in the main README for the module and in all the examples.

**Comment by blongman-snapdocs** [comment]
Running into much the same errors as @adri, but in my case it all works until I try and run it in jenkins.

My configuration looks like this:

```
data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = ">= 1.11.1"
}

provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.cluster.token
    load_config_file       = false
  }
  version = "~> 1.2"
}
```
And I get this as output:

```
Error: name must not be empty, got 

  on config.tf line 50, in data "aws_eks_cluster" "cluster":
  50: data "aws_eks_cluster" "cluster" {



Error: name must not be empty, got 

  on config.tf line 54, in data "aws_eks_cluster_auth" "cluster":
  54: data "aws_eks_cluster_auth" "cluster" {



Error: Invalid index

  on .terraform/modules/eks/terraform-aws-eks-11.0.0/data.tf line 74, in data "template_file" "kubeconfig":
  74:     endpoint                  = aws_eks_cluster.this[0].endpoint
    |----------------
    | aws_eks_cluster.this is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/eks/terraform-aws-eks-11.0.0/data.tf line 75, in data "template_file" "kubeconfig":
  75:     cluster_auth_base64       = aws_eks_cluster.this[0].certificate_authority[0].data
    |----------------
    | aws_eks_cluster.this is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/eks/terraform-aws-eks-11.0.0/data.tf line 82, in data "template_file" "kubeconfig":
  82:       formatlist("\"%s\"", ["token", "-i", aws_eks_cluster.this[0].name]),
    |----------------
    | aws_eks_cluster.this is empty tuple

The given key does not identify an element in this collection value.

make: *** [Makefile:6: prod-east-blue-20200420-plan] Error 1
script returned exit code 2
```

I did a little testing and changed one to be like this:

```
data "aws_eks_cluster" "cluster" {
  name = "eks_${module.eks.cluster_id}"
}
```

And got output like:

```
Error: error reading EKS Cluster (eks_): ResourceNotFoundException: No cluster found for name: eks_.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "ec897e37-e670-4ac1-8879-5158ea81d75b"
  },
  Message_: "No cluster found for name: eks_."
}
```

I checkout S3 for the state, and I don't see the string "cluster_id" anywhere, so my mental model of terraform needs to be updated somewhere, but I'm really lost as to why this worked in my standalone template, and in my template prepped for jenkins, but not when run by jenkins itself.  Any ideas?

**Comment by nick4fake** [comment]
I don't understand why this is closed. I have k8s provider configured and still randomly get this issue. The FAQ update PR does not help as it just states "set your k8s provider config" that we already have.

**Comment by arielvinas** [comment]
I think this is a problem with the k8s provider it self... I have it configured correctly and randomly fails to connect:

https://github.com/hashicorp/terraform/issues/4149
https://github.com/hashicorp/terraform/issues/4149

I found a comment in the provider Golang code that explains the problem:
https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/provider.go#L244

**Comment by tomaszszlek** [comment]
Hi,
I had exactly the same issues. One was that on Jenkins I had error that cluster id wasn't found, the other was that localhost was used for kubernetes API. What is more, in my case I have two different eks clusters.

I was able to solve this issue by doing two changes:
1. I configured kubernetes provider in a bit different way than in examples:

`data "aws_eks_cluster_auth" "cluster" {
  name = module.eks_eu.cluster_id
}

provider "kubernetes" {
  host                   = module.eks_eu.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks_eu.cluster_certificate_authority_data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = ">=1.11.0"
  alias   = "eu"
}`
2. I passed down kubernetes provider into EKS module:

```
module "eks_eu" {
  providers = {
    aws = aws.eu
    kubernetes = kubernetes.eu
  }
```

Hope this will help someone.

**Comment by calvinbui** [comment]
I had this issue after upgrading from Terraform 0.12 to 0.13 and the module from v12 to v13.

I fixed it by running ```terraform state replace-provider 'registry.terraform.io/-/kubernetes' 'registry.terraform.io/hashicorp/kubernetes'```

**Comment by wkhatch** [comment]
> Had to do resource targeting to get it working which might not work with Terraform Cloud.

it definitely isn't working in terraform cloud

**Comment by marcodv** [comment]
Hello, this is still happening randomly.

```
│ Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp [::1]:80: connect: connection refused
│
│   with module.k8s.kubernetes_config_map.aws_auth,
│   on ../../modules/eks/main.tf line 70, in resource "kubernetes_config_map" "aws_auth":
│   70: resource "kubernetes_config_map" "aws_auth" {
```

I'm using 
```
terraform -version
Terraform v1.1.7
on darwin_arm64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.8.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.9.0
```


I've deleted the configMap for EKS with the following command and then re create, but I still get the same issue

`
terraform state rm module.k8s.kubernetes_config_map.aws_auth[0]
`

in the provider section I've this

```
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}

provider "kubectl" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  // the following config fix this issue
  //https://github.com/gavinbunney/terraform-provider-kubectl/issues/35
  load_config_file = false
}
```

What you guys suggest to do ?

Cheers

**Comment by dmitry-mightydevops** [comment]
I have experienced the same issue by upgrading the module from 
```
version = "17.24.0" 
```
to
```
version = "18.21.0"
```

### errors:

```
│ Error: Get "http://localhost/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/system:master": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with module.eks_cluster.kubernetes_cluster_role_binding.system-master,
│   on ../_modules/kubernetes/roles.tf line 1, in resource "kubernetes_cluster_role_binding" "system-master":
│    1: resource "kubernetes_cluster_role_binding" "system-master" {
│ 
╵
╷
│ Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with module.eks_cluster.module.eks_cluster.kubernetes_config_map.aws_auth[0],
│   on .terraform/modules/eks_cluster.eks_cluster/main.tf line 414, in resource "kubernetes_config_map" "aws_auth":
│  414: resource "kubernetes_config_map" "aws_auth" {
│ 

```

changing `manage_aws_auth_configmap = true` to false had no effect.
