### ISSUE TITLE
Destruction of worker ASG blocked by `protect_from_scale_in = true`

### ISSUE THREAD

**Issue by b2cbre** [terraform-aws-modules/terraform-aws-eks#818]
# I have issues

Unable to destroy a worker ASG or the cluster because of  `protect_from_scale_in = true`. This of course can be changed but that is generally undesirable because one expects that if you can create it you can also destroy it without changing the configuration. :)

I'm willing to assist with work on this but figured I'd open a ticket in case someone had thoughts on how to resolve this without making a PR and without changing `protect_from_scale_in` to `false` when we want to destroy or recreate a worker ASG.

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Unable to destroy a worker ASG due to:
> Error: Error draining autoscaling group: Group still has 1 instances

AWS console shows on the ASG activity history:
> Could not scale to desired capacity because all remaining instances are protected from scale-in.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Set `protect_from_scale_in` to `true` on this repo, create a cluster, then try to destroy it with `terraform destroy`.

## What's the expected behavior?

Destruction without code change or updating `protect_from_scale_in`.

## Environment details

* Affected module version: commit 49b0667cd91e15f7c98dba67ad7e5aa5a6f54b5d
* OS: linux
* Terraform version: 0.12.24

## Any other relevant info

None that I can think of at this time.

**Comment by max-rocket-internet** [comment]
It defaults to `false` so I don't get the problem? If you want to destroy without issues then don't set it to `true`?

**Comment by b2cbre** [comment]
Thank you for considering this with me. My intent in opening this issue is not to attack but to discuss.

I suppose I missed where this behavior is documented in the module for this feature. Where may I find that? When digging into this it seems this variable is directly passed to the provider so perhaps that is where I missed the importance of checking the provider's documentation on the variables in `workers_group_defaults` and `workers_group_defaults_defaults`. Perhaps it is profitable for that connection to be noted in the README, FAQ, or comments of `local.tf`.

If the problem is that I opened a ticket after changing defaults then why was #812 not treated the same way?

Contributing guidelines are where? I'd rather not create problems but contribute to solutions. The readme says "Full contributing guidelines are covered here." which links to https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/CONTRIBUTING.md which is a 404 in my experience and I don't see a 'CONTRIBUTING.md' in `/`.

**Comment by dpiddockcmp** [comment]
#812 was a bug in the module caused by a lack of dependency ordering. It was a simple fix.

This issue is about an AWS feature and emergent behaviour of the terraform AWS provider, not something the module can fix.

This issue has come up at least a couple times before:
- #176 
- #288 

There is an open issue against the provider: https://github.com/terraform-providers/terraform-provider-aws/issues/5278

**Comment by b2cbre** [comment]
Awesome! Closing this cause it's pointless to have a duplicate issue.

Thank you, I completely forgot to search existing issues (closed and open).

**Comment by max-rocket-internet** [comment]
> Thank you for considering this with me. My intent in opening this issue is not to attack but to discuss.

We are all here to discuss, don't worry 💛

> There is an open issue against the provider: terraform-providers/terraform-provider-aws#5278

This I was not aware of. Interesting. Thanks @dpiddockcmp
