### ISSUE TITLE
EKS encryption config argument error

### ISSUE THREAD

**Issue by ankit-nclouds** [terraform-aws-modules/terraform-aws-eks#821]
I'm using aws provider with terraform version 0.12.24 to provision network and compute resources. I added this block to enable encryption config as per https://www.terraform.io/docs/providers/aws/r/eks_cluster.html#encryption_config

> encryption_config = {
>    provider = {
>      key_arn = aws_kms_key.ekscrypt.arn
>    }
 >   resources = ["secrets"]
>  }

I'm getting this error stating that the argument is unsupported.
> Error: Unsupported argument
>  on modules/eks/main.tf line 105, in resource "aws_eks_cluster" "k8s":
>  105:   encryption_config = {
> An argument named "encryption_config" is not expected here.

Is this a known issue? Kindly let me know if the config syntax I'm using is incorrect or if it's an issue with the aws provider.

**Comment by barryib** [comment]
What is the version of your aws provider ? The encryption_config has been added in 2.52.0 https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2520-march-06-2020

**Comment by barryib** [comment]
> Error: Unsupported argument
on modules/eks/main.tf line 105, in resource "aws_eks_cluster" "k8s":
105: encryption_config = {
An argument named "encryption_config" is not expected here.

Furthermore, are you using this module ? I don't see any file called main.tf within this module.

**Comment by ankit-nclouds** [comment]
Thanks @barryib , using aws provider version > 2.52.0 solved the issue.

**Comment by oleksandr-tunyk** [comment]
Have an error: "**An argument named "encryption_config" is not expected here.**"
While trying to create a resource **aws_eks_cluster** and one of the parameters is **encryption_config**
```
encryption_config = {
    provider = {
      key_arn = aws_kms_key.eks-kms-key.arn
    }
    resources = ["secrets"]
  }
```
The same when I try to set **kubernetes_network_config** parameter of **aws_eks_cluster** resource.
**AWS provider** version is **3.73.0**
What can be an issue? How to solve?

**Comment by oleksandr-tunyk** [comment]
This works fine:
```
encryption_config {
    provider {
      key_arn = aws_kms_key.eks-kms-key.arn
    }
    resources = ["secrets"]
  }
```
