### ISSUE TITLE
Terraform aws_eks_node_group cannot find service linked role AWSServiceRoleForAmazonEKSNodegroup

### ISSUE THREAD

**Issue by michaeljguarino** [terraform-aws-modules/terraform-aws-eks#823]
# Unable to create nodegroups due to service link role

For some reason, when tf applying this module with configuration to create a managed node group, it barfs with the following:

```
Error: error creating EKS Node Group (demo:demo-default-many-bonefish): InvalidRequestException: Failed to validate if SLR: AWSServiceRoleForAmazonEKSNodegroup already exists due to missing permissions for 'iam:GetRole'
```

My user has administrator access, and I can successfully create node groups in the console.  It's also possible this is an issue with the underlying aws provider but I have no way of knowing.

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Cannot provision managed node groups

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```terraform
module "cluster" {
  source       = "terraform-aws-modules/eks/aws"
  cluster_name = var.cluster_name
  subnets      = var.subnets
  vpc_id       = var.vpc_id

  node_groups_defaults = {
    ami_type  = "AL2_x86_64"
    disk_size = 50
  }

  node_groups = {
    default = {
      desired_capacity = var.min_capacity
      max_capacity     = var.max_capacity
      min_capacity     = var.min_capacity

      instance_type = var.instance_type
      additional_tags = {
        "k8s.io/cluster-autoscaler/${var.cluster_name}" = "owned"
        "k8s.io/cluster-autoscaler/enabled" = "true"
      }
    }
  }
}

data "aws_eks_cluster" "cluster" {
  name = module.cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.cluster.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file = false
  version = "~> 1.11"
}
```

## What's the expected behavior?

A node group is created

## Environment details

* Affected module version: 10.0.0
* OS: mac
* Terraform version: v0.12.24

**Comment by GauntletWizard** [comment]
Doesn't seem to be a problem with the Terraform provider; I was able to reproduce with `aws eks create-nodegroup --cli-input-json '{"clusterName":"foobar-staging","nodegroupName":"workers04","diskSize":100,"instanceTypes":["c5.12xlarge"],"nodeRole":"arn:aws:iam::1:role/foobar-staging-eks-iam","nodegroupName":"workers04","scalingConfig":{"desiredSize":10,"maxSize":100,"minSize":1},"subnets":["subnet-foo","subnet-bar","subnet-baz"]}'`

**Comment by michaeljguarino** [comment]
Odd it succeeded in the aws console for me then.  Although it might have some unique interaction with the eks apis perhaps.

**Comment by GauntletWizard** [comment]
My issue was very simple: My account has a block on IAM actions unless signed in with MFA (see BlockMostAccessUnlessSignedInWithMFA in [this IAM example](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_iam_mfa-selfmanage.html) ). Switching to using a session-token with MFA authentication worked for me.

**Comment by rustlingwind** [comment]
I met the same issue today as well.  Eager to know if the issue has been fixed or not.
Is it a bug of the provider or something configured wrongly in my terraform scripts ?
And today a colleague told me that one of her friend just met this problem a week ago. It seems that the issue happens often but I can hardly find an answer on the internet.

What seems strange to me is that I can create node group successfully via the EKS aws console and cloudformation.

**Comment by dpiddockcmp** [comment]
This is likely a configuration issue with the role that you are using to create the managed node groups.

The module does not, and cannot, create this role. It is created for you by AWS when attempting to create a node group for the first time. Or queried using your role when creating the node group. You will need to examine the role you are using and its configuration. Talk to whoever controls your account and environment for help in debugging the issue.

**Comment by rustlingwind** [comment]
Hi @dpiddockcmp , very appreciated for your reply.

What make me confused is I really don't know exactly which role it is that is responsible for creating the node group.
I just thought it's the cluster role or node group role I created by terraform :

resource "aws_eks_cluster" "main" {
  role_arn = aws_iam_role.eks_cluster_role.arn
}

resource "aws_eks_node_group" "main" {
  node_role_arn   = aws_iam_role.eks_node_role.arn
}

But there are no changes even if I attach the eks_cluster_role and eks_node_role with "iam:GetRole" policy.

So you means that the role is my human role , right ? If so I will contact the administrator to check my account.

I have another question after I examined the cloudformation I ever used to successfully create the node group, I found that it leveraged the IAM Instance Profile and IAM Auto Scaling Group, perhaps this approach used some mechanism different so will not cause the "iam:GetRole" issue .. But it seems quite strange.

**Comment by michaeljguarino** [comment]
I believe there is a service linked role that's supposed to be bootstrapped when the node group api is called, but I wasn't able to find it in my account, even after doing the creation in-console.

I think it's likely this is not a terraform specific problem though, probably something amiss with the eks api itself.

**Comment by rustlingwind** [comment]
@michaeljguarino I didn't find the role in my account either. Though in the aws doc it mentions like below:

**Comment by michaeljguarino** [comment]
Probably same thing with me, aws account was old, definitely prior to node group support in eks

**Comment by rustlingwind** [comment]
Update:

I created the SLR(Service Linked Role)  AWSServiceRoleForAmazonEKSNodegroup manually, and run my terraform scripts (to create the EKS node group),  the node group can be created successfully this time ! 

Regarding why I could create the EKS cluster and worker nodes successfully by aws console and cloudformation, I got the answer, the EKS cluster created by my cloudformation template in fact is not fully managed by kubernetes,  it's only a EC2 cluster with autoscaling group , and then was registered to kubenetes.  Since the worker nodes were not MNG, it didn't require the SLR.  I didn't realize this before, so this make me confusing for a long time.

In any case, there seems to be something wrong on EKS side.  Because the AWS doc has mentioned this SLR need not be created by user , instead it will be created automatically. The AWS support has reached out to the EKS Support Ops team to further troubleshoot this issue. Any bugs or feature requests will be tracked in this containers-roadmap:  https://github.com/aws/containers-roadmap/projects/1

**Comment by rustlingwind** [comment]
@michaeljguarino  I can find the service linked role in the IAM console after I created it manually:

![image](https://user-images.githubusercontent.com/1019206/82856471-9bde9380-9f40-11ea-90a9-547e9b7178d7.png)

I just use terraform created it:

resource "aws_iam_service_linked_role" "AWSServiceRoleForAmazonEKSNodegroup" {
  aws_service_name = "eks-nodegroup.amazonaws.com"
}

**Comment by RobertFr0st** [comment]
I've also observed that this behavior is also present for eks_fargate_profiles  & that similar to aws_eks_node_group manually creating the profile is sufficient to automatically create the `AWSServiceRoleForAmazonEKSForFargate` resource.
