### ISSUE TITLE
Spot Instances don't work without 

### ISSUE THREAD

**Issue by jaygorrell** [terraform-aws-modules/terraform-aws-eks#826]
## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Specifying `spot_instance_pools` in a launch template results in normal on-demand nodes. If you specify `override_instance_types`, it correctly creates Spot instances.

**Comment by max-rocket-internet** [comment]
I agree it is a little confusing but we are just passing the option to the launch template and ASG. You can see how confusing it is here:
https://www.terraform.io/docs/providers/aws/r/launch_template.html
https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html

How would you suggest it be done?

**Comment by jaygorrell** [comment]
That's true, maybe this issue is misplaced. But perhaps something that can be done here is a little comment markup in the spot example?
