### ISSUE TITLE
node group on private subnets

### ISSUE THREAD

**Issue by amitsehgal** [terraform-aws-modules/terraform-aws-eks#834]
# node group on private subnets inspite of providing public and private both 

## What is the current behavior?

I have provided public and private both subnets to variable subnets . I don't see control plane is using public and pvt subnets.. However, i dont see an option for nodegroup to be created in pvt subnet.

node group is choosing public subnet instead of private.

## What's the expected behavior?

I would like a separate variable for subnets in case of node groups where we can sepcify pvt subnets only. We should separate this variable.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/node_groups/node_groups.tf#L8

## Environment details

* Affected module version: 11.0.0
* OS:
* Terraform version:

**Comment by dpiddockcmp** [comment]
You can limit the subnets used for the managed node group by setting the `subnets` key in one of the following maps:
- `workers_group_defaults`
- `node_groups_defaults`
- the individual node group in the `node_groups` map

**Comment by amitsehgal** [comment]
Thanks @dpiddockcmp  Let me try this.

**Comment by amitsehgal** [comment]
works fine ..thanks

**Comment by MihaiAnei** [comment]
I don't want to open another ticket, this is a good context.

@dpiddockcmp I have a question regarding one ASG per subnet which as you said can be controlled by setting `subnets` in one of those maps that in the end actually override the `var.subnets`.

If I override subnets in each of my `node_groups*` or `worker_groups*` (one ASG per subnet for Cluster autoscaler) is `var.subnets` used anymore? If no, do you think it should stay a required value?

**Comment by dpiddockcmp** [comment]
`var.subnets` is used to configure the `aws_eks_cluster`. AWS requires subnets to be given when creating the master resource. It creates ENIs in your subnets for communication with the worker nodes.

**Comment by MihaiAnei** [comment]
> `var.subnets` is used to configure the `aws_eks_cluster`. AWS requires subnets to be given when creating the master resource. It creates ENIs in your subnets for communication with the worker nodes.

Oh right! I forgot about that. Thank you!
