### ISSUE TITLE
Intermittently failing at config map aws_auth.tf

### ISSUE THREAD

**Issue by amitsehgal** [terraform-aws-modules/terraform-aws-eks#849]
# I have issues

## I'm submitting a...

* [ *] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Eks cluster provisioning with map roles intermittently fails at config map creation

## If this is a bug, how to reproduce? Please include a code sample if relevant.
provision eks using node groups.

module.eks-cluster.null_resource.wait_for_cluster[0]: Creation complete after 5m27s [id=7869213295342156152]
--
739 | module.eks-cluster.kubernetes_config_map.aws_auth[0]: Creating...
740 | module.eks-cluster.kubernetes_config_map.aws_auth[0]: Still creating... [10s elapsed]
741 | module.eks-cluster.kubernetes_config_map.aws_auth[0]: Still creating... [20s elapsed]
742 | module.eks-cluster.kubernetes_config_map.aws_auth[0]: Still creating... [30s elapsed]
743 |  
744 | Error: Post https://xxxxxxxxxxxx.yl4.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps: dial tcp 35.175.60.159:443: i/o timeout
745 |  
746 | on .terraform/modules/eks-cluster/aws_auth.tf line 61, in resource "kubernetes_config_map" "aws_auth":
747 | 61: resource "kubernetes_config_map" "aws_auth" {

## What's the expected behavior?

there should not be failure

## Are you able to fix this problem and submit a PR? Link here if you have already.
No
## Environment details

* Affected module version:
v11.0.0
* OS:
* Terraform version:
Terraform v0.12.24
+ provider.aws v2.59.0
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

**Comment by dpiddockcmp** [comment]
Do you have whitelisting of the public endpoint enabled, or the public endpoint turned off?

Maybe you need to increase the timeout for waiting for the endpoint to be available after creating the cluster?

**Comment by amitsehgal** [comment]
how do i increase the timeout...its polling

**Comment by dpiddockcmp** [comment]
If you're absolutely certain that the issue is EKS being very slow at bringing up the endpoint and it's not a networking/security configuration issue then you could increase the sleep time or number of loops in the polling. You can do this via the `wait_for_cluster_cmd` variable since v8.2.0.
```hcl
module "eks" {
  wait_for_cluster_cmd = "for i in `seq 1 60`; do wget --no-check-certificate -O - -q $ENDPOINT/healthz >/dev/null && exit 0 || true; sleep 10; done; echo TIMEOUT && exit 1"
}
```
