### ISSUE TITLE
Bug: Module ignores custom AMI ID

### ISSUE THREAD

**Issue by Jeeppler** [terraform-aws-modules/terraform-aws-eks#85]
# I have issues

I want to use the Ubuntu EKS image (custom) AMI and my settings are ignored by the module.

## I'm submitting a...

* [ ] bug report

## What is the current behaviour?

A custom AMI ID is ignored by the module. I tried to set the AMI ID to the following `ami_id` in the `workers_group_defaults` section:

~~~
workers_group_defaults = {
      ...
      ami_id               = "ami-39397a46"  # Ubuntu Image
      ...
}
~~~

The specified AMI is the [Ubuntu EKS](https://blog.ubuntu.com/2018/06/06/ubuntu-to-host-containers-in-amazons-eks-for-container-portability) image for `us-east-1`. Ubuntu released a statement that they will support and update an image specifically for EKS. The image AMI ID's can be found here: https://cloud-images.ubuntu.com/aws-eks/?_ga=2.56651242.1343651116.1533683680-508754220.1533683680

I would like to use the Ubuntu image instead of the Amazon AMI to make my environment more portable. 

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Use try to set the `ami_id` in the `workers_group_defaults` to use the Ubuntu EKS AMI ID `ami-39397a46` (us-east-1) or `ami-6d622015` (us-west-2).

## What's the expected behaviour?

Custom AMI ID's can be used for worker nodes. Specifically, Ubuntu EKS can be used with this module.

## Are you able to fix this problem and submit a PR? Link here if you have already.

Maybe this is just a misunderstanding or it is super easy to fix. If not let me know.

## Environment details

* Affected module version: 1.4.0
* OS: Ubuntu 18.04 LTS (Container)
* Terraform version: v0.11.7

**Comment by hobbsh** [comment]
I did not write the module, but I use it. The worker group defaults seem to be there for defaults to fallback on, not to customize. I recommend setting up a worker_groups list to make your customizations and passing it to the module call. I do it this way and don't have any issues. I should also add that I have not had any luck getting Ubuntu 16.04 or 18.04 to work in EKS and believe comes down to a lack of support for it on AWS's side, not this module's fault. 

Here's an example worker_group with module call:

```
locals {
  worker_groups = "${list(
                  map(
                      "name", "k8s-worker",
                      "ami_id", "ami-39397a46",
                      "asg_desired_capacity", "5",
                      "asg_max_size", "8",
                      "asg_min_size", "5",
                      "instance_type", "m4.xlarge"
                      )
  )}"
  tags = "${map("Environment", "${terraform.workspace}")}"
}

module "eks" {
  source                     = "terraform-aws-modules/eks/aws"
  cluster_name          = "${terraform.workspace}"
  subnets                   = "${data.aws_subnet_ids.eks_subnets.ids}"
  vpc_id                      = "${data.aws_vpc.vpc.id}"
  worker_groups        = "${local.worker_groups}"
}

**Comment by Jeeppler** [comment]
@hobbsh thanks. I was able to use the Ubuntu EKS image with your configuration. However, the instance created from the EKS image is not connected to the EKS cluster.

**Comment by brandoconnor** [comment]
Hey @all - a little late to the party but thanks for the collaboration here. Exactly as @hobbsh said, you just need to customize each worker group through the `worker_groups` map-list. That ubuntu isn't working beyond that is really more up to how that image is created and how EKS needs to hook into it.

**Comment by LouisDinatale** [comment]
Does anyone know if this issue has an update?

**Comment by dpiddockcmp** [comment]
@LouisDinatale  This issue is over a year old with a merged fix. If you're having trouble please open a new issue with full details of the problems.

With v8.0.0 you can change the `data.aws_ami` filter for the default image to use via the module variables `worker_ami_name_filter` and `worker_ami_owner_id`, or directly specify the `ami_id` in the `worker_groups` or `workers_group_defaults`:
```
worker_groups = [
  {
    ami_id = "ami-xxxxx"
  }
]
workers_group_defaults = {
  ami_id = "ami-xxxxx"
}
```
Please see the README for more details.
