### ISSUE TITLE
How do I tag EC2 instances in aws?

### ISSUE THREAD

**Issue by ImIOImI** [terraform-aws-modules/terraform-aws-eks#850]
# I have issues
I'm wanting to tag all resources that a certain client is using with a Client tag. This will help us keep the bean counters happy. I don't see how to tag EC2 instances (nodes) that are being created.

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first! (I promise I did... and studied the variables in both the node group module and the parent)
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I can tag EKS, I can tag worker groups, I can tag nodes in k8s... but I'm not smart enough to know how to tag nodes inside the worker groups in aws.

## Environment details
I don't really think this is relevant, but I'm running WSL v1 (Ubuntu) on Windows 10.

* Affected module version:
* OS: WSL
* Terraform version: v0.12.24

**Comment by dpiddockcmp** [comment]
How are you creating the worker nodes?

You cannot change the default tags on EC2 instances created by managed node groups. It is not currently supported by AWS.

The Autoscaling Groups directly managed by the module can modify the EC2 instance's tags via the tags list in the `worker_groups`, `worker_groups_launch_template` or `workers_group_defaults` variables.

Example:
```hcl
module "eks" {
  # ...
  worker_groups = [
    {
      name = "example"
      tags  = [
        {
          key                 = "Cost"
          value               = "Team1"
          propagate_at_launch = true
        } 
      ] 
    }
  ]
}
```

**Comment by ImIOImI** [comment]
_That's_ what I was missing... I feel dumb. _Of course_ the tags would be in the same format that an asg takes. I was submitting the tags in the normal key value pair format. Thanks for your quick response. This helps a lot.

As a thank you, would you be interested in a PR that adds a "tags_as_list_of_maps" solution similar to the way it was implemented in the [terraform-aws-autoscalling](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/locals.tf) module?

**Comment by dpiddockcmp** [comment]
That function is much easier to write in TF 0.12 style. You no longer need to run through a `null_resource`:
```
$  terraform console
> [for k,v in {"a" = "b", "c" = "d"} : {key = k, value = v, propagate_at_launch = true}]
[
  {
    "key" = "a"
    "propagate_at_launch" = true
    "value" = "b"
  },
  {
    "key" = "c"
    "propagate_at_launch" = true
    "value" = "d"
  },
]
```

The logic for creating ASG tags is already [quite messy](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v11.1.0/workers_launch_template.tf#L181..L204) and there are valid use cases for setting `propagate_at_launch = false`.

**Comment by ImIOImI** [comment]
Ok, I like that a lot. That's a pretty simple way to ingest the tags I already have. I'm closing this issue. Thanks again for the help!
