### ISSUE TITLE
bootstrap_extra_args is not used in the Windows launch configuration

### ISSUE THREAD

**Issue by tynril** [terraform-aws-modules/terraform-aws-eks#851]
# `bootstrap_extra_args` is not used in the Windows launch configuration

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

The value `bootstrap_extra_args` in a worker configuration under `worker_groups` that has its `platform` set to `windows` isn't used.

See the (Windows user data template)[https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/templates/userdata_windows.tpl]: the `bootstrap_extra_args` is not used. Contrast with the (Linux user data template)[https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/templates/userdata.sh.tpl], which passes it to the bootstrap script.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Deploy the module with a worker using the `windows` platform, and anything set in its `bootstrap_extra_args`. Notice, in the AWS console, that the matching Launch Configuration does not contain the data you've set in `bootstrap_extra_args`.

## What's the expected behavior?

 * `bootstrap_extra_args` is passed to the bootstrap script on Windows, like it is on Linux.

## Are you able to fix this problem and submit a PR? Link here if you have already.

n/a

## Environment details

* Affected module version: All (Observed on 11.1.0)
* OS: Windows
* Terraform version: 0.12.24

## Any other relevant info

n/a

**Comment by dpiddockcmp** [comment]
Hi. This project is not affiliated with AWS. I don't believe we have any AWS devs involved but I could be mistaken.

I guess the correct place for feature requests against the windows nodes is over at https://github.com/aws/containers-roadmap which is the official project of the AWS container team.

**Comment by tynril** [comment]
Got it! I have edited this issue to be strictly about the part that is relevant to this depot. Thanks!
