### ISSUE TITLE
configmaps aws_auth connection refused

### ISSUE THREAD

**Issue by tnguyen14** [terraform-aws-modules/terraform-aws-eks#853]
# I have issues

## I'm submitting a...

* [x] bug report

## What is the current behavior?
I tried running `terraform apply`, and got this error.

```
Error: Post http://localhost/api/v1/namespaces/kube-system/configmaps: dial tcp 127.0.0.1:80: connect: connection refused

  on .terraform/modules/eks/terraform-aws-eks-11.1.0/aws_auth.tf line 62, in resource "kubernetes_config_map" "aws_auth":
  62: resource "kubernetes_config_map" "aws_auth" {
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.
I used the code example from https://github.com/hashicorp/learn-terraform-provision-eks-cluster

## What's the expected behavior?
It should work successfully?

## Environment details

* Affected module version:
* OS:
* Terraform version: 0.12.24

I am running on Terraform Cloud

**Comment by dpiddockcmp** [comment]
Please report issues against the repo you are copying code from. It is broken and not this module.

The example you are following does not configure the kubernetes provider. I wouldn't be surprised if there are other issues with it.

Please read the documentation for this module, especially the section [Usage Example](https://github.com/terraform-aws-modules/terraform-aws-eks/#usage-example)

We also maintain working examples in the [examples](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/v11.1.0/examples) subfolder

**Comment by tnguyen14** [comment]
Thanks for your help.
