### ISSUE TITLE
Tags are not propagated on nodegroup ASG

### ISSUE THREAD

**Issue by amitsehgal** [terraform-aws-modules/terraform-aws-eks#860]
# I have added additional tags on node groups and they are not propagated to ASG or EC2.

  
## I'm submitting a...

* [ * ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Tags does not propagate

## If this is a bug, how to reproduce? Please include a code sample if relevant.
add tags like above
locals {
  common_tags = {
        bu = "bu"
        envType = var.envType
        stackType = "terraform"
    }
}
.
.
.
.

  node_groups_defaults = {
    ami_type  = "AL2_x86_64"
    disk_size = 50
    subnets = split(",",var.private_subnet_ids)
    additional_tags = "${merge(
      local.common_tags,
        map(
          "k8s.io/cluster-autoscaler/${local.cluster_name}", "owned",
          "k8s.io/cluster-autoscaler/enabled","true",
          "stackType", "terraform"
        )
        )}"
  }

## What's the expected behavior?

Tags should appear on ASG or EC2

## Are you able to fix this problem and submit a PR? Link here if you have already.
No
## Environment details
Terraform v0.12.24

terraform-aws-eks 11.0.0
* Affected module version:
* OS:
* Terraform version:

**Comment by rekcah78** [comment]
this not a eks terraform module bug but AWS implementation for the managed nodes:

see: https://docs.aws.amazon.com/eks/latest/userguide/create-managed-node-group.html

> Tags — (Optional) You can choose to tag your Amazon EKS managed node group. These tags do not propagate to other resources in the node group, such as Auto Scaling groups or instances. For more information, see Tagging your Amazon EKS resources.

**Comment by rekcah78** [comment]
https://github.com/aws/containers-roadmap/issues/608

**Comment by atrepca** [comment]
For anyone looking for a workaround:
```hcl
locals {
  asg_name = module.eks-cluster.node_groups["default"]["resources"][0]["autoscaling_groups"][0]["name"]
}

resource "null_resource" "add_custom_tags_to_asg" {
  triggers = {
    node_group = local.asg_name
  }
  provisioner "local-exec" {
    command = <<EOF
aws autoscaling create-or-update-tags \
  --tags ResourceId=${local.asg_name},ResourceType=auto-scaling-group,Key=CUSTOM_TAG_NAME,Value=CUSTOM_TAG_VALUE,PropagateAtLaunch=true
EOF
  }
}
```
You can add multiple tags; newly launched nodes will get the custom tags, thanks to `PropagateAtLaunch=true`.

**Comment by mteodori** [comment]
is the workaround above still needed?

**Comment by smartm13** [comment]
Thanks @atrepca for the quick WA.
 To top it off, I appended ` && aws autoscaling start-instance-refresh   --auto-scaling-group-name ${local.asg_name} --region ${var.region}` to your `local-exec`.
This way, the old instances without tags gets immediately replaced with new correctly tagged ones.

**FYI:** _I have also added this `null_resource.add_custom_tags_to_asg` in `depends_on` of further resources so that they start working on refreshed node group only._

And
> is the workaround above still needed?

Unfortunately yes @mteodori, its still needed, `additional_tags` for managed node groups still wont propagate to ec2 out-of-the-box.

**Comment by gagarinfan** [comment]
Hi. I've similar problem but while having more than one node_group it gets more complicated to apply @atrepca 's solution. Maybe someone will find it useful. 

Use case:
- more than 1 node group (in my case 6)
- a few tags in locals as map (5)

I need to iterate over each node_group and map with tags to apply all of them to every group.

```tf
resource "null_resource" "add_custom_tags_to_asg" {
  for_each = module.eks.node_groups


  provisioner "local-exec" {
    command = <<EOF
      %{ for tagName,tagValue in local.tags }
        aws autoscaling create-or-update-tags --tags \
        ResourceId=${each.value.resources[0].autoscaling_groups[0].name},\
        ResourceType=auto-scaling-group,\
        Key=${tagName},\
        Value=${tagValue},\
        PropagateAtLaunch=true
      %{ endfor ~}
    EOF
  }
}
```
