### ISSUE TITLE
Not able to create worker group into existing eks cluster (conditional creation)

### ISSUE THREAD

**Issue by tarunptala** [terraform-aws-modules/terraform-aws-eks#861]
Not able to conditionally create eks resources (worker group) to existing cluster created by this module. We came across **Conditional creation** section  - [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks)

**FYI** - we have another module called `eks` which creates this cluster using [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks) now we are trying to find ways to create worker group by creating separate module (Conditional Creation). I don't want worker group to be part eks cluster creation module. 

## What is the current behaviour?
Looks like It is trying to create new cluster as opposed to creating only worker group for existing cluster.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
My configuration looks like - `cluster_name` we are passing through variable to discover existing cluster.
```
data "aws_eks_cluster" "cluster" {
  count = var.create_eks ? 1 : 0
  name  = var.cluster_name
}

data "aws_eks_cluster_auth" "cluster" {
  count = var.create_eks ? 1 : 0
  name  = var.cluster_name
}

provider "kubernetes" {
  host                   = element(concat(data.aws_eks_cluster.cluster[*].endpoint, list("")), 0)
  cluster_ca_certificate = base64decode(element(concat(data.aws_eks_cluster.cluster[*].certificate_authority.0.data, list("")), 0))
  token                  = element(concat(data.aws_eks_cluster_auth.cluster[*].token, list("")), 0)
  load_config_file       = false
  version                = "~> 1.11"
}

module "eks-worker" {
  source     = "terraform-aws-modules/eks/aws"
  version    = "~> 11.0.0"
  create_eks = false

  tags = {
     Name        = "${var.env}-${var.workload_type}-eks-worker-nodes"
     Environment = var.env
     Terraform   = "true"
   }

  worker_groups = [
    {
      name                          = "${var.env}-${var.workload_type}-eks-worker-nodes"
      instance_type                 = var.instance_type
      asg_min_size                  = var.asg_min_size
      asg_max_size                  = var.asg_max_size
      key_name                      = var.key_name
      map_roles                     = var.map_roles

      tags = [{
        key                 = "k8s.io/cluster-autoscaler/${var.cluster_name}"
        value               = "owned"
        propagate_at_launch = true
        },
        {
          key                 = "k8s.io/cluster-autoscaler/enabled"
          value               = "true"
          propagate_at_launch = true
      }]

    }
  ]

}
```

## What's the expected behavior?
It should allow us to create worker group within existing cluster.

## Environment details

* Affected module version: 11.0.0
* OS: Mac
* Terraform version: v0.12.24
## Any other relevant info
Using Terragrunt

**Comment by dpiddockcmp** [comment]
This module creates a cluster. There is currently no way to use it to add workers to an existing cluster.

There have been suggestions in the past about pulling the module apart to allow for reusable components, whilst keeping the top level module as a one-shot solution. A recent discussion about it happened in #774

**Comment by tarunptala** [comment]
@dpiddockcmp thanks for acknowledging it. keep a watch on #774

**Comment by jeffbehl** [comment]
After just upgrading to EKS 1.16, the existing workers were functioning fine.  However I'm not unable to create new worker groups, even after removing the old ones.  I resorted to switching to node groups.  Can this be due to the upgrade process and the cluster now being treated as not having been created by the module?  

Apologies if this is not related, it just seemed possible as I struggle to get worker_groups to come back online.  They simple do not connect to the cluster..
