### ISSUE TITLE
nodes can't scale up due to "not authorized to perform: autoscaling:SetDesiredCapacity"

### ISSUE THREAD

**Issue by hasakura12** [terraform-aws-modules/terraform-aws-eks#872]
# I have issues with cluster autoscaler. Seems SetDesiredCapacity can't be done on ASG name.

## I'm submitting a...

* [ x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Followed this IRSA: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa/irsa.tf#L47

Also my setup is EKS cluster + unmanaged node group + IRSA for cluster autoscaler.

Add string condition for IAM policy like this
```
statement {
    sid    = "clusterAutoscalerOwn"
    effect = "Allow"

    actions = [
      "autoscaling:SetDesiredCapacity",
      "autoscaling:TerminateInstanceInAutoScalingGroup",
      "autoscaling:UpdateAutoScalingGroup",
    ]

    resources = ["*"]

    condition {
      test     = "StringEquals"
      variable = "autoscaling:ResourceTag/kubernetes.io/cluster/${module.eks.cluster_id}"
      values   = ["owned"]
    }

    condition {
      test     = "StringEquals"
      variable = "autoscaling:ResourceTag/k8s.io/cluster-autoscaler/enabled"
      values   = ["true"]
    }
  }
}
```

Shell into a pod associated with serviceaccount which can assume a role (IRSA), then call AWS asg cli
```
aws autoscaling set-desired-capacity \
>     --auto-scaling-group-name ASG_NAME \
>     --desired-capacity 2 \
>     --region us-east-1

An error occurred (AccessDenied) when calling the SetDesiredCapacity operation: User: arn:aws:sts::XXXXX:assumed-role/EKSClusterAutoscaler/botocore-session-1588872862 is not authorized to perform: autoscaling:SetDesiredCapacity on resource: arn:aws:autoscaling:us-east-1:XXXXX:autoScalingGroup:XXXXX:autoScalingGroupName/XXXXXX-120200507173038542300000005
```

When I removed the conditions, 
```
statement {
    sid    = "clusterAutoscalerOwn"
    effect = "Allow"

    actions = [
      "autoscaling:SetDesiredCapacity",
      "autoscaling:TerminateInstanceInAutoScalingGroup",
      "autoscaling:UpdateAutoScalingGroup",
    ]

    resources = ["*"]

    # ISSUE with below: SetDesiredCapacity operation: User: arn:aws:sts::202536423779:assumed-role/EKSClusterAutoscaler/botocore-session-1588872862 is not authorized to perform: autoscaling:SetDesiredCapacity on resource: arn:aws:autoscaling:us-east-1:202536423779:autoScalingGroup:b44f55c0-a6a9-4689-8651-7a72b7c6300a:autoScalingGroupName/eks-ue1-prod-peerwell-api-infra-worker-group-staging-120200507173038542300000005
    # condition {
    #   test     = "StringEquals"
    #   variable = "autoscaling:ResourceTag/kubernetes.io/cluster/${module.eks_cluster.cluster_id}"
    #   values   = ["owned"]
    # }

    # condition {
    #   test     = "StringEquals"
    #   variable = "autoscaling:ResourceTag/k8s.io/cluster-autoscaler/enabled"
    #   values   = ["true"]
    # }
  }
}
```

```
aws autoscaling set-desired-capacity \
>     --auto-scaling-group-name ASG_NAME \
>     --desired-capacity 2 \
>     --region us-east-1
```
succeeded and ASG scaled up.

Not sure if these IAM **policy conditions work ONLY FOR MANAGED NODES**, but not for unmanaged nodes
```
condition {
      test     = "StringEquals"
      variable = "autoscaling:ResourceTag/kubernetes.io/cluster/${module.eks.cluster_id}"
      values   = ["owned"]
    }

    condition {
      test     = "StringEquals"
      variable = "autoscaling:ResourceTag/k8s.io/cluster-autoscaler/enabled"
      values   = ["true"]
    }
```

## What's the expected behavior?

Should be able to set desired capacity when scaling up.

## Environment details

kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Terraform v0.12.24
+ provider.aws v2.60.0
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1

**Comment by rvanoo** [comment]
The ASGs aren't being tagged correctly. The workaround at the moment appears to be to set `tags` on the module, which tags everything. Clunky but harmless, and it fixed `cluster-autoscaler` for me:

```
  tags = {
    "k8s.io/cluster-autoscaler/enabled"          = "true"
    "k8s.io/cluster-autoscaler/${local.cluster}" = "owned"
  }
```

(where `local.cluster` is set to the name of my cluster)

**Comment by dpiddockcmp** [comment]
The module does not add the auto-scaling tags to your worker groups. This is not a bug.

As per the [documentation](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.0.0/docs/autoscaling.md), you must tag your groups correctly.

This is also done in the example [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.0.0/examples/irsa/main.tf#L65..L76)

**Comment by hasakura12** [comment]
@dpiddockcmp You shouldn't close this by assuming my ASG not being tagged properly.

Indeed it was tagged, but didn't work if nodes are unmanaged.

**Comment by hasakura12** [comment]
The real issue is IAM role condition is using 
```
kubernetes.io/cluster/${module.eks.cluster_id} = owned
```
 whereas ASG tag is using 

```
k8s.io/cluster-autoscaler/${local.cluster_name} = true
```

Both key and value don't match.
