### ISSUE TITLE
ASG Failed scale up after update aws_launch_template with aws provider 2.61.0 (currently latest version)

### ISSUE THREAD

**Issue by minggaograb** [terraform-aws-modules/terraform-aws-eks#874]
# I have an issue when I update aws_launch_template with [provider.aws=2.61.0](https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v2.61.0). 

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
The latest terraform provider rolled out a new improvement with in [MR](https://github.com/terraform-providers/terraform-provider-aws/pull/11655). It will set "partition_number" to 0 when you not handle it at [placement](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers_launch_template.tf#L297). This will cause ASG failed to launch instance with error 
`Launching a new EC2 instance. Status Reason: Could not launch Spot Instances. InvalidParameterValue - You cannot use PartitionNumber with a Placement Group that does not exist. Specify a valid Placement Group and try again. Launching EC2 instance failed.`

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Use aws provider 2.61.0 (currently latest version), update any launch template and apply

## What's the expected behavior?
ASG will failed to scale up

## Are you able to fix this problem and submit a PR? Link here if you have already.
NA
## Environment details

* Affected module version:
* OS: mac
* Terraform version: 0.11.14

**Comment by dpiddockcmp** [comment]
I've put a fix in #875. Can you confirm that it fixes your issue?

**Comment by minggaograb** [comment]
HI @dpiddockcmp , thanks for fix. It do solve our issue when we didn't set "launch_template_placement_group" in "var.worker_groups_launch_template". 
But since we do not handle "partition_number" in "placement" block, for users want to set "group_name" to "Partition", the partition_number would be become 0 which is an illegal value. I guess this depends how they gonna fix for [issue #13236 in terraform-aws-provider](https://github.com/terraform-providers/terraform-provider-aws/issues/13236).

**Comment by barryib** [comment]
Reopening until a fix is merged upstream or in this module.

**Comment by TBeijen** [comment]
For us reverting to provider `2.60.0` _didn't_ fix the problem. No proposed changes by TF (likely simply ignores anything related to partition number).

Reverting to previous launch template version stopped the bleeding (be sure not to revert to incompatible AMIs or anything).

Trick to fix if having broken asg via provider `2.61.0`: Pin provider to `2.60.0`, trigger a new launch template version by for example increasing disk space from 100 to 105.
