### ISSUE TITLE
Not able to override disk size

### ISSUE THREAD

**Issue by alonshoshani** [terraform-aws-modules/terraform-aws-eks#876]
# I have issues when changing the worker_groups disk_size it  still creating volume with 100g

## I'm submitting a

```
worker_groups = [
    {
      name                          = "worker-group-1"
      instance_type                 = "t2.micro"
      additional_userdata           = "echo foo bar"
      asg_desired_capacity          = 1
      additional_security_group_ids = [aws_security_group.worker_group_mgmt_one.id]
      disk_size = 10
    }
  ]
```
## What is the current behavior?

I expect the volume will be 10g and not the default 100g

**Comment by dpiddockcmp** [comment]
Please review the valid map key names in `locals.tf`. `disk_size` is not a valid name. I think you're aiming for [`root_volume_size`](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.0.0/local.tf#L50)? 

There is no validation of incorrect keys.
