### ISSUE TITLE
issue with aws_auth.tf

### ISSUE THREAD

**Issue by tnimni** [terraform-aws-modules/terraform-aws-eks#878]
# I have issues

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [X] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

when running the module and using iam_instance_profile_name as input for worker_group_launch_template I'm getting the following

```
:35 Error: Invalid template interpolation value
  on .terraform/modules/eks/terraform-aws-eks-12.0.0/aws_auth.tf line 7, in locals:
   7:       worker_role_arn = "arn:${data.aws_partition.current.partition}:iam::${data.aws_caller_identity.current.account_id}:role/${element(
   8:         coalescelist(
   9:           aws_iam_instance_profile.workers_launch_template.*.role,
  10:           data.aws_iam_instance_profile.custom_worker_group_launch_template_iam_instance_profile.*.role_name,
  11:           [""]
  12:         ),
  13:         index
  14:       )}"
    |----------------
    | aws_iam_instance_profile.workers_launch_template is empty tuple
    | data.aws_iam_instance_profile.custom_worker_group_launch_template_iam_instance_profile is tuple with 1 element

The expression result is null. Cannot include a null value in a string
template.
```
this is expected to work as the second value custom_worker_group_launch_template_iam_instance_profile is not empty

I'm unable to understand why it claims the value is null

## What's the expected behavior?

it should work

## Environment details

* Affected module version: 12.0.0
* OS: linux
* Terraform version: 0.12.24

## Any other relevant info

**Comment by dpiddockcmp** [comment]
Please post how you're calling the module

**Comment by tnimni** [comment]
> Please post how you're calling the module

this is no longer an issue,
closing the issue
