### ISSUE TITLE
Use of name_prefix

### ISSUE THREAD

**Issue by max-rocket-internet** [terraform-aws-modules/terraform-aws-eks#88]
Currently we have:

```hcl
resource "aws_iam_role" "workers" {
  name_prefix        = "${aws_eks_cluster.this.name}"
  assume_role_policy = "${data.aws_iam_policy_document.workers_assume_role_policy.json}"
}

resource "aws_iam_instance_profile" "workers" {
  name_prefix = "${aws_eks_cluster.this.name}"
  role        = "${aws_iam_role.workers.name}"
}
```

Is there a reason to use `name_prefix` instead of just `name`? I ask because the resultant names are things like `my-cluster-20180808095045107900000005`.

We have to create cross account IAM policies for things like ECR and it would be nice to have a predictable and consistent name for the roles 🙂

**Comment by brandoconnor** [comment]
Seems to be my personal preference to use `name_prefix` but both here now and in my ALB module, people seem to want the opposite. To lay it out there:

Brandon's opinion:

* `name` leaves room for collisions but `name_prefix` does not. Plays better with testing and means a consumer never needs to worry about creating the same resource in the same region/environment/account/project and hitting a name conflict. idk maybe that's not such a big deal.
* I care much more about a resource's ARN or its tags than its `name`. ARNs are hairy enough that I assume them to be consumed through remote states but I can see how cross-account needs might not render that possible...
* I (perhaps wrongly) assumed max resource lengths are handled for you with name prefixes... though now I'm second guessing whether this is the case for all resources. Also, unsure of how a `name_prefix` longer than the allowed name behaves...

Obviously, the drawback of `name_prefix` being the losing of control of names that become long and ugly.

In any case, I've seen this requested and never the opposite... not really enough data to say what consensus looks like but I'd be willing to make that switch over on the next major release. PR away.

**Comment by brandoconnor** [comment]
I think I've evolved in my thought here as I've built some more things in the wild and use-cases have stacked up for this feature. I think there's a good case to be made for 100% user specified names of the resources in question rather than using `name_prefix`. This may be a breaking change but worth the trouble.

If a user wants to give randomization to any/all resource names, the module still allows that without enforcing it (i.e. append your `cluster_name` with `random_string.suffix.result`). I've come around that configuration details like naming should generally be passed, rather than assumed or enforced. Thanks for linking the issue and consider the field open for PR here. 👍

**Comment by max-rocket-internet** [comment]
> Thanks for linking the issue and consider the field open for PR here.

Nice!

**Comment by rverma-nikiai** [comment]
How to fetch IAM roles with name_prefix? Currently, terraform data_source for IAM role doesn't provide functionality to fetch with tags and neither do we have role tagging implemented. For certain automation like access to elasticsearch or IAM trust policy, it would be nice to use data source provider for IAM role.

**Comment by max-rocket-internet** [comment]
> How to fetch IAM roles with name_prefix?

I don't think it's possible. I think you need to use an output of the module instead.

**Comment by rverma-nikiai** [comment]
is it possible to override the default worker role name if provided by a variable? I can create a PR if you are ready to approve.

**Comment by max-rocket-internet** [comment]
@rverma-nikiai see here: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/282

**Comment by rverma-nikiai** [comment]
#282 is actually an alternative solution than having a name override. It's not I am facing any limitations with IAM creation. I do understand that the rationale behind name prefix is name clash accros region. We can handle this with having region in IAM role name.

**Comment by max-rocket-internet** [comment]
Ah yes, you are right, sorry. Sure, make a PR 👍

**Comment by ivangrynkoring** [comment]
What about use tf-0.12 goodies like this?
`
resource "aws_iam_role" "workers" {
  count                           = var.manage_worker_iam_resources ? 1 : 0
  name_prefix                = var.override_workers_role_name ? null : aws_eks_cluster.this.name
  name                           = var.override_workers_role_name ? var.workers_role_name : null
  assume_role_policy    = data.aws_iam_policy_document.workers_assume_role_policy.json
  permissions_boundary  = var.permissions_boundary
  path                  = var.iam_path
  force_detach_policies = true
  tags                  = var.tags
}
`
