### ISSUE TITLE
Provide support for non EBS-backed instances

### ISSUE THREAD

**Issue by zuc** [terraform-aws-modules/terraform-aws-eks#881]
## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
As far as I can understand, today there's no way to launch instances that aren't EBS-backed (e.g. [instance-store](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html) backed ones).

As a matter of fact, the [current implementation](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.0.0/workers_launch_template.tf#L324-L351) always assumes the user wants to provision a EBS volume along with the instance, but that might actually not be the case for instance types that come with ephemeral local storage devices (which are a lot, see the link above).

What do you think?

**Comment by max-rocket-internet** [comment]
Might be a good idea to allow per worker group external launch templates here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.0.0/workers_launch_template.tf#L129-L137

This would allow you and others to just supply their own LT with whatever settings they need.

**Comment by hermitmaster** [comment]
Reopen? This is relevant for our current usage.
