### ISSUE TITLE
Ensure correct EKS/Kubernetes context is being used before each 'terraform apply'

### ISSUE THREAD

**Issue by Murty0** [terraform-aws-modules/terraform-aws-eks#886]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Hi!

I have a very specific scenario here which is causing us issues.

We have multiple EKS/Kubernetes clusters, which are provisioned and managed via Terraform. We need the appropriate Kubernetes context to be used before any other changes are implemented in each `terraform apply`. 

One possible way which we have found to run something every time is to use something like this:

```
resource "null_resource" "eks_context_switcher" {

  triggers = {
    always_run = timestamp()
  }

  provisioner "local-exec" {
    command = "aws eks --region ${var.region} update-kubeconfig --name ${var.eks_name}"
  }
}
```

But this above solution has the problem that as Terraform is declarative (https://www.terraform.io/docs/configuration/index.html#configuration-ordering), the execution order cannot be guaranteed, and some changes might end up being made in the wrong Kubernetes cluster/context.

To add to the above solution, we could add a `depends_on` meta-argument, which depends on the `null_resource`, within each EKS/Kubernetes resource. But this seems very error-prone, and adds unnecessary toil, and we can already see someone forgetting to add this.

Is there a built-in mechanism which is available in Terraform which would allow us to always run a certain command/recreate a resource first, before anything else gets applied. 

Asking this here as we are using this EKS module to provision our clusters.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Switch Kubernetes context/cluster, do a TF apply intended for any other context/cluster, and voila, changes have been applied to the wrong cluster!

## What's the expected behavior?

Ideally, there should be some mechanism of changing to the correct context/cluster first before any other changes are made.

## Environment details

* Affected module version: all
* OS: all
* Terraform version: all

**Comment by dpiddockcmp** [comment]
How are you creating the kubernetes resources? Are you using the kubernetes terraform provider? If so, then configure the provider for use with your cluster. See the example in the [README](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.0.0/README.md#usage-example) for how to do this.

Are you modifying resources in multiple kubernetes clusters in the same terraform plan? In that case you can define multiple kubernetes providers and use a unique alias in each.
```
provider "kubernetes" {
  alias = "cluster1"
  # ... configuration goes here
}

provider "kubernetes" {
  alias = "cluster2"
  # ... configuration goes here
}

resource "kubernetes_pod" "pod1" {
  provider = kubernetes.cluster1
}

resource "kubernetes_pod" "pod2" {
  provider = kubernetes.cluster2
}
```
See terraform's documentation on [provider aliases](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances)

**Comment by Murty0** [comment]
Hey @dpiddockcmp, thanks for your response here!

Unfortunately, both the options you suggested below are unsuitable for us, and I will explain why.

Before I jump in to that though, I want to give a brief background on our current setup. We use python to generate our terraform templates, because we have to handle a lot of intricacies to handle the generation of different variables for different regions and branches. The result of that is that our terraform templates look exactly the same across all regions and branches, but just the variables are different. Our definitions and configurations for backends for terraform are also handled in the same way. Then, based on the `region/branch` subdirectory we are in, we do a `terraform apply`, which then chooses the correct backend and does the apply correctly. But when it comes to EKS/Kubernetes, as the region cannot be handled based on the Terraform backend being used, thus the issue. 

1) `Are you using the kubernetes terraform provider? If so, then configure the provider for use with your cluster.`

We are indeed using the Kubernetes Terraform provider, and our configuration is actually exactly the same as in the README example which you shared. But again, as our templates look the same,  when we do a `terraform apply`, all other non-EKS changes do get applied in the correct region, but the EKS context, as it is a resource/value which terraform is unaware of, can get applied to the wrong context if we do not remember to manually change the context either via `kubectl` or via the Docker Desktop context switcher. 

2) `Are you modifying resources in multiple kubernetes clusters in the same terraform plan? In that case you can define multiple kubernetes providers and use a unique alias in each.`

We don't modify resources in multiple k8s clusters in the same terraform plan. But again as I noted earlier, as our templates are the same, using an alias here will not solve this issue as the templates look exactly the same, and we dont want to add region/branch specific providers, because this would mean there is a drift/skew in template generation between regions/branches. 

My suggested solution in the original issue comment still seems like the most applicable solution, as even your second option would mean adding a `provider` var to each resource. This is not ideal, as if someone forgets to add a `depends_on` in the resource, this could wreak havoc. 

Another solution would be to use a python wrapper around terraform, but that would definitely be a last resort. 

Any further help will be hugely appreciated!

**Comment by dpiddockcmp** [comment]
The provider is not correctly configured if you need to update your default kube config in order for the kubernetes provider to modify the correct cluster. It should not require external configuration files.

**Comment by Murty0** [comment]
// EU-WEST-1 in /eu-west-1/backend
provider "aws" {
  region  = var.region // value is `eu-west-1` in terraform.tfvars
  version = "= 2.63"
}
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster_auth.token
  load_config_file       = false
  version                = "~> 1.11.1"
}
module "eks_cluster" {
  ...
}
// EU-WEST-2 in /eu-west-2/backend
provider "aws" {
  region  = var.region // value is `eu-west-2` in terraform.tfvars
  version = "= 2.63"
}
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster_auth.token
  load_config_file       = false
  version                = "~> 1.11.1"
}
module "eks_cluster" {
  ...
}
When we cd into `/eu-west-1/backend` and `terraform apply`, then consequently cd into `/eu-west-2/backend` it will not switch the context to our `eu-west-2` EKS cluster.

**Comment by mikeaorlando** [comment]
I encountered the same issue (multiple terraform workspaces using shared configuration, getting applied to the system-wide cluster-context). I did not have a kubernetes provider block defined, I was relying on the one defined in the EKS module.

I created a workaround by specifying the clusters in a similar way. All of the variables in this below `providers.tf` are configured per terraform workspace.

### providers.tf
```
...
(other providers)
...
provider "kubernetes" {
  version = "~> 1.11.1"
  config_path = "~/.kube/config"
  config_context = "arn:aws:eks:${var.environment-region}:${var.environment-account}:cluster/${var.environment-name}"
}
```

I used `kubectl config use-context arn:aws:eks:us-west-2:xxxxxxxx:cluster/production` to set the system wide default cluster context then switched to the development workspace and ran `terraform apply`. My changes showed up in my development cluster `arn:aws:eks:us-east-1:yyyyyyyyyyy:cluster/development`

In this case, I manually added these clusters to my `~/.kube/config` file by running `aws eks --region REGION update-kubeconfig --name CLUSTER_NAME` after the first terraform apply when I had no kubernetes provider defined.

I have not yet been able to find the way to get this process fully automated.

**Comment by Murty0** [comment]
hey @mikeaorlando, my solution outlined in the issue's main comment is what we are using now. We have added the `null_resource.eks_context_switcher` as a `depends_on` meta-argument to each k8s resource, and now this has been pretty much automated for us. I was still looking for a better solution so we dont need to add this manually to each resource, but looks like there isnt one!
