### ISSUE TITLE
can't apply if trying to remove worker_groups_launch_template

### ISSUE THREAD

**Issue by tnimni** [terraform-aws-modules/terraform-aws-eks#887]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
when trying to remove a worker_groups_launch_template can't apply, getting the following:
Error: Cycle: module.eks.random_pet.workers_launch_template[2], module.eks.random_pet.workers_launch_template[2] (destroy deposed 2ff3956f), module.eks.aws_launch_template.workers_launch_template[3] (destroy)

## If this is a bug, how to reproduce? Please include a code sample if relevant.
1. create an eks instance like in /examples/launch_templates
2. delete a launch template out of the two
3. try to apply

## What's the expected behavior?
should be able to remove a worker group

## Environment details

* Affected module version: 12.0.0
* OS: linux/ mac
* Terraform version:0.12.24

**Comment by GaruGaru** [comment]
I have the same issue, but this is not the suggested way to manage old worker groups: 

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#how-do-i-safely-remove-old-worker-groups

The documentation suggest to set min/max node pool size to 0 and just leave the empty node pool.
Anyway I do agree that node group deletion handling would be a nice feature but from my (limited) knowledge of the project I guess that the fact that worker_groups_launch_template is handled as a list (shifting index problem) is a big limit for the implementation .
