### ISSUE TITLE
Eager termination of cluster_https_worker_ingress preventing clean destroy

### ISSUE THREAD

**Issue by michaeljmarshall** [terraform-aws-modules/terraform-aws-eks#888]
# Problem when destroying cluster
I am trying to cleanly destroy an EKS cluster built by terraform using this module. However, there is a resource in the terraform-aws-eks module that gets destroyed too early.

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Currently, this module creates the `aws_security_group_rule` resource named `cluster_https_worker_ingress`, and then doesn't do anything else with the resource. As such, when terraform builds its dependency graph, there are no resources dependent on `aws_security_group_rule.cluster_https_worker_ingress`. This is not a problem on cluster creation, but it is a problem on cluster deletion because some helm charts run kubernetes jobs to destroy kubernetes resources, like CRDs. These jobs need to be able to make calls to the control plane, and without the above security group rule, there is a chance that the security group rule will be destroyed before the kubernetes job runs.

## What's the expected behavior?
I am requesting that a reference to the `aws_security_group_rule.cluster_https_worker_ingress` resource (or all `aws_security_group_rule` resources) are output in the `outputs.tf` file so that dependencies can easily be established and terraform can run delete helm resources before deleting the security group rules.

## Are you able to fix this problem and submit a PR? Link here if you have already.
I can submit a PR for this feature, assuming it is acceptable.

**Comment by dpiddockcmp** [comment]
#901 fixing this request has been merged.

**Comment by dpiddockcmp** [comment]
This has been released in v12.1.0
