### ISSUE TITLE
using dynamic expression inside module call for eks

### ISSUE THREAD

**Issue by amitsehgal** [terraform-aws-modules/terraform-aws-eks#897]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ X] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

I'm not sure if it's directly related to this module or in general terraform. I'm planing to create node group vs worker group conditional. Tried using dynamic like

```
module "eks-cluster" {
  source                           = "github.com/terraform-aws-modules/terraform-aws-eks?ref=v11.1.0"
  cluster_name                     = local.cluster_name

  dynamic "node_groups_defaults" {
    for_each = var.node_groups_enabled ? ["true"] : []
    content {
      ami_type  = "AL2_x86_64"
      disk_size = 50
      subnets = split(",",var.private_subnet_ids)
    }
  }
```
getting an error

  on main.tf line 76, in module "eks-cluster":
  76:   dynamic "node_groups_defaults" {

Blocks of type "dynamic" are not expected here.

I've used dynamic with resources but not much with modules calls.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Use dynamic block inside eks module call

## What's the expected behavior?

It is suppose to compile since node_groups works as individual block
 node_groups_defaults = {

      ami_type  = "AL2_x86_64"
      disk_size = 50
      subnets = split(",",var.private_subnet_ids)
  }
## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by dpiddockcmp** [comment]
[dynamic blocks](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks) don't work on modules.

This does not make sense here either. `node_groups_defaults` is a map of default values to use when creating the node groups defined in the `node_groups` map.

`node_groups` is a map. You can conditionally create it by using the `for` expression. I'm not sure if conditional creation of it will work though. You will need to be careful. The node_groups sub module makes heavy use of the `for_each` expression. This means that Terraform must know the keys to the map before it can decide which resources will need creating. It will give you a big warning and refuse to do anything if you get it wrong.

**Comment by amitsehgal** [comment]
thanks..yep i tried with node_groups as wel...yep...looked like something isn't making sense. Thanks

**Comment by RuBiCK** [comment]
@amitsehgal did you make it work?
