### ISSUE TITLE
How to add TAGs to EBS volumes created using module

### ISSUE THREAD

**Issue by kkapoor1987** [terraform-aws-modules/terraform-aws-eks#898]
I would like to make sure all the aws resources created via module is tagged correctly. 

Currently we set tags like this but seems like this doesnt work for ebs volumes 
workers_group_defaults = {
    tags = [{
      key                 = "TestTag"
      value               = "eks-worker"
      propagate_at_launch = true
    }]
  }

**Comment by dpiddockcmp** [comment]
Hi,

ASG do not propagate tags to volumes, only instances. This is a limitation on the service.

Launch configurations also do not support tagging of volumes.

However the launch template resource does allow specifying tags on volumes. You can create them with the `worker_groups_launch_template` variable to the module. See the [example code](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.0.0/examples/launch_templates/main.tf#L67) for basic use. The tags applied to instances and volumes are from the top level `tags` variable. See the code [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.0.0/workers_launch_template.tf#L391)

Hope that helps

**Comment by kkapoor1987** [comment]
@dpiddockcmp  Thanks for the pointer. I spent some time in trying this out. The issue I am seeing is that if I update from LC --> LT it enforces ASG recreation which means we lose all the instances in the cluster at once.

**Comment by dpiddockcmp** [comment]
Yes, it would do. I would suggest:
- adding the launch_template workers block
- applying the terraform
- draining all the old nodes created via the launch configs ASG
- removing old launch config workers block
- applying terraform to remove launch config ASG

**Comment by kkapoor1987** [comment]
@dpiddockcmp  This is interesting. So you are suggesting I can still have ASG based on both LT & LC at the same time. I am going to try that.

**Comment by kkapoor1987** [comment]
@dpiddockcmp for your help. I think we can close the issue
