### ISSUE TITLE
dyld: Library Not Loaded

### ISSUE THREAD

**Issue by mjarmijo** [terraform-aws-modules/terraform-aws-eks#909]
# I have issues
Installing the EKS module with VPC 

## I'm submitting a...

* [X ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Terraform errors out at the end of applying my plan with this message: 
```
module.my-cluster.module.my-cluster.null_resource.wait_for_cluster[0]: Still creating... [3m0s elapsed]
module.my-cluster.module.my-cluster.null_resource.wait_for_cluster[0] (local-exec): dyld: Library not loaded: /usr/local/opt/libidn2/lib/libidn2.4.dylib
module.my-cluster.module.my-cluster.null_resource.wait_for_cluster[0] (local-exec):   Referenced from: /usr/local/bin/wget
module.my-cluster.module.my-cluster.null_resource.wait_for_cluster[0] (local-exec):   Reason: image not found
module.my-cluster.module.my-cluster.null_resource.wait_for_cluster[0] (local-exec): /bin/sh: line 1: 46698 Abort trap: 6           wget --no-check-certificate -O - -q $ENDPOINT/healthz > /dev/null
module.my-cluster.module.my-cluster.null_resource.wait_for_cluster[0] (local-exec): dyld: Library not loaded: /usr/local/opt/libidn2/lib/libidn2.4.dylib
module.my-cluster.module.my-cluster.null_resource.wait_for_cluster[0] (local-exec):   Referenced from: /usr/local/bin/wget
module.my-cluster.module.my-cluster.null_resource.wait_for_cluster[0] (local-exec):   Reason: image not found
module.my-cluster.module.my-cluster.null_resource.wait_for_cluster[0] (local-exec): /bin/sh: line 1: 46700 Abort trap: 6           wget --no-check-certificate -O - -q $ENDPOINT/healthz > /dev/null
module.my-cluster.module.my-cluster.null_resource.wait_for_cluster[0]: Still creating... [3m10s elapsed]
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

I'm not sure what would be helpful to reproduce this error. As far as I can remember this code was working, but when I reran it recently I ran into this error. 

## What's the expected behavior?
EKS cluster should be created without error. 

## Environment details

* Affected module version:
+ provider.aws v2.53.0
+ provider.http v1.1.0
+ provider.kubernetes v1.11.3
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
* OS: mac high sierra 10.13.4
* Terraform version: Terraform v0.12.19

**Comment by dpiddockcmp** [comment]
Looks like there's either something wrong with your wget install or how Terraform is trying to call it. What happens if you run `/usr/local/bin/wget` directly?

**Comment by mjarmijo** [comment]
I missed that in the output, thanks for pointing it out.  I'm on a mac, so reinstalling wget with brew `brew reinstall -s wget` is what got it working. Thanks.
