### ISSUE TITLE
irsa example: E0609 14:28:46.605089       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.CSINode: the server could not find the requested resource

### ISSUE THREAD

**Issue by weimin** [terraform-aws-modules/terraform-aws-eks#912]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?

At the end of the guide of the irsa readme it asks that we verify the logs and it says server could not find the requested resource:
(base) Weis-MBP:irsa weimin$ kubectl --namespace=kube-system logs -l "app.kubernetes.io/name=aws-cluster-autoscaler"
I0609 14:28:46.452502       1 static_autoscaler.go:343] No unschedulable pods
I0609 14:28:46.452516       1 static_autoscaler.go:390] Calculating unneeded nodes
I0609 14:28:46.452532       1 pre_filtering_processor.go:66] Skipping ip-10-0-3-133.us-west-2.compute.internal - node group min size reached
I0609 14:28:46.452571       1 static_autoscaler.go:439] Scale down status: unneededOnly=true lastScaleUpTime=2020-06-09 14:25:45.78008777 +0000 UTC m=+3.560774141 lastScaleDownDeleteTime=2020-06-09 14:25:45.78008907 +0000 UTC m=+3.560775478 lastScaleDownFailTime=2020-06-09 14:25:45.780090413 +0000 UTC m=+3.560776828 scaleDownForbidden=false isDeleteInProgress=false scaleDownInCooldown=true
I0609 14:28:46.603707       1 reflector.go:188] Listing and watching *v1.CSINode from k8s.io/client-go/informers/factory.go:135
E0609 14:28:46.605089       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.CSINode: the server could not find the requested resource
I0609 14:28:47.605315       1 reflector.go:188] Listing and watching *v1.CSINode from k8s.io/client-go/informers/factory.go:135
E0609 14:28:47.606732       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.CSINode: the server could not find the requested resource
I0609 14:28:48.606953       1 reflector.go:188] Listing and watching *v1.CSINode from k8s.io/client-go/informers/factory.go:135
E0609 14:28:48.608360       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.CSINode: the server could not find the requested resource

## If this is a bug, how to reproduce? Please include a code sample if relevant.
$ kubectl get nodes
NAME                                       STATUS   ROLES    AGE   VERSION
ip-10-0-3-133.us-west-2.compute.internal   Ready    <none>   63s   v1.16.8-eks-e16311
$ helm repo add stable https://kubernetes-charts.storage.googleapis.com
$ helm install cluster-autoscaler --namespace kube-system stable/cluster-autoscaler --values=cluster-autoscaler-chart-values.yaml
NAME: cluster-autoscaler
LAST DEPLOYED: Tue Jun  9 07:25:36 2020
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
To verify that cluster-autoscaler has started, run:

  kubectl --namespace=kube-system get pods -l "app=aws-cluster-autoscaler,release=cluster-autoscaler"

## What's the expected behavior?

Listed in the readme: 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa/README.md

## Are you able to fix this problem and submit a PR? Link here if you have already.

No, I am new to aws and not sure what the problem is. I checked https://github.com/kubernetes/autoscaler/issues/2628 but not sure what it means CA 1.17 is not supposed to be used on k8s 1.14. I am guessing this is k8s 1.16 from above and CA means cluster autoscaler. I tried this https://stackoverflow.com/questions/47130170/how-to-check-kubernetes-cluster-autoscaler-version but nothing was printed. Thanks!

## Environment details
* Affected module version: 
* OS: OSX 
* Terraform version:
$ terraform version
Terraform v0.12.26
+ provider.aws v2.65.0
+ provider.kubernetes v1.11.3
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

**Comment by damm** [comment]
You need an older version of the autoscaler to match the version of the k8s cluster you are running.  If you specify v1.16 as the cluster version below should work for you.

```
helm install cluster-autoscaler --namespace kube-system stable/cluster-autoscaler --values=cluster-autoscaler-chart-values.yaml --set image.tag=v1.16.5 --set image.repository=us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler
```

**Comment by weimin** [comment]
Thanks!
