### ISSUE TITLE
SG rule cluster_private_access can't be created if manage_aws_auth isn't enabled

### ISSUE THREAD

**Issue by arielvinas** [terraform-aws-modules/terraform-aws-eks#914]
The problem is in cluster.tf:

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/f2c4383719354c5bfcb4f15d34555e6b1cc5406d/cluster.tf#L49

This should not be like this, because there's a big chance that the clusted should have private access only even if the module isn't configuring the aws_auth configmap itself.

**Comment by dpiddockcmp** [comment]
Fix has been merged. Thank you.

**Comment by anthonydahanne** [comment]
hello all
I believe this fix has introduced a regression issue: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/915#issuecomment-675535037
Can we please revert it?
Thanks
