### ISSUE TITLE
config_map_aws_auth not being output

### ISSUE THREAD

**Issue by mjarmijo** [terraform-aws-modules/terraform-aws-eks#916]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ X] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I have included two outputs in the moduel, kubeconfig and config_map_aws_auth. The kubeconfig is saved in my project repo when I run a terraform apply, but the config_map is not.  How do I get terraform to output and save the config_map like it is doing with the kubeconfig?

My output.tf file is as follows:
```
# eks
output "kubeconfig" {
  description = "The kubeconfig"
  value       = module.my-cluster.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.my-cluster.config_map_aws_auth[0].data
}
```
(Note: I've also tried  the following with no luck`value = module.my-cluster.config_map_aws_auth`)

here is the config for my eks cluster:
```
module "my-cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = var.eks_cluster_name
  cluster_version = "1.13"
  subnets         = var.subnet_ids
  vpc_id          = var.vpc_id
  manage_aws_auth	= true
```
## What's the expected behavior?
config_map_aws_auth should be saved locally. 

## Environment details

* Affected module version:
* OS: Mac High Sierra 10.13.4

* Terraform version:
Terraform v0.12.26
+ provider.aws v2.53.0
+ provider.http v1.1.0
+ provider.kubernetes v1.11.3
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1

**Comment by dpiddockcmp** [comment]
When you say "save the config map" do you mean it should create a file?

Terraform outputs are stored in Terraform's state. They are not automatically written to file.

The module creates the kubeconfig file using a local_file resource [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.1.0/kubectl.tf).

You could also use a local_file resource to write `module.my-cluster.config_map_aws_auth[0].data` to a file.

**Comment by dpiddockcmp** [comment]
`terraform output` only has access to outputs from the root module. You need to define them.

**Comment by mjarmijo** [comment]
Thank you, I was able to get the `config_map_aws_auth` to output after reading this and reviewing the docs.  When I got this working, though the key value was `module.my-cluster.config_map_aws_auth["mapRoles"]` which actually got the output working, not `[0]`. Any reason for the discrepancy? 

I tried to implement the local_file resources to write the config_map to a file, and I was able to get the file to output, but the config map isn't being stored in that file. 

This runs without error:
config_map.tf
```
resource "local_file" "config_map_aws_auth_file" {
  # count                = var.write_kubeconfig && var.create_eks ? 1 : 0
  count                = 1
#  content              =  local.config_map_aws_auth["mapRoles"].data
  #content              =  local.config_map_aws_auth[0].data
  content              = local.config_map_aws_auth
 # content              = local.module.my-cluster.config_map_aws_auth[0]
  filename             = substr(var.config_output_path, -1, 1) == "/" ? "${var.config_output_path}config_map_aws_auth_${var.cluster_name}" : var.config_output_path
  file_permission      = "0644"
  directory_permission = "0755"
}
```
variables.tf
```
variable "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  default     = ""
  type        = string
}
```


If I try and change content to local.module.my-cluster.config_map_aws_auth[0].data or local.config_map_aws_auth["mapRoles"].data, I get the following error:

```
Error: Invalid index

  on .terraform/modules/my-cluster.my-cluster/terraform-aws-eks-12.1.0/config_map.tf line 5, in resource "local_file" "config_map_aws_auth_file":
   5:   content              =  local.config_map_aws_auth[0].data

This value does not have any indices.
```

Any idea how to get this to output the config_map?  Perhaps I used the wrong type when declaring the variable, I tried map and list types, but that did not work.

**Comment by dpiddockcmp** [comment]
What is `local.config_map_aws_auth`?
`local.module.my-cluster` is invalid syntax.

Maybe you should try reading through the [Terraform documentation](https://www.terraform.io/docs/) and running through some [beginner guides](https://learn.hashicorp.com/terraform)?

**Comment by mjarmijo** [comment]
Thank you for the links to the beginner documentation, but that isn't helpful for my question. I refactored my code into my child module and solved it. 

As I've been able to figure out, the content field can only take a string. Feeding it `module.my-cluster.config_map_aws_auth[0].data` spits out a tuple - this was an issue causing an error. 

`terraform state show "module.my-cluster.module.my-cluster.kubernetes_config_map.aws_auth[0]"` helped make it obvious what was being returned and helped me figure out how to access what I wanted -- `module.my-cluster.config_map_aws_auth[0]["data"]["mapRoles"]`

In order to get the output saved in the file I had to use the following:
```
resource "local_file" "config_map_aws_auth_file" {
   count                = 1
# use this command to get view the configmap: terraform state show "module.my-cluster.module.my-cluster.kubernetes_config_map.aws_auth[0]"
  content              = tostring(module.my-cluster.config_map_aws_auth[0]["data"]["mapRoles"])
  filename             = "config_map_aws_auth_${var.eks_cluster_name}"
  file_permission      = "0644"
  directory_permission = "0755"
}
```

**Comment by dpiddockcmp** [comment]
Great that you solved your problem

**Comment by mjarmijo** [comment]
Thanks for recommending the local_file resource!
