### ISSUE TITLE
Error: server misbehaving

### ISSUE THREAD

**Issue by ivanfarkas2** [terraform-aws-modules/terraform-aws-eks#921]
# I have issues
I am running the Hashicorp official training session **[Provision an EKS Cluster (AWS)](https://learn.hashicorp.com/terraform/kubernetes/provision-eks-cluster)**. 
It's using the **terraform-aws-eks** module (this module).

## I'm submitting a...

* [x] bug report

## What is the current behavior?

The script fails with an error.

```
module.eks.aws_autoscaling_group.workers[1]: Creation complete after 40s [id=training-eks-zmC9QkUi-worker-group-220200615133826933800000011]
module.eks.aws_autoscaling_group.workers[0]: Creation complete after 40s [id=training-eks-zmC9QkUi-worker-group-120200615133826934400000012]

Error: Post "https://99BA0F0213C481CE9D518BC3F246995D.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps": dial tcp: lookup 99BA0F0213C481CE9D518BC3F246995D.gr7.us-east-1.eks.amazonaws.com on 172.30.128.1:53: server misbehaving

  on .terraform/modules/eks/terraform-aws-eks-12.1.0/aws_auth.tf line 64, in resource "kubernetes_config_map" "aws_auth":
  64: resource "kubernetes_config_map" "aws_auth" {
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Clone **[hashicorp/learn-terraform-provision-eks-cluster](https://github.com/hashicorp/learn-terraform-provision-eks-cluster)** git repo.

```
terraform init
terraform apply
```

## What's the expected behavior?

terraform apply complets without an error.

## Are you able to fix this problem and submit a PR? Link here if you have already.
No

## Environment details

* Affected module version:
  - terraform-aws-modules/vpc/aws 2.39.0
  - terraform-aws-modules/eks/aws 12.1.0

* OS: Ubuntu 20.04 LTS
* Terraform version: 0.12.26

**Comment by dpiddockcmp** [comment]
The error you are getting is usually related to DNS issues in go-lang.

There is a massive bug in the repo you are following. Issues have already been filed against it.

The example does not properly configure the kubernetes terraform provider. It also looks like the repo has been abandoned by the author. Please apply the fix from the PR against that repo and try again: https://github.com/hashicorp/learn-terraform-provision-eks-cluster/pull/4
