### ISSUE TITLE
manage_aws_auth=True incompatible with multiple clusters in same plan

### ISSUE THREAD

**Issue by charandas** [terraform-aws-modules/terraform-aws-eks#926]
# `manage_aws_auth=True` unusable with multiple clusters in same tf plan

It assumes that the unaliased/default kubernetes provider is what it needs to reference. The docs should mention that it is impossible to manage aws_auth configmap for multiple clusters in the same plan, unless people want to copy over the aws_auth.tf code from this provider, and use it in a non-DRY way by specifying the kubernetes provider alias name for the config map resource.

## Relevant code in provider

As covered in [aws_auth.tf](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/aws_auth.tf#L64), there is no mention of a `provider` field. Also, its impossible to provide a dynamic value for `provider` anyway.

```tf
resource "kubernetes_config_map" "aws_auth" {
// does not have a provider = <kubernetes.alias_name> argument, so goes by default
// which will not be the correct cluster config for all but one cluster
...
}
```

* [ ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy
* [x] doc-change since it's a limitation that I don't see being addressable. Terraform provider value for a resource cannot come from a `var`. They [cannot be dynamic](https://discuss.hashicorp.com/t/defining-provider-aliases-with-string-interpolation-not-working-in-terraform-0-12/1569/4).

## What is the current behavior?

1. Create a cluster with kubernetes provider block to manage the `aws_auth` config map
2. Create a second cluster with a separate kubernetes provider block (this time aliasing it) and you will get the aws_auth configmap already exists error

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```
resource "aws_iam_role" "test_cluster_eks_access_role" {
  name = "test-cluster-eks-access-role"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "AWS": "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF

  tags = {
    role = "eks-accessor"
  }
}

module "test-cluster-1" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "test-1"
  cluster_version = "1.15"
  subnets         = setunion(data.aws_subnet_ids.private.ids, data.aws_subnet_ids.public.ids)
  vpc_id          = module.vpc.vpc_id
  enable_irsa     = true
  manage_aws_auth = true

  node_groups_defaults = {
    ami_type  = "AL2_x86_64"
    disk_size = 50
  }

  node_groups = {
    default = {
      desired_capacity = 3
      max_capacity     = 3
      min_capacity     = 3

      instance_type = "m5.xlarge"
      k8s_labels = {
        Environment = "test"
      }
    }
  }

  map_roles = [
    {
      rolearn = aws_iam_role.test_cluster_eks_access_role.arn
      username = "test-cluster-eks-access-role"
      groups   = ["system:masters"]
    }
  ]
}

data "aws_eks_cluster" "test_1" {
  name = module.test-cluster-1.cluster_id
}

data "aws_eks_cluster_auth" "test_1" {
  name = module.test-cluster-1.cluster_id
}

locals {
  test_cluster_oidc_issuer_url = module.test-cluster-1.cluster_oidc_issuer_url
  test_oidc_provider_arn = module.test-cluster-1.oidc_provider_arn
}

output "test_cluster_oidc_issuer_url" {
  value = local.test_cluster_oidc_issuer_url
}

output "test_oidc_provider_arn" {
  value = local.test_oidc_provider_arn
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.test_1.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.test_1.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.test_1.token
  load_config_file       = false
  version                = "~> 1.9"
}

module "test-cluster-2" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "test-2"
  cluster_version = "1.15"
  subnets         = setunion(data.aws_subnet_ids.private.ids, data.aws_subnet_ids.public.ids)
  vpc_id          = module.vpc.vpc_id
  enable_irsa     = true
  manage_aws_auth = true // will fail with aws_auth configmaps already exists

  node_groups_defaults = {
    ami_type  = "AL2_x86_64"
    disk_size = 50
  }

  map_roles = [
    {
      rolearn = aws_iam_role.test_cluster_eks_access_role.arn
      username = "test-cluster-eks-access-role"
      groups   = ["system:masters"]
    }
  ]
}

data "aws_eks_cluster" "test_2" {
  name = module.test-cluster-2.cluster_id
}

data "aws_eks_cluster_auth" "test_2" {
  name = module.test-cluster-2.cluster_id
}

// fails to register the cm due to already exists error
provider "kubernetes" {
  alias                  = "test-2"
  host                   = data.aws_eks_cluster.test_2.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.test_2.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.test_2.token
  load_config_file       = false
  version                = "~> 1.11"
}

```

## What's the expected behavior?

N/A

## Are you able to fix this problem and submit a PR? Link here if you have already.

I can submit a doc change once it's verified that I am thinking correctly about this.

## Environment details

* Affected module version: N/A
* OS: N/A
* Terraform version: 0.12

**Comment by charandas** [comment]
Is it possible, there is a way through `kubeconfig_filename` on the outputs, to be fed back in to `kubernetes` provider for things like `configmap` generation/applies?

That might be a way to do it without overriding provider aliases.

**Comment by dpiddockcmp** [comment]
You need to configure a `kubernetes` provider for each cluster and pass it through to the module. The terraform docs for working with multiple providers is [over here](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances)

But basically something like:
```hcl
provider "kubernetes" {
  alias = "test-2"
  # Configure with data sources from cluster-test-2
}

module "test-cluster-2" {
  source = "terraform-aws-modules/eks/aws"
  providers = {
    kubernetes = kubernetes.test-2
  }
}
```

**Comment by charandas** [comment]
Thanks @dpiddockcmp. I have been using terraform for many years, but have had limited experience with inter-module deps. Thanks for the direction.
