### ISSUE TITLE
workers_additional_policies does not attach policies to worker node

### ISSUE THREAD

**Issue by james-knott** [terraform-aws-modules/terraform-aws-eks#930]
# I have issues
Using workers_additional_policies I have placed the arn of three policies and they are not attaching to the worker node.

## I'm submitting a...

* [X ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

The policies get created but do not get attached.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

create a module and add this line

workers_additional_policies = [module.my-eks.route53policy.arn,module.my-eks.albpolicy.arn,module.my-eks.wafpolicy.arn]

## What's the expected behavior?

Expect it to add the policy and attach to worker node

## Are you able to fix this problem and submit a PR? Link here if you have already.

Here is the code from the module. var.manage_worker_iam_resources && var.create_eks are set to true in my cluster

resource "aws_iam_role_policy_attachment" "workers_additional_policies" {
  count      = var.manage_worker_iam_resources && var.create_eks ? length(var.workers_additional_policies) : 0
  role       = aws_iam_role.workers[0].name
  policy_arn = var.workers_additional_policies[count.index]
}

## Environment details

* Affected module version:
* OS: Linux
* Terraform version: 12.24

## Any other relevant info
EKS version 1.15.10

**Comment by dpiddockcmp** [comment]
This appears to work for me.

Just for testing I created the following module:
```hcl
module "eks" {
  source       = "../.."
  cluster_name = local.cluster_name
  subnets      = module.vpc.private_subnets

  vpc_id = module.vpc.vpc_id

  worker_groups = [
    {
      name                          = "worker-group-1"
      instance_type                 = "t2.small"
      asg_desired_capacity          = 1
    },
  ]

  # Example AWS managed policy for testing
  workers_additional_policies = ["arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"]
}
```

And got the expected policy attachment in the plan output:
```
  # module.eks.aws_iam_role_policy_attachment.workers_additional_policies[0] will be created
  + resource "aws_iam_role_policy_attachment" "workers_additional_policies" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"
      + role       = "test-eks-fBrYSBwR20200628121230482600000009"
    }
```

The policy was successfully attached:
```
aws iam list-attached-role-policies --role-name test-eks-fBrYSBwR20200628121230482600000009 --query AttachedPolicies[*].[PolicyArn] --output text
arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
```

Setting `manage_worker_iam_resources = false` would stop the attachment of the policies. The policies must exist before applying resources from the module due to the use of `count`. Apart from that I do now know why the attachment would not be created.

**Comment by k8s-class** [comment]
Thank you

**Comment by james-knott** [comment]
I tried to duplicate what you did and terraform plan is not recognizing the policy and does not give any output that something new was put in place.

**Comment by james-knott** [comment]
I used the example code in the basic code folder and it works fine. So I'm just trying to figure out why my cluster is not picking it up.

**Comment by skimwpi** [comment]
I had the same issue where workers_additional_policies would not attach policies to worker node. After struggling a bit, I realized my mistake. I had the "workers_additional_policies" INSIDE the worker_groups block under one of the worker group. Terraform plan will not complain but it is not going to detect any changes.
