### ISSUE TITLE
Terraform aws_eks_node_group doesn't set a correct group name 

### ISSUE THREAD

**Issue by seasadm** [terraform-aws-modules/terraform-aws-eks#931]
# I have issues
aws_eks_node_group doesn't set a correct group name from value node_group_name to Auto Scaling Groups

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Auto Scaling Groups after creation by aws_eks_node_group have random name (like eks-0eb97841-2793-dbd5-f6a9-c0dfe217a049 )

## If this is a bug, how to reproduce? Please include a code sample if relevant.

resource "aws_eks_node_group" "stage-worker" {
  cluster_name    = aws_eks_cluster.wchess-stage.name
  node_group_name = "stage-worker"
  node_role_arn   = aws_iam_role.stage-node.arn
  subnet_ids      = aws_subnet.wchess-stage[*].id
  disk_size       = 20
  instance_types  = ["t3.medium"]

  scaling_config {
    desired_size = 1
    max_size     = 2
    min_size     = 1
  }

  labels = {
    purpose = "worker"
  }

  depends_on = [
    aws_iam_role_policy_attachment.stage-node-AmazonEKSWorkerNodePolicy,
    aws_iam_role_policy_attachment.stage-node-AmazonEKS_CNI_Policy,
    aws_iam_role_policy_attachment.stage-node-AmazonEC2ContainerRegistryReadOnly,
  ]
}

## What's the expected behavior?

Auto Scaling Group name must be equal value from node_group_name. I.E. "stage-worker".

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by dpiddockcmp** [comment]
Hi. This is a feature of how the AWS Managed Node Groups system works. The ASG name is generated by AWS's systems. This is not something the module can have any control over. I would hazard a guess thatthis is to work around any potential issues with naming conflicts. But I can't speak for the AWS container team as I have no relationship with them.

I can't see any existing request on their board about this. https://github.com/aws/containers-roadmap/issues?q=is%3Aissue+is%3Aopen+label%3A%22EKS+Managed+Nodes%22+
