### ISSUE TITLE
Eager termination of workers_egress_internet preventing clean destroy

### ISSUE THREAD

**Issue by mvaal** [terraform-aws-modules/terraform-aws-eks#934]
# Problem when destroying cluster
Referencing https://github.com/terraform-aws-modules/terraform-aws-eks/issues/888 as it is a very similar issue.

I am trying to cleanly destroy an EKS cluster built by terraform using this module. However, there is a resource in the terraform-aws-eks module that gets destroyed too early.

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Currently, this module creates the aws_security_group_rule resource named workers_egress_internet, and then doesn't do anything else with the resource. As such, when terraform builds its dependency graph, there are no resources dependent on aws_security_group_rule.workers_egress_internet. This is not a problem on cluster creation, but it is a problem on cluster deletion because some helm charts run kubernetes jobs to destroy kubernetes resources, like Prometheus Operator. These jobs need to make a call to the internet to pull a docker container to run a job before launch, there is a chance that the security group rule will be destroyed before the kubernetes job runs.

https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml#L34
https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml#L27

## What's the expected behavior?
I am requesting that a reference to the aws_security_group_rule.workers_egress_internet resource (or all aws_security_group_rule resources) are output in the outputs.tf file so that dependencies can easily be established and terraform can run delete helm resources before deleting the security group rules.

## Are you able to fix this problem and submit a PR? Link here if you have already.
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/933

**Comment by dpiddockcmp** [comment]
Would it be an idea to make the worker and worker launch template ASGs depend on these security group rules, and also the iam_role_policy_attachments? That way external resources do not need to worry about internal workings.

**Comment by mvaal** [comment]
I think that would work, 

> Would it be an idea to make the worker and worker launch template ASGs depend on these security group rules, and also the iam_role_policy_attachments? That way external resources do not need to worry about internal workings.

I think that would work, I don't think there are any circular dependencies there.

**Comment by mvaal** [comment]
I updated the PR with your proposal. If you think that is a better solution (I think so) I will change the description, otherwise I will roll it back to what I had originally.

**Comment by dpiddockcmp** [comment]
Thank you for the update. I think having the workers and cluster depend on the security groups and iam policies is a better solution than requiring external resources to depend on outputs.

Maybe this will also solve some other cluster termination race conditions?

**Comment by dpiddockcmp** [comment]
Fixed via #933
