### ISSUE TITLE
using custom IAM roles/policies and security groups

### ISSUE THREAD

**Issue by rah44** [terraform-aws-modules/terraform-aws-eks#935]
I am not able to use custom IAM roles/policies and security groups while creating eks cluster with worker nodes.
Even though i provided below parameters, its still creating new IAM roles and security groups.

  worker_security_group_id     = "my-sg-id"
  worker_additional_security_group_ids = ["my-sg-id-additional"]
  workers_role_name                 = "my-ec2-instance-profile"
  manage_worker_iam_resources       = false
  worker_create_security_group      = false 
  manage_cluster_iam_resources      = false
  cluster_iam_role_name             = "my-cluster_iam_role_name"
  cluster_create_security_group     = false

**Comment by dpiddockcmp** [comment]
What roles and security groups are you seeing created?

I created a cluster and all the necessary roles and security groups with the [basic example](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/9a0e548dcc9606ac79522363f26aacfc01647ff3/examples/basic).

I then started a new state file with the following configuration, using resources created from the example cluster:
```hcl
module "eks" {
  source       = "../.."
  cluster_name = local.cluster_name
  subnets      = ["subnet-03a811544582bca622", "subnet-0ae13755488620adc", "subnet-0a5c2906403050f83"]

  vpc_id = "vpc-01fbf81e6d62472be"

  worker_groups = [
    {
      name                 = "worker-group-1"
      instance_type        = "t2.small"
      asg_desired_capacity = 0
      asg_min_size         = 0
    },
  ]

  workers_group_defaults = {
    iam_instance_profile_name = "test-eks-fBrYSBwR2020062812123154540000000b"
  }

  worker_security_group_id             = "sg-018b291e6a2067772"
  worker_additional_security_group_ids = ["sg-068e4ca8929cbe63a"]
  workers_role_name                    = "test-eks-fBrYSBwR20200628121230482600000009"
  manage_worker_iam_resources          = false
  worker_create_security_group         = false
  manage_cluster_iam_resources         = false
  cluster_iam_role_name                = "test-eks-fBrYSBwR20200628115935737800000001"
  cluster_create_security_group        = false
}
```

The terraform plan only wanted to create the following resources:
```
  # data.aws_eks_cluster.cluster will be read during apply
  # data.aws_eks_cluster_auth.cluster will be read during apply
  # random_string.suffix will be created
  # module.eks.data.template_file.userdata[0] will be read during apply
  # module.eks.aws_autoscaling_group.workers[0] will be created
  # module.eks.aws_eks_cluster.this[0] will be created
  # module.eks.aws_launch_configuration.workers[0] will be created
  # module.eks.kubernetes_config_map.aws_auth[0] will be created
  # module.eks.local_file.kubeconfig[0] will be created
  # module.eks.null_resource.wait_for_cluster[0] will be created
  # module.eks.random_pet.workers[0] will be created

Plan: 8 to add, 0 to change, 0 to destroy.
```
No IAM or security group resources.

**Comment by rah44** [comment]
Thanks Daniel,

I made this work, now new IAM and SG resources are not creating. Previously I included those values inside worker groups. 

worker_groups = [
    {
######
    },
  ]
Now I have moved them outside and now all good.

**Comment by gnan-s** [comment]
Hello @dpiddockcmp 
Can values to both "workers_role_name" and "iam_instance_profile_name" be same? I got the worker and cluster iam roles created as I dont have permissions to do so. I am launching a cluster with 5 worker nodes

Thanks
