### ISSUE TITLE
Private security rules not created when they should

### ISSUE THREAD

**Issue by alexppg** [terraform-aws-modules/terraform-aws-eks#942]
# I have issues

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [X] kudos, thank you, warm fuzzy

Thanks for your work! This module is awesome!

## What is the current behavior?
I'm having the next problem. When creating an EKS with both public and private endpoints, the security group rules are not added.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

With this code:
```hcl

module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = local.cluster_name
  cluster_version = var.eks_version
  version         = "v12.1.0"
  subnets = concat(
    data.terraform_remote_state.vpc.outputs.private_subnets_ids,
    data.terraform_remote_state.vpc.outputs.public_subnets_ids,
  )
  tags                                  = local.tags
  vpc_id                                = data.terraform_remote_state.vpc.outputs.vpc_id
  worker_groups                         = local.worker_groups
  manage_aws_auth                       = true
  map_users                             = local.k8s_map_users
  cluster_create_security_group         = true
  cluster_endpoint_public_access        = true
  cluster_endpoint_public_access_cidrs  = local.endpoint_public_access_cidr
  cluster_endpoint_private_access       = true
  cluster_endpoint_private_access_cidrs = ["10.70.0.0/16"]
  cluster_enabled_log_types             = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
}
```

I should be able to reach from the network `10.70.0.0/16` the k8s api. But I can't, since [this rule](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9a0e548dcc9606ac79522363f26aacfc01647ff3/cluster.tf#L49) is not created. I know that's not created because I examine the output of terraform state:

```bash
terraform state list | grep cluster_private
```

## What's the expected behavior?

I should be able to reach the api within a private subnet added to `cluster_endpoint_private_access_cidrs`.

## Are you able to fix this problem and submit a PR? Link here if you have already.

I can't, since I don't know the implications of the change. But taking a look to the code, in [this line](cluster_endpoint_private_access_cidrs) you can see the next:

```hcl
resource "aws_security_group_rule" "cluster_private_access" {
  count       = var.create_eks && var.cluster_endpoint_private_access && var.cluster_endpoint_public_access == false ? 1 : 0
  type        = "ingress"
  from_port   = 443
  to_port     = 443
  protocol    = "tcp"
  cidr_blocks = var.cluster_endpoint_private_access_cidrs

  security_group_id = aws_eks_cluster.this[0].vpc_config[0].cluster_security_group_id
}
```

I think it should be changed to:

```hcl
resource "aws_security_group_rule" "cluster_private_access" {
  count       = var.create_eks && var.cluster_endpoint_private_access 
  type        = "ingress"
  from_port   = 443
  to_port     = 443
  protocol    = "tcp"
  cidr_blocks = var.cluster_endpoint_private_access_cidrs

  security_group_id = aws_eks_cluster.this[0].vpc_config[0].cluster_security_group_id
}
```

So the ternary operator should go out, since if you have a private endpoint, you want to modify it's SG, whether you have a public endpoint or not. If that makes sense, I can make a PR without problem, it's a small change.

## Environment details

* Affected module version: v12.1.0
* OS: Arch Linux
* Terraform version: v0.12.28

**Comment by ksmuthuus** [comment]
I workaround by adding a security group rule to the cluster security group id available in eks module output:
`resource "aws_security_group_rule" "cluster_private_access" {
  type        = "ingress"
  from_port   = 443
  to_port     = 443
  protocol    = "tcp"
  cidr_blocks = var.k8s_api_private_access_cidr
  security_group_id = module.eks.cluster_security_group_id
}`
