### ISSUE TITLE
Document how to wait for cluster availability before creating kubernetes resources

### ISSUE THREAD

**Issue by mogul** [terraform-aws-modules/terraform-aws-eks#943]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?
I was unable to figure out how to delay creation of kubernetes resources until the cluster is fully available. I saw a lot of search hits for people experiencing the same problem. There were comments about using a null_resource to get around the problem, mimicking [what happens with the `kubernetes_config_map` in `aws_auth.tf`](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9a0e548dcc9606ac79522363f26aacfc01647ff3/aws_auth.tf#L64-L83), but those comments were by people smarter and more capable than me. 

Finally I found [comments in `outputs.tf`](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9a0e548dcc9606ac79522363f26aacfc01647ff3/outputs.tf#L4-L5) as of PR #890 by @dpiddockcmp indicating an intent to make this easy for users of the module:
```
output "cluster_id" {
  description = "The name/id of the EKS cluster."
  value       = element(concat(aws_eks_cluster.this.*.id, list("")), 0)
  # So that calling plans wait for the cluster to be available before attempting
  # to use it. They will not need to duplicate this null_resource
  depends_on = [null_resource.wait_for_cluster]
}
```

So now I was able to fix the problem by adding a `depends_on` like so: 
```
resource "kubernetes_namespace" "apps" {
  metadata {
    name = "apps"
  }
  depends_on = [
    module.eks.cluster_id
  ]
}
```

This is a **really important feature**! I spent most of day gnashing my teeth on a common problem experienced by users of the module because I didn't know about it. 

Can you please add a description of this feature to:
* the [release notes for `12.1.0`](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v12.1.0)
* the [FAQ.md](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md)
* the [documentation for `cluster_id` on the Terraform Registry](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/12.1.0?tab=outputs)

...so people like me are more likely to find it?

(Note I'm including the rest of the information below in hopes that the detail will help other people who find this problem.)

---

## If this is a bug, how to reproduce? Please include a code sample if relevant.

This all works fine
```
provider "aws" {
  region = local.region
  profile = "terraform-operator"
}

data "aws_availability_zones" "available" {
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.6.0"
  name = "vpc-${local.cluster_name}"
  cidr = "${local.vpc_cidr}" # 192.168 , 172.16
  azs = data.aws_availability_zones.available.names
  public_subnets = "${local.vpc_subnets}"

  enable_dns_support = true
  enable_dns_hostnames = true

  tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
  }
}

data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "~> 1.9"
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "12.1.0"                                               # <-- The critical bit!
  cluster_name = "${local.cluster_name}"
  subnets = module.vpc.public_subnets
  vpc_id = module.vpc.vpc_id
  map_users = var.map_users
  # worker nodes
  worker_groups_launch_template = [
    {
      name                 = "worker-group-1"
      instance_type        = "t3.large"
      asg_desired_capacity = 2
      asg_max_size = 5
      asg_min_size  = 2
      autoscaling_enabled = true
      public_ip            = true
    }
  ]
}
```

The part that failed before 12.1.0:
```
# Explicitly create namespace
resource "kubernetes_namespace" "apps" {
  metadata {
    name = "apps"
  }
}
```

## What's the expected behavior?
The creation of `kubernetes_namespace.app` succeeds without re-running Terraform.

(This works in 12.1.0!)

## What's the actual behavior?
The creation of `kubernetes_namespace.app` times out because the resource attempts creation before the cluster is ready, with a `dial tcp [ip-redacted]:443: i/o timeout` error message. 

(This is what happened in 12.0.0 and earlier.)

## Environment details

* Affected module version: 12.1.0
* OS: `docker pull abdennour/terraform:0.12.28-helm3.2.4-aws-iam-auth`
* Terraform version: 0.12.28

## Any other relevant info
None, this should be plenty.

**Comment by mogul** [comment]
By the way, there's an [upstream PR in the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/pull/11426) which would obviate the need for any workarounds like this, but it's been languishing for 6+ months... Do the module authors have any pull to get that merged?

**Comment by dpiddockcmp** [comment]
The intention of the change in 12.1.0 was so that your kubernetes resources don't have to explicitly depend on anything, if the kubernetes provider is configured following the [Usage Example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.2.0/README.md#usage-example).

Creating the basic example in 12.2.0, adding your namespace:
```hcl
resource "kubernetes_namespace" "apps" {
  metadata {
    name = "apps"
  }
}
```

Terraform apply output:
```
module.eks.null_resource.wait_for_cluster[0]: Creation complete after 2m31s [id=5478466492082028166]
data.aws_eks_cluster_auth.cluster: Refreshing state...
data.aws_eks_cluster.cluster: Refreshing state...
kubernetes_namespace.apps: Creating...
module.eks.kubernetes_config_map.aws_auth[0]: Creating...
kubernetes_namespace.apps: Creation complete after 1s [id=apps]
module.eks.kubernetes_config_map.aws_auth[0]: Creation complete after 1s [id=kube-system/aws-auth]
```

The changelog is automatically generated. This makes life a little easier but also means we can't retroactively modify it. I'll try to add something to the documentation

**Comment by dpiddockcmp** [comment]
Does #955 help clarify the situation?
