### ISSUE TITLE
Error if the desired size is less than the min size

### ISSUE THREAD

**Issue by 8398a7** [terraform-aws-modules/terraform-aws-eks#944]
# I have issues

I can't update the min size of the node group.

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

`InvalidParameterException: desiredSize is not valid`

## If this is a bug, how to reproduce? Please include a code sample if relevant.

First create a node group with `min: 1, desired: 1, max: 2`.
Then if I try to update to `min: 2, desired: 2, max: 3`, I get an error.

This is because the desired size change is ignored.
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.1.0/modules/node_groups/node_groups.tf#L48

```
      ~ scaling_config {
            desired_size = 1
            max_size     = 3
          ~ min_size     = 1 -> 2
        }
```

## What's the expected behavior?

I want to be able to change it to a min size greater than the desired size we specified when we first created the node group.

## Environment details

* Affected module version:
* OS:
* Terraform version: 0.12.28

**Comment by dpiddockcmp** [comment]
You will need to increase the desired size outside of Terraform before you can raise the minimum size.

Changes to the desired size are set to be ignored to allow for the proper functioning of the Cluster Autoscaler and similar systems. Terraform does not allow for interpolations in the lifecycle block so this cannot be changed per environment.

The aws provider sets the desired size as the value it last read from AWS when performing updates to managed node groups.

**Comment by 8398a7** [comment]
Sorry, I was mistaken.
I thought I was getting an error when I changed the desired size from something other than terraform, because the setting kept remaining in terraform first.

In fact, it didn't happen.
Thanks for the support.

**Comment by 8398a7** [comment]
But it still seems to be acting that way.
I can't make the min size larger than the desired size specified at the beginning.

1. Create a node group with min: 1, desired: 1, max: 3
2. Change the desired size from AWS console to 2
3. Change the min size to 2 in terraform

At this time, the desired size is 2 in preview, but when you actually apply it, an error appears as if the desired size is 1.
It seems that the min size cannot exceed the desired size specified at the beginning when creating the node group.

**Comment by 8398a7** [comment]
I'm really sorry. Multiple node groups were covered and I was still mistaken.
Your explanation is correct...
