### ISSUE TITLE
running terraform plan after applying aws-auth configmaps on eks cluster runs into error

### ISSUE THREAD

**Issue by punnarpulusu** [terraform-aws-modules/terraform-aws-eks#952]
# I have issues
when applying aws-auth-config map for the first time , it works fine. 

later when I do run `terraform apply` or `terraform plan` I get an error saying the couldn't connect to cluster(localhost) to obtain configmaps 

workaround : I had remove resource aws-auth-config map from the terraform state to either run plan or apply.

providers information
- `kubernetes` version `1.11`
- `aws` version `2.69`
- ``terraform` version `12.24`

## I'm submitting a... 

* [x ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

when applying aws-auth-config map for the first time , it works fine. 

later when I do run `terraform apply` or `terraform plan` I get an error saying the couldn't connect to local host to obtain configmaps 

workaround : I had remove resource aws-auth-config map from the terraform state to either run plan or apply.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

1. create cluster and have to apply aws-auth-configmaps ..
2. run terraform plan or terraform apply again 

## What's the expected behavior?

terraform plan should run as is 

## Environment details

* Affected module version: tweaked module and created one for own . 
* OS:
* Terraform version: 12.24

**Comment by dpiddockcmp** [comment]
What is your terraform configuration? Have you defined the `provider "kubernetes"` block as in the [Usage Example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.2.0/README.md#usage-example)?

**Comment by punnarpulusu** [comment]
Yes, I have defined the `provider kubernetes`

Here is the provider block using it as a example 
```
provider "kubernetes" {
  host                   = module.eks-cluster.endpoint
  cluster_ca_certificate = base64decode(module.eks-cluster.kubeconfig-certificate-authority-data)
  token                  = data.aws_eks_cluster_auth.eks-cluster.token
  load_config_file       = false
  version                = "~> 1.11"
}
```


In my module, 

I have defined 

```
resource "kubernetes_config_map" "cluster-auth-config" {
  count      = var.manage_aws_auth ? 1 : 0
  depends_on = [null_resource.wait_for_cluster[0]]
  metadata {
    name      = "aws-auth"
    namespace = "kube-system"
  }
  data = {
    mapRoles = yamlencode(
      distinct(concat(
        local.configmap-roles,
        var.configMap-roles,
      ))
    )
    mapUsers = yamlencode(var.configMap-users)
  }
}
```

here is the terraform configuration 

```
locals {
  cluster-main = {
    name                = "my-test-cluster"
    target-environments = ["sandbox"]
  }
}

data "aws_eks_cluster_auth" "eks-cluster" {
  name            = local.cluster-main["name"]
  depends_on = [module.eks-cluster]
}

provider "kubernetes" {
  host                   = module.eks-cluster.endpoint
  cluster_ca_certificate = base64decode(module.eks-cluster.kubeconfig-certificate-authority-data)
  token                  = data.aws_eks_cluster_auth.eks-cluster.token
  load_config_file       = false
  version                = "~> 1.11"
}

module "eks-cluster-sg" {
  source              = "../../modules/terraform-aws-earnin-security-group"
  description         = "eks cluster security group"
  owner               = "Myteam"
  environment         = var.environment
  target-environments = ["sandbox"]
  name                = "${local.cluster-main["name"]}-sg"
  sg-rules = [
    {
      type              = "ingress"
      description       = "ingress to allow port 0 - 65535 in TCP"
      from-port         = 0
      to-port           = 65535
      protocol          = "tcp"
      cidr-blocks       = []
      self              = true
      security-group-id = "none"
  }]
  vpc-id = "vpc-xxxxxxxxxx"
}

data "template_file" "ec2-key-file" {
  template = file("./ec2-key-pairs/my-public-key.pub")
}

resource "aws_key_pair" "eks-cluster-key" {
  key_name   = "${var.environment}-${var.region}-${local.cluster-main["name"]}-eks-cluster-key"
  public_key = data.template_file.ec2-key-file.rendered
}

module "eks-cluster" {
  source                      = "../../modules/terraform-aws-earnin-eks-cluster/"
  owner                       = "myteam"
  environment                 = var.environment
  target-environments         = ["sandbox"]
  name                        = local.cluster-main["name"]
  kubernetes-version          = var.eks-cluster-version
  vpc-endpoint-private-access = var.cluster-vpc-endpoint-private-access
  vpc-endpoint-public-access  = var.cluster-vpc-endpoint-public-access
  vpc-public-access-cidrs     = var.cluster-vpc-public-access-cidrs
  vpc-subnet-ids              = ["subnet-xxxxxxxxx123456", "subnet-xxxxxxxxx1234567", "subnet-xxxxxxxxx12345677"]
  vpc-sg-ids                  = [module.eks-cluster-sg.id]
  enabled-cluster-log-types   = var.cluster-enabled-log-types

  manage_aws_auth = true

  aws-configMap-roles = [
       module.eks-cluster-node-role.arn,
       module.eks-cluster-node-group-1.role-arn,
       module.eks-cluster-admin-role.arn,
       module.eks-cluster-viewer-role.arn,
       module.eks-cluster-app-admin-role.arn,
       module.eks-cluster-app-deployer-role.arn,
  ]

  configMap-users = [
    {
      userarn  = "arn:aws:iam::123456789:user/user2F.user2L"
      username = "user2F.user2L"
      groups   = ["system:masters"]
    },
    {
      userarn  = "arn:aws:iam::123456789:user/user1F.user1L"
      username = "user1F.user1L"
      groups   = ["system:masters"]
    },
  ]
}

resource "null_resource" "wait_for_cluster" {
  count = var.manage_aws_auth ? 1 : 0

  provisioner "local-exec" {
    command     = var.wait_for_cluster_cmd
    interpreter = var.wait_for_cluster_interpreter
    environment = {
      ENDPOINT = module.eks-cluster.endpoint
    }
  }
  depends_on = [
    module.eks-cluster,
    module.eks-cluster-sg,
  ]
}

resource "local_file" "kubeconfig" {
  content  = module.eks-cluster.kubeconfig
  filename = "${local.cluster-main["name"]}.yaml"
}


module "eks-cluster-node-group-1" {
  source                           = "../../modules/terraform-aws-earnin-eks-node-group/"
  cluster-name                     = module.eks-cluster.name
  environment                      = var.environment
  target-environments              = ["sandbox"]
  node-group-name                  = "${module.eks-cluster.name}-nodegroup-1"
  owner                            = "cloudops"
  instance-types                   = ["c5.xlarge"]
  scaling-desired-size             = 3
  scaling-max-size                 = 5
  scaling-min-size                 = 3
  subnet-ids                       = ["subnet-xxxxxxxxx123456", "subnet-xxxxxxxxx1234567", "subnet-xxxxxxxxx12345677"]
  remote-access-ssh-key-name       = aws_key_pair.eks-cluster-key.key_name
  remote-access-security-group-ids = [module.eks-cluster-sg.id]

  ng-depends-on = [module.eks-cluster]

}
```

**Comment by barryib** [comment]
Please can you refer to the [basic example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.2.0/README.md#usage-example) and this [doc](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/955/files#diff-956da29f025cba37fca9fe6b80ab5d48R104-R110) to see how to manage the aws-auth configmap and if needed how to manage kubernetes resources during the same apply.

**Comment by punnarpulusu** [comment]
@barryib  My cluster does get created and `it applies aws-auth config too` ( only when it is for first time ) but on the next terraform run ( either apply or plan ) ...  it errors out...

**Comment by barryib** [comment]
Please share your error output and debug.

**Comment by fliphess** [comment]
I have the same issue, the error that appears is: 
```
Error: Unauthorized
```

**Comment by fliphess** [comment]
Could the problem be that the token is only valid for a limited amount of time, but is saved in the state and as a result when reused every time it is not valid anymore?

**Comment by punnarpulusu** [comment]
> Could the problem be that the token is only valid for a limited amount of time, but is saved in the state, and as a result when reused every time it is not valid anymore?

@fliphess I found a workaround. Can you separate the process of AWS_AUTH creation from EKS cluster creation? though there is a little caveat, you would have manually delete AWS_AUTH configmap first and then let terraform create it.

**Comment by fliphess** [comment]
I've managed to fix it for myself: my issue was not related. 
We used read only credentials when running the terraform apply, but this was unsufficient as the kubernetes provider needed some more permissions to acquire a token.
