### ISSUE TITLE
error deleting eks cluster

### ISSUE THREAD

**Issue by DiemanXT1** [terraform-aws-modules/terraform-aws-eks#953]
# I have issues deleting EKS cluster. 

## I'm submitting a...

* [x] bug report

## What is the current behavior?

1. Comment out module in TF code;
2. Terraform plan
3. Error:

Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused

**Comment by dpiddockcmp** [comment]
Two options:
- Delete the `kubernetes_config_map.aws_auth` resource from your state file with `terraform state rm path.to.aws_auth`
- Restore the kubernetes provider definition and necessary data sources as in [Usage Example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.2.0/README.md#usage-example)

**Comment by DiemanXT1** [comment]
thank you for the quick response. For second option I do have the following:

data "aws_eks_cluster" "tf_kornchain_dev_cluster" {
  name = module.tf_kornchain_dev_cluster.cluster_id
}

data "aws_eks_cluster_auth" "tf_kornchain_dev_cluster" {
  name = module.tf_kornchain_dev_cluster.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.tf_kornchain_dev_cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.tf_kornchain_dev_cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.tf_kornchain_dev_cluster.token
  load_config_file       = false
  version                = "~> 1.11"
}

module "tf_kornchain_dev_cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "tf-kornchain-cluster"
  cluster_version = "1.17"
  subnets         = concat(aws_subnet.tf_kornchain_eks_private_subnet[*].id)
  vpc_id          = aws_vpc.tf_kornchain_eks_vpc.id
  cluster_enabled_log_types = ["api","audit","authenticator","controllerManager","scheduler"]
  cluster_endpoint_private_access = true
  cluster_endpoint_private_access_cidrs = [local.tf_kornchain_vpc_cidr_block["eks"]]
  
  node_groups_defaults = {
    disk_size = 32
  }

  node_groups = {
    example = {
      desired_capacity = 3
      max_capacity     = 10
      min_capacity     = 3
      key_name = module.eks_key_pair.this_key_pair_key_name
      instance_type = "t3a.small"
      k8s_labels = {
        Environment = "tf-kornchain-shared-dev"
        GithubRepo  = "terraform-aws-eks"
        GithubOrg   = "terraform-aws-modules"
      }
      additional_tags = {
        ExtraTag = "tf_kornchain_dev_cluster"
      }
    }
  }

  map_roles = [
    {
      rolearn  = aws_iam_role.tf_kornchain_ec2_role.arn
      username = aws_iam_role.tf_kornchain_ec2_role.id
      groups   = ["system:masters"]
    },
  ]

  # worker_groups = [
  #   {
  #     instance_type = "t3a.small"
  #     asg_max_size  = 5
  #     key_name = module.eks_key_pair.this_key_pair_key_name
  #   }
  # ]
}

Problem that I have is that if I comment module to delete it I get an error for the above mentioned data sources and provider. So question is - what is the right way of deleting EKS cluster?

**Comment by DiemanXT1** [comment]
I am going to close this one as I manually deleted all resources from Tf state. Question still remains - how to delete cluster created by this module though.
