### ISSUE TITLE
how to delete cluster created by this module?

### ISSUE THREAD

**Issue by DiemanXT1** [terraform-aws-modules/terraform-aws-eks#954]
# I have a question that i failed to find in any documentation for this module - how to delete cluster created by this module?

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

**Comment by dpiddockcmp** [comment]
`terraform destroy` will delete everything in a terraform state file.

You can set `create_eks = false` option on the module definition.

You can delete the module import. BUT you must have the two data sources and the kubernetes provider configured with details of the cluster. Obviously, you can't reference the outputs from the module you deleted, so will need to hardcode the cluster's name. This will only work while the eks_cluster still exists in AWS.

**Comment by barryib** [comment]
Closing. @DiemanXT1 feel free to reopen the issue, if the answer doesn't help you.
