### ISSUE TITLE
[Question] How to delete some of worker_groups ASG?

### ISSUE THREAD

**Issue by agung-kargo** [terraform-aws-modules/terraform-aws-eks#956]
Hi,

I have question: how to delete one of worker_groups ASG? SInce it is a list, not a map, to delete one of the worker group in the middle index will cause an error.

**Comment by barryib** [comment]
@agung-kargo please follow the discussion at https://github.com/terraform-aws-modules/terraform-aws-eks/issues/476.

Closing this, since it duplicates #476
