### ISSUE TITLE
Is there a way to modify the aws-k8s-cni yaml before creating the worker groups?

### ISSUE THREAD

**Issue by sc-rz** [terraform-aws-modules/terraform-aws-eks#96]
# I have issues
The AWS CNI by default pre-allocates the max number of IPs per node which results in unnecessary depletion of my IP pool. As of CNI 1.1, you can fix this by setting WARM_IP_TARGET in the [aws-k8s-cni.yaml](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.1/aws-k8s-cni.yaml) but this needs to be applied before the EC2 instances are created. 

Is there a way I can have Terraform apply a k8s config between creating the cluster and creating the worker groups? My current workaround is specifying 0 nodes in the Terraform module, applying my custom aws-k8s-cni.yaml, then changing the worker node count to my actual desired number.

Thanks!

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
The cluster is created using the release aws-k8s-cni.yaml which does not have WARM_IP_TARGET set.

## Environment details

* Affected module version: 1.3.0
* OS: MacOS
* Terraform version: v0.11.7

**Comment by max-rocket-internet** [comment]
Hi @sc-rz 
Can't you just apply your change and then delete all the `aws-node` pods?

`kubectl -n kube-system delete pods -l k8s-app=aws-node`

**Comment by max-rocket-internet** [comment]
No reply in 2 weeks and we also decided we weren't going to head in a direction of managing resources inside the k8s cluster as you can see the referenced issue. I hope you can understand our POV on this 🙂

**Comment by sc-rz** [comment]
@max-rocket-internet sorry lost track of this! Yes, I can understand that. Thanks!
