### ISSUE TITLE
Tagging Volumes 

### ISSUE THREAD

**Issue by soumitasardar** [terraform-aws-modules/terraform-aws-eks#960]
# I have issue regarding tagging Volumes which are created with eks autoscaling group using terraform.

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I am creating eks cluster with enabling autoscaling group with **launch configuration** **using terraform eks module**. I am using **tags** option in main.tf for tagging all resources created with eks. But i could see, volumes which are created are not tagged. How we can tag volumes as well? Please if anyone can help. 

## Environment details

* eks k8s version: 1.16
*   source = "terraform-aws-modules/eks/aws"
  version  = "8.1.0"
* Terraform version: 0.12.23

**Comment by zopz** [comment]
I believe that this needs to be implemented in your storage interface https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/180

At least, that's what our solution was, if there is a way to tag them through this module that would be great!

**Comment by dpiddockcmp** [comment]
ASG + Launch Configurations do not apply tags to volumes. [AWS autoscaling docs](https://docs.aws.amazon.com/autoscaling/ec2/userguide/autoscaling-tagging.html):
> Tags are not propagated to Amazon EBS volumes. To add tags to Amazon EBS volumes, specify the tags in a launch template 

Switch to using the `worker_groups_launch_template` key If you want tags to be applied to volumes at launch time. See the [`launch_templates` example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v12.2.0/examples/launch_templates/main.tf#L71)

**Comment by soumitasardar** [comment]
Thanks @zopz and @dpiddockcmp for response!!
But in our Production environment, we are using launch_configuration and it would be difficult to change worker group from launch configuration to launch_template.
Can you please suggest, if there are any road map or any other way, we can tag root volume with launch configuration only.

**Comment by kkapoor1987** [comment]
@soumitasardar I think we followed @dpiddockcmp  advice about the same thing and moved to Launch templates for taking advantage of tagging feaures for ebs volumes.

**Comment by zopz** [comment]
@soumitasardar my solution is actually for pvs created by k8s after provisioning, so that might not be what you are asking, but we are using `worker_groups` for our definitions, and they do inherit the `tags` at the root of the module, we're on 9.0.0 though, so not sure if that's new behavior

**Comment by soumitasardar** [comment]
Thanks!! Modified worker group with launch_template and it is working.

**Comment by barryib** [comment]
Thanks for your feedback. Closing this issue since it's now resolved.
