### ISSUE TITLE
Support for boothook user-data script

### ISSUE THREAD

**Issue by raonitimo** [terraform-aws-modules/terraform-aws-eks#961]
## I'm submitting a...

* [ X ] feature request

## What is the current behavior?

I can currently set a pre_userdata that will be used in this template to generate a user-data bash script:

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/templates/userdata.sh.tpl

But I need to set a [boothook script](https://cloudinit.readthedocs.io/en/latest/topics/format.html#cloud-boothook) to change settings before docker and kubelet are started for the first time, in addition to the bash script to bootstrap the instance.

Specifically, I'd like to format and mount an nvme volume, and use it for /var/lib/docker on a c5d instance to avoid [soft lockup errors](https://github.com/awslabs/amazon-eks-ami/issues/454) on high disk I/O workloads.

## What's the expected behavior?

Maybe a non-empty boothook variable would point to a [multipart mime](https://cloudinit.readthedocs.io/en/latest/topics/format.html#helper-script-to-generate-mime-messages) template file here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/data.tf#L64

## Are you able to fix this problem and submit a PR? Link here if you have already.

Please let me know if this would work and I'll make a PR.

## Environment details

* Affected module version:
* OS: AL2
* Terraform version:

**Comment by max-rocket-internet** [comment]
You can just replace the whole user-data and think then you have the freedom to do what you want, no?

https://github.com/terraform-aws-modules/terraform-aws-eks/issues/601
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/565

**Comment by raonitimo** [comment]
Yes, missed that. Thanks!
