### ISSUE TITLE
Terraform apply failing when we are changing eks module from 3.0.0 to 6.0.0 with terraform 12

### ISSUE THREAD

**Issue by rushikeshtayde04** [terraform-aws-modules/terraform-aws-eks#964]
# I have issues
Error updating Autoscaling group: ValidationError: You must use a valid fully-formed launch template. The requested configuration is currently not supported. Please check the documentation for supported configurations.
	status code: 400, request id: 4503322f-238f-412c-8c21-7378b87ff9c2
## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## Environment details
eks 1.15 
* Affected module version:
* OS:
* Terraform version:
0.12.9

**Comment by daroga0002** [comment]
please go thru module Release notes 
https://github.com/terraform-aws-modules/terraform-aws-eks/releases?after=v8.0.0

as in sure in v6 are documented breaking changes
