### ISSUE TITLE
How to create multiple instance types worker nodes in same autoscaling group

### ISSUE THREAD

**Issue by soumitasardar** [terraform-aws-modules/terraform-aws-eks#966]
# I have issues
I am trying to create multiple instance type worker nodes in same autoscaling group. But when i am write the code
node_worker_groups_template = [ 
{
  instance_type = "m5.large"
  asg_max_size = "4"
  asg_min_size = "1"
},
{
 instance_type = "m3.large"
  asg_max_size = "4"
  asg_min_size = "1"
}
]
This is creating 2 different autoscaling group .

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
As mentioned above, when i tried to create multiple instance types defined in launch template, but it was creating 2 different autoscaling group. Can there any possibility we can have different instance type worker nodes in same autoscaling group in eks in same availability zone.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
This is not bug. But looking to have some suggestion to resolve my issue.

## What's the expected behavior?
Worker nodes with different instance type mentioned in launch template will create in the same autoscaling group, instead of 2 different.

## Are you able to fix this problem and submit a PR? Link here if you have already.
no

## Environment details

eks k8s version: 1.16
source = "terraform-aws-modules/eks/aws"
version = "8.1.0"
Terraform version: 0.12.23

**Comment by max-rocket-internet** [comment]
> any possibility we can have different instance type worker nodes in same autoscaling group

I use this but only for spot instances. I'm not sure it applies when you're not using at least some spot instances?

I think you can start with something like this:

```
worker_groups_launch_template = [
    worker_groups_launch_template = [
      {
        name                    = "test-1"
        override_instance_types = ["r5.2xlarge", "r5a.2xlarge", "r5d.2xlarge"]
      }
    ]
  ]
```

Then you'll need to test adding attributes related to "mixed", you can find them here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group

Code in this module is here: https://github.com/terraform-aws-modules//terraform-aws-eks/blob/master/workers_launch_template.tf#L91-L127

**Comment by soumitasardar** [comment]
Thank you @max-rocket-internet !!!
let me try with your solution and i will respond back.

**Comment by soumitasardar** [comment]
Hi,
I tried with 2 different instance types 
override_instance_types = ["m5.large","m1.large"] in tfvar file and just run it.
but receiving error while terraform apply
 "Error: Error creating AutoScaling Group: ValidationError: The specified instance type m1.large is not supported by Network Load Balancers
	status code: 400,"
Do i need to specify dynamic mixed_instances_policy {} in main.tf.
Please guide me since i am new to this.

**Comment by max-rocket-internet** [comment]
I don't know for sure, like I said, I only used it with spot instances. I think you need to perhaps configured it manually on the ASG to see what you want and if it works, then work backwards to see how you can apply it with this module 🙂

**Comment by soumitasardar** [comment]
ok, i will do it from console and see the result....thanks
