### ISSUE TITLE
Docker in Docker on managed nodes

### ISSUE THREAD

**Issue by nflew** [terraform-aws-modules/terraform-aws-eks#968]
I read the FAQ about the issues around docker in docker. Is there no bootstraps_arg feature in the node groups config to allow the inner container to communicate outside?

**Comment by dpiddockcmp** [comment]
The node groups API provides very few options for customising the environment currently. It is not a limitation of the module but from AWS.

There are requests on the container team's roadmap for more flexibility. Like https://github.com/aws/containers-roadmap/issues/596 .

**Comment by barryib** [comment]
Custom userdata and launch template are now available for MNG. But so far, this module doesn't support. Please follow https://github.com/terraform-aws-modules/terraform-aws-eks/issues/979 to track this feature.

Closing.
