### ISSUE TITLE
Allow to specify the name of a keypair to associate with worker nodes

### ISSUE THREAD

**Issue by giuscri** [terraform-aws-modules/terraform-aws-eks#969]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## Description
Allow to specify the name of a keypair to associate with worker nodes. This way it's possible to ssh into nodes to debug problems with a kubelet for example.

**Comment by giuscri** [comment]
Check out `workers_group_defaults.key_name`

**Comment by kaykhancheckpoint** [comment]
@giuscri How did u manage to ssh into a worker node, what is the setup? Do i just need to set a key_name in my worker group block?
