### ISSUE TITLE
Support launch template & custom ami for managed node groups

### ISSUE THREAD

**Issue by davidkarlsen** [terraform-aws-modules/terraform-aws-eks#979]
## I'm submitting a...

* [ ] bug report
* [X] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

No configuration option for the new option of launch templates and custom amis.

## What's the expected behavior?

Add support for launch_templates:
https://aws.amazon.com/blogs/containers/introducing-launch-template-and-custom-ami-support-in-amazon-eks-managed-node-groups/
https://github.com/aws/containers-roadmap/issues/585

## Environment details

* Affected module version: current
* OS: N/A
* Terraform version: N/A

**Comment by ghicks-rmn** [comment]
Support in the Terraform AWS Provider is expected in the next release (3.3.0) - https://github.com/terraform-providers/terraform-provider-aws/issues/14702

**Comment by jwesolowski-rms** [comment]
Version [3.3.0](https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v3.3.0) has been released with support for [launch templates](https://github.com/terraform-providers/terraform-provider-aws/pull/14639).

**Comment by amazingandyyy** [comment]
is this module using the terraform-providers/terraform-provider-aws?

**Comment by calvinbui** [comment]
> is this module using the https://github.com/terraform-providers/terraform-provider-aws?

not yet: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/versions.tf

**Comment by stevehipwell** [comment]
I'm eagerly watching PR https://github.com/terraform-aws-modules/terraform-aws-eks/pull/997, are there any other blockers to be aware of before this gets released?

**Comment by galindro** [comment]
@stevehipwell : it should be ready at next Wednesday: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/997#issuecomment-702451725
