### ISSUE TITLE
How can I access the auto scaling groups created via worker_groups_launch_template?

### ISSUE THREAD

**Issue by Sillium** [terraform-aws-modules/terraform-aws-eks#983]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I successfully create an EKS cluster with this module. Auto scaling group(s) for the workers is created with
```
module "eks" {
  source            = "terraform-aws-modules/eks/aws"
  …
  worker_groups_launch_template = [
    {
      name                    = "worker-group-spot-1"
      …
   }
  ]
}
```

I would like to add an aws_autoscaling_schedule to the ASG created by this module. How can I access the asg in
```
resource "aws_autoscaling_schedule" "scale_down" {
  …
  autoscaling_group_name = ?
}
```
if possible at all?

Thanks for this module btw!

**Comment by dpiddockcmp** [comment]
There is an output on the module `workers_asg_names`. This is a list containing the names of all the autoscaling groups created, both from `worker_groups` and `worker_groups_launch_template`.

There is also `workers_asg_arns` if you need the ARNs.

**Comment by Sillium** [comment]
Thank you very much, Daniel!
