### ISSUE TITLE
ailed to download module Could not download module "eks" (eks/main.tf:119) source code from "https://github.com/terraform-aws-modules/terraform-aws-eks/archive/v12.2.0.tar.gz//*?archive=tar.gz": Get

### ISSUE THREAD

**Issue by devi-sandireddy** [terraform-aws-modules/terraform-aws-eks#985]
# I have issue with downloading from github when I run terraform init within an ec2 instance in AWS. [ I had all the security rules and NACL checked, I was able to ping github]..

It works sometimes and fails sometimes...with the error below.  

Terraform version is 0.12.28
with dowloading the eks/module.  --

Terraform snippet:
Create EKS cluster with default worker group using autoscaling
module "eks" {
  source                           = "terraform-aws-modules/eks/aws"
  version                          = "12.2.0"
  cluster_name                     = "${var.app}-${var.env}"

Running terraform init within ec2 instance as the gitlab-runner is running within ec2 instance.  Security rules are provisioned to all calls to github or any internet space.

$ TF_LOG=trace terraform init
2020/08/22 11:26:31 [INFO] Terraform version: 0.12.28  
2020/08/22 11:26:31 [INFO] Go runtime version: go1.12.13
2020/08/22 11:26:31 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2020/08/22 11:26:31 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2020/08/22 11:26:31 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/08/22 11:26:31 [INFO] CLI command args: []string{"init"}
Initializing modules...
2020/08/22 11:26:31 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
2020/08/22 11:26:31 [DEBUG] Module installer: begin eks
2020/08/22 11:26:31 [TRACE] ModuleInstaller: Module installer: eks <nil> already installed in eks
2020/08/22 11:26:31 [DEBUG] Module installer: begin eks.eks
2020/08/22 11:26:31 [TRACE] ModuleInstaller: eks.eks version 12.2.0 no longer compatible with constraints 12.1.0
2020/08/22 11:26:31 [TRACE] ModuleInstaller: discarding previous record of eks.eks prior to reinstall
2020/08/22 11:26:31 [TRACE] ModuleInstaller: also discarding downstream eks.eks.node_groups
2020/08/22 11:26:31 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/eks.eks prior to install of eks.eks
2020/08/22 11:26:31 [TRACE] ModuleInstaller: eks.eks is a registry module at terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] eks.eks listing available versions of terraform-aws-modules/eks/aws at registry.terraform.io
2020/08/22 11:26:31 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/08/22 11:26:31 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
2020/08/22 11:26:31 [DEBUG] fetching module versions from "https://registry.terraform.io/v1/modules/terraform-aws-modules/eks/aws/versions"
2020/08/22 11:26:31 [DEBUG] GET https://registry.terraform.io/v1/modules/terraform-aws-modules/eks/aws/versions
2020/08/22 11:26:31 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/modules/terraform-aws-modules/eks/aws/versions
2020/08/22 11:26:31 [DEBUG] found available version "12.2.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "12.1.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "5.1.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "7.0.1" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "12.0.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "8.2.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "11.1.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "6.0.2" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "4.0.2" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "11.0.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "8.1.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "10.0.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "5.0.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "9.0.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "8.0.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "6.0.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "7.0.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "3.0.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "2.3.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "2.2.1" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "1.6.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "2.3.1" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "2.2.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "6.0.1" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "1.7.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "2.1.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "4.0.1" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "4.0.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "2.0.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "1.8.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "1.2.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "1.0.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "1.3.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "0.1.1" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "0.2.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "1.5.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "1.4.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "0.1.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] found available version "1.1.0" for terraform-aws-modules/eks/aws
2020/08/22 11:26:31 [DEBUG] looking up module location from "https://registry.terraform.io/v1/modules/terraform-aws-modules/eks/aws/12.1.0/download"
2020/08/22 11:26:31 [DEBUG] GET https://registry.terraform.io/v1/modules/terraform-aws-modules/eks/aws/12.1.0/download
2020/08/22 11:26:31 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/modules/terraform-aws-modules/eks/aws/12.1.0/download
Downloading terraform-aws-modules/eks/aws 12.1.0 for eks.eks...
2020/08/22 11:26:32 [TRACE] ModuleInstaller: eks.eks terraform-aws-modules/eks/aws 12.1.0 is available at "https://github.com/terraform-aws-modules/terraform-aws-eks/archive/v12.1.0.tar.gz//*?archive=tar.gz"
2020/08/22 11:26:32 [DEBUG] will download "https://github.com/terraform-aws-modules/terraform-aws-eks/archive/v12.1.0.tar.gz?archive=tar.gz" to .terraform/modules/eks.eks
2020/08/22 11:26:32 [TRACE] fetching "https://github.com/terraform-aws-modules/terraform-aws-eks/archive/v12.1.0.tar.gz?archive=tar.gz" to ".terraform/modules/eks.eks"
2020/08/22 11:26:32 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json
Warning: Interpolation-only expressions are deprecated
  on main.tf line 16, in provider "aws":
  16:   assume_role {role_arn = "${local.workspace_iam_roles[terraform.workspace]}"}
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
Error: Failed to download module
Could not download module "eks" (eks/main.tf:119) source code from
"https://github.com/terraform-aws-modules/terraform-aws-eks/archive/v12.1.0.tar.gz//*?archive=tar.gz":
Get
https://codeload.github.com/terraform-aws-modules/terraform-aws-eks/tar.gz/v12.1.0:
read tcp 172.17.0.2:34228->140.82.113.9:443: read: connection reset by peer.
Error: Failed to download module
Could not download module "eks" (eks/main.tf:119) source code from
"https://github.com/terraform-aws-modules/terraform-aws-eks/archive/v12.1.0.tar.gz//*?archive=tar.gz":
Get
https://codeload.github.com/terraform-aws-modules/terraform-aws-eks/tar.gz/v12.1.0:
read tcp 172.17.0.2:34228->140.82.113.9:443: read: connection reset by peer.

**Comment by daroga0002** [comment]
it seems be rather issue with your workstation as your connection is reset. 

Please try to use those links and just check does you are able download those files (as looks some proxy/firewall error)

**Comment by devi-sandireddy** [comment]
Thanks it was the firewall rules issue within the domain I was running this in.
