### ISSUE TITLE
Cycle when removing first item of worker_groups_launch_template list

### ISSUE THREAD

**Issue by codingthecloud** [terraform-aws-modules/terraform-aws-eks#993]
# I have issues

Hi, I am having an issue whenever I try to delete the first item of the **worker_groups_launch_template** list. Could anybody tell me why it is behaving like this?

I get the below error:
`Error: Cycle: module.eks.aws_launch_template.workers_launch_template[1] (destroy), module.eks.random_pet.workers_launch_template[1] (destroy), module.eks.aws_launch_template.workers_launch_template[0] (destroy deposed 630f0acb), module.eks.aws_iam_instance_profile.workers_launch_template[1] (destroy), module.eks.aws_launch_template.workers_launch_template[0], module.eks.random_pet.workers_launch_template[0], module.eks.aws_autoscaling_group.workers_launch_template[0], module.eks.aws_autoscaling_group.workers_launch_template[0] (destroy deposed 93527070), module.eks.random_pet.workers_launch_template[0] (destroy deposed ad930592)
`
## I'm submitting a...

* [X ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Given:
  ```
worker_groups_launch_template =  [
       { --> I tried removing this element
           additional_security_group_ids = [
               "sg-id1"
            ]
           asg_desired_capacity          = 1
           asg_max_size                  = 5
           instance_type                 = "t2.medium"
           name                          = "application"

           subnets                       = [
               "subnet-id1","subnet-id2",
            ]
        },
       {
           additional_security_group_ids = [
               "sg-id2",
            ]
           asg_desired_capacity          = 1
           asg_max_size                  = 5
           instance_type                 = "t2.small"
           name                          = "monitoring"

           subnets                       = [
               "subnet-id1","subnet-id2",
            ]
        },
    ]
```
If I delete the first item from the list. I get the Cycle error.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Create a list of worker_groups_launch_template and delete the first item in the array.

## What's the expected behavior?

Recreate the node groups correctly.

## Environment details

* Affected module version: eks
* OS: Amazon Linux 2 Ami
* Terraform version: 0.13.1

**Comment by daganida88** [comment]
Having the same issue.

**Comment by barryib** [comment]
@daganida88 @codingthecloud Can you please have a look at https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1043 and tell me if it solves your issue.

BTW, keep in mind that changing the order of workers group is a destructive operation. All workers group are destroyed and recreated. If you want to do this safely, you should move then in state with `terraform state mv`.

This will be fixed when we use map instead of list for workers groups. There is an ongoing PR https://github.com/terraform-aws-modules/terraform-aws-eks/pull/858 for that.
