### ISSUE TITLE
Managed node group launch template support

### ISSUE THREAD

**Issue by nrctmo** [terraform-aws-modules/terraform-aws-eks#995]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## Environment details

* Affected module version:
* OS:
* Terraform version:

## Any other relevant info
[AWS released a new feature mid-August: Managed node group now support launch templates](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-managed-node-groups-now-support-ec2-launch-templates-custom-amis). Supporting this would lead to (besides other things) naming instance nodes so they are distinguishable in AWS console and setting um multiple users accounts with their own ssh key on the nodes to not have a central user.

**Comment by dpiddockcmp** [comment]
Duplicate of #979

**Comment by nrctmo** [comment]
Thanks for the fast response. Sorry for missing the duplicate.
