### ISSUE TITLE
Error: "Provider produced inconsistent final plan" when updating vpc tags, and eks cluster name

### ISSUE THREAD

**Issue by tapanhalani** [terraform-aws-modules/terraform-aws-eks#996]
# I have issues
with terraform failing when trying to update the cluster name, and remove some unnecessary tags from vpc subnets.

## I'm submitting a ...

* [x] bug report

## 
I followed documentation here: https://learn.hashicorp.com/tutorials/terraform/eks, to create first a vpc, and then EKS cluster, which completed successfully. Then to change the name of the cluster, and remove some unnecessary tags from vpc subnets, I re-ran apply after plan, but got this error for all the 4 worker security group rules:

```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.eks.aws_security_group_rule.workers_ingress_cluster_https[0] to include
new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" changed the planned action from
CreateThenDelete to DeleteThenCreate.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
Apart from these, all other resources including cluster, vpc, security-groups are created perfectly.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
(1.) Change the value of `cluster_name` in module.eks
(2.) Add/edit/remove a tag in module.vpc.public_subnet_tags and module.vpc.private_subnet_tags

## What's the expected behavior?
No error should occur. The effect should be as described in the plan i.e. replacement of security_group_id and source_security_group_id

## Are you able to fix this problem and submit a PR? Link here if you have already.
No.

## Environment details

* Affected module version: 12.2.0
* OS: Ubuntu 20.04
* Terraform version: 0.13.0

**Comment by daroga0002** [comment]
module is not ready for terraform 0.13, please use terraform 0.12 or observe a repository incoming releases

**Comment by dpiddockcmp** [comment]
The module is hitting some bug or incompatibility in Terraform 0.13. 

Changing `cluster_name` will cause everything to be recreated. Generally this is not a recommended or supported action. Delete the old cluster and then create a new cluster with the new name.

**Comment by tapanhalani** [comment]
@daroga0002   Sorry if the following question is lame, but does `required_version = ">= 0.12.9"` in the module's versions.tf allows 0.13.0 also, or does it allows only till the latest patch of 0.12 ? I am asking because I didn't get any incompatibility warning or error when running terraform init. Thank you.

@dpiddockcmp The expected output was to re-create the cluster only, with different name (there were no resources/apps running on that cluster anyway). This would recreate all k8s related resources like cluster, node-groups etc. I will move on with deleting the cluster first, and then recreate it. Thank you.

**Comment by daroga0002** [comment]
@tapanhalani 

yes you are right, I deployed module using terrafrom 0.13.1 and seems be deployable, so main issue was caused because you tried to change `cluster_name`

**Comment by dpiddockcmp** [comment]
The module can be used with TF 0.13 however I would currently recommend against it. There have been some internal changes that have broken compatibility with this module.

**Comment by tapanhalani** [comment]
@daroga0002  @dpiddockcmp  Thank you for your responses. I installed terraform version 0.12.9, and re-created the cluster after destroying, which works. Should I close this issue now?
