### ISSUE TITLE
wait_for_cluster fails, times out, then creates an inconsistent plan

### ISSUE THREAD

**Issue by random930** [terraform-aws-modules/terraform-aws-eks#998]
# I have issues
I'm using the EKS module but hit a TIMEOUT, and then an inconsistent state.

## I'm submitting a...

* [ X ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Not hitting the TIMEOUT, and not hitting an inconsistent state.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

The TF code:
```

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  name = "test"

  cidr = "10.0.0.0/16"

  azs             = ["eu-west-1a", "eu-west-1b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]

  enable_nat_gateway = true
  enable_vpn_gateway = true
}

data "aws_eks_cluster" "cluster" {
  name = module.my-cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.my-cluster.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "~> 1.9"
}

/**
If you're running into
InvalidClientTokenId: The security token included in the request is invalid

it means you need MFA on your user to be configured.

Go to the AWS Console and turn on MFA for the user you're trying to run this Terraform file through.
Then, make sure to use the MFA number when running the Terraform command.
*/

module "my-cluster" {
  source  = "terraform-aws-modules/eks/aws"
  cluster_name    = "my-cluster"
  cluster_version = "1.16"
  vpc_id = module.vpc.vpc_id
  subnets = module.vpc.private_subnets

  worker_groups = [
    {
      instance_type = "m4.large"
      asg_max_size  = 5
    }
  ]
}
```

When "applying", it got to the "wait_for_cluster" point:

```
Error: Error running command 'for i in `seq 1 60`; do wget --no-check-certificate -O - -q $ENDPOINT/healthz >/dev/null && exit 0 || true; sleep 5; done; echo TIMEOUT && exit 1': exit status 1. Output: /bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
/bin/sh: wget: command not found
TIMEOUT
```

And now, when I try applying, I get:
```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.my-cluster.null_resource.wait_for_cluster[0] to include new values
learned so far during apply, provider "registry.terraform.io/hashicorp/null"
changed the planned action from CreateThenDelete to DeleteThenCreate.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

(my guess is that the bug is in this module, not the null one)

## What's the expected behavior?

Apply completes successfully.

## Environment details

```
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/aws v3.4.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.12.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
```

* OS: MacOS Catalina

**Comment by daroga0002** [comment]
you are missing a wget over your execution environment, you can install wget or switch to curl or etc. via variables:
`wait_for_cluster_cmd` and `wait_for_cluster_interpreter`


You can also review a thread about similar concerns:
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/829

**Comment by barryib** [comment]
Closing. Look like you don't have `wget` installed. Please see https://github.com/terraform-aws-modules/terraform-aws-eks/issues/998#issuecomment-685462628.

Feel free to re-open this issue if needed.

**Comment by random930** [comment]
@daroga0002 @barryib I think the use of "wget" should be documented somewhere. Also, it's pretty easy to make this a bit more idiot proof (like me): check that wget is actually installed in the execution environment at the beginning of this all.

**Comment by barryib** [comment]
@random930 I just opened the following PR to address your point https://github.com/terraform-aws-modules/terraform-aws-eks/pull/999

**Comment by barryib** [comment]
> @daroga0002 @barryib I think the use of "wget" should be documented somewhere. Also, it's pretty easy to make this a bit more idiot proof (like me): check that wget is actually installed in the execution environment at the beginning of this all.

I don't know how to easily do that in Terraform. But I'll be happy to review any PR to address that.

**Comment by random930** [comment]
It's a bit of a hack, but notice how I've added the null resource to my code, and the depends_on at the bottom. What we need to do here is have this resource at the beginning of the module itself and have one of the basic resources depend on it.

```
resource "null_resource" "verify_wget" {
  provisioner "local-exec" {
    command = "wget https://www.google.com"
    interpreter = ["/bin/sh"]
  }
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  ...
}

data "aws_eks_cluster" "cluster" {
  ...
}

data "aws_eks_cluster_auth" "cluster" {
  ...
}

provider "kubernetes" {
  ...
}

module "my-cluster" {
  source  = "terraform-aws-modules/eks/aws"
  ...

  depends_on = [null_resource.verify_wget]
}
```

If you don't have wget, you'll see this error during apply and it will stop the rest of the apply:
```
Error: Error running command 'wget https://www.google.com': exit status 127. Output: /bin/sh: wget https://www.google.com: No such file or directory
```

**Comment by barryib** [comment]
Your test is only valid for TF 0.13. There is no  depends_on for module in TF 0.12.

Maybe we can do that in the future but not now because most of users are still using TF 0.12.

**Comment by random930** [comment]
Ah that was just an example. You could look at it in the module's code itself:

There's var.wait_for_cluster_cmd which uses wget (as a default). That var is used in cluster.tf under null_resource.wait_for_cluster. That resource can depend on the check I've added, like so:

```
resource "null_resource" "verify_wget" {
  provisioner "local-exec" {
    command = "wget https://www.google.com"
    interpreter = ["/bin/sh"]
  }
}

resource "null_resource" "wait_for_cluster" {
  count = var.create_eks && var.manage_aws_auth ? 1 : 0

  depends_on = [
    aws_eks_cluster.this[0],
    aws_security_group_rule.cluster_private_access,
    null_resource.verify_wget,
  ]

  provisioner "local-exec" {
    command     = var.wait_for_cluster_cmd
    interpreter = var.wait_for_cluster_interpreter
    environment = {
      ENDPOINT = aws_eks_cluster.this[0].endpoint
    }
  }
}
```

Of course, there's no point in doing the wget verification if someone set var.wait_for_cluster_cmd not to use it. So you could replace the "wget https://www.google.com" test with something like this:

```
resource "null_resource" "verify_wget" {
  provisioner "local-exec" {
    command = regex(".*wget.*", var.wait_for_cluster_cmd) ? "wget https://www.google.com" : ""
    interpreter = ["/bin/sh"]
  }
}
```

**Comment by daroga0002** [comment]
above will cause a lot of changes in code because to make it working fine such manual dependency should be injected into most of resources.

From my point of view this is path to no where as bring just some problems.

I think that the only way to solve this is just clear out `default` field in variable `wait_for_cluster_cmd`  and require a input from users  (same what was done during `cluster_version` PR) but this will make hard to use module as people will be not sure what exactly paste there

**Comment by random930** [comment]
That's legitimate. At least if anyone runs into issues, Google will find
this page :)

**Comment by daroga0002** [comment]
I think I found a solution which will solve such kind of issues, addressing in PR:

https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1002
